- vlib/gg/gg.v
This PR updates the mouse click callback to pass the button that was clicked
> gg: add quit fn

- vlib/gg/gg.v
Change "vid" to "ved" in a comment inside the gg module.
> gg: change vid to ved in a comment

- vlib/time/time.v
- vlib/time/time_nix.c.v
- vlib/v/checker/checker.v
Remove an unnecessary exception from the checker
> checker: cleanup type alias pascal case check

- vlib/gg/enums.v
- vlib/gg/gg.v
The PR updates the mouse click callback to include the button that was clicked.
> gg: update mouse click cb to pass button

- cmd/tools/vtest-cleancode.v
- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/import_selective_keep.vv
~~To be rebased after #10234~~ done
> fmt: fix removal of selective imported map key type

- cmd/tools/vast/vast.v
- cmd/v/help/ast.txt
tools: vast add comment and clean code
> tools: vast add comment and clean code

- doc/docs.md
- vlib/v/tests/array_slice_test.v
This PR documents how slices work (since #10219) and adds further test cases to avoid regressions.
I've somewhat re-arranged and extended the documentation for arrays in general to make it a little bit more consecutive.
> docs: describe array/slice behaviour

- vlib/v/checker/checker.v
- vlib/v/checker/tests/direct_map_alias_init_err.out
- vlib/v/checker/tests/direct_map_alias_init_err.vv
> checker: error on direct map alias init

- cmd/tools/vast/test/demo.v
- cmd/tools/vast/vast.v
1. update DeferStmt for latest V.
2. add test for DeferStmt.
> tools:vast update DeferStmt

- cmd/tools/vast/vast.v
It is useful to debugging V's test file
> vast: accept .vv file

- vlib/net/urllib/urllib.v
- vlib/net/urllib/urllib_test.v
> fix: Don't crash on str() if url missing host.

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/cast_expected.vv
- vlib/v/fmt/tests/import_selective_expected.vv
- vlib/v/fmt/tests/import_selective_input.vv
> fmt: fix removal of `Abc` in `import mod { Abc }`, where Abc is used in a `x as Abc` expression

- vlib/v/checker/checker.v
This PR makes minor cleanup of struct_init().
- Simplify parameter variable names.
- Change `utyp` to `unwrapped_struct_type`.
> checker: minor cleanup of struct_init()

- vlib/v/checker/checker.v
This PR makes minor cleanup of assign_stmt().
- Simplify parameter variable names using idiomatic patterns.
- Parameter name `assign_stmt` change to `node`.
> checker: minor cleanup of assign_stmt()

- vlib/v/checker/checker.v
This PR makes minor cleanup of selector_expr().
- Simplify parameter variable names using idiomatic patterns.
- Parameter name `selector_expr` change to `node`.
> checker: minor cleanup of selector_expr()

- vlib/v/checker/checker.v
This PR makes minor cleanup of return_stmt().
- Simplify parameter variable names using idiomatic patterns.
- Parameter name `return_stmt` change to `node`.
> checker: minor cleanup of return_stmt()

- vlib/v/checker/checker.v
- vlib/v/checker/tests/optional_in_println_mismatch.out
- vlib/v/checker/tests/optional_in_println_mismatch.vv
- vlib/v/parser/parser.v
- vlib/v/tests/generics_return_generics_struct_test.v
> checker: check or block inside println calls

- vlib/v/gen/c/assert.v
- vlib/v/gen/c/str.v
> assert: print enum value of CTempVars on fail

- doc/vscode.md
> docs: Update vscode.md : extention -> extension

- cmd/tools/vast/test/demo.v
- cmd/tools/vast/vast.v
> tools: vast fix and clean code

- vlib/orm/README.md
> docs: fix tablename -> table

- doc/docs.md
* explain how to create arrays with mixed content
* explain the shortform to write static arrays
> docs: Array / add mixed struts arrays 

- doc/docs.md
> High order functions -> Higher-order functions

- examples/tetris/README.md
adds list of dependencies required to compile tetris example (Ubuntu reference) 
Thanks for all the work on this, looks like a great language.
> tetris example - add dependencies list

- vlib/v/checker/checker.v
This PR implement smartcast if multi conds (part 1/2).
It's a breaking PR, need two parts merge, so firstly commit part 1.
- Add recursive `smartcast_if_conds()`.
- This is part 1 and fix #10380 at part 2.
```vlang
struct SourcePosition {
source_line   u32
source_column u32
}
type SourcePositionType = Empty | SourcePosition
type NameIndexType = Empty | u32
struct GenPosition {
gen_line   u32
gen_column u32
}
struct Mapping {
GenPosition
sources_ind     u32
names_ind       NameIndexType
source_position SourcePositionType
}
fn ok(mapping_a Mapping, mapping_b Mapping) bool {
if mapping_a.source_position is SourcePosition && mapping_b.source_position is SourcePosition {
return mapping_a.source_position.source_line != mapping_b.source_position.source_line
|| …
```
> checker: implement smartcast if multi conds (part 1/2)

- vlib/sync/channels.v
- vlib/sync/pool/pool.v
- vlib/sync/waitgroup.v
- vlib/v/gen/c/cgen.v
- vlib/v/markused/markused.v
A further follow-up to #9716...
> GC-Boehm: extend optimized mode to channel buffers

- .gitignore
```
» touch a b c d e
» git status
On branch gitignore-garbage-files
Your branch is up to date with 'origin/gitignore-garbage-files'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
a
b
c
d
e
nothing added to commit but untracked files present (use "git add" to track)
» git clean -f
Removing a
Removing b
Removing c
Removing d
Removing e
```
> .gitignore: do not ignore top level binaries to make garbage file cleanup easier

- doc/docs.md
* create a section specific to constant definition in modules
* explain the allowed syntax
> doc: Section constants / modules / declare public constants

- vlib/os/notify/backend_linux.c.v
Also adds comments to document the code.
> os/notify: Make epoll wrapper thread safe

- vlib/net/common.v
Fix the rare occasions when signalling breaks `select` socket calls. For example the Boehm GC uses linux signals inernally when garbage collecting causing the socket operation failing with socket error 4. There are no clean fix to this. My research showed that the suggested work-around was to retry when this happens. For reference see: <https://github.com/ivmai/bdwgc/blob/master/doc/README.linux#L16>
I need some other pair of eyes on this.
> net: Retry logic on select when fail on signal

- cmd/tools/vcreate.v
- cmd/tools/vcreate_test.v
- vcreate: Add test for `v init`.
- vcreate: Init git properly with no dir arg.
- vcreate: Terminate files with newline.
Fixes #10478
> vcreate: Terminate with newlines and fix gitignore creation.

- vlib/v/checker/checker.v
- vlib/v/checker/tests/sum.out
- vlib/v/checker/tests/sum.vv
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/js/js.v
- vlib/v/gen/js/sourcemap/mappings.v
- vlib/v/parser/sql.v
This PR implement if smartcast multi conds (part 2).
- Modify all the related called.
- Restore AsCast check error.
- Restore sum.vv/sum.out.
> checker: implement if smartcast multi conds (part 2)

- vlib/v/gen/c/cgen.v
- vlib/v/parser/parser.v
- vlib/v/tests/assembly/asm_test.amd64.v
This PR fixes the issues explained by @mintsuki here: https://discord.com/channels/592103645835821068/645024404081999885/853424759479861269 (at least I hope it does)
> cgen, parser: fix several assembly bugs

- vlib/gg/gg.v
Applies `ctx.scale` to `draw_circle_line`
> gg: apply ctx.scale to circle pos

- cmd/tools/vast/vast.v
> vast: eprintln and exit instead of panic

- doc/docs.md
- examples/function_types.v
Added documentation for functions types.
Includes as working example as "proof".
Also took the liberty of [correcting the title](https://github.com/vlang/v/commit/61f99bd41bab64f1d467399ee357202bb5fbc7d3) of the relevant chapter.
If you don't want the example or the title change for any reason, those changes are in separate commits.
> doc: function types

- vlib/v/gen/c/auto_str_methods.v
This PR simplify auto_str_methods.v.
- Simplify `gen_str_for_interface()` and `gen_str_for_union_sum_type()`.
- Avoid getting various types of STR functions first.
- This will make it more clearer.
> cgen: simplify auto_str_methods

- vlib/v/ast/table.v
This PR makes a minor cleanup of resolve_generic_to_concrete().
- Use `match mut sym.info` instead of `if ... else if ...`.
> table: cleanup resolve_generic_to_concrete()

- tutorials/building_a_simple_web_blog_with_vweb/README.md
> Docs: Always add filename in example files

- test.v
- vlib/v/parser/fn.v
- vlib/v/tests/fn_return_fn_test.v
> parser: allow anonymous function to return a function

- vlib/v/ast/ast.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/match_expr_empty_branch.out
- vlib/v/checker/tests/match_expr_empty_branch.vv
- vlib/v/checker/tests/match_expr_non_void_stmt_last.out
- vlib/v/checker/tests/match_expr_non_void_stmt_last.vv
- vlib/v/parser/if_match.v
> checker: check for empty branches in match expr

- vlib/os/os_nix.c.v
Updated version of: #10203
This PR implements os.debugger_present() for Linux 
The following I can not fix or provide
> os: add debugger_present() for linux

- vlib/v/gen/c/auto_str_methods.v
- vlib/v/tests/alias_fixed_array_test.v
This PR makes some simplifications of auto_str_methods.v.
> cgen: simplify auto_str_methods.v

- vlib/v/gen/c/cheaders.v
This PR makes minor cleanup in cheaders.v.
> cgen: minor cleanup in cheaders.v

- vlib/builtin/string.v
- vlib/builtin/string_test.v
- vlib/v/gen/c/cgen.v
> builtin: implement string.runes()

- vlib/v/gen/c/array.v
Use `Gen.unwrap` to unwrap generics and aliases in `Gen.array_init`
As suggested by @spytheman, `unwrap_generic` and `unwrap` can probably be moved to be methods of `ast.Table`, but this is out of the scope of the PR. I don't know if this change should be done before or after refactoring gen.c to use `unwrap` ?
> gen: refactor `Gen.array_init` to use `unwrap`

- vlib/os/os_nix.c.v
- vlib/os/os_test.v
- vlib/os/os_windows.c.v
This PR adds the os.utime() function. The include <utime.h> should be added. (see #9794)
- add os.utime() change access and modification time of a file
- test for os.utime()
> os: add function os.utime()

- vlib/v/checker/checker.v
> checker: allow names starting with underscore for translated code

- vlib/gx/color.v
add all predefined constant colors to name map so `gx.fn color_from_string(s string)` Color could resolve them
> vlib: complete string to color map

- examples/hanoi.v
> minor update example hanoi.v

- vlib/v/gen/c/cheaders.v
> build: SerenityOS also needs and have sys/wait.h

- cmd/v/help/build.txt
> native: drop x64 backend reference

- vlib/os/glob_test.v
- vlib/os/os.v
- vlib/os/os_nix.c.v
- vlib/os/os_windows.c.v
> vlib: reimplement glob in V for UNIX to not depend on libc

- vlib/v/pref/os.v
> comptime: uncomment the $serenity line after vc gets regenerated

- cmd/tools/vsymlink.v
Fix so that path can contain spaces and symlink command does not break.
Also show sudo message if execute command fails.
> tools: fix symlink path problems and sudo message

- cmd/tools/vsymlink.v
- vlib/os/os_test.v
> tools: use os.symlink instead of system('ln') in `v symstall`

- cmd/tools/vdoc/html.v
the previous pr seemed to have issues with closing tags. this pr fixes those issues, (which i did not see in local testing somehow).
> doc: fix html doc closing tags

- cmd/tools/vdoc/html.v
- cmd/tools/vdoc/resources/doc.css
- vlib/v/doc/doc.v
> Nicer attributes vdoc

- vlib/v/gen/js/js.v
This PR solves some problems of JS reference support and V will not emit complex JS code to perform a call.
> js: Better reference support

- vlib/regex/regex.v
- vlib/regex/regex_test.v
- vlib/regex/regex_util.v
- Fixed bug on find_all
- Added new test for this cases
bug reference #10799
> Regex: bug fix #10799

- vlib/v/checker/check_types.v
- vlib/v/checker/tests/hex_literal_overflow.out
- vlib/v/checker/tests/hex_literal_overflow.vv
this test is more accurate for checking hex literal overflow.
> checker: fix hex literal overflow check

- vlib/v/parser/fn.v
This PR makes a minor optimization in call_expr().
> parser: minor optimization in call_expr()

- vlib/v/gen/c/cgen.v
- vlib/v/tests/generic_interface_test.v
> cgen: fix generating invalid Option decls for generic interfaces

- vlib/v/gen/c/auto_str_methods.v
- vlib/v/tests/thread_to_string_test.v
this pr allows converting a thread to a string. closes #10810.
> gen: implement `thread.str()`

- doc/docs.md
This is a small follow-up to #10830:
- typos fixed
- singular vs. plural corrected
- some code examples rearranged so that the part discussed is nearer to the text in the browser window
- some comments added
> docs: small fixes for stack/heap section

- vlib/v/parser/parser.v
- vlib/v/parser/tests/empty_name_expr_err.out
- vlib/v/parser/tests/empty_name_expr_err.vv
Fixes https://github.com/vlang/v/issues/10709
> parser: fix error on empty name expr

- vlib/v/gen/c/cgen.v
- vlib/v/tests/interface_nested_field_test.v
Fix interfaces having a field that is another interface (not in builtin)
> Fix embedded interface

- vlib/v/ast/table.v
- vlib/v/checker/checker.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/struct_embed_test.v
Closes https://github.com/vlang/v/issues/9931
> checker, gen: implement basic struct embed direct field init support

- vlib/v/checker/checker.v
- vlib/v/checker/tests/match_alias_type_err.out
- vlib/v/checker/tests/match_alias_type_err.vv
- vlib/v/checker/tests/match_expr_and_expected_type_error.out
- vlib/v/checker/tests/match_undefined_cond.out
Fixes https://github.com/vlang/v/issues/10855
> checker: check match with type alias

- vlib/v/fmt/asm.v
- vlib/v/fmt/fmt.v
Only moved code around, no logical changes.
> fmt: move asm related code into it's own file

- vlib/v/gen/c/comptime.v
Fixes https://github.com/vlang/v/issues/10435
> gen: fix haiku platform

- vlib/builtin/builtin.c.v
- vlib/v/gen/c/assert.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/index.v
- vlib/v/gen/c/json.v
- vlib/v/tests/reserved_keywords_can_be_escaped_with_at_test.v
Fixes https://github.com/vlang/v/issues/9928
> gen: fix keyword escape

- vlib/v/checker/check_types.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/disallow_pointer_arithmetic_err.out
- vlib/v/checker/tests/disallow_pointer_arithmetic_err.vv
- vlib/v/checker/tests/mismatched_ptr_op_ptr.out
- vlib/v/checker/tests/unsafe_pointer_arithmetic_should_be_checked.out
- vlib/v/tests/pointer_arithmetic_test.v
Fixes https://github.com/vlang/v/issues/169
> checker: disallow pointer arithmetic

- vlib/v/gen/c/cgen.v
- vlib/v/tests/c_struct_free/c_struct_free_property_test.v
- vlib/v/tests/c_struct_free/free_struct.c
Fixes https://github.com/vlang/v/issues/5170
> cgen: don't change field name of c structs

- vlib/v/checker/checker.v
- vlib/v/checker/tests/break_anon_fn_err.out
- vlib/v/checker/tests/break_anon_fn_err.vv
Fixes https://github.com/vlang/v/issues/10712
> checker: fix break inside anon fn

- vlib/v/ast/table.v
- vlib/v/checker/checker.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/struct_embed_test.v
Fixes https://github.com/vlang/v/issues/8253
> Implement accessing embedded field and method of aggregate

- vlib/v/checker/checker.v
- vlib/v/checker/tests/if_expr_optional_err.out
- vlib/v/checker/tests/if_expr_optional_err.vv
Fixes https://github.com/vlang/v/issues/10900
> checker: check if condition optional

- vlib/builtin/sorting_test.v
- vlib/v/gen/c/array.v
- vlib/v/gen/c/cgen.v
Fixes https://github.com/vlang/v/issues/10897
> cgen: fix several sort declarations

- vlib/v/fmt/asm.v
- vlib/v/fmt/tests/assembly/asm_keep.vv
> fmt: split up asm code into more granular methods

- vlib/net/http/header.v
- vlib/net/http/header_test.v
- vlib/net/http/request.v
- vlib/net/http/response.v
Closes https://github.com/vlang/v/issues/10930
> net: add parse_headers function and handle header line folding

- Dockerfile.alpine
Instead of cloning the git repo copy the source from the PWD.
> Dockerfile: copy source instead of cloning the repo

- thirdparty/libgc/amalgamation.txt
- thirdparty/libgc/gc.c
- thirdparty/libgc/gc.h
- vlib/builtin/builtin_d_gcboehm.v
A few things still need to be done before tcc can statically link against libgc.
> builtin: add bdwgc to thirdparty, statically link it on Windows

- vlib/v/checker/checker.v
- vlib/v/checker/tests/duplicate_field_method_err.out
- vlib/v/checker/tests/duplicate_field_method_err.vv
Fixes https://github.com/vlang/v/issues/10924
> checker: check duplicated field and method (only for anon-fns yet)

- thirdparty/vschannel/vschannel.c
Closes https://github.com/vlang/v/issues/10726
> thirdparty/vschannel: Bug fix format string vulnerability

- vlib/strings/builder.v
- vlib/v/scanner/scanner.v
- vlib/v/scanner/tests/position_0_err.out
- vlib/v/scanner/tests/position_0_err.vv
- vlib/v/tests/valgrind/simple_interpolation_script_mode.v
Fixes https://github.com/vlang/v/issues/10570
> scanner: pos of first token on position 0

- Dockerfile
> Dockerfile: Added USE_LOCAL for conditional copy of source.

- vlib/builtin/builtin_windows.c.v
This is a small follow-up to #10943:
- use parameters for `C.FormatMessage()` that are suggested in [Microsoft's example](https://docs.microsoft.com/en-us/windows/win32/debug/retrieving-the-last-error-code)
- take into account that the generated error message uses wide characters (it used to be truncated)
- in case of error 8 ("insufficient memory") `C.FormatMessage()`  apparently does not work anymore &ndash; so this case is treated specially
> builtin: fix Windows panic message

- .github/workflows/vab_ci.yml
This PR fixes the `vab` CI jobs.
There's apparently some inconsistencies with the default versions of the SDK/NDK on the GitHub runner.
So to fix it we use a little older version of the tools for now
> ci: fix vab tests

- .github/workflows/vinix-kernel.yml
> gh: Add workflow to test if the Vinix kernel builds

- vlib/v/gen/native/amd64.v
> native: improve few x64 generators

- vlib/v/checker/checker.v
- vlib/v/checker/tests/negative_assign_to_unsigned.out
- vlib/v/checker/tests/negative_assign_to_unsigned.vv
> checker: fix negative values for unsigned integers

- cmd/tools/vdoc/html.v
- cmd/tools/vdoc/html_tag_escape_test.v
> vdoc: fix wrong escaping in HTML docs

- doc/docs.md
This PR just makes "Calling V from C" a little easier to find by adding it to the TOC.
> doc: add calling V from C to toc

- make.bat
Fix wrong command name in help
> make.bat: clean-all --> cleanall

- vlib/v/gen/js/js.v
> js: Fix segfault when anonymous function is declared with assertion

- vlib/net/http/server.v
- vlib/v/markused/markused.v
Because closures are not implemented yet, this allows using other data
in the handler.
> http: Change server handler from function to interface

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/tests/ifs.vv
- vlib/v/gen/native/tests/ifs.vv.out
- vlib/v/gen/native/tests/native_test.v
> native: support more `ifs` constructions for amd64

- examples/vweb/vweb_assets/index.html
- examples/vweb/vweb_assets/vweb_assets.v
> examples: fix static vweb assets example

- doc/docs.md
> docs: Fix typo in Module import aliasing

- vlib/os/os_nix.c.v
- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/native/tests/native_test.v
- vlib/v/gen/native/tests/print.vv
- vlib/v/gen/native/tests/print.vv.err
- vlib/v/gen/native/tests/print.vv.out
> native: add support for print, eprint and eprintln

- vlib/v/ast/types.v
- vlib/v/checker/checker.v
- vlib/v/gen/js/builtin_types.v
- vlib/v/parser/fn.v
- vlib/v/parser/parse_type.v
Fixes https://github.com/vlang/v/issues/11043
> compiler: rename generic_struct_inst to generic_inst

- vlib/v/parser/parser.v
- vlib/v/parser/tests/sum_type_exists_err.out
- vlib/v/parser/tests/sum_type_exists_err.vv
- vlib/v/parser/tests/type_alias_existing_type_err.out
Fixes https://github.com/vlang/v/issues/11042
> parser: add check for existing type on sum type declaration

- vlib/v/parser/parser.v
- vlib/v/tests/array_test.v
> parser: make [..] work

- vlib/v/gen/c/cgen.v
- vlib/v/tests/option_struct_init_test.v
> gen: fix optional generation order

- vlib/v/gen/c/cgen.v
- vlib/v/tests/shared_lock_test.v
Fixes https://github.com/vlang/v/issues/10814
> cgen: fix shared field init

- vlib/v/ast/table.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/sum_type_test.v
Fixes https://github.com/vlang/v/issues/11074
> cgen: support embedded struct fields on sumtype common fields

- vlib/v/checker/checker.v
- vlib/v/checker/tests/assign_to_typeless_variable_err.out
- vlib/v/checker/tests/assign_to_typeless_variable_err.vv
Fixes https://github.com/vlang/v/issues/11077
> checker: fix assign to typeless variable

- cmd/tools/vpm.v
Fixes commands `v show nedpals.args`
> vpm: fix show command

- vlib/v/ast/ast.v
- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/native/tests/assert.vv
- vlib/v/gen/native/tests/assert.vv.out
> native: initial support for assert statements

- vlib/v/scanner/scanner.v
- vlib/v/tests/string_escape_backslash_test.v
Fixes https://github.com/vlang/v/issues/11113
> fix scaped backslash after string interpolation

- vlib/v/gen/native/arm64.v
> native: document arm64 registers with comments

- vlib/term/colors.v
- vlib/time/format.v
- vlib/v/tests/valgrind/logging.v
>  log: avoid using string__plus memory leak 

- vlib/cli/command.v
- vlib/cli/command_test.v
- vlib/cli/flag.v
- vlib/cli/help.v
> cli: add a separate mode for long flags instead of guessing

- cmd/tools/vdoc/resources/doc.css
> vdoc: more readable docs

- vlib/vweb/route_test.v
- vlib/vweb/vweb.v
Closes https://github.com/vlang/v/issues/11167
> vweb: fix catchall route

- vlib/builtin/js/array.js.v
> js: array.delete_last()

- vlib/v/tests/generic_fn_assign_generics_struct_test.v
- vlib/v/tests/generics_return_multiple_generics_struct_test.v
- vlib/v/tests/generics_return_recursive_generics_struct_test.v
- vlib/v/tests/generics_return_reference_generics_struct_test.v
- vlib/v/tests/generics_struct_anon_fn_fields_test.v
- vlib/v/tests/generics_with_embed_generics_test.v
- vlib/v/tests/generics_with_generics_struct_receiver_test.v
This PR supplement multi-instances generic testing.
> tests: supplement multi-instances generic testing

- vlib/v/gen/js/js.v
- vlib/v/gen/js/tests/testdata/overloading.out
- vlib/v/gen/js/tests/testdata/overloading.v
> js: Operator overloading

- vlib/hash/wyhash.c.v
- vlib/hash/wyhash.js.v
- vlib/hash/wyhash.v
- vlib/rand/rand.c.v
- vlib/rand/rand.v
- vlib/v/gen/js/builtin_types.v
- vlib/v/gen/js/js.v
> js: Initial work on porting rand module to JS backend

- vlib/v/gen/js/builtin_types.v
- vlib/v/gen/js/js.v
> js: Fix builtin casts & global declarations with no initializer

- vlib/gg/gg.v
> gg: Fix top left corner pixel not being drawn

- vlib/math/math.v
- vlib/math/math_test.v
```v
import math
gcd, x, y := math.egcd(6, 9)
assert gcd == 3
assert math.abs(6*x + 9*y) == gcd // in this case x == -1 and y == 1
```
> math: Add egcd function implementing the extended Euclidean algorithm

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/interface_with_mut_fields_keep.vv
> fmt: preserve method receiver mutability in interface decls

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/infix_expr.v
- vlib/v/tests/interface_runtime_conversions_test.v
This commit was originally part of #11212, but I guess I force-pushed over it while rebasing by accident :/
> cgen: small interface conversion fix

- vlib/os/file.c.v
> os: add File.read_into_ptr

- vlib/v/gen/c/str.v
- vlib/v/tests/inout/enum_print.out
- vlib/v/tests/inout/enum_print.vv
> cgen: fix enum print

- vlib/v/gen/c/cgen.v
- vlib/v/tests/fn_test.v
Fixes [this CI failure in the ui repo](https://github.com/vlang/ui/pull/377/checks?check_run_id=3372264191).
> cgen: fix interface parameters in fn type aliases

- vlib/json/json_decode_test.v
- vlib/json/json_primitives.v
> fix json.decode bugs for u64

- vlib/v/checker/checker.v
This PR cleanup checker.v.
- Use consistent parameter naming styles.
> checker: cleanup checker.v

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/arm64.v
- vlib/v/gen/native/gen.v
> v.gen.native: improve error messages for unsupported features

- vlib/v/gen/native/amd64.v
```
$ v -native -v i.v
builder.compile() pref:
x: "/Users/pancake/prg/v/modules"
v.module_search_paths:
['/Users/pancake/prg/v', '/Users/pancake/prg/v/modules', '/Users/pancake/prg/v/vlib', '/Users/pancake/.vmodules']
------ resolved dependencies graph: ------
* main -> builtin
------------------------------------------
------ imported modules: ------
['main']
-------------------------------
0.019    ms SCAN
0.961    ms PARSE
0.066    ms CHECK
0.001    ms TRANSFORM
0.000    ms Table.complete_interface_check
001000  e8 fb ef ff ff  call 0
main.main:
001005  55  push rbp
001006  48 89 e5  mov rbp, rsp
001009  48 83 ec 10  sub8 rsp,0x10
00100d  eb fe  jmp $$
00100f  31 ff  xor edi, edi
001011  b8 01 00 00 02  mov eax, 33554433
001016  0f 05  syscall
001018  c3  ret
relocs at 4121 should be …
```
> v.gen.native: support infinite loops `for {}` in amd64 and arm64

- vlib/v/gen/js/js.v
- vlib/v/gen/js/tests/testdata/match.out
- vlib/v/gen/js/tests/testdata/match.v
> js: match support

- vlib/gg/gg.v
Fixes https://github.com/vlang/v/issues/8807
Adds scaling to gg.draw_empty_poly
> gg: Add scaling to draw_empty_poly()

- cmd/tools/vast/test/demo.v
- cmd/tools/vast/vast.v
1. update vast to latest V.
2. add more demo code.
> tools/vast: update vast to latest V

- vlib/v/gen/c/array.v
- vlib/v/tests/array_of_sumtypes_test.v
> cgen: properly cast to sumtypes in array prepend and insert

- examples/http_server.v
- vlib/net/http/server.v
- vlib/net/http/server_test.v
> net.http.Server: Add close method to immediatly close the listener

- cmd/tools/vbug.v
The commit message explains it.
> vbug: fix v doctor markdown

- cmd/tools/vcheck-md.v
- vlib/context/cancel.v
- vlib/net/html/dom.v
- vlib/v/util/module.v
- vlib/x/ttf/ttf.v
This PR change `if !(a in/is b)` to `if a !in/is b`.
> all: change `if !(a in/is b)` to `if a !in/is b`

- vlib/v/checker/checker.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/match_test.v
Fixes https://github.com/vlang/v/issues/11116
> checker: allow noreturn in match expr

- vlib/sokol/sapp/sapp.c.v
- vlib/sokol/sapp/sapp_funcs.c.v
- Added the calls to manage the full screen calls
> sokol: Added fullscreen call

- vlib/builtin/js/array.js.v
- vlib/builtin/js/builtin.js.v
- vlib/builtin/js/builtin.v
- vlib/v/gen/js/fn.v
- vlib/v/gen/js/js.v
- vlib/v/gen/js/str.v
> js: Fix printing, make builtins for result and option types behave correctly

- vlib/gg/gg.c.v
- vlib/gg/gg.v
- vlib/sokol/sapp/enums.v
- vlib/sokol/sapp/sapp.c.v
- vlib/sokol/sapp/sapp_funcs.c.v
- gg/calls for drag&drop of files
> gg: added drag & drop calls

- vlib/os/os.v
- vlib/os/os_test.v
I've needed this a few good times - suggestions for a better name for the function, or optimizations is welcome ofc.
> os: add function to expand "~" to home directory

- vlib/builtin/js/builtin.js.v
- vlib/v/gen/js/js.v
> js: export attr for FnDecl codegen

- cmd/v/help/build.txt
> v help: enumerate all `js_*` backends

- vlib/regex/regex.v
- vlib/regex/regex_test.v
- vlib/regex/regex_util.v
- Fixed segfault in `find_all_str()`
- Syntax error as multiple quantifiers are chained
- More tests
Ref. bug #11366
> Regex: bug fix

- examples/gg/drag_n_drop.v
- Drag and drop example for `gg`/`sokol`
> added gg drag'n'drop example

- vlib/regex/regex.v
- vlib/regex/regex_test.v
**what's inside**
- bug fix for #11404 , quntifier working wrong on finals tokens
- added tests
> Regex: bugfix #11404

- vlib/v/checker/checker.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/generic_complex_sumtype_test.v
This PR fix complex generic sumtype (fix #11392).
- Fix complex generic sumtype.
- Add test.
```vlang
// Binary Search Tree example by @SleepyRoy
// TODO: make Node.value generic once it's robust enough
struct Node<T> {
value T
left  Tree<T>
right Tree<T>
}
type Tree<T> = Empty | Node<T>
// return size(number of nodes) of BST
fn size<T>(tree Tree<T>) int {
return match tree {
Empty { 0 }
Node<T> { 1 + size<T>(tree.left) + size<T>(tree.right) }
}
}
// insert a value to BST
fn insert<T>(tree Tree<T>, x T) Tree<T> {
return match tree {
Empty {
Node<T>{x, tree, tree}
}
Node<T> {
if x == tree.value {
tree
} else if x < tree.value {
Node<T>{
...tree
left: insert<T>(tree.left, x)
}
} else {
Node<T>{
...tree
right: insert<T>(tree.right, x)
}
}
}
}
}
// whether able to find a value …
```
> checker, cgen: fix complex generic sumtype (fix #11392)

- cmd/tools/vtracev.v
> tracev: fix running v tracev from directory with space

- doc/docs.md
> match as alternative to if and unless

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/native/tests/print.vv
- vlib/v/gen/native/tests/print.vv.out
> Native prints

- vlib/v/parser/tests/unexpected_token.out
- vlib/v/parser/tests/unexpected_token.vv
- vlib/v/scanner/scanner.v
> scanner: fix error with token `?`

- cmd/tools/vbug.v
- vlib/os/open_uri_default.c.v
- vlib/os/open_uri_windows.c.v
`open_uri` can open any uri passed, and will use the default application associated with the scheme.
Also refactor `vbug` to use it
> os: add `open_uri/1`

- vlib/v/parser/tmpl.v
- vlib/v/tests/inout/file.html
- vlib/v/tests/inout/tmpl_parse_html.out
- vlib/v/tests/inout/tmpl_parse_html.vv
Fix escaping @ in templates as described by @islonely on [discord](https://discord.com/channels/592103645835821068/592114487759470596/884835255129886731).
> tmpl: fix escaping @

- vlib/builtin/js/builtin.js.v
- vlib/builtin/js/builtin.v
- vlib/v/gen/js/fn.v
- vlib/v/gen/js/js.v
> js: Interfaces support, fix for error propagation & panic stacktraces

- vlib/v/ast/ast.v
- vlib/v/ast/table.v
- vlib/v/fmt/fmt.v
- vlib/v/fmt/struct.v
- Remove some done TODOs
- Remove now unnecessary method `Fmt.prefix_expr_cast_expr`
> ast,fmt: cleanup

- vlib/v/gen/js/fn.v
- vlib/v/gen/js/js.v
- vlib/v/parser/parser.v
> js: Prefix printing functions so they do not overlap with JS

- vlib/v/checker/checker.v
This PR use 'if foo in [TypeA, TypeB]' in checker.v.
> checker: use 'if foo in [TypeA, TypeB]' in checker.v

- vlib/net/http/http.v
- vlib/net/http/request.v
- vlib/net/http/request_test.v
> net/http: Add post_multipart_form function

- vlib/os/os.js.v
- vlib/v/builder/compile.v
- vlib/v/gen/js/auto_eq_methods.v
- vlib/v/gen/js/builtin_types.v
- vlib/v/gen/js/fn.v
- vlib/v/gen/js/js.v
- vlib/v/preludes_js/stats_import.v
> js: Refactor code, fix alias codegen, -stats now again works with tests on the JS backend

- cmd/tools/oldv.v
- cmd/tools/performance_compare.v
- cmd/tools/repeat.v
- cmd/tools/vast/vast.v
- cmd/tools/vwatch.v
- vlib/flag/README.md
- vlib/flag/flag.v
- vlib/flag/flag_test.v
As the title says, this changes some routines from doing panics to returning optionals.
Tests changed to match.
> flag: switch panics to optionals

- vlib/v/gen/c/cgen.v
This PR use 'if foo in [TypeA, TypeB]' in cgen.v.
> cgen: use 'if foo in [TypeA, TypeB]' in cgen.v

- examples/rule110.v
Add a [Rule 110](https://en.wikipedia.org/wiki/Rule_110) implementation in V as a simple example to demonstrate that the V language is Turing complete.
> Example: add Rule 110 example

- vlib/os/args.v
> os: fix typo in args.v

- vlib/v/fmt/fmt.v
- vlib/v/gen/js/js.v
This PR use 'if foo in [TypeA, TypeB]' in fmt.v and js.v.
> all: use 'if foo in [TypeA, TypeB]' in fmt.v and js.v

- vlib/math/math.v
> math: fix typos

- vlib/v/checker/checker.v
- vlib/v/checker/tests/optional_fn_err.out
- vlib/v/tests/option_test.v
Add one new error to checker to prevent compiler internal error
> checker: proper error for optional struct fields (#11293)

- vlib/json/json_test.v
- vlib/v/gen/c/json.v
> cgen: use unmangled variant name for encoding

- vlib/v/scanner/scanner.v
After cleanup the code is much clearer.
> scanner: cleanup scanning of `>`

- thirdparty/sokol/sokol_app.h
- thirdparty/sokol/sokol_gfx.h
- thirdparty/sokol/util/sokol_fontstash.h
- thirdparty/sokol/util/sokol_gl.h
- vlib/sokol/sapp/enums.v
- vlib/sokol/sapp/sapp_structs.c.v
- vlib/sokol/sgl/sgl.c.v
- vlib/sokol/sgl/sgl_funcs.c.v
- upgrade sokol to the last version available the 18/09/2021
- marked all V patches in sokol
- added support for program icons on linux, mac, win
> Sokol upgrade

- vlib/v/gen/c/array.v
This PR format array map/filter/all/any generated c codes.
After the formatting:
```vlang
Array_string arr = new_array_from_c_array(1, 1, sizeof(string), _MOV((string[1]){_SLIT("")}));
for (int _t1 = 0; _t1 < arr.len; ++_t1) {
string i = ((string*)arr.data)[_t1];
bool _t2 = (i.len == 0);
bool _t3 = true;
if (!_t2) {
Array_byte _t3_orig = string_bytes(string_substr(i, 1, i.len));
int _t3_len = _t3_orig.len;
for (int _t4 = 0; _t4 < _t3_len; ++_t4) {
byte it = ((byte*) _t3_orig.data)[_t4];
if (!(byte_is_letter(it))) {
_t3 = false;
break;
}
}
}
if ( _t2 ||_t3) {
println(_SLIT("empty or all char from second is letter!"));
// assert
if (!(true)) {
VAssertMetaInfo v_assert_meta_info__t5 = {0};
v_assert_meta_info__t5.fpath = _SLIT("tt1.v");
v_assert_meta_info__t5.line_nr = 6; …
```
> cgen: format array map/filter/all/any generated c codes

- vlib/log/log.v
Signed-off-by: Robert Marklund <robbelibobban@gmail.com>
> vlib: add get_level to log module

- vlib/v/gen/c/array.v
On current master, if-expression occurs c error when debug mode
```
v -g test vlib/v/tests/if_expression_test.v
---- Testing... --------------------------------------------------------------------------------------------------------
FAIL   418.625 ms vlib/v/tests/if_expression_test.v
/home/zakuro/src/github.com/zakuro9715/v/vlib/v/tests/if_expression_test.v:188:87: warning: extra tokens at end of #line directive [-Wextra-tokens]
#line 176 "/home/zakuro/src/github.com/zakuro9715/v/vlib/v/tests/if_expression_test.v"_t2;
^
//
/home/zakuro/src/github.com/zakuro9715/v/vlib/v/tests/if_expression_test.v:176:2: error: expected expression
} else {
^
1 warning and 1 error generated.
builder error:
```
After this change
```
v -g test …
```
> cgen: fix c error of if-expression when debug mode

- vlib/v/gen/c/array.v
This PR format generated C code of nested array call.
After formatting:
```vlang
Array_string arr = new_array_from_c_array(2, 2, sizeof(string), _MOV((string[2]){_SLIT("abc"), _SLIT("def")}));
bool _t1 = true;
Array_string _t1_orig = arr;
int _t1_len = _t1_orig.len;
for (int _t2 = 0; _t2 < _t1_len; ++_t2) {
string it = ((string*) _t1_orig.data)[_t2];
bool _t3 = true;
Array_byte _t3_orig = string_bytes(it);
int _t3_len = _t3_orig.len;
for (int _t4 = 0; _t4 < _t3_len; ++_t4) {
byte it = ((byte*) _t3_orig.data)[_t4];
if (!(byte_is_letter(it))) {
_t3 = false;
break;
}
}
if (!(_t3)) {
_t1 = false;
break;
}
}
bool all_is_letter =_t1;
println(all_is_letter ? _SLIT("true") : _SLIT("false"));
// assert
if (!(all_is_letter)) {
VAssertMetaInfo …
```
> cgen: format generated C code of nested array call

- vlib/json/json_primitives.v
- vlib/json/json_test.v
- vlib/v/gen/c/json.v
> cgen: json sumtype inlining

- examples/binary_search_tree.v
This PR reflects V's great progress on generic sumtype :-)
> example: make binary search tree example generic

- vlib/net/http/http.v
> net/http: Allow custom headers in post_multipart_form

- vlib/json/json_test.v
> json: assert encoded

- vlib/arrays/arrays.v
- vlib/arrays/arrays_test.v
> arrays: add concat function

- vlib/net/openssl/ssl_connection.v
> net.openssl: fix typos

- vlib/toml/checker/checker.v
- vlib/toml/scanner/scanner.v
- vlib/toml/tests/burntsushi.toml-test_test.v
This PR squashes 7 invalid escape tests
> toml: fix 7 escape tests

- doc/docs.md
> Added the topics: Hoistings and Closures

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/if_expression_test.v
> cgen: Fix if-expression code generation if it evaluates to propagating optional / or block

- vlib/net/http/request.v
> net.http: make public errors and parse_form

- vlib/arrays/arrays.v
- vlib/arrays/arrays_test.v
As requested in #12040
`binary_search` returns an index as I think that would make it the most versatile
> arrays: binary_search, lower_bound, and upper_bound array operations

- vlib/builtin/js/array.js.v
- vlib/builtin/js/byte.js.v
- vlib/builtin/js/int.js.v
- vlib/builtin/js/int_test.js.v
- vlib/builtin/js/map.js.v
- vlib/builtin/js/map_test.js.v
- vlib/builtin/js/string.js.v
- vlib/builtin/js/string_test.js.v
- vlib/v/gen/js/infix.v
- vlib/v/gen/js/js.v
> js: Add more tests to builtin/js and implement more builtin functions

- vlib/v/gen/c/array.v
- vlib/v/tests/interface_array_methods_test.v
- vlib/v/tests/sumtype_array_methods_test.v
> cgen: support `index` and `in` for sumtype/interface arrays

- vlib/os/os.c.v
This PR fixes the rare crash described in #12052
> os: fix rare crash in read_file. Fix #12052

- vlib/builtin/builtin.c.v
I could've used these improvements to track down the bug in #12052 - and the fix in #12053
> builtin: improve malloc panic messages

- vlib/builtin/js/builtin.js.v
- vlib/builtin/js/map_test.js.v
- vlib/builtin/js/rune.js.v
- vlib/builtin/js/string.js.v
- vlib/builtin/js/string_test.js.v
- vlib/builtin/js/utf8.js.v
- vlib/strings/builder.js.v
- vlib/v/gen/js/auto_str_methods.v
- vlib/v/gen/js/builtin_types.v
- vlib/v/gen/js/js.v
> js: Initial runes support

- vlib/v/ast/types.v
- vlib/v/checker/tests/interface_sameness_check_for_mutable_methods.out
- vlib/v/checker/tests/interface_sameness_check_for_mutable_methods.vv
> Don't try to de-reference non-pointer types in `fn_signature_using_aliases`

- vlib/toml/parser/parser.v
This PR adds a `peek()` function to the `parser` module.
It's (unfortunately) needed as a preparation for planned parsing of formatting.
Parsing of formatting is needed in some cases to be able to check for [things like this](https://github.com/BurntSushi/toml-test/blob/643fd7585441148f5d7ff6d1eb1de62292fa900f/tests/invalid/table/rrbrace.toml#L1).
> toml: add peek(n) function

- cmd/tools/vast/vast.v
> vast: update to latest V

- vlib/toml/parser/parser.v
This PR renames the `parser` method `sub_key()` to `dotted_key()` to use the TOML term like we already do for
`table` vs. `map`, `inline_table`, `bare`, `quoted` etc.
> toml: rename sub_key -> dotted_key

- vlib/toml/tests/burntsushi.toml-test_test.v
This PR will fix the failing CI
> toml: add new inline-table duplicate-key test to skip list

- examples/js_dom_draw/draw.js.v
- vlib/jsdom/context_2d.js.v
- vlib/jsdom/dom.js.v
- vlib/jsdom/html_canvas_element.js.v
- vlib/jsdom/path2d.js.v
- vlib/jsdom/point.js.v
> jsdom: Path2D API, All CanvasRenderingContext2D methods (except image methods)

- doc/docs.md
Custom table name was implemented: https://github.com/vlang/v/tree/master/vlib/orm#structs
> docs: ORM – add custom table name definition

- cmd/v/v.v
- vlib/v/pref/pref.v
- vlib/v/tests/vsh_envbang_test.v
This PR change `v run build.vsh gcc` to `v build.vsh gcc`.
- Script execution automatically increments the `run` parameter.
> cmd: `v run build.vsh gcc` change to `v build.vsh gcc`

- vlib/v/checker/checker.v
- vlib/v/gen/js/js.v
- vlib/v/tests/cast_test.js.v
> js,checker: Allow casting JS primitives to V primitives and vice-versa

- vlib/v/checker/checker.v
This PR makes minor cleanup in method_call.
> checker: minor cleanup in method_call

- vlib/toml/checker/checker.v
Nitty-gritty but everything count as they say...
> toml: small start -> end word use change

- vlib/v/tests/generic_arrays_sum_test.v
- vlib/v/tests/generic_fn_infer_modifier_test.v
- vlib/v/tests/generics_array_append_test.v
- vlib/v/tests/generics_array_delete_test.v
- vlib/v/tests/generics_method_on_receiver_types_test.v
- vlib/v/tests/generics_method_str_overload_test.v
- vlib/v/tests/generics_nested_struct_init_test.v
This PR supplement tests for different types of generic parameters.
> tests: supplement tests for different types of generic parameters

- .github/workflows/toml_ci.yml
- vlib/toml/parser/parser.v
- vlib/toml/tests/burntsushi.toml-test_test.v
This PR leaves our TOML parser at 100% compatibility with the *latest* [BurntSushi TOML test suite](https://github.com/BurntSushi/toml-test/) :partying_face:
Next up is 100% compatibility with the value tests :scream:
> toml: 100% BurntSushi test suite parsing compatibility

- vlib/v/tests/generics_method_str_overload_test.v
Return generic type instead of `Gen<G>`.
> Update generics_method_str_overload_test.v: Return generic type instead of `Gen<G>`.

- cmd/tools/vast/vast.v
- vlib/builtin/js/string_test.js.v
- vlib/builtin/string_test.v
- vlib/v/checker/checker.v
- vlib/v/fmt/fmt.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/js/comptime.v
- vlib/v/gen/js/js.v
- vlib/v/parser/comptime.v
- vlib/v/parser/expr.v
- vlib/v/parser/if_match.v
- vlib/v/parser/parser.v
- vlib/v/tests/comptime_attribute_selector_test.v
- vlib/v/tests/valgrind/1.strings_and_arrays.v
This PR makes cleanup of the comptime.
- Maintain a consistent overall style, `comp_xxx` change to `comptime_xxx`.
> all: cleanup of the comptime

- vlib/gg/text_rendering.v
> gg: fix system_font_path

- cmd/tools/vast/vast.v
- vlib/v/ast/ast.v
- vlib/v/ast/str.v
- vlib/v/checker/checker.v
- vlib/v/fmt/fmt.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/js/js.v
- vlib/v/markused/walker.v
- vlib/v/parser/comptime.v
- vlib/v/transformer/transformer.v
This PR change `CompFor` to `ComptimeFor` in ast.
> ast: change `CompFor` to `ComptimeFor`

- vlib/v/checker/checker.v
> checker: format checker.v

- vlib/toml/parser/parser.v
- vlib/toml/tests/burntsushi.toml-test_test.v
- vlib/toml/tests/strings_test.v
This PR implements [a minor TOML spec oddity](https://github.com/BurntSushi/toml-test/issues/95).
> toml: eat first nl if present in multiline strings

- vlib/toml/tests/burntsushi.toml-test_test.v
This PR removes a few tests that was fixed recently
> toml: remove fixed value tests from skip list

- vlib/v/checker/check_types.v
This PR makes a minor cleanup of infer_fn_generic_types() in check_types.v.
> checker: cleanup infer_fn_generic_types()

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/gen.v
> native: support defining functions in any order

- vlib/toml/any.v
- vlib/toml/tests/default_to_test.v
- vlib/toml/tests/table_test.v
- vlib/toml/tests/toml_bom_test.v
- vlib/toml/tests/toml_memory_corruption_test.v
As [discussed on Discord](https://discord.com/channels/592103645835821068/592320321995014154/910841575695863808)
Alternative to #12508
> toml: add Any.default_to() method

- vlib/v/builder/native.v
> native: support passing directory instead of a file

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/gen.v
> native: handle some more statements and don't dup warnings

- examples/js_dom_draw/draw.js.v
- examples/js_dom_draw/index.html
- vlib/builtin/js/jsfns.js.v
- vlib/jsdom/jsdom.js.v
- vlib/v/ast/table.v
- vlib/v/ast/types.v
- vlib/v/checker/checker.v
- vlib/v/gen/js/fn.v
- vlib/v/gen/js/js.v
> js,jsdom: Canvas & context API; Added TypeSymbol.is_js_compatible & temporary hacks for JS ifaces

- .github/workflows/ci.yml
> Add VSL and VTL to CI

- vlib/builtin/builtin_nix.c.v
> build: Fix OpenBSD

- vlib/v/ast/table.v
This PR makes minor cleanup of table.v.
> ast: cleanup table.v

- examples/js_dom_cube/README.md
- examples/js_dom_cube/cube.js.v
- examples/js_dom_cube/index.html
- vlib/builtin/js/array.js.v
- vlib/jsdom/jsdom.js.v
- vlib/v/gen/js/js.v
> jsdom, examples: More WebGL API; Added interactive 3D cube example running on VJS

- examples/js_dom_cube/cube.js.v
- examples/js_dom_cube/index.html
- examples/js_dom_draw/draw.js.v
- vlib/js/dom/dom.js.v
- vlib/js/dom/dom.v
- vlib/js/js.v
- vlib/js/promise/promise.js.v
- vlib/js/promise/promise.v
- vlib/js/promise/promise_test.js.v
- vlib/v/gen/js/fn.v
- vlib/v/gen/js/js.v
- Moved `jsdom` to `vlib/js/jsdom`
- Added promise API wrapper to `vlib/js/promise`
- Fixed codegen for generic structures and functions
> js: Fixes for generic structures and functions; promise API; refactor modules

- cmd/tools/vtest-all.v
- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/native/macho.v
- vlib/v/gen/native/pe.v
> native: Initial working hello world compilation for w64

- cmd/tools/vshader.v
- cmd/v/help/shader.txt
- doc/docs.md
Add `docs.md` shader section and provide text for `v help shader`
> docs: add `v shader` section, add help text

- vlib/v/checker/checker.v
This PR makes cleanup in checker.v.
- remove redundant code of find field with embed.
> checker: remove redundant code of find field with embed

- vlib/js/dom/dom.js.v
- vlib/js/js.js.v
- vlib/js/promise/promise.js.v
- vlib/js/promise/promise_test.js.v
- vlib/v/fmt/fmt.v
- vlib/v/gen/js/js.v
- Also made use of `resolve()` in `go` expr.
> js,vfmt: Fix formatting for JS types; add fetch API

- doc/docs.md
- examples/sokol/02_cubes_glsl/cube_glsl.v
- examples/sokol/03_march_tracing_glsl/rt_glsl.v
- examples/sokol/04_multi_shader_glsl/rt_glsl.v
- examples/sokol/05_instancing_glsl/rt_glsl.v
- examples/sokol/06_obj_viewer/show_obj.v
... As [requested](https://github.com/vlang/v/pull/12594#discussion_r757818389) by @JalonSolov
> docs: add link to shader inclusion example

- .github/workflows/toml_ci.yml
- vlib/toml/checker/checker.v
- vlib/toml/decoder/decoder.v
- vlib/toml/scanner/scanner.v
- vlib/toml/tests/crlf_test.v
This PR will bump and comply with the BurntSushi tests at commit eb989e5
> toml: comply with BurntSushi @eb989e5

- .github/workflows/toml_ci.yml
- vlib/toml/tests/alexcrichton.toml-rs-tests_test.v
This PR adds yet another test suite [alexcrichton/toml-rs](https://github.com/alexcrichton/toml-rs).
It revealed a few bugs so I think it's worth running against.
> toml: add `alexcrichton/toml-rs` test suite to CI

- vlib/toml/tests/testdata/.gitignore
Hide all external testdata from git
> toml: update testdata/.gitignore

- cmd/v/help/build-c.txt
help about using homebrew for libgc
> add help information on how to use brew for libgc

- vlib/toml/README.md
This PR improves the general documentation of the `toml` module.
> toml: add some meat to README.md

- vlib/builtin/js/builtin.v
- vlib/builtin/js/string.js.v
- vlib/builtin/js/utf8.js.v
- vlib/os/os_js.js.v
- vlib/v/util/util.c.v
- vlib/v/util/util.js.v
- vlib/v/util/util.v
Added some lacking functions that were required to make vlib/v/util compile to js backend. Also did split util.v into util.js.v and util.c.v.
> js: Make vlib/v/util compile on JS backend

- cmd/tools/vast/vast.v
- cmd/v/v.v
tools: update vast to latest V
> tools: update vast to latest V

- vlib/semver/semver.v
- vlib/semver/semver_test.v
> add str() to semver.Version with unit tests

- .github/workflows/gfx_ci.yml
- cmd/tools/vgret.v
This PR will enable visual regression testing of selected `gg` applications.
> ci: add `gfx_ci` utilizing `vgret`

- examples/viewer/LICENSE
- examples/viewer/README.md
- examples/viewer/file_scan.v
- examples/viewer/v.mod
- examples/viewer/view.v
- examples/viewer/zip_container.v
A new example for V.
This is a very simple image viewer that can accept:
- single files [JPEG, PNG, BMP, PSD, TGA, GIF (not animated), HDR, PIC, PNM]
- folders
- ziped folders
- a mix of the previous
**Image Operations:**
- Pan
- Zoom
> added image viewer example

- vlib/gg/gg.v
Adds a `draw_empty_triangle()` to `gg`
> gg: add draw_empty_triangle()

- vlib/v/gen/c/cgen.v
This PR makes minor cleanup of struct_init() in cgen.v.
> cgen: clean up struct_init

- vlib/gg/gg.v
Add gg.draw_ring()
**Example:**
```v
import gg
import gx
struct App {
mut:
gg     &gg.Context
}
fn main() {
gg: 0
}
app.gg = gg.new_context(
width: 200
height: 200
window_title: 'Draw Ring'
user_data: app
)
app.gg.run()
}
fn frame(mut app App) {
app.gg.begin()
// draws a ring starting from 0 degrees to 290 degrees.
app.gg.draw_ring(100, 100, 30, 40, 0, f32(math.radians(290)), 30, gx.red)
app.gg.end()
}
```
> gg: add draw_ring()

- vlib/v/fmt/tests/match_expected.vv
- vlib/v/fmt/tests/match_input.vv
- vlib/v/parser/if_match.v
> fmt: remove extra comma of branch instead of parse error

- cmd/v/help/build-js.txt
> Show all js backends in v help build-js

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/cheaders.v
This PR fix ci error of empty struct init.
> cgen: fix ci error of empty struct init

- cmd/tools/vtest-self.v
- vlib/builtin/int_test.v
- vlib/math/complex/complex_test.v
- vlib/v/transformer/transformer.v
> v: fix build and failing tests with tcc on arm64

- .github/workflows/ci.yml
> ci: ensure that V can be built on arm64 using tcc

- vlib/x/json2/encoder.v
- vlib/x/json2/encoder_test.v
Just a small readability update and tests utilizing the fix in #12667
> json2: small readability update + tests utilizing fix #12667

- vlib/v/checker/checker.v
- vlib/v/checker/tests/enum_cast.out
- vlib/v/checker/tests/enum_cast.vv
> checker: fix invalid cast warning for flag enums

- vlib/v/checker/comptime.v
This PR makes minor cleanups of comptime_call() in checker/comptime.v.
> checker: clean up comptime_call()

- cmd/tools/vtest-self.v
- vlib/v/gen/c/cheaders.v
> cgen: support closures on arm64

- vlib/v/gen/c/cgen.v
- vlib/v/tests/reserved_keywords_if_guard_test.v
On current master, fail added test like this.
```
┏ zakuro   ~/src/github.com/zakuro9715/v   master
┗━━⮞ v test vlib/v/tests/reserved_keywords_if_guard_test.v
---- Testing... -------------------------------------------------------------------------------------------------------------------------------------------
FAIL   343.594 ms vlib/v/tests/reserved_keywords_if_guard_test.v
^~~~~~~~~~~~~~~~
/tmp/v/test_session_62661440048178/reserved_keywords_if_guard_test.16762131133145598593.tmp.c:16210:8: error: use of undeclared identifier '_v_array'
if ((_v_array.len == 2)) {
^
6 warnings and 1 error generated.
...
builder error:
This is a compiler bug, please …
```
> cgen: fix c error when use reserved keyword as if guard var

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/import_selective_expected.vv
- vlib/v/fmt/tests/import_selective_input.vv
> fmt: fix removal of selective imported types used in type decl

- .cirrus.yml
- vlib/v/gen/c/cheaders.v
> cgen: support closures on arm32 as well

- cmd/tools/vcreate.v
- cmd/tools/vcreate_test.v
> cmd/tools: add support for .gitattributes

- vlib/v/gen/js/fn.v
> js: dont use async js_main in '-es5' mode

- vlib/v/gen/c/cgen.v
This PR makes minor cleanup in Gen struct definition.
> cgen: minor cleanup in Gen struct definition

- vlib/v/gen/c/cgen.v
When having multiple files with `go `, every parallel cgen thread will generate the `__v_thread_wait ` function (and several other helper functions), causing name conflicts in the cc.
Example error: (function was generated 3 times in this case)
```c
/tmp/v_501/test.16805633307865956473.tmp.c:5323:6: error: redefinition of '__v_thread_wait'
void __v_thread_wait(__v_thread thread) {
^
```
This PR makes `waiter_fns` shared between all cgen threads to prevent duplicate functions. (like `threaded_fns`)
> cgen: fix parallel waiter function generation

- .github/workflows/ci.yml
This PR fix ci error of vls build.
> ci: fix ci error of vls build

- vlib/builtin/js/builtin.js.v
- vlib/gg/gg.js.v
- vlib/js/dom/dom.js.v
> gg: Mouse down/up and mouse leave/out event handling on VJS

- vlib/v/gen/js/builtin_types.v
- vlib/v/gen/js/js.v
> js: Remove usage of default arguments for `-es5` flag 

- vlib/v/gen/c/fn.v
- vlib/v/tests/closure_generator_test.v
> gen: support returning large types from closures on amd64

- vlib/v/gen/js/builtin_types.v
- vlib/v/gen/js/js.v
> js: generate es5 methods for valueOf() and toString()

- cmd/v/help/ast.txt
> cmd: update vast -t help text

- vlib/v/checker/checker.v
This PR makes minor cleanup in the checker.v.
> checker: minor cleanup in the checker.v

- vlib/v/checker/checker.v
- vlib/v/checker/tests/cast_alias_to_byte_err.out
- vlib/v/checker/tests/cast_alias_to_byte_err.vv
This PR makes a minor cleanup in cast_expr().
- Remove  redundant conditional.
> checker: minor cleanup in cast_expr()

- vlib/adt/README.md
- vlib/adt/heap.v
- vlib/adt/heap_test.v
Implemented with this reference: https://en.wikipedia.org/wiki/Binary_heap
> adt: Implement binary MinHeap data structure

- vlib/v/gen/c/auto_str_methods.v
This PR perfect auto_str error messages.
> cgen: perfect auto_str error messages

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/shared_interface_test.v
This PR addresses the issue described [here](https://github.com/vlang/v/issues/12810).
I came across this issue trying to add a mock a service in vweb.
Unfortunately, I don't really know what I'm doing here, so there is probably a lot better way of doing it (but at least there's a working unit test now).
If anyone can think of things which might be broken by this, then please let me know to improve the unit test.
> cgen: Fix compile error on locking interface value

- doc/docs.md
- added negative indexed slices docs
- added "list comprehension"
**Issues:** I've formtaed the code before put in teh docs, but the `./v check-md doc/docs.md`
keep give not formated to the exampel code of the list comprehension, row 893 in the md file.
> DOCS: added negative indexed slices, added example for 'list comprehension'

- vlib/builtin/js/jsfns.js.v
- vlib/builtin/js/string.js.v
- vlib/v/gen/js/tests/js.v
> js: use JS.String instead of string in builtin javascript functions

- cmd/v/help/build.txt
- vlib/v/builder/compile.v
- vlib/v/builder/interpreterbuilder/v_interpret_test.v
- vlib/v/eval/eval.v
- vlib/v/parser/v_parser_test.v
> v.eval: add tests and fix runtime cast crash

- vlib/v/gen/c/cheaders.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/closure_test.v
> cgen: support larger closure parameters

- vlib/net/address_android.c.v
added a copy of `address_linux.c.v` since compilation for Android fails without it.
> net:add adress_android

- vlib/dlmalloc/dlmalloc.v
> dlmalloc: Fix WASM codegen bug

- examples/sokol/06_obj_viewer/modules/obj/obj.v
- fix for the alters on example 06
> sokol: fix for example06

- vlib/net/html/tag.v
- vlib/net/html/tag_test.v
Added three methods to `html.Tag` with the same usage as `html.DocumentObjectModel.get_tag()`.
As for the name, Dom's is `get_tag()`, but since it returns an array, I used `get_tags()`.
> html: add Tag.get_tags()

- examples/call_v_from_python/test.py
> Test.py: Add os detect and call correct file.

- vlib/dlmalloc/dlmalloc.v
> dlmalloc: Temporary fix for segfault

- examples/term.ui/text_editor.v
> examples: fix typo in text_editor.v

- doc/docs.md
I have made a few minor adjustments to the document.
> document: adjust the content of the document

- vlib/v/gen/c/comptime.v
This PR makes minor cleanup in `comptime_if_cond()`.
> cgen: minor cleanup in comptime_if_cond()

- vlib/v/util/util.v
This PR fix the potential error of js_builder command.
> util: fix the potential error of js_builder command

- vlib/v/gen/js/fn.v
- vlib/v/gen/js/js.v
- vlib/v/gen/js/tests/js.v
> js: Fix break and continue in or blocks

- vlib/os/os.js.v
- vlib/v/gen/js/fn.v
- vlib/v/gen/js/js.v
> js,os: Fix `return` in `or` blocks; Properly get path_delimiter and path_separator in JS

- vlib/math/unsigned/uint128.v
- vlib/math/unsigned/uint128_test.v
Added tests for uint128. Uint256 tests will be added later because I found some weird bug with converting string to uint256 and I have to fix it.
> math/unsigned: Add uint128 tests

- vlib/math/easing.v
As part of the refactoring of `ui`, I think this https://github.com/vlang/ui/blob/master/easing.v would be more appropriate in `math` than in `ui`, so I moved it here.
> math: add easing

- vlib/v/checker/struct.v
- vlib/v/checker/tests/field_can_not_be_from_the_same_type_as_containing_struct.out
This PR correct error message in struct_decl().
> checker: correct error message in struct_decl()

- vlib/v/transformer/transformer.v
> transformer: fix some missing `stmt` assignments

- vlib/gg/gg.c.v
Add `screen_size()` for windows, then run v fmt -w gg.c.v.
> `screen_size()` for Windows and run `v fmt -w gg.c.v`.

- examples/gg/mandelbrot.v
There were two issues:
* The program used `println`, but had no `[console]` attribute, which makes it crash on Windows
* The stack size is very limited on Windows, so a 600 * 800 array doesn't fit; now the array is dynamically allocated (on all operating systems); this also theoretically allows for basically infinitely high resolution (although rendering becomes really slow)
> examples: fix the mandelbrot set example on Windows

- vlib/gg/gg.c.v
- vlib/gg/testdata/draw_circles.vv
- Added `draw_circle_empty()`
- Changed `outer_r` to `thickness` in the `draw_arc_[type]()` functions
- Changed `arc_angle` to `end_angle` in the `draw_slice_[type]()` functions
- Changed `r_horizontal` and `r_vertical` to `rw` and `rh` in the `draw_ellipse_[type]()` functions
- Fixed `draw_slice_empty()` not connecting back to the center
> gg: additions, changes and fixes

- vlib/v/gen/c/infix_expr.v
- vlib/v/tests/shared_array_append_many_test.v
> fix appending array to shared array

- vlib/cli/help.v
> cli: make help functions public

- vlib/gg/gg.c.v
Modified some variable names for consistency and readability.
> gg: minor cleanup consistency in variable names

- cmd/tools/modules/testing/common.v
- examples/sokol/simple_shader_glsl/.gitignore
- examples/sokol/simple_shader_glsl/simple_shader.glsl
- examples/sokol/simple_shader_glsl/simple_shader.v
- vlib/sokol/gfx/gfx_structs.c.v
- vlib/sokol/sapp/sapp.c.v
- vlib/sokol/sapp/sapp_funcs.c.v
This PR adds a V port of https://github.com/floooh/sokol-samples/blob/master/sapp/triangle-sapp.c
The aim of this example is to be short and clear about what is happening in the code.
> examples: add port of simple triangle sokol sample

- doc/docs.md
Added an example that uses `as` to cast interface.
related to #13302
> doc: interface casting

- doc/docs.md
At the moment, V does not implement `coroutine`, so it is better to write `thread` to avoid misunderstandings and overestimate.
https://en.wikipedia.org/wiki/Coroutine
> doc: change word coroutine to thread

- doc/docs.md
> doc: add autofree is wip

- vlib/picoev/picoev.v
- vlib/picohttpparser/picohttpparser.v
> picoev: remove unused `#flag`

- doc/docs.md
Added `hello_runes.string()` to show how to get string from []rune.
> doc: add []rune.string()

- .github/ISSUE_TEMPLATE/bug_report.md
Added a requirement to issue template.
> minimal reproducible code

- vlib/v/checker/assign.v
- vlib/v/checker/tests/assing_none.out
- vlib/v/checker/tests/assing_none.vv
Fixes https://github.com/vlang/v/issues/13366
> checker: make a compilation check when we assing a none value

- vlib/arrays/arrays.v
- vlib/arrays/arrays_test.v
> arrays: rotate_left and rotate_right

- doc/docs.md
> docs: add a json section, with subsections for encoding and decoding

- doc/docs.md
The interface example is split, so made the connection clearer.
> doc: improve interface examples

- cmd/tools/vrepl.v
- vlib/v/tests/repl/import_alias.repl
Fixes https://github.com/vlang/v/issues/13342
> repl: support the alias in repl

- cmd/tools/vrepl.v
- cmd/v/v.v
Reduced the logo
I don't know why the logo is needed, but the previous one was taking up too much space. 
If you don't like this one, you can choose another one [here](https://patorjk.com/software/taag/#p=testall&f=Graffiti&t=V), there are many options.
> repl: Reduced the logo

- vlib/net/urllib/values.v
- vlib/net/urllib/values_test.v
This PR will fix a regression introduced in the last change in the urllib parsing logic, and add a minimal unit test to avoid future regression
> urllib: fixed regression in the set function

- cmd/tools/vrepl.v
- vlib/readline/readline.v
- vlib/readline/readline_linux.c.v
Fixes https://github.com/vlang/v/issues/13425
> readline: give the possibility to ignore the empty line in the history

- cmd/tools/vrepl.v
> repl: "list" deleted '/'  | repl: adaptive logo display

- vlib/v/parser/assign.v
This PR makes cleanup in check_undefined_variables().
> parser: cleanup in check_undefined_variables()

- vlib/vweb/vweb.v
> vweb: support ipv6

- doc/docs.md
https://github.com/vlang/v/issues/13513
> fix exec -> execute

- vlib/net/udp.v
- vlib/v/checker/checker.v
fix https://github.com/vlang/v/issues/13512
> Get udp port when bind 0

- vlib/gg/gg.c.v
This will be a breaking change for programs that use `gg` in Android.
I would like to hear opinions from developers who are actually developing on Android using directly `gg`, even better if working on cross-platform development between Android and desktop.
https://github.com/vlang/v/blob/ebb66aa82cd6caccced43fa92d3f467db263c680/vlib/gg/gg_android.c.v#L36
With the current 160, we can only draw 360 pixels wide.
There is a suggestion to change this number of 160, but I think it would be more flexible if it can be changed  when creating an application.
And, there is an idea to make it possible to give an arbitrary value as `android_dpi_scale(multiplier f32)`, but I think it would be convenient to calculate it from the Window width of the program for Android (width field of Context).
As a …
> gg: improve Context scale for Android

- vlib/math/complex/complex.v
make components mutable
currently none of the complex stuff works in-place, this is mostly fine, compiler/cache make it so, but if you need to change one component only, i did, it is overly expensive.
complex is often in tight loop, so small optimisation is v. good.
my tests show, for changing one component in-place, is >30% faster, with no slow down if no used.
this could use a benchmark, i could supply if accepted.
```
// currently to change component
c+=complex.Complex{0,d} 
// after patch
c.im+=d
```
> math.complex: really simple optimisation for scientific/modelling, no apparent drawbacks

- examples/bst_map.v
- vlib/datatypes/bstree.v
- vlib/datatypes/bstree_test.v
> datatype: adding binary seach tree implementation

- vlib/net/socket.v
- vlib/net/tcp.v
- vlib/net/udp.v
as title ,  write `pub fn (s &Socket) address() ?Addr ` only once
> socket address DRY

- vlib/net/socket.v
- vlib/v/checker/for.v
- vlib/v/checker/tests/for_in_invalid_identifier.out
- vlib/v/checker/tests/for_in_invalid_identifier.vv
> checker: only cast as ast.Var if not unresolved, fixes #13561

- vlib/datatypes/bstree.v
> bstree: fixed into node contructor function

- doc/docs.md
Make the documentation of Embedded struct clearer
> Make the documentation of Embedded struct clearer

- vlib/v/ast/table.v
- vlib/v/checker/fn.v
- vlib/v/parser/fn.v
- vlib/v/parser/parser.v
This PR define 'const invalid_type_idx = -1' in ast.
- Avoid using `-1` directly.
> ast: define 'const invalid_type_idx = -1'

- doc/docs.md
Removed duplication and inheritance-oriented explanations that are more than necessary for the official documentation.
Added a missing explanation.
> doc: improve embedded struct section

- doc/docs.md
> doc: fix header size

- vlib/crypto/ed25519/internal/edwards25519/scalar.v
- vlib/v/ast/ast.v
- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/fn_headers_with_comments_expected.vv
- vlib/v/fmt/tests/fn_headers_with_comments_input.vv
- vlib/v/fmt/tests/fn_headers_with_comments_keep.vv
- vlib/v/parser/fn.v
> fmt: keep trailing comments after fn header decl

- vlib/v/checker/assign.v
- vlib/v/tests/match_expr_with_assign_sumtype_test.v
This PR fix match expr with assign sumtype variable (fix #13541).
- Fix match expr with assign sumtype variable.
- Add test.
```vlang
fn main() {
parse_args(['1', '+', '-', '*', '/', ' ']) or { println(err) }
}
enum Operator {
add
subtract
multiply
divide
}
type Value = Operator | int
struct Expression {
left  ?&Expression = none
val   Value
right ?&Expression = none
}
enum State {
expecting
parse_num
parse_operator
}
fn tokenise(args string) ?[]Value {
mut rv := []Value{}
mut state := State.expecting
mut cur_value := Value(0)
for i in args.runes() {
match state {
.expecting {
match i {
`0`...`9` {
state = .parse_num
cur_value = int(i.str().parse_uint(10, 8) ?)
}
`+`, `-`, `*`, `/` {
state = .parse_operator
cur_value = match i {
`+` {
Operator.add
}
`-` {
Operator.subtract
}
`*` { …
```
> checker: fix match expr with assign sumtype variable (fix #13541)

- vlib/v/ast/table.v
- vlib/v/checker/checker.v
- vlib/v/checker/containers.v
This PR add table.is_sumtype_or_in_variant().
- Add table.is_sumtype_or_in_variant().
> ast: add table.is_sumtype_or_in_variant()

- vlib/v/checker/checker.v
This PR makes cleanup of smartcast in checker.v
> checker: cleanup smartcast in checker.v

- vlib/v/checker/for.v
This PR simplify for smartcast in for_stmt().
> checker: simplify for smartcast in for_stmt()

- vlib/encoding/utf8/utf8_util.v
> utf8: fix typo in utf8_util.v

- vlib/v/checker/checker.v
- vlib/v/tests/comptime_generic_test.v
- Fix #13626 (unable to infer correct generic type)
> Side note: this is a temp fix, this generic issue is probably deeper than this situation.
> Fix #13626, check unwrapped type is fixed array and selector expr is 'len'

- vlib/v/checker/checker.v
- vlib/v/checker/for.v
- vlib/v/gen/c/sql.v
- vlib/v/parser/assign.v
- vlib/v/parser/sql.v
- vlib/v/transformer/transformer.v
This PR makes cleanup of smartcast.
> all: cleanup smartcast

- doc/docs.md
Added a basic example to the explanation of Heap structs.
> doc: add struct reference example

- vlib/v/builder/msvc.v
This PR also cleans up msvc.v a little.
> v.builder: only add /DEBUG:FULL when -cflags does NOT contain custom /DEBUG options

- vlib/sokol/sapp/sapp_funcs.c.v
Compared it with `sokol_app.h`, made the order the same as that and added the missing functions.
For the ones I wasn't sure about, just copy-pasted, comment out.
> sokol: reorder and add missing funcs

- vlib/arrays/arrays.v
- vlib/builtin/array.v
Update fold, reduce, group_by description.
Change fold example for clarity.
Mention to see fold for reduce functions, as fold is most general.
> vlib/arrays: Improve fold/reduce docs

- vlib/v/ast/types.v
This PR makes a minor cleanup in pref_arch_to_table_language().
> ast: minor cleanup in pref_arch_to_table_language()

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/native/tests/typeof.vv
- vlib/v/gen/native/tests/typeof.vv.out
> native: initial support for typeof() expressions

- vlib/strings/builder.c.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/ptr_slice.out
- vlib/v/checker/tests/ptr_slice.vv
> checker: fix cgen error on sliced references

- cmd/v/help/build-c.txt
> doc: fix minor typos in build-c

- vlib/builtin/wasm_bare/libc_impl.v
> builtin/wasm_bare: Fix malloc invocation

- vlib/v/checker/match.v
This PR makes a minor cleanup in match_expr().
> checker: minor cleanup in match_expr()

- vlib/v/gen/c/if.v
This PR makes minor cleanup in if_expr().
> cgen: minor cleanup in if_expr()

- README.md
Added some notes and a link to the project installation-issues discussion category as per discussion. (https://discordapp.com/channels/592103645835821068/592114567958495235/953890129620107274)
> Add installation-issues discussion in README

- vlib/v/checker/checker.v
This PR makes a minor cleanup in check_or_last_stmt().
> checker: minor cleanup in check_or_last_stmt()

- vlib/v/gen/c/index.v
This PR makes minor cleanup in index.v.
- Change variable name `elem_typ` to `elem_sym`.
> cgen: minor cleanup in index.v

- cmd/tools/vbug.v
> tools: fix typo in vbug.v

- vlib/v/ast/types.v
- vlib/v/checker/check_types.v
- vlib/v/checker/fn.v
- vlib/v/checker/tests/generic_parameter_on_method.out
- vlib/v/checker/tests/generic_parameter_on_method.vv
Fixes https://github.com/vlang/v/issues/13486
This was fun :) I will give a run with the CI and after that, I will check the comments style.
In addition, I would like to keep the commits explanation here because can be a very difficult drive in the type checking with the code that keeps changing.
> checker: check if the generics value has the same types

- vlib/rand/rand.v
- vlib/rand/random_numbers_test.v
Add generic shuffle function. See also https://github.com/vlang/v/discussions/13793.
> rand: add `shuffle` function for array

- vlib/v/ast/types.v
- vlib/v/gen/c/auto_eq_methods.v
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/json.v
This PR restore Type.str() and fix error for it.
> ast, cgen: restore Type.str() and fix error for it

- vlib/builtin/rune.v
> builtin/rune: document length_in_bytes method

- doc/docs.md
> doc: tweak array methods section

- doc/docs.md
Also fix level of negative slice indexes and method chaining subheadings.
> doc: add links to notable array subheadings

- vlib/v/ast/ast.v
This PR makes a minor cleanup in ast.v.
- Remove the comments that are no longer used.
> ast: minor cleanup in ast.v

- doc/docs.md
Tweak wording of introduction.
Move array operators subheading to first section of *Arrays*. << was used in examples before it had been introduced.
Split << example into 2.
Document `array.data`.
Add a simpler `it` array initialization example.
> doc: improve Arrays section

- doc/docs.md
> doc: move enum methods to enum section from sum types

- vlib/sokol/c/declaration.c.v
> sokol: glcore33 option for macos

- cmd/tools/vdoc/html.v
- vlib/builtin/array.v
- vlib/builtin/int.v
- vlib/builtin/js/byte.js.v
- vlib/builtin/option.v
- vlib/vweb/vweb.v
This doesn't include multi-line examples or v code blocks in the README.md example.
Part of https://github.com/vlang/v/issues/13851.
If the example isn't valid V:
```v
// Example: `if ouch { return error('an error occurred') }`
```
You'll get an error like:
```
internal_memory:1:47: error: invalid character literal `if ouch { return error('an error occurred') }` => `if ouch { return error('an error occurred') }` ([`i`, `f`, ` `, `o`, `u`, `c`, `h`, ` `, `{`, ` `, `r`, `e`, `t`, `u`, `r`, `n`, ` `, `e`, `r`, `r`, `o`, `r`, `(`, `'`, `a`, `n`, ` `, `e`, `r`, `r`, `o`, `r`, ` `, `o`, `c`, `c`, `u`, `r`, `r`, `e`, `d`, `'`, `)`, ` `, `}`]) (more than one character)
internal_memory:1:1: details: use quotes for strings, backticks for characters
```
This one triggers a less informative error: …
> vdoc: highlight inline examples for `-f html`

- vlib/rand/rand.v
- vlib/v/checker/check_types.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/generic_type_inference.vv
When I try to use a more complex usage of generics I receive the following error reproduced in the first commit!
In fact, the error that is produced in the following one
```
➜  v git:(master) ./v vlib/v/checker/tests/generic_type_inference.vv
vlib/v/checker/tests/generic_type_inference.vv:19:13: error: inferred generic type `T` is ambiguous: got `KeyVal<int>`, expected `int`
17 | fn main() {
18 |     mut bst := datatypes.BSTree<KeyVal<int>>{}
19 |     bst.insert(KeyVal<int>{key: "alibaba", val: 12})
|                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20 |     println(bst.in_order_traversals())
21 | }
vlib/v/checker/tests/generic_type_inference.vv:20:14: error: unknown method or field: `datatypes.BSTree<KeyVal<int>>.in_order_traversals`
18 |     mut bst := datatypes.BSTree<KeyVal<int>>{} …
```
> checker: type inference over a generic type should compile

- vlib/encoding/csv/reader.v
- vlib/encoding/csv/reader_test.v
> encoding.csv: allow passing a custom delimiter to the `new_reader` function

- cmd/tools/vdoc/html.v
- cmd/tools/vdoc/utils.v
- vlib/builtin/int.v
- vlib/builtin/string.v
(See https://modules.vlang.io/arrays.html for examples).
Also avoid calling `ascii_str` for terminal color highlight.
Add some builtin doc links.
> vdoc: HTML highlight generic function as function, not name

- cmd/v/help/help.v
> vhelp: minor change

- vlib/v/checker/fn.v
> checker: fix typo

- vlib/gg/draw.c.v
> gg: document all draw functions

- vlib/gg/image.c.v
- vlib/gg/image.v
> gg: add missing doc strings to pub fns in image.*

- vlib/time/parse.v
> time: add missing doc string to parse.v

- vlib/v/gen/c/fn.v
This PR simplify const of optional.
> cgen: simplify const of optional

- vlib/gg/gg.c.v
- vlib/gg/gg_android.c.v
- vlib/gg/recorder.c.v
> gg: add missing doc strings to android, recorder and gg.c.v

- vlib/v/checker/checker.v
> checker: allow all binary operations on pointers when translating code produced by c2v

- examples/web_crawler/web_crawler.v
resolved the new path of the target web page
> resolved the new path of the target web page

- vlib/v/gen/c/fn.v
This PR format json encode/decode generated c codes.
then:
```v
main__TodoDto body = ((main__TodoDto){.foo = 0,});
// json.encode
cJSON* _t3 = json__encode_main__TodoDto(body);
string _t4 = json__json_print(_t3);
cJSON_Delete(_t3); //del
// json.decode
cJSON* _t2 = json__json_parse((_t4));
Option_main__TodoDto _t5 = json__decode_main__TodoDto (_t2);
cJSON_Delete(_t2); //del
Option_main__TodoDto _t1 = (_t5);
if (_t1.state != 0) { /*or block*/
panic_optional_not_set( IError_name_table[_t1.err._typ]._method_msg(_t1.err._object) );
}
main__TodoDto ret =  (*(main__TodoDto*)_t1.data);
println(main__TodoDto_str(ret));
```
now:
```v
main__TodoDto body = ((main__TodoDto){.foo = 0,});
// json.encode
cJSON* _t3 = …
```
> cgen: format json encode/decode generated c codes

- cmd/tools/vpm.v
- cmd/v/help/install.txt
- doc/docs.md
> vpm: add `install --once` option

- doc/docs.md
> docs: add links to download C compilers

- vlib/arrays/arrays_test.v
- vlib/v/gen/c/array.v
> fix: invalid operands to binary expression

- cmd/tools/vcreate.v
Fixes fmt regression introduced in https://github.com/vlang/v/pull/14046
> fmt: reformatted file: tools/vcreate.v

- vlib/v/checker/checker.v
- vlib/v/checker/tests/undefined_type_on_sumtype.out
- vlib/v/checker/tests/undefined_type_on_sumtype.vv
as requested from @spytheman in https://github.com/vlang/v/pull/14006 I removed all the unuseful work!
Fixes https://github.com/vlang/v/issues/14002
> checker: ensure that the concrete type in the SubType exists

- vlib/io/readerwriter.v
> io: Fix typo in readerwriter.v

- vlib/v/token/token.v
This PR makes minor cleanup of token.v.
> token: minor cleanup of token.v

- vlib/v/checker/check_types.v
- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/checker/tests/modules/deprecated_module/main.v
- ~~Allow alias to alias~~ @medvednikov pointed out that it is C2V bug and C2V should resolve it automatically
- Allow signed -> unsigned conversion
> checker: c2v fixes

- vlib/v/ast/types.v
This PR makes minor cleanup of types.v.
> ast: minor cleanup of types.v

- vlib/v/checker/assign.v
This PR makes minor cleanup in assign_stmt().
> checker: minor cleanup in assign_stmt()

- vlib/builtin/js/map_test.js.v
- vlib/builtin/map_test.v
- vlib/builtin/string.v
> builtin: remove unnecessary casts for defunct small unsigned warning

- vlib/gg/draw.c.v
Fix gg.draw_rounded_rect_filled() drawing abnormal problem, and support transparent color filling.
Before fix:
After fix:
> gg:fix gg.draw_rounded_rect_filled() drawing abnormal problem

- vlib/v/parser/parser.v
This PR makes a minor cleanup in stmt().
> parser: minor cleanup in stmt()

- vlib/cli/help.v
> cli: add missing doc strings

- vlib/strconv/f32_str.c.v
- vlib/strconv/f64_str.c.v
- vlib/strconv/format.v
- vlib/strconv/format_mem.c.v
- vlib/strconv/ftoa.c.v
- vlib/strconv/utilities.c.v
- vlib/strconv/vprintf.c.v
> strconv: add missing doc strings

- vlib/v/gen/c/array.v
This PR makes cleanup in array_init().
- Split out long function.
> cgen: cleanup in array_init()

- vlib/gg/draw.c.v
- fix gg.draw_rounded_rect_empty() graphical abnormalities
- some performance and detail optimizations
> gg: fix gg.draw_rounded_rect_empty() graphical abnormalities and some optimizations

- vlib/gg/draw.c.v
about `draw_rounded_rect_filled()` and `draw_rounded_rect_empty()`:
- remove the judgment inside the loop.
- places judgments outside the loop.
> gg: some logic improvements on judgment and looping.

- vlib/arrays/arrays.v
> arrays: rephrase doc string

- vlib/v/checker/checker.v
> checker: Disable addition,subtraction and multiplication overloading on structures when translated

- CONTRIBUTING.md
Added step to format code, so PR require less back and forth and syntax matches
> Contributing Gide: add step

- vlib/v/ast/table.v
- vlib/v/ast/type_size_test.v
- vlib/v/ast/types.v
- vlib/v/builder/builder.v
- vlib/v/checker/check_types.v
- vlib/v/checker/checker.v
- vlib/v/checker/comptime.v
> ast: add a type_size() method

- tutorials/building_a_simple_web_blog_with_vweb/README.md
An improvement over nothing :)
> doc: suggest a basic auto-reload setup

- vlib/v/checker/checker.v
> checker: allow pointer index while translated

- cmd/tools/modules/testing/common.v
- vlib/time/format.v
- vlib/time/relative_test.v
- vlib/time/time.v
Relative time function can now handle future and past dates. Added a test file to verify past and new functionality `v run vlib/time/relative_test.v`
> time: relative update

- vlib/v/gen/c/cgen.v
> cgen: fix const decl gen when translated

- CONTRIBUTING.md
> doc: add JS backend mention

- vlib/v/checker/check_types.v
> checker: allow fixed array to pointer and vice versa when translated

- vlib/v/gen/c/array.v
This PR makes cleanup in gen_array_contains_methods().
> cgen: cleanup in gen_array_contains_methods()

- vlib/v/checker/check_types.v
> checker: allow rune->any int and vice versa when translated

- vlib/builtin/linux_bare/old/array_bare.v
> Fix typo in array_bare.v

- vlib/v/checker/checker.v
- vlib/v/checker/comptime.v
This PR extract comptime_selector() from expr().
> checker: add comptime_selector()

- vlib/v/checker/check_types.v
- vlib/v/checker/fn.v
> checker: allow passing fixed array as pointer to functions; bool <-> int (C2V fixes)

- vlib/v/checker/fn.v
This PR makes a minor cleanup in fn_call().
> checker: minor cleanup in fn_call()

- doc/docs.md
> docs: update keyword list

- vlib/net/http/request.v
- vlib/net/http/request_test.v
I need a way to manage POST json datas.
This PR looks to work for my need: using fetch method in js with a json payload.
-> I don't know if this cover all using cases of POST datas.
To get datas, it's really easy, just :
```v 
if app.form['json'] != '' {
out := json.decode(map[string]string, app.form['json']) ?
}
```
Or 
```v
if app.form['json'] != '' {
out := json.decode(StructName, app.form['json'])  or { StructName{where: ....}
}
```
> vweb: manage POST json datas

- vlib/v/scanner/scanner.v
This PR makes minor simplification in scanner.v.
> scanner: minor simplification in scanner.v

- CONTRIBUTING.md
- vlib/builtin/string.v
- vlib/datatypes/README.md
- vlib/regex/regex_util.v
- vlib/strings/builder.c.v
A few comments were incorrect or associated with the wrong function: fixed those. Added clarity to a regex function with an example. Added corrections to CONTRIBUTING about file location
> documentation: fix

- vlib/strings/builder.c.v
- vlib/strings/builder.js.v
- vlib/strings/builder_test.js.v
- vlib/strings/builder_test.v
Added reset function to clear buffer. Also removed deprecated function
> string builder: add reset

- vlib/os/os.v
- vlib/szip/szip.v
- vlib/szip/szip_test.v
> szip: expose zip_folder

- vlib/regex/regex.v
- vlib/regex/regex_test.v
- Bug fix for bug #14370
- added more Tests
> Regex: bugfix #14370 last IST not managed in advance tests

- vlib/v/checker/fn.v
> checker: alias C2V fix

- vlib/v/checker/fn.v
> checker: allow to pass alias to array as a pointer (c2v)

- .github/workflows/ci.yml
- .github/workflows/ci_bootstrapping_works.yml
- .github/workflows/ci_cross.yml
- .github/workflows/ci_sanitized.yml
- .github/workflows/ci_v_benchmark.yml
- .github/workflows/containers_ci.yml
- .github/workflows/docs_ci.yml
- .github/workflows/gfx_ci.yml
- .github/workflows/other_ci.yml
- .github/workflows/paths_ci.yml
- .github/workflows/sdl_ci.yml
- .github/workflows/toml_ci.yml
- .github/workflows/v_apps_and_modules_compile.yml
- .github/workflows/vab_ci.yml
- .github/workflows/vinix-kernel.yml
- .github/workflows/websockets.yml
> ci: optimize

- vlib/time/parse_test.v
- vlib/time/time.v
- vlib/time/time_addition_test.v
- vlib/time/time_test.v
- vlib/time/unix.v
#14019 points out a current issue with time. I refactored this function based on http://howardhinnant.github.io/date_algorithms.html#civil_from_days and the issue no longer persists
I ran the tests mentioned in original ticket (and #14052) locally to verify
> time: fix calculate_date_from_offset

- vlib/clipboard/clipboard_darwin.c.v
- vlib/clipboard/clipboard_windows.c.v
- vlib/clipboard/dummy/dummy_clipboard.v
- vlib/clipboard/x11/clipboard.c.v
> Flag Clipboard struct as heap

- vlib/net/ftp/ftp.v
> ftp: document all public methods

- vlib/v/gen/c/struct.v
This PR makes minor cleanup in struct_init().
- Delete comments that are no longer useful.
> cgen: minor cleanup in struct_init()

- vlib/v/checker/fn.v
> checker: allow to pass [N]anyptr as [N]otherptr (c2v fix)

- vlib/builtin/string.v
- vlib/builtin/string_test.v
builtin.string: new fn (s string) is_ascii() bool
please ignore the comment for the commit #59408e1, there is no compiler bug
> builtin.string: new fn (s string) is_ascii() bool

- vlib/v/checker/check_types.v
> checker: allow to use [n]anyptr as [n]otherptr in check_types (c2v fix)

- vlib/v/gen/c/index.v
This PR makes minor optimization in index_of_array/map().
> cgen: minor optimization in index_of_array/map()

- vlib/v/checker/check_types.v
> checker: c2v fixed array fix

- vlib/v/gen/c/auto_str_methods.v
This PR makes minor cleanup in auto_str_methods.v.
> cgen: minor cleanup in auto_str_methods.v

- vlib/net/urllib/urllib.v
- vlib/net/urllib/urllib_test.v
`parse_host` would go until the end of the string instead of index of `]`
add `test_parse` to validate parsing
#14450
> url: fix parse

- vlib/builtin/string_interpolation.v
This PR makes minor cleanup in string_interpolation.v.
> builtin: minor cleanup in string_interpolation.v

- cmd/tools/vwatch.v
- examples/sokol/particles/modules/particle/system.v
- vlib/builtin/prealloc.c.v
- vlib/cli/command.v
- vlib/cli/help.v
- vlib/cli/man.v
- vlib/datatypes/bstree.v
- vlib/datatypes/doubly_linked_list.v
- vlib/datatypes/linked_list.v
- vlib/net/html/dom_test.v
- vlib/os/process_windows.c.v
- vlib/sync/channels.c.v
- vlib/term/ui/input_windows.c.v
- vlib/term/ui/termios_nix.c.v
- vlib/v/ast/types.v
- vlib/v/checker/infix.v
- vlib/v/checker/tests/checker_comparison_between_obj_and_int.out
- vlib/v/checker/tests/checker_comparison_between_obj_and_int.vv
- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/index.v
- vlib/v/gen/c/match.v
- vlib/v/gen/c/utils.v
- vlib/v/gen/js/fn.v
- vlib/v/gen/js/js.v
- vlib/v/pkgconfig/main.v
- vlib/v/tests/generics_assign_reference_generic_struct_test.v
- vlib/v/tests/pointers_multilevel_casts_test.v
This is still WIP because required a lot of change on the compiler side!
After discussing this with Alex, we try to keep this like the unsafe block like Rust (a little bit better!)!
Fixes https://github.com/vlang/v/issues/14295
> ban unsafe check out of the unsafe block when we try to make ptr check like `mut Foo == 0`

- .github/workflows/ci.yml
- .github/workflows/ci_bootstrapping_works.yml
- .github/workflows/ci_cross.yml
- .github/workflows/ci_sanitized.yml
- .github/workflows/ci_v_benchmark.yml
- .github/workflows/containers_ci.yml
- .github/workflows/gen_vc.yml
- .github/workflows/gfx_ci.yml
- .github/workflows/other_ci.yml
- .github/workflows/paths_ci.yml
- .github/workflows/sdl_ci.yml
- .github/workflows/toml_ci.yml
- .github/workflows/v_apps_and_modules_compile.yml
- .github/workflows/vab_ci.yml
- .github/workflows/vinix-kernel.yml
- .github/workflows/websockets.yml
> ci: run on all branches on forks

- .github/workflows/ci.yml
- vlib/builtin/builtin_d_gcboehm.c.v
Huge thanks to @Ekopalypse for testing the library to ensure it works reliably
> builtin: add static GC support on Windows with TCC

- vlib/v/checker/fn.v
This PR makes a minor optimization in fn_call() and method_call().
> checker: minor optimization in fn_call() and method_call()

- vlib/os/filepath.v
Nothing special... just some cleanup in the `filepath.v` file in the `os` module.
> os: minor cleanup on filepath.v

- vlib/net/html/dom.v
- vlib/net/html/parser.v
To prevent output with the `-g` option.
> html: chage to `debug_html`

- cmd/tools/vmissdoc.v
This introduces a way to check for missing documentation (`v missdoc --verify .`) in places like CI (acts like `v fmt -verify`)
(it may not be topical for V right now - but other projects can benefit from it until V has been documented 100%)
> missdoc: add --verify mode

- vlib/v/checker/checker.v
This PR makes cleanup in checker.v.
> checker: cleanup in checker.v

- vlib/orm/orm.v
- vlib/orm/orm_test.v
- vlib/pg/orm.v
- vlib/sqlite/orm.v
This PR adds a bit of documentation to the orm & fixed pg issues (pg is now fully tested and can be replaced in `orm_test.v`)
> orm: document & fix pg

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/cheaders.v
- vlib/v/gen/c/cmain.v
- vlib/v/gen/c/fn.v
> cgen: fix a race condition in the closure implementation

- cmd/tools/modules/scripting/scripting.v
- cmd/tools/modules/testing/common.v
- cmd/tools/repeat.v
- cmd/tools/vfmt.v
- vlib/builtin/builtin.c.v
- vlib/builtin/builtin_d_gcboehm.c.v
- vlib/term/control.v
- vlib/term/term_nix.c.v
- vlib/term/ui/input_nix.c.v
- vlib/term/ui/input_windows.c.v
- vlib/term/ui/termios_nix.c.v
- vlib/term/ui/ui.v
> builtin: use C.fwrite (buffered) for _write_buf_to_fd

- vlib/builtin/js/string.js.v
> builtin/js: fix string.int method

- vlib/v/scanner/scanner.v
This PR makes minor cleanup in scanner.v.
> scanner: minor cleanup in scanner.v

- examples/graphs/bellman-ford.v
- examples/graphs/bfs2.v
- examples/graphs/dfs.v
- examples/graphs/dijkstra.v
- examples/graphs/minimal_spann_tree_prim.v
> examples: some new  graphs algorithms and improving 2 others

- vlib/builtin/array.v
> builtin: fix typo in array.v

- vlib/compress/README.md
- vlib/compress/compress.v
- vlib/compress/deflate/README.md
- vlib/compress/deflate/deflate.v
- vlib/compress/gzip/README.md
- vlib/compress/gzip/gzip.v
- vlib/compress/gzip/gzip_test.v
- vlib/compress/zlib/zlib.v
add compress.gzip
related to #14599 and #14682
> add compress.gzip

- vlib/strings/strings.v
- vlib/strings/strings_test.v
As [discussed from here](https://discord.com/channels/592103645835821068/592294828432424960/983685102187991060) - add a function for splitting a string by it's capital letters.
> strings: add split_capital

- vlib/gg/gg.c.v
This PR will make `gg` fire a (generated) resize event, on Android, if the screen size has changed between application start-up and calling of the init function. On Android it seems the resize events are (sometimes?) not emitted in a flow that matches `gg`'s (or probably `sokol`'s) start-up cycle.
See [the discussion](https://discord.com/channels/592103645835821068/592118040179507207/984091896576110664) for the reason.
I've tested the fix locally with `vab` and [Vasteroids](https://github.com/islonely/vasteroids):
(`vab --archs 'arm64-v8a' --name "VASTEROIDS" --api 30 ~/Projects/vdev/vasteroids`)
Before:
After:
> gg: fire resize event before init if necessary on Android

- vlib/v/ast/table.v
This PR makes cleanup in generic_insts_to_concrete().
> ast: cleanup in generic_insts_to_concrete()

- .github/workflows/ci_cross.yml
- .github/workflows/ci_sanitized.yml
- .github/workflows/containers_ci.yml
- .github/workflows/vab_ci.yml
- .github/workflows/vinix-kernel.yml
- GNUmakefile
- vlib/builtin/builtin_d_gcboehm.c.v
- vlib/v/builder/cc.v
- vlib/v/cflag/cflags.v
- vlib/v/pref/default.v
- vlib/v/pref/pref.v
- vlib/v/tests/valgrind/valgrind_test.v
- vlib/v/vcache/vcache.v
> v: enable `-gc boehm` by default

- vlib/builtin/builtin.c.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/cmain.v
- vlib/v/gen/c/fn.v
- vlib/v/markused/markused.v
- vlib/v/tests/closure_data_with_gc_test.v
> cgen: ensure closures are kept alive when using the GC

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/native/tests/print.vv
- vlib/v/gen/native/tests/print.vv.out
This PR contains code in the `convert_int_to_string()` function for detecting (and handling) zero and negative values, as well as some helper functions.
Int-to-string conversion for any integers other than 0 will follow soon.
> native: int-to-string conversion detecting zeros and negative values

- vlib/v/ast/table.v
- vlib/v/checker/fn.v
- vlib/v/gen/c/cgen.v
This PR perfect sorting globals and consts.
-  Supplement dependencies.
> ast, checker, cgen: perfect sorting globals and consts

- vlib/builtin/array.v
- vlib/builtin/array_d_gcboehm_opt.v
- vlib/v/gen/c/cheaders.v
This PR makes a minor optimization for array push many.
- Reduces the extra call when adding an empty array.
> cgen: minor optimization for array push many

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/native/tests/defer.vv
- vlib/v/gen/native/tests/defer.vv.out
> native: initial support for `defer`

- .github/workflows/ci.yml
- vlib/v/builder/nativebuilder/nativebuilder.v
- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/arm64.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/native/macho.v
- vlib/v/gen/native/macho_test.v
Do not merge yet. Needs testing on intel macs to confirm nothing got broken there by accident during the refactoring.
> native: initial support for apple-m1

- vlib/v/pkgconfig/bin/pkgconfig_test.v
- vlib/v/pkgconfig/main.v
Make Main public for standalone pkgconfig.
> v.pkgconfig: fix building standalone pkgconfig

- .github/workflows/android_cross_compile.vsh
- .github/workflows/vab_ci.yml
- vlib/os/os_android.c.v
Looks like it's [working](https://github.com/vlang/v/runs/7019255497?check_suite_focus=true#step:7:1)
> ci: add pure `-os android` checks

- examples/2048/2048.v
AI key changed for gameplay key.
> examples: fix 2048 gameplay

- examples/tetris/tetris.v
> Remove Empty comment

- vlib/gg/draw.c.v
This PR fix alpha color draw_arc_filled and draw_arc_empty functions.
> gg: fix alpha color draw arc functions

- vlib/v/parser/fn.v
- vlib/v/parser/tests/fn_decl_multi_return_types_err.out
This PR fix typo of the error message.
> parser: fix typo of the error message

- examples/term.ui/event_viewer.v
- examples/term.ui/pong.v
- examples/term.ui/rectangles.v
- examples/term.ui/term_drawing.v
- examples/term.ui/text_editor.v
- examples/term.ui/vyper.v
- vlib/net/html/tag.v
- vlib/picohttpparser/response.v
- vlib/x/ttf/render_bmp.v
This PR fix all the others unsafe 0.
> all: fix all the others unsafe 0

- vlib/net/tcp.v
This PR covers only v programs compiled with `-d net_blocking_sockets` 
In case that C.connect returns not 0 select and other unnecessary nonblocking stuff were called. Also, the connect errors weren't returned
Warning: I'm not a big networking expert, therefore review by a network expert is recommended
Remark: It is a very small change, not as much as the diff shows.
> net: blocking support for connect

- vlib/v/gen/c/cmain.v
This fixes a crash on Android when compiling with `-gc *`.
`GC_INIT()` was never called which resulted in weird behaviour:
```
06-27 16:49:15.006 28096 28096 I SOKOL_APP: NativeActivity onCreate()
06-27 16:49:15.015 28096 28096 I BDWGC   : Grow heap to 64 KiB after 0 bytes allocated
06-27 16:49:15.023 28096 28096 D BDWGC   : GC #1 freed 0 bytes, heap 64 KiB (+ 256 KiB internal)
06-27 16:49:15.023 28096 28096 D BDWGC   : World-stopped marking took 7 ms 395000 ns (7 ms in average)
06-27 16:49:15.023 28096 28096 D BDWGC   : In-use heap: 0% (0 KiB pointers + 0 KiB other)
06-27 16:49:15.024 28096 28096 I BDWGC   : Grow heap to 128 KiB after 17536 bytes allocated
06-27 16:49:15.024 28096 28096 I BDWGC   : Grow heap to 192 KiB after 25920 bytes allocated
06-27 16:49:15.024 28096 28096 I BDWGC …
```
> gen: call GC_INIT in sokol_main when compiling with -apk

- vlib/gg/testdata/draw_simple_polygons.vv
This PR adds a test for draw_polygon_filled function.
> gg: add draw_polygon_filled test

- vlib/v/gen/c/str.v
This PR makes a minor cleanup in str.v.
> cgen: minor cleanup in str.v

- cmd/tools/vcheck-md.v
- vlib/os/os.v
- vlib/os/os_js.js.v
- vlib/os/os_nix.c.v
- vlib/os/os_test.v
- vlib/os/os_windows.c.v
- vlib/v/util/util.v
- vlib/v/vcache/vcache.v
> os: add an optional "mode" parameter to os.mkdir and os.mkdir_all

- ROADMAP.md
I think those entries should be removed
> doc: ROADMAP.md

- vlib/gg/testdata/draw_simple_polygons.vv
This PR updates draw polygon test.
- add to main module.
- add polygon to center. edge controlled by arrow keys.
> gg: update draw polygon test

- vlib/v/parser/assign.v
This PR makes a minor cleanup in partial_assign_stmt().
> parser: minor cleanup in partial_assign_stmt()

- vlib/sync/pool/pool.v
> sync: fix typo in pool.v

- vlib/net/websocket/io.v
- vlib/net/websocket/websocket_client.v
This PR enable user to configure read & write timeout of websocket connection.
> net.websocket: allow timeout to be configured

- cmd/tools/vgret.v
This PR adds a generic screenshot test method to `vgret`.
A current use-case can be [found here](https://github.com/Larpon/c2v/blob/45eaa92181ed57dd9e887338ae4b68aa0f52672a/.github/workflows/doom_gfx_regressions.yml#L78) - it's basically a way to test if the DOOM produced by `c2v` can be executed and captured for the title screen - while generally this would be flaky, we're luckily enough that mr. Carmack and his team has made it so the title screen runs for several seconds before going into kiosk/menu mode, allowing for us to, fairly reliably, test for the presence of the title screen graphics with `v gret` using this [new capture method](https://github.com/Larpon/doom-regression-images/blob/master/vgret.doom.toml).
The PR can be tested locally (given you have all [`vgret` …
> tools: add generic_screenshot method to vgret

- vlib/v/gen/c/fn.v
This PR makes cleanup in fn.v.
> cgen: cleanup in fn.v

- vlib/v/checker/tests/ptr_array_init.out
- vlib/v/checker/tests/shared_element_lock.out
- vlib/v/eval/expr.v
- vlib/v/gen/golang/golang.v
- vlib/v/gen/js/js.v
- vlib/v/preludes/test_runner_normal.v
This PR fix the latest ci errors.
> all: fix the latest ci errors

- vlib/mysql/orm.v
- vlib/orm/orm.v
- vlib/pg/orm.v
- vlib/v/ast/ast.v
- vlib/v/ast/table.v
- vlib/v/ast/types.v
- vlib/v/ast/types_test.v
- vlib/v/checker/check_types.v
- vlib/v/checker/checker.v
- vlib/v/checker/comptime.v
- vlib/v/checker/fn.v
- vlib/v/checker/for.v
- vlib/v/eval/expr.v
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/c/index.v
- vlib/v/gen/c/str_intp.v
- vlib/v/gen/js/auto_str_methods.v
- vlib/v/gen/js/js.v
- vlib/v/parser/parse_type.v
It is confusing that `byte_type` refers to `u8`
> all: v.ast.byte_type -> v.ast.u8_type

- vlib/v/ast/ast.v
- vlib/v/ast/table.v
- vlib/v/ast/types.v
- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/parser/parser.v
- vlib/v/parser/struct.v
> checkr,ast: cleanup code about deprecated

- examples/graphs/dijkstra.v
- examples/graphs/minimal_spann_tree_prim.v
This PR removes empty comments.
> examples: remove empty comments

- vlib/v/gen/c/cgen.v
- vlib/v/tests/return_comptime_call.v
> Fixes: #14962 cgen: Lost return at ExprReturn.exprs[0] is ComptimeCall.

- vlib/v/tests/interface_struct_test.v
This PR restore test_interface_struct_from_mut_array() in interface_struct_test.v.
> tests: restore test_interface_struct_from_mut_array() in interface_struct_test.v

- vlib/v/parser/parse_type.v
This PR makes minor cleanup in parse_type.v.
> parser: minor cleanup in parse_type.v

- vlib/v/tests/interfaces_map_test.v
This PR restore interfaces_map_test in tests.
> tests: restore interfaces_map_test

- ROADMAP.md
[See this](https://github.com/vlang/v/pull/15020#issuecomment-1180066652)
> doc: roadmap

- vlib/encoding/csv/reader_test.v
- vlib/encoding/csv/to_struct_arr.v
> add csv to struct test

- vlib/v/checker/tests/array_sort_with_compare_ref_elem_err.out
- vlib/v/checker/tests/fn_arg_of_optional_err.out
- vlib/v/checker/tests/private_redeclaration_of_C_struct.out
- vlib/v/parser/fn.v
This PR fix fn argument type position.
- Fix fn argument type position.
- Modify related tests.
> parser: fix fn argument type position

- vlib/v/gen/native/gen.v
Adds type checking to `gen_var_to_string()` with new easy to use function `get_type_from_var()`
> native: add typechecking to gen_var_to_string()

- vlib/v/gen/c/cgen.v
This PR clean up ident() in cgen.v.
> cgen: clean up ident() in cgen.v

- doc/docs.md
> doc: backlight fix

- vlib/v/gen/c/cgen.v
This PR makes minor cleanup in global_decl().
> cgen: minor cleanup in global_decl()

- doc/docs.md
I added this because there was no example of how to execute multiple functions with `go`.
> doc: add a go example

- vlib/v/parser/expr.v
- vlib/v/parser/fn.v
- vlib/v/parser/parser.v
> parser: cleanup orblock duplicate code

- doc/vscode.md
> vscode.md: fix typos/spelling

- vlib/v/gen/c/auto_str_methods.v
- vlib/v/tests/inout/printing_struct_with_skip_fields.vv
This PR optimize auto_str_methods of [str:skip] fields.
> cgen: optimize auto_str_methods of [str:skip] fields

- vlib/os/README.md
- vlib/os/os.c.v
As mentioned in #10268 a few os functions may allow a `TOCTOU` vulnerability if used incorrectly. This pull request gives a short explanation and a way to work around it. 
Each affected function has an additional warning in the description.
\>>>
* * *
A few `os` module functions can lead to the <b>TOCTOU</b> vulnerability if used incorrectly. 
<b>TOCTOU</b> (Time-of-Check-to-Time-of-Use problem) can occur when a file, folder or similar 
is checked for certain specifications (e.g. read, write permissions) and a change is made 
afterwards. 
In the time between the initial check and the edit, an attacker can then cause damage. 
The following example shows an attack strategy on the left and an improved variant on the right 
so that <b>TOCTOU</b> is no longer possible.
<b>Example</b> …
> os/security: Security advisory for TOCTOU vulnerabilities

- vlib/sync/stdatomic/atomic.c.v
- vlib/sync/stdatomic/atomic_test.v
add/sub result of atomic operation
> stdatomic: add/sub result of op

- vlib/v/pkgconfig/pkgconfig.v
> pkgconfig: add default path for Debian 32bit

- CHANGELOG.md
CHANGELOG.md: fix for a small typo (paramter -> parameter)
> CHANGELOG.md: fix for a small typo (paramter -> parameter)

- vlib/os/file.c.v
- vlib/os/file_test.v
- vlib/os/os_test.v
Add reopen() and eof() methods to File.
> os: add File.reopen and File.eof methods

- vlib/picoev/picoev.v
This PR restore struct Picoev definition.
> picoev: restore struct Picoev definition

- thirdparty/zip/miniz.h
- thirdparty/zip/zip.c
Update zip to [version 0.2.4](https://github.com/kuba--/zip/releases/tag/v0.2.4), which includes bug fixes.
> szip: update zip to version 0.2.4

- vlib/v/gen/native/elf.v
This PR contains the implementation of the remaining elf section types for native.
> native: implement elf section types

- .gitignore
So that I (and others) don't push them accidentally
> gitignore: ignore valgrind `vgcore.*` debug files

- vlib/log/log_test.v
Hi all,
in this PR you can find a little cleanup and update of the log test source (due to some good recent changes in related log library).
Hope it's good.
Thanks. Bye
> log: cleanup tests

- vlib/v/checker/struct.v
This PR makes minor cleanup in struct_decl().
> checker: minor cleanup in struct_decl()

- vlib/v/checker/if.v
> checker: cleanup in if_expr()

- vlib/orm/README.md
orm: add documentation for the ``nonull`` attribute
> Add 'nonull' attribute description

- vlib/v/README.md
> docs: update v/README.md

- vlib/v/gen/c/json.v
- vlib/v/tests/json_serialisation_of_fixed_arrays_test.v
json : adding array_fixed encode/decode to c backend
> json: fix array_fixed encode/decode

- vlib/rand/rand.v
- vlib/v/checker/check_types.v
This PR simplify infer_fn_generic_types().
> checker: simplify infer_fn_generic_types()

- vlib/v/checker/checker.v
- vlib/v/checker/tests/fn_selector_expr_err.out
- vlib/v/checker/tests/fn_selector_expr_err.vv
Fixes https://github.com/vlang/v/issues/15416
> checker: add error for fn used as selector_expr

- vlib/v/gen/c/auto_str_methods.v
- vlib/v/tests/array_to_string_test.v
- vlib/v/tests/fn_with_array_of_aliases_argument_test.v
- vlib/v/tests/multiple_matchs_in_one_expr_test.v
- vlib/v/tests/repl/import_alias.repl
Fixes https://github.com/vlang/v/issues/14750 and discussion about it in https://github.com/vlang/v/issues/14750#issuecomment-1215293816
> cgen: string representation u8 arrays the standard way

- vlib/v/gen/c/auto_eq_methods.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/utils.v
This PR add `fn_var_signature(info ast.FnType, var_name string) string`.
> cgen: extract a common `fn_var_signature(info ast.FnType, var_name string) string` method

- cmd/tools/vdoc/utils.v
This PR adds support for:
- syntax highlighting for types `usize`, `isize` and `u8`
- fix highlighting for variables which were placed between comments and types
- syntax highlighting for embedded structs and interfaces
- More fixes and features coming when I can find about it
> `v doc`: add highlighting for new types and fix highlighting for edge cases

- vlib/v/checker/fn.v
- vlib/v/checker/tests/test_functions_wrong_signature_test.out
This PR improve error message for test function definition.
> checker: improve error message for test function definition

- cmd/tools/vpm.v
Allows vpm modules with git submodules to work properly
> vpm: Make `v install` also clone submodules (when source is git)

- vlib/toml/any.v
- vlib/toml/tests/reflect_test.v
This PR is ~~a~~ partial ~~fix~~ support for https://github.com/vlang/v/issues/15245
(The mapping of full TOML docs to several V struct types will only be possible when V's compile time reflection is more mature.)
> toml: support [toml: '...'] attributes

- vlib/json/json_test.v
This PR makes a minor cleanup in json_test.v.
> json: minor cleanup in json_test.v

- vlib/net/smtp/smtp.v
- vlib/net/smtp/smtp_test.v
It is not easy to add test to it :)
> smtp: send mail to multiple recipients. #15508

- vlib/datatypes/set.v
- vlib/datatypes/set_test.v
> datatypes/set: use generic operator overloading for `difference` and `equal` plus deprecate them; remove un-needed `mut` in method declaration

- vlib/v/checker/check_types.v
- vlib/v/checker/tests/array_sort_with_compare_err.out
- vlib/v/checker/tests/fn_args.out
- vlib/v/checker/tests/non_matching_functional_args.out
- vlib/v/checker/tests/struct_field_type_err.out
This PR improve error message of fn args mismatch.
> checker: improve error message of fn args mismatch

- README.md
@JalonSolov I hope you agree that this more correct 😅
(All languages can be learned in over a weekend if you decide to learn everything slow enough?! 😄)
> docs: "in over a" -> "in a"

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/tests/sumcall.vv
This PR includes alignment fix and var offset fix.
> native: support fncall with 7↑ arguments

- .cirrus.yml
- .github/workflows/ci.yml
- vlib/v/tests/assembly/asm_test.amd64.v
Let's see if #15287 can be reproduced here.
> ci: run more tests on the FreeBSD Cirrus runner

- doc/docs.md
- vlib/v/checker/checker.v
- vlib/v/parser/comptime.v
- vlib/v/tests/comptime_at_test.v
- vlib/v/token/token.v
add `@FILE_LINE` which is like `@FILE:@LINE` makes it easy to write logs.
> token: add @FILE_LINE

- vlib/v/ast/table.v
This PR makes a minor optimization in sumtype_check_function_variant().
> ast: minor optimization in sumtype_check_function_variant()

- vlib/vweb/csrf/README.md
- vlib/vweb/csrf/create_cookie.v
I added README.md to the vweb.csrf-module. I also corrected some comments in the code due to spelling mistakes.
> vweb.csrf: adding README.md, corrected comments

- vlib/v/checker/fn.v
- vlib/v/checker/tests/array_filter_map_optional_function_err.out
- vlib/v/checker/tests/array_filter_map_optional_function_err.vv
Fixes https://github.com/vlang/v/issues/15514
> checker: add check for optional function used as callback for `.map` and `.filter`

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/native/tests/struct.vv
struct literal, struct field, variable init, default value, struct as call args, and as return value.
struct field must be register-sized for now
> native: initial implementation of struct

- vlib/v/checker/if.v
- vlib/v/eval/expr.v
- vlib/v/tests/match_with_complex_sumtype_exprs_add_print_test.v
This PR fix match with complex sumtype exprs that adding print.
- Fix match with complex sumtype exprs that adding print.
- Add test.
```v
struct Node {
value f64
left  Tree
right Tree
}
type Tree = Empty | Node
// return size(number of nodes) of BST
fn size(tree Tree) int {
return match tree {
Empty { 0 }
Node { 1 + size(tree.left) + size(tree.right) }
}
}
// insert a value to BST
fn insert(tree Tree, x f64) Tree {
return match tree {
Empty {
Node{x, tree, tree}
}
Node {
if x == tree.value {
tree
} else if x < tree.value {
Node{
...tree
left: insert(tree.left, x)
}
} else {
Node{
...tree
right: insert(tree.right, x)
}
}
}
}
}
// whether able to find a value in BST
fn search(tree Tree, x f64) bool {
return match tree {
Empty {
false
}
Node {
if x == tree.value {
true
} …
```
> checker: fix match with complex sumtype exprs that adding print

- doc/docs.md
Updated docs.md to include instructions on upgrading V to latest version.
> docs:Update docs.md to include instructions on upgrading V

- vlib/v/gen/c/fn.v
https://github.com/vlang/v/pull/15744#discussion_r969237649
> cgen: modify the temporary variable name of the previous pr 15744

- vlib/v/gen/c/fn.v
- vlib/v/tests/go_call_fn_return_test.v
Fixes https://github.com/vlang/v/issues/13247
> cgen: make go func with array type work

- vlib/v/gen/c/if.v
This PR makes a minor optimization in if_expr().
> cgen: minor optimization in if_expr()

- doc/docs.md
This PR adds an example of how to use nested maps. Closes #15751
Rendered added content:
> docs: add nested map example. Closes #15751

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/native/tests/method.vv
- vlib/v/gen/native/tests/struct.vv
> native: support method definition and call

- cmd/tools/vrepl.v
This PR simplify and cleanup vrepl.v.
> vrepl: simplify and cleanup vrepl.v

- vlib/v/gen/js/js.v
> js: fix typo in js.v

- vlib/v/checker/checker.v
- vlib/v/checker/tests/optional_fn_err.out
This PR clean up checking optional and result in checker.v.
> checker: clean up checking optional and result in checker.v

- vlib/builtin/builtin_d_gcboehm.c.v
> builtin: fix gc.o compilation on macos

- vlib/v/gen/c/cgen.v
This PR makes a minor cleanup in return_stmt() of cgen.v.
> cgen: minor cleanup in return_stmt()

- vlib/os/file_test.v
- vlib/os/process_test.v
- vlib/szip/szip_test.v
This PR omit testsuite_begin/end() returning optional.
> tests: omit testsuite_begin/end() optional

- cmd/tools/modules/testing/common.v
- doc/docs.md
- examples/call_v_from_c/.gitignore
- examples/call_v_from_c/README.md
- examples/call_v_from_c/test_math.c
- examples/call_v_from_c/test_print.c
- examples/call_v_from_c/v_test_math.v
- examples/call_v_from_c/v_test_print.v
Hello, here is a PR where I propose :
- an improvement of the documentation of section `Calling C from V` based on [this discussion](https://github.com/vlang/v/discussions/15754#discussioncomment-3708994)
- a clarification of the section in the `docs.md` and an example in folder `call_v_from_c`.
> docs: call_v_from_c example

- doc/docs.md
> doc: add links to vlib doc - array and map

- doc/docs.md
- examples/clock/clock.v
- examples/fireworks/fireworks.v
- examples/gg/mandelbrot.v
- examples/sokol/01_cubes/cube.v
- examples/sokol/02_cubes_glsl/cube_glsl.v
- examples/sokol/03_march_tracing_glsl/rt_glsl.v
- examples/sokol/04_multi_shader_glsl/rt_glsl.v
- examples/sokol/05_instancing_glsl/rt_glsl.v
- examples/sokol/06_obj_viewer/show_obj.v
- examples/sokol/fonts.v
- examples/sokol/freetype_raven.v
- examples/ttf_font/example_ttf.v
- examples/viewer/view.v
- vlib/gg/testdata/draw_simple_polygons.vv
- vlib/gg/testdata/remove_image_from_cache.vv
- vlib/v/fmt/tests/attrs_expected.vv
- vlib/v/fmt/tests/attrs_input.vv
- vlib/v/gen/c/cmain.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/skip_unused/gg_code.vv
- vlib/x/ttf/README.md
This PR will remove the need for using `[console]` on Windows apps.
> cgen: remove the need for [console]

- vlib/v/parser/v_parser_test.v
This PR fix error of v_parser_test.v.
> parser: fix error of v_parser_test.v

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/global_keep.vv
Fixes https://github.com/vlang/v/issues/15939
> fmt: keep `volatile` ident  in global decl

- vlib/sqlite/result_code.v
Added a function for convenience with recent change.
> sqlite: add is_error()

- cmd/tools/vpm.v
> vpm: replace `println` with `eprintln` where needed

- vlib/v/ast/ast.v
- vlib/v/checker/assign.v
- vlib/v/checker/tests/invalid_literal_assign_err.out
- vlib/v/checker/tests/invalid_literal_assign_err.vv
Fixes https://github.com/vlang/v/issues/15993
> checker: disallow literals to be on left sign of assignment

- vlib/gx/color.v
> gx: add documentation for Color methods

- vlib/v/ast/types.v
- vlib/v/checker/containers.v
- vlib/v/checker/fn.v
- vlib/v/checker/for.v
- vlib/v/checker/infix.v
- vlib/v/checker/interface.v
- vlib/v/checker/tests/fn_arg_of_optional_err.out
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/if.v
- vlib/v/gen/c/struct.v
This PR clean up optional and result.
> all: clean up optional and result

- cmd/tools/vtest-all.v
- thirdparty/stb_image/stbi.c
- vlib/stbi/stbi.c.v
- vlib/v/tests/bench/bench_stbi_load.v
I haven't been able to reproduce any leaks, but I think this should be here.
> `stbi`: fix memory leaks with GC

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/json.v
- vlib/v/markused/markused.v
This PR remove opt_ok2() (part 1).
> cgen: remove opt_ok2() (part 1)

- vlib/builtin/option.v
This PR remove opt_ok2() (part 2).
> builtin: remove opt_ok2() (part 2)

- vlib/v/checker/struct.v
- vlib/v/checker/tests/struct_non_ptr_field_nil_default_value_err.out
- vlib/v/checker/tests/struct_non_ptr_field_nil_default_value_err.vv
Fixes https://github.com/vlang/v/issues/16053
> checker: disallow nil assignment on non pointer struct fields

- cmd/tools/vls.v
- doc/docs.md
- vlib/builtin/string_test.v
- vlib/toml/tests/crlf_test.v
- vlib/v/ast/type_size_test.v
- vlib/v/checker/checker.v
- vlib/v/fmt/tests/empty_lines_keep.vv
- vlib/v/parser/parser.v
- vlib/v/parser/tests/index_expr_optional_err.out
- vlib/v/parser/tests/index_expr_optional_err.vv
- vlib/v/tests/array_map_or_test.v
- vlib/v/tests/map_init_with_multi_enum_keys_test.v
- vlib/v/tests/nested_map_index_test.v
- vlib/v/tests/string_index_or_test.v
This PR change index expr returning optional to result.
> all: change index expr returning optional to result

- vlib/builtin/utf8.c.v
- vlib/builtin/utf8.v
- vlib/readline/readline_linux.c.v
- vlib/term/utf8.c.v
- vlib/term/utf8.v
- Add Home/End key support for `v repl`
Also, I attempted to handle Ctrl+C properly on Linux, but I didn't know how to handle it. Maybe a custom signal handler is needed?
> vrepl: add support for Home and End keys

- vlib/v/gen/c/match.v
This PR makes minor optimization and cleanup in match_expr_sumtype().
> cgen: minor optimization and cleanup in match_expr_sumtype()

- doc/docs.md
- examples/gg/arcs_and_slices.v
- vlib/v/checker/tests/anon_structs_visibility/amod/amod.v
- vlib/v/fmt/struct.v
- vlib/v/tests/struct_test.v
> v fmt: fix extra space for anon struct

- vlib/v/parser/sql.v
This PR makes a minor optimization in sql_expr() (related #16140).
> parser: minor optimization in sql_expr() (related #16140)

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/comptime.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/native/tests/comptime.vv
- vlib/v/gen/native/tests/comptime.vv.out
This PR includes support for assigning variables with comptime-conditionals and printing them in the native backend.
> native: fix small issues with compile-time conditionals

- doc/docs.md
Add a link to TEMPLATES.md in $tmpl section.
> doc: add link to template.md

- doc/docs.md
Fixed a heading that was a sub-heading of Global Variables.
> doc: fix headings under Grobal Variables

- doc/docs.md
> doc: minor fix

- doc/docs.md
> doc: TOC add missing h3

- vlib/net/tcp.v
See #15449 and https://github.com/Wertzui123/TLSe/blob/main/sslconn.c.v#L70.
> net: add a `net.tcp_socket_from_handle_raw` function

- vlib/v/gen/c/cgen.v
defered -> deferred
defination -> definition
> cgen: fix typo

- vlib/v/checker/infix.v
- vlib/v/checker/tests/unwrapped_result_infix_err.out
- vlib/v/checker/tests/unwrapped_result_infix_err.vv
Fixes https://github.com/vlang/v/issues/16160
> checker: add error for unwrapped result in infix expr

- doc/docs.md
> doc: move goto section under statements

- doc/docs.md
A heading that simply says "Module" is not sufficient to indicate the information the user would want to know, how to create a Module.
> doc: module add heading

- cmd/v/help/install.txt
- cmd/v/help/list.txt
- cmd/v/help/remove.txt
- cmd/v/help/update.txt
- cmd/v/help/vpm.txt
- doc/docs.md
And I suggest renaming `.vmodules` to `.vpackages` in harmony with the definition.
> doc: fix package

- doc/docs.md
~~Attributes are one of the basic features of V language, so it is appropriate to include them in Basics, not Advanced topics.
see https://github.com/vlang/v/blob/master/doc/docs.md#required-fields~~
moved it because want readers to read the Attribute before "Hot Code Reloading", before "Calling C."
> doc: move attributes

- doc/docs.md
> doc: add global variables link

- vlib/v/checker/tests/str_interpol_invalid_err.out
- vlib/v/checker/tests/str_interpol_invalid_err.vv
This PR fix ci errors temporary.
> tests: fix ci errors temporary

- vlib/v/eval/eval.v
- vlib/v/util/errors.v
Based on https://github.com/vlang/v/pull/14972#discussion_r916093903.
> v.util: add `path_styled_for_error_messages/1`

- vlib/v/checker/infix.v
- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/native/tests/float.vv
- vlib/v/tests/sizeof_test.v
> native, checker: cast float_literal to f32 explicitly in code gen

- .gitignore
Making sure Intellij specific files don't get checked in.
> Ignore Intellij items.

- vlib/x/json2/README.md
The documentation of `x.json2` contains an example that is not working. This PR fixes the code.
> Doc: fix a json2 example not working.

- cmd/tools/vcreate.v
- cmd/tools/vcreate_test.v
Small simplification to .gitattributes, some editor/system items for .gitignore.
> init: changes for .gitattributes/.gitignore

- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/checker/match.v
- vlib/v/depgraph/depgraph.v
- vlib/v/fmt/fmt.v
- vlib/v/fmt/struct.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/golang/golang.v
- vlib/v/gen/golang/struct.v
- vlib/v/gen/js/js.v
- vlib/v/parser/parse_type.v
- vlib/v/tests/default_thread_stack_size_test.v
- vlib/v/util/suggestions.v
This PR is a minor cleaning. Batch replace ```[len-1]``` of the array with ```last()```
> all: minor cleaning, replace [len-1] to last()

- doc/docs.md
> doc: improve visibility

- doc/docs.md
> doc: add links to Attributes

- doc/docs.md
> doc: minor improve toc

- doc/docs.md
> doc: add links

- doc/docs.md
> doc: fix match in toc and add ref field link

- doc/docs.md
moved Parameter evaluation order to Functions2 section.
> doc: fix function

- doc/docs.md
moved Struct update syntax to Struct section.
change Trailing struct literal arguments heading to h3.
> doc: fix struct

- tutorials/C2V_translating_simple_programs_and_DOOM/README.md
> Add syntax highlighting to code snippet

- vlib/builtin/builtin_windows.c.v
- vlib/crypto/md5/md5.v
- vlib/crypto/sha1/sha1.v
- vlib/crypto/sha1/sha1block_generic.v
- vlib/crypto/sha256/sha256.v
- vlib/os/const_windows.c.v
- vlib/rand/constants/constants.v
- vlib/regex/regex.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/const_int_overflow_err.out
- vlib/v/checker/tests/const_int_overflow_err.vv
- vlib/v/gen/native/macho.v
Fixes https://github.com/vlang/v/issues/16327
> checker: check int overflow for const vars

- vlib/v/pkgconfig/pkgconfig.v
> v.pkgconfig: fix infinite recursion bug when parsing dependencies

- vlib/v/parser/comptime.v
This PR make minor cleanups in comptime.v.
> parser: minor cleanup in comptime.v

- vlib/v/gen/c/embed.v
- vlib/v/gen/c/testdata/embed_with_prod.c.must_have
- vlib/v/gen/c/testdata/embed_with_prod_and_several_decoders.c.must_have
- vlib/v/gen/c/testdata/embed_with_prod_zlib.c.must_have
> cgen: fix #16326 -cstrict with $embed_file

- vlib/v/checker/checker.v
- vlib/v/checker/tests/nested_fn_alias_err.out
- vlib/v/checker/tests/nested_fn_alias_err.vv
Fixes https://github.com/vlang/v/issues/16336
> checker: add check for nested fn aliases

- examples/vweb/vweb_assets/index.html
- vlib/net/html/parser_test.v
- vlib/v/checker/tests/str_interpol_invalid_err.out
- vlib/v/checker/tests/str_interpol_invalid_err.vv
- vlib/v/eval/gen/infix_gen.v
- vlib/v/scanner/scanner.v
- vlib/v/tests/string_interpolation_inner_cbr_test.v
Rollback:
PR#16345 PR#16325 PR#16319 PR#16309 PR#16258 PR#16242
> all: rollback to old interpolation (step 2)

- cmd/tools/vtest-self.v
- vlib/sqlite/sqlite.v
- vlib/sqlite/sqlite_vfs_lowlevel_test.v
- vlib/sqlite/vfs_lowlevel.v
docs: https://www.sqlite.org/vfs.html
It opens ability to do interesting things in v. google: "sqlite vfs based"
> sqlite: exposes SQLite OS Interface "VFS"

- vlib/v/checker/checker.v
- vlib/v/checker/tests/type_alias_struct_generic_unknown_name_err.out
- vlib/v/checker/tests/type_alias_struct_generic_unknown_name_err.vv
Fixes https://github.com/vlang/v/issues/16232
> checker: add check for unknown generic types in type alias decl

- cmd/tools/gen_vc.v
- cmd/tools/modules/vgit/vgit.v
- cmd/tools/repeat.v
- cmd/tools/vbug.v
- cmd/tools/vdoctor.v
- cmd/tools/vpm.v
- vlib/builtin/array_test.v
- vlib/builtin/js/array_test.js.v
- vlib/builtin/string_interpolation.v
- vlib/builtin/string_test.v
- vlib/net/http/request_test.v
- vlib/os/font/font.v
- vlib/strings/strings_test.v
- vlib/v/checker/tests/str_interpol_invalid_err.out
- vlib/v/checker/tests/str_interpol_invalid_err.vv
- vlib/v/eval/gen/infix_gen.v
- vlib/v/fmt/fmt.v
- vlib/v/gen/c/assign.v
- vlib/v/gen/c/str.v
- vlib/v/gen/c/str_intp.v
- vlib/v/gen/js/auto_str_methods.v
- vlib/v/gen/js/fn.v
- vlib/v/gen/js/js.v
- vlib/v/gen/js/sourcemap/basic_test.v
- vlib/v/scanner/scanner.v
- vlib/v/tests/string_interpolation_inner_cbr_test.v
- vlib/v/token/pos.v
It is estimated that there are 4 steps in total, and this is the third step. :)
> all: rollback to old interpolation (step 3)

- vlib/v/ast/types.v
- vlib/v/checker/str.v
- vlib/v/gen/c/auto_str_methods.v
This PR makes minor cleanup of optional and result.
> all: minor cleanup of optional and result

- vlib/v/gen/c/auto_eq_methods.v
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/cheaders.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/for.v
- vlib/v/gen/c/sql.v
- vlib/v/gen/c/struct.v
done.  this is the last step.   :)
> all: rollback to old interpolation (step 4)

- vlib/builtin/float.c.v
- vlib/builtin/float_test.v
This PR fix f32.str().
- Fix f32.str().
- Add test.
errors in vui:
```v
PS D:\Vlang\ui\examples> v run switch.v
UI: using the default UI style, since the .toml file `C:\Users\yuyi9\.vui\styles\style_default.toml` was invalid. TOML parse error: toml.checker.Checker.check_number numbers like "0." (float) can not end with `.` in ...radius = 0.\nbg_color...
UI: using the default UI style, since the .toml file `C:\Users\yuyi9\.vui\styles\style_red.toml` was invalid. TOML parse error: toml.checker.Checker.check_number numbers like "0." (float) can not end with `.` in ...radius = 0.\nbg_color...
UI: using the default UI style, since the .toml file `C:\Users\yuyi9\.vui\styles\style_blue.toml` was invalid. TOML parse error: toml.checker.Checker.check_number numbers like "0." (float) can not end …
```
> builtin: fix f32.str()

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/live.v
- vlib/v/live/common.v
- vlib/v/live/executable/reloader.v
- vlib/v/live/live_test.v
- vlib/v/live/live_test_template.vv
Modify live_test.v to test a project with a module, not just a single top .v file with [live] tags.
> v.live, cgen: enable using [live] in modules too (monitor used .v files for changes, not just the top level one)

- doc/docs.md
The table of contents became longer and less readable, so divided into two rows.
> doc: TOC split into two rows

- doc/docs.md
> doc: improve types order

- vlib/vweb/tests/vweb_test.v
- vlib/vweb/tests/vweb_test_server.v
This PR change optional to result in vweb_test.
> vweb: change optional to result in vweb_test

- vlib/v/checker/fn.v
This PR makes minor cleanup and optimization in method_call().
> checker: minor cleanup and optimization in method_call()

- vlib/v/checker/struct.v
- vlib/v/checker/tests/struct_none_field_type_err.out
- vlib/v/checker/tests/struct_none_field_type_err.vv
Fixes https://github.com/vlang/v/issues/16408
> checker: disallow `none` type in struct fields

- vlib/toml/parser/parser.v
> toml: fix typo in parser.v

- doc/docs.md
Minor changes to unchecked text regarding use of ${} in strings.
> doc: minor update for string interpolation

- vlib/v/checker/assign.v
- vlib/v/checker/return.v
- vlib/v/checker/tests/assing_none.out
- vlib/v/checker/tests/unsafe_assign_none_err.out
- vlib/v/checker/tests/unsafe_assign_none_err.vv
- vlib/v/checker/tests/unsafe_none_return_err.out
- vlib/v/checker/tests/unsafe_none_return_err.vv
Fixes https://github.com/vlang/v/issues/16407
> checker: disallow `unsafe { none }` at many places

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/builtins.v
- vlib/v/gen/native/gen.v
As the title says, this is just a small refactoring to remove some sources for errors.
> native: use enum values instead of strings for identifying builtin algorithms

- vlib/v/gen/c/match.v
This PR clean up and improve need_tmp_var_in_match().
> cgen: clean and improve need_tmp_var_in_match()

- vlib/v/checker/checker.v
- vlib/v/checker/tests/import_sym_builtin_override_err.out
- vlib/v/checker/tests/import_sym_builtin_override_err.vv
Fixes https://github.com/vlang/v/issues/16395
> checker: disable overriding and importing of builtin sym types

- vlib/v/tests/valgrind/import_x_json2.v
- vlib/x/json2/decoder.v
- vlib/x/json2/encoder.v
- vlib/x/json2/encoder_test.v
- vlib/x/json2/json2.v
- vlib/x/json2/json2_test.v
> x.json2: generic-based encoder (finish PR#15137)

- vlib/term/colors.v
Adds slow blink and rapid blink
> term: add missing styles

- vlib/v/builder/builder.v
- vlib/v/builder/msvc_windows.v
- vlib/v/checker/assign.v
- vlib/v/checker/orm.v
- vlib/v/checker/struct.v
- vlib/v/checker/tests/negative_assign_to_unsigned.out
- vlib/v/checker/tests/orm_no_default_value.out
- vlib/v/checker/tests/orm_not_a_struct.out
- vlib/v/checker/tests/struct_field_unsign_type_check_err.out
- vlib/v/gen/js/fn.v
- vlib/v/parser/struct.v
Additional review comments of PR #16458:
https://github.com/vlang/v/pull/16458#discussion_r1026150663
:)
> all: correct the first letter of error message from uppercase to lowercase

- doc/docs.md
> doc: return none instead of error in an example

- vlib/v/checker/checker.v
- vlib/v/checker/tests/optional_fields_addr_err.out
- vlib/v/checker/tests/optional_fields_addr_err.vv
Fixes https://github.com/vlang/v/issues/15549
> checker: disallow taking address of optional fields

- .github/ISSUE_TEMPLATE/config.yml
> Add discord link to config.yml

- vlib/strconv/atof.c.v
- vlib/strconv/converter_test.v
It works in my testing, but may need additional tests too.
Please do not merge for now.
> strconv: fix `float_prec := 1.9999999999999999 + 0.0000000000000000005` being 0.5 (fix #16448)

- vlib/v/tests/sumtype_with_alias_fntype_fn_call_test.v
This PR add new test for #16519.
> tests: add new test for #16519

- vlib/datatypes/bstree.v
- vlib/datatypes/doubly_linked_list.v
- vlib/datatypes/doubly_linked_list_test.v
- vlib/datatypes/heap.v
- vlib/datatypes/heap_test.v
- vlib/datatypes/linked_list.v
- vlib/datatypes/linked_list_test.v
- vlib/datatypes/queue.v
- vlib/datatypes/queue_test.v
- vlib/datatypes/ringbuffer.v
- vlib/datatypes/set.v
- vlib/datatypes/stack.v
- vlib/datatypes/stack_test.v
This PR change optional to result in datatypes module.
> datatypes: change optional to result

- vlib/v/checker/tests/for_loop_range_inclusive_err.out
- vlib/v/checker/tests/for_loop_range_inclusive_err.vv
- vlib/v/parser/for.v
Fixes https://github.com/vlang/v/issues/16541
> parser: add a better error msg for `for a in 1...10{}`

- doc/docs.md
- Add a pacman command for adding a MingW toolchain on Arch Linux
> docs: Add Arch command for MingW

- README.md
> docs: remove Android from the common installation section header, as it has its own section

- vlib/v/builder/cc.v
- vlib/v/builder/cc_windows.v
> builder: fix v builder error

- cmd/tools/vcomplete_test.v
This PR adds tests for the `vcomplete` tool.
It *should* pass when #16586 is merged... :crossed_fingers: (I only tested `bash` locally)
> tools: add tests for vcomplete

- vlib/mysql/orm.v
- vlib/orm/orm.v
- vlib/orm/orm_fn_test.v
- vlib/pg/orm.v
- vlib/sqlite/orm.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/reserved_type_name_const_err.out
- vlib/v/checker/tests/reserved_type_name_const_err.vv
FIxes https://github.com/vlang/v/issues/16582
> checker: disallow reserve type name for const

- vlib/v/checker/checker.v
- vlib/v/checker/tests/check_wrong_usage_of_break_and_continue.out
- vlib/v/checker/tests/check_wrong_usage_of_break_and_continue.vv
- vlib/v/tests/comptime_for_break_test.v
> checker: fix break/continue checking within a loop

- vlib/v/checker/checker.v
- vlib/v/checker/containers.v
- vlib/v/checker/fn.v
- vlib/v/checker/interface.v
- vlib/v/checker/struct.v
- vlib/v/checker/tests/array_of_generic_struct_init_err.out
- vlib/v/checker/tests/generic_interface_missing_type_names_err.out
- vlib/v/checker/tests/generic_sumtype_decl_err_a.out
- vlib/v/checker/tests/generic_sumtype_decl_err_b.out
- vlib/v/checker/tests/generics_fn_arg_type_err.out
- vlib/v/checker/tests/generics_fn_return_generic_struct_err.out
- vlib/v/checker/tests/generics_interface_declaration_err.out
- vlib/v/checker/tests/generics_method_receiver_type_err.out
- vlib/v/checker/tests/generics_struct_declaration_err.out
- vlib/v/checker/tests/map_of_generic_struct_init_err.out
This PR improve error messages of missing generic type names.
> checker: improve error messages of missing generic type names

- doc/docs.md
Also correct the generics-related comments in the source code.
> fix document generic typo.

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/native/tests/multi_assign.vv
> native: support simple multi return

- .github/ISSUE_TEMPLATE/feature-request.yml
Change Environment field to textarea, and add description.
> github: make Environment field in feature request match bug report

- vlib/x/json2/any_test.v
- vlib/x/json2/decode_struct_test.v
- vlib/x/json2/encode_struct_test.v
- vlib/x/json2/encoder.v
- vlib/x/json2/json2_test.v
- vlib/x/json2/types.v
```v
struct StructType[T] {
mut:
val T
}
struct StructTypeOptional[T] {
mut:
val ?T
}
assert json.encode(StructType[time.Time]{ val: time.now() }) == '{"val":"2022-03-11T19:54:25.000Z}'
assert json.encode(StructTypeOptional[time.Time]{ val: time.now() }) == '{"val":"2022-03-11T19:54:25.000Z"}'
```
> feat: json2 time.Time encode

- vlib/v/transformer/transformer.v
This PR clean up expr_stmt_match_expr() in transformer.v.
> transformer: clean up expr_stmt_match_expr()

- vlib/x/json2/decode_struct_test.v
- vlib/x/json2/encode_struct_test.v
- vlib/x/json2/json2.v
```v
import time
const fixed_time = time.Time{
year: 2022
month: 3
day: 11
hour: 13
minute: 54
second: 25
unix: 1647006865
}
struct StructType[T] {
mut:
val T
}
assert json.decode[StructType[time.Time]]('{"val": "2022-03-11T13:54:25.000Z"}')!.val == fixed_time
assert json.decode[StructType[time.Time]]('{"val": "0000-00-00T00:00:00.000Z"}')!.val == time.Time{}
assert json.decode[StructType[time.Time]]('{"val": "2022-03-11 13:54:25.000"}')!.val == fixed_time
assert json.decode[StructType[time.Time]]('{"val": "0000-00-00 00:00:00.000"}')!.val == time.Time{}
```
> json2: decode time.Time

- vlib/v/gen/c/infix.v
- vlib/v/tests/inout/printing_result_in_infix_expr2.out
- vlib/v/tests/inout/printing_result_in_infix_expr2.vv
> Fix CallExpr with result when PrefixExpr is used in conditional

- make.bat
Tested in both cmd and PowerShell with https://github.com/andy-5/wslgit, and in cmd and PowerShell (by @felipensp) with "Git for Windows".
> make.bat: fix path backslashes to forward slashes for more compatibility, change quoting to be more consistent

- cmd/tools/modules/testing/common.v
- cmd/tools/modules/testing/output_teamcity.v
- cmd/v/help/test.txt
- vlib/v/pref/pref.v
- vlib/v/preludes/test_runner_teamcity.v
To display tests in a convenient way inside the JetBrains IDE. See next video for example:
https://user-images.githubusercontent.com/51853996/207796346-c4fb7acc-8168-4fed-9ba3-070161f69fb4.mov
References:
- https://www.jetbrains.com/help/teamcity/service-messages.html
Fixes https://github.com/i582/vlang-idea/issues/29
> tests: added teamcity runner

- vlib/v/gen/c/cgen.v
- vlib/v/tests/map_key_alias_test.v
Fixes https://github.com/vlang/v/issues/16680
> cgen: add support for alias map keys

- vlib/regex/regex.v
> regex: fix typo in regex.v

- vlib/v/ast/table.v
- vlib/v/checker/fn.v
This PR fix checking generic struct type mismatch.
> ast, checker: fix checking generic struct type mismatch

- vlib/v/ast/types.v
- vlib/v/checker/struct.v
- vlib/v/checker/tests/struct_field_generic_struct_unknown_type_err.out
- vlib/v/checker/tests/struct_field_generic_struct_unknown_type_err.vv
Fixes https://github.com/vlang/v/issues/16672
> checker: add err for unknown generic struct field

- cmd/tools/vdoc/utils.v
Fixes https://github.com/vlang/v/issues/16604
> vdoc.cli: highlight new generics syntax

- vlib/builtin/js/builtin.js.v
> js: use write() on the freestanding backend

- vlib/v/gen/c/cgen.v
Fix #16721
Original issue: #16690
> cgen: fix debug generated code fixing #16690

- cmd/tools/vpm.v
Fixes https://github.com/vlang/v/issues/16384
> vpm: fix installation via --git flag

- examples/graphs/bfs.v
- vlib/v/checker/tests/assign_expr_undefined_err_i.out
- vlib/v/checker/tests/assign_expr_undefined_err_i.vv
- vlib/v/checker/tests/optional_fn_err.out
- vlib/v/checker/tests/optional_fn_err.vv
- vlib/v/parser/containers.v
- vlib/v/parser/tests/array_init_given_len_not_given_err.out
- vlib/v/parser/tests/array_init_given_len_not_given_err.vv
Fixes https://github.com/vlang/v/issues/16728
> parser: disallow array init attr when len attr is not provided

- vlib/net/html/README.md
> net.html: README.MD,  fix typo.

- .github/workflows/v_apps_and_modules_compile.yml
> Fix workflow to run rolfschmidt

- GNUmakefile
Does not hurt to add the option to build with GNU make on OpenBSD. Works fine.
> GNUmakefile: Add OpenBSD

- vlib/os/os.v
This PR makes a minor optimization in os.v.
> vlib: minor optimization in os.v

- vlib/v/gen/c/fn.v
- vlib/v/tests/generics_array_drop_test.v
Fixes https://github.com/vlang/v/issues/16322
> cgen: fix generics array delete

- vlib/v/tests/repl/runner/runner.v
This PR makes a minor cleanup in runner.v.
> repl: minor cleanup in runner.v

- vlib/v/checker/checker.v
- vlib/v/checker/tests/fixed_array_decompose_err.out
- vlib/v/checker/tests/fixed_array_decompose_err.vv
- vlib/v/tests/fixed_array_explicit_decompose_test.v
Closes https://github.com/vlang/v/issues/16139
> checker: add check for implicit fixed array decomp

- vlib/v/checker/comptime.v
- vlib/v/gen/c/comptime.v
- vlib/v/tests/forcomp_alias_type_test.v
> Allow $for in alias type

- vlib/net/websocket/handshake.v
> websocket: simplify and better handle handshake

- vlib/io/writer.v
> typo fix #16839

- cmd/tools/vcomplete.v
> tools: fix typo in vcomplete.v

- vlib/v/ast/ast.v
- vlib/v/checker/struct.v
- vlib/v/checker/tests/struct_update_comptime_err.out
- vlib/v/checker/tests/struct_update_comptime_err.vv
- vlib/v/parser/struct.v
Fixes https://github.com/vlang/v/issues/16787
> checker: disallow using struct update for comptime

- cmd/tools/vtest-self.v
- vlib/v/tests/orm_sub_array_struct_test.v
```v
fn test_orm_relationship() {
mut db := sqlite.connect(':memory:') or { panic(err) }
sql db {
create table Parent
}
mut child := Child{name: 'abc'}
par := Parent{
name: 'test'
children: []
}
sql db {
insert par into Parent
}
mut parent := sql db {
select from Parent where id == 1
}
child.parent_id = parent.id
child.name = 'atum'
sql db {
insert child into Child
}
child.name = 'bacon'
sql db {
insert child into Child
}
assert parent.name == par.name
assert parent.children.len == 0
parent = sql db {
select from Parent where id == 1
}
assert parent.name == par.name
assert parent.children.len == 2
assert parent.children[0].name == "atum"
assert parent.children[1].name ==  "bacon"
mut children := sql db {
select from Child
}
assert children.len == 2
sql db {
drop table Parent
}
children = …
```
> orm: test: relationship

- vlib/v/ast/ast.v
- vlib/v/checker/struct.v
- vlib/v/gen/c/struct.v
- vlib/v/tests/struct_init_with_interface_pointer_and_embed_test.v
Fix https://github.com/vlang/v/issues/16882 .
> checker: fix unset type of a pointer field with default value, when a struct contains an embed (fix #16882)

- vlib/v/checker/for.v
- vlib/v/checker/infix.v
- vlib/v/checker/tests/invalid_multi_return_operations_err.out
- vlib/v/checker/tests/invalid_multi_return_operations_err.vv
Fixes https://github.com/vlang/v/issues/16864
> checker: disallow operations on multi return

- vlib/sync/pool/pool.v
I was compile vab with '-prod' and it was needed  to fix and it is of course warning
> Fix unsafe pointer

- vlib/vweb/README.md
> Update vweb README.md with `v new <name> web`

- vlib/builtin/builtin.v
- vlib/v/checker/comptime.v
- vlib/v/gen/c/comptime.v
- vlib/v/tests/comptime_for_in_fields_FieldData_test.v
Implements https://github.com/vlang/v/issues/16912
> comptime: implement `field.is_enum`

- vlib/v/checker/struct.v
- vlib/v/checker/tests/struct_voidptr_field_no_ptr_struct_value_err.out
- vlib/v/checker/tests/struct_voidptr_field_no_ptr_struct_value_err.vv
Fixes https://github.com/vlang/v/issues/16895 https://github.com/vlang/v/issues/13957
> checker: disallow non ptr struct values to voidptr fields

- vlib/x/json2/encode_struct_test.v
- vlib/x/json2/encoder.v
> json2: refactor/fixes after #16951

- vlib/x/json2/json2.v
- vlib/x/json2/json_module_compatibility_test/json_test.v
- vlib/x/json2/json_module_compatibility_test/json_todo_test.vv
```v
module main
import x.json2 as json
struct Foo{
confirm_url string [json: 'confirmUrl'; required]
}
fn main(){
mut j := '{"confirm_url":"http://foo.com"}'
mut f := json.decode[Foo]( j) or { panic(err) }
dump(f)
j = '{"confirmUrl":"http://foo.com"}'
f = json.decode[Foo]( j) or { panic(err) }
dump(f)
}
```
> fix: #16975

- vlib/v/checker/checker.v
- vlib/v/checker/tests/alias_type_cast_option_result_unhandled_err.out
- vlib/v/checker/tests/alias_type_cast_option_result_unhandled_err.vv
- vlib/v/checker/tests/cast_array_to_number_err.out
- vlib/v/checker/tests/cast_array_to_number_err.vv
Fixes https://github.com/vlang/v/issues/16978
> checker: check option and result handling in type-casted aliases

- vlib/v/gen/c/dumpexpr.v
This PR makes minor cleanup in dump_expr().
> cgen: minor cleanup in dump_expr()

- vlib/os/os.c.v
https://github.com/vlang/v/issues/16985
> os: add hint for mv_by_cp to mv

- vlib/crypto/pem/pem.v
I m sorry I m late, I m not reach when it was added ...
> add .free() to crypto.pem Block

- vlib/crypto/pem/pem.v
- vlib/v/cflag/cflags.v
well I know, I know, this is silly optimization, but I hope at least 1 ns will improve ...
> vlib: v: cflags: micro optimalisation 

- vlib/v/tests/bench/bench_json_vs_json2.v
`MAX_ITERATIONS=90_000 ./v -no-bounds-checking -prod -cc clang-15 crun vlib/v/tests/bench/bench_json_vs_json2.v`
`v run`
`-prod` vs not prod
> feat: bench by type

- vlib/x/json2/encode_struct_test.v
- vlib/x/json2/encoder.v
> json2: encode sumtype
