vlang/v

vlib/v/builder/cc.v, vlib/v/builder/compile.v, vlib/v/builder/msvc.v, vlib/v/pref/pref.v, vlib/v/tests/repl/runner/runner.v
This PR remove panics when cleaning up tmp files after tests.
Problem: the following often happens when runing `v test-self` on Windows.
```vlang
OK    [528/659]  1626.192 ms vlib/v/tests/project_with_c_code_3/main_test.v
FAIL  [529/659]  1827.782 ms vlib/v/tests/project_with_c_code/main_test.v
V panic: Failed to remove "C:\Users\yuyi9\AppData\Local\Temp\v\test_session_24725100\main_test.exe": No such file or directory
v hash: 92bb292
C:/Users/yuyi9/AppData/Local/Temp/v/v2.15830381870341978936.tmp.c:17131: at _v_panic: Backtrace
C:/Users/yuyi9/AppData/Local/Temp/v/v2.15830381870341978936.tmp.c:20685: by v__builder__Builder_cleanup_run_executable_after_exit
C:/Users/yuyi9/AppData/Local/Temp/v/v2.15830381870341978936.tmp.c:20668: by v__builder__Builder_run_compiled_executable_and_exit …
```
=> builder: remove panics when cleaning up tmp files after tests

vlib/v/checker/checker.v, vlib/v/tests/if_smartcast_likely_test.v
Fixes https://github.com/vlang/v/issues/11485
Adds a case to `smartcast_if_conds` and test
=> Checking smart cases in if: fixes `_likely_` / `_unlikely` case from #11485

vlib/v/ast/str.v, vlib/v/fmt/fmt.v, vlib/v/fmt/tests/generics_cascade_types_keep.vv, vlib/v/scanner/scanner.v, vlib/v/tests/generics_test.v
This PR fixes scanning of multi-level generics cases (such as `Foo<Bar<int>>`) whose tails were wrongly understood as shift-right (`>>`).  So before this PR you must add an extra strange space (`Foo<Bar<int> >`) to avoid this scanner issue. 
Fmt for these cases is also fixed.
=> scanner, fmt: fix multi-level generics

vlib/v/checker/checker.v, vlib/v/gen/c/auto_free_methods.v, vlib/v/gen/c/fn.v, vlib/v/tests/autogen_free_test.v
This PR implement automatic generate free().
```vlang
struct Info {
name  string
notes []string
maps  map[int]int
info  SubInfo
}
struct SubInfo {
path  string
files []string
}
fn main() {
info := &Info{}
info.free()
}
```
generated codes:
```vlang
void main__SubInfo_free(main__SubInfo* it) {
string_free(&(it->path));
Array_string_free(&(it->files));
}
void main__Info_free(main__Info* it) {
string_free(&(it->name));
Array_string_free(&(it->notes));
map_free(&(it->maps));
main__SubInfo_free(&(it->info));
}
```
=> checker, cgen: implement automatic generate free()

vlib/v/gen/c/auto_free_methods.v, vlib/v/tests/autogen_free_test.v
This PR add gen_free_for_type_array/map().
```vlang
struct Info {
name  string
notes []string
maps  map[int]int
info  []SubInfo
}
struct SubInfo {
path  string
files []string
}
fn main() {
info := &Info{}
info.free()
}
```
gen codes:
```vlang
void Map_int_int_free(Map_int_int* it) {
map_free(it);
}
void main__SubInfo_free(main__SubInfo* it) {
string_free(&(it->path));
Array_string_free(&(it->files));
}
void Array_main__SubInfo_free(Array_main__SubInfo* it) {
for (int i = 0; i < it->len; i++) {
main__SubInfo_free(&(((main__SubInfo*)it->data)[i]));
}
array_free(it);
}
void main__Info_free(main__Info* it) {
string_free(&(it->name));
Array_string_free(&(it->notes));
Map_int_int_free(&(it->maps));
Array_main__SubInfo_free(&(it->info));
}
```
=> cgen: add gen_free_for_type_array/map()

vlib/builtin/string.v, vlib/v/fmt/fmt.v, vlib/v/scanner/scanner.v, vlib/v/tests/generics_test.v
This PR targets the very hard scanner edge cases (`>>(` etc), e.g. `foo<Baz, Bar<int>>(a)` vs `a, b := Foo{}<Foo{}, bar>>(baz)` (`generic call` vs `shift-right`). Before PR, any of the cases wouldn't work (I believe you could list more `:-)` ).
`foo<Baz, Bar<int>> (a)` - GENERIC CALL
`a, b := foo < bar, bar >> (baz)` - SHIFT-RIGHT
The algorithm seems a bit long, but should not influce the perf because 
1. frequency of such edge cases is pretty low (but they're not trivial!)
2. algorithm is carefully designed
=> scanner: fix ambiguity of two-level generics and shift-right

vlib/v/gen/c/cgen.v, vlib/v/gen/c/comptime.v, vlib/v/parser/tmpl.v, vlib/v/tests/tmpl_test.v
Fixes #11305 
Fixed the code generation for `$tmpl` by prepending the generated string builder statements to the current statement that the operation appears in. It's done the same way that `insert_before_stmt` is implemented.
I also slightly modified `return_stmt` in cgen.v
=> v: fix $tmpl comptime operation only working in return statement

vlib/v/gen/c/cgen.v, vlib/v/tests/high_ascii_const_rune_test.v
This PR fixes clang (with -cstrict) throwing an illegal character error in a character literal when a rune with value above 127 but below 256 is saved into a const - which is technically neither valid ASCII, nor UTF-8. See [this CI run](https://github.com/ChAoSUnItY/v/runs/3645736016) for an example.
=> cgen: fix illegal character encoding with rune consts above 127

vlib/builtin/int.v, vlib/v/ast/types.v, vlib/v/checker/check_types.v, vlib/v/checker/checker.v, vlib/v/gen/c/cgen.v, vlib/v/gen/js/builtin_types.v, vlib/v/gen/js/js.v, vlib/v/parser/parse_type.v
Remove all references to former type `size_t`.
I don't know when this should be merged. It's probably better to keep some time after `size_t` deprecation, which happened on September, the 8th (see #11443).
I keep it as draft for now, and let the maintainers decide when the right time has come.
=> all: remove `size_t`

vlib/v/checker/checker.v, vlib/v/tests/generic_sumtype_method_test.v
This PR fix generic sumtype method (fix #11552).
- Fix generic sumtype method.
- Add test.
```vlang
struct Node<T> {
value T
left  Leaf<T>
right Leaf<T>
}
type Leaf<T> = Empty | Node<T>
// return size(number of nodes) of BST
fn (leaf Leaf<T>) size<T>() int {
return match leaf {
Empty { 0 }
Node<T> { 1 + leaf.left.size() + leaf.right.size() }
}
}
fn main() {
r := Node<int>{
value: 20
left: Empty{}
right: Empty{}
}
tree := Leaf<int>(Node<int>{
value: 10
left: Empty{}
right: r
})
println(tree.size())
assert tree.size() == 2
}
2
```
=> checker: fix generic sumtype method (fix #11552)

vlib/v/gen/c/array.v, vlib/v/gen/c/infix_expr.v, vlib/v/tests/if_expr_with_array_call_test.v
This PR fix if infix expr with array.all/any() (fix #11557).
- Fix if infix expr with array.all/any().
- `map` and `filter` will resolve in another PR.
- Add test.
```vlang
fn main() {
arr := ['']
for i in arr {
if i.len == 0 || i[1..].bytes().all(it.is_letter()) {
println('empty or all char from second is letter!')
assert true
}
}
for i in arr {
if i.len == 0 || i[1..].bytes().any(it.is_letter()) {
println('empty or all char from second is letter!')
assert true
}
}
}
empty or all char from second is letter!
empty or all char from second is letter!
```
=> cgen: fix if infix expr with array.all/any() (fix #11557)

vlib/v/gen/c/cgen.v, vlib/v/tests/init_multiple_branches_test.v
with adding a location to `stmt_path_pos` after some `}` in `if_stmt` in cgen.v .
fixes https://github.com/vlang/v/issues/11564
used the test from the issue
=> Struct init: fix struct init with multiple branches bug, fixes #11564

vlib/v/gen/c/array.v, vlib/v/gen/c/infix_expr.v, vlib/v/tests/if_expr_with_array_call_test.v
This PR fix if expr with array call (fix #11557).
- Fix if expr with array call: `map`, `filter`, `all`, `any`.
- Add test.
```vlang
fn main() {
arr := ['']
for i in arr {
if i.len == 0 || i[1..].bytes().all(it.is_letter()) {
println('empty or all char from second is letter!')
assert true
}
}
for i in arr {
if i.len == 0 || (i[1..].bytes().all(it.is_letter())) {
println('empty or all char from second is letter!')
assert true
}
}
for i in arr {
if i.len == 0 || i[1..].bytes().any(it.is_letter()) {
println('empty or all char from second is letter!')
assert true
}
}
for i in arr {
if i.len == 0 || (i[1..].bytes().any(it.is_letter())) {
println('empty or all char from second is letter!')
assert true
}
}
arr2 := ['abc']
if arr2.len == 1 || arr2[1].bytes().map(it.is_letter())[0] { …
```
=> cgen: fix if expr with array call (fix #11557)

vlib/v/scanner/scanner.v, vlib/v/tests/generics_test.v
This PR,
1. conbines two ifs, thanks to @yuyi98 's work!
2. fixes struct name with `_` and accordingly adds tests
3. adjusts place of second non-generic processing logics (Current place would fail if `s.text == s.pos + 2`)
4. refactors whole part ( the cleanest way I could think about :-) )
=> scanner: cleanup scanning of `>`

vlib/v/gen/c/array.v, vlib/v/tests/array_nested_call_test.v
This PR fix nested array methods call (fix #11944).
- Fix nested array methods call.
- Add test.
```vlang
fn main() {
arr := ['abc', 'def']
all_is_letter := arr.all(it.bytes().all(it.is_letter()))
println(all_is_letter)
assert all_is_letter
}
true
```
=> cgen: fix nested array methods call (fix #11944)

vlib/v/checker/checker.v, vlib/v/checker/tests/invalid_insert_references_test.out, vlib/v/checker/tests/invalid_insert_references_test.vv
fixes detection of insertion of invalid references , example in https://github.com/vlang/v/issues/3600
i experimented until i got to this place and check: please review. it's not general enough. changing `check_types` would be better, but it seems to break a lot of code for me (or maybe it requires a bigger change)
=> checker: fix detection of invalid insertions, fixes #3600.

vlib/v/ast/table.v, vlib/v/tests/anon_fn_with_array_arguments_test.v
An anonymous function with a fixed array parameter generates a c gen error because 
of the creation of a C typedef which contains [ as part of the function name.
=> ast: solves fixed array typedef generation issue

vlib/v/fmt/fmt.v, vlib/v/gen/c/array.v, vlib/v/scanner/scanner.v
This PR further fixes nested lambda so that it's mature enough to be introduced into V's code.
You can feel functional programming's greater power on reducing code lines.
Before in scanner.v:
```V
mut is_generic := true
if s.last_lt >= 0 && s.pos - s.last_lt < 100 {
typs := s.text[s.last_lt + 1..s.pos].split(',').map(it.trim_space().trim_right('>').after(']'))
for typ in typs {
if typ.len == 0 || (!(typ[0].is_capital() && typ[1..].bytes().all(it.is_alnum() || it == `_`)) && typ !in ast.builtin_type_names) {
is_generic = false
break
}
}
} else {
is_generic = false
}
```
After in scanner.v:
```V
is_generic := if s.last_lt >= 0 && s.pos - s.last_lt < 100 {
typs := s.text[s.last_lt + 1..s.pos].split(',').map(it.trim_space().trim_right('>').after(']'))
typs.all(it.len > 0 && …
```
=> cgen, fmt, scanner: fix and use nested lambda in scanner

vlib/gg/gg.c.v, vlib/gg/gg.v
This PR allows the user to set the `swap_interval` of Sokol via `gg.Config` thus allowing users to run rendering at lower fps than the default 60. Higher `swap_interval` values = lower FPS. So as an example `swap_interval = 2` will result in a refresh rate at 30fps.
Also please note that currently the fps can't be changed dynamically at runtime nor can it be set higher than 60fps due to how Sokol implement it currently.
I have visually checked that a few `gg` examples still run at 60fps as default after this change.
=> gg: expose sapp_desc.swap_interval via gg.Config

vlib/toml/ast/ast.v, vlib/toml/ast/types.v, vlib/toml/ast/walker/walker.v, vlib/toml/checker/checker.v, vlib/toml/parser/parser.v, vlib/toml/toml.v
I made a mistake by renaming what is currently the `ast.Node` type, just before PRing the `toml` module.
TOML is a format for storing key/value pairs in "tables" (maps in V terms) and thus `Key/Node` makes much less sense than `Key/Value`. This PR simply renames Node back to Value (as it originally was).
Luckily `ast.Node` is not a prominent user facing type so hopefully this doesn't cause much havok :grimacing:
=> toml: rename ast.Node -> ast.Value

vlib/v/gen/c/array.v, vlib/v/gen/c/infix_expr.v, vlib/v/tests/if_expr_with_nested_array_call_test.v
This PR fix if expr with nested array call (fix #11953).
- Fix if expr with nested array call.
- Add test.
```vlang
fn main() {
arr := ['']
if arr.len == 1 || (arr[1] == '' && arr.all(it[0].is_letter())) {
println('yes')
assert true
}
}
yes
```
```vlang
fn main() {
arr := ['abc']
if (arr.len == 1 && arr.all(it.len > 0 && it.bytes().any(it == `b`))) || arr[1] == '' {
println('yes')
}
}
yes
```
=> cgen: fix if expr with nested array call (fix #11953)

vlib/builtin/string_interpolation.v, vlib/strconv/format_mem.c.v
This PR fix the memory leaks with `-autofree` of the floating point string interpolation functions and increase the elaboration speed for the floats of the 9%.
- Rewritten the functions `format_fl`,`format_es` without memory allocations
- Some minor fixes.
=> Str_int: float memory leak fix

vlib/toml/any.v, vlib/toml/ast/types.v, vlib/toml/checker/checker.v, vlib/toml/input/input.v, vlib/toml/parser/parser.v, vlib/toml/toml.v
A few documentation fixes and corrections for the `toml` module
=> toml: correct documentation

vlib/v/gen/c/array.v, vlib/v/tests/if_expr_with_nested_array_call_test.v
This PR fix if expr with complex nested array calls.
- Fix if expr with complex nested array calls.
- Add test.
```vlang
fn main() {
arr := ['abc']
if arr.len == 0 || arr.all(it.bytes().map(it).filter(it != ` `).any(it == `c`)) {
println('yes')
}
}
```
Generated C codes:
```vlang
Array_string arr = new_array_from_c_array(1, 1, sizeof(string), _MOV((string[1]){_SLIT("abc")}));
bool _t1 = (arr.len == 0);
bool _t2 = true;
if (!_t1) {
Array_string _t2_orig = arr;
int _t2_len = _t2_orig.len;
for (int _t3 = 0; _t3 < _t2_len; ++_t3) {
string it = ((string*) _t2_orig.data)[_t3];
Array_byte _t6 = __new_array(0, 0, sizeof(byte));
Array_byte _t6_orig = string_bytes(it);
int _t6_len = _t6_orig.len;
_t6 = __new_array(0, _t6_len, sizeof(byte));
for (int _t7 = 0; …
```
=> cgen: fix if expr with complex nested array calls

examples/database/orm.v, vlib/orm/orm_test.v, vlib/v/checker/checker.v
This PR fixes the detection of other integer types than int. It was a fault in the checker and is tested in `vlib/orm/orm_test.v`
=> orm: fix other int types

vlib/v/gen/c/cgen.v, vlib/v/tests/map_get_assign_blank_test.v
This PR fix assign map get to blank (fix #11508).
- Fix assign map get to blank.
- Add test.
```vlang
type Abc = string | int
fn main() {
x := map[string]Abc{}
_ := x['nonexisting']
if y := x['nonexisting'] {
println(y)
}
assert true
}
.\tt1.v:5:8: warning: `or {}` block required when indexing a map with sum type value
4 |     x := map[string]Abc{}
5 |     _ := x['nonexisting']
|           ~~~~~~~~~~~~~~~
6 |     if y := x['nonexisting'] {
7 |         println(y)
```
=> cgen: fix assign map get to blank (fix #11508)

vlib/v/gen/c/array.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/infix_expr.v
This PR cleanup stmt_path_pos processing in cgen.
- Add `set_current_pos_as_last_stmt_pos()` instead of `g.stmt_path_pos << g.out.len`.
=> cgen: cleanup stmt_path_pos processing

vlib/builtin/int.v, vlib/builtin/rune.v
This PR moves multiple `byte` methods that were previously located in `rune.v` to `int.v`
=> builtin: move byte methods from rune.v to int.v

.github/workflows/ci.yml
This PR remove vls master branch test and `tree-sitter-v` in ci.yml.
=> ci: remove vls master branch test

vlib/toml/scanner/scanner.v, vlib/toml/tests/burntsushi.toml-test_test.v
Correctly report error in this scenario:
```toml
multi = "first line
second line"
```
=> toml: fix invalid bad-multiline test

vlib/v/checker/checker.v, vlib/v/tests/generics_array_map_with_generic_callback_test.v
This PR fix generic array.map with generic callback fn (fix #11989).
- Fix generic array.map with generic callback fn.
- Add test.
```vlang
fn main() {
mut a := []Sth{}
a = arr_generic<Sth>(buggy_cb)
println(a)
assert a.len == 0
}
fn arr_generic<T>(cb fn (int) T) []T {
return []int{}.map(cb(it))
}
fn buggy_cb(a int) Sth {
return Sth{
a: a
}
}
struct Sth {
a int
b string
}
[]
```
=> checker: fix generic array.map with generic callback fn (fix #11989)

vlib/builtin/string.v, vlib/builtin/string_test.v
This PR adds `byte()` method to string.
There are methods for `u16`, `u32`, &... all other number types already, except for `byte`.
=> builtin: add method `byte()` to string

vlib/toml/ast/types.v, vlib/toml/parser/parser.v, vlib/toml/scanner/scanner.v
This PR will let the scanner return a quoted literal *with* all the quotes.
Details is then added in the parser to ast.Quoted. This is necessary to be able to give better error messages about invalid strings in the checker.
I have a follow-up PR after this one is merged that will pass a few of the invalid tests in the BurntSushi test suite that I'm chasing to get to zero.
=> toml: add quote details to ast.Quoted

vlib/v/gen/c/cgen.v, vlib/v/tests/map_get_assign_blank_test.v
This PR fix generated the error C codes of '_ = map[key]' (fix #11999).
- Fix generated the error C codes of '_ = map[key]'.
- Add test.
```vlang
type Abc = int | string
fn main() {
x := map[string]Abc{}
_ = x['nonexisting']
if y := x['nonexisting'] {
println(y)
}
assert true
}
.\tt1.v:5:7: warning: `or {}` block required when indexing a map with sum type value
4 |     x := map[string]Abc{}
5 |     _ = x['nonexisting']
|          ~~~~~~~~~~~~~~~
6 |     if y := x['nonexisting'] {
7 |         println(y)
```
=> cgen: fix generated the error C codes of '_ = map[key]' (fix #11999)

cmd/tools/vtest-cleancode.v, vlib/builtin/int.v, vlib/v/ast/types.v
This PR fix fmt 'bytestr' to '&byte' (fix #12004).
- Fix fmt 'bytestr' to '&byte'.
- Format `vlib/builtin/int.v`.
- Remove `vlib/builtin/int.v` and `vlib/builtin/string_charptr_byteptr_helpers.v` from vtest-cleancode exceaption list.
=> ast: fix fmt 'bytestr' to '&byte' (fix #12004)

vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/infix_expr.v, vlib/v/tests/fn_mut_args_test.v
This PR fix fn mut args with interface type (fix #12002).
- Fix fn mut args with interface type.
- Add test.
```vlang
struct LinuxFile {
}
interface File {
}
fn b(parent File) {
println(parent)
assert '$parent' == 'File(LinuxFile{})'
}
fn a(mut parent File) {
b(parent)
}
fn main() {
mut file := LinuxFile{}
a(mut file)
}
File(LinuxFile{})
```
=> cgen: fix fn mut args with interface type (fix #12002)

vlib/builtin/int.v, vlib/builtin/int_test.v, vlib/builtin/rune.v, vlib/builtin/rune_test.v
This pull request adds the `byte.repeat()` and `rune.repeat()` methods analogous to the `string.repeat()` method.
Thanks to @spytheman for the main `rune.repeat()` implementation.
Both tests pass on my machine.
(This is my second PR for this because I didn't manage to resolve the merge conflicts in the first one.)
=> builtin: add byte.repeat() and rune.repeat()

.gitattributes, vlib/toml/scanner/scanner.v, vlib/toml/tests/strings_test.v, vlib/toml/tests/testdata/strings_test.toml
This fixes collection of escape characters in literal strings.
Before, escape characters `\` didn't make it through to the actual value in TOML literal strings (`literal = '\\\\\\\'`) - it does now.
Tests included :sunglasses:
=> toml: fix scanner escape collecting in literal strings

vlib/v/fmt/fmt.v, vlib/v/fmt/tests/import_selective_expected.vv, vlib/v/fmt/tests/import_selective_input.vv
On current master, v fmt removes selective imported type used in map like this
input:
```
import x { Xyz }
struct Abc {
x map[Xyz]int
}
```
output:
```
import x
struct Abc {
x map[Xyz]int
}
```
This PR fix this problem.
=> fmt: fix removal of selective imported type used in map

vlib/v/checker/checker.v, vlib/v/checker/tests/index_invalid_call.out, vlib/v/checker/tests/index_invalid_call.vv
fixes #11539 https://github.com/vlang/v/issues/11539
show checker errors instead of getting codegen errors
logic structure was already there, i just had to add the errors
=> checker: show errors for index calls to values which are not functions

vlib/v/gen/c/fn.v, vlib/v/tests/closure_test.v
Fixes #11244
Not sure how else to describe this bug, but it should be fixed now (for other statements as well).
Used examples from issue for one of the tests.
=> cgen: Fix closure code gen with if statement in definition

vlib/net/http/http.v
=> net.http: add deprecated attribute for old un/escape functions

vlib/v/checker/checker.v, vlib/v/checker/tests/mut_receiver_wrong_return_type.out, vlib/v/checker/tests/mut_receiver_wrong_return_type.vv
=> checker: fix return type checking being skipped for mutable method receivers

vlib/os/process_nix.c.v
This trivial PR removes a C compiler (eg: GCC) warning about `pipe` result not being used (-Wunused-result), in C code generated by V.
This is because the related function (Process unix_spawn_process) uses naive `_ = pipe(...)` constructs, that in turn generates
C code that indeed does not use the return value, eg: when compiling in optimized mode.
Here is the typical C warnings generated:
```
cc -o main14.elf main14_v.c -O3 -fno-plt -flto -DNDEBUG -lm
main14_v.c: In function ‘os__Process_unix_spawn_process’:
main14_v.c:14765:3: warning: ignoring return value of ‘pipe’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
14765 |   pipe(&pipeset[0]);
|   ^~~~~~~~~~~~~~~~~
main14_v.c:14766:3: warning: ignoring return value of ‘pipe’ declared with attribute ‘warn_unused_result’ …
```
=> Fix pipe unused result warning

vlib/v/gen/c/auto_eq_methods.v, vlib/v/gen/c/infix_expr.v, vlib/v/tests/interface_equality_test.v
Closes #11495 
Implemented auto generated eq methods for interfaces. It checks if the types are the same, then uses the eq method for that type to compare the rest.
```v
interface IExample {}
struct Example {
id string
}
struct Example2 {
n int
}
fn equals(a IExample, b IExample) bool {
return a == b
}
fn main() {
assert !equals(Example {id: 'a'}, "abc")
assert !equals(Example {id: 'a'}, Example {id: 'b'})
assert equals(Example {id: 'a'}, Example {id: 'a'})
}
```
=> cgen: allow/implement eq operator for interfaces

vlib/v/gen/c/cgen.v
This PR cleanup generated thread wait C codes.
- Remove the extra `return;` at the end of the function.
```vlang
void __v_thread_wait(__v_thread thread) {
u32 stat = WaitForSingleObject(thread, INFINITE);
if (stat != 0) { _v_panic(_SLIT("unable to join thread")); }
CloseHandle(thread);
return;
}
```
=> cgen: cleanup generated thread wait C codes

vlib/v/gen/c/fn.v, vlib/v/tests/create_dll/create_win_dll.v, vlib/v/tests/create_dll/create_win_dll_test.v
This ensures that exported functions with different names have the same calling conventions as their original functions.
This solves the problem of dlls created with the 32bit version of gcc or clang calling DllMain correctly.
I don't know if this is something that also affects Linux and macOS libraries.
=> C: For DLLs, ensure calling convention are the same

vlib/v/gen/c/cgen.v, vlib/v/parser/parse_type.v, vlib/v/tests/go_array_wait_without_go_test.v
This PR fix go array wait without go calls (fix #12009).
- Fix go array wait without go calls.
- Add test.
```vlang
fn main() {
sa := SA{}
sb := SA{}
sa.wait()
sb.wait()
assert true
}
struct SA {
mut:
threads []thread
}
pub fn (self SA) wait() {
self.threads.wait()
}
struct SB {
mut:
threads []thread
}
pub fn (self SB) wait() {
self.threads.wait()
}
```
=> cgen: fix threads array wait without go calls (fix #12009)

vlib/v/gen/c/fn.v, vlib/v/tests/str_reference_struct_test.v
This PR fix error of reference struct str() (fix #11498).
- Fix error of reference struct str().
- Add test.
```vlang
struct Example {
}
fn main() {
c1 := Example{}
println((&c1).str())
assert (&c1).str() == '&Example{}'
c2 := &Example{}
println(c2.str())
assert c2.str() == '&Example{}'
}
&Example{}
&Example{}
```
=> cgen: fix error of reference struct str() (fix #11498)

vlib/v/gen/c/cgen.v, vlib/v/gen/c/cheaders.v
This PR format generated code of shared struct.
before:
```vlang
// V shared types:
struct __shared__Array_int { sync__RwMutex mtx; Array_int val; };
struct __shared_map { sync__RwMutex mtx; map val; };
struct __shared_array { sync__RwMutex mtx; array val; };
```
formated:
```vlang
// V shared types:
struct __shared__Array_int {
sync__RwMutex mtx;
Array_int val;
};
struct __shared_map {
sync__RwMutex mtx;
map val;
};
struct __shared_array {
sync__RwMutex mtx;
array val;
};
```
=> cgen: format generated code of shared struct

vlib/v/gen/c/cgen.v, vlib/v/tests/as_cast_literal.v
Fixes #12056 
```v
interface IExample {}
fn thing(a IExample) bool {
return true
}
fn main() {
assert thing(true)
assert thing(123) // previously c error
assert thing(12.3) // previously c error
}
```
=> cgen: fix expr_as_cast for int/float literals

vlib/v/gen/c/cgen.v, vlib/v/gen/js/js.v
While I was studying cgen, I saw this comment:
> // NB: please keep the type names in the match here in alphabetical order:
and noticed it hadn't been followed...
`v self` still works with this PR.
=> gen: fix alphabetic order of ast statement generation

vlib/v/ast/types.v, vlib/v/ast/types_test.v, vlib/v/checker/check_types.v, vlib/v/checker/checker.v, vlib/v/gen/c/cgen.v, vlib/v/parser/expr.v, vlib/v/parser/fn.v
This PR change 'type.to_ptr()' to 'type.ref()' in ast.
- `to_ptr()` is not appropriate to express it when it's already a pointer.
- This corresponds to `deref()`.
=> ast: change 'type.to_ptr()' to 'type.ref()'

examples/game_of_life/modules/automaton/automaton.v
The line seems to not affect the compilation anymore and the program still runs without it.
=> examples: game of life: remove unused work-around

examples/vweb/vweb_example.v
Now that vweb encodes the object in `Context.json`, the example was JSON encoding a manually JSON-encoded string.
=> examples/vweb: use map instead of string in call to app.json

vlib/builtin/array.v, vlib/builtin/builtin.c.v, vlib/strings/builder.c.v, vlib/v/checker/checker.v, vlib/v/depgraph/depgraph.v, vlib/v/parser/parser.v, vlib/v/scanner/scanner.v, vlib/v/tests/valgrind/strings_builder.v
=> strings,builder: reduce V cgen and parser memory consumption, fix strings.Builder leak

vlib/v/checker/checker.v, vlib/v/tests/comptime_if_expr_threads_test.v
This PR fix comptime if expr of sync.threads (fix #12349).
- Fix comptime if expr of sync.threads.
- Add test.
```vlang
import math { floor, sqrt }
import arrays { sum }
fn async(arr_size int, init_val f64) f64 {
mut val_arr := []f64{}
for _ in 1 .. arr_size {
val_arr << floor((sqrt(init_val) / 2) * 3)
}
return sum(val_arr.map(it / 2)) or { f64(1) }
}
fn main() {
size := 2000_000
println('Async')
mut results := []thread f64{cap: 16}
for num in 0 .. 15 {
results << go async(size, num)
}
waited_results := results.wait()
println(waited_results)
sum_result := sum(waited_results) or { 1 }
println(sum_result)
assert sum_result == 4.7999976e+07
}
Async
[0, 999999.5, 1.999999e+06, 1.999999e+06, 2.9999985e+06, 2.9999985e+06, 2.9999985e+06, 2.9999985e+06, 3.999998e+06, …
```
=> checker: fix comptime if expr of sync.threads (fix #12349)

doc/docs.md
fix a typo in the v lang documentation from `submiting` to `submitting`.
=> doc: fix typo

vlib/v/checker/checker.v, vlib/v/tests/generics_with_nested_generics_method_call_assign_test.v
This PR fix generic fn with assign of nested generic method call (fix #12332).
- Fix generic fn with assign of nested generic method call.
- Add test.
```vlang
struct SSS<T> {
mut:
x T
}
fn (s SSS<T>) inner() T {
return s.x
}
fn (s SSS<T>) outer() string {
ret := s.inner<T>()
println(ret)
return '$ret'
}
fn main() {
s1 := SSS<int>{100}
s1.outer()
assert s1.outer() == '100'
s2 := SSS<string>{'hello'}
s2.outer()
assert s2.outer() == 'hello'
}
100
100
hello
hello
```
=> checker: fix generic fn with assign of nested generic method call (fix #12332)

doc/docs.md
The link was still valid, but no longer up to date.
=> docs: change medvednikov/libsodium to vlang/libsodium

vlib/v/checker/checker.v, vlib/v/tests/comptime_if_is_interface_test.v
This PR fix comptime if T is interface (fix #12279).
- Fix comptime if T is interface.
- Add test.
```vlang
interface Something {
i int
}
struct Some {
i int
}
struct App {
mut:
count u8
}
fn (mut self App) next<T>(input T) string {
$if T is Something {
return 'Something'
} $else $if T is f64 {
return 'f64'
} $else {
panic('${typeof(T.typ).name} is not supported')
}
panic('Unreachable')
}
fn main() {
assert app.next(Something(Some{1})) == 'Something'
assert app.next(1.0) == 'f64'
}
```
=> checker: fix comptime if T is interface (fix #12279)

vlib/v/gen/c/cgen.v, vlib/v/tests/for_in_mut_struct_val_test.v
This PR fix for in mut val of struct (fix #12361).
- Fix for in mut val of struct.
- Add test.
```vlang
mut:
array [][]int
}
fn (s Struct) rows() StructsRowIterator {
return StructsRowIterator{
array: s.array
position: 0
}
}
struct StructsRowIterator {
Struct
mut:
position int
}
fn (mut s StructsRowIterator) next() ?[]int {
if s.position >= s.array.len {
return error('out of range')
}
defer {
s.position++
}
return s.array[s.position]
}
fn main() {
mut s := Struct{
array: [[1, 2, 3], [4, 5, 6]]
}
println(s)
mut si := s.rows()
println(si)
for mut row in si {
println(row)
rets << '$row'
}
assert rets[0] == '[1, 2, 3]'
assert rets[1] == '[4, 5, 6]'
}
Struct{
array: [[1, 2, 3], [4, 5, 6]]
} …
```
=> cgen: fix for in mut val of struct (fix #12361)

vlib/toml/checker/checker.v, vlib/toml/scanner/scanner.v, vlib/toml/tests/crlf_test.v, vlib/toml/tests/types_test.v
I messed something up in #12358 when I tried to collaborate on the PR.
GitHub chose to close the PR when I pushed my changes for some reason.
Conversation about fixes is also in #12358 
Sorry @Ekopalypse - I'm not sure why the PR was closed :man_shrugging: 
This PR closes #12345 and #12346
=> toml: fix hex values starting with a, e or E and comments ending with crlf

vlib/toml/scanner/scanner.v, vlib/toml/tests/types_test.v
This PR will fix a minor return type inconsistency in the `scanner.at()` function so that the return type matches the character look-up family of calls.
This PR closes #12344
=> toml: streamline scanner.at() return type, fixes #12344

vlib/v/checker/checker.v, vlib/v/checker/tests/generics_struct_field_fn_args_err.out, vlib/v/checker/tests/generics_struct_field_fn_args_err.vv
This PR check generic struct field fn args error (fix #12359).
- Check generic struct field fn args error.
- Add test.
```vlang
fn get_int() int {
return 42
}
fn dub_int(i int) int {
return i * 2
}
struct Fun<F> {
mut:
call F
}
type FunZero = fn () int
fn main() {
fun0 := Fun<FunZero>{
call: get_int
}
println(fun0.call())
println(fun0.call(1234))
println(fun0.call(1234, 5678))
fun1 := Fun<fn (int) int>{
call: dub_int
}
println(fun1.call(42))
println(fun1.call())
println(fun1.call(42, 43))
}
.\tt1.v:21:20: error: expected 0 arguments, but got 1
19 |     }
20 |     println(fun0.call())
21 |     println(fun0.call(1234))
|                       ~~~~
22 |     println(fun0.call(1234, 5678))
23 |
.\tt1.v:22:20: error: expected 0 arguments, but got 2
20 | …
```
=> checker: check generic struct field fn args error (fix #12359)

vlib/toml/parser/parser.v, vlib/toml/scanner/scanner.v, vlib/toml/tests/array_of_tables_1_level_test.v, vlib/toml/tests/burntsushi.toml-test_test.v, vlib/toml/tests/table_test.v, vlib/toml/tests/testdata/array_of_tables_1_level_test.out
This PR introduces format parsing - adding the possibility to forward formatting characters from the scanner to the parser.
This is needed to be able to validate the formatting of TOML documents in more detail. Before, formatting characters like:
` `,`\t` and `\n` was ignored completely in the parser - resulting in wrong output values (in a few cases).
=> toml: parse formatting

vlib/v/checker/checker.v, vlib/v/checker/tests/generics_struct_field_fn_args_err.out, vlib/v/checker/tests/generics_struct_field_fn_args_err.vv
This PR check generic struct field fn args type mismatch.
- Check generic struct field fn args type mismatch.
- Add test.
```vlang
fn get_int() int {
return 42
}
fn dub_int(i int) int {
return i * 2
}
struct Fun<F> {
mut:
call F
}
type FunZero = fn () int
fn main() {
fun0 := Fun<FunZero>{
call: get_int
}
println(fun0.call())
println(fun0.call(1234))
println(fun0.call(1234, 5678))
fun1 := Fun<fn (int) int>{
call: dub_int
}
println(fun1.call(42))
println(fun1.call())
println(fun1.call(42, 43))
println(fun1.call(true))
println(fun1.call('text'))
println(fun1.call(22.2))
}
.\tt1.v:21:20: error: expected 0 arguments, but got 1
19 |     }
20 |     println(fun0.call())
21 |     println(fun0.call(1234))
|                       ~~~~
22 |     println(fun0.call(1234, 5678)) …
```
=> checker: check generic struct field fn args type mismatch

vlib/v/gen/c/cgen.v, vlib/v/tests/array_of_threads_wait_test.v
This PR fix array of threads wait (fix #12350).
- Fix array of threads wait.
- Add test.
```vlang
import math { floor, sqrt }
fn async(arr_size int, init_val f64) f64 {
mut val_arr := []f64{}
for _ in 1..arr_size {
val_arr << floor((sqrt(init_val) / 2) * 3)
}
return sum(val_arr.map(it / 2))
}
fn sum(val_arr []f64) f64 {
mut result := f64(0)
for val in val_arr {
result += val
}
return result
}
fn main() {
size := 2000_000
init_val := 123456
println("Async")
mut results := []thread f64{ cap: 16, len: 16 }
for num in 0..15 {
results << go async(size, init_val + num)
}
waited_results := results.wait()
println(waited_results)
println(sum(waited_results))
assert sum(waited_results) == 7.9049960475e+09
}
Async[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
```
=> cgen: fix array of threads wait (fix #12350)

vlib/toml/parser/parser.v, vlib/toml/tests/burntsushi.toml-test_test.v
This PR disallow the following TOML:
```toml
"""long
key""" = 1
```
=> toml: disallow multiline keys

vlib/toml/tests/burntsushi.toml-test_test.v
This PR removes a few previously skipped tests from the list that now is correctly handled after the recent formatting update.
```
array/text-before-array-separator.toml
inline-table/linebreak-4.toml
inline-table/linebreak-3.toml
inline-table/linebreak-1.toml
inline-table/linebreak-2.toml
key/newline.toml
key/without-value-2.toml
```
(... also the `Inline table` parsing tests is now all passing :partying_face: )
=> toml: remove some skipped tests related to recent formatting update

vlib/toml/parser/parser.v, vlib/toml/tests/burntsushi.toml-test_test.v
This PR disallows:
```toml
[ [table]]
```
=> toml: disallow spacing between (array of tables) key syntax

vlib/toml/parser/parser.v, vlib/toml/tests/array_of_tables_1_level_test.v, vlib/toml/tests/array_of_tables_2_level_test.v, vlib/toml/tests/burntsushi.toml-test_test.v, vlib/toml/tests/testdata/array_of_tables_2_level_test.out
This PR fixes parsing of this kind of TOML:
```toml
[[albums]]
name = "Born to Run"
[[albums.songs]]
name = "Jungleland"
[[albums.songs]]
name = "Meeting Across the River"
[[albums]]
name = "Born in the USA"
[[albums.songs]]
name = "Glory Days"
[[albums.songs]]
name = "Dancing in the Dark"
```
The code still needs some love (this can be refactored to look less scary I think) but it gets the job done :slightly_smiling_face:
=> toml: fix parsing array of tables

vlib/toml/parser/parser.v
I think it's reasonable to panic instead of returning an error in these cases (since it should never happen :slightly_smiling_face: )
=> toml: panic if access fails to a key that was checked

vlib/v/ast/table.v, vlib/v/tests/generics_nested_struct_init_test.v
This PR fix generic nested struct init (fix #12400).
- Fix generic nested struct init.
- Add test.
```vlang
struct Foo<T> {
foo T
}
struct Bar<T> {
mut:
foos []Foo<T>
}
fn (mut b Bar<T>) add(v T) {
b.foos << Foo<T>{
foo: v
}
}
fn main() {
mut bar := Bar<string>{}
bar.add('bar')
println(bar)
result := '$bar'
assert result.contains('Bar<string>{')
assert result.contains('foos: [Foo<string>{')
assert result.contains("foo: 'bar'")
}
Bar<string>{
foos: [Foo<string>{
foo: 'bar'
}]
}
```
=> ast: fix generic nested struct init (fix #12400)

vlib/v/checker/checker.v
This PR makes minor cleanup in generic struct_init().
- Avoid unnecessary calls to table.unwrap_generic_type().
- Add comments.
=> checker: cleanup generic struct init

vlib/v/gen/c/cgen.v
This PR avoid generating typedef generic array type.
before:
```vlang
typedef array Array_main__Foo;
typedef map Map_string_int;
typedef array Array_main__Foo_T_string;
...
```
`typedef array Array_main__Foo;` is unnecessary, and in some cases, mistakes can be made.
=> cgen: avoid generating typedef generic array type

vlib/v/gen/c/array.v, vlib/v/tests/for_in_mut_array_index_test.v
This PR fix for in mut val in array.index() (fix #12403).
- Fix for in mut val in array.index().
- Add test.
```vlang
fn main() {
mut arr := [1, 2, 3, 4, 5]
mut rets := []int{}
for mut val in arr {
inx := arr.index(val)
println(inx)
rets << inx
}
assert rets == [0, 1, 2, 3, 4]
}
0
1
2
3
4
```
=> cgen: fix for in mut val in array.index() (fix #12403)

vlib/v/parser/fn.v, vlib/v/parser/parser.v, vlib/v/parser/struct.v, vlib/v/parser/tests/generic_struct_type_decl_err.out, vlib/v/parser/tests/generic_struct_type_decl_err.vv
This PR check generic parameters error of generic struct declaration (fix #12401).
- Check generic parameters error of generic struct declaration.
- Add test.
```vlang
struct GMap<Hashable<K>, V> {
map_ map[int]V
}
fn (t GMap<Hashable<K>, V>) contains(k K) bool {
return true // TODO
}
fn (t GMap<Hashable<K>, V>) set(k K, v V) {
// TODO
}
fn main() {
x := GMap<string, string>{}
x.set("hello", "world")
println(x.contains("hello"))
}
.\tt1.v:1:13: error: generic parameter name needs to be exactly one char
1 | struct GMap<Hashable<K>, V> {
|             ~~~~~~~~
2 |     map_ map[int]V
3 | }
```
=> parser: check generic parameters error of generic struct declaration (fix #12401)

vlib/v/checker/checker.v, vlib/v/gen/c/fn.v, vlib/v/tests/alias_map_keys_test.v
This PR fix alias of map keys() (fix #12389).
- Fix alias of map keys().
- Add test.
```vlang
type Foo = map[string]string
fn main() {
keys_list := Foo({
'foo1': 'bar1'
'foo2': 'bar2'
'foo3': 'bar3'
}).keys()
println(keys_list)
assert keys_list == ['foo1', 'foo2', 'foo3']
}
['foo1', 'foo2', 'foo3']
```
=> checker, cgen: fix alias of map keys() (fix #12389)

vlib/toml/parser/parser.v, vlib/toml/tests/burntsushi.toml-test_test.v
This PR makes the TOML parser check for invalid ways to end a line after values and a few left square bracket cases.
Disallowing data like the following (among other cases):
```toml
first = "Tom" last = "Jerry"
```
=> toml: check for more wrong line ending cases

vlib/v/fmt/fmt.v, vlib/v/fmt/tests/import_selective_expected.vv, vlib/v/fmt/tests/import_selective_input.vv
On current master, v fmt behaves like this
```
┏ zakuro   ~/src/github.com/zakuro9715/v   master
┗━━⮞ cat main.v
import x { Abc }
struct St<T> {}
fn f(v St<Abc>) {
}
┏ zakuro   ~/src/github.com/zakuro9715/v   master
┗━━⮞ v fmt main.v
import x
struct St<T> {}
fn f(v St<Abc>) {
}
```
=> fmt: fix removal of selective imported types used as type parameter

vlib/time/parse.c.v, vlib/time/parse_test.v, vlib/toml/checker/checker.v, vlib/toml/tests/burntsushi.toml-test_test.v
This PR adds better date and time checking for TOML date, time and date-time format strings.
I also had to improve on the `parse_iso8601_date` function to be able to check for subtle out-of-range dates, since the RFC 3339 parsing currently uses the iso8601 parsing for some of it's validation.
=> toml: add date and time checks

vlib/toml/parser/parser.v
Before:
```
OK   [32/189] "/home/user/v/vlib/toml/tests/testdata/burntsushi/toml-test/tests/invalid/integer/double-sign-plus.toml"...
toml.parser.Parser.value value expected .boolean, .quoted, .lsbr, .lcbr or .number got "plus" "+"
```
After:
```
OK   [32/189] "/home/user/v/vlib/toml/tests/testdata/burntsushi/toml-test/tests/invalid/integer/double-sign-plus.toml"...
toml.parser.Parser.value value expected .boolean, .quoted, .lsbr, .lcbr or .number got "plus" "+" in this (excerpt): "...n-plus = ++99\n..."
```
(My plan, btw - is to polish the error excerpts to be more like V's sometime in the future)
=> toml: add excerpt to value parse errors

vlib/toml/parser/parser.v, vlib/toml/tests/burntsushi.toml-test_test.v
... and small [improvement](https://github.com/vlang/v/pull/12435/files#diff-29994a423353664b33cf30db632cc2208f0105ef3c42529ff6eb18316ab52c25R465) that hopefully aids readability
=> toml: check for text after comma in arrays

vlib/toml/parser/parser.v, vlib/toml/tests/burntsushi.toml-test_test.v
This PR disallows reassigning new values to keys that have already been assigned a value, in inline-tables:
```toml
a={b=1, b=2}
```
=> toml: check for single-key reassignment in inline tables

vlib/toml/parser/parser.v, vlib/toml/tests/array_of_tables_array_test.v, vlib/toml/tests/burntsushi.toml-test_test.v, vlib/toml/tests/testdata/array_of_tables_array_test.out
Add support for these kinds of alien constructs:
```toml
[[a]]
[[a.b]]
[a.b.c]
d = "val0"
[[a.b]]
[a.b.c]
d = "val1"
```
With this, a "small but big" goal is achieved - because the parser can now parse *all* the *valid* `.toml` files from the BurntSushi test suite (`valid_exceptions = []string{}`) :partying_face:
=> toml: support complex array-tables-array constructs

cmd/tools/vsymlink.v
previously, if you installed V in path that contained spaces, and ran `.\v.exe symlink`, the generated .bat script would not account for this. i'd have to manually edit said batch script to do so. 
this PR aims to fix this behaviour by adding quotes around the path regardless.
=> symlink: fix batch script if path contains spaces on windows

vlib/v/checker/checker.v, vlib/v/gen/c/cgen.v, vlib/v/tests/for_in_iterator_of_generic_struct_test.v
This PR fix for in iterator of generic struct (fix #12439).
- Fix for in iterator of generic struct.
- Add test.
```vlang
struct Split<T> {
arr  []T
pred fn (T) bool
mut:
idx int
}
fn (mut iter Split<T>) next() ?[]T {
start := iter.idx
for iter.idx < iter.arr.len {
if iter.pred(iter.arr[iter.idx]) {
iter.idx++
return iter.arr[start..iter.idx]
}
iter.idx++
}
return none
}
fn split<T>(arr []T, pred fn (T) bool) Split<T> {
return Split<T>{arr, pred, 0}
}
fn main() {
items := [0, 1, 2, 3, 4, 5, 6, 7, 8]
mut iter := split<int>(items, fn (item int) bool {
return item % 3 == 0
})
iter.next() ?
mut ret_list := [][]int{}
for item in iter {
dump(item)
ret_list << item
}
println(ret_list)
assert ret_list.len == 2
assert ret_list[0] == [1, 2, 3]
assert ret_list[1] == [4, 5, 6]
}
PS D:\Test\v\tt1> v …
```
=> checker, cgen: fix for in iterator of generic struct (fix #12439)

vlib/v/gen/js/fn.v, vlib/v/parser/fn.v
This PR allows to declare methods on JS interfaces, this allows to create high-level wrappers without wrapping interfaces in another V struct. For example: 
```v
pub interface JS.CanvasRenderingContext2D {
setLineDash(JS.Array)
}
pub fn (ctx JS.CanvasRenderingContext2D) set_line_dash(arr []f64) {
tmp := JS.Array.prototype.constructor()
for x in arr {
tmp.push(JS.Number(x))
}
ctx.setLineDash(tmp)
}
```
=> js,parser: Allow declaring methods on JS interfaces for easier FFI

vlib/toml/any.v, vlib/toml/ast/types.v, vlib/toml/parser/parser.v, vlib/toml/tests/burntsushi.toml-test_test.v, vlib/toml/tests/quoted_keys_test.v, vlib/toml/toml.v, vlib/toml/util/util.v
This PR fixes support for TOML's quoted keys - both internally (keys were "dequoted" before: `a."b.c"` became `a.b.c`) and externally (via the user facing `.value('...')` retrieval call).
A few examples:
```toml
"b.c".d = "V"
'c.b'.d = "V"
[a."B.C"]
d = "V"
```
=> toml: support for `[a."b.c"]` quoted keys

vlib/v/gen/c/fn.v, vlib/v/tests/comptime_for_in_field_selector_test.v
This PR fix comptime for in field selector (fix #12440).
- Fix comptime for in field selector.
- Add test.
```vlang
fn print_field_values<T>(s T) {
mut value_list := []string{}
println(s.$(field.name))
value_list << s.$(field.name).str()
}
assert value_list.len == 4
assert value_list[0] == 'Simon'
assert value_list[1] == 'simon1234'
assert value_list[2] == 'simon@gmail.com'
assert value_list[3] == '15'
}
struct Foo {
password string
email    string
age      int
}
fn main() {
bar := Foo{
name: 'Simon'
password: 'simon1234'
email: 'simon@gmail.com'
age: 15
}
print_field_values<Foo>(bar)
}
Simon
simon1234
simon@gmail.com
15
```
=> cgen: fix comptime for in field selector (fix #12440)

vlib/v/checker/checker.v, vlib/v/checker/tests/array_pop_immutable_err.out, vlib/v/checker/tests/array_pop_immutable_err.vv
This PR check array pop immutable (fix #12456).
- Check array pop immutable.
- Add test.
```vlang
fn main() {
a := [1,2,3]
dump(a)
a.pop()
dump(a)
}
.\tt1.v:5:2: error: `a` is immutable, declare it with `mut` to make it mutable
3 |     dump(a)
4 |
5 |     a.pop()
|     ^
6 |     dump(a)
7 | }
```
=> checker: check array pop immutable (fix #12456)

vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/tests/comptime_for_in_field_selector_test.v
This PR fix typeof comptime selector (fix #12461).
- Fix typeof comptime selector.
- Add test.
```vlang
fn print_field_values<T>(s T) {
mut value_list := []string{}
mut value_type_list := []string{}
mut var_value_list := []string{}
println(s.$(field.name))
value_list << s.$(field.name).str()
println(typeof(s.$(field.name)).name)
value_type_list << typeof(s.$(field.name)).name
val := s.$(field.name)
println(val)
var_value_list << val.str()
}
assert value_list.len == 4
assert value_list[0] == 'Simon'
assert value_list[1] == 'simon1234'
assert value_list[2] == 'simon@gmail.com'
assert value_list[3] == '15'
assert value_type_list.len == 4
assert value_type_list[0] == 'string'
assert value_type_list[1] == 'string'
assert value_type_list[2] == 'string'
assert …
```
=> cgen: fix typeof comptime selector (fix #12461)

vlib/v/checker/checker.v, vlib/v/gen/c/cgen.v, vlib/v/tests/if_expression_test.v
noreturn can be used as branch in match expr. But not for if expr.
see also #11126
=> checker: allow noreturn in if expr

vlib/toml/parser/parser.v
As [validated on Discord](https://discord.com/channels/592103645835821068/592320321995014154/909788578240946176) this PR fixes some failing tests on Windows (related to CRLF line endings)
=> toml: fix parsing formatting on Windows with crlf line endings

vlib/toml/toml.v
This PR adds a convenience function for converting the whole `toml.Doc` to `toml.Any` (this is currently not possible with `Doc.value()`)
=> toml: add convenience convertion of Doc to map[string]toml.Any

vlib/v/checker/checker.v, vlib/v/checker/tests/invalid_variable_name_err.out, vlib/v/checker/tests/invalid_variable_name_err.vv
This PR check invalid `map` variable name (fix #12469).
- Check invalid `map` variable name.
- Add test.
```vlang
fn main()
{
map := map[string]string
println("nope" in map)
}
.\tt1.v:3:2: error: invalid use of reserved type `map` as a variable name
1 | fn main()
2 | {
3 |     map := map[string]string
|     ~~~
4 |     println("nope" in map)
5 | }
```
=> checker: check invalid `map` variable name (fix #12469)

vlib/v/gen/c/str_intp.v, vlib/v/tests/comptime_for_in_field_selector_test.v
This PR fix string interliteral of the comptime selector.
- Fix string interliteral of the comptime selector.
- Add test.
```vlang
fn print_field_values<T>(s T) {
mut value_list := []string{}
mut value_type_list := []string{}
mut var_value_list := []string{}
mut var_intp_value_list := []string{}
println(s.$(field.name))
value_list << s.$(field.name).str()
println(typeof(s.$(field.name)).name)
value_type_list << typeof(s.$(field.name)).name
val := s.$(field.name)
println(val)
var_value_list << val.str()
var_intp_value_list << 'field value: $val'
}
assert value_list.len == 4
assert value_list[0] == 'Simon'
assert value_list[1] == 'simon1234'
assert value_list[2] == 'simon@gmail.com'
assert value_list[3] == '15'
assert value_type_list.len == 4
assert …
```
=> cgen: fix string interliteral of the comptime selector

vlib/encoding/utf8/utf8_tables.v, vlib/v/checker/check_types.v, vlib/v/checker/checker.v, vlib/v/checker/tests/fn_call_arg_mismatch.out, vlib/v/checker/tests/fn_call_arg_mismatch.vv
This PR check the argument mismatch of fn call (fix #12442).
- Check the argument mismatch of fn call.
- Add test.
```vlang
fn abc(x []int) {
println(x)
}
fn main() {
a := [1, 2, 3]
go abc(&a)
println('done')
}
.\tt1.v:7:9: error: cannot use `&[]int` as `[]int` in argument 1 to `abc`
6 |     a := [1, 2, 3]
7 |     go abc(&a)
|            ~~
8 |     println('done')
9 | }
```
=> checker: check the argument mismatch of fn call (fix #12442)

vlib/sqlite/sqlite.v, vlib/sqlite/sqlite_test.v
This PRs make sqlite constants to be public. We can share the result codes used on this module within any calling code to check for the same results.
Before:
```v
import sqlite
fn main() ? {
db := sqlite.connect("database.sqlite3") ?
users, code := db.exec("SELECT id, name FROM users")
if code != 101 {
panic("Query failed")
}
}
```
After
```v
import sqlite
fn main() ? {
db := sqlite.connect("database.sqlite3") ?
users, code := db.exec("SELECT id, name FROM users")
if code != sqlite.sqlite_done {
panic("Query failed")
}
}
```
=> sqlite: make constants public

vlib/v/gen/c/auto_free_methods.v, vlib/v/tests/generics_struct_free_test.v
This PR fix generic struct free() (fix #12484).
- Fix generic struct free().
- Add test.
```vlang
struct List<T> {
pub mut:
head &ListNode<T> = 0
}
struct ListNode<T> {
pub mut:
value T
next  &ListNode<T> = 0
}
fn list_new<T>() List<T> {
return List<T>{}
}
fn listnode_new<T>() &ListNode<T> {
return &ListNode<T>{0, 0}
}
fn (mut l List<T>) free() {
println('free list')
}
fn main() {
mut list := list_new<string>()
println(list)
list.free()
}
List<string>{
head: &nil
}
free list
```
=> cgen: fix generic struct free() (fix #12484)

.github/workflows/toml_ci.yml, vlib/toml/tests/burntsushi.toml-test_test.v, vlib/toml/toml.v
This PR adds support for the BurntSushi test json format so we can validate both data structure and value output of the parser.
While it does add a layer of friction and potential new bugs - the tests has already revealed several parser bugs - so I think it's worth the added complexity so far.
As previously the goal is to get the `valid_value_exceptions` to be an empty array.
(So far the parser is doing a reasonable job)
The best way I could think of was to write a separate function that can produce the special json format - and then normalize the json structure of both the burntsushi and our output through a battle-tested external tool (`jq`) and then base the result on comparison of these two normalized outputs.
=> toml: add support for validation of structure and values

vlib/v/checker/checker.v, vlib/v/checker/tests/struct_field_with_any_type_err.out, vlib/v/checker/tests/struct_field_with_any_type_err.vv
This PR check struct field using 'any' type (fix #6096).
- Check struct field using 'any' type.
- Add test.
```vlang
struct My_type {
fld any
}
fn main() {
a := My_type{}
println(a)
}
.\tt1.v:2:6: error: struct field cannot be the `any` type, use generics instead
1 | struct My_type {
2 |     fld any
|         ~~~
3 | }
4 |
```
=> checker: check struct field using 'any' type (fix #6096)

vlib/toml/scanner/scanner.v, vlib/toml/tests/strings_test.v, vlib/v/checker/checker.v
This PR fixes a small bug in `scanner` where `\uXXXX` sequences caused the scanner to be left one character behind after the parsing of the sequence.
=> toml: fix scanning of short unicode escapes

vlib/toml/tests/burntsushi.toml-test_test.v, vlib/toml/toml.v, vlib/v/checker/checker.v
This PR will move the BurntSushi related functionality out of userland into testland :small_airplane: 
(I didn't succeed in making it part of the `toml` module via a `_test.v` file with `module toml` at the top :man_shrugging: )
=> toml: move to_burntsushi functionality

vlib/v/checker/checker.v, vlib/v/checker/tests/test_functions_should_not_return_test.out, vlib/v/checker/tests/test_functions_wrong_signature_test.out, vlib/v/checker/tests/test_functions_wrong_signature_test.vv
Currently, test functions that have parameters occurs c error. This PR makes it an checker error
```
$ cat main_test.v
fn test_foo(n int) {}
$ v test main_test.v
---- Testing... ----------------------------------------------------------------------------------------------------------------
FAIL   345.013 ms main_test.v
^~~~~~~~~~~~~~~~
/tmp/v/test_session_151975589431509/main_test.12479305623335159627.tmp.c:15935:45: error: too few arguments to function call, single argument 'n' was not specified
if (!setjmp(g_jump_buffer)) main__test_foo();
~~~~~~~~~~~~~~ ^
/tmp/v/test_session_151975589431509/main_test.12479305623335159627.tmp.c:15568:1: note: 'main__test_foo' declared here
VV_LOCAL_SYMBOL void main__test_foo(int n) {
^ …
```
=> checker: report error for test functions that have parameters

vlib/x/json2/decoder_test.v, vlib/x/json2/encoder.v, vlib/x/json2/encoder_test.v
the json2 encoder handles the few special escapes in the json spec \n \r \t etc, but does not handle all characters 0x20 or lower, which should be \uXXXX encoded. I ran into this because ESC was not being encoded. This patch catches chars less than 0x20 that are not already handled by the special \n \r \t etc codes.
=> encode ascii chars < 0x20 in JSON

vlib/v/fmt/tests/maps_expected.vv, vlib/v/fmt/tests/maps_input.vv, vlib/v/parser/parser.v
format `map[key]value{ key: value }` to `{ key: value }` instead of parser error
=> fmt: format explicit map init with parameter

vlib/toml/any.v, vlib/toml/tests/datetime_test.v, vlib/toml/toml.v
It turns out using `time.Time` for representing TOML time formats isn't such a good idea.
TOML allows for `Local Date-Time`, `Local Date` and `Local Time`. And [as noted](https://toml.io/en/v1.0.0#local-date-time) these types `cannot be converted to an instant in time without additional information. Conversion to an instant, if required, is implementation-specific.` - so I think it's best to still represent the different types in userland (`toml.Date`,`toml.DateTime`,`toml.Time`) and let the users decide how they want to interpret the date. Later we can add specific conversion functions or additional data on the types (like `offset` and `is_local`).
(I bumped into another memory corruption error)
=> toml: don't use time.Time for time representation

vlib/jsdom/jsdom.js.v, vlib/v/checker/checker.v, vlib/v/gen/js/fn.v, vlib/v/gen/js/js.v
- JS structs are now just objects. In case you're creating some API wrapper you have to use `interface JS.DeclName` instead. 
- Variadic parameters now allowed for JS methods
- More DOM API wrappers: Element, Document, MouseEvent,PointerEvent,UIEvent,Event,Node,DOMTokenList etc
=> js,jsdom: JS structs are now just objects; more DOM API support for jsdom

vlib/toml/parser/parser.v, vlib/toml/tests/burntsushi.toml-test_test.v
This PR introduces support for empty tables:
```toml
[a]
[a.b]
```
Before the tables was made on demand when the values was parsed - but TOML allows for empty tables - so with this PR we allocate in the root table when the key is parsed.
=> toml: support empty tables

vlib/toml/ast/types.v, vlib/toml/checker/checker.v, vlib/toml/tests/burntsushi.toml-test_test.v, vlib/toml/toml.v
This PR fixes conversion of different number formats to their respective values.
The following pass their value tests, as an example:
```toml
bin1 = 0b11010110
bin2 = 0b1_0_1
oct1 = 0o01234567
oct2 = 0o755
oct3 = 0o7_6_5
hex1 = 0xDEADBEEF
hex2 = 0xdeadbeef
hex3 = 0xdead_beef
hex4 = 0x00987
```
=> toml: improve number conversion

vlib/v/gen/c/cgen.v, vlib/v/tests/multiple_matchs_in_one_expr_test.v
This PR fix multiple matchs in one expr (fix #12513).
- Fix multiple matchs in one expr.
- Add test.
```vlang
fn hex_to_bytes(s string) ?[]byte {
mut ret := []byte{cap: s.len}
for read := 0; read < s.len; read += 2 {
high := s[read]
low := s[read + 1]
ret << match high {
48...57 { (high - 48) << 4 }
65...70 { (high - 65) << 4 }
97...102 { (high - 97) << 4 }
else { panic('impossible') }
} + match low {
48...57 { low - 48 }
65...70 { low - 65 }
97...102 { low - 97 }
else { panic('impossible') }
}
}
return ret
}
fn main() {
ret := hex_to_bytes('FFFF') or { 'error'.bytes() }
println(ret)
assert '$ret' == '[U, U]'
}
[U, U]
```
=> cgen: fix multiple matchs in one expr (fix #12513)

.gitignore, cmd/tools/vcreate.v, cmd/tools/vcreate_test.v
Includes `vls.log` in the `.gitignore` list.
The VLS log file is generated while using the [V Language Server](https://github.com/vlang/vls). It is helpful for obtaining diagnostic information but does not serve a purpose relevant to the user's project.
=> Include vls.log in list of files to ignore

vlib/v/checker/check_types.v, vlib/v/tests/generic_fn_infer_nested_generic_fn_test.v
This PR fix generics fn infer nested generic fn (fix #6216).
- Fix generics fn infer nested generic fn.
- Add test.
```vlang
module main
import vweb
import json
import os
const (
port = 8081
)
struct App {
vweb.Context
}
fn main() {
mut spawns := []ItemSpawn{}
load_item_spawns(mut spawns)
vweb.run(&App{}, port)
}
fn load_item_spawns(mut spawns []ItemSpawn) {
walk<ItemSpawn>('./data/items/spawns/', mut spawns)
}
fn parse_json<T>(file string, mut array []T) {
data := os.read_file(file) or {
panic('error reading file $file')
return
}
decoded_data := json.decode([]T, data) or {
eprintln('Failed to parse item spawns')
return
}
for d in decoded_data {
array << d
}
}
fn walk<T>(path string, mut array []T) {
if !os.is_dir(path) {
return
}
mut files := os.ls(path) or { return }
for file in files { …
```
=> checker: fix generics fn infer nested generic fn (fix #6216)

vlib/toml/any.v, vlib/toml/tests/datetime_test.v, vlib/toml/tests/toml_memory_corruption_test.v
This PR fixes some string memory corruptions with the new date/time types
=> toml: fix memory corruption when returning new date/time types

vlib/v/checker/checker.v, vlib/v/tests/interface_test.v
This PR fixes function call arguments not registered properly in checker's `type_implements` when the param type is a variadic interface.
```v
type Text = string
fn (t Text) display() string {
return t
}
interface Displayable {
display() string
}
fn print_displayable(ds ...Displayable) {
for d in ds {
println(d.display())
}
}
fn test_variadic_interface() {
print_displayable(Text('test'), Text('hehe'))
}
```
=> checker: fix "unregistered" variadic interface call arguments

vlib/toml/ast/types.v, vlib/toml/ast/walker/walker.v, vlib/toml/checker/checker.v, vlib/toml/decoder/decoder.v, vlib/toml/parser/parser.v, vlib/toml/scanner/scanner.v, vlib/toml/tests/burntsushi.toml-test_test.v, vlib/toml/tests/strings_test.v
This PR will add a proper value decoder.
Right now it operates on basic strings only and can be disabled via the parser config.
This solves many problems (like getting rid of the `toml_to_json_escapes` function) in regards to value retrieval, JSON encoding and the remaining value checks.
=> toml: add value decoding

vlib/v/gen/c/auto_str_methods.v, vlib/v/gen/c/dumpexpr.v, vlib/v/tests/valgrind/dump_nested_structs.v, vlib/v/util/surrounder.v
I've also added a regression test in vlib/v/tests/valgrind/dump_nested_structs.v , which is now leak free under -autofree .
=> cgen: make `dump(x)` use a single write call, fix memleaks for autogenerated .str() methods of nested structs

vlib/v/checker/checker.v, vlib/v/checker/tests/invalid_parameter_name_err.out, vlib/v/checker/tests/invalid_parameter_name_err.vv, vlib/v/tests/for_loops_test.v
This PR check invalid fn parameter name (fix #12536).
- Check invalid fn parameter name.
- Add test.
```vlang
struct Buffer {
}
fn (mut b Buffer) put8(char u8) ? {
return error('-')
}
interface Writer {
mut:
put(char u8) ?
}
fn main() {
}
.\tt1.v:4:24: error: invalid use of reserved type `char` as a parameter name
2 | }
3 |
4 | fn (mut b Buffer) put8(char u8) ? {
|                        ~~~~
5 |     return error('-')
6 | }
.\tt1.v:10:6: error: invalid use of reserved type `char` as a parameter name
8 | interface Writer {
9 | mut:
10 |     put(char u8) ?
|         ~~~~
11 | }
12 |
```
=> checker: check invalid fn parameter name (fix #12536)

vlib/v/checker/checker.v, vlib/v/checker/tests/generics_fn_arg_type_err.out, vlib/v/checker/tests/generics_fn_arg_type_err.vv, vlib/v/checker/tests/generics_method_receiver_type_err.out
This PR check argument type error of the generics fn declaration (fix #12531).
- Check argument type error of the generics fn declaration.
- Add test.
```vlang
interface List<T> {
mut:
add(e T) bool
}
struct LinkedList<T> {
// ...
}
fn (mut list LinkedList<T>) add(e T) {
// ...
}
fn do_list_thing(list List) { // <--- Error here
// ...
}
fn main() {
}
.\tt1.v:14:23: error: generic interface in fn declaration must specify the generic type names, e.g. Foo<T>
12 | }
13 |
14 | fn do_list_thing(list List) {    // <--- Error here
|                       ~~~~
15 |   // ...
16 | }
```
=> checker: check argument type error of the generics fn declaration (fix #12531)

vlib/v/fmt/fmt.v, vlib/v/fmt/tests/asserts_expected.vv, vlib/v/fmt/tests/asserts_input.vv, vlib/v/gen/js/tests/testdata/match.v
v fmt removes paren for  infix expr. But not for others.
=> fmt: remove unnecessary paren in assert stmt

vlib/v/checker/checker.v
This PR fix vtl compile error.
Because the structure is too complex, no test examples are added.
error:
```vlang
fun.v:21:20: error: unknown method or field: `.TensorIterator<f64>.next`
19 |     mut iter := t.iterator()
20 |     for {
21 |         val, pos := iter.next() or { break }
|                          ~~~~~~~~~~~~~~~~~~~
22 |         next_val := f(val, pos)
23 |         t.data.set<T>(pos, next_val)
fun.v:1:1: error: checker.expr(): unhandled EmptyExpr
1 | module vtl
| ^
2 |
3 | import math
fun.v:22:22: error: cannot use `void` as `int` in argument 2 to `f`
20 |     for {
21 |         val, pos := iter.next() or { break }
22 |         next_val := f(val, pos)
|                            ~~~
23 |         t.data.set<T>(pos, next_val)
24 |     }
fun.v:32:20: error: unknown method or …
```
=> checker: fix vtl compile error

vlib/toml/decoder/decoder.v, vlib/toml/parser/parser.v, vlib/toml/tests/burntsushi.toml-test_test.v
This PR fixes a lot of unicode value conversions and escapes in basic TOML strings.
(The code could use some optimizing at one point)
=> toml: fix unicode and escape value decoding

vlib/toml/checker/checker.v, vlib/toml/parser/parser.v, vlib/toml/tests/burntsushi.toml-test_test.v
This PR will support checking and decoding of quoted keys (as opposed to only values).
The checking and decoding of the keys is dis- and enabled on the same conditions as when used on the values.
=> toml: support checking and decoding quoted keys

vlib/v/ast/table.v
This PR fix vtl compile error of generic array type cname.
```vlang
PS D:\vtl> v test .
---- Testing... --------------------------------------------------------------------------------------------------------
OK    [1/8]  1521.065 ms D:/vtl/creation_test.v
OK    [2/8]  1521.200 ms D:/vtl/build_test.v
OK    [3/8]  1520.991 ms D:/vtl/split_test.v
OK    [4/8]  1520.876 ms D:/vtl/stats/stats_test.v
OK    [5/8]  1521.441 ms D:/vtl/broadcast_test.v
OK    [6/8]  1521.204 ms D:/vtl/stack_test.v
OK    [7/8]  1529.970 ms D:/vtl/fun_test.v
OK    [8/8]   344.837 ms D:/vtl/storage/storage_test.v
------------------------------------------------------------------------------------------------------------------------
Summary for all V _test.v files: 8 passed, 8 total. Runtime: 1867 ms, on 7 parallel …
```
=> ast: fix vtl compile error of generic array type cname

doc/vscode.md
The task configuration file is tasks.json not task.json
=> Fix typo in vscode documentation

vlib/v/checker/checker.v, vlib/v/gen/c/cgen.v, vlib/v/tests/for_in_mut_iterator_val_test.v
This PR fix for_in_mut iterator val (fix #12530).
- Fix for_in_mut iterator val.
- Add test.
```vlang
const (
packets = {
0: &Packet{
pid: 2
}
1: &Packet{
pid: 1
}
}
)
struct Packet {
pid        int
handle     fn () string
restricted bool
}
struct Reader {
foo int
bar string
mut:
index int
}
fn (mut p Reader) next() ?&Packet {
if p.index + 1 > packets.len {
return error('')
}
if p.index !in packets {
return error('')
}
p.index++
return packets[p.index - 1]
}
fn main() {
r := Reader{}
for mut packet in r {
println(packet.pid)
rets << '$packet.pid'
}
println(rets)
assert rets[0] == '2'
assert rets[1] == '1'
}
2
1
['2', '1']
```
=> checker, cgen: fix for_in_mut iterator val (fix #12530)

vlib/toml/tests/burntsushi.toml-test_test.v
This PR adds a temporary, local, workaround for #9507
(If merged with #12564 - it also makes the last test case pass successfully :partying_face: )
=> toml: workaround #9507

vlib/toml/any.v, vlib/toml/tests/value_query_test.v, vlib/toml/toml.v
This PR adds the `value()` call to the rest of the `toml.Any` types.
With this it is much easier to pass parts of a TOML document around to different parts of your application.
Example:
`config.toml`
```toml
app = { name: 'Super Game', hype_level: 100 }
[[themes]]
name = "Dracula"
colors = [ "red", "black", "white" ]
[[themes]]
name = "Lemon"
colors = [ "green", "yellow" ]
[[players]]
name = "Player 1"
[[players]]
name = "Player 2"
```
```v
...
toml_doc := toml.parse('config.toml') or { panic(err) }
themes := toml_doc.value('themes')
players := toml_doc.value('players') 
...
game.setup(toml_doc.value('app'))
game.load_themes(themes)
game.load_players(players)
```
In `game.v`
```v
...
pub fn (mut g Game) load_themes(themes toml.Any) {
g.default_theme = …
```
=> toml: streamline value() api

cmd/tools/vdoc/html.v, cmd/tools/vdoc/resources/doc.css
This add a link to the vdoc generated html for spiking header/menu to go directly to the main content of the page.
Really useful when you're using a screen reader, a TUI browser or navigating with your keyboard.
Did I miss something for my first PR ?
=> vdoc: Add "skip to content" link for screen reader and tui browsers

vlib/toml/parser/parser.v, vlib/toml/tests/spaced_keys_test.v, vlib/toml/toml.v
This PR encapsulates the parsing of dotted keys - which is then reused across the parser.
Now spaced keys works everywhere, even in (ugly, but valid) TOML like this:
```toml
"o"   .   	pq  .  r     =    "Yuk"
[[ a . "b.c" ]]
d . e = "V rocks!"
[ tube . test . "test.test" ]
h  .	"i.j."  .   "k"  =   	 "Cryptic"
```
=> toml: clean up and improve spaced and dotted key parsing

vlib/v/checker/checker.v, vlib/v/gen/c/fn.v, vlib/v/tests/fn_type_call_of_match_expr_test.v
This PR fix fn type call of match expr (fix #12543).
- Fix fn type call of match expr.
- Add test.
```vlang
type FnZ = fn () string
type FnO = fn (int) string
type FnQ = FnO | FnZ
fn fnz_z() string {
return 'Got zero'
}
fn fnz_o(one int) string {
return 'Got one $one'
}
fn main() {
mut arr := [FnQ(FnZ(fnz_z)), FnQ(FnO(fnz_o))]
for item in arr {
match item {
FnZ {
println(item())
assert item() == 'Got zero'
}
FnO {
println(item(42))
assert item(42) == 'Got one 42'
}
}
}
}
Got zero
Got one 42
```
=> checker, cgen: fix fn type call of match expr (fix #12543)

vlib/v/tests/interface_test.v
UPDATE:
no more runtime error with current V, see updated comments under.
----
OLD (original) subject for this PR:
and clean-up TODO resolved now.
In this PR you can see that if I call a function with an interface as argument and then I call another function with that interface argument (see related two new lines enabled in this PR) I got a runtime error:
```
interface_test.tmp.c: In function ‘perform_speak’:
interface_test.tmp.c:10178:20: error: implicit declaration of function ‘I_Animal_to_Interface_Animal’; did you mean ‘I_Bird_to_Interface_Animal’? [-Werror=implicit-function-declaration]
10178 |  if (is_dog_or_cat(I_Animal_to_Interface_Animal(&a))){
|                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
|                    I_Bird_to_Interface_Animal …
```
=> interface: update tests

.github/workflows/toml_ci.yml, vlib/toml/tests/iarna.toml-spec-tests_test.v
This PR adds all tests from https://github.com/iarna/toml-spec-tests to CI.
Our TOML parser is doing pretty well :partying_face: - though it still needs a bit of tweaking.
=> toml: add `iarna/toml-spec-tests` to CI tests

vlib/v/checker/checker.v, vlib/v/checker/tests/left_shift_op_expr_not_used.out, vlib/v/checker/tests/left_shift_op_expr_not_used.vv
This PR produces an error for code like this (fix #12584):
```v
1 << 1
``` 
and: 
```v
a := 123 
a << 1 
```
... but not for: 
```v 
x := if true { 1 << 1 } else { 5 << 4 } 
```
because the result of the expression is used.
=> checker: add a check for unused `x << y` expressions (where x != array)

vlib/toml/parser/parser.v, vlib/toml/tests/iarna.toml-spec-tests_test.v
This PR fixes parsing of bare keys with `-` and `_` - allowing:
```toml
-_-_-_-_-=1
```
=> toml: improve parsing of bare keys to include `-` and `_`

vlib/toml/checker/checker.v, vlib/toml/tests/iarna.toml-spec-tests_test.v
Small fix for wrongly checked float values < 1
=> toml: fix float checker bug for `-0.01`

vlib/toml/parser/parser.v, vlib/toml/scanner/scanner.v, vlib/toml/tests/iarna.toml-spec-tests_test.v, vlib/toml/tests/testdata/.gitignore, vlib/toml/tests/types_test.v
This PR fixes cases where (`+/-`) `nan` and `inf` values isn't necessarily the last token on the line.
In the process it led to a little speed increase since we don't need to peek forward for the line ending or anything else :+1:
(Will probably need a small conflict resolve if #12590 is merged first and vice versa)
=> toml: fix, test and optimize `nan` and `inf` values

vlib/v/gen/c/embed.v, vlib/v/gen/c/testdata/embed_with_prod.c.must_have
The last char of the path was missing which lead to `find_index_entry_by_path` not finding the embedded file and falling back to loading from disk (which fails in production because the file does not exist).
Fixes #12090.
=> cgen: fix $embed_file not finding embedded file when using -prod

vlib/toml/tests/iarna.toml-spec-tests_test.v
This PR fixes a small inconsistency between the iarna and BurntSushi test suites.
It seems like iarna is using 3 digit millisecond endings (which might be the sanest) but Burntsushi test expects 6 digits endings.
I *think* the format is implementation specific - since RFC 3339 allows for both versions of the endings.
For now I've chosen to keep the 6 digits since it'll take way more changes to fix all the tests to expect 3.
=> toml: fix date-time and time ms test inconsistency

vlib/v/checker/checker.v, vlib/v/checker/tests/match_expr_range_low_higher_than_high.out, vlib/v/checker/tests/match_expr_range_low_higher_than_high.vv
```v
fn main() {
value := 10
match value {
20...10 {}  // wont match anything
}
}
```
Fixes #12601.
=> checker: add a warning if start value is higher than end value

vlib/v/tests/raw_string_test.v, vlib/v/transformer/transformer.v
Fix #12548.
Always uses `util.smart_quote` to ensure both left string literal and left literal is properly treated.
=> v.transformer: fix string always escaped by transformer

vlib/toml/parser/parser.v, vlib/toml/tests/iarna.toml-spec-tests_test.v
This PR will check for the following condition:
```toml
[product]
type = { name = "Nail" }
type.edible = false  # This is invalid since `type` has been explicitly declared as an inline table (which are immutable)
```
=> toml: check for mutation of immutable inline tables

vlib/crypto/blowfish/block.v, vlib/crypto/blowfish/blowfish.v
add doc blowfish.
```
⫸ v run ./cmd/tools/missdoc.v vlib/crypto/blowfish
/Users/Taillook/project/prjtail/v/vlib/crypto/blowfish/block.v:3:0:pub fn expand_key(key []byte, mut bf Blowfish) 
/Users/Taillook/project/prjtail/v/vlib/crypto/blowfish/block.v:42:0:pub fn expand_key_with_salt(key []byte, salt []byte, mut bf Blowfish) 
/Users/Taillook/project/prjtail/v/vlib/crypto/blowfish/block.v:85:0:fn encrypt_block(l u32, r u32, mut bf Blowfish) []u32 
/Users/Taillook/project/prjtail/v/vlib/crypto/blowfish/block.v:126:0:fn get_next_word(b []byte, pos &int) u32 
/Users/Taillook/project/prjtail/v/vlib/crypto/blowfish/blowfish.v:9:0:pub fn new_cipher(key []byte) ?Blowfish 
/Users/Taillook/project/prjtail/v/vlib/crypto/blowfish/blowfish.v:21:0:pub fn new_salted_cipher(key []byte, salt []byte) …
```
=> vlib/crypto/blowfish: add doc blowfish

vlib/v/checker/tests/return_missing_match_simple.out, vlib/v/parser/if_match.v
An extra brace is added in the c output when `match a{else{}}` is found, but the parser just shows a warning. imho it should be an error.
Fixes this cgen problem. as long as those constructions shouldnt be valid (imho) there's no need to fix the cgen side (or it dies?)
```
$ cat a.v
fn main() {
a := 0
match a {
else {
}
}
}
$ v run a.v
a.v:4:2: warning: `match` must have at least one non `else` branch
2 |     a := 0
3 |     match a {
4 |     else {
|     ~~~~
5 | }
6 |     }
/tmp/v_501/a.15883627273481714965.tmp.c:10601:1: error: extraneous closing brace ('}')
}
^
1 error generated.
...
builder error:
This is a compiler bug, please report it using `v …
```
=> parser: Forbid empty match statements 'match cond.op {else {}}'

vlib/picoev/picoev.v
Fixes errors from https://discord.com/channels/592103645835821068/592114487759470596/911186148443979807
```v
/home/astro/Projects/V/v-main/vlib/picoev/picoev.v:229:7: error: field `sin_family` of struct `C.sockaddr_in` is immutable
227 |     }
228 |     mut addr := C.sockaddr_in{}
229 |     addr.sin_family = C.AF_INET
|          ~~~~~~~~~~
230 |     addr.sin_port = C.htons(config.port)
231 |     addr.sin_addr.s_addr = C.htonl(C.INADDR_ANY)
/home/astro/Projects/V/v-main/vlib/picoev/picoev.v:230:7: error: field `sin_port` of struct `C.sockaddr_in` is immutable
228 |     mut addr := C.sockaddr_in{}
229 |     addr.sin_family = C.AF_INET
230 |     addr.sin_port = C.htons(config.port)
231 |     addr.sin_addr.s_addr = C.htonl(C.INADDR_ANY)
232 |     size := 16 // …
```
=> picoev: use `net` C definitions

vlib/toml/parser/parser.v, vlib/toml/scanner/scanner.v
This PR simplifies the scanner and parser in regards to keys that looks like booleans by having the scanner identifying them as boolean *only* when they're values.
```toml
true = true
false = false
```
=> toml: simplify bool keys in scanner and parser

vlib/toml/parser/parser.v, vlib/toml/tests/iarna.toml-spec-tests_test.v
This PR adds a few more checks for (sub)table redefining.
It also squashes the last exceptions. Further value test passing of the remaining iarna tests will require a YAML parser or some sort of YAML -> JSON conversion tool. But until that it looks like we pass, what is regarded as, the official TOML test suite(s).
:partying_face:
=> toml: add more checks for table redeclarations

vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/str_intp.v, vlib/v/tests/interface_str_method_test.v
This PR fix error of the interface str method (fix #12538).
- Fix interface str method error.
- Add test.
```vlang
interface Str {
str() string
}
struct St {}
fn (s St) str() string {
return 's'
}
fn printer(s Str) string {
println(s)
return '$s'
}
fn main() {
s := St{}
ret := printer(s)
assert ret == 's'
}
s
```
=> cgen: fix error of the interface str method (fix #12538)

vlib/v/gen/c/auto_str_methods.v, vlib/v/gen/js/auto_str_methods.v
This PR makes minor cleanup in auto_str_methods.v.
- `struct_auto_str_func1()` change to `struct_auto_str_func()`.
- `type_to_fmt1()` change to `type_to_fmt()`.
=> gen: cleanup auto_str_methods

vlib/crypto/bcrypt/bcrypt.v
add document bcrypt.
```
⫸ v run ./cmd/tools/missdoc.v vlib/crypto/bcrypt
/Users/Taillook/project/prjtail/v/vlib/crypto/bcrypt/bcrypt.v:33:0:pub fn generate_from_password(password []byte, cost int) ?string 
/Users/Taillook/project/prjtail/v/vlib/crypto/bcrypt/bcrypt.v:39:0:pub fn compare_hash_and_password(password []byte, hashed_password []byte) ? 
/Users/Taillook/project/prjtail/v/vlib/crypto/bcrypt/bcrypt.v:58:0:pub fn generate_salt() string 
/Users/Taillook/project/prjtail/v/vlib/crypto/bcrypt/bcrypt.v:63:0:fn new_from_password(password []byte, cost int) ?&Hashed 
/Users/Taillook/project/prjtail/v/vlib/crypto/bcrypt/bcrypt.v:84:0:fn new_from_hash(hashed_secret []byte) ?&Hashed 
/Users/Taillook/project/prjtail/v/vlib/crypto/bcrypt/bcrypt.v:103:0:fn bcrypt(password []byte, cost int, salt …
```
=> vlib/crypto/bcrypt: add doc bcrypt

vlib/strings/builder.js.v, vlib/v/ast/table.v, vlib/v/checker/checker.v, vlib/v/checker/tests/bool_string_cast_err.out, vlib/v/checker/tests/cast_string_err.out, vlib/v/checker/tests/cast_string_with_byte_err.out, vlib/v/checker/tests/struct_type_cast_err.out, vlib/v/gen/c/cgen.v, vlib/v/gen/native/gen.v, vlib/v/tests/alias_basic_types_test.v, vlib/v/token/position.v
* With this PR, casting of `string` to `string` aliases and back, works just like
other casts. 
* The obsolete and error prone `string(byteptr)` is now disallowed.
All other casts from/to `string` will produce an error to use .str()
instead.
* The same applies to `byte` to `byte` aliases and back.
Previously casting from a `byte` alias, back to `byte` was prevented needlessly:
```
z.v:3:6: error: cannot cast type MyByte to byte
1 | type MyByte = byte
2 | dump(MyByte(byte(123)))
3 | dump(byte(MyByte(123)))
|      ~~~~~~~~~~~~~~~~~
4 |
```			  
* The ast.Table now stores an array of &TypeSymbol, instead of an
array of TypeSymbol, which fixes the need for the preallocation to
avoid reallocations, and multiple unsafe{} usages.
=> all: fix casting of `string(MyString('abc'))` and `byte(MyByte(123))`; improve TypeSymbol handling

vlib/v/dotgraph/dotgraph.js.v
Found this while trying to compile V itself into js `v -b js cmd/v`. There still some more things to fix to get it ready, but at least that's one step closer
=> js: add missing start_digraph() for the js backend

.github/workflows/toml_ci.yml, vlib/toml/tests/iarna.toml-spec-tests_test.v
This PR will enable support for converting the YAML value check files to JSON so we can validate a little more values from the iarna test suite.
=> toml: convert yaml value checks in iarna test suite

vlib/strconv/format.md
This PR fixes the example snippets in `strconv`'s `format.md` - they wouldn't run if copy pasted into e.g. the playground.
They'll work now
=> strconv: fix format.md example snippets

vlib/v/checker/checker.v, vlib/v/tests/map_init_with_enum_keys_test.v
This PR fix map init with enum keys (fix #12636).
- Fix map init with enum keys.
- Add test.
```vlang
enum En {
ea
eb
}
struct St {
mut:
m map[En]string
}
fn main() {
mut st := St{}
st.m = {
.ea: 'a'
}
println(st.m)
assert '$st.m' == "{ea: 'a'}"
}
{ea: 'a'}
```
=> checker: fix map init with enum keys (fix #12636)

vlib/v/gen/c/fn.v, vlib/v/tests/generic_fn_with_anon_fn_test.v
This PR fix generic fn with anon fn in body (fix #12639).
- Fix generic fn with anon fn in body.
- Add test.
```vlang
fn foo<T>() string {
x := fn () string {
return 'ok'
}
return x()
}
fn main() {
ret := foo<int>()
assert ret == 'ok'
}
```
=> cgen: fix generic fn with anon fn in body (fix #12639)

vlib/toml/checker/checker.v, vlib/toml/tests/alexcrichton.toml-rs-tests_test.v
This PR will disallow "floats" like these:
```toml
val0 = 1.2f
val1 = 1.2g
val2 = 1.2abc
```
=> toml: add better float validation

vlib/net/address.v, vlib/net/address_test.v
Fixes #12578
Another option is to use `tos2` instead of `vstring`, I'm not sure which is preferred.
=> net: properly convert IP address C strings to V strings

vlib/toml/parser/parser.v, vlib/toml/tests/alexcrichton.toml-rs-tests_test.v, vlib/toml/tests/array_of_tables_edge_case_2_test.v, vlib/toml/tests/testdata/array_of_tables_edge_case_2_test.out, vlib/toml/tests/testdata/array_of_tables_edge_case_2_test.toml
Improve support for this syntax:
```toml
[[ albums ]] # <- This PR fixes parsing the whitespace on each side of the key here
[[ albums.songs ]] # <- ... and here.
[[ albums.songs ]] # <- Current implementation allows for 2 levels only
[[ artists ]]
[ artists.home.address ] # <- This will work after this PR - where key nesting level is > 2
```
=> toml: support multi-level map keys in arrays-of-tables

vlib/toml/checker/checker.v, vlib/toml/tests/alexcrichton.toml-rs-tests_test.v
TOML allows for escaping multi-line strings to be decoded as a single line:
```toml
equivalent_one = "The quick brown fox jumps over the lazy dog."
equivalent_two = """
The quick brown \
fox jumps over \
the lazy dog."""
equivalent_three = """\
The quick brown \
fox jumps over \
the lazy dog.\
"""
whitespace-after-bs = """\
The quick brown \
fox jumps over \   
the lazy dog.\	
"""
```
The above variables should all have the value `The quick brown fox jumps over the lazy dog.`
This has worked so far but this PR will solidify the validation process and fix an edge case that slipped through before:
```toml
bug = """
Hello \     a # <- ouch this should have failed - but it didn't   
World
"""
```
=> toml: solidify "multi to single"-line escape validation

vlib/v/checker/checker.v, vlib/v/gen/c/cgen.v, vlib/v/tests/match_expr_returning_optional_test.v
This PR fix match expr returning optional with error (fix #12556).
- Fix match expr returning optional with error.
- Add test.
```vlang
fn func() ?string {
code := 0
return match code {
0 { 'zero' }
else { error('as we are returning an optional') }
}
}
fn main() {
ret := func() or { 'error' }
println(ret)
assert ret == 'zero'
}
zero
```
=> checker, cgen: fix match expr returning optional with error (fix #12556)

vlib/toml/any.v, vlib/toml/tests/reflect_test.v, vlib/toml/toml.v
This PR adds methods for easy reflection of TOML values to a V struct:
```v
import toml
const toml_text = '# This TOML can reflect to a struct
name = "Tom"
age = 45
height = 1.97
birthday = 1980-04-23
[bio]
text = "Tom has done many great things"
years_of_service = 5
[config]
data = [ 1, 2, 3 ]
levels = { "info" = 1, "warn" = 2, "critical" = 3 }
'
struct Bio {
text             string
years_of_service int
}
struct User {
age      int
height   f64
birthday toml.Date
config toml.Any
mut:
bio Bio
}
fn test_reflect() {
toml_doc := toml.parse(toml_text) or { panic(err) }
mut user := toml_doc.reflect<User>()
user.bio = toml_doc.value('bio').reflect<Bio>()
assert user.name == 'Tom'
assert user.age == 45
assert user.height == 1.97
assert user.birthday.str() == '1980-04-23'
assert …
```
=> toml: add reflection method

vlib/v/gen/c/fn.v, vlib/v/tests/match_sumtype_var_aggregate_print_var_test.v
This PR fix match sumtype print var aggregate error  (fix #12651).
- Fix match sumtype print var aggregate error.
- Add test.
```vlang
type Bug = i64 | u64
fn main() {
f := Bug(i64(-17))
ret := match f {
u64, i64 {
println(f)
println(f.str())
f.str()
}
}
assert ret == '-17'
}
-17
-17
```
=> cgen: fix match sumtype print var aggregate error  (fix #12651)

cmd/tools/vast/vast.v, vlib/v/ast/ast.v, vlib/v/ast/table.v, vlib/v/checker/checker.v, vlib/v/gen/c/cgen.v, vlib/v/tests/nested_struct_embed_test.v
This PR fix nested struct embed error (fix #12659).
- Fix nested struct embed error.
- Add test.
```vlang
struct Foo {
mut:
x int
}
struct Bar {
Foo
}
struct Baz {
Bar
}
fn test_nested_struct_embed() {
mut baz := Baz{}
baz.x = 3
println(baz.x)
assert baz.x == 3
}
3
```
=> ast, checker, cgen: fix nested struct embed error (fix #12659)

vlib/v/ast/table.v, vlib/v/checker/checker.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/infix_expr.v, vlib/v/gen/js/infix.v, vlib/v/gen/js/js.v
This PR cleanup struct embeds related methods.
- Remove obsolete and useless functions.
- Rename `type_find_method...` to `find_method...` just like `find_field...`.
=> ast: cleanup struct embeds related methods

vlib/builtin/string.v, vlib/builtin/string_test.v
- `split_any()` implementation
- tests for `split_any`
examples:
```v
assert 'ABC'.split_any('') == ['A', 'B', 'C']
assert ''.split_any(' ') == []
assert ' '.split_any(' ') == ['']
assert '  '.split_any(' ') == ['', '']
assert 'Ciao come stai? '.split_any(' ') == ['Ciao', 'come', 'stai?']
assert 'Ciao+come*stai? '.split_any('+*') == ['Ciao', 'come', 'stai? ']
assert 'Ciao+come*stai? '.split_any('+* ') == ['Ciao', 'come', 'stai?']
assert 'first row\nsecond row'.split_any(' \n') == ['first', 'row', 'second', 'row']
```
=> builtin/string: split_any

vlib/crypto/sha256/sha256.v
add missing documentation of `sum`.
=> crypto.sha256: add missing documentation of `sum`

vlib/v/ast/table.v
This PR correct comments of the find_field_from_embeds in ast.
=> ast: correct comments of the find_field_from_embeds

cmd/tools/vtest.v, vlib/v/ast/ast.v, vlib/v/checker/checker.v, vlib/v/gen/js/fn.v, vlib/v/gen/js/js.v
This PR adds initial support for JS.await. The next step is to add support for using It together with the `go` expr and add tests for JS promises and `go` expressions.
=> js: JS.await support 

cmd/tools/vtest-self.v, vlib/sync/once.v, vlib/sync/once_test.v
add sync.Once struct.
There are times when you want to call a function only once.
And I think there's a demand for it.
=> sync.once: add Once

vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/tests/comptime_for_method_call_test.v
This PR fix comptime for_in methods call (fix #12621).
- Fix comptime for_in methods call.
- Add test.
```vlang
struct Foo {}
fn (f Foo) a() int {
return 1
}
fn (f Foo) b() int {
return 2
}
fn main() {
f := Foo{}
$for method in Foo.methods {
x := f.$method()
println(x)
rets << x.str()
}
assert rets[0] == '1'
assert rets[1] == '2'
}
1
2
```
=> cgen: fix comptime for_in methods call (fix #12621)

vlib/net/address.v, vlib/net/udp.v, vlib/net/udp_test.v, vlib/net/websocket/websocket_test.v
The websocket client tests were being skipped for IPv4, with a comment saying "fix client". This was a little misleading, because it wasn't actually the websocket client that was broken, but the server.
The problem was that an IPv6 address was being returned, even though an IPv4 address was being requested.
After changing that, I ran into problems with `udp_test.v` running on Windows (failed in CI), so I added more code to address that.
=> net.websocket: Fix server not listening for IPv4

examples/gg/raven_text_rendering.v, examples/sokol/fonts.v, examples/sokol/freetype_raven.v, vlib/fontstash/fontstash.c.v, vlib/gg/text_rendering.c.v, vlib/sokol/sfons/sfons.c.v, vlib/sokol/sfons/sfons_funcs.c.v
This PR replaces the use of `C.fonsXXX` / `C.sfons_XXX` calls with their wrapped V equivalents.
I have checked that the changed examples still run under Linux.
V UI fixes in https://github.com/vlang/ui/pull/401
=> examples: use `fontstash` wrapper calls

vlib/vweb/vweb.v, vlib/vweb/vweb_app_test.v
Small change to add the `json_pretty()` method to vweb.
If you want to return a pretty-printed JSON response from an endpoint, this allows for a slightly nicer syntax:
Before:
```v
res := json.encode_pretty(&MyStruct{
foo: 'some value'
})
s.set_content_type(vweb.mime_types['.json'])
return s.ok(res)
```
After:
```v
return s.json_pretty(&MyStruct{
foo: 'some value'
})
```
=> vweb: add json_pretty method

vlib/v/ast/table.v, vlib/v/checker/check_types.v, vlib/v/checker/checker.v, vlib/v/checker/tests/sumtype_as_mismatched_type.out, vlib/v/checker/tests/sumtype_as_mismatched_type.vv, vlib/v/gen/c/cgen.v
This PR check sumtype as mismatched type (fix #12713).
- Check sumtype as mismatched type.
- Add test.
```vlang
type Type = bool | int | string
fn main() {
mut t := Type(123)
v := t as &int
t = 456
println(v)
}
.\tt1.v:5:9: error: cannot cast `Type` to `&int`
4 |     mut t := Type(123)
5 |     v := t as &int
|            ~~
6 |     t = 456
7 |     println(v)
```
=> checker: check sumtype as mismatched type (fix #12713)

vlib/v/parser/parser.v
Add support for a dot prefix for attribute names
```v
struct Flags {
name string [cli.abbrev: 'n'; cli.description: 'The Name of a Person'] = 'Alice'
age  int    [cli.required: 'true']
}
```
It only allows a single `.`, so `cli.abbrev.foo` leads to the same unexpected token error as before.
=> v.parser: support dot prefix for attributes

vlib/v/ast/attr.v, vlib/v/parser/parser.v, vlib/v/tests/attribute_test.v
Support boolean values in attributes
```v
struct Test {
foo string [attr0: true; attr1: false]
}
```
=> v.parser: support bool values in attributes

vlib/v/gen/c/str_intp.v, vlib/v/tests/comptime_for_method_call_test.v
This PR fix comptime for_in methods call using str_intp.
- Fix comptime for_in methods call using str_intp.
- Add test.
```vlang
struct Foo {}
fn (f Foo) a() int {
return 1
}
fn (f Foo) b() int {
return 2
}
fn main() {
f := Foo{}
$for method in Foo.methods {
x := f.$method()
println(x)
println(x.str())
println('$x')
rets << x.str()
rets << '$x'
}
assert rets.len == 4
assert rets[0] == '1'
assert rets[1] == '1'
assert rets[2] == '2'
assert rets[3] == '2'
}
1
1
1
2
2
2
```
=> cgen: fix comptime for_in methods call using str_intp

vlib/v/parser/comptime.v
This PR fix $tmpl(absolute path) error (fix #12727).
- Fix $tmpl(absolute path) error.
```vlang
fn main() {
name := 'V'
res := $tmpl('d:/test/1.txt')
println(res)
}
V
```
1.txt
```vlang
@name
```
=> parser: fix $tmpl(absolute path) error (fix #12727)

.github/workflows/ci.yml, vlib/net/openssl/c.v
my openssl wasn't installed in this directory, thus didn't work. we should use #pkgconfig to find it instead
=> openssl: use pkgconfig instead of hardcoded path

vlib/v/gen/c/fn.v
Windows allows to link as gdi32, Gdi32, GDI32 ... using lowercase always ensures it matches always.
=> cgen:ensure that the different gdi32 notations are always matched

vlib/v/checker/checker.v, vlib/v/tests/const_many_pluses_with_raw_string_literal_test.v
This PR fix const type with raw string literal (fix #12604).
- Fix const type with raw string literal.
- Add test.
```vlang
const ca = r'x\n'
const cb = 'x\n'
const cc = ca + cb
const cd = cc + cc
const ce = cd + cd
fn main() {
a := r'x\n'
assert a == ca
b := 'x\n'
assert b == cb
c := a + b
assert c == cc
d := c + c
assert d == cd
e := d + d
assert e == ce
println(e)
result := r'x\nx
x\nx
x\nx
x\nx
'
assert e == result
}
x\nx
x\nx
x\nx
x\nx
```
=> checker: fix const type with raw string literal (fix #12604)

vlib/v/ast/types.v, vlib/v/fmt/tests/generics_keep.vv, vlib/v/tests/generics_test.v
fix below behavior
```
$ v fmt vlib/v/fmt/tests/generics_keep.vv
import mymod { Data, ImpNode }
fn foobar_mymod<U>(inode ImpNode<U>) ImpNode<U> {
return ImpNode{}
}
fn simple<T>() T {
return T{}
}
struct Foo {}
fn (_ Foo) simple<T>() T {
return T{}
}
struct GenericStruct<A, B> {
v mymod.Data<mymod.Data<A>, B>
}
fn proper_generics(gs GenericStruct<A, B>) GenericStruct<A, B> {
return gs
}
fn main() {
simple<int>()
Foo{}.simple<int>()
}
```
=> fmt: fix bug that add unnecessary module name to generic type.

vlib/readline/readline_linux.c.v, vlib/v/tests/repl/println.repl
Japanese IME has full-width mode. When I pressed the space key in full-width mode, vrepl terminated.
Readline converts int to byte in some places. Full-width space is '0x3000'. So it will be converted to '0x00'. 
Therefore, if a full-width space is entered, readline will treat it as an eof.
This PR fix that bug.
=> readline: fix bug that full-width spaces is treated as eof

cmd/tools/vtest-all.v, vlib/gg/gg.v, vlib/gg/recorder.v, vlib/sokol/sapp/sapp_v.c.v, vlib/sokol/sapp/screenshot.c.v
See the discussion here <https://discord.com/channels/592103645835821068/592320321995014154/918126992895930369>
The PR provides a way to record screenshots taken at specific frames and to stop a gg program after a given amount of frames had been rendered. That allows for storing images and comparing them to a pre-recorded set of good images, to detect regressions.
NB: The tool that will launch the gg programs is *not* in this PR.
Example:
```sh
VGG_STOP_AT_FRAME=120 \
VGG_SCREENSHOT_FOLDER=. \
VGG_SCREENSHOT_FRAMES=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60 \
./v -d gg_record run examples/flappylearning/
```
=> gg: support `VGG_STOP_AT_FRAME=120 VGG_SCREENSHOT_FOLDER=. VGG_SCREENSHOT_FRAMES=10,20,30 ./v -d gg_record run examples/gg/bezier_anim.v`

cmd/tools/vcomplete.v, cmd/tools/vgret.v, cmd/v/help/gret.txt, cmd/v/v.v
This PR will add a new tool `vgret` that can aid us in detecting changes in `gg` rendering based apps.
It's a, kind-of, follow up PR to #12767 - because this tool makes use of the features introduced.
I intend to add a dedicated CI workflow that'll make use of `vgret` after this PR is merged.
=> tools: add `vgret` to aid detecting visual regressions in `gg` based apps

vlib/v/ast/table.v, vlib/v/checker/checker.v, vlib/v/parser/fn.v
This PR fix generic fn in builtin module (fix #12760).
- Fix generic fn in builtin module.
- Add `table.register_fn_generic_types()` to register generic fn informations.
- `register_fn_concrete_types()` process in checker phase.
- Testing locally.
builtin.v
```vlang
pub struct Foo<T> {
x T 
}
pub fn foo<T>(x T) Foo<T> {
return Foo<T>{x}
}
```
tt1.v
```vlang
fn main() {
foo<int>(42)
}
```
=> ast, parser, checker: fix generic fn in builtin module (fix #12760)

vlib/builtin/js/promise.js.v, vlib/v/checker/checker.v, vlib/v/gen/js/fn.v
- Added jsgen and checker support for `.wait()` method on promises
- Changed promise type signature from `Promise<T,E>` to `Promise<T>`.This change was necessary because promise might throw other errors than just `E` and if you `reject` something then it is turned into the string and returned as V's option type
=> js: Support for Promise.wait()

vlib/v/ast/table.v, vlib/v/checker/checker.v, vlib/v/gen/c/cgen.v, vlib/v/tests/interface_method_with_struct_embed_test.v
This PR fix interface method with struct embed (fix #12771).
- Fix interface method with struct embed.
- Add test.
```vlang
struct Foo {
x int
}
fn (f Foo) get() int {
return f.x
}
struct Bar {
Foo
}
interface Getter {
get() int
}
fn main() {
mut getter := []Getter{}
foo := Foo{22}
getter << foo
bar := Bar{Foo{11}}
getter << bar
assert getter.len == 2
println(foo)
println(getter[0])
assert getter[0].get() == 22
println(bar)
println(getter[1])
assert getter[1].get() == 11
}
Foo{
x: 22
}
Getter(Foo{
x: 22
})
Bar{
Foo: Foo{
x: 11
}
}
Getter(Bar{
Foo: Foo{
x: 11
}
})
```
=> ast, checker, cgen: fix interface method with struct embed (fix #12771)

vlib/v/checker/check_types.v
This PR fix notice of eval.infix.v on windows.
before notice:
```vlang
......
vlib\v\eval\infix.v:2177:21: notice: shifting a value from a signed type `i64` can change the sign
2175 |                             } else if expecting == ast.int_literal_type_idx {
2176 |                                 unsafe {
2177 |                                     return i64(i64(left) << i64(right.val))
|                                                ~~~~~~~~~
2178 |                                 }
2179 |                             } else {
vlib\v\eval\infix.v:2190:21: notice: shifting a value from a signed type `i64` can change the sign
2188 |                             } else if expecting == ast.int_literal_type_idx {
2189 |                                 unsafe {
2190 | …
```
=> checker: fix notice of eval.infix.v on windows

vlib/v/gen/c/cgen.v, vlib/v/tests/multiple_embed_struct_init_test.v
This PR fix multiple nested embed struct init (fix #12786).
- Fix multiple nested embed struct init.
- Add test.
```vlang
pub struct Boundary {
mut:
x        int
y        int
offset_x int
offset_y int
width    int
height   int
}
pub struct WidgetBase {
Boundary
mut:
id      string
z_index int
hidden  bool
}
pub struct Label {
WidgetBase
}
fn main() {
l := Label{
x: 100
y: 200
}
println(l)
assert l.x == 100
assert l.y == 200
}
Label{
WidgetBase: WidgetBase{
Boundary: Boundary{
x: 100
y: 200
offset_x: 0
offset_y: 0
width: 0
height: 0
}
id: ''
z_index: 0
hidden: false
}
}
```
=> cgen: fix multiple embed struct init (fix #12786)

vlib/builtin/array.v
This PR cleanup array.v in builtin module.
- Remove obsolete code that is not used. (Not sure if it has other uses)
```vlang
// filter creates a new array with all elements that pass the test implemented by the provided function
pub fn (a array) filter(predicate fn (voidptr) bool) array
struct ZZZTmp1 {}
// any tests whether at least one element in the array passes the test implemented by the
// provided function. It returns true if, in the array, it finds an element for which the provided
// function returns true; otherwise it returns false. It doesn't modify the array
pub fn (a array) any(predicate fn (voidptr) bool) bool
struct ZZZTmp2 {}
// all tests whether all elements in the array pass the test implemented by the provided function
pub fn (a array) all(predicate fn (voidptr) bool) …
```
=> builtin: cleanup array.v

vlib/v/fmt/fmt.v, vlib/v/fmt/tests/embed_file_keep.vv
v fmt removes the compression type from `$embed_file`.
```diff
- the_other_png := $embed_file('v.png', .zlib)
+ the_other_png := $embed_file('v.png')
```
=> fmt: fix embedfile compression

vlib/toml/parser/parser.v, vlib/toml/tests/value_query_test.v
This PR fixes the following corner case:
```toml
[defaults]
run.flags = ['-f 1']
[[defaults.env]] # <- Before this PR this entry would redefine `defaults`, making `run.flags` disappear
'RUN_PATH' = '$OUT_PATH'
'RUN_TIME' = 5
'TEST_PATH' = '/tmp/test'
```
=> toml: fix implicit allocation overwrite of existing table

vlib/math/erf.v, vlib/math/gamma.v
This change is a workaround for this bug:
```v
import math
import net.websocket
#flag windows -IC:\Program Files\OpenSSL-Win64\include
#flag windows -LC:\Program Files\OpenSSL-Win64\lib
#flag windows -lssl -lcrypto
fn main(){
}
```
```
error: too many basic types
```
This bug occurs because `C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\rpcndr.h` adds a `#define small char`; thus, `small` cannot be used as an identifier anymore (which vlib currently does though).
=> maths: rename small to small_ to prevent C errors

cmd/tools/vast/vast.v, vlib/v/ast/ast.v, vlib/v/gen/c/index.v, vlib/v/parser/parse_type.v, vlib/v/tests/array_access_optimisation_test.v, vlib/v/tests/testdata/test_array_bound.v, vlib/v/transformer/transformer.v
This PR removes boundary checks for array access when using integer literals such as is found in the binary module (and is common in Go).
```
[inline]
pub fn little_endian_u32(b []byte) u32 {
_ = b[3] // bounds check
return u32(b[0]) | (u32(b[1]) << u32(8)) | (u32(b[2]) << u32(16)) | (u32(b[3]) << u32(24))
}
```
The code is also analysing `assert` which may be a preferable way to perform the check, the following code may be considered more idiomatic:
```
[inline]
pub fn little_endian_u32(b []byte) u32 {
assert b.len >= 4
return u32(b[0]) | (u32(b[1]) << u32(8)) | (u32(b[2]) << u32(16)) | (u32(b[3]) << u32(24))
}
```
The AST tree is analysed during the transformer pass, where `IndexExpr` nodes are annotated with a new `is_direct` boolean, indicating that the array index can be safely …
=> transformer: perform direct access to array when the index is known as safe

vlib/v/gen/c/comptime.v, vlib/v/tests/comptime_for_in_field_selector_test.v
This fixes fields with attributes appearing at the end of `.fields`.
```v
module main
struct Abc {
a byte  [test]
b byte
c byte
}
fn decode<T>() {
}
}
fn main() {
decode<Abc>()
}
```
Prints
```
b
c
a
```
Instead of 
```
a
b
c
```
=> cgen: fix order of comptime reflection fields

vlib/v/gen/c/cgen.v, vlib/v/tests/multiple_embed_struct_with_duplicate_field_init_test.v
This PR fix multiple nested embed struct with duplicate field init (fix #12789).
- Fix multiple nested embed struct with duplicate field init.
- Add test.
```vlang
struct Foo {
mut:
x int
}
struct Bar {
Foo
mut:
x int
}
fn main() {
mut b := Bar{
x: 2
}
println(b)
assert b.x == 2
assert b.Foo.x == 0
}
Bar{
Foo: Foo{
x: 0
}
x: 2
}
```
=> cgen: fix multiple nested embed struct with duplicate field init (fix #12789)

vlib/v/gen/c/cgen.v, vlib/v/tests/struct_init_with_interface_field_test.v
This PR fix struct init with interface field (fix #12780).
- Fix struct init with interface field.
- Add test.
```vlang
interface Refresher {
refresh()
}
fn (d Dummy) refresh() {}
struct Source {
mut:
refresher Refresher = Dummy{}
}
struct App {
mut:
src Source
}
fn main() {
mut app := &App{}
app.src = Source{}
println(app)
assert '$app'.contains('refresher: Refresher(Dummy{})')
}
&App{
src: Source{
refresher: Refresher(Dummy{})
}
}
```
=> cgen: fix struct init with interface field (fix #12780)

vlib/v/gen/c/cgen.v
This PR makes a minor cleanup of interface_table() in cgen.v.
- Remove redundant judgement.
=> cgen: clean up interface_table()

vlib/os/os_js.js.v, vlib/os/process.js.v, vlib/os/signal.c.v, vlib/os/signal.js.v, vlib/os/signal.v
- Added `signal_opt` support for JS backend
- Added `signal.v` that contains backend independent code
TODO:
- Add full support for signals on browser backend using custom events
- Add `js.dispatch_event()` type that will work for browser and probably for NodeJS backend too
=> os: Add support for signal handling on JS backend

.github/workflows/gfx_ci.yml, cmd/tools/vgret.defaults.toml, cmd/tools/vgret.v
This PR will add support for testing of arbitrary `gg` based apps for graphical regressions.
The default is just like before (comparing `examples` in V root folder) - and it still works:  `vgret -v -c /tmp/1 /tmp/2`.
I had to introduce a way to list the apps you want tested/grabbed and a way to tweak the parameters for the tools involved.
Most importantly testing V UI graphics regressions is now supported:
`~/.vmodules/ui/vgret.ui_examples.toml`:
```toml
[compare]
method = 'idiff'
flags = ['-p','-fail 0.001','-failpercent 0.2']
[capture]
method = 'gg_record'
[capture.env]
VGG_STOP_AT_FRAME = '8'
VGG_SCREENSHOT_FOLDER = '$OUT_PATH'
VGG_SCREENSHOT_FRAMES = '5'
[[apps]]
path = 'examples/calculator_resizable.v'
[[apps]]
path = 'examples/demo_canvaslayout.v'
```
Run: `~/.vmodules/ui$  v gret …
=> vgret: add support for config via `toml` and root path

vlib/toml/any.v
Like `(a []Any)` has `as_strings()` - `(m map[string]Any)` will now also get a similar convenience function.
=> toml: add `as_strings()` method to map of `Any`

vlib/v/gen/c/cgen.v, vlib/v/tests/struct_init_with_complex_fields_test.v
This PR fix embed struct init with complex fields (fix #12823).
- Fix embed struct init with complex fields.
- Add test.
```vlang
struct Bar {}
type Fnc = fn ()
struct Foo {
Bar
fnc_fn Fnc = voidptr(0)
}
struct App {
mut:
foo Foo
}
fn main() {
println(app)
ret := '$app'
assert ret.contains('Bar: Bar{}')
assert ret.contains('fnc_fn: fn ()')
}
App{
foo: Foo{
Bar: Bar{}
fnc_fn: fn ()
}
}
```
=> cgen: fix embed struct init with complex fields (fix #12823)

vlib/v/tests/array_access_optimisation_test.v, vlib/v/tests/testdata/test_array_bound.v, vlib/v/transformer/transformer.v
It was noticed that the impact of performing array analysis increased overall code generation time by 3/4% which is not negligeable.
The array optimisation is therefore only enabled when the `-prod` flag is used to reduce this overhead.
=> transformer: only enable array optimisation with -prod

vlib/v/gen/c/cgen.v, vlib/v/tests/struct_init_with_complex_fields_test.v
This PR fix embedded struct init with complex fields (fix #12823).
- Fix embedded struct init with complex fields.
- Add test.
```vlang
struct Bar {}
type Fnc = fn ()
struct Foo {
Bar
fnc_fn Fnc = voidptr(0)
}
struct App {
mut:
foo Foo
}
fn main() {
println(app)
ret := '$app'
assert ret.contains('Bar: Bar{}')
assert ret.contains('fnc_fn: fn ()')
}
App{
foo: Foo{
Bar: Bar{}
fnc_fn: fn ()
}
}
```
=> cgen: fix embedded struct init with complex fields (fix #12823)

vlib/v/gen/c/cgen.v
This PR fix error of embedded struct generating interface_table (fix #12839).
```vlang
import ui
struct App {
mut:
window &ui.Window
fc     &FooWidget
}
fn main() {
window: 0
fc: &FooWidget{}
}
app.window = ui.window(
width: 300
height: 300
state: app
children: [app.fc]
)
ui.run(app.window)
}
//---------------------------
struct Foo {
mut:
x      int
y      int
width  int
height int
}
fn (mut c Foo) draw() {}
//-----------------------------------
struct FooWidget {
Foo
mut:
id       string
z_index  int
offset_x int
offset_y int
hidden   bool
}
fn (mut c FooWidget) init(parent ui.Layout) {}
fn (mut c FooWidget) set_pos(x int, y int) {}
fn (c FooWidget) get_pos() (int, int) { return 0, 0 }
fn (c FooWidget) size() (int, int) { return 0, 0 }
fn (mut c FooWidget) draw() {}
fn …
```
=> cgen: fix error of embedded struct generating interface_table (fix #12839)

vlib/v/checker/comptime.v, vlib/v/tests/goto_test.v
This PR fix goto label with comptime tmpl (fix #12842).
- Fix goto label with comptime tmpl.
- Add test.
```vlang
fn main() {
_ := $tmpl('foo.txt')
println('before goto')
unsafe {
goto label
}
println('failed goto')
assert false
label:
println('goto label')
assert true
}
before goto
goto label
```
=> checker: fix goto label with comptime tmpl (fix #12842)

vlib/gg/gg.v
Alright, so here are the changes:
- Added some documentation comments
- Renamed `draw_arc()` -> `draw_slice()`
- Renamed `draw_arc_lines()` -> `draw_empty_slice()`
- Renamed `draw_ring()` -> `draw_arc()`
- Changed `r` in `draw_slice()` to use `f32` instead of `int` as is done in other functions
- Changed `color` in drawing functions to `c`, so that it matches most other functions
- Grouped some related functions together, to avoid the confusion when looking for specific functions. Before there were some functions like `draw_empty_[shape]()` and `draw_[shape]()` that were spread different places in the code. `begin()` and `end()` were also in the middle of the code between all drawing functions, and they were so small I've moved them above the drawing functions.
`gg` seems to be working as …
=> gg: breaking `draw_arc()` and `draw_ring()` renaming + code consistency improvements

vlib/v/checker/checker.v, vlib/v/gen/c/cgen.v, vlib/v/tests/generics_map_with_generic_type_key_test.v
This PR fix generic map with generic type key (fix #12855).
- Fix generic map with generic type key.
- Add test.
```vlang
fn counts<T>(variables []T) map[T]int {
mut tally := map[T]int{}
for var in variables {
tally[var]++
}
return tally
}
fn str_fn() {
a2 := ['1', '2', '3', '4', '5', '3', '1']
ret := counts(a2)
println(ret)
assert ret.len == 5
}
fn int_fn() {
a1 := [1, 2, 3, 4, 5, 2, 3]
ret := counts(a1)
println(ret)
assert ret.len == 5
}
fn float_fn() {
a3 := [0.1, 0.02, 0.3, 4.0, 0.3]
ret := counts(a3)
println(ret)
assert ret.len == 4
}
fn main() {
str_fn()
float_fn()
int_fn()
}
{'1': 2, '2': 1, '3': 2, '4': 1, '5': 1}
{0.1: 1, 0.02: 1, 0.3: 2, 4.: 1}
{1: 1, 2: 2, 3: 2, 4: 1, 5: 1}
```
=> checker, cgen: fix generic map with generic type key (fix #12855)

.cirrus.yml, .github/workflows/ci.yml, vlib/v/pkgconfig/pkgconfig.v
Cirrus CI (the system that we currently use to test V on freebsd) supports running jobs natively on arm64 CPUs, so this PR replaces the Github Actions workflow introduced in #12841 (which instead used qemu to emulate an arm CPU). 
Note that running V and all its tests via this new workflow (7-9 mins) is faster than just building V in the previous one (10 mins).
This also means that this new workflow will still run even if GH Actions is overloaded and queues regular workflows, as it runs in a different CI platform.
***
Example workflow run: https://cirrus-ci.com/task/6514150863011840
=> ci: run the full V test suite on arm64

vlib/v/gen/c/auto_eq_methods.v, vlib/v/tests/array_of_interfaces_equality_test.v
This PR fix array of interfaces equality error (fix #12867).
- Fix array of interfaces equality error.
- Add test.
```vlang
interface IObject {
foo()
}
struct Foo {}
fn (f Foo) foo() {
}
struct Array {
mut:
array []IObject
}
fn (a Array) contains(x IObject) bool {
for element in a.array {
if element == x {
return true
}
}
return false
}
fn main() {
foo := Foo{}
mut ary := Array{}
ary.array << foo
ret := ary.contains(foo)
println(ret)
}
true
```
=> cgen: fix array of interfaces equality error (fix #12867)

vlib/v/gen/c/index.v, vlib/v/tests/nested_map_test.v
This PR fix error of `map_a[map_b[key]] += 2` (fix #12845).
- Fix error of `map_a[map_b[key]] += 2`.
- Add test.
```vlang
fn main() {
m := {
'a': 'x'
}
mut n := {
'x': 1
}
n[m['a']] += 2
println(n)
assert n['x'] == 3
}
{'x': 3}
```
=> cgen: fix error of 'map_a[map_b[key]] += 2' (fix #12845)

vlib/v/gen/c/cgen.v, vlib/v/tests/interface_struct_embedding_test.v
Fixes overwriting methods being ignore by interfaces
Fixes issue where empty methods throw c error in strict mode
=> cgen: fix overwriting methods of embedded structs + empty struct for interfaces

cmd/tools/vtest-self.v, vlib/gg/draw_fns_api_test.v, vlib/gg/gg.c.v, vlib/gg/testdata/draw_elipses.vv, vlib/gg/testdata/draw_polygons.vv
```v
import gg
import gx
import math
struct App {
mut:
gg     &gg.Context
}
fn main() {
gg: 0
}
app.gg = gg.new_context(
width: 200
height: 200
window_title: 'Draw Ellipse'
user_data: app
)
app.gg.run()
}
fn frame(mut app App) {
app.gg.begin()
app.gg.draw_ellipse(100, 100, 100, 50, gx.red)
app.gg.draw_empty_ellipse(100, 100, 50, 25, gx.black)
app.gg.end()
}
```
=> gg: add draw_ellipse() + draw_ellipse_empty() APIs

vlib/builtin/array.v, vlib/v/gen/c/array.v, vlib/v/tests/array_of_map_with_default_test.v
This PR fix array of map init with default value (fix #12862).
- Fix array of map init with default value.
- Add test.
```vlang
fn init_a(n_rows int) []map[int]int {
mut tally := []map[int]int{}
for _ in 0 .. n_rows {
tally << map[int]int{}
}
return tally
}
fn init_b(n_rows int) []map[int]int {
mut tally := []map[int]int{len: n_rows, init: map[int]int{}}
return tally
}
pub fn tallys_in_array(indexs []int, values [][]int, init fn (int) []map[int]int) []map[int]int {
mut tally := init(indexs.len)
for row in 0 .. values.len {
for i, index in indexs {
tally[i][values[row][index]]++
}
}
return tally
}
fn main() {
indexs := [0, 1]
values := [[1, 201], [1, 3], [1, 201], [1, 3]]
out1 := tallys_in_array(indexs, values, init_a)
println(out1)
out2 := tallys_in_array(indexs, values, init_b) …
```
=> builtin, cgen: fix array of map init with default value (fix #12862)

examples/.gitignore, examples/log.v, vlib/log/log.v
Hi,
with this PR I did some small updates to log and related example.
Log interface now is public, so other logging implementations could implement it as a standard signature; I'm looking if/how to write an async logger implementation so at least same signature and other stuff could be used from this base/standard implementation.
There is a new function that given a string, returns related logging level or none, it could be useful when reading log level from a config file for example.
Added a disabled level, it could be useful when logging is not needed (for example during a benchmark, when execution must not slow down with logging and enabled only when needed or only in some code portions, etc); hope you find it useful.
Note that I changed the `fatal` method so even when related logging …
=> Improve logging

vlib/gg/gg.c.v, vlib/gg/testdata/draw_arcs.vv
```V
module main
import math
import gg
import gx
fn main() {
mut context := gg.new_context(
width: 200
height: 200
window_title: 'Arcs'
)
context.run()
}
fn frame(mut ctx gg.Context) {
ctx.begin()
ctx.draw_arc(100, 100, 35, 45, 0, f32(math.radians(290)), 30, gx.red)
ctx.draw_arc_empty(100, 100, 30, 50, 0, f32(math.radians(290)), 30, gx.white)
ctx.end()
}
```
After this PR, I'll be making a PR that renames stuff to use `gg.draw_[shape]_[filltype]`.
=> gg: add draw_arc_empty

cmd/tools/vtest-self.v, vlib/v/gen/c/cheaders.v, vlib/v/gen/c/fn.v, vlib/v/tests/closure_generator_test.v
This doesn't work on master:
```v
x := 1
f := fn [x] (a string) {
println('x: $i')
println('a: $a')
}
f('hi')
```
And neither does this:
```v
x := 1
f := fn [x] (a int, b int, c int, d int, e int, f int, g int, h int) {
println('x: $i')
println('$a $b $c $d $e $f $g $h')
}
f(1, 2, 3, 4, 5, 6, 7, 8)
```
With this PR, both of those examples (and any combination of the two) now work (on amd64 only, currently).
***
Closes #12351 (string arg)
Closes #11990 (struct arg)
=> cgen: support closures with any number of parameters of any size on amd64

vlib/v/gen/c/fn.v, vlib/v/tests/generics_array_of_interface_method_call_test.v
This PR fix generic array of interface method call (fix #12882).
- Fix generic array of interface method call.
- Add test.
```vlang
struct Array<T> {
pub mut:
elements []T
}
struct String {
str string
}
interface IObject {
equals(IObject) bool
}
pub fn (s1 String) equals(s2 IObject) bool {
if s2 is String {
return s1.str == s2.str
}
return false
}
pub fn (mut m Array<T>) contains(e T) bool {
for mut element in m.elements {
if element.equals(e) {
return true
}
}
return false
}
fn main() {
s := String{'hello'}
mut a := Array<IObject>{[s]}
ret := a.contains(IObject(s))
println(ret)
}
true
```
=> cgen: fix generic array of interface method call (fix #12882)

vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v
This PR makes minor cleanup in cgen.v.
- Merge `Gen.typedefs2` into `Gen.typedefs` and remove `Gen.typedefs2`.
- Rename `Gen.tmp_count2` to `Gen.tmp_count_af`.
- Rename `Gen.comptime_defines` to `Gen.comptime_definitions`.
=> cgen: minor cleanup in cgen.v

vlib/v/checker/assign.v, vlib/v/tests/map_selector_assign_test.v
This PR fix error of map selector assign (fix #12900).
- Fix error of map selector assign.
- Add test.
```vlang
struct Test {
mut:
data int
}
fn main() {
mut m := map[int]Test{}
m[0].data = 1
println(m[0].data)
assert m[0].data == 1
}
1
```
=> checker: fix error of map selector assign (fix #12900)

vlib/v/gen/c/auto_eq_methods.v, vlib/v/tests/fixed_array_of_interfaces_equality_test.v
This PR fix fixed array/alias/map of interfaces equality.
- Fix fixed array/alias/map of interfaces equality.
- Add test.
```vlang
interface IObject {
foo()
}
struct Foo {}
fn (f Foo) foo() {
}
struct Array {
mut:
array [1]IObject
}
fn (a Array) contains(x IObject) bool {
for element in a.array {
if element == x {
return true
}
}
return false
}
fn main() {
foo := Foo{}
mut ary := Array{}
ary.array[0] = foo
ret := ary.contains(foo)
println(ret)
assert ret
}
true
```
=> cgen: fix fixed array of interfaces equality

vlib/v/gen/c/cgen.v, vlib/v/tests/interface_method_using_struct_embed_test.v
This PR fix interface method using struct embed  (fix #12918).
- Fix interface method using struct embed.
- Add test.
```vlang
module main
pub interface IObject {
mut:
do_stuff()
do_something_with_int(int)
do_something_with_string(string)
}
pub struct BaseObject {
mut:
some_attr int
}
pub fn (mut base BaseObject) do_stuff() {}
pub fn (mut base BaseObject) do_something_with_int(n int) {}
pub fn (mut base BaseObject) do_something_with_string(s string) {}
pub fn (mut base BaseObject) method_thats_available_to_all_object() {}
pub struct GameObject {
BaseObject
pub mut:
some_attr_for_game int
}
fn main() {
mut common_object := []IObject{}
common_object << GameObject{}
println(common_object)
assert common_object.len == 1
}
[IObject(GameObject{
BaseObject: BaseObject{ …
```
=> cgen: fix interface method using struct embed  (fix #12918)

vlib/v/parser/parser.v, vlib/v/scanner/scanner.v
Change the codegen implementation to use its own parser instance.
Fixes #12857.
Codegen errors should now be displayed properly.
=> parser/scanner: make codegen impl use own parser. closes #12857

vlib/v/parser/parser.v
`'a.b.c'.all_after('.')` returns `b.c`. So current codogen generates `module b.c` from `module a.b.c` . This PR fix it
=> parser: make codegen generates correct module name

vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/tests/blank_ident_test.v
This PR fix blank ident in for_c_stmt (fix #12832).
- Fix blank ident in for_c_stmt.
- Add test.
```vlang
fn main() {
a := []int{len: 2}
for _ := a[1]; a[1] != 0; {
}
}
PS D:\Test\v\tt1> 
```
=> cgen: fix blank ident in for_c_stmt (fix #12832)

vlib/v/gen/c/cgen.v, vlib/v/tests/multiret_with_sumtype_test.v
This PR fix multiple return with sumtype (fix #12927).
- Fix multiple return with sumtype.
- Add test.
```vlang
module main
type Abc = int | rune | string | u32
fn cyz() (Abc, string) {
return 'a', 'b'
}
fn main() {
x, y := cyz()
println(x)
println(y)
assert x == Abc('a')
assert y == 'b'
}
Abc('a')
b
```
=> cgen: fix multiple return with sumtype (fix #12927)

examples/snek/README.md, examples/snek/index.html, examples/snek/snek.js.v, vlib/gg/gg.js.v, vlib/gg/gg.v, vlib/gg/text_rendering.js.v, vlib/gx/color.v, vlib/gx/text.v, vlib/js/dom/dom.js.v, vlib/time/time.js.v, vlib/time/time_js.js.v, vlib/v/gen/js/js.v
- Fixed `voidptr` to any other type cast for JS backend
- Added `time.ticks()` for JS backend, fixed exception thrown on `window.performance.now()` use in `time`
- Added `snek.js.v` to examples/snek. This is exactly the same `snek.v` except all `os` usage was removed so it is possible to run it on browser
=> gg: Text rendering, keyboard event handling for JS and other fixes

.github/workflows/sdl_ci.yml
This PR will add a workflow with checks to make sure `vlang/sdl` can be built.
Previously it was neclected after the org gulped it up this PR should prevent any further regressions :smiling_face_with_tear: 
I've based it on Ubuntu 18.04 since `sdl` currently only supports SDL2 v 2.0.8 - which is what Ubuntu 18.04 provides - it's planned that we support newer versions of SDL2 - but it's WIP - so 2.0.8 should be a fair starting point.
=> ci: add sdl workflow for testing `vlang/sdl`

vlib/js/js.js.v, vlib/v/fmt/fmt.v, vlib/v/fmt/tests/generic_structs_keep.vv, vlib/v/fmt/tests/generic_structs_using_mod_keep.vv, vlib/v/fmt/tests/obj/obj.v, vlib/v/tests/generics_test.v, vlib/v/tests/str_gen_test.v
This PR fix error of generic struct_init using module. (fix #12893)
- Fix error of generic struct_init using module.
- Add test.
```vlang
import obj
struct GenericStruct<A, B> {
}
fn main() {
_ := GenericStruct<obj.Test, obj.Test>{}
}
PS D:\Test\v\tt1> v fmt tt1.v
import obj
struct GenericStruct<A, B> {
}
fn main() {
_ := GenericStruct<obj.Test, obj.Test>{}
}
```
=> fmt: fix error of generic struct_init using module (fix #12893)

vlib/v/gen/c/infix_expr.v, vlib/v/tests/channels_test.v
This PR fix channel of sumtype (fix #12894).
- Fix channel of sumtype.
- Add test.
```vlang
struct Aa {}
struct Ab {}
type As = Aa | Ab
fn func(ch chan As) {
ch <- Aa{}
}
fn main() {
a := chan As{}
go func(a)
ret := <-a
println(ret)
assert '$ret' == 'As(Aa{})'
}
As(Aa{})
```
=> cgen: fix channel of sumtype (fix #12894)

examples/tetris/README.md, examples/tetris/index.html, examples/tetris/tetris.js.v, vlib/os/os_js.js.v, vlib/os/process.js.v, vlib/v/gen/js/builtin_types.v, vlib/v/gen/js/js.v
At the moment `tetris.v` does not fully work on JS backend natively because of some APIs that are not available in JS so the JS version is at `examples/tetris/tetris.js.v`, in the future I'll provide stubs that will allow `tetris.v` and other `gg` examples run natively without changes to the code.
=> js,os: Fix integer arithmetic; add Process.close() and os.is_readable() for VJS; Make tetris run on JS backend

vlib/v/gen/c/assign.v, vlib/v/tests/map_get_assign_blank_test.v
This PR fix map get assign blank var with optional (fix #12942).
- Fix map get assign blank var with optional.
- Add test.
```vlang
fn get_value() int {
mut m := map[string]int{}
_ := m['a'] or { return 1 }
println('a')
return 0
}
fn main() {
ret := get_value()
println(ret)
}
1
```
=> cgen: fix map get assign blank var with optional (fix #12942)

.github/workflows/sdl_ci.yml, examples/2048/2048.v, examples/fireworks/modules/objects/particle.v, examples/fireworks/modules/objects/rocket.v, examples/game_of_life/life_gg.v, examples/gg/draw_pixels.v, examples/gg/polygons.v, examples/gg/rectangles.v, examples/hot_reload/bounce.v, examples/hot_reload/graph.v, examples/snek/snek.v, examples/tetris/tetris.v, vlib/gg/gg.c.v, vlib/gg/testdata/draw_arcs.vv, vlib/gg/testdata/draw_polygons.vv
```v
import gg
import gx
import math
struct App {
mut:
gg &gg.Context
}
fn main() {
gg: 0
}
app.gg = gg.new_context(
width: 200
height: 200
window_title: 'Renaming Test'
user_data: app
)
app.gg.run()
}
fn frame(mut app App) {
app.gg.begin()
app.gg.draw_rect_empty(8, 8, 25, 25, gx.white)
app.gg.draw_rect_filled(10, 10, 20, 20, gx.red)
app.gg.draw_triangle_empty(60, 8, 80, 34, 40, 34, gx.white)
app.gg.draw_triangle_filled(60, 12, 74, 30, 46, 30, gx.red)
//app.gg.draw_circle_empty(110, 10, 10, gx.white) // Not implemented yet
app.gg.draw_circle_filled(110, 20, 8, gx.red)
app.gg.draw_arc_empty(26, 70, 10, 20, f32(math.radians(270)), f32(math.radians(90)), 30, gx.white)
app.gg.draw_arc_filled(26, 70, 12, 18, f32(math.radians(260)), f32(math.radians(100)), 30, …
```
=> gg: renaming drawing functions

cmd/tools/modules/testing/common.v
=> tests: fix typo in common.v

vlib/v/ast/table.v, vlib/v/tests/alias_char_type_reference_test.v
This PR fix reference of alias char type (fix #12946).
- Fix reference of alias char type.
- Add test.
```vlang
module main
type ALchar = char
fn main() {
c1 := &char(0)
c2 := &ALchar(0)
println('${typeof(c1).name} $c1')
assert '$c1' == '0'
println('${typeof(c2).name} $c2')
assert '$c2' == '0'
}
&char 0
&ALchar 0
```
=> ast: fix reference of alias char type (fix #12946)

vlib/adt/doubly_linked_list.v, vlib/adt/doubly_linked_list_test.v
Apologies if someone else was already working on this, I was already playing around with a doubly linked list earlier in the week.
Modeled off of `adt/linked_list.v` with some notable differences:
* ~`len` attribute is public instead of a `len()` method to be consistent with `array`~
* `Node` struct is private
* added the ability to iterate over the list using V's `for` syntax
* it should be safe to modify the list in the loop body as well, though this is not tested and I may be wrong
* added a `delete(idx int)` method
I imagine both this implementation and `linked_list.v` are leaking memory like crazy. Not sure if we should fix that in this PR (by making everything manual-free), let "auto-free" handle it eventually, or make it memory safe in a follow-up PR.
=> adt: Implement doubly linked list

vlib/v/checker/fn.v, vlib/v/tests/generics_array_builtin_method_call_test.v
This PR fix generic array builtin method call (fix #12955).
- Fix generic array builtin method call.
- Add test.
```vlang
struct Container<T> {
mut:
items []T
}
fn (mut c Container<T>) pop() ?T {
x := c.items.pop()
return x
}
struct Item {
data     string
priority int
}
fn main() {
mut a1 := Container<int>{
items: [11, 22]
}
println(a1)
ret1 := a1.pop() or { 0 }
println(ret1)
assert ret1 == 22
item1 := Item{'a', 1}
item2 := Item{'b', 2}
mut a2 := Container<Item>{
items: [item1, item2]
}
println(a2)
ret2 := a2.pop() or { Item{} }
assert ret2 == item2
}
Container<int>{
items: [11, 22]
}
22
Container<Item>{
items: [Item{
data: 'a'
priority: 1
}, Item{
data: 'b'
priority: 2
}]
}
```
=> checker: fix generic array builtin method call (fix #12955)

vlib/v/checker/checker.v, vlib/v/checker/tests/cast_alias_to_byte_err.out, vlib/v/checker/tests/cast_alias_to_byte_err.vv, vlib/v/checker/tests/cast_string_err.out, vlib/v/checker/tests/cast_to_byte_err.out, vlib/v/checker/tests/cast_to_byte_err.vv, vlib/v/checker/tests/struct_type_cast_err.out
This PR check errors of cast to byte.
- Check errors of cast to byte.
- Add test.
```vlang
type SAlias = string
type CAlias = char
type IAlias = int
type UAlias = u32
type FAlias = f32
fn main() {
// should be errors:
_ := byte('hello')
_ := byte(SAlias('hello'))
// should be allowed:
_ := byte(char(1))
_ := byte(int(1))
_ := byte(u32(1))
_ := byte(f32(1.0))
_ := byte(CAlias(1))
_ := byte(IAlias(1))
_ := byte(UAlias(1))
_ := byte(FAlias(1))
}
.\tt1.v:10:10: error: cannot cast type `string` to `byte`
9 |     // should be errors:
10 |     _ := byte('hello')
|          ~~~~~~~~~~~~~
11 |     _ := byte(SAlias('hello'))
12 |
.\tt1.v:11:10: error: cannot cast type `SAlias` to `byte`
9 |     // should be errors:
10 |     _ := byte('hello')
11 |     _ := …
```
=> checker: check errors of cast to byte

vlib/v/checker/checker.v, vlib/v/tests/cast_to_alias_test.v
This PR fix cast enum to alias (fix #12947).
- Fix cast enum to alias.
- Add test.
```vlang
module main
type CEnum = int
enum Enum {
value = 1
}
fn foo(n int) string {
return '$n'
}
fn bar(n CEnum) string {
return '$n'
}
fn test_cast_to_alias() {
e := Enum.value
mut ret_str := ''
ret_str = foo(int(e))
println(ret_str)
assert ret_str == '1'
ret_str = bar(int(e))
println(ret_str)
assert ret_str == '1'
ret_str = foo(CEnum(e))
println(ret_str)
assert ret_str == '1'
ret_str = bar(CEnum(e))
println(ret_str)
assert ret_str == '1'
}
1
1
1
1
```
=> checker: fix cast enum to alias (fix #12947)

vlib/builtin/option.v, vlib/v/tests/string_optional_none_test.v
This PR add none str() to fix #12964.
- Add none str().
- Add test.
```vlang
struct MyError {
code int
msg  string
}
fn foo() int | none | IError {
return IError(MyError{})
}
fn test_string_optional_none() {
x := foo()
println(x)
}
(int | none | IError)(MyError: )
```
=> builtin: add none str() (fix #12964)

vlib/v/checker/fn.v, vlib/v/checker/tests/js_with_non_js_backend_too_many_arguments.out, vlib/v/checker/tests/js_with_non_js_backend_too_many_arguments.vv
Fixes this crash:
```
$ cat a.v
fn JS.Foo.bar() bool
JS.Foo.bar(123)
$
$ v a.v
V panic: array.get: index out of range (i == 0, a.len == 0)
v hash: 3528239
0   v                                   0x000000010ddc2f4c array_get + 252
1   v                                   0x000000010deb05d2 v__checker__Checker_fn_call + 16498
2   v                                   0x000000010dea6f17 v__checker__Checker_call_expr + 119
3   v                                   0x000000010de821a5 v__checker__Checker_expr + 3685
4   v                                   0x000000010de96852 v__checker__Checker_stmt + 2130
5   v                                   0x000000010dea6d71 v__checker__Checker_stmts_ending_with_expression + 289
6   v                                   0x000000010debbe26 …
```
=> cgen: check call argument on methods

vlib/v/ast/table.v, vlib/v/tests/generic_fn_multi_return_test.v
This PR fix generic fn with multiple return (fix #12960).
- Fix generic fn with multiple return.
- Add test.
```vlang
fn main() {
mut a1 := GenRef<u32, u32>{32, 99}
b1, c1 := a1.generic_reference() ?
println(b1)
assert b1 == 32
println(c1)
assert *c1 == 99
mut a2 := GenRef<u64, u64>{322, 999}
b2, c2 := a2.generic_reference() ?
println(b2)
assert b2 == 322
println(c2)
assert *c2 == 999
mut a3 := GenRef<i32, u64>{22, 77}
b3, c3 := a3.generic_reference() ?
println(b3)
assert b3 == 22
println(c3)
assert *c3 == 77
mut a4 := GenRef<f64, u64>{2.2, 777}
b4, c4 := a4.generic_reference() ?
println(b4)
assert b4 == 2.2
println(c4)
assert *c4 == 777
}
struct GenRef<K, V> {
key K
val V
}
fn (mut self GenRef<K, V>) generic_reference() ?(K, &V) {
if false {
return none
}
return self.key, unsafe { …
```
=> ast: fix generic fn with multiple return (fix #12960)

vlib/v/checker/tests/assign_var_redefinition_err.out, vlib/v/checker/tests/assign_var_redefinition_err.vv, vlib/v/parser/assign.v
This PR check variable redefinition error (fix #12991).
- Check variable redefinition error.
- Add test.
```vlang
fn main() {
println(test('whatever'))
}
fn test(aaaa string) string {
aaaa := 'bbbb' + aaaa
return aaaa
}
.\tt1.v:6:2: error: redefinition of `aaaa`
4 |
5 | fn test(aaaa string) string {
6 |     aaaa := 'bbbb' + aaaa
|     ~~~~
7 |     return aaaa
8 | }
```
=> parser: check variable redefinition error (fix #12991)

vlib/builtin/int.v, vlib/builtin/int_test.v, vlib/v/tests/interface_edge_cases/pass_voidptr_as_interface_reference_test.v, vlib/v/tests/interface_edge_cases/voidptr_casted_as_an_interface_test.v, vlib/v/tests/pointers_multilevel_casts_test.v
This PR add charptr str() and change string format (fix #12959).
- Add charptr str() and change string format.
- Modify voidptr/byteptr str() format, `0x2`.
- Add test.
```vlang
fn main() {
ohm := charptr(0)
println(ohm.str())
}
0x0
```
=> builtin: add charptr str() and change string format (fix #12959)

vlib/v/checker/fn.v, vlib/v/checker/tests/unknown_function.out, vlib/v/checker/tests/unknown_function.vv
This PR check using const var as function (fix #13002).
- Check using const var as function.
- Add test.
```vlang
import math
fn main() {
println(math.max_i64())
}
.\tt1.v:4:15: error: unknown function: math.max_i64
2 |
4 |     println(math.max_i64())
|                  ~~~~~~~~~
5 | }
```
=> checker: check using const var as function (fix #13002)

cmd/tools/vshader.v, examples/sokol/01_cubes/cube.v, examples/sokol/02_cubes_glsl/cube_glsl.v, examples/sokol/03_march_tracing_glsl/rt_glsl.v, examples/sokol/04_multi_shader_glsl/rt_glsl.v, examples/sokol/05_instancing_glsl/rt_glsl.v, examples/sokol/06_obj_viewer/modules/obj/rend.v, examples/sokol/06_obj_viewer/modules/obj/struct.v, examples/sokol/06_obj_viewer/show_obj.v, examples/sokol/drawing.v, examples/sokol/fonts.v, examples/sokol/freetype_raven.v, examples/sokol/particles/particles.v, examples/ttf_font/example_ttf.v, examples/viewer/view.v, examples/viewer/zip_container.v, vlib/gg/gg.c.v, vlib/gg/image.c.v, vlib/sokol/gfx/gfx.c.v, vlib/sokol/gfx/gfx_structs.c.v, vlib/sokol/gfx/gfx_utils.c.v, vlib/sokol/sapp/sapp.c.v, vlib/sokol/sgl/sgl.c.v, vlib/v/fmt/tests/c_struct_init_keep.vv, vlib/x/ttf/README.md, vlib/x/ttf/render_sokol_cpu.v
This PR adds public type aliases for all exposed sokol_gfx structs - resulting in significantly less `C.` prefixes in existing code.
=> sokol: type alias all `gfx` structs

vlib/regex/README.md, vlib/regex/regex_test.v, vlib/regex/regex_util.v
- Added a replace N instances function:
```v
// replace_n return a string where the firts `count` matches are replaced with the repl_str string
// `count` indicate the number of max replacements that will be done.
// if count is > 0 the replace began from the start of the string toward the end
// if count is < 0 the replace began from the end of the string toward the start
// if count is 0 do nothing
pub fn (mut re RE) replace_n(in_txt string, repl_str string, count int) string
```
example:
```v
fn rest_regex_replace_n(){
s := "dario 1234 pepep 23454 pera"
query := r"\d+"
mut re := regex.regex_opt(query) or { panic(err) }
assert re.replace_n(s, "[repl]", 0) == "dario 1234 pepep 23454 pera"
assert re.replace_n(s, "[repl]", -1) == "dario 1234 pepep [repl] pera"
assert …
```
=> Regex: added replace_n function

vlib/net/address.v
=> net: fix typo in new_ip()

examples/sokol/01_cubes/cube.v, examples/sokol/02_cubes_glsl/cube_glsl.v, examples/sokol/03_march_tracing_glsl/rt_glsl.v, examples/sokol/04_multi_shader_glsl/rt_glsl.v, examples/sokol/06_obj_viewer/show_obj.v, examples/sokol/drawing.v, examples/sokol/fonts.v, examples/sokol/freetype_raven.v, examples/sokol/particles/particles.v, examples/viewer/view.v, vlib/gg/gg.c.v, vlib/sokol/gfx/enums.v, vlib/sokol/sgl/enums.v, vlib/sokol/sgl/sgl.c.v, vlib/sokol/sgl/sgl_funcs.c.v, vlib/sokol/sgl/sgl_structs.c.v
This PR is much like #13014, though it adds support for the new `sgl_context` type also.
The type makes it possible to render with different render passes with sokol_gl.h.
More on `sgl_context` [here](https://github.com/floooh/sokol-samples/blob/master/sapp/sgl-context-sapp.c) and an example [here](https://floooh.github.io/sokol-html5/sgl-context-sapp.html)
=> sokol: type alias all `sgl` structs, support `sgl_context`

vlib/net/address.v, vlib/net/address_test.v
This PR fix errors of new_ip(), new_ip6() and ip6.str().
- `copy(a.addr.Ip.addr[..], addr[..])` cannot change fixed array `a.addr.Ip.addr`.
- use `unsafe { vmemcpy(&a.addr.Ip.addr[0], &addr[0], 4) }`.
- Fix ip6.str().
- Add tests in address_test.v.
=> net: fix errors of new_ip(), new_ip6() and ip6.str()

vlib/v/ast/table.v, vlib/v/gen/c/cgen.v, vlib/v/tests/const_fixed_array_of_reference_value_test.v
This PR fix const fixed array of reference value.
- Fix const fixed array of reference value.
- Add test.
```vlang
const (
foo         = u32(1)
bar         = u32(2)
weapon_keys = [&foo, &bar]!
)
fn main() {
assert weapon_keys[0] == &foo
assert weapon_keys[1] == &bar
}
```
=> ast, cgen: fix const fixed array of reference value

vlib/v/gen/c/cgen.v
This PR fix const fixed array of reference var using correct pointer.
```vlang
typedef u32* Array_fixed_u32_ptr1_2 [2];
```
=> cgen: fix const fixed array of reference var using correct pointer

vlib/v/ast/table.v, vlib/v/tests/anon_fn_with_alias_args_test.v
This PR fix anon fn with alias arguments.
- Fix anon fn with alias arguments.
- Add test.
```vlang
type MyString = string
type MyInt = int
struct S1 {
x fn (a int) MyString
}
struct S2 {
y fn (a int) MyInt
}
fn get_string(a int) MyString {
return '$a'
}
fn get_int(a int) MyInt {
return a
}
fn main() {
s1 := S1{
x: get_string
}
println(s1.x)
ret1 := s1.x(22)
println(ret1)
assert ret1 == '22'
s2 := S2{
y: get_int
}
println(s2.y)
ret2 := s2.y(22)
println(ret2)
assert ret2 == 22
}
fn (int) MyString
22
fn (int) MyInt
22
```
```vlang
typedef main__MyString (*anon_fn_int__main__MyString)(int);
typedef main__MyInt (*anon_fn_int__main__MyInt)(int);
```
=> ast: fix anon fn with alias arguments

vlib/v/checker/checker.v, vlib/v/tests/cast_in_comptime_if_test.v
This PR fix cast to byte in comptime if (fix #13035).
- Fix cast to byte in comptime if.
- Add test.
```vlang
fn main() {
generic_bool(true)
}
fn generic_bool<T>(val T) {
$if T is bool {
println(byte(val))
assert byte(val) == 1
println(i8(val))
assert i8(val) == 1
println(i16(val))
assert i16(val) == 1
} $else {
assert false
}
}
1
1
1
```
=> checker: fix cast to byte in comptime if (fix #13035)

vlib/v/gen/c/cgen.v
It probably needs to be discussed if `trim_left` needs to be renamed to something like `trim_charset_left`, to distinguish it from `trim_prefix`, to prevent hard to catch bugs.
=> cgen: fix cgen remove random chars from you parameter_name

examples/2048/2048.v, examples/term.ui/text_editor.v, vlib/math/abs.v, vlib/math/big/array_ops.v, vlib/math/big/integer.v, vlib/math/big/special_array_ops.v, vlib/math/math.v, vlib/math/mathutil.v, vlib/math/mathutil_test.v, vlib/math/util/util.v, vlib/net/openssl/ssl_connection.v, vlib/toml/scanner/scanner.v, vlib/v/fmt/align.v, vlib/v/fmt/fmt.v, vlib/v/fmt/struct.v, vlib/v/mathutil/mathutil.v, vlib/v/mathutil/mathutil_test.v, vlib/v/scanner/scanner.v, vlib/v/tests/generics_method_on_generic_structs_test.v, vlib/v/util/errors.v, vlib/x/ttf/render_bmp.v, vlib/x/ttf/ttf_test.v
This PR deprecates both `math.mathutil` and `math.util`, by moving the generic
functions min/max/abs to `math`.
=> math: move the `math.mathutil` generic `min`/`max`/`abs` fns to `math`

vlib/sqlite/sqlite.v
added a function to set busy_timout.
https://www.sqlite.org/c3ref/busy_timeout.html
=> sqlite: add busy_timeout()

vlib/v/gen/c/auto_eq_methods.v, vlib/v/gen/c/auto_free_methods.v, vlib/v/gen/c/auto_str_methods.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/dumpexpr.v, vlib/v/tests/alias_fixed_array_of_struct_test.v
This PR fix alias fixed array of struct (fix #13037).
- Fix alias fixed array of struct.
- Add test.
```vlang
struct Foo {}
type Bar = [4]Foo
fn main() {
bar := Bar([Foo{}, Foo{}, Foo{}, Foo{}]!)
println(bar)
assert '$bar' == 'Bar([Foo{}, Foo{}, Foo{}, Foo{}])'
}
Bar([Foo{}, Foo{}, Foo{}, Foo{}])
```
=> cgen: fix alias fixed array of struct (fix #13037)

cmd/tools/vtest-all.v, vlib/builtin/builtin.c.v, vlib/builtin/linux_bare/libc_impl.v, vlib/builtin/linux_bare/linux_syscalls.v, vlib/builtin/linux_bare/memory_managment.v, vlib/dlmalloc/dlmalloc.v, vlib/dlmalloc/dlmalloc_sys_nix.c.v, vlib/dlmalloc/global.v, vlib/strconv/bare/str_array_example.v, vlib/v/builder/rebuilding.v, vlib/v/gen/c/cgen.v, vlib/v/util/util.v
In this PR when code is compiled with `-freestanding` flag, `malloc` and `free` calls will use dlmalloc as default allocator instead of mmap/munmap. In the future this should allow us to get freestanding work on Windows/macOS/WASM/etc and not only Linux
=> builtin: Use dlmalloc for freestanding backend

vlib/sokol/sfons/sfons.c.v
=> sokol: fix missing import in `sfons`. Fixes #13061

vlib/v/checker/fn.v, vlib/v/tests/generics_with_nested_generics_fn_inst_call_test.v
This PR fix generics with nested generic fn inst call (fix #13056).
- Fix generics with nested generic fn inst call.
- Add test.
```vlang
fn main() {
value := [byte(105), 116, 32, 119, 111, 114, 107, 115, 33, 33]
decoded := decode_arr<string>(value)
dump(decoded)
assert decoded.len == 4
assert decoded[0] == 'it works!!'
assert decoded[1] == 'it works!!'
assert decoded[2] == 'it works!!'
assert decoded[3] == 'it works!!'
}
fn decode_arr<T>(buf []byte) []T {
arr_size := decode<u32>(buf[0..4])
mut ret := []T{cap: int(arr_size)}
for _ in 0 .. arr_size {
ret << decode<T>(buf[..])
}
return ret
}
fn decode<T>(buf []byte) T {
$if T is u32 {
return u32(buf.len)
} $else $if T is string {
return buf.bytestr()
} $else {
panic('"$T.name" is not supported for `decode`')
}
} …
```
=> checker: fix generics with nested generic fn inst call (fix #13056)

vlib/v/checker/checker.v, vlib/v/tests/cast_to_u8_test.v
This PR fix error for cast to u8 (fix #13057).
- Fix error for cast to u8.
- Add test.
```vlang
module main
fn main() {
r1 := u8(byte(1))
println(r1)
assert '$r1' == '1'
r2 := u8(byte(true))
println(r2)
assert '$r2' == '1'
r3 := u8(true)
println(r3)
assert '$r3' == '1'
}
1
1
1
```
=> checker: fix error for cast to u8 (fix #13057)

vlib/v/checker/checker.v, vlib/v/tests/cast_to_u8_test.v
This PR fix error for cast to u8.
* Fix error for cast `i8` & `char` to u8.  (related to #13058)
* Add test.
=> checker: fix error for cast to u8

vlib/v/gen/c/comptime.v, vlib/v/tests/comptime_call_in_fn_call_test.v
This PR fix comptime call in fn call  (fix #13073).
- Fix comptime call in fn call.
- Add test.
```vlang
struct Foo {}
fn (f Foo) a() string {
return 'method_a'
}
fn (f Foo) b() string {
return 'method_b'
}
fn main() {
f := Foo{}
$for method in Foo.methods {
x := f.$method()
println(x)
println(f.$method())
rets << get_string(f.$method())
}
assert rets[0] == 'method_a'
assert rets[1] == 'method_b'
}
fn get_string(s string) string {
return s
}
method_a
method_a
method_b
method_b
```
=> cgen: fix comptime call in fn call  (fix #13073)

vlib/v/gen/c/index.v, vlib/v/tests/string_index_in_for_mut_in_test.v
This PR fix string range index in for mut var in (fix #13074).
- Fix string range index in for mut var in.
- Add test.
```vlang
module main
[heap]
pub struct Grid {
pub mut:
header []string
}
fn main() {
h := ['yore', 'yaya']
mut grid := Grid{
header: h
}
wrap_text(mut grid)
}
fn wrap_text(mut gv Grid) {
for mut ch in gv.header {
ch = ch[1..2]
}
println(gv)
assert gv.header == ['o', 'a']
}
Grid{
header: ['o', 'a']
}
```
=> cgen: fix string range index in for mut var in (fix #13074)

vlib/builtin/linux_bare/libc_impl.v, vlib/builtin/linux_bare/memory_managment.v, vlib/builtin/wasm_bare/libc_impl.v, vlib/builtin/wasm_bare/memory_management.v, vlib/dlmalloc/dlmalloc.v
In the next PR I'll add `-wasm` flag for compiling to WASM using clang. This PR just contains minimal libc replacement and code for allocating WASM pages in order for dlmalloc to work
=> builtin: Add builtin/wasm_bare 

vlib/v/checker/checker.v, vlib/v/checker/comptime.v
This PR will add support for using `apk` in comptime ifs - like this:
```v
pub fn read_apk_asset(file string) ?[]byte {
$if apk {
...
buf := []byte{}
...
return buf
} $else {
return []byte{len: 0}
}
}
```
This is a preparation to fix a bug regarding the use of `-os android` *without* the `-apk` flag which is currently broken:
`v -os android -o /tmp/android_v.c examples/toml.v`
```
vlib/os/os_android.c.v:22:30: error: unknown function: C.sapp_android_get_native_activity
20 | 
21 | pub fn read_apk_asset(file string) ?[]byte {
22 |     act := &C.ANativeActivity(C.sapp_android_get_native_activity())
|                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
23 |     if isnil(act) {
24 |         return error('Could not get reference to Android activity')
```
A follow up PR for fixing …
=> checker: add support for apk in comptime if

vlib/v/parser/tmpl.v, vlib/v/tests/tmpl/selective_interpolation_in_script_tag.html, vlib/v/tests/tmpl_script_tag_interpolation_test.v
Trimming spaces (with trim_space method) in line before the start of searching of tag was done because the method will fail to recognize tag if there are spaces (tabs) before the tag.
For example, the next tag hasn't been recognized as _script_ tag because of formatting, and the **<script>** section contained a wrong code after template processing.
```
<script>
````
V templates were turned off for **<script>** and **<style>** blocks because CSS and JS have their own '@' sign.
This PR provides a way to allow treat '@' sign as a V template and behaves in the same way as HTML V templates. To do that, a user should provide a comment //V_TEMPLATE in a line where '@' sing was used.
```html
// V won't parse that
<script>
var labels = @benchmark_plot_data.dates;
var values = …
```
=> tmpl.v: fix of is_html_open_tag function and allow usage of V template sign '@' in JS code

vlib/v/ast/ast.v, vlib/v/fmt/fmt.v, vlib/v/fmt/tests/sum_attributes_keep.vv, vlib/v/parser/parser.v
This PR adds a field `attrs` to `v.ast.SumType`
- add field to `v.ast.SumType`
- set value at `v.parser`
```v
[attr; name: 'it works!']
type SumTyp = Aiu | None
// ...
```
```
v.ast.TypeDecl(v.ast.SumTypeDecl{
name: 'SumTyp'
is_pub: false
pos: v.token.Position{
len: 11
line_nr: 1
pos: 26
col: 0
last_line: 1
}
comments: []
typ: ast.Type(0x21 = 33)
generic_types: []
attrs: [attr, name: 'it works!']
...
```
=> ast: support attributes for `ast.SumType`

vlib/toml/scanner/scanner.v
Feel free to close the PR if it doesn't make sense to you.
Allows the Toml test cases to be passed again under Windows.
=> toml: fix comment ends with crlf

vlib/v/ast/table.v, vlib/v/tests/generics_with_nested_generic_type_parameter_test.v
This PR fix generics with nested generic type parameter  (fix #13077).
- Fix generics with nested generic type parameter.
- Add test.
```vlang
module main
pub struct Randomizer<T> {
}
pub struct Element<T> {
}
fn main() {
a := new_randomizer<int>()
println(a)
assert '$a' == '&Randomizer<int>{}'
}
pub fn new_randomizer<T>() &Randomizer<T> {
return &Randomizer<T>{}
}
pub fn (mut r Randomizer<T>) add_multiple(elements []Element<T>) {
}
&Randomizer<int>{}
```
=> ast: fix generics with nested generic type parameter  (fix #13077)

vlib/v/checker/tests/anon_fn_arg_type_err.out, vlib/v/checker/tests/anon_fn_arg_type_err.vv, vlib/v/parser/fn.v
This PR check error of anon fn argument type (fix #13096).
- Check error of anon fn argument type.
- Add test.
```vlang
module main
fn main() {
mut i := 1
func := fn (i) int {
return i
}
println(func(i) == 1)
}
.\tt1.v:8:10: error: undefined ident: `i`
6 |
7 |     func := fn (i) int {
8 |         return i
|                ^
9 |     }
10 |
.\tt1.v:7:14: error: unknown type `i`
5 |     mut i := 1
6 |
7 |     func := fn (i) int {
|                 ^
8 |         return i
9 |     }
.\tt1.v:11:15: error: cannot use `int` as `i` in argument 1 to `func`
9 |     }
10 |
11 |     println(func(i) == 1) // true
|                  ^
12 | }
```
=> parser: check error of anon fn argument type (fix #13096)

vlib/v/checker/containers.v, vlib/v/checker/tests/array_init_with_void_value_err.out, vlib/v/checker/tests/array_init_with_void_value_err.vv
This PR check array init with void type value (fix #13095).
- Check array init with void type value.
- Add test.
```vlang
module main
fn main() {
a := [yo()]
println(a)
}
fn yo() {}
.\tt1.v:4:8: error: invalid void array element type
2 | 
4 |     a := [yo()]
|           ~~~~
5 |     println(a)
6 | }
```
=> checker: check array init with void type value (fix #13095)

vlib/v/gen/c/fn.v, vlib/v/tests/comptime_for_method_call_in_print_call_test.v
This PR fix error for print comptime for method call (fix #13093).
- Fix error for print comptime for method call.
- Add test.
```vlang
module main
struct S1 {}
fn main() {
s1 := S1{}
$for method in S1.methods {
println(s1.$method('ll'))
rets << s1.$method('ll').str()
}
assert rets.len == 4
assert rets[0] == '7'
assert rets[1] == '7.7'
assert rets[2] == 'foo'
assert rets[3] == 'true'
}
fn (t S1) m1(s string) int {
return 7
}
fn (t S1) m2(s string) f64 {
return 7.7
}
fn (t S1) m3(s string) string {
return 'foo'
}
fn (t S1) m4(s string) bool {
return true
}
7
7.7
foo
true
```
=> cgen: fix error for print comptime for method call (fix #13093)

vlib/v/checker/containers.v, vlib/v/tests/option_empty_map_test.v
This PR fix returning optional empty map (fix #13111).
- Fix returning optional empty map.
- Add test.
```vlang
fn opt() ?map[string]string {
return {}
}
fn main() {
x := opt() or {
assert false
return
}
dump(x)
assert '$x' == '{}'
}
[.\\tt1.v:10] x: {}
```
=> checker: fix returning optional empty map (fix #13111)

vlib/v/checker/tests/comptime_call_method_args_err.out, vlib/v/checker/tests/comptime_call_method_args_err.vv, vlib/v/gen/c/comptime.v
This PR check error for comptime call method argument (fix #13107).
- Check error for comptime call method argument.
- Add test.
```vlang
module main
struct S1 {}
fn main() {
s1 := S1{}
$for method in S1.methods {
println(s1.$method('yo'))
}
}
fn (t S1) method_hello() string {
return 'Hello'
}
.\tt1.v:9:14: cgen error: expected 0 arguments to method S1.method_hello, but got 1
7 |
8 |     $for method in S1.methods {
9 |         println(s1.$method('yo'))
|                    ~~~~~~~~~~~~~
10 |     }
11 | }
```
=> cgen: check error for comptime call method argument (fix #13107)

vlib/v/gen/c/cgen.v, vlib/v/gen/c/cheaders.v, vlib/x/json2/decoder.v, vlib/x/json2/encoder.v
Adds `VNOFLOAT` define to output C file and typedefs f32 and f64 to int32_t and int64_t so if you compile to target that does not have support for float and double compiler will not panic. Also changes `json2` part of usage of f32 and f64 so it works with -nofloat properly
=> cgen,json2: Better -nofloat support

cmd/tools/vcomplete.v
This PR adds support for tab completing paths starting with `~` and `/`.
Before `vcomplete` would return an empty list in these cases.
=> vcomplete: add support for ~ and absolute paths

vlib/v/checker/match.v, vlib/v/checker/tests/match_cond_with_parenthesis_err.out, vlib/v/checker/tests/match_cond_with_parenthesis_err.vv
This PR check error for match conditions with parenthesis (fix #13121).
- Check error for match conditions with parenthesis.
- Add test.
```vlang
module main
enum Enum {
a
b
c
}
fn foo() ?Enum {
return .a
}
fn bar() bool {
return match (foo()) {
.a { true }
.b, .c { false }
}
}
fn main() {
bar()
}
.\tt1.v:14:15: error: unnecessary `()` in `match` condition, use `match expr {` instead of `match (expr) {`.
12 |
13 | fn bar() bool {
14 |     return match (foo()) {
|                  ~~~~~~~
15 |         .a { true }
16 |         .b, .c { false }
```
=> checker: check error for match conditions with parenthesis (fix #13121)

vlib/builtin/rune.v, vlib/builtin/rune_test.v
It can be helpful to get the utf-8 bytes from a unicode rune, so this makes it one step easier.
```v
// previously
utf8_bytes := `★`.str().bytes() // [0xe2, 0x98, 0x85]
// now
utf8_bytes := `★`.bytes() // [0xe2, 0x98, 0x85]
```
=> fix: adding a bytes convenience method to runes just like for strings

vlib/v/gen/c/cgen.v, vlib/v/tests/cast_in_index_of_ref_fixed_array_test.v
This PR fix cast in the index of reference fixed array (fix #13128).
- Fix cast in the index of reference fixed array.
- Add test.
```vlang
type Entity = int
struct Component {
vals [256]int
}
fn (c Component) get_broken(e Entity) &int {
return &c.vals[int(e)]
}
fn main() {
c := Component{}
a := c.get_broken(Entity(10))
println(*a)
assert *a == 0
}
0
```
=> cgen: fix cast in the index of reference fixed array (fix #13128)

vlib/builtin/builtin_d_gcboehm.c.v
If this does not make sense from the project's point of view, please just close it.
This workaround allows Windows users to link against gc boehm with self-compiled shared or static gc boehm libs.
To do this, one just needs to add an additional flag to the v-source, such as.
~~~V
$if msvc {
// #flag -lD:\\ProgramData\\Compiler\\gc-8.0.4\\gc64_dll  // 64bit dll usage
#flag -lD:\\ProgramData\\Compiler\\gc-8.0.4\\gc        // static lib usage
}
fn main() { 
println('I was build with boehm')
}
~~~
=> builtin: allow Windows users to link against gc boehm

vlib/v/ast/ast.v, vlib/v/fmt/fmt.v, vlib/v/parser/if_match.v, vlib/v/tests/if_guard_test.v
fixes https://github.com/vlang/v/issues/8944
=> parser: add support for mutable if guards

vlib/v/gen/c/comptime.v, vlib/v/tests/comptime_if_expr_generic_typ_is_type_test.v
This PR fix comptime if expr T.typ is type (fix #13118).
- Fix comptime if expr T.typ is type.
- Add test.
```vlang
module main
fn write<T>(out T) string {
$if T.typ is bool {
println('FOO')
return 'FOO'
} $else $if T.typ !is bool {
println('BAR')
return 'BAR'
}
return 'EMPTY'
}
fn main() {
mut val := false
ret := write<bool>(val)
assert ret == 'FOO'
}
FOO
```
=> cgen: fix comptime if expr T.typ is type (fix #13118)

vlib/v/gen/c/fn.v, vlib/v/tests/fn_call_mut_sumtype_args_test.v
This PR fix fn call with mut sumtype argument (fix #13122).
- Fix fn call with mut sumtype argument.
- Add test.
```vlang
type Sum = Struct1 | int
struct Struct1 {
mut:
value int
}
fn update_sum(mut sum Sum) {
match mut sum {
Struct1 {
sum.value = 42
}
else {}
}
}
fn main() {
mut s := Sum(Struct1{
value: 6
})
update_sum(mut s)
if mut s is Struct1 {
println(s.value)
assert s.value == 42
} else {
assert false
}
}
42
```
=> cgen: fix fn call with mut sumtype argument (fix #13122)

cmd/tools/vcheck-md.v
All I did was include the required line lengths in the error messages.
=> fix: better error messages for check-md tool

examples/gg/worker_thread.v, examples/hot_reload/bounce.v, examples/hot_reload/graph.v, vlib/gg/gg.c.v, vlib/gg/text_rendering.c.v, vlib/gg/text_rendering.v, vlib/os/font/font.v
As discussed on [Discord](<https://discord.com/channels/592103645835821068/592320321995014154/930791812514328576>) this PR will move a few font related functions out in their own module under `os.font`.
One of the reasons is that fonts and font paths aren't always solely needed for graphical apps - so importing `gg` everytime you need to get a default font is not good in systems that doesn't need (or even have) graphics available.
A relevant example is currently if you want to get a default font for your `vlang/sdl` app you'll need to import all of `gg` as well - although we only need `sdl`.
=> os: add font module, move from gg

vlib/v/ast/ast.v, vlib/v/checker/struct.v, vlib/v/parser/fn.v, vlib/v/parser/parser.v, vlib/v/parser/struct.v, vlib/v/tests/generics_struct_field_with_default_struct_value_test.v
This PR fix generic struct field with default struct value (fix #13087).
- Fix generic struct field with default struct value.
- Add test.
```vlang
module main
struct None {}
type OptError = None | string
struct Opt<T> {
value T
error OptError = None{}
}
struct MessageModify {
text Opt<string>
}
fn main() {
edit_query := MessageModify{Opt<string>{
value: 'Hello there!'
}}
println(edit_query)
assert edit_query.text.value == 'Hello there!'
}
MessageModify{
text: Opt<string>{
value: 'Hello there!'
error: OptError(None{})
}
}
```
=> ast, parser, checker: fix generic struct field with default struct value (fix #13087)

vlib/builtin/string.v, vlib/builtin/string_int_test.v
`strconv.parse_int` and `strconv.parse_uint` are now exposed as methods on a string so that parsing can return an optional without importing all of `strconv`
```v
fn test_parse() {
assert i64(1) == '1'.parse_int(0, 8) or { 0 }
assert i64(1) == '0b01'.parse_int(0, 8) or { 0 }
assert i64(1) == '01'.parse_int(0, 8) or { 0 }
assert i64(1) == '0o01'.parse_int(0, 8) or { 0 }
assert i64(1) == '0x01'.parse_int(0, 8) or { 0 }
assert i64(1) == '1'.parse_int(2, 8) or { 0 }
assert i64(1) == '1'.parse_int(8, 8) or { 0 }
assert i64(1) == '1'.parse_int(10, 8) or { 0 }
assert i64(1) == '1'.parse_int(16, 8) or { 0 }
assert u64(1) == '1'.parse_uint(0, 8) or { 0 }
assert u64(1) == '0b01'.parse_uint(0, 8) or { 0 }
assert u64(1) == '01'.parse_uint(0, 8) or { 0 }
assert u64(1) == '0o01'.parse_uint(0, 8) or { 0 …
```
=> exposing parse_int as method on string

vlib/v/gen/c/fn.v, vlib/v/tests/generics_method_with_sumtype_args_test.v
This PR fix generics method with sumtype arguments (fix #13155).
- Fix generics method with sumtype arguments.
- Add test.
```vlang
module main
fn main() {
mut me := CatDad{}
ret := me.adopt<CatType, Cat>(CatType.black, BlackCat{})
println(ret)
}
[flag]
enum CatType {
black
white
}
type Cat = BlackCat | WhiteCat
struct BlackCat {}
struct WhiteCat {}
struct CatDad {}
fn (mut foo CatDad) adopt<D, T>(d D, t T) int {
return 22
}
------------
22
```
=> cgen: fix generics method with sumtype arguments (fix #13155)

vlib/v/checker/fn.v, vlib/v/checker/tests/anon_fn_arg_type_err.out
Anon functions didn't properly check for unnamed args in some cases(e.g. struct types) and therefor resulted in a C compiler error. I already closed my associated issue( #13148 )
=> anon_fn: fixed unrecognized empty argnames

vlib/v/ast/ast.v, vlib/v/checker/containers.v, vlib/v/gen/c/array.v, vlib/v/tests/array_of_sumtype_with_default_test.v
This PR fix array of sumtypes with default (fix #13173 fix #13174).
- Fix array of sumtypes with default.
- Add test.
```vlang
type Abc = int | string
fn main() {
a1 := []Abc{len: 1, init: 22}
println(a1)
assert '$a1' == '[Abc(22)]'
a2 := []Abc{len: 1, init: 'hello'}
println(a2)
assert '$a2' == "[Abc('hello')]"
}
```
---
```vlang
[Abc(22)]
[Abc('hello')]
```
=> ast, checker, cgen: fix array of sumtypes with default (fix #13174)

cmd/tools/vpm.v
With this PR, vpm will support full urls that can be cloned in v.mod's
dependencies field too. For example:
`dependencies: ['https://github.com/spytheman/vperlin', 'vtl', 'ui', 'gporrata.rambo']`
The above, will clone https://github.com/spytheman/vperlin into
~/.vmodules/spytheman/vperlin , when you do `v update` over the
module/project that has it.
Currently on master, that does not work, since it will try to query
https://vpm.vlang.io/ even for urls, not just for `user.modname` type
of specifiers.
=> vpm: support full urls in v.mod's dependencies field

vlib/v/gen/c/cgen.v, vlib/v/tests/match_sumtype_var_return_sumtype_test.v
This PR fix match sumtype var returning sumtype value (fix #13175).
- Fix match sumtype var returning sumtype value.
- Add test.
```vlang
module main
type Sum = Struct | int
mut:
value int
}
fn sum(mut s Sum) Sum {
match mut s {
Struct {
return s
}
else {
return s
}
}
}
fn main() {
mut s := Sum(Struct{
value: 42
})
s = sum(mut s)
dump(s)
ret := '$s'
assert ret.contains('Sum(Struct{')
assert ret.contains('value: 42')
}
------------------------------------------------
[.\\tt1.v:26] s: Sum(Struct{
value: 42
})
```
=> cgen: fix match sumtype var returning sumtype value (fix #13175)

vlib/datatypes/linked_list.v, vlib/datatypes/linked_list_test.v, vlib/datatypes/queue.v, vlib/datatypes/queue_test.v
Sometimes you need to get an arbitrary element of a queue or a linked list, this PR meets that need.
=> datatypes: add index method on LinkedList and Queue

vlib/v/gen/c/cgen.v
This PR makes minor cleanup in match_expr().
- Remove unnecessary comments.
=> cgen: minor cleanup in match_expr()

vlib/v/checker/fn.v, vlib/v/checker/tests/generics_method_called_arg_mismatch.out, vlib/v/checker/tests/generics_method_called_arg_mismatch.vv, vlib/v/tests/generics_with_nested_generics_fn_test.v
This PR check generics method called arg mismatch (fix #13193).
- Check generics method called arg mismatch.
- Add test.
```vlang
fn main() {
mut obj := Obj{}
obj.set<Bar>(Foo{})
}
struct Foo {}
struct Bar {
Foo
}
struct Obj {}
fn (mut o Obj) set<T>(val T) {}
-------------------------------------
.\tt1.v:3:15: error: cannot use `Foo` as `Bar` in argument 1 to `Obj.set`
2 |     mut obj := Obj{}
3 |     obj.set<Bar>(Foo{})
|                  ~~~~~
4 | }
5 |
```
=> checker: check generics method called arg mismatch (fix #13193)

doc/docs.md
Fixed the usage of a word 'properties' according to https://en.wikipedia.org/wiki/Property_(programming)
=> doc: fix usage of a word 'properties'

vlib/v/parser/parser.v, vlib/v/parser/tests/method_call_receiver_err.out, vlib/v/parser/tests/method_call_receiver_err.vv
This PR check the receiver error of method call (fix #13201).
- Check the receiver error of method call.
- Add test.
```vlang
module main
struct S1{}
fn main() {
s1 := S1{}
$for method in S1.methods {
println(S1.method_hello('yo'))
}
}
fn (t S1) method_hello() string {
return 'Hello'
}
.\tt1.v:9:11: error: the receiver of the method call must be an instantiated object, e.g. `foo.bar()`
7 |
8 |     $for method in S1.methods {
9 |         println(S1.method_hello('yo'))
|                 ~~
10 |     }
11 | }
```
=> parser: check the receiver error of method call (fix #13201)

vlib/v/gen/c/assign.v, vlib/v/tests/mut_receiver_of_sumtype_test.v
This PR fix assigning to mut receiver of sumtype (fix #13202).
- Fix assigning to mut receiver of sumtype.
- Add test.
```vlang
pub type Foo = Bar | Baz
fn (mut f Foo) set_baz() {
f = Baz{}
}
pub struct Bar {}
pub struct Baz {}
fn main() {
mut x := Foo(Bar{})
x.set_baz()
println(x)
assert '$x' == 'Foo(Baz{})'
}
Foo(Baz{})
```
=> cgen: fix assigning to mut receiver of sumtype (fix #13202)

vlib/v/gen/c/fn.v, vlib/v/tests/fn_call_mut_sumtype_args_test.v
Fixes the C error when passing a sumtype from a field
=> gen: fix mut sumtype arguments for fields

vlib/v/gen/c/cgen.v, vlib/v/tests/fn_return_mut_sumtype_test.v
Fixes C error when returning a mutable symtype
```
/tmp/v/test_session_27434421237759/fn_return_mut_sumtype_test.15792886877278215264.tmp.c:16576: error: '{' expected (got ";")
...
=================
```
=> cgen: fix return of mut symtype

vlib/v/ast/table.v, vlib/v/ast/types.v, vlib/v/checker/match.v, vlib/v/parser/parse_type.v, vlib/v/parser/parser.v, vlib/v/parser/struct.v
This PR rename `register_type_symbol` to `register_sym`.
- Rename `register_type_symbol` to `register_sym`.
- Modify related called.
=> ast: rename `register_type_symbol` to `register_sym`

vlib/gg/image.v, vlib/gg/testdata/remove_image_from_cache.vv
This is needed if you want to draw on the screen but cannot use a streaming image (for example, because the window has been resized).
I've tested this and it works.
=> gg: add the gg.Context.remove_cached_image_by_idx() method

vlib/v/ast/ast.v, vlib/v/checker/checker.v, vlib/v/checker/for.v, vlib/v/checker/if.v, vlib/v/checker/match.v, vlib/v/gen/c/testdata/addition.c.must_have, vlib/v/parser/parse_type.v, vlib/v/transformer/index_state.v, vlib/v/transformer/transformer.v
This PR updates to transformer so it gets applied to (hopefully) all nodes.
This required some changes to mutability of some AST fields, which furthermore required changes to some `if` and `match` statements if the checker.
A small operational change is that constant folding now only gets applied on `-prod` mode.
=> transformer: refactor + apply transform to (hopefully) all nodes

vlib/v/checker/checker.v, vlib/v/checker/tests/generics_undefined_operation.out, vlib/v/checker/tests/generics_undefined_operation.vv
This PR check generics undefined operation of the infix expression (fix #13221).
- Check generics undefined operation of the infix expression.
- Add test.
```vlang
struct V2d<T> {
mut:
x T
y T
}
fn main() {
v1 := V2d<int>{2, 2}
v2 := V2d<int>{2, 3}
v3 := V2d<int>{4, 6}
if v1 * v2 == v3 {
}
}
.\tt1.v:12:5: error: undefined operation `V2d<int>` * `V2d<int>`
10 |     v3 := V2d<int>{4, 6}
11 |
12 |     if v1 * v2 == v3 {
|        ~~~~~~~
13 |     }
14 | }
```
=> checker: check generics undefined operation of the infix expression (fix #13221)

cmd/tools/vcreate.v, cmd/tools/vcreate_test.v
- Adds support for `.editorconfig`.
- Replaces the existing list of strings approach with multi-line strings.
- Do not exit if `v.mod` already exists. Check and add missing files instead.
- Adds unit tests
=> cmd/tools: Add support for .editorconfig and improve v init to initialize missing files

vlib/v/checker/containers.v, vlib/v/parser/parse_type.v, vlib/v/parser/tests/fixed_array_size_using_non_constant_err.out, vlib/v/parser/tests/fixed_array_size_using_non_constant_err.vv
This PR correct error message of fixed array size using non constant (fix #13219).
- Correct error message of fixed array size using non constant.
- Add test.
```vlang
module main
fn main() {
mut t := [0, 0]
println(t.len)
println(typeof(t.len).name)
mut score := [t.len][t.len]int{}
}
.\tt1.v:10:28: error: fixed array size cannot use non-constant value
8 |     println(typeof(t.len).name)
9 |
10 |     mut score := [t.len][t.len]int{}
|                            ~~~
11 | }
```
=> parser, checker: correct error message of fixed array size using non constant (fix #13219)

vlib/v/gen/c/array.v, vlib/v/gen/c/cgen.v, vlib/v/tests/fn_call_fixed_array_literal_args_test.v
This PR fix fn call with fixed array literal arguments (fix #13220).
- Fix fn call with fixed array literal arguments.
- Add test.
```vlang
fn main() {
ret := get_str([1]!)
assert ret == '[1]'
}
fn get_str(t [1]int) string {
println(t)
return '$t'
}
[1]
```
=> cgen: fix fn call with fixed array literal arguments (fix #13220)

cmd/v/help/build.txt, vlib/v/checker/checker.v, vlib/v/checker/comptime.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/cmain.v, vlib/v/gen/c/comptime.v, vlib/v/gen/c/profile.v, vlib/v/preludes/profiled_program.v, vlib/v/profile/api.v, vlib/v/tests/profile/profile_test.v, vlib/v/tests/profile/profile_test_2.v
Enhance V's profile mode, with the ability to selectively turn the profile
collection on/off.
Also add the ability to ignore the startup/setup calls that are done
before the user's `main()` function was run, to further reduce the
noise in the profile counters.
For example, the following program:
```v
import v.profile
fn abc() {
eprintln(@FN)
}
fn main() {
profile.on(false)
for _ in 0 .. 3 {
abc()
}
println('>>>>>>>>>>')
profile.on(true)
abc()
profile.on(false)
println('>>>>>>>>>>')
for _ in 0 .. 3 {
abc()
}
profile.on(true)
}
```
... when compiled with `v -d no_profile_startup -profile z.txt run
z.v`, will produce a new `z.txt` file containing something like this:
```
1          0.002ms           2381ns eprintln
1          0.002ms           2040ns _writeln_to_fd 
1          0.001ms …
```
=> checker,cgen: implement v.profile.on/1, `[if profile]` and `-d no_profile_startup`

vlib/v/ast/table.v, vlib/v/ast/types.v, vlib/v/tests/generic_sumtype_init_in_generic_fn_call_test.v
This PR fix error for generic sumtype init in generic fn call (fix #13211).
- Fix error for generic sumtype init in generic fn call.
- Add test.
```vlang
pub type Result<S> = Ok<S> | string
pub fn (x Result<S>) unwrap<S>() ?S {
match x {
Ok<S> {
return x.value
}
string {
return error(x)
}
}
}
struct Ok<S> {
value S
}
pub fn ok<S>(value S) Result<S> {
return Ok<S>{value}
}
fn main() {
x := ok<int>(42)
ret := x.unwrap() or { 0 }
println(ret)
assert ret == 42
}
42
```
=> ast: fix error for generic sumtype init in generic fn call (fix #13211)

vlib/v/ast/ast.v, vlib/v/ast/types.v
This PR makes minor cleanup of struct Field.
- Remove struct Field definitions that have been commented out.
=> ast: minor cleanup of struct Field

vlib/toml/any.v, vlib/toml/tests/reflect_test.v
As discussed on Discord this PR adds support for arrays and (`string`) maps of the primitive types supported by the TOML module.
=> toml: add support for arrays and maps of primitives in `reflect<T>`

vlib/toml/any.v, vlib/toml/tests/encode_and_decode_test.v, vlib/toml/toml.v
As discussed on Discord this PR adds `encode` and `decode` functions for the `toml` module which is similar to their `json2` siblings
=> toml: add `encode<T>` and `decode<T>`

vlib/toml/toml.v
I made whoopsie when copying the functions from `json2` 😬
=> toml: fix copy pasta doc string

vlib/json/json_test.v, vlib/v/gen/c/json.v
This PR fix error for json encoding sumtype value (fix #13242).
- Fix error for json encoding sumtype value.
- Add test.
```vlang
module main
import json
struct Asdasd {
data GamePacketData
}
type GamePacketData = GPEquipItem | GPScale
struct GPScale {
value f32
}
struct GPEquipItem {
name string
}
fn create_game_packet(data &GamePacketData) string {
return json.encode(data)
}
fn main() {
ret := create_game_packet(&GamePacketData(GPScale{}))
println(ret)
assert ret == '{"value":0,"_type":"GPScale"}'
}
{"value":0,"_type":"GPScale"}
```
=> json: fix error for json encoding sumtype value (fix #13242)

vlib/v/checker/struct.v
This PR fix ui struct init error with default field value is const var (fix #13209).
```vlang
module ui
import gx
pub struct Foo{ x int }  // Added
[heap]
pub struct Label {
Foo     // Added
pub mut:
id         string
text       string
...
}
module main
import ui
fn main(){
lbl := ui.label(text: 'Hello')
w := ui.window(
width: 300
height: 200
children: [lbl]
)
ui.run(w)
}
```
=> checker: fix ui struct init error with default field value is const var (fix #13209)

vlib/v/checker/checker.v, vlib/v/checker/tests/cast_string_to_rune_err.out, vlib/v/checker/tests/cast_string_to_rune_err.vv
This PR fixed the c error that was thrown on an improper string to rune cast (fix #13197)
- Add detailed error message for improper string to rune cast
- Add test
```v
println(rune('9'))
```
will now produce
```
../file.v:1:9: error: cannot cast `string` to rune, use `'9'.runes()` instead.
1 | println(rune('9'))
|         ~~~~~~~~~
```
=> checker: fix c error on improper string to rune cast (#13197)

vlib/v/checker/fn.v, vlib/v/tests/generics_struct_inst_method_call_test.v
This PR fix method call errors for generic struct instances (fix #13252).
- Fix method call errors for generic struct instances.
- Add test.
```vlang
fn main() {
v1 := V2d<f32>{100}
r1 := v1.in_bounds(tp_lft, bt_rigt)
println(r1)
assert r1
}
const (
tp_lft  = V2d<f32>{20}
bt_rigt = V2d<f32>{650}
)
struct V2d<T> {
mut:
x T
}
pub fn (v1 V2d<T>) unpack() T {
return v1.x
}
pub fn (v1 V2d<T>) less_than(v2 V2d<T>) V2d<bool> {
return V2d<bool>{v1.x < v2.x}
}
pub fn (v1 V2d<T>) in_bounds(top_left V2d<T>, bottom_right V2d<T>) bool {
v1.less_than(bottom_right).unpack()
return true
}
true
```
=> checker: fix method call errors for generic struct instances (fix #13252)

vlib/v/gen/c/array.v, vlib/v/tests/for_in_mut_val_with_if_val_in_test.v
This PR fix 'for in mut val' with 'if val in' (fix #13262).
- Fix 'for in mut val' with 'if val in'.
- Add test.
```vlang
fn main() {
array := ['e']
mut splited := ['h', 'f', 's', 'e']
mut has_e := false
for mut s in splited {
if s in array {
println('Hello')
has_e = true
}
}
assert has_e
}
Hello
```
=> cgen: fix 'for in mut val' with 'if val in' (fix #13262)

vlib/os/os_windows.c.v, vlib/v/builder/msvc.v
I was encountering weird errors on Windows (both on local machines and on [GitHub Actions](https://github.com/hungrybluedev/geo/runs/4927929749?check_suite_focus=true#step:8:11)) regarding the output retrieved from `os.execute()` and the related family of functions.
I observed that there is a `trim_space` call on the output result on the windows implementation, but for the unix one. In order to make the two implementations consistent, I removed the call to the trim function. This is important when comparing the outputs generated by a command against an expected output.
This PR also updates the `msvc.v` to use the trimmed paths.
=> os: remove trim_space() to make execute() implementations consistent

cmd/tools/vast/vast.v, vlib/v/ast/ast.v, vlib/v/ast/str.v, vlib/v/checker/checker.v, vlib/v/checker/if.v, vlib/v/checker/tests/if_guard_variables_err.out, vlib/v/checker/tests/if_guard_variables_err.vv, vlib/v/fmt/fmt.v, vlib/v/gen/c/cgen.v, vlib/v/gen/js/js.v, vlib/v/parser/if_match.v, vlib/v/parser/parser.v, vlib/v/tests/if_guard_with_multi_return_test.v
This PR implement if guard with multi return optional (fix #13249).
- Implement if guard with multi return optional.
- Add test.
```vlang
fn create() ?(int, string, bool) {
return 5, 'aa', true
}
fn main() {
if r1, r2, r3 := create() {
println(r1)
assert r1 == 5
println(r2)
assert r2 == 'aa'
println(r3)
assert r3 == true
} else {
assert false
}
}
5
aa
true
```
```vlang
fn create() ?(int, string, bool) {
return 5, 'aa', true
}
fn main() {
if r1 := create() {
println(r1)
}
if r1, r2, r3, r4 := create() {
println(r1)
println(r2)
println(r3)
println(r4)
}
}
.\tt1.v:6:2: error: if guard expects 3 variables, but got 1
4 |
6 |     if r1 := create() {
|     ~~~~~~~~~~~~~~~~~
7 |         println(r1)
8 |     }
.\tt1.v:10:2: error: …
```
=> ast, checker, cgen: implement if guard with multi return optional (fix #13249)

vlib/term/ui/input_nix.c.v, vlib/term/ui/termios_nix.c.v
This PR adds support for multi byte buffer reads in the event system - and thus fixes a bug with the use of `single_char` in the event loop.
Before this PR the event system would emit single byte events with full contents of the `Event.utf8` field sat - but as the loop reads events until it's empty - the events emitted afterwards would contain only the last half of a 2 byte UTF-8 character.
I.e. the UTF-8 bytes was emitted in as 1 byte pieces, split in two at every loop cycle:
From my debug output when pressing the `æ` key:
```
Raw event bytes: "c3a6" = [0xc3, 0xa6]
Raw event bytes: "a6" = [0xa6]
```
In `text_editor.v` this would result in the sequence of bytes `[0xc3, 0xa6, 0xa6]` resulting in junk output.
This PR makes it the default to read the complete buffer into the event resulting …
=> term.ui: add support for multi byte/UTF-8 events

examples/term.ui/text_editor.v
This PR enables the internal buffer of the editor to handle unicode characters (via `rune`).
Before this PR typing `æøåÆØÅ` on my keyboard resulted in this:
After this PR it results in this:
Please note that character handling, keyboard charmapping, legacy codepages, locale settings and encoding in "raw" terminals is a complex matter that this PR does not try to fix.
To add proper support for UTF-8 **input** we'd probably (like noted in the source) need to [implement X11 support](https://github.com/vlang/v/blob/32f2f0dfa1cd9516b7ad421e7b46cec65e448bd6/vlib/term/ui/input_nix.c.v#L42).
I have, however, added a quick fix that translates the ascii codes for "æøåÆØÅ" received from a `term.ui.Event` into their UTF-8 counterparts via V's `string`. (I'm aware that the codes might be different …
=> examples: support unicode in text_editor.v buffer

vlib/net/http/http.v
Add `allow_redirect` field to FetchConfig now that it's been added to Request.
=> net: add allow_redirect to FetchConfig

cmd/tools/vast/vast.v, vlib/v/ast/ast.v, vlib/v/checker/containers.v, vlib/v/gen/c/cgen.v, vlib/v/tests/map_sumtype_value_init_test.v
This PR fix error for map sumtype value init (fix #13284).
- Fix error for map sumtype value init.
- Add test.
```vlang
type Child = Tree | string
struct Tree {
name  string
child map[string]Child
}
fn main() {
tree := Tree{
name: 'foo'
child: {
'a': 'value'
}
}
println(tree)
ret := tree.child['a'] or { Child('') }
assert ret == Child('value')
}
---------------------------------------------------------
Tree{
name: 'foo'
child: {'a': Child('value')}
}
```
=> ast, checker, cgen: fix error for map sumtype value init (fix #13284)

vlib/v/gen/c/fn.v, vlib/v/tests/struct_multi_embed_method_call_test.v
This PR fix error of struct multi embed method call (fix #13291).
- Fix error of struct multi embed method call.
- Add test.
```vlang
pub struct Boundary {}
pub fn (b Boundary) contains(x int, y int) bool {
return false
}
pub struct Base {
Boundary
}
pub fn (mut b Base) on_event(x int, y int) {
if b.Boundary.contains(x, y) {
}
if b.contains(x, y) {
}
}
pub struct ListBox {
Base
}
pub fn (mut lb ListBox) on_event(x int, y int) {
if lb.Base.Boundary.contains(x, y) {
}
if lb.contains(x, y) {
}
}
fn main() {
mut list_box := ListBox{}
list_box.on_event(11, 22)
println(list_box)
assert true
}
-------------------------------------------------------
ListBox{
Base: Base{
Boundary: Boundary{}
}
}
```
=> cgen: fix error of struct multi embed method call (fix #13291)

examples/sokol/01_cubes/cube.v, examples/sokol/02_cubes_glsl/cube_glsl.v, examples/sokol/03_march_tracing_glsl/rt_glsl.v, examples/sokol/04_multi_shader_glsl/rt_glsl.v, examples/sokol/05_instancing_glsl/rt_glsl.v, examples/sokol/06_obj_viewer/show_obj.v
This PR fixes the crashes that occur when closing the example sokol "0x_*" apps.
The reason they crash on close is that they use `gg` which wraps setup and shutdown of `sokol.gfx` - and these examples also called `gfx.shutdown()` on their exit/cleanup call - resulting in double call/freeing and a message like this:
```
01_cubes: /home/user/v/thirdparty/sokol/sokol_gfx.h:13751: _sg_context_at: Assertion `(slot_index > (0)) && (slot_index < p->context_pool.size)' failed.
7f44dff4b18b : at ???: RUNTIME ERROR: abort() called
4173257325203a75 : by ???
signal 11: segmentation fault
/dev/shm/v_1000/01_cubes.132947864327463290.tmp.c:9478: at print_backtrace: Backtrace
/dev/shm/v_1000/01_cubes.132947864327463290.tmp.c:9544: by v_segmentation_fault_handler
7f44dff4b210 : by ???
005017f9 : by ??? …
```
=> examples: fix segmentation fault crash on exit in sokol 0X_ examples

cmd/tools/vdoc/html.v, cmd/tools/vdoc/utils.v, examples/vpwgen.v, vlib/builtin/array.v, vlib/builtin/string_interpolation.v, vlib/net/html/parser.v, vlib/net/smtp/smtp.v, vlib/regex/regex_test.v, vlib/strconv/format.v, vlib/strconv/format_mem.c.v, vlib/strconv/format_mem.js.v, vlib/strconv/vprintf.c.v, vlib/strings/builder.c.v, vlib/strings/builder.js.v, vlib/strings/builder_test.js.v, vlib/strings/builder_test.v, vlib/v/builder/rebuilding.v, vlib/v/gen/c/cgen.v, vlib/v/parser/tmpl.v, vlib/v/util/errors.v, vlib/v/util/quote.v, vlib/x/json2/encoder.v, vlib/x/ttf/ttf.v
This deprecates `Builder.write_b()` for `Builder.write_byte()`. This adds consistency with the other functions, and it's just more descriptive.
_Note: this is my first V PR that's not for `gg`. I think I got it all right, but there's a possibility I didn't_
=> strings: Builder.write_b() -> Builder.write_byte()

vlib/builtin/utf8.c.v, vlib/builtin/utf8_test.v
With this PR, 'abc'.to_wide() now can be used on non windows too.
(it returned a 0 pointer before).
It returns a &u16 pointer to a WTF-16 encoded version of the string:
consecutive runes, each casted to u16, finished with a u16(0).
=> builtin: use a pure V version of string.to_wide() on != windows

vlib/gx/color.v
This fixes the `+`, `-`, `*`, `/` for the colors.
=> gx: Fix gx.Color math operations

vlib/os/os.v, vlib/os/os_nix.c.v, vlib/os/os_test.v, vlib/os/os_windows.c.v
At current, we are unable to retrieve the exit code with commands dispatched by os.Command.
The exit code is pretty important in some cases as it allows us to handle certain errors accordingly without panicking.
This PR adds the exit_code property to os.Command and updates the os.Command.close() method to set the 
exit code, rather than let it drop off.
=> os: add an .exit_code field to os.Command

vlib/v/ast/table.v, vlib/v/checker/fn.v, vlib/v/tests/generics_with_complex_nested_generics_type_test.v
This PR fix error for calling complex nested generic type function (fix #13025).
- Fix error for calling complex nested generic type function.
- Add test.
```vlang
fn main() {
mut buf := []byte{}
initial<string, u64>(buf)
}
fn initial<K, V>(buf []byte) map[K]V {
mut ret := map[K]V{}
for _ in 0 .. 3 {
k := get<K>(buf)
v := get<V>(buf)
ret[k] = v
}
println(ret)
assert '$ret' == "{'get': 22}"
return ret
}
fn get<T>(buf []byte) T {
$if T is string {
return buf.bytestr() + 'get'
} $else $if T is u64 {
return u64(22)
} $else {
panic('oops!')
}
}
-----------------------------------------------------------
{'get': 22}
```
=> ast, checker: fix error for calling complex nested generic type function (fix #13025)

cmd/tools/vcheck-md.v, cmd/v/help/check-md.txt, doc/docs.md, vlib/gg/README.md, vlib/sokol/README.md
Previously `compile` behaved, as the new `cgen` mode does, by just producing an `x.c` file, but not compiling it, trusting that it would remain compilable. That is faster, but has the problem, that it can NOT spot cgen *regressions* in pure V examples in the documentation.
The default `compile`, will now try to actually *compile* with the backend C compiler, not just generate a x.c file.
See also https://github.com/vlang/v/issues/13322
=> tools: implement `cgen` tag for Markdown examples in `v check-md`

vlib/regex/regex.v, vlib/regex/regex_test.v
**What's inside **
- fix for `a*(b*)*a` query string problem
- added more tests 
test code:
```v
import regex
fn main() {
input := '/*x*/'
query := r'/\**(.*)\**/'
mut re := regex.regex_opt(query) ?
println(re.get_query())
println(re.get_code())
re.debug = 2 // max debug info
s, e := re.match_string(input)
println("$s $e")
}
```
=> Regex: fixed dot char problems on groups with *

cmd/tools/vfmt.v, vlib/os/inode.c.v, vlib/os/inode_test.v
The problem:
After running `v fmt -w <filepath>` on linux the file is overwritten and the file permissions are lost.
The solution:
This update read the file permissions before saving (`os.inode`) and after `os.mv_by_cp` the permission is restored using `os.chmod`.
=> vfmt: updated to keep file permissions on !windows

vlib/v/ast/table.v, vlib/v/gen/c/cgen.v, vlib/v/tests/interface_struct_with_multi_nested_embed_test.v
This PR fix error for interface with multi nested embed struct (fix #13331).
- Fix error for interface with multi nested embed struct.
- Add test.
```vlang
fn main() {
mut win := &Window{}
mut ll := &LinearLayout{}
mut lbl := &Label{
x: 10
y: 20
}
ll.add(mut lbl)
win.add(mut ll)
win.init()
}
[heap]
pub struct Window {
mut:
initables []&Initable
}
interface Initable {
mut:
init(&Window)
}
pub fn (mut w Window) add(mut initable Initable) {
w.initables << initable
}
interface Container {
mut:
layout()
}
fn (mut w Window) init() {
for wd in w.initables {
if mut wd is Container {
mut c := wd as Container
c.layout()
}
}
}
pub struct Rect {
mut:
x int
y int
}
pub fn (r Rect) get_pos() (int, int) {
return r.x, r.y
}
pub struct LayoutBase {
Rect
}
pub struct Base {
LayoutBase
}
pub fn (mut b Base) …
```
=> cgen: fix error for interface with multi nested embed struct (fix #13331)

vlib/vweb/tests/vweb_test.v, vlib/vweb/tests/vweb_test_server.v, vlib/vweb/vweb.v
Add support for running vweb servers that are listening only on
localhost, instead of on all available network interface addresses.
=> vweb: support `vweb.run_at(app, 'localhost', 8099)`

vlib/v/gen/c/cgen.v, vlib/v/tests/interface_with_multi_nested_embed_1_test.v, vlib/v/tests/interface_with_multi_nested_embed_2_test.v
This PR fix error for interface with multi-nested embed struct (fix #13340).
- Fix error for interface with multi-nested embed struct.
- Add test.
```vlang
fn main() {
mut ll := &LinearLayout{}
mut lbl := &Label{
x: 10
y: 20
}
ll.add(mut lbl)
println(ll)
assert ll.x == 10
assert ll.y == 20
}
pub struct Rect {
mut:
x int
y int
}
pub fn (r Rect) get_pos() (int, int) {
return r.x, r.y
}
pub struct LayoutBase {
Rect
}
pub struct Base {
LayoutBase
}
pub fn (mut b Base) init() {}
[heap]
pub struct Label {
Base
}
pub interface Layoutable {
get_pos() (int, int)
mut:
init()
}
[heap]
pub struct LinearLayout {
Base
mut:
layoutables []Layoutable
}
pub fn (mut ll LinearLayout) add(mut l Layoutable) {
x, y := l.get_pos()
ll.x += x
ll.y += y
}
------------------------------------------------------------- …
```
=> cgen: fix error for interface with multi-nested embed struct (fix #13340)

vlib/regex/regex_test.v, vlib/regex/regex_util.v
- Fix for missing find in `replace_by_fn`
- added tests
test code:
```v
import regex
fn main() {
import regex
fn main() {
s := 
'typedef enum
{
SDL_BLENDMODE_NONE = 0x00000000,     /**< no blending
dstRGBA = srcRGBA */
SDL_BLENDMODE_BLEND = 0x00000001,    /**< alpha blending
dstRGB = (srcRGB * srcA) + (dstRGB * (1-srcA))
dstA = srcA + (dstA * (1-srcA)) */
/* Additional custom blend modes can be returned by SDL_ComposeCustomBlendMode() */
} SDL_BlendMode;
/* finish comment */
'
q := r'/[*]{1,2}(.*)[*]/'
mut re := regex.regex_opt(q) or {panic(err)}
flat_blocks := re.replace_by_fn(s, fn (re regex.RE, in_txt string, start int, end int) string {
mut re1 := regex.regex_opt(r'\s{2,}') or {panic(err)}
res :=re1.replace(re.get_group_by_id(in_txt, 0).replace('\n', ' '), ' ') …
```
=> Regex: fix bug in replace_by_fn

cmd/tools/vtest-self.v, vlib/v/gen/c/sql.v, vlib/v/tests/sql_statement_inside_fn_call_test.v
This PR fix error for sql statement inside fn call (fix #13330).
- Fix error for sql statement inside fn call.
- Add test.
```vlang
import sqlite
struct Movie {
id   int    [primary]
name string
}
fn x(m Movie) int {
return m.id
}
fn main() {
db := sqlite.connect(':memory:') ?
sql db {
create table Movie
}
m := Movie{1, 'Maria'}
sql db {
insert m into Movie
}
dump(x(sql db {
select from Movie where id == 1
}))
}
---------------------------------------------------
[.\\tt1.v:21] x(ast.SqlExpr): 1
```
```vlang
import vweb
import sqlite
struct App {
vweb.Context
pub mut:
db sqlite.DB
}
fn main() {
mut app := App{
db: sqlite.connect(':memory:') or { panic(err) }
}
sql app.db {
create table Movie
}
vweb.run(app, 8081)
}
struct Movie {
id          int    [primary; sql: …
```
=> cgen: fix error for sql statement inside fn call (fix #13330)

vlib/v/ast/ast.v, vlib/v/ast/table.v, vlib/v/checker/struct.v, vlib/v/parser/parse_type.v, vlib/v/parser/parser.v, vlib/v/parser/struct.v, vlib/v/tests/generics_struct_init_with_inconsistent_generic_types_test.v
This PR fix generic struct init with inconsistent generic types (fix #12990).
- Fix generic struct init with inconsistent generic types.
- Add test.
```vlang
struct Response<U> {
result U
}
pub fn send<T>(res T) string {
msg := Response<T>{
result: res
}
return '$msg'
}
fn main() {
mut ret := send(123)
println(ret)
assert ret.contains('Response<int>{')
assert ret.contains('result: 123')
ret = send('abc')
println(ret)
assert ret.contains('Response<string>{')
assert ret.contains("result: 'abc'")
}
----------------------------------------------------------------
Response<int>{
result: 123
}
Response<string>{
result: 'abc'
}
```
=> ast, parser, checker: fix generic struct init with inconsistent generic types (fix #12990)

vlib/v/checker/checker.v, vlib/v/checker/tests/cmp_between_struct.out, vlib/v/checker/tests/cmp_between_struct.vv
Fixes https://github.com/vlang/v/issues/13318
CI shows an error in the diff from the test that I added, any idea on what I did wrong?
```
found:
vlib/datatypes/heap.v:16:15: error: cannot use `>` as `<=` operator method is not defined
14 |     mut child := heap.data.len - 1
15 |     mut parent := heap.parent(child)
16 |     for heap.data[parent] > heap.data[child] {
|                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
17 |         heap.data[parent], heap.data[child] = heap.data[child], heap.data[parent]
18 |         child = parent
vlib/datatypes/heap.v:37:15: error: cannot use `>` as `<=` operator method is not defined
35 |     mut left := heap.left_child(parent) or { return item }
36 |     mut right := heap.right_child(parent) or { left }
37 |     for heap.data[parent] > heap.data[left] || …
```
=> checker: make sure that the operator check is made on the concrete type

vlib/v/fmt/fmt.v, vlib/v/fmt/tests/empty_map_fmt_keep.vv
Fixes https://github.com/vlang/v/issues/13281
how the result now looks like
```
➜  v git:(master) ✗ ./v self && ./v fmt .debug/test.v
V self compiling ...
V built successfully as executable "v".
struct Foo {
bar map[int]int
}
fn main() {
foo := Foo{
bar: {
// comment
}
}
}
```
=> fmt: preserve formatting with comments in a empty map

vlib/v/checker/tests/orm_using_undefined_var_in_where_err.out, vlib/v/checker/tests/orm_using_undefined_var_in_where_err.vv, vlib/v/parser/sql.v
This PR check orm using undefined variable in where expr (fix #13367).
- Check orm using undefined variable in where expr.
- Add test.
```vlang
import time
import sqlite
struct User {
id         int       [primary; sql: serial]
created_at time.Time
updated_at time.Time
email      string
password   string
}
fn main() {
db := sqlite.connect(':memory:') ?
sql db {
create table User
}
m := User{}
sql db {
insert m into User
}
_ := sql db {
select from User where email == email
}
}
./tt1.v:24:35: error: undefined variable: `email`
22 |
23 |     _ := sql db {
24 |         select from User where email == email
|                                         ~~~~~
25 |     }
26 | }
```
=> parser: check orm using undefined variable in where expr (fix #13367)

vlib/vweb/vweb.v
method "**mount_static_folder_at**"  produces wrong mount_path,
for example , "/public/assets/img"  will get "public/assets/img" , and this result will later used in method **scan_static_directory**, and then produce url "public/assets/img/a.png" , and this result is wrong for method  **serve_static**, as url must start with "/", in this example is "public/assets/img/a.png"
=> fix Context.mount_static_folder_at  

vlib/v/gen/c/auto_str_methods.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/str.v, vlib/v/tests/struct_with_reference_alias_fields.v
This PR fix error for struct with reference alias fields (fix #8977, fix #13369)
- Fix error for struct with reference alias fields.
- Add test.
- It cannot output informations with gg imported.
```vlang
type SS = string
struct ST {
data &SS
}
fn main() {
mut val := ST{
data: &SS('hi')
}
println(val.data)
assert '$val.data' == 'hi'
}
-------------------------------------------------
hi
```
=> cgen: fix error for struct with reference alias fields (fix #8977 #13369)

vlib/log/log.v, vlib/log/log_test.v
Hi all,
with this small change Log will be usable even as a Logger.
I added a test to show its usage and ensure it works as before and in the more generic way (but limited to interface methods).
As you can see in the test there is a commented portion because I think we need to decide if it's better to keep Log as is, or if accept this PR (once removed commented code) so that each Log/Logger instance has to be mutable.
Note 1: 
I'm writing a custom module for logging and I'd like to use as much as possible v Logger interface and v log public items, to try to standardize behaviour as much as possible. 
I think in general this should be good for extensibility of V with additional implementations.
Note 2:
even a not mutable logger could be useful too, for example to send log only to a …
=> log: update Logger interface so that Log is usable even as a Logger

vlib/v/gen/c/auto_str_methods.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/str.v, vlib/v/tests/struct_with_reference_alias_field.v
This PR fix error for struct with reference alias fields (fix #8977, fix #13369)
- Fix error for struct with reference alias fields.
- Add test.
- It cannot output informations with gg imported.
```vlang
type SS = string
struct ST {
data &SS
}
fn main() {
mut val := ST{
data: &SS('hi')
}
println(val.data)
assert '$val.data' == 'hi'
}
-------------------------------------------------
hi
```
=> cgen: fix error for struct with reference alias field (fix #8977 #13369)

vlib/v/parser/fn.v
Fixes half of #11365, `v -translated self` is still broken.
=> v.parser: fix -translated for modules with C interop

.github/workflows/docs_ci.yml, vlib/log/log.v
This PR introduce a CI step that'll prevent any *undocumented* `pub fn` functions going into `vlib/`.
It works by comparing the count of undocumented public functions in the fork/branch the PR is forked from with the count of the PR itself. If the count for the PR is greater than that of the fork, CI will fail in the following way:
Test runs can be found here from the commmits in this PR's history:
Failed:
https://github.com/Larpon/v/actions/runs/1802505599
Ok (function introduced had docs added):
https://github.com/Larpon/v/runs/5083957234
Currently the numbers speak for themselves:
```
v run cmd/tools/missdoc.v vlib/ | wc -l
1724
```
Currently we have 1724 undocumented functions in vlib - and that number will keep growing if we don't stop it - since very few PR's is currently *adding* …
=> ci: add report-missing-fn-doc job, to prevent adding new undocumented pub symbols in vlib

.github/workflows/docs_ci.yml, cmd/tools/missdoc.v
This PR adds an option to `missdoc` to tell it to omit line number information in it's output - fixing a situation in `docs_ci` where output could be very verbose and confusing.
=> ci: fix undoc pub fn diff output

cmd/tools/vsymlink.v, cmd/v/help/symlink.txt
Allows `./v symlink` to be used on GitHub Actions using the `-githubci` tag. It does not make use of elevated privileges. Instead, we add the location of V's installation to path and invoke `refreshenv` that comes pre-installed with Chocolatey on WIndows CI runners.
=> cmd/tools: add support for ./v symlink -githubci

vlib/datatypes/doubly_linked_list.v, vlib/datatypes/linked_list.v, vlib/v/ast/ast.v, vlib/v/checker/struct.v, vlib/v/checker/tests/generic_fn_decl_without_generic_names_err.out, vlib/v/checker/tests/generic_fn_decl_without_generic_names_err.vv, vlib/v/checker/tests/generics_fn_return_generic_struct_err.out, vlib/v/checker/tests/generics_struct_init_err.out, vlib/v/parser/struct.v, vlib/v/tests/generics_struct_anon_fn_type_test.v
This PR check generic struct init without type parameter in generic fn.
- Check generic struct init without type parameter in generic fn.
- Add test.
```vlang
struct Response<U> {
result U
}
pub fn send<T>(res T) string {
msg := Response{
result: res
}
return '$msg'
}
fn main() {
mut ret := send(123)
println(ret)
assert ret.contains('Response<int>{')
assert ret.contains('result: 123')
ret = send('abc')
println(ret)
assert ret.contains('Response<string>{')
assert ret.contains("result: 'abc'")
}
./tt1.v:6:9: error: generic struct init must specify type parameter, e.g. Foo<T>
4 |
5 | pub fn send<T>(res T) string {
6 |     msg := Response{
|            ~~~~~~~~~
7 |         result: res
8 |     }
./tt1.v:7:3: error: cannot assign to …
```
=> checker: check generic struct init without type parameter in generic fn

doc/docs.md
Just a small example of a `v run` command in the hot reload section of the documentation to show a difference between `v -live run message.v` and `v -live run .` commands
=> Doc: hot reload section - run command example

vlib/v/ast/ast.v, vlib/v/ast/table.v, vlib/v/checker/fn.v, vlib/v/checker/tests/redefining_builtin_pub_functions.out, vlib/v/checker/tests/redefining_builtin_pub_functions.vv, vlib/v/gen/js/fn.v, vlib/v/parser/fn.v, vlib/v/parser/parser.v, vlib/v/parser/struct.v, vlib/v/parser/tests/fn_use_builtin_err.out
On master, V produces an error, when the user tries to redefine one of:
['print', 'println', 'eprint', 'eprintln', 'isnil', 'panic', 'exit']
This PR checks user function names in the main module, against all of the `builtin` public ones.
Functions in other modules are not checked, since they will be visible to their importers through their module's prefix. i.e. `custom.exit(1)` is hard to be mistaken with `exit(1)`.
=> checker: error on redefining any of the public `builtin` functions

vlib/builtin/int_test.v, vlib/builtin/string.v, vlib/strconv/atof.c.v, vlib/strconv/atof.js.v, vlib/strconv/atof_test.v, vlib/v/eval/expr.v
Fixes https://github.com/vlang/v/issues/13417
Maybe it is also a good moment to move all this conversion to the same API with a result?
=> strconv: change atof64 to return an error, if the parsed value is not a valid number

vlib/v/checker/struct.v, vlib/v/checker/tests/generics_struct_init_type_parameter_count_err.out, vlib/v/checker/tests/generics_struct_init_type_parameter_count_err.vv, vlib/v/checker/tests/generics_struct_init_type_parameter_err.out, vlib/v/checker/tests/generics_struct_init_type_parameter_err.vv
This PR check error of the generic struct init type parameter.
- Check error of the generic struct init type parameter.
- Add tests.
```vlang
struct Response<U> {
result U
}
pub fn send<A, B>(res A, b B) string {
msg := Response<A, B>{
result: res
}
println(b)
return '$msg'
}
fn main() {
mut ret := send(123, 22.2)
println(ret)
}
./tt1.v:6:9: error: generic struct init expects 1 generic parameter, but got 2
4 |
5 | pub fn send<A, B>(res A, b B) string {
6 |     msg := Response<A, B>{
|            ~~~~~~~~~~~~~~~
7 |         result: res
8 |     }
```
```vlang
struct Response<U> {
result U
}
pub fn send<A, B>(res A, b B) string {
msg := Response<U>{
result: res
}
println(b)
return '$msg'
}
fn main() {
mut ret := send(123, 22.2)
println(ret)
}
PS D:\Test\v\tt1> v run …
```
=> checker: check error of the generic struct init type parameter

vlib/os/process_windows.c.v
win_read_string() has no implementation so far. Currently it just panic's upon invocation. This patch adds a win_read_string() implementation.
=> win process: add win_read_string implementation

vlib/v/ast/ast.v, vlib/v/checker/assign.v, vlib/v/checker/checker.v, vlib/v/checker/comptime.v, vlib/v/checker/fn.v, vlib/v/checker/tests/comptime_for.out, vlib/v/checker/tests/comptime_for.vv, vlib/v/checker/tests/modules/deprecated_module/main.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/comptime.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/str_intp.v, vlib/v/parser/fn.v, vlib/v/tests/comptime_for_in_field_with_generic_fn_test.v, vlib/v/tests/for_t_fields_with_comptime_if_test.v
This PR fix error for comptime for in field with generic fn (fix #13409).
- Fix error for comptime for in field with generic fn.
- Add test.
```vlang
module main
// exploring `decode` options with nested structs
struct Parent {
name  string
age   int
child Child
}
struct Child {
name string
age  int
}
fn inspect<T>(t T) string {
mut output_str := ''
println('$T.name')
val := t.$(field.name)
$if field.typ is string {
println('  $field.name = $val')
output_str += '  $field.name = $val\n'
} $else $if field.typ is int {
println('  $field.name = $val')
output_str += '  $field.name = $val\n'
} $else {
str := inspect(val)
output_str += str
}
}
return output_str
}
fn main() {
p := Parent{
name: 'parent'
age: 30
child: Child{
name: 'child'
age: 5
}
}
ret := inspect(p) …
```
=> all: fix error for comptime for in field with generic fn (fix #13409)

vlib/v/ast/ast.v, vlib/v/gen/c/cgen.v, vlib/v/tests/struct_init_with_embed_update_test.v
This PR fix struct init with embed field update (fix #10588).
- Fix struct init with embed field update.
- Add test.
```vlang
struct Button {
width  int
height int
}
enum Color {
red
blue
yellow
}
struct ColoredButton {
Button
color Color
}
fn change_color(cb ColoredButton, color Color) ColoredButton {
return ColoredButton{
...cb
color: color
}
}
fn main() {
red_button := ColoredButton{Button{100, 100}, .red}
blue_button := change_color(red_button, .blue)
println(red_button)
println(blue_button)
assert blue_button == ColoredButton{Button{100, 100}, .blue}
}
ColoredButton{
Button: Button{
width: 100
height: 100
}
color: red
}
ColoredButton{
Button: Button{
width: 100
height: 100
}
color: blue
}
```
=> cgen: fix struct init with embed field update (fix #10588)

doc/docs.md, vlib/builtin/js/builtin.v, vlib/builtin/option.v, vlib/encoding/csv/reader.v, vlib/encoding/csv/writer.v, vlib/v/tests/string_optional_none_test.v
- update error implementation in `vlib/encoding` and `vlib/v/tests`
- add some documentation on custom error types
- fix a bug where `panic(err)` does not display a message when using the new implementation
=> Update error implementations + documentation + minor fix

vlib/v/checker/fn.v, vlib/v/gen/c/fn.v, vlib/v/tests/struct_embed_fn_type_test.v
This PR fix error for struct embed with fn type (fix #11520).
- Fix error for struct embed with fn type.
- Add test.
```vlang
type FnClick = fn () string
struct Widget {
mut:
x     int
y     int
click FnClick = click
}
fn click() string {
return 'click me'
}
struct Button {
Widget
title string
}
fn main() {
mut button := Button{
title: 'Click me'
}
button.x = 3
ret := button.click()
println(ret)
assert ret == 'click me'
}
click me
```
=> checker, cgen: fix error for struct embed with fn type (fix #11520)

vlib/v/ast/table.v, vlib/v/tests/struct_embedding_with_interface_test.v
This PR fix error for struct embedding with interface (fix #13411).
- Fix error for struct embedding with interface.
- Add test.
```vlang
fn main() {
mut ll := LinearLayout{}
mut lv := ListView{}
ll.add(lv)
ret := ll.layout()
println(ret)
assert ret.count('ListView') == 2
}
interface Container {
mut:
layout() string
}
interface Layoutable {
get_pos() (int, int)
mut:
set_pos(int, int)
}
pub struct LayouterBase {
mut:
layoutables []Layoutable
}
pub fn (mut lb LayouterBase) add(layoutable Layoutable) {
lb.layoutables << layoutable
}
pub fn (lb LayouterBase) get_pos() (int, int) {
return 0, 0
}
pub fn (mut lb LayouterBase) set_pos(x int, y int) {}
pub struct LinearLayout {
LayouterBase
}
pub fn (mut ll LinearLayout) layout() string {
mut output := ''
for mut l in ll.layoutables { …
```
=> ast: fix error for struct embedding with interface (fix #13411)

vlib/v/ast/table.v, vlib/v/tests/struct_embed_is_interface_test.v
This PR fix error for 'struct embed is interface'  (fix #13306).
- Fix error for 'struct embed is interface'.
- Add test.
```vlang
pub struct Base {
mut:
x int
y int
}
pub fn (mut b Base) init() {}
pub fn (b Base) get_pos() (int, int) {
return b.x, b.y
}
pub struct Label {
Base
}
pub interface Widget {
mut:
init()
}
pub interface Layoutable {
get_pos() (int, int)
}
pub struct Layout {
Base
mut:
widgets []Widget
}
pub fn (mut l Layout) layout() {
for wd in l.widgets {
if wd is Layoutable {
lw := wd as Layoutable
dump(lw.get_pos())
x, y := lw.get_pos()
assert x == 10
assert y == 20
} else {
println('wd is NOT Layoutable')
}
}
}
fn main() {
mut l := Layout{}
l.widgets << Label{
x: 10
y: 20
}
l.layout()
}
[.\\tt1.v:36] lw.get_pos(): (10, 20)
```
=> ast: fix error for 'struct embed is interface'  (fix #13306)

vlib/v/ast/table.v, vlib/v/tests/interface_embedding_call_test.v
This PR fix error for interface embedding call (fix #12766).
- Fix error for interface embedding call.
- Add test.
```vlang
module main
fn main() {
g1 := G1{}
do_the_greet(g1)
}
struct G1 {}
fn (g G1) greet() string {
return 'hello from G1'
}
fn do_the_greet(g ParentGreeter) {
greet := g.greet()
println('Someone says: $greet')
assert greet == 'hello from G1'
}
interface ParentGreeter {
Greeter
}
interface Greeter {
greet() string
}
Someone says: hello from G1
```
=> ast: fix error for interface embedding call (fix #12766)

cmd/tools/vast/vast.v, vlib/v/ast/ast.v, vlib/v/ast/table.v, vlib/v/ast/types.v, vlib/v/checker/checker.v, vlib/v/checker/interface.v, vlib/v/fmt/fmt.v, vlib/v/parser/struct.v
This PR makes cleanup of `interface embedding`.
- Change `ifaces` to `embeds` just like struct embedding.
=> all: cleanup interface embedding

vlib/v/gen/c/cgen.v, vlib/v/tests/interface_embedding_complex_test.v
This PR fix interface embedding complex cases (fix #13467).
- Fix interface embedding complex cases.
- Add test.
```vlang
fn main() {
mut win := &Window{}
ll := &LinearLayout{}
win.initables << ll
win.init()
}
//----------------------------------
[heap]
pub struct Window {
mut:
initables []Initable
}
interface Initable {
get_ptr()
mut:
init(&Window)
}
fn (mut w Window) init() {
for mut i in w.initables {
i.init(w)
}
}
//----------------------------------
pub struct ViewBase {}
pub fn (mut vb ViewBase) init(window &Window) {
dump(@METHOD)
assert false
}
pub fn (vb ViewBase) get_ptr() {}
//-------------------------------------
[heap]
pub struct ContainerBase {
ViewBase
}
// want to excute this method
pub fn (mut cb ContainerBase) init(window &Window) {
dump(@METHOD)
assert true
} …
```
=> cgen: fix interface embedding complex cases (fix #13467)

vlib/strings/strings.v, vlib/strings/strings_test.v
This PR adds a function I've personally missed a lot while working with strings in V. It introduces a way to extract content between two marks in a string in a "balanced" way. It makes it possible to extract "block" or "scope" content in a way that is currently not possible with either of the `find_between`, `all_after*`, `all_before*` methods defined on the `string` type.
My personal use case has been mostly to extract blocks of `enum` or `struct` contents from C (and V) code.
E.g. getting the contents between the opening `{` and closing `}` of the `SDL_RWops` struct in the following was not easy before without extensive parsing (or position/format hacks):
```c
typedef struct SDL_RWops
{
...
int (SDLCALL * close) (struct SDL_RWops * context);
Uint32 type;
union
{
#if defined(__ANDROID__) …
```
=> strings: add find_between_pair

vlib/v/builder/cc.v
the cmd ` v -cc clang -prod .` will fail with the error:
```
clang: error: 'x86_64-w64-windows-gnu': unable to pass LLVM bit-code files to linker
```
on windows for any V project fails without this patch.
=> builder: clang fails to link on windows due to an -ftlo error

cmd/tools/modules/testing/common.v, cmd/tools/vtest-self.v, vlib/net/smtp/smtp.v, vlib/net/smtp/smtp_test.v
This PR fixes the smtp module and adds STARTTLS and implicit SSL support
=> net.smtp: add STARTTLS and implicit SSL support

vlib/v/checker/fn.v, vlib/v/checker/tests/mut_interface_param_err.out, vlib/v/checker/tests/mut_interface_param_err.vv
This PR check mut interface arguments (fix #13437, fix #13456).
- Check mut interface arguments.
- Add test.
```vlang
interface Widget{
mut:
init()
}
struct Button{}
fn (mut b Button) init(){}
struct Label{}
fn (mut l Label) init(){}
struct Window{
mut:
widgets []Widget
}
fn (mut w Window) add_all(mut widgets []Widget){
for mut wd in widgets{
wd.init()
w.widgets << wd
}
}
fn main(){
mut win := Window{}
mut btn := Button{}
mut lbl := Label{}
mut arr := []Widget{}
arr << btn
arr << lbl
win.add_all(arr)  // This should be `mut` error, not refernce issue.
dump(win)
}
./tt1.v:31:14: error: `add_all` parameter `widgets` is `mut`, you need to provide `mut` e.g. `mut arg1`
29 |     arr << btn
30 |     arr << lbl
31 |     win.add_all(arr)  // This should be `mut` error, …
```
=> checker: check mut interface arguments (fix #13437, #13456)

vlib/crypto/ed25519/ed25519.v, vlib/crypto/ed25519/internal/ed25519_test.v, vlib/crypto/ed25519/internal/edwards25519/element.v, vlib/crypto/ed25519/internal/edwards25519/extra.v, vlib/crypto/ed25519/internal/edwards25519/point.v, vlib/crypto/ed25519/internal/edwards25519/scalar.v, vlib/crypto/ed25519/internal/edwards25519/scalarmult.v
Hi V folks, this PR intended to change the `Element` of `ed25519.internal.edwards25519` and availables methods as a public.
This is for several reason,
1. Internal machinery of `ed25519.internal.edwards25519` is needed when this functionality to be used as a basis of  others modules that need dealing with arithmatic of modulo prime of 2^255 - 19, think about `curve25519` or `curve448`.
2. Instead we make of copy of `ed25519.internal.edwards25519` for every modules we want to develop, i think its best just using methods or struct needed from standard library that has been available today.
3. so, this PR make hope for that aim ..
Thank you..
=> ed25519: make ed25519.internal.edwars25519.Element module as a public

vlib/builtin/string_test.v, vlib/v/checker/tests/string_char_null_err.out, vlib/v/checker/tests/string_char_null_err.vv, vlib/v/scanner/scanner.v
Allow for `assert 'A \x00 B'.bytes().hex() == '4120002042'`
Previously that was mainly a problem because println() stopped at 0
bytes in strings, and the values in the generated C code were not
escaped properly. Now these limitations are gone, so the restriction
can be lifted.
=> v.scanner: remove the restriction for \x00 in strings

vlib/math/big/big_test.v, vlib/math/big/integer.v
Adds a few utility functions to `big.Integer`.
Note that the implementation for `big_mod_pow` uses an extension of exponentiation by squaring. The performance for larger divisors can be improved by using a faster algorithm for division (a project for a later date).
=> math.big: add get_bit, set_bit, big_mod_pow

vlib/v/checker/containers.v, vlib/v/tests/array_of_sumtype_init_test.v
This PR fix error for array of sumtype init (fix #13463).
- Fix error for array of sumtype init.
- Add test.
```vlang
pub type MenuItem = Action | Group | Separater
pub struct Group {
children []MenuItem
}
pub struct Separater {}
pub struct Action {}
fn main() {
g := Group{
children: [
Action{},
Separater{},
Group{
children: [
Action{},
]
},
]
}
println(g)
assert g.children.len == 3
}
Group{
children: [MenuItem(Action{}), MenuItem(Separater{}), MenuItem(Group{
children: [MenuItem(Action{})]
})]
}
```
=> checker: fix error for array of sumtype init (fix #13463)

vlib/v/checker/fn.v, vlib/v/checker/tests/array_sort_with_compare_err.out, vlib/v/checker/tests/array_sort_with_compare_ref_elem_err.out, vlib/v/checker/tests/array_sort_with_compare_ref_elem_err.vv
This PR check array sort_with_compare callback function parameters (fix #11484).
- Check array sort_with_compare callback function parameters.
- Add test.
```vlang
struct Vec2 {
x f32
y f32
}
interface Cell {
mut:
pos Vec2
}
struct GridCell {
mut:
pos Vec2
}
pub struct Grid2D {
mut:
cells []&Cell
}
fn sort_cells_by_yx(a &Cell, b &Cell) int {
if a.pos.y == b.pos.y {
if a.pos.x < b.pos.x {
return -1
} else {
return 1
}
} else {
if a.pos.y < b.pos.y {
return -1
} else {
return 1
}
}
}
fn (mut g Grid2D) sort_cells() {
g.cells.sort_with_compare(sort_cells_by_yx)
}
fn main() {
mut grid := Grid2D{}
grid.cells << GridCell{
pos: Vec2{0, 0}
}
grid.cells << GridCell{
pos: Vec2{1, 0}
}
grid.cells << GridCell{
pos: Vec2{1, 2}
}
grid.sort_cells()
println(grid)
}
./tt1.v:21:23: …
```
=> checker: check array sort_with_compare callback function parameters (fix #11484)

vlib/v/builder/cc.v
Fix cross compiling to Windows, a project directory with spaces.
Closes #13517.
=> v.builder: fix cross compiling directory with spaces

vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/tests/generics_with_reference_generic_args_test.v
This PR fix generics with reference generic arguments (fix #13510).
- Fix generics with reference generic arguments.
- Add test.
```vlang
module main
fn foo<T>(val T) ?T {
return val
}
struct Bar {
num int
}
fn main() {
ret := foo<&Bar>(&Bar{ num: 123 }) or { panic(err) }
println(ret)
assert ret.num == 123
}
&Bar{
num: 123
}
```
=> cgen: fix generics with reference generic arguments (fix #13510)

vlib/v/checker/checker.v
I want get all available os in my code and define num for them
=> pub valid_comptime_if_os

vlib/v/gen/c/cgen.v, vlib/v/tests/interface_and_embedded_struct_build_test.v
This PR fix error for interface and embedded struct build (fix #13527).
- Fix error for interface and embedded struct build.
- Add test.
```vlang
pub struct Event {}
pub struct ViewBase {}
pub fn (vb ViewBase) point_inside(e Event) {}
pub struct ContainerBase {
ViewBase
}
interface Focusable {
point_inside(Event)
}
fn main() {
assert true
}
```
=> cgen: fix error for interface and embedded struct build (fix #13527)

vlib/v/gen/c/struct.v, vlib/v/tests/struct_init_with_multi_nested_embed_update_test.v
This PR fix struct init with multi nested embed update expr (fix #13523).
- Fix struct init with multi nested embed update expr.
- Add test.
```vlang
module main
struct Animal {
Duck
id int
}
struct Duck {
RedDuck
action string
}
struct RedDuck {
color string
}
fn main() {
d := Animal{Duck{RedDuck{'red'}, 'fly'}, 1}
println(d)
e := Animal{
...d
id: 2
}
println(e)
assert d.id == 1
assert e.id == 2
}
Animal{
Duck: Duck{
RedDuck: RedDuck{
color: 'red'
}
action: 'fly'
}
id: 1
}
Animal{
Duck: Duck{
RedDuck: RedDuck{
color: 'red'
}
action: 'fly'
}
id: 2
}
```
=> cgen: fix struct init with multi nested embed update expr (fix #13523)

vlib/net/unix/use_net_and_net_unix_together_test.v, vlib/v/parser/parser.v, vlib/v/parser/tests/defer_propagate2.out, vlib/v/parser/tests/defer_propagate2.vv
This PR check error for defer propagate (fix #13534).
- Check error for defer propagate.
- Add test.
```vlang
struct Abc {
mut:
x int = 123
}
fn (mut s Abc) close() ? {
println('> CLOSE 1 s.x: $s.x')
s.x = -1
println('> CLOSE 2 s.x: $s.x')
}
fn opt2() ?int {
mut s := Abc{}
dump(s.x)
defer {
s.close() ?
}
return s.x
}
fn main() {
println(opt2() ?)
}
./tt1.v:16:13: error: error propagation not allowed inside `defer` blocks
14 |     dump(s.x)
15 |     defer {
16 |         s.close() ?
|                   ^
17 |     }
18 |     return s.x
```
=> parser: check error for defer propagate (fix #13534)

vlib/v/ast/ast.v
This PR add comments for struct 'StructInit' and 'StructInitField'.
```vlang
// `field1: val1`
pub struct StructInitField {
pub:
pos           token.Pos
name_pos      token.Pos
comments      []Comment
next_comments []Comment
pub mut:
expr          Expr   // `val1`
name          string // 'field1'
typ           Type   // the type of this field
expected_type Type
parent_type   Type
}
// `s := Foo{
//    ...a
//    field1: 'hello'
// }`
pub struct StructInit {
pub:
pos             token.Pos
name_pos        token.Pos
is_short        bool // Foo{val1, val2}
is_short_syntax bool // foo(field1: val1, field2: val2)
pub mut:
unresolved           bool
pre_comments         []Comment
typ_str              string // 'Foo'
typ                  Type   // the type of this struct
update_expr          Expr …
```
=> ast: add comments for struct 'StructInit' and 'StructInitField'

vlib/v/ast/ast.v, vlib/v/ast/str.v, vlib/v/ast/table.v, vlib/v/checker/checker.v, vlib/v/checker/comptime.v, vlib/v/checker/if.v, vlib/v/fmt/fmt.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/comptime.v, vlib/v/gen/js/js.v, vlib/v/markused/walker.v, vlib/v/parser/comptime.v, vlib/v/parser/expr.v, vlib/v/parser/parser.v, vlib/v/tests/comptime_kinds_test.v
This PR implements simple generic compile-time types. There are 6 kinds of types: Array,Map,Interface,Struct,Int,Float. 
When you do `$if T is $Int`, compiler checks if T is of any possible integer type, same applies to other kinds of types.
In the next PRs additional fields will be introduced to these kinds. For example `Map` will get `key` and `element` fields that would allow you to match on them and this would allow to write complex code that depends on compile-time reflection (i.e it will be possible to finally make `x.json2` module work without user and compiler support)
=> all: initial implementation of compile-time types

vlib/v/gen/c/fn.v, vlib/v/tests/interface_embedding_method_call_test.v
This PR fix interface embedding method call (fix #13535).
- Fix interface embedding method call.
- Add test.
```vlang
fn main() {
mut window := &Window{}
btn := &Button{}
window.initables << btn
window.run()
}
[heap]
pub struct Window {
mut:
initables []Initable
popview   PopView = DummyPopup{}
}
interface Initable {
mut:
init(&Window)
}
interface Drawable {
draw()
}
pub fn (mut window Window) run() {
for mut i in window.initables {
i.init(window)
}
for wd in window.initables {
if wd is Drawable {
d := wd as Drawable
d.draw()
}
}
window.popview.draw()
}
struct DummyPopup {}
fn (d DummyPopup) draw() {}
interface PopView {
Drawable
}
[heap]
pub struct Button {
mut:
window &Window = voidptr(0)
}
pub fn (mut b Button) init(window &Window) {
b.window = window
}
pub fn (b Button) draw() {
g := …
```
=> cgen: fix interface embedding method call (fix #13535)

vlib/net/socket.v, vlib/v/checker/assign.v
This PR makes cleanup of `map = {}` processing.
- Remove useless codes of `map = {}` processing.
=> checker: cleanup 'map = {}' processing

doc/docs.md
added:
for immidaite realoocation and become independent you can call .clone() after slice brackets:
mut a := [0, 1, 2, 3, 4, 5]
mut b := a[2..4].clone()
b[0] = 7 // `b[0]` is not referring to `a[2]`
println(a) // `[0, 1, 2, 3, 4, 5]
=> doc: add how to get reallocated array by slicing

vlib/v/checker/struct.v, vlib/v/checker/tests/struct_field_reference_type_err.out, vlib/v/checker/tests/struct_field_reference_type_err.vv
This PR check struct field reference type mismatch (fix #13571).
- Check struct field reference type mismatch.
- Add test.
```vlang
struct Animal {
mut:
ageee int
duck  Duck
}
struct Duck {
age &int
}
fn main() {
mut animal := Animal{
ageee: 20
}
animal.duck = Duck{
age: animal.ageee
}
dump(animal.duck.age)
}
./tt1.v:17:3: error: reference field must be initialized with reference
15 |
16 |     animal.duck = Duck{
17 |         age: animal.ageee
|         ~~~~~~~~~~~~~~~~~
18 |     }
19 |     dump(animal.duck.age)
```
=> checker: check struct field reference type mismatch (fix #13571)

vlib/v/checker/checker.v, vlib/v/checker/containers.v, vlib/v/checker/tests/array_of_sumtype_append_err.out, vlib/v/checker/tests/array_of_sumtype_append_err.vv
This PR check error for array of sumtype appending (fix #13586).
- Check error for array of sumtype appending.
- Add test.
```vlang
type Bar = BarA | BarB
struct BarA {}
struct BarB {}
fn main() {
mut bar := []Bar{}
bar << ['hey']
bar << 'hey'
}
./tt1.v:9:9: error: cannot append `[]string` to `[]Bar`
8 |     mut bar := []Bar{}
9 |     bar << ['hey']
|            ~~~~~~~
10 |     bar << 'hey'
11 | }
./tt1.v:10:9: error: cannot append `string` to `[]Bar`
8 |     mut bar := []Bar{}
9 |     bar << ['hey']
10 |     bar << 'hey'
|            ~~~~~
11 | }
```
=> checker: check error for array of sumtype appending (fix #13586)

vlib/crypto/cipher/aes_ctr_test.v, vlib/crypto/cipher/ctr.v, vlib/crypto/cipher/des_ctr_test.v
This PR implements the Counter (CTR) Mode (ported from go standard library (simplified)) for block ciphers such as AES or DES.
To check the correctness of the simplification, use the following Go test: https://go.dev/play/p/KQEz5B8Cb6I
```v
import crypto.aes
import crypto.cipher
fn test_aes_ctr() {
key := '6368616e676520746869732070617373'.bytes()
iv := '1234567890123456'.bytes()
str := '73c86d43a9d700a253a96c85b0f6b03ac9792e0e757f869cca306bd3cba1c62b'
mut src := str.bytes()
aes_ctr_en(mut src, key, iv)
assert src.hex() == '04380c1470ab2d8a0b3f9b4c1949b8ace811f22bc0a455a8946a3ea7a03e9f8440820f273ce749e955e4adb9e8f6ffde82bae507e0b6164b531d3eeb32f5beb5'
aes_ctr_de(mut src, key, iv)
assert src.bytestr() == str
println('test_aes_ctr ok')
}
fn aes_ctr_en(mut src []byte, key []byte, iv []byte) …
```
=> crypto: implement Counter (CTR) Mode for AES and DES

vlib/crypto/cipher/aes_ofb_test.v, vlib/crypto/cipher/des_ofb_test.v, vlib/crypto/cipher/ofb.v
This PR implements the Output Feedback (OFB) Mode (ported from go standard library (simplified)) for block ciphers such as AES or DES.
To check the correctness of the simplification, use the following Go test: https://go.dev/play/p/u5whVghNoU7
```v
import crypto.aes
import crypto.cipher
fn test_aes_ofb() {
key := '6368616e676520746869732070617373'.bytes()
iv := '1234567890123456'.bytes()
str := '73c86d43a9d700a253a96c85b0f6b03ac9792e0e757f869cca306bd3cba1c62b'
mut src := str.bytes()
aes_ofb_en(mut src, key, iv)
assert src.hex() == '04380c1470ab2d8a0b3f9b4c1949b8aca120db226fa0a848236f9904f786dfc39bc433b5d3870d1cfdef36debdee5e6f39b0e8e9462b0151d61e822944181b51'
aes_ofb_de(mut src, key, iv)
assert src.bytestr() == str
println('test_aes_ofb ok')
}
fn aes_ofb_en(mut src []byte, key []byte, iv …
```
=> crypto: implement Output Feedback (OFB) Mode for AES and DES

vlib/crypto/ed25519/internal/edwards25519/scalar.v, vlib/v/fmt/fmt.v, vlib/v/fmt/tests/consts_with_comments_expected.vv, vlib/v/fmt/tests/consts_with_comments_input.vv, vlib/v/fmt/tests/consts_with_comments_keep.vv, vlib/v/parser/parser.v
This PR improves the placement of tail comments after *single line* const expressions.
Before this PR, the behaviour was:
`input.v`
```v
// leave 1.0
const one = 1 // leave 1.1
// move me 1.2
const two = 2 /* move 2
*/
```
`input.fmt.v`
```v
// leave 1.0
const one = 1
// leave 1.1
// move me 1.2
const two = 2
/*
move 2
*/
```
After this PR:
`input.v`
```v
// leave 1.0
const one = 1 // leave 1.1
// move me 1.2
const two = 2 /* move 2
*/
```
`input.fmt.v`
```v
// leave 1.0
const one = 1 // leave 1.1
// move me 1.2
const two = 2
/*
move 2
*/
```
... I find the behaviour introduced with this PR a bit more logical.
The most important part, to me, is that the trailing comment after the single line const expression is kept:
`const one = 1 // leave this comment`
`const two = 2 /* also leave this …
=> fmt: improve single line const comment placement

vlib/crypto/ed25519/internal/edwards25519/scalar.v, vlib/v/parser/expr.v, vlib/v/parser/tests/const_index.vv, vlib/v/tests/option_expr_with_array_value_test.v
This PR fix optional expr with array value.
- Fix optional expr with array value.
- Add test.
```vlang
pub struct Empty {
empty string
}
fn print_error() ?[]Empty {
mut test := []Empty{}
test << Empty{
empty: 'Test'
}
if test[0].empty != '' {
return error('Not empty')
}
return test
}
pub fn main() {
test_error := print_error() or {
eprintln(err)
[]Empty{}
}
println(test_error)
assert '$test_error' == '[]'
}
Not empty
[]
```
=> parser: fix optional expr with array value

vlib/v/ast/types.v
This PR makes cleanup in find_method_with_generic_parent().
- Also unwrap `interface` and `sum_type`  method generic return type.
=> ast: cleanup in find_method_with_generic_parent()

vlib/v/parser/struct.v, vlib/v/parser/tests/register_ierror_interface.out, vlib/v/parser/tests/register_ierror_interface.vv, vlib/v/parser/tests/register_ierror_struct.out, vlib/v/parser/tests/register_ierror_struct.vv
This PR check the redefinition of built-in `IError` (fix #12834).
- Check the redefinition of built-in `IError`.
- Add test.
```vlang
interface IError {
foo() string
}
fn main() {
println('Hello World')
}
./tt1.v:1:11: error: cannot register interface `IError`, it is builtin interface type
1 | interface IError {
|           ~~~~~~
2 |     foo() string
3 | }
```
```vlang
struct IError {
msg string
}
fn main() {
println('Hello World')
}
./tt1.v:1:8: error: cannot register struct `IError`, it is builtin interface type
1 | struct IError {
|        ~~~~~~
2 |     msg string
3 | }
```
=> parser: check the redefinition of built-in `IError` (fix #12834)

vlib/v/parser/fn.v, vlib/v/parser/parse_type.v, vlib/v/parser/parser.v, vlib/v/parser/tests/fn_decl_return_type_err_a.out, vlib/v/parser/tests/fn_decl_return_type_err_a.vv, vlib/v/parser/tests/fn_decl_return_type_err_b.out, vlib/v/parser/tests/fn_decl_return_type_err_b.vv
This PR check using 'mut' on fn_decl return type.
- Check using 'mut' on fn_decl return type.
- Add test.
```vlang
struct Foo{}
fn maker() ?mut Foo {
inner := &Foo{}
return *inner
}
fn main() {
}
./tt1.v:3:13: error: cannot use `mut` on fn return type
1 | struct Foo{}
2 |
3 | fn maker() ?mut Foo {
|             ~~~
4 |     inner := &Foo{}
5 |     return *inner
```
```vlang
struct Foo{}
fn maker() (mut Foo) {
inner := &Foo{}
return *inner
}
fn main() {
}
./tt1.v:3:13: error: cannot use `mut` on fn return type
1 | struct Foo{}
2 | 
3 | fn maker() (mut Foo) {
|             ~~~
4 |     inner := &Foo{}
5 |     return *inner
```
=> parser: check using 'mut' on fn_decl return type

vlib/v/gen/c/fn.v, vlib/v/tests/fn_mut_arg_of_interface_test.v
This PR fix fn mut argument of interface type (fix #12537).
- Fix fn mut argument of interface type.
- Add test.
```vlang
module main
interface TheInterface {
mut:
an_interface() ?
}
struct Implementation {
}
fn (mut i Implementation) an_interface() ? {
return
}
fn maker() ?TheInterface {
inner := Implementation{}
return inner
}
fn do(mut inter TheInterface) string {
return 'ok'
}
fn main() {
mut inner := maker() ?
ret := do(mut inner)
println(ret)
assert ret == 'ok'
}
ok
```
=> cgen: fix fn mut argument of interface type (fix #12537)

vlib/net/html/dom.v
Fixed to use `erprintln()` since if `panic()` is used here, other programs using the `html` module will `panic` when we run our program in debugging.
=> net: fix html dom debug print

vlib/v/gen/c/cgen.v, vlib/v/tests/cast_optional_to_interface_test.v
This PR fix error for optional cast to interface (fix #12905, fix #13116).
- Fix error for optional cast to interface.
- Add test.
```vlang
[heap]
struct Package {
str string
}
interface Parser {
main &Package
}
struct ParserV1 {
mut:
main &Package
}
fn new_0_parser() ?ParserV1 {
return ParserV1{
main: &Package{
str: 'test'
}
}
}
fn new_parser() ?Parser {
return Parser(new_0_parser() ?)
}
struct Engine {
parser Parser
}
fn main() {
parser := new_parser() ?
assert parser.main.str == 'test'
eprintln(voidptr(parser.main))
e := Engine{
parser: parser
}
assert e.parser.main.str == 'test'
eprintln(voidptr(e.parser.main))
}
0x8a6890
0x8a6890
```
```vlang
module main
[heap]
struct Package {
str string
}
interface ParserInterface {
main &Package
}
struct Parser {
mut: …
```
=> cgen: fix error for optional cast to interface (fix #12905, #13116)

vlib/v/ast/table.v, vlib/v/parser/parser.v
This PR fix error for 'for smartcast' - part 1.
```vlang
mut elem_type := ts.info.elem_type
mut elem_sym := t.sym(elem_type)
mut dims := 1
for mut elem_sym.info is Array {
info := elem_sym.info as Array
elem_type = info.elem_type
elem_sym = t.sym(elem_type)
dims++
}
```
The `for smartcast` cannot work before.
Fix it must use 2 steps commit and this is step 1.
=> parser: fix error for 'for smartcast' - part 1

vlib/v/gen/c/fn.v, vlib/v/gen/c/str_intp.v, vlib/v/tests/print_smartcast_variable_test.v
This PR fix error for print smartcast variable (fix #13622).
- Fix error for print smartcast variable.
- Add test.
```vlang
struct Point {
x int
y int
}
struct Line {
p1 Point
p2 Point
}
// Sum type
type ObjSumType = Line | Point
fn test_print_smartcast_variable() {
// Type checking and casts
mut point := ObjSumType(Point{2, 5})
if point is Point {
println('Point')
}
if point !is Point {
println('Not Point')
}
if mut point is Point {
println(point)
assert point.str().contains('x: 2')
assert point.str().contains('y: 5')
assert '$point'.contains('x: 2')
assert '$point'.contains('y: 5')
}
}
Point
Point{
x: 2
y: 5
}
```
=> cgen: fix error for print smartcast variable (fix #13622)

vlib/v/ast/ast.v, vlib/v/ast/table.v
This PR fix error for 'for smartcast' - part 2.
```vlang
mut elem_type := sym.info.elem_type
mut elem_sym := t.sym(elem_type)
mut dims := 1
for mut elem_sym.info is Array {
elem_type = elem_sym.info.elem_type
elem_sym = t.sym(elem_type)
dims++
}
```
=> ast: fix error for 'for smartcast' - part 2

vlib/v/checker/containers.v, vlib/v/tests/array_of_interface_init_test.v
This PR fix error for array of interface init in for_in (fix #11542).
- Fix error for array of interface init in for_in.
- Add test.
```vlang
struct Dog {
breed string
}
struct Cat {
breed string
}
fn (d Dog) speak() string {
return 'woof'
}
fn (c Cat) speak() string {
return 'meow'
}
interface Speaker {
breed string
speak() string
}
fn main() {
dog := Dog{'Leonberger'}
cat := Cat{'Siamese'}
for item in [Speaker(dog), cat] {
println(item.speak())
rets << item.speak()
}
assert rets[0] == 'woof'
assert rets[1] == 'meow'
}
woof
meow
```
=> checker: fix error for array of interface init in for_in (fix #11542)

vlib/v/checker/checker.v, vlib/v/checker/for.v, vlib/v/checker/if.v, vlib/v/checker/match.v, vlib/v/checker/tests/incorrect_smartcast_err.out, vlib/v/checker/tests/incorrect_smartcast_err.vv
This PR notice incorrect smartcast (fix #12058).
- Notice incorrect smartcast.
- Add test.
```vlang
interface IExample{
}
struct Example{
field string
}
fn main(){
mut example := IExample(Example{field:"test"})
if example is Example{
println(example.field)
}
}
./tt1.v:10:5: notice: smartcasting requires either an immutable value, or an explicit mut keyword before the value
8 | fn main(){
9 |     mut example := IExample(Example{field:"test"})
10 |     if example is Example{
|        ~~~~~~~
11 |         println(example.field)
12 |     }
./tt1.v:11:19: error: type `IExample` has no field named `field`
9 |     mut example := IExample(Example{field:"test"})
10 |     if example is Example{
11 |         println(example.field)
|                         ~~~~~
12 |     } …
```
=> checker: notice incorrect smartcast (fix #12058)

doc/docs.md
Fixes these two errors when trying to use the shell script example:
> error: function declarations in script mode should be before all script statements
> error: unexpected `?`, the function `os.execute` does not return an optional
=> docs: fix vsh example

vlib/v/checker/tests/assign_expr_undefined_err_m.out, vlib/v/checker/tests/assign_expr_undefined_err_m.vv, vlib/v/checker/tests/assign_expr_undefined_err_n.out, vlib/v/checker/tests/assign_expr_undefined_err_n.vv, vlib/v/parser/assign.v
This PR check assign expr with undefined variable (fix #13648).
- Check assign expr with undefined variable.
- Add test.
```vlang
fn main(){
a := 'add'
n := 2
x := match a {
'add'{ n + x }
else{ 0 }
}
println(x)
}
./tt1.v:5:14: error: undefined variable: `x`
3 |     n := 2
4 |     x := match a {
5 |         'add'{ n + x }
|                    ^
6 |         else{ 0 }
7 |     }
```
```vlang
fn main(){
a := 'add'
n := 2
x := if a == 'add' { n + x } else { 0 }
println(x)
}
./tt1.v:4:27: error: undefined variable: `x`
2 |     a := 'add'
3 |     n := 2
4 |     x := if a == 'add' { n + x } else { 0 }
|                              ^
5 |     println(x)
6 | }
```
=> parser: check assign expr with undefined variable (fix #13648)

vlib/cli/command.v, vlib/term/term.v
Errors are now way prettier, see an example with [Go2V](https://github.com/vlang/go2v):
=> vlib: cli errors now print in red

vlib/toml/tests/alexcrichton.toml-rs-tests_test.v, vlib/toml/tests/burntsushi.toml-test_test.v, vlib/toml/tests/iarna.toml-spec-tests_test.v, vlib/toml/to/to.v, vlib/x/json2/encoder.v, vlib/x/json2/encoder_test.v
This PR adds a new struct named `Encoder` that allows customizing the JSON output. With the new `json2.Encoder`, we can now:
- "Prettify" the output by adding newlines and control the space count for each break. 
- Enable / disable escaping of unicode symbols (CJK and emojis) through the `escape_unicode` option (defaults to true)
- And many more later...
```v
import x.json2
import strings
fn main() {
obj := {'hello': json.Any('world')}
mut sb := &strings.Builder{} 
enc := json2.Encoder{}
enc.encode_value(obj, mut sb) ?
println(sb.str()) // {"hello":"world"}
}
```
```v
import x.json2
import strings
fn main() {
obj := {'hello': json.Any('world')}
mut sb := &strings.Builder{newline: `\n`, newline_space_count: 4} 
enc := json2.Encoder{}
enc.encode_value(obj, mut sb) ?
println(sb.str())
}
``` …
=> x/json2: add customized JSON output capability via Encoder

vlib/x/json2/decoder.v, vlib/x/json2/decoder_test.v, vlib/x/json2/scanner.v
This PR fixes the use of error types in the context of catching decoder errors. The two most common errors: `InvalidTokenError` and `UnknownTokenError`, now generate appropriate error messages based on the underlying error type. Added new tests for catching these specific errors
=> x/json2: fix decoder errors

vlib/v/checker/checker.v, vlib/v/checker/tests/or_err.out, vlib/v/parser/tests/or_default_missing.out, vlib/v/parser/tests/prefix_first.out, vlib/v/tests/or_expr_with_nested_match_expr_test.v
This PR fix error for 'or expr with nested match expr' (fix #13628).
- Fix error for 'or expr with nested match expr'.
- Add test.
```vlang
pub struct API_error {
pub mut:
errors []string
}
pub fn delete_secret_v1() API_error {
response := req_do() or {
match err.msg {
'dial_tcp failed' {
return API_error{
errors: ['Vault server not started']
}
}
else {
return API_error{
errors: [err.msg]
}
}
}
}
println(response)
}
pub fn req_do() ?string {
return error('dial_tcp failed')
}
pub fn main() {
err := delete_secret_v1()
println(err)
assert err.errors.len == 1
assert err.errors[0] == 'Vault server not started'
}
API_error{
errors: ['Vault server not started']
}
```
```vlang
pub struct API_error {
pub mut:
errors []string
}
pub fn …
```
=> checker: fix error for 'or expr with nested match expr' (fix #13628)

vlib/v/gen/c/struct.v, vlib/v/tests/struct_of_time_init_with_update_test.v
This PR fix error for time struct init with update (fix #13659).
- Fix error for time struct init with update.
- Add test.
```vlang
import time
fn main() {
utc := time.utc()
t := time.Time{
...utc
}
println(utc)
println(t)
assert t == utc
}
2022-03-05 10:44:50
2022-03-05 10:44:50
```
=> cgen: fix error for time struct init with update (fix #13659)

vlib/v/gen/c/cgen.v, vlib/v/gen/c/struct.v
This PR makes minor cleanup of struct.v.
- Remove `g.go_back_out(n)` and unified using `g.out.go_back (n)`.
=> cgen: minor cleanup of struct.v

vlib/sync/stdatomic/1.declarations.c.v
It may also benefit other Red Hat based distros like CentOS and Fedora.
=> sync: enable tcc compilation of sync programs on Amazon Linux 2 by default

vlib/v/gen/c/auto_str_methods.v, vlib/v/tests/str_array_of_reference_test.v
This PR fix error for array of reference auto_str (fix #13662).
- Fix error for array of reference auto_str.
- Add test.
```vlang
fn main() {
names := ['John', 'Paul', 'George', 'Ringo']
a := unsafe { [&names[0], &names[1]] }
println(a[0])
println(a)
assert '$a' == "[&'John', &'Paul']"
}
&John
[&'John', &'Paul']
```
=> cgen: fix error for array of reference auto_str (fix #13662)

vlib/v/checker/checker.v, vlib/v/checker/tests/infix_unsigned_and_signed_int_err.out, vlib/v/checker/tests/infix_unsigned_and_signed_int_err.vv
This PR check unsigned integer compared with negative value (fix #13597).
- Check unsigned integer compared with negative value.
- Add test.
```vlang
fn main() {
if u32(1) < -1 {
println('unexpected')
}
if -1 > u32(1) {
println('unexpected')
}
}
./tt1.v:2:14: error: unsigned integer cannot be compared with negative value
2 |     if u32(1) < -1 {
|                 ~~
3 |         println('unexpected')
4 |     }
./tt1.v:6:5: error: unsigned integer cannot be compared with negative value
4 |     }
5 |
6 |     if -1 > u32(1) {
|        ~~
7 |         println('unexpected')
8 |     }
```
=> checker: check unsigned integer compared with negative value (fix #13597)

.gitattributes, cmd/tools/vcreate.v, cmd/tools/vcreate_test.v
1. It's annoying to see `v.mod` files being marked as AMPL so the `.gitattributes` correctly assigns the V language to them.
2. The `.vsh` files were initially excluded from the `.gitattributes` list. It wasn't a severe problem but when cloning on Windows machines, the line endings were set to `crlf` which would break `v fmt` by adding unnecessary lines. Setting line endings to `lf` solves the CI issues too.
=> cmd/tools: modify .gitattributes to categorize *.vsh and v.mod files properly

vlib/v/gen/native/amd64.v, vlib/v/gen/native/elf.v, vlib/v/gen/native/gen.v, vlib/v/gen/native/macho.v
This PR adds support for PIE executables on Linux, but also cleanups and improves several other things
* Consistency write APIs for strings and relative addressing instead of absolute pointers
* String allocation supports 32 and 64 reloc patching and use LEA on x86
* Cleanup ELF constants and generation logic for readability
=> native: generate relocatable ELFs and support relative strings

vlib/arrays/arrays.v, vlib/arrays/arrays_test.v, vlib/builtin/array.v
Implement generic version of builtin `fn copy`. Has same semantics as https://pkg.go.dev/builtin#copy.
Make builtin `copy` use `memmove` not `memcpy` as arrays could overlap when sliced.
=> vlib/arrays: add generic copy fn

vlib/v/checker/checker.v, vlib/v/checker/match.v, vlib/v/tests/match_expr_with_enum_test.v
This PR fix match expr with enum type value (fix #13667).
- Fix match expr with enum type value.
- Add test.
```vlang
enum Foo {
a
b
c
}
fn get() Foo {
return .a
}
fn foo(f Foo) string {
println(f)
return '$f'
}
fn main() {
ret := foo(match get() {
.a { .b }
.b { .c }
.c { .a }
})
println(ret)
assert ret == 'b'
}
b
b
```
=> checker: fix match expr with enum type value (fix #13667)

vlib/v/checker/if.v, vlib/v/tests/if_expr_with_enum_test.v
This PR fix if expr with enum value.
- Fix if expr with enum value.
- Add if_expr_with_enum_test.v.
```vlang
enum Foo {
a
b
}
fn get() Foo {
return .a
}
fn foo(f Foo) string {
println(f)
return '$f'
}
fn main() {
ret := foo(if get() == .a { .b } else { .a })
println(ret)
assert ret == 'b'
}
b
b
```
=> checker: fix if expr with enum value

vlib/v/checker/checker.v
This PR remove redundant `c.expected_type = ast.void_type` in stmts_ending_with_expression().
- Because c.expected_type would be set ast.void_type at the beginning of stmt(), so there's no need to set in stmts_ending_with_expression().
=> checker: remove redundant 'c.expected_type = ast.void_type'

vlib/v/checker/checker.v, vlib/v/checker/tests/infix_compare_optional_err.out, vlib/v/checker/tests/infix_compare_optional_err.vv
This PR check error for infix compare optional (fix #13695).
- Check error for infix compare optional.
- Add test.
```vlang
fn foo() ?int{
return 0
}
fn main(){
if foo() > foo() {}
}
./tt1.v:6:5: error: unwrapped optional cannot be compared in an infix expression
4 | 
5 | fn main(){
6 |     if foo() > foo() {}
|        ~~~~~~~~~~~~~
7 | }
```
=> checker: check error for infix compare optional (fix #13695)

vlib/os/os.v
Fixes an issue with calling `os.quoted_path` on Windows, if the path has a trailing backslash.
Before the fix, quoting `foo\` would return `"foo\"`... which just forces the trailing `"` as part of the path string.
After the fix, quoting `foo\` returns `"foo\\"`... preserving the trailing backslash.
=> fix: handle trailing backslash on windows path when quoting

vlib/arrays/arrays.v, vlib/arrays/arrays_test.v
autofree needs to intervene for those types, so use element assignment.
Also map is not copyable.
Follows on from https://github.com/vlang/v/pull/13677
=> vlib/arrays: fix `copy` to not use memcpy for array, map, string

vlib/v/ast/table.v, vlib/v/ast/types.v, vlib/v/checker/checker.v, vlib/v/checker/struct.v, vlib/v/parser/parse_type.v, vlib/v/parser/parser.v, vlib/v/parser/struct.v
This PR rename TypeSymbol.is_public to TypeSymbol.is_pub.
- Maintain customary consistency with overall usage.
=> ast: rename TypeSymbol.is_public to TypeSymbol.is_pub

vlib/v/parser/fn.v, vlib/v/tests/fn_type_only_argument_test.v
This PR fix error for fn with type only argument (fix #13704).
- Fix error for fn with type only argument.
- Add test.
```vlang
module main
import gg
import gx
struct Game {
update fn (mut gg.Context) = fn (mut gg gg.Context) {}
draw   fn (mut gg.Context) = fn (mut gg gg.Context) {}
mut:
gg gg.Context
}
fn main() {
mut game := Game{}
game.gg = gg.new_context(
bg_color: gx.rgb(230, 230, 240)
)
assert true
}
fn frame(mut game Game) {
game.gg.begin()
game.gg.draw_triangle_filled(450, 142, 530, 280, 370, 280, gx.red)
game.update(mut game.gg)
game.draw(mut game.gg)
game.gg.end()
}
```
=> parser: fix error for fn with type only argument (fix #13704)

vlib/v/parser/fn.v
This PR makes a minor cleanup in fn_args().
- Using `p.peek_tok` instead of `p.peek_token(1)`.
=> parser: minor cleanup in fn_args()

vlib/v/parser/expr.v, vlib/v/parser/parser.v, vlib/v/parser/tests/map_syntax_err.out, vlib/v/parser/tests/map_syntax_err.vv
This PR makes cleanup of map syntax.
- Map syntax error changed from warning to error.
- Remove redundant judgment processing.
- Add check error test.
```vlang
fn main() {
m := map{"aaa": 1}
println(m)
}
./tt1.v:2:7: error: deprecated map syntax, use syntax like `{'age': 20}`
2 |     x := map{"aaa": 1}
|          ~~~
3 |     println(x)
4 | }
```
=> parser: cleanup map syntax

vlib/rand/rand.c.v, vlib/rand/rand.js.v, vlib/rand/rand.v, vlib/rand/random_bytes_test.v
- Adds missing `read` function to the `PRNG` interface. Also add unit tests.
- Makes more functions available to both the generator interface and the `rand` module.
=> rand: further bridge gap b/w rand module and PRNG interface

vlib/v/ast/ast.v, vlib/v/ast/table.v, vlib/v/checker/assign.v, vlib/v/checker/check_types.v, vlib/v/checker/checker.v, vlib/v/checker/match.v, vlib/v/checker/tests/match_mut_with_immutable_var_err.out, vlib/v/checker/tests/match_mut_with_immutable_var_err.vv, vlib/v/fmt/fmt.v, vlib/v/gen/c/assert.v, vlib/v/gen/c/auto_str_methods.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/infix_expr.v, vlib/v/gen/js/auto_str_methods.v, vlib/v/gen/js/deep_copy.v, vlib/v/gen/js/js.v, vlib/v/gen/native/amd64.v, vlib/v/gen/native/gen.v, vlib/v/markused/walker.v, vlib/v/parser/assign.v, vlib/v/parser/parser.v, vlib/v/tests/sumtype_assign_test.v, vlib/v/transformer/transformer.v
This PR check error for match mut with immutable variable (fix #9704, fix #8976).
- Check error for match mut with immutable variable.
- Add test.
- Fix all the related errors.
```vlang
type Int = byte | int
fn main() {
i := Int(0)
match mut i {
int { i = 1 }
byte { i = 2 }
}
println(i)
}
./tt1.v:5:12: error: `i` is immutable, declare it with `mut` to make it mutable
4 |     i := Int(0)
5 |     match mut i {
|               ^
6 |         int { i = 1 }
7 |         byte { i = 2 }
```
=> checker: check error for match mut with immutable variable (fix #9704 #8976)

vlib/stbi/stbi.c.v
`fn load` in `stbi.c.v` creates an error when trying to load a JPG file. (See https://discord.com/channels/592103645835821068/592294828432424960/951999502364061737)
=> stbi: fixed panic when trying to load JPG

vlib/v/ast/ast.v, vlib/v/checker/assign.v, vlib/v/checker/checker.v, vlib/v/checker/for.v, vlib/v/checker/if.v, vlib/v/checker/match.v, vlib/v/checker/tests/if_mut_with_immutable_var_err.out, vlib/v/checker/tests/if_mut_with_immutable_var_err.vv, vlib/v/fmt/fmt.v, vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/infix_expr.v, vlib/v/gen/c/str_intp.v, vlib/v/parser/comptime.v
This PR check error for if mut with immutable variable.
- Check error for if mut with immutable variable.
- Add test.
- Fix all the related errors.
```vlang
type Int = byte | int
fn main() {
i := Int(0)
if mut i is int {
i = 1
} else if mut i is byte {
i = 2
}
println(i)
}
./tt1.v:5:9: error: `i` is immutable, declare it with `mut` to make it mutable
4 |     i := Int(0)
5 |     if mut i is int {
|            ^
6 |         i = 1
7 |     } else if mut i is byte {
./tt1.v:7:16: error: `i` is immutable, declare it with `mut` to make it mutable
5 |     if mut i is int {
6 |         i = 1
7 |     } else if mut i is byte {
|                   ^
8 |         i = 2
9 |     }
```
=> checker: check error for if mut with immutable variable

vlib/math/math.v, vlib/math/math_test.v
The PR improves a function in math library to accept larger numbers. The current math.digits function only accepts int type. This PR changes that to accept i64 allowing larger numbers to be converted e.g. telephone numbers, credit card numbers, barcode numbers. The base argument is optional and defaults to base 10 which should satisfy most cases.
PR also adds a small convenience function count_digits which will return the number of digits in a given integer. 
```
digits(12345)  => [5,4,3,2,1]
digits(i16(5478), 7) => [4, 5, 6, 1, 2]
digits(i64(1_800_275_227), 10) => [7, 2, 2, 5, 7, 2, 0, 0, 8, 1]
count_digits(12345) => 5
count_digits(i16(5478))  => 4
count_digits(i64(1_800_275_227)) => 10
count_digits(-12345) => 5
```
=> math: allow i64 in digits function and add count_digits function

vlib/v/parser/if_match.v, vlib/v/tests/match_branch_with_array_expression_test.v
This PR fix error for match branch with array expression (fix #13190).
- Fix error for match branch with array expression.
- Add test.
```vlang
fn main() {
ret := match true {
[''].contains('') { 22 }
else { 0 }
}
println(ret)
}
22
```
=> parser: fix error for match branch with array expression (fix #13190)

doc/docs.md
Examples for struct field access modifiers are out of date, the builtin string
has no private methods anymore. Instead it's proposed to explain behavior
of access modifiers, because there is no exhaustive definition of visibility
and mutability for struct fields.
=> doc: update struct access modifiers

vlib/v/ast/types.v, vlib/v/tests/typeof_aggregate_test.v
This PR fix error for typeof aggregate (fix #12828).
- Fix error for typeof aggregate.
- Add test.
```vlang
struct Foo {
}
struct Bar {
text string
}
struct Baz {
text string
}
struct Bazaar {
text string
}
type FBB = Bar | Baz | Bazaar | Foo
fn main() {
mut arr := []FBB{}
arr << Foo{}
arr << Bar{
text: 'bar'
}
arr << Baz{
text: 'baz'
}
for a in arr {
match a {
Foo {
println('The type of `a` is `${typeof(a).name}`')
rets << 'The type of `a` is `${typeof(a).name}`'
}
Bar, Baz, Bazaar {
println('The type of `a` is `${typeof(a).name}` and its text says $a.text')
rets << 'The type of `a` is `${typeof(a).name}` and its text says $a.text'
}
}
}
assert rets.len == 3
assert rets[0] == 'The type of `a` is `Foo`'
assert rets[1] == 'The type of `a` is `(Bar | Baz | Bazaar)` …
```
=> ast: fix error for typeof aggregate (fix #12828)

vlib/v/checker/checker.v, vlib/v/checker/tests/invalid_mut.out, vlib/v/checker/tests/invalid_mut.vv, vlib/v/parser/tests/unnecessary_mut.out
This PR check invalid 'mut' keyword in infix expr (related #8187).
- Check invalid 'mut' keyword in infix expr.
- Add test.
```v
fn main() {
mut x := 0
if mut x == 0 {
println(true)
}
if 0 == mut x {
println(true)
}
_ = x
}
./tt1.v:3:5: error: the `mut` keyword is invalid here
2 |     mut x := 0
3 |     if mut x == 0 {
|        ~~~
4 |         println(true)
5 |     }
./tt1.v:6:10: error: the `mut` keyword is invalid here
4 |         println(true)
5 |     }
6 |     if 0 == mut x {
|             ~~~
7 |         println(true)
8 |     }
```
=> checker: check invalid 'mut' keyword in infix expr (related #8187)

vlib/v/ast/ast.v
This PR makes a minor cleanup in is_blank_ident().
- Use `if expr is Ident` instead of `match expr {...}`.
=> ast: minor cleanup in is_blank_ident()

vlib/v/checker/match.v, vlib/v/checker/tests/match_return_sumtype_mismatch_err.out, vlib/v/checker/tests/match_return_sumtype_mismatch_err.vv
This PR check the sumtype mismatch returned by match expr (fix #13750).
- Check the sumtype mismatch returned by match expr.
- Add test.
```v
type St = string
type Ru = rune
type Myt = Ru | St
fn myt_t1(b bool) Myt {
match b {
true { return St('TRUE') }
false { return Ru(`F`) }
}
}
fn myt_t2(b bool) Myt {
return match b {
true { St('TRUE') }
false { `F` }
}
}
fn main() {}
./tt1.v:15:11: error: return type mismatch, it should be `Myt`
13 |     return match b {
14 |         true { St('TRUE') }
15 |         false { `F` }
|                 ~~~
16 |     }
17 | }
```
=> checker: check the sumtype mismatch returned by match expr (fix #13750)

vlib/v/gen/c/if.v, vlib/v/tests/if_expr_with_sumtype_test.v
This PR fix error for if expr returning sumtype (fix #9215).
- Fix error for if expr returning sumtype.
- Add test.
```v
struct A_str {}
struct B_str {}
type Token = A_str | B_str
fn next(mut v []Token) Token {
return if v.len > 0 { v.pop() } else { A_str{} }
}
fn main() {
mut arr := []Token{}
ret1 := next(mut arr)
println(ret1)
assert '$ret1' == 'Token(A_str{})'
arr << A_str{}
arr << B_str{}
ret2 := next(mut arr)
println(ret2)
assert '$ret2' == 'Token(B_str{})'
}
Token(A_str{})
Token(B_str{})
```
=> cgen: fix error for if expr returning sumtype (fix #9215)

vlib/strings/builder.c.v, vlib/strings/builder_test.v
This function behaves exactly the same way as the ones in Go ([`strings.Builder.grow()`](https://pkg.go.dev/strings#Builder.Cap) & [`bytes.Buffer.grow()`](https://pkg.go.dev/bytes?utm_source=gopls#Buffer.Grow)) apart that when giving a negative number it doesn't panic, it just do nothing.
I've also added tests.
=> strings: add `Builder.ensure_cap()` method

.github/workflows/other_ci.yml, vlib/v/gen/c/cgen.v, vlib/v/gen/c/index.v, vlib/v/tests/slice_rval_test.v
Use a temporary variable when the high index expression is missing to avoid double evaluation.
Note: Double evaluation still happens slicing a string or fixed array, I can fix that separately. BTW I'm not sure what the `else` case is, what else can be sliced?
=> gen/c: fix double evaluation of rvalue array expression in slice

vlib/v/parser/if_match.v, vlib/v/parser/tests/if_guard_cond_err.out, vlib/v/parser/tests/if_guard_cond_err.vv
This PR check error of if guard condition expression (fix #13756).
- Check error of if guard condition expression.
- Add test.
```v
import os
import flag
const version = "v0.1.0"
// getting command line options and arguments
// returns the arguments
fn get_args() ?[]string {
mut fp := flag.new_flag_parser(os.args)
fp.application('ticker')
fp.version(version)
fp.description('A CLI yahoo ticker app')
fp.skip_executable()
fp.usage_example('GOOG AAPL')
_ := fp.bool('version', `v`, false, 'version information.')
if args := fp.finalize() && args.len > 0 {
return args
} else {
eprintln(err.msg())
println(fp.usage())
return none
}
}
fn main() {
tickers := get_args() or { return }
println(tickers)
}
./tt1.v:16:16: error: if guard condition expression is illegal, it should …
```
=> parser: check error of if guard condition expression (fix #13756)

vlib/v/gen/c/index.v
Use sizeof element type rather than sizeof indexed expression.
=> gen/c: simplify slicing fixed array

vlib/v/checker/checker.v, vlib/v/checker/if.v, vlib/v/checker/match.v, vlib/v/checker/tests/incorrect_smartcast2_err.out, vlib/v/checker/tests/incorrect_smartcast2_err.vv
This PR notice invalid smartcast with if/match none ident or selector (fix #12317).
- Notice invalid smartcast with if/match none ident or selector.
- Add test.
```v
struct Left<E> {
error E
}
struct Right<T> {
inner T
}
type Either<T, E> =
Left<E> |
Right<T>
fn works(v []Either<int, int>) {
first := v[0]
match first {
Left<int> {
println(first.error)
}
else {}
}
}
fn doesntwork(v []Either<int, int>) {
match v[0] {
Left<int> {
println(v[0].error)
}
else {}
}
}
fn main() {}
./tt1.v:24:9: notice: smartcast can only be used on the ident or selector, e.g. match foo, match foo.bar
22 |
23 | fn doesntwork(v []Either<int, int>) {
24 |     match v[0] {
|            ~~~
25 |         Left<int> {
26 |             println(v[0].error)
./tt1.v:26:17: error: field `error` does …
```
=> checker: notice invalid smartcast with if/match none ident or selector (fix #12317)

cmd/tools/vgret.v, vlib/toml/checker/checker.v, vlib/toml/decoder/decoder.v, vlib/toml/input/input.v, vlib/toml/scanner/scanner.v, vlib/toml/toml.v
...also make it harder to pass wrong data source to scanner/parser.
Following up on second `auto_config` horror show in https://discord.com/channels/592103645835821068/592114487759470596/954101934988615721
=> toml: deprecate input.auto_config() and toml.parse()

vlib/v/gen/c/infix_expr.v, vlib/v/tests/empty_interface_test.v
This PR fix error for empty interface (fix #13760).
- Fix error for empty interface.
- Add test.
```v
interface Any{}
fn print_out(x Any) string {
if x is string {
println(x)
return '$x'
}
return ''
}
fn main(){
ret := print_out('12345')
assert ret == '&12345'
}
&12345
```
=> cgen: fix error for empty interface (fix #13760)

vlib/v/ast/ast.v, vlib/v/checker/fn.v, vlib/v/gen/c/cgen.v, vlib/v/tests/go_anon_fn_variable_call_test.v
This PR fix error for go anon fn variable call (fix #13741).
- Fix error for go anon fn variable call.
- Add test.
```v
fn sum(a int, b int) int {
// Simply proxy the function into an anonymous function for demo purposes
sum_func := fn (a int, b int) int {
return a + b
}
// and run it concurrently
g := go sum_func(a, b)
result := g.wait()
return result
}
fn main() {
ret := sum(22, 33)
println(ret)
assert ret == 55
}
55
```
=> ast, checker, cgen: fix error for go anon fn variable call (fix #13741)

vlib/v/checker/struct.v, vlib/v/checker/tests/struct_field_init_with_nobody_anon_fn_err.out, vlib/v/checker/tests/struct_field_init_with_nobody_anon_fn_err.vv
This PR check error for struct field init with nobody anon fn (fix #9858).
- Check error for struct field init with nobody anon fn.
- Add test.
```v
struct App {
cb fn(x int) // the function signature doesn't make a difference
}
fn main() {
_ = App{
cb: fn(x int)  // Note the missing `{}` (the function body) here
}
}
./tt1.v:7:7: error: cannot initialize the fn field with anonymous fn that does not have a body
6 |     _ = App{
7 |         cb: fn(x int)  // Note the missing `{}` (the function body) here
|             ~~~~~~~~~
8 |     }
9 | }
```
=> checker: check error for struct field init with nobody anon fn (fix #9858)

vlib/v/checker/struct.v, vlib/v/checker/tests/unknown_type_in_anon_fn.out, vlib/v/checker/tests/unknown_type_in_anon_fn.vv
This PR check error for unknown type in anon fn field of struct (fix #9328).
- Check error for unknown type in anon fn field of struct.
- Add test.
```v
module main
struct Struc{
mut:
f fn (s Another, i int) ?
}
fn main() {}
./tt1.v:5:10: error: unknown type `Another`
3 | struct Struc{
4 | mut:
5 |     f fn (s Another, i int) ?
|             ~~~~~~~
6 | }
7 |
```
=> checker: check error for unknown type in anon fn field of struct (fix #9328)

vlib/v/gen/c/cgen.v, vlib/v/tests/modules/alias_to_another_module/alias.v, vlib/v/tests/modules/another_module/module.v, vlib/v/tests/use_alias_from_another_module_in_struct_field_test.v
Previously, there was a cgen error for the following case:
```v
import another
struct Abc {
field another.AliasOfThirdModuleStruct
}	
```
The reason was that Abc depended only on another.AliasOfThirdModuleStruct,
but since that was not a struct, but instead an alias to another struct `third_module.Struct`,
the generated definition of Abc, could be put *before* the definition for
`third_module.Struct`, leading to a failing C compilation.
This PR adds the dependency to the parent struct too, so that after
the topological sort, the struct definitions are now generated in the
proper order - first the ones from the modules, and only after that,
the ones that depend on them.
fix #13775
=> cgen: fix struct type dependency sorting, when struct field types, are aliases to struct types from other modules

vlib/v/gen/c/cgen.v, vlib/v/gen/c/index.v, vlib/v/tests/map_get_anon_fn_value_test.v
This PR fix error for map get anon fn value  (fix #10911).
- Fix error for map get anon fn value.
- Add test.
```v
const numbers = {
'one': fn () int {
return 1
}
}
fn main() {
num1 := numbers['one'] or {
fn () int {
return 2
}
}
ret1 := num1()
println(ret1)
assert ret1 == 1
num2 := numbers['two'] or {
fn () int {
return 2
}
}
ret2 := num2()
println(ret2)
assert ret2 == 2
}
1
2
```
=> cgen: fix error for map get anon fn value  (fix #10911)

vlib/v/checker/checker.v, vlib/v/checker/tests/index_of_optional_err.out, vlib/v/checker/tests/index_of_optional_err.vv
This PR check error for index of optional (fix #13780).
- Check error for index of optional.
- Add test.
```v
fn abc() ?[]int {
return [1, 2, 3]
}
fn main() {
a := abc()[0] or { 5 }
dump(a)
}
./tt1.v:6:7: error: type `?[]int` is optional, it does not support indexing
4 |
6 |     a := abc()[0] or { 5 }
|          ~~~~~
7 |     dump(a)
8 | }
```
=> checker: check error for index of optional (fix #13780)

vlib/v/gen/c/cgen.v, vlib/v/gen/c/testdata/keyword_escaping.vv, vlib/v/tests/keyword_escaping_test.v
This PR fixes #13722, by making `true` and `false` reserved.
=> cgen: add true and false to C reserved words 

vlib/v/tests/go_anon_fn_variable_call_test.v
This PR perfect go_anon_fn_variable_call_test.v.
```v
fn sum1(a int, b int) int {
sum_func1 := fn (a int, b int) int {
return a + b
}
sum_func2 := sum_func1
g := go sum_func2(a, b)
result := g.wait()
return result
}
fn add(a int, b int) int {
return a + b
}
fn sum2(a int, b int) int {
sum_func1 := add
sum_func2 := sum_func1
g := go sum_func2(a, b)
result := g.wait()
return result
}
fn main() {
ret1 := sum1(22, 33)
println(ret1)
assert ret1 == 55
ret2 := sum2(2, 3)
println(ret2)
assert ret2 == 5
}
55
5
```
=> tests: perfect go_anon_fn_variable_call_test.v

vlib/v/gen/c/index.v, vlib/v/tests/array_get_anon_fn_value_test.v
This PR simplify in index_of_array() and add test.
```v
const numbers = [
fn () int {
return 1
},
fn () int {
return 2
},
]
fn main() {
num1 := numbers[0]
ret1 := num1()
println(ret1)
assert ret1 == 1
num2 := numbers[1]
ret2 := num2()
println(ret2)
assert ret2 == 2
}
1
2
```
=> cgen: simplify in index_of_array() and add test

vlib/builtin/array.v
The voidptr returned is immediately dereferenced in cgen so the memory is copied before the array can be appended to: `*(int*)array_pop(&a)`
=> builtin/array: don't `memdup` returned element of `pop`

vlib/strconv/format_mem.c.v, vlib/v/tests/string_interpolation_float_fmt_test.v
This PR fix error for string interpolation of float format (fix #13794).
- Fix error for string interpolation of float format.
- Add test.
```v
fn main() {
mut a := 76.295
eprintln('${a:8.2}')
assert '${a:8.2}' == '   76.30'
eprintln('${a:8.2f}')
assert '${a:8.2f}' == '   76.30'
a = 76.296
eprintln('${a:8.2}')
assert '${a:8.2}' == '   76.30'
eprintln('${a:8.2f}')
assert '${a:8.2f}' == '   76.30'
}
76.30
76.30
76.30
76.30
```
=> strconv: fix error for string interpolation of float format (fix #13794)

vlib/v/gen/c/cgen.v
This PR makes minor cleanup in go_expr().
- Format generated c codes.
before:
```v
VV_LOCAL_SYMBOL int main__sum(int a, int b) {
int (*sum_func) (int a, int b) = 	anon_fn_1315efd87adb6e70_int_int__int_137;
// go
thread_arg_anon_fn_1315efd87adb6e70_int_int__int_137 *arg__t1 = malloc(sizeof(thread_arg_anon_fn_1315efd87adb6e70_int_int__int_137));
arg__t1->arg1 = a;
arg__t1->arg2 = b;
arg__t1->ret_ptr = malloc(sizeof(int));
HANDLE thread_handle__t1 = CreateThread(0,0, (LPTHREAD_START_ROUTINE)anon_fn_1315efd87adb6e70_int_int__int_137_thread_wrapper, arg__t1, 0,0);
if (!thread_handle__t1) panic_lasterr(tos3("`go anon_fn_1315efd87adb6e70_int_int__int_137()`: "));
__v_thread_int thread__t1 = {
.ret_ptr = arg__t1->ret_ptr,
.handle = thread_handle__t1
};
// endgo
__v_thread_int g = thread__t1;
int …
```
=> cgen: minor cleanup in go_expr()

.github/workflows/sdl_ci.yml
[I've just added](https://github.com/vlang/sdl/pull/224) an example that uses shaders - so this PR fixes any potential errors the sdl CI step will give
=> ci: update sdl ci to compile shader example

vlib/v/checker/checker.v, vlib/v/checker/tests/globals/redefine_main.out, vlib/v/checker/tests/globals/redefine_main.vv
This PR check redefinition of global 'main' function (fix #11373).
- Check redefinition of global 'main' function.
- Add test.
```v
__global main = fn () int { return 22 }
fn main() {
}
PS D:\Test\v\tt1> v -enable-globals run .
./tt1.v:1:10: error: the `main` function is the program entry point, cannot redefine it
1 | __global main = fn () int { return 22 }
|          ~~~~
2 |
```
=> checker: check redefinition of global 'main' function (fix #11373)

vlib/strconv/format_mem.c.v
This PR makes minor cleanup in f64_to_str_lnd1().
- Use `match` instead of `multi if/else`.
=> strconv: minor cleanup in f64_to_str_lnd1()

vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/tests/init_global_test.v
This PR fix error for defining global anonymous functions (fix #11374).
- Fix error for defining global anonymous functions.
- Add test in init_global_test.v.
```v
__global (
gg1 = fn () {}
gg2 = fn (n int) int { return n }
gg3 = fn (n int) string { return '$n' }
)
fn main() {
gg1()
ret2 := gg2(22)
println(ret2)
assert ret2 == 22
ret3 := gg3(22)
println(ret3)
assert ret3 == '22'
}
PS D:\Test\v\tt1> v -enable-globals run .
22
22
```
=> cgen: fix error for defining global anonymous functions (fix #11374)

vlib/v/ast/types.v, vlib/v/checker/check_types.v, vlib/v/gen/c/auto_str_methods.v, vlib/v/gen/c/str.v, vlib/v/tests/inout/printing_alias_has_str_method.out, vlib/v/tests/inout/printing_alias_has_str_method.vv
This PR fix error for printing alias that has str method (fix #5683).
- Fix error for printing alias that has str method.
- Add test.
```v
type Byte = byte
fn (b Byte) str() string {
return 'hello'
}
fn main() {
b := Byte(`a`)
println(b)
println(b.str())
println('$b')
}
hello
hello
hello
```
=> ast, checker, cgen: fix error for printing alias that has str method (fix #5683)

examples/sokol/particles/modules/particle/system.v, vlib/builtin/array.v, vlib/builtin/array_shrinkage_test.v
Fixes regression in `GC_PRINT_STATS=1 ./v -gc boehm run examples/sokol/particles/`
by minimising the amount of generated garbage on element deletion.
=> builtin: support a.flags.set(.noslices | .noshrink), use it in the particles example

vlib/strings/builder.c.v
Removes `x := unsafe { (*&[]byte(b))[cut_pos..] }` usage.
Instead, there is now a private method:
`fn (b &Builder) spart(start_pos int, n int) string {`
`spart` also avoids the need for casting and slicing.
=> strings: cleanup unsafe casts in some of strings.Builder ops

vlib/v/parser/fn.v, vlib/v/parser/tests/fn_param_name_cap.out, vlib/v/parser/tests/fn_param_name_cap.vv
Before the error was confusing for `fn g<T>(T v)`:
error: cannot use `int literal` as `v` in argument 1 to `g`
I've made that mistake using C declaration order syntax. The error seemed to not be telling me the type of `v` which I thought was the parameter name. Note for a generic function there's no error 'unknown type `v`'.
=> v/parser: error if parameter name starts with a capital

vlib/builtin/array.v
Move explanation about boolean `it` expressions to `filter`, as `sort` doesn't take a boolean expression. Also move `any` example.
Add 2 filter examples.
Add map example from docs.md.
=> builtin/array: improve docs for methods that take an `it` expression

doc/docs.md
`dump` is mentioned in the interface docs and isn't really an 'advanced' feature. It belongs as a built-in function even though it has special semantics (just like `it` methods are still methods).
Add `println` subheading.
Make 'Printing custom types' a subheading of `println`.
~~Change `print` functions to take IStr, not string and note IStr is not public.~~ Note that `print` functions can take other printable types.
Mention `dump` in built-in functions list.
=> doc: tweak built-in functions section & move `dump` section here

vlib/os/process_windows.c.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/sql.v, vlib/v/tests/cast_bool_to_int_test.v
This PR fix crash for casting bool to int  (fix #13825).
- Fix crash for casting bool to int.
- Add test.
- Use `array_get(a, (int[]){(!i)?1:0}[0]))`.
```v
fn main() {
i := true
a := [1, 2, 3]
println(a[int(!i)])
assert a[int(!i)] == 1
println(a[int(i)])
assert a[int(i)] == 2
}
1
2
```
=> cgen: fix crash for casting bool to int  (fix #13825)

vlib/v/parser/parse_type.v, vlib/v/parser/parser.v, vlib/v/parser/struct.v, vlib/v/parser/tests/struct_field_mut_type_err.out, vlib/v/parser/tests/struct_field_mut_type_err.vv
This PR check error for struct field type using 'mut' (related #8187).
- Check error for struct field type using 'mut'.
- Add test.
```v
struct Foo {
mut:
foo mut string
}
fn main() {
f := Foo{}
println(f)
}
./tt1.v:3:6: error: cannot use `mut` on struct field type
1 | struct Foo {
2 | mut:
3 |     foo mut string
|         ~~~
4 | }
5 |
```
=> parser: check error for struct field type using 'mut' (related #8187)

cmd/tools/vdoc/theme/doc.css
Make keywords bold.
Make attributes use a monospace font (like code).
Tweak light theme foreground colors for better contrast:
* Make default-text, operator-text and punctuation-text a bit darker,  improving the contrast.
* Make builtin-text a bit darker and green (similar to dark theme).
* Make function-text a bit darker and more greeny-blue (similar to dark theme).
* Make attribute-text a bit less transparent for better contrast.
This helps the styles stand out from each other a bit more and be easier to read.
=> vdoc: tweak keyword, attribute and light theme CSS

vlib/v/gen/c/cgen.v
This PR makes a minor cleanup in expr_is_multi_return_call().
=> cgen: minor cleanup in expr_is_multi_return_call()

vlib/v/checker/fn.v, vlib/v/checker/tests/generics_fn_arguments_count_err.out, vlib/v/checker/tests/generics_fn_arguments_count_err.vv
This PR check generics fn arguments count (fix #13850).
- Check generics fn arguments count.
- Add test.
```v
fn get_name<A, B>(a A, b B) string {
return '$a, $b'
}
struct Foo {}
fn (f Foo) get_name<A, B>(a A, b B) string {
return '$a, $b'
}
fn main() {
ret1 := get_name<int>(11, 22)
println(ret1)
ret2 := get_name<int, int, string>(11, 22, 'hello')
println(ret2)
foo := Foo{}
ret3 := foo.get_name<int>(11, 22)
println(ret3)
ret4 := foo.get_name<int, int, string>(11, 22, 'hello')
println(ret4)
}
./tt1.v:12:18: error: too little generic parameters got 1, expected 2
10 | 
11 | fn main() {
12 |     ret1 := get_name<int>(11, 22)
|                     ~~~~~
13 |     println(ret1)
14 |
./tt1.v:15:18: error: too many generic parameters got 3, expected 2
13 | …
```
=> checker: check generics fn arguments count (fix #13850)

vlib/v/checker/fn.v, vlib/v/tests/array_of_anon_fn_call_test.v
This PR fix error for array of anon fn call (fix #13849).
- Fix error for array of anon fn call.
- Add test.
```v
fn main() {
xs := [fn (s string) (string, u32) {
return s, 0
}]
r, n := xs[0]('e')
println(n)
assert n == 0
println(r)
assert r == 'e'
}
0
e
```
=> checker: fix error for array of anon fn call (fix #13849)

vlib/v/parser/expr.v, vlib/v/tests/inout/printing_slice_of_multiline_raw_string.out, vlib/v/tests/inout/printing_slice_of_multiline_raw_string.vv
This PR fix printing slice of multiline raw string (fix #13854).
- Fix printing slice of multiline raw string.
- Add test.
```v
fn main() {
println(r'foo
bar
hi'[..])
}
foo
bar
hi
```
=> parser: fix printing slice of multiline raw string (fix #13854)

vlib/v/checker/checker.v, vlib/v/tests/mark_as_referenced_test.v
This PR fix error for marking as referenced (fix #13857).
- Fix error for marking as referenced.
- Add test.
```v
module main
fn main() {
if true {
a := Type{}
ret := f(a)
println(ret)
assert ret == 'Interface(Type{})'
}
a := Type{}
ret := f(a)
println(ret)
assert ret == 'Interface(Type{})'
}
struct Type {
}
interface Interface {
}
fn f(b Interface) string {
return '$b'
}
Interface(Type{})
Interface(Type{})
```
=> checker: fix error for marking as referenced (fix #13857)

vlib/net/openssl/c.v, vlib/v/builder/cc.v
[Procursus](https://github.com/ProcursusTeam/Procursus) installs libraries such as openssl with `@rpath/libssl.3.dylib` install names, this means that programs linking these libraries have to add the correct path to the `rpath` of the executable.
=> v.builder: fix linker flags for systems with Procursus

vlib/v/builder/cc.v, vlib/v/gen/c/cgen.v, vlib/v/pref/default.v
This has a couple of changes.
First of all, it allows `-cc` to override the default xcode compiler when targeting iOS. This allows for cross compilation to iOS from other systems with the correct environment. I tested this with `v -os ios -cc aarch64-apple-darwin-clang -cflags "-isysroot /usr/home/cameron/Documents/iOS/SDK/iPhoneOS14.3.sdk -isystem /usr/home/cameron/Documents/iOS/include" helloworld.v` and `v -os ios -cc aarch64-apple-darwin-clang -cflags "-isysroot /usr/home/cameron/Documents/iOS/SDK/iPhoneOS14.3.sdk -isystem /usr/home/cameron/Documents/iOS/include" -o v cmd/v`.
I also added `stdbool.h` to the list of includes. This fixes #11087, an issue I also ran into. Because `stdbool.h` is a part of the POSIX standard I feel confident that including it won't limit `v`'s system …
=> v.builder, v.gen, v.pref: fix iOS compilation from non-macOS

vlib/math/big/big_test.v, vlib/math/big/integer.v
- Adds the `bit_len` function (fixes #13868)
- Combines the Euclid and Binary GCD algorithms into the main gcd function.
- Adds documentaion.
=> math.big: add bit_len, optimize gcd, add documentation

vlib/v/checker/fn.v
This PR makes a minor cleanup in fn_call().
- Change variable name from `elem_typ` to `elem_sym`.
- Change variable name from `value_typ` to `value_sym`.
=> checker: minor cleanup in fn_call()

vlib/v/gen/c/fn.v
This PR makes a minor cleanup in ref_or_deref_arg().
=> cgen: minor cleanup in ref_or_deref_arg()

vlib/math/invtrig.v
Fixes [#13876](https://github.com/vlang/v/issues/13876)
Current acos fn return ```nan``` when calculating acos(0.0) instead of π/2 radians. Removes the check from the function
=> math: Allow acos(0) - fixes 13876

vlib/v/builder/cc.v, vlib/v/gen/c/cgen.v, vlib/v/pref/default.v
cgen: re-add stdbool.h for iOS only, this will fix windows tcc builds
builder: fix building for iOS and simulator from macOS
The compiler was being set as `xcrun --sdk iphoneos clang -isysroot path/iPhoneOS.sdk -arch arm64 -arch etc`, then when executed, the compiler string was wrapped in single quotes, causing that whole string to be searched for in the `PATH`, which would fail. Because the SDK is being specified explicitly, the usage of xcrun was useless.
=> builder,cgen: iOS fixes

vlib/v/gen/c/assign.v, vlib/v/tests/cross_assign_test.v
This PR fix error for cross assign of the reserved name variable (fix #13881).
- Fix error for cross assign of the reserved name variable.
- Add test.
```v
fn main() {
mut small := 1
mut big := 2
mut sum := 2
for big < 4_000_000 {
small, big = big, small + big
if big % 2 == 0 {
sum += big
}
}
println(small)
assert small == 3524578
println(big)
assert big == 5702887
println(sum)
assert sum == 4613732
}
3524578
5702887
4613732
```
=> cgen: fix error for cross assign of the reserved name variable (fix #13881)

cmd/tools/vdoc/html.v
https://modules.vlang.io/vweb.html#Context
The above link has:
```
pub:
 HTTP Request
req http.Request
 TODO Response
```
This hides the  character and shows `//` instead.
This still isn't ideal as the indent is missing, and multi-line comments are shown as line comments. I'm not sure how to detect them.
=> vdoc: show `//` comment prefix and hide any \x01 character for HTML

vlib/time/time.c.v, vlib/time/time.v, vlib/time/time_nix.c.v, vlib/time/time_test.v, vlib/time/time_windows.c.v
Fixes https://github.com/vlang/v/issues/13828
On a Linux machine, the local call adds 2 hours each call to the now() result.
I'm adding this test right now because I need to discovered where is the leak
=> time:  fixes  recursive local time call by check local time status 

.github/workflows/ci.yml, vlib/time/time_windows.c.v
This PR fixes error for time.local() on windows.
error on windows :
```v
FAIL  [223/927]   508.175 ms vlib/time/time_test.v
D:\\v\\vlib\\time\\time_test.v:263: ✗ fn test_recursive_local_call
> assert now_tm.str() == now_tm.local().str()
Left value: 2022-04-01 11:31:02
Right value: 2022-04-01 19:31:02
```
=> time: fix error for time.local() on windows

vlib/v/checker/return.v, vlib/v/tests/return_optional_test.v
This PR fix error for returning optional (fix #13896).
- Fix error for returning optional.
- Add test.
```v
fn func1() ?int {
return 0
}
fn func2() ?(int, int) {
return func1() ?, 1
}
fn main() {
a, b := func2() ?
println('$a, $b')
assert a == 0
assert b == 1
}
0, 1
```
=> checker: fix error for returning optional (fix #13896)

vlib/v/gen/c/infix_expr.v, vlib/v/tests/array_of_fixed_array_test.v
This PR fix array of fixed array  (fix #13895).
- Fix array of fixed array.
- Add test.
```v
fn main() {
mut arr := [][3]int{}
fixed_arr1 := [3]int{}
arr << fixed_arr1
fixed_arr2 := [1, 2, 3]!
arr << fixed_arr2
println(arr)
assert arr.len == 2
assert '${arr[0]}' == '[0, 0, 0]'
assert '${arr[1]}' == '[1, 2, 3]'
}
[[0, 0, 0], [1, 2, 3]]
```
=> cgen: fix array of fixed array  (fix #13895)

vlib/arrays/arrays.v, vlib/builtin/string.v, vlib/v/doc/comment.v, vlib/v/doc/node.v
Part of https://github.com/vlang/v/issues/13851.
Added an error when a multi-line example isn't formatted in markdown backticks, e.g.:
```v
// Example:
// st := 'Hello there,
// |this is a string,
// |    Everything before the first | is removed'.strip_margin()
```
```
C:\git\v\vlib\builtin\string.v: Expected code block after empty example line:
// ```
Found:
// st := 'Hello there,
```
=> v/doc: parse multi-line examples (so they get highlighted)

vlib/time/time.c.v, vlib/time/time_test.v
I have not tested this on Windows, so if the CI fails I will have to do that. It should work though, as it is entirely POSIX.
=> time: implement Time.strftime(fmt string) as a wrapper for strftime(3)

vlib/cli/command.v, vlib/cli/man.v, vlib/cli/man_test.v, vlib/v/tests/inout/cli_root_default_help.vv
This will generate a man page in the mdoc(7) format based off of the
cli.Command{} struct.
Example output:
```
%  v run test.v | mandoc -Owidth=46 -Ios=V | col -b
COMMAND(1)  General Commands Manual COMMAND(1)
NAME
command – description
SYNOPSIS
command [-str string] [-b] [-r string]
command subcommand
DESCRIPTION
description
The options are as follows:
-str    str flag
-b -bool
bool flag
-r -required
The subcommands are as follows:
sub     subcommand
sub2    another subcommand
SEE ALSO
command-sub(1), command-sub2(1)
V                April 2, 2022               V
```
=> cli: add automatic manpage generation

vlib/builtin/array.v, vlib/builtin/array_d_gcboehm_opt.v
This PR makes a minor optimization of push() and push_noscan().
- Use `vmemcpy` instead of `vmemmove`.
=> array: minor optimization of push() and push_noscan()

vlib/v/checker/return.v
This PR makes a minor cleanup in find_unreachable_statements_after_noreturn_calls().
=> checker: minor cleanup in find_unreachable_statements_after_noreturn_calls()

vlib/builtin/array.v, vlib/builtin/array_test.v
Skip elements at the start of the array.
Any spare capacity is preserved, unlike slicing.
This is the counterpart of [`trim`](https://modules.vlang.io/index.html#array.trim).
`drop` is used in Haskell, D, Scala, Kotlin.
`shift` is used in JS but `num` is always 1.
`shift` is used in bash with optional `num` but the array is implicit.
=> builtin/array: add `drop` method

cmd/tools/vdoc/html.v, cmd/tools/vdoc/utils.v, vlib/v/token/token.v
Updated for both HTML and color terminal highlighting (though term examples don't use that yet, only symbols).
Add token.Kind.is_postfix().
=> vdoc: highlight `..`, `...` as punctuation & postfix ops as operators 

cmd/tools/vdoc/utils.v, cmd/tools/vdoc/vdoc.v, vlib/builtin/string.v
Screenshot from my test module:
I'm not sure why the `// hi` comment is one char to the left.
Also use string.replace instead of split/map/join to indent.
=> vdoc: highlight terminal examples for `-comments -color`

vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/tests/const_use_nested_optionals_test.v
This PR fix error for const using nested optionals (fix #13914).
- Fix error for const using nested optionals.
- Add test.
```v
module main
import os
const iterations = (os.getenv_opt('ITERATIONS') or { '5' }).int()
fn main() {
println('Number of iterations: $iterations')
assert iterations == 5
}
Number of iterations: 5
```
=> cgen: fix error for const using nested optionals (fix #13914)

cmd/tools/vdoc/html.v, cmd/tools/vdoc/utils.v
Refinement of merged #13923.
For both HTML and color terminal - the latter needs #13937 for example highlighting:
Use whitespace as a heuristic.
=> vdoc: don't highlight less than expression as generic function

vlib/clipboard/clipboard_android.c.v, vlib/clipboard/clipboard_darwin.c.v, vlib/clipboard/clipboard_default.c.v, vlib/clipboard/clipboard_solaris.c.v, vlib/clipboard/clipboard_windows.c.v, vlib/clipboard/dummy/dummy_clipboard.v
Ticks a few boxes in #7047 when merged
=> clipboard: add doc strings to all implementations

vlib/gg/m4/vector.v, vlib/gg/text_rendering.c.v
This should tick off all of `gg` in #7047
(The rest of the functions reported by `missdoc` is false positives in block comments)
=> gg: document pub functions in text_rendering and m4/vector

vlib/json/json_decode_with_encode_arg_test.v, vlib/json/json_decode_with_optional_arg_test.v, vlib/v/gen/c/fn.v
This PR fix json decode with optional argument (fix #13882 fix #13943).
- Fix json decode with optional argument.
- Add test.
```v
import json
import os
struct DbConfig {}
fn main() {
if ret := print_info() {
println(ret)
} else {
println(err)
}
assert true
}
fn print_info() ?string {
dbconf := json.decode(DbConfig, os.read_file('dbconf.json') ?) ?
println(dbconf)
return '$dbconf'
}
failed to open file "dbconf.json"
```
```v
import json
struct TodoDto {
foo int
}
fn main() {
body := TodoDto{}
ret := json.decode(TodoDto, json.encode(body)) ?
println(ret)
assert ret.foo == 0
}
TodoDto{
foo: 0
}
```
=> cgen: fix json decode with optional argument (fix #13943)

vlib/v/gen/c/assign.v, vlib/v/gen/c/fn.v, vlib/v/tests/optional_multi_return_test.v
This PR fix error for optional multi return (fix #13956).
- Fix error for optional multi return.
- Add test.
```v
fn tuple() ?(int, int) {
return 1, 2
}
fn main() {
println(tuple() ?)
a, b := tuple() ?
assert a == 1
assert b == 2
}
(1, 2)
```
=> cgen: fix error for optional multi return (fix #13956)

cmd/tools/missdoc.v
This PR will fix detection of `[deprecated]` tags that has text associated via `[deprecated: '<text>']`
=> missdoc: improve deprecation detection

.github/workflows/ci_v_benchmark.yml
This is one of many steps that bring inside the CI a complete benchmarks about V lang where will be possible to check if any feature introduced or bug fixed will introduce a decrease of performance with a gap that is accepted we will discuss when the checker is ready.
=> ci: introduce v benchmarks inside the ci workflow

examples/process/process_stdin_trick.v
fix examples/process_stdin_trick.v by closing stdin stream, resding streams, then call p.close and p.wait
This file contains itself a test, so I dont add a test on it
ran `v -cc tcc test-all` .
=> examples: fix process_stdin_trick example

vlib/clipboard/x11/clipboard.c.v
This PR fixes #13891
What I find a bit strange is that V let the old code even compile.
The source of the bug is the assignment done in: `xse.property = new_atom(0)`.
The weird thing is that `property` of `C.XSelectionEvent` is of type `Atom` - and `new_atom` returns `&Atom`??
Anyway - this PR fixes it so the Atom assigned is now on the stack of the running thread (I suspect that the crash was because the address of the previous &Atom messed with memory across the UI and event thread started with `go`).
=> clipboard: fix segfault when pasting to some X11 apps

vlib/json/json_decode_with_optional_arg_test.v, vlib/v/gen/c/cgen.v
This PR fix optional with empty struct.
- Fix optional with empty struct.
- Add test.
```v
import json
import os
struct DbConfig {}
fn test_json_decode_with_optional_arg() {
if ret := print_info() {
println(ret)
} else {
println(err)
}
assert true
}
fn print_info() ?string {
dbconf := json.decode(DbConfig, os.read_file('dbconf.json') ?) ?
println(dbconf)
return '$dbconf'
}
failed to open file "dbconf.json"
```
=> cgen: fix optional with empty struct

cmd/tools/vpm.v
i think that `v list` should print the output without indenting or header, so its easier for 3rd party tools to reuse its output.
=> vpm: simplify `v list` output

vlib/v/gen/c/assign.v, vlib/v/gen/c/infix_expr.v, vlib/v/tests/fn_with_fixed_array_args_test.v
This PR fix error for fn with fixed array argument  (fix #13976).
- Fix error for fn with fixed array argument.
- Add test.
```v
struct Test {
mut:
value [4]int
}
fn (mut t Test) set(new_value [4]int) {
t.value = new_value
}
fn main() {
mut t := Test{}
println(t)
assert '$t.value' == '[0, 0, 0, 0]'
t.set([1, 2, 3, 4]!)
println(t)
assert '$t.value' == '[1, 2, 3, 4]'
}
Test{
value: [0, 0, 0, 0]
}
Test{
value: [1, 2, 3, 4]
}
```
```v
struct Test2 {
mut:
fixed_value   [2][4]int
dynamic_value [][4]int
}
fn (mut t Test2) set(index int, new_value [4]int) {
t.fixed_value[index] = new_value
t.dynamic_value << new_value
}
fn main() {
mut t := Test2{}
println(t)
assert '$t.fixed_value' == '[[0, 0, 0, 0], [0, 0, 0, 0]]'
assert '$t.dynamic_value' == '[]'
t.set(0, [1, 2, 3, …
```
=> cgen: fix error for fn with fixed array argument  (fix #13976)

vlib/v/gen/c/cgen.v
this should fix #13822 by not taking the address of a heap allocated pointer when calling auto generated free
=> fix autofree of heap variables

vlib/v/checker/containers.v, vlib/v/checker/tests/array_of_generic_struct_init_err.out, vlib/v/checker/tests/array_of_generic_struct_init_err.vv
This PR check error for array of generic struct init (fix #13935).
- Check error for array of generic struct init.
- Add test.
```v
struct Item<T>{
val T
}
fn main() {
mut arr := []Item{}
}
./tt1.v:7:6: warning: unused variable: `arr`
6 |     //a := Item{42} // <int> missing error
7 |     mut arr := []Item{} // builder error:
|         ~~~
8 | }
./tt1.v:7:15: error: generic struct must specify type parameter, e.g. Foo<int>
6 |     //a := Item{42} // <int> missing error
7 |     mut arr := []Item{} // builder error:
|                  ~~~~
8 | }
```
=> checker: check error for array of generic struct init (fix #13935)

vlib/v/pref/pref.v, vlib/v/pref/pref_test.v
Fixes https://github.com/vlang/v/issues/13983
=> pref: fix access in invalid position when an empty cmd is given to `v`

vlib/v/checker/tests/struct_field_name_err.out, vlib/v/checker/tests/struct_field_name_err.vv, vlib/v/parser/struct.v
This PR check error for struct field name (fix #13986).
- Check error for struct field name.
- Add test.
```v
struct Release {
Architecture []string
Components   []string
}
fn main() {
r := Release{}
println(r)
}
./tt1.v:2:2: error: field name `Architecture` cannot contain uppercase letters, use snake_case instead
1 | struct Release {
2 |     Architecture []string
|     ~~~~~~~~~~~~~~~~~~~~~
3 |     Components   []string
4 | }
./tt1.v:3:2: error: field name `Components` cannot contain uppercase letters, use snake_case instead
1 | struct Release {
2 |     Architecture []string
3 |     Components   []string
|     ~~~~~~~~~~~~~~~~~~~~~
4 | }
5 |
```
=> parser: check error for struct field name (fix #13986)

vlib/rand/musl/musl_rng.v, vlib/rand/pcg32/pcg32.v
Adds the missing `pub` keyword to the RNGs: MUSL and PCG32.
=> rand: add missing pub modifiers to musl and pcg32

vlib/v/checker/containers.v, vlib/v/checker/tests/map_of_generic_struct_init_err.out, vlib/v/checker/tests/map_of_generic_struct_init_err.vv, vlib/v/parser/parser.v
This PR check error for map of generic struct init.
- Check error for map of generic struct init.
- Add test.
```v
struct Item<T>{
val T
}
fn main() {
mut m := map[string]Item{}
}
./tt1.v:6:6: warning: unused variable: `m`
4 | 
6 |     mut m := map[string]Item{}
|         ^
7 | }
./tt1.v:6:11: error: generic struct `Item` must specify type parameter, e.g. Foo<int>
4 | 
6 |     mut m := map[string]Item{}
|              ~~~~~~~~~~~~~~~~~
7 | }
```
=> checker: check error for map of generic struct init

vlib/toml/scanner/scanner.v, vlib/toml/scanner/scanner_test.v
Split out from #13967.
The 3 functions return a byte from a string or `end_of_text`. byte is unsigned. Returning int will cause an error when comparing the result with a byte when we implement unsigned == signed errors. So return u32 instead.
Note this pull doesn't break any running code that checks against a literal `-1`, because `math.max_u32 == -1`. That code will just fail to compile when the unsigned == signed errors are implemented.
=> toml.scanner: make end_of_text, at, next and peek return u32

vlib/arrays/arrays_test.v, vlib/v/gen/c/array.v, vlib/v/gen/c/cheaders.v, vlib/v/gen/c/struct.v
Fixes: #13990 
C99 `sizeof` empty structure  returned `0`, which caused alloc error.
Here `#define EMPTY_STRUCT_DECLARATION char _dummy` definition set as default in all compiler, like tcc, visual c.
And I am sure it is not an elegant solution. That will cause memory overhead.
=> cgen: fix alloc empty struct array error

vlib/v/ast/ast.v, vlib/v/fmt/fmt.v, vlib/v/fmt/tests/consts_with_embeded_comments_expected.vv, vlib/v/fmt/tests/consts_with_embeded_comments_input.vv, vlib/v/parser/parser.v
This PR fix error for vfmt of consts with embeded comments (fix #6949).
- Fix error for vfmt of consts with embeded comments.
- Add test.
```v
import gx
const (
color = //gx.rgb(167,236,82)
gx.rgb(50, 90, 110)
)
fn main() {}
```
vfmt ->
```v
import gx
const (
color = gx.rgb(50, 90, 110) // gx.rgb(167,236,82)
)
fn main() {}
```
=> ast, parser, fmt: fix error for vfmt of consts with embeded comments (fix #6949)

vlib/v/gen/c/array.v, vlib/v/gen/c/infix_expr.v, vlib/v/tests/in_expression_test.v
Fix infix_expr_in_optimization compile error when treating struct arrays or alias arrays.
```
module main
struct Foo1 {}
fn main() {
assert Foo1{} in [Foo1{}]
}
```
error output:
```
^~~~~~~~~~~~~~~
/tmp/v_501/test7.13461198918855249079.tmp.c:11404:53: error: invalid operands to binary expression ('main__Foo1' (aka 'struct main__Foo1') and 'main__Foo1')
if (!((((main__Foo1){EMPTY_STRUCT_INITIALIZATION}) == ((main__Foo1){EMPTY_STRUCT_INITIALIZATION})))) {
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
...
```
=> cgen: Fix infix_expr_in_optimization compile error when treating some kind cannot directly use '=='

vlib/v/gen/c/fn.v
This pr add the __fastcall attribute, I'm not very sure about the same if it should have two "_" or only one in the attribute name.
it may not be useful for a lot of people but it can be useful for some cases with c++ to pass/get the "this" argument since there is no __thiscall in c.
Thanks for reading :)
=> cgen: Added __fastcall attribute

vlib/json/json_decode_with_sumtype_test.v, vlib/v/gen/c/json.v
This PR fix error for json decode with sumtype (fix #14017).
- Fix error for json decode with sumtype.
- Add test.
```v
import json
type Test = []string | string
struct Some {
t Test
}
fn main() {
v := json.decode(Some, '{"t": ["string", "string2"]}') ?
println(v)
assert '$v.t' == "Test(['string', 'string2'])"
}
Some{
t: Test(['string', 'string2'])
}
```
=> json: fix error for json decode with sumtype (fix #14017)

doc/docs.md, vlib/v/ast/ast.v, vlib/v/fmt/fmt.v, vlib/v/fmt/tests/fn_type_attributes_and_calling_convention_keep.vv, vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/parser/fn.v, vlib/v/parser/parse_type.v, vlib/v/parser/parser.v
Hi,
This is my attempts to add the callconv attribute for fns an type.
as discussed before "windows_stdcall" and "_fastcall" now produce a warning, only "stdcall", "fastcall" and "cdecl" are alowed other produce an error and checks for supported calling convention are made in the parser :)
I tried to implement documentation for it but im not very sure about it.
a little exemple:
```v
// produce an error
[callconv]
type MySuperCoolFnWithMissingCallingConv = fn (int) int
// make an error for invalid calling convention
[callconv: "alohacall"]
type MySuperCoolFnWithInvalidCallingConv = fn (int) int
// generate:  typedef int (__fastcall *main__MySuperCoolFnWithfastCallingConv)(int);
[callconv: "fastcall"]
type MySuperCoolFnWithfastCallingConv = fn (int) int
// produce an error
[callconv]
fn …
```
=> gen: add callconv attribute for fn and type

vlib/v/gen/c/auto_str_methods.v, vlib/v/tests/generics_struct_parent_has_str_to_string_test.v
This PR fix error for generics struct that parent has str to string (fix #14034).
- Fix error for generics struct that parent has str to string.
- Add test.
```v
const (
w = 64
h = 32
)
interface Display {
mut:
pixel(x int, y int, val bool)
clear()
refresh()
}
struct Vm {
mut:
display Display
stack   datatypes.Stack<u16>
}
struct Pattern {
pattern []byte
handler fn (mut m Vm)
}
fn new_pattern(pattern string, handler fn (mut m Vm)) Pattern {
return Pattern{pattern.runes().map(byte('0x$it'.int())), handler}
}
fn main() {
p := new_pattern('00E0', fn (mut m Vm) {
println(m)
})
println(p)
assert true
}
Pattern{
pattern: [`\0`, `\0`, 0x0e, `\0`]
handler: fn (mut Vm)
}
```
=> cgen: fix error for generics struct that parent has str to string (fix #14034)

vlib/v/gen/c/auto_str_methods.v
This PR format gen_str_for_union_sum_type() generated c codes.
before:
```v
static string indent_main__Test_str(main__Test x, int indent_count) {
switch(x._typ) {
case 35: return str_intp(2, _MOV((StrIntpData[]){
{_SLIT("Test("), 0xfe10, {.d_s = Array_string_str(*(Array_string*)x._Array_string)}},
{_SLIT(")"), 0, {.d_c = 0 }}
}));		case 20: return str_intp(2, _MOV((StrIntpData[]){
{_SLIT("Test('"), 0xfe10, {.d_s = string_str(*(string*)x._string)}},
{_SLIT("')"), 0, {.d_c = 0 }}
}));		default: return _SLIT("unknown sum type value");
}
}
```
now:
```v
static string indent_main__Test_str(main__Test x, int indent_count) {
switch(x._typ) {
case 35: return str_intp(2, _MOV((StrIntpData[]){
{_SLIT("Test("), 0xfe10, {.d_s = Array_string_str(*(Array_string*)x._Array_string)}},
{_SLIT(")"), 0, …
```
=> cgen: format gen_str_for_union_sum_type() generated c codes

vlib/json/json_decode_with_sumtype_test.v, vlib/v/gen/c/json.v
This PR fix json decode with sumtype of multi array type.
- Fix json decode with sumtype of multi array type.
- Add test.
```v
import json
type Test = []bool | []int | []string | string
struct Some {
t Test
}
fn main() {
v1 := json.decode(Some, '{"t": ["string", "string2"]}') ?
println(v1)
assert '$v1.t' == "Test(['string', 'string2'])"
v2 := json.decode(Some, '{"t": [11, 22]}') ?
println(v2)
assert '$v2.t' == 'Test([11, 22])'
v3 := json.decode(Some, '{"t": [true, false]}') ?
println(v3)
assert '$v3.t' == 'Test([true, false])'
}
Some{
t: Test(['string', 'string2'])
}
Some{
t: Test([11, 22])
}
Some{
t: Test([true, false])
}
```
=> json: fix json decode with sumtype of multi array type

vlib/v/gen/c/infix_expr.v, vlib/v/tests/generic_empty_interface_to_struct_test.v
Using the `is` operator with generics result in C error.
```
fn (container &Container) get_first_struct<T>() ?&T {
concrete := container.concrete
if concrete is T {
println(concrete.a)
return concrete
}
return error("can't cast")
}
```
Throws error `error: '_main__Any_T_index' undeclared`. Fixed by unwrapping `T` into  `_main__Any_Concrete_index`.
=> cgen: fix infix generics bug

cmd/tools/vcreate.v
This allows setting a different default license when using `v init`/`v new`.
=> vcreate: Allow custom default license

vlib/v/checker/if.v, vlib/v/gen/c/if.v, vlib/v/tests/if_expr_with_generic_sumtype_test.v
This PR fix error for if expr with generic sumtype (fix #14038).
- Fix error for if expr with generic sumtype.
- Add test.
```v
type Opt<T> = None<T> | Some<T>
struct None<T> {}
struct Some<T> {
mut:
value T
}
fn operation(r int) Opt<int> {
return if r > 0 { Some<int>{r} } else { None<int>{} }
}
fn main() {
op := operation(1)
println(op)
assert Opt<int>(Some<int>{1}) == op
}
Opt<int>(Some<int>{
value: 1
})
```
=> checker, cgen: fix error for if expr with generic sumtype (fix #14038)

vlib/v/checker/checker.v, vlib/v/checker/if.v, vlib/v/checker/match.v, vlib/v/gen/c/comptime.v, vlib/v/gen/c/if.v, vlib/v/gen/js/comptime.v
This PR makes minor cleanup of last expr stmt expression.
- Use `branch.stmts.last()` instead of `branch.stmts[branch.stmts.len-1]`.
=> checker, cgen: minor cleanup of last expr stmt expression

vlib/v/ast/types.v, vlib/v/checker/checker.v, vlib/v/checker/if.v, vlib/v/checker/match.v, vlib/v/gen/c/infix_expr.v, vlib/v/tests/aggregate_is_nodetype_test.v
This PR fix error for aggregate is nodetype (fix #12936).
- Fix error for aggregate is nodetype.
- Add test.
```v
type Abc = bool | int | string
fn main() {
x := Abc('test')
match x {
string, int {
if x is string {
println('it is a string')
assert true
} else {
assert false
}
}
else {
assert false
}
}
}
it is a string
```
=> ast, checker, cgen: fix error for aggregate is nodetype (fix #12936)

vlib/v/gen/c/infix.v
This PR makes minor cleanup of infix_expr.v.
- Change `infix_expr.v` to `infix.v` just like others.
- Change `sym` to `left_sym` in infix_expr_is_op().
=> cgen: minor cleanup of infix_expr.v

vlib/v/checker/fn.v, vlib/v/checker/tests/fn_arg_of_optional_err.out, vlib/v/checker/tests/fn_arg_of_optional_err.vv
This PR check error for fn decl with optional arguments (fix #6708).
- Check error for fn decl with optional arguments.
- Add test.
```v
fn optional_arg(x ?int) {
println('int type: $x')
}
fn main() {
optional_arg(1)
}
./tt1.v:1:19: error: optional type argument is not supported currently
1 | fn optional_arg(x ?int) {
|                   ^
2 |     println('int type: $x')
3 | }
```
=> checker: check error for fn decl with optional arguments (fix #6708)

vlib/bitfield/bitfield_test.v, vlib/term/ui/input_windows.c.v, vlib/v/checker/checker.v, vlib/v/checker/tests/compare_unsigned_signed.out, vlib/v/checker/tests/compare_unsigned_signed.vv, vlib/x/ttf/render_bmp.v
`gcc -W` doesn't error for e.g. u16 == i32, only for u32 == i16.
Any u16 value can fit in an i32. So I changed my mind, I think we should actually allow `u16 == i32`. (The `u32 == i16` check hasn't been implemented yet).
This keeps the check for unsigned == negative literal. See #13967.
=> checker: revert part of small_unsigned == signed (#13967)

examples/net_raw_http.v, examples/random_ips.v, vlib/v/ast/str.v
This PR fix optional in string interpolation and format error.
- Fix examples/random_ips.v.
- Fix examples/net_raw_http.v.
- Fix vfmt error for optional in string interpolation.
=> examples: fix optional in string interpolation and format error

vlib/v/checker/fn.v, vlib/v/checker/tests/array_contains_args_err.out, vlib/v/checker/tests/array_contains_args_err.vv
This PR check error for arguments of array.contains() (fix #14087, fix #14088).
- Check error for arguments of array.contains().
- Add test.
```v
fn main() {
arr := [0]
mut ret := [0].contains([0])
ret = [0].contains()
ret = [0, 1, 2].contains(0, 1, 2)
ret = [0].contains('a')
ret = [0].contains(arr)
println(ret)
}
./tt1.v:2:17: error: `.contains()` expected `int` argument, but got `[]int`
2 |     mut ret := [0].contains([0])
|                    ~~~~~~~~~~~~~
3 |     arr := [0]
4 |     ret = [0].contains()
./tt1.v:4:12: error: `.contains()` expected 1 argument, but got 0
2 |     mut ret := [0].contains([0])
3 |     arr := [0]
4 |     ret = [0].contains()
|               ~~~~~~~~~~
5 |     ret = [0, 1, 2].contains(0, 1, 2)
6 |     ret = …
```
=> checker: check error for arguments of array.contains() (fix #14087 #14088)

cmd/tools/vpm.v
Fixes broken `get_all_modules` in cmd/tools/vpm.v.
`a` tags on [vpm.vlang.io](http://vpm.vlang.io) uses the single quotation mark, while `get_all_modules` was searching for double quotation marks.
=> vpm: fix get_all_modules()

vlib/v/checker/assign.v, vlib/v/tests/assign_array_of_aliases_test.v
This PR fix error for assigning array of aliases (fix #14082).
- Fix error for assigning array of aliases.
- Add test.
```v
fn main() {
mut arr := [u8(1), 2, 3]
arr = [byte(4), 5, 6]
println(arr)
assert arr.len == 3
assert arr[0] == 4
assert arr[1] == 5
assert arr[2] == 6
}
[0x04, 0x05, 0x06]
```
=> checker: fix error for assigning array of aliases (fix #14082)

vlib/v/checker/checker.v, vlib/v/checker/fn.v, vlib/v/checker/if.v, vlib/v/gen/c/cgen.v
This PR use `stmts.last()` instead of `stmts[stmts.len - 1]`.
=> checker, cgen: using 'stmts.last()' instead of 'stmts[stmts.len - 1]'

vlib/datatypes/bstree.v, vlib/datatypes/bstree_test.v, vlib/v/checker/tests/check_err_msg_with_generics.out
Fixed child access handling for 'none' == root added tests.
Mentioned in #14059.
=> vlib: fixed bst child access if root is none

cmd/tools/vtest-all.v, vlib/builtin/builtin_d_gcboehm.c.v
when building something with `-gc boehm` flag with gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
```
/usr/bin/ld: /home/lemon/git/v/thirdparty/tcc/lib/libgc.a(gc.o): in function `GC_dlopen':
gc.c:(.text+0xd493): undefined reference to `dlopen'
collect2: error: ld returned 1 exit status
```
this happens due to the order of `-ldl` flags.
=> builtin: fix `-cc gcc -gc boehm` on linux and macos

.github/workflows/ci.yml, .github/workflows/ci_bootstrapping_works.yml, .github/workflows/ci_cross.yml, Dockerfile.cross, GNUmakefile, Makefile, cmd/tools/vtest-all.v, make.bat, vlib/sync/stdatomic/1.declarations.c.v
Cleanup the bootstrapping commands.
For most platforms, `gcc v.c -lpthread` should be enough.
=> bootstrap: remove -I ./thirdparty/stdatomic/nix from make files

doc/docs.md
New V users often do not know where to find documentation for V's standard library.  Putting a link at the top of V's documentation will be a great help for them
=> docs: add link for V's standard library

vlib/v/checker/checker.v, vlib/v/gen/c/infix.v, vlib/v/gen/js/infix.v, vlib/v/tests/fixed_array_in_op_test.v
- Fixed #14113, now static (fixed) arrays are able to be used as right expression of `in` infix expression.
=> Allow static (fixed) arrays in `in` operator

vlib/v/checker/fn.v, vlib/v/checker/tests/map_builtin_method_args_err.out, vlib/v/checker/tests/map_builtin_method_args_err.vv
This PR check map builtin method's arguments.
- Check map builtin method's arguments.
- Add test.
```v
fn main() {
mut m := {11: 22}
a1 := m.clone(11)
println(a1)
a2 := m.move(11)
println(a2)
a3 := m.keys('aaa')
println(a3)
}
./tt1.v:4:16: error: `.clone()` does not have any arguments
2 |     mut m := {11: 22}
3 |
4 |     a1 := m.clone(11)
|                   ~~
5 |     println(a1)
6 |
./tt1.v:7:15: error: `.move()` does not have any arguments
5 |     println(a1)
6 |
7 |     a2 := m.move(11)
|                  ~~
8 |     println(a2)
9 |
./tt1.v:10:15: error: `.keys()` does not have any arguments
8 |     println(a2)
9 |
10 |     a3 := m.keys('aaa')
|                  ~~~~~
11 |     println(a3)
12 | }
```
=> checker: check map builtin method's arguments

vlib/v/checker/fn.v, vlib/v/checker/tests/array_builtin_method_args_err.out, vlib/v/checker/tests/array_builtin_method_args_err.vv
This PR check array builtin method's arguments.
- Check array builtin method's arguments.
- Add test.
```v
fn main() {
arr := [1, 2, 3]
a1 := arr.clone(22)
println(a1)
a2 := arr.first('a2')
println(a2)
a3 := arr.last(1)
println(a3)
a4 := arr.pop(2)
println(a4)
}
./tt1.v:4:18: error: `.clone()` does not have any arguments
2 |     arr := [1, 2, 3]
3 | 
4 |     a1 := arr.clone(22)
|                     ~~
5 |     println(a1)
6 |
./tt1.v:7:18: error: `.first()` does not have any arguments
5 |     println(a1)
6 | 
7 |     a2 := arr.first('a2')
|                     ~~~~
8 |     println(a2)
9 |
./tt1.v:10:17: error: `.last()` does not have any arguments
8 |     println(a2)
9 | 
10 |     a3 := arr.last(1)
|                    ^
11 |     println(a3)
12 |
./tt1.v:13:16: …
```
=> checker: check array builtin method's arguments

vlib/v/checker/assign.v, vlib/v/checker/fn.v, vlib/v/tests/fn_with_array_of_aliases_argument_test.v
This PR fix error for fn with array of aliases argument (fix #14116).
- Fix error for fn with array of aliases argument.
- Add test.
```v
fn show_array_of_u8(data []u8) string {
println(data)
return '$data'
}
struct Foo {}
fn (f Foo) show_array_of_u8(data []u8) string {
println(data)
return '$data'
}
fn main() {
a := [byte(1), 2, 3]
s1 := show_array_of_u8(a)
println(s1)
assert s1 == '[0x01, 0x02, 0x03]'
foo := Foo{}
s2 := foo.show_array_of_u8(a)
println(s2)
assert s2 == '[0x01, 0x02, 0x03]'
}
[0x01, 0x02, 0x03]
[0x01, 0x02, 0x03]
[0x01, 0x02, 0x03]
[0x01, 0x02, 0x03]
```
=> checker: fix error for fn with array of aliases argument (fix #14116)

vlib/v/parser/fn.v, vlib/v/tests/generics_anon_fn_decl_with_type_only_arg_test.v
This PR fix generic anon fn decl with type only argument (fix #14118).
- Fix generic anon fn decl with type only argument.
- Add test.
```v
fn main() {
ret := func_b<int>(11, 22, add)
println(ret)
}
fn add(a int, b int) int {
return a + b
}
fn func_b<T>(x T, y T, f fn (T, T) T) T {
return f(x, y)
}
33
```
=> parser: fix generic anon fn decl with type only argument (fix #14118)

vlib/v/gen/c/if.v, vlib/v/tests/if_expr_with_nested_match_expr_test.v
This PR fix error for if expr with nested match expr (fix #14093).
- Fix error for if expr with nested match expr.
- Add test.
```v
fn main() {
a := if true {
match `a` {
`a` { 0 }
else { 1 }
}
} else {
3
}
println(a)
assert a == 0
}
0
```
=> cgen: fix error for if expr with nested match expr (fix #14093)

vlib/v/checker/if.v, vlib/v/checker/return.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/str_intp.v, vlib/v/tests/generic_empty_interface_to_multi_struct_test.v
This PR fix generic empty interface to multi struct (fix #14064).
- Fix generic empty interface to multi struct.
- Add test.
```v
struct ConcreteA {
a int
}
struct ConcreteB {
b int
}
struct Container {
concrete_a Any
concrete_b Any
}
fn cast_struct<T>(any_struct Any) &T {
if any_struct is T {
return any_struct
}
panic('cannot cast')
}
fn main() {
concrete_a := cast_struct<ConcreteA>(ConcreteA{12345})
concrete_b := cast_struct<ConcreteB>(ConcreteB{54321})
println(concrete_a.a)
println(concrete_b.b)
assert concrete_a.a == 12345
assert concrete_b.b == 54321
}
12345
54321
```
=> checker, cgen: fix generic empty interface to multi struct (fix #14064)

vlib/v/checker/fn.v, vlib/v/checker/tests/array_contains_args_err.out
This PR simplify checking array.contains() argument.
- Use `c.check_expected_call_arg()` to handle.
=> checker: simplify checking array.contains() argument

vlib/v/checker/for.v, vlib/v/gen/c/for.v, vlib/v/tests/inout/printing_for_v_in_a.out, vlib/v/tests/inout/printing_for_v_in_a.vv
This PR fix error for printing in 'for v in a' (fix #14139).
- Fix error for printing in 'for v in a'.
- Add test.
```v
fn abc(a Any) {
if a is string {
for x in a {
dump(x)
}
}
if a is []u8 {
for x in a {
dump(x)
}
}
if a is map[string]string {
for k, v in a {
println('> k: $k | v: $v')
}
}
println(@FN)
}
fn main() {
abc('abc')
abc([u8(23), 77])
abc({
'abc': 'xyz'
'def': 'jkl'
})
abc(123)
}
[.\\tt1.v:6] x: 97
[.\\tt1.v:6] x: 98
[.\\tt1.v:6] x: 99
abc
[.\\tt1.v:11] x: 23
[.\\tt1.v:11] x: 77
abc
> k: abc | v: xyz
> k: def | v: jkl
abc
abc
```
=> checker, cgen: fix error for printing in 'for v in a' (fix #14139)

vlib/v/builder/cc.v
This PR aims to improve building V on macOS 10.5 (Darwin 9) as well as on PowerPC machines.
First, the `-no-pie` flag introduced in https://github.com/vlang/v/pull/2607 isn't supported by `/usr/bin/ld` on macOS 10.5 and below (see [ticket](https://trac.macports.org/ticket/34064)). Removing it helps to fix a build error: ([full logs](https://trac.macports.org/attachment/ticket/64913/main_10.5.8_gcc6_errno_removed.log))
```
gcc-mp-6: error: unrecognized command line option '-no-pie'; did you mean '-no-pie'?
```
The `-x objective-c` appears to cause a build error on PowerPC: ([full logs](https://trac.macports.org/attachment/ticket/64913/main_10.5.8_v3.log))
```
/opt/local/lib/gcc6/gcc/ppc-apple-darwin9/6.5.0/include/stdatomic.h:40:1: sorry, unimplemented: '_Atomic' in Objective-C
typedef …
```
=> builder: improve macOS 10.5 and PPC support

vlib/v/gen/c/assign.v
Hi,
I noticed when you create a fn from a ptr which have a defined callconv it don't write it at cgen exemple:
```v
module main
[callconv: 'fastcall']
type P_Cool = fn (string)
[callconv: 'fastcall']
fn cool(hello string) {
dump(hello)
}
fn main() {
cool('hi')
fn_add := voidptr(&cool)
dump('cool add -> $fn_add')
o_fn := &P_Cool(fn_add)
o_fn('no')
}
```
at the line where `o_fn := &P_Cool(fn_add)` it generate this:
```c
void (*o_fn) (string ) = ((main__P_Cool*)(fn_add));
```
as you can see the fastcall is missing and this is what I tried to fix in this pr :) exemple:
expected:
```c
void (*o_fn) (string )__attribute__((fastcall)) = ((main__P_Cool*)(fn_add));
```
or for msvc:
```c
void (__fastcall*o_fn) (string ) = ((main__P_Cool*)(fn_add));
```
Thanks for taking attention of this pr :)
=> cgen: callconv support for fns from ptr

vlib/v/checker/fn.v, vlib/v/gen/c/fn.v, vlib/v/parser/parser.v, vlib/v/tests/fn_call_using_anon_fn_call_args.v
This PR fix error for fn call using anon fn call argument (fix #14149).
- Fix error for fn call using anon fn call argument.
- Add test.
```v
fn foofun1(op string) fn () string {
return fn () string {
return 'x passed'
}
}
fn foofun2(op string) fn () int {
return fn () int {
return 22
}
}
fn main() {
println(main.foofun1('1')())
assert main.foofun1('1')() == 'x passed'
println(main.foofun2('1')())
assert main.foofun2('1')() == 22
}
x passed
22
```
=> parser, checker, cgen: fix error for fn call using anon fn call argument (fix #14149)

vlib/v/gen/c/fn.v, vlib/v/tests/anon_fn_decl_inside_ternary_test.v
This PR fix error for anon fn decl inside ternary (fix #14148).
- Fix error for anon fn decl inside ternary.
- Add test.
```v
fn foofun(op rune) fn () string {
return match op {
`1` {
fn () string {
return '1 passed'
}
}
`2` {
fn () string {
return '2 passed'
}
}
else {
fn () string {
return 'Nor 1 or 2 passed'
}
}
}
}
fn main() {
a := foofun(`1`)
println(a())
assert a() == '1 passed'
}
1 passed
```
=> cgen: fix error for anon fn decl inside ternary (fix #14148)

vlib/v/checker/fn.v, vlib/v/checker/tests/array_index_args_err.out, vlib/v/checker/tests/array_index_args_err.vv
This PR check error for array.index() argument.
- Check error for array.index() argument.
- Add test.
```v
fn main() {
arr := [0]
mut ret := [0].index([0])
ret = [0].index()
ret = [0, 1, 2].index(0, 1, 2)
ret = [0].index('a')
ret = [0].index(arr)
println(ret)
}
./tt1.v:3:23: error: cannot use `[]int` as `int` in argument 1 to `.index()`
2 |     arr := [0]
3 |     mut ret := [0].index([0])
|                          ~~~
4 |     ret = [0].index()
5 |     ret = [0, 1, 2].index(0, 1, 2)
./tt1.v:4:12: error: `.index()` expected 1 argument, but got 0
2 |     arr := [0]
3 |     mut ret := [0].index([0])
4 |     ret = [0].index()
|               ~~~~~~~
5 |     ret = [0, 1, 2].index(0, 1, 2)
6 |     ret = [0].index('a')
./tt1.v:5:18: error: `.index()` …
```
=> checker: check error for array.index() argument

vlib/v/checker/match.v, vlib/v/tests/match_aliases_test.v
This PR fix error for match aliases (fix #14137).
- Fix error for match aliases.
- Add test.
```v
fn main() {
a := byte(97)
ret := match a {
`0`...`9`, `a`...`f` { 'OK' }
else { 'NOT OK' }
}
println(ret)
assert ret == 'OK'
}
OK
```
=> checker: fix error for match aliases (fix #14137)

vlib/v/checker/checker.v
Actually a C2V fix. @medvednikov should this be enabled for regular V code or only for translated mode?
=> checker: allow indexing through alias to int

vlib/v/ast/table.v, vlib/v/checker/check_types.v, vlib/v/checker/if.v, vlib/v/gen/c/cgen.v, vlib/v/tests/multiret_in_or_expr_test.v
This PR fix error for multi-return in or expr (fix #14167).
- Fix error for multi-return in or expr.
- Add test.
```v
fn multi_return1() ?(int, int) {
return 1, 2
}
fn multi_return2() ?(i64, i64) {
return 11, 22
}
fn multi_return3() ?(int, i64) {
return 11, 22
}
fn main() {
a1, b1 := multi_return1() or { 0, -1 }
println('$a1, $b1')
assert a1 == 1
assert b1 == 2
a2, b2 := multi_return2() or { 0, -1 }
println('$a2, $b2')
assert a2 == 11
assert b2 == 22
a3, b3 := multi_return3() or { 0, -1 }
println('$a3, $b3')
assert a3 == 11
assert b3 == 22
}
1, 2
11, 22
11, 22
```
=> ast, checker, cgen: fix error for multi-return in or expr (fix #14167)

vlib/sokol/c/declaration.c.v, vlib/v/ast/cflags.v
Hello --
This PR does two things:
1. Allows `#flag openbsd` to be used
2. Sets up Sokol on OpenBSD
Combined, this PR allows `ved` to build and run on OpenBSD.
Thanks!
=> vlib: Add OpenBSD to allowed_os_overrides and set up sokol properly.

vlib/v/gen/c/auto_str_methods.v, vlib/v/gen/c/cgen.v, vlib/v/tests/cast_to_empty_interface_test.v
This PR fix error for cast to empty interface (fix #14162).
- Fix error for cast to empty interface.
- Add test.
```v
fn thing(any Any) string {
return match any {
int { 'int${*any:17}' }
f64 { 'f64${*any:20}' }
else { 'literal type tag?${any:10}' }
}
}
fn main() {
mut ret_strings := []string{}
mut arr := [Any(int(11)), int(22), Any(8888), 9999, Any(f64(1.11)), f64(2.22), Any(8.88), 9.99]
for i in arr {
println(thing(i))
ret_strings << thing(i)
}
assert ret_strings.len == 8
assert ret_strings[0] == 'int               11'
assert ret_strings[1] == 'int               22'
assert ret_strings[2] == 'int             8888'
assert ret_strings[3] == 'int             9999'
assert ret_strings[4] == 'f64               1.110'
assert ret_strings[5] == 'f64               2.220'
assert …
```
=> cgen: fix error for cast to empty interface (fix #14162)

vlib/math/math_test.v, vlib/math/mathutil.v
This PR fix error for math.abs(0.0)/math.abs(0) (related #14165).
- Fix error for math.abs(0.0)/math.abs(0).
- Add test.
```v
import math
fn main() {
ret1 := math.abs(0)
println(ret1)
assert '$ret1' == '0'
ret2 := math.abs(0.0)
println(ret2)
assert '$ret2' == '0'
}
0
0
```
```v
module main
import math
import rand
const nmax = 20
fn main() {
println(' N    average    analytical    (error)')
println('===  =========  ============  =========')
for n in 1 .. nmax + 1 {
a := avg(n)
b := ana(n)
println('${n:3} ${a:9.4f} ${b:12.4f} ${math.abs(a - b) / b * 100.0:8.2f}%')
}
}
fn avg(n int) f64 {
tests := int(1e6)
mut sum := 0
for _ in 0 .. tests {
mut v := []bool{len: nmax, init: false}
mut x := 0
for !v[x] {
v[x] = true
sum++
x = rand.intn(n) or { 0 }
}
}
return f64(sum) …
```
=> math: fix error for math.abs(0.0)/math.abs(0) (related #14165)

vlib/v/checker/for.v, vlib/v/checker/tests/for_c_stmt_with_optional_call.out, vlib/v/checker/tests/for_c_stmt_with_optional_call.vv
This PR check error in for_c_stmt with optional call (fix #14165).
- Check error in for_c_stmt with optional call.
- Add test.
- It is recommended that the RAND function not use optional.
```v
import rand
import math { abs }
const nmax = 20
fn ana(n int) f64 {
return 1.0 // haven't started
}
fn avg(n int) f64 {
tests := 1e4
mut sum := 0
for t := 0; t < tests; t++ {
mut v := []bool{len: nmax, init: false}
for x := 0; !v[x]; x = rand.intn(n) or { 0 } {
v[x] = true
sum++
}
}
return f64(sum) / tests
}
fn main() {
println(' N   average   analytical   (error)')
println('=== ========= ============ =========')
for n in 1 .. nmax + 1 {
a := avg(n)
b := ana(n)
println('${n:3} ${a:9.4f} ${b:12.4f} (${(abs(a - b) / b * 100):6.2f}%)')
}
}
./tt1.v:15:31: error: optionals are …
```
=> checker: check error in for_c_stmt with optional call

vlib/v/checker/checker.v, vlib/v/tests/array_of_sumtype_append_literal_type_test.v
This PR fix error for array of sumtype appending literal value (fix #14196).
- Fix error for array of sumtype appending literal value.
- Add test.
```v
type Typ_var = f64 | int
fn main() {
mut arr := []Typ_var{}
// literal int/float type error
arr << 123
arr << 1.23
// cast/wrap in type
arr << int(123)
arr << f64(1.23)
arr << Typ_var(456)
arr << Typ_var(4.56)
println(arr)
assert arr[0] == Typ_var(123)
assert arr[1] == Typ_var(1.23)
}
[Typ_var(123), Typ_var(1.23), Typ_var(123), Typ_var(1.23), Typ_var(456), Typ_var(4.56)]
```
=> checker: fix error for array of sumtype appending literal value (fix #14196)

cmd/v/help/build-c.txt, vlib/v/gen/c/fn.v, vlib/v/pref/pref.v, vlib/v/tests/default_thread_stack_size_test.v
Set the default thread stack size to 8MB (on macOS, the default was 512KB, which is too small for too nested call expressions).
=> pref: add support for `-thread-stack-size 4194304` (default set to 8MB)

vlib/v/ast/ast.v, vlib/v/tests/complex_map_op_test.v
This PR fix error for complex map operating (fix #14174).
- Fix error for complex map operating.
- Add test.
```v
fn main() {
mut test_map := map[string]Point_map{}
test_map['test1'].points['point3'] << Point{10, 20}
test_map['test2'].points['point4'] << Point{50, 60}
println(test_map)
assert test_map.len == 2
assert Point{10, 20} in test_map['test1'].points['point3']
assert Point{50, 60} in test_map['test2'].points['point4']
assert Point{10, 20} !in test_map['test2'].points['point4']
assert Point{1, 2} !in test_map['test1'].points['point3']
}
struct Point {
mut:
x int
y int
}
struct Point_map {
mut:
points map[string][]Point
}
{'test1': Point_map{
points: {'point3': [Point{
x: 10
y: 20
}]}
}, 'test2': Point_map{
points: {'point4': [Point{
x: 50
y: 60
}]}
}}
```
=> ast: fix error for complex map operating (fix #14174)

vlib/v/gen/c/fn.v, vlib/v/tests/go_anon_fn_call_with_ref_arg_test.v
This PR fix go anon fn call with ref argument (fix #14192).
- Fix go anon fn call with ref argument.
- Add test.
```v
struct Foo {
bar string
}
fn main() {
foo := &Foo{
bar: 'hello'
}
g := go fn (foo Foo) string {
return foo.bar
}(foo)
ret := g.wait()
println(ret)
assert ret == 'hello'
}
hello
```
```v
import net.html
import vweb
struct App {
vweb.Context
}
struct HtmlData {
mut:
inner_html string
data       []&HtmlData
}
fn convert_to_html_data(tag html.Tag) &HtmlData {
println('convert_to_html_data')
if tag.children.len == 0 {
return &HtmlData{
inner_html: tag.content
data: []
}
}
mut node := &HtmlData{
inner_html: tag.content
data: []&HtmlData{}
}
for child in tag.children {
child_data := convert_to_html_data(child)
node.data << child_data
} …
```
=> cgen: fix go anon fn call with ref argument (fix #14192)

README.md, vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/tests/defer/defer_test.v
This PR fix use of C reserved words inside `defer` statement, and also adds a test (fix #14101).
```v
fn close(i int) {
eprintln("Close $i")
}
fn main() {
if 1 == 1 {
single := 1
defer { close(single) }
}
if 2 == 2 {
double := 9
defer { close(double) }
}
eprintln("Done")
}
```
```
$ ./v2 run x.v
Done
Close 9
Close 1
```
=> cgen: fix use of C reserved words inside `defer` statement (fix #14101)

vlib/builtin/string.v, vlib/builtin/string_test.v, vlib/builtin/utf8.v, vlib/v/gen/c/cgen.v
This PR adds a method to `string` called `len_utf8` that returns the number of runes the string has.
=> builtin: add `string.len_utf8()` method

vlib/builtin/builtin_windows.c.v
Multiple people have experienced issues with `os.cp()` throwing seemingly random errors on Windows but neither crashing the program nor working unexpectedly.
On Discord, we have decided to ignore all `0xE06D7363` errors, as they should not be handled by V and seem to not matter anyway.
This change resolved the issue for me.
=> builtin: ignore C++ exception errors

vlib/v/checker/tests/struct_field_name_err.out, vlib/v/checker/tests/struct_field_name_err.vv, vlib/v/parser/struct.v
This PR check struct field name using uppercase letters (fix #14219).
- Check struct field name using uppercase letters.
- Add test.
```v
struct Release {
Foo          string
Bar          &int
Architecture []string
}
fn main() {
}
./tt1.v:2:2: error: field name `Foo` cannot contain uppercase letters, use snake_case instead
1 | struct Release {
2 |     Foo          string
|     ~~~~~~~~~~~~~~~~~~~
3 |     Bar          &int
4 |     Architecture []string
./tt1.v:3:2: error: field name `Bar` cannot contain uppercase letters, use snake_case instead
1 | struct Release {
2 |     Foo          string
3 |     Bar          &int
|     ~~~~~~~~~~~~~~~~~
4 |     Architecture []string
5 | }
./tt1.v:4:2: error: field name `Architecture` cannot contain uppercase letters, use …
```
=> checker: check struct field name using uppercase letters (fix #14219)

vlib/v/checker/checker.v, vlib/v/checker/for.v, vlib/v/checker/tests/for_in_with_reserved_type_names.out, vlib/v/checker/tests/for_in_with_reserved_type_names.vv, vlib/v/doc/utils.v, vlib/v/gen/js/js.v, vlib/v/tests/struct_init_with_fixed_array_field_test.v, vlib/x/json2/scanner_test.v
This PR checks for an error for a key/value that uses a reserved type name, and also adds a test (fix #14072).
```v
fn main() {
for rune in 'runes' {
println(rune)
}
for char, c in 'runes' {
println(c)
println(char)
}
}
```
```bash
$ ./v2 run x.v
x.v:2:6: error: invalid use of reserved type `rune` as value name
2 |     for rune in 'runes' {
|         ~~~~
3 |         println(rune)
4 |     }
x.v:6:6: error: invalid use of reserved type `char` as key name
4 |     }
5 | 
6 |     for char, c in 'runes' {
|         ~~~~
7 |         println(c)
8 |         println(char)
```
=> checker: check error for reserved type names used as key/value in `for in` stmt (fix #14072)

vlib/v/checker/tests/interface_field_name_err.out, vlib/v/checker/tests/interface_field_name_err.vv, vlib/v/parser/struct.v
This PR check interface field name using uppercase letter (fix #14226).
- Check interface field name using uppercase letter.
- Add test.
```v
interface Animal {
Age int
Foo &int
Bar []string
}
fn main() {
}
./tt1.v:2:2: error: field name `Age` cannot contain uppercase letters, use snake_case instead
1 | interface Animal {
2 |     Age int
|     ~~~
3 |     Foo &int
4 |     Bar []string
./tt1.v:3:2: error: field name `Foo` cannot contain uppercase letters, use snake_case instead
1 | interface Animal {
2 |     Age int
3 |     Foo &int
|     ~~~
4 |     Bar []string
5 | }
./tt1.v:4:2: error: field name `Bar` cannot contain uppercase letters, use snake_case instead
2 |     Age int
3 |     Foo &int
4 |     Bar []string
|     ~~~
5 | }
6 |
```
=> parser: check interface field name using uppercase letter (fix #14226)

vlib/v/ast/ast.v, vlib/v/ast/attr.v, vlib/v/ast/table.v, vlib/v/ast/type_size_test.v, vlib/v/ast/types.v, vlib/v/checker/checker.v, vlib/v/checker/comptime.v, vlib/v/checker/struct.v, vlib/v/doc/doc.v, vlib/v/errors/errors.v, vlib/v/fmt/comments.v, vlib/v/fmt/fmt.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/gen/native/gen.v, vlib/v/live/common.v, vlib/v/parser/parser.v, vlib/v/parser/struct.v, vlib/v/pref/pref.v, vlib/v/scanner/scanner.v, vlib/v/token/token.v, vlib/v/vet/vet.v, x.v
If specified, this new attribute will cause V to optimize the layout of a struct's fields, in order to try to reduce the amount of memory wasted due to padding for the fields' alignment. It will also use C bitfields to make boolean fields take up 1 bit of memory, not 8; and makes enums only take up the number of bits strictly needed to store its different variants.
I added the attribute to some of the V compiler's structs as well, and this decreased the maximum amount of RAM taken up by `./v -o v2.c cmd/v` by almost 8 MB.
=> checker, gen: add support for a [minify] struct attribute 

vlib/v/gen/c/array.v, vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/tests/array_with_it_test.v
This PR fix declare assigning fixed array_init with it (fix #14248).
- Fix declare assigning fixed array_init with it.
- Add test in tests/array_with_it_test.v.
```v
fn main() {
a1 := [4]int{init: it}
println(a1)
a2 := []int{len: 4, init: it * 2}
println(a2)
}
[0, 1, 2, 3]
[0, 2, 4, 6]
```
=> cgen: fix declare assigning fixed array_init with it (fix #14248)

vlib/v/builder/cc.v
Allow `-compress` flag on Windows if upx is installed.
If upx command fails, same behavior as on linux/mac
=> compiler: allow upx on windows

vlib/builtin/array_test.v, vlib/v/parser/containers.v, vlib/v/parser/parser.v
This PR fix inline array's element access (fix #14249).
- Fix inline array's element access.
- Add test.
```v
struct Ok {}
fn main() {
println([Ok{}][0])
a1 := [Ok{}][0]
assert a1 == Ok{}
println([1][0])
a2 := [1][0]
assert a2 == 1
}
Ok{}
1
```
=> parser: fix inline array's element access (fix #14249)

vlib/v/checker/check_types.v, vlib/v/tests/generic_fn_infer_fn_type_argument_test.v
This PR fix generic fn infering fn type argument (fix #14243).
- Fix generic fn infering fn type argument.
- Add test.
```v
fn main() {
to_r := fn (x int) rune {
return [`😺`, `😸`, `😹`, `😻`, `😾`][x - 1]
}
to_f64 := fn (x int) f64 {
return f64(x) + 0.123
}
to_s := fn (x int) string {
return ['One', 'Two', 'Three', 'Four', 'Five'][x - 1]
}
items := [1, 2, 3, 4, 5]
ret_r := fmap(to_r, items)
println('${ret_r.map(rune(it))}')
assert '${ret_r.map(rune(it))}' == "[`😺`, `😸`, `😹`, `😻`, `😾`]"
// returns random same number for every item in array
ret_f64 := fmap(to_f64, items)
println(ret_f64)
assert ret_f64 == [1.123, 2.123, 3.123, 4.123, 5.123]
ret_s := fmap(to_s, items)
println(ret_s)
assert ret_s == ['One', 'Two', 'Three', 'Four', 'Five']
}
// [noah04 #14214] code
fn fmap<I, O>(func fn (I) O, …
```
=> checker: fix generic fn infering fn type argument (fix #14243)

vlib/v/parser/struct.v
This PR makes a minor cleanup in interface_decl().
- Using `embeds` instead of `ifaces` , it's a little bit clearer.
=> parser: minor cleanup in interface_decl()

vlib/v/checker/containers.v, vlib/v/tests/generics_array_init_test.v
This PR fix error for generics array init (fix #14236).
- Fix error for generics array init.
- Add test.
```v
fn get_arr_v1<N, T>(num N, val T) []T {
return []T{len: num, init: val}
}
fn get_arr_v2<N, T>(num N, val T) []T {
return []T{len: int(num), init: val}
}
fn get_arr_v3<N, T>(num N, val T) []T {
tmp := num
return []T{len: tmp, init: val}
}
fn get_arr_v4<N, T>(num N, val T) []T {
tmp := num + 0
return []T{len: tmp, init: val}
}
fn get_arr_v5<N, T>(num N, val T) []T {
tmp := 0 + num
return []T{len: tmp, init: val}
}
fn main() {
println(get_arr_v1(2, 'hallo v1'))
a1 := get_arr_v1(2, 'hallo v1')
assert a1 == ['hallo v1', 'hallo v1']
println(get_arr_v2(2, 'hallo v2'))
a2 := get_arr_v2(2, 'hallo v2')
assert a2 == ['hallo v2', 'hallo v2']
println(get_arr_v3(2, 'hallo v3'))
a3 := …
```
=> checker: fix error for generics array init (fix #14236)

vlib/v/checker/comptime.v, vlib/v/checker/if.v, vlib/v/gen/c/testdata/comp_if_unknown.c.must_have, vlib/v/gen/c/testdata/comp_if_unknown.vv
It now returns an enum containing `.eval, .skip, .unknown`, which should help make the code clearer, and also adds support for the cases where V can't evaluate whether the condition is true or not, such as `$if glibc`.
=> checker: refactor comptime_if_branch

vlib/v/gen/c/array.v, vlib/v/gen/c/infix.v, vlib/v/tests/fixed_array_in_op_test.v
This PR fix error for fixed array in operate (fix #14264).
- Fix error for fixed array in operate.
- Add test.
```v
fn main() {
fixed_arr := [1, 2, 3]!
b1 := 2 in fixed_arr
println(b1)
assert b1
b2 := 5 !in fixed_arr
println(b2)
assert b2
}
true
true
```
=> cgen: fix error for fixed array in operate (fix #14264)

vlib/v/checker/checker.v, vlib/v/checker/tests/comptime_selector_expr_type_err.out, vlib/v/checker/tests/comptime_selector_expr_type_err.vv, vlib/v/gen/c/comptime.v
This PR check comptime selector that has no field name (fix #14272).
- Check comptime selector that has no field name.
- Add test.
```v
module main
pub struct Row {
pub mut:
value string
}
fn main() {
a := []Row{}
for i in a {
$for field in Row.fields {
println('field $i: ' + a.$(field.name).str() )
}
}
}
./tt1.v:12:27: cgen error: `a` has no field named `value`
10 |     for i in a {
11 |         $for field in Row.fields {
12 |             println('field $i: ' + a.$(field.name).str() )
|                                    ^
13 |         }
14 |     }
```
=> checker, cgen: check comptime selector that has no field name (fix #14272)

thirdparty/libbacktrace/amalgamation.txt, thirdparty/libbacktrace/backtrace.c, thirdparty/libbacktrace/backtrace.h, thirdparty/libbacktrace/base.c, thirdparty/libbacktrace/darwin.c, thirdparty/libbacktrace/linux.c, thirdparty/libbacktrace/windows.c, vlib/builtin/builtin.c.v, vlib/builtin/builtin_d_use_libbacktrace.c.v, vlib/builtin/builtin_notd_use_libbacktrace.c.v, vlib/builtin/builtin_test.v, vlib/v/gen/c/cmain.v
This PR integrates [libbackrace](https://github.com/ianlancetaylor/libbacktrace) into `builtin` as an option for generating stack traces alongside TCC's backtrace function and other compiler-specific backtrace functions. This should enable richer stack traces independent of any tool such as `addr2line` and should be able to generate consistent output across all platforms (Windows, Mac, and Linux). Overall, making the debugging process easier.
To use it, simply pass `-d use_libbacktrace` into the compiler flags. (This is not enabled by default as we would have yet to see it's effectiveness)
UPDATE: TCC is not supported at this moment as it lacks the library for stack unwinding (although it has stack unwinding)
=> builtin: add libbacktrace as option for generating stack traces

vlib/v/checker/fn.v, vlib/v/parser/fn.v, vlib/v/tests/generics_method_on_nested_struct_test.v
This PR fix error for generic method on nested struct (fix #14089).
- Fix error for generic method on nested struct.
- Add test.
```v
struct Outer<T> {
mut:
inner Inner<T>
}
struct Inner<T> {
val T
}
fn (mut i Inner<T>) next<S>(input S) f64 {
$if S is f32 {
return 32
} $else {
panic('"$S.name" is not supported')
return 0
}
}
fn main() {
mut outer := Outer<f64>{
inner: Inner<f64>{
val: 1.1
}
}
r1 := outer.inner.next<f32>(99.0)
println(r1)
assert r1 == 32.0
r2 := outer.inner.next<f64, f32>(99.0)
println(r2)
assert r2 == 32.0
r3 := outer.inner.next(f32(99.0))
println(r3)
assert r3 == 32.0
}
32.
32.
32.
```
=> parser, checker: fix error for generic method on nested struct (fix #14089)

vlib/v/checker/checker.v, vlib/v/checker/tests/optional_in_dump_err.out, vlib/v/checker/tests/optional_in_dump_err.vv
This PR check error for optional argument in dump() (fix #14312).
- Check error for optional argument in dump().
- Add test.
```v
struct AStruct {
field1 int
}
fn create() ?AStruct {
return AStruct{123}
}
fn main() {
dump(create())
}
./tt1.v:10:7: error: create() returns an option, so it should have either an `or {}` block, or `?` at the end
8 |
10 |     dump(create())
11 | }
```
=> checker: check error for optional argument in dump() (fix #14312)

vlib/v/builder/cc.v
Based on the default values of msvc compiler setup, tcc, gcc and clang now also use the increased stack size as well as the implicit function declaration warning.
=> pref: Harmonisation of the default settings of the different Windows compilers

vlib/builtin/map.v, vlib/builtin/map_test.v, vlib/v/checker/fn.v, vlib/v/gen/c/fn.v
In addition to `map.keys()`, add `map.values()`.
JS has `Map.prototype.values()`, Python has `dict.values()`, C# has `Dictionary<TKey,TValue>.Values`... It was time for V to have its own.
⚠️ - I only managed to make it work for maps with the same type for the key and the value. I feel like I'm close to making it work completely but as it's my first time messing with more low-level things I'll need some help 🙂
TODO:
=> builtin: add `map.values()`

vlib/v/checker/fn.v, vlib/v/tests/generics_method_on_nested_struct2_test.v
This PR fix error for generic method on nested struct (fix #14098).
- Fix error for generic method on nested struct.
- Add test.
```v
struct Outer<T> {
mut:
inner Inner<T>
}
struct Inner<T> {
val T
}
fn (mut i Inner<T>) next<S>(input S) f64 {
$if S is f32 {
return 32
} $else {
panic('"$S.name" is not supported')
return 0
}
}
fn (mut o Outer<T>) next<S>(input S) f64 {
$if S is f32 {
return o.inner.next(input)
} $else {
panic('"$S.name" is not supported')
return 0
}
}
fn main() {
mut outer := Outer<f64>{
inner: Inner<f64>{
val: 1.1
}
}
res := outer.next(f32(99.0))
println(res)
assert res == 32.0
}
32.
```
=> checker: fix error for generic method on nested struct (fix #14098)

vlib/v/gen/c/cgen.v, vlib/v/tests/if_cond_with_optional_test.v
This PR fix error for if cond with optional expr  (fix #14324).
- Fix error for if cond with optional expr.
- Add test.
```v
module main
import rand
interface Sample {
mut:
get_next() int
}
struct SampleA {
mut:
state int
}
fn (mut sample SampleA) get_next() int {
sample.state++
return sample.state
}
struct SampleB {
mut:
state int = 1
}
fn (mut sample SampleB) get_next() int {
sample.state += 2
return sample.state
}
fn create_sampler() Sample {
return if rand.intn(1) or { 0 } == 0 { Sample(SampleA{}) } else { Sample(SampleB{}) }
}
fn main() {
mut sample := create_sampler()
mut ret := sample.get_next()
println(ret)
ret = sample.get_next()
println(ret)
assert ret == 2
}
1
2
```
=> cgen: fix error for if cond with optional expr  (fix #14324)

vlib/pg/orm.v
PG can return bools as `t` or `f`. Currently this is not supported and throws an error for an unknown type of 18
=> Added type 18 for pg boolean data type

vlib/net/smtp/smtp.v
- 'ZZ' time zone: GMX, a very popular german email server insists on the 'ZZ' time zone info. Otherwise the mail body is rejected (see also RFC2822, 3.3)
- Content type for plain text should be UFT-8 because V also operates with UTF-8, for html I don't know
=> net.smtp: correct date in smtp body

vlib/regex/regex_test.v, vlib/regex/regex_util.v
Added regex split, so strings can be split on regex patterns. Use the results of `find_all` and return list of strings around the indices.
=> regex: add split
