website/templates/docs.html

Resolve some issues discussed in pull #10.

Fix generic docs after pull #10

---

README.md

Done for readability and simplicity.

/home/YOUR_USER -> $HOME

---

compiler/main.v

Shows how to use the run option in help message
```
- To execute a program without creating an executable:
v run file.v
```

main.v: added run option example in help message

---

examples/word_counter/word_counter.v

fix the word counter example

---

math/math.v

Functions exposed:
* ceil
* cosh
* exp
* floor
* log
* log10
* sinh
* tan
* tanh
* trunc

Exposing all the functions from C's math library

---

compiler/scanner.v

fix: add CRLF handling to scanner.v

---

time/time.v

Added `weekday_str()` method which will return the days in a string:

added weekday string method

---

builtin/string.v
builtin/string_test.v

String comparison functions were messed up. This PR fixes it. Also should solve sorting issues like #285.

Fix string comparison functions

---

thirdparty/glad/KHR/khrplatform.h

`glad.h` depends on `khrplatform.h`.
This PR adds `thirdparty/glad/KHR/khrpatform.h`

add `khrplatform.h`

---

builtin/map.v

I wanted to use map more iterable, so I made a function.
Please reject if unnecessary.

add keys fn in map structure.

---

math/math.v

Exposed `fmod` from C's math library

math.v: Expose fmod for modulus on floating point numbers

---

builtin/map.v

Add **exists** method to map.
```
if m.exists(key){
m[key] = m[key] + 1
}else{
m[key] = 1
}

Add exists method to map

---

compiler/jsgen.v
json/json_primitives.v

Add all types of int and float to json decode/encode

---

README.md

[![Build Status](https://dev.azure.com/alexander0785/vlang/_apis/build/status/vlang-CI?branchName=master)](https://dev.azure.com/alexander0785/vlang/_build/latest?definitionId=1&branchName=master)
Let build status be visible to everyone who visits the repository.

Azure Pipeline build status badge in README.md

---

gx/gx.v

Removed duplicate color constants, renamed constants appropriately and added more colors.

Updated colors in gx.v

---

compiler/parser.v
compiler/scanner.v

Solves : #549 
I only change the CAO string into a basic when the scanner finds a ***_ASSIGN token :
```
// Initial
a += b
// New string
a = a + b
```
A better fix would be to change lot of things inside parser

Compound assignment operators

---

examples/game_of_life/README.md

- Fix run command in README.md

Fix examples/game_of_life/README.md

---

.travis.yml
compiler/Makefile
glm/glm_test.v

- using matrix feature on travis
- set build language to C
- changed float to f32 in glm_test.v, because of compile error.
I've confirmed travis build and test passed on my branch (I don't have direct access to vlang/v on travis currently)

Use matrix and add osx build on travis

---

time/time_lin.v
time/time_mac.v

Don't use paste tense (e.g. "fixed foo bar").
Do not use # to generate C code. This feature will be removed in a couple of days.
Squash commits into one if they refer to the same thing. Use `git rebase -i` for that.
./v -o v
./v -o v

time: making methods public again fixing game of life example

---

.github/PULL_REQUEST_TEMPLATE

Fixed typo in PULL_REQUEST_TEMPLATE.

github: fix typo in PULL_REQUEST_TEMPLATE

---

.gitignore
examples/.gitignore

it will be easier to move the examples to a separate repository if it increases

examples: separate .gitignore fix

---

.gitignore
base64/base64.v
builtin/string.v
builtin/string_test.v
compiler/Makefile
glm/glm.v

Fix tests and let CI green

---

README.md

Add [![Build Status](https://travis-ci.org/vlang/v.svg?branch=master)](https://travis-ci.org/vlang/v) to README.md.

readme: add Travis build status badge

---

compiler/scanner.v

Fixes #671 
Partially fixes #632

parsing: fixed compound assignment operator on for loops

---

base64/base64.v

Completely fixes #632 if PR #678 is merged

base64: make encode and decode public

---

os/os.v

A user in the Discord app asked for a function to clear the screen. This did not yet exist, so here it is!
Use it like this:
```
import os
fn main() {
println('hello world')
os.clear()
println('bye world')
}
```

os: added clear()

---

examples/VCasino/.gitignore
examples/VCasino/README.md
examples/VCasino/VCasino.v

This is a little game that I propose for examples

add example VCasino

---

examples/log.v
log/log.v
termcolor/colors.v

#589 
Move `colors` to `termcolor`. And add `log`

add log and rename colors

---

azure-pipelines.yml

Already configured azure pipelines, somehow build is running on only master branch. 
also, I think **integration should be done in the smallest unit**.
Therefore, I changed to build in Pull Request unit.
Please merge if possible.
References:
- https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml

AzurePipelines: let's get started continuous integration for pull requests

---

compiler/Makefile

#732 
Prevent old files from causing upgrade failure

compiler: run clean befor all

---

compiler/main.v
os/os.v

Pressing Enter in REPL should create new line instead of quitting the REPL.
closes #718

REPL: Create new line while pressing enter.

---

compiler/scanner.v

scanner: fix on single letter variable declaration on first line

---

compiler/scanner.v

compiler: add EOF checks in scanner to prevent panic exits

---

gl/gl.v

Remove C hashes from the gl code.

gl: Remove C hashes

---

compiler/fn.v
compiler/parser.v

Check on variables like on regular functions if unused variables in scripting files
Fixes #770

compiler: checks if variables are unused on scripts main function

---

examples/tetris/tetris.v
gg/gg.v
glfw/glfw.v
os/os.v

better tetris example exit and resource loading
added some wrapper functions to glfw
removed hardcored path in gg module

Tetris example improvements

---

os/os.v

fixes windows build. Once v.c is updated with this change it should work in travis too

fix windows build

---

.travis.yml

add windows to travis build.
This will verify #776 after https://raw.githubusercontent.com/vlang/vc/master/v.c is updated

travis: windows build

---

.travis.yml
CHANGELOG.md
CodeStructure.md
Makefile

clean up: remove redundant spaces

---

.github/PULL_REQUEST_TEMPLATE
vlib/builtin/array_test.v
vlib/math/math_test.v

This PR improves tests + cleanups some of them
Makes more readable and also covers a bit more cases

vlib: update and cleanup tests + fix PR template

---

compiler/parser.v

comment out unnecessary println for interface.

remove unnecessary println

---

vlib/base64/base64_test.v

base64: refine test

---

vlib/math/math.v

math.v: log_n, log2, exp2, cbrt and docs

---

vlib/os/const.v

Added constants for generic Win API functions.
Added global-based constants for file open mode.

Create const.v for Unix/Win32 API constants.

---

vlib/os/types_win.v

Provided basic Win API data types.
Ref - https://docs.microsoft.com/en-us/windows/desktop/winprog/windows-data-types

Create types_win.v for Win API basic types.

---

vlib/os/const.v

Added permission bits for owner, group, others.

Added permission bits.

---

vlib/os/os_win.v

it is preferable to open the file in binary mode.

Change permission from 'r' to 'rb'

---

vlib/os/os.v
vlib/os/os_test.v

remove additional line from write_file

---

compiler/main.v
vlib/os/os.v

This PR Implements get_line & get_raw_line for windows
get_line was also simplified to use the output from get_raw_line
it also allows the REPL to work on windows (removed condition with panic)

implements get_line & get_raw_line for windows + REPL

---

vlib/math/fraction.v

This PR adds support for Fractions in the math module this has been achieved using ```struct Fraction``` and the implemented methods also supports direct addition and subtraction using ```+``` and ```-``` using operator overloading. Other methods such as ```reciprocal```, ```reduce```, ```gcf``` and ```to_decimal``` have also been added

math: added support for Fractions

---

vlib/math/fraction.v
vlib/math/fraction_test.v

@medvednikov Added some basic tests. Will make it more comprehensive in due course

math: added basic tests for fraction and fixed typo

---

vlib/os/os_test.v

Remove the created file at the end of the test.

os: remove test file

---

examples/.gitignore

- Remove following entries from examples/.gitignore becuase these directories have their own .gitignore
```
game_of_life/life
tetris/tetris
word_counter/word_counter
```
- Add following entires
```
rune
terminal_control
```

Modify examples/.gitignore

---

examples/nbody.v

Code based on https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/nbody-go-3.html

example: Proposal to add nbody.v example

---

compiler/main.v

Python like interactive shell
```
>>> a=24
undefined: `a`
>>> a:=24
>>> a
24
>>> a=25
`a` is immutable
>>> mut a:=24
redefinition of `a`
>>> mut b:=25 
>>> b=25
>>> b
25
>>> println(b)
25
>>> b
25
```
Not sure how to make test case for this it has to be done manually

main: vrepl interactive shell update

---

examples/spectral.v

Added file spectral.v for spectralnorm

examples: Added Benchmark-games: spectralnorm

---

vlib/math/complex.v
vlib/math/complex_test.v

This PR adds basic support for Complex Numbers in the math module and also implements tests which are based on practice examples of Khan Academy. Will be adding more operations and methods in due course

math: basic complex number support with tests

---

examples/spectral.v

examples: spectral.v Added benchmarks in comments

---

compiler/main.v

Also fixes similar bugs when appending libs to cmd.

fix for #1020

---

vlib/term/control.v

This PR optimizes the move function in term module

term: optimized move function

---

vlib/math/complex.v
vlib/math/complex_test.v

Added the following complex operations - 
1. ```addinv``` - Additive Inverse
2. ```mulinv``` - Multiplicative Inverse
3. ```mod``` - Modulus or Absolute
4. ```pow``` - Nth Power
5. ```root``` - Nth root
6. ```exp``` - Complex Exponential
7. ```ln``` - Natural Logarithm
Tests have been added and cross verified with **Wolfram Alpha**

math: additional complex operations with tests 

---

vlib/math/complex.v
vlib/math/complex_test.v

This PR adds the following operations-
1. ```sin``` - Complex Sin
2. ```cos``` - Complex Complex
3. ```tan``` - Complex Tangent
3. ```sinh``` - Complex Hyperbolic Sin
3. ```cosh``` - Complex Hyperbolic Cosine
3. ```tanh``` - Complex Hyperbolic Tangent
Tests have also been added and cross verified with **Wolfram Alpha**

math: added complex trig operations

---

vlib/math/math.v
vlib/math/math_test.v

add `erf`, `erfc`, `gamma` and `log_gamma` functions to `math.v` and add tests for the same

math : add error and gamma functions

---

vlib/math/fraction.v
vlib/math/fraction_test.v

reduce redundant code and add missing tests for `gcd` and `reduce`

math : reduce redundancy, add tests

---

vlib/http/http_win.v

Line 157 : buf[nr_read] = 0 
set the null character '\0'

http_win : fix buf length

---

vlib/os/os.v

Add flush method for files.
#1004

os: add flush method

---

compiler/parser.v
vlib/hash/crc32/crc32.v
vlib/hash/crc32/crc32_test.v

This PR implements very basic crc32 checksum

crc32 checksum

---

examples/tetris/tetris.v
examples/vcasino/VCasino.v
vlib/bf/bf_test.v
vlib/rand/rand.v
vlib/rand/rand_test.v

If `rand.seed()` can recive seed value, we can reproduce same random sequence by giving same seed.

rand: change rand.seed() to receive seed value

---

vlib/os/os.v
vlib/os/os_test.v

os: fork() and wait()

---

vlib/time/time.v
vlib/time/time_test.v

I'm sorry I cant launch test of this code cause of unknown error:
```
============ running ./vlib/time/time_test ============
sh: ././vlib/time/time_test: Нет такого файла или каталога
```

time: add days_in_month()

---

compiler/main.v
vlib/os/os.v

This PR adds the missing implementation of os.getexepath for mac.
Repl fix now in another PR https://github.com/vlang/v/pull/1034

add missing implementation of os.getexepath for mac

---

vlib/os/const.v
vlib/os/os_win.v

Add get_module_filename

---

vlib/szip/miniz.h
vlib/szip/szip.v
vlib/szip/zip.c
vlib/szip/zip.h

Added wrapper of https://github.com/kuba--/zip . 
Wrapper working, but not working https://github.com/kuba--/zip original C implementation. Please someone fix this.

Add zip wrapper

---

vlib/os/os.v

This fixes dir_exists on windows

fix dir_exists on windows

---

vlib/os/os.v

Before submitting this PR, submit https://github.com/vlang/v/pull/1188

Fixed buf on hostname and added optional type.

---

compiler/scanner.v

Fixed bug where compiler could not read
source files in UTF-8 encoding with BOM.
#781

Fix bug with BOM.

---

vlib/builtin/array.v
vlib/builtin/array_test.v

I had to close the other PR, i messed up the branch.
@medvednikov I added some tests, can you explain how to do it with pointers in V?

array.reverse()

---

vlib/crypto/md5/md5.v
vlib/crypto/md5/md5block_generic.v
vlib/crypto/sha1/sha1.v
vlib/crypto/sha256/sha256.v
vlib/crypto/sha256/sha256_test.v
vlib/crypto/sha256/sha256block_generic.v
vlib/crypto/sha512/sha512.v
vlib/crypto/sha512/sha512block_generic.v

This PR Implements sha256
I also cleaned up some crud I left in the other crypto modules

implement crypto.sha256 + some crypto cleanup

---

compiler/parser.v

If a number wont fit in a u32 it will automatically be made u64
This lets us have u64 in consts also

auto detect u64

---

vlib/net/socket_win.v
vlib/os/os.v
vlib/os/os_nix.v
vlib/os/os_win.v

Fixed `get_error_msg` fox *nix and added socket WSA Version constants.

Fixed get_error_msg for *nix

---

vlib/math/stats/stats.v
vlib/math/stats_test.v

This PR adds some basic statistical operations for f64 arrays-
1. ```freq``` - Frequency
2. ```mean``` - Mean
3. ```geometric_mean``` - Geometric Mean
4. ```harmonic_mean``` - Harmonic Mean
5. ```median``` - Median
6. ```mode``` - Mode
7. ```rms``` - Root Mean Square
8. ```population_variance``` - Population Variance
9. ```sample_variance``` - Sample Variance
10. ```population_stddev``` - Population Standard Deviation
11. ```sample_stddev``` - Sample Standard Deviation
12. ```mean_absdev``` - Mean Absolute Deviation
13. ```min``` - Minimum of the Array
14. ```max``` - Maximum of the Array
15. ```range``` - Range of the Array ( max - min )
Unit tests have been added and cross verified with **Wolfram Alpha**

math: added basic stats operations

---

Makefile

I tried to make a package, but it only builds and doesn't install itself.
It is expected to self-install into $(DESTDIR)$(PREFIX).
Thanks!
Yuri

The makefile doesn't install anything

---

vlib/math/stats_test.v

https://stackoverflow.com/a/347940
Windows displays a NaN as -1.#IND

math : fix win stats_test

---

vlib/bf/bf.v

Added a README file listing and describing all methods and functions provided by 'bf' module.

bf: add basic documentation

---

.travis.yml
compiler/main.v
vlib/builtin/builtin.v
vlib/builtin/utf8.v
vlib/math/math.v
vlib/os/os.v
vlib/os/os_win.v

Continuing https://github.com/vlang/v/pull/1266, rebased on latest Windows changes

WIP: Windows Unicode I/O, 3rd try

---

compiler/main.v
compiler/msvc_win.v
vlib/os/os.v

Added command line processing in Windows style

Windows: unicode command line

---

vlib/os/os.v

If max is 512 then allocate `max * sizeof(wchar_t)` which should be max*2 on all supported platforms.

os: Make windows allocations more consistent & LocalFree args_list

---

vlib/crypto/aes/block_generic.v
vlib/crypto/internal/subtle/aliasing.v

add note & fix typo in crypto

---

compiler/main.v

Just use the mod var I assigned, must have forgot first time.

neaten up small thing with imports

---

Dockerfile

docker: use /opt/ instead of /etc/ for binary storage

---

compiler/fn.v

This fixes the interface methods with arguments issue that people were having
labled as a hack becuase it does not fix interfaces in and of themselves

Hack interfaces into working with arguments

---

vlib/crypto/aes/aes_cbc.v
vlib/crypto/aes/const.v
vlib/crypto/md5/md5.v
vlib/crypto/md5/md5block_generic.v
vlib/crypto/sha1/sha1.v
vlib/crypto/sha256/sha256.v
vlib/crypto/sha512/sha512.v

Just some house keeping in crypto.
Use the new clone/copy.

crypto cleanup - use new copy & clone

---

compiler/modules.v
compiler/parser.v

compiler: fix issue #1350 - an error is produced, when a void fn returns a value.

---

examples/links_scraper.v
examples/news_fetcher.v
vlib/http/http.v

http.get and http.post should return ?string. Fix #1352

---

vlib/term/colors.v
vlib/term/colors_nix.v

fix term module. move format() to fix redefinition

---

vlib/pg/pg.v

Useful for those who does not want to use Homebrew

pg: add Darwin flag for MacPorts installation path

---

vlib/glfw/glfw.v

glfw: add MacPorts library path

---

make_tests.bat

Some tests are failed for now but it will help others to fix them

make_tests.bat: run tests under Windows(gcc)

---

vlib/builtin/int.v
vlib/math/complex_test.v
vlib/math/math_test.v

math.equals for f64 values

---

compiler/fn.v
compiler/parser.v

this fixes string interpolation

compiler: no need to optimize println on Windows

---

compiler/main.v

Initialization moved to init_consts for that

windows: utf-8 stdout was not initialized when we have main()

---

vlib/os/const.v
vlib/os/os.v

os: fix is_dir

---

compiler/modules.v

Just a little cleanup in modules.v

use map.delete and last_node (modules.v)

---

vlib/http/http_test.v
vlib/http/http_win.v

http.escape and http.unescape for windows

---

make_tests.bat
vlib/http/http_win.v

make_tests.bat: exit with error on failed test

---

vlib/net/urllib/urllib.v

fix oopsie with error message

---

compiler/scanner.v

This PR changes compiler error printing format as requested in #1428

scanner: change error printing format (#1428)

---

vlib/builtin/string.v

this adds string.count(substr) which counts occurrences of substr in s

vlib builtin: add string.count(substr)

---

compiler/vfmt.v

compiler: proper line numbers in debuggers (fix regression in 207bab5)

---

compiler/main.v

compiler: fix Raspberry Pi build

---

compiler/comptime.v
compiler/parser.v

It may help PR #1466 , also https://github.com/vlang/vc/issues/4 .

compiler: conditional guard for platform specific #includes in _xxx.v files.

---

compiler/main.v
vlib/builtin/map.v

main.v/builtin: Add import pass for builtin & map.str() use string builder

main.v/builtin: Add import pass for builtin & map.str() use string builder

---

compiler/fn.v
compiler/jsgen.v
compiler/main.v
compiler/parser.v
compiler/table.v

file import table now saved automatically to table.file_imports

compiler: cleanup. rename pkg to mod. auto save file import table after import pass

---

vlib/net/urllib/urllib.v

net.urllib: update enum / const style

net.urllib: update enum / const style

---

vlib/http/http.v

http: update http.v to use urllib.parse

http: update http.v to use urllib.parse

---

Makefile

* cache
* improve reproducibility

Makefile: cache

---

compiler/main.v

This PR implements a cache for the 'v run file.v' compilation ( issue #1365 ).
If a corresponding executable already exists, and is newer than the source file.v, then it is directly  executed without recompilation, saving some time. 
In effect, the 'v run' overhead is negligible on subsequent runs of the same file.

v run: recompile and execute a changed file.v just once.

---

compiler/msvc_win.v
vlib/bf/bf.v
vlib/crypto/aes/aes_cbc.v
vlib/crypto/aes/block_generic.v
vlib/crypto/md5/md5.v
vlib/crypto/rc4/rc4.v
vlib/crypto/rc4/rc4_test.v
vlib/crypto/sha1/sha1.v
vlib/crypto/sha256/sha256.v
vlib/crypto/sha512/sha512.v
vlib/crypto/sha512/sha512block_generic.v
vlib/glm/glm.v
vlib/net/urllib/urllib.v

vlib: fix mutable args

---

vlib/bf/bf.v
vlib/crypto/aes/aes_test.v

vlib: the last of the mut arg fixes

vlib: the last of the mut arg fixes

---

compiler/msvc_win.v

compiler: fix error in msvc_win

compiler: fix error in msvc_win

---

vlib/http/openssl_backend.v

openssl: add Brew openssl path

---

compiler/parser.v

compiler: properly add submodule to types. fixes unknown type for arrays using submodule type etc.

compiler: properly add submodule to types. fixes unknown type for arrays using submodule type etc. 

---

examples/tetris/tetris.v
vlib/freetype/freetype.v

Draw score in tetris, if font is available
Don't exit in freetype if font not available

examples: tetris: draw score

---

vlib/vweb/vweb.v

- Allow extra http methods with form: PUT, PATCH
- Rename `post_form` to `form`

Allow extra http methods with form: PUT, PATCH

---

compiler/main.v
tools/vget.v

Able to install multiple modules in one command:
```
v install pg gl sqlite
```

Able to install multiple modules in one command: 'v install m1 m2 m3 …'

---

tools/vget.v

With this PR, vget does not stop at the first module that fails, but tries to install all.
For example:
```
0[15:33:09]/v/v $ ./tools/vget nonexisting pg anothernonexisting glfw thirdnonexistingmodule 
Skipping module "nonexisting", since it does not exist.
Installing module "pg" from https://github.com/vlang/pg to /home/delian/.vmodules/pg ...
Skipping module "anothernonexisting", since it does not exist.
Installing module "glfw" from https://github.com/vlang/glfw to /home/delian/.vmodules/glfw ...
Could not install module "glfw" to "/home/delian/.vmodules/glfw" .
Error details: fatal: destination path '/home/delian/.vmodules/glfw' already exists and is not an empty directory.
Skipping module "thirdnonexistingmodule", since it does not exist.
1[15:33:15]/v/v $ 
```

vget: handle more errors.

---

vlib/vweb/vweb.v

Fixed the exit of vweb when the return of the socket is ''

vweb: fix V panic: array index out of range: 1/0

---

make.bat

Should be pretty self explanatory

Bootstrap twice on windows

---

vlib/net/urllib/urllib_test.v

net.urllib: fix typo in test

---

compiler/parser.v

This PR will automatically init any struct map fields

parser: auto init struct *map* fields

---

vlib/http/backend_nix.v
vlib/http/backend_win.v
vlib/http/http.v

vlib.http: follow redirects (openssl & schannel) + fix url params

vlib.http: follow redirects (openssl & schannel) + fix url params

---

vlib/encoding/csv/reader.v
vlib/encoding/csv/writer.v

encoding.csv: add write support

encoding.csv: add write support

---

compiler/jsgen.v
compiler/parser.v

https://github.com/vlang/v/issues/1609: Issue asks for storing fields of json obj not as inner object but as string
Added attribute "raw" and check if type of field is "string".
Storing field with attribute "raw" as "string".

raw json field: Add support for raw json fields in structs

---

vlib/http/http.v

vlib.http: make sure all paths start with /

vlib.http: make sure all paths start with /

---

vlib/http/http.v

vlib.http: make do() return errors instead of panic

vlib.http: make do() return errors instead of panic

---

vlib/encoding/csv/csv_test.v

encoding.csv: add test for writer

encoding.csv: add test for writer

---

compiler/tests/repl/error.repl

repl: fix compiler/tests/repl/error.repl test case.

---

make_tests.bat

removes the duplicated tests on windows

Compiler: Dont run so many tests

---

compiler/main.v
compiler/repl.v
compiler/tests/repl/conditional_blocks.repl
compiler/tests/repl/function.repl
compiler/tests/repl/repl_test.v

**Additions**:
Processes the functions and conditionnal blocks written by the user.
Function can be defined, and will be saved apart from standard REPL lines. They then can be called by the user in this REPL session.
Conditionnal block and loops can be written, upon closing they will be executed. All prints inside will be removed to not write them again when user continues on his session.
<br>
**Notes**:
Automated tests have been added.
`Else` statement have to be placed behind closing bracket
<br>
**Examples** : 
- Functions
```
>>> fn test() {
...  println('foo')
... }
>>> test()
foo
```
- Conditionnal blocks
```
>>> if true {
...   println('bar')
... }
bar
```
```
>>> if false {
...   println('foo')
... } else {
...   println('bar')
... }
bar
```
- Loops
```
>>> for i := 0; i < 4; i++ …
```

repl: functions, conditionnal blocks and loops support

---

vlib/pg/pg.v

Does it make sense to have host as parameter to connect?

Adding host parameter to pg connect

---

compiler/cheaders.v
compiler/live.v
compiler/main.v

This PR extracts some code that was not changed in a while from compiler/main.v:
1) The hot code reloading feature plugs into the generation of C declarations, C flags for the compiler and also it adds some C function definitions. All that is now inside compiler/live.v
2) The static C headers that are common to all transpiled C programs, are extracted into a constant in compiler/cheaders.v .

compiler: refactoring - extract cheaders.v and live.v from main.v .

---

compiler/query.v
vlib/builtin/int.v
vlib/pg/pg.v

This PR allows code like this:
existingc := db.select from Customer where id = 123 limit 1 or { panic(err) }
println('Existing customer name: $existingc.name')
It alsow allows multiple db.select orm queries in the same scope.

orm: fix select .. limit 1 => it returns a Row? . Allow multiple queries in the same scope

---

vlib/json/json_test.v

```
fn foo() {
// file_test.v
...
}
```
./v -o v compiler
./v -o v compiler
OK

tests: raw json fields

---

thirdparty/vschannel/vschannel.c
thirdparty/vschannel/vschannel.h
vlib/http/backend_win.v

This one fixes https://github.com/vlang/v/issues/1693

http: Fix issue #1693

---

compiler/parser.v

https://github.com/vlang/v/issues/1749
Register map type when creating new map.
```
fn foo() {
// file_test.v
...
}
```
./v -o v compiler
./v -o v compiler
OK

compiler: map type is not registered under some conditions

---

.travis.yml
compiler/main.v
make.bat
make_msvc.bat

For example with this PR:
```shell
0[20:19:24] /v/v $ time ./v run examples/hello_world.v  
Hello, World!
real    0m0.252s
user    0m0.223s
sys     0m0.027s
0[20:19:26] /v/v $ time ./v -cc tcc run examples/hello_world.v  
Hello, World!
real    0m0.063s
user    0m0.049s
sys     0m0.013s
0[20:19:29] /v/v $ 
```

compiler: allow passing options to v run

---

vlib/net/urllib/urllib.v

Apply changes from https://github.com/golang/go/commit/61bb56ad63992a3199acc55b2537c8355ef887b6

net.urllib: Update with latest changes from go lib

---

compiler/msvc.v
vlib/time/time.v

msvc: check exit code

---

compiler/repl.v

repl: fix issue #1777

---

compiler/tests/repl/naked_strings.repl

A simple test to ensure that inserting naked strings in the v repl does not regress.

repl: add a test for naked strings.

---

thirdparty/vschannel/vschannel.c
thirdparty/vschannel/vschannel.h
vlib/http/backend_win.v

vlib.http: windows - make https requests work in threads

vlib.http: windows - make https requests work in threads

---

vlib/readline/readline_lin.v

**Additions:**
Simple line input read
Ability to change input mode of terminal
**Examples:**
```
import readline
mut rl := readline.Readline{}
rl.enable_raw_mode()
println(rl.read_line())
rl.disable_raw_mode()
```

readline: basic reading on linux

---

compiler/msvc.v
compiler/parser.v

Fixes codegen for msvc and *maybe* other compilers aswell

Compiler: Fix array initialisation generation 

---

tools/gen_vc.v

tools: move gen_vc into the v repo (tools/gen_vc)

tools: move gen_vc into the v repo (tools/gen_vc)

---

tools/gen_vc.v

tools: gen_vc - add purge flag
ok, thats it.. no more it's complete 😄

tools: gen_vc - add purge flag

---

vlib/readline/readline_lin.v

**Additions:**
Cleaner readline module with same features as before.
Using Tokens and switch to dispatch into dedicated functions.

readline: reworked dispatch architecture for easier features add

---

vlib/readline/readline_lin.v

**Additions:**
You can now move you cursor and editing line anywhere.
Moving feature includes :
- Moving left or right
- Moving to start of line (CTRL + A)
- Moving to end of line (CTRL + E)
- Moving word to word left or right ( CTRL + Left/Right )
**Examples:**
- Moving left or right and editing line :
- Moving from end to end
- Moving word to word

readline: moving cursor feature

---

vlib/readline/readline_lin.v

**Additions:**
Now you can edit in multiline without everything falling apart.
You can go back and forth with your cursor and edit through the wrapping without problems.
**Notes:**
This version of readline might be enough as it is to replace the getline used in REPL on Linux.
**Examples:**

readline: multiline wrapping for editing and cursor

---

vlib/readline/readline_lin.v

**Additions:**
Included prompt feature. You give it as an argument to the main function of the readline module.
**Note:**
For no prompt, you can give an empty string as a prompt.
**Examples:**
```
rl.readline('>>> ')
```

readline: add custom prompt feature

---

compiler/parser.v
compiler/table.v
vlib/builtin/int_test.v
vlib/encoding/csv/csv_test.v
vlib/encoding/csv/reader.v
vlib/encoding/csv/writer.v

compiler/vlib: fix bugs breaking tests

compiler/vlib: fix bugs breaking tests

---

.travis.yml

This should make windows tests red

Travis: break windows tests

---

vlib/readline/readline_lin.v

**Additions:**
History feature on same session using up and down key.
**Examples:**

readline: history feature

---

vlib/crypto/rand/rand_test.v

crypto.rand: improve test to actually check for difference in data

crypto.rand: improve test to actually check for difference in data

---

compiler/parser.v
compiler/tests/repl/chained_fields.repl
compiler/tests/repl/repl_test.v

compiler: fix repl chained_fields test

compiler: fix repl chained_fields test (windows)

---

.travis.yml
vlib/builtin/array.v

Travis: make windows tests red again

---

compiler/cgen.v

compiler: simplify & optimize cgen sort_structs

compiler: simplify & optimize cgen sort_structs

---

compiler/tests/fn_test.v

tests: workaround for fn_test on windows to make travis pass

tests: workaround for fn_test on windows

---

compiler/parser.v

Add additional paren for multi case branch in match statement.
Fixes https://github.com/vlang/v/issues/1858.
```
fn foo() {
// file_test.v
...
}
```
./v -o v compiler
./v -o v compiler
OK

compiler-fix: fix multi case branch in match

---

examples/hot_reload/bounce.v
examples/hot_reload/graph.v

examples: fix *Type warning

---

compiler/cgen.v

The note to tag me should be removed after some time, it's just in case I overlooked something and an error occurs. Once it's proven stable we can remove note to tag me, or whole error.

compiler/cgen: fix github username in error message

---

vlib/readline/readline_lin.v

**Additions:**
Access the overwrite mode using Inser key.
Fixed eof ended lines not being saved in the history.
**Examples:**

readline: overwrite mode and eof fix

---

compiler/parser.v

fn add(x,y int)int{
return x + y
}
fn main(){
fadd:=add
println(fadd(1,2))
}

function pointer assign

---

vlib/readline/readline_lin.v

**Additions:**
You can now suspend the readline using the Ctrl-Z key.
Stopped showing special characters that are not handled.
**Examples:**

readline: added suspend handling and dont print special characters

---

vlib/vweb/assets/assets.v

Just a little copy/paste mistake resolve here
Check `commit` to see what is it :)

Change doc comment

---

compiler/cc.v
compiler/cflags.v

compiler: tidy flag order

---

compiler/cc.v
compiler/cflags.v
compiler/msvc.v

thirdparty: remove freetype submodule accidentally added in #1890

thirdparty: remove freetype submodule accidentally added in #1890 & small tidy up

---

compiler/main.v

Isolate responsibility to reduce complexity in the main method.

compiler: isolate install_v to reduce complexity

---

compiler/main.v
vlib/os/os.v

compiler: make self compilation detection more robust

os: use path separator more consistently

---

README.md

Describe some common solutions/answers to problems with v compilation.

Add Troubleshooting section to the README

---

compiler/vhelp.v

Follow-up on this PR https://github.com/vlang/v/pull/1926

compiler: fix typos in vhelp.v

---

compiler/fn.v
compiler/table.v
vlib/strings/similarity.v

compiler: remove testing printf in typo check & clean few things
also changed to f32 was no need for f64

compiler: remove testing printf in typo check & clean few things

---

compiler/cc.v

Create the modules directory if it's not there.

cc.v: build_module mode fix

---

vlib/hash/crc32/crc32.v

hash.crc32: change *Crc32 to &Crc32

hash.crc32: change *Crc32 to &Crc32

---

vlib/bitfield/bitfield.v
vlib/flag/flag.v
vlib/gg/gg.v
vlib/math/math.v
vlib/readline/readline_lin.v
vlib/szip/szip.v
vlib/term/control.v
vlib/vweb/README.md

Fix several typos while I was studying the `/vlib` last night.

vlib: Fix several typos

---

.gitignore

We should be ignoring macOS `.DS_Store` files and other files.

.gitignore: add macOS

---

vlib/readline/readline_lin.v

**Additions:**
Writing without a tty (e.g. through a pipe)
Fix compilation error on column retrieval
No writing if not on tty
**Examples:**
```
$ echo -en "hello world !\nfoo bar!" | ./readline 
read: hello world !
read: foo bar!
```

readline: allow writing without tty and small fixes

---

compiler/tests/struct_test.v
examples/news_fetcher.v
examples/spectral.v
examples/tetris/tetris.v
vlib/bitfield/bitfield.v
vlib/builtin/array_test.v
vlib/crypto/aes/cypher_generic.v
vlib/crypto/md5/md5.v
vlib/crypto/rc4/rc4.v
vlib/crypto/sha1/sha1.v
vlib/crypto/sha1/sha1block_generic.v
vlib/crypto/sha256/sha256.v
vlib/crypto/sha256/sha256block_generic.v
vlib/crypto/sha512/sha512.v
vlib/crypto/sha512/sha512block_generic.v
vlib/net/urllib/urllib.v
vlib/rand/rand_test.v

Update array init syntax: change all occurrences of  `[0;n]` to `[0].repeat(n)`

vlib: change `[0;n]` to `[0].repeat(n)`

---

.travis.yml
compiler/cheaders.v
compiler/gen_c.v

WIP: do not merge for now. This just experiments with the Travis build on windows.

travis: try to spawn 2 separate windows instances

---

compiler/table.v

sorry i forgot to commit a change in last PR

compiler: typo fix 2 - fix module typo detect fn

---

.travis.yml
compiler/cheaders.v
compiler/fn.v
compiler/gen_c.v
compiler/parser.v

fix msvc empty struct & enable travis msvc

compiler: fix msvc empty struct & enable travis msvc

---

compiler/cheaders.v

compiler: update default EMPTY_STRUCT_INITIALIZATION

compiler: update default EMPTY_STRUCT_INITIALIZATION

---

compiler/main.v
compiler/tests/repl/repl_test.v
compiler/tests/repl/run.v
compiler/tests/repl/runner/runner.v
vlib/benchmark/benchmark.v

The new benchmark module is used inside the repl tests too.

benchmark: add vlib/benchmark. Make 'v --verbose test v' use it.

---

vlib/glfw/glfw.v

glfw: printf -> println

---

vlib/encoding/binary/binary.v
vlib/math/bits/bits.v

vlib: inline helper fucntions used a lot in crypto
This will work once https://github.com/vlang/v/pull/2027 is merged

vlib: inline helper functions used a lot in crypto

---

vlib/crypto/rand/rand_test.v
vlib/crypto/rand/utils.v

crypto.rand: utils - rename `read_u64` to `int_u64` + clean up fn

crypto.rand: utils - rename `read_u64` to `int_u64` + clean up fn

---

.travis.yml
compiler/cheaders.v
compiler/gen_js.v

1) classes are evil :)
2) js output should be ES5-compliant
3) no need in nightly(sic!) node, no need in harmony options, no need in custom gcc on linux

js: no need to generate classes

---

vlib/crypto/rand/rand_test.v

crypto.rand: fix rand test from failing sometimes & improve

---

vlib/builtin/array.v

Let's merge this and see if it will stop windows_gcc failures

Trying to prevent sporadically windows gcc test failures

---

.github/workflows/ci.yml
README.md
examples/hello_v_js.v
examples/hello_world.v

github actions: simplify ci.yml, fix log in win, test js backend in win

---

.github/workflows/ci.yml
compiler/parser.v
vlib/freetype/freetype.v

~Please do not merge. This is just an experiment to better understand github actions behaviour, and to measure build steps timings on different platforms.~
This PR contains fixes for running `v test v` with tcc, so that it can be used as a separate github action (the fastest one).

github actions: split jobs to more steps. compiler: fix `v test v` on tcc

---

vlib/math/bits/bits.v

math.bits: add missing pub to fn's

math.bits: add missing pub to fn's

---

compiler/cc.v
compiler/cflags.v
compiler/cgen.v
compiler/comptime.v
compiler/msvc.v

Add the ability to specify module specific, thirdparty object compilation flags.

compiler: compile thirdparty object files using module specific flags.

---

compiler/fn.v
compiler/parser.v
compiler/tests/fn_multiple_returns_test.v

compiler: multiple returns - add test & fix use with array/map

compiler: multiple returns - add test & fix use with array/map

---

compiler/table.v

compiler: improve module typo error message

compiler: improve module typo error message

---

compiler/parser.v

compiler: unused module check always

compiler: unused module check always

---

compiler/table.v

compiler: clean up get_file_import_table

compiler: clean up get_file_import_table

---

compiler/fn.v
compiler/parser.v

compiler: clean up multiple returns a bit

compiler: clean up multiple returns a bit

---

compiler/gen_c.v
compiler/gen_js.v
compiler/parser.v

compiler: re assignable blank identifier `_` & no longer a variable.

compiler: re assignable blank identifier `_` & no longer a variable.

---

compiler/fn.v
compiler/parser.v
compiler/table.v
tools/gen_vc.v
tools/vget.v
vlib/builtin/array.v
vlib/crypto/aes/block_generic.v
vlib/crypto/rc4/rc4.v
vlib/encoding/binary/binary.v
vlib/net/socket_udp_test.v
vlib/net/urllib/urllib.v
vlib/vweb/tmpl/tmpl.v

compiler/vlib: change `_ :=` to `_ =` and disable `_ :=`

compiler/vlib: change `_ :=` to `_ =` and disable `_ :=`

---

.github/workflows/ci.yml

actions: test - try do update first

actions: test - try do update first

---

compiler/main.v
compiler/msvc.v
compiler/parser.v
compiler/table.v
compiler/tests/repl/chained_fields.repl
vlib/crypto/rand/rand.v
vlib/encoding/csv/reader.v
vlib/os/os_win.v
vlib/szip/szip.v
vlib/vweb/assets/assets.v

compiler/vlib: add error for no new vars `_,_` in loop and remove `.` from errors

compiler/vlib: add error for no new vars in loop (`_,_`) & remove `.` from errors

---

compiler/tests/repl/.gitignore
compiler/tests/repl/runner/runner.v
examples/.gitignore

When there is a difference between expected and produced output, the repl runner now shows the difference too (using colordiff or diff).

repl: tests show difference (in color where available)

---

compiler/gen_c.v
compiler/gen_js.v

compiler: small fixes with blank identifier

compiler: small fixes with blank identifier

---

vlib/math/bits/bits.v

math.bits: remove extraneous casts

math.bits: remove extraneous casts

---

vlib/crypto/aes/block_generic.v

crypto.aes: remove extraneous casts

crypto.aes: remove extraneous casts

---

vlib/pg/pg.v

pg: update optional return syntax

pg: update optional return syntax

---

vlib/crypto/md5/md5.v
vlib/crypto/rc4/rc4.v
vlib/crypto/sha1/sha1.v
vlib/crypto/sha1/sha1block_generic.v

crypto.[md5/rc4/sha1]: remove extraneous casts & update array repeat

crypto.[md5/rc4/sha1]: remove extraneous casts & update array repeat

---

compiler/parser.v

This is a PR for #2142 .
such code will cause an error:
```v
fn main() {
mut a := [1]
a << 2
}
```
For `mut a := [1]byte`. First check newline, if there is a newline, then a is just a single element array. If not, a is a fixed array, then check if there is space between `byte` and `[10]`.

compiler/parser: fix single element in array error(#2142)

---

vlib/builtin/string.v

Just some comments/documentation for vlib/builtin/string.v .

string: document the tradeoffs for v strings.

---

vlib/crypto/md5/md5.v

crypto.md5: fix bug. u64 modulus operation

crypto.md5: fix bug. u64 modulus operation

---

compiler/cflags.v
vlib/freetype/freetype.v
vlib/glfw/glfw.v

These changes will make freetype and glfw work under FreeBSD

cflags/freetype/glfw: Enable FreeBSD's cflags

---

.travis.yml
tools/vget.v

refactor vget.v: extract vmodules directory create and chdir logic

Refactor tools

---

compiler/fn.v
compiler/gen_c.v
compiler/gen_js.v
compiler/parser.v

compiler: blank identifier for loops. dont declare any variables

compiler: blank identifier for loops. dont declare any variables

---

.github/workflows/ci.yml
.travis.yml
compiler/main.v
compiler/scanner.v

This also fixes the failing 
./compiler/tests/repl/chained_fields.repl test

compiler: change s.line_nr in just one place in tandem with s.last_nl_pos

---

compiler/fn.v
compiler/parser.v
compiler/scanner.v
compiler/table.v
vlib/term/can_show_color_nix.v
vlib/term/can_show_color_win.v
vlib/term/control.v

This PR implements:
fn (p mut Parser) error_with_tok(s string, tok Tok) 
and uses it to solve issue #2079 .

Fix #2079 . Add some infrastructure for more specific errors.

---

.gitignore
CONTRIBUTING.md

add .vrepl_temp.v to .gitignore and fix some grammar

---

vlib/crypto/md5/md5.v
vlib/crypto/sha1/sha1.v
vlib/crypto/sha256/sha256.v
vlib/crypto/sha512/sha512.v

crypto: make sum safe. copy bytes

crypto: make sum methods safe. copy bytes

---

compiler/fn.v
compiler/gen_c.v
compiler/gen_js.v
compiler/parser.v

compiler: vargs - for loop support & indexing / dot fixes

compiler: vargs - for loop support & indexing / dot fixes

---

compiler/fn.v
compiler/parser.v

compiler: variadic fn - move code to appropriate place

compiler: variadic fn - improve error, fix bug when only arg is varg & cleanup

---

compiler/gen_c.v
compiler/gen_js.v
vlib/builtin/array.v

compiler: add v warn if assigning var to blank identifier `_` & fix C warn

compiler: add v error if assigning var to blank identifier `_` & fix C warn & double semicolon

---

.gitignore
vlib/builtin/js/hashmap.v

Fixes [#2198](https://github.com/vlang/v/issues/2198)

JS : fix js backend build

---

compiler/msvc.v

It will not disable release optimizations but will allow to debug release binary

msvc: generate PDB for prod builds

---

CONTRIBUTING.md

Added [@spytheman's example](https://discordapp.com/channels/592103645835821068/592106336838352923/627559453788733440). Please review @spytheman and @medvednikov with any improvements or updates and clarifications! :) Hope this helps.  I'm sure I can make things a little more consistent or improve formatting a little, but I wanted to get this at least somewhere where we won't forget to share it.

Update CONTRIBUTING.md with workflow example

---

vlib/builtin/array.v
vlib/builtin/array_test.v

Add the `find()` method to the `[]string`.
I'm not sure about the method name, but for now, `find()` is the most suitable and simple. Based on request from #2189.

array: add index() method 

---

compiler/cc.v
compiler/main.v
compiler/module_header.v
compiler/modules.v
compiler/parser.v
compiler/scanner.v
compiler/table.v

compiler: get existing parser using path

compiler: get existing parser using path

---

compiler/main.v
vlib/strings/builder_js.v

compiler/js: fix strings.builder for vjs

compiler/js: fix strings.builder for vjs

---

README.md

Grammar fix on readme.md file

---

compiler/gen_c.v
compiler/parser.v
compiler/tests/fixed_array_test.v

compiler: initializing fixed arrays with [1,2,3]!! works now. Add tests.

---

vlib/time/time.v

adds pub fn (t Time) ddmmy() string {...} to format date in dot notation e.g. 05.02.2012

time: add new public format function ddmmy()

---

compiler/repl.v
compiler/tests/repl/chained_fields.repl
compiler/tests/repl/error_nosave.repl
compiler/tests/repl/immutable_len_fields.repl

**Additions :**
No save of lines that had a generated print.
No save of lines with a print inside a one-line condition / loop
** Notes :**
Fixes #2032 
Fixes #2042 (part of)

repl: no save of lines from generated print and inside one-line conditions

---

compiler/parser.v

This PR makes specifying mutability with multiple return variable declaration possible:
```
a, mut b, c := multi_return_fn()
```
It also disallows assignment mixed in with declaration:
```
a := 1
a, b := multi_return_fn()
```
Instead only these are allowed:
```
a := 1
b := 2
a, b = multi_return_fn()
```
OR
```
a, b := multi_return_fn()
```

compiler: multiple return - allow mut for mr vars & disallow assignment with deceleration

---

compiler/main.v
compiler/modules.v
compiler/parser.v
compiler/table.v

compiler: improve module import error messages.
closes #2124

compiler: improve module import error messages. closes #2124

---

vlib/os/os.v

windows: read console with ReadConsole when it is not redirected

---

.gitignore
vlib/builtin/array.v
vlib/builtin/array_test.v

The `filter()` method creates a new array with all elements that pass the test implemented by the provided function.
```go
fn callback(val string, index int, arr []string) bool {
return val.len >= 6
}
fn main() {
words := ['spray', 'limit', 'elite', 'exuberant', 'destruction', 'present']
new_words := words.filter(callback)
println(new_words)
}
```
```go
["exuberant", "destruction", "present"]
```

array: add filter() method

---

compiler/parser.v

compiler: fix regression with blank identifier & decl assign
`_ := 2` accidentally got allowed again in a previous PR. this makes it behave correctly again

compiler: fix regression with blank identifier & decl assign

---

thirdparty/vschannel/vschannel.c
vlib/net/init_nix.v
vlib/net/init_win.v
vlib/net/net.v
vlib/net/socket.v
vlib/net/socket_win.v

Initialization moved to module init

socket: no need to initialize WinSock on each request

---

vlib/builtin/string.v
vlib/crypto/aes/aes_cbc.v
vlib/crypto/rand/rand_lin.v
vlib/crypto/sha512/sha512.v
vlib/net/urllib/urllib.v
vlib/net/urllib/values.v

Update urllib & new method `strings.index_byte`
rename methods starting with underscore from `urllib` & `crypto`
add builtin strings methods `index_byte` & `last_index_byte`

vlib: urllib update / rem underscore methods from urllib/crypto. add strings index_bytes

---

vlib/builtin/array.v
vlib/builtin/array_test.v

The reduce() method executes a reducer function (that you provide) on each element of the array, resulting in a single output value.
```go
fn sum(prev int, curr int) int {
return prev + curr
}
fn sub(prev int, curr int) int {
return prev - curr
}
fn main() {
a := [1, 2, 3]
b := a.reduce(sum, 0)
c := a.reduce(sub, 0)
d := a.reduce(sum, -1)
println(b)
println(c)
println(d)
}
```
```go
6
-6
5
```

array: add reduce() method

---

compiler/main.v
compiler/parser.v

compiler: cached module - cleanup, remove unneeded code

compiler: cached module - cleanup, remove unneeded code

---

compiler/main.v
compiler/parser.v

compiler: module init, add init fn definition

compiler: module init, add init fn definition

---

compiler/fn.v
vlib/http/backend_win.v
vlib/net/init_nix.v
vlib/net/init_win.v

compiler: detect and error on public init function & remove empty init functions

compiler: detect and error on public init function & remove empty init functions

---

compiler/parser.v
compiler/tests/defer_test.v

Deferred statements are now also executed for void or `?` functions. (Fixes #1884)
This is now possible:
```v
fn (n mut Stuff) {
defer { n.val = 42 }
if n.x < 10 { 
return 
} else {
println("x >= 10")
} 
// defer called in any case
}
```

16:12: Enable deferred stms for void and optional functions

---

vlib/runtime/runtime.v
vlib/runtime/runtime_lin.v
vlib/runtime/runtime_mac.v
vlib/runtime/runtime_test.v
vlib/runtime/runtime_win.v

This trivial change adds support for Windows nr_cpus()
Updated also the test to run on both windows and linux

runtime: add windows support for nr_cpus()

---

compiler/parser.v

Fix parser not doing a complete first pass on a .v file if it finds any statements before declarations.
Fixes #1481

22:40: Fix parser not making a complete first pass on file

---

compiler/compile_errors.v
compiler/fn.v
compiler/main.v
compiler/module_header.v
compiler/modules.v
compiler/parser.v
compiler/table.v

compiler: use original name as p.mod & some mod header fixes & some clean up

compiler: use original name as p.mod & some mod header fixes & some clean up

---

compiler/main.v
examples/hot_reload/graph.v

compiler: optimize parse_lib_imports

compiler: optimize parse_lib_imports

---

compiler/modules.v

compiler: prepare for compiler module rename from vcompiler to compiler

compiler: prepare for compiler module rename from vcompiler to compiler

---

vlib/compiler/main.v
vlib/compiler/table.v

compiler: optimize, don't rescan module directory for files

compiler: optimize, don't rescan module directory for files

---

.github/workflows/ci.yml
.travis.yml
vlib/builtin/js/map.v
vlib/compiler/cc.v

**Please delete this information after reading it.*
```
fn foo() {
// file_test.v
...
}
```
./v -o v compiler
./v -o v compiler

CI: fix ci building v

---

.github/workflows/ci.yml
.travis.yml
make.bat

make/CI: put back temporarily removed flags and env vars

make/CI: put back temporarily removed flags and env vars

---

vlib/compiler/main.v

compiler: add notice about msvc compilation. and remove last traces of os msvc

compiler: add notice about msvc compilation. and remove last traces of os msvc

---

Makefile

Don't download tcc for mac, only tcc win and tcc linux

Download tcc linux and windows only

---

examples/word_counter/README.md
examples/word_counter/word_counter.v

Behavior of word_counter example looked wrong, so I opened an issue (https://github.com/vlang/v/issues/2357). 
The reason was that new lines in a text file was not handled correctly.
This PR fixes the issue.
(not sure why "a" was not counted before and why sort order was different.)

example: fix word_counter

---

vlib/math/unsafe.v

math: add functions for getting the bit representation of a float & vice versa

math: add functions for getting the bit representation of a float & vice versa

---

vlib/compiler/comptime.v
vlib/compiler/parser.v

- Multi-dimensional array including `array_` iteratively
- generate array string function recursively
```
module main
fn main() {
a := [1, 2, 3]
b := [4, 5, 6]
c := [7, 8, 9]
d := [[a, b, c], [b, c, a], [c, a, b]]
println(d)
}
````

Infinite multi-dimensional array

---

vlib/builtin/int.v

fix https://github.com/vlang/v/issues/2228

int: i64 hex() use PRIx64

---

examples/fibonacci.v

**Hello,**
I add this simple program which displays terms of the fibonacci sequence, here is an example :
```bash
$ v run examples/fibonacci.v 10
1
2
3
5
8
13
21
34
55
89
```
This program uses os.args, for loops and inputs / outputs.

examples: add fibonacci

---

vlib/builtin/string.v
vlib/strconv/atoi.v

strconv: optimize functions & make it the responsibility of the caller to properly trim whitespace

strconv: optimize fucntions & make it the responsibility if the caller to properly trim whitespace

---

vlib/compiler/live.v
vlib/os/os.v

Fixes live code reloading with msvc on windows.

live: Fix MSVC hot code reloading

---

vlib/compiler/fn.v

This shouldnt be necessary but is a temporary fix whilst someone looks into that.

Fn: Fix memory bug with generic code generation

---

tools/vnames.v
vlib/builtin/array.v
vlib/builtin/array_test.v
vlib/compiler/cc.v
vlib/compiler/fn.v
vlib/compiler/main.v
vlib/compiler/parser.v
vlib/compiler/table.v
vlib/compiler/tests/repl/run.v
vlib/compiler/vtest.v
vlib/hash/hash.v
vlib/vweb/assets/assets.v

This tool is meant to be used for generating word lists for auto completion purposes.
It also serves as test using `import compiler` outside of the main v.v .
This:
```shell
tools/vnames vlib/math 
```
or just:
```shell
tools/vnames .
```
This tool also found some problems with existing v files ( vlib/vweb/assets/assets.v and vlib/hash/hash.v ) , so it can also be used as a kind of a linter too.

tools/vnames: new tool to extracts function names declared in v files

---

vlib/compiler/compile_errors.v
vlib/compiler/scanner.v

With this PR:
```v
0[18:11:15]delian@nemesis: /v/nv $ ./v /v/misc/syntax_error.v
/v/misc/syntax_error.v:2:17: undefined: `this`
1| fn main(){
2|     println( this is a syntax error )
^
3| }
4|
1[18:11:17]delian@nemesis: /v/nv $
```
vs before:
```v
0[18:11:52]delian@nemesis: /v/nv $ /v/newv/v /v/misc/syntax_error.v
/v/misc/syntax_error.v:2:17: undefined: `this`
1| fn main(){
2|     println( this is a syntax error )
^
3| }
```

compiler: cleanup empty lines in errors. Simplify source line tracking.

---

vlib/time/time.v

* squashes three occasions of const(...) into one const(...) statement at the top of the file

time: squash three occasions of const(...) into one at top of file

---

vlib/compiler/fn.v
vlib/compiler/tests/fn_variadic_test.v

compiler: generic variadic -fix bug when returning from variadic & add test

compiler: generic variadic -fix bug when returning from variadic & add test

---

vlib/compiler/cgen.v
vlib/compiler/depgraph.v
vlib/compiler/main.v

compiler: show struct dependency cycles in error & update module cycle error

compiler: show struct dependency cycles in error & update module cycle error

---

vlib/freetype/freetype.v
vlib/gg/gg.v
vlib/gl/1shader.v
vlib/glfw/glfw.v
vlib/glm/glm.v
vlib/gx/gx.v

vlib: make more structs, consts, & enums public

---

vlib/compiler/parser.v
vlib/compiler/table.v

compiler: add const to typo suggestions & small typo format update

compiler: add const to typo suggestions & small typo format update

---

vlib/compiler/compile_errors.v
vlib/compiler/fn.v
vlib/compiler/main.v
vlib/compiler/modules.v
vlib/compiler/parser.v
vlib/compiler/table.v

compiler: cleanup general & with parser reuse
I'm seeing 100-150ms speedup compiling with TCC

compiler: cleanup general & with parser reuse

---

vlib/builtin/array.v
vlib/builtin/array_test.v
vlib/builtin/string.v
vlib/builtin/string_test.v
vlib/compiler/gen_c.v
vlib/compiler/parser.v

compiler/builtin: add `[..2]` & `[2..]` support for slices

compiler/builtin: add `[..2]` & `[2..]` support for slices

---

vlib/builtin/array_test.v

builtin: pub back actual array left & right method tests which I accidentally removed

builtin: pub back actual array left & right method tests

---

vlib/readline/readline_lin.v

readline:  switch => match

---

vlib/sqlite/sqlite.v

Add flags for FreeBSD to pass sqlite test

sqlite: Add flags for FreeBSD to pass sqlite test

---

vlib/compiler/gen_c.v
vlib/compiler/gen_js.v

compiler: remove duplicate code. create single function to handle optionals

compiler: remove duplicate code. create single function to handle optionals

---

vlib/readline/readline_lin.v

I dont know what the name of this feature :grinning:

readline: using direct dot

---

vlib/compiler/fn.v

Fixes https://github.com/vlang/v/issues/2579

Fix broken methods with vargs

---

vlib/compiler/comptime.v
vlib/compiler/fn.v
vlib/compiler/main.v
vlib/compiler/parser.v
vlib/compiler/table.v

compiler: add varg str method & varg / parser optimizations
closes #2433
also this makes vargs use the actual type `vargs_*type*` instead of `...type`

compiler: add varg str method & varg / parser optimizations

---

vlib/compiler/cc.v

compiler: remove now unneeded blank ident assignment

compiler: remove now unneeded blank ident assignment

---

vlib/compiler/modules.v
vlib/compiler/parser.v
vlib/compiler/table.v

compiler: improve typo detection, support all types and fn definitions

compiler: improve typo detection, support all types and fn definitions

---

vlib/readline/readline_linux.v

**Additions:**
Revert to old function to catch SIGUSER Signal (^C) to reset the tty
**Notes:**
Fixes #2628

readline: catch siguser signal to reset tty

---

vlib/compiler/compile_errors.v
vlib/compiler/gen_c.v
vlib/compiler/gen_js.v
vlib/compiler/parser.v

compiler: add error when trying to assign from a function that does not return a value
closes #2640

compiler: add error when trying to assign from a function that does not return a value

---

vlib/compiler/table.v

compiler: typo detection - fix error & slightly optimize function
thanks @avitkauskas

compiler: typo detection - fix error & slightly optimize function

---

vlib/compiler/parser.v

@medvednikov i've opened a new clear PR for #2669

parser: fix builtin as name not allowed

---

tools/vtest.v
vlib/compiler/msvc.v
vlib/os/os.v
vlib/os/os_nix.v
vlib/os/os_windows.v

This will allow to os.exec from tcc and from gui programs in the future

windows: use CreateProcess for os.exec

---

vlib/compiler/parser.v

This PR addresses issue [#2666](https://github.com/vlang/v/issues/2666).

parser: fix mod assign type check

---

vlib/math/math.v

little correction of the return value of ceil, it should be f64.
some comment in floor had integer return value but it did return f64 correctly.

Pullrequest

---

vlib/compiler/fn.v
vlib/compiler/live.v

trivial fix to remove stupid pthread_create voidptr 3rd arg warning

Fix pthread 3rd arg voidptr warning

---

vlib/builtin/builtin.v

Trivial byteptr signedness warning fix

Fix byteptr signedness warning

---

vlib/os/os.v

Trivial fix to remove stat mode signedness comparison warning

fix stat mode signedness warning

---

vlib/compiler/expression.v

This PR addresses issue [#2691](https://github.com/vlang/v/issues/2691).

compiler: check mul and div operations on strings

---

vlib/compiler/expression.v

This PR addresses issue #2690.
The error message is slightly modified.

parser: add xor type check

---

.github/workflows/ci.yml

tests: enable tcc tests in CI

---

vlib/compiler/expression.v
vlib/compiler/parser.v
vlib/compiler/tests/pointers_test.v

```
fn test_pointer_arithmetic() {
arr := [1,2,3,4]
unsafe {
mut parr := *int(arr.data)
parr += 1
assert 2 == *parr
parr++
assert 3 == *parr
assert *(parr + 1) == 4
}
}
```

ptr++,*(ptr+1)

---

examples/random_ips.v

Added new example showing off `rand.next()` to generate 10 random IP addresses.

examples: add random_ips.v

---

vlib/compiler/main.v
vlib/compiler/module_header.v

fix the vexe path when it's relative instead of absolute to not having /usr/local/bin/v point to /usr/local/bin/v

fix "v symlink" when relative path

---

vlib/compiler/comptime.v
vlib/compiler/main.v
vlib/compiler/modules.v

compiler: add -vpath and -vlib_path options

---

vlib/compiler/fn.v
vlib/vweb/vweb.v

compiler/vweb: small optimization with generics and use os.is_dir in vweb again

compiler/vweb: small optimization with generics and use os.is_dir in vweb again

---

vlib/compiler/fn.v

compiler: clean up & optimize generics. add comments & support all param types

compiler: clean up & optimize generics. add comments & support all param types

---

vlib/compiler/fn.v

compiler: generics fix byteptr support & add comments / formatting

compiler: generics fix byteptr support

---

tools/gen_vc.v
tools/vcreate.v
tools/vpm.v
vlib/compiler/cc.v
vlib/compiler/main.v
vlib/compiler/module_header.v
vlib/compiler/vtmp.v
vlib/os/os.v
vlib/os/os_nix.v
vlib/os/os_test.v
vlib/os/os_windows.v
vlib/vweb/assets/assets.v

os: mkdir() error handling

---

vlib/compiler/cgen.v
vlib/compiler/main.v

* making Haiku known to v
Signed-off-by: Enrico Lefass <enrico.lefass@mailbox.org>

haiku: adding support to v #1

---

vlib/compiler/compile_errors.v

compiler: fix get_last_nl_from_pos when error is last token

compiler: fix get_last_nl_from_pos when error is last token

---

vlib/compiler/comptime.v
vlib/compiler/modules.v
vlib/compiler/parser.v
vlib/vweb/tmpl/tmpl.v

compiler/vweb: update to get vweb working

compiler/vweb: update to get vweb working

---

vlib/builtin/builtin.v
vlib/builtin/builtin_nix.v
vlib/compiler/cgen.v

* support for backtarce on freebsd platform
* support for freebsd platform in vlang language

freebsd: backtrace support

---

vlib/compiler/comptime.v
vlib/compiler/fn.v
vlib/compiler/main.v
vlib/compiler/parser.v
vlib/vweb/tmpl/tmpl.v

compiler: vweb remove no longer needed vweb special cases& fix tmpl

compiler: vweb remove no longer needed vweb special cases& fix tmpl 

---

vlib/net/urllib/urllib.v

urllib: escape() return string() add .len for []byte, if not add it will get garbled string.

urllib: escape() return string() add .len

---

vlib/builtin/isnil_test.v
vlib/compiler/fn.v

I had to build v with itself to get isnil_test.v to pass.

compiler: allow function expecting a void* to receive a byteptr. Resolves #2905

---

vlib/builtin/bare/.checks/checks.v
vlib/builtin/bare/.checks/linuxsys/linuxsys.v
vlib/builtin/bare/array_bare.v
vlib/builtin/bare/linuxsys_bare.v
vlib/builtin/bare/mm_bare.v
vlib/builtin/bare/syscallwrapper_test.v
vlib/compiler/cc.v
vlib/compiler/cheaders.v
vlib/compiler/main.v

Also removed -lm and -lpthread from freestanding.

freestanding: Add array support (stack only for now). Add array read/write checks.

---

tools/vcreate.v

Add a user defined module to v create.

Update vcreate.v for sub module.

---

vlib/mysql/mysql.v

Sometimes we need to store it on a struct. So it will be good if we make it public

mysql: make the struct from private to pub & update some code

---

vlib/mysql/mysql.v

mysql: add error handling

---

vlib/compiler/cc.v
vlib/compiler/main.v
vlib/os/os.v

Adds support for the Haiku Operating System (part 2).

Adding support for Haiku Operating System (part 2)

---

vlib/compiler/cc.v

compiler: guess cc kind for -prod builds, to know when to add -flto .

---

vlib/builtin/bare/.checks/checks.v
vlib/builtin/bare/.checks/consts/consts.v
vlib/builtin/bare/builtin_bare.v
vlib/compiler/main.v
vlib/os/bare/bare.S

With this PR, v consts are initialized properly in -freestanding mode too.

freestanding mode: init consts

---

tools/gen_vc.v

tools: update gen_vc with -output-cross-platform-c

tools: update gen_vc with -output-cross-platform-c

---

tools/gen_vc.v

tools: gen_vc - fix regression with v compilation

tools: gen_vc - fix regression with v compilation

---

vlib/sdl/examples/tvintris/tvintris.v
vlib/sdl/image/image.v

This PR fixes all `vsdl2` references

Fix old vsdl2 references into sdl

---

vlib/os/os_test.v

This PR adds a test case for os.is_link() inside vlib/os/os_test.v .

add a test for os.is_link

---

vlib/sdl/examples/tvintris/tvintris.v

trivial changes to fix the missing else cases

Fix tvintris else cases

---

vlib/sdl/README.md

Add some troubleshooting instructions for brew users that have no working music in the tvintris demo.

update brew instructions for sdl dependencies

---

examples/game_of_life/life_gg.v
examples/hot_reload/bounce.v
examples/hot_reload/graph.v
examples/hot_reload/message.v
vlib/gg/gg.v
vlib/glm/glm.v

live: remove unused os/time references from existing hot reload programs

---

vlib/builtin/array_test.v
vlib/compiler/cflags.v
vlib/compiler/compile_errors.v
vlib/compiler/comptime.v
vlib/compiler/fn.v
vlib/compiler/table.v
vlib/compiler/tests/fn_expecting_ref_but_returning_struct_test.v
vlib/compiler/token.v
vlib/glm/glm.v

alternate fix, close this or fix 1
compiler: force custom struct .str() methods to be defined public
closes #3031

compiler: #3031 fix 2 - force custom struct .str() methods to be defined public

---

examples/vweb/vweb_example.v
vlib/strings/builder_c.v
vlib/vweb/vweb.v

I try to fix the issue #3050 
Test Case:
```
$ v run vweb_example.v
$ curl -X POST http://127.0.0.1:8082/text/
Hello world
```
thankyou!

live: fix vweb server will blocking while post request with not any form data

---

vlib/sdl/events.v
vlib/sdl/examples/basic_window/main.v
vlib/sdl/examples/tvintris/tvintris.v
vlib/sdl/sdl.v

- define and fill in the SDL event structs
- strongly type the event struct passed to SDL proper

Cleanup SDL event system

---

vlib/compiler/expression.v
vlib/compiler/table.v
vlib/compiler/tests/type_alias_test.v

```
type Myint int
pub fn (n Myint) str() string {
return int(n).str()
}
fn main() {
i := Myint(10)
ret := i + 100
println(ret.str())
}
```

Type alias

---

v.v
vlib/compiler/compiler_options.v

Fix a regression caused in 12ebed05897108ab7d81258e906cd4d7ddff080a .

compiler: restore ability to pass -prod option to run and runrepl.

---

vlib/builtin/array_test.v
vlib/compiler/expression.v
vlib/compiler/for.v
vlib/compiler/gen_c.v
vlib/compiler/parser.v

This PR let array can hold pointer type(*SomeSturct)!!
next can add FN type,and let map support it !!
```
fn main() {
mut arr := [] *int
i := 100
pi := &i
n := 1000
n3 := 10000
arr << pi
arr << &n
arr << &n3
for ii,var in arr {
print(ii)
print(' ')
println(*var)
}
for var in arr {
println(*var)
}
}
```

pointer_array

---

vlib/compiler/cc.v
vlib/os/os.v

Some fixes for compilation on freebsd systems (thanks to discord user pa3k).
Closes #3133 .

freebsd: fix compilation

---

vlib/compiler/parser.v
vlib/compiler/tests/fn_test.v

```
type MyFn fn (int) int
fn test(n int) int {
return n + 1000
}
struct MySt {
f MyFn
}
fn main() {
mut arr := []MyFn
arr << MyFn(test)
println(arr[0](10))
st := MySt{f:test}
println(st.f(10))
}
```

Fn type call

---

vlib/compiler/cgen.v
vlib/compiler/fn.v

This PR always generates a C dispatch table for each interface, even if none of its method is called.
Closes https://github.com/zenith391/vgtk3/issues/7 .

compiler: interface generation bugfix for not used interfaces

---

tools/performance_compare.v

Make tools/performance_compare.v more useful for comparing latest v versions.

tools: update tools/performance_compare.v to have more knowledge about v

---

vlib/mysql/mysql.v

add mysql -I flag for ubuntu 18.04

mysql: add -I flag for linux

---

vlib/compiler/cgen.v
vlib/compiler/expression.v
vlib/compiler/fn.v
vlib/compiler/gen_c.v
vlib/compiler/gen_js.v
vlib/compiler/get_type.v
vlib/compiler/main.v
vlib/compiler/parser.v
vlib/compiler/struct.v
vlib/compiler/table.v
vlib/compiler/tests/generic_test.v

[WIP] compiler: generic struct support

[needs cleanup] compiler: generic struct support

---

vlib/compiler/fn.v
vlib/compiler/parser.v
vlib/compiler/struct.v

compiler: generic structs add comments & initial cleanup

compiler: generic structs add comments & initial cleanup

---

vlib/builtin/hashmap.v

builtin/hashmap: use fnv1a32 as hash algo & make new/get/set methods public
I saw a 20ms speed increase just from changing the algo to fnv1a32 when using the hashmap with a lot of lookups for the new type system

builtin/hashmap: use fnv1a32 as hash algo & make new/get/set methods public

---

vlib/sqlite/readme.md

Update readme.md: add Ubuntu 20.04.

---

vlib/strconv/atof.v

**Motivation**
atof.v ==> A small fix for a possible bug for very small numbers near +zero approximation.

atof.v bug fix on +zero

---

vlib/builtin/array_test.v
vlib/builtin/map_test.v
vlib/compiler/compile_errors.v
vlib/compiler/comptime.v
vlib/compiler/expression.v
vlib/compiler/fn.v
vlib/compiler/for.v
vlib/compiler/gen_c.v
vlib/compiler/get_type.v
vlib/compiler/if_match.v
vlib/compiler/parser.v
vlib/compiler/struct.v
vlib/compiler/table.v
vlib/compiler/tests/option_test.v

support `map[string]&type` and `?&type` and `[]&type`
this pr allows to use `[][]&type` without error

compiler: map[string]pointer, ?pointer, fix []pointer

---

vlib/strings/strings_test.v

Check if string is empty if repeat counter is zero.
```v
pub fn repeat(c byte, n int) string {
if n <= 0 {
return '' // this branch was not tested
}
mut arr := [c].repeat(n + 1)
arr[n] = `\0`
return string(arr,n)
}
```

strings: extend tests

---

.editorconfig

This PR describes formally the editor settings used in the project, so that editors that support https://editorconfig.org/ can be automatically adjusted.

Add .editorconfig file at the top level of the project.

---

vlib/strconv/atoi_test.v

Added tests for `atoi` function in `strconv` module.

strconv: add tests for `atoi` function

---

Makefile

This PR fixes building V on Termux.

make: fix building on termux.

---

vlib/v/ast/ast.v
vlib/v/parser/parser.v
vlib/v/scanner/scanner.v
vlib/v/scanner/scanner_test.v
vlib/v/token/token.v

v: update parser / token & split parsing into methods

v: update parser / token & split parsing into methods

---

vlib/flag/flag.v

flag help message is now a bit more compact

---

tools/vpm.v
vlib/os/os.v

This PR implements all the 4 functions of vpm fully including dependency resolution:
**Install:**
Install was already implemented but it needed some improvements like dependency resolution and automatic update if module was already installed.
**Update:**
Update was fully implemented with dependency resolution. `v update` fetches all the modules in `.vmodules` dir and updates them.
**Search:**
Search is basically a scraper of `vpm.best` (The representation of the results can be improved maybe?)
**Remove:**
For remove I had to add `rmdir_recursive` and `is_dir_empty` functions in the os module.
**Notes:**
I also had to implement a hacky vmod file parser. It has no validation so a malformed v.mod file would also be parsed however it can be. This is of course only until someone implements a …

vpm: implement & improve install, search, update, remove

---

vlib/os/os.v

Sorry for the new pull request, I "accidentialy" deleted my forked repo
Please test @thecodrr, I don't own any mac computer.
* https://github.com/vlang/v/pull/2869

os: fix tmpdir on unix

---

tools/vfmt.v

This PR also ensures that all other vfmt worker output goes to stderr.

vfmt: ensure by default vfmt stdout is used *only* for the formatted source

---

README.md

Updates the estimated release date to match the current repository description.

Update release date in README.md

---

vlib/time/time_test.v

time_unix: add test for #3291

---

vlib/uiold/ui_windows.v

Update and rename ui_win.v to ui_windows.v

---

vlib/v/gen/tests/1.vv
vlib/v/parser/parser.v
vlib/v/token/token.v

v: try fix dot

---

vlib/compiler/expression.v
vlib/compiler/tests/type_test.v

compiler: implement direct cast for sum type

compiler: implement direct cast for sum type

---

vlib/pg/pg.v

Makes possible:
```v
db.exec_param_many(
'insert into modules (name, url, vcs) values ($1, $2, $3)', 
[name, url, vcs]
)
```

pg: add db.exec_param_many/2 .

---

vlib/v/parser/parser.v
vlib/v/table/table.v
vlib/v/types/types.v

v: small fixes typo & register struct & and add array elem pointer

v: small fixes typo & register struct & and add array elem pointer 

---

Makefile
vlib/builtin/builtin_nix.v
vlib/compiler/comptime.v
vlib/os/os.v
vlib/os/os_nix.v

android: fix os.create and builtin, so that v still use libc

---

vlib/v/ast/ast.v
vlib/v/gen/cgen.v
vlib/v/gen/jsgen.v
vlib/v/gen/tests/1.c
vlib/v/gen/tests/1.vv
vlib/v/parser/a_type.v
vlib/v/parser/fn.v
vlib/v/parser/parser.v
vlib/v/table/type.v
vlib/v/types/types.v

v: general cleanup & fixes. update variadic & multiple return parsing/ & gen

v: general cleanup & fixes. update variadic & multiple return parsing/ & gen

---

vlib/v/parser/a_type.v
vlib/v/parser/parser.v
vlib/v/table/table.v
vlib/v/types/types.v

v: initial type work for methods / struct fields

v: initial type work for methods / struct fields

---

.gitignore
tools/modules/scripting/scripting.v
tools/modules/vgit/vgit.v
tools/oldv.v
tools/performance_compare.v
tools/vtest-fmt.v
vlib/flag/flag.v
vlib/flag/flag_test.v

flag: fix flag parsing, when given conflicting -v and --v-xxx options
performance_compare: save several performance .json files
oldv: cleanup and fixes (extract common functionality with performance_compare)

tools: bugfixes and new features for oldv and performance_compare

---

vlib/builtin/builtin.v
vlib/builtin/cfns.v
vlib/compiler/cheaders.v
vlib/os/os.v

Now we are compatible up to Windows 2000 :)

windows: read console using ReadFile/ReadConsole

---

tools/vfmt.v
vlib/compiler/string_expression.v

This PR enables vfmt-ing of projects, that have many files at the top level folder, while still keeping the ability to format standalone programs, in the same folder (like in examples/ and tools/).

vfmt: support for vid like projects having many module main .v files

---

vlib/glfw/glfw.v
vlib/os/os.v
vlib/os/os_nix.v

This PR is needed so that the https://github.com/vlang/ui
file examples/users/users.v can be compiled and work on linux too.

ui: fixes so that the ui demo works on linux too

---

vlib/pg/pg.v

use defined password to connect.
what's the best way to test such change?

pg: connect, use password

---

vlib/net/http/http.v

Adds the methods DELETE, PUT, PATCH
DELETE function adds DELETE method for HTTP
```
pub fn delete(url string) ?Response {
req := new_request('DELETE', url, '') or {
return error(err)
}
res := req.do() or {
return error(err)
}
return res
}
```
PUT function adds PUT method for HTTP
```
pub fn put(url string) ?Response {
req := new_request('PUT', url, '') or {
return error(err)
}
res := req.do() or {
return error(err)
}
return res
}
```
PATCH function adds PATCH method for HTTP
```
pub fn patch(url string) ?Response {
req := new_request('PATCH', url, '') or {
return error(err)
}
res := req.do() or {
return error(err)
}
return res
}
``

http : Added PATCH, DELETE, and PUT methods

---

vlib/compiler/main.v

Fix, now ln fails silently using os.exec and grep runs silently

---

vlib/regex/README.md
vlib/regex/regex.v
vlib/regex/regex_test.v

**What is it**
It is an update for regex 0.9b
- "no greedy" flag for quantifier `{min.max}?`
- bytewise parsing (parse byte buffer ignoring utf-8 chars)
- new flags like "stop at newline"
- `README.md` with the first release of the doc for the module
- some small fix and optimizations

regex 0.9c

---

vlib/regex/README.md

Regex updated README.md, no code change

---

README.md

Ref https://github.com/vlang/ui/commit/a4eaf74c88853e3f88b1a7729150ec72cc0a7806.

readme: fix screenshot path

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/gen/cgen.v
vlib/v/parser/parser.v

v2: move array_init to checker

---

vlib/net/ftp/ftp.v

Fix on multiline control data, and using CRLF to be compatible with strict protocol ftp hosts.

protocol compatibility

---

vlib/freetype/freetype.v

high dpi text vertical positioning should now take scaling into account

freetype: cleanup calculation of text y position while drawing the text.

---

vlib/os/const.v
vlib/os/const_nix.v
vlib/os/const_windows.v
vlib/os/os.v
vlib/os/os_nix.v
vlib/os/os_test.v

This pull request adds a new 'open_file' function similar to Go. The open_file function takes in a path, flags (r, r+, w, w+, a, a+, etc) and permission octet.

OS: add open_file function

---

vlib/math/bits/bits.v

Some unnecessary brackets might be left over
**Please delete this information after reading it.*
Please title your PR as follows: `time: fix foo bar`. 
Always start with the thing you are fixing, then describe the fix.
```
fn foo() {
// file_test.v
...
}
```
Before submitting a PR, please:
A) run the tests with `v test-compiler` .
B) make sure, that V can still compile itself:
```shell
./v -o v v.v
./v -o v v.v
```
Applying labels to PRs is not …

math.bits: fix warnings regarding unnecessary casts

---

vlib/v/scanner/scanner.v

v2: fix bug in scanner, introduced in da9b639 (_ in num literals)

v2: fix bug in scanner, introduced in da9b639 (_ in num literals)

---

vlib/sokol/c/c.v

sokol: fix issue causing win test to fail introduced in 0502a54

sokol: fix issue causing win test to fail introduced in 0502a54

---

tools/modules/testing/common.v

tools: disable picoev test on windows

tools: skip pico example on windows (as no windows support yet)

---

vlib/builtin/string.v
vlib/builtin/string_test.v

string.split_nth - return the rest of the string as the last value in the result array

---

vlib/builtin/hashmap/hashmap.v
vlib/builtin/hashmap/hashmap_test.v

This is a very fast implementation of robin hood hashing. A lot of optimization are yet to be done. This replaces the old hashmap with a much faster and more memory efficient map.  This hashmap also has dynamic size unlike the old. Support for different types of values will be added shortly.

hashmap: new and fast hashmap with dynamic size

---

vlib/compiler/asm.v

<!--
Please title your PR as follows: `time: fix foo bar`. 
Always start with the thing you are fixing, then describe the fix.
```
fn foo() {
// file_test.v
...
}
```
Before submitting a PR, please:
A) run the tests with `v test-compiler` .
B) make sure, that V can still compile itself:
```shell
./v -o v v.v
./v -o v v.v
```
->

Update copyright year in asm.v

---

examples/fizz_buzz.v

This PR adds `examples/fizz_buzz.v` :smile:

examples: add fizz_buzz.v

---

vlib/gg/gg.v

```v
gg.draw_arc(x, y, r, start_angle, end_angle f32, segments int, color gx.Color)
```
start_angle and end_angle are in degrees.
Creates an array of verticies using `x: cos(angle), y: sin(angle)` then draws them using `draw_arrays(C.GL_LINE_STRIP)`

gg: added draw_arc

---

vlib/regex/README.md
vlib/regex/regex.v
vlib/regex/regex_test.v

**what is inside**
- named capturing groups
- no capturing groups
- small fixes to some bugs
- updated README.md

Regex 0.9d

---

vlib/hash/wyhash/wyhash.v

wyhash: update benchmark file location in comment

wyhash: update benchmark file location in comment

---

vlib/gg/gg.v

```v
draw_filled_arc(x, y, r, start_angle, end_angle f32, segments int, color gx.Color)
draw_circle(x, y, r f32, color gx.Color)
```
Change draw mode:
```v
set_mode_wireframe()
set_mode_point()
set_mode_fill()
```

gg: filled arcs and circles

---

examples/linear_regression/.gitignore
examples/linear_regression/simple_linear_regression.v

Simple example for Linear Regression
<!--
Please title your PR as follows: `time: fix foo bar`. 
Always start with the thing you are fixing, then describe the fix.
```
fn foo() {
// file_test.v
...
}
```
Before submitting a PR, please:
A) run the tests with `v test-compiler` .
B) make sure, that V can still compile itself:
```shell
./v -o v v.v
./v -o v v.v
```
->

simple linear regression example

---

vlib/gg/gg.v
vlib/gg/utils.v

```v
draw_rounded_rect(x, y, w, h, r f32, color gx.Color)
```
Implemented rounded rectangles and cleaned up gg.v a bit by adding some reusable functions.

gg: roundrects

---

vlib/os/os.v

The current readlines implementation is buggy and duplicates some code, 
```
import os
fn main() {
mut len := 0
for i := 0; i < 200 ; i++  {
lines := os.read_lines('/etc/services') or {
panic(err)
}
len = lines.len
}
eprintln('$len')
}
```
There's a small performance degradation:
* Before: 1.6s
* Using .split('\n') = 3.2s
* Using .split_into_lines() = 1.8s
So my feeling is:
* the simpler the better
* we should optimize split('\n') to be as fast as split_into_lines

Simplify os.read_lines()

---

vlib/compiler/enum.v
vlib/compiler/tests/enum_test.v

<!--
Please title your PR as follows: `time: fix foo bar`. 
Always start with the thing you are fixing, then describe the fix.
```
fn foo() {
// file_test.v
...
}
```
Before submitting a PR, please:
A) run the tests with `v test-compiler` .
B) make sure, that V can still compile itself:
```shell
./v -o v v.v
./v -o v v.v
```
->

Resolve optional enum type

---

vlib/crypto/rand/rand_linux.v
vlib/crypto/rand/utils.v

crypto.rand: utils - update slice method to slice syntax & fix typo in error

crypto.rand: utils - update slice method to slice syntax & fix typo in error

---

vlib/hash/wyhash/rand.v
vlib/hash/wyhash/wyhash_test.v

hash.wyhash: implement rand function from wyhash original impl

hash.wyhash: implement rand function from wyhash original impl

---

vlib/compiler/aparser.v
vlib/compiler/main.v
vlib/v/ast/ast.v
vlib/v/builder/builder.v
vlib/v/builder/modules.v
vlib/v/builder/prefs.v
vlib/v/checker/checker.v
vlib/v/gen/cgen_test.v
vlib/v/gen/tests/1.vv
vlib/v/parser/parser.v

v2: initial module support

---

tools/gen_vc.v

tools: gen_vc - update to show subject in commit message

tools: gen_vc - update to show subject in commit message

---

vlib/strings/similarity.v
vlib/strings/similarity_test.v

strings: fix bug in levenshtein distance & add tests. closes #3630

strings: fix bug in levenshtein distance & add tests. closes #3630

---

vlib/glfw/glfw.v

vui need window resize event. add set resize callback method, so I can add resize process in vui.

glfw: window add set resize callback method

---

vlib/builtin/int.v
vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/gen/cgen_test.v
vlib/v/gen/tests/4.c
vlib/v/gen/tests/4.vv
vlib/v/parser/fn.v
vlib/v/parser/parser.v
vlib/v/table/table.v

v2: resolve unresolved call expression types & add test

v2: resolve unresolved call expression types & add test

---

tools/gen_vc.v
vlib/time/time.v
vlib/time/time_test.v

time: return optional value in `parse` and `parse_iso` functions

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/gen/cgen.v
vlib/v/gen/cgen_test.v
vlib/v/gen/jsgen.v
vlib/v/gen/tests/1.vv
vlib/v/gen/tests/4.c
vlib/v/gen/tests/4.vv
vlib/v/parser/fn.v
vlib/v/parser/parse_type.v
vlib/v/parser/parser.v
vlib/v/table/atypes.v
vlib/v/table/table.v

v2: use pointer to table.type, fix unresoved array subtype. fix cgen test windows

v2: use pointer to table.type, fix unresolved array/map sub-types. fix cgen test windows

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/gen/cgen.v
vlib/v/gen/jsgen.v
vlib/v/gen/tests/4.c
vlib/v/gen/tests/4.vv
vlib/v/gen/x64/gen.v
vlib/v/parser/parser.v
vlib/v/table/atypes.v

v2: start impl multi assign, (skip multi return for now) & add some casting helper fns

v2: start impl multi assign, (skip multi return for now) & add some casting helper fns

---

vlib/v/builder/builder.v
vlib/v/checker/checker.v
vlib/v/parser/parser.v
vlib/v/table/table.v

v2: checker & unresolved fixes & small updates

v2: checker & unresolved fixes & small updates

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/gen/cgen.v
vlib/v/parser/fn.v
vlib/v/parser/parse_type.v
vlib/v/parser/parser.v
vlib/v/table/atypes.v
vlib/v/table/table.v

v2: lots of small fixes parent method/field resolution & simplify variadic

v2: lots of small fixes parent method/field resolution & simplify variadic

---

vlib/v/parser/parser.v

v2: restore important line that I removed by accident for expr resolving

---

vlib/v/checker/checker.v
vlib/v/parser/parse_type.v
vlib/v/parser/parser.v
vlib/v/table/atypes.v
vlib/v/table/table.v

v2: map / string / builtin type fixes

---

doc/docs.md

This PR translates changes to docs.html to Markdown, 
as discussed in https://github.com/vlang/website/pull/128

Add tips for C/V interoperability to doc/docs.md too.

---

README.md

readme: update selfcompile instruction

---

.github/PULL_REQUEST_TEMPLATE

PR template: update selfcompile instruction

---

vlib/math/bits/bits_test.v

Renamed the functions as Joe tell to me in the closed PR.

renamed test bits functions

---

Makefile

Related to https://github.com/vlang/v/issues/3500
PD: this is a blind fix, i dont have any freebsd machine here to test. but i can use the PR for testing it in https://builds.sr.ht . feel free to review or test.

Fix #3500 - build on FreeBSD

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/parser/parse_type.v
vlib/v/parser/parser.v
vlib/v/table/atype_symbols.v
vlib/v/table/table.v

v2: fix array index, for loop, add cast expr & other minor fixes

v2: fix array index, for loop, add cast expr & other minor fixes

---

.gitignore
vlib/os/os.v

os: typo in wait function

---

vlib/v/gen/tests/4.c
vlib/v/gen/tests/4.vv
vlib/v/parser/parser.v

v2: make index_expr return array array element type

v2: make index_expr return array array element type

---

.github/workflows/periodic.yml

Ref https://github.com/vlang/v/actions/runs/38150240.
Also, I noticed periodic task fails on macOS job. This PR **does not** fix that issue.

ci: fix complilation in periodic workflow

---

cmd/tools/vcreate.v

1.optimizing file content process
2.fix prompt
3.early judge folder is exist

vcreate: optimize and fix

---

vlib/v/ast/ast.v
vlib/v/ast/scope.v
vlib/v/builder/builder.v
vlib/v/checker/checker.v
vlib/v/gen/tests/1.c
vlib/v/gen/x64/gen.v
vlib/v/parser/fn.v
vlib/v/parser/parse_type.v
vlib/v/parser/parser.v
vlib/v/parser/parser_test.v
vlib/v/scanner/scanner.v
vlib/v/table/table.v
vlib/v/token/position.v
vlib/v/token/token.v

v2: remove unresolved types, handle types in checker stage when known. add scope class

v2: remove unresolved types, handle types in checker stage when known. add scope struct

---

vlib/v/parser/parse_type.v
vlib/v/parser/parser.v

v2: update parse type not to prefix builtin types with module

v2: update parse type not to prefix builtin types with module

---

vlib/v/ast/ast.v
vlib/v/ast/scope.v
vlib/v/builder/builder.v
vlib/v/checker/checker.v
vlib/v/parser/parser.v
vlib/v/parser/parser_test.v

v2: move more type handling to checker (unresovled idents) & some clean up

v2: move more type handling to checker (unresovled idents) & some clean up

---

vlib/os/os.v

windows: use %USERPROFILE% for os.home_dir()

---

vlib/compiler/aparser.v
vlib/v/gen/cgen.v
vlib/v/gen/tests/1.c
vlib/v/parser/parser.v
vlib/v/table/table.v

v2: cleanup old & unused code, add new simple tmp vars in cgen

v2: cleanup old & unused code, add new simple tmp vars in cgen

---

vlib/compiler/cheaders.v

This is an extremely fast hash-function created by the author of wyhash. It will be used in the hashmap if it is not too insecure.

Add FastestHash to cheaders.v

---

cmd/tools/vrepl.v

There are also a couple minor formatting fixes.

vrepl.v: Added newline on REPL exit

---

vlib/sokol/gfx/enums.v
vlib/sokol/gfx/gfx.v
vlib/sokol/gfx/gfx_funcs.v
vlib/sokol/gfx/gfx_structs.v
vlib/sokol/sapp/enums.v
vlib/sokol/sapp/sapp.v
vlib/sokol/sapp/sapp_funcs.v
vlib/sokol/sapp/sapp_structs.v

fix the missing msg argument

---

vlib/compiler/tests/typeof_test.v

add typeof test for fn

---

vlib/compiler/scanner.v
vlib/v/scanner/scanner.v

This PR simply does pure logic code simplification and unifies code style.

scanner: pure logic code simplification and unify style

---

vlib/math/math.v

This is a trivial change to add math.powf() and other float32 math functions

math: add powf and other float32 functions

---

examples/quick_sort.v

I noticed there was no example of sorting so add this.
I believe this is a nice example to quickly catch the point of V. 
I was going to write it with generics, but then found recursive generics had a bug (see #3782), so had to gave it up.

examples: add quick_sort example

---

vlib/v/doc/doc.v

This PR adds a new method `Doc.get_fn_signatures` returns a list of function signatures. The method takes a filter function as an argument; the filter function should check if a given `FnDecl` satisfies certain requirements, and should return a boolean value.
This approach allows to reduce code duplication: we can get a list of function signatures using the only `Doc.get_fn_signatures` method combined with filters.
Also I renamed local variables for consistency and for better readability (`fn_names` array contains not function names, but function signatures).

vdoc: remove duplicated code

---

vlib/v/parser/parser.v
vlib/v/scanner/scanner.v

the old code just check BOM only in scanner,new code check both scanner and parser.

make sure scanner and parser both check BOM

---

vlib/compiler/fn.v

This PR fix interface bug that do not distinguish between operating systems.
V UI crash on linux is just interface usage error, it will work if corrected interface usage.

Fix interface on all platform

---

vlib/builtin/builtin_nix.v
vlib/builtin/int.v
vlib/builtin/map.v
vlib/math/bits/bits.v
vlib/strconv/ftoa/utilities.v

PR to fix as much (linux) warnings in C code generated by V (using external compilation of tvintris as a vehicle)

Fix linux warnings in generated C code

---

vlib/v/fmt/tests/simple_expected.vv
vlib/v/fmt/tests/simple_input.vv

Ref https://github.com/vlang/v/pull/3869#issuecomment-592418912.

fmt: add function with variadic arg to test file

---

vlib/v/doc/doc.v

doc: don't modify path to vlib

---

vlib/sdl/README.md

- Add actual instructions for Windows
- Capitalize sentences
- Fix path to tVintris screenshot
- Fix list of contributors
- Remove spaces before colons
- Use proper header levels

sdl: update readme

---

vlib/v/fmt/tests/simple_expected.vv
vlib/v/fmt/tests/simple_input.vv

Ref https://github.com/vlang/v/pull/3945#issuecomment-595967284.

fmt: fix errors in test files

---

cmd/tools/vfmt.v
vlib/compiler/main.v
vlib/compiler/modules.v
vlib/compiler/v_mod_cache.v
vlib/freetype/freetype.v
vlib/log/log.v
vlib/os/os.v
vlib/os/os_test.v

This PR change `os.basedir` to `os.base_dir` like `home_dir` similar to Vlang style.

os api: basedir => base_dir

---

vlib/compiler/tests/repl/repl_test.v
vlib/os/os.v

This PR change `os.cachedir` to `os.cache_dir` like `os.home_dir` similar to Vlang style.

os api: cachedir => cache_dir

---

cmd/tools/gen_vc.v

Fixes vc generation by cmd/tools/gen_vc.v .
vc generation stopped at aab31f4 .

Fix cmd/tools/gen_vc.v, use -os cross .

---

doc/docs.md

Now that [shebangs are supported](https://github.com/vlang/v/pull/1304), I thought it would be useful to document them. Note that I haven't tested these changes yet.

doc: improve the cross-platform shell scripts documentation

---

vlib/pg/readme.md

Create readme.md: install needed softwares first.

---

vlib/builtin/array.v

builtin: implement []int.str() .

---

vlib/compiler/fn.v
vlib/compiler/tests/interface_test.v

This PR fix interface bug #3979 and add test in interface_test.v.

interface: fix interface bug #3979

---

cmd/tools/vfmt.v
vlib/compiler/cgen.v

Better NetBSD and OpenBSD support in vfmt and filename $if

---

vlib/v/ast/ast.v

make ast.ReturnStmt field public

make ast.ReturnStmt field public

---

cmd/tools/modules/testing/common.v
cmd/tools/oldv.v
cmd/tools/performance_compare.v
cmd/tools/preludes/tests_with_stats.v
cmd/tools/vbin2v.v
cmd/tools/vcreate.v
cmd/tools/vfmt.v
cmd/tools/vnames.v
vlib/compiler/aparser.v
vlib/compiler/live.v
vlib/compiler/tests/repl/runner/runner.v
vlib/compiler/vtmp.v
vlib/log/log.v
vlib/os/os.v
vlib/v/fmt/fmt_keep_test.v
vlib/v/fmt/fmt_test.v
vlib/v/pref/default.v

This PR change `os.filename` to `os.file_name` like `os.file_size` similar to Vlang style.

os api: filename => file_name

---

vlib/compiler/cflags.v
vlib/time/time_nix.v

This PR improves support for _solaris.v and #flag solaris .

solaris: _solaris.v and #flag solaris (stage 1)

---

vlib/flag/flag.v
vlib/flag/flag_test.v

This PR change all `666` to `0o666` in flag_test.v for unify octal digital format.

flag_test.v: 666 => 0o666

---

vlib/builtin/map.v

map: small cleanup

---

vlib/builtin/int.v

int to str/hex function without buffer offset.

int to str without offset buffer

---

vlib/v/gen/cgen.v
vlib/v/gen/cgen_test.v
vlib/v/gen/tests/1.c
vlib/v/gen/tests/2.c
vlib/v/gen/tests/3.c
vlib/v/gen/tests/4.c

This PR enables compilation of hello world (builtin) with tcc.
```c
strconv__ftoa__pow5_split_64 = new_array_from_c_array(326, 326,
sizeof(strconv__ftoa__Uint128), (strconv__ftoa__Uint128[]){
```
=> 
```c
strconv__ftoa__pow5_split_64 = new_array_from_c_array(326, 326,
sizeof(strconv__ftoa__Uint128), (strconv__ftoa__Uint128[326]){
```

v2: fix hello world compilation with tcc

---

examples/tcp_echo_server.v

This PR demonstrates how to implement a basic tcp service in V, using
the net module.

examples: add a simple self contained tcp echo server.

---

vlib/glfw/glfw.v

This PR fix glfw compile error.
This compilation error should be a problem with the compiler, this is a temporary solution.

glfw: fix compile error

---

vlib/term/term_nix.v
vlib/term/term_solaris.v

android: fix building in termux

---

.gitignore
cmd/tools/modules/testing/common.v
vlib/term/term_nix.v
vlib/term/term_solaris.v
vlib/v/tests/live_test.v

This PR fixes the SmartOS/Solaris build, while keeping termux building
too.

solaris & termux: fix both, using the more portable termios.h

---

vlib/v/scanner/scanner.v

This PR optimize vlib/v/scanner/scanner.v.
**Before**
```v
fn is_name_char(c byte) bool {
return c == `_` || c.is_letter()
}
```
**Change**
```v
[inline]
fn is_name_char(c byte) bool {
return (c >= `a` && c <= `z`) || (c >= `A` && c <= `Z`) || c == `_`
}
```
It's the same as /compiler/scanner.v, can improve processing efficiency.

scanner.v: optimize vlib/v/scanner/scanner.v

---

examples/mini_calculator.v

This is a mini "home-made" calculator. You may also regard it as a very elementary version of "interpreter".

example: add example mini_calculator

---

vlib/v/scanner/scanner.v

This PR optimize vlib/v/scanner/scanner.v.
- Put const definitions all in front.
```v
const (
single_quote = `\'`
double_quote = `"`
error_context_before = 2 // how many lines of source context to print before the pointer line
error_context_after = 2 // ^^^ same, but after
is_fmt = os.getenv('VEXE').contains('vfmt')
num_sep = `_` // char used as number separator
)
```
- Change `scan_res` to `new_token`, what the function means is so clearer.
```v
fn (s &Scanner) new_token(tok_kind token.Kind, lit string) token.Token {
return token.Token{
kind: tok_kind
lit: lit
line_nr: s.line_nr + 1
pos: s.pos
}
}
```

scanner: minor optimizations

---

vlib/builtin/array.v
vlib/builtin/builtin_windows.v
vlib/builtin/map.v
vlib/builtin/sorted_map.v

VC doesn't allow pointer arithmetic on void pointers, so we should to convert them.

array, map: cast voidptr to byteptr

---

vlib/builtin/string.v
vlib/readline/readline_linux.v

This PR enables v2 compilation of cmd/tools/vrepl.v .
It works if you give it complete V programs like
`fn main(){println(2+2)}`
but not for single expressions like 2+2 or statements like a:='abc'

v2: compile vrepl, 'fn main(){println(2+2)}' runs now.

---

vlib/builtin/int_test.v

Ref https://github.com/vlang/v/issues/3376#issuecomment-573315986.

builtin: add operator precendence test

---

vlib/sync/sync_windows.v

This PR brings back `v test` on Windows.

sync: fix build on Windows

---

vlib/v/scanner/scanner.v

This PR optimize scan() in scanner.v.
**Before**
```v
mut nextc := `\0`
if s.pos + 1 < s.text.len {
nextc = s.text[s.pos + 1]
}
```
**Change**
```v
nextc := if s.pos + 1 < s.text.len { s.text[s.pos + 1] } else { `\0` }
```
No need to use mut type.

scanner: minor optimization

---

vlib/rand/rand.v
vlib/rand/rand_test.v

Fixes #4199.
- Fixed build.
- Simplified tests.
- Added a test for `rand_r` to check if a seed is updated.

rand: update module

---

vlib/v/eval/eval.v
vlib/v/parser/parser_test.v

This PR fix `new_checker` argument incomplete issue.

checker: fix new_checker argument incomplete issue

---

vlib/v/gen/cgen.v

fixes #4169. The code example there now produces the output `[4, 8, 12, 16, 20, 24, 28, 32, 36, 40]`.

foreach loops: fix assignments to mutable arrays

---

vlib/clipboard/clipboard_windows.v

```
$ v test vlib\clipboard
----------------------------------- Testing... ---------------------------------
OK     1125 ms [1/1] vlib\clipboard\clipboard_test.v
--------------------------------------------------------------------------------
1125 ms <=== total time spent running V _test.v files
ok, fail, skip, total =     1,     0,     0,     1
```

clipboard: fix build on Windows

---

vlib/bitfield/bitfield.v
vlib/bitfield/bitfield_test.v

- Converted module functions to methods
- Inlined internal functions
- Updated documentation
Keep consistent style of doc comments.

bitfield: update module

---

vlib/v/ast/ast.v

ast:pub interface field

---

vlib/builtin/map.v

This should fix the mem-leaks of the map.

map: fix mem-leak

---

vlib/v/checker/checker.v

It is no longer possible to add duplicate fields to a struct for this PR.
Example code that it now handles correctly:
```
module main
struct Sample {
a string
b int
}
fn main() {
// Shouldn't be allowed but is allowed
c := Sample {
a: '',
a: ''
}
println(c)
// Outright crashes the compiler
d := Sample {
a: '',
a: '',
b: 3
}
println(d)
}
```

vlib/v/checker: Make struct_init check more robust

---

cmd/tools/vself.v
cmd/tools/vup.v
vlib/v/util/util.v

this issue shows correct errors when the user has no privileges to `v up`, `v self` or compile a command line tool in v (`cmd/tools`).
I hope it works...

cmd: show correct messages when user can't compile a tool or v itself

---

cmd/tools/vcreate.v
cmd/v/internal/help/default.txt
cmd/v/v.v

Changed 'v create' -> 'v new'

---

vlib/v/gen/cgen.v

```
'${true}' => prints: true instead of 1
```

cgen: print bool correctly in interpolation

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/consts_expected.vv
vlib/v/fmt/tests/consts_input.vv

fmt: align consts

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/fmt/fmt.v
vlib/v/gen/cgen.v
vlib/v/parser/parser.v

it checks that the default expressions are IntegerLiterals.

checker: check enum

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/parser/parser.v
vlib/v/scanner/scanner.v
vlib/v/token/position.v
vlib/v/token/token.v
vlib/v/util/errors.v

```
abc.v:5:10: error: undefined: `hello` 
3| 
4| fn main() {
5|     println(hello)
~~~~~
6| }
```

scanner: even better error messages

---

.gitignore
vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/checker/tests/inout/checker_error_test.v
vlib/v/checker/tests/inout/enum_err.out
vlib/v/checker/tests/inout/enum_err.vv
vlib/v/parser/parser.v
vlib/v/util/errors.v

fixes the "too many ~" bug.
adds some tests for checker errors
add string position

checker: fix error messages

---

vlib/v/checker/checker.v
vlib/v/checker/tests/inout/void_fn_as_value.out
vlib/v/checker/tests/inout/void_fn_as_value.vv
vlib/v/checker/tests/inout/void_function_assign_to_string.out
vlib/v/parser/fn.v
vlib/v/parser/parser.v

```
vlib/v/checker/tests/inout/void_fn_as_value.v:5:8: error: unknown fn: x
3| fn main() {
4|   mut a := 'aa'
5|   a += x('a','b')
~~~~~~~~~~
6|   mut b := 'abcdef'
7| }
```

parser: fix void assign check

---

cmd/tools/vfmt.v
vlib/v/ast/ast.v
vlib/v/ast/str.v
vlib/v/fmt/fmt.v
vlib/v/gen/cgen.v
vlib/v/parser/parser.v
vlib/v/table/atypes.v
vlib/v/tests/enum_default_value_in_struct_test.v

parser: fix enum default value in struct

---

vlib/v/gen/cgen.v
vlib/v/tests/inout/string_interp.out
vlib/v/tests/inout/string_interp.vv
vlib/v/tests/string_interpolation_test.v

cgen: % escape in c

---

vlib/v/gen/cgen.v

cgen: fix !in not working with maps

---

README.md

To use the Discord badge a Discord server admin must enable the widget setting on the server.

readme: nicer look

---

vlib/v/tests/type_alias_test.v

```
type X = int
type Y = f32
type Z = f64
```

tests: add new type alias syntax tests

---

cmd/tools/vup.v

Checks if git log contains "master is up to date" string and returns early if it does.

Closes #4285

---

vlib/v/checker/checker.v

checker: match exhaustive as stmt and with enum

---

CONTRIBUTING.md

This PR fixes CONTRIBUTING.md typos.

doc: fix CONTRIBUTING.md typos

---

vlib/v/gen/js/js.v

jsgen: selector expressions

---

vlib/v/checker/checker.v
vlib/v/gen/fn.v
vlib/v/tests/fn_test.v

checker/cgen: fix calling struct field with fn type

checker/cgen: fix calling struct field with fn type

---

cmd/v/v.v

Though about this simplification after my https://github.com/vlang/v/pull/4414 was merged

Simplify v run

---

doc/docs.md

Update docs.md Uniform 'var' keywords

---

cmd/tools/vtest-fixed.v
vlib/cli/command.v
vlib/cli/flag_test.v

Fix cli module.
Enables tests in test-fixed command.

cli: fix command and tests

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/checker/tests/inout/short_struct_too_many.out
vlib/v/checker/tests/inout/short_struct_too_many.vv
vlib/v/checker/tests/inout/struct_unknown_field.out
vlib/v/checker/tests/inout/struct_unknown_field.vv
vlib/v/fmt/fmt.v
vlib/v/gen/cgen.v
vlib/v/gen/js/js.v
vlib/v/parser/parser.v

some hours of work. thanks...
```
vlib/v/checker/tests/inout/struct_unknown_field.v:8:9: error: struct init: no such field `bar` for struct `Test`
6|     t := Test{
7|         foo: true
8|         bar: false
^
9|     }
10| }
```

refactor: error unknown struct field

---

vlib/v/checker/checker.v
vlib/v/parser/fn.v

Might be a good idea to enforce consistency here since this doesn't seem to be useful

checker: disallow pub fn main()

---

vlib/v/parser/parser.v

This PR fix number parse error: Fix #4448.

parser: fix number parse error

---

cmd/tools/modules/testing/common.v

There was a race condition in displaying and modifying testing messages. Fixes issue #4475

testing: Fix race condition, made messages private

---

vlib/v/scanner/scanner.v

This PR refactors ident_dec_number function (also adds more comments) so it's easier to understand.
A by-product is fixing range `5a..10`. After this PR it results in an error.

scanner: refactor ident_dec_number and fix 5a..10 

---

vlib/v/tests/string_interpolation_test.v

string: add more interpolation tests

---

doc/docs.md

Looks like a typo anyway, unless I'm missing something ...

docs: fix typo

---

vlib/v/table/cflags.v
vlib/v/table/cflags_test.v

tests: test cflags parsing

---

cmd/tools/vfmt.v
vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/checker/tests/inout/checker_error_test.v
vlib/v/checker/tests/inout/no_pub_in_main.out
vlib/v/checker/tests/inout/no_pub_in_main.vv
vlib/v/checker/tests/inout/pub_fn_main.out
vlib/v/checker/tests/inout/pub_fn_main.vv
vlib/v/parser/fn.v
vlib/v/parser/parser.v
vlib/v/parser/struct.v
vlib/v/token/position.v

Add pos to EnumDecl and TypeDecl.
Warn if a declaration is public in the main module.

checker: disallow pub in main

---

vlib/v/gen/cgen.v
vlib/v/tests/struct_test.v

This PR fixes at least two issues related to struct initialization. See linked issues for details.
Added test cases from issues linked to this PR.

cgen: fix struct initialization

---

vlib/v/checker/tests/inout/checker_error_test.v

This PR enable checker error tests on Windows and fix bug.

checker_error_test: enable test on windows and fix bug.

---

cmd/tools/vrepl.v

This PR fix vrepl.v error (fix #4485 fix #4502).

repl: fix vrepl.v error (fix #4485)

---

vlib/strconv/ftoa/f32_str.v
vlib/strconv/ftoa/f64_str.v

- fix to rounding of `f32` and `f64`
- new utility functions for float to string conversions
- some code for `sprintf`

ftoa: some fixes for rounding, added new functions

---

vlib/v/parser/for.v

Should cover the other cases now, tell me if I missed something

 parser: disallow for i in i (fixed)

---

cmd/tools/vup.v

vup: fix unnecessary recompiles

---

cmd/tools/vtest-fixed.v
vlib/builtin/bare/linuxsys_bare.v
vlib/builtin/bare/mm_bare.v
vlib/v/gen/cgen.v
vlib/v/gen/cheaders.v
vlib/v/gen/js/js.v
vlib/v/tests/option_test.v

gen: fix optional pointers

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/optional.vv
vlib/v/fmt/tests/optional_keep.vv
vlib/v/table/atypes.v

fmt: fix optional formatting

---

examples/path_tracing.v
vlib/clipboard/clipboard_linux.c.v
vlib/net/websocket/ws.v
vlib/regex/regex.v
vlib/v/gen/js/tests/js.v

This PR fix `enum` syntax error.
- V2 does not allow commas between items.

enum: fix enum syntax error

---

doc/docs.md

See https://github.com/vlang/v/issues/4520 .

documentation: fix misleading description of optionals

---

cmd/tools/vup.v

Previous vup fix left out crucial extension.  Adding it here so vup actually gets compiled.

vup: add missing extension to make it work

---

vlib/v/tests/inout/compiler_test.v

This PR enable vlib/v/tests/inout/compiler_test.v on Windows.

test: enable vlib/v/tests/inout/compiler_test.v on Windows

---

vlib/v/gen/cgen.v
vlib/v/tests/fixed_array_to_string_test.v

This PR add `gen_str_for_array_fixed`.
- Add `gen_str_for_array_fixed`.
- Add tests `fixed_array_to_string_test.v`.

cgen: add gen_str_for_array_fixed

---

vlib/net/websocket/handshake.v
vlib/net/websocket/ssl.v
vlib/net/websocket/utf8.v
vlib/net/websocket/utils.v
vlib/net/websocket/ws.v

websocket: update to work with latest V

---

vlib/v/ast/ast.v
vlib/v/ast/str.v
vlib/v/builder/x64.v
vlib/v/checker/tests/inout/checker_error_test.v
vlib/v/doc/doc.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/types_expected.vv
vlib/v/fmt/tests/types_input.vv
vlib/v/gen/json.v
vlib/v/table/atypes.v

Sort sum types.
Handle FnTypeDecl.
Format more files in V compiler.

fmt: TypeDecl

---

vlib/freetype/freetype.v
vlib/gg/gg.v
vlib/gg/utils.v
vlib/math/math.v

fix a few warnings

---

vlib/strconv/format.v
vlib/strconv/format_test.v

- fix for the tests
- some small fixes

strconv: fix on the tests, now platform independent

---

examples/fetch.v
vlib/net/http/http.v

made Request pub items mutable
Added an example of usage

http: mutable request

---

vlib/strconv/format.md

- first release of the `v_printf` documentation

strconv: v_printf documentation

---

vlib/cli/flag.v

cli: add option with default to flag get

---

vlib/v/util/errors.v

before:
after:
The color is the same as GCC.

parser: print warnings in magenta

---

README.md

Readme.md 0.2 realease date bump

---

vlib/v/gen/fn.v

Since GitHub won't let me reopen #4670

cgen: generate static C functions

---

vlib/v/gen/cgen.v
vlib/v/tests/interface_test.v

Fix using pointers in struct implementing interfaces.

gen: fix using pointer as interface receiver

---

doc/docs.md

doc: fix wording for "return none"

---

doc/docs.md

My previous PR had a typo :cry:.

doc: fix wording for "return none" part 2

---

vlib/v/tests/interface_test.v

Hi,
as requested by @medvednikov  I propose a simple PR with some changes in interface test; there is even a sample usage of the `typeof` that could be useful here, to get automatically struct name.
Tests passes.
Tell me if you need more info.
Bye

add another function to the Animal interface

---

vlib/v/tests/interface_test.v

Hi all, in agreement with @medvednikov I add here another small block of code to play with interfaces and structs, mainly to use as a sample (I think it could be useful).
Hope it's good. Bye

interface test, add 'str' function to some structs and interfaces

---

vlib/v/checker/checker.v
vlib/v/checker/tests/no_main_mod.out
vlib/v/checker/tests/no_main_mod.vv

checker: verify that there is a main module

---

vlib/mysql/result.v

Also refactor `Row` field name & add some doc. Make sense to rename it to `cols`, because it's  a column.

mysql: Simplify `Result.maps`

---

doc/docs.md

I fixed broken example on document.

doc: fix wrong syntax

---

vlib/v/checker/checker.v
vlib/v/checker/tests/unimplemented_interface_a.out
vlib/v/checker/tests/unimplemented_interface_a.vv
vlib/v/checker/tests/unimplemented_interface_b.out
vlib/v/checker/tests/unimplemented_interface_b.vv
vlib/v/checker/tests/unimplemented_interface_c.out
vlib/v/checker/tests/unimplemented_interface_c.vv
vlib/v/checker/tests/unimplemented_interface_d.out
vlib/v/checker/tests/unimplemented_interface_d.vv
vlib/v/checker/tests/unimplemented_interface_e.out
vlib/v/checker/tests/unimplemented_interface_e.vv
vlib/v/checker/tests/unimplemented_interface_f.out
vlib/v/checker/tests/unimplemented_interface_f.vv
vlib/v/checker/tests/unimplemented_interface_g.out
vlib/v/checker/tests/unimplemented_interface_g.vv
vlib/v/table/atypes.v
vlib/v/table/table.v
vlib/v/tests/interface_test.v

Checks that types implement the interface.
This PR assumes that interfaces can't have methods, like `Animal` use to do in `interface_test.v`.
If they can, then some changes will be necessary, as well as an explanation of the expected behavior :sweat_smile:

Check interface implementation

---

vlib/v/parser/parser.v

This PR simplify import statement process.

parser: simplify import statement process

---

vlib/bitfield/bitfield.v
vlib/bitfield/bitfield_test.v

bitfield: Rename function names

---

doc/docs.md

Improved the clarity of docs.md

---

doc/docs.md

Update documentation on iterators.

---

vlib/v/checker/checker.v
vlib/v/checker/tests/no_interface_receiver.out

Hi, this is a fix for a typo in an error message and related test.
Bye

fix typo on error message, and related test

---

cmd/tools/vpm.v

vpm: Fix error message

---

vlib/builtin/map.v

Just slightly faster `get` and `exists`-methods.

map: faster get and exists

---

vlib/v/util/errors.v

compiler: print underlines in the same color as the error

---

CHANGELOG.md

This PR fix typo of changelog.md.

doc: fix typo of changelog.md

---

vlib/math/fractions/fraction.v
vlib/math/fractions/fraction_test.v

Briefly, here are the changes:
1. Added strict guarantees to the Fractions created using the factory function.
2. Added an `is_reduced` field to the struct to enable quicker returns from `reduce()`
3. Completely reworked arithmetic to be safe from overflows (as much as possible for `i64`s)
4. Deprecated named arithmetic functions: prefer overloaded functions
5. Added comparison functions for `ge`, `gt`, `le` and `lt`.
6. Completely reworked tests
1. long functions split into smaller ones. Max 1 or 2 asserts per test
2. added tests to check possible overflow cases
3. added tests for comparison checking

math.fractions: Overhaul fractions.v; refactor and add more tests

---

vlib/os/os.v
vlib/v/gen/cgen.v
vlib/v/gen/cheaders.v

C++ compiler support - Part 1

---

cmd/tools/vrepl.v
vlib/v/tests/repl/error.repl

Add a final newline to fix columns in the repl error messages

repl: fix error messages

---

vlib/v/scanner/scanner.v

scanner: add a colon to error messages

---

doc/docs.md
vlib/gl/1shader.v
vlib/gl/gl.v
vlib/glm/glm.v
vlib/glm/glm_test.v

This PR adds 2 functions in gl module, which can be used to get uniform locations/attribute locations from the shader, 1 which sets the data at a uniform location. I added also a mult function in the glm module. The function multiplies 2 matrices, tests are working, but they need to improvment.

Added matrices multiplication & gl uniform&attribute location function 

---

vlib/v/util/errors.v

I also refactored and simplified the code and I have some questions.

compiler: color only the relevant part of the source code in error messages

---

vlib/pg/pg.v

I fixed the functions and return values in the pg module which had `pg.Type` instead of `Type`

fixed postgres module

---

vlib/v/gen/cgen.v
vlib/v/gen/fn.v
vlib/v/tests/interface_test.v

Temporary fix for interface pointers.
I haven't found a better way to do it, but someone more knowledgeable in C than me may find one later.
Also adds tests.

gen: fix interface pointers

---

vlib/flag/flag.v

Fix comment: missing `abbr` argument.

flag: Fix comment with abbr

---

vlib/math/fractions/fraction.v

1. Completed documentation
2. Flattened source code
3. Removed `mut` variables in favour of default immutable ones.

fraction: minor changes

---

examples/json.v

json: Update json.v

---

vlib/v/gen/cgen.v
vlib/v/gen/cgen_test.v

It fixes compilation of broken nested conditional statements, bug #3105

cgen: fix #3105 nested conditional statements

---

vlib/v/tests/interface_test.v

Hi,
here I'm adding some additional test on interfaces, and add some comment to clarify to newbies (like me) what happens behind compilation.
String delimiters are different to test more combinations.
Also I add even some (commented) statements on two features that would be useful (is possible to have).
Hope it's good. Thanks for now. Bye

add more tests on interfaces

---

vlib/v/gen/cgen.v
vlib/v/tests/goto_test.v

fixes https://github.com/vlang/v/issues/4674

cgen: fix goto error

---

doc/docs.md

docs: Fix TOC navigation links

---

vlib/v/parser/parser.v

This PR optimize stmt() in parser.v.
- Add `.name` match branch.
1. Make its logic clearer.
2. Increased processing priority because calls are frequent.

parser: optimize stmt()

---

.gitignore

Similar to sublime workspaces the ones for VS Code should be ignored too.

gitignore: ignore VS Code workspaces

---

cmd/tools/vpm.v

This fixes the `v update ui` command by rebaseing the pulled changes.

  [WIP] vpm: fix v update ui

---

vlib/v/checker/checker.v
vlib/v/checker/tests/no_interface_instantiation_a.out
vlib/v/checker/tests/no_interface_instantiation_a.vv
vlib/v/checker/tests/no_interface_instantiation_b.out
vlib/v/checker/tests/no_interface_instantiation_b.vv
vlib/v/checker/tests/no_interface_instantiation_c.out
vlib/v/checker/tests/no_interface_instantiation_c.vv

checker: prevent interface instantiation

---

doc/docs.md

Follow up the https://github.com/vlang/v/commit/1bf26a35fa520da71f63bf3ab9a1cab71098fa85

doc: rename field `default` to `init` for Array

---

vlib/v/gen/cgen.v
vlib/v/tests/for_loops_test.v

Avoid creating an extra variable in for in range statements.

gen: simplify for in range

---

cmd/tools/vrepl.v

repl: fix work with structs

---

vlib/regex/README.md
vlib/regex/regex.v
vlib/regex/regex_test.v

- added the `-` char management in Class Chars
- removed all `C.printf` from the debug code
- updated the `README.md`

regex: 0.9e

---

vlib/v/gen/cgen.v
vlib/v/tests/array_init_test.v

This PR fix array_init_with_default.
- Resolving temporary variable name conflicts.
- Add tests.

cgen: fix array_init_with_default

---

cmd/tools/vrepl.v
vlib/v/checker/tests/in_mismatch_type.out
vlib/v/checker/tests/in_mismatch_type.vv
vlib/v/checker/tests/match_expr_else.out

This PR fix vrepl and cast test errors in tests.

test: fix vrepl and cast test errors

---

doc/docs.md

This PR fix minor typo in doc.md.

doc: fix minor typo

---

cmd/tools/vrepl.v

repl: fix assigning an anomous function to a variable

---

vlib/v/builder/builder.v

builder: fix false-positive import cycle warning

---

vlib/gl/gl.v

This PR adds gl functions to improve the clean up in the end. I also added the `bind_attrib_location` function to create custom inputs.

Add functions to gl module

---

vlib/v/checker/tests/import_unused_warning.out
vlib/v/parser/module.v

Better unused imports warning

---

vlib/gl/gl.v
vlib/glm/glm.v
vlib/glm/glm_test.v

This PR adds functions to set values into a uniform variable and implements a function to rotate a matrix in glm

Adds uniform functions & Adds matrix rotation

---

vlib/regex/README.md

regex manual: english syntax corrections

---

vlib/v/builder/builder.v

It's a temporary solution for now

builder: add check for import builtin 

---

make.bat

This PR add `--quiet` for `git pull` in make.bat, avoid displaying too much information.

make.bat: git pull add `--quiet`

---

vlib/v/gen/cheaders.v

as preparation for further development in PR4971
Further development in my other PR would be easier if these definitions are already present in `cheader`.

add definitions of any_float and any_int types to cheader

---

tutorials/building-a-simple-web-blog-with-vweb.md

Syntax in the markdown examples was updated.

tutorials: switch to `(mut f Foo)`

---

vlib/builtin/map.v

It does not work yet, but should. I'll fix it tomorrow, but if you can find the error for me, it will be greatly appreciated.
```
fn main() {
mut a := map[string]int
a['a'] = 1
mut b := a.clone()
b['a'] = 2
}
```
gives
```
map_test.v:5:11: error: cannot assign `int` to variable `b["a"]` of type `map`
3 |     a['a'] = 1
4 |     mut b := a.clone()
5 |     b['a'] = 2
|              ^
6 | }
```

[WIP] map: clone

---

vlib/os/os_nix.c.v
vlib/os/os_windows.c.v
vlib/v/pref/pref.v

cmd/v: Reimplement -path flag

---

vlib/builtin/map.v

This fixes a small mem-leak in the map. Now the keys passed to the map are also cloned.

builtin: map: fix mem-leak

---

vlib/v/checker/checker.v
vlib/v/gen/cgen.v

Adds support for returning from a multi return value which was the issue in #5028.
closes #5028

checker,cgen: unpack multi returns in return statements

---

vlib/rand/rand.v
vlib/rand/random_numbers_test.v

This will add helpful random functions for `f32` and `f64` types

rand: add random functions for f32 and f64 both from 0 to max and range min to max versions

---

vlib/rand/rand.v

This PR adds a const(`max_i32`) to math module and replaces the divisions with multiplications.

rand: Add max_i32 const, replace divisions with multiplications

---

vlib/os/os.v

Fixes https://github.com/vlang/v/issues/5038

Fix build issue caused by fileno on FreeBSD/OpenBSD/NetBSD

---

examples/cli.v
vlib/cli/command.v
vlib/cli/help.v
vlib/cli/version.v

cli: assign parent by default + add disable_flag option

---

cmd/v/v.v
vlib/v/util/util.v

in preparation for v cli rewrite using the cli module

utils: add args argument to launch_tool

---

CONTRIBUTING.md

doc: fix line breaks to make it 80 charecters / line

---

examples/spectral.v

examples: fix spectral.v .Fixed array creation method to not leak memory

---

examples/game_of_life/modules/automaton/automaton.v

Fixed error in compilation of game of life due to type mismatch

examples: game_of_life example fix

---

vlib/v/gen/cgen.v
vlib/v/gen/json.v

This expands on @spytheman's changes from moments ago

cgen,json: Fix generation for enums and some primitives

---

vlib/builtin/cfns.c.v
vlib/net/socket.v
vlib/net/websocket/io.v
vlib/os/os.v

As the title says, cp implemented for Unix

os.cp: implemented for unix

---

vlib/json/json_test.v

Make sure this doesn't break in the future

json: Add enum to json_test

---

vlib/v/checker/tests/function_arg_mutable_err.out
vlib/v/checker/tests/mut_int.out
vlib/v/parser/fn.v

This PR improves the message for all non mut types and the check

parser: update check for non mut types in fn

---

vlib/vweb/tmpl/tmpl.v

Currently it's only possible to process a file.
It would be nice to process a string as well. So i spitted the functions.

vweb: add tmpl api to compile either file or a string

---

vlib/gl/gl.v

This PR includes comments for the gl module, some parameter name changes, that they are more clear and a bind_texture method to be able, to use other modes too.

Adds comments to gl & cleaning up gl.v 

---

cmd/tools/vdoc.v

Merge this first before #5236.
- Add parent type prefix.
- Fix segfault when including readme.
- Remove "pub" when including public fn's only
- Fix some highlighting.

[merge before 5236] vdoc fixes

---

cmd/tools/modules/testing/common.v
examples/pico/pico.v
thirdparty/picohttpparser/src/picohttpparser.h
vlib/picoev/picoev.v
vlib/picohttpparser/request.v
vlib/picohttpparser/response.v

Fix issues with picoev

---

cmd/tools/vdoc-resources/doc.css

vdoc: fix horizontal scrollbar

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/gen/cgen.v
vlib/v/parser/comptime.v
vlib/v/parser/parser.v
vlib/vweb/tmpl/tmpl.v

vweb: impl of comptime tmpl parsing (fix vweb_example)

vweb: impl of comptime tmpl parsing (fix vweb_example)

---

cmd/tools/vup.v

This PR makes `v up` work from a release archive (where `.git` dir is not included).
Now users can just use `v up` whether they extracted from the archive or used `git clone` to start.

vup: make 'v up' work from release archive

---

vlib/net/http/http.v

This PR adds a `location` header. Problem was for me, I wanted to get something and it has `location` in the response instead of `Location` this fix it

Added http do fix for redirect

---

cmd/tools/vdoc-resources/doc.css
cmd/tools/vdoc-resources/doc.js

vdoc: scroll indicator

---

cmd/tools/vdoc-resources/doc.css
cmd/tools/vdoc.v

There was an issue that code had different styles. I simplified it.

vdoc: fix code formatting

---

vlib/glm/glm.v
vlib/glm/glm_test.v

This PR simplifies the glm.mult function and added better tests for it

Improved matrix mult function and added tests

---

cmd/tools/vdoc-resources/doc.css

* Adjusted padding
* Anchor links

Vdoc mobile fixes

---

vlib/v/table/atypes.v
vlib/v/table/atypes_test.v

This PR adds tests to atypes and refactors some methods for performance

table: add tests and improve performance

---

cmd/tools/vdoc.v

vdoc: move builtin to top

---

vlib/mysql/_cdefs.c.v
vlib/mysql/mysql.v
vlib/mysql/result.v
vlib/mysql/utils.v

- Update documentation
- Rename some methods
- Add `real_query` methods

mysql: Update documentation, rename some methods & add real_query methods

---

vlib/vweb/tmpl/tmpl.v

vweb: make @include work

---

vlib/strconv/ftoa/f64_str.v
vlib/v/checker/checker.v
vlib/v/checker/checker_test.v
vlib/v/checker/tests/plus_or_minus_assign_one_err.out
vlib/v/checker/tests/plus_or_minus_assign_one_err.vv
vlib/v/tests/option_test.v

[READY] checker: use ++ / -- instead of += 1 / -= 1

---

examples/concurrency/concurrency.v
examples/concurrency/concurrency_http.v

Add examples using concurrent task syncing with WaitGroup.
* **concurrency.v** : run multiple concurrent tasks using time.sleep_ms function.
* **concurrency_http.v**: Makes http request to public resources using concurrent tasks.
**PS**: vlang is awesome :)
Sorry, my basic and limited english 🇺🇾

examples: concurrency

---

.github/workflows/ci.yml
.gitignore
cmd/tools/vsymlink.v
make.bat
temp_test.c
thirdparty/.gitignore
thirdparty/sokol/sokol_app.h
thirdparty/vschannel/vschannel.c
vlib/clipboard/clipboard_windows.c.v
vlib/math/math.c.v
vlib/math/math_test.v
vlib/net/http/backend_windows.c.v
vlib/os/os.v
vlib/v/builder/c.v
vlib/v/builder/cc.v
vlib/v/gen/cheaders.v

This PR aims to fix the compilation of all test files under `tcc` on Windows.   
Hopefully, once they all pass, we can add a `windows-tcc` CI job to ensure it doesn't break again.

tcc_win: fix tests

---

vlib/vweb/tmpl/README.md

tmpl: add docs

---

cmd/tools/check_os_api_parity.v
cmd/tools/vdoc.v
vlib/builtin/map.v
vlib/builtin/map_test.v
vlib/builtin/sorted_map.v
vlib/net/http/http.v
vlib/net/urllib/urllib.v
vlib/net/urllib/values.v
vlib/v/depgraph/depgraph.v
vlib/v/gen/cgen.v

map: rename size to len

---

vlib/sync/waitgroup.v

waitgroup: Remove races, make platform independent, document

---

vlib/builtin/cfns.c.v
vlib/os/os.v

Especially helpful if the permission to delete the specified file is missing.

os: make rm return an optional

---

cmd/tools/vbin2v.v

bin2v: validate .v file extension for write

---

vlib/builtin/map.v
vlib/v/gen/cgen.v

Just a couple of comments and renaming of the function introduced in 67d9d94.

map: comments and renaming

---

vlib/os/os.v

This PR change `os.cp` `os.cp_all` `os.mv_by_cp` return type from `?bool` to `?`.
```v
pub fn cp(old, new string) ? {...}
pub fn cp_all(osource_path, odest_path string, overwrite bool) ? {...}
pub fn mv_by_cp(source string, target string) ? {...}
```

os_api: change `os.cp` `os.cp_all` `os.mv_by_cp` return type from `?bool` to `?`

---

vlib/os/os.v

os: make all rm functions return an optional

---

doc/docs.md

doc: describe coroutines and how to exchange data

---

vlib/v/gen/sql.v

This PR fixes names which would be keywords like `Commit` in sqlite

Fixed sql table names

---

cmd/tools/vrepl.v

repl: Add some array functions to possible statement patterns

---

vlib/os/os.v
vlib/v/gen/fn.v
vlib/v/parser/fn.v

This PR fix fn()? return.
I think the reason for the test error is the need to update v.c.

cgen: fix fn()? return

---

doc/docs.md

docs: add `as` and `is` keywords plus cpp syntax highlighting

---

vlib/cli/help.v

cli: calculate indent based on name length

---

vlib/v/gen/cgen.v

This PR minor optimize `index_expr()` in cgen.v.
- Remove `mut is_range`.
- Use `else` instead of `if !is_range`.
- Make it cleaner.
The contrast between the changes looks messy, and it's actually putting the code of 'if! is_range' into 'else'.

cgen: minor optimize `index_expr()`

---

vlib/net/http/http.v

This PR adds a post method which supports json as payload

add post function with json as payload

---

cmd/tools/vpm.v

vpm: replace `-` in author names with `_` for module folder

---

tutorials/building-a-simple-web-blog-with-vweb.md
tutorials/code/blog/article.v

tutorials: update markdown code snippets

---

tutorials/building-a-simple-web-blog-with-vweb.md

Speed has a connotation of performance and so using speed of Python seems contradictory + you use performance just afterwards. Agility matches the intention better and for those of us who think of Ruby instead of Python for agility is just a little more icing. :)

Tutorial: Change speed to agility

---

vlib/cli/command.v
vlib/cli/flag.v
vlib/cli/help.v
vlib/cli/version.v

cli: help/version abbrev optional + fix various inconsistencies

---

cmd/tools/modules/testing/common.v
examples/sokol/particles/main.v
examples/sokol/particles/particle/LICENSE
examples/sokol/particles/particle/color.v
examples/sokol/particles/particle/particle.v
examples/sokol/particles/particle/system.v
examples/sokol/particles/particle/vec2/vec2.v

This will add a small sokol (sgl) example of a minimal particle system emitting particles from the mouse pointer
(in fashionable V colors!)

examples: add sokol particle example

---

CONTRIBUTING.md

This will try to fix the formatting of, especially, point `8.`

docs: fix formating of points 7, 8, 9 in Example Workflow ... section

---

vlib/v/scanner/scanner.v
vlib/v/tests/string_interpolation_test.v

scanner: fix string interpolation for '$a.b().c'

---

vlib/cli/command.v
vlib/cli/flag.v
vlib/cli/flag_test.v

cli: add flag/cmd sorting + get_all_found

---

examples/quick_sort.v

Clean up quick_sort example I introduced.

example: clean up quick_sort

---

vlib/orm/orm_test.v
vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/gen/sql.v
vlib/v/parser/sql.v

This pr adds the order statement to orm

add order by orm

---

vlib/orm/orm_test.v
vlib/v/gen/sql.v

add orm test

---

tutorials/code/blog/article.v
tutorials/code/blog/blog.v

fix vweb example

---

vlib/v/gen/cgen.v

This PR add unsafe block braces and comments in generated code.
before:
```v
inline static u64 hash__wyhash__wyhash64(byteptr key, u64 len, u64 seed_) {
if (len == 0) {
return 0;
}
byte* p = &key[0];
u64 seed = seed_;
u64 i = (len & 63);
if (i < 4) {
seed = hash__wyhash__wymum(((hash__wyhash__wyr3(p, i) ^ seed) ^ _const_hash__wyhash__wyp0), (seed ^ _const_hash__wyhash__wyp1));
} else if (i <= 8) {
seed = hash__wyhash__wymum(((hash__wyhash__wyr4(p) ^ seed) ^ _const_hash__wyhash__wyp0), ((hash__wyhash__wyr4(p + i - 4) ^ seed) ^ _const_hash__wyhash__wyp1));
} else if (i <= 16) {
seed = hash__wyhash__wymum(((hash__wyhash__wyr8(p) ^ seed) ^ _const_hash__wyhash__wyp0), ((hash__wyhash__wyr8(p + i - 8) ^ seed) ^ _const_hash__wyhash__wyp1));
} else if (i <= 24) {
seed = …
```

cgen: add unsafe block braces and comments in generated code

---

examples/vweb/vweb_assets/main.v
vlib/vweb/vweb.v

This pr fix the handling in vweb for `/` links and use the index() function then

fix vweb index

---

vlib/v/gen/js/js.v

js: fix int division

---

vlib/vweb/vweb.v

This PR adds a get map to the vweb context, which is parsed from the link

vweb: add get map

---

vlib/orm/orm_test.v
vlib/v/gen/sql.v
vlib/v/parser/sql.v

This PR adds the `delete` statement to orm, usage: ```v
sql db {
delete from User where age == 34
}
```

orm: add delete from stmt

---

doc/docs.md

This PR updates the number of keywords to 25 and includes the missing `mut` keyword in docs.

Update keywords section in docs

---

vlib/gg/text_rendering.v

This PR fix text rendering in gg

fix text rendering

---

vlib/v/parser/comptime.v

This PR adds a new folder structure to vweb

parser: add template path by fn name

---

doc/docs.md
vlib/v/tests/struct_test.v

* Update tests for struct literal function arguments
* Update docs: struct literals without struct name

Update docs and tests for struct literals

---

vlib/v/parser/comptime.v

merge this before #5755, it fixes something which i forgot in #5754

if-smartcast part 2.1

---

vlib/v/checker/checker.v
vlib/v/fmt/fmt.v
vlib/v/gen/cgen.v
vlib/v/tests/sum_type_test.v

it generates the original variable name.

if-smartcast part 3

---

vlib/vweb/vweb.v

This PR fix the router array param

vweb: fix router

---

cmd/tools/check_os_api_parity.v
doc/docs.md
examples/lander.v
vlib/v/ast/ast.v
vlib/v/ast/str.v
vlib/v/builder/builder.v
vlib/v/checker/checker.v
vlib/v/checker/tests/returns/return_missing_simple.vv
vlib/v/doc/doc.v
vlib/v/fmt/fmt.v
vlib/v/gen/cgen.v
vlib/v/gen/comptime.v
vlib/v/gen/js/js.v
vlib/v/parser/assign.v
vlib/v/parser/comptime.v
vlib/v/parser/fn.v
vlib/v/parser/if.v
vlib/v/parser/pratt.v
vlib/v/tests/if_smartcast_test.v
vlib/v/token/token.v

all: remove it smartcast and replace with original variable name

---

vlib/vweb/vweb.v

This PR fix routes which hasn't parameter

fix router for non param routes

---

cmd/tools/vcreate.v

See commit messages for details

vcreate: various fixes and improvements

---

vlib/v/checker/checker.v
vlib/v/checker/tests/no_interface_str.out
vlib/v/checker/tests/no_interface_str.vv

* Use typeof or implement the str() method in the interfaced types.

Fix #5533 - .str() method is not allowed on interface types.

---

.github/workflows/ci.yml
make.bat

- print debugging info if compilation fails
- don't add V to PATH automatically

`make.bat`: debugging and PATH fixes

---

doc/upcoming.md

doc: describe upcomming automatic lock feature

---

vlib/net/smtp/smtp-test.v
vlib/net/smtp/smtp.v
vlib/net/smtp/smtp_test.v

Implementation of SMTP in V.
Features: 
- sending email trough SMTP server
- making connection with SMTP and handling fail cases 
Tests:
For now there is only smtp-test.v file which is just sample for using this library.
More in depth test will be put in next PR

Implementation of SMTP RFC 2821

---

vlib/v/ast/ast.v
vlib/v/ast/str.v
vlib/v/checker/checker.v
vlib/v/fmt/fmt.v
vlib/v/gen/cgen.v
vlib/v/gen/js/js.v
vlib/v/parser/parser.v
vlib/v/parser/pratt.v
vlib/v/tests/ptr_arithmetic_test.v

Implement #5655.
~~Draft for now because I haven't added a test yet~~. This is my first significant addition to a compiler, so hopefully I did things right ;-)
~~Edit: it doesn't work yet for unsafe checking.~~

v: Add UnsafeExpr

---

vlib/os/os_windows.c.v
vlib/rand/mt19937/mt19937.v

This PR fix broken links and old email address in code comment.

contributing: fix broken links in code comment

---

vlib/net/smtp/smtp-test.v
vlib/net/smtp/smtp.v
vlib/net/smtp/smtp_test.v

This PR contains an implementation of mail sent confirmation and  SMTP tests for public fn

Mail sent confirmation and tests for smtp lib

---

vlib/net/smtp/smtp.v
vlib/net/smtp/smtp_test.v

This PR changes the API of the new SMTP module to feel more V-like. The new approach also has the advantage of reusing the SMTP connection to the server between emails, so it should result in much better performance, since it doesn't need to reconnect/reauthenticate between mails.
It also adds a few new features/fixes:
- `cc` / `bcc` support
- Email sent time support
- Fixes in case the server's response was >1024 bytes long

smtp: rewrite module api

---

cmd/v/help/default.txt

help : document existence of vet in default help

---

vlib/v/ast/ast.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/module_interface_keep.vv
vlib/v/parser/struct.v

fmt: fix formatting interface declaration

---

doc/docs.md

Show how to ignore one of a function's results.
Add *Matching sum types* subheading.
Option types:
Inline `new_repo` function in main example for simplicity.
Add *Handling optionals* subheading.
Update propagating an optional example and wording.
Add 3 subheadings for *Calling C functions* section, tweak formatting.
Add *Debugging code* heading (was part of *Calling C*).

doc: Option, Calling C tweaks

---

doc/docs.md

I've also reorganized the colums of the toc to make them all have more or less the same height.

doc: make int base section more concise

---

examples/smtp/mail.v

Sample code for SMTP module:
- shows how to establish a connection
- set configuration
- do authorization with an email server (username, password)
- configure error messages
- sends an email

Add sample code for SMTP module
