- vlib/pg/orm.v
Currently the PG ORM only resolves `int` based date time values.
This PR resolves string based date time values. This is achieved by checking for ` /:-` characters in the value, if they exist the value is then given to `time.parse`.
> pg: resolve string datetime

- vlib/v/checker/checker.v
- vlib/v/tests/match_reference_sumtype_var_test.v
This PR fix error for match sumtype that referenced before (fix #14246).
- Fix error for match sumtype that referenced before.
- Add test.
```v
struct Player {
mut:
x     int
y     int
level int
}
struct Enemy {
mut:
x      int
y      int
damage f64
}
type PlayerOrEnemy = Enemy | Player
fn test_match_reference_sumtype_var() {
mut entity := PlayerOrEnemy(Player{10, 12, 3})
x_move := 11
y_move := 22
mut ref := &entity
match mut entity {
Player {
entity.x += x_move
entity.y += y_move
println('Player is moved to $entity.x, $entity.y and its level is $entity.level')
}
Enemy {
entity.x += x_move
entity.y += y_move
println('Enemy is moved to $entity.x, $entity.y and its damage is $entity.damage')
}
}
println(typeof(ref).name)
assert true
}
Player is moved to 21, 34 and …
```
> checker: fix error for match sumtype that referenced before (fix #14246)

- CHANGELOG.md
- doc/docs.md
- vlib/v/checker/comptime.v
- vlib/v/checker/tests/compile_error.out
- vlib/v/checker/tests/compile_error.vv
- vlib/v/parser/comptime.v
This PR adds the `compile_error` and `compile_warn` comptime functions.
Both are very useful for handling cases where, for example, a certain generic type, or an operating system, is not supported.
```v
$ cat x.v
module main
$if linux {
$compile_error('Linux is not supported')
}
fn main() {
}
$ ./v2 run x.v
x.v:4:5: error: Linux is not supported
2 |
3 | $if linux {
4 |     $compile_error('Linux is not supported')
|     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
5 | }
6 |
```
> all: add `compile_error` and `compile_warn` comptime functions

- thirdparty/vschannel/vschannel.c
- thirdparty/vschannel/vschannel.h
- vlib/net/http/backend_windows.c.v
Fix `http.fetch` crashing with `Unhandled Exception 0xC0000374` while using gc boehm on windows.
> net.http: Fix crash on Windows when using Boehm GC

- vlib/v/checker/fn.v
- vlib/v/checker/tests/return_aliases_of_fixed_array.out
- vlib/v/checker/tests/return_aliases_of_fixed_array.vv
This PR check error for returning aliases of fixed array (fix #14344).
- Check error for returning aliases of fixed array.
- Add test.
```v
type Mat = [2][2]int
fn main() {
a := Mat([[1, 2]!, [3, 4]!]!)
println(a.foo())
}
fn (v Mat) foo() Mat {
return v
}
fn bar() Mat {
return Mat([[1, 2]!, [3, 4]!]!)
}
./tt1.v:8:18: error: fixed array cannot be returned by function
6 | }
7 |
8 | fn (v Mat) foo() Mat {
|                  ~~~
9 |     return v
10 | }
./tt1.v:12:10: error: fixed array cannot be returned by function
10 | }
11 |
12 | fn bar() Mat {
|          ~~~
13 |     return Mat([[1, 2]!, [3, 4]!]!)
14 | }
```
> checker: check error for returning aliases of fixed array (fix #14344)

- vlib/v/parser/parse_type.v
- vlib/v/parser/tests/generic_struct_parameter_err.out
- vlib/v/parser/tests/generic_struct_parameter_err.vv
This PR check error for generic struct parameter (fix #14311).
- Check error for generic struct parameter.
- Add test.
```v
import datatypes { LinkedList }
struct MyNode<T> {
mut:
data T
}
struct MyContainer<T> {
mut:
lst LinkedList<MyNode<T>>
}
fn (mut c MyContainer<T>) push(data T) {
node := MyNode<T>{
data: data
}
c.lst.push<T>(node)
}
fn main() {
mut c := MyContainer<string>{}
println(c)
}
./tt1.v:10:17: error: generic struct parameter name needs to be exactly one char
8 | struct MyContainer<T> {
9 | mut:
10 |     lst LinkedList<MyNode<T>>
|                    ~~~~~~~~~
11 | }
12 |
```
> parser: check error for generic struct parameter (fix #14311)

- vlib/os/os_nix.c.v
- vlib/os/os_windows.c.v
I'm adding this to be able to do my own character escaping on Windows to be able to bootstrap `vab`.
See https://discord.com/channels/592103645835821068/592320321995014154/971422720803893298 for reference discussions.
> os: add `raw_execute` on Windows

- vlib/v/checker/checker.v
- vlib/v/checker/tests/generic_sumtype_decl_err.out
- vlib/v/checker/tests/generic_sumtype_decl_err.vv
This PR check generic sumtype declare error (fix #14004).
- Check generic sumtype declare error.
- Add test.
```v
struct Just<T> {
value T
}
struct Nothing {}
type Maybe = Nothing | Just
fn main() {
}
./tt1.v:7:24: error: generic struct `Just` must specify generic type names, e.g. Foo<T>
5 | struct Nothing {}
6 |
7 | type Maybe = Nothing | Just
|                        ~~~~
8 |
```
> checker: check generic sumtype declare error (fix #14004)

- vlib/net/common.v
Changes wait_for_common to convert timeouts to deadlines which are then waited on. This replaces the previous select_with_retries.
> net: Select with deadlines

- doc/docs.md
- vlib/v/gen/c/cheaders.v
- vlib/v/gen/c/fn.v
This PR optimizes the closure implementation: calling a closure is now anywhere from 1.5x - 5x faster (depending on the number/size of its arguments).
(`old` is the current master, `new` is the first commit of the PR, and `new2` is the most up-to-date version here)
This PR also improves support for closures on x86 / arm32.
> gen: make the closure implementation more performant

- vlib/builtin/map.v
- vlib/builtin/map_test.v
Added clear() to builtin module, and added associated tests.
clear() is present in array builtin, so makes logical sense to also be present in map builtin, for uniformity.
clear() in map acts similar to way it does in array; wherein it does not deallocate memory but instead sets lengths to 0.
> added clear() to map in builtin module

- vlib/v/checker/checker.v
- vlib/v/checker/tests/cast_function_to_string_err.out
- vlib/v/checker/tests/cast_function_to_string_err.vv
This PR check error for cast function to string (fix #14357).
- Check error for cast function to string.
- Add test.
```v
fn main() {
println(string(main))
}
./tt1.v:2:10: error: cannot cast function `main` to string
2 |     println(string(main))
|             ~~~~~~~~~~~~
3 | }
```
> checker: check error for cast function to string (fix #14357)

- vlib/rand/rand.v
This PR makes a minor cleanup in choose() (fix #13897).
- Use `rng.shuffle(mut indices) ?` instead of `rng.shuffle<int>(mut indices) ?`.
- `infer_fn_generic_types` can work.
> rand: minor cleanup in choose() (fix #13897)

- .github/workflows/ci.yml
- .github/workflows/ci_bootstrapping_works.yml
- .github/workflows/ci_cross.yml
- .github/workflows/ci_sanitized.yml
- .github/workflows/ci_v_benchmark.yml
- .github/workflows/containers_ci.yml
- .github/workflows/debug_ci.yml
- .github/workflows/docs_ci.yml
- .github/workflows/gfx_ci.yml
- .github/workflows/module_docs.yml
- .github/workflows/other_ci.yml
- .github/workflows/paths_ci.yml
- .github/workflows/sdl_ci.yml
- .github/workflows/toml_ci.yml
- .github/workflows/vab_ci.yml
- .github/workflows/vinix-kernel.yml
- .github/workflows/websockets.yml
Because our CI is often very full and the code formatting check is the one that fails most of the time, all CI checks will run only if code formatting was successful.
> ci: check fmt before all other

- vlib/math/big/array_ops.v
- vlib/math/big/big.v
- vlib/math/big/division_array_ops.v
- vlib/math/big/integer.v
- vlib/math/big/large_number_power_and_string_conversion_test.v
- vlib/math/big/special_array_ops.v
This PR makes common `math.big` operations 3x-5x faster.
It also fixes the exploding memory usage of the Integer.str() method for larger integers.
> math.big: reduce memory usage of Integer.str() (free intermediary Integers), optimise some operations using `[direct_array_access]`

- vlib/v/checker/checker.v
- vlib/v/checker/tests/infix_compare_optional_err.out
- vlib/v/checker/tests/infix_err.out
- vlib/v/checker/tests/unwrapped_optional_infix.out
This PR fixes the checker error when an infix expression has an optional on both sides. It also slightly improves that check message by highlighting which side(s) contain the optional.
Apologies if my commit messages are formatted wrong or too numerous -- I will gladly start over from scratch & Do It Right if necessary (but I'd rather not, I've burnt an inordinate amount of time working on this due to git troubles... >.>)
I don't understand this comment... it seems outdated? -- Should I just remove it?
```// TODO move this to symmetric_check? Right now it would break `return 0` for `fn()?int ` ```
The "unwrapped optional infix comparison" check overlaps highly with "unwrapped optional infix use" check. In fact I'm inclined to remove it as redundant -- should I?
The checker specifically …
> checker: fix optionals in infix expression check (fix #14354)

- examples/submodule/v.mod
Adds missing v.mod file to actually make the example work correctly.
> examples: add missing v.mod file

- vlib/v/gen/c/struct.v
- vlib/v/tests/append_struct_to_interface_array_test.v
This PR fix appending struct to interface array (fix #14355).
- Fix appending struct to interface array.
- Add test.
```v
struct Vec {
mut:
x f64
y f64
z f64
}
struct Plane {
position Vec
normal   Vec
}
struct Sphere {
position Vec
radius   f64
}
interface Object {
position Vec
}
fn main() {
mut scene := []Object{}
scene << Plane{
position: Vec{0, -10, 0}
normal: Vec{0, -1, 0}
}
scene << Sphere{
position: Vec{0, 0, -20}
radius: 7
}
println(scene)
assert scene.len == 2
assert scene[0].position.x == 0
assert scene[0].position.y == -10
assert scene[0].position.z == 0
assert scene[1].position.x == 0
assert scene[1].position.y == 0
assert scene[1].position.z == -20
}
[Object(Plane{
position: Vec{
x: 0
y: -10
z: 0
}
normal: Vec{
x: 0
y: -1
z: 0
}
}), Object(Sphere{ …
```
> cgen: fix appending struct to interface array (fix #14355)

- vlib/math/cbrt.v
- vlib/math/math_test.v
The cbrt fn had improper `()` making it always return nan. I fixed the placement so it returns cube roots. Also added a test to verify.
> math: cbrt fix

- examples/2048/2048.v
This PR uses `gg.Context`'s methods instead of just `gg`'s on Android.
Before:
After:
> examples: fix 2048 scaling on Android

- vlib/net/openssl/ssl_connection.v
In case your ssl client read a unknown amount of data of a server it is essential that the read call doesn't block infinitely and observes the tcp timeout.
When connecting or writing that timeout isn't that important. Therefore I changed only the read function. I'm not a professional with SSL, but for me it works and make sense to observe a timeout. I also checked the smlp implementation, it is still ok with this PR.
> openssl: read doesn't block infinitely

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/anon_fn_with_if_expr_expected.vv
- vlib/v/fmt/tests/anon_fn_with_if_expr_input.vv
- vlib/v/fmt/tests/shared_input.vv
- vlib/v/tests/bench/math_big_gcd/bench_euclid.v
This PR fix fmt error of anon fn with if expr (fix #14393).
- Fix fmt error of anon fn with if expr.
- Add test.
```v
fn main() {
a := fn () {
if true {
println('a')
} else {
println('a')
}
}
a()
}
```
formated:
```v
fn main() {
a := fn () {
if true {
println('a')
} else {
println('a')
}
}
a()
}
```
> fmt: fix fmt error of anon fn with if expr (fix #14393)

- vlib/os/filepath.v
- vlib/os/filepath_test.v
- vlib/os/os.v
- vlib/os/os_test.v
The current `os.is_abs_path` function ([source](https://github.com/vlang/v/blob/master/vlib/os/os.v#L458)) is **not** implemented correctly for Windows systems, because the function only checks whether the passed path starts with a drive letter on a Windows system, and not whether the path is rooted.
Here is a comparison of the **current**  `os.is_abs_path` function with the `filepath.IsAbs()` function of Go (on a Windows system): 
Go:
```go
package main
import (
"fmt"
"path/filepath"
)
func main() {
fmt.Println(filepath.IsAbs("C:rel\\path\\to\\file.v"))   	// false
fmt.Println(filepath.IsAbs("C:.."))   					// false
fmt.Println(filepath.IsAbs("C:\\abs\\path\\to\\file.v"))  	// true
}
```
V:
```v
module main
import os { is_abs_path }
fn main() { …
```
> os: fix is_abs_path function for Windows systems

- vlib/net/smtp/smtp.v
before some mail clients misinterpreted subjects with non-ascii characters (e.g. 'öäü ÖÄÜ ß')
Now every client will show the correct characters
BTW would be nice to have ```fn (str string) is_ascii() bool {return !str.bytes().any(it < u8(` `) || it > u8(`~`))``` as vlib string function
> net.smtp: handle UTF-8 subjects according RFC 1342

- cmd/tools/vtest-self.v
- cmd/tools/vvet/tests/array_init_one_val.out
- cmd/tools/vvet/tests/indent_with_space.out
- cmd/tools/vvet/tests/no_warn_about_missing.vv
- cmd/tools/vvet/tests/parens_space_a.out
- cmd/tools/vvet/tests/parens_space_b.out
- cmd/tools/vvet/vvet.v
Fixes #14402 
On a side note there seem to have been updates related to the `NB` -> `Note` wording - which I've fixed also so the tests actually pass if I run `v test .` locally in the directory, I wonder why this didn't show in CI - has the `vvet` tests been disabled?
> vvet: fix false positive, add test

- vlib/v/ast/types.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/generic_method_with_variadic_generic_args_test.v
This PR fix generic method with variadic generic argument (fix #14401).
- Fix generic method with variadic generic argument.
- Add test.
```v
struct Foo<T> {
mut:
arr []T
}
fn (mut foo Foo<T>) push(items ...T) {
for item in items {
foo.arr << item
}
}
fn main() {
mut f := Foo<int>{}
f.push(1, 2, 3, 5, 8, 13, 21, 34, 55)
println(f.arr)
assert f.arr == [1, 2, 3, 5, 8, 13, 21, 34, 55]
}
[1, 2, 3, 5, 8, 13, 21, 34, 55]
```
> ast, cgen: fix generic method with variadic generic argument (fix #14401)

- vlib/v/gen/c/index.v
- vlib/v/tests/struct_field_array_index_test.v
This PR fix error for struct field array index (fix #14394).
- Fix error for struct field array index.
- Add test.
```v
struct App {
mut:
buffer []string
}
fn main() {
buffer: []string{len: 2}
}
app.buffer[0] += 'hello'
app.buffer[1] += 'world'
println(app)
assert app.buffer == ['hello', 'world']
}
&App{
buffer: ['hello', 'world']
}
```
```v
import term.ui as tui
import term
struct App {
mut:
tui    &tui.Context = 0
buffer []string
cursor term.Coord
}
fn event(e &tui.Event, x voidptr) {
mut app := &App(x)
if e.typ == .key_down {
app.buffer[app.cursor.y] += e.utf8
}
}
fn main() {
buffer: []string{}
}
app.tui = tui.init(
user_data: app
event_fn: event
hide_cursor: false
)
app.tui.run()?
}
PS D:\Test\v\tt1> …
```
> cgen: fix error for struct field array index (fix #14394)

- vlib/v/parser/parse_type.v
- vlib/v/tests/parse_invalid_map_type_test.v
This PR fix panic for parse invalid map type (fix #14425).
- Fix panic for parse invalid map type.
- Add test.
```v
import v.ast
import v.parser
import v.pref
fn main() {
result := parser.parse_text('a := map[*Node]bool', '', ast.new_table(), .parse_comments,
&pref.Preferences{
output_mode: .silent
is_fmt: true
})
assert true
}
&v.ast.File{
nr_lines: 0
nr_bytes: 19
mod: v.ast.Module{
name: 'main'
short_name: 'main'
attrs: []
pos: v.token.Pos{
len: 0
line_nr: 0
pos: 0
col: 0
last_line: 0
}
name_pos: v.token.Pos{
len: 0
line_nr: 0
pos: 0
col: 0
last_line: 0
}
is_skipped: true
}
global_scope: &# 0 - 0
is_test: false
is_generated: false
is_translated: false
idx: 0
path: ''
path_base: '.'
scope: &# 0 - 19
* var: a - ast.Type(0x0 = 0)
stmts: [module …
```
> parser: fix panic for parse invalid map type (fix #14425)

- vlib/v/builder/builder.v
- vlib/v/checker/tests/fn_duplicate.out
- vlib/v/checker/tests/fn_duplicate.vv
- vlib/v/util/errors.v
This PR perfect error message (fix #14386).
- Perfect error message.
- Modify test.
```v
module main
fn main() {
say_something()
}
pub fn say_something(yo string) {
println('yo with arg')
}
pub fn say_something() {
println('yo')
}
builder error: redefinition of function `say_something`
./tt1.v:7:1: conflicting declaration: pub fn say_something(yo string)
5 | }
6 |
7 | pub fn say_something(yo string) {
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
8 |
9 |     println('yo with arg')
./tt1.v:13:1: conflicting declaration: pub fn say_something()
11 |
12 |
13 | pub fn say_something() {
| ~~~~~~~~~~~~~~~~~~~~~~
14 |
15 |     println('yo')
```
> builder: perfect error message (fix #14386)

- vlib/v/gen/c/fn.v
- vlib/v/tests/alias_array_has_method_test.v
This PR fix alias of array that has builtin method (fix #14422).
- Fix alias of array that has builtin method.
- Add test.
```v
type Alias = []int
fn (a Alias) last() int {
return 22
}
fn main() {
ret := Alias([0]).last()
println(ret)
}
22
```
> cgen: fix alias of array that has builtin method (fix #14422)

- vlib/builtin/builtin.c.v
- vlib/builtin/builtin.v
- vlib/builtin/builtin_d_use_libbacktrace.c.v
- vlib/builtin/builtin_notd_use_libbacktrace.c.v
This PR adds a new variant of print_libbacktrace, named `eprint_libbacktrace` which prints the backtrace to stderr instead of the usual stdin. 
This is meant for some applications such as [VLS](https://github.com/vlang/vls) where crash reports depend on outputs in the stderr pipe.
> builtin: printing libbacktrace to stderr when printing panics/segfault crash

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/cheaders.v
In the current master, we allocate 32kb of memory (at runtime) every time a closure is created.
With this PR, creating the first closure will still allocate that 32kb, but an extra 681 closures can now be created before the next allocation needs to be made :)
> gen: reduce the closure memory usage

- cmd/tools/vcomplete.v
This PR improves flag tab completion.
On top I've added the `missdoc` tool to completions, since this was my initial intend - before discovering
that flag completion didn't work very well :slightly_smiling_face: 
With this PR you'll now get a flag list when doing e.g.: `v -<tab>` or only long flags: `v --<tab>`. This also works
for sub commands like e.g. `missdoc` or `doc`
I'm still fighting a couple of known odd cases:
`v -v<tab>` -> `bash: syntax error near unexpected token '('`
`v -V<tab>` -> `V: command not found`
`v -version<tab>` -> `V: command not found`
`v --version<tab>` -> `V: command not found`
I'm puzzled why the bugs only shows when the version is involved.
One more odd one is:
`v --enable-globals<tab>` -> `--enable-globals` flag is deprecated, please use `-enable-globals` …
> vcomplete: improve flag completion, add missdoc

- vlib/v/gen/c/infix.v
- vlib/v/tests/in_expression_test.v
This PR fix error for 'in array of sumtype' (fix #14439).
- Fix error for 'in array of sumtype'.
- Add test.
```v
type TokenValue = rune | u64
fn main() {
val := TokenValue(`+`)
if val in [TokenValue(`+`), TokenValue(`-`)] {
println("ok")
}
}
ok
```
> cgen: fix error for 'in array of sumtype' (fix #14439)

- vlib/os/os.v
Adds function to get a list of users installed on the system.
```v
// user_names returns an array of the name of every user on the system.
pub fn user_names() ?[]string {
mut result := Result{}
$if windows {
result = execute('wmic useraccount get name')
} $else {
// Single quotes must be used here. The awk command produces
// a different output with double quotes.
result = execute("awk -F: '{ print \$1 }' /etc/passwd")
}
if result.exit_code != 0 {
return error('Failed to get user names. Exited with code $result.exit_code: $result.output')
}
mut users := result.output.split_into_lines()
// it seems the windows command returns an empty line at the end
$if windows {
users.delete(users.len - 1)
}
if _unlikely_(users.len == 0) {
return error('No users found on system.')
}
return users
}
```
> os: add `fn user_names()`

- vlib/v/gen/c/infix.v
- vlib/v/tests/in_expression_test.v
This PR fix another error for 'in array of sumtype'  (fix #14439).
- Fix another error for 'in array of sumtype'.
- Add test.
```v
type TokenValue = rune | u64
fn main() {
val := `+`
if val in [TokenValue(`+`), TokenValue(`-`)] {
println("ok")
}
}
ok
```
> cgen: fix another error for 'in array of sumtype'  (fix #14439)

- vlib/v/parser/for.v
- vlib/v/tests/for_cond_test.v
This PR fix 'val in array' as condition in for stmt (fix #14440).
- Fix 'val in array' as condition in for stmt.
- Add test.
```v
type TokenValue = rune | u64
fn main() {
val := `+`
for val in [TokenValue(`+`), TokenValue(`-`)] {
println("ok")
break
}
}
ok
```
> parser: fix 'val in array' as condition in for stmt (fix #14440)

- vlib/v/parser/for.v
- vlib/v/parser/tests/for_val_in_array_err.out
- vlib/v/parser/tests/for_val_in_array_err.vv
This PR improve error messages of 'for val in array'.
- Improve error messages of 'for val in array'.
- Add test.
```v
type TokenValue = rune | u64
fn main() {
val := `+`
for val in [TokenValue(`+`), TokenValue(`-`)] {
println("ok")
break
}
}
./tt1.v:5:6: error: redefinition of value iteration variable `val`, use `for (val in array) {` if you want to check for a condition instead
4 |     val := `+`
5 |     for val in [TokenValue(`+`), TokenValue(`-`)] {
|         ~~~
6 |         println("ok")
7 |         break
```
> parser: improve error messages of 'for val in array'

- vlib/v/gen/c/auto_str_methods.v
This PR simplify auto_str_methods.v.
- `enum StrIntpType` is builtin type, so remove the same definition.
- Remove unused `type_to_str()`.
> cgen: simplify auto_str_methods.v

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/chain_calls_with_comments_expected.vv
- vlib/v/fmt/tests/chain_calls_with_comments_input.vv
This PR fix fmt error for chain calls with comments (fix #10590).
- Fix fmt error for chain calls with comments.
- Add test.
```v
fn main() {
options := cmdline
.only_options(args)
.filter(it != '-') // options, not including '-'
.map(if it.bytes().len>1{
1
})
println(options)
}
```
fmt to:
```v
fn main() {
options := cmdline
.only_options(args)
.filter(it != '-') // options, not including '-'
.map(if it.bytes().len > 1 {
1
})
println(options)
}
```
> fmt: fix fmt error for chain calls with comments (fix #10590)

- .github/workflows/v_apps_and_modules_compile.yml
- vlib/os/filepath.v
- vlib/os/filepath_test.v
- vlib/v/builder/builder.v
This pull request will add two new useful functions to the `os` module.
- norm_path
- abs_path
The `norm_path` function normalizes paths by resolving
resolving backlinks (..), eliminating redundant path separators 
and references to the current directories (.).
And the `abs_path` function joins the current working directory
with the path (if the path is relative)
and returns the absolute path representation.
> os: add norm_path and abs_path function

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/strings_name_variable_call_keep.vv
This PR fix 'strings' name variable call generate auto import (fix #9713).
- Fix 'strings' name variable call generate auto import.
- Add test.
```v
fn main() {
strings := 'hello'
a := strings.repeat(2)
println(a)
}
```
fmt to:
```v
fn main() {
strings := 'hello'
a := strings.repeat(2)
println(a)
}
```
> fmt: fix 'strings' name variable call generate auto import (fix #9713)

- vlib/v/checker/fn.v
- vlib/v/checker/tests/fn_type_mismatch.out
- vlib/v/tests/map_get_anon_fn_value_with_mut_arg_test.v
This PR fix map get anon fn value with mut argument (fix #14479).
- Fix map get anon fn value with mut argument.
- Add test.
```v
type Foo = map[int]fn (mut bar Bar) int
struct Bar {}
fn main() {
foo := Foo({
0: fn (mut bar Bar) int {
return 22
}
})
mut bar := Bar{}
ret := foo[0](mut bar)
println(ret)
}
22
```
> checker: fix map get anon fn value with mut argument (fix #14479)

- vlib/v/checker/fn.v
- vlib/v/checker/tests/method_call_arg_mismatch.out
- vlib/v/checker/tests/method_call_arg_mismatch.vv
This PR check method call argument type mismatch (fix #14490).
- Check method call argument type mismatch.
- Add test.
```v
struct Foo {}
fn (f Foo) bar(baz fn ()) {}
fn baz() {}
fn main() {
foo := Foo{}
foo.bar(baz())
}
./tt1.v:9:10: error: `baz()` (no value) used as value in argument 1 to `Foo.bar`
8 |     foo := Foo{}
9 |     foo.bar(baz())
|             ~~~~~
10 | }
```
> checker: check method call argument type mismatch (fix #14490)

- vlib/v/gen/c/cgen.v
- vlib/v/parser/expr.v
- vlib/v/tests/sizeof_test.v
This PR fix error for sizeof(c'hello') (fix #14499).
- Fix error for sizeof(c'hello').
- Add test.
```v
fn main() {
println(sizeof(c'hello'))
println(sizeof(r'hello'))
}
6
6
```
> parser: fix error for sizeof(c'hello') (fix #14499)

- vlib/v/gen/c/cgen.v
- vlib/v/tests/sizeof_test.v
This PR fix sizeof('str') and sizeof(r'str').
- Fix sizeof('str') and sizeof(r'str').
- Add test.
```v
fn main() {
println(sizeof(r'hello'))
println(sizeof(c'hello'))
println(sizeof('hello'))
}
16
6
16
```
> cgen: fix sizeof('str') and sizeof(r'str')

- vlib/v/parser/fn.v
- vlib/v/parser/tests/fn_decl_multi_return_types_err.out
- vlib/v/parser/tests/fn_decl_multi_return_types_err.vv
This PR check fn decl multi return types without parentheses (fix #14505).
- Check fn decl multi return types without parentheses.
- Add test.
```v
fn main() {
}
fn foo() int, int {
return 0, 0
}
./tt1.v:4:10: error: multiple return types in function declaration must use parentheses, .e.g (int, string)
2 | }
3 | 
4 | fn foo() int, int {
5 |     return 0, 0
6 | }
```
> parser: check fn decl multi return types without parentheses (fix #14505)

- vlib/v/fmt/tests/json_decode_fmt_keep.vv
- vlib/v/parser/fn.v
This PR fix fmt error for json decode (fix #10175).
- Fix fmt error for json decode.
- Add test.
```v
import json
struct Request {
a int
}
fn parse(s string) ?Request {
return json.decode(Request, s)
}
fn parse2(s string) ?Request {
req := json.decode(Request, s)?
return req
}
fn main() {
println(parse('{"a": 22} ')?)
println(parse2('{"a": 22} ')?)
}
```
keep fmt.
> parser: fix fmt error for json decode (fix #10175)

- vlib/v/checker/fn.v
- vlib/v/checker/tests/fn_call_arg_mismatch_err_c.out
- vlib/v/checker/tests/fn_call_arg_mismatch_err_c.vv
This PR check fn call with argument mismatch (fix #14514).
- Check fn call with argument mismatch.
- Add test.
```v
module main
import os
fn list_files() ?[][]string {
mut unchecked_files := os.ls('utilities/modules')?
println(unchecked_files)
for files in unchecked_files {
println(files)
if os.is_file(files) == true {
println(files)
} else {
println(os.ls(os.chdir(files)?)?)
}
println(files)
}
mut modules := [['Module:', 'Path:', 'Description']]
return modules
}
fn main() {
mut data := [
['Module:', 'Path:', 'Description'],
]
mods := list_files() or { [['null', 'null', 'null']] }
for _, mod in mods {
data << mod
}
}
./tt1.v:13:18: error: `os.chdir(files) ?` (no value) used as value in argument 1 to `os.ls`
11 |             println(files)
12 |         } else {
13 …
```
> checker: check fn call with argument mismatch (fix #14514)

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/generic_struct_init_keep.vv
This PR fix fmt of Ok<[]Token>{[]} (fix #13852).
- Fix fmt of Ok<[]Token>{[]}.
- Add test.
```v
module x
struct Ok<T> {
foo []T
}
fn test_fmt() {
r := Ok<[]Token>{[]}
}
```
vfmt keep.
> fmt: fix fmt of Ok<[]Token>{[]} (fix #13852)

- CONTRIBUTING.md
- vlib/v/embed_file/embed_file.v
- vlib/v/gen/c/embed.v
- vlib/v/parser/comptime.v
As discussed on Discord and in #14430.
~~I think an additional *dedicated* debug flag (for the debug print) might be overkill in this case.~~
(Edit: see comments below)
> embed_file: rename debug_embed_file_in_prod -> force_embed_file

- doc/docs.md
- vlib/v/ast/ast.v
- vlib/v/checker/check_types.v
- vlib/v/checker/checker.v
- vlib/v/checker/containers.v
- vlib/v/checker/fn.v
- vlib/v/checker/return.v
- vlib/v/checker/str.v
- vlib/v/checker/struct.v
- vlib/v/checker/tests/field_deprecations.out
- vlib/v/checker/tests/field_deprecations.vv
- vlib/v/checker/tests/module_with_structs_with_deprecated_fields/fields.v
- vlib/v/parser/struct.v
With this PR, if you try to use a module `abc`, containing this declaration:
```v
module abc
pub struct Xyz {
pub mut:
a int
b int [deprecated]
c int [deprecated: 'c use Xyz.a instead'; deprecated_after: '2021-03-01'] // past, turned into error
d int [deprecated: 'd use Xyz.a instead'; deprecated_after: '2999-03-01'] // far future, just a notice
}
```
... then trying to access one of the deprecated fields in abc.Xyz directly,
will produce either a notice, warning or an error, depending on whether the
deprecation date had already passed.
Note: unlike with functions/methods, field deprecations are *only* shown
for field accesses for external modules, i.e. the module itself can continue
to use the deprecated fields, without its users getting any deprecation
messages, if they do *NOT* access …
> v: add support for struct field deprecation

- vlib/v/fmt/tests/fn_types_list_ending_with_comma_expected.vv
- vlib/v/fmt/tests/fn_types_list_ending_with_comma_input.vv
- vlib/v/parser/parse_type.v
This PR fix fn return types list ending with comma (fix #13592).
- Fix fn return types list ending with comma.
- Add test.
```v
fn ok(a int,) (int, string,) {
return 11, 'hello'
}
fn main() {}
```
fmt to:
```v
fn ok(a int) (int, string) {
return 11, 'hello'
}
fn main() {}
```
> fmt: fix fn return types list ending with comma (fix #13592)

- vlib/v/parser/parser.v
- vlib/v/tests/match_case_with_struct_init_test.v
This PR fix match expr case with struct init (fix #14531).
- Fix match expr case with struct init.
- Add test.
```v
struct Get {}
struct Post {}
struct Part {
value string
}
type RoutePart = Get | Part | Post
fn main() {
route := [RoutePart(Get{}), RoutePart(Part{
value: '/'
})]
status_code := match route {
[RoutePart(Get{}), RoutePart(Part{
value: '/'
})] {
'200'
}
else {
'404'
}
}
print(status_code)
assert status_code == '200'
}
200
```
> parser: fix match expr case with struct init (fix #14531)

- vlib/v/checker/assign.v
- vlib/v/tests/assign_literal_with_closure_test.v
This PR fix declare assign literal with closure (fix #14539).
- Fix declare assign literal with closure.
- Add test.
```v
fn sma(period int) fn (f64) f64 {
mut i := 0
mut sum := 0.0
mut storage := []f64{len: 0, cap: period}
return fn [mut storage, mut sum, mut i, period] (input f64) f64 {
if storage.len < period {
sum += input
storage << input
}
sum += input - storage[i]
storage[i], i = input, (i + 1) % period
return sum / f64(storage.len)
}
}
fn main() {
sma3 := sma(3)
sma5 := sma(5)
println('x       sma3   sma5')
for x in [f64(1), 2, 3, 4, 5, 5, 4, 3, 2, 1] {
println('${x:5.3f}  ${sma3(x):5.3f}  ${sma5(x):5.3f}')
}
}
x       sma3   sma5
1.000  1.000  1.000
2.000  1.500  1.500
3.000  2.000  2.000
4.000  3.000  2.500
5.000  4.000  3.000
5.000  4.667  3.800
4.000 …
```
> checker: fix declare assign literal with closure (fix #14539)

- vlib/v/gen/c/assign.v
- vlib/v/parser/assign.v
- vlib/v/tests/cross_assign_with_parentheses_test.v
This PR fix cross assign with parentheses (fix #14540).
- Fix cross assign with parentheses.
- Add test.
```v
import math
const ep = 1e-14
fn agm(aa f64, gg f64) f64 {
mut a, mut g := aa, gg
for math.abs(a - g) > math.abs(a) * ep {
a, g = (a + g) * .5, math.sqrt(a * g)
}
return a
}
fn main() {
ret := agm(1.0, 1.0 / math.sqrt2)
println(ret)
assert ret == 0.8472130847939792
}
0.8472130847939792
```
> parser, cgen: fix cross assign with parentheses (fix #14540)

- vlib/v/ast/str.v
- vlib/v/checker/tests/fn_call_arg_mismatch_err_c.out
This PR fix call_expr.str() with propagate_option or propagate_result.
- Fix call_expr.str() with propagate_option or propagate_result.
- Modify test.
```v
module main
import os
fn list_files() ?[][]string {
mut unchecked_files := os.ls('utilities/modules')?
println(unchecked_files)
for files in unchecked_files {
println(files)
if os.is_file(files) == true {
println(files)
} else {
println(os.ls(os.chdir(files)?)?)
}
println(files)
}
mut modules := [['Module:', 'Path:', 'Description']]
return modules
}
fn main() {
mut data := [
['Module:', 'Path:', 'Description'],
]
mods := list_files() or { [['null', 'null', 'null']] }
for _, mod in mods {
data << mod
}
}
./tt1.v:13:18: error: `os.chdir(files)?` (no value) used as value in argument 1 to `os.ls`
11 | …
```
> ast: fix call_expr.str() with propagate_option or propagate_result

- vlib/v/gen/c/assign.v
- vlib/v/tests/assign_literal_with_closure_test.v
This PR fix cross assign in closure.
- Fix cross assign in closure.
- Add test.
```v
fn sma(period int) fn (f64) f64 {
mut i := 0
mut sum := 0.0
mut storage := []f64{len: 0, cap: period}
return fn [mut storage, mut sum, mut i, period] (input f64) f64 {
if storage.len < period {
sum += input
storage << input
}
sum += input - storage[i]
storage[i], i = input, (i + 1) % period
return sum / f64(storage.len)
}
}
fn main() {
sma3 := sma(3)
sma5 := sma(5)
println('x       sma3   sma5')
for x in [f64(1), 2, 3, 4, 5, 5, 4, 3, 2, 1] {
println('${x:5.3f}  ${sma3(x):5.3f}  ${sma5(x):5.3f}')
}
assert true
}
x       sma3   sma5
1.000  1.000  1.000
2.000  1.500  1.500
3.000  2.000  2.000
4.000  3.000  2.500
5.000  4.000  3.000
5.000  4.667  3.800
4.000  4.667  4.200
3.000 …
```
> cgen: fix cross assign in closure

- vlib/v/fmt/tests/cast_or_dump_arg_ending_with_comma_expected.vv
- vlib/v/fmt/tests/cast_or_dump_arg_ending_with_comma_input.vv
- vlib/v/parser/expr.v
- vlib/v/parser/parser.v
This PR fix cast or dump arguments ending with comma (fix #14551).
- Fix cast or dump arguments ending with comma.
- Add test.
```v
fn main() {
println(u8(1,),)
dump(1,)
}
```
vfmt to:
```v
fn main() {
println(u8(1))
dump(1)
}
```
> parser: fix cast or dump arguments ending with comma (fix #14551)

- vlib/v/scanner/scanner.v
- vlib/v/tests/string_interpolation_inner_cbr_test.v
This PR fix string interpolation with inner curly braces (fix #12242).
- Fix string interpolation with inner curly braces.
- Add test.
```v
struct St {}
fn foo() ?int { return 22 }
fn main() {
println('${ foo() or { 11 } }')
println('${ St{} }')
println('${ {'a': 1} }')
}
22
St{}
{'a': 1}
```
> scanner: fix string interpolation with inner curly braces (fix #12242)

- cmd/tools/vpm.v
- examples/concurrency/concurrency_http.v
- examples/fetch.v
- examples/get_weather/get_weather.v
- examples/http_server.v
- examples/net_t.v
- examples/news_fetcher.v
- vlib/net/http/chunked/dechunk.v
- vlib/net/http/download.v
- vlib/net/http/http.v
- vlib/net/http/http_httpbin_test.v
- vlib/net/http/http_test.v
- vlib/net/http/response.v
- vlib/net/http/response_test.v
- vlib/net/http/server.v
- vlib/net/http/server_test.v
- vlib/vweb/tests/vweb_test.v
- vlib/vweb/vweb.v
- vlib/vweb/vweb_app_test.v
- vlib/x/json2/README.md
closes #14477 
I've just made the `.text` field deprecated
> net.http: `Response.text` -> `Response.body`

- vlib/v/checker/tests/overload_return_type.out
- vlib/v/checker/tests/overload_return_type.vv
This PR vfmt overload_return_type.vv.
- `mut one := Point {x:1, y:2}` should be `mut one := Point{x:1, y:2}`.
before:
```
struct Point {
mut:
x int
y int
}
fn (a Point) +(b Point) int {
return a.x + b.x
}
fn main() {
mut one := Point {x:1, y:2}
mut two := Point {x:5, y:1}
two = one + two
}
```
vfmt to:
```v
struct Point {
mut:
x int
y int
}
fn (a Point) + (b Point) int {
return a.x + b.x
}
fn main() {
mut one := Point{
x: 1
y: 2
}
mut two := Point{
x: 5
y: 1
}
two = one + two
}
```
> checker: vfmt overload_return_type.vv

- vlib/os/filepath.v
- vlib/os/filepath_test.v
This PR adds the proposed function `existing_path` from @JalonSolov  to the `os` module. The function checks all parts of the given path for their existence and returns the existing part.
Here are a few examples:
```v
os.existing_path('/my/existing/path/OOF/this/does/not/exist') // returns: '/my/existing/path'
```
```v
os.existing_path('this/does/not/exist') // returns: ''
```
```v
os.existing_path('/myTYPO/existing/path') // returns: '/'
```
Of course, this also works for Windows paths...
Thanks to @JalonSolov  for the great idea! :slightly_smiling_face:
> os: add existing_path function

- vlib/v/checker/checker.v
- vlib/v/gen/c/if.v
- vlib/v/tests/array_index_optional_with_if_expr_test.v
This PR fix array index optional with if expr (fix #12197).
- Fix array index optional with if expr.
- Add test.
```v
fn main() {
ret := []string{}[0] or {
if true { 'a' } else { 'b' }
}
println(ret)
assert ret == 'a'
}
a
```
> checker, cgen: fix array index optional with if expr (fix #12197)

- .github/workflows/v_apps_and_modules_compile.yml
I disabled the failing part of the failing test on Go2V's side, it makes way more sense to do so.
https://github.com/vlang/go2v/commit/9756059a91c7f9e339970a9747c597f1e69bc340
> ci: re-enable Go2V test suite

- vlib/v/gen/c/fn.v
- vlib/v/gen/c/testdata/alias_interface_method_call.vv
- Fix #14568, fix alaised type method call on interface is not being unaliased.
- Add output test:
```v
import io { Reader }
type Decoder = Reader
fn (mut d Decoder) decode(len int) ?[]u8 {
mut buf := []u8{len: len}
d.read(mut buf)?
return buf
}
```
> cgen: fix type not being unaliased (Fix #14568)

- vlib/os/os.v
- vlib/os/os_test.v
Right **now** the `os.file_ext` function handles file extensions as follows:
```v
assert os.file_ext('file.v') == '.v'  // ok
assert os.file_ext('.') == '.'      // wrong imo
assert os.file_ext('.git') == '.git' // wrong imo
assert os.file_ext('file.') == '.'  // wrong imo
assert os.file_ext('..') == '.'  // wrong imo
```
In my eyes a file extension is a file extension if there is something in prefix to the `.` (otherwise it would not be an *extension*).
My fix would do the following:
```v
assert os.file_ext('file.v') == '.v'
assert os.file_ext('.') == '' 
assert os.file_ext('.git') == '' 
assert os.file_ext('file.') == ''
assert os.file_ext('..') == ''
```
> os: fix file_ext function

- vlib/v/ast/str.v
This PR fix IfExpr.str().
before: (missing `{` after else).
`if true { 'a' } else 'b' }`
now:
`if true { 'a' } else { 'b' }`
> ast: fix IfExpr.str()

- cmd/tools/vrepl.v
- vlib/v/tests/repl/error_exitasdfasdf.repl
This PR fix error for exitasdfasdf in repl (fix #14593).
- Fix error for exitasdfasdf in repl.
- Add test.
```v
>>> exitasdfasdf
error: undefined ident: `exitasdfasdf`
6 |
7 | println(exitasdfasdf)
>>>
```
> vrepl: fix error for exitasdfasdf in repl (fix #14593)

- vlib/v/ast/ast.v
- vlib/v/checker/checker.v
This PR makes minor cleanup in is_lit().
- Rename `is_lit()` to `is_pure_literal()`.
- Add missing `FloatLiteral`.
- Modify related calls.
> ast: minor cleanup in is_lit()

- thirdparty/sokol/sokol_audio.h
For me, the issue was that sound was only played with my speakers, but not my headset.
I haven't applied all changes from the latest sokol since it would need some reworking of the malloc/free system.
> sokol: apply bug fix from latest upstream sokol_audio.h

- vlib/json/json_test.v
- vlib/v/gen/c/json.v
This PR fix json decode with missing map type field (fix #13412).
- Fix json decode with missing map type field.
- Add test.
```v
import json
struct Info {
id    int
items []string
maps  map[string]string
}
fn main() {
info := json.decode(Info, '{"id": 22, "items": null}')?
println(info)
assert info.id == 22
assert '$info.items' == '[]'
assert '$info.maps' == '{}'
}
Info{
id: 22
items: []
maps: {}
}
```
> json: fix json decode with missing map type field (fix #13412)

- vlib/v/checker/fn.v
- vlib/v/checker/tests/fn_ref_arg_mismatch_err.out
- vlib/v/checker/tests/fn_ref_arg_mismatch_err.vv
This PR check using literal argument as reference parameter  (fix #14296).
- Check using literal argument as reference parameter.
- Add test.
```v
module main
struct Foo<T> { }
fn (f &Foo<T>) foo(a &T) {
println(a)
}
fn bar<T>(a &T) {
println(a)
}
fn main() {
foo := Foo<int>{}
foo.foo(12)
bar<int>(12)
}
./tt1.v:15:10: error: literal argument cannot be passed as reference parameter `&T`
13 | fn main() {
14 |     foo := Foo<int>{}
15 |     foo.foo(12)
|             ~~
16 |
17 |     bar<int>(12)
./tt1.v:17:11: error: literal argument cannot be passed as reference parameter `&T`
15 |     foo.foo(12)
16 |
17 |     bar<int>(12)
|              ~~
18 | }
```
> checker: check using literal argument as reference parameter  (fix #14296)

- vlib/builtin/array_test.v
- vlib/v/gen/c/array.v
- vlib/v/gen/c/testdata/array_init_no_error.vv
- fix #14679, fix array init with it when initializing an default array.
- Add output test (no error test):
```v
// From issue #14679
fn iterate_linear(value1 u32, value2 u32, length u32) []u32 {
step := u32((value2 - value1) / (length - 1))
return []u32{len: int(length), init: value1 + step * u32(it + 1)}
}
pub fn iterate_rect_single(val1 u32, val2 u32, val3 u32, val4 u32, width u32, height u32) [][]u32 {
left := iterate_linear(val1, val3, height)
right := iterate_linear(val2, val4, height)
return [][]u32{len: int(width), init: iterate_linear(left[it], right[it], width)}
}
```
> cgen: fix array init with it (fix #14679)

- vlib/v/gen/c/index.v
- vlib/v/tests/nested_map_index_test.v
This PR fix nested map index check (fix #14683).
- Fix nested map index check.
- Add test.
```v
struct Foo {
mut:
foo map[int]Bar
}
struct Bar {
mut:
bar map[int]string
}
fn main() {
f := Foo{
foo: {
11: Bar{
bar: {
22: 'hello'
}
}
}
}
ret := f.foo[11]?.bar[22]?
println(ret)
assert ret == 'hello'
}
hello
```
```v
import encoding.binary as bin
[heap]
struct NMachine {
mut:
threads shared map[u16]NThread
pub mut:
modules   map[u64]NModule
constants shared map[u64]NStackValue
}
pub struct NModule {
pub mut:
functions map[u64]NFunction
constants map[u64]NStackValue
}
[heap]
pub struct NFunction {
pub mut:
labels map[u64]int
mut:
code []u8
}
[heap]
pub struct NThread {
pub mut:
last_index     int
current_module u64
mut:
stack NStack
}
pub type NStackValue = []u8 | u8 …
```
> cgen: fix nested map index check (fix #14683)

- vlib/v/gen/c/cgen.v
- vlib/v/tests/generics_interface_with_non_generic_method_test.v
This PR fix generic interface with non-generic method (fix #14692).
- Fix generic interface with non-generic method.
- Add test.
```v
module main
interface TypeFactory<T> {
get_type(type_name string) T
}
enum NodeType {
unknown
expression
statement
literal
}
struct EnumTypeFactory {}
fn (f EnumTypeFactory) get_type(type_name string) NodeType {
return match type_name {
'expression' { NodeType.expression }
'statement' { NodeType.statement }
'literal' { NodeType.literal }
else { NodeType.unknown }
}
}
struct Node<T> {
factory   TypeFactory<T>
type_name NodeType
}
fn new_node<T>(type_name string, factory TypeFactory<T>) Node<T> {
return Node<T>{
factory: factory
type_name: factory.get_type(type_name)
}
}
fn main() {
root1 := new_node<NodeType>('literal', EnumTypeFactory{})
println(root1) …
```
> cgen: fix generic interface with non-generic method (fix #14692)

- vlib/v/gen/c/cgen.v
- vlib/v/tests/generics_interface_with_non_generic_method_test.v
This PR fix cast to generic interface (fix #14699).
- Fix cast to generic interface.
- Add test.
```v
module main
interface TypeFactory<T> {
get_type(type_name string) T
}
enum NodeType {
unknown
expression
statement
literal
}
struct EnumTypeFactory {}
fn (f &EnumTypeFactory) get_type(type_name string) NodeType {
return match type_name {
'expression' { NodeType.expression }
'statement' { NodeType.statement }
'literal' { NodeType.literal }
else { NodeType.unknown }
}
}
struct RawNode {
type_name string
}
struct Node<T> {
factory   TypeFactory<T>
type_name NodeType
raw_node  RawNode
}
fn new_node<T>(factory TypeFactory<T>, raw_node RawNode) ?Node<T> {
return Node<T>{
factory: factory
type_name: factory.get_type(raw_node.type_name)
raw_node: raw_node
}
}
fn program<T>(factory TypeFactory<T>) …
```
> cgen: fix cast to generic interface (fix #14699)

- vlib/term/ui/README.md
The event data flickers on the screen. Video in referenced issue. Seems like this line was meant for debugging but never removed?
> term.ui: don't print event data in readme example (vlang#14719)

- vlib/v/checker/tests/generic_type_name_in_non_generic_function.out
- vlib/v/parser/expr.v
- vlib/v/parser/if_match.v
- vlib/v/parser/parser.v
This PR check undefined ident in if expr using generic type name (fix #14717).
- Check undefined ident in if expr using generic type name.
- Modify test.
```v
fn main() {
c := u8(`D`)
if c >= A && c <= Z {
println('yes')
} else {
println('no')
}
}
./tt1.v:4:10: error: undefined ident: `A`
2 |     c := u8(`D`)
3 | 
4 |     if c >= A && c <= Z {
|             ^
5 |         println('yes')
6 |     } else {
```
> parser, checker: check undefined ident in if expr using generic type name (fix #14717)

- vlib/v/depgraph/depgraph.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/json.v
This PR implement sorting globals and consts definitions.
now `json` and `rand` module have problems to fix.
```v
const (
weapon_keys = [&foo, &bar]!
foo         = u32(1)
bar         = u32(2)
)
fn main() {
println(weapon_keys)
assert weapon_keys[0] == &foo
assert weapon_keys[1] == &bar
}
[1, 2]
```
c2v:
```v
PS D:\Test\v\c2v_out> v -o "doom.o" -w -translated .
C:/Users/yuyi9/AppData/Local/Temp/v_0/doom.o.10437404920755315205.tmp.c:574: warning: WINVER redefined
C:/Users/yuyi9/AppData/Local/Temp/v_0/doom.o.10437404920755315205.tmp.c:8597: error: incompatible types for redefinition of 'LoadMenuW'
...
builder error:
```
> cgen: implement sorting globals and consts definitions

- vlib/v/gen/c/cgen.v
This PR makes minor cleanup for sort globals and consts.
- Remove useless `g.stringliterals`.
> cgen: minor cleanup for sort globals and consts

- vlib/v/gen/native/arm64.v
Implement the `neg()` function of the amd64 generator for arm64.
> native: implement  `neg()` for arm64

- vlib/v/checker/tests/selector_expr_assign.out
- vlib/v/parser/assign.v
This PR correct error message for seclector_expr_assign.vv (fix #14744).
- Correct error message for seclector_expr_assign.vv.
```v
struct Abc {
a int
}
fn main() {
abc := Abc{}
abc.a := 2
}
./tt1.v:7:8: error: use assignment `=` instead of declaration `:=` when modifying struct fields
6 |     abc := Abc{}
7 |     abc.a := 2
|           ~~
8 | }
```
> parser: correct error message for selector_expr_assign.vv (fix #14744)

- vlib/net/websocket/websocket_test.v
- vlib/v/ast/types.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/const_array_init_order_test.v
- vlib/v/tests/const_function_call_init_order_test.v
This PR sort const array init order (fix #14748).
- Sort const array init order.
- Add test.
```v
const (
cst3 = [[[cst1, cst2]]]
cst1 = [11]
cst2 = [22]
)
fn main() {
println(cst3)
assert cst3 == [[[[11], [22]]]]
}
[[[[11], [22]]]]
```
> cgen: sort const array init order (fix #14748)

- vlib/v/ast/table.v
- vlib/v/checker/fn.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/const_call_expr_order_test.v
This PR sort consts with call expr (fix #14748).
- Sort consts with call expr.
- Add test.
```v
import os
const (
shdc_exe_name = 'sokol-shdc.exe'
tool_name     = os.file_name(os.executable())
cache_dir     = os.join_path(os.cache_dir(), 'v', tool_name)
shdc          = shdc_exe()
)
fn main() {
dump(cache_dir)
dump(shdc)
}
fn shdc_exe() string {
return os.join_path(cache_dir, shdc_exe_name)
}
[.\\tt1.v:11] main.cache_dir: C:\Users\yuyi9\.cache\v\tt1.exe
[.\\tt1.v:12] main.shdc: C:\Users\yuyi9\.cache\v\tt1.exe\sokol-shdc.exe
```
```v
const (
cst3 = [[[cst1, cst2]]]
cst1 = [11]
cst2 = [22]
)
fn main() {
println(cst3)
assert cst3 == [[[[11], [22]]]]
}
[[[[11], [22]]]]
```
> ast, checker, cgen: sort consts with call expr (fix #14748)

- vlib/v/gen/c/cgen.v
This PR simplify sorting globals and consts.
- Remove `line` field of GlobalConstDef.
> cgen: simplify sorting globals and consts

- vlib/v/util/util.v
This PR optimize in launch_tool().
- Add a retry mechanism for the occasional command execution failure.
The original multi-tasking tests produced the following errors.
```v
FAIL  [  41/1022]  8766.738 ms vlib/builtin/js/int_test.js.v
failed    cmd: "D:\v\v.exe" -skip-unused "D:\v\cmd\tools\builders\js_builder.v"
failed   code: 1
C:/Users/yuyi9/AppData/Local/Temp/v/test_session_65330900/js_builder.505065901838222281.tmp.c:69435: warning: cast between pointer and integer of different size
tcc: error: could not write 'D:\v\cmd\tools\builders\js_builder.exe': Permission denied
...
builder error:
This is a compiler bug, please report it using `v bug …
```
> util: optimize in launch_tool()

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/testdata/embed.c.must_have
- vlib/v/gen/c/testdata/embed_with_prod.c.must_have
- vlib/v/gen/c/testdata/embed_with_prod_zlib.c.must_have
This PR format module_init generated c codes.
before:
```v
{ // Initializations for module strings :
}
{ // Initializations for module math.bits :
_const_math__bits__overflow_error = _SLIT("Overflow Error");
_const_math__bits__divide_error = _SLIT("Divide Error");
_const_math__bits__de_bruijn32tab = new_array_from_c_array(32, 32, sizeof(u8), _MOV((u8[32]){
((u8)(0)), 1, 28, 2, 29, 14, 24, 3, 30,
22, 20, 15, 25, 17, 4, 8, 31,
27, 13, 23, 21, 19, 16, 7, 26,
12, 18, 6, 11, 5, 10, 9}));
...
```
format to:
```v
// Initializations for module math.bits
_const_math__bits__overflow_error = _SLIT("Overflow Error");
_const_math__bits__divide_error = _SLIT("Divide Error");
_const_math__bits__de_bruijn32tab = new_array_from_c_array(32, 32, sizeof(u8), _MOV((u8[32]){
((u8)(0)), 1, 28, 2, 29, 14, 24, 3, …
```
> cgen: format module_init generated c codes

- doc/docs.md
Hello,
This is a really cool project! Noticed a typo while reading the documentation. 😃 
Best,
Danilo Lekovic
> doc: fix 'specifing' typo

- cmd/tools/vmissdoc.v
#14773 
Fix Vmissdoc to ignore attributes
The PR adds a simple filter to remove the attributes from checking, fixing the cases where docs are present  but an attribute is in between the documented object.
> tool/vmissdoc: Filter out attributes, when missdoc is run

- vlib/v/ast/table.v
- vlib/v/tests/array_of_reference_sumtype_append_test.v
This PR fix array of reference sumtype appending (fix #14794).
- Fix array of reference sumtype appending.
- Add test.
```v
struct Element {
AbstractNode
attributes []&Attribute
}
struct Attribute {
AbstractNode
name  string
value string
}
pub type Node = Attribute | Element
struct AbstractNode {
pub mut:
child_nodes []&Node
}
pub fn (mut n AbstractNode) append_child(child &Node) {
n.child_nodes << child
}
fn main() {
mut parent := &Element{
name: 'parent'
}
mut child := &Element{
name: 'child'
}
parent.append_child(child)
dump(parent)
assert parent.child_nodes[0].name == 'child'
}
[.\\tt1.v:33] parent: &Element{
AbstractNode: AbstractNode{
child_nodes: [Node(Element{
AbstractNode: AbstractNode{
child_nodes: []
}
name: 'child'
attributes: []
})] …
```
> ast: fix array of reference sumtype appending (fix #14794)

- vlib/v/checker/fn.v
This PR makes cleanup in `checker.fn_decl()`.
> checker: cleanup in fn_decl()

- vlib/clipboard/clipboard_windows.c.v
This PR makes clipboard.Clipboard public on windows.
- To fix vui errors on windows.
> clipboard: make clipboard.Clipboard public on windows

- vlib/encoding/csv/reader.v
This will fix the following implementation on VTL. Link [here](https://github.com/vlang/vtl/runs/6977385326?check_suite_focus=true).
It is needed to have the struct public so it is possible to write a Database loader around it.
> encoding: Make csv.Reader public

- vlib/v/gen/c/array.v
- vlib/v/tests/array_of_reference_sumtype_test.v
This PR fix array of reference sumtype index()  (fix #14801).
- Fix array of reference sumtype index().
- Add test.
```v
struct Element {
AbstractNode
mut:
value      string
attributes []&Attribute
}
struct Attribute {
AbstractNode
mut:
name  string
value string
}
pub type Node = Attribute | Element
struct AbstractNode {
pub mut:
child_nodes []&Node
}
pub fn (mut n AbstractNode) append_child(child &Node) {
n.child_nodes << child
}
pub fn (n &AbstractNode) has_child(child &Node) int {
return n.child_nodes.index(child)
}
fn main() {
mut parent := &Element{
name: 'parent'
}
mut child := &Element{
name: 'child'
}
parent.append_child(child)
ret := parent.has_child(child)
println(ret)
dump(parent)
assert parent.child_nodes[0].name == 'child'
assert ret == 0
}
PS D:\Test\v\tt1> …
```
> cgen: fix array of reference sumtype index()  (fix #14801)

- vlib/vweb/vweb.v
remove the extra '/' when calling scan_static_directory, or the moun_path will be '//$file'.
Tests pasted with examples\vweb\server_sent_events.
I found this bug when running this example too , static files in assets/  were not served , because the mount_path being '//assets'.
Removing the extra '\' , it  worked correctly.
> fix scan_static_directory 

- .github/workflows/other_ci.yml
- .github/workflows/v_apps_and_modules_compile.yml
- .github/workflows/vab_ci.yml
Since github does show the status of failed tasks as OK, with `continue-on-error: true`
using it can and did hide important errors after bigger V changes (like the new pub
requirement for private C. types, used in external modules).
This removes that attribute, to see what the failures are, so that they can be fixed quicker.
> ci: remove `continue-on-error: true` for most ci jobs

- vlib/v/parser/fn.v
- vlib/v/parser/tests/closure_var_name_conflict.out
- vlib/v/parser/tests/closure_var_name_conflict.vv
This PR check closure var name conflict (fix #14787).
- Check closure var name conflict.
- Add test.
```v
fn main() {
x := 1
y := fn [x] (x int) {
println(x)
}
y(x)
y(2)
}
./tt1.v:4:15: error: the parameter name `x` conflicts with the captured value name
2 |     x := 1
3 | 
4 |     y := fn [x] (x int) {
|                  ^
5 |         println(x)
6 |     }
```
> parser: check closure var name conflict (fix #14787)

- .github/workflows/native_backend_tests.yml
- vlib/v/gen/native/macho.v
PD: This patch has been tested on:
> native: Fix macho generation for macos11-amd64

- vlib/v/gen/c/auto_str_methods.v
- vlib/v/tests/string_array_of_ref_type_test.v
This PR fix auto string method generated for []&int{len:1} (fix #14786).
- Fix auto string method generated for []&int{len:1}.
- Add test.
```v
fn main() {
a := []&int{len: 2}
println(a)
assert '$a' == '[nil, nil]'
}
[nil, nil]
```
> cgen: fix auto string method generated for []&int{len:1} (fix #14786)

- .github/workflows/ci_cross.yml
- vlib/os/os_android.c.v
I was trying to fix a [JNI interop bug](https://github.com/Larpon/jni/runs/6998834197?check_suite_focus=true#step:10:65) that was introduced with the recent `pub` changes and decided to clean up the code a bit.
`os.NativeActivity` can now be used instead of `C.ANativeActivity`.
I've tested that `read_apk_asset` still works by running the `examples/sokol/06_obj_viewer` which uses it to load the default V model.
(`vab -v 1 --log --device auto run path/to/v/examples/sokol/06_obj_viewer`)
> os: improve Android interop

- vlib/v/gen/c/cgen.v
This PR format cgen.init() generated c codes.
before:
```v
// V cheaders:
// Generated by the V compiler
#if defined(__TINYC__) && defined(__has_include)
// tcc does not support has_include properly yet, turn it off completely
#undef __has_include
#endif
#if defined(__has_include)
```
format to:
```v
// V cheaders:
// Generated by the V compiler
#if defined(__TINYC__) && defined(__has_include)
// tcc does not support has_include properly yet, turn it off completely
#undef __has_include
#endif
#if defined(__has_include)
```
> cgen: format cgen.init() generated c codes

- vlib/builtin/string.v
- vlib/builtin/string_test.v
Adding contains_only method to complement contains_any. Added tests and made sure it was functionally similar, for example
```vlang
assert !''.contains_any('')
assert !''.contains_only('')
```
Both work fine.
\- Liam
> builtin: created contains_only builtin method on string

- vlib/os/os.c.v
- vlib/os/os_windows.c.v
As @JalonSolov mentioned (https://github.com/vlang/v/pull/14835#discussion_r904465164), `.cmd` is also a valid extension for batch files (I think).
> os: add `.cmd` to list of Windows executable suffixes

- vlib/v/checker/checker.v
- vlib/v/checker/tests/cast_sumtype_err.out
- vlib/v/checker/tests/cast_sumtype_err.vv
This PR check error for cast sumtype (fix #14771).
- Check error for cast sumtype.
- Add test.
```v
module main
type Test = int | u32 | f32
fn main() {
data := Test(12)
eprintln(int(data))
}
./tt1.v:7:14: error: cannot cast `Test` to `int`, please use `as` instead, .e.g `expr as Ident`
6 |     data := Test(12)
7 |     eprintln(int(data))
|              ~~~~~~~~~
8 | }
```
> checker: check error for cast sumtype (fix #14771)

- vlib/v/checker/checker.v
- vlib/v/checker/tests/chan_elem_type_unknown.out
- vlib/v/checker/tests/chan_elem_type_unknown.vv
This PR check unknown chan element type (fix #14775).
- Check unknown chan element type.
- Add test.
```v
fn main() {
_ := chan NonExistingType{}
}
./tt1.v:2:7: error: unknown type `NonExistingType`
2 |     _ := chan NonExistingType{}
|          ~~~~~~~~~~~~~~~~~~~~~~
3 | }
```
> checker: check unknown chan element type (fix #14775)

- vlib/v/checker/fn.v
- vlib/v/tests/array_of_alias_pop_test.v
This PR fix error for aliases_of_array.pop() (fix #14860).
- Fix error for aliases_of_array.pop().
- Add test.
```v
[heap]
struct Attribute {
mut:
name  string
value string
}
type AttributeStack = []&Attribute
fn main() {
mut stack := AttributeStack([]&Attribute{})
stack << &Attribute{'foo', 'bar'}
ret := stack.pop()
println(ret)
assert ret.name == 'foo'
assert ret.value == 'bar'
}
&Attribute{
name: 'foo'
value: 'bar'
}
```
> checker: fix error for aliases_of_array.pop() (fix #14860)

- vlib/v/parser/struct.v
- vlib/v/parser/tests/interface_name_err.out
- vlib/v/parser/tests/interface_name_err.vv
This PR check interface name using single letter capital  (fix #14005).
- Check interface name using single letter capital.
- Add test.
```v
interface A {
a int
b() int
}
struct Ba {
a int
}
fn (b &Ba) b() int {
return b.a
}
fn main() {
a := &Ba{
a: 1
}
b := A(a)
}
./tt1.v:1:11: error: single letter capital names are reserved for generic template types.
1 | interface A {
|           ^
2 |     a int
3 |     b() int
```
> parser: check interface name using single letter capital  (fix #14005)

- vlib/v/ast/ast.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/chan_elem_type_unknown.out
- vlib/v/parser/parser.v
This PR add elem_type_pos in struct ChanInit (related #14775).
- Add elem_type_pos in struct ChanInit.
- Modify test.
```v
fn main() {
_ := chan NonExistingType{}
}
./tt1.v:2:12: error: unknown type `NonExistingType`
2 |     _ := chan NonExistingType{}
|               ~~~~~~~~~~~~~~~
3 | }
```
> ast: add elem_type_pos in struct ChanInit (related #14775)

- vlib/v/checker/struct.v
- vlib/v/checker/tests/struct_field_init_with_void_expr_err.out
- vlib/v/checker/tests/struct_field_init_with_void_expr_err.vv
This PR check struct field init with void expression (fix #13944).
- Check struct field init with void expression.
- Add test.
```v
import cli { Command }
import os
struct App {}
fn (a App) test_func() {}
fn main() {
mut cmd := Command{
name: 'cli'
version: '0.0.1'
}
app := App{}
mut add := Command{
name: 'add'
description: 'Add something.'
execute: app.test_func()
}
cmd.add_command(add)
cmd.setup()
cmd.parse(os.args)
}
./tt1.v:19:3: error: `app.test_func()` (no value) used as value
17 |         name: 'add'
18 |         description: 'Add something.'
19 |         execute: app.test_func()
|         ~~~~~~~~~~~~~~~~~~~~~~~~
20 |     }
21 |
```
> checker: check struct field init with void expression (fix #13944)

- vlib/crypto/README.md
Very useful and didactic example implementing "crypto.hmac" and "crypto.sha256". 
The data used match with data presented on the website "https://jwt.io/"
> docs: common jwt example

- vlib/v/parser/parser.v
- vlib/v/parser/tests/const_decl_err.out
- vlib/v/parser/tests/const_decl_err.vv
This PR check const declaration using multiple assign (fix #5125).
- Check const declaration using multiple assign.
- Add test.
```v
fn foo() (int, int, int) {
return 1, 2, 3
}
const (
a, b, c = foo()
)
fn main() {
println("$a $b $c")
}
./tt1.v:6:3: error: const declaration do not support multiple assign yet
4 |
5 | const (
6 |     a, b, c = foo()
|      ^
7 | )
8 |
```
> parser: check const declaration using multiple assign (fix #5125)

- vlib/v/parser/parser.v
- vlib/v/parser/tests/type_decl_name_err.out
- vlib/v/parser/tests/type_decl_name_err.vv
This PR fix the incorrect location of the type declaration name.
- Fix the incorrect location of the type declaration name.
- Add test.
```v
type A = int | string
fn main() {
a := A(11)
println(a)
}
./tt1.v:1:6: error: single letter capital names are reserved for generic template types
1 | type A = int | string
|      ^
2 | 
```
> parser: fix the incorrect location of the type declaration name

- vlib/v/fmt/struct.v
- vlib/v/fmt/tests/import_with_symbol_of_struct_keep.vv
This PR fix fmt error for import with symbol of struct (fix #14889).
- fix fmt error for import with symbol of struct.
- Add test.
fmt keep:
```v
import datatypes { Stack }
fn main() {
stack := Stack<int>{}
}
```
> fmt: fix import with symbol of struct (fix #14889)

- CHANGELOG.md
Fixed 0.2.4 heading (had leading `-` causing inconsistent formatting)
> Fixed 0.2.4 heading

- vlib/v/fmt/struct.v
This PR makes a minor optimization in struct.v.
- Avoid import `mathutil` just for max/min.
> fmt: minor optimization in struct.v

- doc/docs.md
Added a quick note on required mingw gcc package install for cross-compilation.
> added mingw-w64 note to docs.md

- vlib/v/builder/cc.v
This PR fix cross compiling for linux on windows (fix #6241, fix #12922).
- Fix cross compiling for linux on windows.
- `gc` mode now cannot successfully compiled.
```v
fn main() {
println('hello, world')
}
PS D:\Test\v\tt1> v -gc none -os linux .
D:\Test\v\tt1\tt1 has been successfully compiled
```
test on ubuntu:
> builder: fix cross compiling for linux on windows (fix #6241, fix #12922)

- README.md
I saw online some concern that we don't properly acknowledge TCC, specifically Fabrice, nor link to his page anywhere.  I believe this is a valid comment since the success of V is in part due to his work.
> added TCC acknowledgement

- vlib/v/pkgconfig/pkgconfig.v
- vlib/v/pkgconfig/test_samples/hogweed.pc
- vlib/v/pkgconfig/test_samples/nettle.pc
Fix parsing comments appearing mid-line.
Currently:
```
$ ./bin/bin /lib/pkgconfig/hogweed.pc
could not resolve dependency #
```
> v.pkgconfig: fix parsing mid-line comments

- vlib/v/gen/c/assign.v
- vlib/v/tests/results_multi_return_test.v
This PR fix error for result multi_return (fix #14932).
- Fix error for result multi_return.
- Add test.
```v
struct Err {
msg  string
code int
}
fn (e Err) msg() string {
return e.msg
}
fn (e Err) code() int {
return e.code
}
fn foo() ?string {
return 'foo'
}
fn bar() !(string, int) {
a := foo() or { return IError(Err{
msg: 'error test'
}) }
return a, 1
}
fn main() {
b, _ := bar() or { panic(err) }
println(b)
assert b == 'foo'
}
foo
```
> cgen: fix error for result multi_return (fix #14932)

- CHANGELOG.md
> docs: fix typo in CHANGELOG

- .github/workflows/c2v.yml
Adds a copy of c2v's `doom-regressions` CI step to check if V causes DOOM runtime errors
> ci: add runtime DOOM checks via vgret

- vlib/sqlite/README.md
- vlib/sqlite/sqlite.v
The current behavior of exec_none merely discards the row data array from the call to exec, and therefore calls to exec_none will still walk the row result data for no reason, affecting performance.
This revised exec_none performs only what's required (execute the database statement, and return the int code)
Also added a couple tips to the README in regards to increasing performance when performing a large number of exec calls (i.e. 300K insertions, etc).
> change exec_none behaviour

- vlib/sqlite/README.md
- vlib/sqlite/sqlite.v
- Added functions to sqlite module to control the journal and disk-writing (sync) behaviour of sqlite.
- Added description to "create_table" (none before)
- Cleaned up description to "exec_none", "busy_timeout"
- Modified the README for new functions for performance tips
> sqlite: added sync and journal funcs, docs

- vlib/v/gen/c/cgen.v
- vlib/v/tests/sumtype_with_none_test.v
This PR fix sumtype with none type (fix #14963).
- Fix sumtype with none type.
- Add test.
```v
module main
fn string_none() string | none {
return none
}
fn main() {
x := string_none()
res := match x {
string {
false
}
none {
true
}
}
assert res
}
```
> cgen: fix sumtype with none type (fix #14963)

- vlib/v/ast/types.v
- vlib/v/fmt/tests/inline_sum_type_keep.vv
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/parser/parser.v
- vlib/v/tests/anon_sum_type_test.v
- vlib/v/tests/cast_to_anon_sumtype_test.v
- vlib/v/tests/string_optional_none_test.v
- vlib/v/tests/sumtype_with_none_test.v
This PR fix error for cast to anon sumtype (fix #14967).
- Fix error for cast to anon sumtype.
- Add test.
```v
module main
fn main() {
x := string|none(none)
println(x)
assert '$x' == 'string|none(none)'
}
string|none(none)
```
> ast, parser, cgen: fix error for cast to anon sumtype (fix #14967)

- cmd/v/help/build-c.txt
- doc/docs.md
- vlib/v/builder/cc.v
Support for the Intel C Compiler (icc) is added in this PR.
It can be [downloaded here](https://www.intel.com/content/www/us/en/developer/articles/tool/oneapi-standalone-components.html#dpcpp-cpp).  I can add it to the Wiki if this PR is merged.
Of course, icc must be in PATH first; (the default installation directory is `/opt/intel/oneapi/compiler/2022.1.0/linux/bin/intel64/icc`)
Running benchmarks on various tests it is very fast with optimization, and likely has some specific Intel optimizations for Intel CPUs.  It shares almost all the same flags as gcc when analyzing `icc -help` and `icc -help opt`, the only difference is no -lfto flag in icc, and -0fast which covers -03 and some other optimizations.
I have tested as well with more complex programs with OpenSSL, SQLite, etc to ensure …
> builder: add support for icc (Intel C Compiler)

- vlib/v/gen/c/comptime.v
- vlib/v/tests/comptime_method_call_test.v
This PR fix error for comptime method call (fix #14991).
- Fix error for comptime method call.
- Add test.
```v
struct App {}
fn (mut app App) method_one() string {
return '1'
}
fn (mut app App) method_two() string {
return '2'
}
fn reflect_call(method_name string) string {
a := App{}
$for method in App.methods {
if method.name == method_name {
return a.$method() + ''
}
}
panic('Method not supported: $method_name')
}
fn main() {
result := reflect_call('method_one')
assert result == '1'
}
1
```
> cgen: fix error for comptime method call (fix #14991)

- .gitignore
- vlib/encoding/binary/README.md
- vlib/encoding/binary/binary.v
- vlib/encoding/binary/binary_test.v
- Added unit tests to the encoding module.
- Documentation added in README and function documentation comments.
- Ignore `.tmperr` files generated by the go backend when Go is not installed.
> encoding.binary: add unit tests and module documentation

- vlib/v/pref/os.v
Without this workaround Termux thinks it is js_node when running examples/fetch.v and is unable to use openssl for the request.
> pref: detect termux more reliably

- vlib/net/websocket/websocket_client.v
- vlib/net/websocket/websocket_server.v
This PR allow user to use custom logger, by allowing to pass logger as an arg.
Currently, logger is hardcoded and impossible to change log format.
https://github.com/vpkgs/slog/blob/v3.0.0/targeted.v#L44-L54
```v
logger := slog.get_v_logger('net.websocket')
websocket.new_client(url, logger: &logger)
```
This PR can be breaking change, for users setting log level for each websocket connection like followings
```v
mut conn := websocket.new_client(wck.url)?
conn.logger.set_level(.debug)
```
The above code will be follows, after these changes
```v
mut conn := websocket.new_client(wck.url)?
if conn.logger is log.Logger as logger {
logger.set_level(.debug)
}
```
> net.websocket: make logger configurable

- vlib/v/ast/scope.v
- vlib/v/checker/tests/globals/closure_capture_global_var.out
- vlib/v/checker/tests/globals/closure_capture_global_var.vv
- vlib/v/parser/fn.v
This PR check closure capture global variable (fix #15004).
- Check closure capture global variable.
- Add test.
```v
module main
__global (
number	int
)
fn init() {
number = 123
}
fn main() {
f1 := fn [number] () {
println(number)
}
f1()
}
PS D:\Test\v\tt1> v -enable-globals run .
./tt1.v:12:12: error: no need to capture global variable `number` in closure
10 |
11 | fn main() {
12 |     f1 := fn [number] () {
|               ~~~~~~
13 |         println(number)
14 |     }
```
> parser: check closure capture global variable (fix #15004)

- CHANGELOG.md
- cmd/tools/vcomplete.v
- cmd/tools/vls.v
- cmd/v/help/ls.txt
- cmd/v/v.v
> **NOTE:** To all Windows users who are interested, please try this branch and provide some feedback here so I will know if this works smoothly or not. Thanks!
This PR adds a unified tool for installing, updating, and launching/executing the [V language server](https://github.com/vlang/vls) or VLS. Prior to this, the installation methods presented are time-consuming or in the case of [vscode-vlang](https://github.com/vlang/vscode-vlang), buggy due to unmaintained code. 
With this tool, users can simply do `v ls --install` or `v ls --update` when installing or updating the language server. For extensions, this will be an advantage as there is no code required other than calling the executable. 
RELATED: https://github.com/vlang/vscode-vlang/pull/450
> cmd/tools: add vls launcher and updater utility

- vlib/vweb/vweb.v
This PR check invalid port number (fix #15012).
- Check invalid port number.
```v
import vweb
struct App {
vweb.Context
}
fn main() {
vweb.run(&App{}, 0)
}
V panic: invalid port number `0`, it should be between 1 and 65535
v hash: bfcf5b1
```
```v
import vweb
struct App {
vweb.Context
}
fn main() {
vweb.run(&App{}, 804567)
}
V panic: invalid port number `804567`, it should be between 1 and 65535
v hash: bfcf5b1
```
> vweb: check invalid port number (fix #15012)

- cmd/tools/vls.v
Fixes `v ls --install` when the config file (`vls.config.json`) is not present.
> cmd/tools/vls: fix installing vls when config is not present

- vlib/v/checker/struct.v
- vlib/v/checker/tests/struct_field_with_any_type_err.out
- vlib/v/parser/parse_type.v
- vlib/v/parser/tests/cast_to_any_type_err.out
- vlib/v/parser/tests/cast_to_any_type_err.vv
This PR check for illegal use of any type (fix #15003).
- Check for illegal use of any type.
- Add test.
```v
fn main() {
a := any(22)
println(a)
}
./tt1.v:2:7: error: cannot use `any` type here, `any` will be implemented in V 0.4
2 |     a := any(22)
|          ~~~
3 |     println(a)
4 | }
```
> parser: check for illegal use of any type (fix #15003)

- vlib/v/checker/infix.v
- vlib/v/gen/c/infix.v
- vlib/v/tests/alias_operator_overloading_test.v
This PR fix alias operator overloading (fix #12122).
- Fix alias operator overloading.
- Add test.
```v
pub struct Vector {
vec []f64
}
pub fn (a Vector) + (b Vector) Vector {
size := a.vec.len
if size != b.vec.len {
panic('unequal sizes')
}
mut c := []f64{len: size}
for i in 0 .. size {
c[i] = a.vec[i] + b.vec[i]
}
return Vector{
vec: c
}
}
type Vec = Vector
fn main() {
a := Vec{
vec: [0.1, 0.2]
}
b := Vec{
vec: [0.3, 0.2]
}
c := a + b
println(c)
assert c.vec == [0.4, 0.4]
}
Vec(Vector{
vec: [0.4, 0.4]
})
```
> checker, cgen: fix alias operator overloading (fix #12122)

- vlib/v/checker/infix.v
- vlib/v/checker/return.v
- vlib/v/tests/comptime_call_type_test.v
1. Fixes #14996
2. Add test.
At present, only a few scenarios have been processed.
The workload of this problem is a little large, mainly because it is difficult to deal with the type of infixExpr, AssignStmt..... The reason is that the type of comptimecall is forcibly set to string type.
t := int(0)
t = $method()
t += $method() // *=, /= ...
t = $method() + 0 // InfixExpr left
t = 0 + $method() // InfixExpr right
if $method() > 0 // condition
......
> Fixes: #14996 The type of ComptimeCall can be detected by the checker in some scenarios.

- vlib/v/checker/infix.v
This PR makes minor cleanup in infix_expr().
- Change `left_final` to `left_final_sym`.
- Change `right_final` to `right_final_sym`.
> checker: minor cleanup in infix_expr()

- vlib/v/ast/types.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/voidptr_dereference_err.out
- vlib/v/checker/tests/voidptr_dereference_err.vv
As mentioned in #15002, the compiler allows you to dereference a `voidptr`, but it shouldn't.
This PR fixes it and introduces one more test.
> checker.v: fix #15002 compiler bug about dereferencing voidptr.

- vlib/v/builder/builder_test.v
- `arrays.concat` is deprecated
- It is causing the CI run to fail
- Replace it with `<<`.
> builder: replace arrays.concat with <<

- vlib/v/checker/infix.v
- vlib/v/gen/c/infix.v
- vlib/v/tests/array_of_sumtype_append_alias_test.v
This PR fix array of sumtype appending alias (fix #12606).
- Fix array of sumtype appending alias.
- Add test.
```v
type Attribute = NextHop | Origin
type Origin = u8
type NextHop = []u8
fn main() {
mut attrs := []Attribute{cap: 100}
bytes := []u8{len: 4}
attrs << NextHop(bytes)
attrs << Origin(1)
for attr in attrs {
if attr is Origin {
println(attr)
continue
}
if attr is NextHop {
println(attr)
continue
}
panic('oh no !')
}
assert attrs.len == 2
assert attrs[0] == Attribute(NextHop(bytes))
assert attrs[1] == Attribute(Origin(1))
}
NextHop([`\0`, `\0`, `\0`, `\0`])
1
```
> checker, cgen: fix array of sumtype appending alias (fix #12606)

- vlib/v/parser/fn.v
- vlib/v/tests/c_function_mut_param/optional_args_test.v
This PR fix parse c function with optional argument name (fix #13234).
- Fix parse c function with optional argument name.
- Add test.
```v
module main
#include "@VMODROOT/code.c"
fn C.mut_arg(&u8, mut val usize)
fn test_c_function_mut_param() {
key := &u8(1)
mut val := usize(1)
C.mut_arg(key, mut &val)
assert val == usize(5)
}
```
> parser: fix parse c function with optional argument name (fix #13234)

- examples/c_interop_wkhtmltopdf.v
This PR fix a typo in c_interop_wkhtmltopdf.v.
> examples: fix typo in c_interop_wkhtmltopdf.v

- vlib/v/gen/c/cgen.v
- vlib/v/tests/struct_shared_field_with_default_init_test.v
This PR fix struct shared field with default init (fix #10813).
- Fix struct shared field with default init.
- Add test.
```v
struct App {
id string
mut:
app_data shared AppData
}
struct AppData {
id           string
sub_app_data SubAppData
}
struct SubAppData {
id      string
message string = 'Default message'
}
fn main() {
println(app)
rlock app.app_data {
assert app.app_data.sub_app_data.message == 'Default message'
}
}
App{
id: ''
app_data: AppData{
id: ''
sub_app_data: SubAppData{
id: ''
message: 'Default message'
}
}
}
```
> cgen: fix struct shared field with default init (fix #10813)

- vlib/v/checker/interface.v
- vlib/v/checker/tests/generics_interface_declaration_err.out
- vlib/v/checker/tests/generics_interface_declaration_err.vv
This PR check generic interface declaration (fix #15042, fix #15043).
- Check generic interface declaration.
- Add test.
```v
interface Expr {
accept(v Visitor<R>) R
}
interface Visitor<R> {
}
fn main() {
}
./tt1.v:1:1: error: generic interface declaration must specify the generic type names, e.g. Foo<T>
1 | interface Expr {
| ~~~~~~~~~~~~~~~~
2 |     accept(v Visitor<R>) R
3 | }
```
> checker: check generic interface declaration (fix #15042, #15043)

- vlib/v/gen/c/index.v
- vlib/v/tests/fixed_array_literal_index_test.v
This PR fix fixed array literal index (fix #14959).
- Fix fixed array literal index.
- Add test.
```v
fn main() {
println([1]int{}[0])
assert [1]int{}[0] == 0
println([1, 2]![1])
assert [1, 2]![1] == 2
}
0
2
```
```v
fn main() {
println([1]&int{}[0])
}
./tt1.v:2:12: warning: fixed arrays of references need to be initialized right away (unless inside `unsafe`)
2 |    println([1]&int{}[0])
|            ~~~~~~~~~
3 | }
&nil
```
> cgen: fix fixed array literal index (fix #14959)

- vlib/v/ast/table.v
- vlib/v/checker/fn.v
- vlib/v/checker/tests/generic_fn_decl_err_a.out
- vlib/v/checker/tests/generic_fn_decl_err_a.vv
This PR check generic fn declaration error (fix #15057).
- Check generic fn declaration error.
- Add test.
```v
module main
struct Db {}
struct User {}
struct Post {}
fn main() {
r := Db{}
u := User{}
p := Post{}
r.create(u, p)
}
fn (r Db) create<U>(u U, p P) {
println('Yo')
}
./tt1.v:17:28: error: generic type name `P` is not mentioned in fn `create<U>`
15 | }
16 |
17 | fn (r Db) create<U>(u U, p P) {
|                            ^
18 |     println('Yo')
19 | }
```
> ast, checker: check generic fn declaration error (fix #15057)

- vlib/v/gen/c/cgen.v
- vlib/v/tests/fixed_array_of_threads_test.v
This PR fix fixed array of threads (fix #15082).
- Fix fixed array of threads.
- Add test.
```v
module main
fn main() {
mut avar := [8]thread string{}
avar[0] = go printme()
ret := avar[0].wait()
assert ret == 'me'
}
fn printme() string {
println('me')
return 'me'
}
me
```
> cgen: fix fixed array of threads (fix #15082)

- vlib/v/checker/tests/generic_interface_method_decl_err.out
- vlib/v/checker/tests/generic_interface_method_decl_err.vv
- vlib/v/parser/struct.v
This PR check generic interface method declaration (fix #15043).
- Check generic interface method declaration.
- Add test.
```v
interface Expr {
accept<R>(v Visitor<R>) R
}
interface Visitor<R> {
}
fn main() {
}
./tt1.v:2:8: error: no need to add generic type names in generic interface's method
1 | interface Expr {
2 |     accept<R>(v Visitor<R>) R
|           ^
3 | }
4 |
```
> parser: check generic interface method declaration (fix #15043)

- vlib/encoding/csv/reader_test.v
- vlib/encoding/csv/to_struct_arr.v
This PR changes the following behavior
- treating non-zero value as `true` while decoding bool value for struct
> encoding.csv: update bool condition for decode struct

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/builtins.v
- vlib/v/gen/native/gen.v
Adding a system for defining internal algorithms which are not inlined, but rather treated like functions.
This is necessary to keep executable sizes small and the generated code clean (especially for debugging). Algorithms like the int-to-string conversion, etc. no longer get duplicated when needed.
> native: system for defining internal builtin algorithms which are not inlined

- vlib/v/checker/struct.v
- vlib/v/checker/tests/generics_struct_decl_no_mention_err.out
- vlib/v/checker/tests/generics_struct_decl_no_mention_err.vv
This PR check generic struct declaration.
- Check generic struct declaration.
- Add test.
```v
fn main() {}
struct Foo<U> {
Bar<T>
foo U
bar P
}
struct Bar<T> {
}
./tt1.v:4:2: error: generic type name `T` is not mentioned in struct `Foo<U>`
2 | 
3 | struct Foo<U> {
4 |     Bar<T>
|     ~~~~~~
5 |     foo U
6 |     bar P
./tt1.v:6:6: error: generic type name `P` is not mentioned in struct `Foo<U>`
4 |     Bar<T>
5 |     foo U
6 |     bar P
|         ^
7 | }
8 |
```
> checker: check generic struct declaration

- vlib/v/checker/interface.v
- vlib/v/checker/tests/generics_interface_decl_no_mention_err.out
- vlib/v/checker/tests/generics_interface_decl_no_mention_err.vv
This PR check generic interface declaration.
- Check generic interface declaration.
- Add test.
```v
fn main() {}
interface Foo<U> {
Bar<T>
foo(u U, p P)
bar(u U) []P
}
interface Bar<T> {
}
./tt1.v:4:2: error: generic type name `T` is not mentioned in interface `Foo<U>`
2 |
3 | interface Foo<U> {
4 |     Bar<T>
|     ~~~
5 |     foo(u U, p P)
6 |     bar(u U) []P
./tt1.v:5:13: error: generic type name `P` is not mentioned in interface `Foo<U>`
3 | interface Foo<U> {
4 |     Bar<T>
5 |     foo(u U, p P)
|                ^
6 |     bar(u U) []P
7 | }
./tt1.v:6:11: error: generic type name `P` is not mentioned in interface `Foo<U>`
4 |     Bar<T>
5 |     foo(u U, p P)
6 |     bar(u U) []P
|              ~~~
7 | }
8 |
```
> checker: check generic interface declaration

- cmd/tools/vls.v
Fixes an issue when executing `v ls --socket` causes the language server to start in stdio mode because of the beginning `ls` argument when the `v ls` launcher passed the remaining arguments to the server executable (`['ls', '--socket']` instead of `['--socket']`).
> cmd/tools/vls: skip 'ls' argument on `v ls`

- examples/web_crawler/web_crawler.v
"Respond.text" property will be depreciated soon and the compiler is showing warning about it. 
So replaced it with "Respond.body".
> Replaced "resp.text" with "resp.body".

- vlib/mysql/_cdefs.c.v
- vlib/mysql/mysql.v
- vlib/mysql/mysql_orm_test.v
- vlib/mysql/orm.v
- vlib/orm/README.md
FIX1: ```V panic: mysql.SQLError: Incorrect datetime value: '1657993703' for column 'created_at' at row 1 (1) (INSERT INTO `TestTimeType` (`username`, `created_at`, `updated_at`, `deleted_at`) VALUES (?, ?, ?, ?);)```
FIX2:
```
/tmp/v_1000/v.10678589466079111090.tmp.c:17797: at print_backtrace: Backtrace
/tmp/v_1000/v.10678589466079111090.tmp.c:17868: by v_segmentation_fault_handler
7fcb42179520 : by ???
7fcb4210dcf0 : by ???
7fcb4210e2fb : by ???
/tmp/v_1000/v.10678589466079111090.tmp.c:54587: by mysql__Stmt_fetch_stmt
/tmp/v_1000/v.10678589466079111090.tmp.c:54148: by mysql__Connection_select
/tmp/v_1000/v.10678589466079111090.tmp.c:10274: by mysql__Connection_select_Interface_orm__Connection_method_wrapper
/tmp/v_1000/v.10678589466079111090.tmp.c:54876: by main__main …
```
> mysql: fix for adapting mysql types to v structs

- vlib/v/checker/struct.v
- vlib/v/checker/tests/struct_field_with_default_err.out
- vlib/v/checker/tests/struct_field_with_default_err.vv
This PR check struct field with default expression (fix #15147).
- Check struct field with default expression.
- Add test.
```v
struct Dummy<T> {
arbitrary_field T = T{}
}
fn main() {}
./tt1.v:2:22: error: unknown struct `T`
1 | struct Dummy<T> {
2 |     arbitrary_field T = T{}
|                         ~~~
3 | }
4 |
```
> checker: check struct field with default expression (fix #15147)

- vlib/v/gen/c/comptime.v
- vlib/v/tests/comptime_if_expr_in_struct_field_default_test.v
This PR fix comptime if in struct field default (fix #15058).
- Fix comptime if in struct field default.
- Add test.
```v
struct Foo{
text string = $if linux { 'linux' } $else {
println('else')
'else'
}
}
fn main(){
f := Foo{}
println(f)
assert f.text.len > 0
}
else
Foo{
text: 'else'
}
```
> cgen: fix comptime if in struct field default (fix #15058)

- vlib/v/ast/ast.v
- vlib/v/ast/comptime_const_values.v
- vlib/v/ast/init.v
- vlib/v/ast/table.v
- vlib/v/checker/checker.v
- vlib/v/checker/containers.v
- vlib/v/fmt/fmt.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/infix.v
- vlib/v/gen/golang/golang.v
- vlib/v/parser/assign.v
- vlib/v/parser/containers.v
- vlib/v/parser/expr.v
- vlib/v/parser/fn.v
- vlib/v/parser/for.v
- vlib/v/parser/if_match.v
- vlib/v/parser/parser.v
- vlib/v/parser/sql.v
- vlib/v/parser/struct.v
- vlib/v/transformer/transformer.v
This PR improves the performance of the V parser & checker by ~2% .
It also reduces memory consumption for:
`./v -o x.c -check cmd/v`
... from ~158MB to ~148MB.
(measured on Ubuntu 20.04, with v compiled with tcc, on i3-3225)
> ast: use `const empty_expr` instead of `fn empty_expr` (thanks to Joe Conigliaro for the idea)

- vlib/v/checker/checker.v
- vlib/v/checker/if.v
- vlib/v/tests/comptime_if_expr_in_const_decl_test.v
This PR fix comptime if in const declaration (fix #15160, fix #9886, fix #10395).
- Fix comptime if in const declaration.
- Add test.
```v
const msg = $if windows {
'windows, eh?'
} $else {
'ok, then'
}
fn main() {
println(msg)
assert msg.len > 0
}
windows, eh?
```
```v
const(
a = $if linux { 1 } $else { 2 }
)
fn main(){
println(a)
}
2
```
> checker: fix comptime if in const declaration (fix #15160)

- vlib/v/checker/fn.v
- vlib/v/tests/vargs_with_enum_value_test.v
This PR fix fn variadic with enum value (fix #15174).
- Fix fn variadic with enum value.
- Add test.
```v
enum Foo {
a
b
c
}
fn foo(n int, m ...map[Foo]int) {
println(m)
assert m.len == 2
assert '$m' == '[{a: 1}, {b: 2}]'
}
fn main() {
foo(1, {
.a: 1,
}, {
.b: 2,
})
}
[{a: 1}, {b: 2}]
```
> checker: fix fn variadic with enum value (fix #15174)

- vlib/os/file.c.v
The comment refers to a .get_line() method, but there is no such method,
only a global function.
> doc: remove misleading comment about stdin()

- vlib/v/gen/c/str.v
- vlib/v/tests/custom_str_on_struct_with_too_many_fields_test.v
This PR fix custom str on struct with too many fields (fix #15193).
- Fix custom str on struct with too many fields.
- Add test.
```v
struct Abc {
a string
b string
c string
d string
//
e string
f string
g string
h string
//
x int // number of fields must be > 8
}
fn (a Abc) str() string {
return 'abc'
}
fn (a Abc) some_method() string {
println(a)
return '$a'
}
fn main() {
abc := Abc{}
ret := abc.some_method()
println(ret)
assert ret == 'abc'
}
abc
abc
```
> cgen: fix custom str on struct with too many fields (fix #15193)

- vlib/crypto/README.md
add v example for validate token using crypto lib
```v
fn auth_verify(token string) bool {
secret := 'your-256-bit-secret'
token_split := token.split('.')
signature_mirror := hmac.new(secret.bytes(), '${token_split[0]}.${token_split[1]}'.bytes(),
sha256.sum, sha256.block_size).bytestr().bytes()
signature_from_token := base64.url_decode(token_split[2])
return hmac.equal(signature_from_token, signature_mirror)
}
```
> doc: token auth_verify example

- vlib/math/big/array_ops.v
- vlib/math/big/big.v
- vlib/math/big/special_array_ops.v
- vlib/math/big/special_array_ops_test.v
- Updates the threshold for Karatsuba multiplication. This is done based on results captured [here](https://github.com/hungrybluedev/vbigmath/blob/main/observations/data.csv).
- Adds Toom Cook 3 multiplication routine with an appropriate threshold. Could be optimised further, but good enough to observe a difference now.
- Adds `three_int` to the module.
- Updates the `lshift_in_place` function name.
> math.big: Improve multiplication performance

- vlib/os/os.c.v
On Windows `get_raw_line()` is breaking lines incorrectly at `\r`, which causes the behavior described in #5900. The `\r\n` line ending is interpreted incorrectly as a line ending followed by an empty line. This fixes #5900 by ignoring the `\r`.
> os: Windows get_raw_line() should not break lines on \r (fix #5900)

- vlib/pg/README.md
`pg` is a wrapper for the PostgreSQL client library. It provides access to a PostgreSQL DB server.
Before you can use this module, you must first have PostgreSQL installed on your system.
To do this, find your OS and perform the actions listed.
**NOTE**: These instructions are meant only as a convenience. If your OS is not listed or you 
need extra help, [go here](https://www.postgresql.org/download/).
```
sudo dnf install postgresql-server postgresql-contrib
sudo systemctl enable postgresql # to autostart on startup
sudo systemctl start  postgresql
```
```
sudo apt-get install postgresql postgresql-client
sudo systemctl enable postgresql # to autostart on startup
sudo systemctl start  postgresql
```
```
brew install postgresql
brew services start postgresql
```
```
gem install pg -- …
```
> refactor: improve pg README.md

- vlib/v/scanner/scanner.v
- vlib/v/scanner/tests/undefined_ident_in_string_literal_err.out
- vlib/v/scanner/tests/undefined_ident_in_string_literal_err.vv
This PR check undefined ident in string literal (fix #15209).
- Check undefined ident in string literal.
- Add test.
```v
fn abc() string {
return 'abc $type'
}
fn xyz() string {
return '42P01'
}
fn main() {}
./tt1.v:2:15: error: undefined ident: `type`
1 | fn abc() string {
2 |     return 'abc $type'
|                  ~~~~
3 | }
4 |
```
> scanner: check undefined ident in string literal (fix #15209)

- vlib/v/gen/c/auto_str_methods.v
- vlib/v/tests/inout/printing_struct_with_skip_fields.out
- vlib/v/tests/inout/printing_struct_with_skip_fields.vv
This PR fix printing struct with skip fields.
- Fix printing struct with skip fields.
- Add test.
```v
struct Foo {
name string
age  int    [str: skip]
}
fn main() {
x := Foo{'Peter', 25}
println(x)
}
Foo{
name: 'Peter'
}
```
> cgen: fix printing struct with skip fields

- vlib/v/scanner/scanner.v
- vlib/v/scanner/tests/empty_character_literal_err.out
- vlib/v/scanner/tests/empty_character_literal_err.vv
This PR correct error message of empty character literal (fix #15226).
- Correct error message of empty character literal.
- Add test.
```v
fn main() {
a := ``
println(a)
}
./tt1.v:2:8: error: invalid character literal `` => `` ([]) (empty literal)
2 |     a := ``
|           ^
3 |     println(a)
4 | }
./tt1.v:2:7: details: use quotes for strings, backticks for characters
2 |     a := ``
|          ^
3 |     println(a)
4 | }
```
> scanner: correct error message of empty character literal (fix #15226)

- vlib/mysql/mysql_orm_test.v
- vlib/mysql/orm.v
- vlib/orm/README.md
- vlib/orm/orm.v
- vlib/orm/orm_fn_test.v
- vlib/pg/orm.v
- vlib/pg/pg_orm_test.v
- vlib/sqlite/orm.v
- vlib/sqlite/sqlite_orm_test.v
- vlib/sqlite/sqlite_test.v
- vlib/sqlite/stmt.v
```v
import pg
struct Member {
id         string [default: 'gen_random_uuid()'; primary; sql_type: 'uuid']
created_at string [default: 'CURRENT_TIMESTAMP'; sql_type: 'TIMESTAMP']
}
fn main() {
db := pg.connect(pg.Config{
host: 'localhost'
port: 5432
user: 'user'
password: 'password'
dbname: 'dbname'
}) or {
println(err)
return
}
defer {
db.close()
}
sql db {
create table Member
}
new_member := Member{
name: 'John Doe'
}
sql db {
insert new_member into Member
}
selected_member := sql db {
select from Member where name == 'John Doe' limit 1
}
sql db {
update Member set name = 'Hitalo' where id == selected_member.id
}
}
```
> orm: feat/ default attribute

- vlib/v/gen/c/comptime.v
- vlib/v/tests/comptime_for_method_call_with_args_test.v
This PR fix comptime for method call with arguments (fix #15234).
- Fix comptime for method call with arguments.
- Add test.
```v
import os
fn (d Dummy) sample(file_name string) {
println(file_name)
}
fn main() {
$for method in Dummy.methods {
if os.args.len > 1 {
Dummy{}.$method(os.args)
}
}
}
PS D:\Test\v\tt1> v run . hello
D:\Test\v\tt1\tt1.exe
```
> cgen: fix comptime for method call with arguments (fix #15234)

- GNUmakefile
This fixes a build failure when using `%make_build` in an RPM spec file:
```makefile
make: 1: No such file or directory
make: *** [GNUmakefile:100: all] Error 127
```
> GNUmakefile: rename "V" to "VEXE", to prevent conflict(s)

- vlib/v/checker/tests/comptime_call_method_void_err.out
- vlib/v/checker/tests/comptime_call_method_void_err.vv
- vlib/v/gen/c/comptime.v
This PR check comptime call method (no value) used as value (fix #15233).
- Check comptime call method (no value) used as value.
- Add test.
```v
import os
fn (d Dummy) sample2(file_name string) int {
println(file_name)
return 22
}
fn (d Dummy) sample1(file_name string) {
println(file_name)
}
fn main() {
$for method in Dummy.methods {
if os.args.len >= 1 {
println(Dummy{}.$method(os.args[0]))
}
}
}
./tt1.v:17:20: cgen error: method `sample1()` (no value) used as value
15 |     $for method in Dummy.methods {
16 |         if os.args.len >= 1 {
17 |             println(Dummy{}.$method(os.args[0]))
|                             ~~~~~~~~~~~~~~~~~~~
18 |         }
19 |     }
```
> cgen: check comptime call method (no value) used as value (fix #15233)

- vlib/v/checker/tests/undefined_ident_in_if_guard_err.out
- vlib/v/checker/tests/undefined_ident_in_if_guard_err.vv
- vlib/v/parser/assign.v
- vlib/v/parser/if_match.v
This PR check undefined ident in if guard expr (fix #15251).
- Check undefined ident in if guard expr.
- Add test.
```v
module main
import regex
fn main() {
if re := re.regex_opt('a') {
print('Hooray')
}
}
./tt1.v:6:11: error: undefined variable: `re`
4 |
6 |     if re := re.regex_opt('a') {
|              ~~
7 |         print('Hooray')
8 |     }
```
> parser: check undefined ident in if guard expr (fix #15251)

- vlib/v/ast/str.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/match.v
- vlib/v/gen/js/js.v
This PR also cleanups the generated code a little (no break; right after return).
> cgen: use switch/case statements for matches with integer literal branches, instead of an `if else if` ladder.

- vlib/net/websocket/events.v
- vlib/picoev/picoev.v
- vlib/v/checker/fn.v
- vlib/v/checker/tests/method_call_arg_no_mut_err.out
- vlib/v/checker/tests/method_call_arg_no_mut_err.vv
- vlib/v/gen/native/amd64.v
This PR check struct field's fn call  (fix #15249).
- Check struct field's fn call.
- Add test.
```v
module main
type Fkt = fn (mut a Alarm)
struct Alarm {
x int
}
struct Clock {
mut:
arr       []Alarm
alarm_fkt Fkt
}
fn fkt(mut a Alarm) {
println(a.x)
}
fn main() {
mut c := Clock{
alarm_fkt: fkt
}
c.arr << Alarm{}
mut last := c.arr.last()
c.alarm_fkt(last)
}
./tt1.v:25:14: error: method `alarm_fkt` parameter `a` is `mut`, so use `mut last` instead
23 |     c.arr << Alarm{}
24 |     mut last := c.arr.last()
25 |     c.alarm_fkt(last)
|                 ~~~~
26 | }
```
> checker: check struct field's fn call  (fix #15249)

- vlib/v/parser/assign.v
- vlib/v/parser/expr.v
- vlib/v/parser/fn.v
- vlib/v/parser/lock.v
- vlib/v/parser/parse_type.v
- vlib/v/parser/parser.v
- vlib/v/parser/sql.v
Creating similar error messages with same function improves consistency of error messages and makes  code clearer.
> create and use `parser.unexpected` to cleanup

- vlib/v/checker/checker.v
- vlib/v/checker/tests/invalid_variable_err.out
- vlib/v/checker/tests/invalid_variable_err.vv
This PR check invalid variable (fix #15240).
- Check invalid variable.
- Add test.
```v
fn main() {
a, b := c
if a {
}
}
./tt1.v:2:5: warning: unused variable: `b`
2 |     a, b := c
|        ^
3 |     if a {
4 |     }
./tt1.v:2:7: error: assignment mismatch: 2 variable(s) 1 value(s)
2 |     a, b := c
|          ~~
3 |     if a {
4 |     }
./tt1.v:3:5: error: invalid variable `a`
2 |     a, b := c
3 |     if a {
|        ^
4 |     }
5 | }
```
> checker: check invalid variable (fix #15240)

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/comptime_method_call_keep.vv
This PR fix fmt of comptime method call.
- Fix comptime method call.
- Add test.
comptime_method_call_keep.vv
```v
import os
fn (d Dummy) sample(x int) int {
return x + 1
}
fn main() {
$for method in Dummy.methods {
if os.args.len > 1 {
Dummy{}.$method(os.args[1].int())
}
}
}
```
> fmt: fix comptime method call

- vlib/builtin/string.v
- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/interface_method_with_fntype_arg_keep.vv
This PR fix interface method with fntype argument (fix #15276).
- Fix interface method with fntype argument.
- Add test.
vlib\v\fmt\tests\interface_method_with_fntype_arg_keep.vv
```v
module main
interface Test {
test(fn (Test))
}
struct Test1 {
}
fn (t Test1) test(f fn (Test)) {
f(Test(t))
}
fn main() {
t := Test1{}
t.test(fn [t] (t1 Test) {
println('$t, $t1')
t.test(fn [t] (t2 Test) {
println('$t, $t2')
})
})
}
```
> fmt: fix interface method with fntype argument (fix #15276)

- vlib/builtin/builtin_d_gcboehm.c.v
This fixes the random memory corruption(s) with `-d dynamic_boehm`.
The `GC_PTHREADS` definition is removed because redundant.
According to upstream documentation, only `GC_WIN32_THREADS` is explicit.
> bultin: always enable GC_THREADS, otherwise multithread operation is unsafe

- vlib/v/checker/fn.v
- vlib/v/checker/tests/method_call_arg_no_mut_err.out
- vlib/v/checker/tests/method_call_arg_no_mut_err.vv
This PR improve error message of method_call_arg_no_mut_err.vv.
- Improve error message because sometimes only the parameter type is provided.
- Modify test.
```v
module main
type Fkt = fn (mut Alarm)
struct Alarm {
x int
}
struct Clock {
mut:
arr       []Alarm
alarm_fkt Fkt
}
fn fkt(mut a Alarm) {
println(a.x)
}
fn main() {
mut c := Clock{
alarm_fkt: fkt
}
c.arr << Alarm{}
mut last := c.arr.last()
c.alarm_fkt(last)
}
```
before:
```v
./tt1.v:25:14: error: method `alarm_fkt` parameter `` is `mut`, so use `mut last` instead
23 |     c.arr << Alarm{}
24 |     mut last := c.arr.last()
25 |     c.alarm_fkt(last)
|                 ~~~~
26 | }
```
now:
```v
./tt1.v:25:14: error: method `alarm_fkt` parameter 1 is `mut`, so use `mut last` …
```
> checker: improve error message of method_call_arg_no_mut_err.vv

- vlib/v/gen/c/utils.v
* Improve comment formatting.
* Wrap unsafe code inside an `unsafe` block instead of using 2 blocks.
* Replace `0` with `nil`.
* Replace `muttable` => `mut_table`.
> gen.c: simplify `unwrap_generic` method

- vlib/v/scanner/scanner.v
This PR `makes scan_all_tokens_in_buffer()/scan_remaining_text()` private.
> scanner: make scan_all_tokens_in_buffer() private

- .github/PULL_REQUEST_TEMPLATE
I saw a PR that had the title `30 Jul 2022 9:17 pm : Updating docs to include example for Function literals in Functions section`. This PR tries to avoid that confusion by giving an example with a module different than `time`.
> .github: Add example on PR template  title to avoid confusion

- vlib/rand/rand.v
- vlib/rand/random_numbers_test.v
Temporarily fixes #15323 
- As @spytheman pointed out, using `func<T>()` explicitly instead of `func()` seems to fix this problem. Needs to be looked at from the generics implementation level later.
- Updates the shuffle algorithm to be closer to the Fisher-Yates shuffle.
> rand: fix incorrect generic function call

- CHANGELOG.md
- cmd/tools/vast/vast.v
- doc/docs.md
- vlib/builtin/builtin.v
- vlib/v/ast/ast.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/assert_extra_message.out
- vlib/v/checker/tests/assert_extra_message.vv
- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/assert_extra_message_keep.vv
- vlib/v/gen/c/assert.v
- vlib/v/markused/walker.v
- vlib/v/parser/parser.v
- vlib/v/preludes/test_runner_normal.v
- vlib/v/tests/skip_unused/assert_with_extra_message_works_test.run.out
- vlib/v/tests/skip_unused/assert_with_extra_message_works_test.skip_unused.run.out
- vlib/v/tests/skip_unused/assert_with_extra_message_works_test.vv
With this PR, the following is valid V:
```v
fn test_assertion_with_extra_message_failure() {
for i in 0 .. 100 {
assert i * 2 - 45 < 75 + 10, 'i: $i'
}
}
```
When run, it produces:
Fix #15315 .
> all: support `assert condition, extra_message`, evaluating and showing extra_message on assert failure

- vlib/v/checker/check_types.v
- vlib/v/checker/fn.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/inout/nested_generic_fn_call.out
- vlib/v/tests/inout/nested_generic_fn_call.vv
This PR fix nested generic fn call (fix #15328).
- Fix nested generic fn call.
- Add test.
```v
module main
fn shuffle_impl<T>(mut a []T) ? {
println('FN: ${@FN:20} | T: ${typeof(a).name}')
}
fn shuffle<T>(mut a []T) ? {
println('FN: ${@FN:20} | T: ${typeof(a).name}')
shuffle_impl(mut a)?
}
fn main() {
mut a := [1, 2]
mut b := [f64(1.0), 2.0]
shuffle(mut a)?
shuffle(mut b)?
}
FN:              shuffle | T: &[]int
FN:         shuffle_impl | T: &[]int
FN:              shuffle | T: &[]f64
FN:         shuffle_impl | T: &[]f64
```
> checker: fix nested generic fn call (fix #15328)

- vlib/v/checker/containers.v
- vlib/v/checker/tests/generic_interface_missing_type_names_err.out
- vlib/v/checker/tests/generic_interface_missing_type_names_err.vv
This PR check generic interface missing type parameter (fix #15342).
- Check generic interface missing type parameter.
- Add test.
```v
interface Output<T> {
val T
name string
}
struct Coil {
pub mut: val int
pub: name string [required]
}
struct Light {
pub mut: val int
pub: name string [required]
}
fn main() {
mut outs := []Output{}
outs << Coil { name: 'outhole' }
outs << Light { name: 'shoot again' }
}
./tt1.v:16:17: error: generic interface must specify type parameter, e.g. Foo<int>
14 |
15 | fn main() {
16 |   mut outs := []Output{}
|                 ~~~~~~
17 |   outs << Coil { name: 'outhole' }
18 |   outs << Light { name: 'shoot again' }
```
> checker: check generic interface missing type parameter (fix #15342)

- vlib/v/gen/c/fn.v
- vlib/v/tests/inout/dump_generic_interface_ref_arg.out
- vlib/v/tests/inout/dump_generic_interface_ref_arg.vv
This PR fix generic interface call with reference argument (fix #15341).
- Fix generic interface call with reference argument.
- Add test.
```v
interface In {
in_() f64
}
interface Out {
out() f64
}
interface InOut {
}
struct MyImpl {
in_ f64
out f64
}
pub fn (mi &MyImpl) in_() f64 {
return mi.in_
}
pub fn (mi &MyImpl) out() f64 {
return mi.out
}
fn main() {
mi := MyImpl{
in_: 1.0
out: 2.0
}
dump(mi.in_())
dump(mi.out())
run(&mi)
}
fn run<T>(in_put T) {
dump(in_put.in_())
dump(in_put.out())
$if T is InOut {
dump(in_put.in_())
dump(in_put.out())
} $else $if T is In {
dump(in_put.in_())
} $else $if T is Out {
dump(in_put.out())
}
}
[.\\tt1.v:30] mi.in_(): 1.
[.\\tt1.v:31] mi.out(): 2.
[.\\tt1.v:36] in_put.in_(): 1.
[.\\tt1.v:37] in_put.out(): 2.
[.\\tt1.v:39] …
```
> cgen: fix generic interface call with reference argument (fix #15341)

- vlib/v/gen/c/fn.v
- vlib/v/tests/generic_fn_call_with_reference_argument_test.v
- vlib/v/tests/inout/dump_nested_generic_fn_call_ref_arg.out
- vlib/v/tests/inout/dump_nested_generic_fn_call_ref_arg.vv
This PR fix nested generic fn call with reference argument (fix #15349).
- Fix nested generic fn call with reference argument.
- Add test.
```v
interface Average {
ave() f64
}
struct Score {
ave f64
}
pub fn (s &Score) ave() f64 {
return s.ave
}
fn next<T>(input T) f64 {
$if T is Average {
dump('${T.name} $input')
return next2<T>(input)
} $else {
dump('${T.name} $input')
return next2<T>(input)
}
}
fn next2<T>(input T) f64 {
dump('${T.name} $input')
$if T is Average {
return input.ave()
} $else $if T is f64 {
return 64.0
}
return 0.0
}
fn main() {
dump(next(1))
dump(next(1.0))
dump(next(11.1))
ave := Score {
ave: 23.4
}
dump(next(ave))
dump(next(&ave))
}
[.\\tt1.v:19] '$T.name $input': int 1
[.\\tt1.v:26] '$T.name $input': int 1
[.\\tt1.v:36] next(1): 0 …
```
> cgen: fix nested generic fn call with reference argument (fix #15349)

- examples/net_failconnect.v
- vlib/net/errors.v
- vlib/net/net_nix.c.v
- vlib/net/net_windows.c.v
- vlib/net/tcp.v
- vlib/net/tcp_self_dial_from_many_clients_test.v
- vlib/net/websocket/websocket_test.v
- vlib/vweb/tests/vweb_test.v
- vlib/vweb/tests/vweb_test_server.v
Resolves #15336 where the socket error is quered incorrectly, resulting in error 56 returned. Also adds better logging as to why your dial_tcp() failed.
This supercedes and therefore closes #15335
> net: connect error contains addrs, and why they failed

- cmd/tools/vrepl.v
This PR will create the 'pin' command on the repl. The on successful output from the ran program, the pin command will clear the screen, list source code and then print the output.
Having the source code above while writing makes it extremely obvious what will be ran. Take a look at this video below.
https://user-images.githubusercontent.com/66291634/183278967-a4534eb2-5add-4779-b206-7529b7021c25.mp4
\- lm
> vrepl: creating the 'pin' command

- vlib/io/buffered_reader.v
- vlib/io/custom_string_reading_test.v
- vlib/io/io_test.v
- vlib/io/reader.v
- vlib/io/reader_test.v
- vlib/io/readerwriter.v
- vlib/net/http/request_test.v
- vlib/net/openssl/ssl_connection.v
- vlib/net/tcp.v
- vlib/net/websocket/io.v
- vlib/os/file.c.v
- vlib/os/file_test.v
- vlib/v/gen/js/sourcemap/vlq/vlq_decode_test.v
Fixes https://github.com/vlang/v/issues/15197
This PR include an api change in the `ioReader` where the API migration will move from
```v
pub interface Reader {
// read reads up to buf.len bytes and places
// them into buf.
// A type that implements this should return
// `none` on end of stream (EOF) instead of just returning 0
mut:
read(mut buf []u8) ?int
}
````
to
```v
pub interface Reader {
// read reads up to buf.len bytes and places
// them into buf.
// A type that implements this should return
// `io.Eof` on end of stream (EOF) instead of just returning 0
mut:
read(mut buf []u8) !int
}
```
> api: migrate the `io.Reader.read` API return `Result` instead of `Option` type

- vlib/net/http/response.v
Currently (on V 0.3.0 8c33a40, with default flags, and with -prod) the following simple vweb fileserver is capable of immediately serving small text files, 1 MB zip files, 512 MB zip files ... but hung permanently, using 100% CPU per thread per request attempt, if asked to serve a 1.9G zip file.
```v
module main
import vweb
struct App {
vweb.Context
}
fn main() {
if !app.mount_static_folder_at('static', '/down') {
eprintln('failed to mount static folder')
exit(1)
}
vweb.run(app, 6060)
}
```
This was traced to the string interpolation that's removed with this patch, of `'$resp.body'`. Since resp.body is already a string, the interpolation isn't necessary, but it's the difference between 'working' and 'not working' in this case.
I realize the server has other issues, and …
> http: avoid costly string interpolation of resp.body

- vlib/v/checker/check_types.v
- vlib/v/checker/tests/generics_type_ambiguous.out
- vlib/v/tests/generics_with_nested_generics_fn_infer_call_test.v
This PR fix generics with nested generic fn call (fix #15356).
- Fix generics with nested generic fn call.
- Add test.
- Fixed v ui compile error, please commit first.
```v
module main
pub struct Reptile {}
pub struct Insect {}
fn main() {
mut r := Reptile{}
mut i := Insect{}
ret1 := node_search(mut r)
println(ret1)
assert ret1 == Reptile{}
ret2 := node_search(mut i)
println(ret2)
assert ret2 == Insect{}
}
pub fn node_search<T>(mut t T) T {
return hydrate(mut t)
}
fn hydrate<T>(mut t T) T {
return t
}
Reptile{}
Insect{}
```
> checker: fix generics with nested generic fn call (fix #15356)

- vlib/v/gen/c/fn.v
- vlib/v/tests/shared_array_last_test.v
This PR fix shared array.last() (fix #15363).
- Fix shared array.last().
- Add test.
```v
module main
fn main() {
shared a := []int{}
lock  {
a << 1
a << 2
}
rlock a {
println(a.last())
assert a.last() == 2
}
}
2
```
> cgen: fix shared array.last() (fix #15363)

- vlib/v/checker/fn.v
- vlib/v/checker/tests/generics_method_arg_type_err.out
- vlib/v/checker/tests/generics_method_arg_type_err.vv
This PR check generic method call argument mismatch (fix #15282).
- Check generic method call argument mismatch.
- Add test.
```v
module main
pub struct Redis {}
pub struct Reptile {
name string
}
fn main() {
mut r := Redis{}
mut g := Reptile{
name: 'Gecko'
}
r.node_create(mut g)
}
pub fn (mut r Redis) node_create<T>(t T) bool {
return true
}
./tt1.v:14:20: error: `node_create` parameter `t` is not `mut`, `mut` is not needed`
12 |         name: 'Gecko'
13 |     }
14 |     r.node_create(mut g)
|                       ^
15 | }
16 |
```
> checker: check generic method call argument mismatch (fix #15282)

- vlib/v/checker/fn.v
- vlib/v/checker/tests/void_method_call.out
- vlib/v/checker/tests/void_method_call.vv
There used to be an error showing that the type `void` had no such method, but that check was removed.
This PR redoes that check and throws an error when a method is called using an expression whose result type is `void`.
Fix #15324.
> checker: disallow method calls with invalid expressions

- .github/workflows/ci.yml
- .github/workflows/containers_ci.yml
- .github/workflows/native_backend_tests.yml
- Dockerfile
- Dockerfile.alpine
- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/elf.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/native/tests/native_test.v
This PR contains initial linking support for Linux using `ld.lld`. The generated object file now gets linked with some libraries (`libc`, `pthread`, etc.) and the C runtime objects. Currently, this isn't that useful since calling external functions is not implemented yet.
I don't know how many tests will pass... I only tested it on Linux x86_64, other OSes should be unchanged.
> native: initial linking support for linux

- vlib/v/checker/checker.v
This PR add pref.is_verbose for print_backtrace() (related #15383)
```v
sample :=
PS D:\Test\v\tt1> v run tt1.v
tt1.v:1:1: warning: unused variable: `sample`
1 | sample :=
| ~~~~~~
tt1.v:1:1: error: checker.expr(): unhandled EmptyExpr
1 | sample :=
| ^
```
> checker: add pref.is_verbose for print_backtrace (related #15383)

- vlib/v/checker/checker.v
- vlib/v/tests/inout/dump_generic_fn_mut_arg.out
- vlib/v/tests/inout/dump_generic_fn_mut_arg.vv
This PR fix dumping generic fn mut argument (fix #15358).
- Fix dumping generic fn mut argument.
- Add test.
```v
module main
pub struct Reptile {}
fn main() {
mut r := Reptile{}
do(mut r)
}
pub fn do<T>(mut t T) {
dump(t)
}
[.\\tt1.v:11] t: &Reptile{}
```
> checker: fix dumping generic fn mut argument (fix #15358)

- vlib/v/gen/c/fn.v
- vlib/v/tests/shared_struct_method_call_test.v
This PR fix shared struct method call (fix #15380).
- Fix shared struct method call.
- Add test.
```v
module main
struct Aa {
mut:
b []int
}
fn append_ok(shared a Aa, new_b int) {
lock a {
a.b << new_b
}
}
fn (shared a Aa) append_fails(new_b int) {
lock a {
a.b << new_b
}
}
fn main() {
shared a := Aa{}
append_ok(shared a, 1)
a.append_fails(2)
rlock a {
println(a.b)
assert a.b == [1, 2]
}
}
[1, 2]
```
> cgen: fix shared struct method call (fix #15380)

- vlib/v/checker/fn.v
- vlib/v/tests/generics_with_nested_generic_method_call_test.v
This PR fix generics with nested generic method call (fix #15387).
- Fix generics with nested generic method call.
- Add test.
```v
struct Calc<S> {
mut:
typ S
}
struct TypeA {}
struct TypeB {}
fn (mut c Calc<S>) next<T>(input T) f64 {
$if S is TypeA || S is TypeB {
return c.typ.next(input)
} $else {
return 99.0
}
}
fn (mut t TypeA) next<T>(input T) f64 {
return 10.0
}
fn (mut t TypeB) next<T>(input T) f64 {
return 11.0
}
fn main() {
{
mut c := Calc<TypeA>{
typ: TypeA{}
}
assert c.next(100) == 10.0
}
{
mut c := Calc<TypeB>{
typ: TypeB{}
}
assert c.next(100) == 11.0
}
println('OK!!')
}
OK!!
```
> checker: fix generics with nested generic method call (fix #15387)

- vlib/v/gen/c/cgen.v
Avoid a "Suspicious comparison of 'sizeof(expr)' to a constant" warning
issued by clangd LSP while inspecting the generated C code.
> cgen: avoid a compiler warning in generated code

- vlib/vweb/vweb.v
This PR fix vweb static url (fix #15382).
```v
module main
import os
import vweb
struct App {
vweb.Context
}
fn main() {
if !os.is_dir(os.resource_abs_path('static')) {
os.mkdir(os.resource_abs_path('static'))?
os.mkdir(os.resource_abs_path('static/css'))?
os.create(os.resource_abs_path('static/hello.css'))?
os.create(os.resource_abs_path('static/css/style.css'))?
}
app.mount_static_folder_at('./static', '/')
app.display_recorded_static()
vweb.run<App>(&app, 8181)
}
pub fn (mut app App) index() vweb.Result {
return app.text('yo')
}
pub fn (mut app App) display_recorded_static() {
for k,v  in app.static_files {
mut tab := ""
for _ in k.len/8..8 {
tab += "\t"
}
println( k + tab + v)
}
}
/css/style.css …
```
> vweb: fix vweb static url (fix #15382)

- vlib/sokol/sgl/sgl_structs.c.v
This is needed for things like layered font rendering:
[Reference](https://github.com/floooh/sokol/issues/703)
> sokol: expose context_pool_size field on sgl.Desc

- vlib/v/checker/return.v
- vlib/v/checker/tests/return_result_type_mismatch.out
- vlib/v/checker/tests/return_result_type_mismatch.vv
This PR check mismatch of return result type (fix #15395).
- Check mismatch of return result type.
- Add test.
```v
// Result
fn foo(a int) !int {
return a + 1
}
// Option
fn bar(a int) ?int {
return foo(a)
}
fn main() {
x := bar(1)?
println('$x')
}
./tt1.v:8:9: error: cannot use `!int` as type `?int` in return argument
6 | // Option
7 | fn bar(a int) ?int {
8 |     return foo(a)
|            ~~~~~~
9 | }
10 |
```
> checker: check mismatch of return result type (fix #15395)

- vlib/v/ast/str.v
This PR fix expr.str() (fix #12650, fix #13312).
> ast: fix expr.str() (fix #12650 #13312)

- vlib/v/ast/table.v
- vlib/v/tests/anon_fn_with_nested_anon_fn_args_test.v
This PR fix anon fn with nested anon fn argument (fix #15403).
- Fix anon fn with nested anon fn argument.
- Add test.
```v
module main
fn main() {
mut xa := fn (x fn (int) string, y int) string {
return x(y)
}
a := xa(fn (i int) string {
return 'a' + i.str()
}, 8)
println(a)
assert a == 'a8'
}
a8
```
> ast: fix anon fn with nested anon fn argument (fix #15403)

- vlib/v/checker/check_types.v
- vlib/v/tests/generics_with_multi_nested_generic_method_call_test.v
This PR fix generics with multi nested generic method call  (fix #15400).
- Fix generics with multi nested generic method call.
- Add test.
```v
struct Wrapper<S> {
mut:
calc Calc<S>
}
fn (mut w Wrapper<S>) next<T>(input T) f64 {
$if S is TypeA || S is TypeB {
$if T is f64 {
return w.calc.next(input)
} $else {
panic('"$T.name" is not supported')
return -1
}
return -1
} $else {
panic('"$S.name" is not supported')
return -1
}
}
struct Calc<S> {
mut:
typ S
}
struct TypeA {}
struct TypeB {}
fn (mut c Calc<S>) next<T>(input T) f64 {
$if S is TypeA || S is TypeB {
$if T is f64 {
return c.typ.next(input)
} $else {
panic('Unsupported type $T.name')
}
} $else {
panic('Unsupported type $S.name')
}
}
fn (mut t TypeA) next<T>(input T) f64 {
return 10
}
fn (mut t TypeB) next<T>(input T) f64 {
return …
```
> checker: fix generics with multi nested generic method call  (fix #15400)

- cmd/v/help/build-c.txt
There is no arg '-no-prelude'.
> help(build-c): fix arg name

- vlib/v/gen/c/index.v
- vlib/v/tests/array_index_optional.v
- vlib/v/tests/array_index_optional_with_if_expr_test.v
This PR fixes a bug with the use of optional indexes with mutable arrays.
```v
$ cat x.v
struct Arrs {
mut:
x [][]int
}
fn main() {
mut arr := Arrs{
x: [[1, 2]]
}
for mut sub_arr in arr.x {
x := sub_arr[0] or { 3 }
println(x)
assert x == 1
}
}
$ ./v2 run x.v
1
```
Fix #15116.
> cgen: fix optional indexes with mutable arrays

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/generics_with_multi_nested_generic_method_call_ref_arg_test.v
This PR fix generic with multi-nested generic method call ref argument (fix #15417).
- Fix generic with multi-nested generic method call ref argument.
- Add test.
```v
struct Wrapper<S> {
mut:
calc Calc<S>
}
fn (mut w Wrapper<S>) next<T>(input T) f64 {
$if S is TypeA || S is TypeB {
$if T is f64 {
return w.calc.next(input)
} $else $if T is SecretCase {
return w.calc.next(input)
} $else {
panic('"$T.name" is not supported')
return -1
}
return -1
} $else {
panic('"$S.name" is not supported')
return -1
}
}
struct Calc<S> {
mut:
typ   S
inner InnerCalc
}
struct InnerCalc {}
fn (mut c InnerCalc) next<T>(input T) f64 {
$if T is f64 {
return 64.2
} $else {
return 100.0
}
}
struct TypeA {}
struct TypeB {}
interface SecretCase {
secret() f64
}
interface SpecialCase {
SecretCase
}
struct …
```
> cgen: fix generic with multi-nested generic method call ref argument (fix #15417)

- vlib/v/checker/fn.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/inout/closure_with_fn_variables.out
- vlib/v/tests/inout/closure_with_fn_variables.vv
This PR fix closure with fn variables (fix #15286).
- Fix closure with fn variables.
- Add test.
```v
module main
fn test1() {
println('test1')
}
fn test2() {
println('test2')
}
fn main() {
t1 := test1
t2 := test2
anon := fn [t1, t2] () {
t1()
t2()
}
anon()
}
test1
test2
```
> checker, cgen: fix closure with fn variables (fix #15286)

- vlib/v/gen/c/fn.v
- vlib/v/tests/shared_map_delete_test.v
This PR fix shared map delete (fix #15430).
- Fix shared map/array delete.
- Add test.
```v
fn main() {
shared store := map[string]int{}
lock store {
store['abc'] = 5
store['xyz'] = 10
}
lock store {
assert store.len == 2
store.delete('abc')
assert store.len == 1
assert store['xyz'] == 10
}
}
```
> cgen: fix shared map delete (fix #15430)

- vlib/v/gen/c/cgen.v
Avoid a "Suspicious comparison of 'sizeof(expr)' to a constant" warning
issued by clangd LSP while inspecting the generated C code.
This is a follow-up to my previous commit 509536483801
> cgen: avoid another compiler warning in generated code

- vlib/v/gen/c/cgen.v
This PR makes a minor optimization in return_stmt().
- Avoid using temp variable when return ident that has no defer stmts.
> cgen: minor optimization in return_stmt()

- vlib/v/gen/c/assign.v
- vlib/v/gen/c/auto_eq_methods.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/utils.v
- vlib/v/tests/anon_fn_decl_with_anon_fn_params_test.v
This PR fix fn_var_signature() when param type is function.
- Fix fn_var_signature() when param type is function.
- Add test.
```v
fn main() {
a := fn (p1 fn () int, p2 string) string {
n := p1()
return '$n' + p2
}
ret := a(aaa, 'hello')
println(ret)
assert ret == '22hello'
}
fn aaa() int {
return 22
}
22hello
```
generated c codes
```v
string (*a) (int (*) (), string) = 	anon_fn_1315efd87adb6e70_fn__int_string__string_54;
string ret = a((voidptr)main__aaa, _SLIT("hello"));
println(ret);
}
```
> cgen: fix fn_var_signature() when param type is function

- vlib/crypto/rand/rand_freebsd.c.v
- vlib/crypto/rand/rand_openbsd.c.v
Add the OpenBSD arc4random syscall.  Platform-specific of course.
> crypt: add OS-specific source of random bytes for OpenBSD and FreeBSD

- vlib/v/checker/fn.v
- vlib/v/tests/fn_call_mut_array_of_aliases_args_test.v
This PR fix fn call with mut array of aliases arguments (fix #15439).
- Fix fn call with mut array of aliases arguments.
- Add test.
```v
fn f1(mut b []byte) string {
return '$b'
}
fn f2(b []byte) string {
return '$b'
}
fn f3(mut b []u8) string {
return '$b'
}
fn main() {
mut s1 := 'test'.bytes()
ret1 := f1(mut s1)
println(ret1)
assert ret1 == '[116, 101, 115, 116]'
ret2 := f2(s1)
println(ret2)
assert ret2 == '[116, 101, 115, 116]'
ret3 := f3(mut s1)
println(ret3)
assert ret3 == '[116, 101, 115, 116]'
}
[116, 101, 115, 116]
[116, 101, 115, 116]
[116, 101, 115, 116]
```
> checker: fix fn call with mut array of aliases arguments (fix #15439)

- vlib/v/gen/c/fn.v
- vlib/v/tests/go_call_fn_with_anon_fn_arg_test.v
This PR fix go call fn with anon fn argument (fix #10351, fix #10270).
- Fix go call fn with anon fn argument.
- Add test.
```v
fn start(f fn ()) string {
f()
return 'ok!!'
}
fn on_connect() {
println('fn ok!!')
}
fn main() {
g := go start(on_connect)
ret := g.wait()
assert ret == 'ok!!'
}
fn ok!!
```
> cgen: fix go call fn with anon fn argument (fix #10351, fix #10270)

- vlib/v/gen/c/array.v
- vlib/v/tests/array_of_fixed_array_map_test.v
This PR fix array of fixed array map(it[0]) (fix #15422).
- Fix array of fixed array map(it[0]).
- Add test.
```v
fn main() {
mut db := [][2]string{}
db << ['aaa', '111']!
db << ['bbb', '222']!
db << ['ccc', '333']!
keys := db.map(it[0])
println(keys)
assert keys == ['aaa', 'bbb', 'ccc']
}
['aaa', 'bbb', 'ccc']
```
> cgen: fix array of fixed array map/filter/any/all(it[0]) (fix #15422)

- vlib/v/compiler_errors_test.v
- vlib/v/pref/pref.v
- vlib/v/tests/trace_calls/simple.run.out
- vlib/v/tests/trace_calls/simple.vv
- vlib/v/tests/trace_calls/with_modules.run.out
- vlib/v/tests/trace_calls/with_modules.vv
- vlib/v/transformer/transformer.v
This PR will add a new `-trace-calls` flag to `v`:
```
v -trace-calls run examples/json.v
fn main()
fn json_parse(s string) &C.cJSON
fn decode_string(root &C.cJSON) string
fn decode_int(root &C.cJSON) int
fn decode_string(root &C.cJSON) string
fn decode_int(root &C.cJSON) int
Frodo: 25
Bobby: 10
0) Frodo
fn (u User) can_register() bool
fn (mut u User) register()
Frodo is registered
1) Bobby
fn (u User) can_register() bool
Cannot register Bobby, they are too young
fn encode_string(val string) &C.cJSON
fn encode_int(val int) &C.cJSON
fn encode_bool(val bool) &C.cJSON
fn encode_string(val string) &C.cJSON
fn encode_int(val int) &C.cJSON
fn encode_bool(val bool) &C.cJSON
fn json_print(json &C.cJSON) string
[{"name":"Frodo","age":25,"is_registered":true},{"name":"Bobby","age":10,"is_registered" …
```
> v.pref: support `v -trace-calls ...`

- vlib/v/scanner/scanner.v
- vlib/v/tests/scanner_and_and_not_test.v
This PR fix false &&!ok1 (fix #7524).
```v
fn main() {
ok1 := true
ok2 := false &&!ok1
println(ok2)
}
false
```
> scanner: fix false &&!ok1 (fix #7524)

- vlib/v/checker/struct.v
- vlib/v/checker/tests/struct_init_update_type_err.out
- vlib/v/gen/c/struct.v
- vlib/v/tests/struct_init_with_update_test.v
This PR fix struct init with update expr (fix #9472).
- Fix struct init with update expr.
- Using temporary value when update expr is not lvalue.
- Add test.
```v
module main
struct Author {
username string
pass     string
height   int
age      int
}
fn cool_author() Author {
return Author{
username: 'Terisback'
name: 'Bob'
pass: '123456'
height: 175
age: 18
}
}
fn main() {
mut o := Author{
...cool_author()
age: 21
}
println(o)
assert o.username == 'Terisback'
assert o.name == 'Bob'
assert o.pass == '123456'
assert o.height == 175
assert o.age == 21
}
Author{
username: 'Terisback'
name: 'Bob'
pass: '123456'
height: 175
age: 21
}
```
generated c codes:
```v
main__Author _t1 = main__cool_author();
main__Author …
```
> checker: fix struct init with update expr (fix #9472)

- vlib/v/gen/c/cgen.v
- vlib/v/tests/shared_optional_test.v
This PR fix shared optional (fix #9569).
- Fix shared optional.
- Add test.
```v
module main
struct ABC {
mut:
s string
}
fn main() {
shared abc := foo() or { panic('scared') }
rlock abc {
println(abc)
assert abc.s == 'hello'
}
}
fn foo() ?ABC {
mut a := ABC{}
a.bar()?
return a
}
fn (mut a ABC) bar() ? {
a.s = 'hello'
println(a.s)
}
hello
ABC{
s: 'hello'
}
```
> cgen: fix shared optional (fix #9569)

- vlib/v/ast/str.v
- vlib/v/fmt/tests/string_intp_with_result_keep.vv
This PR fix string interpolation fmt with result call (fix #15465).
- Fix string interpolation fmt with result call.
- Add test.
keep fmt:
```v
fn err() !u8 {
return 1
}
fn main() {
println('${err()!}')
}
```
> ast: fix string interpolation fmt with result call (fix #15465)

- vlib/v/checker/infix.v
- vlib/v/checker/tests/infix_and_op_expr_err.out
- vlib/v/checker/tests/infix_and_op_expr_err.vv
- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/infix_expr_and_op_expected.vv
- vlib/v/fmt/tests/infix_expr_and_op_input.vv
This PR check infix_expr with `and` op.
- Check infix_expr with `and` op.
- Fix vfmt of infix_expr with `and` op.
- Add tests.
```v
fn main() {
ok1 := true
ok2 := false&&ok1
println(ok2)
}
./tt1.v:3:17: error: the right expression should be separated from the `&&` by a space
2 |     ok1 := true
3 |     ok2 := false&&ok1
|                 ~~
4 |     println(ok2)
5 | }
```
v fmt:
```v
fn main() {
ok1 := true
ok2 := false&&ok1
println(ok2)
}
```
fmt to
```v
fn main() {
ok1 := true
ok2 := false && ok1
println(ok2)
}
```
> checker, fmt: check infix_expr with 'and' op

- tutorials/building_a_simple_web_blog_with_vweb/README.md
Remove unnecessary `json.encode` in the `/articles` JSON endpoint because the `app.json` already does that.
If it is not removed, the response will look like this:
```
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 151
Server: VWeb
Connection: close
"[{\"id\":1,\"title\":\"Hello, World!\",\"text\":\"V is great!\"},{\"id\":2,\"title\":\"Second post\",\"text\":\"Hmm... What should I write about?\"}]"
```
Here's the response after the proposed changes:
```
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 129
Server: VWeb
Connection: close
[{"id":1,"title":"Hello, World!","text":"V is great!"},{"id":2,"title":"Second post","text":"Hmm... What should I write about?"}]
```
> tutorials: remove unnecessary json.encode in vweb tutorial

- vlib/v/gen/c/cgen.v
- vlib/v/tests/inout/push_on_closed_channel.out
- vlib/v/tests/inout/push_on_closed_channel.vv
This PR fix push on closed channel (fix #15442).
- Fix push on closed channel.
- Add test.
```v
fn main() {
ch := chan int{cap: 100}
ch.close()
ch <- 1 or { println('Channel closed.') }
}
Channel closed.
```
> cgen: fix push on closed channel (fix #15442)

- vlib/v/checker/check_types.v
- vlib/v/tests/comptime_if_generic_shift_test.v
This PR fix comptime if generic value shift (fix #15470).
- Fix comptime if generic value shift.
- Add test.
```v
fn generic<T>(val T) T {
$if T is u64 {
println(val << 1)
return val << 1
}
return val
}
fn main() {
ret := generic(u64(2))
println(ret)
assert ret == 4
}
4
4
```
> checker: fix comptime if generic value shift (fix #15470)

- vlib/v/parser/parse_type.v
- vlib/v/parser/tests/generic_struct_type_using_multi_return_err.out
- vlib/v/parser/tests/generic_struct_type_using_multi_return_err.vv
This PR check generic struct init using multi return type (fix #15369, fix #15366).
- Check generic struct init using multi return type.
- Add test.
```v
struct Tuple<T> {
data T
}
fn main() {
sample := Tuple<(int, int)>{}
println(sample)
}
./tt1.v:6:18: error: cannot use multi return as generic concrete type
4 | 
6 |     sample := Tuple<(int, int)>{}
|                     ~~~~~~~~~~
7 |     println(sample)
8 | }
```
```v
import datatypes { Queue }
fn main() {
example := Queue<(int, int)>{}
// ...
first, second := example.pop()?
// ...
}
./tt1.v:4:19: error: cannot use multi return as generic concrete type
2 |
4 |     example := Queue<(int, int)>{}
|                      ~~~~~~~~~~
5 |     // ...
6 | …
```
> parser: check generic struct init using multi return type (fix #15369)

- cmd/tools/vdoc/utils.v
With this PR `v doc`'s syntax highlighter now highlights symbols which are provided as `variadic` type.
> vdoc: highlight variadic function parameters

- vlib/vweb/README.md
- vlib/vweb/vweb.v
A simple yet powerful web server with built-in routing, parameter handling, templating, and other
features.
The [gitly](https://gitly.org/) site is based on vweb.
**_Some features may not be complete, and have some bugs._**
- **Very fast** performance of C on the web.
- **Small binary** hello world website is <100 KB.
- **Easy to deploy** just one binary file that also includes all templates. No need to install any
dependencies.
- **Templates are precompiled** all errors are visible at compilation time, not at runtime.
There are some examples
that can be explored [here](https://github.com/vlang/v/tree/master/examples/vweb).
And others like:
- [vweb_orm_jwt](https://github.com/vlang/v/tree/master/examples/vweb_orm_jwt) (back-end)
- [vorum](https://github.com/vlang/vorum) (front-end)
- …
> vweb/doc: vlib/vweb/README.md improvement

- doc/docs.md
As discussed on Discord, document the current V implementation
dependent lack of guarantee of the evaluation order of function
parameters.
See: https://discord.com/channels/592103645835821068/592114487759470596/1009858931776032888
Closes #15463
> docs: add a `Parameter evaluation order` section

- vlib/v/builder/cc.v
- vlib/v/builder/cflags.v
- vlib/v/builder/msvc_windows.v
- vlib/v/builder/rebuilding.v
- vlib/v/vcache/vcache.v
The new cache paths look like this:
```
~/.vmodules/cache/49/49c109d7fb7f6c858a87b8bc7bb1b0f6.dependencies
~/.vmodules/cache/49/49c109d7fb7f6c858a87b8bc7bb1b0f6.build_options
~/.vmodules/cache/98
~/.vmodules/cache/98/982b25d7ee599f6992721973814f1dad.module.v.vnew.os.description.txt
~/.vmodules/cache/98/982b25d7ee599f6992721973814f1dad.module.v.vnew.os.o
~/.vmodules/cache/a8
~/.vmodules/cache/a8/a8bbfbaffbdd74d9123249a226d92a80.module.v.vnew.strings.textscanner.o
~/.vmodules/cache/a8/a8bbfbaffbdd74d9123249a226d92a80.module.v.vnew.strings.textscanner.description.txt
~/.vmodules/cache/b7
~/.vmodules/cache/b7/b7dc6d156ddb2811a4684aefe4889354.hashes
~/.vmodules/cache/embed_file
~/.vmodules/cache/8e
~/.vmodules/cache/8e/8e2cfe3dbe1495b4d5dd51633a0346b2.module.v.vnew.sokol.sapp.description.txt …
```
> v.vcache, v.builder: use the module name inside the usecache paths (for more readable cache entries at a glance)

- vlib/v/checker/fn.v
- vlib/v/tests/generics_method_with_nested_generic_method_test.v
This PR fix generic method with nested generic method (fix #15475).
- Fix generic method with nested generic method.
- Fix test with propgate result.
- Add test.
```v
fn (dummy &Dummy) res<T>() !T {
$if T is int {
return 1
} $else $if T is f32 {
return dummy.res<int>()! + 1
} $else {
return error('exhausted')
}
}
fn main() {
d := Dummy{}
println(d.res<int>()!)
ret1 := d.res<int>()!
assert ret1 == 1
println(d.res<f32>()!)
ret2 := d.res<f32>()!
assert ret2 == 2.0
}
1
2.
```
> checker: fix generic method with nested generic method (fix #15475)

- vlib/datatypes/set.v
This PR make Set's methods public (fix #15488).
```v
module main
import datatypes {Set}
fn main() {
mut my_set := Set<u32>{}
my_set.add(1)
my_set.add(3)
my_set.add(2)
my_set.add(2)
my_set.add(2)
my_set.remove(1)
my_set.remove(2)
my_set.remove(3)
println(my_set.is_empty())
}
true
```
> datatypes: make Set's methods public (fix #15488)

- vlib/v/scanner/scanner.v
- vlib/v/scanner/tests/invalid_unicode_err.out
- vlib/v/scanner/tests/invalid_unicode_err.vv
Fixes https://github.com/vlang/v/issues/10717
Works for both `rune` and `string` types
> scanner: add check for invalid unicode

- vlib/json/json_test.v
- vlib/v/gen/c/json.v
This PR fix json encode struct with alias field (fix #15486).
- Fix json encode struct with alias field.
- Add test.
```v
import json
struct Aa {
sub SumType
}
struct Bb {
a int
}
type SumType = Bb
fn main() {
s := json.encode(Aa{
sub: Bb{
a: 1
}
})
println(s)
assert s == '{"sub":{"a":1}}'
}
{"sub":{"a":1}}
```
> cgen: fix json encode struct with alias field (fix #15486)

- vlib/v/gen/c/match.v
- vlib/v/tests/match_sumtype_var_with_none_test.v
This PR fix match sumtyp var with `none` (fix #15481).
- Fix match sumtyp var with `none`.
- Add test.
```v
fn number() int|none {
return none
}
fn main() {
n := number()
ret := match n {
int { 'n: $n' }
none { '?' }
}
println(ret)
assert ret == '?'
}
?
```
> cgen: fix match sumtype var with `none` (fix #15481)

- vlib/v/gen/c/infix.v
- vlib/v/tests/inout/printing_sumtype_with_none.out
- vlib/v/tests/inout/printing_sumtype_with_none.vv
This PR fix if sumtype var is `none` (fix #15479).
- Fix if sumtype var is `none`.
- Add test.
```v
module main
struct None {}
my_first_field  string|none
my_second_field string|none
my_third_field  string|None
}
fn main() {
s := MyStruct{
my_first_field: 'blah'
my_second_field: none
my_third_field: None{}
}
println(if s.my_first_field is string {
'first field is a string'
} else {
'first field is none'
})
println(if s.my_second_field is none {
'second field is none'
} else {
'second field is a string'
})
println(if s.my_third_field is None {
'third field is None'
} else {
'third field is a string'
})
}
first field is a string
second field is none
third field is None
```
> cgen: fix if sumtype var is `none` (fix #15479)

- vlib/builtin/array.v
- vlib/v/tests/c_array_test.c
- vlib/v/tests/c_array_test.v
This PR adds a convenience function like `cstring_to_vstring`.
Closes #15493
> builtin: add carray_to_varray, closes #15493

- vlib/arrays/arrays.v
- vlib/builtin/array.v
- vlib/v/tests/c_array_test.c
- vlib/v/tests/c_array_test.v
This PR moves `carray_to_varray` to `arrays` and makes it generic, as Alex suggests in #15499
> arrays: move carray_to_varray, make it generic

- vlib/v/checker/checker.v
- vlib/v/checker/struct.v
- vlib/v/checker/tests/unknown_array_fn_type_in_struct_field.out
- vlib/v/checker/tests/unknown_array_fn_type_in_struct_field.vv
This PR check unknown array of fn type in struct field  (fix #9380).
- Check unknown array of fn type in struct field.
- Add test.
```v
struct Virt {
fns [2]fn (num u32) UnknownThing
}
fn (virt Virt) caller() {
func := virt.fns[0]
func(5)
}
fn main() {}
./tt1.v:2:22: error: unknown type `UnknownThing`.
Did you mean `[2]fn (u32) UnknownThing`?
1 | struct Virt {
2 |     fns [2]fn (num u32) UnknownThing
|                         ~~~~~~~~~~~~
3 | }
4 |
```
```v
struct Virt {
fns[2] fn (num u32)
}
fn print_table(virt &Virt) {
println(virt)
}
fn main() {
virt := Virt{}
print_table(&virt)
}
&Virt{
fns: [fn (u32), fn (u32)]
}
```
```v
struct Context {
virt &Virt
}
struct Virt {
set[2] fn (virt &Virt)
}
pub fn (ctx &Context) set_fill_style() { …
```
> checker: check unknown array of fn type in struct field  (fix #9380)

- cmd/tools/vdoc/utils.v
Fixes https://github.com/vlang/v/issues/15498
> vdoc: highlight generic structs properly

- vlib/v/checker/fn.v
This PR prevents warning from being displayed with `free` methods already marked as `unsafe`.
before:
```v
warning: manual memory management with `free()` is only allowed in unsafe code
6 |
7 | x := ""
8 | x.free()
|   ~~~~~~
warning: method `string.free` must be called from an `unsafe` block
6 |
7 | x := ""
8 | x.free()
|   ~~~~~~
```
after:
```v
warning: method `string.free` must be called from an `unsafe` block
6 |
7 | "".free()
|    ~~~~~~
```
> checker: don't show warning with `free` methods already marked as `unsafe`

- vlib/v/gen/c/array.v
- vlib/v/tests/array_with_it_test.v
This PR fix array init with it (fix #15521).
- Fix array init with it.
- Add test.
```v
fn main() {
input := [3.1, 1.1]
arr := []f64{len: 3, init: input[it] or { 0.0 }}
println(arr)
assert arr[0] == 3.1
assert arr[1] == 1.1
assert arr[2] == 0.0
}
[3.1, 1.1, 0]
```
> cgen: fix array init with it (fix #15521)

- cmd/tools/vgret.v
- cmd/tools/vpm.v
- cmd/tools/vrepl.v
- vlib/datatypes/linked_list.v
- vlib/math/big/special_array_ops.v
- vlib/mysql/orm.v
- vlib/net/html/data_structures.v
- vlib/semver/parse.v
- vlib/v/ast/table.v
- vlib/v/checker/assign.v
- vlib/v/checker/check_types.v
- vlib/v/checker/checker.v
- vlib/v/checker/return.v
- vlib/v/checker/tests/array_assign_err.out
- vlib/v/checker/tests/array_assign_err.vv
- vlib/v/checker/tests/array_or_map_assign_err.out
- vlib/v/fmt/fmt.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/golang/golang.v
- vlib/v/gen/js/fn.v
- vlib/v/parser/assign.v
- vlib/v/parser/fn.v
- vlib/v/parser/parser.v
- vlib/v/tests/shared_elem_test.v
This PR check unsafe array assign (fix #9651).
- Check unsafe array assign.
- Add test.
- Modify all the related issues.
```v
struct Dumb {
mut:
v []int
}
fn main() {
a := Dumb{[1, 2, 3]}
mut b := a.v // I expect a compiler error
for _ in 0 .. 100 {
b << [4, 5, 6]
}
println(a) // prints [4,5,6] in this case, but I've also seen crashes
}
./tt1.v:8:8: error: use `mut array2 := array1.clone()` instead of `mut array2 := array1` (or use `unsafe`)
6 | fn main() {
7 |     a := Dumb{[1, 2, 3]}
8 |     mut b := a.v // I expect a compiler error
|           ~~
9 |     for _ in 0 .. 100 {
10 |         b << [4, 5, 6]
```
> checker: check unsafe array assign (fix #9651)

- vlib/v/checker/return.v
- vlib/v/gen/c/fn.v
- vlib/v/parser/fn.v
- vlib/v/tests/generics_closure_fn_test.v
This PR implement generics anon fn (fix #15120, fix #13253).
- Implement generics anon fn.
- Add test.
```v
fn setter<T>(mut m map[T]int) fn (T, int) {
return fn [mut m] <T>(x T, k int) {
m[x] = k
}
}
fn main() {
mut m := {
f32(0.1): 1
}
f := setter(mut m)
f(0.2, 2)
println(m)
assert m == {
f32(0.1): 1
0.2:      2
}
}
{0.1: 1, 0.2: 2}
```
```v
fn closure<T>(input T) fn () T {
return fn [input] <T>() T {
return input
}
}
fn main() {
f := closure(123)
println(f())
}
123
```
> parser, checker, cgen: implement generics anon fn (fix #15120)

- vlib/os/os_nix.c.v
Hey,
I found a small typo in your error handling when passed a folder which isn't a folder. 
The resulting error message is: "builder error: `folder` is not a folder"
I can reproduce it on my ubuntu 20.04.1 by typing: touch not_a_folder ; v not_a_folder/main.v
I hope that was helpful. It was also my very first pull request to v.
:wave:
> os: typo in error message - `folder` instead of `$folder`

- vlib/v/ast/table.v
- vlib/v/parser/parser.v
- vlib/v/parser/struct.v
- vlib/v/parser/v_parser_test.v
a.v:
```v
module main
import json
fn main() {
_ := json.decode(Foo, '{}') or { return }
}
struct Foo {
data []struct {
name string
}
}
```
b.v:
```v
module main
pub struct Bar {
data []struct {
name string
}
}
```
pass through.
> parser: fixed #15516 Anonymous struct name conflict

- vlib/v/gen/c/assign.v
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/for.v
- vlib/v/gen/c/infix.v
- vlib/v/gen/js/fn.v
This PR clean up generic_fn_name() in cgen.
- Remove unused parameter `is_decl`.
> cgen: cleanup generic_fn_name()

- cmd/tools/vwhere/finder.v
Fix #15046 edge case, when you are in the v compilers directory, and you run `v where fn <function to look for>` and it will collect the results two times, first time in the current dir, second time in the vlib_dir.
> cmd/tools/where: check if parent already included vlib_dir

- vlib/v/checker/assign.v
- vlib/v/checker/tests/assign_with_dump_multireturn_value.out
- vlib/v/checker/tests/assign_with_dump_multireturn_value.vv
This PR check error for simple assignment with dumping of multireturn value
```v
fn two_returns() (string, string) {
return 'hello', 'world'
}
x := dump(two_returns())
println(x)
```
```v
x.v:3:3: error: assignment mismatch: 1 variable(s) 2 value(s)
1 | fn two_returns() (string, string) { return 'hello', 'world' }
2 |
3 | x := dump(two_returns())
|   ~~
4 | println(x)
```
Fix #9346.
> checker: check error for simple assignment with dumping of multireturn value

- vlib/log/log.v
- vlib/log/log_test.v
There is a utility function `level_from_tag` for `LogLevel`, but the same did not exist for `LogTarget`. This PR adds it, along with some unit tests.
> log: add target_from_label and unit tests

- vlib/v/ast/ast.v
- vlib/v/gen/c/fn.v
- vlib/v/parser/fn.v
- vlib/v/tests/inout/closure_with_nested_closure_var.out
- vlib/v/tests/inout/closure_with_nested_closure_var.vv
This PR fix closure with nested closure variable (fix #15270).
- Fix closure with nested closure variable.
- Add test.
```v
module main
interface Test {
test(fn (Test))
}
struct Test1 {
}
fn (t Test1) test(f fn (Test)) {
f(Test(t))
}
fn main() {
t := Test1{}
t.test(fn [t] (t1 Test) {
println('$t, $t1')
t.test(fn [t] (t2 Test) {
println('$t, $t2')
})
})
}
Test1{}, Test(Test1{})
Test1{}, Test(Test1{})
```
> ast, parser, cgen: fix closure with nested closure variable (fix #15270)

- vlib/v/pref/should_compile.v
Reduces the generated C source code by ~2KB.
It also makes it more compatible with https://github.com/vnmakarov/mir (use `v -gc none -o x.c examples/hello_world.v`, then `c2m ./x.c -ei`).
> v.pref: skip vlib/builtin/prealloc.c.v, when -prealloc is not passed

- vlib/v/checker/assign.v
- vlib/v/checker/tests/array_plus_assign_err.out
- vlib/v/checker/tests/array_plus_assign_err.vv
This PR fix no error on performing plus-assigning on array (fix #15544):
- Fix condition checking
- Add output test
```v
mut buffer := []u8{cap: 1024}
buffer += "ipconfig && sudo apt-get install -y some_amazing_package name + command output".bytes()
>>>
./vlib/v/checker/tests/array_plus_assign_err.vv:1:5: warning: unused variable: `buffer`
1 | mut buffer := []u8{cap: 1024}
|     ~~~~~~
2 | buffer += "ipconfig && sudo apt-get install -y some_amazing_package name + command output".bytes()
./vlib/v/checker/tests/array_plus_assign_err.vv:2:1: error: operator `+=` not defined on left operand type `[]u8`
1 | mut buffer := []u8{cap: 1024}
2 | buffer += "ipconfig && sudo apt-get install -y some_amazing_package name + command output".bytes()
| ~~~~~~
```
> checker: fix no error on plus-assigning array (fix #15544)

- vlib/v/ast/table.v
- vlib/v/checker/check_types.v
- vlib/v/checker/checker.v
- vlib/v/parser/fn.v
- vlib/v/parser/parse_type.v
This PR clean up `table.find_or_register_fn_type()`.
- Remove `mod` parameter.
> ast: clean up `table.find_or_register_fn_type()`

- vlib/vweb/README.md
To handle the query context, you just need use the  `query` field
**Example:**
```v
module main
import vweb
struct App {
vweb.Context
}
fn main() {
vweb.run(&App{}, 8081)
}
['/user'; get]
pub fn (mut app App) controller_get_user_by_id() vweb.Result {
// http://localhost:3000/user?q=vpm&order_by=desc => { 'q': 'vpm', 'order_by': 'desc' }
return app.text(app.query.str())
}
```
> doc: query

- vlib/encoding/csv/reader.v
- vlib/encoding/csv/writer.v
- vlib/encoding/csv/writer_test.v
This PR tweaks the encapsulation of fields in encoding.csv.Writer and encoding.csv.Reader (fix #15558):
- Writer now follows up Reader's config struct to allow users to customize `delimiter` and `use_crlf` options
- Reader is now unable to be created outside of the module, and makes `delimiter` and `comment` immutable
> encoding.csv: Re-encapsulate fields in Writer/Reader (fix #15558)

- vlib/v/checker/checker.v
- vlib/v/checker/tests/result_missing_propagate_err.out
- vlib/v/checker/tests/result_missing_propagate_err.vv
- vlib/v/checker/tests/wrong_propagate_ret_type.out
- vlib/v/checker/tests/wrong_propagate_ret_type.vv
This PR fix illegal result propagate on non-result type (fix #15574):
- Error on illegal result propagate
- Add output tests
```v
fn result() !int {
return 1
}
fn main() {
a := result()
println(a)
}
>>>
vlib/v/checker/tests/result_missing_propagate_err.vv:6:7: error: result() returns a result, so it should have either an `or {}` block, or `!` at the end
4 |
6 |     a := result()
7 |     println(a)
8 | }
```
```v
fn ret_none() ?int {
return none
}
fn ret_bool() bool {
return true
}
fn opt_call() int {
a := ret_none()?
return a
}
fn res_call() bool {
a := ret_bool()!
return a
}
>>>
vlib/v/checker/tests/wrong_propagate_ret_type.vv:6:17: error: to propagate the optional call, `opt_call` must return an optional
4 |
5 | fn opt_call() int {
6 |     a := …
```
> checker: fix illegal result propagate on non-result type (fix #15574)

- vlib/v/gen/c/assign.v
- vlib/v/tests/cross_assign_fixed_array_test.v
This PR fix cross assign of fixed array (fix #15577).
- Fix cross assign of fixed array.
- Add test.
```v
fn main() {
number := 5
ans := fib(number)
println(ans)
assert ans == 21
}
fn fib(n int) u64 {
if n <= 0 {
panic('Bad number')
}
return match n {
1 | 2 {
1
}
else {
mut pair := [1, 2]!
for _ in 0 .. n {
pair[0], pair[1] = pair[1], pair[0] + pair[1]
}
pair[1]
}
}
}
21
```
> cgen: fix cross assign of fixed array (fix #15577)

- vlib/net/smtp/smtp.v
- vlib/net/smtp/smtp_test.v
When the format of the message body is a little complicated, the body display will be very confusing, and base64 encoding needs to be added.
> smtp: Add base64 encoding to the body of the email to prevent the format confusion

- .github/workflows/toml_ci.yml
This PR phases out the use of Ubuntu 18.04 in the TOML tests.
> ci: use ubuntu-latest for toml tests

- vlib/v/gen/c/struct.v
- vlib/v/tests/struct_init_with_update_test.v
This PR fix struct init with update expr (fix #15595).
- Fix struct init with update expr.
- Add test.
```v
struct Foo{
s string
n int
}
fn main(){
f := &Foo{s:'AA'}
b := Foo{
...*f
n: 3
}
println(b)
assert b.s == 'AA'
assert b.n == 3
}
Foo{
s: 'AA'
n: 3
}
```
> cgen: fix struct init with update expr (fix #15595)

- vlib/v/checker/checker.v
- vlib/v/checker/tests/cast_to_ref_struct_err.out
- vlib/v/checker/tests/cast_to_ref_struct_err.vv
This PR check cast to reference struct (fix #15590).
- Check cast to reference struct.
- Add test.
```v
module main
pub struct SomeError {
mut:
msg string
}
fn main() {
a := unsafe { &SomeError('yo') }
println(a)
}
./tt1.v:9:16: error: cannot cast `string` to `&SomeError`
7 |
9 |     a := unsafe { &SomeError('yo') }
|                   ~~~~~~~~~~~~~~~~
10 |     println(a)
11 | }
```
> checker: check cast to reference struct (fix #15590)

- vlib/v/ast/table.v
- vlib/v/parser/parse_type.v
- vlib/v/parser/parser.v
- vlib/v/tests/inout/sumtype_with_fntype.out
- vlib/v/tests/inout/sumtype_with_fntype.vv
This PR fix sumtype with multi fntype (fix #15557).
- Fix sumtype with multi fntype.
- Add test.
```v
type Fn = fn () int | fn (int) int
fn main() {
f1 := Fn(fn (a int) int {
return a
})
println(typeof(f1).name)
f2 := Fn(fn () int {
return 22
})
println(typeof(f2).name)
}
Fn
Fn
```
> parser: fix sumtype with multi fntype (fix #15557)

- vlib/v/gen/c/dumpexpr.v
- vlib/v/tests/inout/dump_shared_arg.out
- vlib/v/tests/inout/dump_shared_arg.vv
This PR fix dumping shared variable (fix #15573).
- Fix dumping shared variable.
- Add test.
```v
module main
struct AtomicStruct {
a int
}
fn main() {
shared inst := AtomicStruct{
a: 1
}
lock inst {
dump(inst)
}
}
[.\\tt1.v:10] inst: &AtomicStruct{
a: 1
}
```
> cgen: fix dumping shared variable (fix #15573)

- GNUmakefile
- vlib/time/time_nix.c.v
#6605 has been fixed in the [MacPorts build](https://ports.macports.org/port/vlang/) of V. This has been tested since it builds from source on the [MacPorts builders](https://ports.macports.org/port/vlang/builds/) pre-10.12 (Darwin 16), whilst without the patches it doesn't. (see ﻿https://github.com/vlang/v/issues/7396).
This PR aims to replicate these changes in the upstream source code as closely as possible. [MacPorts legacy support](https://github.com/macports/macports-legacy-support) is built on required macOS versions in `TMPLEGACY`, and the V binary is linked to the libs in `LEGACYLIBS`.
I don't have a machine to test this on, so this PR is a bit of guesswork. For reference, [here](https://build.macports.org/builders/ports-10.7_x86_64-builder/builds/110524/steps/install-port/logs/st …
> make: add clock_gettime on macOS < 10.12 (fix #6605)

- vlib/crypto/ed25519/internal/ed25519_test.v
- vlib/sync/pool/README.md
- vlib/v/checker/checker.v
- vlib/v/checker/tests/cast_voidptr_to_struct_err.out
- vlib/v/checker/tests/cast_voidptr_to_struct_err.vv
- vlib/v/gen/c/cgen.v
- vlib/v/tests/generic_interface_infer_test.v
This PR check casting voidptr to generic struct (fix #15618).
- Check casting voidptr to generic struct.
- Add test.
```v
struct Foo {
x int
}
fn unwrap_concrete(ptr voidptr) Foo {
return Foo(ptr)
}
fn unwrap_generic<T>(ptr voidptr) T {
return T(ptr)
}
pub fn main() {
foo1 := unwrap_concrete(voidptr(0))
foo2 := unwrap_generic<Foo>(voidptr(0))
println(foo1)
println(foo2)
}
./tt1.v:6:9: error: cannot cast `voidptr` to struct
4 |
5 | fn unwrap_concrete(ptr voidptr) Foo {
6 |     return Foo(ptr)
|            ~~~~~~~~
7 | }
8 |
./tt1.v:10:9: error: cannot cast `voidptr` to struct
8 |
9 | fn unwrap_generic<T>(ptr voidptr) T {
10 |     return T(ptr)
|            ~~~~~~
11 | }
12 |
```
> checker: check casting voidptr to generic struct (fix #15618)

- vlib/v/gen/native/elf.v
This fixes the linker failing when:
- 32 bit libraries exist in `/usr/lib`.
- 64 bit libraries are in `/usr/lib64` and not `/usr/lib/x86_64-linux-gnu`.
> native: fix order and add missing path in find_o_path()

- vlib/encoding/csv/writer.v
This PR makes a minor cleanup in writer.v.
warning before:
```v
vlib/encoding/csv/writer.v:17:19: warning: unnecessary default value `false`: struct fields are zeroed by default
15 | [params]
16 | pub struct WriterConfig {
17 |     use_crlf  bool = false
|                      ~~~~~
18 |     delimiter u8   = `,`
19 | }
```
> csv: minor cleanup in writer.v

- vlib/v/checker/fn.v
- vlib/v/checker/tests/fn_variadic_arg_err.out
- vlib/v/checker/tests/fn_variadic_arg_err.vv
This PR check fn variadic passing arg error (fix #15629).
- Check fn variadic passing arg error.
- Add test.
```v
module main
fn main() {
a := [u8(1), 2, 3, 4]
varg_fn_a(a)
}
fn varg_fn_a(b ...u8) {
println(b)
}
./tt1.v:5:2: error: to pass `a` ([]u8) to `varg_fn_a` (which accepts type `...u8`), use `...a`
4 |     a := [u8(1), 2, 3, 4]
5 |     varg_fn_a(a)
|     ~~~~~~~~~~~~
6 | }
7 |
```
> checker: check fn variadic passing arg error (fix #15629)

- vlib/v/gen/c/assert.v
This PR fix assert value is '*unknown value*' (fix #15640).
```v
fn main() {
res := ['one', 'two', 'three']
assert res[0] == 'three'
}
.\\tt1.v:3: FAIL: fn main.main: assert res[0] == 'three'
left value: res[0] = one
right value: 'three' = three
V panic: Assertion failed...
v hash: 4bd49a0
C:/Users/yuyi9/AppData/Local/Temp/v_0/tt1.8983093021732834113.tmp.c:6667: at _v_panic: Backtrace
C:/Users/yuyi9/AppData/Local/Temp/v_0/tt1.8983093021732834113.tmp.c:12188: by main__main
C:/Users/yuyi9/AppData/Local/Temp/v_0/tt1.8983093021732834113.tmp.c:12559: by wmain
0046ec38 : by ???
0046ed9b : by ???
7ff889d2244d : by ???
```
> cgen: fix assert value is '*unknown value*' (fix #15640)

- vlib/builtin/map_test.v
- vlib/v/gen/c/fn.v
This PR fix alias of map delete (fix #15641).
- Fix alias of map delete.
- Add test.
```v
type Map = map[int]int
fn main() {
mut m := Map(map[int]int{})
m[11] = 111
m[22] = 222
println(m)
m.delete(11)
println(m)
assert m.len == 1
assert m[22] == 222
}
Map({11: 111, 22: 222})
Map({22: 222})
```
> cgen: fix alias of map delete (fix #15641)

- vlib/v/checker/if.v
- vlib/v/checker/tests/if_guard_variables_err.out
- vlib/v/checker/tests/if_guard_variables_err.vv
This PR check if guard with multiple return variable (fix #9350).
- Check if guard with multiple return variable.
- Add test.
```v
fn maybe() ?(int, int) {
return 1, 2
}
fn main() {
if x := maybe() {
println('$x')
}
}
./tt1.v:6:2: error: if guard expects 2 variables, but got 1
4 | 
6 |     if x := maybe() {
|     ~~~~~~~~~~~~~~~
7 |         println('$x')
8 |     }
```
> checker: check if guard with multiple return variable (fix #9350)

- vlib/v/gen/c/match.v
- vlib/v/tests/match_expr_with_struct_init_test.v
This PR fix match expr with optional (fix #15650).
- Fix match expr with optional.
- Add test.
```v
struct Test {
a string
}
fn main() {
a := map[string]string{}
b := match 'test' {
'test' {
Test{a['test'] or { '' }}
}
else {
Test{''}
}
}
println(b)
assert b.a == ''
}
Test{
a: ''
}
```
> cgen: fix match expr with optional (fix #15650)

- vlib/os/environment.c.v
I noticed that this function wasn't needed anymore after I went  hunting for references to `C.environ` in vlib as I wanted a multi-argument `os.system` using `C.posix_spawnp` (so that I didn't have to worry about the shell possibly interpreting some arbitrary text passed to the command).
This patch just removes the function, replacing its one use with `&&char(C.environ)`
`v test-all` is the same with and without the patch.
> os: remove unix_environ() helper function as no longer needed

- cmd/tools/vgret.v
- cmd/v/help/gret.txt
This PR adds region support to the `generic_screenshot` capture method.
Among other useful things - it's intended to improve the reliability of the doom-regression-tests by letting the game run long enough, past the title screen, for us to capture glimpses of the UI - this way we do not fight the timing for when the title screen is showed but instead the longer running kiosk mode - giving us more time to capture something reliable.
I still see one pit-fall for this method: when the AI player picks up a health/amour pack or takes damage from an enemy - the screen flashes either green or red (including the UI) this will probably trigger a false positive BUT I think/hope we might be able to tweak it by adjusting parameters of the `idiff` tool when the shots are compared (hard to capture them …
> vgret: add region support

- vlib/v/gen/c/assign.v
- vlib/v/gen/c/auto_eq_methods.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/utils.v
- vlib/v/tests/go_call_anon_fn_with_closure_test.v
This PR fix go call anon fn with closure (fix #15526, fix #15634).
- Fix go call anon fn with closure.
- Add test.
```v
fn main() {
a := 1
b := fn [a] () int {
println(a)
return a
}
g := go b()
ret := g.wait()
}
1
```
```v
fn main() {
m := {
'key1': 1
'key2': 2
}
h := go fn [m] () int {
println(m['key2'])
return m['key2']
}()
ret := h.wait()
assert ret == 2
}
2
```
> cgen: fix go call anon fn with closure (fix #15526, #15634)

- vlib/v/gen/c/assign.v
- vlib/v/gen/c/utils.v
- vlib/v/tests/fn_var_name_using_reserved_test.v
This PR fix fn variable name using reserved c word (fix #15647).
- Fix fn variable name using reserved c word.
- Add test.
```v
fn ret_int() fn (int) int {
return fn (i int) int {
return i
}
}
fn main() {
new := ret_int()
println(new(42))
assert new(42) == 42
}
42
```
> cgen: fix fn variable name using reserved c word (fix #15647)

- vlib/v/checker/fn.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/go_call_fn_using_map_value_test.v
This PR fix go call fn using map value (fix #13820).
- Fix go call fn using map value.
- Add test.
```v
module main
fn main() {
sum := fn (x int, y int) int {
return x + y
}
mut fns := map[string]fn (int, int) int{}
fns['sum'] = sum
g := go fns['sum'](2, 3)
x := g.wait()
println('$x')
assert x == 5
}
5
```
> checker, cgen: fix go call fn using map value (fix #13820)

- vlib/v/gen/c/if.v
- vlib/v/tests/if_expr_with_index_expr_test.v
This PR fix if expr with index expr (fix #15664).
- Fix if expr with index expr.
- Add test.
```v
import rand
fn main() {
a := [1, 2, 3]
b := if true { a[rand.intn(a.len) or { 0 }] } else { 0 }
println(b)
}
3
```
> cgen: fix if expr with index expr (fix #15664)

- vlib/v/checker/checker.v
- vlib/v/checker/tests/globals/name_conflict_with_const.out
- vlib/v/checker/tests/globals/name_conflict_with_const.vv
```v
const (
aaaa = 'abc'
)
__global (
aaaa = 123
)
```
output:
```
a.v:47:2: error: duplicate global and const `aaaa`
45 | 
46 | __global (
47 |     aaaa = 123
|     ~~~~
48 | )
49 |
```
> checker: fix missing name conflict check of const and __global variables. fix: #15668

- vlib/v/gen/c/if.v
- vlib/v/gen/c/match.v
- vlib/v/tests/if_expr_with_index_expr_test.v
This PR refactor `need_tmp_var_in_expr()` and `need_tmp_var_in_match()`. (fix #15675)
- Refactor `need_tmp_var_in_expr()` and `need_tmp_var_in_match()`.
- Add test.
```v
import rand
struct Foo {
name string
}
fn main() {
a := [Foo{'abc1'}, Foo{'abc2'}, Foo{'abc3'}]
b := if true { a[rand.intn(a.len) or { 0 }].name } else { 'not found' }
println(b)
}
abc3
```
> cgen: refactor `need_tmp_var_in_expr/match()` (fix #15675)

- vlib/v/gen/c/cgen.v
- vlib/v/tests/sumtype_with_fntype_test.v
This PR fix sumtype with fntype using fn directly (fix #15674).
- Fix sumtype with fntype using fn directly.
- Add test.
```v
type Expr = fn () int | fn (int) int
fn id(n int) int {
return n
}
fn func() Expr {
return id
}
fn main() {
f := func()
f1 := f as fn (int) int
println(123)
assert f1(123) == 123
if f is fn (int) int {
ret := f(123)
println(ret)
assert ret == 123
}
match f {
fn (int) int {
ret := f(321)
println(ret)
assert ret == 321
}
else {}
}
}
123
123
321
```
> cgen: fix sumtype with fntype using fn directly (fix #15674)

- vlib/v/checker/struct.v
- vlib/v/checker/tests/generics_non_generic_struct_used_like_a_generic_one.out
- vlib/v/checker/tests/generics_non_generic_struct_used_like_a_generic_one.vv
This PR check non generic struct used like a generic one  (fix #15677).
- Check non generic struct used like a generic one.
- Add test.
```v
struct Toy{
toy_name string
}
fn get_toy1(toy Toy) Toy{
return Toy<T>{toy.toy_name}
}
fn get_toy2(toy Toy) Toy{
return Toy<T,U>{toy.toy_name}
}
fn main() {
println(get_toy1(Toy{'Fire Truck'}))
println(get_toy2(Toy{'Police Car'}))
}
./tt1.v:6:9: error: a non generic struct `Toy` used like a generic struct
4 | 
5 | fn get_toy1(toy Toy) Toy{
6 |     return Toy<T>{toy.toy_name}
|            ~~~
7 | }
8 |
./tt1.v:10:9: error: a non generic struct `Toy` used like a generic struct
8 |
9 | fn get_toy2(toy Toy) Toy{
10 |     return Toy<T,U>{toy.toy_name}
|            ~~~
11 | }
12 |
```
> checker: check non generic struct used like a generic one  (fix #15677)

- vlib/v/checker/match.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/match.v
- vlib/v/tests/match_expr_with_result_test.v
This PR fix match expr with result (fix #15703).
- Fix match expr with result.
- Add test.
```v
fn foo(i int) ?bool {
return match true {
i == 0 { true }
else { none }
}
}
fn bar(i int) !bool {
return match true {
i == 0 { true }
else { error('') }
}
}
fn main() {
r1 := foo(0) or { false }
println(r1)
assert r1
r2 := bar(0) or { false }
println(r2)
assert r2
}
true
true
```
> checker, cgen: fix match expr with result (fix #15703)

- vlib/v/gen/c/if.v
- vlib/v/tests/if_expr_with_fn_call_result_test.v
This PR fix if expr with fn call result (fix #15700).
- Fix if expr with fn call result.
- Add test.
```v
fn foo() !int {
return 0
}
fn bar(n int) bool {
return true
}
fn is_ok(b bool) !bool {
return if b {
bar(foo()!)
} else {
true
}
}
fn main() {
ret := is_ok(true) or { false }
println(ret)
assert ret
}
true
```
> cgen: fix if expr with fn call result (fix #15700)

- vlib/v/checker/if.v
- vlib/v/gen/c/if.v
- vlib/v/tests/if_expr_with_result_test.v
This PR fix if expr with result (fix #15708).
- Fix if expr with result.
- Add test.
```v
fn foo(i int) ?bool {
return if i == 0 { true } else { none }
}
fn bar(i int) !bool {
return if i == 0 { true } else { error('') }
}
fn main() {
r1 := foo(0) or { false }
println(r1)
assert r1
r2 := bar(0) or { false }
println(r2)
assert r2
}
true
true
```
> checker, cgen: fix if expr with result (fix #15708)

- vlib/v/ast/str.v
- vlib/v/fmt/struct.v
- vlib/v/fmt/tests/anon_struct_as_param_expected.vv
- vlib/v/fmt/tests/anon_struct_as_param_input.vv
input:
```v
fn func(arg struct{foo string='bar'}) {
println(arg.foo)
}
fn main() {
func(struct {foo: 'foo'
})
}
```
output:
```v
fn func(arg struct { foo string = 'bar' }) {
println(arg.foo)
}
fn main() {
func(struct {
foo: 'foo'
})
}
```
> fmt: fix replaces anonymous struct in paramter with invalid type name (fix #15696)

- vlib/v/gen/native/elf.v
This small PR contains a struct representation of an ELF file header used for codegen. This will be useful when we have multiple ways of generating elf files (e.g. with/without linking)
> native: add struct representing elf headers

- vlib/v/gen/c/struct.v
- vlib/v/tests/anon_struct_type_test.v
1. fix #15698
2. add test.
```v
fn func(arg struct { foo string }) {
println(arg.foo)
}
fn main() {
func(struct { 
foo: 'foo' 
})
}
```
output:
```
foo
```
> cgen: fix missing type name when anonymous struct is used as parameter.

- vlib/v/checker/fn.v
- vlib/v/checker/tests/inner_functions_call_before_define.out
- vlib/v/checker/tests/inner_functions_call_before_define.vv
1. Fix #15673 
2. Add test.
```v
fn main() {
_ := f()
go f()
f := fn () string { return "hello" }
_ := f() // avoid warnings
}
```
output:
```
vlib/v/checker/tests/inner_functions_call_before_define.vv:2:7: error: unknown function: f
2 |     _ := f()
|          ~~~
3 |     go f()
4 |
vlib/v/checker/tests/inner_functions_call_before_define.vv:3:5: error: unknown function: f
2 |     _ := f()
3 |     go f()
|        ~~~
4 | 
5 |     f := fn () string { return "hello" }
```
> checker: fix inner functions are called before definition. (fix #15673)

- vlib/v/checker/checker.v
- vlib/v/checker/tests/cast_string_to_ptr_err.out
- vlib/v/checker/tests/cast_string_to_ptr_err.vv
1. Fix #14921
2. Add test.
```v
fn main() {
_ := &char('foo')
}
```
output:
```
vlib/v/checker/tests/cast_string_to_ptr_err.vv:2:7: error: cannot cast string to `&char`, use `'foo'.str` instead.
2 |     _ := &char('foo')
|          ~~~~~~~~~~~~
3 | }
```
> checker: fix check omission in cast string to ptr. (fix #14921)

- vlib/v/checker/checker.v
- vlib/v/checker/tests/sumtype_define_recursively.out
- vlib/v/checker/tests/sumtype_define_recursively.vv
1. Fix #15684 
2. Add test.
```v
type Expr = fn ([]Expr) Expr | int
fn f(exprs []Expr) Expr {
return 0
}
fn main() {
mut m := map[string]Expr{}
m['f'] = f
}
```
output:
```
vlib/v/checker/tests/sumtype_define_recursively.vv:1:13: error: sum type `Expr` cannot be defined recursively
1 | type Expr = fn ([]Expr) Expr | int
|             ~~~~~~~~~~~~~~~~
2 | 
3 | fn f(exprs []Expr) Expr {
```
> checker: fix recursive define check is missing when defining sumtype. (fix #15684)

- vlib/v/ast/table.v
- vlib/v/tests/inout/dump_sumtype_of_fntype.out
- vlib/v/tests/inout/dump_sumtype_of_fntype.vv
This PR fix dumping sumtype of fntype (fix #15729).
- Fix dumping sumtype of fntype.
- Add test.
```v
import v.ast
type MyFnSumtype = fn () | fn (int) ast.Expr
fn f(z int) ast.Expr {
return ast.empty_expr
}
fn main() {
dump(MyFnSumtype(f))
}
[.\\tt1.v:10] main.MyFnSumtype(main.f): MyFnSumtype(fn (int) v.ast.Expr)
```
> ast: fix dumping sumtype of fntype (fix #15729)

- vlib/toml/parser/parser.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/struct_field_map_address_err.out
- vlib/v/checker/tests/struct_field_map_address_err.vv
This PR check taking the address of map field outside unsafe block  (fix #15705).
- Check taking the address of map field outside unsafe block.
- Add test.
```v
import os
struct StructWithMap {
mut:
name string
m    map[string]StructWithMap
}
fn abc() (&StructWithMap, &map[string]StructWithMap) {
mut s := &StructWithMap{}
s.m['abc'] = StructWithMap{'abc', {}}
pointer_to_map_value := &s.m['abc'].m['xyz'].m
dump(ptr_str(pointer_to_map_value))
return s, pointer_to_map_value
}
fn main() {
mut s, p := abc()
n := os.args[1] or { '2' }.int()
dump(n)
for i in 0 .. n {
s.m['$i'] = StructWithMap{}
}
dump(s.m['abc'])
dump(p)
eprintln('-----------------------------------------------------')
}
./tt1.v:12:26: error: cannot take the address of map values outside `unsafe`
10 | …
```
> checker: check taking the address of map field outside unsafe block  (fix #15705)

- vlib/v/checker/if.v
- vlib/v/gen/c/if.v
- vlib/v/tests/if_expr_nested_with_optional_result_test.v
This PR fix nested `if expr` with optional or result (fix #15735).
- Fix nested `if expr` with optional or result.
- Add test.
```v
// optional
pub fn foo1() bool {
return false
}
pub fn bar1(i int) ?int {
if i < 0 {
return none
}
return if i == 0 {
if foo1() {
1
} else {
2
}
} else {
3
}
}
// result
pub fn foo2() bool {
return false
}
pub fn bar2(i int) !int {
if i < 0 {
return error('')
}
return if i == 0 {
if foo2() {
1
} else {
2
}
} else {
3
}
}
fn main() {
ret11 := bar1(0) or { 0 }
println(ret11)
assert ret11 == 2
ret12 := bar1(1) or { 0 }
println(ret12)
assert ret12 == 3
ret21 := bar2(0) or { 0 }
println(ret21)
assert ret21 == 2
ret22 := bar2(1) or { 0 }
println(ret22)
assert ret22 == 3
}
2
3
2
3
```
> checker, cgen: fix nested if expr with optional or result (fix #15735)

- vlib/v/gen/c/fn.v
- vlib/v/tests/sumtype_with_struct_fn_field_call_test.v
1. Fix: #15730
2. Add test.
```v
type Expr = Fun | int
struct Fun {
f fn (int) int
}
fn test_sumtype_with_struct_fn_field_call() {
f := Expr(0)
if f is Fun {
println((f as Fun).f(0))
}
assert true
}
```
output:
pass
> cgen: fix generate call fn error when the struct type of sumtype has the fn field and is same to the struct name. (fix #15730)

- vlib/v/checker/checker.v
- vlib/v/checker/tests/cast_array_to_number_err.out
- vlib/v/checker/tests/cast_array_to_number_err.vv
This PR check casting array to number (fix #11480, fix #12591).
- Check casting array to number.
- Add test.
```v
import encoding.hex as hx
fn main() {
bytes := '010000150107120508d37445a0d7e5c5071980710c64310d9e12043000777369ff0424ab78b91a05164b00e50034003300'
yr := i16(hx.decode(bytes.substr(6,8))?)
println(bytes)
println('yr: $yr')
}
./tt1.v:5:8: error: cannot cast array `[]u8` to `i16`
4 |     bytes := '010000150107120508d37445a0d7e5c5071980710c64310d9e12043000777369ff0424ab78b91a05164b00e50034003300'
5 |     yr := i16(hx.decode(bytes.substr(6,8))?)
|           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6 |     println(bytes)
7 |     println('yr: $yr')
```
```v
type IP = []byte
fn main() {
mut ip := IP([]byte{cap:4})
ip << 0
ip << 0
ip << 0
ip << 1 …
```
> checker: check casting array to number (fix #11480)

- vlib/v/gen/c/infix.v
- vlib/v/tests/in_expression_test.v
This PR fix error of `in array of sumtype` (fix #12239).
- Fix error of `in array of sumtype`.
- Add test.
```v
type StringOrNumber = int | string
fn main() {
arr := [StringOrNumber(1), 2, 'test']
println(1 in arr)
assert 1 in arr
}
true
```
> cgen: fix error of `in array of sumtype` (fix #12239)

- vlib/v/checker/tests/fn_call_arg_mismatch_err_d.out
- vlib/v/checker/tests/fn_call_arg_mismatch_err_d.vv
This PR add test for fn call arg of fn pointer mismatch (fix #9966).
- #9966 is fixed.
- Add test.
```v
type Flag = bool | f64 | int | string
fn parse_percent(value string) f64 {
f_val := value.f64()
if f_val >= 0 && f_val <= 100 {
return f_val
} else {
return 0
}
}
fn parse_option(str string, validator fn (string) ?Flag) ?Flag {
return validator(str)
}
fn main() {
t := parse_option('45', parse_percent)?
println(t)
}
./tt1.v:17:26: error: cannot use `fn (string) f64` as `fn (string) ?Flag` in argument 2 to `parse_option`
15 |
16 | fn main() {
17 |     t := parse_option('45', parse_percent)?
|                             ~~~~~~~~~~~~~
18 |     println(t)
19 | }
```
> add test for fn call arg of fn pointer mismatch (fix #9966)

- vlib/v/checker/struct.v
- vlib/v/tests/struct_init_update_with_mutable_receiver_test.v
This PR fix struct init with update of mutable receiver (fix #7033).
- Fix struct init with update of mutable receiver.
- Add test.
```v
module main
name string
age  int
}
fn (mut p Person) change(name string) {
p = Person{
...p
name: name
}
}
fn main() {
mut p := Person{'bob', 22}
p.change('tom')
println(p)
assert p.name == 'tom'
assert p.age == 22
}
Person{
name: 'tom'
age: 22
}
```
> checker: fix struct init with update of mutable receiver (fix #7033)

- vlib/v/gen/c/auto_str_methods.v
- vlib/v/tests/inout/dump_expression.out
- vlib/v/tests/inout/dump_expression.vv
Fixes https://github.com/vlang/v/issues/15740
> cgen: fix printing and dumping of struct having referenced interface as field

- vlib/builtin/array.v
- vlib/builtin/array_d_gcboehm_opt.v
- vlib/builtin/builtin_d_use_libbacktrace.c.v
- vlib/builtin/builtin_nix.c.v
- vlib/builtin/sorted_map.v
- vlib/darwin/darwin.v
- vlib/gg/gg.c.v
- vlib/gx/image.v
- vlib/sync/pool/pool.v
- vlib/v/ast/scope.v
- vlib/v/builder/msvc_windows.v
- vlib/v/checker/check_types.v
- vlib/v/checker/checker.v
- vlib/v/checker/comptime.v
- vlib/v/checker/containers.v
- vlib/v/checker/fn.v
- vlib/v/checker/return.v
- vlib/v/checker/str.v
- vlib/v/checker/struct.v
- vlib/v/embed_file/embed_file.v
- vlib/v/fmt/fmt.v
- vlib/v/gen/c/cgen.v
- vlib/v/util/util.v
This PR makes `v self` ~2% faster (that is with tcc on Ubuntu 20.04, i3, without -prod. With -prod the speedup is <~1%).
> builtin, compiler: replace isnil(x) calls with `x == unsafe { nil }` (a little faster without -prod)

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/passing_sumtype_parameter_in_sumtype_matching_results_test.v
This PR fix passing sumtype parameter in sumtype matching results (fix #15078).
- Fix passing sumtype parameter in sumtype matching results.
- Add test.
```v
struct Foo {}
type Bar = Foo | int
type Baz = Foo | f32
fn foo(a Bar) int {
return 22
}
fn bar() Baz {
return Foo{}
}
fn main() {
a := bar()
mut ret := 0
match a {
Foo {
ret = foo(Bar(a))
}
f32 {}
}
println(ret)
}
22
```
> cgen: fix passing sumtype parameter in sumtype matching results (fix #15078)

- vlib/v/gen/c/comptime.v
Fix the hardcoded app param name, o/w using any other name leads to builder error, e.g.
```
/tmp/v_1000/vweb_crash.10723254446889791592.tmp.c:30259: error: 'app' undeclared
```
Change `app` to anything, e.g. `server` in /examples/vweb/vweb_example.v
```diff
- pub fn (mut app App) index() vweb.Result 
+ pub fn (mut server App) index() vweb.Result  
```
> fix hardcoded param name vweb html

- vlib/v/checker/struct.v
- vlib/v/checker/tests/reference_field_must_be_initialized.out
- vlib/v/checker/tests/struct_ref_fields_uninitialized_err.out
- vlib/v/checker/tests/struct_ref_fields_uninitialized_err.vv
1. Fix #15768
2. Add test.
```v
struct ContainsRef {
a &int = unsafe { nil }
b &int
}
struct Outer {
c ContainsRef
}
struct Ref {}
struct EmbedStruct {
ref1 &Ref = unsafe { nil }
ref2 &Ref
}
EmbedStruct
}
fn main() {
_ := Outer{}
_ := Struct{}
}
```
output:
```
vlib/v/checker/tests/struct_ref_fields_uninitialized_err.vv:22:7: warning: reference field `Outer.c.b` must be initialized
20 | 
21 | fn main() {
22 |     _ := Outer{}
|          ~~~~~~~
23 |     _ := Struct{}
24 | }
vlib/v/checker/tests/struct_ref_fields_uninitialized_err.vv:23:7: warning: reference field `Struct.ref2` must be initialized
21 | fn main() {
22 |     _ := Outer{}
23 |     _ := Struct{}
24 | }
```
> checker: fix nested struct ref field init check for embedded structs (fix #15768)

- cmd/tools/vrepl.v
- vlib/v/tests/repl/array_method.repl
- vlib/v/tests/repl/error.repl
- vlib/v/tests/repl/error_exitasdfasdf.repl
- vlib/v/tests/repl/error_nosave.repl.skip
This PR fix array method call error in vrepl (fix #15769).
- Fix array method call error.
- Add test.
```v
PS D:\vlang\v> v
____    ____
\    /     |  V 0.3.1 7e69619 . Use  list  to see the accumulated program so far.
>>> mut arr := [1, 2, 3]
>>> arr
[1, 2, 3]
>>> arr.delete_last()
>>> arr
[1, 2]
>>> arr.clear()
>>> arr
[]
>>>
```
> vrepl: fix array method call errors (fix #15769)

- vlib/v/checker/fn.v
- vlib/v/checker/tests/result_type_call_err.out
- vlib/v/checker/tests/result_type_call_err.vv
This PR check result type method call (fix #15778).
- Check result type method call.
- Add test.
```v
struct Foo {}
fn (f Foo) foo() int {
return 1
}
fn new_foo() !Foo {
return Foo{}
}
fn main() {
new_foo().foo()
}
./tt1.v:12:2: error: result type cannot be called directly
10 |
11 | fn main() {
12 |     new_foo().foo()
|     ~~~~~~~~~
13 | }
```
> checker: check result type method call (fix #15778)

- cmd/tools/vrepl.v
- vlib/v/tests/repl/print_and_fn_call.repl
This PR fix output error of print and fn call.
- Fix output error of print and fn call.
- Add test.
```v
PS D:\vlang\v> v
____    ____
\    /     |  V 0.3.1 26443cf . Use  list  to see the accumulated program so far.
>>> println('hello')
hello
>>> fn abc(x int) { println(x) }
>>> abc(123)
123
>>> abc(456)
456
>>> println('hello')
hello
>>> 
```
> vrepl: fix output error of print and fn call

- cmd/tools/vrepl.v
- vlib/v/tests/repl/error_and_continue_print.repl
This PR fix output errors (fix #15801).
- Fix output errors in vrepl.
- Add test.
```v
PS D:\vlang\v> v
____    ____
\    /     |  V 0.3.1 d67aa8d . Use  list  to see the accumulated program so far.
>>> a = 3
error: undefined ident: `a` (use `:=` to declare a variable)
6 |
7 | a = 3
| ^
>>> b
error: undefined ident: `b`
6 |
7 | println(b)
|         ^
>>> [4, 5].filter(it < 5)
[4]
>>>
```
> vrepl: fix output errors (fix #15801)

- vlib/v/parser/if_match.v
- vlib/v/tests/match_expr_with_string_fn_test.v
This PR fix error for match expr with 'fn'  (fix #15803).
- Fix error for match expr with 'fn'.
- Add test.
```v
fn main() {
a := 'hello'
ret := match a {
'hello' { 1 }
'fn' { 2 }
else { 0 }
}
println(ret)
}
1
```
> parser: fix error for match expr with 'fn'  (fix #15803)

- doc/docs.md
I added a note saying that Clang is required to translate C to V, fixing this issue: https://github.com/vlang/v/issues/15783.
> docs: add note that clang is required

- vlib/v/gen/c/array.v
- vlib/v/tests/array_insert_as_mut_receiver_test.v
This PR fix array insert in fn as mut receiver (fix #15800).
- Fix array insert in fn as mut receiver.
- Add test.
```v
fn main() {
mut ns := []Node{cap: 2}
other(mut ns)
println(ns)
assert ns.len == 1
assert ns[0].id == 1
assert ns[0].a == 0
}
fn other(mut ns []Node) {
n1 := Node{
id: 1
}
ns.insert(0, n1)
}
pub struct Node {
pub:
id u32 [required]
a  int
}
[Node{
id: 1
a: 0
}]
```
> cgen: fix array insert in fn as mut receiver (fix #15800)

- vlib/v/checker/struct.v
- vlib/v/checker/tests/anon_structs_visibility.out
- vlib/v/checker/tests/anon_structs_visibility/amod/amod.v
- vlib/v/checker/tests/anon_structs_visibility/main.v
- vlib/v/fmt/struct.v
- vlib/v/parser/struct.v
1. Fix #15763
2. Add test
amod.v:
```v
module amod
pub struct Foo {
pub mut:
bar struct  {
pub mut:
baz int
}
}
```
main.v:
```v
import amod
fn main() {
foo := amod.Foo{
bar: struct {
baz: 1
}
}
assert foo.bar.baz == 1
}
```
output:
pass.
> checker, parser, fmt: Fix visibility of anon struct in different modules.(fix #15763)

- examples/js_dom_draw_bechmark_chart/chart/main.v
- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/checker/tests/optional_propagate_nested.out
- vlib/v/checker/tests/propagate_result_with_option.out
- vlib/v/checker/tests/wrong_propagate_ret_type.out
1. Optimized #15780
2. Add test.
```v
fn foo() !string{
return ''
}
fn bar() {
println(foo()!)
}
```
output:
```
vlib/v/checker/tests/fn_must_return_optional_or_result_pos.vv:5:10: error: to propagate the call, `bar` must return an result type
3 | }
4 | 
5 | fn bar() {
|          ^
6 |     println(foo()!)
7 | }
```
> checker: optimized the position indicated by pos when the function needs to return an optional or result(fix #15780)

- examples/2048/2048.v
- vlib/os/os.c.v
- vlib/os/os_nix.c.v
- vlib/os/process_nix.c.v
- vlib/sokol/c/declaration.c.v
- vlib/v/ast/types.v
- vlib/v/checker/checker.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/comptime.v
- vlib/v/pref/default.v
- vlib/v/pref/os.v
- vlib/v/pref/pref.v
This `./v -os wasm32_emscripten examples/2048/` will generate 2 files:
`examples/2048/2048`      <-- a .js loader
`examples/2048/2048.wasm` <-- a .wasm file with the game (with an embedded font)
The `emcc` cross compiler, can be changed by setting the `VCROSS_COMPILER_NAME` env variable.
This makes generating apps like https://v2048.vercel.app/ hopefully easier.
TODO:
> pref,os,sokol,cgen: ease compilation of 2048 with `-os wasm32_emscripten`

- thirdparty/sokol/sokol_app.h
- vlib/sokol/sapp/enums.v
- vlib/sokol/sapp/sapp_structs.c.v
See https://github.com/floooh/sokol/pull/717 for the associated sokol PR; it hasn't been merged yet, but I've tested my changes and they work, so we can either merge this before it gets into upstream sokol or wait until then.
https://developer.android.com/ndk/reference/group/input#amotionevent_gettooltype
> sapp/gg: add a `tool_type` field to `gg.TouchPoint` (differenciate different types of touch input)

- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/c/testdata/ref_sumtype_as_struct_field.out
- vlib/v/gen/c/testdata/ref_sumtype_as_struct_field.vv
1. Fix #15827 
2. Add test
```v
struct S1 {}
struct S2 {}
type T1 = S1 | S2
struct SumTypePtr {
ptr &T1 = unsafe { nil }
}
fn main() {
ptr := SumTypePtr{}
dump(ptr)
}
```
output:
```
[vlib/v/gen/c/testdata/ref_sumtype_as_struct_field.vv:13] ptr: SumTypePtr{
ptr: &nil
}
```
> cgen: fix using reference of sumtype or map as struct field (fix: #15827)

- vlib/v/builder/cc.v
This was introduced when we enabled the GC by default,as a suggestion for resolving C errors caused by the user having an outdated TCC clone. However, now that several months have passed, it is very unlikely that people still have out-of-date copies of TCC, and instead it is more likely that this error message is hiding the true cause of some C errors unrelated to TCC or the GC.
> builder: remove outdated tcc error

- cmd/tools/vtest-all.v
- doc/docs.md
- vlib/v/builder/compile.v
- vlib/v/pref/default.v
- vlib/v/pref/pref.v
This allows users to use shebangs and be more free by not being forced to have the vsh file extension(see the changes to docs.md for details)
> Compiler: add -raw-vsh-tmp-prefix compiler flag

- vlib/datatypes/ringbuffer.v
- vlib/datatypes/ringbuffer_test.v
**Rewritten ringbuffer-feature moved to vlib/datatypes. Implementing head and tail pointers, as well as fixed sized array**
Example:
```
module main
fn main() {
// create a new ringbuffer with size 4
// the generic argument sets the type
mut r := datatypes.new_ringbuffer<int>(4)
// push elements
r.push(3)
r.push(4)
// get the oldest element. It will be removed from the buffer when calling `pop()`
oldest_value := r.pop()
println(oldest_value) // Output: 3
}
```
> datatypes: adding ringbuffer

- cmd/tools/modules/testing/common.v
- cmd/tools/vtest-self.v
- vlib/net/websocket/websocket_client.v
- vlib/net/websocket/websocket_server.v
- vlib/v/tests/websocket_logger_interface_should_compile_test.v
Removed a use of `unsafe { nil }` from the net.websocket module due to it causing edge case errors where the V compiler generated C code that tried to use a non-existent function that converted an integer to the log.Logger interface.
The value I replaced this with (in both cases as it was effectively the same code) was `&log.Logger(&log.Log{level: .info})` since that is the default value supplied by the ServerOpt and ClientOpt structs when the initiate the struct of which was edited.
Here's the ServerOpt struct for proof:
`[params]
pub struct ServerOpt {
logger &log.Logger = &log.Logger(&log.Log{
level: .info
})
}`
> net.websocket: swap unsafe use of nil for a safe default value

- vlib/v/scanner/scanner.v
- vlib/v/scanner/scanner_test.v
This PR fixes a bug in escape handling in scanner.
Presently `s.decode_u_escapes` may change `string_so_far` and thus invalidates positions stored in  `h_escapes_pos`. For example, for the string '\u2605\x61'
```
>>> '\u2605\x61'
V panic: substr(8, 10) out of bounds (len=7)
v hash: 69c9d47
/tmp/v_1000/v.7489314593549803884.tmp.c:19538: at _v_panic: Backtrace
/tmp/v_1000/v.7489314593549803884.tmp.c:22773: by string_substr
/tmp/v_1000/v.7489314593549803884.tmp.c:19872: by v__scanner__decode_h_escapes
/tmp/v_1000/v.7489314593549803884.tmp.c:19848: by v__scanner__Scanner_ident_string
/tmp/v_1000/v.7489314593549803884.tmp.c:19345: by v__scanner__Scanner_text_scan
```
Instead
```
>>> '\u2605\x61'
★a
```
This fix merges and sorts all escape pos and go through them in one pass avoid changing …
> v/scanner: fix string escape handling 

- vlib/v/gen/c/fn.v
- vlib/v/tests/embed_method_call_test.v
This PR fix reference embed method call (fix #15831).
- Fix reference embed method call.
- Add test.
```v
struct Access {}
fn (access &Access) acc() bool {
return true
}
struct Field {
Access
}
fn main() {
mut fields := []&Field{}
fields << &Field{}
mut rets := []bool{}
for mut field in fields {
println(field.acc())
rets << field.acc()
}
assert rets.len == 1
assert rets[0]
}
true
```
> cgen: fix reference embed method call (fix #15831)

- vlib/sync/sync_darwin.c.v
- vlib/v/tests/str_gen_test.v
1. Fix #15491 
2. Add test.
```v
import sync
struct Foo {
mutex &sync.Mutex
}
fn main() {
foo := Foo{
mutex: sync.new_mutex()
}
println(foo)
}
```
output:
```
Foo{
mutex: &sync.Mutex{
mutex: pthread_mutex_t{}
}
}
```
> sync: fix C.pthread_mutex_t struct typedef is missing in darwin (fix: #15491)

- vlib/encoding/utf8/utf8_tables.v
- vlib/encoding/utf8/utf8_util.v
- vlib/encoding/utf8/utf8_util_test.v
- Add `is_space` function
- Add test
```v
fn test_is_space() {
for ra in `a` .. `z` {
assert utf8.is_space(ra) == false
}
for ra in `A` .. `Z` {
assert utf8.is_space(ra) == false
}
assert utf8.is_space(`\u202f`) == true
assert utf8.is_space(`\u2009`) == true
assert utf8.is_space(`\u00A0`) == true
}
```
> encoding.utf8: Add is_space

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/const_can_use_optionals_results_test.v
This PR fix const expr using optional or result.
- Fix const expr using optional or result.
- Add test.
```v
const (
aaa = iopt()?
bbb = sopt()!
)
fn iopt() ?int {
return 1234
}
fn sopt() !string {
return 'xyz'
}
fn main() {
z1 := aaa
println(z1)
assert z1 == 1234
z2 := bbb
println(z2)
assert z2 == 'xyz'
}
1234
xyz
```
> cgen: fix const expr using optional or result

- vlib/v/parser/comptime.v
- vlib/v/tests/comptime_at_test.v
1. Fix: #15672 
2. Add test.
```v
fn main() {
line1, line2, line3 := @LINE, @LINE, @LINE
dump(line1)
dump(line2)
dump(line3)
}
```
output:
```
[vlib/v/parser/tests/comptime_at_last_token_line_number.vv:3] line1: 2
[vlib/v/parser/tests/comptime_at_last_token_line_number.vv:4] line2: 2
[vlib/v/parser/tests/comptime_at_last_token_line_number.vv:5] line3: 2
```
> parser: fix line number error of comptime atExpr in the last token of the line (fix: #15672)

- vlib/os/file.c.v
- vlib/os/file_test.v
This PR fix file.read() (fix #15513).
- Change file.read(), return `IError(Eof{})` when end of file. It always return `NotExpected` before.
- Change test.
```v
import os
fn slurp(path string) !string {
mut result := []u8{}
mut buffer := []u8{len: 4096}
mut f := os.open(path) or { return err }
defer {
f.close()
}
for {
len := f.read(mut buffer) or {
if err == IError(os.Eof{}) {
break
}
return err
}
result << buffer[0..len]
}
return result.bytestr()
}
fn main() {
println(slurp(@FILE)!)
}
import os
fn slurp(path string) !string {
mut result := []u8{}
mut buffer := []u8{len: 4096}
mut f := os.open(path) or { return err }
defer {
f.close()
}
for {
len := f.read(mut buffer) or {
if err == IError(os.Eof{}) {
break
}
return err
}
result << buffer[0..len]
}
return …
```
> os: fix file.read() (fix #15513)

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/builtins.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/native/tests/print.vv
- vlib/v/gen/native/tests/print.vv.out
This PR adds support for printing `bool` and `string` -typed identifiers for the native backend.
> native: add printing support for boolean and string variables

- vlib/v/gen/c/infix.v
- vlib/v/tests/array_test.v
1. Fix #15855 
2. Add test.
```v
fn main() {
mut arr1 := [][]string{}
mut arr2 := [][]string{}
mut arr3 := []string{}
arr4 := []string{}
arr1 << arr2
arr1 << arr3
arr3 << arr4
append_2d_2d(mut arr1, arr2)
append_2d_1d(mut arr1, arr3)
append_1d_1d(mut arr3, arr4)
assert true
}
fn append_2d_2d(mut arr1 [][]string, arr2 [][]string) {
arr1 << arr2
}
fn append_2d_1d(mut arr1 [][]string, arr2 []string) {
arr1 << arr2
}
fn append_1d_1d(mut arr1 []string, arr2 []string) {
arr1 << arr2
}
```
output:
```
nothing, passed
```
> cgen: fix array appending when array is used as fn parameter (fix: #15855)

- examples/gg/arcs_and_slices.v
- vlib/gg/draw.c.v
Numerous improvements/fixes/optimisations to `libv/gg/draw.c.v`...
* `draw_slice_*()` and `draw_arc_*()` functions did not respect `Context.scale` -- fixed
* `draw_slice_*()` functions `end_angle` argument was an arc length (in radians) and not an end angle -- changed to be an end_angle, consistent with other functions
* optimisation: `draw_arc_empty()` and `draw_arc_filled()` repeatedly called `sin()` and `cos()` for every segment of the arc being drawn, and also twice (redundantly) for each point -- rewritten (in the same vein as `draw_slice_*` functions) to use `tan()` and a) only perform multiplication in the segment-drawing loop, and b) draw a triangle strip (rather than quads)
* optimisation: in `draw_convex_poly()` triangle strip drawing loop, points were re-issued in successive …
> gg: arc/slice drawing improvements/optimisations/fixes

- cmd/tools/vcheck-md.v
- cmd/v/help/check-md.txt
- doc/docs.md
- Documents the `[noinit]` attribute for structs.
- Closes https://github.com/vlang/v/issues/15655
> docs.md: document [noinit] attribute with example

- vlib/builtin/cfns.c.v
- vlib/os/os.c.v
- vlib/os/os_test.v
- vlib/strings/builder.c.v
os.read_text and os.read_bytes rely on file size returned by ftell. Virtual filesystems such as /proc on Linux return zero size. It prevents both functions to read anything from those files. I've added extra case that when size is zero it attempts to read 4096 bytes instead. Now both functions are able to read /proc entries.
I didn't add test as I'm not sure if e.g. /proc/mounts is available in your CI environment. Should I assume it is?
> os: fixes issue #15852

- vlib/v/parser/assign.v
- vlib/v/parser/tests/if_guard_undefined_variable_err.out
- vlib/v/parser/tests/if_guard_undefined_variable_err.vv
This PR check undefined variable in if guard (fix #15880).
- Check undefined variable in if guard.
- Add test.
```v
module main
fn main() {
if f := f.g.x() {
}
}
./tt1.v:4:10: error: undefined variable: `f`
2 |
4 |     if f := f.g.x() {
|             ^
5 |     }
6 | }
```
> parser: check undefined variable in if guard (fix #15880)

- vlib/v/gen/c/dumpexpr.v
- vlib/v/tests/dump_c_structs/dump_c_struct_test.v
- vlib/v/tests/dump_c_structs/epoll.h
This PR fix dumping c structs (fix #15878).
- Fix dumping c structs.
- Add test.
epoll.h
```v
typedef union epoll_data {
void *ptr;
int fd;
uint32_t u32;
uint64_t u64;
} epoll_data_t;
struct epoll_event {
uint32_t events; /* Epoll events */
epoll_data_t data; /* User data variable */
};
```
```v
#include "@VMODROOT/epoll.h"
pub struct C.epoll_event {
mut:
events u32
data   C.epoll_data_t
}
[typedef]
pub union C.epoll_data_t {
mut:
ptr voidptr
fd  int
u32 u32
u64 u64
}
struct Epoll{
ev C.epoll_event
}
fn main(){
ev := C.epoll_event{}
unsafe{ C.memset(&ev, 0, sizeof(ev))}
dump(ev)
println(ev)
e := Epoll{
ev: C.epoll_event{}
}
dump(e)
println(e)
}
[.\\tt1.v:25] ev: struct epoll_event{
events: 0
data: epoll_data_t{
ptr: 0
fd: 0
u32: 0
u64: 0
}
}
struct epoll_event{ …
```
> cgen: fix dumping c structs (fix #15878)

- vlib/v/checker/interface.v
- vlib/v/tests/generics_interface_with_generic_sumtype_test.v
This PR fix generics interface with generic sumtype (fix #15883).
- Fix generics interface with generic sumtype.
- Add test.
```v
// optional.v
struct NonValue {}
pub type Optional<T> = NonValue | T
pub fn (self Optional<T>) is_some<T>() bool {
return self is T
}
pub fn (self Optional<T>) is_none<T>() bool {
return !self.is_some()
}
pub fn (self Optional<T>) expect<T>(msg string) T {
if self.is_some() {
return self as T
} else {
panic(msg)
}
}
pub fn (self Optional<T>) unwrap<T>() T {
return self.expect('unwrap on a none value')
}
pub fn (self Optional<T>) unwrap_or<T>(default T) T {
if self.is_some() {
return self as T
} else {
return default
}
}
pub fn (self Optional<T>) unwrap_or_else<T>(else_fn fn () T) T {
if self.is_some() {
return self as T
} else {
return else_fn()
}
}
pub fn …
```
> checker: fix generics interface with generic sumtype (fix #15883)

- vlib/v/gen/c/fn.v
This PR makes a minor cleanup in method_call().
- Change `unsafe { g.cur_fn != 0 }` to `g.cur_fn != unsafe { nil }`.
> cgen: minor cleanup in method_call()

- vlib/gg/draw.c.v
When drawing a circle, `Context.scale` affects the radius. However, `Context.scale` isn't taken in to account when automatically deciding how many segments to use. When `scale = 2.0`, the result is circles with visible sides.
> gg: radius_to_segments() should use Context.scale

- vlib/v/fmt/tests/fn_with_variadic_arg_expected.vv
- vlib/v/fmt/tests/fn_with_variadic_arg_input.vv
- vlib/v/parser/fn.v
This PR fix formating fn with variadic argument  (fix #15889).
- Fix formating fn with variadic argument.
- Add test.
```v
fn abc(a ...int, ) {}
fn main() {}
```
fmt to:
```v
fn abc(a ...int) {}
fn main() {}
```
> parser: fix formating fn with variadic argument  (fix #15889)

- vlib/net/urllib/values.v
To allow the Values struct to be defined in function arguments.
Specifically, the goal is to have the following code work:
```v
fn new_request(method http.Method, endpoint string, query urllib.Values) ?http.Request {}
```
Currently it is private, so the following compile error occurs:
```shell
error: struct `net.urllib.Values` was declared as private to module `net.urllib`, so it can not be used inside module `zztkm.microcms`
```
If there are no problems, I would like to change to a public struct.
> net.urllib change Values struct to public

- vlib/v/parser/parse_type.v
- vlib/v/parser/tests/ref_array_pos_err.out
- vlib/v/parser/tests/ref_array_pos_err.vv
1. Fix #15907
2. Add test.
```v
struct Foo {
b &[]u8
n int
}
```
output:
```
vlib/v/parser/tests/ref_array_pos_err.vv:2:5: error: V arrays are already references behind the scenes,
there is no need to use a reference to an array (e.g. use `[]string` instead of `&[]string`).
If you need to modify an array in a function, use a mutable argument instead: `fn foo(mut s []string) {}`.
1 | struct Foo {
2 |     b &[]u8
|        ^
3 |     n int
4 | }
```
> parser: fix pos error when define reference array type (fix: #15907)

- vlib/v/fmt/comments.v
- vlib/v/fmt/tests/comments_inside_if_cond_expected.vv
- vlib/v/fmt/tests/comments_inside_if_cond_input.vv
1. Fix: #15914
2. Add test.
a.v:
```v
if true /* comments */ {
}
```
v fmt -w a.v
output:
```v
// comments
if true {
}
```
> fmt: fix error when comments inside if and condition. (fix #15914)

- vlib/gg/gg.c.v
- vlib/gg/gg_ui.c.v
- vlib/gg/text_rendering.c.v
Most of the function in `gg.Context` are to do with drawing stuff, or setting colours or text. And the functions to do with text are clearly labelled as such, since text rendering is only a part of what you can do with a `Context`.
Except for `set_cfg()`. It takes a `gx.TextCfg` argument, but is named as though it sets config for the `Context`, rather than just the text rendering.
So this is a proposal to rename `gg.Context.set_cfg()` to `gg.Context.set_text_cfg()`.
PR includes a deprecated `gg.Context.set_cfg()` shim for compatibility.
Note: I'm also submitting work to ui and will update calls there.
> gg: proposed rename of Context.set_cfg() -> Context.set_text_cfg()

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/comments_expected.vv
- vlib/v/fmt/tests/comments_input.vv
1. Fix #15918
2. Add test.
```v
for // comments
{
break
}
```
output:
```v
// comments
for {
break
}
```
> fmt: fix comments between for and { is wrong (fix #15918)

- vlib/v/ast/ast.v
- vlib/v/checker/assign.v
- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/checker/for.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/for.v
- vlib/v/tests/generic_fn_with_comptime_for_test.v
This PR fix generic fn with comptime for (fix #15905).
- Fix generic fn with comptime for.
- Add test.
```v
fn fn_a<T>(data T, depth int, nl bool) {
for _ in 0 .. depth {
print('\t')
}
$if T.typ is int {
print('int: $data')
} $else $if T.typ is string {
print('string: $data')
} $else $if T is $Array {
println('array: [')
for i, elem in data {
fn_a(elem, depth + 1, false)
if i < data.len - 1 {
print(', ')
}
println('')
}
print(']')
} $else $if T is $Map {
println('map: {')
for key, value in data {
print('\t(key) ')
fn_a(key, depth, false)
print(' -> (value) ')
fn_a(value, depth, true)
}
print('}')
} $else $if T is $Struct {
println('struct $T.name: {')
print('\t($field.name) ')
fn_a(data.$(field.name), depth, true)
// uncommenting either of these lines will cause a …
```
> ast, checker, cgen: fix generic fn with comptime for (fix #15905)

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/defer/defer_test.v
1. Fix #15891
2. Add test.
3. Fix cgen: indent for defer stmts.
```v
fn main() {
$if cond ? {
} $else {
defer {
_ := 1
}
}
}
```
cgen output:
```c
bool main__main_defer_0 = false;
#if defined(CUSTOM_DEFINE_cond)
{
}
#else
{
main__main_defer_0 = true;
}
#endif
// Defer begin
if (main__main_defer_0) {
#if defined(CUSTOM_DEFINE_cond)
#else
{int_literal _ = 1;}
;
#endif
}
// Defer end
}
```
> cgen: fix error when defer inside comptime if {} else {} (fix #15891)

- vlib/v/gen/native/elf.v
- vlib/v/gen/native/gen.v
Skip the linking step of the native backend in favor of smaller executable sizes when no library functions get called.
Also fixes linking errors on `aarch64-linux-gnu` targets.
> native: skip linking when no library functions get called

- vlib/v/checker/fn.v
- vlib/v/checker/tests/fn_array_decompose_arg_mismatch_err.out
- vlib/v/checker/tests/fn_array_decompose_arg_mismatch_err.vv
This PR check mismatch of the fn array decompose argument (fix #15926).
- Check mismatch of the fn array decompose argument.
- Add test.
```v
module main
type Any = string | u8
fn test(args ...Any) {
println('args $args')
}
fn main() {
mut args := []string{cap: 3}
args << ['test', 'test1', 'test2']
test(...args)
}
./tt1.v:12:7: error: cannot use `...string` as `...Any` in argument 1 to `test`
10 |     mut args := []string{cap: 3}
11 |     args << ['test', 'test1', 'test2']
12 |     test(...args)
|          ~~~~~~~
13 | }
```
> checker: check mismatch of the fn array decompose argument (fix #15926)

- vlib/v/checker/struct.v
- vlib/v/checker/tests/struct_ref_fields_uninitialized_err.out
- vlib/v/checker/tests/struct_ref_fields_uninitialized_err.vv
1. Fix #15935 
2. Add test.
```v
struct ContainsRef {
a &int = unsafe { nil }
b &int
}
type TypeForContainsRef = ContainsRef
struct Outer {
c1 ContainsRef
c2 TypeForContainsRef
}
struct Ref {}
struct EmbedStruct {
ref1 &Ref = unsafe { nil }
ref2 &Ref
}
EmbedStruct
}
fn main() {
_ := Outer{}
_ := Struct{}
}
```
output:
```
vlib/v/checker/tests/struct_ref_fields_uninitialized_err.vv:25:7: warning: reference field `Outer.c1.b` must be initialized
23 | 
24 | fn main() {
25 |     _ := Outer{}
|          ~~~~~~~
26 |     _ := Struct{}
27 | }
vlib/v/checker/tests/struct_ref_fields_uninitialized_err.vv:25:7: warning: reference field `Outer.c2.b` must be initialized
23 | 
24 | fn main() {
25 |     _ := Outer{}
|          ~~~~~~~
26 |     _ := Struct{}
27 | } …
```
> checker: fix feferences for alias type can still be uninitalized (fix #15935)

- vlib/v/parser/fn.v
- vlib/v/parser/struct.v
This PR fix checking for duplicate main functions (fix #15933).
```v
import mod
fn main() {}
./tt1.v:1:8: warning: module 'mod' is imported but never used
1 | import mod
|        ~~~
2 |
3 | fn main() {}
mod/mod.v:5:12: error: cannot register struct `mod.Foo`, another type with this name exists
3 | pub struct Foo{}
4 |
5 | pub struct Foo<T>{}
|            ~~~
```
multiple main files in the folder.
tt1.v 
```v
fn main() {}
```
tt2.v
```v
fn  main() {}
```
```v
./tt2.v:1:4: error: multiple `main` functions detected, and you ran `v .`
perhaps there are multiple V programs in this directory, and you need to
run them via `v file.v` instead
1 | fn main() {}
|    ~~~~
```
> parser: fix checking for duplicate main functions (fix #15933)

- vlib/v/checker/fn.v
- vlib/v/gen/native/tests/atexpr.vv
- vlib/v/gen/native/tests/atexpr.vv.out
Check arguments of native builtin functions. 
Fixes things like printing `AtExpr`s directly with the native backend:
```v
println(@LINE)
```
> checker, native: check arguments of native builtin functions

- vlib/arrays/arrays.v
- vlib/arrays/arrays_test.v
- vlib/maps/maps.v
- vlib/maps/maps_test.v
- Add more commonly used functions (inspired from [Kotlin's stdlib](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-list/))
- arrays
- - `flat_map`
- - `flat_map_indexed`
- - `filter_indexed`
- - `fold_indexed`
- - `reduce_indexed`
- - `map_indexed`
- maps
- - `flatten` -> `flat_map` (for consistency reason)
- add tests (see diff)
P.S: I'll make another PR for major code cleanup for both module after this one is done.
> arrays, maps: Add indexed variant of collection function and minor cleanup

- vlib/v/ast/ast.v
- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/comments_expected.vv
- vlib/v/fmt/tests/comments_input.vv
- vlib/v/parser/for.v
1. Fix #15922
2. Add tests.
a.v:
```v
for // comments
{
break
}
for /* comments */ {
break
}
for i := 0; i < 1; i++ // comments
{
break
}
for i := 0; i < 1; i++ /* comments */ {
break
}
for /* comments1 */ i := 0; /* comments2 */ i < 1; /* comments3 */ i++ /* comments4 */ {
break
}
for _ in [1, 2] /* comments */ {
break
}
for _ in [1, 2] // comments
{
break
}
for /* comments1 */ _ in /* comments2 */ [1, 2] /* comments3 */ {
break
}
```
v fmt -w a.v
output:
```v
// comments
for {
break
}
// comments
for {
break
}
// comments
for i := 0; i < 1; i++ {
break
}
// comments
for i := 0; i < 1; i++ {
break
}
// comments1
// comments2
// comments3
// comments4
for i := 0; i < 1; i++ {
break
}
// comments
for _ in [1, 2] {
break
}
// comments
for _ in [1, 2] {
break
}
// comments1
// comments2
// …
```
> fmt,parser,ast: fix and optimized comments for 'for, for_c, for_in' stmts (fix: #15922)

- vlib/net/net_windows.c.v
fixes https://github.com/vlang/v/issues/15959 and part of https://github.com/vlang/v/pull/15932
> net: add unsafe block to int -> enum cast

- vlib/arrays/arrays.v
- vlib/arrays/arrays_test.v
- vlib/maps/maps.v
- Unifies function signature format (parameter names only)
- - `a` / `arr` -> `array`
- Define anonymous function signature's parameter
- - `fn (R, T)` -> `fn (acc R, elem T)` - From `arrays.fold`
- - `fn (int, R, T)` -> `fn (idx int, acc R, elem T)` - From `arrays.fold_indexed`
- Changes return type `!` from `?` when function returns error instead of none
The following refactor only happens on public functions while the purpose of this PR is to enhance the functions definition for documentation
> arrays, maps: Refactor function signature and comment cleanup

- vlib/v/gen/c/comptime.v
- vlib/vweb/vweb_app_test.v
This PR fix vweb using generic method (fix #15888).
- Fix vweb using generic method.
```v
import vweb
struct ApiSuccessResponse<T> {
success bool
result  T
}
struct App {
vweb.Context
}
fn (mut app App) json_success<T>(result T) vweb.Result {
response := ApiSuccessResponse<T>{
success: true
result: result
}
return app.json(response)
}
fn main() {
mut app := &App{}
vweb.run(app, 80)
}
[Vweb] Running app on http://localhost:80/
```
> cgen: fix vweb using generic method (fix #15888)

- vlib/term/ui/input_windows.c.v
This PR fix errors of input_windows.c.v.
errors in windows:
```v
FAIL  [ 240/1120]   203.977 ms vlib/term/ui/1_term_and_ui_compilation_test.v
vlib/term/ui/input_windows.c.v:168:16: error: casting numbers to enums, should be done inside `unsafe{}` blocks
166 |                     C.VK_INSERT { KeyCode.insert }
167 |                     C.VK_DELETE { KeyCode.delete }
168 |                     65...90 { KeyCode(ch + 32) } // letters
|                               ~~~~~~~~~~~~~~~~
169 |                     91...93 { KeyCode.null } // special keys
170 |                     96...105 { KeyCode(ch - 48) } // numpad numbers
vlib/term/ui/input_windows.c.v:170:17: error: casting numbers to enums, should be done inside `unsafe{}` blocks
168 |                     65...90 { KeyCode(ch + 32) } // …
```
> term: fix errors of input_windows.c.v

- vlib/v/checker/fn.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/parser/fn.v
- vlib/v/tests/fn_variadic_test.v
fixes #15943
nr_muls are derived onto the parent type instead of just the elem type, this was happening when flags were copied using derive.
A few fixes were added to workaround the underlying issue, this PR fixes the underlying issue so have removed them:
- https://github.com/vlang/v/pull/11115
- https://github.com/vlang/v/blob/master/vlib/v/checker/fn.v#L239
I wonder if some of these extra checks could now be removed? https://github.com/vlang/v/blob/master/vlib/v/checker/fn.v#L1053
```go
fn fn_varg_a(strings ...&string) {
fn_a(strings)
}
fn fn_a(s []&string) {
println(s)
}
fn main() {
a := 'a'
b := 'b'
fn_varg_a(&a, &b)
}
```
expected no error, but got:
```sh
➜  v-algorand-sdk git:(master) ✗ v ../varg_ptr.v
../varg_ptr.v:4:7: error: cannot use `&[]&string` as `[]&string` in argument 1 …
```
> ast/parser: varg with pointer type fix: #15943

- vlib/v/builder/cc.v
This PR prevents the contents of `LDFLAGS` to reach object file compilation.
Compilers handle the arguments inconsistently which can lead to compile errors/warnings with some compilers (tcc, clang) - and success with others (gcc). This PR prevents such confusion.
> builder: exclude `LDFLAGS` in .o builds

- vlib/gg/image.c.v
- vlib/stbi/stbi.c.v
Now image load from `stbi` works with `gg`.
I'm using it in https://git.envs.net/iacore/adbctl
> fix: loading image from memory with stbi

- cmd/tools/vpm.v
This PR stop and output an error message after parsing the v.mod file failed. (fix #15986).
```v
PS D:\Vlang\v> v install https://github.com/duarteroso/vglfw
Installing module "duarteroso\vglfw" from "https://github.com/duarteroso/vglfw" to "C:\Users\yuyi9\.vmodules\duarteroso\vglfw" ...
Parsing v.mod file failed, vmod: invalid token "duarteroso", at line 5
```
> vpm: stop and output an error message after parsing the v.mod file failed. (fix #15986)

- vlib/v/checker/infix.v
- vlib/v/checker/tests/generic_infix_plus_err.out
- vlib/v/checker/tests/generic_infix_plus_err.vv
This PR check undefined operation of the generic infix expr  (fix #15967).
- Check undefined operation of the generic infix expr.
- Add test.
```v
fn sum<T>(a T, b T) T {
return a + b
}
fn main() {
sum({
'id': 1
}, {
'id': 1
})
}
./tt1.v:2:9: error: undefined operation `map[string]int` + `map[string]int`
1 | fn sum<T>(a T, b T) T {
2 |     return a + b
|            ~~~~~
3 | }
4 |
```
> checker: check undefined operation of the generic infix expr  (fix #15967)

- vlib/dl/dl.v
- vlib/dl/dl_nix.c.v
- vlib/dl/rtld_next_test.v
- vlib/v/ast/comptime_const_values.v
- vlib/v/checker/comptime.v
- vlib/v/gen/c/cgen.v
With this PR, the following program compiles:
```v
module main
import dl
#flag -D_GNU_SOURCE
type RealOpen = fn(charptr, int, int) int
[export: open]
fn open(filename charptr, oflag int, mode int) int {
println('dl.rtld_next: ${ptr_str(dl.rtld_next)}')
real_open := RealOpen((dl.sym(dl.rtld_next, "open")))
println('> real_open: ${ptr_str(real_open)} | filename:
${unsafe{cstring_to_vstring(filename)}}')
return real_open(filename, oflag, mode)
}
```
... and produces:
```
dl.rtld_next: ffffffffffffffff
> real_open: 7ffff7e95ce0 | filename: /proc/stat
```
> cgen,checker: support simple voidptr casts in consts, without delaying the initialisation to _vinit

- vlib/v/parser/containers.v
- vlib/v/parser/expr.v
- vlib/v/parser/parser.v
- vlib/v/tests/map_init_with_multi_enum_keys_test.v
This PR fix map init with multi enum keys (fix #15965).
- Fix map init with multi enum keys.
- Add test.
```v
enum Foo {
a
b
}
fn main() {
mp := {
Foo.a: 'A' // Foo.a: 'A', Works if comma is there.
.b:    'B'
}
println(mp)
assert mp[.a] == 'A'
assert mp[.b] == 'B'
}
{a: 'A', b: 'B'}
```
> parser: fix map init with multi enum keys (fix #15965)

- vlib/v/checker/check_types.v
- vlib/v/checker/return.v
- vlib/v/checker/tests/fn_return_fn_type_mismatch_err.out
- vlib/v/checker/tests/fn_return_fn_type_mismatch_err.vv
This PR check fn returning fn type mismatch  (fix #15988).
- Check fn returning fn type mismatch.
- Add test.
```v
pub struct ExpectedType {
a u32
b u32
}
struct WrongType {
c string
d int
}
pub type Fn = fn (&ExpectedType, i64, u64) int
pub fn good_signature() Fn {
return fn (n &ExpectedType, a i64, b u64) int {
println('good signature param0=$n')
return 0
}
}
pub fn bad_signature() Fn {
// create closure that has nonmatching signature due to first arg. Compiler should reject it
return fn (n &WrongType, a i64, b u64) int {
println('bad signature param0=$n')
return 0
}
}
fn main() {
arg := &ExpectedType{
a: 3
b: 7
}
mut cb := good_signature()
cb(arg, 1, 1)
cb = bad_signature()
cb(arg, 1, 1)
}
./tt1.v:22:9: error: cannot use `fn (&WrongType, i64, u64) int` as type …
```
> checker: check fn returning fn type mismatch  (fix #15988)

- vlib/v/checker/str.v
- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/infix_expr_expected.vv
- vlib/v/fmt/tests/infix_expr_input.vv
1. Fix #15635
2. Add tests.
```v
if 
c.table.final_sym(typ).kind in [.array, .array_fixed, .struct_, .interface_, .none_, .map, .sum_type]
&& fmt in [`E`, `F`, `G`, `e`, `f`, `g`, `d`, `u`, `x`, `X`, `o`, `c`, `p`, `b`] {
c.error('illegal format specifier `${fmt:c}` for type `${c.table.get_type_name(ftyp)}`', node.fmt_poss[i])
}
```
v fmt -w:
output:
```v
if c.table.final_sym(typ).kind in [.array, .array_fixed, .struct_, .interface_, .none_, .map, .sum_type]
&& fmt in [`E`, `F`, `G`, `e`, `f`, `g`, `d`, `u`, `x`, `X`, `o`, `c`, `p`, `b`] {
c.error('illegal format specifier `${fmt:c}` for type `${c.table.get_type_name(ftyp)}`',
node.fmt_poss[i])
}
```
> fmt: fix unreasonable wrap when infix expression is too long (fix #15635)

- examples/viewer/view.v
***What's Inside***
Bug fix: adapted the code to use of the modified `stbi.load_from_memory_with_channels`
> Bug Fix: use stbi load_from_memory_with_channels in the viewer example

- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/js/auto_str_methods.v
- vlib/v/tests/str_gen_test.v
1. Fix #15970 
2. Add tests.
```v
struct Foo {
cp charptr = charptr(0)
}
fn main() {
println(charptr(0))
f := Foo{}
println(f)
}
```
output:
```
0x0
Foo{
cp: C""
}
```
> cgen: fix str() fails when the structure 'charptr' type field is nil (fix #15970)

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/maps_expected.vv
- vlib/v/tests/map_init_with_enum_keys_test.v
- vlib/v/tests/map_init_with_multi_enum_keys_test.v
- vlib/v/tests/vargs_with_enum_value_test.v
This PR remove comma inside map_init using multi_line.
```v
enum Foo {
a
b
}
type NestedAbc = map[string]string | string
enum NestedFoo {
a
b
c
}
fn test_map_init_with_multi_enum_keys() {
mp := {
Foo.a: 'A'
.b:    'B'
}
println(mp)
assert mp[.a] == 'A'
assert mp[.b] == 'B'
}
fn test_nested_map_init_with_multi_enum_keys() {
mp := {
NestedFoo.a: NestedAbc({
'A': 'AA'
})
.b:          'B'
.c:          {
'c': 'C'
}
}
println(mp)
assert mp[.a]? == NestedAbc({
'A': 'AA'
})
assert mp[.b]? == NestedAbc('B')
assert mp[.c]? == NestedAbc({
'c': 'C'
})
}
```
> fmt: remove comma inside map_init using multi_line

- vlib/builtin/array.v
- vlib/v/gen/native/amd64.v
- This PR deprecates `array.reduce` from module `builtin`
- Encourages users using `arrays.reduce` instead, which has more flexibility then original one
- The removal time is `2023-4-11`.
> builtin.array : Deprecate array.reduce

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/testdata/sumtype_struct_depend_order.vv
1. Fix #16003
2. Add tests.
```v
type OneOrTwo = One | Two
struct One {
sig u32
num u32
items [16]Three
}
struct Two {
sig u32
num u64
items [16]Three
}
struct Three {
}
pub fn (obj OneOrTwo) get_sig() u32 {
return obj.sig
}
```
output:
passed.
> cgen: fix dependency order error between sumtype and fixed array type (fix #16003)

- vlib/v/checker/fn.v
This PR notice generic route methods of vweb. (related #15888)
```v
import vweb
struct ApiSuccessResponse<T> {
success bool
result  T
}
struct App {
vweb.Context
}
fn (mut app App) json_success<T>(result T) vweb.Result {
response := ApiSuccessResponse<T>{
success: true
result: result
}
return app.json(response)
}
fn main() {
mut app := &App{}
vweb.run(app, 80)
}
./tt1.v:12:1: notice: generic method routes of vweb will be skipped
10 | }
11 |
12 | fn (mut app App) json_success<T>(result T) vweb.Result {
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
13 |     response := ApiSuccessResponse<T>{
14 |         success: true
[Vweb] Running app on http://localhost:80/
```
> checker: notice generic route methods of vweb

- vlib/net/mbedtls/ssl_connection.v
Without this fix connections don't get correctly closed (they hang in a CLOSE_WAIT state) for me on linux. 
Credits to @spytheman in helping my out and finding a fix here https://discord.com/channels/592103645835821068/592294828432424960/1029031286569967708
> net.mbedtls: add explicit closing of the tcp connection in the shutdown method

- vlib/v/checker/containers.v
- vlib/v/tests/fn_return_opt_or_res_of_array_test.v
This PR fix fn returning result of array (fix #15973).
- Fix fn returning result of array.
- Add test.
```v
fn foo_res() ![]string {
return []
}
fn foo_opt() ?[]string {
return []
}
fn main() {
foo_res() or { panic(err) }
foo_opt() or { panic(err) }
assert true
}
```
> checker: fix fn returning result of array (fix #15973)

- vlib/v/checker/match.v
- vlib/v/checker/tests/return_match_expr_type_mismatch.out
- vlib/v/checker/tests/return_match_expr_type_mismatch.vv
This PR check type mismatch of return match expr (fix #15989).
- Check type mismatch of return match expr.
- Add test.
```v
struct Poss1 {}
struct Poss2 {}
type Possibilities = Poss1 | Poss2
struct PossOwner {
pos Possibilities
}
struct SomeTuple {
p PossOwner
f Poss1
}
fn get_file(item PossOwner) ?SomeTuple {
return match item.pos {
Poss1 { item.pos }
else { error('not poss1') }
}
}
fn main() {
item := PossOwner{
pos: Poss1{}
}
r := get_file(item) or {
println('err=$err')
return
}
println('got $r')
}
./tt1.v:18:16: error: return type mismatch, it should be `SomeTuple`
16 | fn get_file(item PossOwner) ?SomeTuple {
17 |     return match item.pos {
18 |         Poss1 { item.pos }
|                      ~~~
19 |         else { error('not poss1') }
20 |     }
```
> checker: check type mismatch of return match expr (fix #15989)

- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/testdata/attr_string_quotes_escape.out
- vlib/v/gen/c/testdata/attr_string_quotes_escape.vv
- vlib/v/gen/c/utils.v
1. Fix #15194
2. Add tests.
```v
['option1: "1"']
["option2: '1'"]
['option3: \'1\'']
["option4: \"1\""]
fn (d Dummy) sample_method() {
}
fn main() {
$for method in Dummy.methods {
println(method)
}
}
```
output:
```
FunctionData{
name: 'sample_method'
attrs: ['option1: "1"', 'option2: '1'', 'option3: '1'', 'option4: "1"']
args: []
return_type: 1
typ: 0
}
```
> cgen: fix wrong when string attributes with quotes (fix #15194)

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/utils.v
- vlib/v/tests/generic_struct_init_with_generic_cast_test.v
This PR fix generic struct init with generic cast (fix #16011).
- Fix generic struct init with generic cast.
- Add test.
```v
pub struct Range<T> {
start T
end   T [required]
step  T = T(1)
mut:
now T
}
fn main() {
r1 := Range<int>{
end: 10
}
println(r1)
r2 := Range<f64>{
end: 2.2
}
println(r2)
assert true
}
Range<int>{
start: 0
end: 10
step: 1
now: 0
}
Range<f64>{
start: 0
end: 2.2
step: 1
now: 0
}
```
> cgen: fix generic struct init with generic cast

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/index.v
- vlib/v/tests/map_value_with_optional_result_test.v
1. Fix #15972
2. Add tests.
```v
import os
struct AdbDevice {
opts1 map[string]?string
opts2 map[string]!string
}
fn test_map_value_with_optional_result() {
// avoid warnings
_ := os.max_path_len
assert true
}
```
output:
passed.
> cgen: fix map with optional or result (fix #15972)

- vlib/builtin/cfns.c.v
The C function putchar is missing in "v\vlib\builtin\cfns.c.v". Adding this will help us enable it in c2v as supported built-in function. And it would help us translate programs like below.
```c
#include <stdio.h>
int main(void)
{
int c;
c = getchar();
while (c != EOF)
{
putchar(c);
c = getchar();
}
return 0;
}
```
> Adding C function putchar to supported builtins

- vlib/v/gen/c/index.v
- vlib/v/tests/map_value_with_optional_result_test.v
1. This pr is a supplement and fix to pr#16036
2. Add tests.
```v
import os
struct AdbDevice {
opts map[string]?string
}
fn test_map_value_with_optional_result() {
// avoid warnings
_ := os.max_path_len
assert true
}
fn foo(arg map[string]?string) ?string {
return arg['akey']
}
```
run passed.
I'm so sorry to miss a situation: when returning value of map[], still need to keep its optional. 😭
> cgen: fix map with optional or result on return

- vlib/v/gen/c/cgen.v
- vlib/v/tests/fn_with_opt_or_res_of_multi_return_test.v
This PR fix fn with optional of multi_return (fix #16038).
- Fix fn with optional of multi_return.
- Add test.
```v
struct Aa {
x string
}
struct Bb {
a int
}
fn give(succ Aa) ?(Aa, Bb) {
return match succ.x {
'x' {
succ, Bb{}
}
else {
error('nok')
}
}
}
fn main() {
res, _ := give(Aa{ x: 'x' }) or { panic('got unexpected err') }
assert res.x == 'x'
println('success')
}
success
```
> cgen: fix fn with optional of multi_return (fix #16038)

- vlib/v/checker/fn.v
- vlib/v/checker/tests/fn_call_with_extra_parenthesis.out
- vlib/v/checker/tests/fn_call_with_extra_parenthesis.vv
This PR check error for fn call with extra parenthesis (fix #16026).
- Check error for fn call with extra parenthesis.
- Add test.
```v
fn doit(i int) {
}
fn main() {
main.doit()(1)
}
./tt1.v:5:7: error: expected 1 arguments, but got 0
3 |
4 | fn main() {
5 |     main.doit()(1)
|          ~~~~~~
6 | }
```
> checker: check error for fn call with extra parenthesis (fix #16026)

- vlib/v/checker/checker.v
- vlib/v/checker/tests/optional_or_block_mismatch.out
- vlib/v/checker/tests/optional_or_block_mismatch.vv
1. Fix: #16050 
2. Add tests.
```v
module main
struct Bar {}
fn foo() ?&Bar {
return none
}
fn main() {
x := foo() or { Bar{} }
println(x)
foo() or { Bar{} }
}
```
output:
```
vlib/v/checker/tests/optional_or_block_mismatch.vv:10:18: error: wrong return type `Bar` in the `or {}` block, expected `&Bar`
8 | 
10 |     x := foo() or { Bar{} }
|                     ~~~~~
11 |     println(x)
12 |
vlib/v/checker/tests/optional_or_block_mismatch.vv:13:13: error: the default expression type in the `or` block should be `&Bar`, instead you gave a value of type `Bar`
11 |     println(x)
12 | 
13 |     foo() or { Bar{} }
|                ~~~~~
14 | }
```
> cgen: fix mismatch when the default expression or block has optional (fix #16050)

- vlib/v/ast/table.v
- vlib/v/fmt/tests/map_value_with_optional_result_expected.vv
- vlib/v/fmt/tests/map_value_with_optional_result_input.vv
- vlib/v/tests/map_value_with_optional_result_test.v
This PR fixes the missing optional and result in the type name and cname of the map.
For this reason, fmt and run fail:
```v
struct Foo {
map1 map[string]!string
map2 map[string]?string
}
fn foo() {
map1 := map[string]!string{}
map2 := map[string]!string{}
}
fn bar(arg map[string]?string) ?string {
return arg['akey']
}
```
fmt -w:
```v
struct Foo {
map1 map[string]!string
map2 map[string]!string
}
fn foo() {
map1 := map[string]!string{}
map2 := map[string]!string{}
}
fn bar(arg map[string]!string) ?string {
return arg['akey']
}
```
and run fail:
```
a.v:12:12: error: cannot use `!string` as type `?string` in return argument
10 | 
11 | fn bar(arg map[string]?string) ?string {
12 |     return arg['akey']
|               ~~~~~~~~
13 | }
```
> ast: fix missing 'optional' and 'result' in type name and cname of map

- vlib/v/gen/c/assign.v
- vlib/v/tests/assign_optional_of_multi_return_with_heap_test.v
This PR fix assigning optional of multi_return with heap (fix #16041).
- Fix assigning optional of multi_return with heap.
- Add test.
```v
struct Poss1 {}
struct Poss2 {}
type Possibilities = Poss1 | Poss2
// comment out this attribute to make error go away BUT now you need to remember to use &PossOwner everytime you create new instance :(
[heap]
pub struct PossOwner {
pub:
name    string
details Possibilities
}
fn (t PossOwner) get_file(path string) ?(PossOwner, Poss1) {
match t.details {
Poss1 { return t, t.details }
else { return error('not a file') }
}
}
fn (item PossOwner) check() ?int {
assert item.name == 'x'
return 0
}
fn somefun() ?int {
t := PossOwner{
name: 'x'
details: Poss1{}
}
path_info, _ := t.get_file('') or {
println('NOTOK1')
return 1
}
_ := path_info.check() or { …
```
> cgen: fix assigning optional of multi_return with heap (fix #16041)

- vlib/v/gen/c/fn.v
- vlib/v/tests/generics_closure_fn_direct_call_test.v
This PR fix generic closure fn direct call (fix #16012).
- Fix generic closure fn direct call.
- Add test.
```v
pub struct App {
}
pub fn (mut app App) register<T>(service T) {
fn [service] <T>() {
println(service)
}()
}
pub struct Service {
}
fn main() {
app.register(Service{})
assert true
}
Service{}
```
> cgen: fix generic closure fn direct call (fix #16012)

- vlib/v/ast/table.v
- vlib/v/checker/tests/go_append_optional_to_threads_err.out
- vlib/v/checker/tests/go_append_optional_to_threads_err.vv
1. Fix #16061 
2. Add tests.
```v
fn foo() ! {}
fn main() {
mut ths := []thread{}
ths << go foo()
ths.wait()
}
```
output:
```
vlib/v/checker/tests/go_append_optional_to_threads_err.vv:5:12: error: cannot append `thread !` to `[]thread`
4 |     mut ths := []thread{}
5 |     ths << go foo()
|               ~~~~~
6 |     ths.wait()
7 | }
```
> ast: disallow append fn() optional or result to go threads (fix #16061)

- cmd/tools/vdoc/utils.v
`int_literal` and `float_literal` are internal types so highlighting them makes no sense
> v doc: remove `int_literal` and `float_literal` from syntax highlighting

- vlib/rand/rand.v
- vlib/rand/random_numbers_test.v
It was suggested to add a convenience function `rand.element` (and the corresponding `PRNG.element`) that takes an array as an argument (variable or literal) and returns an arbitrary element from the array.
> rand: add rand.element and prng.element functions with unit test

- vlib/os/filepath.v
- vlib/os/filepath_test.v
This PR adds `from_slash` and `to_slash` functions and their tests.
They work the same as Go's ToSlash and FromSlash, respectively.
- `from_slash` returns the result of replacing each slash (`/`) character is path with a separator character.
- `to_slash` returns the result of replacing each separator character in path with a slash (`/`).
These functions help to perform cross-platform file path operations.
image:
```v
module main
import os
fn main() {
println(os.to_slash(r'C:\Users\takum\dev\sandbox\vdev'))
println(os.from_slash(r'C:/Users/takum/dev/sandbox/vdev'))
}
```
output:
```shell
C:/Users/takum/dev/sandbox/vdev # to_slash
C:\Users\takum\dev\sandbox\vdev # from_slash
```
reference
- https://pkg.go.dev/path/filepath#FromSlash
- https://pkg.go.dev/path/filepath#ToSlash
> os: add to and from slash function

- vlib/v/gen/c/cgen.v
- vlib/v/tests/option_test.v
1. Fix #16070
2. Add tests.
```v
import os
fn foo() ?C.stat {
buf := C.stat{}
return buf
}
fn main() {
_ := foo() or { C.stat{} }
}
```
output:
passed.
> cgen: fix missing * of optional non-ref structs (fix: #16070)

- vlib/v/gen/c/fn.v
- vlib/v/tests/go_wait_option_test.v
1. Fix #16065
2. Add tests.
```v
fn get_only_a_option_return(return_none bool) ? {
if return_none {
return
}
return error('msg')
}
fn get_only_a_result_return() ! {
return error('msg')
}
fn test_only_a_option_return() {
t1 := go get_only_a_option_return(true)
t1.wait() or { assert false }
t2 := go get_only_a_option_return(false)
t2.wait() or { assert true }
assert true
}
fn test_only_a_result_return() {
t := go get_only_a_result_return()
t.wait() or { assert true }
assert true
}
```
output:
passed.
> cgen: fix when waiting for a go thread and only one result is returned (fix #16065)

- vlib/builtin/int.v
- vlib/builtin/int_test.v
- vlib/math/const.v
- vlib/math/math_test.v
This PR fix math.min_i64.str() (fix #16086).
- Fix math.min_i64.str().
- Add test.
```v
import math
fn main() {
println(math.min_i64.str())
}
-9223372036854775808
```
> builtin: fix math.min_i64.str() (fix #16086)

- vlib/builtin/cfns.c.v
- vlib/os/os.c.v
- vlib/term/ui/input_windows.c.v
Updates the WIN32 declarations in vlib/builtin/cfns.c.v so that invalid usages can be caught earlier by the V compiler.
> builtin: make the C. WIN32 API declarations more precise, to catch errors earlier

- examples/quadtree_demo/quadtree_demo.v
- vlib/datatypes/README.md
- vlib/datatypes/quadtree.v
- vlib/datatypes/quadtree_test.v
Hi team, 
as proposed by Jalon and discussed in the channel here's the PR to add the quadtree structure to the `datatypes`
As I posted in the channel I'm not sure if I need to take action on the generics, I've tested it locally, and works straight as it supposes to. If you have extra requirements, happy to contribute. 
I'm using some idempotency on the tests, and of course, I'm happy to get code reviews and feedback, I'm a full-time CTO and Head of Product so I code the 4% of my daily time, to prototype only, don't expect I'm super fast :)
Thanks, looking forward to helping more.
> extra: add quadtree to datatypes, and its demo to /examples 

- cmd/tools/vtest-self.v
This PR add skipping ssl tests on windows.
errors:
```v
FAIL  [ 158/1136]  4422.398 ms vlib/net/mbedtls/mbedtls_compiles_test.v
D:/Vlang/v/thirdparty/mbedtls/library/platform_util.c:113: warning: implicit declaration of function 'gmtime_s'
C:/Users/yuyi9/AppData/Local/Temp/v/tsession_22b4_255301100/mbedtls_compiles_test.exe.14270699108114662994.tmp.c:25149: warning: assignment from incompatible pointer type
tcc: error: undefined symbol 'CryptAcquireContextA'
tcc: error: undefined symbol 'CryptGenRandom'
tcc: error: undefined symbol 'CryptReleaseContext'
tcc: error: undefined symbol 'gmtime_s'
...
builder error:
This is a compiler bug, please report it …
```
> vtest-self: add skipping ssl tests on windows

- vlib/v/gen/c/match.v
- vlib/v/tests/match_expr_with_last_branch_aggregate_test.v
This PR fix match expr with last aggregate branch (fix #16100).
- Fix match expr with last aggregate branch.
- Add test.
```v
type MyT = f32 | f64 | i64 | int | rune | string | u32 | u64
type FnMyT = fn (MyT)
fn (any []MyT) each(fun FnMyT) {
for x in any {
fun(x)
}
}
fn (myt MyT) to_s() string {
return match myt {
string { myt }
rune { rune(myt).str() }
int, u32, i64, u64, f32, f64 { myt.str() } // FAIL compilation
}
}
fn main() {
mut arr := [MyT(1), `😝`, 'we are mamamoo', f32(u64(-1)), f64(u64(-1)), i64(-1), u64(-1)]
arr.each(fn (my MyT) {
println(my.to_s())
})
}
1
😝
we are mamamoo
1.8446744e+19
1.8446744073709552e+19
-1
18446744073709551615
```
> cgen: fix match expr with last aggregate branch (fix #16100)

- vlib/net/websocket/io.v
- vlib/net/websocket/websocket_client.v
- vlib/net/websocket/websocket_server.v
- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/lock_expected.vv
- vlib/v/fmt/tests/lock_input.vv
- vlib/v/tests/shared_array_last_test.v
> v fmt: fix extra space for lock/rlock without expressions

- cmd/tools/vdoctor.v
- vlib/io/util/util.v
- vlib/io/util/util_test.v
- vlib/os/dir_expansions_test.v
- vlib/os/filelock/lib_nix.c.v
- vlib/os/filelock/lib_windows.c.v
- vlib/os/os.js.v
- vlib/os/os.v
- vlib/os/os_js.js.v
- vlib/os/os_nix.c.v
- vlib/os/os_test.v
- vlib/os/os_windows.c.v
- vlib/v/builder/compile.v
APIs like the existing `os.mkdir()!` return `!bool`, but in actuality,
they will be clearer if they just returned `!` instead, since their
boolean return value is ignored in practically 100% of the call sites.
> os: cleanup APIs returning `!bool` to either return `!` or `bool`

- vlib/v/ast/table.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/array_elements_with_optional_test.v
1. Fix #16099 
2. Add test.
```v
struct Foo1 {
arr1 [5]?int
arr2 [5]int
}
fn get_has_optional_fixed() ?int {
foo := Foo1{}
return foo.arr1[0]
}
fn get_no_optional_fixed() int {
foo := Foo1{}
return foo.arr2[0]
}
fn test_optional_fixed() ? {
x := get_has_optional_fixed()?
assert x == 0
assert get_no_optional_fixed() == 0
}
struct Foo2 {
mut:
arr1 []?int
arr2 []int
}
fn get_has_optional() ?int {
mut foo := Foo2{}
foo.arr1 << 0
return foo.arr1[0]
}
fn get_no_optional() int {
mut foo := Foo2{}
foo.arr2 << 0
return foo.arr2[0]
}
fn test_optional_non_fixed() ? {
x := get_has_optional()?
assert x == 0
assert get_no_optional() == 0
}
```
output:
passed.
explain:
When a fixed array element has optional, some "option_xxx definitions" need to be forward to the up of "typedef".
> ast, cgen: fix wrong in name and cname when array and fixed array elements have optional (fix #16099)

- vlib/v/checker/fn.v
- vlib/v/checker/tests/generics_method_called_variadic_arg_mismatch.out
- vlib/v/checker/tests/generics_method_called_variadic_arg_mismatch.vv
This PR check generic method called variadic argument mismatch (fix #16106).
- Check generic method called variadic argument mismatch.
- Add test.
```v
struct Client {}
fn (cl Client) req<T>(data ...string) {}
struct Product {}
fn (c Client) products_list(options ...string) {
c.req<Product>(options) // (...options) works
}
fn main() {
mut sc := Client{}
sc.products_list()
}
./tt1.v:8:4: error: to pass `options` (string) to `req` (which accepts type `...string`), use `...options`
6 | 
7 | fn (c Client) products_list(options ...string) {
8 |     c.req<Product>(options) // (...options) works
|       ~~~~~~~~~~~~~~~~~~~~~
9 | }
10 |
```
> checker: check generic method called variadic argument mismatch (fix #16106)

- examples/log.v
- examples/logfatal.v
- vlib/log/log.v
This PR marks Log fatal as `[noreturn]`, addressing issue #16128
Log fatal is documented as calling panic, and therefore can't return.
However, Log fatal can't be used in places that require `[noreturn]`
> log: mark fatal as [noreturn]

- vlib/v/checker/fn.v
- vlib/v/tests/map_builtin_call_test.v
1. Fix #16077 
2. Add tests.
```v
pub struct Set<T> {
mut:
elements map[T]u8
}
pub fn (mut set Set<T>) rest() ?[]T {
element := set.pick()?
return set.elements.keys().filter(it != element)
}
pub fn (set Set<T>) pick() ?T {
for k, _ in set.elements {
return k
}
return error('Set is empty.')
}
fn mian() {
_ := Set<string>{}
_ := Set<int>{}
}
```
output:
passed.
> checker: fix generic information is lost of the map built-in method call (fix #16077)

- vlib/v/parser/assign.v
- vlib/v/parser/if_match.v
- vlib/v/parser/sql.v
This PR simplify and cleanup check_undefined_variable().
- Remove redundant check_undefined_variable_by_names().
- Add `UnsafeExpr` and `CastExpr`.
- Change optional to result.
> parser: simplify and cleanup check_undefined_variable()

- vlib/v/checker/fn.v
- vlib/v/tests/closure_test.v
Fix updating of the scope, that has the closed over variable, when that variable is from a `for x in y {` loop, `x,y := multi()` (and probably others as well). Add tests.
> checker: fix taking a closure of x, where `x` may be coming from a non trivial parent scope, like `for x in y {` or `x,y := multi()` (fix #16141)

- vlib/v/ast/ast.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/unused_label.out
1. Fix #16146
2. Add tests.
```v
module main
fn main() {
label:
}
```
output:
```
vlib/v/checker/tests/label_not_used_warning.vv:4:2: warning: label `label` defined and not used
2 | 
4 |     label:
|     ~~~~~~
5 | }
```
> checker: fix the pos information in the warning message when the label is not used (fix #16146)

- vlib/v/checker/struct.v
- vlib/v/checker/tests/struct_field_optional_init_err.out
- vlib/v/checker/tests/struct_field_optional_init_err.vv
1. Fix #16152 
2. Add tests.
```v
struct Foo {
bar !int
baz ?int
}
fn main() {
_ := Foo{
bar: 1
baz: 1
}
}
```
output:
```
vlib/v/checker/tests/struct_field_optional_init_err.vv:8:3: error: field `bar` is result, but initialization of result fields currently unsupported
6 | fn main() {
7 |     _ := Foo {
8 |         bar: 1
|         ~~~~~~
9 |         baz: 1
10 |     }
vlib/v/checker/tests/struct_field_optional_init_err.vv:9:3: error: field `baz` is optional, but initialization of optional fields currently unsupported
7 |     _ := Foo {
8 |         bar: 1
9 |         baz: 1
|         ~~~~~~
10 |     }
11 | }
```
> checker: fix checker missed the check on the initialization of the result field of the struct (fix #16152)

- vlib/v/gen/c/cgen.v
- vlib/v/tests/return_result_in_or_block_test.v
This PR fix return result in or block (fix #15219).
- Fix return result in or block.
- Add test.
```v
fn unwrap_int() ?int {
return 1
}
fn unwrap_function1() !int {
return unwrap_int() or { error('we are issing the return?') }
}
fn unwrap_function2() ?int {
return unwrap_int() or { none }
}
fn main() {
x1 := unwrap_function1() or { panic(err) }
println(x1)
assert x1 == 1
x2 := unwrap_function2() or { panic(err) }
println(x2)
assert x2 == 1
}
1
1
```
> cgen: fix return result in or block (fix #15219)

- vlib/builtin/array_test.v
- vlib/v/gen/c/assign.v
This PR fix using 'array' name variable in array_init  (fix #16165).
- Fix using 'array' name variable in array_init.
- Add test.
```v
fn main() {
array := []int{len: 4, init: it}
println(array)
assert array == [0, 1, 2, 3]
}
[0, 1, 2, 3]
```
> cgen: fix using 'array' name variable in array_init  (fix #16165)

- vlib/v/checker/fn.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/aliased_array_method_call_test.v
1. Fix #16169 
2. Add tests.
```v
fn get_bytes_array() []byte {
return [byte(97), 98, 99]
}
fn main() {
println(get_bytes_array().bytestr())
arr := [byte(97), 98, 99]
println(arr.bytestr())
}
```
output:
```
abc
abc
```
> checker, cgen: when the array element is an alias, enable to call the method of the parent element array (fix #16169)

- vlib/v/gen/c/comptime.v
- vlib/vweb/vweb_app_test.v
This PR fix vweb app route methods filtering (fix #9636).
- Fix vweb app route methods filtering.
- Add test.
```v
module main
import vweb
pub struct App {
vweb.Context
}
fn main() {
vweb.run(&App{}, 9080)
}
struct ExampleStruct {
example int
}
pub fn (mut app App) request_raw_2() vweb.Result {
stuff := []ExampleStruct{}
return app.request_raw(stuff)
}
pub fn (mut app App) request_raw(foo []ExampleStruct) vweb.Result {
return $vweb.html()
}
[Vweb] Running app on http://localhost:9080/
```
> cgen: fix vweb app route methods filtering (fix #9636)

- vlib/v/checker/checker.v
- vlib/v/checker/return.v
- vlib/v/tests/embed_error_in_returning_result_test.v
This PR fix returning embedded error result.
- Fix returning embedded error result.
- Add test.
```v
struct NotFoundErr {
Error
id string
}
struct User {}
fn find_by_id(id string) !User {
return NotFoundErr{
id: id
}
}
fn main() {
find_by_id('id123') or {
println(err)
assert true
return
}
assert false
}
NotFoundErr:
```
> checker: fix returning embedded error result

- vlib/v/parser/comptime.v
- vlib/v/parser/tests/comptime_path_not_found_err.out
- vlib/v/parser/tests/comptime_path_not_found_err.vv
This PR correct comptime path not found error position (fix #16189).
- Correct comptime path not found error position.
- Add test.
```v
fn main() {
tmp := $tmpl('tempate.txt')
a := tmp
}
./tt1.v:2:15: error: template file "tempate.txt" not found
2 |     tmp := $tmpl('tempate.txt')
|                  ~~~~~~~~~~~~~
3 |     a := tmp
4 | }
```
> parser: correct comptime path not found error position (fix #16189)

- vlib/v/ast/table.v
- vlib/v/checker/check_types.v
- vlib/v/checker/checker.v
- vlib/v/checker/comptime.v
- vlib/v/checker/fn.v
- vlib/v/checker/infix.v
- vlib/v/checker/struct.v
- vlib/v/checker/tests/pointer_ops.out
- vlib/v/eval/expr.v
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/struct.v
- vlib/v/gen/js/auto_str_methods.v
- vlib/v/tests/interface_fields_test.v
1. Fix #16198
2. Add tests.
```v
interface Speaker {
speak() string
}
struct Dog {}
fn (d Dog) speak() string {
return 'woof'
}
struct Foo {
mut:
speaker &Speaker = unsafe { nil }
}
fn main() {
mut foo := Foo{
speaker: unsafe { nil }
}
assert true
foo.speaker = unsafe { nil }
assert true
foo.speaker = &Dog{}
assert foo.speaker.speak() == 'woof'
}
```
output:
passed.
> ast, checker, cgen: fix the wrongs when the struct interface type field is nil (fix #16198)

- examples/brainvuck.v
This PR adds a tiny brainvuck interpreter to the examples directory. It can serve as a showcase for basic `os` module usage, a foundation in interpreter programming and as a teaching tool for the tiny language.
> examples: add tiny brainvuck interpreter

- vlib/v/parser/tmpl.v
- vlib/v/tests/tmpl/template.in
- vlib/v/tests/tmpl_with_single_quotes_test.v
This PR fix vtmpl with single quotes (fix #16154).
- Fix vtmpl with single quotes.
- Add test.
template.in
```v
someval: @{s.someval('huh')}
someotherval: @{s.m['hah']}
```
```v
module main
pub struct SomeThing {
pub:
m map[string]string
}
fn (s SomeThing) someval(what string) string {
return s.m[what]
}
fn (s SomeThing) template() string {
return $tmpl('template.in')
}
fn main() {
mut sm := map[string]string{}
sm['huh'] = 'monkey'
sm['hah'] = 'parrot'
s := SomeThing{sm}
result := s.template()
assert result.trim_space() == "someval: monkey
someotherval: parrot"
}
someval: monkey
someotherval: parrot
```
> parser: fix $tmpl with single quotes (fix #16154)

- vlib/v/gen/c/auto_eq_methods.v
- vlib/v/tests/struct_auto_eq_gen_interface_test.v
(This issue is related to the merged PR #16199 to some extent, so I fixed it by the way)
1. Fix: #16074 
2. Add tests.
```v
pub interface Logger {
mut:
info(s string)
}
struct LogContainer {
name string
mut:
logger &Logger = unsafe { nil }
}
fn main() {
assert LogContainer{
name: 'abc'
} == LogContainer{
name: 'abc'
}
}
```
output:
passed.
> cgen: fix comparison with == of structs with pointers to interfaces autogenerates invalid eq comparison method (fix #16074)

- vlib/v/eval/eval.v
Now it shows the same commit hash on panic:
```v
$ cat x.v
panic('panic!')
$ ./v2 run x.v
V panic: panic!
v hash: 71bff21
/tmp/v_1000/x.11155285029361023853.tmp.c:6650: at _v_panic: Backtrace
/tmp/v_1000/x.11155285029361023853.tmp.c:12115: by main__main
/tmp/v_1000/x.11155285029361023853.tmp.c:12486: by main
$ ./v2 -interpret run x.v
V panic: panic!
V hash: 71bff21
/home/jomaca/dev/v-world/vdev/vlib/builtin/builtin.c.v:88: at panic
/home/jomaca/dev/v-world/vdev/x.v:1: by main.main
```
> v.eval: consistency in commit hash shown on panic

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/comptime_method_args_expected.vv
- vlib/v/fmt/tests/comptime_method_args_input.vv
- vlib/v/tests/comptime_method_args_test.v
1. Fix #16218 
2. Add tests.
```v
fn main() {
$if !linux {
$compile_error('Only Lin\"ux is currently supported')
}
}
```
output (on macos):
```
a.v:2:2: error: Only Lin\"ux is currently supported
1 | $if !linux {
2 |     $compile_error("Only Lin\"ux is currently supported")
|     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 | }
4 |
```
------------------------
```v
$if !linux {
$compile_error("Only Lin\"ux is currently supported")
}
```
v fmt output:
```v
$if !linux {
$compile_error('Only Lin\"ux is currently supported')
}
```
> fmt: fix compiler_error('...') broken by fmt (fix #16218)

- vlib/v/checker/tests/str_interpol_invalid_err.out
- vlib/v/checker/tests/str_interpol_invalid_err.vv
- vlib/v/scanner/scanner.v
- vlib/v/tests/string_interpolation_inner_cbr_test.v
This PR fix and resotre string interpolation tests.
```v
struct St {}
fn foo() ?int {
return 22
}
fn main() {
s1 := '${foo() or { 11 }}'
println(s1)
assert s1 == '22'
s2 := '${St{}}'
println(s2)
assert s2 == 'St{}'
s3 := '${{
'a': 1
}}'
println(s3)
assert s3 == "{'a': 1}"
}
22
St{}
{'a': 1}
```
```v
struct Foo {}
type Alias = Foo
type SumType = Alias | int
fn main() {
_ = '${[1]:x}'
_ = '${[1]!:x}'
_ = '${Foo{}:x}'
_ = '${[1]:f}'
_ := '${none:F}'
_ = '${{"a": "b"}:x}'
_ = '${Alias(Foo{}):x}'
_ = '${SumType(int(5)):o}'
}
./tt1.v:8:13: error: illegal format specifier `x` for type `[]int`
6 | 
8 |     _ = '${[1]:x}'
|                ^
9 |     _ = '${[1]!:x}'
10 |     _ = '${Foo{}:x}'
./tt1.v:9:14: error: illegal format …
```
> scanner: fix and restore string interpolation tests

- vlib/v/checker/return.v
- vlib/v/tests/results_multi_return_test.v
- vlib/v/tests/string_optional_none_test.v
- vlib/vweb/parse.v
This PR fix return error with multi_return optional.
- Fix return error with multi_return optional.
- Modify the related tests.
```v
struct Err {
msg  string
code int
}
fn (e Err) msg() string {
return e.msg
}
fn (e Err) code() int {
return e.code
}
fn foo() ?string {
return 'foo'
}
fn bar() !(string, int) {
a := foo() or { return Err{
msg: 'error test'
} }
return a, 1
}
fn main() {
b, _ := bar() or { panic(err) }
println(b)
assert b == 'foo'
}
foo
```
> checker: fix return error with multi_return optional

- vlib/v/gen/c/dumpexpr.v
- vlib/v/tests/inout/dump_multiple_ptr.out
- vlib/v/tests/inout/dump_multiple_ptr.vv
1. Fix #16247 
2. Add tests.
```v
fn main() {
i := 42
dump(i)
ir := &i
dump(ir)
irr := &ir
dump(irr)
irrr := &irr
dump(irrr)
}
```
output:
```
[vlib/v/tests/inout/dump_multiple_ptr.vv:3] i: 42
[vlib/v/tests/inout/dump_multiple_ptr.vv:5] ir: &42
[vlib/v/tests/inout/dump_multiple_ptr.vv:7] irr: &&42
[vlib/v/tests/inout/dump_multiple_ptr.vv:9] irrr: &&&42
```
> cgen: fix dump() multi ptr (fix #16247)

- cmd/tools/vtest-cleancode.v
- vlib/v/eval/gen/infix_gen.v
- vlib/v/scanner/scanner.v
- vlib/v/tests/string_new_interpolation_test.v
This PR fix new string interpolation `println('{a}{b}{c}{d}')`. (fix #16257)
- Fix new string interpolation `println('{a}{b}{c}{d}')`.
- Add test.
```v
fn main() {
a, b, c, d := 1, 2, 3, 4
println('{a}{b}{c}{d}')
assert '{a}{b}{c}{d}' == '1234'
println('{a} {b} {c} {d}')
assert '{a} {b} {c} {d}' == '1 2 3 4'
}
1234
1 2 3 4
```
> scanner: fix new string interpolation println('{a}{b}{c}{d}')

- vlib/v/gen/c/cgen.v
- vlib/v/tests/return_match_expr_of_sumtype_result_test.v
This PR fix return match expr of sumtype result  (fix #16255).
- Fix return match expr of sumtype result.
- Add test.
```v
type Foo = int | string
fn foo1() !Foo {
return match true {
true { 1 }
else { '' }
}
}
fn foo2() ?Foo {
return match true {
true { 1 }
else { '' }
}
}
fn main() {
ret1 := foo1() or { return }
println(ret1)
assert '$ret1' == 'Foo(1)'
ret2 := foo2() or { return }
println(ret2)
assert '$ret2' == 'Foo(1)'
}
Foo(1)
Foo(1)
```
> cgen: fix return match expr of sumtype result  (fix #16255)

- cmd/tools/vtest-cleancode.v
- vlib/v/scanner/scanner.v
- vlib/v/tests/inout/string_interpolation_inner_expr_cbr.out
- vlib/v/tests/inout/string_interpolation_inner_expr_cbr.vv
Fix #16240 
```v
enum Foo{
abc
def
}
fn main() {
println('Foo = {Foo.def}')
println('Foo = {unsafe{Foo(1)}}')
}
```
output:
```
Foo = def
Foo = def
```
> scanner: prevent resolving to nested interpolation (fix #16240)

- vlib/v/checker/check_types.v
- vlib/v/checker/tests/return_result_fn_mismatch.out
- vlib/v/checker/tests/return_result_fn_mismatch.vv
This PR check fn type mismatch of return result type fn (fix #16260).
- Check fn type mismatch of return result type fn.
- Add test.
```v
type AnonOptionalFun = fn () !
// do_test is used to test functionality
pub fn do_test(cb AnonOptionalFun) {
cb() or { panic(err) }
}
fn foo () ! {
}
fn main() {
test := fn () {
foo() or { return }
}
do_test(test)
}
./tt1.v:15:10: error: cannot use `fn ()` as `fn () !` in argument 1 to `do_test`
13 |         foo() or { return }
14 |     }
15 |     do_test(test)
16 | }
```
> checker: check fn type mismatch of return result type fn (fix #16260)

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/native/tests/print.vv
- vlib/v/gen/native/tests/print.vv.out
This PR enables printing for all implemented expressions of the types `bool`, `int` and `string` for the native backend.
> native: enable printing for all supported expressions

- README.md
Updates the section about installing OpenSSL, since it is no longer required (but may still be desired).
> doc: update ssl section

- examples/vweb/vweb_example.v
- examples/vweb_orm_jwt/src/main.v
Use of before_request in examples
```bash
$ v run .
[Vweb] Running app on http://0.0.0.0:8081/
[Vweb] POST /task/create
[Vweb] POST /task/create_all
```
bugfix: create table panic
> examples: use of before_request function for multi-route examples and bugfix

- vlib/v/checker/check_types.v
- vlib/v/checker/fn.v
- vlib/v/checker/tests/fn_call_arg_ptr_mismatch_err.out
- vlib/v/checker/tests/fn_call_arg_ptr_mismatch_err.vv
1. Fix:
#16261
#16262
#16263
2. Add tests.
```v
struct Something {
value int
}
fn get_value(s &Something) int {
return s.value
}
fn main() {
s := &Something{
value: 1
}
v := get_value(&s)
println(v)
}
```
output:
```
a.v:58:17: error: cannot use `&&Something` as `&Something` in argument 1 to `get_value`
56 |     }
57 |  
58 |     v := get_value(&s)
|                    ~~
59 |     println(v)
60 | }
```
--------------
```v
interface ISomething {
value int
get_value() int
}
struct Something {
value int
}
fn (s Something) get_value() int {
return s.value
}
fn get_value(s &ISomething) int {
return s.value
}
fn main() {
s := &Something{
value: 1
}
v := get_value(&s)
println(v)
}
```
output:
```
a.v:87:17: error: cannot use `&&Something` as `&ISomething` in argument 1 to `get_value`
85 |     } …
```
> checker: fix multiple pointer check of fn and method args (fix #16261 #16262 #16263)

- vlib/v/gen/c/dumpexpr.v
- vlib/v/tests/inout/dump_none.out
- vlib/v/tests/inout/dump_none.vv
This PR fix `dump(none)` (fix #16283).
- Fix `dump(none)`.
- Add test.
```v
fn main() {
dump(none)
}
[.\\tt1.v:2] none: none
```
> cgen: fix dump(none) (fix #16283)

- vlib/v/checker/checker.v
- vlib/v/checker/comptime.v
- vlib/v/checker/fn.v
- vlib/v/checker/tests/closure_undefined_ident_err.out
- vlib/v/checker/tests/closure_undefined_ident_err.vv
This PR check undefined ident in closure anon fn (fix #16274).
- Check undefined ident in closure anon fn.
- Add test.
```v
module main
struct Custom {
name string
}
interface MyInterface {
some_function()
}
fn (c Custom) some_function() {
println('hello $c.name from ${@METHOD}')
}
fn main() {
a := Custom{'rabbit'}
x := a.some_function
x()
b := Custom{'horse'}
y := b.some_function
y()
c := Custom{'noname'}
$for method in MyInterface.methods {
z := fn [c] () {
c.$method()
}
z()
}
}
./tt1.v:25:7: warning: unused variable: `method`
23 |     c := Custom{'noname'}
24 | 
25 |     $for method in MyInterface.methods {
|          ~~~~~~
26 |         z := fn [c] () {
27 |             c.$method()
./tt1.v:27:6: error: undefined ident `method` in the anonymous function
25 | …
```
> checker: check undefined ident in closure anon fn (fix #16274)

- vlib/v/gen/c/fn.v
- vlib/v/tests/interface_variadic_test.v
1. Fix #16286 
2. Add tests.
```v
interface Bar {
get(...int) []int
}
struct Foo {}
fn (f Foo) get(n ...int) []int {
if n.len == 0 {
return [-1]
} else {
return n
}
}
fn main() {
f := Foo{}
println(f.get())
b_values := Bar(Foo{})
println(b_values.get(1, 2, 3))
b_empty := Bar(Foo{})
println(b_empty.get())
}
```
output:
```
[-1]
[1, 2, 3]
[-1]
```
> cgen: fix call method with an empty args on an interface with variadic (fix #16286)

- vlib/v/gen/native/elf.v
- vlib/v/gen/native/macho.v
With this PR, string literals will only generate once, even if used multiple times in the native backend. This should be no problem since strings are immutable and enables optimizations when comparing strings in the future.
> native: don't generate duplicate strings

- vlib/v/parser/containers.v
- vlib/v/tests/map_test.v
1. Fix #16285 
2. Add tests.
```v
fn main() {
mut m := {
r'key': 1
}
assert m[r'key'] == 1
m[r'key'] = 2
assert m[r'key'] == 2
}
```
output:
passed.
> parser: fix raw string as map keys (fix #16285)

- vlib/v/gen/c/comptime.v
- vlib/v/tests/comptime_for_test.v
The compile-time-for can iterate methods in a struct and it is supposed to provide a method's details such as `name`, `typ`, and `return_type`. However, the `typ` has not worked properly as reported in #16277. This PR fixes compile-time-for, so it finds methods' `typ` correctly.
Once this patch is applied, `vlib/v/gen/c/compiletime/methods.v` will result in:
```console
method_one is NOT `fn(string) string`
method_one does NOT return `int`
method_one's first arg is NOT `string`
method_one IS a void method
method_two is NOT `fn(string) string`
method_two DOES return `int`
method_two's first arg is NOT `string`
method_two is NOT a void method
method_three IS `fn(string) string`
method_three does NOT return `int`
method_three's first arg IS `string`
method_three is NOT a void method
``` …
> cgen: fix a bug that compile-time-for does not find methods typ

- vlib/v/checker/infix.v
- vlib/v/checker/tests/generic_sumtype_invalid_variant.out
- vlib/v/checker/tests/infix_is_notis_interface_unimplemented_err.out
- vlib/v/checker/tests/infix_is_notis_interface_unimplemented_err.vv
- vlib/v/checker/tests/is_type_invalid.out
- vlib/v/pkgconfig/bin/pkgconfig_test.v
- vlib/v/tests/generics_array_typedef_test.v
- vlib/v/tests/generics_assign_reference_generic_struct_test.v
1. Fix #16282 
2. Fix #16298
3. Add tests.
```v
fn f() ?int {
return none
}
fn type_unimplemented_ierror() {
if _ := f() {
} else {
_ = err is int
}
_ = f() or {
_ = err is int
0
}
}
interface IAbc {
some_method()
}
struct Struct {}
fn (s Struct) some_method() {}
fn type_unimplemented_interface() {
ivalue := IAbc(Struct{})
_ := ivalue is int
}
```
output:
```
vlib/v/checker/tests/infix_is_notis_interface_unimplemented_err.vv:8:14: error: `int` doesn't implemented interface `IError`
6 |     if _ := f() {
7 |     } else {
8 |         _ = err is int
|                    ~~~
9 |     }
10 |
vlib/v/checker/tests/infix_is_notis_interface_unimplemented_err.vv:12:14: error: `int` doesn't implemented interface `IError`
10 | 
11 |     _ = f() or {
12 |         _ = err is int
|                    ~~~ …
```
> checker: fix the check of types not implemented by interfaces in infix key_is and not_is (fix #16282 #16298)

- vlib/v/scanner/scanner.v
- vlib/v/tests/string_new_interpolation_test.v
This PR fix new string interpolation - print('{a}{{b}}') (fix #16294).
- Fix new string interpolation - print('{a}{{b}}').
- Add test.
```v
fn main() {
a, b := 1, 2
println('{a}{{b}}')
println('{a}\{{b}}')
println('{a}{{{b}}}')
}
1{2}
1{2}
1{{2}}
```
> scanner: fix new string interpolation - print('{a}{{b}}') (fix #16294)

- vlib/v/gen/js/js.v
- vlib/v/gen/js/tests/testdata/match.out
- vlib/v/gen/js/tests/testdata/match.v
This PR enables the JS backend to support `match true {}` expression.
1. Run the following command.
```
v -b js run vlib/v/gen/js/tests/testdata/match.v
```
2. Make sure the output is the same with the content of the `match.out` file.
Resovles #14473
> js: fix the js backend that cannot support `match true {}`.

- vlib/net/html/parser_test.v
- vlib/v/eval/gen/infix_gen.v
- vlib/v/scanner/scanner.v
- vlib/v/tests/string_new_interpolation_test.v
This PR fix the new string interpolation - println('{s == 'hello'}') (fix #16318).
- Fix the new string interpolation - println('{s == 'hello'}').
- Add test.
```v
fn main() {
s := 'hello'
println('{s == 'hello'}')
println('{s != 'hello'}')
n := 22
println('{n >= 10}')
println('{n <= 10}')
}
true
false
true
false
```
> scanner: fix the new string interpolation - println('{s == 'hello'}') (fix #16318)

- vlib/regex/regex.v
- vlib/regex/regex_test.v
- fix for problem with last group
- added test
Example code:
```v
any_but_newline_group := "([^\n]|a)*"
mut re_group := regex.regex_opt(any_but_newline_group) or { panic(err) }
txt := "a"
start_group, end_group := re_group.find(txt)
println("group  | start: {start_group}, end: {end_group}")
```
must return [0,1]
> Regex: bug fix for last group with OR inside

- tutorials/building_a_simple_web_blog_with_vweb/README.md
Old address:
https://github.com/vlang/v/tree/master/tutorials/code/blog
New address:
https://github.com/vlang/v/tree/master/tutorials/building_a_simple_web_blog_with_vweb/code/blog
Also the link now uses a relative path so it will still work if the folder gets moved/renamed.
> Fix broken link in tutorial

- examples/vweb/vweb_assets/index.html
- vlib/rand/random_numbers_test.v
- vlib/v/scanner/scanner.v
- vlib/v/tests/string_new_interpolation_test.v
This PR fix new string interpolation: print('{n:10}') (fix #16321).
- Fix new string interpolation: print('{n:10}').
- Add test.
```v
fn main() {
n := 22
println('{n:10}')
f := 2.345
println('{f:05.2}')
println('{@FILE}')
}
22
02.35
D:\Test\v\tt1\tt1.v
```
> scanner: fix new string interpolation: print('{n:10}') (fix #16321)

- .editorconfig
- make.bat
make.bat: fix use of `make.bat` from `v up`
- use move semantics, instead of replace, for `v` executable updates
- fixes [#16184](https://github.com/vlang/v/issues/16184)
- includes DRY changes for `v` executable names
- includes some feedback/comment changes to hopefully improve future-dev understanding
- also includes...
- some minor `make.bat` UI fixes
- an EditorConfig change fixing the EOLN setting for BAT/CMD files
`v up` updates the executable by directly calling `make.bat`, awaiting the result, which keeps an open file handle to it's own executable file. `make.bat` compiles and, crucially, attempts to directly replace that `v` executable. But, in WinOS, files with open file handles cannot be deleted/replaced, so the `make` then fails. The other key point is that, although WinOS …
> make.bat: fix use of `make.bat` from `v up`

- vlib/v/checker/constants/constants.v
- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/conditional_compilation_keep_in_module.vv
As reported in #16328, `fmt` transforms compile time options when conflicting names are used. With this patch, the comptime options will be kept even in that case.
No errors should occur when running `v fmt` against the new test file.
```
v fmt -c vlib/v/fmt/tests/conditional_compilation_keep.vv
```
Resolves #16328
> fmt: fix - `v fmt` transforms compile time options in some cases

- vlib/v/gen/c/auto_str_methods.v
- vlib/v/tests/generic_sumtype_str_test.v
This PR fix generic sumtype auto str  (fix #16340 part1).
- Fix generic sumtype auto str.
- Add test.
```v
module main
struct None {}
pub type Maybe<T> = None | T
pub fn (m Maybe<T>) str<T>() string {
return if m is T {
x := m as T
'Some($x)'
} else {
'Noth'
}
}
pub fn some<T>(v T) Maybe<T> {
return Maybe<T>(v)
}
fn main() {
a := some(123)
b := some('abc')
println(a.str())
println(a)
println('$a')
assert '$a' == 'Some(123)'
println(b.str())
println(b)
println('$b')
assert '$b' == 'Some(abc)'
}
Some(123)
Some(123)
Some(123)
Some(abc)
Some(abc)
Some(abc)
```
> cgen: fix generic sumtype auto str  (fix #16340 part1)

- vlib/v/checker/fn.v
- vlib/v/checker/struct.v
- vlib/v/checker/tests/anon_fn_without_body.out
- vlib/v/checker/tests/anon_fn_without_body.vv
- vlib/v/checker/tests/globals/global_anon_fn_without_body.out
- vlib/v/checker/tests/globals/global_anon_fn_without_body.vv
- vlib/v/checker/tests/struct_field_init_with_nobody_anon_fn_err.out
The check doesn't trigger errors for anonymous functions without body block as reported in #16212. This PR makes the checker disallow the no-body-block anon functions.
It also deletes lines of code from `checker > struct.v` because it will be never called and the relevant test is updated accordingly.
Run the two new test files. The output should be the same as the corresponding `.out` files.
Resolves #16212
> checker: fix: anon fn without body block doesn't trigger errors

- vlib/v/scanner/scanner.v
- vlib/v/tests/string_new_interpolation_test.v
This PR fix new string interpolation - nested quotes.
- Fix new string interpolation - nested quotes.
- Add test.
```v
fn foo() string {
match true {
true {
fields := ['aaa', 'bbb', 'ccc']
return '[]T{{fields.join(', ')}}'
}
else {
fields := ['aaa', 'bbb', 'ccc']
return ('const ({fields.join(' ')})')
}
}
}
fn main() {
ret := foo()
println(ret)
}
[]T{aaa, bbb, ccc}
```
> scanner: fix new string interpolation - nested quotes

- GNUmakefile
- make.bat
`make rebuild` (for both POSIX and WinOS platforms)
- cleans repository, including removal of TCC, LEGACY, and VC sub-repos, then initiates a clean rebuild of V
During development, especially jumping between CMD and WSL, the sub-repositories may become altered or be in an incorrect state for the currently in-use platform. `make rebuild` will remove the sub-repos and initiate a new clean build of V (using newly retrieved, correct, copies of the sub-repos).
---
Currently, an equivalent process would be `make clean && make` for POSIX and a slightly different `make cleanall && make` for WinOS. This just combines the steps into one, easy-to-remember, `make rebuild` command, which is the same for either platform-type. This can really be helpful when you're jumping back and forth between …
> make: add 'rebuild' target (clean and reset sub-repos, then rebuild V)

- vlib/v/checker/checker.v
- vlib/v/checker/comptime.v
- vlib/v/checker/constants/constants.v
This is a follow-up PR of #16351. It moves comptime constants into a separate module - `v.checker.constants` as per @spytheman 's suggestion.
Make sure that no errors occur while compiling `v`.
> refactor: checker: move comptime constants into separate module

- examples/news_fetcher.v
- vlib/crypto/ed25519/internal/ed25519_test.v
- vlib/sync/pool/README.md
- vlib/sync/pool/pool.v
- vlib/sync/pool/pool_test.v
- vlib/v/builder/cbuilder/parallel_cc.v
- vlib/v/checker/check_types.v
- vlib/v/checker/tests/struct_field_init_fntype_mismatch.out
- vlib/v/checker/tests/struct_field_init_fntype_mismatch.vv
- vlib/v/gen/c/cgen.v
This PR check fntype mismatch of struct field init (fix #16372).
- Check fntype mismatch of struct field init.
- Add test.
```v
struct Foo{}
type FooFn = fn(mut f Foo) 
struct Server{
foo_fn FooFn = unsafe{ nil }
}
fn foo(f &Foo) {}
fn main(){
srv := Server{
foo_fn: foo
}
dump(isnil(srv.foo_fn))
}
./tt1.v:13:3: error: cannot assign to field `foo_fn`: expected `fn (mut Foo)`, not `fn (&Foo)`
11 | fn main(){
12 |     srv := Server{
13 |         foo_fn: foo
|         ~~~~~~~~~~~
14 |     }
15 |     dump(isnil(srv.foo_fn))
```
> checker: check fntype mismatch of struct field init (fix #16372)

- examples/gg/additive.v
- examples/gg/rotating_textured_quad.v
- vlib/gg/draw.c.v
- vlib/gg/gg.c.v
- vlib/gg/image.c.v
- vlib/gg/image.v
- vlib/gg/text_rendering.c.v
- vlib/x/ttf/render_sokol_cpu.v
This PR changes the way pipeline works in `gg`, Context's `timage_pip` is now deprecated in favour of the new `PipelineContainer` in Context.
The reason why I'm keeping the `timage_pip` (for now) is because of v ui, some of the code depends on it and I'm not quite sure how to handle it, [here](https://github.com/vlang/ui/blob/62dd926bcdc2b189c34003aa758185303b5f3897/src/interface_drawtextwidget.v#L150) and [here](https://github.com/vlang/ui/blob/8866addcc2758effe4d0bd773840f844921077a7/src/extra_draw.v#L374)
* PipelineContainer to store `alpha`, `add` pipeline (more effects will be added later on)
* DrawImageConfig now has a `effect`, which can be used with `ImageEffect` enum.
```v
pub enum ImageEffect {
// TODO: Add more effects
alpha
add
}
```
Instead of using `timage_pip`, we can now …
> gg: Revamp `Context` pipeline for more effects

- vlib/v/parser/parse_type.v
- vlib/v/parser/tests/struct_field_required_fn_optional_type.out
- vlib/v/parser/tests/struct_field_required_fn_optional_type.vv
- vlib/v/parser/tests/struct_field_required_fn_result_type.out
- vlib/v/parser/tests/struct_field_required_fn_result_type.vv
When a `required` field attribute follows `void` optional or result type, the parser handles it as an array which results in a type error as reported in #16388. This PR fixes the parser so it handles the field attribute properly.
Run the new tests files and make sure each output is the same with the corresponding output file. For example, let's run the following code.
```v
struct Foo {
foo fn() ! [required]
}
fn main() {
f := Foo{}
println(f)
}
```
It should produce:
```console
vlib/v/parser/tests/struct_field_required_fn_result_type.vv:6:7: error: field `Foo.foo` must be initialized
4 |
6 |     f := Foo{}
|          ~~~~~
7 |     println(f)
8 | }
```
Resolves #16388
> Fix: parse error when required field attribute follows void optional or result type

- vlib/v/checker/check_types.v
- vlib/v/checker/fn.v
- vlib/v/checker/tests/generics_method_sumtype_arg_mismatch.out
- vlib/v/checker/tests/generics_method_sumtype_arg_mismatch.vv
This PR check sumtype argument mismatch of the generic method  (fix #16340 part2).
- Check sumtype argument mismatch of the generic method.
- Add test.
```v
module main
struct None {}
pub type Maybe<T> = None | T
pub fn (m Maybe<T>) str<T>() string {
return if m is T {
x := m as T
'Some($x)'
} else {
'Noth'
}
}
pub fn some<T>(v T) Maybe<T> {
return Maybe<T>(v)
}
pub fn noth<T>() Maybe<T> {
return Maybe<T>(None{})
}
pub fn (m Maybe<T>) is_some<T>() bool {
return match m {
None { false }
T { true }
}
}
pub fn (m Maybe<T>) is_noth<T>() bool {
return match m {
None { true }
T { false }
}
}
pub fn (m Maybe<T>) @or<T>(m2 Maybe<T>) Maybe<T> {
return match m {
None {
match m2 {
None { None{} }
T { m2 }
}
}
T {
m
}
}
}
fn main() {
a := some(123)
b := some('abc')
c := a.@or(b)
println(c)
}
PS …
```
> checker: check sumtype argument mismatch of the generic method  (fix #16340 part2)

- vlib/time/README.md
A library that provides utilities for working with time and dates:
TODO
- parsing of time values expressed in one of the commonly used standard time/date formats
- formatting of time values
- arithmetic over times/durations
- converting between local time and UTC (timezone support)
- stop watches for accurately measuring time durations
- sleeping for a period of time
**Examples:**
time can be comparable
see: [V Playground](https://play.vlang.io/p/c121a6dda7)
```v
import time
println(time.now())
```
**Examples:**
see: [V Playground](https://play.vlang.io/p/133d1a0ce5)
```v
import time
const (
time_to_test = time.Time{
year: 1980
month: 7
day: 11
hour: 21
minute: 23
second: 42
microsecond: 123456
unix: 332198622
}
)
println(time_to_test.format())
assert '1980-07-11 21:23' == …
```
> doc: add more examples to vlib/time/README.md

- vlib/sqlite/sqlite.v
- vlib/sqlite/sqlite_orm_test.v
- vlib/sqlite/sqlite_test.v
implements "affected rows count" which is crucial to decide whether insert, update, delete actually did changes in database
> sqlite: affected rows count

- vlib/v/tests/bench/bench_compare_tokens.v
tests: add unsafe block to enum cast 
In [bench_compare_tokens.v](https://github.com/vlang/v/blob/master/vlib/v/tests/bench/bench_compare_tokens.v) on line 18, the result of `km_trie.find` is cast to an enum without an unsafe block, generating an error.
This pull request fixes this by adding an unsafe block to this line.
> tests: add unsafe block to enum cast

- vlib/v/ast/ast.v
- vlib/v/ast/types.v
- vlib/v/checker/fn.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/const_name_equals_fn_name_test.v
Previously, this was a cgen error:
```v
import term
const y = term.yellow // previously this was a cgen error: incompatible types for redefinition of 'term__yellow'
println(y)
```
> checker,cgen: support `const y = term.yellow`, then `println(y('abc'))`

- vlib/v/gen/c/if.v
- vlib/v/tests/if_expr_with_sumtype_map_test.v
This PR fix if expr with sumtype value of map (fix #16427).
- Fix if expr with sumtype value of map.
- Add test.
```v
module main
type ConfigValue = bool | int | string
type ConfigMap = map[string]ConfigValue
fn foo(conf ConfigMap) bool {
mut bar := false
// Check type
bar = if conf['baz'] or { false } is bool {
conf['baz'] or { false } as bool
} else {
false
} // Default value
return bar
}
fn main() {
conf := {
'baz': ConfigValue(123)
}
ret := foo(conf)
println(ret)
assert !ret
}
false
```
> cgen: fix if expr with sumtype value of map (fix #16427)

- vlib/v/gen/c/dumpexpr.v
- vlib/v/tests/inout/dump_nil_voidptr.out
- vlib/v/tests/inout/dump_nil_voidptr.vv
1. Fix #16455
2. Add test.
```v
fn get_nil() ?&int {
return unsafe { nil }
}
fn get_voidptr() ?&int {
return voidptr(0)
}
fn main() {
mut a := get_nil()?
dump(a)
a = get_voidptr()?
dump(a)
}
```
output:
```
[vlib/v/tests/inout/dump_nil_voidptr.vv:11] a: &nil
[vlib/v/tests/inout/dump_nil_voidptr.vv:13] a: &nil
```
> cgen: fix dump(nil), dump(voidptr) (fix #16455)

- vlib/v/checker/assign.v
- vlib/v/checker/struct.v
- vlib/v/checker/tests/struct_field_unsign_type_check_err.out
- vlib/v/checker/tests/struct_field_unsign_type_check_err.vv
1. Fix #16457
2. Add test.
```v
struct Foo {
mut:
n u32 = -1
}
fn main() {
mut foo := Foo {
n: -1
}
foo.n = -1
}
```
output:
```
vlib/v/checker/tests/struct_field_unsign_type_check_err.vv:3:10: error: Cannot assign negative value to unsigned integer type
1 | struct Foo {
2 | mut:
3 |     n u32 = -1
|             ~~
4 | }
5 |
vlib/v/checker/tests/struct_field_unsign_type_check_err.vv:8:6: error: Cannot assign negative value to unsigned integer type
6 | fn main() {
7 |     mut foo := Foo{
8 |         n: -1
|            ~~
9 |     }
10 |
vlib/v/checker/tests/struct_field_unsign_type_check_err.vv:11:10: error: Cannot assign negative value to unsigned integer type
9 |     }
10 | 
11 |     foo.n = -1
|             ~~
12 | }
```
> checker: fix struct field unsigned type check (fix #16457)

- vlib/v/parser/if_match.v
- vlib/v/tests/inout/struct_field_optional.out
- vlib/v/tests/inout/struct_field_optional.vv
1. Fix #16460
2. Add test.
```v
struct Foo {
bar ?int = 1
baz ?int = none
}
fn main(){
f := Foo{}
if a := f.bar {
println(a)
} else {
println(err)
}
if a := f.baz {
println(a)
} else {
println(err)
}
}
```
output:
```
1
none
```
> parser: fix if-guard for struct optional fields (fix #16460)

- vlib/v/gen/c/cgen.v
Fixes https://github.com/vlang/v/issues/16418
> cgen: add escaping for `near`, `far` and `huge` keyword ptrs

- vlib/v/ast/str.v
- vlib/v/gen/c/match.v
- vlib/v/tests/inout/struct_field_optional.out
- vlib/v/tests/inout/struct_field_optional.vv
This PR fix match struct.field? {...}.
```v
struct Foo {
bar ?int = 1
baz ?int = none
}
fn main() {
f := Foo{}
match f.bar? {
1 {
println(1)
}
else {
}
}
}
```
output:
```
1
```
> ast, cgen: fix match struct.field? {...}

- vlib/v/gen/c/cgen.v
- vlib/v/tests/inout/struct_field_optional.out
- vlib/v/tests/inout/struct_field_optional.vv
1. Fix #16482
2. Add test.
```v
struct Foo {
a ?int
}
fn goo() ?Foo {
return Foo{}
}
fn main() {
println(goo()?.a?)
}
```
output:
```
0
```
> cgen: fix "fn()?.field?" expr cgen error (fix #16482)

- vlib/v/checker/check_types.v
This PR just removes code that is no longer needed (added in 0da827f 2021-04-04).
> checker: cleanup obsolete code for compatibility between byteptr and &byte

- vlib/v/checker/check_types.v
- vlib/v/checker/fn.v
- vlib/v/checker/struct.v
- vlib/v/checker/tests/generics_struct_init_type_parameter_err.out
- vlib/v/tests/generic_fn_with_short_generic_struct_init_syntax_test.v
This PR fix generic fn with short generic struct init syntax  (fix #16471).
- Fix generic fn with short generic struct init syntax.
- Add test.
```v
pub struct EncodeOptions<T> {
payload   T
key       string
algorithm string = 'HS256'
}
pub fn encode<T>(options EncodeOptions<T>) !string {
return 'test'
}
fn main() {
payload := {
'test': 'test'
}
ret := encode(payload: payload, key: 'test')!
println(ret)
assert ret == 'test'
}
test
```
> checker: fix generic fn with short generic struct init syntax  (fix #16471)

- vlib/v/checker/assign.v
- vlib/v/checker/check_types.v
- vlib/v/checker/checker.v
- vlib/v/checker/containers.v
- vlib/v/checker/fn.v
- vlib/v/checker/if.v
- vlib/v/checker/infix.v
- vlib/v/checker/interface.v
- vlib/v/checker/match.v
- vlib/v/checker/return.v
- vlib/v/checker/str.v
- vlib/v/checker/struct.v
This PR makes minor cleanup in checker module.
- Remove `pub` of most of the functions in checker module.
> checker: minor cleanup in checker module

- vlib/v/checker/assign.v
- vlib/v/checker/tests/assign_generic_fn_err.out
- vlib/v/checker/tests/assign_generic_fn_err.vv
This PR check assigning generic function to a variable (fix #16485).
- Check assigning generic function to a variable.
- Add test.
```v
fn main() {
fun := fn <T> (value T) T {
return value
}
println(fun<int>(100))
} 
./tt1.v:2:9: error: cannot assign generic function to a variable
2 |     fun := fn <T> (value T) T {
|            ~~~~~~~~~~~~~~~~~~~~
3 |         return value
4 |     }
./tt1.v:6:13: error: a non generic function called like a generic one
4 |     }
5 |
6 |     println(fun<int>(100))
|                ~~~~~
7 | }
```
> checker: check assigning generic function to a variable (fix #16485)

- vlib/toml/README.md
- vlib/toml/any.v
- vlib/toml/ast/ast.v
- vlib/toml/ast/types.v
- vlib/toml/ast/walker/walker.v
- vlib/toml/parser/parser.v
- vlib/toml/token/token.v
- vlib/toml/toml.v
- vlib/toml/util/util.v
- `v missdoc vlib/toml` now returns nothing
- Updated the signature of `value_opt` to be consistent for `Doc` and `Any`.
- Update usage in README.md
> toml: update value_opt syntax and add missing documentation

- vlib/v/gen/c/assign.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/testdata/comptime_optional_call.out
- vlib/v/gen/c/testdata/comptime_optional_call.vv
1. Fix #16499 
2. Fix #16465
3. Add test.
```v
struct Foo {
foobar int
bar    ?int
baz    ?int = none
}
fn (f Foo) bar() int {
return 1
}
fn (f Foo) baz() ?string {
return none
}
fn main() {
foo := Foo{}
$for field in Foo.fields {
var := foo.$(field.name)
println(var)
println(foo.$(field.name))
}
$for method in Foo.methods {
var := foo.$method()
println(var)
println(foo.$method())
}
}
```
output:
```
0
0
Option(0)
Option(0)
Option(error: none)
Option(error: none)
1
1
println(NIL)
Option(error: none)
```
-------
```v
struct Test {
a ?int = none
b ?int
}
fn fuba<U>(val U) {
println(val.$(field.name))
variable := val.$(field.name)
}
}
fn main() {
test := Test{}
fuba(test)
}
```
output:
```
Option(error: none)
Option(0)
```
> cgen: fix comptime optional methods call and optional field (fix #16499 #16465)

- vlib/v/gen/c/cgen.v
- vlib/v/tests/sumtype_with_alias_fntype_test.v
This PR fix sumtype with alias fntype variant (fix #16514).
- Fix sumtype with alias fntype variant.
- Add test.
```v
struct None {}
type Myfn = fn (int) int
type Myfnfact = fn () Myfn
type Maybefnfact = Myfnfact | None
// Myfn
fn abc(i int) int {
return i
}
fn run(mmff Maybefnfact) string {
match mmff {
Myfnfact { return 'yes fn' }
None { return 'None fn' }
}
}
fn main() {
// create Myfn
myfnfact := fn () Myfn {
return abc
}
r1 := main.myfnfact()(1)
println(r1)
assert r1 == 1
r2 := run(None{})
println(r2)
assert r2 == 'None fn'
r3 := run(myfnfact)
println(r3)
assert r3 == 'yes fn'
}
1
None fn
yes fn
```
> cgen: fix sumtype with alias fntype variant (fix #16514)

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/sumtype_with_alias_fntype_test.v
This PR fix fn call of sumtype with alias fntype variant (fix #16514).
- Fix fn call of sumtype with alias fntype variant.
- Add test.
```v
struct None {}
type Myfn = fn (int) int
type Myfnfact = fn () Myfn
type Maybefnfact = Myfnfact | None
// Myfn
fn abc(i int) int {
return i
}
// create Myfn
fn myfnfact() Myfn {
return abc
}
// run fn if exists
fn run(mmff Maybefnfact) string {
match mmff {
Myfnfact {
r := mmff()
return 'yes fn: ${r}'
}
None {
return 'None fn'
}
}
}
fn main() {
r1 := main.myfnfact()(1)
println(r1)
assert r1 == 1
r2 := run(None{})
println(r2)
assert r2 == 'None fn'
r3 := run(myfnfact)
println(r3)
assert r3 == 'yes fn: fn (int) int'
}
1
None fn
yes fn: fn (int) int
```
> cgen: fix fn call of sumtype with alias fntype variant (fix #16514)

- vlib/v/checker/check_types.v
- vlib/v/checker/struct.v
This PR perfect infer_struct_generic_types().
- Change `infer_generic_struct_init_concrete_types()` to `infer_struct_generic_types()`.
- Add `.function` processing.
> checker: perfect infer_struct_generic_types()

- vlib/v/parser/fn.v
- vlib/v/parser/parse_type.v
- vlib/v/parser/parser.v
- vlib/v/parser/struct.v
This PR replace generic `<>` with `[]` part 1.
- Add `[]` in addition to `<>`.
```v
struct Tuple[K, V] {
a K
b V
}
// map to array of key-value tuples
fn map_to_array[K, V](m map[K]V) []Tuple[K, V] {
mut r := []Tuple[K, V]{cap: m.len}
r << Tuple[K, V]{k, v}
}
return r
}
fn main() {
x := {
'one': 1
'two': 2
}
println(x)
println(map_to_array(x))
}
{'one': 1, 'two': 2}
[Tuple<string, int>{
a: 'one'
b: 1
}, Tuple<string, int>{
a: 'two'
b: 2
}]
```
> generic: replace generic `<>` with `[]` part 1

- vlib/v/checker/fn.v
- vlib/v/checker/tests/check_fn_init_as_mutable.out
- vlib/v/checker/tests/check_fn_init_as_mutable.vv
- vlib/v/checker/tests/pass_mut_lit.out
This commit improves the error message that v provides, to make the error more user-friendly for users that are not familiar with how `mut` works.
With the following code
```v
struct MyStruct {}
fn process(mut ms MyStruct) {}
fn main() {
process(mut MyStruct{})
}
```
produce the following error
```
test.v:6:14: error: cannot pass a struct initialization as `mut`, you may want to use a variable `mut var := MyStruct{....}`
4 |
6 |     process(mut MyStruct{})
|                 ~~~~~~~~~~
7 | }
```
Instead of this generic one
```
code.v:4:13: error: cannot pass expression as `mut`
2 | struct MyStruct {}
3 | fn process(mut ms MyStruct) {}
4 | process(mut MyStruct{})
|             ~~~~~~~~~~
Exited with error status 1
```
Fixes https://github.com/vlang/v/issues/16535
> checker: improve error msg

- vlib/datatypes/fsm/fsm.v
- vlib/datatypes/fsm/fsm_test.v
- vlib/datatypes/fsm/tools/fsm_graph.v
This PR fix fsm.set_state() and cleanup fsm module.
> datatypes: fix fsm.set_state() and cleanup fsm module

- vlib/v/checker/return.v
- vlib/v/tests/option_void_2_test.v
This PR fix `return none` in void optional function (fix #16544).
- Fix `return none` in void optional function.
- Add test.
```v
fn main() {
foo(22)?
assert true
}
fn foo(n int) ? {
if n > 0 {
println(n)
} else {
return none
}
}
22
```
> checker: fix `return none` in void optional function (fix #16544)

- vlib/v/gen/c/infix.v
- vlib/v/tests/match_expr_in_infix_expr_test.v
- vlib/v/tests/valgrind/match_expr.v
This PR fix error of match expr (fix #16554).
- Fix error of match expr.
- Add test.
```v
fn main() {
mut a := true
b := a && match true {
true {
a = false
true
}
false {
false
}
}
println(a)
assert a == false
println(b)
assert b == true
}
false
true
```
> cgen: fix error of match expr (fix #16554)

- vlib/gg/image.c.v
- vlib/stbi/stbi.c.v
Fixes vlang/vab#239
Will probably obsolete #16561
At some point `init_sokol_image()` was changed to use the number of channels detected by stbi instead of the hardcoded `4`. While this should've been a good idea, and the most logical thing to do - reality is a little different. [sokol_gl expects `.rgba8`/4 channels](https://github.com/floooh/sokol/blob/7cf434a922fe1bab285db96bf792f647b83314f7/util/sokol_gl.h#L3195) in it's default contexts, which `gg` currently also uses when loading images. This PR set the number of channels back where it came from and leaves a more juicy note for next time :)
I don't think it's a good idea to manipulate the channel number like this in unexpected places:
https://github.com/vlang/v/pull/15981/files#diff-3566edbb636a40b3c608bb8b51fb2403f57929e1626e96f39ccb7 …
> gg: always use 4 channels in init_sokol_image

- vlib/v/checker/struct.v
- vlib/v/checker/tests/struct_init_update_type_err.out
- vlib/v/checker/tests/struct_init_update_type_err.vv
Fixes #16565
This now works:
```v
struct Foo {}
type FooAlias{}
fn main() {
foo := FooAlias{}
bar := FooAlias{
...foo // <-- previously a compiler error: expected struct, found `FooAlias`
}
}
```
> checker: allow struct updates from struct aliases

- cmd/tools/vast/vast.v
- vlib/datatypes/doubly_linked_list.v
- vlib/datatypes/linked_list.v
- vlib/datatypes/set.v
- vlib/os/os_test.v
- vlib/v/ast/table.v
- vlib/v/checker/check_types.v
- vlib/v/checker/checker.v
- vlib/v/checker/containers.v
- vlib/v/checker/fn.v
- vlib/v/checker/interface.v
- vlib/v/checker/tests/array_of_generic_struct_init_err.out
- vlib/v/checker/tests/generic_closure_fn_decl_err.out
- vlib/v/checker/tests/generic_fn_decl_err.out
- vlib/v/checker/tests/generic_fn_decl_without_generic_names_err.out
- vlib/v/checker/tests/generic_interface_missing_type_names_err.out
- vlib/v/checker/tests/generic_sumtype_decl_err_a.out
- vlib/v/checker/tests/generic_sumtype_decl_err_b.out
- vlib/v/checker/tests/generics_fn_arg_type_err.out
- vlib/v/checker/tests/generics_fn_called_no_arg_err.out
- vlib/v/checker/tests/generics_fn_return_generic_struct_err.out
- vlib/v/checker/tests/generics_interface_declaration_err.out
- vlib/v/checker/tests/generics_method_receiver_type_err.out
- vlib/v/checker/tests/map_of_generic_struct_init_err.out
- vlib/v/gen/golang/golang.v
- vlib/v/parser/fn.v
- vlib/v/tests/fn_variadic_test.v
- vlib/v/tests/generics_test.v
This PR replace generic '<>' with '[]' in error messages.
> generic: replace generic '<>' with '[]' in error messages

- vlib/term/colors.v
I was going to implement this method in my color.v library for efficent tag rendering, but i decided it would be better to add here
> term: add format_esc

- cmd/tools/vcomplete.v
This PR fixes return values from `v complete <SHELL> v /path/to/dir-containing-only-one-file/`
Previously it would return only the filename e.g. `v file.v` - after this PR it now keep the path it was completing and return it with the filname: `v /path/to/dir-containing-only-one-file/file.v`.
Related: #16587
> tools: fix vcompletion for single-file directories

- vlib/v/checker/checker.v
- vlib/v/checker/struct.v
- vlib/v/checker/tests/generics_interface_field_type_err.out
- vlib/v/checker/tests/generics_interface_field_type_err.vv
- vlib/v/checker/tests/generics_struct_field_type_err.out
This PR check generic interface type specifing type names (fix #16576).
- Check generic interface type specifing type names.
- Add test.
```v
module main
pub struct Entity {
pub:
id u16
}
pub struct Position {  // other components ie Velocity
pub mut:
x f64
y f64
z f64
}
pub interface IComponentStore<T> {
mut:
add(Entity, T)
}
pub struct ComponentStore<T> {
pub mut:
typ string
// data etc
}
pub fn (mut cs ComponentStore<T>) add(e Entity, value T) {
//	index := cs.set.add(e.id)
//	cs.instances[index] = value
}
[heap]
struct Registry {
pub mut:
data map[string]IComponentStore
}
pub fn registry() &Registry {
mut r := &Registry {
data: map[string]IComponentStore{}
}
return r
}
fn main() {
}
tt1.v:34:18: error: `IComponentStore` type is generic interface, must specify …
```
> checker: check generic interface type specifing type names (fix #16576)

- vlib/v/gen/c/array.v
- vlib/v/gen/c/if.v
- vlib/v/tests/if_expr_with_multi_array_call_test.v
This PR fix if expr with multiple array call (fix #16583).
- Fix if expr with multiple array call.
- Add test.
```v
fn main() {
ret := foo()
println(ret)
assert ret == 'all'
}
fn foo() string {
x := [3, 4]
y := [2, 3, 4, 5]
if x.all(it in y) || y.all(it in x) {
return 'all'
} else if x.any(it in y) {
return 'any'
}
return ''
}
all
```
> cgen: fix if expr with multiple array call (fix #16583)

- vlib/v/checker/checker.v
- vlib/v/tests/or_expr_with_comptime_test.v
Fix for #16538 bug
```
fn foo() ! {
}
foo() or {
$if linux {
}
}
```
> checker: fix panic caused by compile-time code within or block

- vlib/regex/regex.v
- vlib/v/gen/c/array.v
- vlib/v/tests/array_init_with_fields_test.v
This PR fix array init with fields (fix #16596).
- Fix array init with fields.
- Add test.
```v
struct Fluid[T] {
mut:
elements  datatypes.Queue[T]
switch    bool // 0 by default
selements datatypes.Stack[T]
}
fn (mut fluid Fluid[T]) push(item T) {
if fluid.switch {
fluid.selements.push(item)
} else {
fluid.elements.push(item)
}
}
fn (mut fluid Fluid[T]) pop() !T {
if fluid.switch {
return fluid.selements.pop()!
} else {
return fluid.elements.pop()!
}
}
fn (fluid Fluid[T]) str() string {
if fluid.switch {
return fluid.selements.str()
} else {
return fluid.elements.str()
}
}
fn (fluid Fluid[T]) peek() !T {
if fluid.switch {
return fluid.selements.peek()!
} else {
return fluid.elements.peek()!
}
}
// this function converts queue to stack
fn (mut fluid Fluid[T]) to_stack() …
```
> cgen: fix array init with fields (fix #16596)

- vlib/v/checker/tests/generics_interface_decl_no_mention_err.out
- vlib/v/checker/tests/generics_interface_decl_no_mention_err.vv
- vlib/v/parser/struct.v
This PR fix parsing embedded generic interface using '[]'.
> parser: fix parsing embedded generic interface using '[]'

- vlib/v/gen/c/auto_str_methods.v
- vlib/v/tests/string_map_with_generic_struct_value_test.v
This PR fix string of map with generic struct value (fix #16594).
- Fix string of map with generic struct value.
- Add test.
```v
fn main() {
p := map[string]datatypes.Stack[int]{}
println(p)
assert '${p}' == '{}'
}
{}
```
> cgen: fix string of map with generic struct value (fix #16594)

- vlib/v/checker/tests/assign_generic_fn_err.out
- vlib/v/checker/tests/assign_generic_fn_err.vv
- vlib/v/parser/fn.v
This PR fix parsing generic types using '[]' in anon fn decl.
> parser: fix parsing generic types using '[]' in anon fn decl

- vlib/v/checker/checker.v
- vlib/v/checker/struct.v
- vlib/v/checker/tests/check_incompatible_struct.out
- vlib/v/checker/tests/check_incompatible_struct.vv
Fixes #16608 bug
```
struct Foo {
b int
}
struct Bar {
a int
b int
}
fn main() {
foo := Foo{2}
bar2 := Bar{...foo a: 1}
bar3 := Bar{...foo b: 1}
bar4 := Bar{...foo b: 1 a: 2}
bar := Bar{...foo}
print(bar)
print(bar2)
print(bar3)
print(bar4)
}
```
As long Foo and Bar has 'b' field, the 'a' field on Bar was not taken in count when checking both.
> checker: Fix incompatible struct checking

- vlib/v/checker/tests/globals_run/global_nested_struct_test.vv
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/struct.v
Fixes issue #16528
```
pub struct Foo {
val Bar
}
pub struct Bar {
number int
}
[cinit]
__global (
baz = Foo{Bar{number: 5}}
)
fn main() {
print(baz)
}
```
> cgen: Fix nested struct generation for gcc

- vlib/arrays/arrays_test.v
- vlib/arrays/index_of.v
- vlib/arrays/map_of.v
Examples:
```v
import arrays
assert arrays.map_of_indexes([1,2,3,4,4,2,1,4,4,999]) == {1: [0, 6], 2: [1, 5], 3: [2], 4: [3, 4, 7, 8], 999: [9]}
assert arrays.map_of_counts([1,2,3,4,4,2,1,4,4]) == {1: 2, 2: 2, 3: 1, 4: 4}
assert arrays.index_of_first([4,5,0,7,0,9], fn(idx int, x int) bool { return x == 0 }) == 2
assert arrays.index_of_last([4,5,0,7,0,9], fn(idx int, x int) bool { return x == 0 }) == 4
```
> arrays: add map_of_counts/1, map_of_indexes/1 as well as index_of_first/2, index_of_last/2 utilities

- vlib/builtin/string.v
- When checking out V for my first time, I tried running `println(os.user_names()!)`. I expected an array of all the users on the system to be printed, but instead `'] 'WDAGUtilityAccount` was printed. After a lot of digging, I found the culprit to be that the output of the WMI command `os.user_names()` run on Windows has line ends consisting of `\r\r\n` instead of the standard `\r\n`
- Seems that this is an issue that occurs in lot of Windows programs
- I fixed this by replacing the check for a single `\r` at the end of each string with `trim_right('\r')` that removes every `\r` at the end of each string
> string: Fix bug with split_into_lines when strings have extra CR's

- vlib/v/gen/c/match.v
- vlib/v/tests/match_expr_skip_in_infix_expr_test.v
This PR fix error of match c generation (fix #16554).
- #16555 is not complete enough.
- Fix it completely.
generated c codes:
```v
bool a = true;
bool _t1 = (a);
bool _t2 = true;
bool _t3 = 0;
if (_t1) {
if (_t2 == (true)) {
a = false;
_t3 = true;
}
else if (_t2 == (false)) {
_t3 = false;
}
}
bool b = _t1 && _t3;
println(a ? _SLIT("true") : _SLIT("false"));
println(b ? _SLIT("true") : _SLIT("false"));
}
```
```v
fn test_match_expr_skip_in_infix_expr_1() {
mut a := false
b := a && match true {
true {
a = true
true
}
false {
false
}
}
println(a)
assert a == false
println(b)
assert b == false
}
fn test_match_expr_skip_in_infix_expr_2() {
mut a := true
b := a || match true {
true {
a = false
true
}
false {
false
}
}
println(a)
assert a == true …
```
> cgen: fix error of match c generation (fix #16554)

- vlib/v/gen/c/cgen.v
- vlib/v/tests/fn_return_typeof_test.v
Fixes the following bug (#16611):
```
fn bar[T]() string {
return typeof[T]()
}
print(bar[int]()) // 'T' instead of 'int'
```
> cgen: fix typeof[T]() return

- cmd/tools/vtest-self.v
- vlib/orm/orm.v
- vlib/v/tests/fn_literal_type_test.v
Fix #16579 bug
```
const (
const_users_offset = 5
const_users_offset2 = 5.2
)
```
> orm: declare missing functions to handle literal types

- .github/ISSUE_TEMPLATE/bug-report.yml
Environment field suggests using `v doctor`, but only gave a single line input field.
This changes the field to a textarea to accommodate full `v doctor` output.
> github: change bug template Envionment field to textarea

- vlib/v/checker/fn.v
- vlib/v/tests/generics_fn_return_result_test.v
This PR fix generic fn returning result (fix #16644).
- Fix generic fn returning result.
- Add test.
```v
fn make_2x3[T](mut res [][]T) ! {
mut a := []T{len: 6}
res = reshape(a, [2, 3])!
}
fn reshape[T](y []T, dims []int) ![][]T {
mut res := [][]T{len: dims[0], init: []T{len: 1}}
return res
}
fn main() {
mut acopy := [][]f32{len: 1, init: []f32{len: 1}}
make_2x3(mut acopy)!
dump(acopy)
assert '${acopy}' == '[[0.0], [0.0]]'
mut bcopy := [][]u8{len: 1, init: []u8{len: 1}}
make_2x3(mut bcopy)!
dump(bcopy)
assert '${bcopy}' == '[[0], [0]]'
}
[.\\tt1.v:14] acopy: [[0.0], [0.0]]
[.\\tt1.v:18] bcopy: [[0], [0]]
```
> checker: fix generic fn returning result (fix #16644)

- vlib/v/parser/containers.v
- vlib/v/tests/option_init_test.v
Fix bug #16651
```
struct Cell {}
fn main() {
dump([]?Cell{len:1})
}
```
After patching produces:
```
[test.v:3] []T{len: 1}: [Option(Cell{})]
```
> parser: fix initializing option type syntax

- vlib/v/checker/fn.v
- vlib/v/checker/tests/incorrect_smartcast3_err.out
- vlib/v/checker/tests/incorrect_smartcast3_err.vv
This PR check smartcasting requires either an immutable value, or anexplicit mut keyword before the value (fix #16624).
- Check smartcasting requires either an immutable value, or anexplicit mut keyword before the value.
- Add test.
```v
module main
import regex { RE, regex_opt }
pub struct EmptyRegex {
}
type OurRegex = EmptyRegex | RE
pub struct ListArgs {
pub mut:
regex OurRegex
}
fn main() {
query := r'(c(pa)+z ?)+'
mut re := regex_opt(query) or { panic(err) }
item := 'sss'
mut la := ListArgs{
regex: re
}
mut r := la.regex
if r is RE {
println(r)
println(r.matches_string(item))
}
match r {
RE { r.matches_string(item) }
else {}
}
}
tt1.v:25:5: notice: smartcasting requires either an immutable value, or an explicit mut keyword before the value
23 |
24 |     mut …
```
> checker: check smartcasting requires either an immutable value, or anexplicit mut keyword before the value (fix #16624)

- vlib/builtin/array.v
- vlib/builtin/array_notd_gcboehm_opt.v
- vlib/v/gen/c/array.v
- vlib/v/tests/array_init_element_size_equal_array_size_test.v
This PR fix array init with array default (fix #16662).
- Fix array init with array default.
- Add test.
```v
import math
struct Cell {
p_i int
p_j int
f   f64 = math.max_f64
g   f64 = math.max_f64
h   f64 = math.max_f64
}
fn main() {
mut cells := [][]Cell{len: 1, init: []Cell{len: 1}}
println(cells)
assert '${cells[0][0].p_i}' == '0'
assert '${cells[0][0].p_j}' == '0'
assert '${cells[0][0].f}' == '1.7976931348623157e+308'
assert '${cells[0][0].g}' == '1.7976931348623157e+308'
assert '${cells[0][0].h}' == '1.7976931348623157e+308'
}
[[Cell{
p_i: 0
p_j: 0
f: 1.7976931348623157e+308
g: 1.7976931348623157e+308
h: 1.7976931348623157e+308
}]]
```
> builtin: fix array init with array default (fix #16662)

- vlib/encoding/html/escape.v
- vlib/encoding/html/escape_test.v
- vlib/vweb/vweb.v
Adds `html.escape` which is useful for translating input text to HTML-safe strings. Common usecase is to sanitize form inputs and prevent XSS attacks.
It also replaces the default escaping mechanism used in vweb.
> encoding.html: add escape() function

- vlib/builtin/array.v
- vlib/builtin/array_flags_test.v
The `.nogrow` array flag and `.nofree` flags were implemented to serve the purpose of specific manually allocated regions of memory.
```v
mut a := unsafe {
array {
element_size: 1
data: C.mmap(...)
cap: ...
flags: .noshrink | .nogrow | .nofree
}
}
```
On the freeing of the array, if `.nofree` flag is set the libc `free()` function will not be called on `.data` and would simply return.
Using the `.nogrow` and `.noshrink` flags in tandem will allow the a heap allocated array to behave like a fixed one.
```v
mut a := []u64{cap: 100}
unsafe { a.flags.set(.nogrow | .noshrink) }
```
[Related conversation on the V discord.](https://discord.com/channels/592103645835821068/592294828432424960/1052064181500780604)
> builtin: `.nogrow` and `.nofree` flags in array

- vlib/x/json2/README.md
> The name `json2` was chosen to avoid any unwanted potential conflicts with the
> existing codegen tailored for the main `json` module which is powered by CJSON.
`x.json2` is an experimental JSON parser written from scratch on V.
```v
import x.json2
import time
mut:
age      ?int = 20
birthday time.Time
deathday ?time.Time = none
}
fn main() {
mut person := Person{
name: 'Bob'
birthday: time.now()
}
person_json := json2.encode[Person](person)
// person_json == {"name": "Bob", "age": 20, "birthday": "2022-03-11T13:54:25.000Z"}
}
```
```v
import x.json2
import time
mut:
age      ?int = 20
birthday time.Time
deathday ?time.Time = none
}
fn main() {
resp := '{"name": "Bob", "age": 20, "birthday": ${time.now()}}'
person := …
```
> doc: update json2

- vlib/v/checker/comptime.v
- vlib/v/checker/tests/comptime_dump_fields_var_test.out
- vlib/v/checker/tests/comptime_dump_fields_var_test.vv
- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/dumpexpr.v
Fix #16631
Fix #16489
```V
module main
struct Foo{
a string 
b ?string
c int
d ?int
e struct {
i ?int
}
}
fn sei_oq_la[T](val T){
$for field in T.fields { dump(val.$(field.name)) }
}
fn main(){
foo := Foo{"c","d", 1, 0, struct {100}}
sei_oq_la(foo)
}
```
> Fix dump when using comptime variable val.${field.name}

- vlib/builtin/array_d_gcboehm_opt.v
[This is a follow up to a earlier PR.](https://github.com/vlang/v/pull/16661)
V contains separate array definitions in the `array_d_gcboehm_opt.v`, different to the main `array.v` file in the builtin library.
The array implementation specific to the boehm GC did not contain the changes needed to make use of the `.nogrow` array flag. This PR adds them in so that the programs compiled with and without the boehm GC are equivalent to ones without it.
This is a bugfix and should be applied relatively quickly.
> builtin: apply `.nogrow` flags to gcboehm array

- vlib/v/checker/tests/comptime_if_optional_string_test.out
- vlib/v/checker/tests/comptime_if_optional_string_test.vv
- vlib/v/gen/c/comptime.v
Fix #16630
```V
module main
struct Foo{
a string 
b ?string
}
fn main(){
$for field in Foo.fields {
dump(field.name)
$if field.typ is ?string {
dump(1)
} $else $if field.typ is string {
dump(2)
}
}
}
```
> cgen: Fix comptime checking optional type with IS operator

- vlib/v/ast/table.v
- vlib/v/ast/types.v
- vlib/v/parser/parse_type.v
- vlib/v/tests/generics_struct_init_with_inconsistent_generic_types_3_test.v
This PR fix generic struct init with inconsistent generic types (fix #16668).
- Fix generic struct init with inconsistent generic types.
- Add test.
```v
module main
pub struct Maybe[T] {
present bool
val     T
}
pub fn some[T](t T) Maybe[T] {
return Maybe[T]{true, t}
}
pub fn (me Maybe[T]) map[T, U](f fn (T) U) Maybe[U] {
if me.present {
return Maybe[U]{true, f(me.val)}
}
return Maybe[U]{}
}
pub fn (o Maybe[T]) get() ?T {
if o.present {
return o.val
} else {
return none
}
}
fn main() {
m := some[int](12)
ret := m.map[int, string](fn (i int) string {
return i.str()
})
println(ret)
assert ret.val == '12'
}
Maybe[string]{
present: true
val: '12'
}
```
> ast, parser: fix generic struct init with inconsistent generic types (fix #16668)

- vlib/v/gen/c/cgen.v
- vlib/v/tests/struct_selector_or_block_test.v
Fix #16581
```V
module main
interface Greeting {
tt ?string
}
struct Hello {
tt    ?string = none
value string
}
struct Hi {
tt ?string = none
}
fn greet(g Greeting) string {
// Problematic piece of code here
// If I leave it unchecked, the compiler complains (as expected)
t := g.tt or { 'UNKNOWN' }
return t
}
assert greet(Hello{}) == 'UNKNOWN'
assert greet(Hello{'cool', ''}) == 'cool'
}
```
> cgen: Fix struct selector with or block

- vlib/v/ast/table.v
- vlib/v/checker/struct.v
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/c/cgen.v
- vlib/v/parser/parse_type.v
- vlib/v/tests/generics_struct_init_with_inconsistent_generic_types_4_test.v
This PR fix generic struct init with inconsistent generic types (fix #16677).
- Fix generic struct init with inconsistent generic types.
- Add test.
```v
struct Tuple1[A] {
a A
}
a A
b B
}
struct Tuple3[A, B, X] { // note: "C" is reserved for C language...
a A
b B
c X
}
// map to array of key tuples
fn map_to_array1_k[K, V](m map[K]V) []Tuple1[K] {
mut r := []Tuple1[K]{cap: m.len}
for k, _ in m {
r << Tuple1[K]{k}
}
return r
}
// map to array of value tuples
fn map_to_array1_v[K, V](m map[K]V) []Tuple1[V] {
mut r := []Tuple1[V]{cap: m.len}
for _, v in m {
r << Tuple1[V]{v}
}
return r
}
// map to array of key-value tuples
fn map_to_array2_k_v[K, V](m map[K]V) []Tuple2[K, V] {
mut r := []Tuple2[K, V]{cap: m.len}
r << Tuple2[K, V]{k, v}
}
return r
}
// …
```
> cgen: fix generic struct init with inconsistent generic types (fix #16677)

- vlib/v/gen/c/cgen.v
Remove repeated conditional code
```diff
+[inline]
+fn (mut g Gen) get_type(typ ast.Type) ast.Type {
+       return if typ == g.field_data_type { g.comptime_for_field_value.typ } else { typ }
+}
-       typ := if raw_type == g.field_data_type { g.comptime_for_field_value.typ } else { raw_type }
+       typ := g.get_type(raw_type)
```
> cgen: remove repeated code

- vlib/rand/xoroshiro128pp/xoros128pp.v
- vlib/rand/xoroshiro128pp/xoros128pp_test.v
This is a fast PRNG useful for signed/unsigned ints and for floating point conversions.  A smaller footprint than xoroshiro256++ (a smaller state vector), otherwise seems to be equivalent (according to the paper published with the code.)
This is a cut and paste and edit from pcg32 so apologies if I missed something in the doc.
> add Blackman/Vigna xoroshiro128++ PRNG

- vlib/v/checker/fn.v
- vlib/v/checker/tests/method_op_alias_err.out
- vlib/v/checker/tests/overload_operator_difference_in_operand_types.out
- vlib/v/checker/tests/overload_operator_difference_in_operand_types.vv
- vlib/v/gen/c/infix.v
- vlib/v/tests/operator_overloading_with_reference_operands_test.v
Also disallow differences in operand types for overloaded operators
for now (Type vs &Type), which simplifies cgen a lot.
> cgen: fix cgen errors for overloaded operators using reference types for the receiver and operand (fix #16725) (fix #15859)

- vlib/v/ast/table.v
- vlib/v/parser/parse_type.v
- vlib/v/parser/tests/generic_struct_parameter_err.out
- vlib/v/parser/tests/generic_struct_receiver_nested_generic_err.out
- vlib/v/parser/tests/generic_struct_receiver_nested_generic_err.vv
- vlib/v/tests/generics_struct_init_with_inconsistent_generic_types_5_test.v
This PR fix generic struct init with nested generic struct (fix #16709).
- Fix generic struct init with nested generic struct.
- Add test.
```v
a A
b B
}
// map to array of Tuple2[int, Tuple2[key, value]] tuples
fn map_to_array_int_kv[K, V](m map[K]V) []Tuple2[int, Tuple2[K, V]] {
mut r := []Tuple2[int, Tuple2[K, V]]{cap: m.len}
mut i := 0
r << Tuple2[int, Tuple2[K, V]]{i, Tuple2[K, V]{k, v}}
i += 1
}
return r
}
// map to array of Tuple2[int, Tuple2[Tuple2[key, value], Tuple2[value, key]]] tuples
fn map_to_array_int_kv_vk[K, V](m map[K]V) []Tuple2[int, Tuple2[Tuple2[K, V], Tuple2[V, K]]] {
mut r := []Tuple2[int, Tuple2[Tuple2[K, V], Tuple2[V, K]]]{cap: m.len}
mut i := 0
r << Tuple2[int, Tuple2[Tuple2[K, V], Tuple2[V, K]]]{i, …
```
> ast, parser: fix generic struct init with nested generic struct (fix #16709)

- vlib/v/checker/match.v
- vlib/v/checker/tests/match_expr_non_void_stmt_last.out
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/if.v
- vlib/v/gen/c/match.v
- vlib/v/tests/match_expr_with_branch_returning_1_test.v
- vlib/v/tests/match_expr_with_branch_returning_2_test.v
This PR fix match expr with branch returning (fix #16696).
- Fix match expr with branch returning.
- Add test.
```v
fn foo() ! {
a := match true {
true {
2
}
2 == 2 {
return error('hello')
}
else {
0
}
}
println(a)
assert a == 2
}
fn main() {
foo()!
}
2
```
> checker, cgen: fix match expr with branch returning (fix #16696)

- vlib/builtin/builtin_nix.c.v
- vlib/v/gen/c/cheaders.v
On latest Alpine, `libexecinfo-dev` and the file `execinfo.h` are not
easily available anymore.
This makes V programs buildable on latest Alpine, with the prebuild tcc,
without having to install `libexecinfo-dev` from external sources.
> cgen: improve generated source compatibility with latest Alpine (lacking libexecinfo-dev and execinfo.h) and the prebuilt tcc

- vlib/builtin/map.v
- vlib/builtin/map_test.v
This PR fix map.clear() (fix #16711).
- Fix map.clear().
- Add test.
```v
struct State {
mut:
state map[string]rune
}
struct Foo {
bar int
baz int
}
fn (mut st State) add(s string, r rune) {
st.state[s] = r
}
fn (mut st State) add2(foos []Foo) {
for f in foos {
st.state['${f.bar},${f.baz}'] = `z`
}
}
fn (mut st State) reset() {
st.state.clear()
}
fn main() {
mut s := State{}
item1 := [Foo{
bar: 1
baz: 2
}, Foo{
bar: 3
baz: 4
}]
s.add2(item1)
println(s)
assert s.state.len == 2
s.reset()
println(s)
s.add2(item1)
println(s)
assert s.state.len == 2
}
State{
state: {'1,2': `z`, '3,4': `z`}
}
State{
state: {}
}
State{
state: {'1,2': `z`, '3,4': `z`}
}
```
> builtin: fix map.clear() (fix #16711)

- vlib/arrays/arrays_test.v
- vlib/builtin/array.v
- vlib/builtin/builtin.c.v
- vlib/builtin/map.v
- vlib/builtin/map_d_gcboehm_opt.v
- vlib/v/gen/c/array.v
- vlib/v/gen/c/cheaders.v
- vlib/v/tests/arrays_and_maps_of_empty_structs_should_work_test.v
- vlib/v/tests/empty_struct_test.v
Instead of sizeof(EmptyStruct) == 8, now it is 1 for msvc and tcc, and 0 otherwise.
Note: MSVC does not allow for completely empty structs, so there is still a 1 byte padding in its case.
TCC now *does allow for empty structs, in most cases*, except when they are used in an array or another context that may require taking their address. A failing example is trying to compile `cmd/tools/vgret.v` which uses `toml`, which in turn has toml.Null declared as an empty struct and `pub const null = Any(Null{})` with EMPTY_STRUCT_INITIALIZATION and EMPTY_STRUCT_DECLARATION being set to ''.
```v
struct Z0 {}
struct Z1 { padding1 char}
struct Z2 { padding1 char padding2 char}
struct Z3 { padding1 char padding2 char padding3 char}
struct Z4 { padding1 char padding2 char padding3 char padding4 char}
fn …
```
> cgen: minimise `sizeof(EmptyStruct)` by changing EMPTY_STRUCT_DECLARATION and EMPTY_STRUCT_INITIALIZATION

- vlib/v/gen/c/fn.v
- vlib/v/tests/sumtype_on_match_test.v
Fix #16742
On V code like:
```V
e := Event(be) // type Event = MotionEvent | ButtonEvent | WheelEvent
match e {
MotionEvent {
handle_game_event(e)
}
ButtonEvent {
handle_game_event(e)
}
else {}
}
```
It was generating:
```C
if (e._typ == 94 /* main.MotionEvent */) {
main__handle_game_event((*e._main__MotionEvent));
}
else if (e._typ == 95 /* main.ButtonEvent */) {
main__handle_game_event((*e._main__ButtonEvent));
}
```
instead of 
```C
if (e._typ == 94 /* main.MotionEvent */) {
main__handle_game_event(main__MotionEvent_to_sumtype_main__GameEvent(&(*e._main__MotionEvent)));
}
else if (e._typ == 95 /* main.ButtonEvent */) {
main__handle_game_event(main__ButtonEvent_to_sumtype_main__GameEvent(&(*e._main__ButtonEvent)));
}
```
> cgen: fix call arg type changing on match expr

- vlib/v/ast/types.v
- vlib/v/parser/parse_type.v
- vlib/v/tests/generics_struct_init_with_inconsistent_generic_types_5_test.v
This PR fix wrong type name of nested generics  (fix #16745).
- Fix wrong type name of nested generics.
- Add test.
```v
a A
b B
}
// map to array of Tuple2[int, Tuple2[key, value]] tuples
fn map_to_array_int_kv[K, V](m map[K]V) []Tuple2[int, Tuple2[K, V]] {
mut r := []Tuple2[int, Tuple2[K, V]]{cap: m.len}
mut i := 0
r << Tuple2[int, Tuple2[K, V]]{i, Tuple2[K, V]{k, v}}
i += 1
}
return r
}
// map to array of Tuple2[int, Tuple2[Tuple2[key, value], Tuple2[value, key]]] tuples
fn map_to_array_int_kv_vk[K, V](m map[K]V) []Tuple2[int, Tuple2[Tuple2[K, V], Tuple2[V, K]]] {
mut r := []Tuple2[int, Tuple2[Tuple2[K, V], Tuple2[V, K]]]{cap: m.len}
mut i := 0
r << Tuple2[int, Tuple2[Tuple2[K, V], Tuple2[V, K]]]{i, Tuple2[Tuple2[K, V], Tuple2[V, …
```
> ast, parser: fix wrong type name of nested generics  (fix #16745)

- vlib/builtin/linux_bare/linux_syscalls.v
- vlib/math/big/big_test.v
- vlib/os/file_test.v
- vlib/v/checker/check_types.v
- vlib/v/checker/tests/int_signess_call_arg_test.out
- vlib/v/checker/tests/int_signess_call_arg_test.vv
Fix #9753
```V
fn main(){
test(-1)
test2(-1)
test3(-1)
test4(-1)
test5(-1)
}
fn test(len u64){println(len)}
fn test2(len u8){println(len)}
fn test3(len u16){println(len)}
fn test4(len u32){println(len)}
fn test5(len usize){println(len)}
```
Expected:
```
test.v:3:7: error: cannot use literal signed integer as `u64` in argument 1 to `test`
1 |
2 | fn main(){
3 |     test(-1)
|          ~~
4 |     test2(-1)
5 |     test3(-1)
test.v:4:8: error: cannot use literal signed integer as `u8` in argument 1 to `test2`
2 | fn main(){
3 |     test(-1)
4 |     test2(-1)
|           ~~
5 |     test3(-1)
6 |     test4(-1)
test.v:5:8: error: cannot use literal signed integer as `u16` in argument 1 to `test3`
3 |     test(-1)
4 |     test2(-1)
5 |     test3(-1)
|           ~~
6 |     test4(-1)
7 | …
```
> checker: add int signess mismatch checking

- vlib/v/ast/types.v
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/tests/inout/printing_nested_generic_struct.out
- vlib/v/tests/inout/printing_nested_generic_struct.vv
- vlib/v/tests/printing_c_structs/string_interpolation_test.v
- vlib/v/tests/str_gen_test.v
This PR fix printing nested generic struct.
- Fix printing nested generic struct.
- Add test.
```v
a A
b B
}
// map to array of Tuple2[int, Tuple2[key, value]] tuples
fn map_to_array_int_kv[K, V](m map[K]V) []Tuple2[int, Tuple2[K, V]] {
mut r := []Tuple2[int, Tuple2[K, V]]{cap: m.len}
mut i := 0
r << Tuple2[int, Tuple2[K, V]]{i, Tuple2[K, V]{k, v}}
i += 1
}
return r
}
// map to array of Tuple2[int, Tuple2[Tuple2[key, value], Tuple2[value, key]]] tuples
fn map_to_array_int_kv_vk[K, V](m map[K]V) []Tuple2[int, Tuple2[Tuple2[K, V], Tuple2[V, K]]] {
mut r := []Tuple2[int, Tuple2[Tuple2[K, V], Tuple2[V, K]]]{cap: m.len}
mut i := 0
r << Tuple2[int, Tuple2[Tuple2[K, V], Tuple2[V, K]]]{i, Tuple2[Tuple2[K, V], Tuple2[V, K]]{Tuple2[K, V]{k, v}, …
```
> ast, cgen: fix printing nested generic struct

- vlib/v/gen/c/struct.v
- vlib/v/tests/generics_struct_init_with_inconsistent_generic_types_6_test.v
This PR fix generic struct init with inconsistent generic optional types (fix #16755).
- Fix generic struct init with inconsistent generic optional types.
- Add test.
```v
a ?A // Option
b ?B // Option
}
// map to array of Tuple2[int, Tuple2[key, value]] tuples
fn map_to_array_int_kv[K, V](m map[K]V) []Tuple2[int, Tuple2[K, V]] {
mut r := []Tuple2[int, Tuple2[K, V]]{cap: m.len}
mut i := 0
r << Tuple2[int, Tuple2[K, V]]{i, Tuple2[K, V]{k, v}}
i += 1
}
return r
}
// map to array of Tuple2[int, Tuple2[Tuple2[key, value], Tuple2[value, key]]] tuples
fn map_to_array_int_kv_vk[K, V](m map[K]V) []Tuple2[int, Tuple2[Tuple2[K, V], Tuple2[V, K]]] {
mut r := []Tuple2[int, Tuple2[Tuple2[K, V], Tuple2[V, K]]]{cap: m.len}
mut i := 0
r << Tuple2[int, …
```
> cgen: fix generic struct init with inconsistent generic optional types (fix #16755)

- vlib/os/os.v
- vlib/os/os_test.v
This PR fix os.file_ext() (fix #16751).
- Fix os.file_ext().
- Add test.
```v
import os
fn main() {
println(os.file_ext('.gitignore'))
println(os.file_ext('/.git/'))
}
```
> vlib: fix os.file_ext() (fix #16751)

- vlib/v/gen/c/array.v
- vlib/v/tests/array_filter_using_direct_closure_test.v
This PR fix array filter using direct closure (fix #16770).
- Fix array filter/all/any/map using direct closure.
- Add test.
```v
struct File {
name   string
typ    string
is_dir bool
}
fn filter(all_files []File, interested_file File) []File {
println(interested_file)
return all_files.filter(fn [interested_file] (f File) bool {
println(interested_file)
return true
})
}
fn main() {
filenames := ['one', 'two', 'three']
files := filenames.map(fn (f string) File {
return File{
name: f
typ: if f == 'one' {
'file'
} else {
'dir'
}
is_dir: if f == 'one' {
false
} else {
true
}
}
})
ret := filter(files, files[0])
println(ret)
assert ret.len == 3
assert ret[0].name == 'one'
assert ret[0].typ == 'file'
assert ret[1].name == 'two'
assert ret[1].typ == 'dir'
assert ret[2].name == 'three'
assert …
```
> cgen: fix array filter using direct closure (fix #16770)

- vlib/v/ast/ast.v
- vlib/v/checker/check_types.v
- vlib/v/checker/checker.v
- vlib/v/checker/comptime.v
- vlib/v/gen/c/assign.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/comptime_on_generics_func_test.v
- vlib/v/tests/comptime_var_on_multiple_args_test.v
Fix #16759 (not completely, it just works from dump() call)
```V
b string
c bool
}
fn get_type[T](t T) T {
return t
}
fn main() {
my := MyStruct{'cool', false}
$for field2 in MyStruct.fields {
$if field2.typ is string {
var := get_type(my.$(field2.name))
dump(var)
}
$if field2.typ is bool {
var := get_type(my.$(field2.name))
dump(var)
}
}
}
```
Prints
```
[test.v:16] var: cool
[test.v:20] var: false
```
> fix comptime value recognize on generic argument

- vlib/v/checker/comptime.v
- vlib/v/gen/c/comptime.v
- vlib/v/tests/comptime_for_in_fields_FieldData_test.v
This is a followup to 3d545ee .
It implements setting the new fields, based on the compiletime known information in cgen
and adds tests to prevent future regressions.
It also contains a patch, that fixes cgen for the following program (thanks again @felipensp) :
```v
i int
oi ?int
ci chan int
ai atomic int // on master, this field leads to a cgen error, if left uncommented
}
fn main() {
$for f in MyStruct.fields {
dump(f)
}
}	
```
> cgen: fill in the new `FieldData` fields, add tests

- vlib/v/checker/check_types.v
- vlib/v/tests/fn_call_generic_array_arg_test.v
Fix #14047
```V
fn f64_fun(x []f64) f64 {
return x[0] + x[1]
}
fn t_fun<T>(x []T) T {
$if T is f64 {
return f64_fun(x)
}
$else {
return T(0)
}
}
fn main() {
print(t_fun([1.0, 2.0]))
}
```
> checker: Fix fn call with generic []T arg

- vlib/v/checker/checker.v
- vlib/v/checker/comptime.v
- vlib/v/gen/c/comptime.v
- vlib/v/tests/inout/comptime_bool_fields.out
- vlib/v/tests/inout/comptime_bool_fields.vv
Fix #16786
```V
struct Bb {
a int
b struct{}
}
fn fuba[U](val U) {
$if field.is_struct {
println('struct')
}
$if field.is_struct == false {
println('not struct')
}
println('text')
}
}
fn main() {
bb := Bb{}
fuba(bb)
}
```
> checker,cgen: Make boolean field.is_<field> accessible at compile-time

- vlib/v/gen/c/fn.v
- vlib/v/tests/fn_call_comptime_array_arg_test.v
> cgen: Fix generic func arg type when passing array compile-time field

- vlib/v/gen/c/fn.v
- vlib/v/parser/expr.v
- vlib/v/tests/anon_fn_optional_call_in_if_expr_test.v
This PR fix anon fn optional call in if expr (fix #16673).
- Fix anon fn optional call in if expr.
- Add test.
```v
fn main() {
if fn () ?bool {
return true
}() or { false }
{
println('ok')
assert true
} else {
assert false
}
}
ok
```
> parser, cgen: fix anon fn optional call in if expr (fix #16673)

- vlib/v/gen/c/comptime.v
Fix #16801
Thanks @enghitalo for finding it! :-)
> cgen: Fix uneeded C generated code when using selectorexpr on $if

- vlib/v/gen/c/dumpexpr.v
- vlib/v/tests/dump_on_generic_func_test.v
> cgen: Fix dump fn name using generic var

- vlib/v/gen/c/index.v
- vlib/v/tests/fixed_array_literal_range_index_test.v
This PR fix fixed array literal range index (fix #16807).
- Fix fixed array literal range index.
- Add test.
```v
fn main() {
arr := [1, 2, 3, 4]![..]
println(arr)
println(typeof(arr).name)
assert typeof(arr).name == '[]int'
assert '${arr}' == '[1, 2, 3, 4]'
}
[1, 2, 3, 4]
[]int
```
> cgen: fix fixed array literal range index (fix #16807)

- vlib/crypto/bcrypt/bcrypt.v
- vlib/crypto/bcrypt/bcrypt_test.v
Fix issue #16769 security problem in compare_hash_and_password
The function compare_hash_and_password gaves ok for password with same chars "bb" or "bbb" or "bbbbb".
The solution is based on https://cs.opensource.google/go/x/crypto/+/master:bcrypt/bcrypt.go;l=226 that copy the key and add a NULL char at the end of the key
Tests are added in  file vlib/crypto/bcrypt/bcrypt_test.v
PS: I'm new Vlang maybe there is a better way to clone and append NULL char to an array.
> bcrypt: fix issue #16769 security problem in compare_hash_and_password

- vlib/v/gen/c/struct.v
- vlib/v/gen/c/testdata/comptime_optional_call.out
- vlib/v/tests/struct_optional_field_zero_test.v
- vlib/x/json2/encode_struct_test.v
This PR fix struct optional field zero init (fix #16623).
- Fix struct optional field zero init.
- Add test.
```v
struct Foo {
foo ?string
}
fn main() {
a := Foo{}
if foo := a.foo {
println(foo)
assert false
} else {
assert true
}
b := Foo{'hello'}
if foo := b.foo {
println(foo)
assert true
} else {
assert false
}
}
hello
```
> cgen: fix struct optional field zero init (fix #16623)

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/comptime.v
Implements and uses a stack for keeping the state inside Gen.comptime_for (when making nested calls, and between different functions), instead of doing it piece by piece with manual deletions/saving of the variables.
> cgen: add g.push_existing_comptime_values and g.pop_existing_comptime_values, use them inside Gen.comptime_for

- thirdparty/stb_image/stb_image.h
Just makes sure that we are using all the latest improvements and bugs
from https://github.com/nothings/stb/blob/master/stb_image.h .
> thirdparty: update stb_image.h to its latest version v2.27

- vlib/v/ast/table.v
- vlib/v/tests/generics_from_modules/infer_generic_struct_test.v
- vlib/v/tests/generics_from_modules/newmodule/newmodule.v
This PR fix inferring generic struct (fix #16830).
- Fix inferring generic struct.
- Add test.
```v
import newmodule as nm
fn main() {
a_in := [int(1), 2, 4]
res := nm.take_input(a: a_in, b: 3, c: int(5))
// res := nm.take_input(nm.Params[int]{a: a_in, b: 3, c: int(5)})  // this works
println(res)
}
[1.0, 2.0, 4.0, 3.0, 5.0]
```
```v
module newmodule
pub struct Params[T] {
mut:
a []T
b int
c T
}
pub fn take_input[T](p Params[T]) []f32 {
mut res := []f32{}
for x in p.a {
res << f32(x)
}
res << f32(p.b)
res << f32(p.c)
return res
}
```
> table: fix inferring generic struct (fix #16830)

- vlib/v/parser/parser.v
- vlib/v/tests/array_of_functions_direct_call_test.v
This PR fix array of functions direct call (fix #16835, fix #16578).
- Fix array of functions direct call.
- Add test.
```v
fn foo() string {
println('foo')
return 'foo'
}
fn bar() string {
println('bar')
return 'bar'
}
fn call() {
funcs := [foo, bar]
i := 1
ret := funcs[i]()
assert ret == 'bar'
}
fn main() {
call()
}
bar
```
```v
type Sfn = fn() string
const greeting = 'hallo gday aloha'.split(' ')
fn main() {
mut greet := []Sfn{ len: 3, init: fn [it] ()string { return greeting[it] } }
println( greet[1]() )
for g in greet {
println( g() )
}
println('')
// compiler error unknown function greet
tmp := 1
println( greet[tmp]() ) 
for ind in 0..greet.len { 
println( greet[ind]() )
}
}
gday
hallo
gday
aloha
gday
hallo
gday
aloha
```
> parser: fix array of functions direct call (fix #16835, fix #16578)

- vlib/os/file_test.v
Add a small test demonstrating and testing the use of the os.open_append/1 function.
> os: add test for os.open_append

- README.md
GitHub "sanitizes" readme files by removing all css styles.  This means that even though `align="center"` is deprecated, it's the only thing that works on GitHub.
However, it doesn't hurt to have that along with the newer way of doing things, so adding it back.  When browsers stop supporting `align="center"`, they'll have to fix it, but until then, at least it'll look "pretty" on GitHub.
> README: add back align=center to make github happy

- vlib/v/checker/fn.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/method_call_var_comp_test.v
Fix #16841
Fix method call passing comptime var like:
```V
$if field.is_array {
value := val.$(field.name)
e.encode_array(value) // it was generating wrong data type name
```
> cgen,checker: fix method call with comptime var

- vlib/v/gen/c/comptime.v
- vlib/v/tests/comptime_if_expr_with_result_call_test.v
This PR fix comptime if expr with optional or result call (fix #16837).
- Fix comptime if expr with optional or result call.
- Add test.
```v
import os
fn main() {
config_dir := $if !windows {
os.home_dir()
} $else {
os.config_dir() or { os.home_dir() }
}
println(config_dir)
}
C:\Users\yuyi9\AppData\Roaming
```
> cgen: fix comptime if expr with optional or result call (fix #16837)

- vlib/v/checker/infix.v
- vlib/v/checker/tests/check_err_msg_with_generics.out
- vlib/v/tests/generics_stack_of_sumtype_push_test.v
This PR fix generic stack of sumtype push() (fix #16834).
- Fix generic stack of sumtype push().
- Add test.
```v
type Content = bool | string
struct DataStack {
mut:
data datatypes.Stack[Content]
}
fn (mut dstack DataStack) push(content Content) {
dstack.data.push(content)
}
fn main() {
mut dstack := DataStack{}
dstack.push('hello')
println(dstack)
assert dstack.data.len() == 1
assert dstack.data.array() == [Content('hello')]
}
DataStack{
data: [Content('hello')]
}
```
> checker: fix generic stack of sumtype push() (fix #16834)

- vlib/json/json_encode_struct_with_optional_field_test.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/json.v
This PR fix json encode struct with optional field (fix #16462).
- Fix json encode struct with optional field.
- Add test.
```v
import json
struct Foo {
name string
num  ?int
}
fn main() {
f1 := Foo{
name: 'hello'
}
ret1 := json.encode(f1)
println(ret1)
assert ret1 == '{"name":"hello","num":null}'
f2 := Foo{'hello', 22}
ret2 := json.encode(f2)
println(ret2)
assert ret2 == '{"name":"hello","num":22}'
}
{"name":"hello","num":null}
{"name":"hello","num":22}
```
> cgen: fix json encode struct with optional field (fix #16462)

- vlib/v/builder/builder.v
- vlib/v/util/errors.v
V will try to detect that situation now, and show a hint like this:
```
If the code of your project is in multiple files, try with `v project` instead of `v project/main.v`
```
> builder: show a hint about `v .`, on unknown errors, suggesting that the user tried to compile a single .v file from a multi file project

- vlib/v/gen/c/cgen.v
- vlib/v/tests/optional_compvar_types_test.v
- vlib/v/tests/optional_compvar_val_test.v
Fix #16848
Fix #16849
```V
struct FixedStruct1 {
a int
b string
}
struct FixedStruct2 {
c ?int
d ?string
}
fn encode_struct[T](val T) bool {
wr := Writer{}
value := val.$(field.name)
write1(value) // it was broken
wr.write2(value) // it was broken
}
return true
}
```
> cgen: fix code generated for optional comptime var

- vlib/v/gen/c/array.v
- vlib/v/tests/assert_with_array_ref_test.v
Fix #16891
Cgen generates wrong code for:
```V
myu16 := u16(50)
size_of_u16 := sizeof(u16)
mut asu8 := unsafe { &u8(malloc(size_of_u16)) }
asu8 = &[myu16]! // look this
assert unsafe { asu8.vbytes(int(size_of_u16)) } == [u8(50), 0]
}
```
It does generates `HEAP(Array_fixed_u16_1, {myu16};` missing the final `)` char.
> cgen: fix array_init generated code for reference var

- vlib/v/checker/comptime.v
- vlib/v/fmt/fmt.v
- vlib/v/gen/c/comptime.v
- vlib/v/parser/parser.v
- vlib/v/tests/check_in_is_consistency_test.v
- vlib/v/tests/comptime_in_type_checking_test.v
Fix #16887
Make possible to do type checking like:
```V
fn check[T](val T) string {
$if T in [$Array, $Struct, array] {
return 'array or struct'
} $else $if T in [$Int, $Float, int, f64] {
return 'int or float'
} $else $if T in [$Map, $Sumtype, map] {
return 'map or sumtype'
}
return ''
}
```
> checker, cgen: add in operator for comptime type checking

- vlib/v/checker/checker.v
- vlib/v/checker/return.v
- vlib/v/checker/tests/aliased_optional_fn_call_err.out
- vlib/v/checker/tests/aliased_optional_fn_call_err.vv
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/aliased_optional_fn_call_test.v
This PR fix aliased optional or result fn call (fix #16409).
- Fix aliased optional or result fn call.
- Add test.
```v
type OptStr = ?string
fn foo() OptStr {
return 'abc'
}
fn main() {
ret := foo()?
println(ret)
assert ret == 'abc'
}
abc
```
```v
type OptStr = ?string
fn foo() OptStr{
return 'abc'
}
fn main(){
println(foo())
}
tt1.v:8:10: error: foo() returns an option, so it should have either an `or {}` block, or `?` at the end
6 |
7 | fn main(){
8 |     println(foo())
|             ~~~~~
9 | }
```
> checker, cgen: fix aliased optional or result fn call (fix #16409)

- vlib/json/json_encode_struct_with_option_field_test.v
- vlib/v/gen/c/json.v
This PR fix json encoding struct with option field (fix #16868).
- Fix json encoding struct with option field.
- Add test.
```v
import json
import x.json2
struct Foo {
name string
num  ?int
}
fn main() {
f1 := Foo{
name: 'hello'
}
ret1 := json.encode(f1)
println(ret1)
assert ret1 == '{"name":"hello"}'
ret2 := json2.encode(f1)
println(ret2)
assert ret2 == '{"name":"hello"}'
f2 := Foo{'hello', 22}
ret3 := json.encode(f2)
println(ret3)
assert ret3 == '{"name":"hello","num":22}'
ret4 := json2.encode(f2)
println(ret4)
assert ret4 == '{"name":"hello","num":22}'
}
{"name":"hello"}
{"name":"hello"}
{"name":"hello","num":22}
{"name":"hello","num":22}
```
> cgen: fix json encoding struct with option field (fix #16868)

- vlib/v/gen/c/match.v
- vlib/v/tests/match_return_fn_test.v
Fix #16473
Fixes situation which match expr return pointer to function and has more than 5 branch stmst, i.e. it does not get converted to ternary code.
```V
fn dummy() string {
return 'b'
}
fn err() fn () string {
return match Foo.a {
.a { dummy }
.b { dummy }
.c { dummy }
.d { dummy }
.e { dummy }
else { dummy }
}
}
var := main.err()()
assert var == 'b'
}
```
> fix code generated to matchexpr which returns function

- vlib/os/inode.c.v
This PR makes `os.FileMode` public. This is necessary for the `pathlib` module I'm working on (#16782), because `Path.inode()` returns the result from `os.inode()`, which is `os.FileMode`.
I've ran the tests for tests for the os module, which still work. Let me know if I need to do anything else.
See discussion under the aforementioned PR: https://github.com/vlang/v/pull/16782#issuecomment-1375560314
> os: make os.FileMode public

- vlib/x/json2/encode_struct_test.v
- vlib/x/json2/encoder.v
- vlib/x/json2/json_module_compatibility_test/json_test.v
- vlib/x/json2/json_module_compatibility_test/json_todo_test.vv
Thanks @spytheman @Delta456 !
```v
struct Aa {
sub AliasType
}
struct Bb {
a int
}
type AliasType = Bb
fn test_encode_alias_field() {
s := json.encode(Aa{
sub: Bb{
a: 1
}
})
assert s == '{"sub":{"a":1}}'
}
```
> json2: encode alias struct

- vlib/v/ast/ast.v
- vlib/v/ast/table.v
- vlib/v/fmt/fmt.v
- vlib/v/gen/golang/golang.v
- vlib/v/parser/comptime.v
- vlib/v/tests/comptime_kinds_test.v
This PR adds support for `$if T is $Function {` and `$if T is $Alias`,
similar in behaviour to `$if T is $Struct {` .
> comptime: add support for `T is $Alias` and `T is $Function`

- vlib/v/checker/comptime.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/comptime.v
- vlib/v/tests/comptime_method_call_with_check_test.v
Fix #9357
Makes possible to run code like:
```V
struct TestStruct {}
fn (t TestStruct) one_arg(a string) {
println(a)
}
fn (t TestStruct) two_args(a string, b int) string {
println('${a}:${b}')
return a
}
t := TestStruct{}
mut out := ''
$for method in TestStruct.methods {
$if method.name == 'one_arg' {
res := t.$method(method.name)
out += res
println(res)
} $else $if method.name == 'two_args' {
res := t.$method(method.name, 42)
out += res
println(res)
}
}
}
```
> checker,cgen: allow method.name checking in comptime

- examples/sokol/.gitignore
- thirdparty/fontstash/stb_truetype.h
- thirdparty/sokol/sokol_app.h
- thirdparty/sokol/sokol_audio.h
- thirdparty/sokol/sokol_gfx.h
- thirdparty/sokol/util/sokol_fontstash.h
- thirdparty/sokol/util/sokol_gl.h
- vlib/sokol/audio/audio.v
- vlib/sokol/c/declaration.c.v
- vlib/sokol/f/f.v
- vlib/sokol/gfx/gfx.c.v
- vlib/sokol/gfx/gfx_allocator_and_logger.c.v
- vlib/sokol/gfx/gfx_structs.c.v
- vlib/sokol/memory/memory.v
- vlib/sokol/sapp/enums.c.v
- vlib/sokol/sapp/sapp.c.v
- vlib/sokol/sapp/sapp_allocator_and_logger.c.v
- vlib/sokol/sapp/sapp_structs.c.v
- vlib/sokol/sfons/sfons.c.v
- vlib/sokol/sfons/sfons_funcs.c.v
- vlib/sokol/sgl/sgl.c.v
- vlib/sokol/sgl/sgl_allocator_and_logger.c.v
- vlib/sokol/sgl/sgl_structs.c.v
- vlib/v/checker/tests/modules/module_with_redeclaration.out
- vlib/v/checker/tests/modules/module_with_redeclaration/redeclare_time_structs.v
- vlib/v/checker/tests/private_redeclaration_of_C_struct.out
The headers were copied, then the V patches were applied, and the V wrappers were adapted
to the new APIs (where the compilation was broken).
Most user programs should not need to be updated, as long as they are using the V APIs,
and not the C ones directly.
There is a small addition, related to the updates too: now all sokol/gg programs can be
compiled with `-d trace_sokol_memory` .
> thirdparty: update all sokol and fontstash headers with their upstream versions

- doc/docs.md
C wrapper generates by the `v translate wrapper` command, not the `v wrapper`.
> docs: fix v wrapper command

- vlib/v/parser/comptime.v
- vlib/v/tests/tmpl_using_variable_or_const_path_test.v
This PR fix $tmpl using variable or const path argument (fix #16941).
- Fix $tmpl using variable or const path argument.
- Add test.
```v
const template_path = 'tmpl/template.in'
pub struct SomeThing {
pub:
m map[string]string
}
fn (s SomeThing) someval(what string) string {
return s.m[what]
}
fn (s SomeThing) template_variable() string {
path := 'tmpl/template.in'
return $tmpl(path)
}
fn (s SomeThing) template_const() string {
return $tmpl(template_path)
}
fn test_tmpl_with_variable_path() {
mut sm := map[string]string{}
sm['huh'] = 'monkey'
sm['hah'] = 'parrot'
s := SomeThing{sm}
result := s.template_variable()
assert result.trim_space() == 'someval: monkey
someotherval: parrot'
}
fn test_tmpl_with_const_path() {
mut sm := map[string]string{}
sm['huh'] = 'monkey' …
```
> parser: fix tmpl using variable or const path argument (fix #16941)

- vlib/v/fmt/fmt.v
- vlib/v/parser/comptime.v
- vlib/v/tests/tmpl_using_variable_or_const_path_test.v
This PR fix fmt error of `$tmpl(path)`.
> parser, fmt: fix fmt error of `$tmpl(path)`

- vlib/v/fmt/struct.v
- vlib/v/fmt/tests/struct_with_array_of_anon_struct_field_decl_keep.vv
- vlib/v/parser/parse_type.v
- vlib/v/parser/parser.v
- vlib/v/parser/struct.v
This PR fix fmt in struct decl with array of anon struct field (fix #16947).
- Fix fmt in struct decl with array of anon struct field.
- Add test.
struct_with_array_of_anon_struct_field_decl_keep.vv
```v
struct Abc {
a []struct {
b string
}
}
fn main() {
abc := Abc{
a: [struct {'this is b'}]
}
dump(abc)
}
```
> parser, fmt: fix fmt in struct decl with array of anon struct field (fix #16947)

- cmd/tools/vtest-self.v
- vlib/v/checker/orm.v
- vlib/v/tests/orm_stmt_wrong_return_checking_test.v
Fix #16330
```V
sql dbs {
insert repo into Target
} or {
println(err)
return 1
}
assert true // checker was pointing as unreachable code
return 1 
```
> checker: fix orm unreachable code checking

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/import_selective_expected.vv
- vlib/v/fmt/tests/import_selective_input.vv
See test. Added imports will be remove by v fmt on current master
> fmt: fix removal of selective imporcted types used as array elements

- vlib/db/pg/README.md
> docs: fix ALL `db.pg` docs is italic in html format

- vlib/v/checker/tests/comptime_dump_fields_var_test.out
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/slow_tests/inout/printing_struct_with_arrays_of_anon_struct_field.out
- vlib/v/slow_tests/inout/printing_struct_with_arrays_of_anon_struct_field.vv
This PR fix printing struct with arrays of anonymous struct fields. (fix #16947)
- Fix printing struct with arrays of anonymous struct fields. 
- Add test.
```v
struct Abc {
a []struct {
b string
}
}
fn main() {
abc := Abc{
a: [struct {'this is b'}]
}
println(abc)
}
Abc{
a: [struct {
b: 'this is b'
}]
}
```
> cgen: fix printing struct with arrays of anonymous struct fields (fix #16947)

- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/js/auto_str_methods.v
- vlib/v/tests/tag_autostr_allowrecurse_test.v
This PR implements the `[autostr: allowrecurse]` struct attribute to hint to the compiler that it is safe to dereference recursive structures without fear of a circular reference.
A `[autostr: allowrecurse]` struct attribute can be used to guarantee that in printing operations, the entirety of a node tree is dereferenced.
```v
[autostr: allowrecurse]
struct Node {
a &Node = unsafe { nil }
b &Node = unsafe { nil }
}
fn main() {
abc := &Node{
a: &Node{
b: &Node{}
}
b: &Node{
a: &Node{}
}
}
println(abc)
} 
```
Without `allowrecurse`:
```
&Node{
a: &<circular>
b: &<circular>
}
```
With `allowrecurse`:
```
&Node{
a: &Node{
a: &nil
b: &Node{
a: &nil
b: &nil
}
}
b: &Node{
a: &Node{
a: &nil
b: &nil
}
b: &nil
}
}
```
> gen c/js: `[autostr: allowrecurse]` attribute

- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/call_to_str_on_option_test.v
Fix #16897
Makes `.str()` consistent on compile-time with option values.
```V
mut value := val.$(field.name)
$if field.is_option {
println(value?.str())
println(val.$(field.name)?.str())
count += 1
}
}
```
> checker,cgen: allow ?.str() on compile-time fields var

- vlib/v/checker/comptime.v
- vlib/v/checker/if.v
- vlib/v/checker/tests/unknown_comptime_expr.out
- vlib/v/checker/tests/unknown_comptime_expr.vv
- vlib/v/gen/c/comptime.v
- vlib/v/tests/var_type_is_checking2_test.v
- vlib/v/tests/var_type_is_checking_test.v
Fix #16930
Makes possible to do:
```V
struct Test {
a int
b ?int
}
hh := 1 // i64(4)
$if hh is $Int {
println('int')
assert true
} $else $if hh !is $Int {
println('string')
assert false
}
b := 1.2
$if b is $Int {
assert false
} $else $if b is $Float {
println('float')
assert true
}
c := true
$if c is bool {
println('bool')
assert true
}
d := Test{}
$if d.b is ?int {
println('?int')
assert true
}
$if d.a is ?int {
println('?int')
assert false
} $else $if d.a is int {
println('int')
assert true
}
$if d is Test {
println('Test')
}
}
```
field.unaliased_typ 
```V
type MyAlias = string
struct Foo {
a string
b ?string
c MyAlias
}
fn main() {
$for field in Foo.fields {
println('${field.name} - ${field.typ} - ${field.unaliased_typ}')
$if field.unaliased_typ is ?string { …
```
> cgen, checker: var type checking at compile-time

- vlib/v/parser/fn.v
- vlib/v/tests/type_alias_of_fn_with_mut_args_test.v
This PR fix type alias of fn with mut argument (fix #16970).
- Fix type alias of fn with mut argument.
- Add test.
```v
type MutCallback = fn (mut []string)
fn mutate(mut ss []string, cb MutCallback) {
cb(mut ss)
}
fn main() {
mut s := ['a']
mutate(mut s, fn (mut ss []string) {
ss << 'b'
})
println(s)
assert s == ['a', 'b']
}
['a', 'b']
```
> parser: fix type alias of fn with mut argument (fix #16970)

- vlib/v/checker/if.v
- vlib/v/tests/unaliased_typ_checking_test.v
Fix #16980
Makes possible such code:
```V
type MyArray = []string
type MyString = string
type MyFloat = f64
type MyMap = map[string]string
struct Foo {
a string
b ?string
c MyArray
d MyString
e MyFloat
f MyMap
}
mut out := map[string][]string{}
$for field in Foo.fields {
print('${field.name} is ')
$if field.unaliased_typ is $Int {
println('numeric')
out[field.name] << 'numeric'
} $else $if field.unaliased_typ is $Array {
println('array')
out[field.name] << 'array'
} $else $if field.unaliased_typ is $Float {
println('float')
out[field.name] << 'float'
} $else $if field.unaliased_typ is $Map {
println('map')
out[field.name] << 'map'
} $else $if field.unaliased_typ is string || field.unaliased_typ is ?string {
println('string opt? ${field.is_option}')
out[field.name] << …
```
> checker: Fix compile-time field.unaliased_typ checking against ComptimeType

- vlib/hash/crc32/crc32.v
- vlib/hash/wyhash.c.v
- vlib/hash/wyhash.v
Add missing documentation per `v missdoc` command for [#7047](https://github.com/vlang/v/issues/7047):
```
$ v missdoc vlib/hash/                                
/home/nahua/projects/v/vlib/hash/wyhash.c.v:10:0:pub fn wyhash_c(key &u8, len u64, seed u64) u64 
/home/nahua/projects/v/vlib/hash/wyhash.c.v:15:0:pub fn wyhash64_c(a u64, b u64) u64 
/home/nahua/projects/v/vlib/hash/wyhash.c.v:20:0:pub fn sum64_string(key string, seed u64) u64 
/home/nahua/projects/v/vlib/hash/wyhash.c.v:25:0:pub fn sum64(key []u8, seed u64) u64 
/home/nahua/projects/v/vlib/hash/wyhash.v:32:0:pub fn wymum(a u64, b u64) u64 
/home/nahua/projects/v/vlib/hash/crc32/crc32.v:48:0:pub fn (c &Crc32) checksum(b []u8) u32 
```
Please …
> hash: add missing documentation to all public functions

- vlib/v/checker/assign.v
- vlib/v/checker/checker.v
- vlib/v/tests/map_reference_value_test.v
This PR fix map with reference value (fix #16989).
- Fix map with reference value.
- Add test.
```v
struct Foo {
bar string
}
fn main() {
m1 := map[string]&Foo{}
if e := m1['bar'] {
println(e.bar)
}
println(m1)
mut m2 := map[string]&Foo{}
m2['bar'] = &Foo{}
println(m2)
assert true
}
{}
{'bar': Foo{
bar: ''
}}
```
> checker: fix map with reference value (fix #16989)

- vlib/v/checker/assign.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/map_index_reference_value.out
- vlib/v/checker/tests/map_index_reference_value.vv
This PR check unsafe map index operation (fix #16989).
- Check unsafe map index operation.
- Add test.
```v
struct Foo {
bar string
}
fn main() {
mut m := map[string]&Foo{}
m['bar'].bar = 'bar'
// m['bar'] << 'baz' // etc
}
tt1.v:7:3: notice: accessing a pointer map value requires an `or{}` block outside `unsafe`
6 |     mut m := map[string]&Foo{}
7 |     m['bar'].bar = 'bar'
|      ~~~~~~~
8 |     // m['bar'] << 'baz' // etc
9 | }
tt1.v:7:11: error: field `bar` of struct `&Foo` is immutable
6 |     mut m := map[string]&Foo{}
7 |     m['bar'].bar = 'bar'
|              ~~~
8 |     // m['bar'] << 'baz' // etc
9 | }
```
> checker: check unsafe map index operation (fix #16989)

- vlib/v/checker/checker.v
- vlib/v/checker/tests/undefined_var_in_comptime_for_test.out
- vlib/v/checker/tests/undefined_var_in_comptime_for_test.vv
```V
value := val.$(field.name)
if value.str() != 'Option(error: none)' {
fields_len++ // crashing
}
}
```
> checker: fix postfix var checking break

- vlib/v/checker/checker.v
- vlib/v/checker/comptime.v
- vlib/v/checker/fn.v
- vlib/v/fmt/fmt.v
- vlib/v/gen/c/array.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/if.v
- vlib/v/gen/golang/golang.v
- vlib/v/gen/js/js.v
- vlib/v/parser/parser.v
This PR clean up multiple `!is` infix expr.
> all: clean up multiple `!is` infix expr

- vlib/v/checker/for.v
- vlib/v/tests/for_comptime_selector_test.v
Fix #16966
Makes possible to do:
```V
fn call_generic[U](val U) int {
mut out := 0
for element in val.$(field.name) {
dump(element)
out += element
}
}
return out
}
```
> checker: fix for..in statement with comptimeselector

- vlib/v/gen/c/cgen.v
- vlib/v/tests/struct_init_with_chan_field_test.v
This PR fix struct init with chan field (fix #16996).
- Fix struct init with chan field.
- Add test.
```v
struct Abc {
def Def
}
struct Def {
ch chan string
}
fn main() {
abc1 := Abc{Def{}}
println('printing abc1')
println(abc1) // this works
abc2 := Abc{}
println('printing abc2')
println(abc2) // this gives invalid memory access
assert '${abc1}' == '${abc2}'
}
printing abc1
Abc{
def: Def{
ch: chan string{cap: 0, closed: 0}
}
}
printing abc2
Abc{
def: Def{
ch: chan string{cap: 0, closed: 0}
}
}
```
> cgen: fix struct init with chan field (fix #16996)

- vlib/v/ast/table.v
- vlib/v/slow_tests/inout/printing_const_array.out
- vlib/v/slow_tests/inout/printing_const_array.vv
This PR fix const values defined in the wrong order (fix #16995).
- Fix const values defined in the wrong order.
- Add test.
```v
const (
dat = 'Data tag ,No data'.split(',')
dd  = []Info{len: 4, init: Info{if it in tag { dat[0] + it.str() } else { dat[1] }}}
tag = [1, 2]
)
struct Info {
val string
}
fn main() {
println(dd)
}
[Info{
val: 'No data'
}, Info{
val: 'Data tag 1'
}, Info{
val: 'Data tag 2'
}, Info{
val: 'No data'
}]
```
> ast: fix const values defined in the wrong order (fix #16995)

- vlib/v/gen/c/assign.v
- vlib/v/tests/comptime_var_assignment_test.v
Fix #16884
```V
struct FixedStruct1 {
a int
b string
c ?int
d ?string
}
fn encode_struct[T](val T) []string {
mut out := []string{}
value := val.$(field.name)
$if field.is_option {
gg := value
println(gg)
out << gg.str()
} $else {
gg := value
println(gg)
out << gg.str()
}
}
return out
}
fn main() {
out := encode_struct(FixedStruct1{1, 'foo', 4, 'bar'})
assert out[0] == '1'
assert out[1] == 'foo'
assert out[2] == 'Option(4)'
assert out[3] == "Option('bar')"
}
```
> cgen: fix assignment from comptime var

- vlib/encoding/base32/base32.v
Add missing documentation per `v missdoc` command for [#7047](https://github.com/vlang/v/issues/7047):
```
$ v missdoc vlib/encoding/                                
/home/nahua/projects/v/vlib/encoding/base32/base32.v:27:0:pub fn decode_string_to_string(src string) ?string 
/home/nahua/projects/v/vlib/encoding/base32/base32.v:31:0:pub fn decode_to_string(src []u8) ?string 
/home/nahua/projects/v/vlib/encoding/base32/base32.v:36:0:pub fn decode(src []u8) ?[]u8 
/home/nahua/projects/v/vlib/encoding/base32/base32.v:41:0:pub fn encode_string_to_string(src string) string 
/home/nahua/projects/v/vlib/encoding/base32/base32.v:45:0:pub fn encode_to_string(src []u8) string 
/home/nahua/projects/v/vlib/encoding/base32/base32.v:49:0:pub fn encode(src []u8) []u8 …
```
> encoding: Add missing documentation for all public `base32` functions

- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/for.v
- vlib/v/gen/js/js.v
This PR clean up multiple `is` infix expr.
> all: clean up multiple `is` infix expr

- cmd/tools/vast/vast.v
- vlib/v/ast/ast.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/recursive_alias_type_err.out
- vlib/v/checker/tests/recursive_alias_type_err.vv
- vlib/v/parser/parser.v
Fix #17008 by disallowing recursive alias declarations with more precise/helpful error messages
> checker: add error for `type Alias = map[string]Alias` (fix #17008)

- vlib/v/checker/infix.v
- vlib/v/gen/c/infix.v
- vlib/v/tests/for_in_mut_array_with_mul_test.v
This PR fix for in mut array with mul operation (fix #17019).
- Fix for in mut array with mul operation.
- Add test.
```v
fn main() {
mut ints_a := [1, 2]
for mut i in ints_a {
i = i * i
}
print('${ints_a}')
assert ints_a == [1, 4]
}
[1, 4]
```
> checker, cgen: fix for in mut array with mul operation (fix #17019)

- vlib/v/checker/check_types.v
- vlib/v/slow_tests/inout/generic_fn_with_alias_arg.out
- vlib/v/slow_tests/inout/generic_fn_with_alias_arg.vv
This PR fix generic fn infering error with alias argument (fix #17022).
- Fix generic fn infering error with alias argument.
- Add test.
```v
struct MyStruct[T] {
a T
}
fn mprint[T](s MyStruct[T]) {
println(s)
}
fn mprint_with_alias(s MyStructAlias) {
println(s)
}
type MyStructAlias = MyStruct[int]
fn main() {
a := MyStruct[int]{}
mprint(a)              // works
mprint_with_alias(a)   // works
b := MyStructAlias{}
mprint(b)              // does not work, requires mprint[int](b)
mprint_with_alias(b)   // works
}
MyStruct[int]{
a: 0
}
MyStructAlias(MyStruct[int]{
a: 0
})
MyStruct[int]{
a: 0
}
MyStructAlias(MyStruct[int]{
a: 0
})
```
> checker: fix generic fn infering error with alias argument (fix #17022)

- vlib/net/html/dom.v
- vlib/net/html/dom_test.v
- vlib/net/html/parser.v
- vlib/net/html/tag.v
- vlib/net/html/tag_test.v
**Summary**: This PR adds functions that search tags by class names.
The current implementation, `get_tags_by_attribute_value`, cannot retrieve tags with partial or shuffled class names. (Please check #17004)
This PR solves the issue.
It adds two functions: `DocumentObjectModel.get_tags_by_class_name` and `&Tag.get_tags_by_class_name`
Their behavior is similar to [Element.getElementsByClassName](https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByClassName), but they use variadic arguments instead of [space-separated tokens](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#space-separated-tokens).
I hope this helps HTML-related works.
**Example**
```v
import net.html
fn main() {
mut dom := …
```
> net.html: add get_tags_by_class_name

- vlib/term/colors.v
Add missing documentation for `vlib/term/colors.v` per `v missdoc` command for [#7047](https://github.com/vlang/v/issues/7047).
> term: add missing documentation for all colors public functions

- cmd/tools/vcreate.v
- examples/vweb_fullstack/src/databases/config_databases_sqlite.v
- vlib/v/tests/orm_stmt_wrong_return_checking_test.v
This PR fixes an import statement from 3 files.
They use `import sqlite`, which will be deprecated after 2023-02-01.
Note that  #16820 fixed almost every other DB import statement.
> Fix deprecated import
