vlang/v

vlib/v/checker/assign.v, vlib/v/checker/fn.v, vlib/v/checker/tests/method_op_alias_err.out, vlib/v/gen/c/assign.v, vlib/v/tests/alias_basic_types_test.v
Fix #17023 .
Allow using +,-,*,/ and += etc for aliases of int like i32, allow the op method overriding for the aliases too.
=> checker: relax checks on operators done on aliases of primitives like int, u8, string etc.; add tests

vlib/term/control.v, vlib/term/ui/input_nix.c.v, vlib/term/ui/input_windows.c.v, vlib/term/ui/ui.v
Add missing documentation for all remaining public functions inside `vlib/term/` per `v missdoc vlib/term/` command for [#7047](https://github.com/vlang/v/issues/7047).
=> term: add missing documentation for all remaining public functions

vlib/v/slow_tests/inout/generic_fn_with_alias_arg.vv
This PR correct the test comment in generic_fn_with_alias_arg.vv.
=> tests: correct the test comment in generic_fn_with_alias_arg.vv

vlib/v/tests/bench/bench_json_vs_json2.v
Motivation: this benchmark is already a little big and it tends to get much bigger and, therefore, more difficult to find the code referring to the benchmark. So using dump function can help in this issue.
=> bench_json_vs_json2: jump to

vlib/v/gen/c/struct.v, vlib/v/tests/generics_struct_no_key_init_test.v
This PR fix generic struct no_key init (fix #17040).
- Fix generic struct no_key init.
- Add test.
```v
struct Am {
inner int
}
fn convert[T](num int) T {
return T{num}
}
fn main() {
println(convert[Am](3).inner)
assert convert[Am](3).inner == 3
}
3
```
=> cgen: fix generic struct no_key init (fix #17040)

vlib/x/json2/encoder.v
=> json2: perf time encode. around 2x faster

vlib/v/ast/table.v, vlib/v/tests/const_call_expr_order_test.v, vlib/v/tests/const_selector_expr_order_test.v
Fix #15049 .
```v
module main
import v.vmod
pub const manifest = vmod.from_file('v.mod') or { panic(err) }
pub const (
version = manifest.version
name    = manifest.name
)
```
... now properly initialises the const `version` after `manifest` was initialised.
Previously it was done before `manifest` was assigned the value from the function call, which led to `version` having .str == 0 -> println(version) was outputing `println(NIL)` instead.
=> ast: fix const dependency order for consts initialised with ast.SelectorExpr (fix #15049)

vlib/os/os_windows.c.v
Fix somewhat messy and scattered `uname()`, instead mimicking other current utilities (busybox/uutils).
=> os/uname: fix WinOS uname() recipe

vlib/v/checker/fn.v, vlib/v/checker/tests/fn_call_using_none_arg_err.out, vlib/v/checker/tests/fn_call_using_none_arg_err.vv
This PR check fn call using 'none' as argument (fix #17057).
- Check fn call using 'none' as argument.
- Add test.
```v
fn f[T](v T) {
println(v)
}
fn main() {
f(none)
}
tt1.v:6:4: error: cannot use `none` as function argument
4 |
6 |     f(none)
|       ~~~~
7 | }
```
=> checker: check fn call using 'none' as argument (fix #17057)

vlib/v/checker/check_types.v
This PR makes a minor cleanup in infer_fn_generic_types().
- Change generic seperator `<>` to `[]`.
=> checker: minor cleanup in infer_fn_generic_types()

vlib/os/os.c.v, vlib/os/os.v, vlib/os/os_js.js.v, vlib/os/os_test.v
Fixes #16985 .
Moves the existing `os.mv` implementation to `os.rename`.
The new `os.mv` first tries to move/rename with the old fast platform specific version and falls back to `os.mv_by_cp` if the former didn't work.
Note: We should somehow add a test to cover "moving files from one partition to another", but I'm currently unsure how to do that.
=> os: rework mv so it works with different partitions

vlib/v/checker/struct.v, vlib/v/checker/tests/generics_struct_nokeys_init_err.out, vlib/v/checker/tests/generics_struct_nokeys_init_err.vv
This PR check generic struct no_keys init (fix #17061).
- Check generic struct no_keys init.
- Add test.
```v
struct Am {
inner int
}
fn convert[T](num int) T {
return T{num, 1}
}
fn main() {
println(convert[Am](3).inner)
assert convert[Am](3).inner == 3
}
tt1.v:4:9: error: struct `Am` no_keys init expected `1` fields, but got `2`
2 |
3 | fn convert[T](num int) T {
4 |     return T{num, 1}
|            ~~~~~~~~~
5 | }
6 |
```
=> checker: check generic struct no_keys init (fix #17061)

doc/docs.md
`__global` cannot be used as identifier so it can be treated like `__offsetof` as keyword.
See https://play.vlang.io/p/f7142536dc
=> docs: add `__global` to keyword list

doc/docs.md
Empty tags are not recognized by all browsers and markdown parsers, so it is safer to use the expanded versions
=> doc: expand empty `<a>` tags

vlib/v/gen/c/index.v
=> cgen: autofree bug in `or` block for array of strings

vlib/gx/color.v, vlib/gx/image.v, vlib/gx/text.v
Sorry it's a short PR today for low-hanging fruits (eyes are a bit sore and need to rest) :see_no_evil: 
Add missing documentation for all remaining public functions inside `vlib/gx/` per `v missdoc vlib/gx/` command for [#7047](https://github.com/vlang/v/issues/7047).
=> `vlib/gx`: add missing docs or update previous docs

vlib/builtin/js/string.js.v, vlib/builtin/js/string_test.js.v, vlib/builtin/string.v, vlib/builtin/string_test.v
* fixes and increases cross-platform portability of `split_into_lines()`; now has MacOS (`\r`), POSIX (`\n`), and WinOS (`\r\n`) compatibility
* added/revised tests for the updated capability
* also fixes the builtin/js version and activated/corrected it's tests as well
Could you explain the *builtin/js* version? I did correct it's function and activated the respective test, but I'm not sure about the applicability.
Anyway, CI with all tests (both *builtin* and *builtin/js*) are now passing.
=> Feat add multi-platform portability to string `split_into_lines()`

vlib/builtin/linux_bare/old/.checks/linuxsys/linuxsys.v, vlib/builtin/linux_bare/old/.checks/string/string.v
It's strange that it worked at all, but somehow it seems we can't write like that.
=> builtin: fix wrong module name

vlib/v/ast/types.v
I need to use `is_primitive()`, and noticed that it ignores boolean types. Is it deliberate or not?
=> ast: is_primitive ignores bool type

vlib/io/buffered_reader.v, vlib/io/io.v, vlib/io/reader.v, vlib/io/readerwriter.v, vlib/io/util/util.v, vlib/io/writer.v
:wave:  Add missing documentation for all remaining public functions inside `vlib/io/` per `v missdoc vlib/io/` command for [#7047](https://github.com/vlang/v/issues/7047).
Thank you for your time and review :smiley:
=> io: add missing documentation and edit existing ones

vlib/v/gen/c/cgen.v
why not use cleanup like .init() too, example:
```
fn main(){
println('text')
}
fn init() {
println('init')
}
fn cleanup(){
println('clean')
}
```
produce:
```
init
text
clean
```
I know that will more rare than .init() but in some c libraries can be usefull to not give duty to "end-point" programers ...
=> v: support an optional `fn cleanup() {` in each module, to complement the existing optional `fn init() {`

vlib/net/http/http.v, vlib/net/http/method.v, vlib/net/http/server.v, vlib/net/http/status.v
:wave:  Add missing documentation for some public functions inside `vlib/net/http` per `v missdoc vlib/net/http` command for [#7047](https://github.com/vlang/v/issues/7047).
Thank you for your time and review :smiley:
=> net.http: add documentation to http, method, server, and status

vlib/v/gen/c/auto_eq_methods.v
Fix #17131
```V
type MyInt = int
type MyOptInt = ?int
type MyOptStr = ?string
type MySumType = int | f64 | string
struct Foo {
i int
i_opt ?int
arr []int
arr2 []int = [1,2]
dec f64
dec_opt ?f64	
dec_arr []f64
i_arr []int
str_arr []string
opt_int ?int
opt_int2 ?int = 3
myalias MyInt
myoptlias ?MyInt
myoptlias2 ?MyInt = MyInt(1)
myoptint MyOptInt
mysumtype MySumType
mysumtypeopt ?MySumType
str string 
str2 string = 'b'
str_opt ?string
str_opt2 ?string = 'a'
str3 MyOptStr
}
struct Bar {
pub:
foo ?Foo = none
}
fn main() {
m := Bar{}
assert m == Bar{}
}
```
=> cgen: fix opt member eq operation

vlib/v/gen/c/str_intp.v, vlib/v/slow_tests/inout/printing_for_mut_v_in_a.out, vlib/v/slow_tests/inout/printing_for_mut_v_in_a.vv
This PR fix printing for mut v in arr (fix #17123).
- Fix printing for mut v in arr.
- Add test.
```v
fn main() {
// check to see if mutable integers work as expected
mut num := 255
println('mutable num is ${num}')
mut arr := [255]
// check to see if mutable arrays with immutable iteration work as expected
for elem in arr {
println('imutable element is ${elem}')
}
// check to see if mutable arrays with mutable iteration work as expected
for mut elem in arr {
println('mutable element is ${elem}')
}
// check to see if mutable arrays with mutable iteration work as expected (explicit format)
for mut elem in arr {
println('mutable element is ${elem:d}')
}
}
mutable num is 255
imutable element is 255
mutable element is 255
mutable element is 255
```
=> cgen: fix printing for mut v in arr (fix #17123)

vlib/v/gen/c/match.v, vlib/v/tests/match_expr_with_opt_result_test.v
Fix #17146
```V
struct Foo {
pub:
a int
}
fn foo() !Foo {
return Foo{1}
}
fn bar() ?Foo {
return Foo{2}
}
fn main() {
match foo()!.a {
1 {
assert true
}
else {
assert false
}
}
match bar()?.a {
2 {
assert true
}
else {
assert false
}
}
}
```
=> cgen: fix generated code for matchexpr with call expr using propagation

vlib/compress/gzip/gzip.v, vlib/compress/gzip/gzip_test.v
Bug:
Flag location as per RFC1952 is 3 (4th byte). It is looking at position 4 (5th byte) instead.
Solution:
Fix by using the right location in the header which is 3 (4th byte)
Explanation:
To keep it simple, moved the header validation logic to a new function. Existing test should cover the test cases.
Added a new struct to hold the gzip header elements. This validation function can be used independently as well (that's why made it public)
Added constants for the flags to improve readability without comments.
=> gzip: fix flag location in header

cmd/tools/vast/vast.v, vlib/v/ast/ast.v, vlib/v/checker/infix.v
This PR is to solve a problem with infix expressions that popped up whilst developing a new backend.
There is a discrepancy between the resulting type of an infix expression inside the checker and backends.
```v
int + i64 == int // cgen: uses the type on the left hand side
int + i64 == i64 // checker: type promotion, returned value of Checker.expr()
```
For example `cgen` takes the type of the left hand side as the resulting type of the expression, but the checker performs type promotion. It is okay for the checker to do this, however the promoted type is not exposed to/filled in on the infix expression itself.
So the checker can run `c.expr(InfixExpr)` and use that resulting type as the type of the infix expression, but compiler backends will only have `left_type` and `right_type` …
=> checker, ast: field `promoted_type` for `InfixExpr`

vlib/v/ast/ast.v, vlib/v/checker/orm.v, vlib/v/checker/tests/orm_insert_object_with_mismatched_type_error.out, vlib/v/checker/tests/orm_insert_object_with_mismatched_type_error.vv, vlib/v/checker/tests/orm_using_undefined_object_in_insert_error.out, vlib/v/checker/tests/orm_using_undefined_object_in_insert_error.vv, vlib/v/parser/sql.v
Fixes #12425 
And detect using undefined variables as an inserting object.
=> orm: detect type mismatching on inserting an object

vlib/sync/once.v
=> docs: separate code block with a space (`fn (Once) do_with_param`)

examples/dynamic_library_loader/modules/library/library.v, examples/dynamic_library_loader/use.v, examples/dynamic_library_loader/use_test.v, vlib/dl/README.md, vlib/dl/loader.v, vlib/dl/loader/README.md, vlib/dl/loader/loader.v, vlib/dl/loader/loader_test.v
This PR adds a struct to optimize dynamic loading of libraries when the paths are multiple. Also simplifies all usage of vlib/dl. Also makes it possible to look for paths at runtime using env vars. In the example bellow it will use the env var `LIB_PATH`
```v
import dl.loader
// Load a library from a list of paths
const default_paths = [
'not-existing-dynamic-link-library'
// 'C:\\Windows\\System32\\shell32.dll',
'shell32',
]
fn main() {
mut dl_loader := loader.get_or_create_dynamic_lib_loader(
key: 'LibExample'
env_path: 'LIB_PATH'
paths: default_paths
)!
defer {
dl_loader.unregister()
}
sym := dl_loader.get_sym('CommandLineToArgvW')!
assert !isnil(sym)
}
```
=> vlib/dl: Add DynamicLibLoader to simplify libraries dl

vlib/v/parser/fn.v, vlib/v/parser/tests/argumented_op_overloading_fn_decl_err.out, vlib/v/parser/tests/argumented_op_overloading_fn_decl_err.vv, vlib/v/parser/tests/argumented_op_overloading_fn_op_overloaded_decl_err.out, vlib/v/parser/tests/argumented_op_overloading_fn_op_overloaded_decl_err.vv
Fixes https://github.com/vlang/v/issues/17073
=> parser: add better errors for fn decl of argumented operator overloading

examples/gg/cursor.v, examples/pendulum-simulation/modules/sim/anim/app.v, vlib/gg/gg.c.v, vlib/gg/gg.js.v
This PR sets
* `Context.user_data` (if the user didn't set it), and
* `Context.window.user_data`
as before, but late, when `Context.run()` is called, rather than on initial setup of the `Context` returned by `new_context()`. 
Currently, `new_context()` returns a `Context` which holds a reference to itself in a field inside itself. So the assumption currently is that the reference will still be correct at the time `Context.run()` is called. This is problematic when embedding the `Context` in another struct, which necessarily *copies* it.
E.g., in the V UI library we're looking at doing this:
```v
pub struct DrawDeviceContext {
gg.Context
// ...
}
```
Setting up a new `DrawDeviceContext` would look something like:
```v
mut dd := DrawDeviceContext{
Context: gg.new_context(
// ...
)
//...
} …
```
=> gg: setup ctx.window.user_data and ctx.user_data on ctx.run()

cmd/tools/vshare.v, cmd/v/v.v, vlib/v/help/other/other.txt, vlib/v/help/other/share.txt
Earlier today in the Discord, user [Sarctiann](https://github.com/Sarctiann) brought up being able to submit code with a command from V.
Add a way to submit code to the Playground to make it easier to share code.
Add `vshare.v` to `cmd/tools/` that allows users to submit code to the Playground from the terminal.
It is currently implemented by generating code from `os.read_file()` and then POSTing to `https://play.vlang.io/share`
There are currently two ways to check for errors: first it ensures the file has a `.v` extension and exists in the current directories `.` and `os.getwd()/src/`.
Upon successful share, it prints out a link to the Playground. 
Example:
https://play.vlang.io/?query=e8669cf46d
- `.vsh` and extensionless v shell files are currently ignored, an exception will have to …
=> tools: Share to Playground

cmd/tools/vtest-self.v, vlib/v/gen/c/cgen.v, vlib/v/tests/sumtype_as_cast_test.v
This PR fix sumtype as cast with calling twice (fix #17156).
- Fix sumtype as cast with calling twice.
- Add test.
```v
type Sum = int | string
fn ret_sum() Sum {
println('println')
return 22
}
fn main() {
_ := ret_sum() as int
}
println
```
=> cgen: fix sumtype as cast with calling twice

vlib/net/html/dom.v, vlib/net/html/parser.v, vlib/net/html/parser_test.v, vlib/net/html/tag.v
`\n` replacement was removed because it may break a multiline string, for example, JS code.
=> fix: html.parse() with empty string did panic, remove replacement `\n`

vlib/v/gen/c/cgen.v, vlib/v/tests/if_expr_nested_with_option_result_test.v
Fix for #17204.
* in `vlib/v/gen/c/cgen.v` in `expr_with_cast()`, check that a type with kind "function" is not an option/result, before casting to `(voidptr)`.
* `vlib/v/tests/if_expr_nested_with_option_result_test.v` has been updated to include an additional test for option/result function return types. This extra test previously caused generation of invalid C.
=> cgen: don't voidptr cast option/result functions, fixes #17204

doc/docs.md, vlib/builtin/string_test.v, vlib/net/websocket/websocket_client.v, vlib/v/checker/assign.v, vlib/v/checker/tests/var_decl_import_sym_conflict.out, vlib/v/checker/tests/var_decl_import_sym_conflict.vv, vlib/v/pref/should_compile.v
- Fix #17173, forbids variable name shadowing import symbol.
- Add output test
`var_decl_import_sym_conflict.vv`
```v
import arrays
fn x() {
arrays := 1
}
```
```v
var_decl_import_sym_conflict.vv:4:2: error: duplicate of an import symbol `arrays`
2 |
3 | fn x() {
4 |     arrays := 1
|     ~~~~~~
5 | }
```
This is a breaking change, serveral modules and tests are effected. Including vinix, stdlib etc.
=> v: forbid local variable names, shadowing imported module names

vlib/v/checker/fn.v, vlib/v/tests/if_guard_with_struct_option_fntype_field_test.v
This PR fix if guard with struct option fntype field (fix #17149).
- Fix if guard with struct option fntype field.
- Add test.
```v
struct Foo {
f ?fn (int) int
}
fn t1(a int) int {
println(a)
return a
}
fn main() {
foo := Foo{t1}
if ff := foo.f {
ret := ff(22)
} else {
assert false
}
}
22
```
=> checker: fix if guard with struct option fntype field (fix #17149)

vlib/v/gen/c/assign.v, vlib/v/tests/assign_option_of_struct_fntype_field_test.v
This PR fix assigning option of struct fntype field (fix #17223).
- Fix assigning option of struct fntype field.
- Add test.
```v
struct Foo {
mut:
bar ?fn (string) string
}
fn main() {
mut foo := Foo{}
foo.bar = fn (s string) string {
return s
}
if ff := foo.bar {
ret := ff('hello')
println(ret)
assert ret == 'hello'
}
}
hello
```
=> cgen: fix assigning option of struct fntype field (fix #17223)

vlib/v/checker/infix.v, vlib/v/checker/tests/sumtype_in_unknown_types_err.out, vlib/v/checker/tests/sumtype_in_unknown_types_err.vv
This PR check sumtype in unknown type (fix #17221).
- Check sumtype in unknown type.
- Add test.
```v
type Foo = FooA | FooB | FooC
struct FooA {}
struct FooB {}
struct FooC {}
fn main() {
foo := Foo(FooA{})
if foo in [FooB, FooC, FooD] {
panic('not possible')
} else {
println('ok')
}
}
tt1.v:11:25: error: unknown type `FooD`.
Did you mean `Foo`?
10 |     foo := Foo(FooA{})
11 |     if foo in [FooB, FooC, FooD] {
|                            ~~~~
12 |         panic('not possible')
13 |     } else {
```
=> checker: check sumtype in unknown type (fix #17221)

vlib/v/gen/c/cgen.v
This PR correct comments for expr_with_tmp_var().
=> cgen: correct comments for expr_with_tmp_var()

vlib/v/checker/for.v, vlib/v/checker/tests/for_in_mut_string.out, vlib/v/checker/tests/for_in_mut_string.vv
This PR check `for mut letter in 'abc' { x := letter - 1 }` (fix #17213).
- Check `for mut letter in 'abc' { x := letter - 1 }`.
- Add test.
```v
fn main() {
for mut letter in 'abc' {
bit := letter - 1
println(bit)
}
}
tt1.v:2:6: error: string type is immutable, it cannot be changed
2 |     for mut letter in 'abc' {
|         ~~~
3 |         bit := letter - 1
4 |         println(bit)
```
=> checker: check `for mut letter in 'abc' { x := letter - 1 }` (fix #17213)

vlib/v/checker/fn.v, vlib/v/tests/array_filter_of_fn_mut_arg_test.v
This PR fix array filter of fn mut argument (fix #17226).
- Fix array filter of fn mut argument.
- Add test.
```v
fn foo(mut arr []&int) {
arr = arr.filter(it != unsafe { nil })
}
fn main() {
mut arr := []&int{}
foo(mut arr)
println(arr.len)
assert arr.len == 0
}
0
```
=> checker: fix array filter of fn mut argument (fix #17226)

vlib/v/gen/c/infix.v, vlib/v/tests/for_in_mut_array_with_infix_expr_test.v
This PR fix for in mut array with infix expr (fix #17228).
- Fix for in mut array with infix expr.
- Add test.
```v
import net
fn main() {
ignore := net.TcpConn{}
mut array := []&net.TcpConn{}
for mut socket in array {
if ignore != socket {
println('not eq')
}
}
assert true
}
```
=> cgen: fix for in mut array with infix expr (fix #17228)

examples/call_v_from_c/README.md
It will make the executables more portable like windows. And with the way, you can run application without `LD_LIBRARY_PATH`.
It could be possible to work the way on MacOS. But I can not test it on a Mac. So, i updated only Linux instructions.
=> Examples: Call V From C - Use `-Wl,-rpath=.` instead of `LD_LIBRARY_PATH=.`

vlib/v/gen/c/cgen.v, vlib/v/tests/empty_interface_is_another_empty_interface_check_test.v
Fix #15691
This PR stops generating wrong func code when interface variants is zero:
```V
static inline bool I_main__Foo_is_I_main__Bar(main__Foo x) {
return ;
}
```
Because in this case currently `Foo is TypeNode` produces `false`, not the call for wrong function:
```V
void main__set_foo(main__Foo* foo) {
if (false) {
}
}
```
=> cgen: remove unused generated func

vlib/v/fmt/tests/anon_struct_as_param_with_fn_attrs_keep.vv, vlib/v/parser/struct.v
This PR fix fn attrs with anon struct param (fix #17264).
- Fix fn attrs with anon struct param.
- Add test.
anon_struct_as_param_with_fn_attrs_keep.vv
```v
// foo.v
[params]
fn hello(person struct { name string }) string {
if person.name == '' {
return 'Hello World!'
} else {
return 'Hello ${person.name}'
}
}
fn main() {
println(hello())
}
```
=> parser: fix fn attrs with anon struct param (fix #17264)

vlib/v/checker/infix.v, vlib/v/tests/generic_array_of_sumtype_push_test.v
This PR fix generic array of sumtype push operation (fix #17259).
- Fix generic array of sumtype push operation.
- Add test.
```v
type SumType = int | string
fn template_fn[T](a []T) []T {
mut b := []T{}
b << a
return b
}
fn main() {
ret1 := template_fn([SumType(1)])
println(ret1)
assert ret1.len == 1
assert ret1[0] == SumType(1)
ret2 := template_fn([SumType('hello')])
println(ret2)
assert ret2.len == 1
assert ret2[0] == SumType('hello')
}
[SumType(1)]
[SumType('hello')]
```
=> checker: fix generic array of sumtype push operation (fix #17259)

doc/docs.md
Non-GitHub markdown parsers can't process tables if there is no new line before. V markdown library doesn't parse it too.
Before: <img width="1448" alt="before" src="https://user-images.githubusercontent.com/104449470/217956273-20457c26-1b02-4427-a114-b6e3be97766a.png">
After: <img width="1448" alt="after" src="https://user-images.githubusercontent.com/104449470/217956286-1c63e3f8-5e81-475c-9287-9c7df89c740d.png">
=> docs: add a new line before tables

vlib/clipboard/x11/clipboard.c.v, vlib/net/http/header.v, vlib/v/checker/checker.v, vlib/v/checker/struct.v, vlib/v/checker/tests/nested_struct_with_required_attr_err.out, vlib/v/checker/tests/nested_struct_with_required_attr_err.vv, vlib/v/checker/tests/struct_field_generic_struct_unknown_type_err.out, vlib/v/checker/tests/struct_field_reference_type_err.out, vlib/v/checker/tests/struct_ref_fields_uninitialized_err.out, vlib/vweb/csrf/csrf_test.v
This PR check nested struct field with required attr (fix #10913, fix #16400, fix #16423).
- Check nested struct field with required attr.
- Add test.
```v
struct Foo {
bar Bar
}
struct Bar {
egg Egg
}
struct Egg {
name string [required]
}
fn main() {
f := Foo{}
println(f)
}
tt1.v:13:7: error: field `Egg.name` must be initialized
11 | 
12 | fn main() {
13 |     f := Foo{}
|          ~~~~~
14 |     println(f)
15 | }
```
```v
import mod
struct Bar{
foo mod.Foo
}
fn main(){
b := Bar{}
println(b)
}
tt1.v:8:7: error: struct `mod.Foo` is declared with a `[noinit]` attribute, so it cannot be initialized with `mod.Foo{}`
6 |
7 | fn main(){
8 |     b := Bar{}
|          ~~~~~
9 |     println(b)
10 | }
```
=> checker: check nested struct field with required attr (fix #10913)

vlib/v/gen/c/auto_str_methods.v, vlib/v/gen/c/fn.v
This PR fix c_fn_name() for mongo module.
```v
pub fn (document &C.bson_t) str() string {
return unsafe {
C.bson_as_json(document, 0).vstring()
}
}
```
Before: generated fn name: `bson_t_str()`.
Now: generated fn name: `C__bson_t_str()`.
- Use consistent function naming.
=> cgen: fix c_fn_name() for mongo module

vlib/v/gen/c/cgen.v, vlib/v/tests/cast_comptime_test.v
Fix #17193
This PR fixes wrong code generated for comptime variable on $for loop.
=> cgen: fix cast with comptime var

vlib/v/tests/option_test.v
There are tests for struct option fields only in `slow_tests/inout/`.
I think it is better to also exists as normal tests.
=> tests: add more tests for struct option fields in `vlib/v/tests/option_test.v`

CONTRIBUTING.md, README.md, ROADMAP.md, TESTS.md, doc/docs.md, doc/upcoming.md, doc/vscode.md, examples/regex/readme.md, tutorials/building_a_simple_web_blog_with_vweb/README.md, vlib/db/mysql/README.md, vlib/db/pg/README.md, vlib/dl/README.md, vlib/encoding/binary/README.md, vlib/eventbus/README.md, vlib/gx/README.md, vlib/js/README.md, vlib/rand/README.md, vlib/regex/README.md, vlib/strconv/format.md, vlib/v/TEMPLATES.md, vlib/v/help/FORMATTING.md, vlib/v/preludes/README.md, vlib/v/tests/project_with_tests_for_main/README.md, vlib/x/ttf/README.md
`NB`, `N.B.`, `Note`, `NOTE`, `Please note` replaced with `**Note**`
One common standard allows the reader to better navigate the material. 
Also "Note" is more understandable to non-native speakers than "NB".
Highlighting each note as a quote also makes it easier to notice them than if they are written in the same style as other text.
Example:
See also: https://github.com/community/community/discussions/16925
=> docs: unify format of notes

vlib/v/checker/fn.v, vlib/v/checker/tests/arraydecompose_arg2_err.out, vlib/v/checker/tests/arraydecompose_arg2_err.vv, vlib/v/checker/tests/arraydecompose_arg_err.out, vlib/v/checker/tests/arraydecompose_arg_err.vv, vlib/v/fmt/fmt.v, vlib/v/gen/c/comptime.v, vlib/v/gen/c/fn.v, vlib/v/tests/arraydecompose_nonvariadic_test.v
This PR allow passing array decompose to function calls.
```V
fn call[T](func_name string, args ...T) string {
return match func_name {
'foo' { foo(...args) }
'bar' { bar(...args) }
'baz' { baz(...args) }
'varargs' { varargs(...args) }
else { '' }
}
}
```
```V
assert call('foo', 10, 100) == '10 : 100'
assert call('bar', 1.1, 1.2, 1.3) == '1.1 : 1.2 : 1.3'
assert call('baz', 'test') == 'test'
assert call_any('foo_any', 10, 1.2, 'test') == "Any(10) : Any(1.2) : Any('test')"
assert call[Any]('varargs', 10, 1.2, 'test') == "Any(10) : Any(1.2) : Any('test')"
``` 
```V
fn varargs[T](args ...T) string {
assert args.len > 0
return args.map(it.str()).join(' : ')
}
```
```V
mut c := []Any{}
c << 10
c << 1.2
c << 'test'
assert varargs(...c) == "Any(10) : Any(1.2) : Any('test')"
```
```V
fn (t Test2) …
```
=> cgen, checker: allow array decompose on non-variadic func call (e.g call(...arr))

vlib/net/websocket/websocket_client.v, vlib/net/websocket/websocket_test.v
This pr calls the client's close events when closed abruptly
=> net.websocket: call close event

vlib/v/checker/str.v, vlib/v/tests/print_address_of_reference_struct_test.v
This PR fix printing address of reference struct (fix #17312).
- Fix printing address of reference struct.
- Add test.
```v
struct Foo {
abc int
}
fn main() {
foo := Foo{}
foo_ptr := &foo
println('${foo_ptr:p}')
println('${&foo:p}')
assert true
}
1fefe0
1fefe0
```
=> checker: fix printing address of reference struct (fix #17312)

vlib/v/gen/c/str.v, vlib/v/tests/print_reference_function_test.v
This PR fix printing reference function (fix #17303).
- Fix printing reference function.
- Add test.
```v
fn foo() {
}
fn main() {
println(&foo)
assert '${&foo}' == 'fn ()'
}
fn ()
```
=> cgen: fix printing reference function (fix #17303)

vlib/v/ast/str.v, vlib/v/checker/assign.v, vlib/v/checker/check_types.v, vlib/v/checker/checker.v, vlib/v/checker/comptime.v, vlib/v/checker/for.v, vlib/v/checker/if.v, vlib/v/checker/postfix.v, vlib/v/checker/struct.v, vlib/v/checker/tests/comptime_dump_fields_var_test.out, vlib/v/gen/c/assign.v, vlib/v/tests/comptime_sumtype_cast_test.v, vlib/x/json2/encoder.v
This PR does a minor clean up on ComptimeSelector checking.
Doing such clean up I've spotted some bugs so I've fixed them.
Improved $if comp branching detecting `field.unaliased_typ is TypeNode`, `field.is_* is TypeNode` and `field.typ is TypeNode` checking.
=> cgen, checker: fix comptimeselector resolution + if comptime branching improvement + comptimeselector cleanup

vlib/v/checker/struct.v, vlib/v/checker/tests/struct_unneeded_default.out, vlib/v/checker/tests/struct_unneeded_default.vv
Default value of `?int` is `none`.
https://github.com/vlang/v/blob/b13f7118ab6ae9afd78c92c312510eab20201973/vlib/v/tests/option_test.v#L183-L188
https://github.com/vlang/v/blob/b13f7118ab6ae9afd78c92c312510eab20201973/vlib/v/tests/option_test.v#L194-L196
But checker show warn for `= 0` not `= none`.
This PR fix it.
=> checker: fix warn of unnnecessary default value for optional

vlib/v/checker/str.v, vlib/v/tests/print_address_of_reference_int_test.v
This PR fix printing address of integer variable (fix #17326).
- Fix printing address of integer variable.
- Add test.
```v
fn main() {
a1 := 22
println('${&a1:p}')
a2 := 22.22
println('${&a2:p}')
a3 := `a`
println('${&a3:p}')
a4 := 'hello'
println('${&a4:p}')
a5 := true
println('${&a5:p}')
assert true
}
14efe5c
14efdd0
14efd4c
14efcb8
14efc27
```
=> checker: fix printing address of integer variable (fix #17326)

vlib/db/mysql/orm.v, vlib/db/pg/orm.v, vlib/db/sqlite/orm.v, vlib/mysql/orm.v, vlib/orm/orm.v, vlib/orm/orm_fn_test.v, vlib/orm/orm_insert_test.v, vlib/pg/orm.v, vlib/sqlite/orm.v
Fixes #17296 
The code generated for SQLite contained syntax errors because ORM generates one code for all databases. But it's wrong because, in detail, databases have syntax differences. I just added one `if` for SQL generation for now, but I'll refactor the whole ORM in the future.
=> orm: allow inserting empty objects

vlib/v/gen/c/comptime.v, vlib/v/tests/comptime_name_check_test.v
Fix #17317
Makes possible to do `$if field.name == "foo"`, `method.name` already works.
=> cgen: add comptime $if field.name checking

README.md
Formatted as other dependencies installation sections
For some Linux distros (Debian/Ubuntu based), you need to run this: `sudo apt install libxi-dev libxcursor-dev`. 
For Fedora/RH/CentOS, you need to run this: `sudo dnf install libXcursor-devel libXi-devel libX11-devel libglvnd-devel` . 
For NixOS, add these packages to your `environment.systemPackages`: `xorg.libX11.dev xorg.libXcursor.dev xorg.libXi.dev libGL.dev`
```bash
Debian/Ubuntu based:
sudo apt install libxi-dev libxcursor-dev
Fedora/RH/CentOS:
sudo dnf install libXcursor-devel libXi-devel libX11-devel libglvnd-devel
NixOS:
add xorg.libX11.dev xorg.libXcursor.dev xorg.libXi.dev libGL.dev to your environment.systemPackages manually
```
=> Improve graphic apps dependencies installation section

cmd/tools/vcheck-md.v
It will be used in documentation site
=> tools: support `play` and `play-test` for tagging code blocks in `v check-md file.md`

vlib/v/checker/fn.v, vlib/v/checker/tests/option_in_receiver_err.out, vlib/v/checker/tests/option_in_receiver_err.vv, vlib/v/parser/fn.v
This PR blocks using .question on receiver declaration
`fn (f ?Foo) test() {}`
=> parser: block option on receiver

vlib/v/checker/checker.v, vlib/v/tests/cast_none_to_option_test.v
This PR fixes none casting to option alias type.
`?i32(none)`
=> checker: fix alias cast to option type

vlib/arrays/arrays.v
One of the many changes needed to remove `C.` calls from "pure" V files.
=> arrays: replace C. usage with v routines

vlib/v/gen/c/array.v, vlib/v/tests/array_init_test.v
This PR fix array initilize with len and no default (fix #17358).
- Fix array initilize with len and no default.
- Add test.
```v
fn main() {
mut arr := []map[int]int{len: 3}
arr[0][0] = 0
arr[1][1] = 1
arr[2][2] = 2
println(arr)
}
[{0: 0}, {1: 1}, {2: 2}]
```
=> cgen: fix array initilize with len and no default (fix #17358)

cmd/tools/vcreate/vcreate.v, cmd/tools/vcreate/vcreate_test.v
`v init` behaviour fix : `v init` on an existing project, and V re-writes main.v file , the PR contains changes to fix the behavior where a if a src/main.v file already exists it will remain unmodified on running `v init` command.
The PR fixes the issue https://github.com/vlang/v/issues/17362
=>  fix for issue v init on an existing project, and V re-writes main.v file https://github.com/vlang/v/issues/17362

vlib/gg/gg.c.v
From sokol.sapp, delegate toggle_fullscreen and is_fullscreen to gg to avoid import sokol.sapp when using gg.
=> gg:  toggle_fullscreen and is_fullscreen added

vlib/v/checker/infix.v, vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/for.v, vlib/v/gen/c/infix.v, vlib/v/tests/none_checking_test.v
This PR allows option struct field to be checked against `none` and simplify the code generated for `assert option == none`.
```V
struct Test {
a ?int
}
a := ?int(none)
if a == none {
assert true
} else {
assert false
}
b := Test{}
if b.a == none {
assert true
} else {
assert false
}
c := ?Test(Test{})
if c?.a == none {
assert true
} else {
assert false
}
}
```
=> cgen, checker: fix none checking

README.md
Add `libgl-dev` to "Installation method" for Debian/Ubuntu based system
The original issue was reported on Discord, the help channel
=> README: update gg/sokol Ubuntu dependencies

vlib/v/checker/tests/anon_arg_redefinition_err.out, vlib/v/checker/tests/anon_arg_redefinition_err.vv, vlib/v/parser/fn.v
Fix missing redefinition checking for anon func.
```V
fn main() {
a := fn (a int, a int) {
}
}
```
=> parser: add anon func param redefinition checking

vlib/v/parser/expr.v, vlib/v/tests/channels_test.v
This PR fix channel pop with or expression (fix #17384).
- Fix channel pop with or expression.
- Add test.
```v
struct Iter[T] {
item chan T
}
fn new_iter[T](ch chan T) Iter[T] {
return Iter[T]{
item: ch
}
}
fn (self Iter[T]) next() ?T {
self.item.close()
ch := <-self.item or { return none }
return ch
}
fn main() {
ch := chan int{}
iter := new_iter[int](ch)
ret := iter.next() or {
println('channel closed')
assert true
return
}
println(ret)
assert false
}
channel closed
```
=> parser: fix channel pop with or expression (fix #17384)

vlib/v/gen/c/cgen.v
This PR makes a minor cleanup in expr().
- Remove useless comments in expr().
=> cgen: minor cleanup in expr()

vlib/v/gen/c/assign.v, vlib/v/parser/parser.v, vlib/v/tests/option_fixed_array_test.v
Fix #17398 
```V
fn test_simple() {
mut maybe_fixed1 := ?[3]int(none)
println(maybe_fixed1) // Option(error: none)
}
fn test_simple_assign() {
mut maybe_fixed1 := ?[3]int(none)
assert maybe_fixed1 == none
maybe_fixed1 = [1,2,3]!
assert maybe_fixed1 != none
println(maybe_fixed1) // Option([1, 2, 3])
}
fn test_array_fixed_param(args ?[2]int) ? {
println(args)
assert args?.len == 2
}
fn main() {
test_simple()
test_simple_assign()
test_array_fixed_param([1,2]!)
}
```
=> cgen: implement option fixed array

vlib/v/checker/match.v, vlib/v/tests/return_match_expr_with_custom_error_test.v
This PR fix returning match expr with custom error (fix #17406).
- Fix returning match expr with custom error.
- Add test.
```v
struct CustomError {
Error
}
fn ret() !string {
return match true {
true { 'ok' }
else { CustomError{} }
}
}
fn main() {
if r := ret() {
assert r == 'ok'
} else {
assert false
}
}
```
=> checker: fix returning match expr with custom error (fix #17406)

vlib/v/gen/c/struct.v, vlib/v/tests/nested_option_struct_init_test.v
This PR fix nested option struct init (fix #17415).
- Fix nested option struct init.
- Add test.
```v
struct Data {
a ?int
b ?int = 1
c ?int = none
}
struct Data2 {
d Data
}
fn main() {
d2 := Data2{}
println(d2)
assert d2.d.a == none
assert d2.d.b != none
assert d2.d.b? == 1
assert d2.d.c == none
}
tt1.v:4:11: warning: unnecessary default value of `none`: struct fields are zeroed by default
2 |     a ?int
3 |     b ?int = 1
4 |     c ?int = none
|              ~~~~
5 | }
6 |
Data2{
d: Data{
a: 0
b: 1
c: 0
}
}
```
=> cgen: fix nested option struct init (fix #17415)

vlib/os/debugger_darwin.c.v
The current weekly release doesn't build on macOS 11 or below. This PR should hopefully fix that.
The build error is the following ([full log](https://build.macports.org/builders/ports-11_x86_64-builder/builds/104908/steps/install-port/logs/stdio)):
```
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_vlang/vlang/work/vc-fed3800f83b51aba951a88e4d3d9d37ed5c10ee2/v.c:1943:
/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/sys/ptrace.h:99:42: error: unknown type name 'caddr_t'
int     ptrace(int _request, pid_t _pid, caddr_t _addr, int _data);
^
1 error generated.
make: *** [all] Error 1
```
This is the [corresponding patch file](https://github.com/macports/macports-ports/blob/83b6ae060066926be1f622ca7db0e73b4bb67530/lang/ …
=> os: add `#include <sys/types.h>` to debugger_darwin

vlib/v/gen/wasm/binaryen/binaryen.c.v
The current `#flags` for linking with `lbinaryen` does not support MacOS + homebrew. These changes add it in.
This change could get a fast pass through the CI since the CI only performs checks on Linux, not MacOS.
\- l-m
=> wasm: `binaryen.c.v` compile flags to assist darwin

doc/docs.md
While learning V I noticed a few things didn't work as shown in the docs and tested locally to verify. 
I also made some minor grammar / readability improvements while I was at it.
Changes:
The syntax `p = Point{10, 20}` is said to only work with 3 or less fields, but it works with larger amounts: `p = Point{1, 2, 3, 4, 5, 6, 7, 8, 9, 0}` compiles and runs with no error.
Best explained by reading the code in https://github.com/vlang/v/commit/bb1b519500165ef7998225463f4be80dbe757eaa. Due to the way smart casting with `is` works, the explicit cast inside of the `if a is IBar {...}` should not be necessary. The `if a is ...` smart casts `a` correctly as expected and calling `a.bar()` works fine without the explicit cast.
Let me know if there's anything else I should do for this PR.
=> docs: fix incorrect struct literal and interface smart cast errors

vlib/v/checker/for.v, vlib/v/tests/for_in_mut_mutable_app_field_test.v
Fixes a compiler panic found here:
https://discord.com/channels/592103645835821068/592294828432424960/1080794337216057424
=> checker: fix compiler panic for `for k, mut val in app.field[x].values {`

vlib/v/fmt/fmt.v, vlib/v/fmt/tests/comptime_warn_keep.vv
Fix #17445
```
felipe@~/github/v (master)$ v run bug.v
bug.v:2:2: warning: WARN
2 |     $compile_warn('WARN')
|     ~~~~~~~~~~~~~~~~~~~~~
3 | }
felipe@~/github/v (master)$ v fmt bug.v
fn main() {
.$compile_warn(WARN)
}
```
=> fmt: fix fmt for $compile_warn

vlib/v/checker/checker.v, vlib/v/checker/tests/option_return_call_non_opt_err.out, vlib/v/checker/tests/option_return_call_non_opt_err.vv, vlib/v/checker/tests/option_return_selector_non_opt_err.out, vlib/v/checker/tests/option_return_selector_non_opt_err.vv
Fix #17466
Add missing or-block expected type as using `or { f.field }`, `or { f.call() }`.
=> checker: fix or-block expected type checking

vlib/v/gen/c/fn.v, vlib/v/gen/c/testdata/sumtype_pass_by_reference.out, vlib/v/gen/c/testdata/sumtype_pass_by_reference.vv
Fixes #17160 
Passing `Expr(pair)` or `par.expr`, where `par.expr` is a sum type, generates the wrong C code, which is not compiled. And I had to insert `&` by hand in ORM fixes. I fixed It, but I need a good review because I first-time contribute to such "low-level" V things.
=> cgen: automatically passing sum types by reference if the argument expects it

vlib/.vdocignore
This will fix multiple issues relating to the conflicting builtin library files, where the WebAssembly `builtin` library would overwrite the main builtin.
=> doc: ignore `builtin/wasm`

vlib/v/checker/orm.v, vlib/v/parser/sql.v
=> checker && parser: remove redundant `&` for passing sum types after #17476

vlib/v/gen/c/auto_str_methods.v, vlib/v/tests/map_reference_value_test.v
This PR fix printing map reference value (fix #17492).
- Fix printing map reference value.
- Add test.
```v
fn main() {
mut m := map[string]&datatypes.Queue[i64]{}
println('${m}')
}
{}
```
=> cgen: fix printing map reference value (fix #17492)

vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/if.v, vlib/v/parser/if_match.v, vlib/v/tests/option_var_2_test.v
This PR fix option variable error (fix #17460, fix #17461).
- Fix option variable error.
- Add test.
```v
struct Foo {
name ?string
}
fn main() {
foo := Foo{}
other := foo.name
println(typeof(other).name)
if name := other {
println('with name: ${name}')
assert false
} else {
println('without name')
assert true
}
println(foo.name)
}
?string
without name
Option(error: none)
```
```v
struct Foo {
name ?string
}
fn main() {
foo := Foo{}
other := foo.name
mut counter := 0
val := other or {
counter++
'default'
}
assert val == 'default'
assert counter == 1
}
```
=> parser, cgen: fix option variable error (fix #17460)

vlib/v/gen/c/cgen.v
Add calls to all typeof functions for interfaces and sum-types in **debug** mode, to be able to call them in the debugger, otherwise the C compiler will optimize them
This will allow the IDEA plugin to add pretty-printers that output concrete types in the debugger.
For example:
=> cgen: add calls to all typeof functions for interfaces and sum-types 

vlib/v/ast/table.v, vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/tests/option_multi_return_test.v
Fix #17465
```V
fn tuple() ?(int, int) {
return 1, 2
}
fn tuple2() ?(string, int) {
return '', 2
}
fn tuple3() ?(?int, ?int) {
return none, none
}
fn tuple4() ?(?int, ?int) {
return none
}
fn test_tuple_1() {
a, b := tuple()
assert a == 1
assert b == 2
}
fn test_tuple_2() {
a, b := tuple2()
assert a == ''
assert b == 2
}
fn test_tuple_3() {
a, b := tuple3()
assert a == none
assert b == none
}
fn test_tuple_4() {
a, b := tuple4()
assert a == none
assert b == none
}
```
=> cgen: fix multi return with option type

vlib/v/checker/struct.v, vlib/v/tests/nested_option_struct_init_test.v
This PR fix nested option struct with required attr init (fix #17513).
- Fix nested option struct with required attr init.
- Add test.
```v
struct AA {
bb ?BB // defaults to none
}
struct BB {
x string [required]
}
fn main() {
aa := AA{}
println(aa)
assert aa.bb == none
}
AA{
bb: Option(error: none)
}
```
=> checker: fix nested option struct with required attr init (fix #17513)

vlib/v/checker/comptime.v, vlib/v/gen/c/comptime.v, vlib/v/gen/c/testdata/comptime_interface_field.out, vlib/v/gen/c/testdata/comptime_interface_field.vv
- Fix #17346, support interface field compile time reflection
- Add output test
`vlib/v/gen/c/testdata/comptime_interface_field.vv`
```v
interface User {
name string
age int
}
fn main() {
$for field in User.fields {
}
}
```
`vlib/v/gen/c/testdata/comptime_interface_field.out`
```v
name
age
```
=> v: support interface field compile time reflection

vlib/v/checker/comptime.v, vlib/v/tests/comptime_const_def_test.v
Fix #17521
Make possible:
```V
const (
buf_size = $if windows { os.max_path_len * 2 } $else { os.max_path_len }
)
```
=> checker: fix const init with comptime

vlib/v/gen/c/dumpexpr.v, vlib/v/tests/option_array_dump_in_generic_fn_test.v
=> cgen: fix dump option value on generic function

vlib/v/checker/checker.v, vlib/v/checker/tests/cast_to_interface_err.out, vlib/v/checker/tests/cast_to_interface_err.vv, vlib/v/checker/tests/infix_is_notis_interface_unimplemented_err.out, vlib/v/checker/tests/mut_receiver_wrong_return_type.out
This PR check error of casting to interface (fix #17522).
- Check error of casting to interface.
- Add test.
```v
fn main() {
dump(foo()!)
}
fn foo() !int {
// do something
if true {
return 1
}
return my_error()
}
struct CustomError {
pub:
msg  string
code int
}
fn my_error() IError {
return IError(CustomError{})
}
tt1.v:20:9: notice: `CustomError` doesn't implement method `msg` of interface `IError`. The usage of fields is being deprecated in favor of methods.   
18 |
19 | fn my_error() IError {
20 |     return IError(CustomError{})
|            ~~~~~~~~~~~~~~~~~~~~~
21 | }
tt1.v:20:9: error: `CustomError` does not implement interface `IError`, cannot cast `CustomError` to interface `IError`
18 |
19 | fn my_error() IError {
20 |     return IError(CustomError{}) …
```
=> checker: check error of casting to interface (fix #17522)

vlib/v/gen/c/array.v, vlib/v/tests/option_array_init_test.v
=> cgen: fix default initialization of option array with none values

cmd/tools/vast/vast.v, doc/docs.md, vlib/builtin/array_test.v, vlib/rand/rand.v, vlib/v/ast/ast.v, vlib/v/gen/c/array.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/infix.v, vlib/v/gen/c/str.v, vlib/v/gen/c/testdata/array_init_no_error.vv, vlib/v/gen/native/amd64.v, vlib/v/parser/containers.v, vlib/v/slow_tests/inout/printing_const_array.vv, vlib/v/tests/array_with_it_test.v, vlib/v/tests/closure_generator_test.v, vlib/v/tests/for_in_ref_arr_test.v, vlib/v/tests/generic_fn_infer_fn_type_argument_test.v
- Fix #17541, avoid confusion by renaming `it` variable in array initialization syntax into `index`.
=> v: Rename variable it into index

vlib/v/checker/checker.v, vlib/v/checker/tests/wrong_option_unwrap_err.out, vlib/v/checker/tests/wrong_option_unwrap_err.vv, vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/tests/option_unwrap_assign_test.v
Fix #17549
Fix #17548
It also fixes missing check for:
```V
fn main() {
a := ?string('c')
b := a or { none }
println(b)
}
```
=> cgen: fix option unwrap on assignment

vlib/v/gen/c/str.v, vlib/v/tests/option_void_fn_return_test.v
Fix #17472
```V
fn foo() ? {
return none
}
println(foo()) // <none>
assert true
}
```
=> cgen: fix fn option-only return print

vlib/v/gen/c/fn.v, vlib/v/tests/generic_array_of_alias_test.v
This PR fix generic array of alias .str() (fix #17569).
- Fix generic array of alias .str().
- Add test.
```v
type Distance = int
struct Foo {
field datatypes.LinkedList[Distance]
}
fn main() {
foo := Foo{}
println(foo)
assert '${foo.field}' == '[]'
}
Foo{
field: []
}
```
=> cgen: fix generic array of alias .str() (fix #17569)

vlib/v/checker/assign.v, vlib/v/checker/checker.v, vlib/v/checker/tests/comptime_dump_fields_var_test.out, vlib/v/gen/c/assign.v, vlib/v/gen/c/dumpexpr.v, vlib/v/tests/option_array_dump_in_generic_fn_test.v, vlib/v/tests/option_dump_test.v
```V
a := ?int(0)
b := dump(a)
println(b)
c := ?int(none)
d := dump(c)
println(d)
fn test_comptime() ? {
v := Test{}
$for f in Test.fields {
a := dump(v.$(f.name))
b := v.$(f.name)
dump(a)
dump(b)
}
}
```
```
[bug.v:2] a: Option(0)
Option(0)
[bug.v:7] c: Option(error: none)
Option(error: none)
```
=> cgen, checker: fix dump() to return option values

vlib/v/gen/c/assign.v
This PR fix assign option value using propagate option (fix #17576).
- Fix assign option value using propagate option.
```v
fn main() {
a := ?int(none)
y := a?
println(y)
}
V panic: option not set (none)
v hash: 71c3b66
```
=> cgen: fix assign option value using propagate option (fix #17576)

vlib/builtin/string.v, vlib/builtin/string_test.v
- This PR adds `rsplit_any`, `rsplit`, and `rsplit_nth` functions to `builtin`.
- Introduces new function `split_once` and `rsplit_once` to return pair of string (see [rust's impl](https://doc.rust-lang.org/std/primitive.str.html#method.split_once) for more info)
=> builtin: Add `rsplit` functions

README.md
I'm seeing more and more IntelliSense questions on Discord, so I think it's worth adding the info to the main README.
=> readme: add section about editor plugins and IntelliSense

vlib/v/checker/struct.v, vlib/v/checker/tests/struct_embed_required_field_err.out, vlib/v/checker/tests/struct_embed_required_field_err.vv, vlib/v/checker/tests/struct_ref_fields_uninitialized_err.out
This PR check struct embed required field (fix #17587).
- Check struct embed required field.
- Add test.
```v
struct Foo {
foo u8 [required]
}
struct Bar {
Foo
foo u8 [required]
}
fn main() {
b := Bar {
foo: 1
}
println(b)
}
tt1.v:11:7: error: field `Foo.foo` must be initialized
9 |
10 | fn main() {
11 |     b := Bar {
|          ~~~~~
12 |         foo: 1
13 |     }
```
=> checker: check struct embed required field (fix #17587)

vlib/v/checker/fn.v, vlib/v/tests/generic_struct_test.v
=> checker: fix missing re-check of recursive generic function 

vlib/sync/channels.c.v, vlib/sync/empty_struct_chan_init_test.v, vlib/v/gen/c/cgen.v
This PR fix error of empty struct channel (fix #17556).
- Fix error of empty struct channel.
- Add test.
```v
struct User {
}
fn main() {
user_ch := chan User{cap: 10}
println(user_ch)
assert true
}
chan User{cap: 10, closed: 0}
```
=> sync: fix error of empty struct channel (fix #17556)

vlib/builtin/string.v, vlib/builtin/string_test.v
- This PR refactors `string_test.v` by removing `println` invocations in test functions.
- And adds `[inline]` attribute to appropriate functions that has small function body.
=> builtin: string test refactor, string functions inlining

vlib/readline/readline_darwin.c.v, vlib/readline/readline_default.c.v
The current code only implements raw mode features for Linux. This patch split the definition of the termios structure per os, allowing to use of the Linux code with other Unixes, bringing the full API to them.
The termios definition for Linux was also not matching the kernel definition (by one byte, which would have been padded), so it was updated.
As it would appear that while `qnx` is listed as an OS using `_qnx.c.v` is not working as should (the file is always included), the QNX definition was included but left out commented.
The code was only tested for OSX (M1) and Linux (aarch64 qemu).
=> readline: linux features to other *nix 

vlib/crypto/internal/subtle/aliasing.v, vlib/v/ast/ast.v, vlib/v/fmt/fmt.v, vlib/v/fmt/tests/infix_expr_with_comments_keep.vv, vlib/v/parser/expr.v, vlib/v/parser/parser.v
This PR fix fmt error of infix expr with comments (fix #17560).
- Fix fmt error of infix expr with comments.
- Add test.
infix_expr_with_comments_keep.vv
```v
fn main() {
a := 4 // comment1
+ /* comment2 */ 6
b := 5 /* comment1 */ + // comment2
6
c := 4 /* comment1 */ + /* comment2 */ 6 // comment3
}
```
=> ast, parser, fmt: fix fmt error of infix expr with comments (fix #17560)

vlib/os/os.v, vlib/v/pref/os.v, vlib/v/pref/should_compile.v
This patch should be a resolution for https://github.com/vlang/v/issues/17606
As I do not run QNX I can not check if works, but a _qnx.c.v file stops to cause a compilation error.
=> build: handle _qnx.c.v

vlib/v/gen/c/struct.v, vlib/v/tests/option_struct_init_with_ref_opt_test.v
This PR fix option struct init with reference option (fix #17616).
- Fix option struct init with reference option.
- Add test.
```v
struct Node {
value int
mut:
prev ?&Node = none
next ?&Node = none
}
struct LinkedList {
mut:
head ?&Node = none
tail ?&Node = none
}
pub fn (mut l LinkedList) push(value int) {
node := &Node{
value: value
prev: l.tail
}
if l.head == none {
l.head = node
} else {
mut tail := l.tail or { panic('head is not none but tail is') }
tail.next = node
}
l.tail = node
}
pub fn (mut l LinkedList) pop() int {
tail := l.tail or { panic('Empty list not supported') }
if tail.prev == none { // single element
l.head = none
l.tail = none
} else { // multiple elements
mut prev := tail.prev or { panic('prev cannot be none at this point') }
prev.next = none
l.tail = prev
}
return …
```
=> cgen: fix option struct init with reference option (fix #17616)

vlib/v/checker/fn.v, vlib/v/checker/tests/option_fn_field_err.out, vlib/v/checker/tests/option_fn_field_err.vv
Fix #17148
Fix #17627
```V
struct Foo {
f ?fn(int)
}
fn main() {
foo := Foo{}
foo.f(1)
}
```
```
vlib/v/checker/tests/option_fn_field_err.vv:7:6: error: Option function field must be unwrapped first
6 |     foo := Foo{}
7 |     foo.f(1)
|         ~~~~
8 | }
```
=> checker: fix missing option function field checking

doc/docs.md, vlib/v/builder/cc.v, vlib/v/builder/msvc_windows.v, vlib/v/help/build/build-c.txt, vlib/v/pref/pref.v
- pref: support `-ldflags` in addition to `-cflags` too
- document the new -ldflags option
=> v: support `-ldflags` in addition to `-cflags` (allow adding C options *after* other C option, similar to `LDFLAGS`)

vlib/v/parser/containers.v, vlib/v/parser/expr.v, vlib/v/parser/fn.v, vlib/v/parser/parser.v, vlib/v/parser/struct.v, vlib/v/tests/option_import_struct_test.v
Fix #17609
Fix module handling on cast and struct initialization with full name (module prefix).
=> parser: fix option struct init decl with module prefix

vlib/os/os.v, vlib/os/os_js.js.v, vlib/os/os_nix.c.v, vlib/os/os_windows.c.v, vlib/os/signal.js.v
Make os.temp_dir() always return a full path name on windows.
=> os: return the long path for os.temp_dir() on windows

vlib/net/urllib/urllib_test.v, vlib/net/urllib/values.v, vlib/net/urllib/values_test.v
The `net.urllib.Values.get` method's return type is changed to an option type. 
This allows for a better handling of missing keys and should allows to distinguish keys with empty values from actual missing keys.
=> urllib: change Values.get to return option type

vlib/v/ast/table.v, vlib/v/ast/types.v, vlib/v/checker/check_types.v, vlib/v/gen/c/cgen.v, vlib/v/parser/parse_type.v, vlib/v/tests/generics_struct_init_with_inconsistent_generic_types_7_test.v
This PR fix generic struct init with inconsistent generic types (fix #17555).
- Fix generic struct init with inconsistent generic types.
- Add test.
```v
struct MyData[T] {
}
fn myfunc[U](a MyData[U]) string {
println(a)
return '${a}'
}
fn main() {
d1 := MyData[int]{}
r1 := myfunc(d1)
println(r1)
assert r1 == 'MyData[int]{}'
}
MyData[int]{}
MyData[int]{}
```
=> ast, parser, cgen: fix generic struct init with inconsistent generic types (fix #17555)

vlib/v/checker/fn.v, vlib/v/checker/tests/missing_export_attr_arg_err.out, vlib/v/checker/tests/missing_export_attr_arg_err.vv
Fix #17625
```V
vlib/v/checker/tests/missing_export_attr_arg_err.vv:1:1: error: missing argument for [export] attribute
1 | [export]
| ~~~~~~~~
2 | fn foo() string{
3 |     return "foo"
```
=> checker: fix missing check for [export] attr without parameter

vlib/v/checker/assign.v, vlib/v/checker/tests/option_var_assign_err.out, vlib/v/checker/tests/option_var_assign_err.vv
=> checker: fix missing check for wrong assignment: non-option to option type

vlib/v/gen/c/assign.v, vlib/v/tests/unsafe_fixed_array_test.v
Fix #17642
```V
fn test_fixed_array_on_unsafe_int() {
x := [3]int{}
y := unsafe { x }
assert x == [0, 0, 0]!
}
fn test_fixed_array_on_unsafe_string() {
x := [3]string{init: ''}
y := unsafe { x }
assert x == ['', '', '']!
}
```
=> cgen: fix fixed array assignment from unsafe block

vlib/v/gen/c/assign.v, vlib/v/tests/option_multi_ret_test.v
Fix #17672
```V
struct Test {
mut:
a ?int
b ?string
c ?[]int
}
fn mr_1() (?int, string, []int) {
return 0, 'foo', [1]
}
fn mr_2() (?int, string, []int) {
return none, 'foo', [1]
}
fn mr_3() ([]?int, ?int) {
a := ?int(0)
return [a], none
}
fn test_mr_first_option() {
mut t := Test{}
t.a, t.b, t.c = mr_1()
a := dump(t.a)
b := dump(t.b)
c := dump(t.c)
assert a? == t.a?
assert b? == t.b?
assert c? == t.c?
}
fn test_mr_first_option_none() {
mut t := Test{}
t.a, t.b, t.c = mr_2()
a := dump(t.a)
b := dump(t.b)
c := dump(t.c)
assert a == none
assert b? == t.b?
assert c? == t.c?
}
fn test_mr_first_option_array() {
a, b := mr_3()
t := a[0]
assert t? == 0
assert b == none
}
```
=> cgen: fix multi return assignment with option

vlib/v/gen/c/auto_str_methods.v, vlib/v/gen/c/str.v, vlib/v/tests/option_print_ptr_test.v
Fix #17632
```V
struct One {
thing string = 'thing 1'
}
struct Two {
maybe_one ?&One
}
fn main() {
a := Two{}
println(a)
println(Two{})
dump(Two{})
}
```
=> cgen: fix option ptr printing

vlib/json/json_encode_with_ptr_test.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/json.v
Fix #17610
```V
module main
import json
struct User {
name string
}
user	&User //
users	map[string]User 
users2	map[string]&User 
}
fn main() {
user := User{
name: "foo"
}
data := MyStruct{
user: &user
users: { "keyfoo": user}
users2: { "keyfoo": &user}
}
assert json.encode(data) == '{"user":{"name":"foo"},"users":{"keyfoo":{"name":"foo"}},"users2":{"keyfoo":{"name":"foo"}}}'
}
```
=> json: support for &ptr types

vlib/v/checker/fn.v, vlib/v/checker/tests/generic_fn_call_arg_mismatch_err.out, vlib/v/checker/tests/generic_fn_call_arg_mismatch_err.vv, vlib/v/token/keywords_matcher_trie.v, vlib/x/json2/encoder.v
This PR check generic fn call argument type mismatch (fix #17018).
- Check generic fn call argument type mismatch.
- Add test.
- Fix all the related errors.
```v
import strings
fn my_fn[T]() {
mut b := strings.new_builder(16)
var := T{}
ptr := &var
b.write_string(*ptr)
}
fn main() {
my_fn[int]()
}
tt1.v:7:17: error: cannot use `int` as `string` in argument 1 to `strings.Builder.write_string`
5 |     var := T{}
6 |     ptr := &var
7 |     b.write_string(*ptr)
|                    ~~~~
8 | }
9 |
```
=> checker: check generic fn call argument type mismatch (fix #17018)

vlib/v/gen/c/auto_str_methods.v, vlib/v/gen/c/infix.v, vlib/v/tests/option_push_array_opt_test.v
Fix #17654
```V
mut vals := []?string{cap: 4}
vals << none
vals << 'a'
vals << 'b'
vals << 'c'
```
=> cgen: fix push operation on array of option

vlib/v/gen/c/auto_str_methods.v, vlib/v/tests/ptr_str_method_test.v
Fix #17641
```V
module main
struct Name {
age int = 222
}
fn (n &Name) str() string {
return n.age.str()
}
fn test_str_method_with_ptr() {
name := &Name{}
mut mp := map[string]&Name{}
mp['aaa'] = name
assert mp.str() == "{'aaa': 222}"
assert name.str() == '222'
}
```
=> cgen: fix argument dereference for str method when receiver is ptr

vlib/v/gen/c/cgen.v, vlib/v/tests/selectorexpr_alias_to_ptr_test.v
Fix #17634
```V
struct ABC {
data int
}
type RABC = &ABC
fn do(abc RABC) {
println(abc.data)
}
fn main() {
abc := &ABC{
data: 5
}
do(abc)
}
```
=> cgen: fix selector expr with alias to ptr

vlib/v/checker/struct.v, vlib/v/checker/tests/wrong_fn_init_err.out, vlib/v/checker/tests/wrong_fn_init_err.vv
Fix #17650
```V
type MyCallback = fn () string
fn main() {
a := MyCallback{}
println(a)
}
```
=> checker: fix anon fn initialization as struct-like

vlib/vweb/vweb.v
add `msg: false` to `vweb.RunParams` to disable `[VWeb] Running app on ...`
refer to issue #17622
add an option `msg: false` to RunParams to disable the message
`msg` is `true` by default
example: 
```
vweb.run_at(&App{}, vweb.RunParams{
host: "localhost"
port: 8080
family: .ip
msg: false
})
```
=> vweb: add an option to disable startup message

vlib/v/gen/c/fn.v, vlib/v/tests/spawn_method_on_generic_struct_test.v
This PR fix spawning method on generic struct (fix #17631).
- Fix spawning method on generic struct.
- Add test.
```v
struct Gen[T] {
data T
}
fn (g Gen[T]) process() string {
th := spawn g.internal()
r := th.wait()
return r
}
fn (g Gen[T]) internal() string {
println(g.data * g.data)
return '${g.data * g.data}'
}
fn main() {
g := Gen[int]{
data: 5
}
r1 := g.process()
assert r1 == '25'
r2 := g.internal()
assert r2 == '25'
}
25
25
```
=> cgen: fix spawning method on generic struct (fix #17631)

vlib/v/gen/c/cgen.v, vlib/v/gen/c/index.v, vlib/v/tests/map_complex_array_test.v
This PR fix map of complex array (fix #17646).
- Fix map of complex array.
- Add test.
```v
struct Instr {
mut:
a int
b int
}
fn main() {
mut map1 := map[string][]&Instr{}
instr := &Instr{
a: 1
b: 2
}
arr := [instr]
map1['Hello'] = arr
map1['Hello'][0].a = 2
println(map1['Hello'][0].a)
assert map1['Hello'][0].a == 2
assert map1['Hello'][0].b == 2
}
2
```
=> cgen: fix map of complex array (fix #17646)

vlib/net/http/http.v
No need to make the function return an optional Request. It always returns a proper Request object.
=> net: update new_request from http.v

vlib/json/json_encode_with_mut_test.v, vlib/v/gen/c/json.v
Fix #17689
```V
module main
import json
pub enum PlatformType {
unknown
osx
ubuntu
alpine
}
pub enum CPUType {
unknown
intel
arm
intel32
arm32
}
[heap]
pub struct Node {
pub:
name string = 'mymachine'
pub mut:
platform    PlatformType
cputype     CPUType
done        map[string]string
environment map[string]string
}
pub fn (mut node Node) save() ! {
data :=  json.encode(node)
println(data)
}
fn main() {
mut n := Node {
platform: .osx
cputype: .unknown
}
n.save() or {
panic(err)
}
}
```
=> json: fix ptr field access

vlib/strconv/format_test.v, vlib/strconv/vprintf.c.v
This PR fix v_sprintf with '%%' (fix #17638).
- Fix v_sprintf with '%%'.
- Add test.
```v
import strconv
fn main() {
n := 69
s := strconv.v_sprintf('%d is 100%% awesome', n)
println(s)
assert s == '69 is 100% awesome'
}
69 is 100% awesome
```
=> strconv: fix v_sprintf with '%%' (fix #17638)

vlib/vweb/assets/assets.v, vlib/vweb/assets/assets_test.v
When using the asset manager the `href` and `src` values will always be the filename. This doesn't work when you are mounting a static directory under another name. 
For example let's say you have vweb application with a static folder mounted at the root. And you have a css file in "static/css/main.css".
```v
app.handle_static('static', true)
```
The `href` and `src` values are relative: "static/css/main.css" becomes `href="static/css/main.css"`. If you are at a subpath let's say "/auth/login" the browser will look for the css file in "/auth/static/css/main.css"
With `add_css_as` you can make sure the href will always be correct.
```v
mut am := assets.new_manager()
am.add_css_as('static/css/main.css', '/css/main.css')
css_links := am.include_css(false)
```
Now the href will just be …
=> vweb.assets: add option for custom href and src attribute values

vlib/v/gen/c/fn.v, vlib/v/tests/closure_with_fixed_array_var_test.v
This PR fix closure with fixed array variable (fix #17700).
- Fix closure with fixed array variable.
- Add test.
```v
struct Crasher {
value int
}
fn crash(c [1]Crasher) fn () int {
return fn [c] () int {
println(c[0].value)
return c[0].value
}
}
fn main() {
crash_fn := crash([Crasher{1}]!)
ret := crash_fn()
}
1
```
=> cgen: fix closure with fixed array variable (fix #17700)

cmd/tools/vls.v
Single backslashes in file path string causes json parse error, converting to double slashes should fix this
=> Fix vls error unexpected token U in JSON

vlib/v/checker/struct.v, vlib/v/checker/tests/generic_interface_err.out, vlib/v/checker/tests/generics_struct_init_err.out, vlib/v/checker/tests/interface_generic_err.out, vlib/v/tests/generics_struct_types_infer_test.v
This PR implement infering generic struct types.
- Implement infering generic struct types.
- Add test.
```v
struct Foo[T, U] {
a T
b U
}
fn main() {
st11 := Foo{'two', 2}
println(st11.a)
println(st11.b)
assert st11.a == 'two'
assert st11.b == 2
st12 := Foo{
a: 'two'
b: 2
}
println(st12.a)
println(st12.b)
assert st12.a == 'two'
assert st12.b == 2
st21 := Foo{1, 'one'}
println(st21.a)
println(st21.b)
assert st21.a == 1
assert st21.b == 'one'
st22 := Foo{
a: 1
b: 'one'
}
println(st22.a)
println(st22.b)
assert st22.a == 1
assert st22.b == 'one'
}
two
2
two
2
1
one
1
one
```
=> checker: implement infering generic struct types

vlib/v/checker/match.v, vlib/v/checker/tests/match_cond_with_parenthesis_err.out, vlib/v/checker/tests/option_with_match_err.out, vlib/v/checker/tests/option_with_match_err.vv, vlib/v/gen/c/match.v, vlib/v/tests/option_match_test.v
Fix #17711
```V
fn main() {
mut a := ?int(12)
match a? {
12 { println(a) }
//none { println('none') }
else { println('else') }
}
match a {
none { println('none') }
else { println('else') }
}
a = none
match a {
none { println('none') }
else { println('else') }
}
mut b := ?string('aaa')
match b? {
'aaa' { println(b) }
else { println('else') }
}
match b {
none { println('none') }
else { println('else') }
}
b = none
match b {
none { println('none') }
else { println('else') }
}
}
```
Added error when using option type without unwrap to check against value different of `none`:
```V
bug.v:4:8: error: `match` expression with Option type only checks against `none`, to match its value you must unwrap it first `var?`
2 |     mut a := ?int(12)
3 |     match a {
4 |         12 { println(a) }
| …
```
=> cgen: fix match with option type

.github/workflows/v_apps_and_modules_compile_ci.yml, doc/docs.md, examples/vweb_fullstack/src/auth_services.v, examples/vweb_fullstack/src/user_services.v, examples/vweb_orm_jwt/src/auth_services.v, examples/vweb_orm_jwt/src/user_services.v, vlib/db/sqlite/sqlite_orm_test.v, vlib/orm/orm_insert_test.v, vlib/orm/orm_sql_or_blocks_test.v, vlib/orm/orm_test.v, vlib/v/parser/sql.v, vlib/v/tests/orm_sub_array_struct_test.v, vlib/v/tests/orm_sub_struct_test.v, vlib/v/tests/sql_statement_inside_fn_call_test.v
This is the first PR from a series of breaking changes for `V ORM`, which makes it more consistent in working with types. Before this PR, `V ORM` didn't allow us to check a returned object from `select` for existence. Everything we could do is compare struct id with 0. It gave no guarantees and required the id field. Now, `V ORM` always returns an array for non-count queries. And you just can check the length of the result. If it is 0, `select` didn't return anything.
Example:
```v
users := sql db {
select from User
}
no_users := users.len == 0
```
=> parser: V ORM returns an array for non-count queries

vlib/v/ast/types.v, vlib/v/tests/embed_struct_name_test.v
Fix #17721
`MyTemplate[MyEnum]` was generating wrong code on struct declaration.
=> type: fix embed name with enum as generic struct type

vlib/v/checker/assign.v, vlib/v/checker/checker.v, vlib/v/checker/if.v, vlib/v/checker/tests/if_diff_expected_type_err.out, vlib/v/checker/tests/if_diff_expected_type_err.vv
Fix #17687
```V
const (
some_runes       = [`a`, `b`, `c`]
some_other_runes = [`c`, `b`, `a`]
)
fn main() {
runes := if true { &some_runes } else { some_other_runes }
println(runes)
}
```
=> checker: fix missing type mismatch with ptr types

vlib/v/ast/ast.v, vlib/v/fmt/fmt.v, vlib/v/gen/golang/golang.v, vlib/v/parser/comptime.v, vlib/v/parser/containers.v, vlib/v/parser/expr.v, vlib/v/parser/parser.v, vlib/v/slow_tests/inout/generic_fn_with_array_arg.vv, vlib/v/tests/comptime_generic_test.v, vlib/v/tests/comptime_in_type_checking_test.v, vlib/v/tests/comptime_kinds_test.v, vlib/v/tests/comptime_map_test.v, vlib/v/tests/comptime_option_field_test.v, vlib/v/tests/comptime_sumtype_cast_test.v, vlib/v/tests/comptime_type_test.v, vlib/v/tests/fn_call_comptime_array_arg_test.v, vlib/v/tests/generic_fn_with_comptime_for_test.v, vlib/v/tests/generic_struct_test.v, vlib/v/tests/method_call_var_comp_test.v, vlib/v/tests/option_compvar_val_test.v, vlib/v/tests/option_fn_test.v, vlib/v/tests/unaliased_typ_checking_test.v, vlib/v/tests/var_type_is_checking_test.v, vlib/x/json2/encoder.v, vlib/x/json2/json2.v
This PR turns compile-time type ($int, $enum, $map, etc) lowercased.
```V
interface Abc {}
enum EnumTest {
a
b
}
type Alias = Abc
type Sumtype = int | string
struct Foo {}
struct Test {
a Abc
b map[string]string
c []int
d EnumTest
e int
f f64
g Alias
h Foo
i fn ()
j Sumtype
k ?int
}
fn test_comptime_types() {
mut i := 0
mut a := 0
mut m := 0
mut e := 0
mut c_int := 0
mut c_float := 0
mut c_alias := 0
mut c_struct := 0
mut c_fn := 0
mut c_sum := 0
mut c_option := 0
$for f in Test.fields {
$if f.typ is $alias {
c_alias++
} $else $if f.typ is $interface {
i++
} $else $if f.typ is $array {
a++
} $else $if f.typ is $map {
m++
} $else $if f.typ is $enum {
e++
} $else $if f.typ is $int {
c_int++
} $else $if f.typ is $float {
c_float++
} $else $if f.typ is $struct {
c_struct++
} $else $if f.typ …
```
=> v: comptime type lowercase ($int, $enum, $option, etc)

vlib/v/parser/parser.v, vlib/v/tests/option_array_submodule_test.v
=> parser: fix parsing cast array syntax from another module

vlib/v/gen/c/cgen.v, vlib/v/tests/comptime_concrete_type_register_test.v, vlib/v/tests/comptime_enum_test.v
Fix #17745 .
```v
enum Test{
alpha
bravo
charlie
}
fn main(){
$for value in Test.values{
println(value.name)
}
}
```
will work after this PR.
=> cgen: fix `println(value.name)` inside `$for value in Test.values{`

vlib/v/checker/checker.v, vlib/v/checker/fn.v, vlib/v/tests/skip_unused/generics_array_delete_method.vv
This PR fix generic array delete in skip_unused mode (fix #17600).
- Fix generic array delete in skip_unused mode.
- Add test.
```v
struct Bar[K] {
}
struct Foo[K] {
mut:
bars []Bar[K]
}
fn main() {
mut f := Foo[int]{[Bar[int]{}]}
f.xy()
}
pub fn (mut f Foo[K]) xy() {
f.bars.delete(0)
}
PS D:\Test\v\tt1> v -skip-unused run .
```
=> checker: fix generic array delete in skip_unused mode (fix #17600)

examples/database/orm.v, vlib/orm/orm.v
- orm: add tracing of the generated queries by the orm module, when a program is compiled with `-d trace_orm`
- examples: fix examples/database/orm.v, add comments, and ensure that the example can be run several times with no errors
=> examples, orm: fix orm example; add `-d trace_orm` option to see all ORM generated queries

vlib/math/big/big_test.v, vlib/math/big/integer.v
- Add a special case for the minimum 32-bit signed integer value to fix #17637
- Update syntax
=> math.big: fix min i32 value bug

vlib/v/ast/table.v, vlib/v/tests/concrete_type_as_generic_type_test.v
- Fix #17778.
- Add tests
`concrete_type_as_generic_type_test.v`
```v
// ...
fn func_fn_multi_return_concrete() FnMultiReturn[string, string, string] {
return fn (s string) (string, string) {
return s[..1], s[1..]
}
}
fn test_concrete_function_type_as_generic_type() {
// ...
s1, s2 := func_fn_multi_return_concrete()('VLang')
assert s1 == 'V'
assert s2 == 'Lang'
}
```
=> v: Fix concrete fn type that returns pair type as generic type

vlib/v/checker/struct.v, vlib/v/tests/embed_struct_field_default_value_test.v
This PR fix embedded struct field with default value (fix #17758).
- Fix embedded struct field with default value.
- Add test.
```v
struct Papa {
fam_name string
}
pub struct Child {
Papa
pub mut:
activity Activity = Fun.roll
age      u8       = 2
}
type Activity = Fun | Other
pub enum Fun {
run
roll
jump
}
pub struct Other {}
// Same struct without embedding just works.
pub struct Human {
fam_name string
pub mut:
activity Activity = Fun.roll
age      u8       = 2
}
fn main() {
c := Child{}
println(c.activity)
assert c.activity == Activity(Fun.roll)
h := Human{}
println(h.activity)
assert h.activity == Activity(Fun.roll)
}
Activity(roll)
Activity(roll)
```
=> checker: fix embedded struct field with default value (fix #17758)

vlib/v/checker/if.v, vlib/v/tests/return_error_in_if_expr_test.v
This PR fix returning error in if expr (fix #17733).
- Fix returning error in if expr.
- Add test.
```v
struct NotFoundError {
Error
}
fn get_username() !string {
return NotFoundError{}
}
fn print_username() !string {
username := get_username() or {
if err is NotFoundError {
'test'
} else {
return err
}
}
println(username)
return username
}
fn main() {
ret := print_username()!
assert ret == 'test'
}
test
```
=> checker: fix returning error in if expr (fix #17733)

vlib/v/checker/struct.v, vlib/v/checker/tests/option_fn_err.out
This should fix #17781 
I hope I did not break anything and this is the right place for the check. 
This is my first try on a compiler related fix.
=> checker: fix missing check for option value on non-optional struct field assignment

vlib/v/checker/checker.v, vlib/v/gen/c/assert.v, vlib/v/tests/assert_if_guard_expr_test.v
This PR fix asserting if guard expr (fix #17743).
- Fix asserting if guard expr.
- Add test.
```v
fn foo() !int {
return error('error')
}
fn main() {
assert if _ := foo() {
false
} else {
true
}
}
```
=> checker, cgen: fix asserting if guard expr (fix #17743)

vlib/v/gen/c/assign.v, vlib/v/tests/array_string_test.v
=> cgen: fix fixed array of string item concatenation

vlib/v/checker/check_types.v, vlib/v/checker/tests/generic_interface_err.out, vlib/v/checker/tests/generics_struct_infer_err.out, vlib/v/checker/tests/generics_struct_infer_err.vv, vlib/v/checker/tests/generics_struct_init_err.out, vlib/v/checker/tests/interface_generic_err.out
This PR check generic struct types infering error.
- Check generic struct types infering error.
- Add test.
```v
struct Foo[T, U] {
a T
b U
}
fn main() {
st11 := Foo{
a: 'two'
}
println(st11)
}
tt1.v:7:10: error: could not infer generic type `U` in generic struct `Foo[T, U]`
5 | 
6 | fn main() {
7 |     st11 := Foo{
8 |         a: 'two'
9 |     }
```
=> checker: check generic struct types infering error

doc/docs.md
Documentation examples in the documentation are wrong since they contain a blank line between a documentation comment and the function declaration. 
This is wrong since such a comment will not be treated as a documentation comment for that function but as a common comment.
=> docs: fix documentation examples

examples/tcp_notify_echo_server.v, vlib/os/file_test.v, vlib/v/checker/if.v, vlib/v/checker/tests/if_guard_expr_err.out, vlib/v/checker/tests/if_guard_expr_err.vv
This PR check if guard returning non-propagate option or result (fix #17742).
- Check if guard returning non-propagate option or result.
- Add test.
```v
fn foo() ! {
return error("error")
}
fn main() {
a := if r := foo() {
true
} else {
false
}
println(a)
}
tt1.v:6:10: warning: unused variable: `r`
4 |
6 |     a := if r := foo() {
|             ^
7 |         true
8 |     } else {
tt1.v:6:7: error: if guard expects non-propagate option or result
4 |
6 |     a := if r := foo() {
|          ~~~~~~~~~~~~~
7 |         true
8 |     } else {
```
=> checker: check if guard returning non-propagate option or result (fix #17742)

vlib/v/checker/if.v, vlib/v/tests/if_cond_with_alias_test.v
This PR fix if cond with alias (fix #17818).
- Fix if cond with alias.
- Add test.
```v
type BOOL = bool
fn example() BOOL {
return true
}
fn main() {
if example() {
println('Should work, or not?')
assert true
} else {
assert false
}
}
Should work, or not?
```
=> checker: fix if cond with alias (fix #17818)

vlib/v/ast/ast.v, vlib/v/fmt/fmt.v, vlib/v/fmt/tests/generics_fntype_keep.vv, vlib/v/parser/parser.v, vlib/v/tests/call_on_anon_test.v, vlib/v/tests/const_name_equals_fn_name_test.v, vlib/v/tests/fn_call_using_anon_fn_call_args_test.v, vlib/v/tests/match_return_fn_test.v, vlib/v/tests/sumtype_with_alias_fntype_fn_call_test.v, vlib/v/tests/sumtype_with_alias_fntype_test.v
This PR fix fmt error of generic fntype. (fix #17773)
- Fix fmt error of generic fntype.
- Add test.
vlib\v\fmt\tests\generics_fntype_keep.vv
```v
type Fn[T] = fn (T)
type FnReturn[T, R] = fn (T) R
fn func_fn_concrete() Fn[string] {
return fn (_s string) {}
}
fn func_fn_dynamic[T]() Fn[T] {
return fn [T](_t T) {}
}
fn func_fn_return_dynamic[T, R]() FnReturn[T, R] {
return fn [T, R](t T) R {
return t.int()
}
}
fn main() {
func_fn_concrete()('V')
func_fn_dynamic[string]()('V')
assert func_fn_return_dynamic[string, int]()('100') == 100
}
```
=> ast, parser, fmt: fix fmt error of generic fntype

vlib/v/checker/struct.v, vlib/v/tests/generic_struct_init_with_update_expr_test.v
This PR fix generic struct init with update expr (fix #17824).
- Fix generic struct init with update expr.
- Add test.
```v
pub struct Time[T] {
pub mut:
start T
end   T
}
pub struct Transform[T] {
pub mut:
time   Time[T]
before []T
after  []T
}
pub fn (t Transform[T]) clone() Transform[T] {
return Transform[T]{
...t
}
}
pub fn (t Transform[T]) default() Transform[T] {
return Transform[T]{}
}
fn main() {
a := Transform[f64]{
before: [0.0, 0.0]
after: [320.0, 240.0]
}
b := a.clone()
println(b)
assert b.before == a.before
assert b.after == a.after
c := a.default()
println(c)
assert c.before.len == 0
assert c.after.len == 0
}
Transform[f64]{
time: Time[f64]{
start: 0.0
end: 0.0
}
before: [0.0, 0.0]
after: [320.0, 240.0]
}
Transform[f64]{
time: Time[f64]{
start: 0.0 …
```
=> checker: fix generic struct init with update expr (fix #17824)

cmd/tools/vast/vast.v, vlib/v/ast/ast.v, vlib/v/gen/c/fn.v, vlib/v/gen/js/fn.v, vlib/v/tests/generics_closures_with_different_generic_types_test.v
This PR fix generic closures with different generic types (fix #17829).
- Fix generic closures with different generic types.
- Add test.
```v
fn abc[T](x T) fn (p T) T {
return fn [x] [T](p T) T {
return p * x
}
}
fn main() {
f := abc[int](12345)
a := f(2)
dump(a)
assert a == 24690
g := abc[u8](5)
b := g(2)
dump(b)
assert b == 10
}
[.\\tt1.v:10] a: 24690
[.\\tt1.v:15] b: 10
```
=> ast, cgen: fix generic closures with different generic types (fix #17829)

vlib/strings/builder.c.v, vlib/strings/builder_test.v
Just a small cleanup of the strings.drain_builder method.
Reduces number of C warnings with latest clang on macos, in code using `strings` to 0.
=> strings: simplify Builder.drain_builder; add test

vlib/v/checker/containers.v, vlib/v/checker/tests/array_init_option_err.out, vlib/v/checker/tests/array_init_option_err.vv, vlib/v/checker/tests/option_fn_err.out
=> checker: fix missing check for initializer with function returning options

vlib/v/gen/c/auto_str_methods.v, vlib/v/tests/typeof_type_test.v
- Fix #17847.
- Add assertion test:
`vlib\v\tests\typeof_type_test.v`:
```v
fn test_typeof_fn() {
// ...
assert typeof[fn (s string, x u32) ?(int, f32)]().name == 'fn (string, u32) ?(int, f32)'
assert typeof[fn (s string, x u32) !(int, f32)]().name == 'fn (string, u32) !(int, f32)'
// ...
}
```
=> cgen: Fix result of typeof function returns result type

vlib/v/scanner/scanner.v, vlib/v/tests/nested_multiline_comments_test.v
This PR fix nested multiline comments (fix #17841).
- Fix nested multiline comments.
- Add test.
```v
fn main() {
tt()
assert true
}
/*
fn tt() {
}
//*/
fn tt() {
println('hello, world')
}
hello, world
```
=> scanner: fix nested multiline comments (fix #17841)

vlib/v/gen/c/auto_str_methods.v, vlib/v/tests/map_to_string_test.v
This PR fix gen_str_for_map() (fix #17854).
- Fix gen_str_for_map().
- Add test.
```v
fn main() {
mut m1 := map[string]int{}
m1['one'] = 1
m1['two'] = 2
m1.delete('two')
println(m1)
assert '${m1}' == "{'one': 1}"
mut m2 := map[string]int{}
m2['one'] = 1
m2['two'] = 2
m2.delete('one')
println(m2)
assert '${m2}' == "{'two': 2}"
}
{'one': 1}
{'two': 2}
```
=> cgen: fix gen_str_for_map() (fix #17854)

vlib/v/checker/return.v, vlib/v/tests/fn_return_alias_of_ptr_test.v
This PR fix fn returning alias of pointer (fix #17861).
- Fix fn returning alias of pointer.
- Add test.
```v
type HANDLE = voidptr
struct ExampleStruct {
handle HANDLE
}
fn get_ptr(arg ExampleStruct) voidptr {
return arg.handle
}
fn main() {
h := ExampleStruct{}
r := get_ptr(h)
println(r)
assert r == unsafe { nil }
}
0x0
```
=> checker: fix fn returning alias of pointer (fix #17861)

vlib/v/gen/c/fn.v
- Fix #17878.
**`Example 1`**
`Before`:
`After`:
**`Example 2`**
`Before`:
`After`:
=> cgen: Fix wrong indent generation in anon fn decl

vlib/vweb/vweb.v
Fix issue where controllers couldn't add static files.
Static files are only copied from the main App. Now each time a request app is constructed the static files of that request app are used.
=> vweb: fix static files copying

vlib/v/scanner/scanner.v, vlib/v/tests/string_interpolation_string_lit_with_fmt_test.v
This PR fix string interpolation string literal with fmt (fix #17865).
- Fix string interpolation string literal with fmt.
- Add test.
```v
fn main() {
println('${'hello':-12s}')
assert '${'hello':-12s}' == 'hello       '
println('${'hello':12s}')
assert '${'hello':12s}' == '       hello'
}
hello
hello
```
=> scanner: fix string interpolation string literal with fmt (fix #17865)

vlib/v/checker/fn.v, vlib/v/checker/tests/array_delete_print_err.out, vlib/v/checker/tests/array_delete_print_err.vv
Fixes https://github.com/vlang/v/issues/17900
=> checker: disallow printing void

vlib/v/checker/return.v, vlib/v/gen/c/fn.v, vlib/v/tests/type_alias_of_pointer_types_test.v
This PR fix type alias of pointer (fix #17860).
- Fix type alias of pointer.
- Add test.
```v
type HANDLE = voidptr
fn example(arg voidptr) {
println('Handle value in function is: ${arg}')
assert '${arg}' == '0'
}
fn main() {
handle := get_handle()
println('Actual handle value is: ${handle}')
println('Memory address of handle is: ${&handle}')
example(handle)
assert '${handle}' == '0'
}
fn get_handle() HANDLE {
return unsafe { nil }
}
Actual handle value is: 0
Memory address of handle is: 14efe58
Handle value in function is: 0
```
=> checker, cgen: fix type alias of pointer (fix #17860)

vlib/math/limit.v, vlib/math/math_test.v
provides functions to get a maximum or minimum value of a given type.
```v
math.maxof[int]() // 2147483647
math.minof[u8]() // 0
```
=> math: add `maxof[T]()` and `minof[T]()`

vlib/v/ast/ast.v, vlib/v/ast/table.v, vlib/v/ast/types.v
This PR clean up ast.v, table.v and types.v.
- Move struct Fn, Param from table.v to ast.v.
- Group type definitions together.
=> ast: clean up ast.v, table.v and types.v

vlib/v/gen/c/assert.v
The string values were not used in the test runner callbacks, and generating them may have non trivial costs, if your values are more deeply nested.
Also see: https://discord.com/channels/592103645835821068/592320321995014154/1094223536320696352 .
=> cgen: do not generate the stringified values for `assert x in y`, for the `pass` case

examples/wasm_codegen/add.v, examples/wasm_codegen/control_flow.v, examples/wasm_codegen/factorial.v, examples/wasm_codegen/functions.v, examples/wasm_codegen/hello_wasi.v, examples/wasm_codegen/memory.v, vlib/wasm/README.md, vlib/wasm/encoding.v, vlib/wasm/functions.v, vlib/wasm/instructions.v, vlib/wasm/module.v, vlib/wasm/tests/arith_test.v, vlib/wasm/tests/block_test.v, vlib/wasm/tests/call_test.v
Add `wasm` module with a pure V implementation of the WebAssembly bytecode module format.
The module provides a builder to generate WebAssembly modules in memory, enabling users to create functions, opcodes, and use the entire wasm specification without relying on large dependencies like binaryen.
The module generates a `[]u8`, which can be written to a `.wasm` file or executed in memory.
```v
import wasm
import os
fn main() {
mut m := wasm.Module{}
mut func := m.new_function("add", [.i32_t, .i32_t], [.i32_t])
{
func.local_get(0) // | local.get 0
func.local_get(1) // | local.get 1
func.add(.i32_t)  // | i32.add
}
m.commit(func, true) // `export: true`
mod := m.compile() // []u8
os.write_file_array("add.wasm", mod)!
}
```
=> wasm module: pure V webassembly seralisation library

vlib/encoding/leb128/leb128.v, vlib/encoding/leb128/leb128_test.v
The decoding functions in the module `encoding.leb128` returns the number of bytes used.
Leb128 allows to encode and decode values with variable length. The program won't know the length until the value has been decoded. Decoding the value and not knowing how long the encoded value was may not always(never) be helpful.
For example I have to `u64` values `34` and `69` encoded as leb128 in my `u8` array `[0x22, 0x45]`. After decoding the first value I still don't know where the encoded first value ends with the previous decoding function. But now I also have that information and can use it as offset to decode the second value too without knowing the encoded sizes of the values beforehand.
=> leb128: decoding returns number of bytes used for decoding

vlib/v/gen/c/auto_str_methods.v, vlib/v/slow_tests/inout/printing_recursive_array_of_reference_struct.out, vlib/v/slow_tests/inout/printing_recursive_array_of_reference_struct.vv
This PR fix printing array of recursive reference struct (fix #17858).
- Fix printing array of recursive reference struct.
- Add test.
```v
name string
mut:
relatives []&Person
}
fn main() {
mut father := &Person{
name: 'John'
}
mut mother := &Person{
name: 'Jane'
relatives: [father]
}
father.relatives = [mother]
println(father)
println('Success')
}
&Person{
name: 'John'
relatives: [<circular>]
}
Success
```
=> cgen: fix printing array of recursive reference struct (fix #17858)

vlib/x/json2/encode_struct_test.v, vlib/x/json2/encoder.v
```v
assert json.encode(StructType[map[string]map[string]int]{
val: {
'a': {
'1': 1
}
}
}) == '{"val":{"a":{"1":1}}}'
```
=> json2: fix: encode maps with maps like map[string]map[string]int

vlib/builtin/string.v
In file [builtin/string.v](https://github.com/vlang/v/blob/master/vlib/builtin/string.v), the documentation inverts `common_parse_uint()` and `common_parse_int()` for `parse_uint()` and `parse_int()`: `parse_int` exposes `common_parse_int` but not `common_parse_uint` as mentionned, and vice versa.
(This pr doesn't affect any functionnal code)
=> builtin/string: correct small documentation mistake

vlib/vweb/README.md, vlib/vweb/tests/controller_duplicate_server.v, vlib/vweb/tests/controller_test.v, vlib/vweb/tests/controller_test_server.v, vlib/vweb/tests/vweb_test.v, vlib/vweb/tests/vweb_test_server.v, vlib/vweb/vweb.v
Added custom fallback route e.g. custom 404 page and updated tests for vweb Controllers.
Change the default behaviour of vweb to return `app.not_found()` instead of writing 404 directly to the connection. This allows users to implement their own custom 404 pages by implementing their own `not_found` method on App. I've updated the according docs and tests.
Also made all App methods `pub` in the vweb controllers tests for consistency between files.
=> vweb: custom 404 page + vweb tests fixes

doc/docs.md
The time to learn/read V docs has increase over the course of the last couple of years, this is a simple change to the docs on Github to reflect the same visble on the homepage.
=> docs.md: reflect accurate time needed to learn V

vlib/v/ast/types.v, vlib/v/checker/check_types.v, vlib/v/checker/checker.v, vlib/v/checker/comptime.v, vlib/v/checker/containers.v, vlib/v/checker/fn.v, vlib/v/checker/for.v, vlib/v/checker/if.v, vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/dumpexpr.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/index.v
This PR makes a minor optimization of clear_flags().
- Change `clear_flags()` to `clear_flags(flags ...TypeFlag)`.
- Change `type.clear_flag(.option).clear_flag(.result)` to `type.clear_flags(.option, .result)`.
=> ast: minor optimization of clear_flags()

vlib/regex/README.md
This PR fixes formatting inconsistencies in regex docs. It does this in respect of preserving things like manually added line breaks in `v ignore` blocks. To find the dominant style, I've checked other v docs and oriented the changes towards it.
Working with regex I found something additional to be solved in a separate issue: The example for `Total customization of the regex environment creation` doesn't work(is probably outdated?). Since the structs are declared private. https://github.com/vlang/v/blob/f41ca48ab969ca9d2b0a1f5dd9e4497e55a33bbe/vlib/regex/README.md?plain=1#L846-L849
=> docs(regex): fix formatting inconsistencies

cmd/tools/test_os_process.v, vlib/os/process.v, vlib/os/process_nix.c.v, vlib/os/process_test.v, vlib/os/process_windows.c.v
Allow for setting the initial working folder of a new process in a non racing way on both unix and windows.
=> os: implement Process.set_work_folder/1 to set the initial working folder of the new child process

vlib/wasm/constant.v, vlib/wasm/encoding.v, vlib/wasm/functions.v, vlib/wasm/instructions.v, vlib/wasm/module.v, vlib/wasm/tests/block_test.v, vlib/wasm/tests/call_test.v, vlib/wasm/tests/var_test.v
Implement global variables, and initialisation with constant expressions. Also implemented function reference types and cleaned up the code.
As I have mentioned before, if the tests pass on my PC they will pass on others. The V CI also does not contain special CI for testing the wasm module. Skipping CI would be preferrable.
```v
import wasm
fn main() {
mut m := wasm.Module{}
// global, export: "__vsp", type: i32, mutable: true, init: i32.const 10
vsp := m.new_global("__vsp", .i32_t, true, wasm.constexpr_value(10))
mut func := m.new_function('vsp', [], [.i32_t])
{
func.global_get(vsp)
func.i32_const(20)
func.add(.i32_t)
func.global_set(vsp)
func.global_get(vsp)
}
m.commit(func, true)
}
````
\- l-m
=> wasm module: globals, constant expressions and function reference types

vlib/vweb/parse.v, vlib/vweb/tests/vweb_test.v, vlib/vweb/tests/vweb_test_server.v
vweb fix multipart form parsing.
The boundary argument was passed as string `"boundary"` in `parse.v`, but `parse_multipart_form` expects only the string `boundary` without quotes. I updated the boundary to be correct. and changed the tests to use the `net.http.post_multipart_form` function instead of passing the data raw.
=> vweb: fix multipart_form parsing

vlib/flag/flag.v
This wasn't caught in tests since they assert the string return and not the type.
=> flag: fix typo in vlib/flag uknown flag struct

vlib/v/parser/parser.v, vlib/v/slow_tests/repl/comptime_for.repl
This PR fix comptime_for in repl (script mode) (fix #5976).
- Fix comptime_for in repl (script mode).
- Add test.
```v
____    ____
\    /     |  V 0.3.3 2179db3 . Use  list  to see the accumulated program so far.
>>> struct Person {
... name string
... age int
... }
>>> $for field in Person.fields {
... println(field.name)
... }
name
age
>>>
```
=> parser: fix comptime_for in repl (script mode) (fix #5976)

vlib/v/checker/tests/invalid_comptime_test.out, vlib/v/checker/tests/invalid_comptime_test.vv, vlib/v/parser/parser.v
Fix #17967
`$something` was generating `IfExpr` AST nodes.
=> parser: fix wrong nodes generated for $something

vlib/v/checker/checker.v, vlib/v/checker/fn.v, vlib/v/gen/c/array.v, vlib/v/gen/c/utils.v, vlib/v/tests/map_with_selector_test.v
Fix #17956
```V
fn main() {
k := [10, 20, 30]
println(k.map(it.hex()))
dump(k.map(it.hex))
a := k.map(it.hex)
assert dump(a[0]()) == 'a'
assert dump(a[1]()) == '14'
assert dump(a[2]()) == '1e'
}
```
=> cgen: fix map with selectorexpr returning closure

.github/workflows/wasm_wabt_tests_ci.yml, .gitignore, cmd/tools/install_wabt.vsh, vlib/wasm/tests/arith_test.v, vlib/wasm/tests/block_test.v, vlib/wasm/tests/call_test.v, vlib/wasm/tests/common.v, vlib/wasm/tests/var_test.v
- tests: extract the common code from wasm tests into a common.v file
- tests: make the wasm tests work on Windows too (use `wasm-validate file.wasm` instead of piping to `wasm-validate -`)
- tests: final cleanup of vlib/wasm tests and cmd/tools/install_wabt.vsh
=> ci: add `wasm` module test jobs for macos, linux and windows

vlib/v/gen/c/infix.v, vlib/v/tests/strings_builder_shift_array_reverse_test.v
This PR fix strings builder shift array.reverse() (fix #17948).
- Fix strings builder shift array.reverse().
- Add test.
```v
import rand
import strings
fn main() {
mut a := strings.new_builder(0)
mut b := strings.new_builder(0)
b << rand.ascii(5).bytes()
a << b.reverse()
ret := a.str()
println(ret)
assert ret.len == 5
}
cw\-}
```
=> cgen: fix strings builder shift array.reverse() (fix #17948)

vlib/v/builder/cc.v
With [vzcc](https://github.com/malisipi/vzcc), we can create windows executables from Termux. But the compiler needs to allow cross-compiling from Termux. If not, V will panic with `your platform is not supported yet` text.
=> v: allow cross-compiling from Termux

vlib/toml/any.v, vlib/toml/tests/inline_test.v
Serializing a nested struct like the following to toml:
```v
name string
address Address
}
struct Address {
street string
city   string
}
p := Person{
name: 'John'
address: Address{'Elm Street', 'Springwood'}
}
```
currently results in:
```
name = "John"
address = { street = "Elm Street", city = "Springwood", }
```
trying to deserialize it again with `doc := toml.parse_text(toml_txt) or { panic(err) }` will cause:
> V panic: toml.parser.Parser.inline_table unexpected "rcbr" "}" at this (excerpt): "...ngwood", }..."
This PR will cause serialization without a trailing comma on last items of inline tables to prevent this.
It also includes a little incremental refactor of variable assignments.
Edit: sorry about the spelling issue in the commit message. I think since PRs are …
=> toml: fix trailing comma in inline toml

vlib/v/ast/table.v, vlib/v/checker/fn.v, vlib/v/checker/infix.v, vlib/v/gen/c/array.v, vlib/v/tests/generics_array_of_threads_test.v
This PR fix generic array of threads (fix #17976).
- Fix generic array of threads.
- Add test.
```v
fn async_map[T](arr []T, func fn (T) T) []T {
mut threads := []thread T{}
for element in arr {
threads << spawn func(element)
}
return threads.wait()
}
fn main() {
arr := [1, 2, 3, 4]
results := async_map(arr, fn (a int) int {
return -a
})
println(results)
assert results == [-1, -2, -3, -4]
}
[-1, -2, -3, -4]
```
=> ast, checker, cgen: fix generic array of threads (fix #17976)

cmd/tools/vtest-self.v, vlib/v/gen/c/auto_str_methods.v, vlib/v/tests/c_struct_with_reserved_field_name_test.v
This PR fix c struct with reserved field name (fix #17993).
- Fix c struct with reserved field name.
- Add test.
```v
import gg
import gx
struct Game {
mut:
gg ?gg.Context
}
fn main() {
mut game := Game{
gg: none
}
mut cont := gg.new_context(
bg_color: gx.rgb(174, 198, 255)
width: 600
height: 400
window_title: 'Polygons'
)
game.gg = cont
println(game.gg)
assert true
}
Option(gg.Context{
render_text: true
image_cache: []
needs_refresh: false
ticks: 0
native_rendering: false
scale: 0.0
width: 0
height: 0
clear_pass:     sokol.gfx.PassAction(C.sg_pass_action{
_start_canary: 0
colors: [C.sg_color_attachment_action{
action: _default
value:     sokol.gfx.Color(C.sg_color{
r: 0.0
g: 0.0
b: 0.0
a: 0.0
})
}, C.sg_color_attachment_action{
action: _default
value: …
```
=> cgen: fix c struct with reserved field name (fix #17993)

vlib/v/checker/check_types.v, vlib/v/checker/fn.v, vlib/v/gen/c/fn.v, vlib/v/tests/comptime_selector_ptr_test.v
=> checker, cgen: fix infering type for comptimeselector when using ptr type

vlib/vweb/README.md, vlib/vweb/vweb.v
At this moment it is only possible to have 1 ongoing datbase connection for an entire vweb application. Problems arise when multiple workers need to access that same database connection over multiple threads, see #18006.
This pullrequest adds the option to have a pool of database connections. 
Example with postgres as database.
```v
module main
import vweb
import db.pg
struct App {
vweb.Context
db_handle vweb.DatabasePool[pg.DB]
mut:
db pg.DB
}
fn get_database_connection() pg.DB {
return pg.connect(user: 'dev', password: 'password', dbname: 'database') or { panic(err) }
}
fn main() {
pool := vweb.database_pool(handler: get_database_connection, nr_workers: 20)
vweb.run_at(&App{
db_handle: pool
},
port: 8080
nr_workers: 20
)!
}
```
In this example there are 20 workers and there must be 1 …
=> vweb: implement database pool

vlib/v/ast/table.v, vlib/v/parser/parse_type.v, vlib/v/parser/parser.v, vlib/v/tests/concrete_type_as_generic_fn_type_1_test.v, vlib/v/tests/concrete_type_as_generic_fn_type_2_test.v
This PR fix generic fntype to concrete types (fix #17982).
- Fix generic fntype to concrete types.
- Add test.
```v
struct ParseResult[T] {
result T
rest   string
}
type ParseFunction[T] = fn (string) !ParseResult[T]
fn literal(l string) ParseFunction[string] {
return fn [l] (input string) !ParseResult[string] {
if !input.starts_with(l) {
return error(input)
}
return ParseResult[string]{
result: l
rest: input.all_after_first(l)
}
}
}
fn main() {
l_func := literal('start')
val1 := l_func('start test') or { ParseResult[string]{} }
val2 := l_func('test') or { ParseResult[string]{} }
println(val1)
assert val1.result == 'start'
assert val1.rest == ' test'
println(val2)
assert val2.result == ''
assert val2.rest == ''
}
ParseResult[string]{
result: 'start'
rest: ' test' …
```
=> ast, parser: fix generic fntype to concrete types (fix #17982)

vlib/v/checker/tests/generics_fn_called_fntype_arg_mismatch.vv, vlib/v/parser/parse_type.v, vlib/v/parser/tests/generic_fn_type_decl_err.out, vlib/v/parser/tests/generic_fn_type_decl_err.vv
This PR check generic fntype declaration without type name.
- Check generic fntype declaration without type name.
- Add test.
```v
type Fn = fn (I) !(O, R)
fn main() {
}
tt1.v:1:6: error: `Fn` type is generic fntype, must specify the generic type names, e.g. Fn[T]
1 | type Fn = fn (I) !(O, R)
|      ~~
2 | 
```
=> parser: check generic fntype declaration without type name

vlib/v/tests/c_struct_with_reserved_field_name_test.v
This PR clean up c_struct_with_reserved_field_name_test.v.
- Avoid printing out large amounts of structure information.
```v
OK    [ 489/1416]   346.828 ms vlib/v/tests/c_function_mut_param/option_args_test.v
OK    [ 490/1416]   369.833 ms vlib/v/tests/c_struct_free/c_struct_free_property_test.v
OK    [ 491/1416]   367.251 ms vlib/v/tests/call_on_anon_test.v
OK    [ 492/1416]   353.942 ms vlib/v/tests/call_to_str_on_option_test.v
Option(gg.Context{
render_text: true
image_cache: []
needs_refresh: false
ticks: 0
native_rendering: false
scale: 0.0
width: 0
height: 0
clear_pass:     sokol.gfx.PassAction(C.sg_pass_action{
_start_canary: 0
colors: [C.sg_color_attachment_action{
action: _default
value:     sokol.gfx.Color(C.sg_color{
r: 0.0
g: 0.0
b: 0.0
a: 0.0
})
}, …
```
=> tests: clean up c_struct_with_reserved_field_name_test.v

vlib/v/gen/wasm/gen.v
This PR adds a check in the new wasm backend that takes the `[export: 'name']` attribute into account when exporting functions for wasm modules. It doesn't alter the behavior otherwise (e.g. functions still need to be marked `pub` and need to be part of the `main` module), however it now uses the name specified in the `[export]` attribute (if applied) rather than the actual function name).
Partially addresses #17621
=> wasm: Add support for [export]ed functions

vlib/v/gen/c/assign.v, vlib/v/tests/cross_assign_with_generic_fn_call_test.v
This PR fix cross assign with generic fn call (fix #18042).
- Fix cross assign with generic fn call.
- Add test.
```v
import math
fn main() {
mut x := -1
mut y := -2
x, y = y, math.abs(x)
println('${x} | ${y}')
assert x == -2
assert y == 1
}
-2 | 1
```
=> cgen: fix cross assign with generic fn call (fix #18042)

vlib/v/checker/struct.v, vlib/v/parser/struct.v, vlib/v/tests/generic_struct_init_with_field_struct_init_test.v
This PR fix generic struct init with field struct init (fix #18040).
- Fix generic struct init with field struct init.
- Add test.
```v
struct Child {
}
struct Test[T] {
child Child
}
fn new[T]() Test[T] {
return Test[T]{
child: Child{}
}
}
fn main() {
t := new[int]()
println(t)
assert t.child == Child{}
}
Test[int]{
child: Child{}
}
```
=> parser, checker: fix generic struct init with field struct init (fix #18040)

vlib/v/gen/c/orm.v
This doesn't constitute a complete overhaul of the cgen code. I've made some simplifications and structural improvements, including adding essential comments and formatting the output of the C code.
I think it will be a little easier to understand the work of this code now.
Now these are not one-liners, but structured code that can be easier to read while searching for problems.
=> cgen(orm): refactor, comments, simplify

vlib/v/gen/native/amd64.v, vlib/v/gen/native/arm64.v, vlib/v/gen/native/builtins.v, vlib/v/gen/native/elf.v, vlib/v/gen/native/gen.v, vlib/v/gen/native/macho.v, vlib/v/gen/native/macho_test.v, vlib/v/gen/native/pe.v, vlib/v/gen/native/syscall.v
This PR will consist of two parts:
This is necessary, because `amd64.v` has become a big and cluttered, leaving behind `arm64.v` and potential other platforms we might support in the future.
The idea is, that the `CodeGen` interface allows anyone to add support for a new platform _(`riscV` would be nice)_ without needing to implement the whole code generation logic all over again.
> ~~Note, that this is not ready for merging, although all tests _should_ succeed~~
=> native: make code generation logic platform-independant

examples/smtp/mail.v, vlib/net/smtp/smtp.v
Executing `v examples/smtp/mail.v` outputs this notice:
```bash
examples/smtp/mail.v:21:21: notice: interface field `io.BufferedReader.reader` must be initialized
19 |     subject := os.input('Subject: ')
20 |     body := os.input('Body: ')
21 |     client_cfg := smtp.Client{
|                        ~~~~~~~
22 |         server: mailserver
23 |         from: from
```
@spytheman suggested this small fix/workaround (`reader: unsafe { nil }`) on Discord.
https://discord.com/channels/592103645835821068/592294828432424960/1098252925727416340
=> examples: smtp/mail fix reader notice

vlib/builtin/builtin.c.v, vlib/builtin/builtin_d_gcboehm.c.v, vlib/builtin/builtin_notd_gcboehm.c.v
Expose gcboehm's API to get memory usage:
- `gc_memory_use()` _returns the total memory use in bytes by all allocated blocks_
- `gc_heap_usage()` _returns the heap usage info_
```V
import time
[heap]
struct Test {
a []int
}
fn stats() {
s := gc_heap_usage()
eprintln('gc_memory_use: ${gc_memory_use():7} | heap_size: ${s.heap_size:7} | free_bytes: ${s.free_bytes:7} | total_bytes: ${s.total_bytes:7} | bytes_since_gc: ${s.bytes_since_gc:7}')
}
fn main() {
stats()
for {
a := Test{
a: [1].repeat(10)
}
b := Test{
a: [1].repeat(20)
}
c := Test{
a: [1].repeat(30)
}
_ := 'a:${a} | b:${b} | c:${c}'
stats()
time.sleep(10 * time.millisecond)
}
}
```
```
gc_memory_use:  192512 | heap_size:  131072 | free_bytes:   45056 | total_bytes:   18400 | bytes_since_gc:   18400
gc_memory_use:  229376 | heap_size: …
```
=> builtin: heap memory usage api

vlib/flag/flag.v
=> flag: fix typo in flag.v

vlib/v/checker/if.v, vlib/v/checker/match.v, vlib/v/checker/tests/match_cond_with_parenthesis_err.out, vlib/v/checker/tests/unnecessary_parenthesis.out
This PR changes the error given by using brackets around an if or match statement into a warning.
When writing an if statement in v, if the programmer uses brackets around the expression as is common in other languages the compiler will alert them that this is not necessary, in the form of an error. This is a bit extreme as the code will still operate just fine with the brackets, it is just simply not v's preferred coding style. This PR changes this error to a warning, so debug builds can still be compiled with these statements, for example if a programmer was just trying to make a feature work and not considering the style of their code, or even was using multiple brackets to separate conditions and removed one without removing the brackets from the other, they can still build and test …
=> checker: Warn instead of error for unnecessary brackets on if/match

vlib/v/ast/ast.v, vlib/v/ast/table.v, vlib/v/checker/checker.v, vlib/v/fmt/fmt.v, vlib/v/gen/c/cgen.v, vlib/v/parser/parser.v, vlib/v/tests/generics_fn_variable_test.v
This PR implement generic fn variable (fix #14937).
- Implement generic fn variable.
- Add test.
```v
type Fn[T] = fn (x T, i int) T
fn func[T](x T, i int, f_ Fn[T]) T {
return f_(x, i)
}
fn f[T](x T, i int) T {
return x
}
fn main() {
ff := f[int]
ret := ff(1, 11)
println(ret)
x := func[f64](2.0, 3, f[f64])
println(x)
assert x == 2.0
}
1
2.0
```
=> ast, parser, checker, cgen, fmt: implement generic fn variable (fix #14937)

vlib/v/parser/expr.v, vlib/v/parser/parser.v
This PR makes a minor cleanup for parse_ident().
- Change `parse_ident()` to `ident()` in order to keep the style consistent.
=> parser: clean up parse_ident()

vlib/v/gen/c/fn.v, vlib/v/tests/generics_array_of_threads_test.v
This PR fix generics array of threads with multiple types (fix #18136).
- Fix generics array of threads with multiple types.
- Add test.
```v
fn async_map[T](arr []T, func fn (T) T) []T {
mut threads := []thread T{}
for element in arr {
threads << spawn func(element)
}
return threads.wait()
}
fn main() {
arr1 := [1, 2, 3, 4]
results1 := async_map(arr1, fn (a int) int {
return -a
})
println(results1)
assert results1 == [-1, -2, -3, -4]
arr2 := [1.0, 2.0, 3.0, 4.0]
results2 := async_map(arr2, fn (a f64) f64 {
return -a
})
println(results2)
assert results2 == [-1.0, -2.0, -3.0, -4.0]
}
[-1, -2, -3, -4]
[-1.0, -2.0, -3.0, -4.0]
```
=> cgen: fix generics array of threads with multiple types (fix #18136)

vlib/v/gen/c/index.v, vlib/v/tests/nested_map_of_fn_call_test.v
This PR fix nested map of fn call (fix #18133).
- Fix nested map of fn call.
- Add test.
```v
fn main() {
mut a := map[string]map[string]fn () int{}
a['a']['a'] = fn () int {
return 0
}
b := a['a']['a']()
println(b)
assert b == 0
}
0
```
=> cgen: fix nested map of fn call (fix #18133)

vlib/vweb/vweb.v
This PR make controllers of struct Controller public  (fix #18148).
- Make controllers of struct Controller public.
```v
import vweb
pub struct CouldExist[T] {
pub:
optional ?T
}
struct App {
vweb.Context
vweb.Controller
}
struct Admin {
vweb.Context
}
struct Foo {
vweb.Context
}
fn main() {
controllers: [
vweb.controller('/admin', &Admin{}),
vweb.controller('/foo', &Foo{}),
]
}
vweb.run(app, 8080)
}
['/path']
pub fn (mut app Admin) path() vweb.Result {
return app.text('Admin')
}
[Vweb] Running app on http://localhost:8080/
[Vweb] We have 3 workers
```
=> vweb: make controllers of struct Controller public  (fix #18148)

vlib/v/checker/check_types.v, vlib/v/tests/generics_struct_init_with_generic_struct_items_test.v
This PR fix generic struct init with generic struct items (fix #18149).
- Fix generic struct init with generic struct items.
- Add test.
```v
struct Item[T] {
val T
}
struct Items[A, B] {
item1 Item[A]
item2 Item[B]
}
fn combine[A, B](a A, b B) Items[A, B] {
return Items[A, B]{
item1: Item[A]{
val: a
}
item2: Item[B]{
val: b
}
}
}
fn main() {
_ := Items[int, string]{Item{42}, Item{'bye'}}
_ := Items[int, string]{
item1: Item{42}
item2: Item{'bye'}
}
_ := Items[int, string]{
item1: Item{
val: 42
}
item2: Item{
val: 'bye'
}
}
_ := Items[int, string]{
item1: Item[int]{
val: 42
}
item2: Item[string]{
val: 'bye'
}
}
_ := Items[string, int]{
item1: Item[string]{
val: 'hallo'
}
item2: Item[int]{
val: 42
}
}
_ := Items[string, string]{
item1: Item[string]{
val: 'hallo'
}
item2: Item[string]{
val: …
```
=> checker: fix generic struct init with generic struct items (fix #18149)

vlib/v/checker/infix.v, vlib/v/checker/tests/generics_undefined_operation_2.out, vlib/v/checker/tests/generics_undefined_operation_2.vv
This PR check generic undefined operation (fix #18162).
- Check generic undefined operation.
- Add test.
```v
pub struct INode {
mut:
heapindex u64
}
pub struct IHeap[T] {
mut:
array []&T
size  u64
}
pub fn create_iheap[T](capacity int) &IHeap[T] {
mut h := &IHeap[T]{
array: []&T{cap: capacity}
size: 0
}
h.array << &T(unsafe { nil })
return h
}
fn (mut h IHeap[T]) percolateup(hl u64, mut element T) {
mut hole := hl
for hole > 1 && element < h.array[hole / 2] {
// ^ Notice that '<' was not defined
println("didnt define '<' for the INode")
hole /= 2
}
}
fn main() {
heap := create_iheap[INode](3000000)
println(heap)
}
tt1.v:23:18: error: undefined operation `&INode` < `&INode`
21 | fn (mut h IHeap[T]) percolateup(hl u64, mut element T) {
22 |     mut hole := hl
23 | …
```
=> checker: check generic undefined operation (fix #18162)

vlib/v/fmt/fmt.v, vlib/v/fmt/tests/fn_with_end_comments_keep.vv
This PR fix formating of fn decl with end comments (fix #18176).
- Fix formating of fn decl with end comments.
- Add test.
`fn_with_end_comments_keep.vv`
```v
fn (c Color) is_blue() bool {
return c == .blue
} // method of enum
fn (c Color) show_int() int {
return int(c)
} // method of enum
fn main() {}
```
=> fmt: fix formating of fn decl with end comments (fix #18176)

cmd/tools/vast/vast.v, vlib/v/ast/ast.v, vlib/v/fmt/fmt.v, vlib/v/fmt/tests/types_expected.vv, vlib/v/fmt/tests/types_input.vv, vlib/v/parser/parse_type.v, vlib/v/parser/parser.v
This PR implement comments inside sumtype declaration. (fix #5908)
- Implement comments inside sumtype declaration.
- Add test.
```v
// Callback represents all the possible callbacks
pub type Callback = ConnectedCallback 	// connected callback
| LoggedOnCallback // logged on callback
| DisconnectedCallback 	// disconnected callback
| LoggedOffCallback // logged off callback
struct ConnectedCallback{}
struct DisconnectedCallback{}
struct LoggedOnCallback{}
struct LoggedOffCallback{}
```
format to:
```v
// Callback represents all the possible callbacks
pub type Callback = ConnectedCallback // connected callback
| DisconnectedCallback // disconnected callback
| LoggedOffCallback // logged off callback
| LoggedOnCallback // logged on callback
struct ConnectedCallback {}
struct …
```
=> fmt: implement comments inside sumtype declaration

vlib/v/checker/assign.v, vlib/v/gen/c/assign.v, vlib/v/parser/assign.v, vlib/v/tests/swap_array_test.v
This PR fix error of swapping array (fix #8661).
- Fix error of swapping array.
- Add test.
```v
fn main() {
mut array1 := []int{len: 10, init: 1}
println(array1)
swaper(mut array1)
println(array1)
assert array1 == [22, 2, 2, 2, 2, 2, 2, 2, 2, 2]
}
fn swaper(mut array1 []int) {
mut array2 := []int{len: 10, init: 2}
array1[0] = 11
array2[0] = 22
unsafe {
array1, array2 = array2, array1
}
}
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[22, 2, 2, 2, 2, 2, 2, 2, 2, 2]
```
=> parser, checker, cgen: fix error of swapping array (fix #8661)

vlib/v/checker/containers.v, vlib/v/tests/array_of_sumtype_append_array_of_sumtype_test.v
This PR fix array of sumtype appending array of sumtype (fix #18197).
- Fix array of sumtype appending array of sumtype.
- Add test.
```v
type IntStr = int | string
fn main() {
mut a := [IntStr(1), 2, 'a']
a << [3, 4, 'dsafa']
println(a)
assert '${a}' == "[IntStr(1), IntStr(2), IntStr('a'), IntStr(3), IntStr(4), IntStr('dsafa')]"
}
[IntStr(1), IntStr(2), IntStr('a'), IntStr(3), IntStr(4), IntStr('dsafa')]
```
=> checker: fix array of sumtype appending array of sumtype (fix #18197)

vlib/net/html/tag.v
Removes unnecessary comment that slipped through while adding the `get_tag` methods for first matches.
=> net.html: remove unnecessary comment

vlib/v/checker/check_types.v, vlib/v/checker/fn.v, vlib/v/gen/c/array.v, vlib/v/tests/array_of_interfaces_index_test.v
This PR fix array of interfaces index() (fix #18225).
- Fix array of interfaces index().
- Add test.
```v
struct Entity {
id u64
mut:
components []IComponent
}
interface IComponent {
hollow bool
}
struct IsControlledByPlayerTag {
hollow bool
}
fn get_component[T](entity Entity) !&T {
for component in entity.components {
if component is T {
return component
}
}
return error('Entity does not have component')
}
fn main() {
entity := Entity{1, [IsControlledByPlayerTag{}]}
id := entity.components.index(*get_component[IsControlledByPlayerTag](entity)!)
println('id = ${id}')
assert id == 0
}
id = 0
```
=> checker, cgen: fix array of interfaces index() (fix #18225)

vlib/v/parser/parser.v
This PR clean up in parser.v.
- Remove `scope_register_it()` and `scope_register_ab()`.
- They are used in checker phase.
=> parser: clean up in parser.v

vlib/os/file.c.v, vlib/os/file_test.v, vlib/os/os.c.v
This PR fix open_file() on windows (fix #18245).
- Fix open_file() on windows.
- Add test.
```v
import os
fn main() {
mut result := os.open_file('中文.txt', 'w+', 0x666) or { panic(err) }
result.write_string('中文，test') or { panic(err) }
}
```
generated:
`中文.txt`
```v
中文，test
```
=> os: fix open_file() on windows (fix #18245)

vlib/v/parser/expr.v, vlib/v/parser/parser.v, vlib/v/tests/array_method_using_it_in_defer_test.v
This PR fix array method using it in defer (fix #18246).
- Fix array method using it in defer.
- Add test.
```v
fn main() {
arr := ['1', '1.1', '1.2', '2', '2.1', '2.2']
defer {
ret := arr.filter(it.contains('1'))
println(ret)
assert ret == ['1', '1.1', '1.2', '2.1']
}
}
['1', '1.1', '1.2', '2.1']
```
=> parser: fix array method using it in defer (fix #18246)

vlib/v/ast/table.v, vlib/v/gen/c/fn.v, vlib/v/tests/generics_struct_with_inconsistent_generic_types_1_test.v
This PR fix generic struct with inconsistent generic types (fix #18254).
- Fix generic struct with inconsistent generic types.
- Add test.
```v
pub struct Generic[D] {
pub mut:
field D
}
pub fn (j Generic[D]) foo() D {
return j.field
}
pub fn new_generic[T](field T) Generic[T] {
return Generic[T]{
field: field
}
}
fn main() {
my_generic1 := new_generic[int](2)
r1 := my_generic1.foo()
println(r1)
assert r1 == 2
my_generic2 := new_generic[string]('hello')
r2 := my_generic2.foo()
println(r2)
assert r2 == 'hello'
}
2
hello
```
=> ast, cgen: fix generic struct with inconsistent generic types (fix #18254)

vlib/v/checker/fn.v, vlib/v/tests/generic_fn_with_nested_generic_fn_call_test.v
This PR fix generic fn with nested generic fn call (fix #18285).
- Fix generic fn with nested generic fn call.
- Add test.
```v
struct Test {}
fn unmarshal[T]() ! {
get_number[int]()!
}
fn get_number[T]() !T {
return T(42)
}
fn main() {
unmarshal[Test]()!
assert true
}
```
=> checker: fix generic fn with nested generic fn call (fix #18285)

vlib/v/checker/containers.v, vlib/v/tests/generic_fn_infer_map_argument_test.v
This PR fix generic fn infering map argument (fix #18337).
- Fix generic fn infering map argument.
- Add test.
```v
fn f[T](src map[string]T) T {
return src['a']
}
fn main() {
r1 := f({
'a': 1
})
println(r1)
assert r1 == 1
r2 := f({
'a': 'hello'
})
println(r2)
assert r2 == 'hello'
}
1
hello
```
=> checker: fix generic fn infering map argument (fix #18337)

vlib/v/ast/table.v, vlib/v/tests/for_in_iterator_of_generic_struct_3_test.v
This PR fix for in iterator of generic struct (fix #18339).
- Fix for in iterator of generic struct.
- Add test.
```v
struct MyGenericArray[T] {
arr []T
mut:
idx int
}
fn (mut self MyGenericArray[T]) next() ?T {
if self.arr.len <= self.idx {
return none
} else {
defer {
self.idx++
}
return self.arr[self.idx]
}
}
fn main() {
mut a := MyGenericArray{[4, 5, 6], 1}
mut ret := []int{}
for i in a {
println(i)
ret << i
}
assert ret.len == 2
assert ret[0] == 5
assert ret[1] == 6
}
5
6
```
=> ast: fix for in iterator of generic struct (fix #18339)

vlib/v/ast/table.v
This PR makes a minor cleanup in generic_insts_to_concrete().
- Remove redundant initialization assignment.
=> ast: minor cleanup in generic_insts_to_concrete()

vlib/v/ast/cflags.v, vlib/v/ast/comptime_valid_idents.v, vlib/v/checker/checker.v, vlib/v/checker/comptime.v, vlib/v/fmt/fmt.v
This PR fix compiler internal formatting failed.
error:
```v
PS D:\Vlang\v\vlib\v\checker> v fmt -w check_types.v
cannot compile `D:\Vlang\v\cmd\tools\vfmt.v`: 
D:/Vlang/v/vlib/v/ast/cflags.v:30:36: error: undefined ident: `v.checker.constants.valid_comptime_not_user_defined`
28 |     mut fos := ''
29 |     mut allowed_os_overrides := []string{}
30 |     allowed_os_overrides << constants.valid_comptime_not_user_defined
|                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
31 |     allowed_os_overrides << ctimedefines
32 |     for os_override in allowed_os_overrides {
D:/Vlang/v/vlib/v/fmt/fmt.v:2012:46: error: undefined ident: `v.checker.constants.valid_comptime_not_user_defined`
2010 | pub fn (mut f Fmt) ident(node ast.Ident) {
2011 |     if node.info is ast.IdentVar { …
```
=> ast, checker, fmt: fix compiler internal formatting failed

vlib/v/checker/check_types.v, vlib/v/tests/generics_fn_return_result_test.v, vlib/v/tests/infer_generic_array_type_in_nested_call_test.v
This PR fix infering generic array type in nested call (fix #18317).
- Fix infering generic array type in nested call.
- Add test.
```v
fn unmarshal_any[T]() T {
mut typ := T{}
$if T is $array {
unmarshal_array(mut typ)
}
return typ
}
fn unmarshal_array[T](mut typ []T) {
typ << 42
}
fn main() {
ret := unmarshal_any[[]int]()
println(ret)
assert ret == [42]
}
[42]
```
=> checker: fix infering generic array type in nested call (fix #18317)

vlib/v/util/util.v
Prevents module lookup problems when recompiling V tools in a current folder != the V project root one.
An example for such is: https://github.com/vlang/v/pull/18356 .
=> v.util: make util.launch_tool/3 more robust, by recompiling V tools always in a known current working folder (vroot)

vlib/v/gen/c/fn.v, vlib/v/tests/alias_map_clone_test.v
This PR fix alias of map clone() (fix #18384).
- Fix alias of map clone().
- Add test.
```v
type Fields = map[string]string
fn main() {
f := Fields({'s': 'a'})
s := f.clone()
println(s)
assert s == {'s': 'a'}
}
{'s': 'a'}
```
=> cgen: fix alias of map clone() (fix #18384)

cmd/tools/vast/vast.v, vlib/v/ast/ast.v, vlib/v/markused/walker.v, vlib/v/transformer/transformer.v
This PR clean up ast.StructInit.
- Remove unused field `embeds`.
=> ast: clean up ast.StructInit

vlib/v/checker/struct.v, vlib/v/slow_tests/inout/struct_with_embed_field_init.out, vlib/v/slow_tests/inout/struct_with_embed_field_init.vv
This PR fix embedded structure initialization warnings (fix #18376).
- Fix embedded structure initialization warnings.
- Add test.
```v
struct Embedded {
a &int
}
fn new_embedded() Embedded {
return Embedded{
a: unsafe { nil }
}
}
struct Outer {
Embedded
}
fn main() {
o := Outer{
Embedded: new_embedded()
}
println(o)
}
Outer{
Embedded: Embedded{
a: &nil
}
}
```
=> checker: fix embedded structure initialization warnings (fix #18376)

vlib/arrays/arrays.v
This PR correct method comments for the arrays module.
- The original vdoc will see many examples of comments that are incorrect.
=> arrays: correct method comments for the arrays module

doc/docs.md
I noticed a few things while reading the docs:
1) "casted" doesn't exist, it's called "cast";
2) In line 518, I believe the comment should be about "y", not about "x". "x" is clearly declared as f32 in the line above.
=> docs: Fixing a few typos

vlib/v/ast/types.v, vlib/v/gen/c/auto_str_methods.v, vlib/v/gen/js/auto_str_methods.v, vlib/v/tests/string_interpolation_struct_with_usize_field_test.v
Consider:
```v
struct StructWithUsizeField {
f_usize usize
f_u64   u64
f_u32   u32
//
f_isize isize
f_i64   i64
f_i32   i32
}
fn main() {
a := StructWithUsizeField{
f_usize: usize(-1)
f_isize: isize(-1)
f_u64: u64(-1)
f_i64: i64(-1)
f_u32: u32(-1)
f_i32: i32(-1)
}
dump(a)
}
```
On master, it prints:
```
[x.v:20] a: StructWithUsizeField{
f_usize: -1
f_u64: 18446744073709551615
f_u32: 4294967295
f_isize: -1
f_i64: -1
f_i32:     i32(-1)
}
```
Notice that `f_usize: -1`, which is wrong. That is because on master, `usize` fields are stringified as i32, which loses information on 64bit platforms, and changes the sign.
With this PR:
```
[x.v:20] a: StructWithUsizeField{
f_usize: 18446744073709551615
f_u64: 18446744073709551615
f_u32: 4294967295
f_isize: -1
f_i64: -1
f_i32:     i32(-1)
}
```
=> cgen: fix stringification of usize struct fields (before, they were treated as 32 bit *signed* numbers)

vlib/net/http/cookie_test.v, vlib/strconv/tables.v, vlib/v/fmt/tests/array_init_comment_ending_keep.vv, vlib/v/scanner/scanner.v
This PR fix indent error for line comment generated by vdoc.
before:
```v
yuyi@yuyi-PC:~$ v doc time
module time
const (
days_string        = 'MonTueWedThuFriSatSun'
long_days          = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday',
'Sunday']
month_days         = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
months_string      = 'JanFebMarAprMayJunJulAugSepOctNovDec'
long_months        = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August',
'September', 'October', 'November', 'December']
// The unsigned zero year for internal calculations.
// Must be 1 mod 400, and times before it will not compute correctly,
// but otherwise can be changed at will.
absolute_zero_year = i64(-292277022399)
seconds_per_minute = 60
seconds_per_hour   = 60 * …
```
=> scanner: fix indent error for line comment generated by vdoc

cmd/tools/vdoc/utils.v
This PR highlight comments with gray color in vdoc.
=> vdoc: highlight comments with gray color

vlib/builtin/array.v, vlib/builtin/map.v, vlib/builtin/string.v
Note the maximum RAM usage for the following program. It is significantly lower with this PR (1611608KB vs 1918948KB):
Program:
```v
fn work_with_map() {
mut m := map[string]int{}
for i in 0 .. 4_000_000 {
m['k_${i}'] = i
}
eprintln('   > m.len: ${m.len:10}')
unsafe { m.free() }
}
fn main() {
eprintln('start')
for k in 0 .. 10 {
work_with_map()
eprintln('k: ${k:10}')
}
eprintln('stop')
}
```
On master:
```
#0 17:19:41 ᛋ master /v/vnew❱xtime ./m_old
start
> m.len:    4000000
k:          0
GC Warning: Repeated allocation of very large block (appr. size 67112960):
May lead to memory leak and poor performance
> m.len:    4000000
k:          1
> m.len:    4000000
k:          2
> m.len:    4000000
k:          3
> m.len:    4000000
k:          4
GC Warning: Repeated allocation of very large …
```
=> builtin: zero out internal map/array pointers on m.free(), to reduce the work for the GC mark phase for non escaping maps/arrays, used in hot loops

examples/pendulum-simulation/modules/sim/anim/app.v, vlib/v/fmt/fmt.v, vlib/v/fmt/struct.v, vlib/v/fmt/tests/fn_with_short_args_keep.vv, vlib/v/gen/native/amd64.v, vlib/v/gen/native/gen.v
This PR fix fn with short arguments (fix #18398).
- Fix fmt of fn with short arguments.
- Add test.
fn_with_short_args_keep.vv
```v
struct Config {
name string
age  int
}
fn get_info(a int, b string, c Config) string {
return b + '-' + c.name + '-${a}'
}
fn main() {
ret1 := get_info(11, 'aaaaabbbbb',
name: 'john'
age: 11
)
println(ret1)
ret2 := get_info(22, 'aaaaabbbbbcccccdddddeeeeefffffggggghhhhhiiiiijjjjjkkkkklllllmmmmm',
name: 'bob'
age: 22
)
println(ret2)
}
```
=> fmt: fix fn with short arguments (fix #18398)

vlib/v/gen/c/fn.v, vlib/v/tests/fn_voidptr_param_call_with_nonpointer_rvalue_test.v
This PR fix fn voidptr param calling with nonpointer rvalue (fix #18424).
- Fix fn voidptr param calling with nonpointer rvalue.
- Add test.
```v
import eventbus
struct MyMessage {
msg string
}
fn main() {
eb := eventbus.new()
mut subscriber := eb.subscriber
subscriber.subscribe('my_publish', subscriber_method)
do_something(eb)
assert true
}
fn subscriber_method(receiver voidptr, ev &MyMessage, sender voidptr) {
dump(ev)
}
fn do_something(eb &eventbus.EventBus) {
eb.publish('my_publish', eb, MyMessage{ msg: 'this is my message' })
}
[.\\tt1.v:18] ev: &MyMessage{
msg: 'this is my message'
}
```
=> cgen: fix fn voidptr param calling with nonpointer rvalue (fix #18424)

vlib/v/ast/types.v, vlib/v/checker/assign.v, vlib/v/checker/check_types.v, vlib/v/checker/checker.v, vlib/v/checker/containers.v, vlib/v/checker/fn.v, vlib/v/checker/return.v, vlib/v/checker/struct.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/json.v, vlib/v/gen/native/amd64.v, vlib/v/gen/native/gen.v, vlib/v/gen/wasm/gen.v, vlib/v/gen/wasm/mem.v, vlib/v/gen/wasm/ops.v
This PR remove redundant method is_real_pointer().
- `is_real_pointer()` is same as `is_any_kind_of_pointer()`.
```v
[inline]
pub fn (t Type) is_any_kind_of_pointer() bool {
return (int(t) >> 16) & 0xff > 0 || (u16(t) & 0xffff) in ast.pointer_type_idxs
}
[inline]
pub fn (typ Type) is_real_pointer() bool {
return typ.is_ptr() || typ.is_pointer()
}
```
=> ast: remove redundant method is_real_pointer()

vlib/v/checker/if.v, vlib/v/checker/match.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/if.v, vlib/v/gen/c/match.v, vlib/v/tests/if_expr_with_continue_in_branch_test.v
This PR fix if/match expr with continue in branch (fix #18457).
- Fix if/match expr with continue in branch.
- Add test.
```v
fn main() {
mut result := []int{}
for i in 0 .. 10 {
s := if i < 2 {
100 + i
} else {
continue
}
println(s)
result << s
}
assert result.len == 2
assert result[0] == 100
assert result[1] == 101
}
100
101
[100, 101]
```
=> checker, cgen: fix if/match expr with continue in branch (fix #18457)

vlib/v/ast/ast.v, vlib/v/checker/assign.v, vlib/v/checker/check_types.v, vlib/v/checker/checker.v, vlib/v/checker/containers.v, vlib/v/checker/fn.v, vlib/v/checker/infix.v, vlib/v/checker/match.v, vlib/v/checker/postfix.v, vlib/v/checker/return.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/struct.v, vlib/v/parser/fn.v
This PR clean up with is_any_kind_of_pointer().
- Change `typ.is_ptr() || typ.is_pointer()` to `typ.is_any_kind_of_pointer()`.
=> all: clean up with is_any_kind_of_pointer()

vlib/v/checker/checker.v, vlib/v/gen/c/cgen.v, vlib/v/tests/generics_method_variable_test.v
This PR fix generic method variable (fix #18505).
- Fix generic method variable.
- Add test.
```v
type Func = fn (string) string
struct Struct[T] {
a T
mut:
func Func
}
fn (st Struct[T]) foo[T](s string) string {
println('${st.a} - ${s}')
return '${st.a} - ${s}'
}
fn main() {
mut st := Struct[int]{
a: 22
}
st.func = st.foo
ret := st.func('hello')
assert ret == '22 - hello'
}
22 - hello
```
=> checker, cgen: fix generic method variable (fix #18505)

vlib/builtin/sorted_map.v
This PR makes a minor cleanup in sorted_map.v.
- Change `0` to `unsafe { nil }`.
=> builtin: minor cleanup in sorted_map.v

vlib/time/parse.c.v, vlib/x/json2/json2.v
This PR fixes a couple of issues I found when trying to decode ISO 8601 timestamps in a JSON string (generated from a .NET app)
The changes are as follows:
Increased the maximum number of digits for milliseconds that can be parsed by `time.parse_iso8601()` from 6 to 9 (.NET generates 7, which caused an error)
Removed the length check in x.json2 for iso8601 dates to allow it to try and parse times as well. This check still isn't perfect, as it just checks if a string has a `-` at index 4 and 7, but a more comprehensive check may hurt performance.
made x.json2 use the `[json: 'name']` attribute for times like it does everything else
=> time, x.json2: Improve iso8601 decoding

vlib/v/checker/struct.v, vlib/v/checker/tests/struct_voidptr_field_init_err.out, vlib/v/checker/tests/struct_voidptr_field_init_err.vv
This PR check struct init with pointer field (fix #18485).
- Check struct init with pointer field.
- Add test.
```v
struct Example {
example voidptr
}
fn main() {
println(Example{
example: get()
})
}
fn get() string {
return 'hello'
}
tt1.v:7:3: error: cannot assign to field `example`: expected a pointer `voidptr`, but got `string`
6 |     println(Example{
7 |         example: get()
|         ~~~~~~~~~~~~~~
8 |     })
9 | }
```
=> checker: check struct init with pointer field (fix #18485)

vlib/v/checker/struct.v, vlib/v/checker/tests/struct_field_init_with_result_err.out, vlib/v/checker/tests/struct_field_init_with_result_err.vv
This PR check struct field init with result value (fix #18511).
- Check struct field init with result value.
- Add test.
```v
fn example() !int {
return 0
}
struct Example {
example int
}
fn main() {
println(Example{example()})
}
tt1.v:10:18: error: example() returns a Result, so it should have either an `or {}` block, or `!` at the end
8 | 
10 |     println(Example{example()})
|                     ~~~~~~~~~
11 | }
```
=> checker: check struct field init with result value (fix #18511)

vlib/v/parser/struct.v, vlib/v/tests/modules/module_a/module_a.v, vlib/v/tests/modules/module_b/module_b.v, vlib/v/tests/multiple_embed_external_interface_test.v
This PR fix multiple embedded external module interface (fix #18527).
- Fix multiple embedded external module interfaces.
- Add test.
```v
import module_a
import module_b
pub interface MyInterface {
module_a.Writer
module_b.Reader
}
fn main() {
println('abc')
}
abc
```
=> parser: fix multiple embedded external module interface (fix #18527)

vlib/builtin/builtin_windows.c.v, vlib/builtin/cfns.c.v, vlib/os/os.c.v, vlib/os/os_windows.c.v, vlib/time/time.c.v, vlib/v/parser/parser.v
- parser: remove the hardcoded list of `C.statvfs`, `C.stat`, `C.sigaction`, for the known C struct names, that are C function names as well
- fix for `./v -b js_browser examples/tetris/tetris.js.v`
- fix `v vlib/v/gen/c/coutput_test.v`
=> parser: remove hardcoded check for function calls for `C.stat`, `C.sigaction`, etc

vlib/v/checker/assign.v, vlib/v/checker/checker.v, vlib/v/checker/tests/shared_param_assign_err.out, vlib/v/checker/tests/shared_param_assign_err.vv
This PR check shared parameter assigning (fix #18525).
- Check shared parameter assigning.
- Add test.
```v
fn foo(shared arr []string) {
arr2 := arr
println(arr2)
}
fn main() {
shared arr := ['']
foo(shared arr)
}
tt1.v:2:10: error: `arr` is `shared` and must be `rlock`ed or `lock`ed to be used as non-mut right-hand side of assignment
1 | fn foo(shared arr []string) {
2 |     arr2 := arr
|             ~~~
3 |     println(arr2)
4 | }
tt1.v:3:10: error: `arr2` is `shared` and must be `rlock`ed or `lock`ed to be used as non-mut argument to print
1 | fn foo(shared arr []string) {
2 |     arr2 := arr
3 |     println(arr2)
4 | }
5 |
```
=> checker: check shared parameter assigning (fix #18525)

vlib/flag/flag.v, vlib/flag/flag_test.v
This PR fix finalize with multiple shortargs (fix #18536).
- Fix finalize with multiple shortargs.
- Add test.
```v
import os
import flag
fn main() {
mut fp := flag.new_flag_parser(os.args)
fp.skip_executable()
a_bool := fp.bool('a_bool', `a`, false, '')
println(a_bool)
b_bool := fp.bool('b_bool', `b`, false, '')
println(b_bool)
c_bool := fp.bool('c_bool', `c`, false, '')
println(c_bool)
additional_args := fp.finalize()!
println(additional_args.join_lines())
}
PS D:\Test\v\tt1> v run . -ab -c
true
true
true
```
=> flag: fix finalize with multiple shortargs (fix #18536)

vlib/v/gen/c/cgen.v, vlib/v/gen/c/index.v
This PR makes a minor cleanup for ast.clear_flags().
- Using `clear_flag(.result)` instead of `clear_flags(.result)` .
=> all: minor cleanup for ast.clear_flags()

cmd/tools/vls.v
`v ls --install` downloads a prebuilt release from the projects _official_ repository.
However, when compiling from source the _original_ repository is being cloned.
This PR fixes that.
:information_source:  I encountered this due to [a recent compilation issue](https://github.com/vlang/vls/pull/442) that is fixed in the official repository only.
```
$ v ls --update --source
> Cloning VLS repo...
> Compiling VLS from source...
v ls error: Cannot compile VLS from source: jsonrpc/jsonrpc.v:7:8: error: cannot import `jsonrpc` into a module with the same name
5 |
6 | import json
7 | import jsonrpc
|        ~~~~~~~
8 | import strings
9 | import io
> Building VLS...
v -g -o /home/werkzeug/.vls/src/bin/vls -gc boehm -cc cc -d use_libbacktrace cmd/vls
Failed building VLS
```
=> vls: fix official repository source

vlib/v/checker/infix.v, vlib/v/tests/autocast_in_if_conds_test.v
This PR implement autocast in if conditions `if n is Ident && n.is_mut { ... }`.
- Implement autocast in if conditions `if n is Ident && n.is_mut { ... }`.
- Add test.
```v
struct S1 {
is_name bool
name    string
}
struct S2 {
field2 bool
}
fn main() {
s := MySumType(S1{
is_name: true
name: 'bob'
})
if s is S1 && s.is_name && s.name == 'bob' {
println('ok')
assert true
} else {
assert false
}
}
ok
```
=> checker: implement autocast in if conditions `if n is Ident && n.is_mut { ... }`

examples/web_crawler/web_crawler.v, vlib/net/html/dom.v, vlib/net/html/dom_test.v, vlib/net/html/tag.v
This PR addresses semantic inconsistencies in the html module.
The main change is about consistent usage of "tag" and "tag**s**".
In `html/dom.v` we currently have functions such as `get_tag_by_attribute` and `get_tags_by_class_name`, both of which return an array of tags. While in `html/tag.v` all functions that return an array of tags are named `get_tags_...` and functions returning a single ?&Tag are named `get_tag_...`.
To achieve consistency the `get_tag_...` functions returning arrays of tags were marked as deprecated and refer to their added `get_tags_...` equivalents.
~~This includes a small breaking change for `get_tags`, which currently retrieves all the tags in the document without taking additional arguments. It was renamed to `get_all_tags`, allowing to use `get_tags(name …
=> net.html: fix semantic inconsistencies of tag retrieving functions

vlib/v/checker/infix.v, vlib/v/tests/autocast_in_if_conds_3_test.v
This PR fix autocast in complex if condtions 2.
- Fix autocast in complex if condtions 2.
- Add test.
```v
struct Info {
name string
}
struct Node {
left MySumType
}
struct S1 {
is_info bool
info    Info
}
fn (s1 S1) is_info() bool {
return s1.is_info
}
struct S2 {
field2 string
}
fn get_name(name string) string {
return name
}
fn main() {
node := Node{
left: MySumType(S1{
is_info: false
info: Info{'foo'}
})
}
a := 22
if a > 0 && node.left is S1 && !node.left.is_info && get_name(node.left.info.name) == 'foo'
&& !node.left.is_info() {
println('ok')
}
}
ok
```
=> checker: fix autocast in complex if condtions 2

vlib/v/checker/infix.v, vlib/v/tests/autocast_in_if_conds_4_test.v
This PR fix autocast in complex if condtions 3.
- Fix autocast in complex if condtions 3.
- Add test.
```v
struct Info {
name string
}
struct S1 {
is_info bool
info    Info
}
struct S2 {
field2 string
}
fn get_name(s1 S1) string {
return s1.info.name
}
fn main() {
s := MySumType(S1{
is_info: false
info: Info{'foo'}
})
if s is S1 && !s.is_info && get_name(s) == 'foo' {
println('ok')
assert true
} else {
assert false
}
}
ok
```
=> checker: fix autocast in complex if condtions 3

vlib/v/checker/infix.v, vlib/v/tests/autocast_in_if_conds_4_test.v
This PR fix autocast in complex if conditions 3.
- Fix autocast in complex if conditions 3.
- Add test.
```v
struct Info {
name string
}
struct S1 {
is_info bool
info    Info
}
struct S2 {
field2 string
}
fn get_name(s1 S1) string {
return s1.info.name
}
fn main() {
s := MySumType(S1{
is_info: false
info: Info{'foo'}
})
if s is S1 && !s.is_info && get_name(s) == 'foo' {
println('ok')
assert true
} else {
assert false
}
}
ok
```
=> checker: fix autocast in complex if conditions 3

vlib/v/ast/ast.v, vlib/v/checker/checker.v, vlib/v/checker/comptime.v, vlib/v/doc/doc.v, vlib/v/parser/v_parser_test.v
This PR change `check(file_ &ast.File)` to `check(mut file ast.File)`.
- Avoid `mut file := unsafe { file_ }`.
=> ast, checker: change `check(file_ &ast.File)` to `check(mut file ast.File)`

vlib/v/checker/infix.v, vlib/v/tests/autocast_in_if_conds_5_test.v
This PR fix autocast in complex if conditions 4.
- Fix autocast in complex if conditions 4.
- Add test.
```v
struct Info {
name string
}
struct Node {
left MySumType
}
struct S1 {
is_info bool
info    Info
}
fn (s1 S1) is_info() bool {
return s1.is_info
}
struct S2 {
field2 string
}
fn get_name(s1 S1) string {
return s1.info.name
}
fn main() {
node := Node{
left: MySumType(S1{
is_info: false
info: Info{'foo'}
})
}
a := 22
if a > 0 && node.left is S1 && !node.left.is_info && get_name(node.left) == 'foo'
&& !node.left.is_info() {
println('ok')
assert true
} else {
assert false
}
}
ok
```
=> checker: fix autocast in complex if conditions 4

vlib/v/gen/c/cgen.v, vlib/v/gen/c/struct.v, vlib/v/gen/c/utils.v
This PR remove `mut mut_table := unsafe { &ast.Table(g.table) }`.
- Make `Gen.table` mutable.
=> cgen: remove `mut mut_table := unsafe { &ast.Table(g.table) }`

vlib/builtin/builtin.c.v, vlib/v/gen/c/array.v, vlib/v/gen/c/spawn_and_go.v
- cgen: fix memleak for `[]T{len: x}`
- use _v_malloc, in the wrapper generated by `spawn f()` as well
Test program:
```v
import os
const mypid = os.getpid()
fn abc(k int, m int) [][]int {
mut z := [][]int{len: k}
z[0] = []int{len: m}
z[0][0] = 9999
z[0][m/2] = 9999
z[0][m-1] = 9999
return z
}
fn f() bool {
x := abc(10_000, 1000)
return x[0][0] == 0
}
fn main() {
mut i := u64(0)        
for {
f()
i++
if i % 1_000 == 0 {
eprintln('> i: $i')
}
}
}
```
(run the above on linux, after executing `ulimit -v 1000000` in the same shell, to limit the amount of available memory to that process to 1GB)
On master, it will fail with:
```
#0 21:46:16 ᛋ master /v/vnew❱xtime ./v run bb.v 
> i: 0
> i: 1000
> i: 2000
> i: 3000
7f3e3e03cbcb : at ???: RUNTIME ERROR: invalid memory access …
```
=> cgen: fix memleak for [][]T{len: x}, or []Struct{len: x}

.github/workflows/v_apps_and_modules_compile_ci.yml
Comment out VLS build steps in `.github/workflows/v_apps_and_modules_compile_ci.yml`.
=> CI: remove vls builds

vlib/builtin/utf8.c.v, vlib/builtin/utf8_test.v
The following now works on both windows and !windows:
```v
a := [u8(67), 0, 76, 0, 52, 0, 54, 0, 73, 0, 49, 0, 65, 0, 48, 0, 48, 0,
54, 0, 52, 0, 57, 0, 0, 0, 0]
assert unsafe{ string_from_wide(a.data) } == 'CL46I1A00649'
```
=> builtin: implement string_from_wide/1 and string_from_wide2/2 on *nix too

vlib/v/checker/checker.v, vlib/v/checker/for.v, vlib/v/checker/if.v, vlib/v/checker/match.v
This PR change `smartcast(expr_ ast.Expr,..)` to `smartcast(mut expr ast.Expr,..)`.
- Avoid `mut expr := unsafe { expr_ }`.
=> checker: change `smartcast(expr_ ast.Expr,..)` to `smartcast(mut expr ast.Expr,..)`

vlib/orm/orm.v, vlib/orm/orm_insert_test.v
Previously this code:
```v
// sets a custom table name. Default is struct name (case-sensitive)
[table: 'customers']
struct Customer {
id        i64 [primary; sql: serial] // a field named `id` of integer type must be the first field
name      string
}
fn main() {
db := sqlite.connect('abc.db')!
sql db {
create table Customer
}!
for i in ["Bob", "Charlie"] {
// insert a new customer
new_customer := Customer{
name: i
}
sql db {
insert new_customer into Customer
}!
}
users:= sql db {
select from Customer
}!
println("${users}")
}
```
produced this:
```
#148 21:17:44 ᛋ fix_18779 /v/vnew❱v -g -d trace_orm run zz_i64.v 
> orm: CREATE TABLE IF NOT EXISTS `customers` (`id` INTEGER, `name` TEXT, PRIMARY KEY(`id`));
> orm: INSERT INTO `customers` (`id`, `name`) VALUES (?1, ?2); …
```
=> orm: fix inserting sequential values (id=0), in tables with an i64 primary field

vlib/v/doc/doc.v, vlib/v/doc/utils.v
This PR cleanup with 'mut expr ast.Expr'.
=> doc: cleanup with 'mut expr ast.Expr'

vlib/v/parser/if_match.v, vlib/v/tests/match_return_reference_test.v
Fixes: #18782 
```v
fn main() {
var := match 0 {
0 {
&Foo{}
}
else {
unsafe { nil }
}
}
assert(var != unsafe { nil })
}
struct Foo{}
fn foo() &Foo {
return match 0 {
0 {
&Foo{}
}
else {
&Foo{}
}
}
}
```
compile: pass.
=> parser: fix compiler error when match returns reference (#18728)

cmd/tools/vtest-self.v, vlib/v/gen/c/cgen.v, vlib/v/tests/nested_or_expr_call_test.v
This PR fix nested or expr call (fix #18803).
- Fix nested or expr call.
- Add test.
```v
// sets a custom table name. Default is struct name (case-sensitive)
[table: 'customers']
struct Customer {
id   int    [primary; sql: serial] // a field named `id` of integer type must be the first field
name string
}
fn main() {
db := sqlite.connect(':memory:')!
sql db {
create table Customer
}!
uid_map := map[int]string{}
uid := 2
username := if uid <= 0 {
'unknown'
} else {
uid_map[uid] or {
users := sql db {
select from Customer where id == uid
} or {
[Customer{
id: uid
name: 'unknown'
}]
}
name := if users.len == 1 { users[0].name } else { 'unknown' }
name
}
}
println('${uid} is ${username}')
}
2 is unknown
```
=> cgen: fix nested or expr call (fix #18803)

vlib/v/checker/assign.v, vlib/v/checker/checker.v, vlib/v/checker/fn.v, vlib/v/checker/if.v, vlib/v/checker/infix.v, vlib/v/checker/match.v, vlib/v/checker/postfix.v
This PR change `fail_if_immutable(expr_ ast.Expr)` to `fail_if_immutable(mut expr ast.Expr)`.
- Avoid `mut expr := unsafe { expr_ }`.
=> checker: change `fail_if_immutable(expr_ ast.Expr)` to `fail_if_immutable(mut expr ast.Expr)`

vlib/v/gen/c/infix.v, vlib/v/tests/shift_test.v
After this PR, this passes without failing the assertion:
```v
fn main() {
x := u32(1)
base := u32(2)
shift := u32(3)
dump(x + base << shift)
dump(x + (base << shift))
dump((x+base) << shift)
assert x + base << shift == (x + (base << shift))
}
```
printing:
```
[file.v:5] x + base << shift: 17
[file.v:6] x + (base << shift): 17
[file.v:7] (x + base) << shift: 24
```
=> cgen: ensure that `<<` and `>>` has higher precedence, than `+` and `-` (diff between C and V precedences)

vlib/v/gen/c/fn.v, vlib/v/tests/anon_fn_direct_call_with_option_test.v
This PR fix anon fn direct call with option (fix #18825).
- Fix anon fn direct call with option.
- Add test.
```v
fn main() {
z := true
a := fn [z] () ?int {
match z {
true { return 1 }
else { return none }
}
}()
b := a or {
println('failed')
return
}
println('b: ${b}')
println(a)
assert b == 1
}
b: 1
Option(1)
```
=> cgen: fix anon fn direct call with option (fix #18825)

vlib/v/gen/c/assign.v, vlib/v/tests/cross_assign_aliased_array_test.v
This PR fix cross assign with aliased array (fix #18828).
- Fix cross assign with aliased array.
- Add test.
```v
pub type IntSlice = []int
pub fn (mut x IntSlice) swap(i int, j int) {
x[i], x[j] = x[j], x[i]
}
fn main() {
mut x := IntSlice([11, 22])
println(x)
x.swap(0, 1)
println(x)
assert x == IntSlice([22, 11])
}
IntSlice([11, 22])
IntSlice([22, 11])
```
=> cgen: fix cross assign with aliased array (fix #18828)

examples/gg/many_thousands_of_circles.v, vlib/gg/gg.c.v
Add a gg example, on how to use several sokol passes, to render lots of primitives, based on <https://discord.com/channels/592103645835821068/713953140952530965/1127785206879879320> .
=> examples: add examples/gg/many_thousands_of_circles.v, document how to use `ctx.end(how:.passthru)`.

vlib/strconv/vprintf.c.v
VSL should be the only V project that uses them actively so far.
I've already marked the usages there with `unsafe {}` in https://github.com/vlang/vsl/commit/b9f4776ff909607c0bd621ebeb4296b235e5aeed .
=> strconv: mark strconv.v_sprintf and strconv.v_printf with [unsafe] (part 2, breaking change, needed an update to vsl)

vlib/v/checker/infix.v
This PR fix autocast in complex if condtions 5.
```v
return node is ast.Ident && node.info is ast.IdentVar && node.kind == .variable
&& ((node as ast.Ident).obj as ast.Var).ct_type_var != .no_comptime
```
to
```v
return node is ast.Ident && node.info is ast.IdentVar && node.kind == .variable
&& (node.obj as ast.Var).ct_type_var != .no_comptime
```
=> checker: fix autocast in complex if condtions 5

vlib/v/checker/tests/const_field_name_snake_case.out, vlib/v/parser/parser.v
This PR change warn to error for const name with upper letter (fix #18838).
- Change warn to error for const name with upper letter.
- Modify the test.
```v
const CMB_CONJUNTO_QT_DE_BOLAS = 10
fn main() {
qt_bolas_selecionadas := 1
if qt_bolas_selecionadas == CMB_CONJUNTO_QT_DE_BOLAS {		
for id := 0; id < 100; id += 1  {
println("valor: ${id}")
}
}	
if qt_bolas_selecionadas == CMB_CONJUNTO_QT_DE_BOLAS {
for id := 0; id < 100; id += 1  {
println("valor: ${id}")
}
}	
}
tt1.v:1:7: error: const names cannot contain uppercase letters, use snake_case instead
1 | const CMB_CONJUNTO_QT_DE_BOLAS = 10
|       ~~~~~~~~~~~~~~~~~~~~~~~~
2 | 
```
=> parser: change warn to error for const name with upper letter (fix #18838)

vlib/v/gen/c/cgen.v, vlib/v/tests/option_map_fn_type_value_test.v
This PR fix option map with fn type value (fix #18786).
- Fix option map with fn type value.
- Add test.
```v
const mouse_action_to_function_map = {
1: handle_mouse_down_signal
}
fn handle_mouse_down_signal() string {
return 'hello'
}
fn main() {
t := mouse_action_to_function_map[1] or { return }
println(t())
assert t() == 'hello'
}
hello
```
=> cgen: fix option map with fn type value (fix #18786)

vlib/v/gen/c/cgen.v, vlib/v/tests/return_option_call_test.v
This PR fix return option call (fix #18848).
- Fix return option call.
- Add test.
```v
fn issue(data string) ?(int, string) {
if data.len == 0 {
return none
}
return data.len, data
}
fn wrapper(data string) ?(int, string) {
return issue(data)
}
fn main() {
dump(wrapper('issue'))
dump(wrapper('foobar'))
dump(wrapper(''))
assert true
}
[.\\tt1.v:13] wrapper('issue'): Option((5, 'issue'))
[.\\tt1.v:14] wrapper('foobar'): Option((6, 'foobar'))
[.\\tt1.v:15] wrapper(''): Option(none)
```
=> cgen: fix return option call (fix #18848)

vlib/v/checker/checker.v, vlib/v/checker/containers.v, vlib/v/checker/fn.v, vlib/v/checker/infix.v, vlib/v/checker/interface.v, vlib/v/checker/match.v, vlib/v/checker/orm.v, vlib/v/checker/struct.v, vlib/v/checker/tests/any_int_float_ban_err.out, vlib/v/checker/tests/private_redeclaration_of_C_struct.out
This PR clean up ensure_type_exists().
=> checker: clean up ensure_type_exists()

vlib/v/checker/checker.v, vlib/v/checker/tests/generic_sumtype_decl_err_d.out, vlib/v/checker/tests/generic_sumtype_decl_err_d.vv, vlib/v/checker/tests/generic_sumtype_decl_err_e.out, vlib/v/checker/tests/generic_sumtype_decl_err_e.vv
This PR check generic sumtype declaration (fix #18741).
- Check generic sumtype declaration.
- Add test.
```v
type Fn[T] = fn (string) T
type Fnn = fn (string) string
type Parser = Fn | Fnn
fn main() {
println('hello')
}
tt1.v:5:15: error: generic fntype `Fn` must specify generic type names, e.g. Fn[T]
3 | type Fnn = fn (string) string
4 | 
5 | type Parser = Fn | Fnn
|               ~~
6 | 
```
```v
type Fn[T] = fn (string) T
type Fnn = fn (string) string
type Parser[T] = Fn[T] | Fnn
fn f(x string) string { return '>> f $x' }
fn main() {
_ := Parser(f)
}
tt1.v:10:10: error: generic sumtype `Parser` must specify type parameter, e.g. Parser[int]
8 | 
10 |     _ := Parser(f)
|          ~~~~~~~~~
11 | }
```
=> checker: check generic sumtype declaration (fix #18741)

vlib/crypto/pem/decode.v, vlib/crypto/pem/encode.v, vlib/crypto/pem/pem.v, vlib/crypto/pem/pem_test.v
This PR deprecates the `new` function in favour of the new static methods and adds test cases for input data that doesn't contain complete PEM data.
Would it be good to make `decode` a static method as well or would we be getting into territory of making everything a static method making it a messy?
=> crypto.pem: make static method `Block.new` to replace `new`

vlib/v/gen/c/cgen.v, vlib/v/gen/c/struct.v
This PR format generated c codes of sorted structs.
before:
```v
// #start sorted_symbols
struct none {
EMPTY_STRUCT_DECLARATION;
};
struct ContextRecord {
EMPTY_STRUCT_DECLARATION;
};
struct ExceptionPointers {
ExceptionRecord* exception_record;
ContextRecord* context_record;
};
struct None__ {
Error Error;
};
struct StrIntpCgenData {
string str;
string fmt;
string d;
};
struct GCHeapUsage {
usize heap_size;
usize free_bytes;
usize total_bytes;
usize unmapped_bytes;
usize bytes_since_gc;
};
struct VCastTypeIndexName {
int tindex;
string tname;
};
struct VAssertMetaInfo {
string fpath;
int line_nr;
string fn_name;
string src;
string op;
string llabel;
string rlabel;
string lvalue;
string rvalue;
string message;
bool has_msg;
};
struct MethodArgs {
int typ;
string name;
};
struct …
```
=> cgen: format generated c codes of sorted structs

vlib/v/checker/checker.v, vlib/v/gen/c/cgen.v, vlib/v/tests/closure_with_sumtype_var_test.v
This PR fix closure with inherited sumtype variable (fix #18869).
- Fix closure with inherited sumtype variable.
- Add test.
```v
import encoding.binary
import rand
type DataType = int | string
struct DataBuilder {
mut:
func fn (mut []u8)
len  int
}
pub fn (mut d DataBuilder) add(v DataType) {
func := d.func
len := d.len
d.func = fn [v, len, func] (mut b []u8) {
if !isnil(func) {
func(mut b)
}
match v {
int {
binary.big_endian_put_u32_at(mut b, u32(v), len)
}
string {
binary.big_endian_put_u16_at(mut b, u16(v.len), len)
for i := 0; i < v.len; i++ {
b[len + 2 + i] = v[i]
}
}
}
}
d.len += match v {
int { 4 }
string { 2 + v.len }
}
}
pub fn (d &DataBuilder) build() []u8 {
mut b := []u8{len: d.len}
d.func(mut b)
binary.big_endian_put_u16(mut b, u16(d.len - 2))
unsafe {
d.func = nil
d.len = 2 …
```
=> checker, cgen: fix closure with inherited sumtype variable (fix #18869)

vlib/v/gen/c/cgen.v
This PR format generated c codes of hash stmt and enum decl.
before:
```v
// V includes:
#if defined(__TINYC__) && defined(__has_include)
// tcc does not support has_include properly yet, turn it off completely
#undef __has_include
#endif
// added by module `builtin`, file: builtin_d_gcboehm.c.v:98:
#if defined(__has_include)
#if __has_include(<gc.h>)
#include <gc.h>
#else
#error VERROR_MESSAGE Header file <gc.h>, needed for module `builtin` was not found. Please install the corresponding development headers.
#endif
#else
#include <gc.h>
#endif
// added by module `builtin`, file: float.c.v:9:
#if defined(__has_include)
#if __has_include(<float.h>)
#include <float.h>
#else
#error VERROR_MESSAGE Header file <float.h>, needed for module `builtin` was not found. Please install the …
```
=> cgen: format generated c codes of hash stmt and enum decl

vlib/strconv/atoi.v, vlib/strconv/atoi_test.v
**What is inside**
- this code fix the bug #18875 
- added more tests for `common_parse_uint2`
=> strconv.atoi: bug fix #18875

vlib/time/time.v, vlib/time/time_test.v
Adding a duration/integer to a Time object via `.add()` or `.add_days()` or `add_seconds()` returns a new Time object that does not preserve the original state of `is_local` value.
The state should be preserved in order not to loose it which can lead to unexpected/strange results.
=> time: fix loosing of is_local flag after adding duration

vlib/readline/readline_nix.c.v
currently the output of `readline` includes the new line character at the end of the string which it shouldn't. 
problem: 
```v
input := read_line('> ')!
// type <hello> and press enter
print(input.len) // output is 6 but should be 5
```
=> readline: remove new line \n character from readline output

vlib/builtin/js/string.js.v, vlib/builtin/string.v, vlib/builtin/utf8.v, vlib/toml/input/input.v, vlib/toml/toml.v
Before:
```
#0 14:11:46 ᛋ master /v/vnew❱rg deprecated_after|grep 2022
vlib/net/http/response.v:13:text         string [deprecated: 'use Response.body instead'; deprecated_after: '2022-10-03']
vlib/net/http/response.v:121:text    string  [deprecated: 'use ResponseConfig.body instead'; deprecated_after: '2022-10-03']
vlib/builtin/utf8.v:71:[deprecated_after: '2022-05-28']
vlib/time/chrono.v:21:[deprecated_after: '2022-11-23']
vlib/builtin/array.v:956:[deprecated_after: '2022-10-11']
vlib/builtin/js/string.js.v:360:[deprecated_after: '2022-01-19']
vlib/builtin/js/string.js.v:368:[deprecated_after: '2022-01-19']
vlib/builtin/string.v:1683:[deprecated_after: '2022-01-19']
vlib/builtin/string.v:1691:[deprecated_after: '2022-01-19']
vlib/toml/input/input.v:21:[deprecated_after: '2022-06-18'] …
```
=> vlib: remove methods deprecated before 2022-07-22

vlib/v/fmt/fmt.v, vlib/v/fmt/tests/comptime_call_keep.vv
This PR fix formatting of the comptime call (fix #18942).
- Fix formatting of the comptime call.
- Add test.
```v
$if linux {
$compile_error("This won't be formatted correctly by v fmt :')")
}
fn main() {}
```
=> fmt: fix formatting of the comptime call (fix #18942)

vlib/time/time_windows.c.v, vlib/v/gen/c/infix.v, vlib/v/tests/infix_expr_with_overflow_test.v, vlib/x/ttf/common.v, vlib/x/ttf/render_sokol_cpu.v, vlib/x/ttf/ttf.v, vlib/x/ttf/ttf_test.v
This PR fix infix expr with number overflow (fix #18905).
- Fix infix expr with number overflow.
- Add test.
```v
fn main() {
a := u8(255)
b := u8(1)
c := a + b
println(c)
assert c == 0
println(a + b)
assert a + b == 0
println(a + b < a)
assert a + b < a
}
0
0
true
```
=> cgen: fix infix expr with number overflow (fix #18905)

vlib/v/checker/checker.v, vlib/v/tests/const_from_multi_branchs_of_if_expr_test.v
This PR fix const from multi branchs of if expr (fix #18933).
- Fix const from multi branchs of if expr.
- Add test.
```v
import os
const bin = $if linux {
os.join_path(@VMODROOT, 'bin_linux_64')
} $else $if macos {
os.join_path(@VMODROOT, 'bin_macos')
} $else {
''
}
fn main() {
println('Hello')
}
Hello
```
=> checker: fix const from multi branchs of if expr (fix #18933)

vlib/v/scanner/scanner.v, vlib/v/tests/string_interpolation_match_expr_test.v
This PR fix string interpolation with match expr (fix #18963).
- Fix string interpolation with match expr.
- Add test.
```v
fn main() {
x := 0
println('Hello ${match x {
0 { 'John' }
1 { 'George' }
else { 'Others' }
}}')
assert '${match x {
0 { 'John' }
1 { 'George' }
else { 'Others' }
}}' == 'John'
}
Hello John
```
=> scanner: fix string interpolation with match expr (fix #18963)

vlib/vweb/parse.v
This PR makes routes in vweb specified through attributes case sensitive (e.g. `['/index'] fn index() {...` is different to `['/Index'] fn index() {...`). This fixes #17960, and seemed to work great for me in my testing (including unit tests), however I'm still not sure about it, as this seemed to work a little too well and be too easy. Things in software are never just a one line fix with no side effects, so when someone finds that their project doesn't work anymore because of this, please let me know before it's merged (if it gets merged) :)
As discussed in #17960, this does seem to be the "correct" way of doing this, as URLs are case sensitive and therefore vweb should treat them as such, although it does beg the question of if there should be a config option somewhere to use case …
=> vweb: Make routes case sensitive

vlib/v/checker/check_types.v, vlib/v/checker/tests/fn_call_arg_array_mismatch_err.out, vlib/v/checker/tests/fn_call_arg_array_mismatch_err.vv
This PR check fn call argument mismatch for array struct type (fix #18967).
- Check fn call argument mismatch for array struct type.
- Add test.
```v
import os
const (
service_file = '[Unit]'
service_path = 'dockerman.service'
)
fn main() {
os.write_file_array(service_path, service_file) or {
eprintln('Error: write file service')
exit(1)
}
}
tt1.v:9:36: error: cannot use `string` as `array` in argument 2 to `os.write_file_array`
7 | 
9 |     os.write_file_array(service_path, service_file) or {
|                                       ~~~~~~~~~~~~
10 |         eprintln('Error: write file service')
11 |         exit(1)
```
=> checker: check fn call argument mismatch for array struct type (fix #18967)

vlib/v/checker/fn.v, vlib/v/slow_tests/valgrind/fn_call_result_arg.v
This PR fix running `f(g()!)` with autofree mode (fix #18930).
- Fix running `f(g()!)` with autofree mode.
- Add test.
```v
fn f() !string {
return 'abc'
}
fn g(s string) {
println(s)
}
fn main() {
g(f()!)
}
PS D:\Test\v\tt1> v -autofree run .
abc
```
=> checker: fix running `f(g()!)` with autofree mode (fix #18930)

vlib/v/fmt/fmt.v, vlib/v/fmt/tests/interface_fields_with_pre_comments_keep.vv, vlib/v/parser/struct.v
This PR fix formatting interface fields with pre-comments (fix #18980, fix #18981).
- Fix formatting interface fields with pre-comments.
- Add test.
vlib\v\fmt\tests\interface_fields_with_pre_comments_keep.vv
```v
module main
fn main() {
}
pub interface IOperateInfo {
mut:
// title
title string
// msg
msg string
// id
id string
}
```
=> parser, fmt: fix formatting interface fields with pre-comments (fix #18980)

doc/docs.md, vlib/v/ast/ast.v, vlib/v/fmt/struct.v, vlib/v/fmt/tests/struct_decl_with_comments_keep.vv, vlib/v/fmt/tests/structs_expected.vv, vlib/v/parser/struct.v
This PR fix formatting struct declaration with comments (fix #18982).
- Fix formatting struct declaration with comments.
- Add test.
vlib\v\fmt\tests\struct_decl_with_comments_keep.vv
```v
module main
fn main() {
}
pub struct OperateInfo { // implements IperateInfo
pub mut:
title string // title
// msg
msg string
// id
id string
} // operate info
```
=> ast, parser, fmt: fix formatting struct declaration with comments (fix #18982)

vlib/v/parser/for.v, vlib/v/tests/for_c_init_with_var_assign_test.v
This PR fix for_c_stmt that init with var assign (fix #18999).
- Fix for_c_stmt that init with var assign.
- Add test.
```v
fn main() {
mut v := 4
mut r := 0
for v >>= 1; v != 0; v >>= 1 {
r++
}
println(r)
assert r == 2
}
2
```
=> parser: fix for_c_stmt that init with var assign (fix #18999)

vlib/v/checker/fn.v, vlib/v/checker/tests/fn_array_decompose_arg_mismatch_err_c.out, vlib/v/checker/tests/fn_array_decompose_arg_mismatch_err_c.vv
Fixed: #18995 
```v
fn main() {
foo(...args)
}
fn foo() {
}
```
```
vlib/v/checker/tests/fn_array_decompose_arg_mismatch_err_c.vv:2:6: error: expected 0 arguments, but got 1
2 |     foo(...args)
|         ~~~~~~~
3 | }
4 |
```
=> checker: fix compiler panic for passing an extra decompose parameter to a function (fix: 18995)

vlib/v/fmt/fmt.v, vlib/v/fmt/tests/interface_method_with_pre_comments_keep.vv, vlib/v/parser/struct.v
This PR fix formatting interface method with pre-comments (related #18980).
- Fix formatting interface method with pre-comments.
- Add test.
vlib\v\fmt\tests\interface_method_with_pre_comments_keep.vv
```v
module main
fn main() {
}
pub interface IOperateResult {
mut:
// is_success
is_success bool
// is_show_msg
is_show_msg bool
// msg
msg string
// comment before method def
set_msg(msg string) // comment after method def
}
```
=> parser, fmt: fix formatting interface method with pre-comments (related #18980)

vlib/builtin/string.v, vlib/builtin/string_test.v
```v
module man
fn main() {
assert '1:2:3'.split_nth(':', 2) == ['1', '2:3']
assert '123'.split_nth('', 2)    == ['1', '23']
assert '1:2:3'.rsplit_nth(':', 2) == ['3', '1:2']
assert '123'.rsplit_nth('', 2)    == ['3', '12']
assert ''.split_nth('', 2)  == []
assert ''.rsplit_nth('', 2) == []
println('success')
}
```
Fix bugs in `string.split_nth` and `string.rsplit_nth` with empty delimiters. Preserve the delimiter characters in the output substrings. (#18997)
=> builtin: fix split_nth() and rsplit_nth() on an empty delimeter

vlib/v/checker/check_types.v, vlib/v/checker/checker.v, vlib/v/checker/struct.v, vlib/v/tests/generics_struct_field_with_default_fn_type_test.v
This PR fix generic struct field with default fn_type value (fix #19011).
- Fix generic struct field with default fn_type value.
- Add test.
```v
[heap]
struct BloomFilter1[T] {
hash_func     fn (T) u32 = unsafe { nil } // hash function, input [T] , output u32
table_size    int        // every entry is one-bit, packed into `table`
num_functions int        // 1~16
}
[heap]
struct BloomFilter2[T] {
// TODO V bug
hash_func     fn (T) u32 = default_cb[T] // hash function, input [T] , output u32
table_size    int        // every entry is one-bit, packed into `table`
num_functions int        // 1~16
mut:
table []u8
}
fn default_cb[T](x T) u32 {
return 22
}
fn main() {
filter1 := BloomFilter1[int]{}
println(filter1)
assert true
filter2 := BloomFilter2[int]{}
println(filter2.hash_func(11))
assert …
```
=> checker: fix generic struct field with default fn_type value (fix #19011)

vlib/v/parser/fn.v, vlib/v/parser/parse_type.v, vlib/v/parser/struct.v
This PR change `fn_args()` to `fn_params()` and cleanup all the related calls.
=> parser: change `fn_args()` to `fn_params()`

vlib/v/parser/parse_type.v, vlib/v/tests/parse_thread_type_test.v
Fixed: #19029 
```v
struct Foo1 {
before_1 int
thr      thread
after_1  int
after_2  int
after_3  int
}
struct Foo2 {
thr thread
a   ?int
}
struct Foo3 {
thrs []thread
a    []int
}
struct Foo4 {
thrs []thread int
a    []int
}
fn test_parse_thread_type() {
_ = &Foo1{}
_ = &Foo2{}
_ = &Foo3{}
_ = &Foo4{}
assert true
}
```
```
passed.
```
=> parser: fix improper token advancement when parsing the types of struct thread type fields(fix #19029)

vlib/v/fmt/tests/fn_with_args_comments_keep.vv
This PR fix formatting of fn with argument comments (fix #15354).
- Add test.
vlib\v\fmt\tests\fn_with_args_comments_keep.vv
```v
fn main() {
filtered_links := text_processing.filter_links(links, /* unwanted_domains = */ [
'www.kickstarter.com',
'www.pepper.pl',
'tenor.com',
'www.wykop.pl',
'giphy.com',
])
}
```
=> fmt: fix formatting of fn with argument comments (fix #15354)

vlib/v/gen/c/for.v, vlib/v/parser/for.v, vlib/v/tests/for_c_init_with_var_inc_test.v
This PR fix `for i++; i<10; i++ {` (fix #18445).
- Fix for_c_stmt that init is `i++`.
- Add test.
```v
fn main() {
mut results := []int{}
mut i := 0
for i++; i < 10; i++ {
println(i)
results << i
}
assert results == [1, 2, 3, 4, 5, 6, 7, 8, 9]
}
1
2
3
4
5
6
7
8
9
```
=> parser, cgen: fix `for i++; i<10; i++ {` (fix #18445)

vlib/v/parser/expr.v, vlib/v/tests/parse_type_of_ref_array_from_another_mod_test.v
1、Fix #19033 
2、Add test.
```v
import another_module
struct SomeStruct {}
fn type_from_another_mod() {
_ = &[]another_module.SomeStruct{}
}
fn type_from_current_mod() {
_ = &[]SomeStruct{}
}
```
```
passed.
```
=> parser: fix parse error in the type of a ref array when the element type is a structure of another mod(fix #19033)

vlib/v/fmt/tests/comptime_if_expr_script_keep.vv, vlib/v/parser/parser.v
This PR fix formatting comptime if expr script (fix #15073).
- Fix formatting comptime if expr script.
- Add test.
vlib\v\fmt\tests\comptime_if_expr_script_keep.vv
```v
mut pre_built_str := ''
$if prebuilt ? {
the_date := if $env('DATE') != '' { $env('DATE') } else { '##DATE##' }
pre_built_str = '[pre-built binary release (${the_date})]\n'
}
dump(pre_built_str)
```
=> parser: fix formatting comptime if expr script (fix #15073)

vlib/v/gen/c/str_intp.v, vlib/v/tests/string_interpolation_test.v
1. Fix #19048 
2. Add test.
```v
struct Foo {
}
fn (mut f Foo) intp_pointer() string {
return '${f:p}'
}
fn main() {
mut foo := Foo{}
str1 := foo.intp_pointer()
str2 := '${&foo:p}'
assert str1 == str2
}
```
```
passed
```
=> cgen: fix an error when interpo a ptr and specifier is p(fix #19048)

vlib/v/ast/str.v, vlib/v/fmt/fmt.v, vlib/v/fmt/tests/fn_headers_with_inline_comments_expected.vv
This PR simplify fmt.fn_decl().
- Remove fmt.fn_header().
- Avoid duplicate codes.
=> ast, fmt: simplify fmt.fn_decl()

vlib/os/notify/backend_darwin.c.v, vlib/os/notify/kqueue.h, vlib/os/notify/notify_test.v
On the premise of keeping the existing interface of the Notifier completely unchanged, the implementation of kqueue has been added. Because in order to maintain interface consistency, there are some slight tailoring in the features of kqueue, but it does not affect its use in most scenarios.
Although kqueue can be used on platforms such as UNIX, freeBSD, and openBSD, there may be slight differences between different platforms. I have not tested it on these platforms yet, so I will set it as the macos platform first.
```
v run vlib/os/notify/notify_test.v
```
passed.
=> os: implement the kqueue backend for os.Notifier

vlib/v/ast/str.v, vlib/v/fmt/tests/fn_headers_with_param_comments_expected.vv, vlib/v/fmt/tests/fn_headers_with_param_comments_input.vv
This PR fix formatting fn header with parameter comments (fix #16879).
- Fix formatting fn header with parameter comments.
- Add test.
```v
fn foo(
// Foo
s string) {
}
fn bar(/*p1*/a string, /*p2*/b int) {
println('hello')
}
```
fmt to:
```v
fn foo(
// Foo
s string) {
}
fn bar( /* p1 */ a string, /* p2 */ b int) {
println('hello')
}
```
=> ast: fix formatting fn header with parameter comments (fix #16879)

vlib/v/checker/fn.v, vlib/v/tests/struct_field_fn_call_test.v
This PR fix struct field fntype value call (fix #19063).
- Fix struct field fntype value call.
- Add test.
```v
struct Foo {
f fn (Foo) int = dummy
}
fn dummy(s Foo) int {
return 22
}
fn (mut s Foo) fun() int {
return s.f(s)
}
fn main() {
mut s := Foo{}
ret := s.fun()
println(ret)
}
22
```
=> checker: fix struct field fntype value call (fix #19063)

vlib/v/fmt/tests/c_fn_headers_with_comments_expected.vv, vlib/v/fmt/tests/c_fn_headers_with_comments_input.vv, vlib/v/parser/fn.v
This PR fix formatting of `C.f(/*mut*/buff &char) i64` (fix #17195).
- Fix formatting of `C.f(/*mut*/buff &char) i64`.
- Add test.
```v
module main
fn main() {
println('Hello World!')
}
fn C.f(/*mut*/buff &char) i64
```
fmt to:
```v
module main
fn main() {
println('Hello World!')
}
fn C.f( /* mut */ buff &char) i64
```
=> fmt: fix formatting of `C.f(/*mut*/buff &char) i64` (fix #17195)

vlib/os/notify/backend_darwin.c.v, vlib/os/notify/backend_linux.c.v
This PR remove the meaningless [noinit] attribute of the os.notifier.  😄
=> os: remove the meaningless [noinit] attribute of the os.notifier

vlib/net/html/tag_test.v, vlib/v/checker/checker.v, vlib/v/checker/fn.v, vlib/v/checker/tests/generics_struct_init_err.out, vlib/v/checker/tests/option_type_call_err.out, vlib/v/checker/tests/or_block_check_err.out, vlib/v/checker/tests/or_block_check_err.vv, vlib/v/checker/tests/result_type_call_err.out
1. Fixed #19061 
2. Add test.
```v
fn callexpr_with_or_block_call() !string {
return error('')
}
fn main() {
_ = callexpr_with_or_block_call() or {}.replace('a', 'b')
_ = (callexpr_with_or_block_call() or {}).replace('a', 'b')
_ = callexpr_with_or_block_call() or { eprintln('error') }.replace('a', 'b')
_ = (callexpr_with_or_block_call() or { eprintln('error') }).replace('a', 'b')
}
```
output:
```
vlib/v/checker/tests/or_block_check_err.vv:6:36: error: assignment requires a non empty `or {}` block
4 | 
6 |     _ = callexpr_with_or_block_call() or {}.replace('a', 'b')
|                                       ~~~~~
7 |     _ = (callexpr_with_or_block_call() or {}).replace('a', 'b')
8 |
vlib/v/checker/tests/or_block_check_err.vv:7:37: error: assignment requires a non empty `or …
```
=> checker: fix missing or_block check for left expr of CallExpr(fix #19061)

vlib/v/scanner/scanner.v, vlib/v/tests/string_interpolation_with_inner_quotes_test.v
This PR fix string interpolation with nested string interpolation in inner quotes (fix #19081 partial).
- Fix string interpolation with nested string interpolation in inner quotes.
- Add test.
```v
fn f(x int, s string) string {
return 'label ${s}: ${x}'
}
// vfmt off
fn main() {
x := 'hi'
println('abc ${f(123, 'def')} xyz')
assert 'abc ${f(123, 'def')} xyz' == 'abc label def: 123 xyz'
println('abc ${f(123, "def")} xyz')
assert 'abc ${f(123, "def")} xyz' == 'abc label def: 123 xyz'
println("abc ${f(123, 'def')} xyz")
assert "abc ${f(123, 'def')} xyz" == 'abc label def: 123 xyz'
println("abc ${f(123, "def")} xyz")
assert "abc ${f(123, "def")} xyz" == 'abc label def: 123 xyz'
println("abc ${f(123, "$x $x")} xyz")
assert "abc ${f(123, "$x $x")} xyz" == 'abc label hi hi: 123 xyz'
println('abc …
```
=> scanner: fix string interpolation with nested string interpolation in inner quotes (fix #19081)

vlib/v/scanner/scanner.v, vlib/v/scanner/tests/empty_character_literal_err.out, vlib/v/scanner/tests/newline_character_literal_err.out, vlib/v/scanner/tests/newline_character_literal_err.vv
=> scanner: check invalid newline rune literal  (fix #19087)

vlib/v/scanner/scanner.v, vlib/v/tests/string_interpolation_with_inner_quotes_test.v
This PR fix string interpolation with nested string interpolation (fix #19081).
- Fix string interpolation with nested string interpolation.
- Add test.
```v
fn f(x int, s string) string {
return 'label ${s}: ${x}'
}
// vfmt off
fn main() {
x := 'hi'
println('abc ${f(123, 'def')} xyz')
assert 'abc ${f(123, 'def')} xyz' == 'abc label def: 123 xyz'
println('abc ${f(123, "def")} xyz')
assert 'abc ${f(123, "def")} xyz' == 'abc label def: 123 xyz'
println("abc ${f(123, 'def')} xyz")
assert "abc ${f(123, 'def')} xyz" == 'abc label def: 123 xyz'
println("abc ${f(123, "def")} xyz")
assert "abc ${f(123, "def")} xyz" == 'abc label def: 123 xyz'
println("abc ${f(123, "$x $x")} xyz")
assert "abc ${f(123, "$x $x")} xyz" == 'abc label hi hi: 123 xyz'
println('abc ${f(123, '$x $x')} xyz')
assert 'abc …
```
=> scanner: fix string interpolation with nested string interpolation (fix #19081)

vlib/v/parser/parse_type.v, vlib/v/tests/struct_field_default_fn_type_value_init_test.v
This PR fix struct field fn type with default value (fix #19099).
- Fix struct field fn type with default value.
- Add test.
```v
struct Flip {
name    string = 'NULL'
execute fn () ! = unsafe { nil }
}
fn (flip Flip) exec() ! {
if isnil(flip.execute) {
return
}
println('Executing ${flip.name}')
flip.execute()!
}
fn main() {
fl := Flip{
name: 'a function'
execute: fn () ! {
println('Hello, World!')
}
}
fl.exec()!
}
Executing a function
Hello, World!
```
=> parser: fix struct field fn type with default value (fix #19099)

vlib/v/gen/c/spawn_and_go.v, vlib/v/gen/c/testdata/spawn_call_fn_struct_field.out, vlib/v/gen/c/testdata/spawn_call_fn_struct_field.vv
1. Fix #18862 
2. Add test.
```v
struct Foo {
mut:
func1 fn (int) = unsafe { nil }
func2 fn (int) = do
}
fn do(a int) {
println('hello')
}
mut foo := Foo{}
foo.func1 = do
mut p := spawn foo.func1(1)
p.wait()
p = spawn foo.func2(1)
p.wait()
```
output:
```
hello
hello
```
=> cgen: fix spawn call fn struct field(fix #18862)

vlib/v/checker/fn.v, vlib/v/gen/c/fn.v, vlib/v/parser/parse_type.v, vlib/v/tests/return_aliases_of_fixed_array_test.v, vlib/v/tests/return_fixed_array_test.v
This PR fix fn return alias of fixed array.
- Don't change return type from alias type to fixed array type in parser chase.
- Fmt is correct.
- Change the related tests.
```v
type Mat = [2][2]int
fn main() {
a := Mat([[1, 2]!, [3, 4]!]!)
println(a.foo())
z := a.foo()
assert z == [[1, 2]!, [3, 4]!]!
}
fn (v Mat) foo() Mat {
return v
}
fn bar() Mat {
return Mat([[1, 2]!, [3, 4]!]!)
}
Mat([[1, 2], [3, 4]])
```
Fmt is correct.
=> parser, checker, cgen: fix fn return alias of fixed array

vlib/v/ast/table.v, vlib/v/gen/c/if.v, vlib/v/parser/parse_type.v, vlib/v/tests/generic_struct_init_with_reference_struct_type_test.v
This PR fix generic struct init (Stack[&Person]{}) (fix #19119).
- Fix generic struct init (Stack[&Person]{}).
- Add test.
```v
import datatypes { Stack }
mut:
name string
age  int
}
fn main() {
mut adam := &Person{'Adam', 21}
println(adam)
mut people := Stack[&Person]{}
people.push(adam)
assert people.len() == 1
mut top_person := people.pop()!
top_person.age++
println(adam)
assert people.len() == 0
}
&Person{
name: 'Adam'
age: 21
}
&Person{
name: 'Adam'
age: 22
}
```
=> ast, parser, cgen: fix generic struct init (Stack[&Person]{}) (fix #19119)

vlib/v/scanner/scanner.v, vlib/v/tests/string_interpolation_with_inner_quotes_test.v
This PR fix string interpolation with nested string interpolation in inner quotes 3.
- Fix string interpolation with nested string interpolation in inner quotes.
- Add test.
```v
fn f(x int, s string) string {
return 'label ${s}: ${x}'
}
// vfmt off
fn main() {
x := 'hi'
println('abc ${f(123, 'def')} xyz')
assert 'abc ${f(123, 'def')} xyz' == 'abc label def: 123 xyz'
println('abc ${f(123, "def")} xyz')
assert 'abc ${f(123, "def")} xyz' == 'abc label def: 123 xyz'
println("abc ${f(123, 'def')} xyz")
assert "abc ${f(123, 'def')} xyz" == 'abc label def: 123 xyz'
println("abc ${f(123, "def")} xyz")
assert "abc ${f(123, "def")} xyz" == 'abc label def: 123 xyz'
println("abc ${f(123, "$x $x")} xyz")
assert "abc ${f(123, "$x $x")} xyz" == 'abc label hi hi: 123 xyz'
println('abc ${f(123, '$x $x')} …
```
=> scanner: fix string interpolation with nested string interpolation in inner quotes 3

vlib/v/gen/c/fn.v, vlib/v/gen/c/testdata/alias_of_array_method_call.out, vlib/v/gen/c/testdata/alias_of_array_method_call.vv
1. Fix #19125 
2. Add tests.
```v
struct Element {}
type ElementStack = []&Element
fn (mut stack ElementStack) pop_front() ?&Element {
return if stack.len > 0 {
val := stack.first()
stack.delete(0)
val
} else {
none
}
}
fn main() {
mut stack := ElementStack([]&Element{})
stack << &Element{}
a := stack.pop_front()
println(a)
}
```
output:
```
&Option(Element{})
```
=> cgen: fix alias of array method call(fix #19125)

vlib/v/checker/fn.v, vlib/v/fmt/fmt.v, vlib/v/tests/modules/methods_struct_another_module/import_symbol_static_method_test.v
1. Fix #19127 
2. Add tests.
```v
module main
import amod { SomeStruct }
fn main() {
result := SomeStruct.new()
}
```
output:
```
amod.SomeStruct{}
```
=> checker, fmt: fix static methods not recognized when imported from a module(fix #19127)

vlib/toml/tests/encode_and_decode_test.v, vlib/toml/toml.v
PR adds direct encoding and decoding in toml.
Let me know about considerations and nitpicks to make this good as it should be.
=> toml: add generic de- and encoding of simple structs when they don't implement custom methods

vlib/vweb/vweb.v
`vweb.mime_types` is of type `pub const`. Added support for files with `.wasm` extension
=> vweb: add .wasm to mime_types

vlib/builtin/string.v, vlib/encoding/base32/base32.v, vlib/flag/flag.v, vlib/net/urllib/urllib.v, vlib/regex/regex_util.v, vlib/v/checker/assign.v, vlib/v/checker/tests/slice_clone_notice.out, vlib/v/checker/tests/slice_clone_notice.vv, vlib/v/gen/js/tests/array.v, vlib/v/tests/array_slice_assign_test.v, vlib/v/tests/array_slice_test.v
This PR fix assigning array slice (fix #19120).
- Fix assigning array slice.
- `mut a := arr[..i]` -> `mut a := arr[..i].clone()` if left var or right var is mut and not inside unsafe.
- Add test.
```v
fn main() {
xs := [1, 2, 3, 4, 5, 6, 7, 8]
mut s := xs[1..]
s.sort(a > b)
println(s)
assert s == [8, 7, 6, 5, 4, 3, 2]
println(xs)
assert xs == [1, 2, 3, 4, 5, 6, 7, 8]
}
tt1.v:4:13: notice: an implicit clone of the slice was done here
2 |     xs := [1, 2, 3, 4, 5, 6, 7, 8]
3 | 
4 |     mut s := xs[1..]
|                ~~~~~
5 | 
6 |     s.sort(a > b)
Details: tt1.v:4:13: details: To silence this notice, use either an explicit `a[..].clone()`, 
or use an explicit `unsafe{ a[..] }`, if you do not want a copy of the slice.
2 |     xs := [1, 2, 3, 4, 5, 6, 7, 8]
3 | …
```
=> checker: fix assigning array slice (fix #19120)

vlib/v/checker/fn.v
This PR fixed an inappropriate variable name.
```v
// If the left expr has an or_block, it needs to be checked for legal or_block statement.
return_type := c.expr(mut node.left)
c.check_expr_opt_call(node.left, return_type)
```
==>
```v
// If the left expr has an or_block, it needs to be checked for legal or_block statement.
left_type := c.expr(mut node.left)
c.check_expr_opt_call(node.left, left_type)
```
=> checker: fix an inappropriate variable name

vlib/v/checker/assign.v, vlib/v/checker/struct.v, vlib/v/checker/tests/slice_clone_in_struct_init_notice.out, vlib/v/checker/tests/slice_clone_in_struct_init_notice.vv
This PR fix assigning array slice in struct init (fix #19145).
- Fix assigning array slice in struct init.
- Add test.
```v
struct AA {
a []int
}
fn main() {
mut a := []int{len: 10}
_ := AA{
a: a[0..5]
}
_ := a[0..5]
}
tt1.v:9:7: notice: an implicit clone of the slice was done here
7 |
8 |     _ := AA{
9 |         a: a[0..5]
|             ~~~~~~
10 |     }
11 |     _ := a[0..5]
Details: tt1.v:9:7: details: To silence this notice, use either an explicit `a[..].clone()`,
or use an explicit `unsafe{ a[..] }`, if you do not want a copy of the slice.
7 |
8 |     _ := AA{
9 |         a: a[0..5]
|             ~~~~~~
10 |     }
11 |     _ := a[0..5]
```
=> checker: fix assigning array slice in struct init (fix #19145)

vlib/v/gen/wasm/gen.v, vlib/v/help/build/build-wasm.txt, vlib/v/pref/pref.v
This PR adds a new flag to the compiler that allows overriding the value used for the wasm stack_top. This fixes compatibility with some platforms such as [TIC-80](https://tic80.com/), as they have very specific memory layout requirements and by default V writes into reserved memory. If a compiler flag isn't the best way to do this please let me know, but I couldn't think of a better place to put it.
=> wasm: add -wasm-stack-top flag to compiler

vlib/v/checker/fn.v, vlib/v/checker/tests/enum_from_string_args_err.out, vlib/v/checker/tests/enum_from_string_args_err.vv
This PR check enum static from_string arguments errors (fix #19158).
- Check enum static from_string arguments errors.
- Add test.
```v
enum Color {
red
green
blue
}
fn main() {
Color.from_string()
Color.from_string('red', 'blue')
Color.from_string(22)
Color.from_string(22.22)
Color.from_string(true)
}
tt1.v:8:2: error: expected 1 argument, but got 0
6 |
8 |     Color.from_string()
|     ~~~~~~~~~~~~~~~~~~~
9 |     Color.from_string('red', 'blue')
10 |     Color.from_string(22)
tt1.v:9:2: error: expected 1 argument, but got 2
8 |     Color.from_string()
9 |     Color.from_string('red', 'blue')
|     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10 |     Color.from_string(22)
11 |     Color.from_string(22.22)
tt1.v:10:2: error: expected `string` …
```
=> checker: check enum static from_string arguments errors (fix #19158)

vlib/v/gen/c/fn.v, vlib/v/tests/enum_custom_static_from_string_test.v
This PR fix using custom enum static from_string() (fix #19165).
- Fix using custom enum static from_string().
- Add test.
```v
enum Color {
red
green
blue
}
fn Color.from_string(x string) Color {
return Color.red
}
fn main() {
ret := Color.from_string('abc')
println(ret)
assert ret == Color.red
}
red
```
=> cgen: fix using custom enum static from_string() (fix #19165)

vlib/v/checker/checker.v, vlib/v/tests/const_from_comptime_if_expr_test.v
This PR fix const from comptime if expr (fix #19169).
- Fix const from comptime if expr.
- Add test.
```v
import term
const (
color = $if windows {
term.bright_cyan('WINDOWS')
} $else {
term.bright_green('UNIX')
}
)
fn main() {
salutation := 'hello'
// works if you add `'' +` before 'color'
val := match salutation {
'hello' { color + ' some text' }
'goodbyte' { color + ' some other text' }
else { 'invalid' }
}
println(val)
assert true
}
WINDOWS some text
```
=> checker: fix const from comptime if expr (fix #19169)

vlib/v/checker/infix.v, vlib/v/checker/tests/infix_sumtype_in_array_err.out, vlib/v/checker/tests/infix_sumtype_in_array_err.vv
This PR check error for sumtype in array (fix #19170).
- Check error for sumtype in array.
- Add test.
```v
struct OtherType {
foo string
bar string
}
type RuneAlias = rune
type RuneAliasOrOtherType = OtherType | RuneAlias
const whitespace = [rune(0x0009), 0x000a, 0x000c, 0x000d, 0x0020]
fn main() {
mut x := RuneAliasOrOtherType(RuneAlias(rune(`!`)))
match x {
RuneAlias {
if x in whitespace {
// doing `if x as RuneAlias in whitepsace` here
// works but it should be doing that automatically
// since I'm inside the RuneAlias match condition.
}
}
else {
// do something else
}
}
}
tt1.v:15:7: error: left operand to `in` does not match the array element type: expected `rune`, not `RuneAliasOrOtherType`
13 |     match x {
14 |         RuneAlias {
15 | …
```
=> checker: check error for sumtype in array (fix #19170)

doc/docs.md
Added "thread" to the list of keywords in the appendix. Added documentation for the undocumented behavior mentioned in #18207 (interface dynamic cast converting value variable to pointer) and #18196 (files in module share functions, structs, interfaces, types, etc.).
=> docs: add undocumented behavior

vlib/v/gen/c/if.v, vlib/v/tests/match_with_comptime_if_expr_in_branch_test.v
This PR fix match with comptime if expr in branch (fix #19166).
- Fix match with comptime if expr in branch.
- Add test.
```v
fn main() {
x := match 'green' {
'red' {
'color is red'
}
'green' {
$if windows {
'color is green windows'
} $else {
'color is green unix'
}
}
else {
'nothing to say'
}
}
println(x)
}
color is green windows
```
=> cgen: fix match with comptime if expr in branch (fix #19166)

vlib/v/ast/ast.v, vlib/v/fmt/fmt.v, vlib/v/fmt/tests/return_with_comments_expected.vv, vlib/v/fmt/tests/return_with_comments_input.vv, vlib/v/parser/expr.v
This PR fix formatting return with comments in parentheses (fix #19173).
- Fix formatting return with comments in parentheses.
- Add test.
```v
fn foo1() int {
return (0/* some comment */)
}
fn foo2() int {
return (/* some comment */0)
}
fn foo3() int {
return (/* some comment1 */ 0/* some comment2 */)
}
fn foo4() int {
return (/* some comment1 */ /* some comment2 */0)
}
fn foo5() int {
return (/* some comment1 */ /* some comment2 */0/* some comment3 */ /* some comment4 */)
}
fn main() {
}
```
fmt to:
```v
fn foo1() int {
return (0 /* some comment */ )
}
fn foo2() int {
return ( /* some comment */ 0)
}
fn foo3() int {
return ( /* some comment1 */ 0 /* some comment2 */ )
}
fn foo4() int {
return ( /* some comment1 */ /* some comment2 */ 0)
}
fn foo5() int {
return ( /* some comment1 */ /* …
```
=> ast, parser, fmt: fix formatting return with comments in parentheses (fix #19173)

vlib/v/gen/c/cgen.v, vlib/v/tests/generics_struct_with_option_fn_test.v
This PR fix generic struct with option fn field (fix #19202).
- Fix generic struct with option fn field.
- Add test.
```v
struct Cmp[K] {
cmp ?fn (K, K) bool
}
fn (c Cmp[K]) compare(a K, b K) bool {
cmp := c.cmp or { return a < b }
return cmp(a, b)
}
fn main() {
c := Cmp[int]{}
print(c.compare(1, 2))
assert c.compare(1, 2)
}
true
```
=> cgen: fix generic struct with option fn field (fix #19202)

vlib/v/gen/c/array.v, vlib/v/tests/array_sort_with_fn_call_test.v
This PR fix array sort with fn call parameter (fix #19220).
- Fix array sort with fn call parameter.
- Add test.
```v
struct Info {
mut:
fields []string
}
fn main() {
mut info := Info{
fields: ['aaa(', 'b(']
}
info.fields.sort(a.before('(').len < b.before('(').len)
println(info.fields)
assert info.fields == ['b(', 'aaa(']
}
['b(', 'aaa(']
```
=> cgen: fix array sort with fn call parameter (fix #19220)

vlib/builtin/builtin.c.v
Do less allocations for println/eprintln by default.
The old mode where println and eprintln form the final string in memory is still available with `-d bultin_writeln_should_write_at_once` .
Also add the ability to use the vinix/freestanding output mode (i.e. C.write, instead of C.fwrite) directly with `-d bultin_write_buf_to_fd_should_use_c_write` .
=> builtin: add support for `-d bultin_writeln_should_write_at_once` and `-d bultin_write_buf_to_fd_should_use_c_write`

examples/log.v, vlib/log/README.md, vlib/log/common.v, vlib/log/default.c.v, vlib/log/default.v, vlib/log/default_test.v, vlib/log/log.v, vlib/log/log_test.v, vlib/log/logger_interface.v, vlib/log/safe_log.v, vlib/sync/common_mutex.v, vlib/sync/sync.c.v, vlib/sync/sync_darwin.c.v, vlib/sync/sync_default.c.v, vlib/sync/sync_windows.c.v, vlib/v/tests/str_gen_test.v
- log: reduce usage complexity in the most common cases, by providing a log.Logger global instance, and utility functions to work with it
- log: add log.ThreadSafeLog, use it for the default log.Logger
=> log: improve the most common use case

vlib/v/fmt/tests/structs_input.vv, vlib/v/parser/struct.v, vlib/v/parser/tests/struct_embed_wrong_pos_in_pub_err.out, vlib/v/parser/tests/struct_embed_wrong_pos_in_pub_err.vv
This PR check struct embed with wrong position (fix #19241).
- Check struct embed with wrong position.
- Add test.
```v
struct Log {}
struct Xyz {}
pub struct ThreadSafeLog {
pub:
Log
pub mut:
mu Xyz
}
fn main() {}
tt1.v:6:5: error: struct embedding must be declared at the beginning of the struct body
4 | pub struct ThreadSafeLog {
5 | pub:
6 |     Log
|     ~~~
7 | pub mut:
8 |     mu Xyz
PS D:\Test\v\tt1> v fmt -w tt1.v   
tt1.v:6:5: error: struct embedding must be declared at the beginning of the struct body
4 | pub struct ThreadSafeLog {
5 | pub:
6 |     Log
|     ~~~
7 | pub mut:
8 |     mu Xyz
Internal vfmt error while formatting file: tt1.v.
Encountered a total of: 1 errors.
```
=> parser: check struct embed with wrong position (fix #19241)

vlib/v/gen/c/array.v, vlib/v/tests/mixed_fixed_array_and_array_init_test.v
This PR fix mixed fixed array and array initializing (fix #19244).
- Fix mixed fixed array and array initializing.
- Add test.
```v
fn main(){
a := [0.312, 12.0213]!
b := [0.23, 2131.213]!
ab := [a, b]
println(ab)
}
[[0.312, 12.0213], [0.23, 2131.213]]
```
```v
fn main(){
a := [0.312, 12.0213]!
b := [0.23, 2131.213]!
mut ab := [a]
ab << b
println(ab)
}
[[0.312, 12.0213], [0.23, 2131.213]]
```
```v
fn main(){
a := [0.312, 12.0213]!
b := [0.23, 2131.213]!
mut ab := [a,b]!
println(ab)
}
[[0.312, 12.0213], [0.23, 2131.213]]
```
=> cgen: fix mixed fixed array and array initializing (fix #19244)

doc/docs.md
`a[1..4]` should have `unsafe { a[1..4] }` or `a[1..4].clone()`
=> docs: fix #19249

vlib/os/README.md
Updates the examples in the os modules readme. 
The change is mainly concerned with improving support when viewing it in narrower windows. 
E.g. on https://modules.vlang.io/os.html up until a window width of about 1300-1400px, it's not visible that the example has a right part of how to do it correctly at all.
Hopefully, also improves general readability of the examples.
GH rendered preview:
current: https://github.com/vlang/v/blob/master/vlib/os/README.md
suggestion: https://github.com/ttytm/v/blob/os/update-readme/vlib/os/README.md
=> os: update TOCTOU example in readme

vlib/v/gen/c/array.v, vlib/v/gen/c/struct.v
This PR cleanup in struct_init_field().
=> cgen: cleanup in struct_init_field()

bench/vectors/vectors.cs, bench/vectors/vectors.v, vlib/math/exp.c.v, vlib/math/log.c.v, vlib/math/log.v, vlib/math/pow.c.v, vlib/math/pow.v, vlib/math/sin.c.v, vlib/math/sqrt.c.v, vlib/math/square.v, vlib/math/square_test.v, vlib/math/unsafe.v, vlib/math/vec/vec2_test.v
Optimize the `math` module a bit, for the common case of using the default C backend.
See https://discord.com/channels/592103645835821068/592842126304477184/1148219591957417994 for the motivation.
This PR also speeds up `examples/path_tracing.v`, on my machine, by ~ 2x with `-cc gcc -prod`, without changes to the example.
=> math: add more C. fn overrides for the default C backend (speed up examples/path_tracing.v)

cmd/tools/vdoc/html.v
current tag escape with regex: `536.382ms`
tag escape new: `79.732ms` (`50.160ms` when using constants)
There are not too many `replace_each` occurrences in the code base. If they don't use consts, should we replace the array arguments with constants for all functions that are called often internally and for potentially often called pub fns?
=> vdoc: improve html tag escape

vlib/v/parser/parse_type.v, vlib/v/tests/fixed_array_const_size_test.v, vlib/v/transformer/transformer.v
This PR fix transformer.infix_expr() and cleanup parse_types.v (related #19269).
- Fix transformer.infix_expr() and cleanup parse_types.v.
- Add test.
```v
const (
rows = 2
cols = 3
)
struct Matrix {
data [rows * cols + 1]int
}
fn main() {
mat := Matrix{}
println(mat)
}
Matrix{
data: [0, 0, 0, 0, 0, 0, 0]
}
```
=> parser, transformer: fix transformer.infix_expr() and cleanup parse_types.v (related #19269)

vlib/v/gen/c/auto_str_methods.v, vlib/v/slow_tests/inout/printing_struct_with_thread_field.out, vlib/v/slow_tests/inout/printing_struct_with_thread_field.vv
This PR fix printing struct with thread field (fix #19282).
- Fix printing struct with thread field.
- Add test.
```v
// Video is the object containing all the information needed for
// conversion to ascii.
struct Video {
pub:
// path may be URL or path on local file system.
path         string
tmp_dir      string
frame_count  int
frame_format FrameFormat
pub mut:
// TODO: once V fixes bug #19281 replace the type here
// with `thread !`. And the return type on the corresponding
// function that is spawned.
extract_frames_thread thread string
}
enum FrameFormat {
bmp
jpg
}
fn (video Video) extract_frames() string {
// try to extract frames os.execute()
// if os.execute() returns with an exit
// code other than 0, return an error.
if true {
return 'Failed to extract frames: os.execute() cmd …
```
=> cgen: fix printing struct with thread field (fix #19282)

vlib/v/tests/fixed_array_const_size_test.v
This PR supplement test cases in fixed_array_const_size_test.v (related #19269).
```v
const (
rows = 2
cols = 3
)
struct Matrix1 {
data [rows * cols]int
}
struct Matrix2 {
data [rows * cols + 4]int
}
struct Matrix3 {
data [rows * 4 - 2 * cols]int
}
struct Matrix4 {
data [5 * rows - cols * 2]int
}
struct Matrix5 {
data [5 * rows / 2]int
}
struct Matrix6 {
data [5 * rows / 2 + 1]int
}
fn main() {
mat1 := Matrix1{}
println(mat1)
assert mat1.data.len == 6
mat2 := Matrix2{}
println(mat2)
assert mat2.data.len == 10
mat3 := Matrix3{}
println(mat3)
assert mat3.data.len == 2
mat4 := Matrix4{}
println(mat4)
assert mat4.data.len == 4
mat5 := Matrix5{}
println(mat5)
assert mat5.data.len == 5
mat6 := Matrix6{}
println(mat6)
assert mat6.data.len == 6
}
Matrix1{
data: [0, 0, 0, …
```
=> test: supplement test cases in fixed_array_const_size_test.v (related #19269)

vlib/v/gen/c/cgen.v, vlib/v/slow_tests/inout/printing_struct_with_thread_field.out, vlib/v/slow_tests/inout/printing_struct_with_thread_field.vv
This PR fix printing struct with thread field (fix #19283).
- Fix printing struct with thread field.
- Add test.
```v
// Video is the object containing all the information needed for
// conversion to ascii.
struct Video {
pub:
// path may be URL or path on local file system.
path         string
tmp_dir      string
frame_count  int
frame_format FrameFormat
pub mut:
// TODO: once V fixes bug #19281 replace the type here
// with `thread !`. And the return type on the corresponding
// function that is spawned.
extract_frames_thread thread string
frames                [][]u8
framerate             f64 = 24.0
}
enum FrameFormat {
bmp
jpg
}
fn (video Video) extract_frames() string {
// try to extract frames os.execute()
// if os.execute() returns with an exit
// code other than 0, return an …
```
=> cgen: fix printing struct with thread field (fix #19283)

vlib/v/checker/checker.v, vlib/v/checker/tests/enum_field_value_duplicate_c.out, vlib/v/checker/tests/enum_field_value_duplicate_c.vv
This PR check enum fields with duplicate value (fix #19309).
- Check enum fields with duplicate value.
- Add test.
```v
pub enum HardwareAccelerationDevice as i64 {
@none = 0
cpu = (1 << 0)
gpu = (1 << 1)
accelerator = (1 << 2)
default = (1 << 0)
all = 0xFFFFFFFF
}
fn main() {
device := HardwareAccelerationDevice.@none
println(device)
}
tt1.v:6:12: error: enum value `1` already exists
4 |     gpu = (1 << 1)
5 |     accelerator = (1 << 2)
6 |     default = (1 << 0)
|               ~~~~~~~~
7 |     all = 0xFFFFFFFF
8 | }
```
=> checker: check enum fields with duplicate value (fix #19309)

thirdparty/vschannel/vschannel.c, thirdparty/vschannel/vschannel.h, vlib/builtin/cfns.c.v, vlib/net/http/backend_windows.c.v
net.http:fix post error with https on windows
the post data is treated as a string,so data will be truncated when post binary data that contains \0
=> net.http:fix post error with https on windows

vlib/v/ast/ast.v, vlib/v/fmt/fmt.v, vlib/v/fmt/tests/type_decl_with_anon_struct_keep.vv
This PR fix formatting type decl with anon struct (fix #19342).
- Fix formatting type decl with anon struct.
- Add test.
vlib\v\fmt\tests\type_decl_with_anon_struct_keep.vv
```v
pub type Unit1 = struct {}
pub type Unit2 = struct {
name string
age  int
}
pub const unit1 = Unit1{}
pub const unit2 = Unit2{'bob', 22}
fn main() {
println(unit1)
println(unit2)
}
```
=> ast, fmt: fix formatting type decl with anon struct (fix #19342)

vlib/v/fmt/fmt.v, vlib/v/fmt/tests/type_decl_with_anon_struct_keep.vv
This PR fix formatting type decl with anon struct 2 (related #19356).
- Fix formatting type decl with anon struct 2.
- Change test.
vlib\v\fmt\tests\type_decl_with_anon_struct_keep.vv
```v
pub type Unit1 = struct {}
pub type Unit2 = struct {
name string
age  int
}
pub const unit1 = Unit1{}
pub const unit2 = Unit2{'bob', 22}
fn main() {
println(unit1)
println(unit2)
}
```
=> ast, fmt: fix formatting type decl with anon struct 2 (related #19356)

vlib/v/gen/c/cgen.v, vlib/v/tests/thread_array_test.v
1. Fix #19365 
2. Add tests.
```v
fn main() {
mut threads := []thread{len: 1}
threads[0] = spawn fn () {
a := 1
dump(a)
assert true
}()
threads.wait()
}
```
output:
```
[a.v:6] a: 1
```
=> cgen: fix assign the spawn or go expr to the []thread(fix #19365)

vlib/v/checker/checker.v, vlib/v/checker/fn.v, vlib/v/checker/str.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/str_intp.v, vlib/v/tests/cast_to_empty_interface_test.v, vlib/v/tests/empty_interface_test.v, vlib/v/tests/print_smartcast_interface_variable_test.v
This PR fix printing smartcast interface variable (fix #18886).
- Fix printing smartcast interface variable.
- Add test.
```v
fn do(v Any) string {
match v {
int {
println('> integer answer: ${2 * v}')
return '${2 * v}'
}
string {
println('> string answer: ${v}, len: ${v.len}')
return '${v}'
}
else {
return ''
}
}
}
fn main() {
s1 := do(123)
assert s1 == '246'
s2 := do('abc')
assert s2 == 'abc'
}
> integer answer: 246
> string answer: abc, len: 3
```
=> checker, cgen: fix printing smartcast interface variable (fix #18886)

vlib/v/fmt/struct.v
This PR simplify formatting struct field comments.
- Remove inline comments between field name and field type.
=> fmt: simplify formatting struct field comments

vlib/v/gen/c/cgen.v, vlib/v/tests/interface_with_multi_nested_embed_3_test.v
This PR fix interface with multiple nested embedded fields (fix #19207).
- Fix interface with multiple nested embedded fields.
- Add test.
```v
interface NodeInterface {
mut:
node_type NodeType
node_name string
}
enum NodeType {
@none
}
struct Node {
mut:
// removing this field works makes `InterfaceNode(x).node_name.len` below work as expected
node_type NodeType
node_name string
}
struct Element {
Node
}
struct HTMLElement {
Element
}
fn main() {
x := &HTMLElement{}
struct_name_len := x.node_name.len
interface_name_len := NodeInterface(x).node_name.len
println('struct: ${struct_name_len}')
assert struct_name_len == 0
println('interface: ${interface_name_len}')
assert interface_name_len == 0
}
struct: 0
interface: 0
```
=> cgen: fix interface with multiple nested embedded fields (fix #19207)

vlib/v/gen/c/fn.v, vlib/v/tests/chan_interface_test.v
This PR fix channel of interface (fix #19382).
- Fix channel of interface.
- Add test.
```v
interface TestInterface {
a int
}
struct TestStruct {
a int
}
fn main() {
c := chan TestInterface{cap: 1}
c.try_push(TestInterface(TestStruct{ a: 1 }))
m := <-c
println(m)
assert m.a == 1
}
TestInterface(TestStruct{
a: 1
})
```
=> cgen: fix channel of interface (fix #19382)

vlib/orm/orm.v
Provides sql appropriate quotes around the table name and field name when utilizing `[references]`.
Should have been done initially
=> orm: quote table and field name in `[references]`

vlib/v/parser/containers.v, vlib/v/tests/fixed_array_of_option_test.v
This PR fix fixed array of option values (fix #19385).
- Fix fixed array of option values.
- Add test.
```v
module main
fn main() {
mut a := [3]?int{init: ?int(1)}
a[0] = none
a[1] = 2
println(a)
assert '${a}' == '[Option(none), Option(2), Option(1)]'
}
[Option(none), Option(2), Option(1)]
```
=> parser: fix fixed array of option values (fix #19385)

vlib/builtin/sorted_lambda_expr_test.v, vlib/v/ast/ast.v, vlib/v/ast/str.v, vlib/v/checker/checker.v, vlib/v/checker/fn.v, vlib/v/checker/lambda_expr.v, vlib/v/eval/expr.v, vlib/v/fmt/fmt.v, vlib/v/gen/c/array.v, vlib/v/gen/c/cgen.v, vlib/v/gen/golang/golang.v, vlib/v/gen/js/js.v, vlib/v/markused/walker.v, vlib/v/parser/expr.v, vlib/v/parser/fn.v, vlib/v/parser/parser.v, vlib/v/tests/lambda_expr_test.v
- all: support short lambda expressions like `a.sorted(|x,y| x > y)`, in all callsites that accept a fn callback
- ci: fix `v build-tools`
- fixes for vlib/v/parser/tests/anon_sum_type_multi_return_err.vv
=> all: support short lambda expressions like a.sorted(|x,y| x > y), in all callsites that accept a fn callback

vlib/v/builder/compile.v, vlib/v/tests/projects_that_should_compile_test.v, vlib/v/tests/testdata/modules_in_src/src/main.v, vlib/v/tests/testdata/modules_in_src/src/modules/somemodule/somemodule.v, vlib/v/tests/testdata/modules_in_src/v.mod
Fixed a problem where modules in src were not recognized.
=> builder: fix compiling code, importing a module located in `src/modules`

vlib/v/gen/c/array.v, vlib/v/tests/fixed_array_of_option_test.v
This PR fix fixed array of option type default (related #19392).
- Fix fixed array of option type default.
- Add test.
```v
fn main() {
mut a1 := [3]?int{init: ?int(1)}
a1[0] = none
a1[1] = 2
println(a1)
assert '${a1}' == '[Option(none), Option(2), Option(1)]'
mut a2 := [3]?int{}
a2[0] = 1
println(a2)
assert '${a2}' == '[Option(1), Option(none), Option(none)]'
}
[Option(none), Option(2), Option(1)]
[Option(1), Option(none), Option(none)]
```
=> cgen: fix fixed array of option type default (related #19392)

vlib/v/checker/infix.v, vlib/v/tests/generic_comparison_for_conditional_assign_test.v
This PR fix generic comparison for conditional assignment (fix #19398).
- Fix generic comparison for conditional assignment.
- Add test.
```v
fn clip[N](x []N, min N, max N) []N {
mut result := []N{cap: x.len}
for value in x {
result << if value < min {
min
} else if value > max {
max
} else {
value
}
}
return result
}
fn main() {
a := [1, 2, 3, 4, 5]
dump(a)
b := clip(a, 2, 4)
dump(b)
assert b == [2, 2, 3, 4, 4]
}
[.\\tt1.v:17] a: [1, 2, 3, 4, 5]
[.\\tt1.v:19] b: [2, 2, 3, 4, 4]
```
=> checker: fix generic comparison for conditional assignment (fix #19398)

vlib/v/gen/c/array.v, vlib/v/tests/fixed_array_of_option_test.v
This PR fix fixed array with index variable (related #19397).
- Fix fixed array with index variable.
- Add test.
```v
fn main() {
a1 := [3]?int{init: ?int(index * 2)}
println(a1)
assert '${a1}' == '[Option(0), Option(2), Option(4)]'
}
[Option(0), Option(2), Option(4)]
```
=> cgen: fix fixed array with index variable (related #19397)

vlib/toml/tests/encode_and_decode_test.v, vlib/toml/toml.v
As outlined in issue #19300 the default *toml* encoder caused compile time errors when encoding more complex structs. 
#19338 attempted to solve this issue by adding additional logic that covers the edge cases mentioned within the issue. However, other edge cases exist that bypass the fix and lead to compile time errors again. Examples are defined within the new test cases in this PR and include:
```v
struct Example3 {
arr_arr [][]Problem
}
struct Example4 {
mp map[string]Problem
}
```
This PR extends the `encode_struct` function of the *toml* module by adding handling of currently missing types (e.g. `$map`, which fixes `Example4` from above) and by applying encoding recursively (fixes `Example3` from above). This should catch quite some more edge cases, although I'm not sure whether it …
=> toml: Fix toml encoding of complex types

vlib/v/parser/assign.v, vlib/v/parser/containers.v
This PR fix assigning with in another module sumtypes 2.
- #19414 couldn't resolve assign_stmt(), and this PR can work.
=> parser: fix assigning with in another module sumtypes 2 (related #19414)

vlib/v/gen/c/struct.v, vlib/v/tests/struct_field_option_type_with_default_value_init_test.v
This PR fix struct field option type with default value init (fix #19418).
- Fix struct field option type with default value init.
- Add test.
```v
type SomeType = SomeStruct | string
struct SomeStruct {}
struct AnotherStruct {
field ?SomeType = 'default_string'
}
fn main() {
s := AnotherStruct{}
println(s.field)
assert '${s.field}' == "Option(SomeType('default_string'))"
}
Option(SomeType('default_string'))
```
=> cgen: fix struct field option type with default value init (fix #19418)

vlib/v/gen/c/assign.v
This PR cleanup in assign_stmt() (related #19415).
=> cgen: cleanup in assign_stmt() (related #19415)

vlib/v/checker/containers.v, vlib/v/gen/c/array.v, vlib/v/tests/fixed_array_of_option_test.v
This PR fix fixed array of option with default value (related #19405).
- Fix fixed array of option with default value.
- Add test.
```v
fn main() {
mut a1 := [3]?int{init: ?int(1)}
a1[0] = none
a1[1] = 2
println(a1)
assert '${a1}' == '[Option(none), Option(2), Option(1)]'
mut a11 := [3]?int{init: 1}
a11[0] = none
a11[1] = 2
println(a11)
assert '${a11}' == '[Option(none), Option(2), Option(1)]'
mut a2 := [3]?int{}
a2[0] = 1
println(a2)
assert '${a2}' == '[Option(1), Option(none), Option(none)]'
a3 := [3]?int{init: ?int(index * 2)}
println(a3)
assert '${a3}' == '[Option(0), Option(2), Option(4)]'
a33 := [3]?int{init: index * 2}
println(a33)
assert '${a33}' == '[Option(0), Option(2), Option(4)]'
}
[Option(none), Option(2), Option(1)]
[Option(none), Option(2), …
```
=> checker, cgen: fix fixed array of option with default value (related #19405)

vlib/v/gen/c/array.v
This PR cleanup in array.v (related #19422).
=> cgen: cleanup in array.v (related #19422)

vlib/v/gen/c/comptime.v
This PR cleanup in comptime_if_conds().
=> cgen: cleanup in comptime_if_conds()

vlib/v/gen/c/cgen.v, vlib/v/tests/interface_with_option_field_test.v
This PR fix interface with option field (fix #19419).
- Fix interface with option field.
- Add test.
```v
import time
interface InterfaceObject {
mut:
duration ?time.Duration
update()
}
struct Object {
mut:
duration ?time.Duration
}
fn (mut obj Object) update() {
duration := obj.duration or { time.second }
println(duration)
}
struct FooObject {
Object
}
fn (mut obj FooObject) update() {
duration := obj.duration or { time.millisecond * 500 }
println(duration)
}
fn main() {
mut object := InterfaceObject(FooObject{})
println(object)
assert '${object.duration}' == 'Option(none)'
}
InterfaceObject(FooObject{
Object: Object{
duration: Option(none)
}
})
```
=> cgen: fix interface with option field (fix #19419)

vlib/v/checker/lambda_expr.v, vlib/v/parser/expr.v, vlib/v/tests/lambda_as_struct_field_value_test.v
This fixes #19428 as well as allowing lambdas anywhere an anonymous function is expected.
=> parser, checker: allow lambdas anywhere anonymous functions are expected

vlib/v/builder/compile.v, vlib/v/tests/projects_that_should_compile_test.v, vlib/v/tests/testdata/modules_in_src/modules/somemoduletwo/somemoduletwo.v, vlib/v/tests/testdata/modules_in_src/src/main.v
Fixed problem with 'modules' not being recognized when `src/modules` and `modules` exist
=> Builder: fixed compile code when importing modules in both `src/modules` and `modules`.

vlib/v/gen/c/cheaders.v
I'm working on getting the plan 9 compilation working on ape/psh environment, and to do that it probably needs to be as close to normal ANSI C as possible, so I am changing the C headers to be more linux-ey.
This may change in the future, but I'm eliminating variables.
=> Revert libc.h include, exits(), void main

vlib/toml/tests/encode_and_decode_test.v, vlib/toml/toml.v
Adds simple decoding of toml objects into map[string] types (as struct members). The code is a little long, as I tried to use the new lambda syntax but it didn't seem to support multiple return values and I wasn't in the mood to go recursively bug fixing, so I just left a comment for when that's fixed.
=> toml: Add decoding for map[string]

vlib/builtin/array.v, vlib/builtin/string.v, vlib/v/gen/c/index.v, vlib/v/slow_tests/inout/printing_slice_of_fn_call_string.out, vlib/v/slow_tests/inout/printing_slice_of_fn_call_string.vv
This PR fix printing slice of fn call string (fix #19435).
- Fix printing slice of fn call string.
- Add test.
```v
struct Wrapper {
element string
}
fn (instance Wrapper) get() string {
println("Get called")
return instance.element
}
fn main() {
wrapper := Wrapper{
element: "Hello"
}
println(wrapper.get()[1..])
}
Get called
ello
```
=> builtin, cgen: fix printing slice of fn call string (fix #19435)

vlib/builtin/array.v, vlib/builtin/string.v, vlib/v/markused/markused.v
This PR cleanup in string.v and array.v.
- Remove unused internal fn `string.substr2(start int, end int, end_max bool)`.
- Remove unused internal fn `array.slice2(start int, end int, end_max bool)`.
=> builtin: cleanup in string.v and array.v

vlib/v/gen/c/index.v, vlib/v/tests/array_of_fns_index_call_with_direct_array_access_test.v
This PR fix array of fns index call with direct_array_access mode (fix #19458).
- Fix array of fns index call with direct_array_access mode.
- Add test.
```v
struct Bar {
f []fn (int) int
}
fn func(n int) int {
return n
}
[direct_array_access]
fn (b Bar) foo() int {
return b.f[0](22)
}
fn main() {
bar := Bar{[func]}
ret := bar.foo()
println(ret)
}
22
```
=> cgen: fix array of fns index call with direct_array_access mode (fix #19458)

vlib/net/html/tag.v
It's public field of Tag struct, but type itself is private
=> fix: make CloseTagType public

vlib/os/os.c.v, vlib/os/process_nix.c.v, vlib/v/builder/compile.v
=> os, v.builder: show more details, when a program ran by `v run file.v`, exits by a signal (fix #19412)

vlib/v/checker/containers.v, vlib/v/checker/tests/fixed_array_init_with_default.out, vlib/v/checker/tests/fixed_array_init_with_default.vv, vlib/v/checker/tests/option_fn_err.out
This PR check fixed array init with default expression (fix #19467).
- Check fixed array init with default expression.
- Add test.
```v
struct Foo {
stack_arr [2]string
}
fn main() {
_ := Foo{[2]string{init: ['a', 'b']}}
_ := Foo{[2]string{init: 2.2}}
_ := Foo{[2]string{init: 22}}
_ := Foo{[2]string{init: true}}
}
tt1.v:6:27: error: expected `string`, not `[]string`
4 | 
6 |     _ := Foo{[2]string{init: ['a', 'b']}}
|                              ~~~~~~~~~~
7 |     _ := Foo{[2]string{init: 2.2}}
8 |     _ := Foo{[2]string{init: 22}}
tt1.v:7:27: error: expected `string`, not `float literal`
6 |     _ := Foo{[2]string{init: ['a', 'b']}}
7 |     _ := Foo{[2]string{init: 2.2}}
|                              ~~~
8 |     _ := …
```
=> checker: check fixed array init with default expression (fix #19467)

vlib/v/gen/c/auto_str_methods.v, vlib/v/slow_tests/inout/dump_fixed_array_of_option.out, vlib/v/slow_tests/inout/dump_fixed_array_of_option.vv
This PR fix printing fixed array of options (fix #19469).
- Fix printing fixed array of options.
- Add test.
```v
fn main() {
a1 := [?string('foo'), ?string(none)]!
dump(a1)
a2 := [?int(22), ?int(none)]!
dump(a2)
a3 := [?f64(22.2), ?f64(none)]!
dump(a3)
a4 := [?bool(true), ?bool(none)]!
dump(a4)
}
[.\\tt1.v:3] a1: [Option('foo'), Option(none)]
[.\\tt1.v:6] a2: [Option(22), Option(none)]
[.\\tt1.v:9] a3: [Option(22.2), Option(none)]
[.\\tt1.v:12] a4: [Option(true), Option(none)]
```
=> cgen: fix printing fixed array of options (fix #19469)

vlib/v/gen/c/struct.v, vlib/v/tests/array_elements_with_option_test.v, vlib/v/tests/struct_field_fixed_array_init_test.v
This PR fix struct field of fixed array init (fix #19483).
- Fix struct field of fixed array init.
- Add test.
```v 
struct Foo {
mut:
bar [2]string
}
fn main() {
foo := Foo{}
println(foo.bar[0])
assert foo.bar[0] == ''
}
```
=> cgen: fix struct field of fixed array init (fix #19483)

doc/docs.md, vlib/v/ast/str.v, vlib/v/checker/checker.v, vlib/v/parser/comptime.v, vlib/v/tests/comptime_at_test.v, vlib/v/token/token.v
```v
// abc
// def
fn abc() {
eprintln(@LOCATION)
}
}
fn MyStruct.new() MyStruct {
eprintln(@LOCATION)
return MyStruct{}
}
fn (s MyStruct) mymethod() {
eprintln(@LOCATION)
}
eprintln(@LOCATION)
abc()
MyStruct.new().mymethod()
eprintln(@LOCATION)
```
produces:
```
/Users/delyanangelov/code/misc/2023_10_01__19/loc.v:20, main.main
/Users/delyanangelov/code/misc/2023_10_01__19/loc.v:5, main.abc
/Users/delyanangelov/code/misc/2023_10_01__19/loc.v:12, main.MyStruct.new (static)
/Users/delyanangelov/code/misc/2023_10_01__19/loc.v:17, main.MyStruct{}.mymethod
/Users/delyanangelov/code/misc/2023_10_01__19/loc.v:23, main.main
```
=> all: add support for `@LOCATION`, for more convenient logging/tracing, without needing to combine `@FILE`, `@LINE` at runtime

vlib/v/gen/c/cgen.v, vlib/v/tests/struct_init_with_multi_option_fn_type_test.v
This PR fix struct init with multi option fn type (fix #19478).
- Fix struct init with multi option fn type.
- Add test.
```v
// CycleMenuItem is a menu item that can be cycled through by pressing a button.
pub struct CycleMenuItem {
mut:
label  string
values []string
on     CycleMenuItemEvents
}
// CycleMenuItemEvents is a set of events that can be invoked by a
// `CycleMenuItem`.
[params]
pub struct CycleMenuItemEvents {
__global:
click ?fn (string) bool
cycle ?fn (string) bool
}
// CycleMenuItem.new creates a new `CycleMenuItem` with the given label, values,
// and function to invoke when the item is selected.
[inline]
pub fn CycleMenuItem.new(label string, values []string, events CycleMenuItemEvents) CycleMenuItem {
return CycleMenuItem{
label: label
values: values
on: events
}
}
fn …
```
=> cgen: fix struct init with multi option fn type (fix #19478)

vlib/v/parser/parser.v, vlib/v/tests/assign_static_method_to_anon_fn_test.v
This PR fix assigning static method to anon fn (fix #19484).
- Fix assigning static method to anon fn.
- Add test.
```v
struct Foo {
}
fn Foo.bar() string {
println('bar')
return 'bar'
}
fn main() {
anon_fn := Foo.bar
ret := anon_fn()
assert ret == 'bar'
}
bar
```
=> parser: fix assigning static method to anon fn (fix #19484)

vlib/v/fmt/fmt.v, vlib/v/parser/parser.v, vlib/v/tests/assign_static_method_to_anon_fn_test.v
This PR fix formatting assign static method to anon fn.
- Fix formatting assign static method to anon fn.
- Remove `// vfmt off/on` in the test.
=> parser, fmt: fix formatting assign static method to anon fn

vlib/math/math.v
=> math: fix documentation for math.radians, math.degrees and math.aprox_cos

vlib/v/gen/c/struct.v, vlib/v/tests/cast_to_interface_with_struct_field_default_test.v
This PR fix casting to interface with struct field default expr (fix #19497).
- Fix casting to interface with struct field default expr.
- Add test.
```v
import time
interface Cursor {
mut:
blink time.StopWatch
}
struct LineCursor {
__global:
blink time.StopWatch = time.new_stopwatch(auto_start: true)
}
fn main() {
c := Cursor(LineCursor{})
time.sleep(2 * time.millisecond)
duration := c.blink.elapsed().milliseconds()
println(duration)
assert duration > 0
}
12
```
=> cgen: fix casting to interface with struct field default expr (fix #19497)

vlib/math/fractions/fraction.v
`struct Fraction` must be public for use in other modules.
=> math.fractions: fix struct to be public

doc/docs.md, vlib/builtin/builtin.c.v, vlib/v/checker/checker.v, vlib/v/eval/eval.v, vlib/v/gen/js/js.v, vlib/v/gen/native/expr.v, vlib/v/parser/comptime.v, vlib/v/token/token.v
This PR implements `@VCURRENTHASH` as a replacement of the `C.V_CURRENT_COMMITH_HASH` macro. This is necessary to use this functionality on other backends than `cgen`.
To finish this transition, the following changes have to be applied _after_ merging this PR to remove `V_CURRENT_COMMIT_HASH`:
```diff
diff --git a/vlib/builtin/builtin.c.v b/vlib/builtin/builtin.c.v
index a7107b415..28c370987 100644
--- a/vlib/builtin/builtin.c.v
+++ b/vlib/builtin/builtin.c.v
@@ -50,7 +50,7 @@ fn panic_debug(line_no int, file string, mod string, fn_name string, s string) {
eprintln(' function: ${fn_name}()')
eprintln('  message: ${s}')
eprintln('     file: ${file}:${line_no}')
-		eprintln('   v hash: ${@VHASH}') // TODO: use @VCURRENTHASH when bootstrapped
+		eprintln('   v hash: ${@VCURRENTHASH}') …
```
=> all: implement `@VCURRENTHASH` to replace `C.V_CURRENT_COMMIT_HASH`

vlib/v/checker/fn.v
This PR fix fn call with option call argument in autofree mode (fix #19495).
```v
import os
fn maybe_error() !string {
return 'string'
}
fn return_string_result() ! {
os.write_file('./test.txt', maybe_error()!)!
}
fn main() {
return_string_result() or {
println(err.msg())
exit(1)
}
}
PS D:\Test\v\tt1> v -autofree run .
```
=> checker: fix fn call with option call argument in autofree mode (fix #19495)

vlib/math/complex/complex.v, vlib/math/gamma.v
=> math: add missing docstrings for math.log_gamma_sign and for the complex.complex constructor function

cmd/tools/vast/vast.v, vlib/v/ast/ast.v, vlib/v/checker/assign.v, vlib/v/fmt/fmt.v, vlib/v/fmt/tests/comments_expected.vv, vlib/v/parser/assign.v, vlib/v/parser/if_match.v, vlib/v/parser/lock.v, vlib/v/parser/parser.v
This PR simplify formatting assign statement comments.
=> fmt: simplify formatting assign statement comments

vlib/term/ui/input.v, vlib/term/ui/input_windows.c.v, vlib/term/ui/termios_nix.c.v
This is potentially BC-breaking, but I think it's better than using `unsafe{ nil }`.
=> term.ui: fix notices about uninitialized pointers

cmd/tools/repeat.v, vlib/v/ast/types.v, vlib/v/builder/nativebuilder/nativebuilder.v, vlib/v/checker/tests/compare_unsigned_signed.out, vlib/v/checker/tests/compare_unsigned_signed.vv, vlib/v/gen/native/amd64.v, vlib/v/gen/native/arm64.v, vlib/v/gen/native/array.v, vlib/v/gen/native/builtins.v, vlib/v/gen/native/dos.v, vlib/v/gen/native/elf.v, vlib/v/gen/native/expr.v, vlib/v/gen/native/gen.v, vlib/v/gen/native/macho.v, vlib/v/gen/native/pe.v, vlib/v/gen/native/stmt.v, vlib/v/gen/native/syscall.v, vlib/v/gen/wasm/gen.v, vlib/v/gen/wasm/mem.v, vlib/v/reflection/reflection.v, vlib/v/tests/array_test.v, vlib/v/tests/const_comptime_eval_before_vinit_test.v, vlib/v/tests/string_interpolation_struct_with_usize_field_test.v, vlib/wasm/constant.v, vlib/wasm/encoding.v, vlib/wasm/instructions.v
This PR fix native new_int errors.
=> native: fix native new_int errors

vlib/benchmark/benchmark.v, vlib/benchmark/benchmark_test.v
The current implementation of `benchmark::measure` always prints on call, but in some cases, the user may want to print the summary at the end of all calls to `benchmark::measure` 
```v
fn main() {
mut b := benchmark.start()
time.sleep(1500 * time.millisecond)
println('Doing job')
b.measure('Job')
println('Another')
time.sleep(500 * time.millisecond)
b.measure('Another')
}
```
The example above returns the following output:
```
Doing job
SPENT  1500.158 ms in Job
Another
SPENT   500.123 ms in Another
```
The PR implements two new functions:
- **step_measure:** same as `measure`, but stores the time spent message in `Benchmark::measure_steps`
- **total_measured_message:** generates a string with all the measured messages stored in `Benchmark::measure_steps`
```v
module main
import time …
```
=> benchmark: extend time measure

cmd/tools/vcreate/tests/new_with_model_arg.expect, cmd/tools/vcreate/tests/new_with_name_arg.expect, cmd/tools/vcreate/tests/new_with_no_arg.expect, cmd/tools/vcreate/vcreate_input_test.v, examples/password/tests/correct.expect, examples/password/tests/incorrect.expect, examples/password/tests/output_from_expect_arg.expect, examples/readline/tests/readline.expect, examples/readline/tests/readline_from_expect_arg.expect
=> ci: fix vcreate_input_test.v on FreeBSD (`expect` if installed, is in `/usr/local/bin` there) (fix #19577)

vlib/v/builder/builder.v, vlib/v/builder/dump_lists.v, vlib/v/checker/checker.v, vlib/v/checker/comptime.v, vlib/v/help/build/build-c.txt, vlib/v/pref/pref.v
Here is an example:
```
#0 02:53:20 ᛋ feature_dump_defines /v/vnew❱./v -dump-defines - examples/2048/
system,no_bounds_checking,skip
system,prealloc,skip
system,freestanding,skip
system,native,unknown
system,tinyc,eval
system,macos,skip
system,freebsd,skip
system,openbsd,skip
system,netbsd,skip
system,linux,eval
system,android,skip
system,glibc,unknown
system,vinix,skip
system,ios,skip
system,termux,skip
system,prod,skip
system,debug,skip
system,amd64,eval
system,arm64,skip
system,i386,skip
system,arm32,skip
system,windows,skip
system,solaris,skip
system,fast_math,unknown
system,x64,unknown
system,x32,unknown
system,dragonfly,skip
system,haiku,skip
system,qnx,skip
system,serenity,skip
system,darwin,skip
user,debug_strconv,skip
user,nofloat,skip
user,no_backtrace,skip …
```
=> checker, builder, pref: support `-dump-defines -` to help explore all the available user and system defines for a given program

vlib/math/big/big_test.v, vlib/math/big/integer.v
1. Fix #19585 
2. Add tests.
```v
fn main() {
println(big.integer_from_int(1234) / big.integer_from_int(10))
println(big.integer_from_int(-1234) / big.integer_from_int(10))
println(big.integer_from_int(1234) / big.integer_from_int(-10))
println(big.integer_from_int(-1234) / big.integer_from_int(-10))
}
```
output:
```
123
-123
-123
123
```
=> math.big: fix incorrect division with negative numbers(fix #19585)

vlib/net/http/server.v, vlib/net/http/server_test.v, vlib/net/tcp.v
Improves the ergonomics of `http.Server` from the module `net.http` .
=> net.http: support passing on_running, on_stopped, on_closed callback functions to http.Server{}, as well as show_startup_message: false.

vlib/v/reflection/reflection.v, vlib/v/tests/reflection_test.v
1. Fix #19595 
2. Add tests.
```v
import v.reflection
fn main() {
s := c'abc'
println(reflection.type_of(s))
}
```
outputs:
```
reflection.Type{
name: 'u8'
idx: 11
sym: reflection.TypeSymbol{
name: 'u8'
idx: 11
parent_idx: 0
language: v
kind: u8
info: reflection.TypeInfo(reflection.None{
parent_idx: 0
})
methods: [reflection.Function{
mod_name: 'builtin'
name: 'vbytes'
args: [reflection.FunctionArg{
name: 'data'
......
```
```v
import v.reflection
struct User {
name string
}
fn main() {
s := &User{}
println(reflection.type_of(s))
}
```
outputs:
```
reflection.Type{
name: 'User'
idx: 95
sym: reflection.TypeSymbol{
name: 'main.User'
idx: 95
parent_idx: 0
language: v
kind: struct_
info: reflection.TypeInfo(reflection.Struct{
parent_idx: 0
attrs: []
fields: [reflection.StructField{
name: …
```
=> reflection: fix an error when reflecting ref types(fix #19595)

vlib/net/aasocket.c.v, vlib/net/common.v, vlib/net/http/request.v, vlib/net/mbedtls/ssl_connection.v, vlib/net/openssl/ssl_connection.v, vlib/net/tcp.v, vlib/net/unix/common.v, vlib/picoev/loop_default.c.v
1. Fix #19580 
2. I don't know how to write test cases for net changes, For the use case of this issue, there is no written test case due to the result uncertainty  😄 
```v
module main
fn main(){
mut ch := chan string{}
mut threads := []thread {}
for _ in 1 .. 15 {
threads << spawn  fn(ch chan string){
for {
m := <-ch or {
break
}
res := http.get(m) or {
println(err)
continue
}
println(res.status_code)
}
}(ch)
}
for _ in 0..5 {
s:= "http://ip.sb"
ch <- s
}
ch.close()
threads.wait()
}
```
outputs:
```
200
200
200
200
200
```
=> net, net.http: fix missing select calls when request is read from non-block socket(fix #19580)

vlib/net/mbedtls/ssl_connection.v, vlib/net/openssl/ssl_connection.v
1. This PR fixed handling of spurious wake-up signals lost when calling select() in mbedtls and openssl.
2. Significantly reduced issue #19580 exception response messages.
3. There are many reasons of issue #19580. I will continue to submit PR to solve other small problems. It also needs to be kept open.
```
Shoves-MacBook:temp shove$ v a.v
Shoves-MacBook:temp shove$ ./a
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
```
=> net: fix handling of spurious wake-up signals lost when calling select() in mbedtls and openssl

vlib/v/ast/table.v, vlib/v/tests/const_init_order_test.v
The method is used for finding the constants, that another constant depends on.
=> ast: check receivers of callexprs too in ast.Table.dependent_names_in_expr

vlib/strings/builder.c.v, vlib/strings/builder_test.v
The new method writes a decimal number to the builder instance *without additional allocations* (if there is enough space).
=> strings: add Builder.write_decimal/1

vlib/math/stats/stats.v, vlib/net/http/backend_nix.c.v, vlib/net/http/request.v, vlib/net/mbedtls/ssl_connection.v, vlib/net/openssl/ssl_connection.v
This PR:
1. Fixed some ssl library call return values judgment and handling.
2. Fixed timeout handling for ssl/tls read and write operations.
3. Further reduced exception messages in issue #19580.
There are several more PR's for issue #19580, please keep it open, thanks, @spytheman 😄
=> net, net.http: fixed some ssl library call return values judgment and handling

vlib/os/signal.v, vlib/os/signal_darwin.c.v, vlib/os/signal_default.c.v, vlib/os/signal_linux.c.v, vlib/os/signal_test.v
This PR:
1. Added a convenient way to ignore certain system signals. It handles things differently depending on whether the current thread is the main thread or the background thread.
2. It's also part of improving the robustness of http.get() and can be useful in net applications.
3. Calling it is as simple as in go, in go: signal.Ignore(syscall.SIGPIPE, syscall.SIGILL, syscall.SIGURG)
```v
import os
os.signal_ignore(.pipe, .urg)
```
=> os: add a convenient way to ignore certain system signals

vlib/v/checker/for.v, vlib/v/checker/tests/for_c_stmt_with_option_call.out, vlib/v/gen/c/for.v, vlib/v/tests/for_c_stmt_with_option_call_test.v, vlib/v/tests/for_c_stmt_with_result_call_test.v
This PR fix for c stmt with option or result calls (fix #19630).
- Fix for c stmt with option or result calls.
- Add test.
```v
module main
fn foo() !int {
return 5
}
fn main() {
mut pos := 0
for ; pos > 10; pos = foo()! {
println(pos)
}
for pos = foo()!; pos > 10; {
println(pos)
}
assert true
}
PS D:\Test\v\tt1> v run .  
```
```v
import rand
import math { abs }
const nmax = 20
fn ana(n int) f64 {
return 1.0 // haven't started
}
fn avg(n int) f64 {
tests := 1e4
mut sum := 0
for t := 0; t < tests; t++ {
mut v := []bool{len: nmax, init: false}
for x := 0; !v[x]; x = rand.intn(n) or { 0 } {
v[x] = true
sum++
}
}
return f64(sum) / tests
}
fn main() {
println(' N   average   analytical   (error)')
println('=== ========= ============ =========')
for n in 1 .. nmax + 1 {
a := avg(n)
b := ana(n) …
```
=> checker, cgen: fix for c stmt with option or result calls (fix #19630)

vlib/os/os_windows.c.v
Handle cases where files cannot be opened. for example:"System Volume Information"
```
import os
ret := os.ls("e:\\System Volume Information") //produce ['']
```
=> fix ls() in os_windows.c.v when file no right to open.

vlib/net/http/http.v, vlib/net/http/http_proxy.v, vlib/net/http/http_proxy_test.v, vlib/net/http/request.v
In the fetch method of the net module, I added the ability to make requests using an http proxy
The request pool was taken as a basis https://github.com/vlang/v/pull/12276
UPD
```
fn main() {
proxy_addr := 'https://20.111.54.16:8123'
response := http.fetch(
method: http.Method.get,
url: "https://ifconfig.me/ip",
proxy: proxy_addr
)!
println(response.body)
}
```
Output
```
20.111.54.16
```
=> http.fetch http proxy support

vlib/net/net_nix.c.v, vlib/net/tcp.v
This PR:
1. At the socket level to ignore the exception signal (SIGNPIPE).
2. Enable the NODELAY option by default.
Related to http.get()
=> net: ignore the SIGNPIPE signal at the socket level on macos

README.md
I have noticed two grammar mistakes in **README.md** inside section "**Stability, future changes, post 1.0 freeze**".
"**stabilized in V 1.0. Of course the APIs will..**"  should be "**stabilized in V 1.0. Of course, the APIs will..**" and also
"**features being introduced and old features modified..**."  should be "**features being introduced and old features being modified...**"
Below I have attached a screenshot of it.
Please review my PR.
=> Update README.md - fixed two grammar mistakes.

vlib/v/checker/checker.v, vlib/v/checker/infix.v, vlib/v/tests/generics_array_append_test.v
- Resolve #19608, fix generic array append when generic type is known and the value type is matched.
- Add test code.
`v/tests/generics_array_append_test.v`
```v
fn g[T](arr []T) {
mut r := []T{}
r << arr
assert arr.len > 0
}
fn test_generic_array_append() {
g([1, 2, 3])
g([1.1, 2.2, 3.3])
g(['aa', 'bb', 'cc'])
gs[[]string]()!
}
fn gs[T]() !T {
mut typ := T{
cap: 10
}
if T.name == '[]string' {
typ << 'strings'
} else {
return error('only string arrays are supported')
}
return typ
}
```
=> checker: fix generic array append

vlib/net/http/backend_nix.c.v, vlib/net/http/http.v, vlib/net/http/request.v
1. Add a retry mechanism to http.fetch()
2. This PR is an ongoing follow-up on the stability of http.get()
3. After testing, it is much more stable now.  😄
=> net.http: add a retry mechanism to http.fetch() when the socket inevitably errors

CHANGELOG.md, README.md
I have updated the name of Twitter to X in all the documentation (Texts and Links) of this repo.
Everyone must be well aware by now that the legal name of Twitter has been formally changed to X. Therefore, I have updated the Readme and other files and corrected the name to X. Therefore, Wouldn't it be best to be updated with the latest?
=> docs: update the name of Twitter to X

vlib/v/gen/c/array.v, vlib/v/gen/c/infix.v, vlib/v/tests/array_methods_test.v
1. Fix #19670 
2. Add tests.
```v
interface Param {}
const some_strings = ['one', 'two', 'three']
fn test(params ...Param) {
param := params[0]
match param {
string {
if param in some_strings {
println('in some_strings')
}
}
else {
panic('oops')
}
}
}
fn main() {
test('three')
}
```
outputs:
```
in some_strings
```
=> cgen: fix array contains method with interface(fix #19670)

vlib/crypto/cipher/cipher.v, vlib/net/http/server.v, vlib/v/checker/checker.v, vlib/v/checker/tests/modules/implement_private_interface.out, vlib/v/checker/tests/modules/implement_private_interface/baz.v, vlib/v/checker/tests/modules/implement_private_interface/main.v, vlib/v/embed_file/decoder.v
This PR check error of implementing other module private interface (fix #19620).
- Check error of implementing other module private interface.
- Add test.
```v
// sub module
module baz
interface Foo {
a int
}
pub fn print_foo(f Foo) {
println(f.a)
}
```
```v
module main
import baz
fn main() {
b := Bar{10}
baz.print_foo(b) // prints 10
}
struct Bar {
a int
}
tt1.v:6:16: error: `Bar` cannot implement private interface `baz.Foo` of other module
4 | fn main() {
5 |     b := Bar{10}
6 |     baz.print_foo(b) // prints 10
|                   ^
7 | }
8 |
```
=> checker: check error of implementing other module private interface (fix #19620)

vlib/crypto/sha1/sha1.v, vlib/crypto/sha1/sha1_test.v, vlib/crypto/sha256/sha256.v, vlib/crypto/sha256/sha256_test.v, vlib/crypto/sha512/sha512.v, vlib/crypto/sha512/sha512_test.v
1. Fixed #19696 
2. Add tests.
```v
import crypto.sha256
fn main() {
s := 'sha256 this string'.bytes()
dump(s.hex())
mut d1 := sha256.new()
o1 := d1.sum(s)
dump(o1.hex())
mut d2 := sha256.new()
n := d2.write(s)!
dump(n)
o2 := d2.sum([]u8{})
o3 := d2.sum([]u8{})
dump(o2.hex())
dump(o3.hex())
}
```
outputs:
```
Shoves-MacBook:temp shove$ ./a
[a.v:6] s.hex(): 736861323536207468697320737472696e67
[a.v:10] o1.hex(): 736861323536207468697320737472696e67e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
[a.v:14] n: 18
[a.v:18] o2.hex(): 1af1dfa857bf1d8814fe1af8983c18080019922e557f15a8a0d3db739d77aacb
[a.v:19] o3.hex(): 1af1dfa857bf1d8814fe1af8983c18080019922e557f15a8a0d3db739d77aacb
```
=> crypto.sha: fix calculating hash values again for sha1/256/512(fix #19696)

vlib/crypto/md5/md5.v, vlib/crypto/md5/md5_test.v, vlib/crypto/sha1/sha1.v, vlib/crypto/sha256/sha256.v, vlib/crypto/sha512/sha512.v
1. Fixed calculating the same hash values when .sum() is called several times for md5
2. Add tests.
3. Add deprecated information to md5, sha1/256/512 checksum().
4. Maybe close issue #19696
=> crypto.md5: fix calculating the same hash values when .sum() is called several times

vlib/v/parser/parser.v
This PR cleanup enum_decl() in parser.v, formatting errors have occurred in the VUI occasionally.
- Direct calling of eat _ comments() in the field initialization of the constructs may cause errors due to a different initialization order,  so we should call in sequence before.
=> parser: cleanup enum_decl() in parser.v

vlib/crypto/md5/md5.v, vlib/crypto/sha1/sha1.v, vlib/crypto/sha256/sha256.v, vlib/crypto/sha512/sha512.v
@spytheman , I'm so sorry :(
In the last PR, I didn't notice that calling from inside the library would also get deprecation notification, so I modified it. Do you think this is OK?
=> crypto: eliminate deprecating notifications from internal calls to checksum()

vlib/log/log_test.v, vlib/v/checker/assign.v, vlib/v/checker/checker.v, vlib/v/checker/fn.v, vlib/v/checker/tests/mod_name_duplicate_const_err.out, vlib/v/checker/tests/mod_name_duplicate_param_err.out, vlib/v/checker/tests/mod_name_duplicate_var_err.out
> **Important**
> Wait with merge until deprecation date 2023/10/31 has passed.
=> checker: turn warning for var and param module name duplicates into error

vlib/net/html/html.v
- `net.html::parse` turns all tags to lowercase without expressing it in any of the docs **I found**, unless you check the actual implementation.
Example:
```XML
<MyTag></MyTag>
```
If we call `get_tags` with `MyTag` it fails, since the parser parses all tags to lowercase. This is a problem because the end user asks what he can see in the `XML` data.
I had two ideas:
1. Set all input to `get_tag` or `get_tags` to lowercase.
2. Add a note to both `parse` and `parse_file` to inform the user that he should search for lowercase tags.
I decided to use the second solution since most of the web uses lowercase tags, and being able to parse `XML` with `net.html` is only a side-effect of the DOM using the XML format, even though nowadays the usage of custom tags is big and most of them follow the …
=> net.html: Add documentation note to parse and parse_file

cmd/tools/vdoc/html.v
Hi everyone. It's been a while. Just checking in to see how V was doing lately and it turns out there's no code highlighting yet for README's in vdoc (*shocked face*). Good thing I'm on a break right now so I have time to fix this.
This just utilizes the things that I have implemented in the `markdown` library (see PRs below) as well as the good ol' `html_highlight` function already available in vdoc so there's few code added here.
Requires vlang/markdown#15 and vlang/markdown#16 to be merged.
Just to show the power of code highlighting changes things, here's a side-by-side comparison:
|Before|After|
|--|--|
|![image](https://github.com/vlang/v/assets/7358345/ed5f2ee6-da7e-41b0-9e8c-bb23e6d83a38)|![image](https://github.com/vlang/v/assets/7358345/2708b187-c3cc-41b3-92ce-6ab79990d619)| …
=> vdoc: support for highlighting code in README's

vlib/net/http/http.v
Most browsers allow up to 20 redirects.  Safari is one of the lowest, at 16 (IE8 was 10).
Increase max redirects to 16 to match lowest current browser use.
=> http: increase max redirects

vlib/v/checker/fn.v, vlib/v/tests/closure_in_if_guard_test.v
This PR fix closure in if guard (fix #19748).
- Fix closure in if guard.
- Add test.
```v
struct Foo {
optional ?int
}
fn main() {
f := Foo{45}
mut ret := ''
if v := f.optional {
func := fn [v] () string {
println(v)
return '${v}'
}
ret = func()
}
assert ret == '45'
}
45
```
=> checker: fix closure in if guard (fix #19748)

vlib/v/gen/c/assign.v, vlib/v/tests/closure_test.v
1. Fixed #19734 
2. Add tests.
```v
module main
fn main() {
f := foo()
f()
}
fn foo() fn () {
return fn () {
mut left := 1
mut right := 2
left, right = right, left
println('${left} ${right}')
}
}
```
outputs:
```
2 1
```
=> cgen: fix closure parameter judgment when var cross assign inside anon fn(fix #19734)

cmd/tools/vcreate/tests/init.expect, cmd/tools/vcreate/vcreate.v, cmd/tools/vcreate/vcreate_init_test.v, cmd/tools/vcreate/vcreate_new_test.v
The PR wants to add the feature of allowing to add project information when using `v init` to initialize a project, instead of just printing ``Change the description of your project in `v.mod`"``. Just like we do with `v new`, but with a shorter prompt that uses the name of the current directory instead of asking for the project name. 
It also updates and extends tests. Using dedicated tests for the commands with `vcreate_init_test.v` and `vcreate_new_test.v`.
=> tools.vcreate: prompt for meta data on init

cmd/tools/vpm/install.v, cmd/tools/vpm/vpm.v
- Improves the feedback messages that are printed during installation.
E.g. currently all this is printed in non-verbose mode, when installing a module.
```
❯ v install https://github.com/vlang/markdow
Installing module "markdown" from "https://github.com/vlang/markdown" to "/home/t/.vmodules/vlang/markdown" ...
Relocating module from "vlang/markdown" to "markdown" ("/home/t/.vmodules/markdown") ...
Warning module "/home/t/.vmodules/markdown" already exists!
Removing module "/home/t/.vmodules/markdown" ...
Module "markdown" relocated to "markdown" successfully.
```
But when using `--once`, the already installed info would only be printed with the verbose flag added. Without it, the install command would immediately finish, without printing any info.
```
❯ v install -v --once …
```
=> tools.vpm: improve prints for install command

vlib/v/tests/const_with_fn_param_with_the_same_name_test.v, vlib/v/transformer/transformer.v
Fix #19766.
Discovered by partially reverting commit 055e113af37017a5bbc9173b17cecbe556b79b39 in https://discord.com/channels/592103645835821068/592294828432424960/1170655326526242837 .
=> transformer: fix using a constant, instead of a fn parameter, with the same name (fix #19766)

vlib/math/complex/complex.v, vlib/v/ast/types.v
=> vlib: add missing docstring for vlib/v/ast/types.v functions

vlib/regex/regex.v, vlib/regex/regex_test.v
* Fix for regex issue #19789
* Added more tests on the topic
* Removed all wrong `rune` cast for regex interpreter instructions, **they must be `u32`**
=> regex: bug fix for issue #19789

vlib/v/gen/c/fn.v, vlib/v/tests/closure_variable_in_smartcast_test.v
This PR fix closure variable in smartcast (fix #19616).
- Fix closure variable in smartcast.
- Add test.
```v
pub type MyCallback = fn () | fn (ctx voidptr)
fn my_lower_level_func(func fn (ctx voidptr), ctx voidptr) {
println('Bar')
}
fn my_func(cb MyCallback, ctx voidptr) {
my_lower_level_func(fn [cb] (ctx voidptr) {
match cb {
fn () {
cb()
}
fn (ctx voidptr) {
cb(ctx)
}
}
}, ctx)
}
fn main() {
my_func(fn () {
println('Foo')
}, unsafe { nil })
assert true
}
Bar
```
=> cgen: fix closure variable in smartcast (fix #19616)

cmd/tools/modules/testing/common.v, cmd/tools/vbuild-tools.v
- tests: ensure that each _test.v file runs in its own unique folder, to prevent naming conflicts as much as possible
- tools: fix `v build-tools` (move all tools back inside cmd/tools, to make packaging V easier)
=> tools: fix `v build-tools`, make `v test` more robust

vlib/v/gen/c/assign.v, vlib/v/tests/shared_generic_test.v
1. Fixed #19798
2. Add tests.
```v
shared test := datatypes.Queue[int]{}
lock test {
println(test)
}
```
outputs:
```
[]
```
=> cgen: fix shared variable assign generic structs(fix #19798)

vlib/v/checker/tests/option_ref_init_err.out, vlib/v/checker/tests/option_ref_init_err.vv, vlib/v/parser/fn.v, vlib/v/tests/shared_generic_test.v
1. Fixed #19804 
2. Add tests.
```v
struct Test[T] {
value T
}
fn do_something(shared stuff Test[int]) {
rlock stuff {
println(stuff.value)
}
}
shared test := Test[int]{}
do_something(shared test)
```
outputs:
```
0
```
=> parser: fix shared generic struct as fn parameters(fix #19804)

cmd/tools/vpm/common.v, cmd/tools/vpm/install.v, cmd/tools/vpm/install_test.v, cmd/tools/vpm/update.v, cmd/tools/vpm/vpm.v
Based on the end result of #19813 we can make it a 3 or 4 part change which can be better monitored. 
This PRs main change:
- Add a parse_query step - to evaluate the requested modules (and versions to use in a followup PR) at the beginning and use []Module arrays that store all data that is needed instead of working with []string arrays for the whole process.
=> vpm: add parse_query

cmd/tools/vpm/common.v, cmd/tools/vpm/install.v, cmd/tools/vpm/update.v, cmd/tools/vpm/vpm.v
Part 2/3 of splitting up #19813.
Includes updates of methods and all cleanups and preparations.
Also preps `update.v` to use `parse_query.v` and to get things fixed and tested.
=> tools: prepare vpm version installs

vlib/v/gen/c/str.v, vlib/v/tests/interface_str_method_test.v
1. Fixed #19788 
2. Add tests.
```v
module main
interface Abc {
a int
}
struct Xyz {
a int
}
fn main() {
d := Abc(Xyz{})
if d is Xyz {
println(d)
}
}
```
outputs:
```
&Xyz{
a: 0
}
```
=> cgen: fix gen interface to string(fix #19788)

examples/path_tracing.v, vlib/v/checker/assign.v, vlib/v/checker/tests/invalid_literal_assign_err.out, vlib/v/checker/tests/prefix_expr_decl_assign_err.out, vlib/v/checker/tests/unsafe_deref_assign_err.out, vlib/v/checker/tests/unsafe_deref_assign_err.vv, vlib/v/tests/assign_bitops_with_type_aliases_test.v, vlib/v/tests/mut_test.v
1. Fixed #19819 
2. Add tests.
3. Fixed related tests.
```v
c := 0
cref := &c
*cref = 1
(*cref) = 1
```
outputs:
```
a.v:4:7: error: modifying variables via dereferencing can only be done in `unsafe` blocks
2 | cref := &c
3 | 
4 | *cref = 1
|       ^
5 | (*cref) = 1
6 |
a.v:5:9: error: modifying variables via dereferencing can only be done in `unsafe` blocks
3 | 
4 | *cref = 1
5 | (*cref) = 1
|         ^
6 | 
7 |
```
=> checker: fix: missing check when assignment statement lvalue is ParExpr(fix #19819)

vlib/v/parser/expr.v
Fixed #19539 
```v
struct Foo {
value int = 0xf00
}
struct Bar {}
type FooBar = Bar | Foo
fn main() {
mut foobar := FooBar(Bar{})
match mut foobar {
Foo {
println('foo')
}
else {
println('bar')
}
}
}
```
```v
struct Foo {
value int = 0xf00
}
struct Bar {}
type FooBar = Bar | Foo
fn main() {
mut foobar := FooBar(Bar{})
if mut foobar is Foo {
println('foo')
} else {
println('bar')
}
}
``` 
Invalid warnings have been removed.
=> parser: fix invalid warning 'unused' for mut var in if/match cond(fix#19539)

vlib/v/checker/checker.v, vlib/v/checker/match.v, vlib/v/checker/tests/match_return_mismatch_type_err.out, vlib/v/checker/tests/match_return_mismatch_type_err.vv, vlib/v/gen/c/cgen.v, vlib/v/gen/c/match.v, vlib/v/tests/match_test.v
1. Fixed #16203
2. Add tests.
Because smartcast adds one level of ref to the interface type, special handling is required in the return type of the match expr branch.
```v
fn (any Any) echo() {
r := match any {
string { any }
else { 'unsupported' }
}
println(r)
}
Any('hallo').echo()
```
outputs:
```
hallo
```
=> checker, cgen: fix match branches return type ref mismatch, when return type exists interface or sumtype(fix #16203)

vlib/v/checker/lambda_expr.v, vlib/v/tests/lambda_expr_test.v
1. Fixed #19853 
2. Add tests.
```v
fn f(g fn (int) string) {
println('function returned: ${g(42)}')
}
fn main() {
f(|_| 'hello world')
}
```
outputs:
```
function returned: hello world
=> checker: fix blank_ident as param of lambda exprs(fix #19853)

vlib/v/ast/table.v, vlib/v/checker/checker.v, vlib/v/checker/fn.v, vlib/v/checker/for.v, vlib/v/checker/match.v, vlib/v/checker/postfix.v, vlib/v/checker/str.v, vlib/v/gen/c/array.v, vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/comptime.v, vlib/v/gen/c/dumpexpr.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/for.v, vlib/v/gen/c/match.v, vlib/v/gen/c/str_intp.v
A minor cleanup:
Extract is_interface_var(), is_comptime_var() methods from cgen, checker to ast.table
=> ast, checker, cgen: a minor cleanup

vlib/v/parser/parser.v, vlib/v/tests/generics_call_with_fixed_array_arg_test.v
This PR fix generic fn call with fixed array argument (fix #19863).
- Fix generic fn call with fixed array argument.
- Add test.
```v
fn generic[T](t T) string {
return '${t}'
}
fn main() {
r1 := generic[[3]int]([1, 2, 3]!)
println(r1)
assert r1 == '[1, 2, 3]'
r2 := generic[[]int]([1, 2, 3])
println(r2)
assert r2 == '[1, 2, 3]'
r3 := generic[int](22)
println(r3)
assert r3 == '22'
r4 := generic[bool](true)
println(r4)
assert r4 == 'true'
}
[1, 2, 3]
[1, 2, 3]
22
true
```
=> parser: fix generic fn call with fixed array argument (fix #19863)

.github/workflows/other_ci.yml, cmd/tools/vtest-parser.v, vlib/v/parser/fn.v, vlib/v/parser/parse_type.v, vlib/v/parser/parser.v, vlib/v/scanner/scanner.v
- parser: make the parser a bit more robust for fuzzed source code, and show more context on scanner fails for source code without backing .v files
- parser: make the parser more robust for fuzzed source code
=> parser: fix failures found with fuzzing

vlib/v/checker/checker.v, vlib/v/checker/tests/lambda_undefined_variables_err.out, vlib/v/checker/tests/lambda_undefined_variables_err.vv, vlib/v/parser/expr.v
1. Fixed #19860 
2. Add tests.
```v
fn f(g fn (int) string) {
println('function returned: ${g(42)}')
}
fn main() {
s := 'hello world'
f(|i| s)
}
```
outputs:
```
a.v:5:9: warning: unused variable: `s`
3 | }
4 | fn main() {
5 |         s := 'hello world'
|         ^
6 |         f(|i| s)
7 | }
a.v:6:15: error: undefined variable `s`
4 | fn main() {
5 |         s := 'hello world'
6 |         f(|i| s)
|               ^
7 | }
8 |
a.v:6:11: error: `s` used as value
4 | fn main() {
5 |         s := 'hello world'
6 |         f(|i| s)
|           ^
7 | }
8 |
```
=> parser, checker: fix var scope in lambda(fix #19860)

vlib/v/checker/return.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/tests/generics_return_fixed_array_test.v
This PR fix generic fn returning fixed array (fix #19872).
- Fix generic fn returning fixed array.
- Add test.
```v
module main
fn init_type[T]() T {
return T{}
}
fn main() {
r1 := init_type[[3]int]()
println(r1)
assert '${r1}' == '[0, 0, 0]'
}
[0, 0, 0]
```
=> checker, cgen: fix generic fn returning fixed array (fix #19872)

vlib/v/checker/struct.v, vlib/v/gen/c/cgen.v, vlib/v/parser/parse_type.v, vlib/v/tests/constant_array_size_test.v
1. Fixed #19593 
2. Add tests.
```v
struct Test {
posts [max_posts_count]int
}
const max_posts_count = 5
t := Test{}
println(t)
```
outputs:
```
[0, 0, 0, 0, 0]
```
=> parser, checker: fix const var below at struct fixed array fields(fix#19593)

vlib/v/checker/tests/incorrect_name_sum_type.out, vlib/v/checker/tests/incorrect_name_sum_type.vv
fmt code and add `type_idx` method on test
```bash
vlib/v/checker/tests/incorrect_name_sum_type.vv:1:1: error: sum type `integer` must begin with capital letter
1 | type integer = i16 | i64 | i8 | int
| ~~~~~~~~~~~~
2 | type Integer = i16 | i64 | i8 | int
3 |
vlib/v/checker/tests/incorrect_name_sum_type.v:4:1: error: method overrides built-in sum type method
2 | type Integer = i16 | i64 | i8 | int
3 |
4 | fn (i Integer) type_idx() {
| ~~~~~~~~~~~~~~~~~~~~~~~~~
5 | }
6 |
vlib/v/checker/tests/incorrect_name_sum_type.v:7:1: error: method overrides built-in sum type method
5 | }
6 |
7 | fn (i Integer) type_name() {
| ~~~~~~~~~~~~~~~~~~~~~~~~~~
8 | }
```
=> test improve incorrect_name_sum_type

vlib/v/gen/c/cgen.v, vlib/v/tests/modules/consts_with_or_blocks_in_different_files/config.v, vlib/v/tests/modules/consts_with_or_blocks_in_different_files/consts_should_not_conflict_test.v
1. Fixed #19149 
2. Add tests.
=> cgen: fix temporary var name conflicts between const definitions with or_block in different files(fix #19149)

vlib/v/fmt/fmt.v, vlib/v/fmt/tests/match_with_multi_commented_branches_keep.vv, vlib/v/parser/if_match.v
This PR fix match with multi-commmented branchs (fix #19880).
- Fix match with multi-commmented branchs.
- Add test.
vlib\v\fmt\tests\match_with_multi_commented_branches_keep.vv
```v
import strings
fn escape_string(s string) string {
mut res := strings.new_builder(s.len * 2)
for ch in s {
match ch {
0 // NUL (null)
{
res.write_u8(92) // \
res.write_u8(48) // 0
}
10 { // LF (line feed)
res.write_u8(92) // \
res.write_u8(110) // n
}
13 { // CR (carriage return)
res.write_u8(92) // \
res.write_u8(114) // r
}
26 { // SUB (substitute)
res.write_u8(92) // \
res.write_u8(90) // Z
}
34,  // "
39,  // '
92 // \
{
res.write_u8(92) // \
res.write_u8(ch)
}
else {
res.write_u8(ch)
}
}
}
return res.bytestr()
}
fn main() {
}
```
=> parser, fmt: fix match with multi-commmented branchs (fix #19880)

cmd/tools/vast/vast.v, doc/docs.md, examples/js_dom_draw_bechmark_chart/v_vweb_orm/src/main.v, tutorials/building_a_simple_web_blog_with_vweb/README.md, vlib/json/README.md, vlib/json/json_encode_recursive_ptr_test.v, vlib/orm/orm_null_test.v, vlib/v/ast/table.v, vlib/v/fmt/attrs.v, vlib/v/fmt/fmt_keep_test.v, vlib/v/fmt/struct.v, vlib/v/fmt/tests/old_attrs_to_new_expected.vv, vlib/v/fmt/tests/old_attrs_to_new_input.vv, vlib/v/tests/enum_attr_2_test.v, vlib/v/tests/generics_for_in_iterate_test.v, vlib/v/tests/struct_fields_required_test.v, vlib/v/tests/struct_test.v
- vfmt: convert all [attr] to @[attr] automatically
- fix the remaining old [attributes] (`v test-all` now passes, after the vfmt change)
=> vfmt: automate transition from the old [attribute] to the new @[attribute] syntax

vlib/v/checker/fn.v, vlib/v/gen/c/array.v, vlib/v/gen/c/fn.v, vlib/v/tests/alias_array_built_in_methods_test.v
1. Fixed #19896 
2. Fixed built-in methods: filter, map, any, all, sort, sorted, contains.
3. Add tests.
```v
enum MsgType {
null  = 0
text  = 1
ctrl  = 2
frame = 3
}
struct Msg {
msg_type MsgType
payload  []u8
}
type Msgs = []Msg
fn main() {
msgs0 := [Msg{
msg_type: .null
}, Msg{
msg_type: .text
}, Msg{
msg_type: .null
}, Msg{
msg_type: .frame
}]
// it works without aliased msg
msgs1 := msgs0.clone()
null_msgs1 := msgs1.filter(it.msg_type == .null)
dump(null_msgs1)
// with aliased array
msgs2 := Msgs(msgs0)
null_msgs2 := msgs2.filter(it.msg_type == .null)
dump(null_msgs2)
}
```
outputs:
```
[a.v:29] null_msgs1: [Msg{
msg_type: null
payload: []
}, Msg{
msg_type: null
payload: []
}]
[a.v:34] null_msgs2: Msgs([Msg{
msg_type: null
payload: []
}, Msg{
msg_type: null
payload: []
}])
```
=> checker, cgen: fix arrays alias built-in methods call(fix #19896)

doc/docs.md
1. Added newline after `**Note**` for readability: before, "Note" caption was mixed with the content. By the way, isn't it better to use `[!NOTE]` syntax?
2. On 548th line: moved code outside the comment. Not sure if I'm right, but looked like typo or formatting error.
=> doc: add newlines to "Note" quotes

cmd/tools/vpm/common.v, cmd/tools/vpm/install_test.v
The PR will add a warning when installing vpm-registered modules that are missing a manifest. Unlike for URL installs, the installation will for now continue without an error.
E.g.,
```
❯ v install spytheman.regex
warning: `spytheman.regex` is missing a manifest file.
Installing `spytheman.regex`
Installed `spytheman.regex` 
```
If the module has an active issues section, details will be added to the warning. Below, `sdl` serves just as an example; it is not actually missing a manifest file. 
The link would open a pre-filled issue.
```
❯ v install sdl
warning: `sdl` is missing a manifest file.
details: Help to ensure future-compatibility by adding a `v.mod` file or opening an issue at:
`https://github.com/vlang/sdl/issues/new?title=Missing%20Manifest&body=sdl%20is%20missing%20a%20manifest, …
```
=> tools.vpm: add warning when installing a vpm module without a manifest

vlib/v/ast/ast.v, vlib/v/checker/fn.v, vlib/v/gen/c/fn.v, vlib/v/tests/interface_embedding_call_test.v
1. Fixed #16496 
2. Add tests.
```v
interface Foo {
a_method()
}
fn (f Foo) foo_method() int {
return 0
}
interface Bar {
Foo
}
fn (b Bar) bar_method() int {
return b.foo_method()
}
struct Derived {}
fn (d &Derived) a_method() {
}
fn main() {
bar := Bar(Derived{})
println(bar.bar_method())
}
```
outputs:
```
0
```
This problem occurs when calls the method of the embedded interface in the interface method, because the transformation mechanism of the interface embedded method is currently missing.  This PR implements the same mechanism in the interface by calling the method of the embedded struct from the struct
=> ast, checker, cgen: fix interface embeded methods call(fix #16496)

vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/json.v, vlib/v/tests/var_name_using_reserved_test.v
This PR fix variable name using reserved name (fix #19808).
- Fix variable name using reserved name.
- Add test.
```v
fn main() {
error := {
0: 1
1: 2
2: 3
}
ret := error[4] or { 42 }
println(ret)
assert ret == 42
}
42
```
=> cgen: fix variable name using reserved name (fix #19808)

vlib/v/checker/containers.v, vlib/v/checker/struct.v, vlib/v/checker/tests/array_map_elements_ref_fields_uninitialized_err.out, vlib/v/checker/tests/array_map_elements_ref_fields_uninitialized_err.vv, vlib/v/tests/const_fixed_array_containing_references_to_itself_test.v, vlib/v/tests/str_circular_test.v
1. Fixed #19864 
2. Add tests.
```v
struct Foo {
n &int
}
fn main() {
_ = []Foo{}
_ = [1]Foo{}
_ = map[string]Foo{}
_ = map[string][]Foo{}
}
```
outputs:
```
a.v:6:6: error: reference field `Foo.n` must be initialized (part of struct `Foo`)
4 | 
6 |     _ = []Foo{}
|         ~~~~~~
7 |     _ = [1]Foo{}
8 |     _ = map[string]Foo{}
a.v:7:6: error: reference field `Foo.n` must be initialized (part of struct `Foo`)
6 |     _ = []Foo{}
7 |     _ = [1]Foo{}
|         ~~~~~~~~
8 |     _ = map[string]Foo{}
9 |     _ = map[string][]Foo{}
a.v:8:6: error: reference field `Foo.n` must be initialized (part of struct `Foo`)
6 |     _ = []Foo{}
7 |     _ = [1]Foo{}
8 |     _ = map[string]Foo{}
|         ~~~~~~~~~~~~~~~~
9 |     _ = map[string][]Foo{}
10 | }
a.v:9:6: …
```
=> checker: check element and its children for ref uninitialized fields(fix #19864)

cmd/tools/vdoc/tests/testdata/multiline/main.comments.out, cmd/tools/vdoc/tests/testdata/multiline/main.out, cmd/tools/vdoc/tests/testdata/multiline/main.v, cmd/tools/vdoc/tests/testdata/newlines/main.comments.out, cmd/tools/vdoc/tests/testdata/newlines/main.v, cmd/tools/vdoc/theme/doc.css, vlib/v/doc/utils.v
The PR updates the linebreak handling and treats lines that start with `Note` || `Fixme` || `Todo` (indepdent of lettercase) as own paragraphs. 
The current logic of adding line breaks after periods was removed, as it inevitable results in inconsistencies. Instead, a word-wrap via css was added if a line exceeds 100 characters (this similar to how doc comments are handled in go docs). While removing the period line breaks might not result in a better outcome for every single case that intentionally made use of this, I think for the bigger part can benefit from the change and that the general consistency outweigh it.
Many comments use `Note:` / `NOTE:` / `note:` to add additional info or emphasize something. 
Those would now be put into a separate paragraph. If such a comment is used, the …
=> doc: update linebreak logic, handle "highlight-comments"

vlib/v/gen/c/fn.v, vlib/v/tests/fn_call_interface_args_test.v
1. Fixed #19947 
2. Add tests.
```v
interface Foo {}
fn main() {
foo := Foo(1)
thing(foo)
}
fn thing(src_objects Foo) {
other_thing(src_objects, src_objects)
}
fn other_thing(a &Foo, b &Foo) {
dump(a)
dump(b)
}
```
outputs:
```
[a.v:14] a: &Foo(1)
[a.v:15] b: &Foo(1)
```
=> cgen: fix  ref and deref when interface as a function parameter(fix #19947)

vlib/builtin/map.v, vlib/builtin/map_d_gcboehm_opt.v, vlib/gg/gg.c.v, vlib/net/urllib/urllib.v, vlib/os/os_windows.c.v, vlib/os/process_windows.c.v, vlib/sync/channels.c.v, vlib/v/ast/table.v, vlib/v/checker/checker.v, vlib/v/checker/struct.v, vlib/v/checker/tests/struct_ref_fields_init_0_err.out, vlib/v/checker/tests/struct_ref_fields_init_0_err.vv, vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/orm.v, vlib/v/parser/comptime.v, vlib/v/parser/fn.v, vlib/v/parser/parser.v
1. Fixed #14911 (Just a notice for now)
2. Add tests
```v
struct Node {
val   int
left  &Node
right &Node
}
fn main() {
_ = Node { 123, 0, 0 }
}
```
outputs:
```
a.v:23:21: notice: assigning `0` to a reference field is only allowed in `unsafe` blocks
21 | 
22 | fn main() {
23 |     _ = Node { 123, 0, 0 }
|                     ^
24 | }
25 |
```
=> all: assigning `0` to reference fields requires unsafe blocks(fix #14911)

vlib/v/checker/containers.v, vlib/v/checker/tests/ptr_array_init.out, vlib/v/checker/tests/ptr_array_init.vv
1. Close #14958 
2. this PR just changed the check to be recursive so can check its children.
3. Add tests.
```v
fn main() {
_ = [][1]&int{len: 1}[0][0]
_ = []map[int]&int{len: 1}
}
```
outputs:
```
vlib/v/checker/tests/ptr_array_init_2.vv:2:6: warning: arrays of references need to be initialized right away, therefore `len:` cannot be used (unless inside `unsafe`)
2 |     _ = [][1]&int{len: 1}[0][0]
|         ~~~~~~~~~~
3 |     _ = []map[int]&int{len: 1}
4 | }
vlib/v/checker/tests/ptr_array_init_2.vv:3:6: warning: arrays of references need to be initialized right away, therefore `len:` cannot be used (unless inside `unsafe`)
2 |     _ = [][1]&int{len: 1}[0][0]
3 |     _ = []map[int]&int{len: 1}
|         ~~~~~~~~~~~~~~~
4 | }
```
=> checker: fix ref elements of the array must be initialized right away(fix #14958)

vlib/v/checker/containers.v, vlib/v/checker/tests/array_map_elements_ref_fields_uninitialized_err.out, vlib/v/checker/tests/array_map_elements_ref_fields_uninitialized_err.vv
1. The check of PR 19944 is too strict and can be relaxed when no `len` argument is specified in `[]&Struct{}`
2. The related tests were adjusted
=> checker: add a qualification to array elements ref initialization checks

cmd/tools/vpm/common.v, cmd/tools/vpm/install.v, cmd/tools/vpm/parse.v
The recent updates to VPM allow for cleanups.
E.g. the installation for vpm registered modules and external modules was standardized to the extent that handling the modules in their separate functions is now obsolete. Such cleanups are done in the first commit.
The second commit just organizes, e.g. it moves parsing functionality - which has grown - into its own file, and a common function into `common.v`.
=> tools.vpm: cleanup, extract parsing into `parse.v`

vlib/v/checker/checker.v, vlib/v/checker/tests/index_sumtype_or_interface_params_err.out, vlib/v/checker/tests/index_sumtype_or_interface_params_err.vv
1. Fixed #19811 
2. Add tests.
```v
type Tree = string| map[string]string
fn append(mut tree Tree) {
print(tree["key"])
}
fn main() {
}
```
outputs:
```
a.v:4:15: error: type `Tree` does not support indexing
2 | 
3 | fn append(mut tree Tree) {
4 |     print(tree["key"])
|               ~~~~~~~
5 | }
6 |
```
=> checker: disallow directly indexing sumtype and interface, when using as parameters(fix #19811)

vlib/os/file.c.v, vlib/os/os.c.v
Adds line breaks for comments that should define sections in the source code to not make them part of doc comments. 
E.g., like it's already done here:
https://github.com/vlang/v/blob/399af6768d04a57fc76b399343a7dc91642960b3/vlib/os/file.c.v#L415-L419
Removes one sectional comments for OS ops since all operations are OS ops in that file
=> os: update comments

vlib/builtin/builtin_d_gcboehm.c.v
Enable mmap for Boehm GC memory allocation on FreeBSD to avoid the use of sbrk().
=> define USE_MMAP for freebsd for gc when tcc is not used -- this avoids use of sbrk()

vlib/v/checker/check_types.v, vlib/v/gen/c/infix.v, vlib/v/tests/generics_call_with_interface_arg_test.v
1. Fixed #19976 
2. Add tests.
```v
import arrays
interface AnythingGoes{ }
mut the_one_array := []AnythingGoes{}
some_string := 'It would suck'
another_string := 'if I was forced'
last_string := 'to << every var into the array'
random_int := 69
// this produces an error, but it shouldn't!
the_one_array = arrays.concat(the_one_array, some_string, another_string, last_string, random_int)
println(the_one_array)
```
outputs:
```
[AnythingGoes('It would suck'), AnythingGoes('if I was forced'), AnythingGoes('to << every var into the array'), AnythingGoes(69)]
```
=> checker, cgen: fix generics call with interface arg(fix #19976)

vlib/v/ast/table.v, vlib/v/checker/fn.v, vlib/v/tests/generics_with_embed_generics_method_call_test.v
This PR fix generics with embed generic method call (fix #19968).
- Fix generics with embed generic method call.
- Add test.
```v
pub type Handler[T] = fn (mut T) bool
struct Collector[T] {
mut:
handlers []Handler[T]
}
pub fn (mut c Collector[T]) use(func Handler[T]) {
c.handlers << func
}
pub struct Context {}
fn handler(mut ctx Context) bool {
println('from test_handler!')
return true
}
pub struct MainStruct {
Collector[Context]
}
fn main() {
mut s := MainStruct{}
s.use(handler)
println(s)
assert s.handlers.len == 1
}
MainStruct{
Collector: Collector[Context]{
handlers: [fn (mut Context) bool]
}
}
```
=> ast, checker: fix generics with embed generic method call (fix #19968)

vlib/v/fmt/fmt.v, vlib/v/fmt/tests/global_keep.vv
It doesn't make any sense to leave `__global` block empty.
=> vfmt: remove empty `__global()`

vlib/v/ast/table.v, vlib/v/tests/generics_with_embed_generics_structs_test.v
1. Fixed #20021 
2. Add tests.
```v
struct Foo[T] {
field T
}
struct MainStruct[T] {
Foo[T]
}
fn main() {
m := MainStruct[int]{}
println(m.field)
}
```
outputs:
```
0
```
=> ast: fix generics with embed generics structs(fix #20021)

vlib/v/ast/table.v, vlib/v/ast/types.v
This PR fixed: duplicated code gen for embedded generic fields
```v
struct Foo[T] {
field T
}
struct MainStruct[T] {
Foo[T]
}
fn main() {
m := MainStruct[int]{}
println(m.field)
}
```
code gen:
now:
```c
main__MainStruct_T_int m = ((main__MainStruct_T_int){.Foo = ((main__Foo_T_int){.field = 0,}),});
println(int_str(m.Foo.field));
}
```
=> ast: duplicated code gen for embedded generic fields

vlib/v/ast/types.v, vlib/v/parser/parse_type.v
There's a real chance of confusion here, and the notes are added to make it easier to read and remember.
=> ast, parser: add comments to several representations of complete qualified names for generics

vlib/v/gen/c/if.v, vlib/v/tests/if_match_branches_with_call_expr_with_or_block_test.v
1. Fixed #20044 
2. Add tests.
```v
fn baz(str string) !string {
return str
}
foo := '/bar'
bar := if foo.contains('foo') {
foo.all_after('foo')
} else {
baz(foo) or { panic('panic') }.trim_left('/')
}
assert bar == 'bar'
println(bar)
```
outputs:
```
bar
```
=> cgen: fix call_expr in branches and left_expr of call_expr with or_block(fix #20044)

examples/sokol/06_obj_viewer/modules/obj/obj.v, vlib/builtin/js/string.js.v, vlib/builtin/string.v, vlib/builtin/string_test.v, vlib/io/util/util.v, vlib/net/urllib/urllib.v, vlib/os/os.v, vlib/semver/parse.v, vlib/v/checker/checker.v, vlib/v/checker/struct.v, vlib/v/checker/tests/type_cast_option_err.out, vlib/v/checker/tests/type_cast_option_err.vv, vlib/v/gen/js/js.v, vlib/v/tests/option_default_values_test.v
- builtin: deprecate string.last_index/1 and string.last_index_u8/1.
- instead use string.index_last/1 and string.index_u8_last/1.
- use the more efficient string.index_u8_last/1, where possible.
=> builtin: deprecate string.last_index/1 for string.index_last/1, and string.last_index_u8/1 for string.index_u8_last/1

vlib/v/checker/interface.v, vlib/v/tests/generic_interface_array_type_infer_test.v
This PR fix generic interface inferring error (fix #19951).
- Fix generic interface inferring error.
- Add test.
```v
struct Metadata {}
struct TagOrText {}
pub interface Layout[R] {
render(content []R) string
}
struct DefaultLayout {
}
pub fn (self DefaultLayout) to_layout() Layout[TagOrText] {
return self
}
pub fn (self DefaultLayout) render(content []TagOrText) string {
return 'Hello world'
}
fn main() {
ret := DefaultLayout{}.to_layout().render([])
println(ret)
assert ret == 'Hello world'
}
Hello world
```
=> checker: fix generic interface inferring error (fix #19951)

vlib/regex/regex.v, vlib/regex/regex_test.v
1. Fixed #19802 
2. Add tests.
```v
import regex
fn main() {
re1 := regex.regex_opt('^abc\0$')!
assert re1.matches_string('abc') == false
assert re1.matches_string('abc\0') == true
re2 := regex.regex_opt('^abc\0xyz$')!
assert re2.matches_string('abc' + 'xyz') == false
assert re2.matches_string('abc\0xyz') == true
}
```
outputs:
```
passed
```
=> regex: fix '\0' terminator always matched as last character(fix #19802)

examples/gg/bezier.v, examples/gg/bezier_anim.v, vlib/x/ttf/README.md
Fixes a few "notice: assigning `0` to a reference field is only allowed in `unsafe` blocks" and some unnecessary `gg: 0` assignments
=> examples, x: fix notice about assigning 0 to a reference field

vlib/v/checker/struct.v, vlib/v/tests/generics_struct_method_params_is_generics_struct_and_not_called_test.v
1. Fixed #20132 
2. Add tests.
```v
import time
pub type EventListener[T] = fn (T) !
struct Chan[T] {
c chan T
}
struct EventWaiter[T] {
check ?fn (T) bool
c &Chan[T]
}
pub struct EventController[T] {
mut:
id int
wait_fors map[int]EventWaiter[T]
listeners map[int]EventListener[T]
}
fn (mut ec EventController[T]) generate_id() int {
return ec.id++
}
@[params]
pub struct EmitOptions {
pub:
error_handler ?fn (int, IError)
}
pub fn (mut ec EventController[T]) emit(e T, options EmitOptions) {
}
@[params]
pub struct EventWaitParams[T] {
pub:
check ?fn (T) bool
timeout ?time.Duration
}
pub fn (mut ec EventController[T]) wait[T](params EventWaitParams[T]) ?T {
return none
}
pub fn (mut ec EventController[T]) override[T](listener EventListener[T]) EventController[T] {
return ec
}
pub fn (mut ec …
```
=> checker: fix unwrap when generic structs are used as arguments in uncalled methods(fix #20132)

vlib/v/checker/struct.v, vlib/v/tests/struct_init_update_with_generics_test.v
1. Fixed #20136 
2. Add tests.
```v
struct S1 {
a int
b string
isbool bool
}
fn do[T](s T) {
println(T{
...s
isbool: true
})
}
fn main() {
do(S1{
a: 1
b: '2'
})
}
```
outputs:
```
Shoves-MacBook:temp shove$ ./a
S1{
a: 1
b: '2'
isbool: true
}
```
=> checker: fix struct init update with generics(fix #20136)

cmd/tools/vpm/expect/accept_reinstall_mod_with_version_installation.expect, cmd/tools/vpm/expect/decline_reinstall_mod_with_version_installation.expect, cmd/tools/vpm/install.v, cmd/tools/vpm/install_test.v, cmd/tools/vpm/install_version_test.v, cmd/tools/vpm/parse.v, cmd/tools/vpm/settings.v, cmd/tools/vpm/vcs.v
- Adds support for ssh installs e.g. `v install git@github.com:vlang/libsodium.git`.
- and for version installs (`@<tag>`) for modules using mercurial.
ssh is currently kind of supported. While at current master ssh modules CANNOT be installed via `v install`, `v update` CAN update such modules when adding an ssh module manually or changing the origin url of a module to an ssh address. But the update command has other issues. Adding (hopefully full) ssh support - before fixing the remaining known issues with the update command in a next step - will help keep the current functionality intact and make working with the ssh feature easier.
SSH CI tests are not added here, if git ssh is set up locally, it can be tested as follows:
```sh
❯ v install git@github.com:vlang/vsl
...
❯ git -C …
```
=> tools.vpm: add support for ssh and hg version installations

cmd/tools/vpm/install.v
For some V installations, e.g. when it's installed via the setup action in Windows CI, an `Access is denied` error might happen when trying to move from the temporary to the vmodules directory.
This is the reason why v-analyzer is currently failing. This regression should be fixed by this PR.
ref.: https://github.com/ttytm/v-analyzer/actions/runs/7167557843/job/19513888974
In regular V CI when, when installing V from source, this issue doesn't happen:
ref.: https://github.com/ttytm/v/actions/runs/7167524975/job/19513788776
=> tools.vpm: fix moving from temp to vmodules dir

vlib/v/parser/parser.v, vlib/v/parser/tests/struct_init_from_another_mod_err.out, vlib/v/parser/tests/struct_init_from_another_mod_err.vv
1. Fixed #20141
2. Add tests.
```v
import rand
import rand.config
fn main() {
mut a := [0, 1, 2]
rand.shuffle(mut a, rand.config.ShuffleConfigStruct{})!
}
```
outputs:
```
a.v:6:27: error: unknown module `rand.config`; did you mean `config`?
4 | fn main() {
5 |     mut a := [0, 1, 2]
6 |     rand.shuffle(mut a, rand.config.ShuffleConfigStruct{})!
|                              ~~~~~~
7 | }
8 |
```
```v
import rand
fn main() {
mut a := [0, 1, 2]
rand.shuffle(mut a, rand.config.ShuffleConfigStruct{})!
}
```
outputs:
```
a.v:5:27: error: unknown module `rand.config`
4 |     mut a := [0, 1, 2]
5 |     rand.shuffle(mut a, rand.config.ShuffleConfigStruct{})!
|                              ~~~~~~
6 | }
7 |
```
=> parser: fix an error message when initializing a struct from another module(fix #20141)

examples/graphs/bellman-ford.v, vlib/v/checker/fn.v, vlib/v/tests/generics_with_generics_fn_return_generics_map_type_test.v, vlib/v/tests/multiple_generic_resolve_test.v
This PR fix generic fn with generic fn call returning generic map (fix #20106).
- Fix generic fn with generic fn call returning generic map.
- Add test.
```v
fn generic1[K,V](a map[K]V) string {
t := expect_map[K, V](a)
dump(t)
return '${t}'
}
fn generic2[K,V](a map[K]V) string {
t := expect_map(a)
dump(t)
return '${t}'
}
fn expect_map[K, V](a map[K]V) map[K]V {
return a
}
fn main() {
a := { 'a': 1 }
b := { 1: 'a' }
assert generic1(a) == "{'a': 1}"
assert generic1(b) == "{1: 'a'}"
assert generic2(a) == "{'a': 1}"
assert generic2(b) == "{1: 'a'}"
}
[.\\tt1.v:3] t: {'a': 1}
[.\\tt1.v:3] t: {1: 'a'}
[.\\tt1.v:9] t: {'a': 1}
[.\\tt1.v:9] t: {1: 'a'}
```
=> checker: fix generic fn with generic fn call returning generic map (fix #20106)

vlib/v/gen/c/utils.v, vlib/v/tests/anon_fn_test.v
1. Fixed #20163 
2. Add tests.
```v
import net
fn main() {
mut conn := &net.TcpConn{}
a := 1
t := spawn fn [a] (mut conn net.TcpConn) int {
return a
}(mut conn)
println(t.wait())
}
```
outputs:
```
1
```
=> cgen: fix wrong cname of anon fn(fix #20163)

vlib/v/gen/c/cgen.v, vlib/v/tests/match_smartcast_test.v
1. Fixed #20167
2. Add tests.
```v
import x.json2
type Foo = f64 | int | string
fn f(j map[string]json2.Any) {
println(j['name'] or { return })
assert (j['name'] or { return } as string) == 'foo'
}
struct Bar {
foo Foo
}
fn g(bar Bar) {
f({
'name':  json2.Any('foo')
'value': match bar.foo {
string { bar.foo }
int { bar.foo }
f64 { bar.foo }
}
})
}
fn main() {
g(Bar{
foo: Foo(42)
})
}
```
outputs:
```
foo
```
=> cgen: fix smartcast for struct fields(fix #20167)

vlib/v/help/build/build-c.txt
Help for the `-gc` option was a bit out of date.  Hopefully this corrects that problem.
=> help: Fix gc help

vlib/v/ast/table.v, vlib/v/ast/types.v, vlib/v/checker/tests/fn_call_arg_array_mismatch_err.out, vlib/v/checker/tests/fn_call_arg_array_mismatch_err.vv
1. Fixed #20172 
2. Add tests.
```v
fn foo(mut arr []int) {
bar(mut arr)
}
fn bar(mut arr [][]int) {
}
fn main() {
mut arr := [1, 2, 3]
foo(mut arr)
}
```
outputs:
```
a.v:2:10: error: cannot use `&[]int` as `&[][]int` in argument 1 to `bar`
1 | fn foo(mut arr []int) {
2 |     bar(mut arr)
|             ~~~~~
3 | }
4 |
```
=> ast: fix fn/method mut array args dimension mismatch check(fix #20172)

vlib/net/net_windows.c.v
Following this post: [forum_discuss](https://github.com/vlang/v/discussions/20174)
It was not possible to use or compile code containing calls to the "_net.unix_" library on a **Windows environment** ( in my case, Windows 10). The errors encountered were:
**v/vlib/net/unix/stream.c.v:73:54: error: constant 'net.msg_nosignal' is private**
`C.photon_send(c.sock.handle, ptr, remaining, net.msg_nosignal, c.write_timeout)`
**v/vlib/net/unix/stream.c.v:75:47: error: constant 'net.msg_nosignal' is private**
`C.send(c.sock.handle, ptr, remaining, net.msg_nosignal)`
**v/vlib/net/unix/stream.c.v:380:47: error: constant 'net.fionbio' is private**
`net.socket_error(C.ioctlsocket(handle, net.fionbio, &t))!`
**v/vlib/net/unix/stream.c.v:493:47: error: constant 'net.fionbio' is private** …
=> net: fix windows constants to make them public for net.unix usage

examples/gg/arcs_and_slices.v, vlib/gg/draw.c.v
Before this PR (using a transparent color instead of black):
After this PR:
=> gg: fix overlapping slices in `draw_slice_filled()`

vlib/v/parser/parse_type.v, vlib/v/tests/thread_returns_test.v
1. Implement #19281 
2. Add tests.
```v
struct Foo {
mut:
field1 thread !int
field2 thread ?int
field3 thread (int, int)
}
fn Foo.new() Foo {
mut foo := Foo{
field1: spawn get_error()
field2: spawn get_none()
field3: spawn get_multi_returns()
}
return foo
}
fn (mut foo Foo) bar() {
if _ := foo.field1.wait() {
assert false
}
if _ := foo.field2.wait() {
assert false
}
a, b := foo.field3.wait()
assert a == 1 && b == 2
}
fn get_error() !int {
return error('error')
}
fn get_none() ?int {
return none
}
fn get_multi_returns() (int, int) {
return 1, 2
}
mut foo := Foo.new()
foo.bar()
}
```
=> parser: implement thread returns result and multi_returns(fix #19281)

vlib/json/json_encode_recursive_ptr_test.v, vlib/v/checker/struct.v, vlib/v/checker/tests/struct_field_init_option_ref_err.out, vlib/v/checker/tests/struct_field_init_option_ref_err.vv
1. Fixed #19555
2. Add tests.
```v
module main
import rand
struct MyType {
foo string
}
struct TypeWithOption {
maybe ?&MyType
}
fn main() {
println("trying...")
x := rand.int()
ptr := if x > 0 {
?MyType(MyType{foo:"bar"})
} else {
?MyType(none)
}
container := TypeWithOption{maybe: ptr} // Expects ?&MyType, not ?MyType. Sema doesn't catch this, I guess.
println("success!")
println(container)
}
```
outputs:
```
a.v:22:30: error: cannot assign to field `maybe`: expected a pointer `?&MyType`, but got `?MyType`
20 |     }
21 | 
22 |     container := TypeWithOption{maybe: ptr} // Expects ?&MyType, not ?MyType. Sema doesn't catch this, I guess.
|                                 ~~~~~~~~~~
23 |     println("success!")
24 |     println(container)
```
```
=> checker: fix incorrect checks when struct fields are ref and option type(fix #19555)

vlib/builtin/string_int_test.v, vlib/builtin/string_interpolation.v, vlib/v/checker/str.v, vlib/v/gen/c/auto_str_methods.v, vlib/v/gen/c/str_intp.v, vlib/v/gen/js/auto_str_methods.v
**Wath's inside**
New flag for `string interpolation`
The new `r`,`R` flags repeat the string passed in the string_interpolation the number of times indicated.
Example:
```v
fn main(){
a:= "pippo"
println("${'*':10r} TEXT WITH STARTS ${'*':10r}")
println("${a:10r}")
println("${a:10R}")
}
```
Output:
```
********** TEXT WITH STARTS **********
pippopippopippopippopippopippopippopippopippopippo
PIPPOPIPPOPIPPOPIPPOPIPPOPIPPOPIPPOPIPPOPIPPOPIPPO
```
=> all: add `r` and `R` switches for repeating in string interpolation, `'${"abc":3r}'`  == 'abcabcabc'

vlib/v/gen/c/str_intp.v, vlib/v/tests/string_interpolation_test.v
1. Fixed #20199 
2. Add tests.
```v
module main
fn main() {
test := 'test'
println("$test\x00$test")
println("$test\x00$test".len)
println("$test\x00$test".bytes())
}
```
outputs:
```
testtest
9
[116, 101, 115, 116, 0, 116, 101, 115, 116]
```
=> cgen: fix string interp with zero characters(fix #20199)

vlib/v/gen/c/auto_eq_methods.v, vlib/v/gen/c/cgen.v, vlib/v/tests/interface_eq_methods_with_option_and_ref_test.v
1. Fixed #19441
2. Add tests.
```v
pub interface NodeInterface {
mut:
node_name string
}
pub interface Element {
NodeInterface
mut:
tag_name string
}
pub struct Node {
pub mut:
node_name string
}
pub struct HTMLElement {
Node
pub mut:
tag_name string
}
pub struct HTMLInputElement {
// removing either one of these embedded structs lets the code compile
HTMLElement
PopoverInvokerElement
pub mut:
value string
}
pub struct PopoverInvokerElement {
pub mut:
// changing this field to `&Element` lets the code compile
popover_target_element ?&Element
popover_target_action  string
}
fn main() {
mut arr := []&NodeInterface{}
arr << &HTMLElement{}
arr << &HTMLElement{}
// removing this comparison lets the code compile
println(arr[0] == arr[1])
}
```
outputs:
```
true
```
=> cgen: fix interface eq method with option and ref(fix #19441)

vlib/v/fmt/tests/enum_decl_with_comment_expected.vv, vlib/v/fmt/tests/enum_decl_with_comment_input.vv, vlib/v/fmt/tests/interface_decl_with_comment_expected.vv, vlib/v/fmt/tests/interface_decl_with_comment_input.vv, vlib/v/parser/parser.v, vlib/v/parser/struct.v
This PR fix formatting enum and interface decl with comments (related #20202).
- Fix formatting enum and interface decl with comments.
- Add tests.
```v
enum ABC  // enum ABC
{
// aaa
aaa
}
interface Abc   // interface Abc
{
a int
get_info() string
}
```
fmt to:
```v
enum ABC { // enum ABC
// aaa
aaa
}
interface Abc { // interface Abc
a int
get_info() string
}
```
=> parser: fix formatting enum and interface decl with comments (related #20202)

vlib/v/gen/c/array.v, vlib/v/tests/array_insert_variadic_arg_variable_test.v
This PR fix array insert variadic arg variable (fix #20213).
- Fix array insert variadic arg variable.
- Add test.
```v
fn foo(args ...string) []string {
mut v := ['a']
v.insert(1, ['b'])
v.insert(1, args)
return v
}
fn main() {
ret := foo('b')
println(ret)
assert ret == ['a', 'b', 'b']
}
['a', 'b', 'b']
```
=> cgen: fix array insert variadic arg variable (fix #20213)

vlib/builtin/js/string.js.v
Makes the usage of the attribute uniform with `trim_right` in `string.v` and `trim_left` in `string.js.v` / `string.v`
=> builtin: add `@[direct_array_access]` to js string trim_right method

vlib/v/gen/c/infix.v, vlib/v/tests/infix_expr_in_mut_receiver_method_test.v
This PR fix infix expr in method of mut receiver variable  (fix #20220).
- Fix infix expr in method of mut receiver variable.
- Add test.
```v
@[heap]
struct UI {}
pub fn (ui &UI) draw_rect() {
println('[]')
}
@[heap]
pub interface Node {
id u64
draw()
mut:
ui &UI
init(ui &UI) !
}
@[heap]
pub struct Item {
pub:
id u64 = 1
mut:
ui   &UI = unsafe { nil }
body []&Node
}
pub fn (mut i Item) init(ui &UI) ! {
assert i != unsafe { nil } // This assert generates a C gen error
i.ui = ui
for mut child in i.body {
child.init(ui)!
}
}
pub fn (i &Item) draw() {
assert i != unsafe { nil }
for child in i.body {
child.draw()
}
}
@[heap]
pub struct Rectangle {
Item
pub mut:
field f32
}
pub fn (r &Rectangle) draw() {
assert r != unsafe { nil }
r.ui.draw_rect()
r.Item.draw()
}
fn main() {
ui := &UI{}
mut …
```
=> cgen: fix infix expr in method of mut receiver variable  (fix #20220)

vlib/v/gen/c/auto_eq_methods.v, vlib/v/tests/interface_eq_methods_with_option_and_ref_test.v
1. Fixed #20212
2. Add tests.
```v
pub interface Iface {}
// test ref
pub struct Derived {
field1 &Iface = unsafe { nil }
}
// test option and ref
pub struct Struct {
field2 ?&Iface
}
// test non-ref and embeded
pub struct Mixin {
Derived
Struct
field3 Iface = Iface(1)
field4 ?Iface
}
fn main() {
mut arr := []&Iface{}
arr << &Derived{}
arr << &Derived{}
assert arr[0] == arr[1]
s1 := Iface(Struct{})
s2 := Iface(Struct{})
assert s1 == s2
i1 := Iface(Mixin{})
i2 := Iface(Mixin{})
assert i1 == i2
}
```
outputs:
```
passed
```
=> cgen: fix comparing interface values of structs containing optional ref interface fields(fix #20212)

vlib/v/checker/fn.v, vlib/v/tests/generics_array_method_call_with_multi_types_test.v
This PR fix generic array method call with multi-types (fix #20230).
- Fix generic array method call with multi-types.
- Add test.
```v
pub type EventListener[T] = fn (T) !
pub type Check[T] = fn (T) bool
pub struct EventController[T] {
mut:
id        int
listeners map[int]EventListener[T]
}
fn (mut ec EventController[T]) generate_id() int {
return ec.id++
}
@[params]
pub struct EmitOptions {
pub:
error_handler ?fn (int, IError)
}
pub fn (mut ec EventController[T]) emit(e T, options EmitOptions) {
if ec.listeners.len == 1 {
f := ec.listeners.values()[0]
f(e) or {
if g := options.error_handler {
g(0, err)
}
}
return
}
}
struct Foo {}
struct Bar {}
fn main() {
foo := EventController[Foo]{}
println(foo)
assert foo.id == 0
bar := EventController[Bar]{}
println(bar)
assert bar.id == 0
}
PS …
```
=> checker: fix generic array method call with multi-types (fix #20230)

vlib/js/dom/dom.js.v
Example:
```v
// v -b js_browser .
import js.dom
fn main() {
document := dom.document
mut h1 := document.body.querySelector('main h1'.str)?
list := document.body.querySelectorAll('ul li'.str)
h1.innerText = 'Hello, world!'.str
list.forEach(fn (elem JS.HTMLElement, num JS.Number, list JS.NodeList) {
JS.console.log(elem)
}, false)
}
```
=> js.dom: add querySelector[All] and NodeList

vlib/x/json2/encoder.v, vlib/x/json2/encoder_test.v
=> x.json2: fix encoding of 💀🐈 etc emojis (fix #20243)

cmd/tools/vtest-self.v, vlib/db/pg/pg.c.v, vlib/db/pg/pg_test.v
Closes: #20020 
- Fixes an invalid memory access caused by `.vstring()` reusing memory
- Adds a test to ensure returned memory is valid
- Prevents test from running in CI due to postgres not being installed
=> db.pg: Fix invalid memory access in res_to_rows

vlib/x/vweb/README.md, vlib/x/vweb/context.v, vlib/x/vweb/sse/README.md, vlib/x/vweb/sse/sse.v, vlib/x/vweb/sse/sse_test.v, vlib/x/vweb/vweb.v
This pr fixes the fsanitize CI from failing occasionally.
The documentation on the usage of `Context.takeover_conn` is improved to prevent users from making the same mistake.
=> x.vweb: fix fsanitize-address test for SSE and improve documentation on the usage of `takeover_conn`

vlib/v/gen/c/spawn_and_go.v, vlib/v/tests/go_call_fn_with_anon_fn_array_arg_test.v
1. Fixed #19425 
2. Add tests.
```v
module main
import time
import io
import os
interface Message {
a int
}
struct Impl {
a int
}
type HookFunc = fn (Message) ?Message
struct TestStruct {
fns []HookFunc
}
fn (ts TestStruct) run(mut writer io.Writer) {
spawn handle_fns(ts.fns, mut writer)
}
fn handle_fns(fns []HookFunc, mut writer io.Writer) {
mut message := Message(Impl{a: 1})
for f in fns {
message = f(message) or { continue }
}
println(message)
}
fn main() {
stack := TestStruct{
fns: [
fn (m Message) ?Message {
return Message(Impl{a: m.a + 1})
},
fn (m Message) ?Message {
return none
}
]
}
stack.run(mut os.stdout())
time.sleep(2 * time.second)
}
```
outputs:
```
Message(Impl{
a: 2
})
```
=> cgen: fix gen wrong for thread wrappers, when spawn with anon-fn array args(fix #19425)

vlib/v/checker/containers.v, vlib/v/checker/tests/array_map_elements_ref_fields_uninitialized_err.out
1. Close #20245 
2. Remove unnecessary notifications
3. Handle with the implicit creation of map instances later
=> checker: remove unnecessary struct ref field initialization checks and notifications at map initializing(fix #20245)

vlib/v/gen/c/cgen.v, vlib/v/tests/fixed_array_return_decl_test.v
Fix #20261
```V
import runtime { is_big_endian }
union F32A {
float f32
value [4]u8
}
union F64A {
float f64
value [8]u8
}
pub fn read_f32le(bytes [4]u8) f32 {
if is_big_endian() {
bytes_rev := [4]u8{init: bytes[3 - index]}
float := F32A{value: bytes_rev}
unsafe {
return float.float
}
} else {
float := F32A{value: bytes}
unsafe {
return float.float
}
}
}
pub fn write_f32le(float f32) [4]u8 {
float_copy := F32A{float: float}
if is_big_endian() {
unsafe {
return [4]u8{init: float_copy.value[3 - index]}
}
} else {
unsafe {
return float_copy.value
}
}
}
fn main() {
a := [4]u8{}
b := write_f32le(0.0)
assert a == b
mut a2 := [4]u8{}
a2 = [u8(205),204,204,61]!
b2 := write_f32le(0.1)
assert a2 == b2
}
```
=> cgen: fix fixed array return when returning fixed array initialization

vlib/v/ast/table.v, vlib/v/checker/check_types.v, vlib/v/checker/checker.v, vlib/v/checker/fn.v, vlib/v/checker/tests/map_index_reference_value.out, vlib/v/checker/tests/map_index_reference_value.vv, vlib/v/gen/c/cmain.v, vlib/v/gen/c/orm.v, vlib/v/markused/markused.v, vlib/v/markused/walker.v
1. Finish any remaining work: https://github.com/vlang/v/pull/20251#issuecomment-1867390542
2. Recursively checks whether the map value contains a pointer.
3. Add tests.
```v
field &int
}
fn main() {
m := map[string][]Struct{}
a := m['key']
println(a)
}
```
outputs:
```
a.v:7:8: notice: accessing map value that contain pointers requires an `or {}` block outside `unsafe`
6 |     m := map[string][]Struct{}
7 |     a := m['key']
|           ~~~~~~~
8 |     println(a)
9 | }
[]
```
=> ast, checker: improved accessing map value that contain pointers requires an `or {}` block

vlib/v/parser/parser.v, vlib/v/tests/fn_call_with_newline_opening_brace_test.v
This PR fix fn call with newline opening brace (fix #20258).
- Fix fn call with newline opening brace.
- Add test.
```v
// vfmt off
struct Address
{
pub:
street string
city string
state string
zip int
}
fn main() 
{
println(initialized_address)
assert true
}
struct AddressConfig {
pub:
street string = '1234 Default St'
city   string = 'Your Favorite City'
state  string = 'Could Be Any'
zip    int    = 42 
}
fn new_address(cfg AddressConfig) &Address
{
return &Address
{
street:cfg.street
city:cfg.city
state:cfg.state
zip:cfg.zip
}
}
const (
default_address     = new_address(AddressConfig{})
initialized_address = new_address
(
street: '0987 tluafeD tS'
city: 'ytiC etirovaF rouY'
state: 'ynA eB dluoC'
zip: 24
)
)
fn (a Address) str() string {
return 'Address.str(): $a.street, $a.city, …
```
=> parser: fix fn call with newline opening brace (fix #20258)

vlib/v/gen/c/cgen.v, vlib/v/tests/match_with_return_result_test.v
Fix #20260 (it requires fix for #20169 to be applied to work the test case below)
```V
import x.json2
fn maybe_map_map[T, U, X, Y](m map[T]U, f fn(T, U) !(X, Y) ) !map[X]Y {
mut r := map[X]Y{}
nk, nv := f(k, v)!
r[nk] = nv
}
return r
}
type Snowflake = int
struct User {
id Snowflake
name string
}
fn User.parse(j json2.Any) !User {
match j {
map[string]json2.Any {
return User{
id: j['id']! as int
name: j['name']! as string
}
}
else {
return error('expected user to be object, got ${j.type_name()}')
}
}
}
struct Resolved {
users ?map[Snowflake]User
}
fn Resolved.parse(j json2.Any) !Resolved {
match j {
map[string]json2.Any {
return Resolved{
users: if m := j['users'] {
maybe_map_map[string, json2.Any, Snowflake, User](m as map[string]json2.Any, fn (k string, v json2.Any) …
```
=> cgen: fix function generated code when returning from match

vlib/v/gen/c/array.v, vlib/v/tests/in_expression_test.v
1. Fixed #20268
2. Add tests.
```v
struct At {
mut:
list_lien	[]&At
}
fn (mut at At) li(mut at_li &At) {
if at_li !in at.list_lien{	
}
}
fn main() {
mut at_1 := At{[]}
mut at_2 := At{[]}
at_1.li(mut &at_2)
}
```
outputs:
```
passed
```
=> cgen: fix in expression with mut and ref(fix #20268)

vlib/v/parser/parser.v, vlib/v/tests/fn_call_with_newline_opening_brace_test.v
This PR fix parse_vet_file() with vfmt off/on flag.
- Fix parse_vet_file() with vfmt off/on flag.
- Add test.
```v
// vfmt off
struct Address  
{
pub:
street string
city string
state string
zip int  
}
fn test_fn_call_with_newline_opening_brace()  
{
println(initialized_address) 
assert true 
}
struct AddressConfig { 
pub:
street string = '1234 Default St' 
city   string = 'Your Favorite City' 
state  string = 'Could Be Any' 
zip    int    = 42 
}
fn new_address(cfg AddressConfig) &Address 
{
return &Address 
{
street:cfg.street
city:cfg.city
state:cfg.state
zip:cfg.zip
}
}
const (
default_address     = new_address(AddressConfig{}) 
initialized_address = new_address 
(
street: '0987 tluafeD tS'
city: 'ytiC etirovaF rouY'
state: 'ynA eB dluoC'
zip: 24
)
)
// vfmt on
fn (a Address) str() …
```
=> parser: fix parse_vet_file() with vfmt off/on flag

vlib/v/checker/check_types.v, vlib/v/checker/tests/fn_call_arg_fn_mismatch_err.out, vlib/v/checker/tests/fn_call_arg_fn_mismatch_err.vv
1. Fixed #19325 
2. Add tests.
```v
type Response = int | string
fn my_resp() string {
return 'hello'
}
fn event(cb fn () Response) {
resp := cb()
dump(resp is string)
}
event(my_resp)
```
outputs:
```
a.v:12:7: error: cannot use `fn () string` as `fn () Response` in argument 1 to `event`
10 | }
11 | 
12 | event(my_resp)
|       ~~~~~~~
13 | 
14 |
```
=> checker: fix mismatch checking when a function returns sumtype as an argument(fix #19325)

vlib/v/checker/if.v, vlib/v/gen/c/cgen.v, vlib/v/tests/option_cast_test.v
Fix #18790
```V
struct Test {
a int
}
fn main() {
a := ?int(1)
if a != none {
dump(a)
}
b := ?Test{
a: 1
}
if b != none {
dump(b)
}
}
```
=> v: auto option wrapping when comparing != none

vlib/v/gen/c/str.v, vlib/v/gen/c/testdata/gen_expr_to_string_with_call_and_return_ref.out, vlib/v/gen/c/testdata/gen_expr_to_string_with_call_and_return_ref.vv
1. Fixed #20282 
2. Add tests.
```v
struct Abc {
s string
}
fn str_gen_with_call_and_return_ref() &Abc {
dump('It should be printed only once')
return &Abc{}
}
fn main() {
println(str_gen_with_call_and_return_ref())
}
```
outputs:
```
[a.v:6] 'It should be printed only once': It should be printed only once
&Abc{
s: ''
}
```
=> cgen: fix generating callexpr to string is actually called twice(fix #20282)

vlib/v/gen/c/cgen.v, vlib/v/tests/const_fixed_array_of_string_value_msvc_test.v
1. Fixed #20287 
2. Add tests.
```v
const escaped_chars = [(r'\b'), (r'\f'), (r'\n'), (r'\r'), (r'\t')]!
```
v -cc msvc -o a.c a.v:
```c
Array_fixed_string_5 _const_main__escaped_chars; // inited later
```
......
```
// Initializations of consts for module main
_const_main__escaped_chars[0] = (_SLIT("\\b"));
_const_main__escaped_chars[1] = (_SLIT("\\f"));
_const_main__escaped_chars[2] = (_SLIT("\\n"));
_const_main__escaped_chars[3] = (_SLIT("\\r"));
_const_main__escaped_chars[4] = (_SLIT("\\t"));
```
=> cgen: fix initialization of const string arrays on msvc(fix #20287)

doc/docs.md
The @[nonull] attribute is no longer used and is replaced by using an option type. https://github.com/vlang/v/pull/19379
=> docs: update null convention in ORM example

vlib/builtin/string_test.v, vlib/v/scanner/scanner.v
- scanner: fix literal strings containing \\ followed directly by a newline (fix #20291)
- small optimisation: change `x % 2 == 0` to `x & 1 == 0`
=> scanner: fix backslashes followed directly by newline in string literals (fix #20291)

vlib/v/gen/c/infix.v, vlib/v/tests/if_expression_test.v
1. Fixed #20300
2. Add tests.
```v
module main
import os
type Data = map[string]map[u32]map[string]u32
fn main() {
content := os.read_file('input.txt') or {
eprintln('Could not read file: ${err}')
return
}
seeds, data := setup(content)
result_one := part_one(seeds, data)
print('Part one: ${result_one}')
}
fn setup(content string) ([]u32, Data) {
mut seeds := []u32{}
mut data := Data(map[string]map[u32]map[string]u32{})
lines := content.split_into_lines()
for i, line in lines {
if line.starts_with('seeds:') {
seeds = line.split(' ').filter(it.u32() != 0).map(it.u32())
} else if ':' in line.split('') {
key := line.split(' ')[0].trim(' ')
for map_line in lines[i + 1..] {
if map_line == '' {
break
}
values := map_line.split(' ').map(it.u32())
data[key][values[1]] = {
'destination': values[0] …
```
=> cgen: fix code generation when 'in array init' is in the if-conds(fix#20300)

vlib/v/checker/fn.v
This PR cleanup method_call().
=> checker: cleanup method_call()

vlib/v/pref/pref.c.v
Disable the `-macosx-version-min` clang flag which is poorly documented, but which seems to affect STL (and some other headers) and also which runtime is linked against.
This flag causes problems (on my Intel-based mac, at least), such as
* use of `C.environ` causes segfault
* `os.Process._spawn()` segfaults
This results in total breakage of some v commands, including `v run` and `v test`. E.g., `v run` segfaults as follows:
```
signal 11: segmentation fault
0   libsystem_platform.dylib            0x00007ff8009cf37d _sigtramp + 29
1   ???                                 0x0000000000000000 0x0 + 0
2   v                                   0x000000010bd3e5db os__Process__spawn + 155
3   v                                   0x000000010bd3e503 os__Process_wait + 35
4   v …
```
=> pref: disable -macosx-version-min clang flag by default

vlib/x/vweb/assets/README.md, vlib/x/vweb/assets/assets.v, vlib/x/vweb/assets/assets_test.v
This pr reimplements the old assets module for `x.vweb`.
You can use this module to minify CSS and Javscript files,
combine them into a single file and to make sure the asset you're using exists.
See the README.md file for the usage.
=> x.vweb.assets: reimplement assets module for x.vweb

examples/viewer/view.v, examples/viewer/zip_container.v, vlib/v/gen/c/fn.v
Fixed #20306
The cause of this issue is that when compiled using the `-g` flag, the `line info` generated in the code does not break a line with the closure's calling code `_t1()`.
```v
x := 1
fn [x] () {
println(2)
}()
```
original outputs:
```c
#line 1 "/usr/local/v/temp/a.v"
int x = 1;
void (*_t1) () = 	__closure_create(anon_fn_e61da51904666690__18, (struct _V_anon_fn_e61da51904666690__18_Ctx*) memdup_uncollectable(&(struct _V_anon_fn_e61da51904666690__18_Ctx){.x = x,
}, sizeof(struct _V_anon_fn_e61da51904666690__18_Ctx)));
#line 5 "/usr/local/v/temp/a.v"_t1();
}
```
now outputs:
```c
#line 1 "/usr/local/v/temp/a.v"
int x = 1;
void (*_t1) () = 	__closure_create(anon_fn_e61da51904666690__18, (struct _V_anon_fn_e61da51904666690__18_Ctx*) memdup_uncollectable(&(struct …
```
=> cgen: fix missing line breaks in generated code with closure IIFE, when compiled with '-g'(fix #20306)

vlib/orm/orm.v
While most SQL databases support "!=" for not equal, "<>" is the standard operator.
=> orm: fix "not equal" operator

vlib/v/checker/assign.v, vlib/v/checker/tests/assign_type_mismatch_with_generics_err.out, vlib/v/checker/tests/assign_type_mismatch_with_generics_err.vv, vlib/v/tests/generics_chans_select_test.v
1. Fixed #20298
2. Add tests.
This issue(20298) contains several issues. This PR starts with a simple solution to a type checking problem.
Then split a new issue, and resolve it.
The new issue is a `CallExpr` may have 2 `or block{}` :
```v
type Fn = fn ()
method ?Fn
}
fn main() {
s := Struct {
method: fn () {}
}
s.method or_1 {} (args...) or_2 {}
}
```
or_1 {}   for  ?Fn
or_2 {}  for  method call.
=> checker: fix type mismatch checking for assignments with generics(fix#20298)

vlib/v/ast/scope.v, vlib/v/checker/checker.v, vlib/v/checker/comptime.v, vlib/v/checker/for.v, vlib/v/checker/if.v, vlib/v/checker/infix.v, vlib/v/checker/match.v, vlib/v/comptime/comptimeinfo.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/comptime.v, vlib/v/gen/c/infix.v, vlib/v/tests/comptime_var_is_check_test.v
Fix #20312
```v
type TestSum = string | int
fn gen[T, R](sum T) R {
$if T is $sumtype {
$for v in sum.variants {
if sum is v {
dump(sum)
$if sum is R {
return sum
}
}
}
}
return R{}
}
fn main() {
dump(gen[TestSum, string](TestSum('foo')))
}
```
=> v: improved comptime var checking with `is` operator and smartcasting

vlib/sokol/c/declaration.c.v
It needs this include path in order to find `X11/Xlib.h`.
This was tested on OpenBSD/amd64 with a local X11 display using various programs in `examples/`.
=> sokol: Fix build on OpenBSD

vlib/db/pg/README.md, vlib/db/pg/pg.c.v
Whenever it is compiled on Windows and there are no .dlls in the executable folder, it simply closes with the error code `-1073741515` equivalent to `0xC0000135`.
1. I'm adding to the readme which .dlls are needed.
2. Correcting the flag that is passed to the msvc compiler.
3. Explained where to place libpq if using the msvc compiler.
=> db.pg: fix error with msvc compiler +instructions

vlib/net/tcp.c.v
=> net: support only ip and ip6 in net.tcp_listener

vlib/v/gen/c/fn.v, vlib/v/tests/map_clear_test.v
Fix #20338
Missing map method .clear() translation to map_clear() call.
=> cgen: add missing clear method

vlib/v/tests/go_array_wait_test.v
Fix compiler syntax error.  At some point in time this syntax might have been legal, but now it is neither legal nor required.
=> vlib: fix syntax error in go_array_wait_test.v

vlib/v/gen/c/array.v, vlib/v/gen/c/dumpexpr.v, vlib/v/tests/array_fixed_ptr_test.v
Fix #20343 
```v
a := &[2]u8{}
dump(a)
assert a.len == 2
}
fn test_empty() {
_ := &[2]u8{}
assert true
}
```
=> cgen: fix array fixed initialization with prefixexpr &

vlib/v/checker/assign.v, vlib/v/tests/assign_type_checking_with_generics_test.v
Close #20335
This PR is a patch to PR #20327, temporarily relaxing the mismatch check on generic types.   :)
1. The test case of the original PR 20327 continues to be valid
2. `discord.v` on the submitted 94d5563 can already be compiled properly.
At present, the type mismatch check on assignment is too lenient for generics, and there will be some missed cases.  I have written it down in a memo and arranged time for detailed handling
=> checker: fix being too strict with generics in assignment type mismatch checking

vlib/v/gen/c/cgen.v, vlib/v/tests/option_init_ptr_test.v, vlib/v/tests/option_ptr_init_empty_test.v
Fix #20345
```V
pub struct Test {
a int = 10
b int = 5
}
pub struct ABC {
test ?&Test
}
abc := ABC{
test: &Test{}
}
if ttt := abc.test {
assert ttt.a == 10
assert ttt.b == 5
} else {
assert false
}
}
```
=> cgen: fix option initialization with default struct initialization to not be `none`

vlib/v/gen/c/auto_eq_methods.v, vlib/v/gen/c/auto_str_methods.v, vlib/v/tests/option_arr_auto_str_test.v
Fix #20350
```V
import x.json2
pub fn maybe_map[T, X](a []T, f fn (T) !X) ![]X {
mut r := []X{cap: a.len}
for v in a {
r << f(v)!
}
return r
}
pub enum ApplicationCommandOptionType {
sub_command       = 1
sub_command_group
string
integer
boolean
user
channel
role
mentionable
number
attachment
}
pub struct ApplicationCommandOption {
pub:
typ         ApplicationCommandOptionType @[required]
name        string                       @[required]
description string                       @[required]
options     ?[]ApplicationCommandOption
}
pub fn ApplicationCommandOption.parse(j json2.Any) !ApplicationCommandOption {
match j {
map[string]json2.Any {
return ApplicationCommandOption{
typ: unsafe { ApplicationCommandOptionType(j['type']!.int()) }
name: j['name']! as string
description: …
```
=> cgen: fix auto str for arr options with possible circular reference

vlib/v/pref/pref.c.v
Implements https://github.com/vlang/v/issues/20355
=> v: support `-?` as alias to `-help`

vlib/v/gen/native/tests/native_test.v
Just like on FreeBSD, skip the native tests for now.
=> tests: Also skip native tests on OpenBSD

vlib/v/util/diff/diff.v
OpenBSD's diff doesn't have the long option names like FreeBSD does.
=> diff: Add support for OpenBSD's diff implementation

vlib/v/checker/assign.v, vlib/v/checker/checker.v, vlib/v/checker/containers.v, vlib/v/checker/fn.v, vlib/v/checker/if.v, vlib/v/checker/infix.v, vlib/v/checker/match.v, vlib/v/checker/struct.v
Renames `check_expr_opt_call` function to match the behavior since only the `.result` flag is cleared.
=> checker: rename `check_expr_opt_call` to `check_expr_result_call`

vlib/v/gen/c/cgen.v, vlib/v/tests/return_fixed_array_test.v
1. Fixed #20366
2. Add tests.
```v
pub fn foo(mut fixed [3]int) [3]int {
return fixed
}
fn main() {
mut fixed := [3]int{}
mut res := foo(mut fixed)
println(res)
}
```
outputs:
```
[0, 0, 0]
```
=> cgen: fix code generation when the function returns mut fixed array(fix #20366)

vlib/v/checker/fn.v, vlib/v/tests/generics_method_with_multi_types_test.v
1. Fixed #20330 
2. Add tests.
```v
module main
struct Test[T] {}
fn (t Test[T]) abc[U]() {
t.xyz[U]()
}
fn (t Test[T]) xyz[U]() {}
fn main() {
t := Test[string]{}
t.abc[f32]()
t.abc[u32]()
}
```
outputs:
```
passed
```
=> checker: fix generic method calls with multi generic types (fix #20330)

vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/tests/return_fixed_array_test.v
1. Fixed #20373 
2. Add tests.
```v
pub fn foo(fixed [3]int) ![3]int {
return fixed
}
fn main() {
mut fixed := [3]int{}
mut res := foo(fixed) or {
return
}
println(res)
}
```
```v
pub fn foo(fixed [3]int) ?[3]int {
return fixed
}
fn main() {
mut fixed := [3]int{}
mut res := foo(fixed) or {
return
}
println(res)
}
```
outputs:
```
[0, 0, 0]
```
=> cgen: fix code generation when fn returns option/result fixed array(fix #20373)

vlib/v/gen/c/array.v, vlib/v/gen/c/struct.v, vlib/v/tests/struct_init_with_fixed_array_field_test.v
1. Fixed #20361
2. Both the cases with and without generics are fixed
3. Add tests.
```v
struct Builder {
mut:
buf [3]int
}
pub fn new_builder(mut fixed [3]int) !Builder {
return Builder{fixed}
}
fn main() {
mut fixed := [3]int{}
mut sb := new_builder(mut fixed) or {
return
}
println(sb)
}
```
outputs:
```
[0, 0, 0]
```
```v
struct Builder[T] {
mut:
buf T
}
pub fn new_builder[F](mut fixed_array F) !Builder[F] {
$if F is $array_fixed {
return Builder[F]{fixed_array}
} $else {
return error('fixed_buf need be a fixed array')
}
}
fn main() {
mut fixed := [3]u8{}
mut sb := new_builder(mut fixed) or {
eprintln(err)
return
}
println(sb)
}
```
outputs:
```
Builder[[3]u8]{
buf: [0, 0, 0]
}
```
=> cgen: fix returns struct with mut fixed array init(with/without generics)(fix #20361)

vlib/picoev/picoev.v, vlib/x/vweb/tests/large_payload_test.v, vlib/x/vweb/vweb.v
fixes #20323 
This pr adds a missing call to the raw callback in picoev on a timeout event. 
When a timeout occurs `x.vweb` sends a HTTP 408 Request Timeout response.
This pr probably also fixes the flakiness issues in the `large_payload_test.v`, but I'll check that in some time
=> x.vweb, picoev: fix timeout event

vlib/v/checker/fn.v, vlib/v/checker/tests/unknown_method.out, vlib/v/checker/tests/unknown_method.vv
1. Close #20364 
2. Add tests.
```v
struct Builder[T] {
mut:
buf T
}
pub fn new_builder[F](mut fixed_array F) !Builder[F] {
$if F is $array_fixed {
return Builder[F]{fixed_array}
} $else {
return error('fixed_buf need be a fixed array')
}
}
fn main() {
mut fixed := [3]u8{}
mut sb := new_builder(mut fixed) or {
return
}
sb.write_string("")
}
```
outputs:
```
a.v:21:5: error: unknown method or field: `Builder[F].write_string`
19 |     }
20 |     // println(sb)
21 |     sb.write_string("")
|        ~~~~~~~~~~~~~~~~
22 | }
23 |
If the code of your project is in multiple files, try with `v .` instead of `v a.v`
```
=> checker: optimize error messages for method not exists(fix #20364)

vlib/v/checker/fn.v, vlib/v/checker/tests/generics_method_receiver_type_err_b.out, vlib/v/checker/tests/generics_method_receiver_type_err_b.vv
1. Close #20362 
2. Add tests.
```v
struct Builder[T] {}
pub fn new_builder[F](mut fixed_array F) !Builder[F] {
}
pub fn (mut b Builder) write_string(s string) {
}
```
outputs:
```
a.v:6:15: error: generic struct `Builder` in fn declaration must specify the generic type names, e.g. Builder[T]
4 | }
5 | 
6 | pub fn (mut b Builder) write_string(s string) {
|               ~~~~~~~
7 | }
8 |
```
=> checker: optimize error messages for must specify the generic type names(fix #20362)

vlib/v/checker/checker.v, vlib/v/checker/tests/map_index_or_block_type_mismatch_err.out, vlib/v/checker/tests/map_index_or_block_type_mismatch_err.vv
1. Fixed #20390 
2. Add tests.
```v
fn get_value(m map[string]int, key string) ?int {
return m[key] or { ?int(none) }
}
```
outputs:
```
a.v:3:22: error: `or` block must provide a value of type `int`, not `?int`
1 | // https://github.com/vlang/v/issues/20390
2 | fn get_value(m map[string]int, key string) ?int {
3 |     return m[key] or { ?int(none) }
|                         ~~~~~~~~~
4 | }
5 |
```
=> checker: fix checking got 'none' from or_block of map index(fix #20390)

vlib/sync/mutex_test.v, vlib/sync/rwmutex_test.v, vlib/sync/sync_darwin.c.v, vlib/sync/sync_default.c.v, vlib/sync/sync_windows.c.v
sync: add try_lock support for mutex/rwmutex
=> add try_lock to mutex/rwmutex

vlib/v/gen/c/fn.v, vlib/v/tests/method_call_chain_test.v
1. Fixed #20395 
2. Add tests.
```v
module main
fn main() {
mut path := 'hello/file.txt'
extension := path.split('.').pop()
println(extension)
}
```
outputs:
```
txt
```
=> cgen: fix brackets are asymmetric in chained method calls (fix #20395)

vlib/v/gen/c/assert.v, vlib/v/gen/c/fn.v, vlib/v/tests/comptime_smartcast_assert_test.v
Fix #20396
`assert_stmt()` was changing node.expr.left and node.expr.right inside. 
```V
pub type Any = []Any
| bool
| f32
| f64
| i16
| i64
| i8
| int
| map[string]Any
| string
| u16
| u32
| u64
| u8
ana := Any([Any('')])
name(ana)
match ana {
[]Any {
for i := 0; i < ana.len; i++ {
name(ana[i])
}
}
else {
assert false
}
}
assert true
}
fn name[T](val T) {
$for v in val.variants {
if val is v {
dump(val.str())
$if val is []Any {
assert val.str() == "[Any('')]"
} $else {
assert val.str() == ''
}
dump(val)
}
}
}
```
=> cgen: fix assert expr handling + print with comptime smartcast

vlib/v/checker/fn.v, vlib/v/checker/tests/fn_return_array_sort_err.out, vlib/v/checker/tests/mut_receiver_lit.out, vlib/v/checker/tests/mut_receiver_lit.vv, vlib/v/tests/method_call_chained_test.v
When calling the methods of array/map, the checking that expr cannot be used as mut receiver is missed,
This PR fixes it, as well as adding and modifying test cases.
=> checker: fix checking of expression as mut receiver when calling methods of arrays/maps

vlib/v/checker/containers.v, vlib/v/checker/tests/array_init_element_option_mismatch_err.out, vlib/v/checker/tests/array_init_element_option_mismatch_err.vv
1. Fixed #20409 
2. Add tests.
When the array is initialized, V takes the type of the first element as the type of the array elements, so when the first type is not option, the following elements should not have option either.
```v
import db.pg
@[table: 'demo']
struct Demo {
id int @[primary; sql: serial]
a string
b ?string
}
fn run() ! {
conn := '' // insert own connection string
db := pg.connect_with_conninfo(conn)!
sql db { create table Demo }!
demo := Demo{0, 'a', none}
_ := db.exec_param_many('INSERT INTO demo(a, b) VALUES($1, $2)', [demo.a, demo.b])!
db.close()
}
run() or { panic(err.msg()) }
```
outputs:
```
a.v:15:81: error: cannot use `?string` as `string`, it must be unwrapped first
13 |     sql db { create table Demo }!
14 |     demo := Demo{0, 'a', none}
15 |     _ := …
```
=> checker: fix option mismatch checking on array initializations(fix #20409)

doc/docs.md
Update docs.md provide accurate examples for warning and errors
The current mentioned example is not clear enough the explain the secnario where an warning is displayed and when error is displayed.Hence the PR to update them we clearer example.
=> docs: add `Warnings and declaration errors` section in docs.md

vlib/v/gen/c/fn.v, vlib/v/tests/comptime_deref_or_ref_test.v
Fix #20400
```V
pub struct Association {
price       string
association &Association = unsafe { nil }
}
fn encode_struct[U](a U) {
mut c := 0
$if field.name == 'association' {
c += 1
assert ptr_str(a.$(field.name)) == '0'
} $else {
c += 1
assert ptr_str(a.$(field.name)) != '0'
}
}
assert c == 2
}	
fn main() {
a := Association{}
assert ptr_str(a.price) != '0'
assert ptr_str(a.association) == '0'
encode_struct(a)
}
```
=> cgen: fix comptime ref_or_deref_arg for ComptimeSelector

vlib/vweb/vweb.v
The docstrings claim that the server will respond with `HTTP_OK`, but it will actually respond with the most recent set status code. I.e. if you explicitly set the status code before calling one of the response functions, it will use that code and not the default `200 OK` status.
=> vweb: update docstrings for response functions

vlib/v/gen/c/fn.v, vlib/v/tests/fn_heap_promoted_test.v
Fix #20419
```V
@[heap]
struct Context {}
type Method = fn (ctx Context)
fn call(method Method, ctx Context) { // or switch `ctx` and `method` also ok
method(ctx)
}
fn get(ctx Context) {
println('ok')
}
call(get, Context{})
assert true
}
```
=> cgen: fix wrong heap promoted arg detection

vlib/v/checker/return.v, vlib/v/checker/tests/fn_mismatch_option_return_err.out, vlib/v/checker/tests/fn_mismatch_option_return_err.vv
Fix #20418
```V
import time
fn foo() time.Duration {
return ?time.Duration(0)
}
println(foo())
```
=> checker: fix return option mismatch checking

vlib/v/gen/c/auto_eq_methods.v, vlib/v/tests/option_auto_eq_test.v
Fix #20314
```V
import x.json2
pub struct PartialEmoji {
pub:
id       ?int
animated bool
}
pub fn PartialEmoji.parse(j json2.Any) !PartialEmoji {
match j {
map[string]json2.Any {
return PartialEmoji{
id: if s := j['id'] {
if s !is json2.Null {
?int(s.int())
} else {
none
}
} else {
none
}
name: j['name']! as string
animated: if b := j['animated'] {
b as bool
} else {
false
}
}
}
else {
return error('expected partial emoji to be object, got ${j.type_name()}')
}
}
}
pub enum ButtonStyle {
primary   = 1
secondary
success
danger
link
}
pub struct Button {
pub:
style     ButtonStyle = .secondary
label     ?string
emoji     ?PartialEmoji
custom_id ?string
url       ?string
disabled  ?bool
}
pub fn Button.parse(j json2.Any) !Button {
match j {
map[string]json2.Any {
return …
```
=> cgen: fix auto eq method for option fields

vlib/v/checker/lambda_expr.v, vlib/v/tests/lambda_expr_with_result_test.v
This PR fix lambda expr with result (fix #19874).
- Fix lambda expr with result.
- Add test.
```v
fn main() {
take_lambda(|| println('abc'))
}
fn take_lambda(l fn () !) {
l() or { panic(err) }
}
abc
```
=> checker: fix lambda expr with result (fix #19874)

vlib/v/gen/c/str_intp.v, vlib/v/tests/string_interpolation_test.v
1. Fixed #20432 
2. Add tests.
```v
module main
fn main() {
name := '李杰'
println('${name},你好啊')
}
```
outputs:
```
李杰,你好啊
```
=> cgen: fix escape of non-ascii characters in string interpolation(fix #20432)

vlib/v/checker/checker.v, vlib/v/checker/tests/cast_voidptr_to_struct_alias_err.out, vlib/v/checker/tests/cast_voidptr_to_struct_alias_err.vv
1. This PR: fix checking when converting `voidptr/nil` to struct aliases, maybe close #20429
Maybe there's something wrong with my environment and I can't find the method `sdl.render_set_v_sync`, so I'm not sure, But it solves several issues with converting `voidptr/nil` to aliases.
2. Add tests.
The issues:
```v
module main
@[typedef]
struct C.Foo {}
type AliasFoo = C.Foo
fn main() {
_ = AliasFoo(unsafe { nil })
}
```
C error:
```
/tmp/v_501/a.4242773401540172409.tmp.c:12658:23: warning: cast to smaller integer type 'main__AliasFoo' (aka 'int') from 'void *' [-Wvoid-pointer-to-int-cast]
{main__AliasFoo _ = ((main__AliasFoo)(((void*)0)));}
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
...
```
```v
module main
struct Bar {}
type AliasBar = Bar
fn main() { …
```
=> checker: fix checking when converting 'voidptr/nil' to struct aliases(fix #20429)

vlib/v/ast/types.v, vlib/v/checker/check_types.v, vlib/v/checker/checker.v, vlib/v/checker/containers.v, vlib/v/checker/fn.v, vlib/v/checker/for.v, vlib/v/checker/if.v, vlib/v/checker/lambda_expr.v, vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/orm.v
This PR add clear_option_and_result() and cleanup all the related calls.
=> ast: add clear_option_and_result() and cleanup all the related calls

cmd/tools/vtest-all.v, vlib/v/builder/cc.v
=> v.builder: allow for `v -shared -os windows file.v` on Linux/macos (fix #20445)

examples/dynamic_library_loader/modules/library/library.v, examples/dynamic_library_loader/use_test.v, vlib/dl/dl_windows.c.v, vlib/v/gen/c/cgen.v
As Windows LoadLibrary/FreeLibrary do not support constructor/destructor,  add vlib/dl_windows.c.v support a workaround.
Inside the dl.open(), call the _vinit_caller().
Inside the dl.close(), call the _vcleanup_caller().
This will build the v runtime environment for the DLL.
fix (#20447 )
=> cgen, dl: add windows dll support, fix (#20447)

.github/workflows/vab_ci.yml
- ci: bump java-version: to 11 in .github/workflows/vab_ci.yml, to make the CI more robust to github action runner upgrades
- ci: show the paths to d8 and dx if possible in vab_ci.yml
=> ci: make the `vab-compiles-v-examples` job, more robust to github runner and Android SDK changes

vlib/v/checker/errors.v, vlib/v/checker/lambda_expr.v, vlib/v/checker/tests/lambda_expression_in_map.out, vlib/v/checker/tests/lambda_expression_invalid.out, vlib/v/checker/tests/lambda_expression_invalid.vv, vlib/v/checker/tests/lambda_undefined_variables_err.out, vlib/v/parser/expr.v
This PR check invalid lambda expr (fix #20414).
- Check invalid lambda expr.
- Add test.
```v
fn main() {
x := 5
f := if x == 5 { |x| x - 5 } else { |x| x }
println(f(x))
}
tt1.v:3:19: error: lambda expressions are allowed only in places expecting function callbacks
2 |     x := 5
3 |     f := if x == 5 { |x| x - 5 } else { |x| x }
|                      ~~~~~~~~~
4 |     println(f(x))
5 | }
```
=> parser, checker: check invalid lambda expr (fix #20414)

vlib/v/checker/containers.v, vlib/v/gen/c/cgen.v, vlib/v/parser/parse_type.v, vlib/v/tests/constant_array_size_test.v
1. Fixed #20311 
2. Add tests.
This issue reports errors that occur when a multidimensional fixed array expression contains const and cannot be evaluated in the parser phase. now move the evaluation process into checker and evaluated the multiple dimensions recursively.
```v
module main
fn main() {
a := [width][2][width + 1]f64{}
println(a.len)
println(a[0].len)
println(a[0][0].len)
println(a)
}
const width = 2
```
outputs:
```
2
2
3
[[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]], [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]]
```
=> parser, checker, cgen: fix multidimensional fixed array size expression evaluation(fix #20311)

vlib/net/tcp_test.v
The vlib listen_tcp API only allows IP based address family.
The UNIX domain stream- and datagram is tested in
net/unix/unix_tests.v.
=> net.listen_tcp af .unix expect to return error

vlib/v/gen/c/assign.v, vlib/v/gen/c/infix.v, vlib/v/tests/fixed_array_op_overload_test.v
Fix #20467
```V
type Vec3 = [3]int
fn (v Vec3) add(u Vec3) Vec3 {
return Vec3([v[0] + u[0], v[1] + u[1], v[2] + u[2]]!)
}
fn (v Vec3) + (u Vec3) Vec3 {
return Vec3([v[0] + u[0], v[1] + u[1], v[2] + u[2]]!)
}
vec := Vec3([1, 2, 3]!)
a := vec.add(vec)
b := vec + vec
assert a == b
}
```
=> cgen: fix fixed array handling with operator overloading call

vlib/x/vweb/static_handler.v, vlib/x/vweb/tests/static_handler_test.v
This pr improves error handling when the directory passed to `StaticHandler` can't be found.
It now returns an error when the static directory does not exist, instead of `false`.
=> x.vweb: add error when static directory does not exist

vlib/sync/sync_freebsd.c.v
mutex: add try*lock functions for freebsd. This fixes the vlib/sync/mutex_test.v test.
=> sync: add mutex.try*lock functions for FreeBSD too

vlib/sync/mutex_test.v, vlib/sync/rwmutex_test.v, vlib/sync/sync_freebsd.c.v
The FreeBSD implementation of the sync functions were not updated when the default, darwin, and windows implementations were.  As a result, the unit tests would fail on FreeBSD.  This change brings it into agreement with the other implementations.
In addition, I noticed a few spelling and grammar errors in the mutex_test.v and rwmutex_test.v files.  I did not change anything of substance in those files, just the spelling and grammar.
=> sync: fix FreeBSD implementation of sync functions

vlib/v/gen/c/fn.v, vlib/v/tests/fixed_array_generic_ret_test.v
Fix #20465
```V
fn example[T]() ?T {
return T{}
}
dump(example[[1]int]())
a := example[[1]int]()
assert a? == [0]!
}
```
=> cgen: fix code generated for generic option fixed array return type

vlib/v/parser/parser.v, vlib/v/tests/selectorexpt_field_name_test.v
1. Fixed #20436
2. Add tests.
```v
struct Foo {
sort []int
}
fn main() {
f := Foo{}
fn [f] () {
println(f.sort.len)
assert f.sort.len == 0
}()
}
```
outputs:
```
0
```
=> parser: fix close_scope() missing when field.name is sort, sorted(fix#20436)

vlib/v/checker/orm.v, vlib/v/checker/tests/orm_invalid_recursive_structs_err.out, vlib/v/checker/tests/orm_invalid_recursive_structs_err.vv
1. Fixed #20285 
2. Add tests.
```v
@[table: 'parents']
struct Parent {
id       int     @[primary; sql: serial]
children []Child @[fkey: 'parent_id']
}
@[table: 'children']
struct Child {
id        int    @[primary; sql: serial]
parent_id int
parent    Parent
}
fn main() {
mut db := sqlite.connect('/dev/null') or { panic(err) }
defer {
db.close() or { panic(err) }
}
_ := sql db {
select from Parent
} or { panic(err) }
}
```
outputs:
```
a.v:8:2: error: invalid recursive struct `Child`
6 | struct Parent {
7 |     id int @[primary; sql: serial]
8 |     children []Child @[fkey: 'parent_id']
|     ~~~~~~~~~~~~~~~~
9 | }
10 |
```
=> orm: fix checking invalid recursive structs(fix #20285)

vlib/v/checker/struct.v, vlib/v/tests/anon_struct_with_default_expr_test.v
1. Fixed #20452 
2. Add tests.
```v
module main
const salutation = 'Good morning!'
fn greeting(args struct {
name string
salut string = salutation
}) string {
return 'Hi, ${args.name}! ${args.salut}'
}
fn main() {
println(greeting(name: 'Flibby'))
}
```
outputs:
```
Hi, Flibby! Good morning!
```
=> checker: fix anon struct init with const fields(fix #20452)

vlib/log/log.v, vlib/log/log_test.v, vlib/v/slow_tests/inout/dump_expression.out
enhance log time format setting
support most time format in time module, and custom time format also.
=> log: enhance log time format setting

vlib/v/gen/c/cgen.v, vlib/v/gen/c/dumpexpr.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/infix.v, vlib/v/tests/fixed_array_generic_ret_test.v, vlib/v/tests/option_or_result_fixed_arr_test.v
```v
type Abc = [2]int
// option
fn a() ?Abc {
return [1, 2]!
}
fn b() ?Abc {
return none
}
// result
fn aa() !Abc {
return [1, 2]!
}
fn bb() !Abc {
return error('b')
}
fn test_option() {
var_a := dump(a()?)
var_b := Abc([1, 2]!)
assert var_a == var_b
}
fn test_result() {
var_aa := dump(aa()!)
var_bb := Abc([1, 2]!)
assert var_aa == var_bb
}
fn test_opt_block() {
var_a := b() or { [0, 0]! }
dump(var_a)
assert var_a == Abc([0, 0]!)
}
fn test_res_block() {
var_a := bb() or { [0, 0]! }
dump(var_a)
assert var_a == Abc([0, 0]!)
}
```
```v
fn example2[T]() !T {
return T{}
}
fn test_result() {
dump(example2[[1]int]()!)
a := example2[[1]int]()!
assert a == [0]!
}
```
=> cgen: fix fixed array handling on generic result return and on or block

vlib/v/checker/orm.v, vlib/v/checker/tests/orm_invalid_recursive_structs_err_1.out, vlib/v/checker/tests/orm_invalid_recursive_structs_err_1.vv, vlib/v/checker/tests/orm_invalid_recursive_structs_err_2.out, vlib/v/checker/tests/orm_invalid_recursive_structs_err_2.vv
1. Fixed #20278 
2. Add tests.
PR 20491 fixed only the `sql expr` case, but misses the `sql stmt` case, which should now be complete.
```v
@[table: 'character']
struct Character {
id int @[primary; sql: serial]
user_id User
}
@[table: 'user']                  
struct User {
id int @[primary; sql: serial]
characters []Character @[fkey: "user_id"]
}
fn main() {
mut db := sqlite.connect(':memory:')!
defer {
db.close() or { panic(err) }
}
sql db {
create table User
}!
}
```
outputs:
```
a.v:13:5: error: ORM: invalid recursive struct `Character`
11 | struct User {
12 | 	id int @[primary; sql: serial]
13 | 	characters []Character @[fkey: "user_id"]
| 	~~~~~~~~~~~~~~~~~~~~~~
14 | }
15 |
```
=> orm: fix checking invalid recursive structs in sql stmts(fix #20278)
