examples/call_v_from_c/README.md
=> docs: improve the README for examples/call_v_from_c/ with instructions for macos

vlib/builtin/string.v, vlib/builtin/string_test.v, vlib/builtin/string_trim_indent_test.v
Also add helper methods:
- `is_blank()`
- `indent_width()`
Fixes #17086
=> builtin: add `string.trim_indent()`` method

examples/graphs/bfs2.v, examples/graphs/dfs.v, examples/graphs/dfs2.v
Backtracking Code Using #16767.
=> examples: graphs examples add & fix typo.

vlib/v/ast/ast.v, vlib/v/checker/checker.v, vlib/v/checker/tests/enum_field_value_overflow.out, vlib/v/parser/parser.v
Fixes https://github.com/vlang/v/issues/17055
=> v: add enum type pos

vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/reflection.v, vlib/v/reflection/reflection.v, vlib/v/tests/reflection_test.v
Implementation of a V reflection module
The reflection metainfo data are only added to the final source when `import v.reflection` is used.
`struct Type` - V type representation to userland
`struct TypeSymbol` - V type symbol representation to userland
`struct Module` - V module representation to userland
`struct Function` - V function representation to userland
`struct FunctionArg` - V function argument representation to userland
`struct Enum` - V enum representation to userland
`struct EnumField` - V enum field representation to userland
`struct Interface` - V interface representation to userland
`pub fn get_enums() []Enum` - Retrieve V registered enums to userland
`pub fn get_types() []Type` - Retrieve V registered types to userland
`pub fn get_type_symbols() []TypeSymbol` - Retrieve V …
=> v.reflection module

vlib/v/parser/sql.v, vlib/v/parser/tests/sql_undefined_variables_in_complex_exprs.out, vlib/v/parser/tests/sql_undefined_variables_in_complex_exprs.vv
=> parser: recursively search undefined variables in `where`

vlib/v/gen/c/comptime.v, vlib/v/tests/ifexpr_with_option_result_test.v
=> cgen: fix ifexpr with opt res

vlib/v/checker/fn.v, vlib/v/tests/generic_array_clone_test.v
=> checker: fix generic array clone

doc/docs.md
Missed a spot on the big push before.
=> doc: one more Optional to Option

README.md
=> Void Linux instructions

vlib/dl/dl_nix.c.v, vlib/dl/dl_windows.c.v
=> dl: add more dlopen flags

doc/docs.md
=> docs: removed note about shadowng of import name due 0b7a1cd

vlib/gg/gg_ui.c.v
Using dpi_scale is not recommend on Android. So, causes wrong behavior on Android. https://github.com/vlang/v/blob/master/vlib/gg/gg.c.v#L633
=> Fix gg.scissor_rect behavior on Android

vlib/v/ast/ast.v
This PR add comments for ast.AssertStmt and ast.IfGuardExpr.
=> ast: add comments for ast.AssertStmt and ast.IfGuardExpr

vlib/v/gen/c/cgen.v
This PR makes a minor cleanup in stmt().
=> cgen: minor cleanup in stmt()

examples/vweb_fullstack/src/main.v
fix error db.sqlite.SQLError: no such table: products
=> example(vweb_fullstack): fix missing Product table

vlib/v/builder/cc.v
The title is enough explicit I think
=> builder: Corrected bug in paths containing icc somewhere

vlib/v/tests/empty_struct_compare_test.v
Just found a missing test which I haven't add in another PR :)
=> tests: add empty_struct_compare_test.v too

vlib/orm/orm_insert_test.v, vlib/v/checker/orm.v, vlib/v/gen/c/sql.v
=> orm: allow using reference objects in ORM insert. 

doc/docs.md
Formatting makes the document neater (see tables) and formats it according to standards (for example, the line after the heading).
=> docs: format with IDEA formatter

vlib/v/checker/checker.v, vlib/v/tests/comptime_sumtype_cast_test.v
=> checker: fix sumtype cast of comptime var

vlib/v/slow_tests/inout/vscript_using_generics_in_os.vsh
This PR change option to result in vscript_using_generics_in_os.vsh.
=> tests: change option to result in vscript_using_generics_in_os.vsh

doc/docs.md
Feature that has been included with V for a bit undocumented.
This has been asked on the Discord to be documented, so I thought it is about time that be done.
=> doc: Document #preinclude

vlib/orm/orm_test.v, vlib/v/checker/orm.v
=> checker: allow using struct field as ORM limit and offset.

vlib/math/factorial.v
=> math: fix typo in factorial.v

vlib/v/gen/c/fn.v, vlib/v/tests/method_call_on_aggregate_test.v
=> cgen: fix missing aggregate rec_type

README.md
Original issue -> https://github.com/badges/shields/issues/8837
@medvednikov we should also fix a badge on the V's web page and all V repos
=> Fix twitter badge in README (fix #17166)

vlib/os/notify/backend_linux.c.v, vlib/term/ui/input_windows.c.v, vlib/term/ui/termios_nix.c.v, vlib/v/checker/struct.v, vlib/v/checker/tests/enum_init_err.out, vlib/v/checker/tests/enum_init_err.vv, vlib/v/gen/c/str_intp.v, vlib/v/tests/enum_test.v
Fixes https://github.com/vlang/v/issues/17215
=> checker: disallow enum initalization

vlib/os/os_nix.c.v
```
long ptrace(enum __ptrace_request request, pid_t pid,
void *addr, void *data);
```
=> vlib: fix ptrace signature

vlib/v/gen/c/auto_str_methods.v, vlib/v/slow_tests/inout/printing_fixed_array_of_pointers.out, vlib/v/tests/array_of_ptrs_test.v
Fixes https://github.com/vlang/v/issues/17359
=> gen/c: add `&` before ptr arr elements

vlib/v/gen/c/auto_str_methods.v, vlib/x/json2/README.md, vlib/x/json2/json2.v
Fix #17387
Fix #17378
Fix #17338
json2 example was broken.
=> cgen, json2: fix auto str option type generator and json2 option type handling

vlib/v/checker/assign.v, vlib/v/checker/checker.v, vlib/v/checker/tests/option_ptr_err.out, vlib/v/checker/tests/option_ptr_err.vv, vlib/v/gen/c/cgen.v, vlib/v/gen/c/str.v, vlib/v/parser/expr.v, vlib/v/tests/option_ptr_test.v
Initial work for `?&int()` type.
=> cgen: option pointer support - ?&type 

.github/workflows/other_ci.yml, vlib/v/gen/c/cgen.v
Also add a CI test, to ensure that will be true in the future too.
=> cgen: add `requires` to `c_reserved`, so that V generated code can be compiled with `-cc g++-11 -no-std -cflags -std=c++20` as well

vlib/v/builder/builder.v, vlib/v/builder/compile.v, vlib/v/builder/interpreterbuilder/ibuilder.v, vlib/v/eval/eval.v, vlib/v/eval/expr.v, vlib/v/eval/tests/push_val_test.v, vlib/v/pref/pref.v
Returns an Eval instance
Adds a user file to be processed with the .run() code
Pushes a value onto the host stack
Execute the code and returns the possible values
Pops a value from the host stack
```V
fn test() {
println('test() called')
}
``` 
```V
import v.eval
mut e := eval.create()
e.push_val(i64(2))
e.push_val(f64(2.2))
e.push_val('calc')
e.add_file('./t.v')
e.run('test() println("\${host_pop()}: \${i64(host_pop())+i64(host_pop())}")')!
```
```
test() called
calc: 4
```
=> eval: Host API

vlib/v/checker/return.v, vlib/v/checker/tests/void_fn_multiple_ret_err.out, vlib/v/checker/tests/void_fn_multiple_ret_err.vv
=> checker: fix and improve return stmt error messages

cmd/tools/modules/testing/common.v, cmd/tools/modules/testing/output.v, cmd/tools/modules/testing/output_teamcity.v
Fixes https://github.com/intellij-v/intellij-v/issues/398
=> test: handle compile error when run tests

vlib/os/os.v
=> os: fix typo in os.v

vlib/v/gen/c/struct.v, vlib/v/tests/option_struct_init_test.v
=> cgen: fix struct initialization for nested option struct

vlib/v/gen/c/assign.v, vlib/v/tests/option_or_block_test.v
=> cgen: fix or-block with return void statement

vlib/v/checker/checker.v, vlib/v/checker/tests/wrong_none_on_or_block_err.out, vlib/v/checker/tests/wrong_none_on_or_block_err.vv
=> checker: fix missing check for none type on or block on non-option

vlib/v/gen/c/array.v, vlib/v/tests/check_init_value_for_arrays_of_option_test.v
=> cgen: fix default init value for array of option

vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/struct.v, vlib/v/tests/option_struct_init_interface_test.v, vlib/v/tests/option_struct_init_with_opt_test.v
=> cgen: fix struct initialization with option value

vlib/x/json2/encode_option_test.v, vlib/x/json2/encoder.v
=> json2: fix decode result with option fields

vlib/v/gen/c/fn.v, vlib/v/tests/option_unwrap_print_test.v
=> cgen: fix code for unwrap option on print

vlib/v/gen/c/cgen.v, vlib/v/tests/option_selector_test.v
=> cgen: fix selector accessing field

vlib/crypto/ed25519/internal/edwards25519/extra.v, vlib/math/unsigned/uint128.v
This PR change option to result in crypto and math.
=> crypto, math: change option to result

vlib/v/checker/infix.v, vlib/v/checker/tests/option_wrapped_cmp_op_err.out, vlib/v/checker/tests/option_wrapped_cmp_op_err.vv, vlib/v/tests/option_multi_return_test.v
Fixes https://github.com/vlang/v/issues/17585
=> checker: check wrapped Option types before comparison

cmd/tools/vtest-all.v, vlib/v/pref/pref.v
- v: support `v -e "println(2+5)"` too
- add test to ensure it will not regress silently
=> v: support `v -e "println(2+5)"` too

vlib/v/gen/c/fn.v, vlib/v/tests/option_fn_test.v
=> cgen: fix code generated to option fn

cmd/tools/vast/vast.v, vlib/v/ast/ast.v, vlib/v/ast/scope.v, vlib/v/checker/assign.v, vlib/v/checker/checker.v, vlib/v/checker/comptime.v, vlib/v/checker/for.v, vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/comptime.v, vlib/v/gen/c/dumpexpr.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/for.v, vlib/v/tests/comptime_map_test.v
Fix #17009
Fix #17010
Fix #17011
Fix #17012
Fix #17013
Fix #17014
Makes working:
```V
$if field.typ is $Map {
for k, v in data.$(field.name) {
keys << k.str()
vals << v.str()
}
}
```
=> cgen: fix map with comp-time reflection + improved comptime var handling

vlib/v/checker/checker.v
This PR clean up sum_type_decl().
=> checker: clean up sum_type_decl()

vlib/v/checker/checker.v, vlib/v/checker/struct.v, vlib/v/checker/tests/struct_embed_required_field_err.out, vlib/v/checker/tests/struct_embed_required_field_err.vv, vlib/v/checker/tests/struct_init_wrong_warn.vv
=> checker: fix wrong struct warn about inited fields

vlib/v/checker/assign.v
This PR clean up assign_stmt().
=> checker: clean up assign_stmt()

vlib/v/gen/c/index.v, vlib/v/tests/result_with_index_expr_test.v
=> cgen: fix indexexpr with complex index expr

vlib/v/checker/check_types.v
This PR clean up infer_struct_generic_types() and infer_fn_generic_types().
=> checker: clean up infer_struct_generic_types() and infer_fn_generic_types()

vlib/v/parser/parser.v, vlib/v/tests/option_array_submodule_test.v
=> parser: fix parsing array from submodule

vlib/regex/regex.v, vlib/regex/regex_complex_test.v
=> regex: fix simple char match

vlib/v/gen/c/cgen.v
This PR clean up comments in cgen.v.
=> cgen: clean up comments in cgen.v

vlib/time/time_test.v, vlib/v/gen/c/assign.v
Closes https://github.com/vlang/v/issues/17712
=> gen/c: allow using of original operation if alias is number and no custom method is defined

vlib/v/tests/comptime_concrete_type_register_test.v
This PR fix comptime_concrete_type_register_test.v.
=> tests: fix comptime_concrete_type_register_test.v

vlib/x/json2/json2.v, vlib/x/json2/json2_test.v
fix: 
This is just a hotfix for 17644. It is not a good nether a robust solution for the problem, already that this logic is giving a lot of bug.
I hope that a best solution will be created in #16913 where I am working right now after a big time gap.
=> json2: fix decode to map doesn't work

vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/parser/parser.v, vlib/v/tests/call_on_anon_test.v
=> cgen: fix nested fn call with result/option propagation

vlib/v/parser/parse_type.v
This PR clean up in parse_generic_inst_type().
=> parser: clean up in parse_generic_inst_type()

vlib/v/checker/match.v, vlib/v/checker/tests/struct_match_same_type_node.out, vlib/v/checker/tests/struct_match_same_type_node.vv, vlib/v/gen/c/match.v, vlib/v/tests/match_struct_type_test.v
Fixes https://github.com/vlang/v/issues/17412
=> checker, cgen: add check and cgen for match struct

vlib/v/gen/c/auto_eq_methods.v, vlib/v/tests/option_struct_compare_test.v
This PR fixes several broken code handling option data.
=> cgen: multiple auto equality func generated fixes

vlib/regex/regex.v, vlib/regex/regex_complex_test.v
**What's inside:**
- a fix for a particular case for the pr #17701
- more tests for complex regex
=> Regex: fix issue with multiple repetitions out of the groups

cmd/tools/vvet/tests/brackets_in_documentation_comment_no_warn.vv, cmd/tools/vvet/vvet.v
=> vet: fix false warning on brackets in documentation

vlib/json/json_struct_option_test.v, vlib/v/gen/c/json.v
=> json: fix decode option string

vlib/json/json_omitempty_test.v, vlib/v/gen/c/json.v
=> json: fix [omitempty] with string

vlib/v/tests/concrete_type_as_generic_type_test.v
- (Fix) format test file caused by bug that was fixed by PR #17814.
=> v.test: Format test file

vlib/v/gen/c/if.v, vlib/v/gen/c/match.v, vlib/v/tests/option_match_expr_test.v
=> cgen: fix match tmp var needing check when working with option on branches

vlib/v/checker/containers.v, vlib/v/checker/tests/array_init_option_err.out, vlib/v/checker/tests/array_init_option_err.vv
A follow-up of https://github.com/vlang/v/pull/17820
=> checker: add check for unwrapped option in array cap

vlib/readline/README.md
If you run readline with a "?" - V compiler gets a warning: Because propagating a Result like an Option is deprecated.
=> readline: README.md Change '?' to '!' 

vlib/v/checker/infix.v, vlib/v/checker/tests/unwrapped_option_result_in_operation_err.out, vlib/v/checker/tests/unwrapped_option_result_in_operation_err.vv
Fixes https://github.com/vlang/v/issues/17870
=> checker: disallow unwrapped option/result with `in` operator

vlib/v/checker/checker.v, vlib/v/tests/generic_fn_infer_test.v
Closes https://github.com/vlang/v/issues/17881
=> checker: allow `~T(0)` where T is `int`

vlib/v/gen/c/assign.v, vlib/v/tests/option_ptr_cast_test.v
=> cgen: fix cast option ptr

vlib/json/json_generic_array_test.v, vlib/v/gen/c/auto_eq_methods.v, vlib/v/gen/c/json.v
=> json: fix encode/decode fixed array

vlib/encoding/base32/base32.v
=> vlib: change `?` to `!` in encoding.base32

vlib/crypto/pem/decode.v
=> vlib: fix typo in decode.v

vlib/rand/rand.v
=> rand: update documentation for normal and normal_pair

vlib/json/json_raw_test.v, vlib/v/gen/c/json.v
Fix #17894
```V
import json
struct TestOptionalRawString {
id int 
data ?string [raw]
}
fn main() {
test := TestOptionalRawString{
id: 1
data: "t
e
s
t"
}
encoded := json.encode(test)
assert json.decode(TestOptionalRawString, encoded)!.data? == r'"t\ne\ns\nt"'
test_none()!
}
fn test_none() ! {
test := TestOptionalRawString{
id: 1
data: none
}
encoded := json.encode(test)
r := json.decode(TestOptionalRawString, encoded)!.data
assert r == none
}
```
=> json: fix [raw] for option string

vlib/v/fmt/fmt.v, vlib/v/tests/isreftype_test.v, vlib/v/tests/sizeof_test.v
See https://github.com/vlang/v/pull/16684
=> tests: use `isreftype[T]()` and `sizeof[T]()` syntax

examples/vweb_fullstack/src/auth_dto.v, examples/vweb_fullstack/src/product_entities.v, examples/vweb_fullstack/src/user_entities.v, vlib/readline/README.md
In the [ORM-DOC](https://github.com/vlang/v/tree/master/vlib/orm) there is no 'Field' with the name `required`. Use therefore `nonull`
=> examples/vweb_fullstack: Fix wrong db ORM-fields

vlib/v/checker/checker.v
=> checker: disallow more reserved types to be used as a variable name

doc/docs.md
=> docs: improve `in` documentation for maps

examples/vweb_fullstack/readme.md
=> examples: Create readme.md for vweb_fullstack

vlib/json/json_alias_test.v, vlib/v/gen/c/json.v
=> json: fix json with alias to map

vlib/x/json2/encode_struct_test.v, vlib/x/json2/encoder_test.v, vlib/x/json2/json2.v
=> json2: encode array

vlib/v/parser/comptime.v
This PR correct comments in comptime_for().
=> parser: correct comments in comptime_for()

vlib/json/json_option_struct_test.v, vlib/v/gen/c/json.v
=> json: fix json with option struct

vlib/v/parser/containers.v
This PR clean up in array_init().
=> parser: clean up in array_init()

vlib/builtin/cfns.c.v
Closes https://github.com/vlang/v/issues/17671
=> builtin: add `C.scanf` fn decl to `cfns.c.v`

vlib/v/gen/c/comptime.v
This PR correct comments and cleanup in comptime_for().
=> cgen: correct comments and cleanup in comptime_for()

vlib/regex/README.md
=> regex: remove outdated examples in README.md

vlib/v/checker/checker.v, vlib/v/checker/tests/option_selector_or_block_err.out, vlib/v/checker/tests/option_selector_or_block_err.vv, vlib/v/checker/tests/wrong_none_on_or_block_err.out
=> checker: fix missing check for or-block on selectorexpr

vlib/cli/cli_test.v, vlib/cli/help.v
=> cli: fix indent handling

vlib/v/gen/c/cgen.v, vlib/v/tests/option_generic_ptr_return_test.v
=> cgen: fix generic return for option ptr

vlib/v/checker/return.v
This PR makes a minor cleanup in return_stmt().
=> checker: minor cleanup in return_stmt()

vlib/v/checker/containers.v, vlib/v/checker/tests/array_decl_type_err.out, vlib/v/checker/tests/array_decl_type_err.vv
=> checker: disallow `[]array{}`

vlib/json/json_encode_primite_test.v, vlib/v/gen/c/json.v
=> json: allow decode/encode of alias to primitive type

cmd/tools/vcheck-md.v
We have documents in the documentation in which we embed part of the HTML code, which causes our check to fail, the `-skip_line_length_check` flag will make it possible to skip this check and make our CI green.
> I'm sorry, I mistakenly pushed to a branch in the repository and not in the fork.
=> add `-skip_line_length_check` flag and fixed `vmod` handling in '```vmod'

vlib/json/json_encode_map_test.v, vlib/v/gen/c/json.v
=> json: fix -cstrict build + optional map

vlib/json/json_encode_sumtype_test.v, vlib/v/gen/c/json.v
=> json: fix option sumtype with int types

vlib/json/json_omitempty_types_test.v, vlib/v/gen/c/json.v
=> json: fix omitempty for alias, struct, sumtype, array and map

cmd/tools/vcreate/vcreate.v
fix errors (Updated using actual `examples/vweb_fullstack` code)
=> fix: cmd/tools/vcreate/vcreate.v

doc/docs.md
Starting to program more and more in V, this is one of the super cool things I've found by accident, but I wish they were documented 😊.
=> docs: add concise control flow example

vlib/v/checker/struct.v, vlib/v/checker/tests/assign_anon_struct_to_typed_struct_err.out, vlib/v/checker/tests/assign_anon_struct_to_typed_struct_err.vv
Closes https://github.com/vlang/v/issues/15631
=> checker: disallow assigning anon `struct` to typed `struct`

vlib/v/gen/c/index.v
This PR clean up in index_of_map().
- Change `elem` to `val`.
=> cgen: clean up in index_of_map()

vlib/v/checker/struct.v
This PR clean up in `struct_init()`.
=> checker: clean up in struct_init()

vlib/v/checker/containers.v
This PR clean up in array_init().
=> checker: clean up in array_init()

examples/graphs/bellman-ford.v
=> fix typo in bellman-ford.v

vlib/net/http/server.v
PR: Add remote-addr to net/http/server to allow obtaining the remote IP address.
=> server add header: remote-addr

vlib/v/parser/comptime.v, vlib/v/parser/expr.v, vlib/v/parser/fn.v, vlib/v/parser/module.v, vlib/v/parser/parse_type.v, vlib/v/parser/parser.v
This PR remove `pub` of the most fn in module parser.
=> parser: remove public of the most fn in module parser

vlib/json/json_decode_with_generic_array_test.v, vlib/v/checker/fn.v
This PR fix json decode with generic array of struct (fix #18300).
- Fix json decode with generic array of struct.
- Add test.
```v
import json
struct Response[T] {
time string
cars []T
}
struct Car {
brand string
power int
}
fn string_to_response[T](text string) {
result := json.decode([]Response[T], text) or { panic(err) }
assert result.len == 2
assert result[0].time == '12ms'
assert result[0].cars[0].brand == 'Ferrari'
assert result[0].cars[0].power == 232
assert result[0].cars[1].brand == 'Lamborghini'
assert result[0].cars[1].power == 345
assert result[1].time == '12ms'
assert result[1].cars[0].brand == 'Ferrari'
assert result[1].cars[0].power == 232
assert result[1].cars[1].brand == 'Lamborghini'
assert result[1].cars[1].power == 345
}
fn main() {
text := '[
{ …
```
=> checker: fix json decode with generic array of struct (fix #18300)

cmd/tools/vtest-self.v, cmd/tools/vtest.v, vlib/context/README.md, vlib/context/cancel_test.v, vlib/context/context.v, vlib/context/deadline_test.v, vlib/context/empty.v, vlib/context/onecontext/onecontext.v, vlib/context/onecontext/onecontext_test.v
While working on https://github.com/ulises-jeremias/rxv I found some improvements areas for the context module
=> vlib: Improvements to the context module

vlib/regex/regex.v, vlib/regex/regex_test.v
- Bug fix for the bug #18363
- Added more tests
=> Regex: bugfix for #18363, [^\s]+ act different from \S+

vlib/compress/deflate/deflate.v, vlib/compress/gzip/gzip.v, vlib/compress/zlib/zlib.v
This PR correct comments in compress module.
=> vlib/compress: correct comments in compress module

vlib/v/checker/fn.v
This PR clean up in method_call().
- Unfound method is handled first.
=> checker: clean up in method_call()

vlib/v/checker/infix.v
This PR makes minor cleanup in infix_expr().
=> checker: minor cleanup in infix_expr()

doc/docs.md, vlib/v/parser/fn.v
- Format example in docs.md.
- Fix reflection_sym_test.v.
=> fix current ci errors

vlib/v/checker/assign.v, vlib/v/checker/check_types.v, vlib/v/checker/checker.v, vlib/v/checker/comptime.v, vlib/v/checker/if.v, vlib/v/checker/infix.v, vlib/v/checker/match.v, vlib/v/checker/return.v, vlib/v/eval/eval.v, vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/comptime.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/infix.v, vlib/v/gen/c/match.v, vlib/v/gen/c/str.v
This PR change to autocast in if conditions.
=> all: change to autocast in if conditions

vlib/v/checker/assign.v, vlib/v/checker/check_types.v, vlib/v/checker/checker.v, vlib/v/checker/comptime.v, vlib/v/checker/infix.v, vlib/v/gen/c/cgen.v, vlib/v/gen/golang/golang.v, vlib/v/gen/js/js.v, vlib/v/parser/expr.v, vlib/v/parser/parser.v
This PR use autocasting in complex conditions.
=> v: use autocasting in complex conditions

vlib/sync/channels.c.v
Refactored the channel_select function to enhance code readability, eliminate redundant branches, and improve flexibility for future changes.
=> channels: refactor the channel_select function

vlib/v/checker/comptime.v
This PR use autocasting in complex if conditions.
=> checker: use autocasting in complex if conditions

vlib/v/checker/assign.v
This PR clean up in assign_stmt().
=> checker: clean up in assign_stmt()

vlib/v/ast/table.v
This PR makes a minor simplification in new_table().
=> ast: minor simplification in new_table()

vlib/v/ast/types.v
=> ast: clean up in types.v

vlib/net/ftp/ftp.v
=> ftp: dir() fix in files which contain spaces

.github/workflows/v_apps_and_modules_compile_ci.yml
Now that v-analyzer has replaced vls, make sure it builds with any V changes.
=> CI: add v-analyzer builds

vlib/v/ast/table.v
This PR make minor cleanups in table.v.
=> ast: minor cleanup in table.v

vlib/v/checker/checker.v
This PR clean up in cast_expr().
=> checker: clean up in cast_expr()

vlib/v/gen/c/infix.v
This PR makes a minor cleanup in infix_expr_arithmetic_op().
=> cgen: minor cleanup in infix_expr_arithmetic_op()

vlib/v/checker/tests/invalid_insert_references_test.out
This PR fix invalid_insert_references_test.vv.
=> tests: fix invalid_insert_references_test.vv

.github/workflows/linux_ci.yml, .github/workflows/macos_ci.yml, .github/workflows/windows_ci.yml
With this PR, the CI output for -autofree related failures, will be easier to diagnose.
=> ci: make -autofree failures easier to diagnose, test -autofree more on linux and windows too

vlib/v/checker/fn.v
=> checker: cleanup in fn.v

vlib/v/scanner/scanner.v
This PR makes a minor cleanup in ident_string().
=> scanner: minor cleanup in ident_string()

vlib/v/checker/struct.v, vlib/v/tests/generics_struct_field_with_default_fn_type_test.v
This PR fix generic struct field init recursively (related #19014).
=> checker: fix generic struct field init recursively (related #19014)

cmd/tools/check_os_api_parity.v, vlib/v/ast/str.v, vlib/v/builder/builder.v, vlib/v/doc/utils.v, vlib/v/fmt/fmt.v, vlib/v/gen/golang/golang.v
This PR clean up stringify_fn_decl() and stringify_anon_decl().
=> ast: clean up stringify_fn_decl() and stringify_anon_decl()

cmd/tools/modules/testing/common.v, examples/call_v_from_ruby/README.md, examples/call_v_from_ruby/test.rb, examples/call_v_from_ruby/test.v
This is a copy/adaptation of the python example (#13105)
In the same way as python example, I believe this may be useful to other ruby programmers.
=> examples: show how to call a simple v module from ruby

vlib/v/gen/c/fn.v
This PR makes minor cleanups in method_call().
=> cgen: minor cleanups in method_call()

vlib/v/util/module.v
Fix issue: #18970 
But I couldn't find a good way to write test cases, so I continued to try...
=> util: fix an wrong in path analysis when parsing 'mod_name'(fix #18970)

vlib/benchmark/benchmark.v
This PR makes a minor cleanup in total_message().
=> benchmark: minor cleanup in total_message()

vlib/net/websocket/events.v
NOTE: I'm not sure if that's the way to go, but using optionals would introduce a lot of boilerplate code instead.
=> websocket: initialize function pointers with nil

doc/docs.md, doc/packaging_v_for_distributions.md
The PR contains some notes from Discord, on how to make the life of package (un)maintainers easier, and hopefully, the lives of V developers and users as well.
=> docs: add doc/packaging_v_for_distributions.md

vlib/net/websocket/tests/autobahn/README.md
=> net.websocket: fix typo (ws -> wss)

vlib/v/checker/checker.v
This PR cleanup in check_expr_opt_call().
=> checker: cleanup in check_expr_opt_call()

doc/docs.md
updated link to remove old doc reference
=> docs: fix link

vlib/flag/flag.v
=> flag: cleanup in flag.v

vlib/v/gen/c/array.v
This PR cleanup in array_init() and fixed_array_init() (related #19246).
=> cgen: cleanup in array_init() and fixed_array_init() (related #19246)

cmd/tools/vast/vast.v, vlib/v/ast/ast.v, vlib/v/ast/str.v, vlib/v/fmt/comments.v, vlib/v/fmt/fmt.v, vlib/v/parser/parser.v
This PR simplify the processing logic for removing inline comments.
=> fmt: simplify the processing logic for removing inline comments

vlib/v/fmt/asm.v, vlib/v/fmt/attrs.v, vlib/v/fmt/comments.v, vlib/v/fmt/fmt.v, vlib/v/fmt/struct.v
=> fmt: cleanup fmt comments

vlib/v/gen/c/array.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/comptime.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/if.v, vlib/v/gen/c/index.v, vlib/v/gen/c/infix.v, vlib/v/gen/c/match.v, vlib/v/gen/c/orm.v, vlib/v/gen/c/past_tmp_var.v, vlib/v/gen/c/spawn_and_go.v, vlib/v/gen/c/struct.v, vlib/v/gen/c/text_manipulation.v
This PR cleanup go_before_stmt(0).
- Change `go_before_stmt(0)` to `go_before_last_stmt()`.
=> cgen: cleanup go_before_stmt(0)

examples/graphs/bfs3.v
=> examples: add another graph example for bread first search with backtracking

examples/wasm_codegen/bf_compiler.v
This will be used in my V talk.
=> examples: add a brainfuck->wasm compiler example

vlib/v/parser/parser.v
This PR makes minor optimization in name_expr().
=> parser: minor optimization in name_expr()

vlib/v/markused/markused.v
This PR cleanup in mark_used().
=> markused: cleanup in mark_used()

vlib/v/ast/types.v
This PR fix error in is_int().
=> ast: fix error in is_int()

vlib/crypto/bcrypt/base64.v, vlib/crypto/bcrypt/bcrypt.v, vlib/crypto/bcrypt/bcrypt_test.v, vlib/crypto/blowfish/block.v
https://github.com/vlang/v/issues/19558
Fix this issue
=> fix bcrypt algo

vlib/v/parser/struct.v
=> parser: minor cleanup in struct_decl

vlib/os/signal.c.v, vlib/os/signal_darwin.c.v, vlib/os/signal_default.c.v, vlib/os/signal_test.v, vlib/os/signal_windows.c.v
😄 The last PR broke, so sorry.
I changed it again, and this should not broke.
=> os: add a convenient way to ignore certain system signals

vlib/v/checker/check_types.v
This PR cleanup in check_types().
=> checker: cleanup in check_types()

.github/workflows/v_apps_and_modules_compile_ci.yml, cmd/tools/vdoc/main.v, cmd/tools/vdoc/run_examples.v, cmd/tools/vdoc/tests/testdata/run_examples_bad/main.comments.out, cmd/tools/vdoc/tests/testdata/run_examples_bad/main.out, cmd/tools/vdoc/tests/testdata/run_examples_bad/main.v, cmd/tools/vdoc/tests/testdata/run_examples_good/main.comments.out, cmd/tools/vdoc/tests/testdata/run_examples_good/main.out, cmd/tools/vdoc/tests/testdata/run_examples_good/main.v, cmd/tools/vdoc/tests/vdoc_file_test.v, cmd/tools/vdoc/vdoc.v, cmd/tools/vrepl.v, vlib/v/doc/comment.v, vlib/v/vmod/vmod.v
- tools: support `v doc -run-examples vlib/math` for running all the examples in doc comments in `math`
- make the output of `v doc -l os Process` more convenient to use with editors like vim and emacs
- tools: make the repl detect `assert 2*2==4` as a statement
- cleanup and add tests
=> vdoc support running examples

vlib/v/checker/assign.v
A minor cleanup, remove the two redundant judgments.
=> checker: a minor cleanup

cmd/tools/vup.v
=> [vup] fix don't delete ./v when missing .git dir

vlib/v/gen/c/fn.v, vlib/v/gen/c/live.v, vlib/v/live/executable/reloader.c.v
fix for issue https://github.com/vlang/v/issues/18716
=> fix live mode on Windows

vlib/db/pg/README.md, vlib/db/pg/pg.c.v
fix for https://github.com/vlang/v/issues/18128
=> fix postgre connection on windows

vlib/v/checker/fn.v
=> checker: a minor cleanup (typo)

vlib/v/checker/interface.v
This PR makes a minor simplification in resolve_generic_interface().
=> checker: minor simplification in resolve_generic_interface()

vlib/json/README.md
Adds @[omitempty] documentation to json module.
@[raw] still needs to be documented. I don't know how to document it in a clear way right now.
=> Partially solve #20121

vlib/os/file.c.v, vlib/os/file_test.v
fix for this https://github.com/vlang/v/issues/20069
=> fix crlf files modif on Windows

vlib/v/checker/checker.v, vlib/v/gen/c/spawn_and_go.v, vlib/v/gen/c/utils.v, vlib/v/tests/generics_chans_select_test.v
This PR fix generics chans select (fix #20145).
- Fix generics chans select.
- Add test.
```v
import time
pub type EventListener[T] = fn (T) !
@[heap]
struct Chan[T] {
c chan T
}
pub type Check[T] = fn (T) bool
struct EventWaiter[T] {
check ?Check[T]
c     &Chan[T]
}
pub struct EventController[T] {
mut:
id        int
wait_fors map[int]EventWaiter[T]
listeners map[int]EventListener[T]
}
fn (mut ec EventController[T]) generate_id() int {
return ec.id++
}
@[params]
pub struct EmitOptions {
pub:
error_handler ?fn (int, IError)
}
pub fn (mut ec EventController[T]) emit(e T, options EmitOptions) {
for i, w in ec.wait_fors {
mut b := false
if w.check != none {
b = (w.check or { panic(err) })
e
} else {
b = true
}
if b {
w.c.c <- e
ec.wait_fors.delete(i)
return
}
}
mut ts := []thread{}
for i, l …
```
=> checker, cgen: fix generics chans select (fix #20145)

vlib/net/http/file/entity.v, vlib/net/http/file/folder_index.v, vlib/net/http/file/static_server.v, vlib/os/file.c.v, vlib/os/inode.c.v, vlib/os/os.c.v, vlib/os/os_nix.c.v
After `v -e 'import net.http.file; file.serve()'` and visiting:
http://127.0.0.1:4001/examples/wasm/
=> os, net.http.file: add a folder listing to the http static file server, started by file.serve/1

vlib/v/gen/c/index.v
=> cgen: cleanup in index.v

vlib/v/gen/c/assign.v
This PR cleanup in assign_stmt().
=> cgen: cleanup in assign_stmt()

vlib/encoding/binary/little_endian.v
=> encoding.binary: fix u32 little endian comments

doc/docs.md
See https://github.com/vlang/v/pull/20286.
=> docs: add example of nullable ORM field

vlib/strings/builder.js.v, vlib/v/checker/fn.v
This PR cleanup array and alias of array method call.
=> checker: cleanup array and alias of array method call

vlib/orm/README.md
According to the discord group, someone pointed out the example codes in the readme of ORM has `@` and some quotes missing. Ref to [this message](https://discord.com/channels/592103645835821068/631271043876519967/1183823916851019887). So I tried to fix it so that the syntax looks right. As I don't develop with ORM or databases, I haven't tested the code, but I think it is better than before with syntax error.
=> ORM: Fix example in readme

vlib/x/json2/encoder.v
=> perf: improve none checker on json2 (time encode around 20% faster)

vlib/v/gen/c/assign.v, vlib/v/gen/c/fn.v, vlib/v/tests/option_unwrap_fn_test.v
=> cgen: fix auto unwrapping option fn type

doc/docs.md
Add `$string` comp-time type to doc.
=> doc: add $string docs

doc/docs.md
Initial doc for comptime resources
=> doc: initial doc for comptime resources

vlib/v/gen/c/cgen.v, vlib/v/tests/return_fixed_array_test.v, vlib/v/tests/struct_init_with_fixed_array_field_test.v
Many thanks @spytheman for a review suggest. I found a problem while adjusting the related test case! It is now cleanup and fixed!
Adore very much 👍
=> cgen: fix option/result fixed array init and related tests

doc/docs.md
=> doc: Fix typo in embedded structs description

cmd/tools/vtest-self.v, cmd/tools/vtest.v, vlib/db/pg/orm.v, vlib/db/pg/pg_double_test.v, vlib/net/conv/conv.v
=> orm.pg: fix f32 and f64 endianness

README.md
Reference new repo for `v-analyzer`
=> readme: v-analyzer/v-analyzer → vlang/v-analyzer in README.md

vlib/strings/similarity.v
This algorithm is about 2.8x faster compared to the old implementation (added @[direct_array_access], early array initialization and use a faster implementation of the 2 loops)
=> strings: use faster levenshtein distance algorithm

vlib/v/ast/types.v, vlib/v/checker/check_types.v, vlib/v/checker/checker.v, vlib/v/checker/if.v, vlib/v/checker/infix.v, vlib/v/checker/return.v, vlib/v/checker/str.v, vlib/v/gen/c/assign.v, vlib/v/gen/c/auto_str_methods.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/comptime.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/if.v, vlib/v/gen/c/match.v, vlib/v/gen/c/str_intp.v, vlib/v/gen/wasm/gen.v, vlib/v/parser/struct.v
This PR add has_any_flag() and cleanup all the related calls.
=> ast: add has_option_or_result() and cleanup all the related calls

doc/docs.md
=> doc: add `r` and `R` string interpolation switch examples

vlib/strings/similarity.v, vlib/strings/similarity_test.v
=> Fix strings.levenshtein_distance function

doc/docs.md
Documentation for operator overloading with return type limitation.
=> docs: document the return type restrictions for operator overloading

doc/docs.md
=> Add field shadowing comment

vlib/encoding/csv/utils.v, vlib/encoding/csv/utils_test.v
Q: What is the best way to organize high-level helper functions?
=> encoding.csv: add a new utility fn `new_reader_from_file/2`

vlib/v/checker/tests/generic_fn_decl_err.out, vlib/v/checker/tests/generic_fn_decl_err.vv, vlib/v/checker/tests/generic_interface_method_decl_err.out, vlib/v/checker/tests/generic_interface_method_decl_err.vv, vlib/v/checker/tests/generics_fn_arguments_count_err.out, vlib/v/checker/tests/generics_fn_arguments_count_err.vv, vlib/v/checker/tests/generics_inst_non_generic_struct_err.out, vlib/v/checker/tests/generics_inst_non_generic_struct_err.vv, vlib/v/checker/tests/generics_interface_declaration_err.out, vlib/v/checker/tests/generics_interface_declaration_err.vv, vlib/v/checker/tests/generics_non_generic_fn_called_like_a_generic_one.out, vlib/v/checker/tests/generics_non_generic_fn_called_like_a_generic_one.vv, vlib/v/checker/tests/generics_struct_field_fn_args_err.out, vlib/v/checker/tests/generics_struct_field_fn_args_err.vv, vlib/v/checker/tests/generics_struct_init_type_parameter_err.out, vlib/v/checker/tests/generics_struct_init_type_parameter_err.vv, vlib/v/checker/tests/vweb_routing_checks.vv, vlib/v/checker/tests/vweb_tmpl_used_var.vv
This PR cleanup the generic tests in checker/tests.
=> checker: cleanup the generic tests

vlib/v/checker/fn.v
This PR cleanup in method_call().
=> checker: cleanup in method_call()

vlib/v/tests/closure_test.v
This PR is in addition to the test case against PR #20557
=> test: optimize a test case about closure parameters cloning on -autofree

vlib/encoding/csv/csv_reader_random_access.v, vlib/encoding/csv/csv_reader_test.v
- Bug fix for buffer elongation over the limit
- More tests on coherence
=> encoding.csv: fix bug RandomAccessReader

doc/docs.md
=> docs: fix typo (`stucts` -> `structs`)

doc/docs.md
Initial doc for `$dbg` statement.
=> docs: `$dbg` statement docs

vlib/x/json2/decode_struct_test.v, vlib/x/json2/json2.v
Extracted from another PR for clarity.
=> x.json2: fix #20593

vlib/v/help/build/build.txt
=> help: fix a typo

cmd/tools/vtest-self.v
tests: add *_test.c.v to all_test_files
=> tests: make `v test-self` available for *_test.c.v

cmd/tools/vtest-self.v, vlib/gg/m4/m4_test.v, vlib/gg/m4/vector.v, vlib/v/checker/comptime.v, vlib/v/tests/generics_fn_variable_2_test.v, vlib/v/tests/sizeof_test.v, vlib/v/tests/type_alias_test.v
This PR make 'test-self' pass under msys2/MINGW32.
=> test: make 'test-self' pass under msys2/MINGW32

vlib/v/gen/c/cgen.v, vlib/v/gen/c/cmain.v, vlib/v/gen/c/testdata/closure_shared_lib.c.must_have, vlib/v/gen/c/testdata/closure_shared_lib.vv
=> v.gen.c: initialize closures in shared library mode

.github/workflows/v_apps_and_modules_compile_ci.yml, vlib/v/parser/parser.v, vlib/v/tests/enum_from_generic_static_method_test.v, vlib/v/util/util.v
- parser: fix `MyEnum.from(0)!`
~~- parser: implement MyFlaggedEnum.zero()~~ - this currently conflicts with the existing static methods in discord.v .
=> parser: fix `MyEnum.from(0)!`

vlib/log/common.v, vlib/log/default_test.v, vlib/log/log.v, vlib/log/log_test.v, vlib/v/slow_tests/inout/dump_expression.out
log: add short tag support
when enabled:
'[FATAL]'=>'[F]'
'[ERROR]'=>'[E]'
'[WARN ]'=>'[W]'
'[INFO ]'=>'[I]'
'[DEBUG]'=>'[D]'
=> log: add short tag

doc/docs.md
As per our discussion on Discord.
=> docs: add a section about modules specifics

doc/docs.md
=> doc: fix minor embedded struct typo

vlib/vweb/README.md
=> vweb: fix minor typo in vweb doc

vlib/v/gen/c/cgen.v, vlib/v/gen/c/cheaders.v, vlib/v/gen/c/cmain.v, vlib/v/gen/c/profile.v, vlib/v/slow_tests/profile/profile_test.v, vlib/v/slow_tests/profile/profile_test_interrupted.v
=> v.gen.c: write profile out upon CTRL-C or kill

vlib/v2/types/checker.v
=> v2: fix typo in checker.v

vlib/v/tests/tmpl/interpolation.txt, vlib/v/tests/tmpl_test.v
Nothing to fix as it works with current master (0.4.4 1141432).
=> $tmpl: add test for #9838

vlib/v/gen/c/cgen.v
=> v.debug: fix code generated for stringfy ptr with non-pointer str() 

vlib/v/tests/as_cast_selector_test.v
=> test: add test for cast as selector fix

vlib/v/checker/checker.v, vlib/v/tests/defer_if_comptime_test.v
=> checker: fix comptime ident checking on defer stmt

vlib/v/gen/c/cgen.v, vlib/v/tests/interface_multi_return_test.v
=> cgen: fix interface on multi return func

vlib/v/gen/c/cgen.v, vlib/v/slow_tests/valgrind/if_expr_autofree_optional.v, vlib/v/slow_tests/valgrind/valgrind_test.v
=> cgen: Fix premature variable release by autofree

vlib/v/gen/c/cgen.v, vlib/v/tests/option_call_on_orexpr_test.v
=> cgen: fix return with option on orexpr

vlib/x/templating/dtm/README.md
First version of DTM documentation.
Feel free to suggest modifications or corrections if necessary. Thank you in advance!
=> dtm: First version of user documentation

vlib/x/vweb/middleware.v
changed `origin: '*'` to 
`origins: ['*']`
=> x.vweb: fix cors example

vlib/v/gen/c/auto_str_methods.v, vlib/v/tests/map_auto_str_ptr_test.v
=> cgen: fix auto str for map with ptr str

vlib/x/templating/dtm/README.md, vlib/x/templating/dtm/dynamic_template_manager.v, vlib/x/templating/dtm/tmpl.v
The template parsing and rendering system has been completely overhauled for significant performance improvements.
=> dtm: Optimization of parser/gen of template 

vlib/v/gen/c/cgen.v, vlib/v/tests/option_call_on_orexpr_test.v
=> cgen: fix unwrap on or-expr when calling option fn

vlib/net/dial_tcp_with_bind_test.v, vlib/net/tcp_test.v
- net: extract dial_tcp_with_bind_test.v from tcp_test.v, reduce/isolate remaining test flakyness
- net: reduce test flakyness
=> net: reduce flakyness of tcp test

vlib/x/crypto/sm4/sm4.v
Use _fixed version of encoding.binary
=> x.crypto.sm4: fix sm4 use encoding.binary _fixed fns

cmd/tools/vdoc/utils.v
=> doc: simplify `is_module_readme` function

vlib/net/util.v
=> net: fix function name in split_address doc comment

doc/docs.md
docs.md - enums - add section about converting enum from/to string and int values
Covers usage of `from()` `froms_string()` and `str()` functions
=> docs: add section explaining how to convert enum from/to str/int values

.github/workflows/cancel.yml
=> ci: Change spaceface777/cancel-workflow-action to styfle/cancel-workflow-action

vlib/v/gen/c/auto_eq_methods.v, vlib/v/tests/option_operator_overload_test.v
=> cgen: fix auto_eq for option eq operator overload

vlib/v/gen/c/auto_str_methods.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/tests/modules/enum_from_string_in_different_mods/src/main_test.v, vlib/v/tests/modules/enum_from_string_in_different_mods/src/mod2/mod2.v
=> cgen: fix from_string fn generation missing mod name

examples/vweb/static_website/README.md
The title of the README.md was not good
=> doc: static example fix

vlib/v/gen/c/cgen.v, vlib/v/tests/option_selector_assign_test.v
=> cgen: fix unwrapped option selector assigning 

vlib/x/templating/dtm/dynamic_template_manager.v, vlib/x/templating/dtm/dynamic_template_manager_test.v
=> dtm: fix clock test for CI

vlib/v/checker/if.v, vlib/v/checker/tests/if_mismatch_option_err.out, vlib/v/checker/tests/if_mismatch_option_err.vv
=> checker: fix if branch option type mismatch

vlib/json/json_decode_struct_ptr_test.v, vlib/v/gen/c/json.v
=> json: fix decode struct ptr

vlib/x/templating/dtm/dynamic_template_manager.v, vlib/x/templating/dtm/dynamic_template_manager_cache_system_test.v
This time, it should solve the CI issues related to the cache manager tests.
I hope so!
=> dtm: Fix concurrency and timing issues with tests of cache handler

vlib/x/crypto/poly1305/poly1305_test.v
=> tests: fix the length of `all_key` in `poly1305_test.v`

vlib/v/gen/c/spawn_and_go.v, vlib/v/tests/thread_ptr_ret_test.v
=> cgen: fix thread return type generation

vlib/v/gen/c/cgen.v, vlib/v/tests/anon_struct_default_value_test.v
=> cgen: fix code generated for anon struct default value 

doc/docs.md
=> docs: update v.debug docs - callstack+trace

vlib/net/tcp.c.v
=> net: fix -prod mode gcc bug

vlib/v/gen/c/coutput_test.v, vlib/v/gen/c/testdata/aligned_attr_gcc_windows.c.must_have, vlib/v/gen/c/testdata/aligned_attr_gcc_windows.vv
=> tests: add 'aligned_attr_gcc_windows.vv' for gcc

vlib/v/checker/assign.v
This PR cleanup in assign_stmt().
=> checker: cleanup in assign_stmt()

vlib/v/gen/c/array.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/struct.v, vlib/v/tests/multiple_fixed_array_var_init_test.v
This PR fix multiple fixed array variable init (fix #20895).
- Fix multiple fixed array variable init.
- Add test.
```v
struct Cell {
value  int
fvalue f32
mut:
mut_value  int = 10
mut_fvalue f32
}
struct Grid {
cells [2][2][2]Cell
}
fn main() {
mut tile_field := [2][2][2]Cell{}
b := Grid{
cells: tile_field
}
println('The original:')
println(tile_field)
println('==========')
println('The struct:')
println(b.cells)
assert b.cells[0][0][0].value == 0
assert b.cells[0][0][0].mut_value == 10
assert b.cells[0][0][1].value == 0
assert b.cells[0][0][1].mut_value == 10
assert b.cells[0][1][0].value == 0
assert b.cells[0][1][0].mut_value == 10
assert b.cells[0][1][1].value == 0
assert b.cells[0][1][1].mut_value == 10
assert b.cells[1][0][0].value == 0
assert b.cells[1][0][0].mut_value == 10
assert …
```
=> cgen: fix multiple fixed array variable init (fix #20895)

vlib/toml/input/input.v
=> toml: return an error from toml.parse_file(), when the passed path does not exist

doc/docs.md
Verb should agree with plural subject.
=> doc: fix minor grammar error in attribute comment

ROADMAP.md, examples/gg/arcs_and_slices.v, examples/gg/path_finding_algorithm_visualizer/README.md, examples/gg/path_finding_algorithm_visualizer/aStar.v, thirdparty/fontstash/stb_truetype.h, thirdparty/libgc/gc.c, thirdparty/mbedtls/include/mbedtls/asn1write.h, thirdparty/mbedtls/library/debug.c, thirdparty/mbedtls/library/ssl_client.c, thirdparty/sokol/util/sokol_gl.h, vlib/benchmark/benchmark.v, vlib/builtin/js/string.js.v, vlib/builtin/string.v, vlib/builtin/wasm/builtin.v, vlib/math/stats/stats.v, vlib/regex/regex_opt.v, vlib/regex/regex_util.v, vlib/v/ast/types.v, vlib/v/checker/checker.v, vlib/v2/parser/parser.v, vlib/x/vweb/sse/README.md
=> all: fix typos in comments

vlib/cli/command.v
=> cli: add pluralization to err msg if required number of args is not met

vlib/v/checker/assign.v, vlib/v/checker/checker.v, vlib/v/checker/containers.v, vlib/v/checker/fn.v, vlib/v/checker/infix.v, vlib/v/checker/postfix.v, vlib/v/checker/tests/no_arrays_of_references_in_translated.vv, vlib/v/checker/tests/no_cannot_cast_a_fixed_array_in_translated.vv, vlib/v/checker/tests/no_function_must_be_called_from_unsafe_in_translated.vv, vlib/v/checker/tests/no_goto_requires_unsafe_in_translated.vv, vlib/v/checker/tests/no_method_must_be_called_from_unsafe_in_translated.vv, vlib/v/checker/tests/no_operator_can_only_be_used_as_a_statement_in_translated.vv, vlib/v/checker/tests/no_pointer_arithmetic_is_only_allowed_in_translated.vv, vlib/v/checker/tests/no_reading_a_union_field_in_translated.vv, vlib/v/checker/tests/no_unused_variable_in_translated.vv, vlib/v/parser/expr.v
TODO: add regression tests in vlib/v/checker/tests/ .
=> parser,checker: silence more warnings for `@[translated]` files

vlib/v/gen/c/array.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/struct.v, vlib/v/tests/fixed_array_generic_ini_test.v, vlib/v/tests/option_return_fixed_arr_test.v
=> cgen: fix fixed array return on fn with option generic return

thirdparty/mbedtls/include/psa/crypto.h, vlib/os/os.v
=> remove repetitive words

vlib/crypto/blake3/blake3.v
One of these days, I'll learn how to spell.
=> crypto/blake3: fix typo on Digest comment

vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/tests/comptime_generic_arg_test.v
=> cgen: fix code generated to comptime passed to generic arg

vlib/builtin/string.v
=> builtin: fix a few grammar errors in builtin.string comments

vlib/v/util/vtest/vtest.v
=> v.util: simplify vtest

vlib/v/checker/struct.v
=> checker: cleanup and simplify struct processing p1

vlib/v/checker/infix.v, vlib/v/checker/tests/chan_incompatible_type_err.out, vlib/v/checker/tests/chan_incompatible_type_err.vv
=> checker: fix missing incompatible pushval type for chan <- operator

vlib/v/fmt/fmt.v, vlib/v/fmt/tests/interface_decl_with_comment_expected.vv, vlib/v/fmt/tests/interface_decl_with_comment_input.vv, vlib/v/parser/struct.v
=> parser, fmt: fix parsing of interface with comment above `mut:` keyword

vlib/builtin/string.v, vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/struct.v
=> cgen: enable autofree for option

doc/docs.md
=> docs: Update docs.md

.github/workflows/compile_shaders_in_examples.sh, .github/workflows/other_ci.yml, cmd/tools/modules/testing/common.v, cmd/tools/vgret.defaults.toml, examples/sokol/clear.v, examples/sokol/sdf/.gitignore, examples/sokol/sdf/sdf.glsl, examples/sokol/sdf/sdf.v, vlib/sokol/sapp/sapp_structs.c.v
Port https://github.com/floooh/sokol-samples/blob/master/sapp/clear-sapp.c .
Port https://github.com/floooh/sokol-samples/blob/master/sapp/sdf-sapp.c .
=> examples: port sokol/clear.v and sokol/sdf/sdf.v

vlib/v/gen/c/cgen.v, vlib/v/tests/option_array_fixed_struct_test.v
=> cgen: fix code generated for array fixed of option struct

vlib/v/builder/cc.v, vlib/v/builder/cc_windows.v, vlib/v/builder/compile.v, vlib/v/checker/checker.v
=> builder, checker: utilize vroot field of pref.Preferences struct

vlib/v/fmt/fmt.v, vlib/v/fmt/tests/interface_js_interop_method_keep.vv, vlib/v/parser/fn.v, vlib/v/parser/tests/interop_js_func_body_err.out, vlib/v/parser/tests/interop_js_func_body_err.vv
Builds on #21070 and it's comments.
Adds a test for the scenario and for #12447.
=> parser, fmt: parse methods on JS interfaces, write JS method bodies

vlib/encoding/base64/base64.c.v, vlib/v/gen/js/comptime.v, vlib/v/gen/js/js.v
=> vlib: fix typos

vlib/v/ast/ast.v
=> ast: cleanup

.github/workflows/build_vinix_locally.sh, .github/workflows/c2v_ci.yml, .github/workflows/compile_v_with_vtcc.sh, .github/workflows/cross_ci.yml, .github/workflows/freebsd_build_tcc.sh, .github/workflows/gen_vc_ci.yml, .github/workflows/gg_regressions_ci.yml, .github/workflows/linux_ci.yml, .github/workflows/macos_ci.yml, .github/workflows/native_backend_tests_ci.yml, .github/workflows/other_ci.yml, .github/workflows/periodic_ci.yml, .github/workflows/retry.sh, .github/workflows/sanitized_ci.yml, .github/workflows/sdl_ci.yml, .github/workflows/toml_ci.yml, .github/workflows/v_apps_and_modules_compile_ci.yml, .github/workflows/vab_ci.yml, .github/workflows/vinix_ci.yml, .github/workflows/websockets_ci.yml
It should make transient network failures, that are false positives for the V project, much less frequent:
https://github.com/vlang/v/actions/runs/8432987251/job/23093124059
=> ci: retry all setup commands that need network access, till they succeed (so the CI jobs have less false positives)

thirdparty/zstd/README.md, thirdparty/zstd/zstd.c, thirdparty/zstd/zstd.h
Updates zstd to its latest release version 1.5.6.
=> thirdparty: update zstd to latest release 1.5.6

vlib/v/gen/c/cgen.v, vlib/v/tests/option_result_interface_ret_test.v
=> cgen: fix return code when returning interface result type

examples/flappylearning/game.v, examples/game_of_life/life_gg.v, examples/gg/drag_n_drop.v, examples/gg/draw_pixels.v, examples/gg/raven_text_rendering.v, examples/gg/rectangles.v, examples/gg/stars.v, examples/gg/worker_thread.v, examples/hot_reload/graph.v, examples/snek/snek.v, examples/sokol/sounds/melody.v, examples/ttf_font/example_ttf.v
Utilizes the structs default value instead of an additional assignment of 0 to resolve a warning during compilation.
=> examples: fix warnings about 0 assignments to reference fields

vlib/v/checker/checker.v, vlib/v/gen/c/cgen.v, vlib/v/tests/const_array_test.v
=> checker, cgen: fix const initialized with array

vlib/v/gen/c/infix.v, vlib/v/tests/array_ptr_compare_test.v
=> cgen: fix infix array heap comparison

README.md
Fixes a badge and while already editing the file, minor formatting discrepancies are updated in the same breath.
=> docs: fix sponsors bade in readme, format

vlib/bitfield/bitfield.v
=> bitfield: correct a few typos

cmd/tools/vpm/common.v, cmd/tools/vpm/settings.v, cmd/tools/vpm/vpm.v
If not running vpm in explicit debug mode(logging to stdout) the changes will append the debug logs to a log file for later analysis.
=> tools.vpm: debug-log to `$VMODULES/cache/vpm.log` if not running in debug mode

cmd/tools/measure/fmt_speed.v, cmd/tools/measure/parser_speed.v, vlib/v/parser/parser.v
=> parser: remove redundant comments_mode field

vlib/os/os.c.v, vlib/v/gen/c/cgen.v
=> cgen: fix comptime `autofree`

vlib/math/stats/stats.v
=> fix typo in stats.v

cmd/tools/vdoc/html.v
=> vdoc: minor cleanup

.github/workflows/cross_ci.yml, .github/workflows/gg_regressions_ci.yml, .github/workflows/other_ci.yml, .github/workflows/toml_ci.yml, .github/workflows/v_apps_and_modules_compile_ci.yml, .github/workflows/vab_ci.yml, .github/workflows/websockets_ci.yml
=> ci: limit workflows to relevant paths, fix typo in workflow comment

examples/pidigits.v, vlib/math/big/array_ops.v, vlib/math/big/division_array_ops.v, vlib/math/big/integer.v, vlib/math/big/special_array_ops.v
- examples: add pidigits.v
- optimise math.big's Integer divide a bit
=> examples: examples: add pidigits.v; optimise math.big's Integer divide a bit

vlib/v/util/diff/diff.v
=> util: improve detection for opendiff when automatically searching difftools

vlib/builtin/string.v
=> builtin: cleanup `compare_strings` functions

cmd/tools/vpm/vcs.v
The PR should resolve https://github.com/vlang/v/pull/21216#issuecomment-2049974869
=> vpm: check for git version before adding `--also-filter-submodules` flag

vlib/crypto/ed25519/README.md
=> Fix typo in readme. "proted" to "ported"

cmd/tools/vtest-self.v
=> tools: revise `vtest-self.v`: remove dead paths, fix json2 essential test path

cmd/tools/vtest-self.v
=> test: enable http tests that were ignored due to malfunctions that have been fixed

vlib/v/parser/expr.v, vlib/v/parser/for.v, vlib/v/parser/parser.v, vlib/v/tests/struct_init_on_for_expr_test.v
=> parser: allow struct init on for expr (iterator)

cmd/tools/vdoc/html.v, cmd/tools/vdoc/tests/testdata/output_formats/main.ansi, cmd/tools/vdoc/tests/testdata/output_formats/main.text, vlib/v/doc/utils.v
=> vdoc: update `merge_doc_comments` so recent fixes extend to all output formats

cmd/tools/vretry.v
=> tools: fix typo in vretry.v

vlib/.vdocignore
=> vdoc: remove obsolete entries from `.vdocignore`

vlib/v/checker/assign.v, vlib/v/checker/tests/array_assign_err.out, vlib/v/checker/tests/array_or_map_assign_err.out
The PR would resolve a TODO, turning in a warning into an error.
=> checker: turn array assign warning into error

cmd/tools/vwhere/finder.v, cmd/tools/vwhere/finder_utils.v, cmd/tools/vwhere/vwhere.v
cleans up and makes minor improvements to the tool.
=> tools: cleanup vwhere

vlib/v/gen/c/fn.v
=> cgen: fix hot code reloading on windows

.github/workflows/bootstrapping_ci.yml, .github/workflows/bootstrapping_works_ci.yml
=> ci: update bootstrapping workflow, reactivate `v up` testing, cleanup

.github/workflows/linux_ci.yml, .github/workflows/sanitized_ci.yml
=> ci: enable native code gen check, and msvc cleancode test

vlib/v/checker/checker.v, vlib/v/tests/last_stmt_semicolon_or_expr_test.v
=> checker: ignore last semicolon on or-expr

vlib/v/pref/pref.c.v
Makes minor changes:
- Performing a clone of the args that follow the current is not required for any cycle in the loop therefore they are passed directly where required.
- Removes obsolete / inconsistent use of continue statements in exhaustive branches.
=> pref: make minor performance related changes / simplify

vlib/v/pref/pref.c.v
Things that happen when things go fast 🏎️
=> pref: fix conflict happend due to simultaneous merge of  #21377 and #21379

vlib/cli/command.v, vlib/cli/command_test.v, vlib/cli/flag.v
Attempts to create an easier-to-understand base for working with the processes updated in the PR.
=> cli: simplify flag parsing

vlib/v/pref/pref.v, vlib/v/pref/pref_test.v
- Adds tests
- Removes a loop condition in the else block that is never true since all the items are handled in the match arms before. It is likely an older piece of code.
The commits after `update tests` are split to build up on each other in case this helps to simplify reviewing.
=> v.pref: improve maintainability and performance for parsing args; add tests

cmd/tools/vdoc/tests/vdoc_file_test.v, vlib/v/fmt/fmt_bin2v_test.v, vlib/v/fmt/fmt_keep_test.v, vlib/v/fmt/fmt_test.v, vlib/v/fmt/fmt_vlib_test.v, vlib/v/gen/c/coutput_test.v, vlib/v/gen/js/program_test.v, vlib/v/slow_tests/repl/runner/runner.v
Utilizes new diff functions. Integrated based on #21431.
=> v: utilize new diff functions p2

vlib/v/checker/checker.v, vlib/v/gen/c/cgen.v
Add support to specific the section for global var. (function is already supported)
=> v: add @[_linker_section] for global variable

vlib/v/gen/c/fn.v, vlib/v/tests/array_delete_last_test.v
=> cgen: fix array.delete_last call generation

vlib/v/gen/c/cgen.v, vlib/v/tests/option_ptr_unwrap_test.v
=> cgen: fix option ptr unwrapping

.github/.prettierrc, .github/ISSUE_TEMPLATE/documentation.yml, .github/dependabot.yml, .github/workflows/debug.yml, .github/workflows/docs_ci.yml, .github/workflows/macos_ci.yml, .github/workflows/paths_ci.yml, .github/workflows/prebuilt.yml, .github/workflows/sanitized_ci.yml, .github/workflows/vinix_ci.yml, .github/workflows/workflow_lint.yml
- Adds a formatting check to help with keeping a consistent code style. 
- Resolves non-conformity formatting.
It would only run on changes to .yml files and takes a few seconds.
=> ci: add a linter for the .yml workflow files

cmd/tools/vvet/vet_test.v
A file updated that got missed somewhere between switching branches.
=> tools.vet: update diff comparison in `vet_test.v`

vlib/math/big/special_array_ops.v
=> math.big: fix typo in special_array_ops.v

vlib/toml/decoder/decoder.v
=> toml: simplify `decode_quoted_escapes`

vlib/v/checker/checker.v, vlib/v/checker/struct.v, vlib/v/checker/tests/no_heap_struct.out, vlib/v/tests/heap_struct_member_ptr_test.v
=> checker: fix wrong checking for heap struct

thirdparty/sokol/sokol_audio.h, vlib/sokol/audio/audio.c.v
This just adds the configuration needed for compiling the audio example.
=> examples/audio: fix audio example to work on FreeBSD

vlib/v/gen/c/cgen.v, vlib/v/gen/c/struct.v, vlib/v/tests/array_fixed_struct_field_test.v
=> cgen: fix array fixed initialization on struct from call

vlib/v/gen/c/index.v, vlib/v/tests/indexexpr_or_test.v
=> cgen: fix indexexpr with orexpr

vlib/v/gen/c/struct.v, vlib/v/tests/generic_struct_init_ptr_test.v
=> cgen: fix generic struct init when it is a reference &T

vlib/v/parser/module.v, vlib/v/parser/tests/import_alias_selective_fn_used.vv, vlib/v/parser/tests/import_alias_selective_symbol_used.out, vlib/v/parser/tests/import_alias_selective_symbol_used.vv
=> parser: register selective import aliases as used

vlib/v/gen/c/match.v, vlib/v/tests/match_expr_result_test.v
=> cgen: fix generated code for handling fn call with result/option return on match conditional

vlib/v/parser/parser.v, vlib/v/tests/enum_flag_from_test.v, vlib/v/tests/flag_from_test.v
=> parser: allow multi flag value acceptable to enum.from()

vlib/v/gen/js/js.v
This PR contains only code quality changes. Output remains identical.
- use new library and language features like smartcasting and the `ast.IndexExpr.is_map` field
- eliminate a lot of dead or duplicate branches
- add some additional informative comments
- add TODO comments
- overall reduce redundant code and nesting
=> jsgen: general code cleanup

vlib/v/gen/c/str.v, vlib/v/tests/print_void_ret_test.v
=> cgen: fix missing call generated when used on print call

vlib/v/ast/ast.v
=> ast: add comment showing what `blank_ident` represents

vlib/v/gen/js/README.md
Add a README file with some information I believe is valuable to new developers wanting to contribute to the jsgen module.
=> jsgen: add README.md

vlib/v/checker/tests/missing_concrete_type_err.out, vlib/v/checker/tests/missing_concrete_type_err.vv, vlib/v/parser/parse_type.v, vlib/v/parser/parser.v
=> checker: fix missing concrete type checking on generic type specifier

examples/vweb_fullstack/src/auth_services.v
=> examples: check array length before access

cmd/tools/vpm/settings.v
=> vpm: don't write logfiles in CI runs

vlib/v/gen/c/cgen.v, vlib/v/tests/option_or_expr_with_non_opt_test.v
=> cgen: fix or expr with non option fn call return

vlib/veb/README.md
Aligns the module name in veb docs
=> veb: update import name in docs

vlib/v/checker/checker.v
This PR makes a minor cleanup in expr().
=> checker: minor cleanup in expr()

vlib/veb/auth/README.md, vlib/veb/auth/auth.v
also added small section about security considerations
=> veb.auth: use constant time compare

vlib/v/checker/checker.v, vlib/v/checker/tests/anon_fn_arg_type_err.out, vlib/v/parser/tests/closure_not_declared.out
=> checker: update checker.v

vlib/v/checker/checker.v, vlib/v/gen/c/assign.v, vlib/v/gen/c/fn.v, vlib/x/json2/decoder.v, vlib/x/json2/tests/decode_map_test.v
=> cgen,x.json2: fix generic map decoding

vlib/v/checker/checker.v, vlib/v/tests/if_comptime_check_const_test.v
=> checker: fix if cond using const with $d() def

vlib/builtin/string.v, vlib/builtin/string_test.v
Reimplements the method based on the recent comments (https://github.com/vlang/v/pull/21736#discussion_r1654092934)
=> builtin: improve snake to camel case conversion

vlib/v/checker/comptime.v, vlib/v/checker/if.v
This PR change `comptime_if_branch()` to `comptime_if_cond()`.
=> checker: change comptime_if_branch() to comptime_if_cond()

vlib/v/ast/ast.v, vlib/v/checker/match.v, vlib/v/gen/c/match.v, vlib/v/gen/c/testdata/global_export_nix.c.must_have, vlib/v/parser/parse_type.v, vlib/v/tests/enum_test.v, vlib/v/transformer/transformer.v
Fix https://github.com/vlang/v/issues/21777
=> transformer: handle `enum_variant = some_const + 10` (fix #21777)

vlib/v/ast/types.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/dumpexpr.v, vlib/v/tests/array_fixed_empty_struct_test.v
=> cgen: fix array fixed empty struct code generated on clang

vlib/v/checker/assign.v, vlib/v/checker/if.v, vlib/v/tests/generic_if_ret_test.v
=> checker: fix assign generic if expr

examples/gg/fire.v
this PR adds a `gg` example showcasing a pixelated animation of fire
=> examples: add `gg/fire.v`

.github/workflows/v_apps_and_modules_compile_ci.yml
This PR restore v_apps_and_modules_compile_ci.yml.
=> ci: restore v_apps_and_modules_compile_ci.yml

examples/macos_tray/tray.v
=> examples: update macos_tray example to cleanly compile

doc/docs.md
I noticed that the documentation didn't mention some of the legal values for builtin compile-time options.  I think these updates are accurate and complete.
=> doc: update full list of builtin compile options

vlib/v/tests/closure_generator_test.v
I noticed that on macos, the max_params value was limited to 9 instead of 16 with the comment that 10 or more was not supported on m1.
In my experimentation, only the closure test on strings was limited and that the other, integer types, worked when max_params was 16.
This compiler limitation also did not appear to be specific to macos.  I found that on FreeBSD, when using the clang compiler on an arm64 machine, I needed to limit the string tests to 9 but the other integer types would work all the way up to 16, and even a little beyond 16 but I left the upper bound at 16 for them.
When using gcc on FreeBSD, I could let max_params be 16 for the string tests.  Also testing with clang on FreeBSD on amd64, I could let max_params be 16 for the string tests.
Since there was some special …
=> v/tests: fix handling of string type closure test

cmd/tools/vrepl.v
=> vrepl: cleanup in vrepl.v

cmd/tools/vrepl.v
This PR makes a minor cleanup in current_source_code().
=> vrepl: minor cleanup in current_source_code()

vlib/v/ast/table.v, vlib/v/gen/c/if.v, vlib/v/tests/fn_generic_resolve_test.v
=> table: fix high order generic func resolution

cmd/tools/vrepl.v
This PR makes a minor cleanup in run_repl() (related #21879).
=> vrepl: minor cleanup in run_repl() (related #21879)

vlib/v/gen/c/auto_str_methods.v, vlib/v/tests/map_value_ref_interp_test.v
=> cgen: fix missing & when map has value ref

vlib/v/checker/checker.v, vlib/v/tests/modules/sub/foo/c/foo.v, vlib/v/tests/modules/sub/foo/const.v, vlib/v/tests/modules/sub/global_fixed_array_test.v
=> checker: fix global fixed array key resolution when it is a constant ident

examples/gg/raycaster.v
Demonstrates how raycasting works. The left side shows
the 2D layout of the walls and player. The green lines
represent the field of view of the player.
The right side is a simple 3D projection of the field
of view.
There is no collision detection so yes, you can walk
through walls.
Watch https://www.youtube.com/watch?v=gYRrGTC7GtA to
learn more on how this code works. There are some silly
digression's in the video but the tech content is spot on.
=> Add raycaster.v  demo to gg examples

vlib/arrays/arrays.v, vlib/arrays/arrays_fold_test.v
=> vlib: fix arrays.fold with array type

vlib/v/gen/c/cgen.v, vlib/v/tests/option_ret_ptr_generic_test.v
=> cgen: fix generic option/result reference return

vlib/v/fmt/align.v
This PR change align threshold as dynamic.
=> fmt: change align threshold as dynamic

vlib/gg/gg.c.v
=> gg: reset ctx.mouse_d? and ctx.scroll_? at the end of each frame (fix #21945)

vlib/v/gen/c/auto_str_methods.v, vlib/v/gen/c/cgen.v, vlib/v/tests/generic_sumtype_repeated_test.v
=> cgen: fix generic sumtype with repeated concrete type

vlib/json/json_sumtype_test.v
Increased test cases before enabling sumtype decode in all json libraries
=> json: increased test cases before enabling sumtype decode in all json libraries

vlib/v/TEMPLATES.md
Documentation updated: Described how to use @ as a normal char inside a template.
=> tmpl: documentation

vlib/v/gen/c/array.v, vlib/v/gen/c/cgen.v, vlib/v/tests/closure_fn_arg_in_map_test.v
=> cgen: fix map with closure var fn

vlib/v/gen/c/cgen.v, vlib/v/tests/interface_var_selector_test.v
=> cgen: fix selector with interface var

examples/gg/path_finding_algorithm_visualizer/aStar.v, vlib/builtin/string_interpolation.v, vlib/encoding/csv/README_csv_reader.md, vlib/v/ast/ast.v, vlib/v/fmt/align.v, vlib/v/fmt/fmt.v, vlib/v/fmt/struct.v, vlib/v/fmt/tests/struct_init_with_comments_keep.vv, vlib/v/fmt/tests/struct_init_with_newline_and_comments_keep.vv, vlib/v/parser/struct.v, vlib/v/tests/option_ptr_init_empty_test.v
This PR cleanup fields alignment and add ignore_newline config.
=> fmt: cleanup fields alignment and add ignore_newline config

doc/docs.md
Change annotations of old syntax to the new one
=> docs: update old [anon] -> @[anon]

vlib/x/json2/decoder2/decode.v
Just some doc and renaming json_data to json
=> x.json2.decoder2: rename fields, add more comments

cmd/tools/bench/wyhash.v, cmd/tools/changelog_helper.v, cmd/tools/fast/fast.v, cmd/tools/modules/testing/common.v, cmd/tools/modules/testing/output.v, cmd/tools/oldv.v, cmd/tools/regress.v, cmd/tools/test_if_v_test_system_works.v, cmd/tools/vbug.v, cmd/tools/vbuild-tools.v, cmd/tools/vcheck-md.v, cmd/tools/vdoctor.v, cmd/tools/vrepeat.v, cmd/tools/vrepl.v, cmd/tools/vself.v, cmd/tools/vtest-all.v, cmd/tools/vtest-cleancode.v, doc/docs.md, vlib/x/crypto/chacha20poly1305/chacha20poly1305_test.v, vlib/x/templating/dtm/tmpl.v
This PR change empty comment to newline.
=> all: change empty comment to newline

vlib/builtin/result.v, vlib/picohttpparser/request_test.v
This PR cleanup interface IError.
=> builtin: cleanup interface IError

vlib/v/gen/c/cgen.v, vlib/v/gen/c/for.v, vlib/v/tests/array_fixed_for_loop_test.v
=> cgen: fix for loop with array fixed returned from fn

vlib/v/gen/c/auto_free_methods.v, vlib/v/tests/option_free_method_test.v
=> cgen: fix free method for option fields

vlib/v/gen/c/auto_free_methods.v, vlib/v/tests/free_method_test.v
=> cgen: fix auto free method for option map

doc/docs.md
docs: Options/results when returning multiple values
=> docs: Options/results when returning multiple values

vlib/v/parser/parse_type.v, vlib/v/parser/parser.v
This PR cleanup using `token.is_next_to()`.
=> parser: cleanup using token.is_next_to()

vlib/time/parse.c.v
=> time: update parse_format comment description in parse.c.v

vlib/v/util/util.v
This PR cleanup check_module_is_installed().
- `pub fn check_module_is_installed(modulename string, is_verbose bool, need_update bool) !bool {...}`
- Cancel the update operation every time if `need_update = false`.
=> util: cleanup check_module_is_installed(), do not run automatically updates of modules, just because their v.mod is present.

vlib/v/checker/check_types.v, vlib/v/checker/fn.v, vlib/v/checker/return.v, vlib/v/comptime/comptimeinfo.v, vlib/v/gen/c/fn.v, vlib/v/tests/generic_lambda_expr_test.v
=> checker: fix generic lambda type binding resolution

.github/workflows/v_apps_and_modules_compile_ci.yml
This PR restore verifying v_analyzer format.
=> ci: restore verifying v_analyzer format

doc/docs.md
=> doc: fix minor typos in the memory management section

vlib/v/ast/table.v, vlib/v/tests/interface_generic_implements_test.v
=> cgen,table: fix generic interface implements

vlib/sync/stdatomic/atomic_test.v
syncronization -> synchronization
=> sync: update atomic_test.v

vlib/veb/README.md
=> veb: fix vweb_livereload reference to veb_livereload

vlib/builtin/array.v
- **docs: add more details to the newly added `-compress` section**
- **builtin: small cleanup in array.free() (make debugging easier)**
=> builtin: small cleanup in array.free() (make debugging easier)

vlib/veb/README.md
=> veb: fix a few minor errors in the veb README.md

vlib/v/gen/c/index.v, vlib/v/tests/builtin_arrays/array_of_fns_index_call_with_embeded_array_call_test.v
This PR fix array of fns index call with embeded array index (fix #17381).
- Fix array of fns index call with embeded array index.
- Add test.
```v
fn max_speed(functions []fn (int) int, g fn (int) int, end_time int) int {
mut s := [0]
mut gears := []int{len: end_time, init: 0}
for t in 0 .. end_time {
stay_in_gear_speed := if t - 1 >= 0 { functions[gears[t - 1]](s[t - 1]) } else { 0 }
shift_gear_speed := if t - 2 >= 0 { functions[gears[t - 2] + 1](g(s[t - 2])) } else { 0 }
if stay_in_gear_speed > shift_gear_speed {
gears[t] = if t - 1 >= 0 { gears[t - 1] } else { 0 }
s << stay_in_gear_speed
} else {
gears[t] = if t - 2 >= 0 { gears[t - 2] } else { 0 } + 1
s << shift_gear_speed
}
}
return s[end_time]
}
@[direct_array_access]
fn max_speed_direct_access(functions []fn (int) int, g fn (int) …
```
=> cgen: fix array of fns index call with embeded array index (fix #17381)

.github/workflows/v_apps_and_modules_compile_ci.yml
This PR restore v_apps_and_modules_compile_ci.yml.
=> ci: restore the `Format vlang/v-analyzer` task in v_apps_and_modules_compile_ci.yml

vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/index.v, vlib/v/tests/indexexpr_with_assign_test.v
=> cgen: fix code generated for indexexpr with complex assigning

vlib/v/gen/c/fn.v, vlib/v/gen/c/testdata/c_ident_for_ptr_arg.c.must_have, vlib/v/gen/c/testdata/c_ident_for_ptr_arg.vv
=> cgen: fix code for C ident when ptr is expected

vlib/json/json_decode_embed_test.v, vlib/v/gen/c/json.v
=> json: fix decode struct with embed

vlib/json/json_embed_test.v, vlib/json/json_encode_embed_test.v, vlib/v/gen/c/json.v
=> json: fix json encode/decode with embed support

examples/gg/stars.v
(FPS counter is from `-d show_fps`)
=> examples: make `gg/stars.v` run on Android

vlib/v/gen/c/fn.v, vlib/v/gen/c/testdata/alias_char_ptr_to_ptr.c.must_have, vlib/v/gen/c/testdata/alias_char_ptr_to_ptr.vv
=> cgen: fix codegen for alias to charptr passed as ptr

vlib/v/parser/tmpl.v, vlib/v/tests/tmpl/if_cond.txt, vlib/v/tests/tmpl_if_cond_test.v, vlib/v/tests/tmpl_test.v
=> tmpl: fix extra newline added on @if-@else-@end block

.github/workflows/hub_docker_ci.yml
Github action to checkout vlang/docker repo and build docker images for amd64 and arm64 platforms.
Manual trigger for now - can be adjusted latter.
=> Build docker images action

.github/workflows/hub_docker_ci.yml
Fix docker build action by adding context path to current directory.
=> Hub docker action fix

vlib/v/gen/c/fn.v, vlib/v/tests/fns/variadic_sumtype_test.v
=> cgen: fix variadic arg var passed to another call which expects variadic

vlib/v/gen/c/array.v
This PR cleanup in gen_array_insert()/gen_array_prepend() (related #22324).
=> cgen: cleanup in gen_array_insert()/gen_array_prepend() (related #22324)

vlib/v/gen/c/fn.v, vlib/v/tests/fns/iface_method_fixed_arr_test.v
=> cgen: fix codegen for interface method call which returns array fixed

vlib/v/checker/checker.v, vlib/v/checker/fn.v
This PR cleanup checking array method call.
=> checker: cleanup checking array method call

vlib/encoding/csv/csv_reader_eol_test.v, vlib/encoding/csv/reader.v
=> encoding.csv: fix reading when there is no line ending

vlib/v/gen/c/fn.v
This PR makes a minor cleanup in method_call().
=> cgen: minor cleanup in method_call()

vlib/v/ast/ast.v, vlib/v/checker/checker.v, vlib/v/parser/parser.v, vlib/v/parser/tests/global_reserved_name_err.out, vlib/v/parser/tests/global_reserved_name_err.vv
=> checker: fix missing reserved name check on global declaration

vlib/v/gen/c/fn.v
This PR refactor gen_array_method_call().
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmY5N2MwYzQzYjBiYWU0OTU4YzI2OTUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.Wi39uCDn9VRZpYaPfQsvxAiKgU4_KOjf7QunzELpA_Q">Huly&reg;: <b>V_0.6-20816</b></a></sub>
=> cgen: refactor gen_array_method_call()

vlib/v/ast/types.v, vlib/v/checker/containers.v, vlib/v/gen/c/infix.v, vlib/v/tests/aliases/alias_array_push_test.v
Fix #22374
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZiNDc0ZjQzYjBiYWU0OTU5NjNhNmEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.Bh6wPh9be3iopjYYWWzEz4WgQOpsEPbh0ST9TXqmP20">Huly&reg;: <b>V_0.6-20837</b></a></sub>
=> cgen: fix array to alias push operation

vlib/x/json2/decoder2/decode.v
Not new features, just clean up
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZiMjhjZTQzYjBiYWU0OTU5NGFjNTgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.6QngUR_uWvOIzK-4Z4isJM-_65KcdDp3-aHhWb1P61M">Huly&reg;: <b>V_0.6-20835</b></a></sub>
=> x.json2.decoder2: clean up

vlib/v/gen/c/fn.v
This PR cleanup in method_call().
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZiZjk0ODQzYjBiYWU0OTU5ZTk1ZDEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.lNUTFjVb821POuMi0KatWe2fdJlIqRDuSmv0EbE83uI">Huly&reg;: <b>V_0.6-20844</b></a></sub>
=> cgen: cleanup in method_call()

vlib/builtin/array.v, vlib/builtin/array_d_gcboehm_opt.v
This PR cleanup push_many()/push_many_noscan().
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZjMDQ1ZDQzYjBiYWU0OTU5ZjExZDYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.spXT_d86yID3rDBQpCqV2GvaOhP5aO7hofm_IAUXTDQ">Huly&reg;: <b>V_0.6-20845</b></a></sub>
=> builtin: cleanup push_many()/push_many_noscan()

vlib/x/json2/decoder.v, vlib/x/json2/tests/decode_array_array_test.v
Fix #22362
PS: [][]?type is not working
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZhYTFhNDQzYjBiYWU0OTU4ZTZlNjkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.X5alUUz1Ynxi_sGfhewZV_gvWm3fVWFuxvTHHI6CMuM">Huly&reg;: <b>V_0.6-20828</b></a></sub>
=> json2: add support to array of array

vlib/v/checker/match.v
This PR cleanup in match_expr().
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZmOTE2NzQzYjBiYWU0OTVjYzYzNWQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.Sp7zFhhChR182MtfU7P5Ej1tI4-zVwT3IJb64E34hBE">Huly&reg;: <b>V_0.6-20869</b></a></sub>
=> checker: cleanup in match_expr()

vlib/toml/any.v, vlib/toml/tests/default_value_test.v, vlib/toml/toml.v
As #22181 suggested, add default values support when decoding/reflecting TOML to struct.
```v
struct Test {
val_string   string        = 'abcd'
val_bool     bool          = true
val_int      int           = 123
val_i64      i64           = 1234
val_u64      u64           = 12345
val_f32      f32           = 100.1
val_f64      f64           = 1000.1
val_datetime toml.DateTime = toml.DateTime{'1980-07-11 21:23:42.123'}
val_date     toml.Date     = toml.Date{'1977-07-07'}
val_time     toml.Time     = toml.Time{'11:11:11.111'}
}
```
=> toml: add reflect/decode struct default value support

vlib/v/checker/autocomplete.v, vlib/v/checker/check_types.v, vlib/v/checker/checker.v, vlib/v/checker/comptime.v, vlib/v/checker/fn.v
- **checker: reduce allocations in Checker.register_trace_call/2**
- **checker: pass all ast.Fn args by reference explicitly**
=> checker: reduce allocations part 2

vlib/v/parser/parse_type.v, vlib/x/json2/json2.v, vlib/x/json2/tests/json2_test.v
Allow to parse a value of multidimensional array in map_from.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA0MWMwNWI5ODBmNDFkYjY2ZDEzNzgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.ecY4FQssL29UQnX09bTAucVsRPNB7PAvbRID9DKSQ80">Huly&reg;: <b>V_0.6-20903</b></a></sub>
=> x.json2: allow parsing a value from a multidimensional array in map_from

vlib/v/ast/types.v, vlib/v/checker/struct.v, vlib/v/checker/tests/struct_scope_err.out, vlib/v/checker/tests/struct_scope_err.vv, vlib/v/parser/struct.v
Fix #22437
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA1MjQ1OWI5ODBmNDFkYjY3MDU2M2UiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.TU3l4DKYu1F1bicr0oSYRI5qZMEiyKARJoVgOBUj2L8">Huly&reg;: <b>V_0.6-20910</b></a></sub>
=> checker: add scope validation for struct

vlib/rand/rand.c.v
- **rand: tag with `@[direct_array_access]` some frequently used functions, that are already debugged**
=> rand: tag with `@[direct_array_access]` some frequently used functions, that are already debugged

vlib/v/checker/fn.v, vlib/v/gen/c/fn.v, vlib/v/parser/fn.v, vlib/v/tests/va_arg_test.v
Fix #20636
Improving C interop 👍🏻
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBlNWRiMThkY2MwMDM2MTU1YjAyMWQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.oRJFuFrBDcLjb21_hH6ys8CqOVBbOtOoItWu04JhtlA">Huly&reg;: <b>V_0.6-20984</b></a></sub>
=> v: allow `C.va_arg(Type, va)`

vlib/v/ast/scope.v, vlib/v/comptime/comptimeinfo.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/comptime.v, vlib/v/gen/c/fn.v, vlib/v/tests/comptime/comptime_call_method_closure_test.v
=> cgen: fix comptime for method with `$method` as inherited var

vlib/v/ast/ast.v, vlib/v/checker/checker.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/comptime.v, vlib/v/gen/js/js.v, vlib/v/parser/parser.v, vlib/v/tests/comptime/comptime_generic_unaliased_typ_test.v
=> v: added `T.unaliased_typ` 

vlib/time/time_nix.c.v, vlib/v/trace_calls/tracing_calls_nix.c.v
=> time: fix clock_gettime return type

vlib/v/ast/types.v, vlib/v/checker/if.v, vlib/v/gen/c/comptime.v, vlib/v/tests/comptime/comptime_call_is_check_test.v
=> v: allow checking method comptime signature with `is` operator

vlib/v/pref/vsh_envbang_test.v
fix https://github.com/vlang/v/issues/22562
=> v: fix vsh_envbang_test

doc/docs.md
Be more verbose about how deprecation works. Document learnings and missing hints discovered through https://github.com/vlang/v/pull/22560
=> doc: explain deprecation process

vlib/v/checker/fn.v, vlib/v/checker/infix.v, vlib/v/checker/tests/array_sort_err.out, vlib/v/checker/tests/qsort_external_variable_err.out, vlib/v/checker/tests/qsort_external_variable_err.vv
=> checker: check for external variable access on qsort/sorted callback

vlib/v/ast/types.v, vlib/v/gen/c/if.v, vlib/v/parser/struct.v, vlib/v/tests/options/option_struct_init_on_if_test.v
=> cgen: fix codegen for if with struct init that contains option type

vlib/v/gen/c/array.v
This PR cleanup in fixed_array_init().
=> cgen: cleanup in fixed_array_init()

vlib/v/tests/c_structs/cstruct_alias.h, vlib/v/tests/c_structs/cstruct_alias_test.v
Fix #22586
Added test to confirm fix.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE1MThjYzJlYjk5ZmZhYzRiMjY5OWQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0._JUyBP57W9xYJ2etMcq_M2uzQ5W-H6QluCXu0DvZq1k">Huly&reg;: <b>V_0.6-21049</b></a></sub>
=> test: add test for fix #22586

vlib/v/checker/comptime.v, vlib/v/tests/comptime/comptime_unaliased_typ_test.v
Fix #22587
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE1MDQyYjJlYjk5ZmZhYzRiMWZjZWUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.FS67jOa86OUStZ8wqY92J73p7Sp11jlgsg9zLGPqOB0">Huly&reg;: <b>V_0.6-21047</b></a></sub>
=> checker: fix `T.unaliased_typ` if branch evaluation

vlib/x/json2/decoder2/tests/decode_object_test.v
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE3MGMwNjRjMjRlYTI4ODIwNGM2OTEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.Xgz_AX9ydInbfXNa1oC4VrFkfesRLBQ-1RnmG-YtwEE">Huly&reg;: <b>V_0.6-21064</b></a></sub>
=> test: decode pretty json

vlib/v/checker/assign.v, vlib/v/checker/fn.v, vlib/v/gen/c/assign.v, vlib/v/gen/c/fn.v, vlib/v/tests/generics/generic_fn_param_test.v
Fix #22612
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE4ZjAwZmYwMmQ4YTAzZmIyZmM2Y2QiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.vbHT0fhOvgyDPpR-B8zrrRCQhKHQtSKHjhLB5bupqgk">Huly&reg;: <b>V_0.6-21076</b></a></sub>
=> checker: fix generic fn call return type resolve on var assignment

vlib/builtin/fixed_array_map_test.v, vlib/v/checker/fn.v, vlib/v/gen/c/array.v, vlib/v/gen/c/fn.v
This PR implement fixed array method map().
- Implement fixed array method map().
- Add test.
```v
fn main() {
a := [1, 2, 3]!
b1 := a.map(it * 2)
println(b1)
assert b1 == [2, 4, 6]!
b11 := a.map(|x| x * 2)
println(b11)
assert b11 == [2, 4, 6]!
b2 := a.map('${it}')
println(b2)
assert b2 == ['1', '2', '3']!
b22 := a.map(|x| '${x}')
println(b22)
assert b22 == ['1', '2', '3']!
b3 := a.map(it + 2)
println(b3)
assert b3 == [3, 4, 5]!
b33 := a.map(|x| x + 2)
println(b33)
assert b33 == [3, 4, 5]!
}
PS D:\Test\v\tt1> v run .      
[2, 4, 6]
[2, 4, 6]
['1', '2', '3']
['1', '2', '3']
[3, 4, 5]
[3, 4, 5]
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFhNmMyYmYwMmQ4YTAzZmIzMzliOTEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6Ii …
=> checker, cgen: implement fixed array method map()

vlib/builtin/fixed_array_sort_test.v, vlib/v/checker/checker.v, vlib/v/checker/fn.v, vlib/v/gen/c/array.v, vlib/v/gen/c/fn.v
This PR implement method sort()/sorted() for fixed array.
- Implement method sort()/sorted() for fixed array.
- Add test.
```v
struct User {
age  int
name string
}
fn test_fixed_array_sort() {
mut a := ['hi', '1', '5', '3']!
a.sort()
assert a == ['1', '3', '5', 'hi']!
mut nums := [67, -3, 108, 42, 7]!
nums.sort()
assert nums == [-3, 7, 42, 67, 108]!
nums.sort(a < b)
assert nums == [-3, 7, 42, 67, 108]!
nums.sort(b < a)
assert nums == [108, 67, 42, 7, -3]!
mut users := [User{22, 'Peter'}, User{20, 'Bob'}, User{25, 'Alice'}]!
users.sort(a.age < b.age)
assert users[0].age == 20
assert users[1].age == 22
assert users[2].age == 25
assert users[0].name == 'Bob'
assert users[1].name == 'Peter'
assert users[2].name == 'Alice'
users.sort(a.age > b.age)
assert users[0].age == 25
assert users[1].age …
```
=> checker, cgen: implement method sort()/sorted() for fixed array

vlib/v/checker/checker.v, vlib/v/gen/c/cgen.v, vlib/v/tests/selector_generic_fn_test.v
Fix #22657
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFkODI2ZmYwMmQ4YTAzZmIzNDExYjQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.vfXR2n0nsIdgBAdtswST1MWdm8o2C8fU5nTLPiGwsuI">Huly&reg;: <b>V_0.6-21114</b></a></sub>
=> checker: generic selector with fn

GNUmakefile
Fixes #22673
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFlOWVmZDI3Y2M3NjgxYzYyMjMxYzkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0._ugiUA2vAM8XSAPNGfJMJLW7Y8bgiqM1ZzMpYjcaJDE">Huly&reg;: <b>V_0.6-21124</b></a></sub>
=> GNUmakefile: fix `make` with msys

vlib/v/checker/assign.v, vlib/v/checker/fn.v, vlib/v/tests/comptime/comptime_generic_container_test.v
Fix #22693
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzIyMmQ2NDI3Y2M3NjgxYzYyM2E3ZjEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.6t_OpEOsAGW_AE0EBfRkHhWEnndkBvFnvsHX8vst0RY">Huly&reg;: <b>V_0.6-21147</b></a></sub>
=> checker: fix generic resolve comptime generic var

vlib/json/json_encode_ptr_test.v, vlib/v/gen/c/json.v
Fix #22717
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzIzZjRkMjI3Y2M3NjgxYzYyNTdkYWQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0._hW0JOkHm9pTgnS006AMzY8IAfLgzeRKGF00kriNWCI">Huly&reg;: <b>V_0.6-21167</b></a></sub>
=> json: fix ptr field encoding

vlib/v/gen/c/array.v
This PR cleanup in array.v.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzI0YTM2MDI3Y2M3NjgxYzYyNTkxMjEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.Wkg_9hK6u54OxZefA2P9z5jphud6Mz7TJtOkLNcGVwI">Huly&reg;: <b>V_0.6-21170</b></a></sub>
=> cgen: cleanup in array.v

vlib/x/json2/decoder2/decode.v, vlib/x/json2/decoder2/tests/decode_array_test.v, vlib/x/json2/decoder2/tests/decode_object_test.v
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJhOTBmZGU3Y2M1YTc4NTQyODkxNDAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.Q1bE96fVvp2-EbHmLrPLx3HCrCFxc-KeyOzyGlPsvKE">Huly&reg;: <b>V_0.6-21218</b></a></sub>
=> x.json2.decoder2: update-with-new-master-after-22751

cmd/tools/vast/vast.v, vlib/v/ast/ast.v, vlib/v/ast/str.v, vlib/v/checker/checker.v, vlib/v/checker/fn.v, vlib/v/fmt/fmt.v, vlib/v/gen/c/fn.v, vlib/v/parser/fn.v, vlib/v/tests/fns/aliased_static_method_test.v
Fix #22773
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJjYmQwN2U3Y2M1YTc4NTQyOTRmYWQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.n_-tXbvOun38quxfBxlgt0LdzxSDYEvWuvu_3SRE2qI">Huly&reg;: <b>V_0.6-21233</b></a></sub>
=> parser,checker: improve static method call resolution

.github/workflows/vinix_ci.yml
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzMwMThjYWU3Y2M1YTc4NTQyYTRlYTUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.DiL5Fy-G6eWkpJXzSZyZw3GIAB0aqPjyxqB0X7I_0KY">Huly&reg;: <b>V_0.6-21263</b></a></sub>
=> ci: fix vinix_ci.yml for latest Vinix commits

doc/docs.md
Added implements keyword into V's keyword list so it appears in Appendix I: Keywords.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNhMjM0ZWU3Y2M1YTc4NTQyZDhkODAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.YnNBTrQjfcRoGLkrad5iPDT6FN32dyWjyQtPx_TxF6Y">Huly&reg;: <b>V_0.6-21332</b></a></sub>
=> Update docs.md (Added implements keyword)

vlib/v/checker/checker.v, vlib/v/checker/if.v, vlib/v/checker/tests/assign_type_mismatch_with_generics_err.out, vlib/v/checker/tests/assign_type_mismatch_with_generics_err.vv, vlib/v/checker/tests/option_ptr_without_unwrapp_err.out, vlib/v/checker/tests/option_ptr_without_unwrapp_err.vv, vlib/v/gen/c/cgen.v, vlib/v/tests/generics/generics_chans_select_test.v, vlib/v/tests/options/option_selector_unwrap_test.v, vlib/v/tests/options/option_selector_unwrap_types_test.v, vlib/v/tests/options/option_unwrap_test.v
Fix #22892
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNhNTBlM2U3Y2M1YTc4NTQyZDk1OGYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.9sxQVkpZg4nCDnHbLj5ftvGGPh3yprk_jHKesUnXXio">Huly&reg;: <b>V_0.6-21338</b></a></sub>
=> v: add selector option unwrapping on if `!= none`

cmd/tools/modules/testing/common.v, cmd/tools/modules/testing/output_normal.v, cmd/tools/vcreate/vcreate_new_test.v, cmd/tools/vtest_test.v
With this PR:
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNkYzhkMmU3Y2M1YTc4NTQyZTUwNzEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.auBSkRmG3ZSHOdSz9nlwYaTq-lhDdTCPQr8XxQ7HVaM">Huly&reg;: <b>V_0.6-21364</b></a></sub>
=> tools: cleanup the output for failing tests with `v test .`

doc/docs.md
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQxYjFhM2QyZWY0Y2JjYzQ2ODFjMTciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.SqpgRRSHPQcVal9Lxct3P7MrD97cUQi-p2x_R6aCsiw">Huly&reg;: <b>V_0.6-21386</b></a></sub>
=> docs: Update docs.md about Enum using reserved keywords

vlib/v/gen/c/assert.v, vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/for.v, vlib/v/gen/c/index.v, vlib/v/gen/c/infix.v, vlib/v/gen/c/json.v, vlib/v/gen/c/struct.v
This PR aims to cleanup some comments generated by cgen.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQzNWIyZGQyZWY0Y2JjYzQ2ODcwOWMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.KRlc2rp2z-MfP3-Jt2m29RIUVf7PajjI6sv7OHnRnVU">Huly&reg;: <b>V_0.6-21403</b></a></sub>
=> cgen: cleanup comments

vlib/v/checker/fn.v, vlib/v/checker/tests/with_check_option/v_import_const.out, vlib/v/checker/tests/with_check_option/v_import_const.vv
=> checker: prevent panic while running `v -check file.v` (fix #22981)

vlib/json/tests/json_decode_arr_ref_test.v, vlib/v/gen/c/json.v
Fix #23007
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRhMzM3MmQyZWY0Y2JjYzQ2Y2FkNGYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.c56QOuoZMUfysBFtUZQ23unskNerHdHS0tdeg1ldWvI">Huly&reg;: <b>V_0.6-21451</b></a></sub>
=> json: fix decode codegen for []&type

vlib/x/json2/decoder2/decode.v, vlib/x/json2/decoder2/tests/decode_array_test.v, vlib/x/json2/decoder2/tests/json_sumtype_test.v
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRjYzAxNmQyZWY0Y2JjYzQ2ZDBmMDciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.WAL66TAfcQmhDQ_KY6IINegpYX5ZRIS6FS2nj6bZ2ds">Huly&reg;: <b>V_0.6-21481</b></a></sub>
=> x.json2.decoder2: fix wrong sumtype and struct decoder in array

vlib/x/json2/decoder2/tests/json_sumtype_test.v
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRkYmQwNmQyZWY0Y2JjYzQ2ZDY3YTAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.24WOJQ-__UjDl7phPA4b0bUjPxnFdZQYyg298ConM9c">Huly&reg;: <b>V_0.6-21491</b></a></sub>
=> test: include missing test for #22730

vlib/v/gen/c/cgen.v
This PR cleanup in cast_expr().
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzUxMWU0M2QyZWY0Y2JjYzQ2ZWE4ZGIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.eXVl09VvndApgu_MTu0WjVjbcz6b6kzy_dHDN5Lwkzw">Huly&reg;: <b>V_0.6-21507</b></a></sub>
=> cgen: cleanup in cast_expr()

vlib/v/markused/markused.v, vlib/v/markused/walker.v
Minor cleanup.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzUwZDM4ZGQyZWY0Y2JjYzQ2ZWExODYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.B5RTCn80yhD-ZcP-EOl_lq036RvExYKMne5Cmm1ufik">Huly&reg;: <b>V_0.6-21506</b></a></sub>
=> markused: minor cleanup

vlib/x/json2/decoder2/decode.v, vlib/x/json2/decoder2/decode_sumtype.v, vlib/x/json2/decoder2/decode_test.v, vlib/x/json2/decoder2/tests/json2_tests/decode_and_encode_struct_any_test.v, vlib/x/json2/decoder2/tests/json2_tests/decode_map_test.v, vlib/x/json2/decoder2/tests/json2_tests/decode_struct_test.v, vlib/x/json2/decoder2/tests/json2_tests/decoder_test.v, vlib/x/json2/decoder2/tests/json2_tests/encoder_test.v, vlib/x/json2/decoder2/tests/json2_tests/json2_test.v, vlib/x/json2/decoder2/tests/json2_tests/json_module_compatibility_test/json_decode_todo_test.v, vlib/x/json2/decoder2/tests/json2_tests/json_module_compatibility_test/json_test.v, vlib/x/json2/encoder.v
```sh
V cache folder /home/hitalo/.vmodules/.cache was wiped.
V tmp.c and tests folder folder /tmp/v_1000 was wiped.
SPENT   457.661 ms in decoder2.decode[Stru](json_data)!
SPENT   500.609 ms in old_json.decode(Stru, json_data)!
SPENT   511.574 ms in decoder2.decode[SumTypes](json_data)!
SPENT   515.587 ms in old_json.decode(SumTypes, json_data)!
SPENT   121.126 ms in decoder2.decode[StructType[string]](json_data1)!
SPENT   106.676 ms in old_json.decode(StructType[string], json_data1)!
SPENT   136.142 ms in decoder2.decode[StructTypeOption[string]](json_data1)!
SPENT   102.942 ms in old_json.decode(StructTypeOption[string], json_data1)!
SPENT    73.734 ms in decoder2.decode[StructType[int]](json_data2)!
SPENT   114.299 …
```
=> x.json2.decode2: minor improvements and bugfixes

vlib/v/checker/containers.v, vlib/v/tests/empty_array_push_test.v
Fix #23093
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU0YTgyM2QyZWY0Y2JjYzQ2ZjdmZmYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.ElOvHGV-kyPBHcJG47cjsSPpYiUyUZviQAUeEGkgaq8">Huly&reg;: <b>V_0.6-21534</b></a></sub>
=> checker: fix empty array append multi dims

vlib/v/gen/c/for.v, vlib/v/tests/arrays_closure_fixed_array_test.v
Fix #23075
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU0ZGUwZmQyZWY0Y2JjYzQ2ZjgyOGEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.NqHRwNMtSnumr1XaSfgag49UIkQv1_MI9qyZO_k60VE">Huly&reg;: <b>V_0.6-21539</b></a></sub>
=> cgen: fixed for in loop with generic fixed array

vlib/v/checker/checker.v, vlib/v/checker/tests/selector_generic_or_block_err.out, vlib/v/checker/tests/selector_generic_or_block_err.vv
Fix #23088
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU1N2FhZDFlMDYzMmRkMDhlMjU0OWEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.7lzLXPMPtxFJuBDpCZvcF1kfzRaI0Ha2oEq49_R5eAE">Huly&reg;: <b>V_0.6-21540</b></a></sub>
=> checker: fix selector generic or block

vlib/v/checker/infix.v, vlib/v/tests/skip_unused/array_push.vv
Fix #23110
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU2YzZlMjFlMDYzMmRkMDhlMjc5NWQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.vHYm3x_YKNpNOIn57hKUZWz7u48TKp3S0VDdgvCBXF4">Huly&reg;: <b>V_0.6-21549</b></a></sub>
=> markused: fix short program with array push only

vlib/v/checker/for.v, vlib/v/gen/c/for.v, vlib/v/tests/for_in_iterator_next_test.v
Fix #23119
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU4ZDZhYTFlMDYzMmRkMDhlMmRmNjIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.tK6Smv10kmOBaDQbCwrASDayyZHwWMcCOhrVzSEKQjk">Huly&reg;: <b>V_0.6-21564</b></a></sub>
=> checker, cgen: fix for in for interface type

.github/workflows/macos_ci.yml
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzViNGZkMTFlMDYzMmRkMDhlMzYwMGEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.jWWmtWKzooX51SFwHotvOfKtbTL8ErhLiqLqSxp3eTs">Huly&reg;: <b>V_0.6-21582</b></a></sub>
=> ci: comment out the task `V self compilation with -usecache` on macos for now

vlib/json/tests/json_prim_type_validation_test.v, vlib/v/gen/c/auto_eq_methods.v, vlib/v/gen/c/json.v, vlib/v/markused/markused.v
Fix #23021
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVhY2ViYjFlMDYzMmRkMDhlMzQ5MzMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.XigmRUC6OgaIOAHvodaPGX8o1RBh0Lk3Gn-rGwlfeRc">Huly&reg;: <b>V_0.6-21579</b></a></sub>
=> json: add primitive type validation

vlib/gg/gg.c.v, vlib/v/gen/c/auto_str_methods.v, vlib/v/gen/c/testdata/fixed_arr_compare.c.must_have, vlib/v/gen/c/testdata/fixed_arr_compare.vv
Fix.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVhZjk5YTFlMDYzMmRkMDhlMzUzODQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.-z0-I0IcponNj7YtXyknZ8keIOeHTg9w1u-CL0VAOpM">Huly&reg;: <b>V_0.6-21581</b></a></sub>
=> v: fix array fixed auto str on `-cstrict`

vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v
Clean up
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVjYWZhYzFlMDYzMmRkMDhlMzhhY2IiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.wIC1AyQvoTAQpjkGNjGbItuiEXJuANGmU5xIhzo_osc">Huly&reg;: <b>V_0.6-21589</b></a></sub>
=> cgen: cleanup unneeded comments

vlib/v/builder/cbuilder/cbuilder.v, vlib/v/builder/cbuilder/parallel_cc.v, vlib/v/gen/c/cgen.v, vlib/v/parser/v_parser_test.v
Clean up
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVkNjMwYzFlMDYzMmRkMDhlMzk3ZmQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.2-TnlSzhE-j6EIR7fRaO_jvb8GveSveCODfVdBiwGKY">Huly&reg;: <b>V_0.6-21595</b></a></sub>
=> cgen: -parallel-cc cleanup

vlib/v/ast/types.v, vlib/v/gen/c/auto_eq_methods.v, vlib/v/gen/c/infix.v, vlib/v/gen/c/str.v, vlib/v/tests/assert_alias_array_test.v
Fix #23149
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVkODlmMzFlMDYzMmRkMDhlMzlhMjkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.xm8pklxrkoX_ZPIS4UIxEZHHURsbYLoh22afOETf_fQ">Huly&reg;: <b>V_0.6-21598</b></a></sub>
=> cgen: fix assert for alias to fixed array

vlib/net/urllib/urllib.v, vlib/net/urllib/urllib_test.v
Fix issue #21061
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzYwMDkzMWYxNDRmNTg1YWU0ZDgzNGYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.RbDJ7COriIadd8uaya-CRf5QHRFK5TcCDRfRgffBLdo">Huly&reg;: <b>V_0.6-21617</b></a></sub>
=> urllib: fix parse url relative address

doc/docs.md
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzYwNjc3ZWYxNDRmNTg1YWU0ZDliNzQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.Lo_tsp_ksC3MGHaZjUHoCYpysmyKb5T84J_nKj6iddg">Huly&reg;: <b>V_0.6-21621</b></a></sub>
=> docs: add a section for static variables

vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/dumpexpr.v, vlib/v/gen/c/for.v, vlib/v/gen/c/index.v, vlib/v/tests/options/option_fn_voidptr_test.v
Fix #23170
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzYwMDNmYmYxNDRmNTg1YWU0ZDgyMzciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.twNyBvDLU-J6Ihuea-0PylsS7mLc8F1SCsfBVAgWp0s">Huly&reg;: <b>V_0.6-21616</b></a></sub>
=> cgen: fix option fn with voidptr arg

vlib/rand/cuid2/cuid2.v, vlib/rand/cuid2/cuid2_test.v
[Feature/Enhancement Request](https://github.com/vlang/v/issues/21467)
issue #21467
Ported from https://github.com/paralleldrive/cuid2
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzYwMGM1ZWYxNDRmNTg1YWU0ZDgzN2YiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.w477bsdRAmoPXNw47sEQZ6jcGYgUlkCfmUkW2y3dF7c">Huly&reg;: <b>V_0.6-21618</b></a></sub>
=> vlib: add new `rand.cuid2` module

vlib/v/builder/cbuilder/parallel_cc.v, vlib/v/builder/cc.v
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzYxNjFmM2YxNDRmNTg1YWU0ZGM0NGIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.8eGc4KlwRppvc4RBdQqr2Fma2P-efKaP20iljPx4aYM">Huly&reg;: <b>V_0.6-21627</b></a></sub>
=> v.builder: integrate more compile/linker options into parallel_cc.v

.github/workflows/sanitized_ci.yml
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY1YWFkNWYxNDRmNTg1YWU0ZTlkOTgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.adrzZElilMXhyocxrIm3VRtOLgtYAOyWUbLRtLz3gk0">Huly&reg;: <b>V_0.6-21657</b></a></sub>
=> ci: try to speed up sanitizer run

vlib/v/gen/c/cgen.v
sFix
when building ui/examples/users.v
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY2OTc3ZGYxNDRmNTg1YWU0ZWFkOTciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.ZHzRPlbpdB_h9uxvjQdssOBFNGWT__qrBM9xGZQ822Q">Huly&reg;: <b>V_0.6-21664</b></a></sub>
=> parallel-cc: fix build when closure is used

vlib/json/tests/json_decode_struct_with_default_test.v, vlib/v/gen/c/json.v
Fix #23216
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY3Mzk2NmYxNDRmNTg1YWU0ZWI5YzMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.E3u6R-ywdnSsZoZNxe9Bu_C64HAwebNtzjNsexTSbbg">Huly&reg;: <b>V_0.6-21667</b></a></sub>
=> json: fix codegen for struct default expr

vlib/v/gen/c/cgen.v, vlib/v/tests/options/option_selector_interface_ptr_test.v
Fix #23250
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZhOWEzOGYxNDRmNTg1YWU1MDA2ZmQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.MrxOFeYaqvFburwRUHQtzhjMuY_j-YRcqHtxWr9tjs4">Huly&reg;: <b>V_0.6-21694</b></a></sub>
=> cgen: fix codegen for selector on option ptr unwrapping

examples/gg/easing_animation.v
The example looks like this:
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY5ZThiM2YxNDRmNTg1YWU0ZmRmM2EiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.fh9VQdPrx7KM10O58aupOnnD8dCYx6V_BJ8mhdIjTX0">Huly&reg;: <b>V_0.6-21687</b></a></sub>
=> examples: add `examples/gg/easing_animation.v`

examples/2048/2048.v, vlib/builtin/float.c.v, vlib/math/interpolation.v, vlib/math/interpolation_bezier.v, vlib/math/interpolation_test.v
Here is a before/after comparison of how the game looks/behaves:
https://github.com/user-attachments/assets/7749a305-8714-4e3d-8db4-dfe107e1b678
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZjNDJlN2YxNDRmNTg1YWU1MDRlMWYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.630qE0142tdsS7aaHryMxWhUS9VQECT9S_ZN5JWwkK0">Huly&reg;: <b>V_0.6-21702</b></a></sub>
=> math,examples: make 2048 use sliding animation for the tile movement

vlib/net/http/cookie.v, vlib/net/http/response_test.v
Fix issue #23220
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZhNjU0MWYxNDRmNTg1YWU0ZmZjOTkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.yU-5PBQdNkBZJGPOlE-UN-dJQhLKYl-gyB5x1ff2vh8">Huly&reg;: <b>V_0.6-21691</b></a></sub>
=> net.http: add support '=' in cookie values

vlib/db/sqlite/sqlite.c.v
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZlY2I1NWYxNDRmNTg1YWU1MTE4Y2IiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.19_jq8MIdJvEOiMf38uZSYffdU3yr5FUIAqIKQVCHJM">Huly&reg;: <b>V_0.6-21718</b></a></sub>
=> db.sqlite: reduce memory usage in common db.exec() methods, by using `val.vstring()` instead of `tos_clone(val)`

.github/workflows/v_apps_and_modules_compile_ci.yml
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZlZjFhNGYxNDRmNTg1YWU1MTJhZjUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.SOi1mzrrHmYQlo71VuyQpbBs56Oa1jJDQvT6TBH_fcw">Huly&reg;: <b>V_0.6-21723</b></a></sub>
=> ci: use updated build/test instructions for vsql

vlib/os/os.v
Close #23267
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZmMDdmN2YxNDRmNTg1YWU1MTJjMzUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.O5s3Q9q4SkOr_6gIrNTGOLu-bY-DwpT48IxErsvwWSE">Huly&reg;: <b>V_0.6-21724</b></a></sub>
=> vlib: fix typo

vlib/v/markused/markused.v, vlib/v/tests/skip_unused/simple_array_init.vv
Fix #23298
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcwODZkZmYxNDRmNTg1YWU1MTNkNzEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.YuqSMtBilKFb4tI-NXiGvY3An19YqT1DTw8sk42P0tw">Huly&reg;: <b>V_0.6-21733</b></a></sub>
=> markused: fix for short program with u8_array() call

doc/docs.md
Close #23265
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcxMGNjMGYxNDRmNTg1YWU1MTQwZGUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.NCuHK0qjLwBMdnQ-pxVDhdwrhfRQBbp7o26zOpaIc8s">Huly&reg;: <b>V_0.6-21735</b></a></sub>
=> Cleanup -skip-unused flag since it's now on by default

vlib/v/ast/types.v, vlib/v/checker/checker.v, vlib/v/gen/c/cgen.v, vlib/v/transformer/transformer.v
Optimizing
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcxOGVhZWYxNDRmNTg1YWU1MTRhYWIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.BskHHUqo6Oydu-d14sxioT9aVqpFEnYX-RJyMUMYYPA">Huly&reg;: <b>V_0.6-21738</b></a></sub>
=> v: some minor optimizations

vlib/v/ast/ast.v, vlib/v/checker/comptime.v, vlib/v/gen/c/assign.v, vlib/v/gen/c/comptime.v, vlib/v/gen/c/dumpexpr.v, vlib/v/gen/c/fn.v, vlib/v/type_resolver/comptime_resolver.v
- Clean up
- Cache selector `.typ` key for type selector type maping search
- Flag `is_name=true` if `field.$(f.name)`
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcxYTc4YmYxNDRmNTg1YWU1MTRlZTciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.qjhPqnSag65Z_mTL6HwvP9CddL6IoA-tXtMRQmM7AVA">Huly&reg;: <b>V_0.6-21740</b></a></sub>
=> v: cleanup ComptimeSelector `.typ` key generating

vlib/v/gen/c/for.v
Cleanup
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcyYjEwYWYxNDRmNTg1YWU1MTZjODAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.pG29FIycyUPuLwium1oVK2xJtWR2EKnLmHnAE7Hcebo">Huly&reg;: <b>V_0.6-21749</b></a></sub>
=> comptime: for cleanup

vlib/v/checker/for.v, vlib/v/tests/skip_unused/generic_iterator_loop.vv
Fix #23312
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcyZGNjZWYxNDRmNTg1YWU1MTcyNmQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.tIQheEJawr3iGPNOaSbvDFfXXvY3xfApbAtOtzvbCOY">Huly&reg;: <b>V_0.6-21753</b></a></sub>
=> markused: fix for iterator method not marked as used

vlib/v/checker/if.v
Cleanup
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc1MmRhZmYxNDRmNTg1YWU1MWZmZWUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.T6Jl-qDT_B4c5gQqTnREMl4awzX8b_ns02pnV-brur0">Huly&reg;: <b>V_0.6-21761</b></a></sub>
=> checker: cleanup check_non_expr_branch_last_stmt

vlib/v/gen/c/array.v, vlib/v/gen/c/assert.v, vlib/v/gen/c/infix.v
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc1MmYzNmYxNDRmNTg1YWU1MjAwMmQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.lSrQN3qjLwLPwNkKYTAb9SjkMN6omf8colDcBrRy354">Huly&reg;: <b>V_0.6-21762</b></a></sub>
=> v: remove double string cloning

vlib/v/checker/fn.v, vlib/v/gen/c/fn.v, vlib/x/json2/decoder.v, vlib/x/json2/json2.v, vlib/x/json2/tests/decode_nested_array_test.v
Fix
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc1NTI1Y2YxNDRmNTg1YWU1MjAzNzQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.SqOh5cN_kTI20pQMpTig3J5GuZRQGaYXYxyzyEpEmy4">Huly&reg;: <b>V_0.6-21764</b></a></sub>
=> checker: fix comptime indexexpr resolving

vlib/v/gen/c/assign.v, vlib/v/gen/c/str_intp.v, vlib/v/type_resolver/generic_resolver.v, vlib/v/type_resolver/type_resolver.v
Cleanup
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc5MzlhOWYxNDRmNTg1YWU1MjdjNDUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.loIguZSEJS1sVXVuY4kfXAvMKLisxOpOXLNcAvXR4ig">Huly&reg;: <b>V_0.6-21803</b></a></sub>
=> cgen: cleanup comptime checkings

vlib/v/gen/c/cgen.v
Cleanup and optimization.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzdlNWY3NWYxNDRmNTg1YWU1MzM0YjgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.b6clc0CDWT2klyzJq5ntPJwQsbNsI2xejJofTLkKMSM">Huly&reg;: <b>V_0.6-21839</b></a></sub>
=> cgen: caching return_stmt()'s node.exprs[0] and node.types[0]

vlib/v/gen/c/cgen.v, vlib/v/gen/c/infix.v, vlib/v/gen/c/spawn_and_go.v
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzdmYjQxZWJjMjA5NGNjMDE3Zjc0NWMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.foEPf8fczYNGpdtqFcR4DNS_PuiYtsXqo1fFgJv3lkU">Huly&reg;: <b>V_0.6-21848</b></a></sub>
=> v: minor optimization removing repeated code

vlib/v/checker/assign.v, vlib/v/checker/checker.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/index.v, vlib/v/tests/concurrency/shared_array_slice_test.v
Fix #23426
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzgxNzdmYmJjMjA5NGNjMDE4NDU4MDkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.t4lKe7sqnzqxo0tzfMowE86zzxNuMgXpLMpUezCkQsE">Huly&reg;: <b>V_0.6-21857</b></a></sub>
=> cgen: fix shared array slice

vlib/v/checker/check_types.v, vlib/v/checker/tests/mut_arg_different_muls_err.out, vlib/v/checker/tests/mut_arg_different_muls_err.vv, vlib/v/tests/conditions/ifs/in_expression_test.v, vlib/v/tests/fns/fn_call_mut_ref_args_test.v, vlib/v/tests/fns/fn_mut_arg_of_sumtype_ref_test.v, vlib/v/tests/options/option_reference_params_test.v
Fix #23157
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzgxOWIxYWJjMjA5NGNjMDE4NDVhYmIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.qR6yklQYBekxatv543j2Bcc4kLgDiS1Tah5sRzcHeIg">Huly&reg;: <b>V_0.6-21858</b></a></sub>
=> checker: fix call with mut arg with different muls

vlib/v/gen/c/array.v, vlib/v/tests/builtin_arrays/array_sumtype_init_test.v
=> cgen: fix array of sumtype initialization with var string

vlib/v/help/common/crun.txt
As title says.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzgyNGFkYWJjMjA5NGNjMDE4NDZiNTkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.pWFm2n4yTYK7nfg_Y3xmhugMQpF84F68UnUfFcjcFjk">Huly&reg;: <b>V_0.6-21861</b></a></sub>
=> help: `v help crun` message

vlib/v/checker/fn.v
=> checker: cleanup fn_call

vlib/v/markused/markused.v, vlib/v/tests/skip_unused/call_arguments.vv
=> markused: fix `-skip-unused` on short program that prints array

vlib/dl/loader/README.md
=> dl/loader: fix minor typo in README.md

examples/vascii.v
Because sometimes you just need a darn ASCII table :)
Prints a nicely formatted ASCII table in octal/hex/decimal.
usage:
```
v run vascii.v
The octal set:
000 nul  001 soh  002 stx  003 etx  004 eot  005 enq  006 ack  007 bel
010 bs   011 ht   012 nl   013 vt   014 np   015 cr   016 so   017 si
020 dle  021 dc1  022 dc2  023 dc3  024 dc4  025 nak  026 syn  027 etb
030 can  031 em   032 sub  033 esc  034 fs   035 gs   036 rs   037 us
040 sp   041  !   042  "   043  #   044  $   045  %   046  &   047  '
050  (   051  )   052  *   053  +   054  ,   055  -   056  .   057  /
060  0   061  1   062  2   063  3   064  4   065  5   066  6   067  7
070  8   071  9   072  :   073  ;   074  <   075  =   076  >   077  ?
100  @   101  A   102  B   103  C   104  D   105  E   106  F   107  G
110  H   111 …
```
=> examples: vascii.v

vlib/v/gen/c/fn.v, vlib/v/tests/fns/decompose_variadic_test.v
Fix issue found on sample code of issue #23474
=> cgen: fix array decomposing on variadic call

vlib/v/checker/struct.v, vlib/v/tests/generics/generic_alias_map_type_test.v
=> checker: fix checker generic alias type

vlib/v/gen/c/cgen.v, vlib/v/tests/options/option_nested_unwrapping_test.v
=> cgen: fix option var nested unwrapping from sumtype

vlib/v/checker/fn.v, vlib/v/tests/skip_unused/auto_str.run.out, vlib/v/tests/skip_unused/auto_str.skip_unused.run.out, vlib/v/tests/skip_unused/auto_str.vv
=> markused: fix markused auto str detection

vlib/v/checker/containers.v, vlib/v/checker/tests/array_none_element_err.out, vlib/v/checker/tests/array_none_element_err.vv
=> checker: fix missing check for `[none]`

vlib/flag/README.md
=> flag: fix minor typo, remove repeated word "in" from README.md

vlib/regex/regex_util.v
=> regex: fix misspelled word "firts" in replace_n description

doc/docs.md
=> doc: fix minor grammar error in attributes description

vlib/crypto/blake2b/blake2b.v, vlib/crypto/blake2s/blake2s.v
This is somewhat embarrassing since I made those typos.
=> blake2s, blake2b: fix typo in new_digest description

vlib/v/gen/c/cgen.v, vlib/v/tests/options/option_unwrap_selector_test.v
=> cgen: fix unwrapping option interface field

vlib/v/checker/if.v
This PR makes a minor cleanup in smartcast_if_conds().
=> checker: minor cleanup in smartcast_if_conds()

vlib/v/checker/fn.v, vlib/v/checker/used_features.v, vlib/v/tests/skip_unused/option_ptr_print.run.out, vlib/v/tests/skip_unused/option_ptr_print.skip_unused.run.out, vlib/v/tests/skip_unused/option_ptr_print.vv
=> markused: fix option ptr printing

doc/docs.md
Document keyword use struct fields with example
=> doc: document keyword use struct fields

vlib/gg/image.c.v
mark create_image_with_size() as deprecated
=> gg: mark create_image_with_size() as deprecated

make.bat
Related: https://news.ycombinator.com/item?id=42822889
=> make.bat: add note about antivirus programs on windows and compilation slowdowns

doc/docs.md
Idea came about from this discord conversation: https://discord.com/channels/592103645835821068/592294828432424960/1333887308520230913
=> docs: improve string description

cmd/tools/vast/vast.v, vlib/v/ast/ast.v, vlib/v/checker/checker.v, vlib/v/gen/c/assert.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/comptime.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/str.v, vlib/v/type_resolver/comptime_resolver.v, vlib/v/type_resolver/type_resolver.v
=> type_resolver: refactor resolve_comptime_type

.github/workflows/vpm_ci.yml, cmd/tools/vpm/install_test.v, cmd/tools/vpm/outdated_test.v, cmd/tools/vpm/settings.v
It also fixes the local runs of `CI=name ./v -d network test cmd/tools/vpm/` .
=> ci: fix `CI=name ./v -d network test cmd/tools/vpm/` ; update image runners in vpm_ci.yml

vlib/v/parser/struct.v, vlib/v/parser/tests/struct_no_body_err.out, vlib/v/parser/tests/struct_no_body_err.vv
=> parser: fix error message for struct lacking body

cmd/tools/vcomplete.v, cmd/tools/vreduce.v, cmd/v/v.v, vlib/v/help/other/reduce.txt
Adds the `v reduce` tool that helps doing minimal reproducible examples.
The tool works: `v reduce [options]` and outputs the rpdc.v file in the current directory.
I dont know if I missed something I should have done.
=> tools: add vreduce

vlib/v/gen/c/cgen.v, vlib/v/tests/options/option_for_or_block_test.v
=> cgen: fix codegen for `for` or-block

vlib/v/checker/check_types.v
Remove repeated fn call to `got.is_ptr()` and `expected.is_ptr()`.
=> checker: cleanup check_expected_call_arg

vlib/v/gen/c/auto_eq_methods.v
Remove repetead `left_type.has_flag(.option)`.
=> cgen: cleanup gen_fixed_array_equality_fn

vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/tests/options/option_sumtype_map_test.v
=> cgen: fix codegen for sumtype cast from option variants on map_set

vlib/net/http/file/static_server.v
=> net.http.file: use urllib decode uri

vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/if.v, vlib/v/gen/c/match.v, vlib/v/tests/array_fixed_ternary_test.v
=> cgen: fix codegen for array fixed on if and match expr

cmd/tools/vreduce.v
Make the output of `v reduce` easier to scan, let it continue after most current assertions fail, since the output is still useful.
Given this code in `a.c.v`:
```v
#define FAIL_TO_COMPILE abc()
fn C.FAIL_TO_COMPILE()
fn main() {
C.FAIL_TO_COMPILE()
}
```
with this PR, it produces:
The resulting `rpdc.v` is shorter and still works for a reproduction of the intentional problem 🥳 .
=> tools: improve `v reduce` output; bump version, warn on failed string_reproduces/3, but continue to run

vlib/veb/csrf/csrf.v
We introduce a new `verbose` option in `CsrfConfig` to move the default print statements behind this flag in order to allow users to make it configurable and select when it should be enabled.
=> veb.csrf: Make default printing of verbose data optional via config flag

vlib/v/checker/fn.v, vlib/v/gen/c/fn.v, vlib/v/tests/sumtypes/sumtype_inherited_var_test.v
=> checker, cgen: fix sumtype smartcasted var as inherited var

vlib/v/ast/table.v, vlib/v/checker/fn.v, vlib/v/markused/markused.v, vlib/v/tests/skip_unused/sumtype_type_name.run.out, vlib/v/tests/skip_unused/sumtype_type_name.skip_unused.run.out, vlib/v/tests/skip_unused/sumtype_type_name.vv
=> markused: add identification for sumtype.type_name() call

vlib/v/checker/struct.v, vlib/v/tests/struct_init_update_test.v
=> checker: fix spreed operator ref field validation

vlib/v/ast/ast.v, vlib/v/checker/checker.v, vlib/v/checker/str.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/infix.v, vlib/v/gen/c/match.v, vlib/v/tests/comptime/comptime_aggregate_var_test.v, vlib/v/tests/typeof_aggregate_test.v, vlib/v/type_resolver/type_resolver.v
=> checker, cgen: fix aggregate var handling on match branch

vlib/x/json2/decoder2/tests/decode_string_test.v
=> x.json2.decoder2: improve tests

vlib/cli/README.md
=> cli: fix minor typo

vlib/os/os.c.v
=> os.get_raw_line fix buffer overflow under Windows

vlib/flag/flag_to.v, vlib/net/dialer.v, vlib/strconv/atou.v
=> fix: typos in documentation files

vlib/v/ast/ast.v, vlib/v/ast/str.v, vlib/v/fmt/struct.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/struct.v, vlib/v/parser/parse_type.v, vlib/v/parser/struct.v, vlib/v/tests/options/option_anon_struct_test.v, vlib/v/tests/options/option_none_to_anon_struct_test.v
=> v: fix anon struct option support

vlib/log/log.v
Delete it since it was said to be deleted
=> Remove the log notice

vlib/json/tests/json_decode_autofree_test.v, vlib/v/gen/c/fn.v, vlib/v/gen/c/testdata/autofree_json_decode.c.must_have, vlib/v/gen/c/testdata/autofree_json_decode.vv
=> json: fix json.decode autofree codegen

vlib/v/fmt/struct.v, vlib/v/fmt/tests/array_option_anon_struct_keep.vv
=> fmt: fix formatting for option array of anon struct

examples/breakout/.gitignore, examples/breakout/breakout.html, examples/breakout/breakout.v
It looks like this:
I've tested it with wasm too, compiling with:
```
./v -prod -os wasm32_emscripten -o examples/breakout/breakout.js examples/breakout/
```
and then:
```
emrun examples/breakout/breakout.html
```
=> examples: add a small breakout game

vlib/v/tests/generics/generic_anon_fn_inside_generic_fn_test.v, vlib/v/type_resolver/comptime_resolver.v
=> type_resolver: fix recheck identification for anonfn on structinit

vlib/v/checker/struct.v, vlib/v/tests/options/option_ptr_field_test.v
=> checker: fix option ptr field assign checking

vlib/crypto/ecdsa/README.md, vlib/crypto/ecdsa/ecdsa.v, vlib/crypto/ecdsa/util.v
This small PR just updates the docs related things to align with the rest, ie, in the form
- Removes caution warning from README file, its already buildable with`-cstrict` option.
- Add some missing bits of the docs (for `CurveOptions` opaque)
- Updates some bits of function docs. (`.equal`,  `generate_key`, etc)
- Clears out some unneeded comment
Thx
=> crypto.ecdsa: Updates some bits of the module docs

vlib/crypto/aes/block_generic.v
fix warnings in crypto.aes for #23898
=> crypto.aes: fix warnings about order of operations 

vlib/v/parser/containers.v, vlib/v/parser/expr.v, vlib/v/parser/parser.v, vlib/v/tests/enums/enum_on_array_init_test.v
Fix #23937
```v
enum Animal {
cat
cow
dog
eagle
horse
rabbit
snake
}
array := [Animal.cat .dog .rabbit]
assert array.str() == '[cat, dog, rabbit]'
```
=> parser: fix enum value parsing inside array initialization

vlib/v/checker/assign.v, vlib/v/checker/tests/assign_const_ptr_int_literal_err.out, vlib/v/checker/tests/assign_immutable_reference_var_with_parenthesis_err.out, vlib/v/checker/tests/const_reference_write_err.out, vlib/v/checker/tests/const_reference_write_err.vv, vlib/v/checker/tests/immutable_deref.out, vlib/v/checker/tests/immutable_deref.vv, vlib/v/checker/tests/mut_assign_ref.out, vlib/v/checker/tests/mut_assign_ref.vv
=> checker: add block for const reference

vlib/v/checker/assign.v, vlib/v/checker/checker.v, vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/comptime.v, vlib/v/tests/generics/generic_typeof_test.v, vlib/v/tests/options/option_var_test.v
=> checker: fix typeof evaluation for generic reference

vlib/db/mysql/mysql.c.v
This PR make ssl connection work.
Tested with `tidbcloud.com` mysql db.
And turn ConnectionFlag into @[flag], so we can write code like this:
```v
mut mysql_config := mysql.Config{
host:     '127.0.0.1'
port:     4000
username: 'root'
password: '123'
dbname:   'admin'
ssl_ca : './client-cert.pem'
flag:     .client_ssl | .client_ssl_verify_server_cert
}
```
=> db.mysql: add SSL support; turn ConnectionFlag into @[flag]

vlib/v/debug/tests/struct_heap.expect, vlib/v/debug/tests/struct_heap.vv, vlib/v/gen/c/cgen.v
=> debug: fix `$dbg` with heap struct 

vlib/os/process_test.v, vlib/os/process_windows.c.v
Fix issue #10628
Update `process_test.v`, then it work now.
=> os: windows add set_environment() support

vlib/v/gen/c/cgen.v
=> cgen: cleanup write_sumtype_casting_fn

vlib/v/gen/c/assign.v, vlib/v/gen/c/cgen.v, vlib/v/gen/c/fn.v, vlib/v/tests/sumtypes/sumtype_arg_mutable_test.v
=> cgen: fix codegen to make mutable sumtype working

vlib/v/depgraph/depgraph.v, vlib/v/depgraph/depgraph_test.v
1. Fix issue #24075
2. Fix issue #23970
3. Fix issue #23968
4. May fix some bugs related to strange const miss declaration, such as `'_const_math__bits__ntz_8_tab' undeclared when compiling pure V code`, `C error: '_const_math__bits__de_bruijn32tab' undeclared`... such as issue(have not been verified) #22391..
=> v.depgraph: fix resolve()

vlib/v/gen/c/fn.v, vlib/v/tests/c_function/array.c, vlib/v/tests/c_function/pass_ref_test.c.v
=> cgen: fix `@[keep_args_alive]` with ptr

vlib/v/vmod/encoder.v, vlib/v/vmod/encoder_test.v, vlib/v/vmod/parser.v
This PR:
- Adds encoder function for v.mod
- Adds tests
=> v.vmod: add manifest encoder fn

vlib/v/gen/c/cgen.v, vlib/v/gen/c/cmain.v, vlib/v/tests/options/option_array_push_test.v
=> cgen: fix option array push on unwrapped array

vlib/v/tests/comptime/comptime_for_selector_array_test.v, vlib/v/type_resolver/generic_resolver.v
=> type_resolver: fix comptime_for  array generic

vlib/v/gen/c/infix.v, vlib/v/tests/in_op_array_fixed_test.v
=> cgen: in operator with fixed array

vlib/v/gen/c/comptime.v, vlib/v/tests/comptime/comptime_multiline_attr_test.v
=> cgen: fix codegen for comptime multiline attr

vlib/v/gen/c/cgen.v, vlib/v/tests/options/option_embed_field_test.v
=> cgen: fix codegen for selector with embed field option 

vlib/v/tests/comptime/comptime_infer_generic_map_test.v, vlib/v/type_resolver/generic_resolver.v
=> type_resolver: fix map generic resolver 

vlib/v/checker/infix.v, vlib/v/checker/tests/option_array_push.out, vlib/v/checker/tests/option_array_push.vv, vlib/v/checker/tests/wrong_shift_left_option_err.out
=> checker: fix checker for pushing on option array

vlib/encoding/binary/README.md, vlib/encoding/binary/serialize.v, vlib/encoding/binary/serialize_test.v
This PR provide  Serialization/Deserialization functions for generic type `T`.
We can serialize generic data into a []u8 byte array and deserialize it back to its original form.
=> encoding.binary: add encode_binary()/decode_binary() generic functions

vlib/v/checker/fn.v, vlib/v/checker/tests/wrong_predicate_type_err.out, vlib/v/checker/tests/wrong_predicate_type_err.vv
=> checker: fix wrong type hint on predicate arg type mismatch

vlib/db/mysql/orm.c.v
=> db.mysql: fix nullable timestamp

.github/workflows/docker_ci.yml, vlib/orm/orm.v, vlib/orm/orm_complex_where_test.v
=> orm: fix gen sql complex where (fix #24136)

vlib/v/checker/check_types.v
Refactor + minor clean up/optimization
=> checker: simplify some check types logic

doc/docs.md, vlib/v/ast/comptime_valid_idents.v
enable "$if s390x {...}" + mention in the doc.
=> comptime: enable s390x + docs

vlib/orm/orm_generic_test.v, vlib/v/parser/orm.v
=> parser: fix orm generic struct table type parsing

vlib/db/mysql/consts.c.v
=> db.mysql: use hardcoded const declare

.github/workflows/bootstrapping_ci.yml, .github/workflows/c2v_ci.yml, .github/workflows/cross_ci.yml, .github/workflows/docker_ci.yml, .github/workflows/docs_ci.yml, .github/workflows/gen_vc_ci.yml, .github/workflows/gg_regressions_ci.yml, .github/workflows/hub_docker_ci.yml, .github/workflows/other_ci.yml, .github/workflows/paths_ci.yml, .github/workflows/release_ci.yml, .github/workflows/s390x_linux_ci.yml, .github/workflows/sdl_ci.yml, .github/workflows/symlink_ci.yml, .github/workflows/tools_ci.yml, .github/workflows/v_apps_and_modules_compile_ci.yml, .github/workflows/vab_ci.yml, .github/workflows/vsl_and_vtl_compile_ci.yml, .github/workflows/vup_works.yml, .github/workflows/websockets_ci.yml
- **ci: fix issues reported by https://github.com/rhysd/actionlint**
=> ci: fix issues reported by actionlint

vlib/db/mysql/pool.v, vlib/db/pg/pool.v, vlib/db/sqlite/pool.v
=> db: connection pool

vlib/encoding/binary/serialize.v, vlib/encoding/binary/serialize_test.v
=> encoding.binary: fix serialize map struct

vlib/datatypes/set.v, vlib/datatypes/set_test.v
This help get all elements from a set.
=> datatypes.set: add array()

vlib/v/gen/c/fn.v, vlib/v/tests/fns/call_args_variadic_sumtype_test.v
=> cgen: fix variadic sumtype args passing

vlib/v/checker/return.v
=> checker: cleanup return_stmt

vlib/v/checker/fn.v, vlib/v/tests/generics/generic_return_array_generic_test.v
=> checker: fix array generic return checking

vlib/orm/orm_func.v, vlib/orm/orm_func_test.v
=> orm:set default value for require field if database value is null

cmd/tools/vcreate/project_model_bin.v, cmd/tools/vcreate/project_model_lib.v, cmd/tools/vcreate/project_model_web.v, cmd/tools/vcreate/vcreate_init_test.v
Step 1 for removing support for the `src` subdir.
=> new: remove `src` subdir from created projects

vlib/v/gen/c/consts_and_globals.v, vlib/v/tests/consts/const_cstr_test.v
=> cgen: fix codegen for const to c string

vlib/db/mysql/_cdefs.c.v, vlib/db/mysql/mysql.c.v, vlib/db/mysql/result.c.v, vlib/db/mysql/stmt.c.v, vlib/v/gen/c/json.v, vlib/v/gen/c/testdata/json_option_time.out, vlib/v/gen/c/testdata/json_option_time.vv
=> json: fix option time

vlib/json/cjson/cjson_wrapper.c.v, vlib/json/json_primitives.c.v
Fix issue #24272
It also need to fix `tccbin` `math.h` to fix this bug.
https://github.com/vlang/tccbin/issues/59
=> json: link with libm

cmd/tools/vdoc/vdoc.v, cmd/tools/vdoc/vdoc_test.v
=> vdoc: fix infinit recursive calls

doc/docs.md
=> doc: update link to map method

vlib/v/checker/struct.v, vlib/v/checker/tests/invalid_recursive_struct_err.out, vlib/v/checker/tests/recursive_struct_inited_array_err.out, vlib/v/checker/tests/recursive_struct_inited_array_err.vv
=> checker: add check for recursive array init on struct

vlib/v/parser/struct.v, vlib/v/parser/tests/invalid_field_name_err.out, vlib/v/parser/tests/invalid_field_name_err.vv
=> parser: fix invalid field name checking

vlib/v/gen/c/assign.v, vlib/v/tests/defer/defer_fixed_array_test.v
=> cgen: fix codegen for assigning fixed array on defer var

vlib/v/gen/c/cgen.v, vlib/v/tests/options/option_selector_unwrapping_test.v
=> cgen: fix codegen for nested selector unwrapping on lhs

vlib/toml/scanner/scanner.v, vlib/toml/scanner/scanner_test.v
=> toml: fix multiline string CRLF

vlib/v/gen/c/cgen.v, vlib/v/tests/options/option_ptr_unwrap_test.v, vlib/v/tests/options/option_unwrap_selector_write_test.v
=> cgen: fix codegen for writing on unwrapped selector

vlib/v/gen/c/fn.v, vlib/v/tests/fns/call_result_test.v
=> cgen: fix codegen for handling multiple return result type on call

vlib/x/json2/encoder.v, vlib/x/json2/json2.v, vlib/x/json2/tests/any_test.v
=> x.json2: add u16(),u32()

vlib/v/gen/c/cgen.v, vlib/v/tests/options/option_nested_selector_test.v
=> cgen: fix codegen for nested selector option ptr

vlib/v/gen/js/js.v, vlib/v/gen/js/tests/callback.v
- fix optional callback parameter
- improve callback examples
Fixes #24325
=> fix optional callback parameter and improve examples (fix #24325)

vlib/rand/rand.c.v
rand: fix uuid_v7 seperator, from `_` to `-`
=> rand: fix uuid_v7 seperator, from `_` to `-`

vlib/v/gen/c/struct.v
This PR provide a workaround for issue #24331
=> cgen: workaround tcc aarch64 bug #24331

cmd/tools/vreduce.v
- adds a flag to specify a custom command to run the project with 
- adds a flag to specify to vreduce it needs to copy the whole project, not just the specified file
- adds a flag to set a timeout in case the command takes too long (the command could be stuck in an infinite loop at runtime)
=> tools: vreduce timeout, vreduce custom run command

cmd/tools/vreduce.v
removes ambiguity for path variables.
Sorry for the silly mistakes
=> tools: vreduce fix var names

doc/docs.md
exchanges two lines (3rd and 4th)
Sorry again, don't know how I did not check that too.
=> doc: profiler: fix inverted lines

vlib/v/tests/comptime/comptime_if_is_test.v, vlib/v/type_resolver/comptime_resolver.v, vlib/x/json2/encoder.v
=> type_resolver: i32 is $int

vlib/v/ast/table.v, vlib/v/tests/structs/struct_scoped_test.v
=> table: fix array of scoped struct

vlib/v/checker/if.v, vlib/v/gen/c/comptime.v, vlib/v/tests/comptime/comptime_call_void_test.v
=> comptime: fix `$if var.return_type == 1 {`

vlib/v/markused/walker.v, vlib/v/tests/skip_unused/generic_call_from_json.vv
=> markused: fix generic method call mark

vlib/v/gen/c/cgen.v, vlib/v/gen/c/struct.v, vlib/v/tests/options/option_fn_struct_init_test.v
=> cgen: fix codegen for anon option fn struct field init

vlib/os/os_test.c.v, vlib/os/os_windows.c.v
=> os.windows:force not create window when execute

vlib/v/gen/c/cgen.v, vlib/v/tests/options/option_mut_if_none_test.v
=> cgen: fix `if mut var != none {` generated code

vlib/v/checker/for.v, vlib/v/gen/c/for.v, vlib/v/tests/generics/generic_for_mut_val_test.v
=> cgen, checker: fix for with mut generic value

vlib/v/gen/c/array.v, vlib/v/tests/interfaces/interface_array_init_test.v
=> cgen: fix array init with interface element type

vlib/v/gen/c/comptime.v, vlib/v/tests/comptime/comptime_call_map_receiver_test.v
=> cgen: fix comptimecall with map receiver

vlib/v/tests/generics/generic_array_pass_test.v
=> test: remove wrong comment since bug has been fixed

vlib/v/gen/c/for.v
=> cgen: workaround tcc aarch64 bug

vlib/v/gen/c/for.v
This PR is a supplement to PR #24474
=> cgen: workaround tcc aarch64 fn call bug

vlib/v/checker/fn.v, vlib/v/tests/generics/generic_struct_return_test.v
=> checker: fix resolver for returning struct generic 

vlib/v/gen/c/auto_eq_methods.v, vlib/v/tests/options/option_array_compare_test.v
=> cgen: fix codegen for array of option element auto eq 

vlib/v/gen/c/consts_and_globals.v, vlib/v/slow_tests/run_project_folders/issue_24521_constants_in_different_v_files/a.v, vlib/v/slow_tests/run_project_folders/issue_24521_constants_in_different_v_files/b.v, vlib/v/slow_tests/run_project_folders/issue_24521_constants_in_different_v_files/main.v
=> cgen: fix tmp var redeclaration on const inited later code gen

vlib/v/gen/js/js.v, vlib/v/gen/js/tests/casting.v
=> jsgen: fix casting (fix #24512)

vlib/v/gen/js/auto_eq_methods.v, vlib/v/gen/js/infix.v, vlib/v/gen/js/tests/alias.v, vlib/v/gen/js/util.v
=> jsgen: alias types are not properly resolved (fix #24486 #24507)

vlib/v/gen/js/tests/alias.v
After fixing #24512 we can now simplify assertions.
=> jsgen(tests): simplify assertions in alias tests

cmd/tools/vpm/common.v, cmd/tools/vpm/search_test.v
=> vpm: make search work again

vlib/math/interpolation.v, vlib/math/interpolation_test.v
V port of the function presented here: https://youtu.be/LSNQuFEDOyQ?t=2977
=> math: add `exp_decay` to `interpolation.v`

vlib/db/pg/pg.c.v, vlib/db/pg/pg_double_test.v, vlib/db/pg/pg_orm_test.v
=> pg: fix incompatible fn signature

thirdparty/stdatomic/win/atomic.h, vlib/sync/stdatomic/1.declarations.c.v, vlib/sync/stdatomic/atomic.c.v, vlib/sync/stdatomic/atomic_test.v
This PR create atomic types and add/sub load/store operation on them.
=> sync.stdatomic: add atomic types

vlib/v/checker/used_features.v, vlib/v/tests/generics/generic_different_type_test.v
=> markused: fix for generic ptr receiver on method call

vlib/v/checker/struct.v, vlib/v/tests/aliases/alias_updated_expr_test.v
=> checker: fix update expr checking when alias is used

vlib/builtin/js/string.js.v, vlib/v/gen/js/tests/string.v
=> jsgen: fix string.runes method (fix #20500)

thirdparty/zstd/fix.md, thirdparty/zstd/zstd.c, thirdparty/zstd/zstd_v.patch, vlib/compress/zstd/zstd.c.v, vlib/compress/zstd/zstd_d_musl.c.v
Required by #24595
A update for PR #24597, with a release version of `zstd`.
Tested on Ubuntu/OpenBSD/FreeBSD with `tcc`.
=> thirdparty.zstd: upgrade to v1.5.7 release

vlib/v/gen/native/amd64.v, vlib/v/gen/native/arm64.v, vlib/v/gen/native/expr.v, vlib/v/gen/native/gen.v, vlib/v/gen/native/tests/string.vv, vlib/v/gen/native/tests/struct.vv
- support for nested structs
- support more expressions for the right expr of IndexExpr
- make the StringLiterals more robust (explicit lea instead of relying on previous state)
=> native: nested structs, more support for right expr of IndexExpr

tutorials/building_a_simple_web_blog_with_veb/README.md
=> tutorials: fix compilation errors in `Building a simple web blog with Veb`

vlib/builtin/builtin.c.v
- remove constraints related to the program from the module
=> builtin: remove playground related code

vlib/orm/orm_func.v, vlib/orm/orm_func_test.v
Adds in and not in to orm funcs
Closes 24639
=> orm: add `in` and `not in` to orm_func

examples/gg/memory.v
This PR adds a small gg based memory puzzle (you have to open all tiles with matching letters to win it).
=> examples: add a small memory game

doc/docs.md
Description:  
This pull request makes several minor improvements to the documentation for better clarity and consistency:
- Corrects grammar and wording in several comments and explanations.
- Updates examples to improve readability.
- Ensures consistent terminology throughout the documentation.
No functional code changes are included; this PR is documentation-only.
=> Minor Documentation Improvements and Clarifications

vlib/v/checker/if.v, vlib/v/checker/tests/option_mut_non_mut_err.out, vlib/v/checker/tests/option_mut_non_mut_err.vv
Spotted by @jorgeluismireles at #24692
=> checker: fix mutable option from immutable

doc/docs.md
=> docs: add section for Lambda functions

vlib/picoev/loop_default.c.v, vlib/picoev/loop_freebsd.c.v, vlib/picoev/loop_linux.c.v, vlib/picoev/loop_macos.c.v, vlib/picoev/loop_openbsd.c.v, vlib/picoev/loop_termux.c.v, vlib/picoev/picoev.v, vlib/picoev/socket_util.c.v
Add/Fix comments for functions in `vlib/picoev/`
=> picoev: improve documentation

vlib/v/gen/c/cgen.v, vlib/v/tests/interfaces/interface_method_closure_test.v
=> cgen: fix codegen for interface method closure get

vlib/v/gen/c/fn.v, vlib/x/json2/tests/encode_anon_struct_test.v
=> cgen, x.json2: fix anon struct encode

vlib/json/tests/json_decode_option_alias_field_test.v, vlib/v/gen/c/cgen.v
=> cgen: fix json decode option alias

vlib/v/ast/table.v, vlib/v/gen/c/cgen.v, vlib/v/tests/consts/const_indexexpr_dep_test.v
=> cgen: fix const indexexpr dep

vlib/v/checker/checker.v, vlib/v/checker/struct.v, vlib/v/checker/tests/direct_map_alias_init_err.out, vlib/v/checker/tests/direct_map_alias_init_err.vv, vlib/v/gen/c/struct.v, vlib/v/tests/aliases/alias_map_test.v
Fix #24878
Also fixes the map part of issue at #24887
=> cgen: allow alias to map

vlib/runtime/used_memory_darwin.c.v, vlib/runtime/used_memory_default.c.v, vlib/runtime/used_memory_linux.c.v, vlib/runtime/used_memory_test.v, vlib/runtime/used_memory_windows.c.v
// used_memory retrieves the current physical memory usage of the process.
pub fn used_memory() !u64
=> runtime: add used_memory()

vlib/os/os.v
Remove useless debug (code in comments) in `home_dir` function (`vlib/os/os.v`)
=> os: remove debug in home_dir() function

vlib/v/gen/native/comptime.v
native: add comptime cpu archs indent support.
=> native: add comptime cpu archs support

vlib/time/format.v, vlib/time/time_test.v
=> time: fix custom_format panic

vlib/v/ast/table.v, vlib/v/checker/checker.v, vlib/v/checker/comptime.v, vlib/v/checker/fn.v, vlib/v/checker/infix.v, vlib/v/checker/used_features.v, vlib/v/gen/c/dumpexpr.v, vlib/v/markused/markused.v, vlib/v/markused/walker.v
=> markused: clean up features tracking from checker - remove 1 all_fns loop

vlib/v/gen/native/amd64.v, vlib/v/gen/native/blacklist.v, vlib/v/gen/native/elf.v, vlib/v/gen/native/expr.v, vlib/v/gen/native/gen.v, vlib/v/gen/native/stmt.c.v, vlib/v/gen/native/tests/linux.vv, vlib/v/gen/native/tests/native_test.v
The groundwork for supporting globals. Only supports basic features, but more will come when needed
=> native: (elf) globals 

vlib/v/markused/walker.v, vlib/v/tests/generics/struct_generic_map_index_test.v
=> markused: fix generic map index

vlib/json/tests/json_decode_sumtype_option_test.v, vlib/v/markused/walker.v
=> markused: fix option tracking on sumtype

vlib/v/checker/checker.v
=> checker: remove unused `c.using_new_err_struct`

vlib/v/scanner/scanner.v, vlib/v/tests/builtin_strings_and_interpolation/string_interpolation_with_escape_test.v
=> scanner: refactor string interpolation

vlib/v/markused/walker.v, vlib/v/tests/runes_test.v
=> markused: fix array append c code dependency 

.github/workflows/paths_ci.yml, .github/workflows/termux_ci.yml
- **cgen: fix building on Termux after fa904c4**
- **ci: add experimental support for testing on a Termux docker container**
=> ci: add experimental support for building V and testing on a Termux docker container

vlib/v/checker/checker.v, vlib/v/tests/consts/const_propagate_result_test.v
=> checker: support propagate result in const declare

vlib/v/gen/c/assign.v, vlib/v/tests/translated_test.v
Fix issue #25079 
generate a pointer assignment instead of `memcpy`.
=> cgen: fix translated file fixed-array assignment

vlib/v/gen/c/cgen.v, vlib/v/tests/sumtypes/sumtype_init_literal_test.v
=> cgen: fix alias to sumtype cast initialization

vlib/v/gen/c/cgen.v, vlib/v/tests/options/option_generic_array_field_test.v
=> cgen: fix codegen for generic struct field array option 

vlib/v/tests/generics/generic_selector_field_test.v, vlib/v/type_resolver/generic_resolver.v
=> resolver: fix generic selector field type resolver

vlib/v/gen/c/cgen.v, vlib/v/gen/c/json.v, vlib/v/tests/sumtypes/sumtype_arg_mutable_test.v, vlib/v/tests/sumtypes/sumtype_mutable_test.v
Fix issue #25108
remove `$d('mutable_sumtype', false)`, and this will make `sumtype` is mutable.
=> cgen: fix mutable sumtype

vlib/v/checker/checker.v, vlib/v/checker/tests/map_repeated_float_key_err.out, vlib/v/checker/tests/map_repeated_float_key_err.vv
=> checker: fix missing map float key duplicated checking

vlib/v/gen/c/orm.v
=> orm: fix sub_structs

vlib/orm/orm_result_test.v, vlib/v/checker/orm.v
=> checker: fix sql insert expr propagate result

vlib/flag/flag_to.v, vlib/flag/flag_to_tail_bool_test.v
=> flag: fix tail/single bool flag error condition logic in `flag_to.v`

doc/docs.md, vlib/v/checker/checker.v, vlib/v/parser/comptime.v, vlib/v/scanner/tests/unknown_comptime_var_err.out, vlib/v/tests/comptime/comptime_at_test.v, vlib/v/token/token.v
add `@OS`  `@COMPILER`  `@BACKEND` `@PLATFORM` comptime support.
=> v: add support for `@OS`, `@CCOMPILER` `@BACKEND` and `@PLATFORM`

vlib/v/checker/fn.v, vlib/v/checker/tests/multi_return_arg_missing_err.out, vlib/v/checker/tests/multi_return_arg_missing_err.vv, vlib/v/checker/tests/multi_return_err.out
=> checker: fix multi return arg passing checking

vlib/v/ast/table.v, vlib/v/gen/c/cgen.v, vlib/v/markused/walker.v, vlib/v/tests/generics/generic_interface_field_test.v
=> cgen, table: fix resolving generic interface field from generic struct 

vlib/v/checker/match.v, vlib/v/tests/comptime/comptime_match_unaliased_typ_test.v
=> checker: add `T.typ` and `T.unaliased_typ` checking to `$match`

vlib/v/ast/ast.v, vlib/v/checker/assign.v, vlib/v/checker/tests/static_init_err.out, vlib/v/checker/tests/static_init_err.vv
=> checker: fix static init var

vlib/readline/readline_nix.c.v
Fix issue #25219
Use `east_asian.display_width()` calculate the display width of a string.
=> readline: fix wide char display width

vlib/v/checker/match.v, vlib/v/tests/comptime/comptime_match_eval_only_true_branch_test.v
=> checker: comptime match only eval true branch

vlib/builtin/cfns.c.v, vlib/os/os.c.v, vlib/os/os_darwin.c.v
=> builtin: fix C prefix for proc_pidpath()

vlib/v/markused/walker.v
=> markused: fix CI

vlib/v/gen/native/amd64.v, vlib/v/gen/native/blacklist.v, vlib/v/gen/native/comptime.v, vlib/v/gen/native/expr.v, vlib/v/gen/native/gen.v, vlib/v/gen/native/tests/assign.vv, vlib/v/gen/native/tests/struct.vv
- begin Const support 
- support more assigns operations (vars and struct fields
- replace some panics with native errors
=> native: consts, support more assigns

vlib/v/markused/walker.v, vlib/v/tests/generics/generic_fn_multi_mutable_struct_test.v
Fixes #25312. 
Maybe a more efficient way to do this? Doesn't appear to have significant performance impact so should be fine.
Also no idea what to set as the commit message, it sounds confusing to me too.
=> markused: fix missing declaration on mutable multi struct generic call

vlib/v/ast/type_size_test.v, vlib/v/ast/types.v
=> v.ast: fix type_size for hardcode map and array

vlib/gx/color.v
=> gx: fix int to i32

vlib/v/gen/c/str_intp.v, vlib/v/markused/walker.v, vlib/v/tests/options/option_unwrap_none_test.v
=> cgen: fix option unwrap with string interpolation

vlib/v/checker/checker.v, vlib/v/checker/tests/interface_implemented_by_function.out, vlib/v/checker/tests/interface_implemented_by_function.vv
Fixes #24846.
Skipped on js backend for correct interop.
=> checker: disallow function implementing interface

vlib/v/gen/c/match.v, vlib/v/tests/options/option_case_test.v
=> cgen: fix match codegen with option

vlib/v/gen/c/infix.v, vlib/v/tests/options/option_match_eq_test.v
=> cgen: fix option match case 

vlib/x/crypto/sm4/sm4.v, vlib/x/crypto/sm4/sm4_test.v
Fix issue #25406
In CBC mode, make `iv` immutable.
rewrite tests.
=> x.crypto.sm4: fix cbc API, make iv immutable

vlib/v/transformer/tests/const_infix_expr_test.v
Add test for `transformer`, test `infix_expr` right now.
=> transformer: add test
