- vlib/v/gen/c/cgen.v
- vlib/v/parser/comptime.v
- vlib/v/parser/containers.v
- vlib/v/parser/fn.v
- vlib/v/parser/lock.v
This PR does some minor cleanup work based on the comments of several previous PRs.
- Moved some `close_scope()` into defer (parser).
- Get fixed array size from sym.info.size (cgen, suggestions from previous PR)
> parser, cgen: a minor cleanup

- examples/call_v_from_ruby/test.rb
I noticed that the "call v from ruby" example doesn't work on MacOS, and likely also not on Windows, since the shared library artifact generated by `v -d no_backtrace -shared examples/call_v_from_ruby/test.v` has a different, platform-specific extension (`.dylib` and `.dll` respectively - [source](https://github.com/vlang/v/blob/757929392e0e7a75fc1272116460981e589737d5/vlib/dl/dl.v#L9-L20)) but the ruby code assumed `.so`.  
While I was there, I also improved the user feedback from the Ruby script if the shared library is missing.
- Quite a few failures on my machine, but this also happens on `master` and I'm only changing ruby code, so I hope this is OK.
> examples: fix "call v from ruby" example for Windows and Mac

- cmd/tools/vrepl.v
```v
fn repl_help() {
println(version.full_v_version(false))
println('
|help                   Displays this information.
|list                   Show the program so far.
|reset                  Clears the accumulated program, so you can start a fresh.
|Ctrl-C, Ctrl-D, exit   Exits the REPL.
|clear                  Clears the screen.
|pin                    Pins the entered program to the top.
|!sh [COMMAND]          Execute on REPL shell commands.
'.strip_margin())
}
```
```v
fn run_shell(command string) {
if command.len >= 2 && command[0..2] == 'cd' {
command_splited := command.split(' ')
assert command_splited.len >= 2
dir := command_splited[command_splited.len - 1]
os.chdir(dir) or { eprintln('`${command}` failed, err: ${err}') }
} else {
os.system(command)
}
}
```
```v
if r.line.len …
```
> repl: support executing shell commands on REPL with `!sh [COMMAND]`

- vlib/os/os.v
Intended to fix failures similar to this one:
https://github.com/vlang/v/actions/runs/7487373820/job/20387668781
```
FAIL  [ 153/1701]  2033.642 ms vlib/flag/usage_example_test.v
V panic: mkdir failed for "C:\Users\runneradmin\.cache", because CreateDirectory 
returned: Cannot create a file when that file already exists.
```
> os: make os.cache_dir() and os.vtmp_dir() more robust to parallel test executions, extract common code

- vlib/v/gen/c/array.v
- vlib/v/tests/cast_fixed_array_to_ptr_ptr_test.v
Fix #20454
```V
struct Foo {
bar &&char
}
fn main() {
foo := Foo{
bar: unsafe {
&&char(['a', 'b', nil]!)
}
}
println(foo)
a := unsafe { cstring_to_vstring(*foo.bar) }
assert a == 'a'
}
```
> cgen: fix generated code for fixed array cast

- vlib/net/urllib/urllib.v
- vlib/net/urllib/urllib_test.v
- vlib/vweb/tests/vweb_test.v
> vweb: fix parsing url error when querypath is '//'(fix #20476)

- vlib/v/builder/cc.v
Replaces invalid linker flag "-rdynamic" with the clang/MacOS version "-Wl,-export_dynamic".
This enables cross-compiling from MacOS to Windows to work with debug enabled, which is currently broken.
I've tested this manually in my own project.
> Fix for Issue #20510: https://github.com/vlang/v/issues/20510

- cmd/tools/modules/vgit/vgit.v
- vlib/v/checker/fn.v
- vlib/v/checker/for.v
- vlib/v/checker/struct.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/index.v
- vlib/v/tests/reflection_sym_test.v
Reduce the amount of allocations done in cgen by ~2MB for recompiling V itself.
> checker,cgen: change `x.filter(cond).len > 0` to `x.any(cond)`, and `x.filter(cond) == 0` to `x.all(!cond)`

- vlib/v/checker/fn.v
- vlib/v/checker/struct.v
- vlib/v/checker/tests/missing_export_attr_arg_err.out
- vlib/v/checker/tests/modules/module_struct_noinit.out
- vlib/v/checker/tests/modules/module_struct_noinit/src/main.v
- vlib/v/checker/tests/modules/module_struct_noinit/src/mod.v
Fix #20508
```V
import mod1
fn main() {
dump(default_value[mod1.Foo]())
println(default_value[mod1.Foo]())
//a := mod1.Foo{}
}
fn default_value[T]() T {
return T{}
}
```
> checker: fix missing check for struct initialization with @[noinit] attribute through T{} usage

- cmd/tools/vrepl.v
- vlib/v/slow_tests/repl/error.repl
- vlib/v/slow_tests/repl/error_and_continue_print.repl
- vlib/v/slow_tests/repl/error_exitasdfasdf.repl
- vlib/v/slow_tests/repl/function.repl
- vlib/v/slow_tests/repl/function.repl.skip
- vlib/v/slow_tests/repl/if_and_for_with_print_inside_them.repl
> [Fix] - repl: Fixing an issue with `print` and println after the execution of for or `if` - ISSUE #20524

- vlib/v/ast/ast.v
- vlib/v/checker/fn.v
- vlib/v/markused/walker.v
The comment of PR 20527 was not clear enough to be misleading, and this PR rewrites it.
> ast, markused, checker: modified comments on generic receiver type storage

- vlib/net/unix/unix_test.v
This is a trivial change that I find useful.  If you get a connection dropped error, you immediately know if it was on a read or write operation.
> net/unix: make error messages more specific

- vlib/v/gen/c/for.v
- vlib/v/tests/for_in_option_test.v
1. Fixed #20528
2. Add tests.
```v
pub type Snowflake = int
pub struct PermissionOverwrite {
id Snowflake
n  int
}
pub struct Channel {
permission_overwrites ?[]PermissionOverwrite
}
pub fn (c Channel) get_overwrite(id Snowflake) ?PermissionOverwrite {
for overwrite in c.permission_overwrites or { return none } {
if overwrite.id == id {
return overwrite
}
}
return none
}
fn main() {
channel := Channel{
permission_overwrites: [
PermissionOverwrite{
id: 1
n: 42
},
PermissionOverwrite{
id: 2
n: 84
},
PermissionOverwrite{
id: 3
n: 6969
},
PermissionOverwrite{
id: 4
n: 4242
},
]
}
println(channel.get_overwrite(3)?.n)
}
```
outputs:
```
6969
```
> cgen: fix code generation wrong, when 'x.?[]array or {}' as a 'for-in' condition(fix #20528)

- vlib/v/checker/tests/generic_interface_method_decl_err.out
- vlib/v/checker/tests/generic_interface_method_decl_err.vv
- vlib/v/parser/struct.v
- vlib/v/parser/tests/generic_interface_decl_err.out
- vlib/v/parser/tests/generic_interface_decl_err.vv
This PR check non-generic interface defining generic method (fix #20430).
- Check non-generic interface defining generic method.
- Add test.
```v
module main
interface Abc {
test[T]()
}
struct Xyz {}
fn (xyz Xyz) test[T]() {}
fn main() {
_ := Abc(Xyz{})
}
tt1.v:4:6: error: non-generic interface `Abc` cannot define a generic method
2 | 
3 | interface Abc {
4 |     test[T]()
|         ^
5 | }
6 |
```
> parser: check non-generic interface defining generic method (fix #20430)

- vlib/v/checker/checker.v
- vlib/v/checker/return.v
- vlib/v/tests/return_map_index_with_or_block_test.v
This PR fix return map index with or_block (fix #20391).
- Fix return map index with or_block.
- Add test.
```v
fn get_value1(m map[string]int, key string) ?int {
return m[key] or { none }
}
fn get_value2(m map[string]int, key string) !int {
return m[key] or { error('not found') }
}
fn main() {
m := {
'aaa': 111
}
if ret1 := get_value1(m, 'aaa') {
println(ret1)
assert ret1 == 111
} else {
assert false
}
if ret2 := get_value2(m, 'aaa') {
println(ret2)
assert ret2 == 111
} else {
assert false
}
}
111
111
```
> checker: fix return map index with or_block (fix #20391)

- vlib/math/const.v
- vlib/v/ast/ast.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/deprecations_consts.out
- vlib/v/checker/tests/deprecations_consts.vv
- vlib/v/parser/parser.v
1. Fixed #20523
2. Add tests.
To avoid too many cluttered warnings, the deprecated notification mechanism for consts is:
- When using the const variable directly or indirectly.
- When used outside the module defined by const.
```v
import math
_ = math.max_i8
```
outputs:
```
a.v:3:10: warning: const `math.max_i8` has been deprecated since 2023-12-31, it will be an error after 2024-06-28; use built-in constant `max_i8` instead
1 | 
2 | import math
3 | _ = math.max_i8
|          ~~~~~~
4 | 
5 |
```
> ast, parser, checker: fix `@[deprecated]` attribute for in const defines (fix #20523)

- vlib/v/gen/c/fn.v
- vlib/v/tests/closure_test.v
1. Fixed #20498 
2. Add tests.
```v
fn foo() fn() {
arr := [1, 2, 3]
return fn [arr] () {
println(arr)
}
}
fn main() {
print_arr := foo()
print_arr()
}
```
v -autofree run a.v
```
[1, 2, 3]
```
> cgen: fix necessary clone when the closure param is string/array on autofree(fix #20498)

- vlib/readline/readline.v
- vlib/readline/readline_nix.c.v
Usage:
```V
import readline
fn main() {
list := ['mem', 'memory', 'method']
mut r := readline.Readline{
// completion_list: list
// or   
completion_callback: fn [list] (prefix string) []string {
return list.filter(it.starts_with(prefix))
}
}
dump(r.read_line('prompt> ')!)
}
```
> readline: completion support

- vlib/builtin/string.v
- vlib/builtin/string_test.v
```v
// Check if a string is an octal value. Returns 'true' if it is, or 'false' if it is not
@[direct_array_access]
pub fn (str string) is_oct() bool {
mut i := 0
if str[i] == `0` {
i++
} else if str[i] == `-` || str[i] == `+` {
i++
if str[i] == `0` {
i++
} else {
return false
}
} else {
return false
}
if str[i] == `o` {
i++
} else {
return false
}
if i == str.len {
return false
}
for i < str.len {
if str[i] < `0` || str[i] > `7` {
return false
}
i++
}
return true
}
// Check if a string is an binary value. Returns 'true' if it is, or 'false' if it is not
@[direct_array_access]
pub fn (str string) is_bin() bool {
mut i := 0
if str[i] == `0` {
i++
} else if str[i] == `-` || str[i] == `+` {
i++
if str[i] == `0` {
i++
} else {
return false
}
} else {
return false
}
if str[i] == `b` {
i++
} …
```
> builtin: Add `is_hex()`, `is_int()`, `is_bin()`, and `is_oct()` by strings - Feature

- vlib/builtin/string.v
- vlib/builtin/string_test.v
Fulfilling the request of @spytheman on the merged PR #20540
```v
// Check if a string is an octal value. Returns 'true' if it is, or 'false' if it is not
@[direct_array_access]
pub fn (str string) is_oct() bool {
mut i := 0
if str.len == 0 {
return false
}
if str[i] == `0` {
i++
} else if str[i] == `-` || str[i] == `+` {
i++
if str[i] == `0` {
i++
} else {
return false
}
} else {
return false
}
if str[i] == `o` {
i++
} else {
return false
}
if i == str.len {
return false
}
for i < str.len {
if str[i] < `0` || str[i] > `7` {
return false
}
i++
}
return true
}
// Check if a string is an binary value. Returns 'true' if it is, or 'false' if it is not
@[direct_array_access]
pub fn (str string) is_bin() bool {
mut i := 0
if str.len == 0 {
return false
}
if str[i] == `0` {
i++
} else if str[i] …
```
> builtin: Add empty string verification suggested on PR #20540

- doc/docs.md
- vlib/builtin/map.v
- vlib/v/ast/ast.v
- vlib/v/checker/containers.v
- vlib/v/checker/tests/map_init_invalid_update.out
- vlib/v/checker/tests/map_init_invalid_update.vv
- vlib/v/checker/tests/map_init_wrong_expected_type.out
- vlib/v/checker/tests/map_init_wrong_expected_type.vv
- vlib/v/checker/tests/map_init_wrong_update_type.out
- vlib/v/checker/tests/map_init_wrong_update_type.vv
- vlib/v/fmt/fmt.v
- vlib/v/gen/c/cgen.v
- vlib/v/parser/containers.v
- vlib/v/tests/map_init_with_update_test.v
Add support for map update-init syntax to v:
```v
foo := {
...base_map
'a': 55
'b': 66
}
```
which is functionally equivalent to:
```v
mut foo := base_map.clone()
foo['a'] = 55
foo['b'] = 66
```
except that it yields an expression which does not have to be mutable.
This PR updates:
* ast, checker, parser and cgen
* adds `new_map_update_init()` to builtin/map.v to support cgen
* docs
* v fmt
* v tests & checker tests
> v: add map update-init syntax

- vlib/v/gen/c/fn.v
- vlib/v/tests/closure_test.v
1. Fixed #20208 
2. Add tests.
```v
@[heap]
struct Abc {
value int
}
@[heap]
struct Container {
aa &Abc = unsafe { nil }
}
fn (mut c Container) m() fn () {
mut cr := &c
dump(voidptr(c.aa))
dump(voidptr(cr.aa))
f := fn [mut cr] () {	
dump(voidptr(cr.aa))
dump(cr)
}
return f
}
mut c := &Container{aa: &Abc{1234}}
dump(voidptr(c))
dump(c)
dump(voidptr(c.aa))
f := c.m()
f()
```
outputs:
```
[a.v:24] voidptr(c): 0x10241ffd0
[a.v:25] c: &Container{
aa: &Abc{
value: 1234
}
}
[a.v:26] voidptr(c.aa): 0x10241ffe0
[a.v:14] voidptr(c.aa): 0x10241ffe0
[a.v:15] voidptr(cr.aa): 0x10241ffe0
[a.v:17] voidptr(cr.aa): 0x10241ffe0
[a.v:18] cr: Container{
aa: &Abc{
value: 1234
}
}
```
```v
@[heap]
struct Container {
content int
}
fn foo(mut c Container) {
c2 := c
dump(c.content)
dump(c2.content)
tmp1 := fn [c] …
```
> cgen: fix cgen wrong when auto_heap var as closure args(fix #20208)

- cmd/tools/vast/vast.v
- vlib/v/ast/str.v
PR adds:
* `v ast` support for map update-init syntax
* `ast.Expr.str()` support for for map update-init syntax
* also added `StructInit.update_expr_pos`, which was missing
> vast,ast: output map init update expression

- vlib/db/pg/pg.c.v
PostgreSQL headers and library were not being found when compiling on FreeBSD.
> db/pg: add include and lib paths for postgres on freebsd

- vlib/v/debug/interactive_test.v
- vlib/v/debug/tests/aggregate.expect
- vlib/v/debug/tests/common.tcl
- vlib/v/debug/tests/comptime_smartcast.expect
- vlib/v/debug/tests/comptime_variant.expect
- vlib/v/debug/tests/interface_var.expect
- vlib/v/debug/tests/iteration.expect
- vlib/v/debug/tests/mut_arg.expect
- vlib/v/debug/tests/option_unwrap.expect
- vlib/v/debug/tests/smartcast.expect
- vlib/v/debug/tests/sumtype.expect
* Make the output of `./v vlib/v/debug/interactive_test.v` be much less verbose by default,
while still keeping it verbose on the CI.
`./v vlib/v/debug/interactive_test.v` now looks like this (when there is no failure):
* When there is a failure, it will be printed, as well as the command, that can be used to reproduce it:
* Simplify the .expect files, extract the common parts into a common.tcl script, sourced by the rest.
> v.debug: cleanup interactive_test.v

- doc/docs.md
change from https://github.com/vlang/v/blob/master/vlib/v/tests/project_with_c_code/mod1/wrapper.v to https://github.com/vlang/v/blob/master/vlib/v/tests/project_with_c_code/mod1/wrapper.c.v
> docs: fix link for `an example of a module that calls C code from V`

- doc/docs.md
fix typo: change `statemnts` to `statements`
> docs: fix typo (`statemnts` -> `statements`)

- vlib/v/checker/match.v
- vlib/v/checker/tests/match_enum_ref.out
- vlib/v/checker/tests/match_enum_ref.vv
Add a check for non-dereferenced enum values when used in a match statement and a corresponding test.
This fixes issue #10045.
> checker: fix non dereferenced enum in match statements (fixes #10045)

- vlib/v/ast/ast.v
- vlib/v/parser/parser.v
- vlib/v/tests/enum_from_generic_static_method_test.v
- parser: implement `Enum.from(123)!` and `Enum.from(abc)!`
- parser: cleanup the implementation of p.codegen/1
- debug and add tests
> parser: implement MyEnum.from generic static method

- cmd/tools/modules/testing/common.v
- cmd/tools/modules/testing/output.v
- cmd/tools/modules/testing/output_normal.v
- cmd/tools/vtest-self.v
- cmd/tools/vtest.v
- vlib/benchmark/benchmark.v
- vlib/v/help/build/build.txt
- vlib/v/pref/pref.c.v
- benchmark: support passing an optional preparation time for the step messages
- pref: support a -skip-running option
- testing: add `compile_begin` and `compile_end` messages to the testing.Reporter interface
- testing: support the new messages in the output_normal.v Reporter
- benchmark: add Benchmark.step_restart/0 method
- tools: fix `v test` to not skip _test.c.v files by default
- testing,benchmark: use the new -skip-running and the enhanced Reporter to implement a separate compilation time measurement for each test
> tests: show compile time and runtime for each _test.v file in separate columns

- vlib/v/checker/checker.v
- vlib/v/debug/tests/comptime_variant.expect
- vlib/v/debug/tests/comptime_variant.vv
- vlib/v/gen/c/cgen.v
- vlib/v/tests/comptime_smartcast_var_test.v
```V
type TestSum = int | bool
fn main() {
a := TestSum(true)
$for v in TestSum.variants {
if a is v {
dump(a)
}
}    
}
```
> checker: fix .variant smartcast on non-comptime variables

- examples/regex/readme.md
- fix typo: change `exteranl` to `external`
- tidy up list
> examples: [regex] fix typo (`exteranl` -> `external`) and tidy up list

- vlib/json/json_decode_option_enum_test.v
- vlib/v/gen/c/json.v
Fix #20593
```V
import json
enum Lang {
en = 1
}
struct Request {
lang ?Lang // ?string, ?int are ok
}
assert dump(json.decode(Request, '{}')!) == Request{
lang: ?Lang(none)
}
assert dump(json.decode(Request, '{"lang": "en"}')!) == Request{
lang: .en
}
}
```
> json: fix struct with option enum field

- examples/flappylearning/README.md
change from https://github.com/vlang/v/blob/master/examples/flappylearning/img/flappy.png to https://github.com/vlang/v/blob/master/examples/flappylearning/assets/img/flappy.png
> examples: [flappylearning] fix link for image flappy.png

- vlib/v/debug/tests/mut_sumtype.expect
- vlib/v/debug/tests/mut_sumtype.vv
- vlib/v/debug/tests/option.expect
- vlib/v/debug/tests/option.vv
- vlib/v/gen/c/cgen.v
Fix dereferencing of variable when passing to .str() which expects ptr.
```V
struct Test2 {}
struct Test3 {}
type Test = Test2 | Test3
fn (f Test) test(mut t Test) {
$dbg;
}
fn main() {
mut a := Test(Test2{})
a.test(mut a)
}
```
> debug: fix variable dereferencing

- vlib/vweb/csrf/README.md
- vlib/x/vweb/README.md
- vlib/x/vweb/csrf/README.md
- vlib/x/vweb/sse/README.md
remove unused whitespace and fix typo:
vweb.csrf: 
- adn -> and
x.vweb:
- nothinng -> nothing
- controll -> control
- te -> the
- registerted -> registered
- similair -> similar
x.vweb.csrf:
- HTTPOnlye -> HTTPOnly
- adn -> and
x.vweb.sse:
- seperate -> separate
- mesage -> message
> vweb & x.vweb: fix typo in README documentation

- doc/docs.md
- examples/readdir.v
- vlib/os/os.v
- vlib/os/os_nix.c.v
os.ls (using readdir) doc and example
// ls returns ![]string of the files and folders in the given `path` ( os.ls uses C.readdir ). It includes symbolic links. See also: `os.is_dir`, `os.is_file`
// Example: https://github.com/vlang/v/blob/master/examples/readdir.v
// ```
//   entries := os.ls(os.home_dir()) or { [] }
//   for entry in entries {
//     if os.is_dir(os.join_path(os.home_dir(), entry)) {
//       println('dir: $entry')
//     } else {
//       println('file: $entry')
//     }
//   }
// ```
pub fn ls(path string) ![]string {
> os.ls (using readdir) doc and example

- doc/docs.md
Added a note to the Range `for` section in the documentation to explain the rationale behind using exclusive range notation and zero-based indexing. From spytheman in Discord https://discord.com/channels/592103645835821068/592115457029308427/1194711919572033576, This update references Edsger W. Dijkstra's 'Why Numbering Should Start at Zero' to provide theoretical backing and clarity on this design choice.
> docs: update range `for`: 0-based index rationale

- vlib/v/debug/debug.v
I have a little OCD 😁, I missed cleaning the screen.
> debug: add command to clear the terminal in the $dbg prompt

- examples/term.ui/cursor_chaser.v
- examples/term.ui/event_viewer.v
- examples/term.ui/pong.v
- examples/term.ui/rectangles.v
- examples/term.ui/term_drawing.v
- examples/term.ui/text_editor.v
- examples/term.ui/vyper.v
When using clang version 14, the function types for init_fn, frame_fn, event_fn, and cleanup_fn were not strictly enforced and the example programs in examples/term.ui would all compile.
With clang version 16, these function types are strictly checked and the added type definitions clean up the errors.
> examples/term.ui: add casts to term.ui functions to satisfy stricter type checking

- vlib/os/process_windows.c.v
According to Microsoft documentation [ns-processthreadsapi-startupinfow](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/ns-processthreadsapi-startupinfow), `cb` is the size of the structure(_STARTUPINFOW), in bytes.
Run the following test code `test-process.v` under the `cmd` console:
```
import os
fn main() {
mut process := os.new_process('v')
process.set_args(['-v'])
process.set_redirect_stdio()
process.wait()
//  println('process : ${process}')
println('filename         : ${process.filename          }')
println('pid              : ${process.pid               }')
println('code             : ${process.code              }')
println('status           : ${process.status            }')
println('err              : ${process.err               }')
println('args …
```
> os(windows): Fix `win_spawn_process` not using `stdout pipe` in `cmd` console

- vlib/io/buffered_reader.v
- vlib/io/custom_string_reading_test.v
BufferedReader.read_line() used to return `error('none')` upon reaching the end of the stream instead return `io.Eof`.
> io: ensure BufferedReader.read_line() returns io.Eof

- vlib/v/gen/c/cgen.v
- vlib/v/tests/generic_smartcast_test.v
Fix #20590
```V
fn cast_interface[T, U](u U) T {
$if U is $interface {
if u is T {
return u
} else {
panic('expected t to be ${typeof[T]().name}, got ${typeof[U]().name}')
}
} $else {
$compile_error('not an interface')
}
}
interface Foo {
f()
}
struct Bar {}
fn (bar Bar) f() {}
struct Baz {}
fn (baz Baz) f() {}
fn (_ Bar) g() int {
return 0
}
fn (_ Baz) g() int {
return 1
}
fn f(foo Foo) int {
if foo is Bar {
return cast_interface[Bar, Foo](foo).g()
}
if foo is Baz {
return cast_interface[Baz, Foo](foo).g()
}
return -1
}
assert f(Bar{}) == 0
assert f(Baz{}) == 1
}
```
> cgen: fix interface generic smartcast

- doc/docs.md
- vlib/v/debug/debug.v
This PR add docs for recent `clear` debug cmd and fix the debug helps format.
> debug: fix help and add docs for clear cmd

- vlib/v/builder/cc.v
Close #20481 
Tested on FreeBSD 13.2, `execinfo` depends on `elf`. After adding the `-lelf` link flag, the compiler passes normally.
> builder: add '-lelf' to linker flags on freebsd(fix #20481)

- vlib/net/smtp/smtp.v
This PR: Implement smtp mail attachment support.
Close #19920
```v
send_cfg := smtp.Mail{
from: '${nicename}<${sender}>'
to: receivers
subject: subject
body_type: smtp.BodyType.html
body: body
attachments: [
smtp.Attachment {
filename: 'readme.txt'
bytes: '...Some file content...'.bytes()
}
]
}
mut client := smtp.new_client(client_cfg)!
client.send(send_cfg)!
client.quit()!
```
> smtp: Implement smtp mail attachment support(fix #19920)

- vlib/vweb/README.md
This is updating `vweb`'s `Quick Start` guide with the current command to get a web project started.
> vweb: fix quickstart docs on how to create a new project

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/testdata/func_type_dependency.c.must_have
- vlib/v/gen/c/testdata/func_type_dependency.vv
Allow a function type to depend on another.
Fixes #19367.
NB. I tried to use depgraph.DepGraph but for some reason it did not sort the types appropriately so I resorted to a basic slice algorithm.
> v.gen.c: support inter-dependent function types

- vlib/v/ast/ast.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/testdata/global_export_nix.c.must_have
- vlib/v/gen/c/testdata/global_export_nix.vv
- vlib/v/markused/walker.v
- vlib/v/parser/parser.v
Fix #20477
```V
const foo = "bar"
@[export]
__global global_exported = foo + "qux"
```
```
0000000000000000       O *UND*  0000000000000000              global_exported
```
> v: enable @[export] for global

- vlib/vweb/vweb.v
- vlib/x/vweb/vweb.v
Update error checking when a bufferred reader is empty.
The error in the `io` module got changed in #20619
> vweb, x.vweb: update error checking when checking for io.Eof

- vlib/net/http/http.v
Temporary fix #20506 
More details from here : https://github.com/vlang/v/issues/20506#issuecomment-1908943267
Thanks at @spytheman and @Casper64 for testing the proposed temporary solutions and taking the time to identify the one with the least impact on performance. ( See comments in issue ).
> net.http: Temporary fix intermittent segfault with http get text and gcc 13 2 [issue #20506]

- vlib/io/buffered_reader.v
- vlib/io/reader_test.v
Enable BufferedReader to work consistently with lines terminated by characters other than \n (such as \0 when using coreutils with the zero-terminated option). 
Test for the new function has been added in reader_test.v; tests for existing read_line() pass as before.
> Enhance read_line() for BufferedReader to accept custom line delimiters

- vlib/builtin/builtin.c.v
- vlib/builtin/builtin_unbuffer_stdout_test.v
This API addresses this Discord discussion: https://discord.com/channels/592103645835821068/592294828432424960/1161031983506411533
With it, you can implement a simple progress bar, using code like this:
```v
import time
unbuffer_stdout()
for _ in 0 .. 10 {
print('*')
time.sleep(100 * time.millisecond)
}
println(' done')
```
Note that each `*` will appear in your terminal right away. If you comment the `unbuffer_stdout()` call, then each star will be buffered, and you will see the whole bar, only at the end (after the println() call).
> builtin: implement unbuffer_stdout/0

- vlib/x/vweb/context.v
- vlib/x/vweb/tests/persistent_connection_test.v
- vlib/x/vweb/tests/vweb_test.v
- vlib/x/vweb/vweb.v
Allow persistent HTTP connections so multiple requests and responses can be sent over a single connection.
Remove the default behaviour of vweb to always send the `Connection: close` header. The connection will be closed when the client sends the `Connection: close` header in the request, or if a read on the socket returns `0` indicating that the client has closed the connection. According to HTTP 1.1 standard.
This pr greatly improves the speed of `x.vweb` for clients that support HTTP 1.1 and higher
> x.vweb: support HTTP 1.1 persistent connections

- cmd/tools/vdoc/markdown.v
- cmd/tools/vdoc/tests/testdata/comments/main.comments.out
- cmd/tools/vdoc/tests/testdata/comments/main.out
- cmd/tools/vdoc/tests/testdata/comments/main.v
- cmd/tools/vdoc/vdoc.v
- vlib/v/doc/doc.v
This PR addresses issue #8044 and fixes the -comments flag being always added for json and md generations.
> vdoc: fixes for #8044 and -comments flag

- vlib/v/checker/assign.v
- vlib/v/checker/tests/assign_blank_none_err.out
- vlib/v/checker/tests/assign_blank_none_err.vv
> v.checker: disallow assigning none to _

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/consts_with_comments_end_keep.vv
- vlib/v/fmt/tests/consts_with_comments_expected.vv
- vlib/v/fmt/tests/consts_with_comments_input.vv
> v.fmt: drop newline in end comments for const

- vlib/os/process.c.v
- vlib/os/process_nix.c.v
- vlib/os/process_windows.c.v
There is only signal_kill() option to terminate a process wich is not working.
The proper way is to send TERM signal.
> os: Add proper process termination in Linux

- vlib/bitfield/bitfield.v
- vlib/bitfield/bitfield_test.v
`set_if()` sets bit number 'bit_nr' to 1 (count from 0) if `cond` is true or clear the bit.
`toggle_bits()` changes the value (from 0 to 1 or from 1 to 0) of bits
`set_bits()` sets multiple bits in the array to 1.
`clear_bits()` clear multiple bits in the array to 0.
`has()` test if *at least one* of the bits is set
`all()` test if *all* of the bits are set
> bitfield: enhance multiple flags operation

- vlib/v/checker/match.v
- vlib/v/checker/tests/option_fn_err.out
Fix #20663
```V
enum Test {
a
b
}
fn optional() ?Test {
return none
}
fn optional2() ?Test {
return .a
}
fn main() {
match optional() {
.a { assert false }
else { assert true }
}
match optional2() {
.a { }
else { }
}
}
```
> checker: fix checking for option matching with non-option

- vlib/os/file.js.v
- vlib/os/open_and_read_from_file_test.js.v
Fixed #20501 File.read() function for the JavaScript backend. 
The issue was due to incorrect array access in the JavaScript generated from V code.
To respond at ticket expectation : 
- _Using the js backend: expected to either read a non-zero amount of bytes, or raise an error._
The original function already includes a try-catch block to manage errors. Unless specifically requested, I don't plan to add additional error handling
_- Using the js_browser: expected to either fail compilation (since File I/O is unavailable in the browser), or for os.open() to always return an error._
the existing code already handles errors. If **open_file()** is called in a non-NodeJS environment, an error is generated. However, it appears that the test in ticket was conducted using Node.js, which could …
> os: Fix File.read() in JS backends [Issue : #20501]

- GNUmakefile
Trivial patch to make V build fine within an MSYS2 shell
> Use standard default RM make variable to fix MSYS2 env

- vlib/v/gen/c/cgen.v
Fix #20710
```v
struct Foo {
mut:
x int
}
struct Bar {
mut:
y int
}
type Foobar = Foo | Bar
fn main() {
mut bar := Foobar(Bar{y: 123})
assert bar as Bar.y == 123
}
```
> cgen: fix as cast as selector

- vlib/v/gen/c/infix.v
- vlib/v/tests/method_call_none_check_test.v
Fix #20711
```V
struct Foo {
x int
}
struct Bar {
x int
}
type Foobar = Foo | Bar
struct Foobars {
m map[string]Foobar
}
fn (f &Foobars) find_foobar(name string) ?Foobar {
return f.m[name] or { return none }
}
fn (mut f Foobars) is_known(name string) bool {
return f.find_foobar(name) != none
}
fn main() {
mut foobars := Foobars{
m: map[string]Foobar{}
}
println(foobars.is_known('deadbeef'))
}
```
> cgen: fix method call checking against `none` 

- examples/xvweb/cors/vweb_cors_example.v
- vlib/x/vweb/middleware.v
- vlib/x/vweb/tests/cors_test.v
fix for #20708 
This pr adds a middleware function in x.vweb to handle CORS requests.
It also includes a small test and a modified example of `examples/vweb/cors`
CORS request can be traced by adding `-d vweb_trace_cors` when you compile
You only need to add `vweb.cors` as middleware to your app and configure CORS
**Example:**
```v
import x.vweb
pub struct Context {
vweb.Context
}
pub struct App {
vweb.Middleware[Context]
}
fn main() {
mut app := &App{}
// use the cors middleware
app.use(vweb.cors[Context](vweb.CorsOptions{
origin: '*'
allowed_methods: [.get, .head, .put, .post, .patch, .delete]
}))
vweb.run[App, Context](mut app, 8080)
}
```
> x.vweb: add cors middleware

- vlib/clipboard/clipboard_windows.c.v
**clipboard: Add ``unsafe`` line for windows**
This PR modifies the `WndClassEx` struct initialization to handle `lpsz_menu_name` and `h_icon_sm` in an unsafe block. This is necessary because V language requires explicit `unsafe` block for operations that could lead to undefined behaviors.
Before:
```v
// v/vlib/clipboard/clipboard_windows.c.v
.
.
.
wndclass := WndClassEx{
cb_size: sizeof(WndClassEx)
lpfn_wnd_proc: voidptr(&C.DefWindowProc)
lpsz_class_name: class_name.to_wide()
lpsz_menu_name: 0
h_icon_sm: 0
}
```
After:
```v
// v/vlib/clipboard/clipboard_windows.c.v
.
.
.
wndclass := WndClassEx{
cb_size: sizeof(WndClassEx)
lpfn_wnd_proc: voidptr(&C.DefWindowProc)
lpsz_class_name: class_name.to_wide()
lpsz_menu_name: unsafe { 0 }
h_icon_sm: unsafe { 0 }
}
```
Fix this notice
```bash …
```
> Added unsafe line in clipboard_windows.c.v

- vlib/builtin/string.v
- vlib/builtin/string_test.v
u8_array returns the value of the hex/bin string as u8 array.
hex string example: `'0x11223344ee'.u8_array() == [u8(0x11),0x22,0x33,0x44,0xee]`.
bin string example: `'0b1101_1101'.u8_array() == [u8(0xdd)]`.
underscore in the string will be stripped.
This will help convert a hex/bin format string into a u8 array.
> builtin: add string to u8 array support

- vlib/vweb/tests/dynamic_template_manager_test_server/dynamic_template_manager_test_server.v
- vlib/x/templating/dtm/dynamic_template_manager.v
- vlib/x/templating/dtm/dynamic_template_manager_test.v
To adjust certain behaviors recommended in this PR: #20716 , the DTM has undergone some minor modifications:
- The creation and initialization of a DTM instance have been merged into the same function
- Some function names have been revised.
- Now, for the cache folder : User can define cache folder path. If not exist or problem with it, an attempt will be made to create the directory in the temporary storage area of the OS. Otherwise, cache system will be desactived and the problem is reported if the user had activated the cache service..
- Internal and external test files have been updated accordingly.
- Raw text files are now managed by the dtm
@spytheman  I will update the documentation in due course. However, this PR needs to be reviewed and, if accepted, merged as a priority; …
> dtm: redesign certain parts

- vlib/v/parser/parse_type.v
- vlib/v/parser/tests/already_existing_sym_err.out
- vlib/v/parser/tests/already_existing_sym_err.vv
Fix #20730
```v
@[translated]
module vnkxcb
type Nk_size = u32
union Nk_handle {
ptr voidptr
id int
}
enum Nk_plugin_alloc {
nk_tree_node
nk_tree_tab
}
type Nk_plugin_alloc = fn (Nk_handle, voidptr, Nk_size) voidptr // already registered name as Enum below
```
> parser: fn type declaration does not check already registered name

- vlib/x/vweb/README.md
Add a small example in the README on how to use the `serve_static` method on the `StaticHandler` struct.
At the start of the `Static files` doc section is an example file structure. That one is also used for this example
> x.vweb: add serve_static example in README

- vlib/os/os_windows.c.v
- vlib/v/builder/builder_test.v
This PR enables `v test vlib/v/builder/builder_test.v` to pass the test on Windows systems below Win10.
The following are the test results before modification:
```
v test                      vlib/v/builder/builder_test.v
---- Testing... ----------------------------------------------------------------
FAIL  2431.316 ms vlib/v/builder/builder_test.v
retry: 1
comp_cmd: "D:\gym\test\mingw-w64-packages\mingw-w64-v\src\v-weekly.2024.05\mingw-w64-x86_64-v.exe" -skip-running   -o "D:\gym\test\mingw-w64-packages\mingw-w64-v\tmp\mingw-w64-x86_64-v-weekly.2024.05-1\v_0\tsession_379c_25796335\01HNF86CWK22A0VZCBA79SRX6H\builder_test.exe" "D:\gym\test\mingw-w64-packages\mingw-w64-v\src\v-weekly.2024.05\vlib\v\builder\builder_test.v"
run_cmd: "D:\gym\test\mingw-w64-packages\mingw-w64-v\tmp\mingw-w64-x86 …
```
> test: make 'vlib/v/builder/builder_test.v' pass on older Windows versions.

- vlib/v/gen/c/cheaders.v
```sh
make fresh_vc
make[1]: Entering directory '/home/runner/work/v/v'
rm -rf ./vc
git clone --filter=blob:none --quiet https://github.com/vlang/vc ./vc
make[1]: Leaving directory '/home/runner/work/v/v'
cd ./vc && git clean -xf && git pull --quiet
make fresh_tcc
make[1]: Entering directory '/home/runner/work/v/v'
rm -rf ./thirdparty/tcc
git clone --filter=blob:none --quiet --branch thirdparty-linux-amd64 https://github.com/vlang/tccbin ./thirdparty/tcc
make[2]: Entering directory '/home/runner/work/v/v'
make[2]: Leaving directory '/home/runner/work/v/v'
make[1]: Leaving directory '/home/runner/work/v/v'
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
cc  -std=gnu99 -w -o v1.exe ./vc/v.c -lm -lpthread 
./v1.exe -no-parallel -o v2.exe  cmd/v
vlib/v/gen/c/cheaders.v:839:52: error: …
```
> cgen: remove ull, which will cause compile error?

- vlib/v/gen/c/fn.v
- vlib/v/tests/comptime_smart_receiver_test.v
> cgen: fix comptime smartcast as receiver on method call

- vlib/os/inode.c.v
- vlib/os/os.c.v
- vlib/os/os.v
- vlib/os/os_nix.c.v
- vlib/os/os_stat_default.c.v
- vlib/os/os_stat_windows.c.v
Goal: simplify `os` codebase and reduce number of unsafe blocks.
Changes:
- Introduce os.lstat() to call C.lstat explicitly to be consistent with the behavior of C.stat() and C.lstat()
- Refactor the following functions to use os.stat() or os.lstat(): file_size, cp, is_executable, is_dir, is_link, kind_of_existing_path, file_last_mod_unix, posix_set_permission_bit, and inode
- Add comments to the Stat struct
When appropriate because of Win API instead of C lib calls, split functions between os_stat_default.c.v or os_stat_windows.c.v.
Regression tested with existing os tests.
> os: refactor to use os.stat and os.lstat instead of unsafe C calls

- vlib/v/ast/table.v
- vlib/v/tests/const_order_with_str_interp_test.v
> table: fix global const ordering with string inter literal

- vlib/orm/orm_insert_test.v
- vlib/v/gen/c/orm.v
Hello,
Fixed #20017 
Fixed #20019 
To achieve this, a condition has been added in cgen.orm to first verify if the primary element has been successfully inserted. Following this, it checks if the sub-element insertions are successful. 
If not, the error is captured and returned to the user code for handling as desired.
A test function has also been added.
Would it be necessary to includes files in v/slow_tests/ for this update?
I am available for any suggestions/modifications.
> orm: fix orm insert issue if table missing [Issue : #20017]

- vlib/builtin/builtin_d_gcboehm.c.v
Before this commit, V didn't link with user32 on Windows for compilers other than tcc, so the MessageBoxA call in gcboehm was an unresolved symbol.
This fixes https://github.com/vlang/v/issues/20724.
> builtin: link user32 for boehm GC on Windows

- vlib/builtin/builtin_d_gcboehm.c.v
- vlib/coroutines/coroutines.c.v
- vlib/coroutines/sp_corrector.c
- vlib/v/gen/c/cmain.v
**This will only work once all the GC static libs are rebuilt to the newest version (actually it seems to be passing anyway, maybe there are no tests running for it 🤔)**
This fixes the GC crashes with coroutines. 
The segfaults were caused because boehm GC knows nothing about coroutines, it only knows about threads.
coroutines allocate their own stack and then the stack pointer is modified to point to that stack, however the GC does not know that this has happened. So we need to tell the GC about the correct stack base.
> fix coroutines with boehm GC by using stack pointer corrector

- cmd/tools/vtest-self.v
- vlib/v/ast/scope.v
- vlib/v/tests/orm_create_several_tables_test.v
Fix https://github.com/vlang/v/issues/18324 .
> ast: make Scope.find methods more robust, when called on default initialised `scope &Scope = unsafe { nil }` fields

- examples/js_dom_draw_benchmark_chart/README.md
- examples/js_dom_draw_benchmark_chart/chart/README.md
Example was renamed, but README files weren't updated.
> fix path in `js_dom_draw_benchmark` example docs

- vlib/builtin/builtin_d_gcboehm.c.v
- vlib/builtin/builtin_nix.c.v
- vlib/builtin/builtin_notd_gcboehm.c.v
- vlib/builtin/builtin_windows.c.v
With the new prebuilt libgc.a, I get warnings when running gg programs, similar to this one: 
```
#0 14:26:29 ᛋ master /v/oo❱v run examples/gg/mandelbrot.v
GC Warning: Heap grown by 4600 KiB while GC was disabled
```
This PR silences them by default, while also giving an API for redirecting them to a user specified callback, if needed.
> builtin: add gc_collect/0, gc_get_warn_proc/0, gc_set_warn_proc/1. Use them to turn off GC warnings by default.

- vlib/x/sessions/README.md
- vlib/x/sessions/db_store.v
- vlib/x/sessions/memory_store.v
- vlib/x/sessions/sessions.v
- vlib/x/sessions/store.v
- vlib/x/sessions/tests/db_store_test.v
- vlib/x/sessions/tests/memory_store_test.v
- vlib/x/sessions/tests/session_app_test.v
Change the session store implementation to use results instead of options. This way (database) errors can be propagated and handled by the end users instead of forcing a session store to handle the error.
Could not find any reason why the `db_store_test` failed very rarely (see [pr checks of 20774](https://github.com/vlang/v/actions/runs/7855494077/job/21437262845?pr=20774)). Adding error propagation will also help debug future issues.
> x.sessions: change session Store interface to use results instead of options

- cmd/tools/modules/testing/common.v
- cmd/tools/vtest-self.v
- cmd/tools/vtest.v
- vlib/v/pref/should_compile.v
- vlib/v/tests/filtering_android_outside_termux_test.v
- vlib/v/tests/filtering_macos_test.v
- vlib/v/tests/filtering_nix_test.v
- vlib/v/tests/filtering_windows_test.v
Allow OS-specific _test.v files analogous to the logic re: `foo_nix.c.v` to make it easier to write platform-specific tests without a lot of `$if !windows {}` type code.
`foo_nix_test.v` would only run on nix OSes and `bar_windows_test.v` only on Windows, etc. On a non-targeted host OS, v test will skip the test with the `[SKIP]` message.
Technically, this could affect existing tests (though I didn't find any in the V repo) that are unfortunately named something like `<something>_windows_test.v` without targeting intention but this would be caught by the dev seeing the [SKIP] message.
`should_test()` in cmd/tools/vtest.v has been modified to check for an OS suffix and skip the test if the suffix is not a target of the host OS.
`pub fn (this_os &OS) is_target_of(target string) bool` has …
> vtest,pref: add ability to have platform specific _test.v files

- CONTRIBUTING.md
I didn't find a reference to `v check-md` in `CONTRIBUTING.md` so I added it
> doc: add Markdown check to contributing rules

- examples/vweb/static_website/README.md
- examples/vweb/static_website/dist/another.html
- examples/vweb/static_website/dist/index.html
- examples/vweb/static_website/server.v
- vlib/x/vweb/README.md
- Add a mention of `index.html` and `index.htm` serving from root URL of a static folder (see #20784)
- Add a ready to compile example and a link to it in documentation
> doc: x.vweb static website capabilities

- cmd/tools/vcheck-md.v
Before:
After:
New output, when there are no errors (previously, it was an empty line):
> tools: make the output of `v check-md .` more informative

- vlib/v/gen/c/fn.v
- vlib/v/tests/map_generic_call_test.v
> cgen: fix map methods call with generic types

- cmd/tools/vast/vast.v
- vlib/v/ast/ast.v
- vlib/v/checker/fn.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/sumtype_ptr_arg_test.v
> cgen, ast, checker: fix auto deref arg when fn expects ref

- cmd/tools/vpm/common.v
- cmd/tools/vpm/install.v
- cmd/tools/vpm/install_test.v
- cmd/tools/vpm/parse.v
- cmd/tools/vpm/remove_test.v
- cmd/tools/vpm/vpm.v
Closes #20775
Adds a fix which is already used in other places to work around failing rm_dir commands (apparently permissions issues) on Windows.
> vpm: fix remove command on Windows, add test

- vlib/v/pref/pref.c.v
Fix for #20834 
This PR tries to use `curl` to download the coroutine's .so file for systems that do not use `wget`, and prints a message with manual download instructions if both `wget` and `curl` fail.
> pref: allow fetching the photonwrapper .so (for the coroutines) with curl too, or print details for manual download

- vlib/x/vweb/README.md
- VWeb > vweb unification
- Missing commas
- other small fixes
> docs: x.vweb typos

- vlib/time/format.v
- vlib/time/time_format_test.v
This adds a UNIX time stamp to HTTP date/time stamp as defined in [RFC2616](https://www.rfc-editor.org/rfc/rfc2616#section-3.3.1), which should be used in HTTP headers such as `Expires`, `Last-Modified`, etc.
A test has been added to `vlib/time/time_format_test.v` to cover this new function.
> time: add http_header_string() for HTTP date/time stamps

- vlib/v/parser/orm.v
- vlib/v/parser/testdata/silent/orm_infinite_loop_in_parser_sql_stmt.vv
- vlib/v/parser/v_parser_test.v
- vlib/v/parser/v_print_v_files_works_test.v
- parser: fix `-silent -print-v-files` (fix #20869)
- cleanup the output of v_parser_test.v
- parser: add a simpler (and faster to compile) test v_print_v_files_works_test.v
> parser: fix infinite loop in Parser.sql stmt in `-silent -print-watched-files` mode (used by `v watch`)

- vlib/builtin/string.v
- vlib/encoding/txtar/README.md
- vlib/encoding/txtar/pack_unpack.v
- vlib/encoding/txtar/txtar.v
- vlib/encoding/txtar/txtar_test.v
- encoding: add txtar/README.md
- vlib: add encoding.txtar (draft implementation)
> vlib: add `encoding.txtar` (port of Go's txtar module)

- vlib/v/gen/c/comptime.v
- vlib/v/slow_tests/inout/comptime_selector_of_interface.out
- vlib/v/slow_tests/inout/comptime_selector_of_interface.vv
This PR fix comptime selector of interface (fix #20864).
- Fix comptime selector of interface.
- Add test.
```v
struct People {
count int
}
interface IPeople {
count int
}
fn main() {
p := IPeople(People{42})
dump(p.count)
$for f in IPeople.fields {
dump(p.$(f.name))
}
}
[.\\tt1.v:12] p.count: 42
[.\\tt1.v:14] p.$(f.name): 42
```
> cgen: fix comptime selector of interface (fix #20864)

- vlib/v/checker/assign.v
- vlib/v/tests/struct_field_init_with_generic_fn_test.v
This PR fix struct field init with generic fn variable (fix #20847).
- Fix struct field init with generic fn variable.
- Add test.
```v
struct ClassInfo {
func fn () int = unsafe { nil }
}
pub fn func2[T]() int {
return sizeof(T)
}
pub fn func1[T]() int {
ci := ClassInfo{
func: func2[T]
}
return ci.func()
}
struct Struct1 {}
struct Struct2 {}
fn main() {
r1 := func1[i32]()
println(r1)
assert r1 == 4
r2 := func1[bool]()
println(r2)
assert r2 == 1
r3 := func1[Struct1]()
println(r3)
assert r3 == 1
r4 := func1[Struct2]()
println(r4)
assert r4 == 1
}
4
1
1
1
```
> checker: fix struct field init with generic fn variable (fix #20847)

- vlib/v/tests/init_global_test.v
> tests: fix `init_global_test.v` failing occasionally

- vlib/crypto/sha256/sha256.v
- vlib/crypto/sha256/sha256_test.v
- vlib/crypto/sha512/sha512.v
- vlib/crypto/sha512/sha512_test.v
This PR basically fix behavioral bug in `crypto.sha256` and `crypto.sha512` especially in future deprecated `.checksum()` method of the Digest. This is discussed previously with @joe-conigliaro on discord channel, see this [thread](https://discord.com/channels/592103645835821068/592106336838352923/1209734382357577800) for detail.
Basically,  behavioral `.checksum()` bug comes from the facts the `.checksum()` just calls private `.checksum_internal()` without returning proper size of the underlying digest. Its affect `sha256` or `sha512` Digest when operates on non standard size of the module, ie., `size224` for `sha256` and the size other than `sha512.size` that sha512 support them.
This snippet from discord copied here for sake of clarity
```v
import encoding.hex
import crypto.sha256
fn …
```
> sha256/512: fix behavioral bug in .checksum

- vlib/os/os_stat_test.v
On FreeBSD, the stat.rdev value of a regular file and its parent directory are not necessarily the same.
> os: don't check rdev equality on FreeBSD

- vlib/v/tests/struct_field_init_with_generic_anon_fn_test.v
This PR fix struct field init with generic anon fn (fix #18294).
- Has been fixed by #20878.
- Add test.
```v
pub struct Module {
}
pub struct Service {
callback fn () = unsafe { nil }
}
pub fn (mut self Module) do_anything[T]() {
}
pub fn (mut self Module) register[T]() {
_ := Service{
callback: fn [mut self] [T]() {
self.do_anything[T]()
}
}
}
struct Something {
}
struct SomethingDifferent {
}
fn main() {
mut mod := Module{}
mod.register[Something]()
mod.register[SomethingDifferent]()
assert true
}
```
> checker: fix struct field init with generic anon fn (fix #18294)

- vlib/gg/gg.c.v
- vlib/gg/text_rendering.c.v
Update the dpi scaling in ctx and ctx.ft when a window is dragged to a monitor with a different dpi scaling.
> ui: handle dpi change when moving window to another monitor

- vlib/v/ast/ast.v
- vlib/v/fmt/fmt.v
- vlib/v/parser/containers.v
- vlib/v/parser/expr.v
- vlib/v/parser/parser.v
- vlib/v/tests/alias_array_no_cast_init_test.v
This PR fix alias array no cast init (fix #20715 #10748).
- Fix alias array no cast init.
- Add test.
```v
pub type Labels = [][]int
pub fn new_labels(width int, height int) Labels {
mut labels := Labels{len: height, init: []int{len: width}}
return labels
}
fn main() {
mut labels := new_labels(2, 2)
println(labels)
assert labels == [[0, 0], [0, 0]]
}
Labels([[0, 0], [0, 0]])
```
> ast, parser, fmt: fix alias array no cast init (fix #20715 #10748)

- vlib/v/ast/ast.v
- vlib/v/checker/checker.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/generics_method_with_embedded_structs_test.v
> ast,checker,cgen: fix generics function with embedded structs, ensure correct link generation in cgen

- vlib/v/checker/match.v
- vlib/v/checker/tests/match_branch_call_expr_arg_mismatch.out
- vlib/v/checker/tests/match_branch_call_expr_arg_mismatch.vv
This PR fix checking match branch call expr twice (fix #20709).
- Fix checking match branch call expr twice.
- Add test.
```v
struct Foo {
mut:
x int
}
struct Bar {
mut:
y int
}
type Foobar = Foo | Bar
fn mutate_foobar1(mut foobar Foobar) {
match foobar {
Foo {
mutate_foo(mut foobar)
}
Bar {
mutate_bar(mut foobar)
}
}
}
fn mutate_foobar2(mut foobar Foobar) int {
return match foobar {
Foo {
mutate_foo(mut foobar)
}
Bar {
mutate_bar(mut foobar)
}
}
}
fn mutate_foo(mut foo Foo) int {
foo.x = 5
return 5
}
fn mutate_bar(mut bar Bar) int {
bar.y = 10
return 10
}
fn main() {
mut bar := Bar{y: 0}
mutate_foobar1(mut bar)
mutate_foobar2(mut bar)
}
tt1.v:16:19: error: cannot use `&Foobar` as `&Foo` in argument 1 to `mutate_foo`
14 |     match foobar {
15 |         Foo {
16 …
```
> checker: fix checking match branch call expr twice (fix #20709)

- vlib/x/json2/encoder.v
- vlib/x/json2/tests/encode_struct_skippable_fields_test.v
- vlib/x/json2/tests/encode_struct_test.v
Although all tests were passing, the encoding of structs were not working properly for some reason, even if they were on the tests.
However my struct encoding tests were only using generic structs that only had fields of the same type:
```v
struct StructTypeSkippedFields[T] {
mut:
val  T @[json: '-']
val1 T
val2 T @[json: '-']
val3 T
}
```
These kind of structs were passing on the tests. However as soon as I tested them with non generic structs with different types on each field, they were not encoding correctly, having missing commas
This is what it would look like:
```v
struct StructTypeSkippedField5 {
pub mut:
val string @[json: '-']
val1 int @[json: '-']
val2 f64
val3 bool
val4 string
val5 string
}
json2.encode(StructTypeSkippedField5{
val: 'foo'
val1: 999
val2: 999.0
val3: true
val4: …
```
> [x.json2] [FIX] Encoding Structs with Skipped fields not generating commas correctly

- vlib/v/fmt/tests/comptime_if_after_inc_expr_keep.vv
- vlib/v/parser/expr.v
This PR fix formatting comptime if expr after inc expr (fix #20927).
- Fix formatting comptime if expr after inc expr.
- Add test.
vlib\v\fmt\tests\comptime_if_after_inc_expr_keep.vv
```v
fn main() {
mut i := 0
i++
$if abc ? {
println(i)
}
println('done')
}
```
> parser: fix formatting comptime if expr after inc expr (fix #20927)

- vlib/v/gen/c/cgen.v
- vlib/v/tests/return_option_call_in_non_option_fn_test.v
This PR fix returning option call in non-option fn (fix #20939).
- Fix returning option call in non-option fn.
- Add test.
```v
import rand
pub fn random_number() i64 {
return rand.i64_in_range(111111, 999999) or { rand.i64() }
}
fn main() {
ret := random_number()
println(ret)
assert true
}
350474
```
> cgen: fix returning option call in non-option fn (fix #20939)

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/testdata/global_initializer.c.must_have
- vlib/v/gen/c/testdata/global_initializer.vv
Fix code generated to build `vcc` on with `-cc gcc`
> cgen: fix global initializer of fixed array on gcc

- vlib/v/checker/if.v
- vlib/v/checker/postfix.v
- vlib/v/gen/c/comptime.v
- vlib/v/tests/comptime_is_interface_check_test.v
> cgen: fix comptime `is` condition when using interface

- vlib/v/doc/doc.v
- vlib/v/doc/doc_test.v
Fixes: #20714.
This PR adds attributes for enums and structs to the documentation.
Here is a light-mode example:
and here is the dark-mode for the same example:
Note that I ran `v test-all` locally and there were 5 errors that appear to be unrelated to this change:
```
---- Summary of `v test-all`: ---------------------------------------------------------------------------------------------------
Total runtime: 349169 ms
...
>      Failed: '/Users/glenn/src/github.com/vlang/v/v' -os linux -experimental -b native -o hw.linux examples/hello_world.v
>      Failed: '/Users/glenn/src/github.com/vlang/v/v' -os macos -experimental -b native -o hw.macos examples/hello_world.v
>      Failed: '/Users/glenn/src/github.com/vlang/v/v' -o vtmp_werror -cstrict cmd/v
>      Failed: …
```
> vdoc: add attributes to enums and structs

- cmd/tools/vdoc/theme/doc.js
Some browsers (e.g. Chrome) have a feature called "site search" that allow you to associate a shortcut with a custom site search string URL. For example, the shortcut "gl" can be set to `https://pkg.go.dev/search?q=%s` such that if you type "gl net/http" the browser would search for `https://pkg.go.dev/search?q=net/http` which then redirects to `https://pkg.go.dev/net/http`.
This PR would allow users to create a "vl" shortcut set to `https://modules.vlang.io/?q=%s` that would immediately act as if the user had typed `Ctrl-k` followed by their search string.
I have tested this locally with `?q=<alert>yo</alert>` and `?q=&lt;alert&gt;yo&lt;/alert&gt;` and it appears that [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent …
> vdoc: enable browser custom search with ?q=<search>

- vlib/v/checker/checker.v
- vlib/v/checker/tests/interface_option_cast_err.out
- vlib/v/checker/tests/interface_option_cast_err.vv
Fix missing interface cast checking
```v
interface IFoo {
a int
}
struct Foo {
a int
}
fn main() {
a := ?Foo{}
dump(a)
b := IFoo(a?)
c := IFoo(a) // must be an error
}
```
> checker: fix missing check for interface cast of option type

- examples/sokol/02_cubes_glsl/cube_glsl.v
- examples/sokol/03_march_tracing_glsl/rt_glsl.v
- examples/sokol/04_multi_shader_glsl/rt_glsl.v
- examples/sokol/05_instancing_glsl/rt_glsl.v
- examples/sokol/06_obj_viewer/show_obj.v
- examples/sokol/drawing.v
- examples/sokol/fonts.v
- examples/sokol/freetype_raven.v
- examples/sokol/particles/particles.v
- examples/sokol/simple_shader_glsl/simple_shader.v
- thirdparty/sokol/sokol_app.h
- thirdparty/sokol/sokol_gfx.h
- thirdparty/sokol/util/sokol_gl.h
- vlib/gg/gg.c.v
- vlib/sokol/gfx/gfx.c.v
- vlib/sokol/gfx/gfx_funcs.c.v
- vlib/sokol/gfx/gfx_structs.c.v
- vlib/sokol/gfx/gfx_utils.c.v
- vlib/sokol/sapp/sapp.c.v
- vlib/sokol/sapp/sapp_funcs.c.v
So... quite a bit changed with this update.
**Highlights**
* `sg_begin_default_pass/3` has been removed in favor of a unified `sg_begin_pass/1` which account for a lot of the example changes.
* Instead of including yet another C dependency (`sokol_glue.h`) I decided to just implement it's 2 functions in V directly in `sapp.glue_environment/0` and `sapp.glue_swapchain/0` their current quirk is that they cannot be called before `sapp` has actually opened a window, hence all the `pass := sapp.create_default_pass(pass_action)` calls in the `frame` callback. There's no noticeable/visual/performance changes on my old hardware - but it would be cleaner if the `pass` was only created once when the app is intialized and the window fully opened, but it'll need some refactoring I think.
* Renamed …
> sokol, gg, examples: update to match uptream at 058a4c5

- vlib/v/fmt/fmt.v
- vlib/v/fmt/fmt_vmodules_test.v
Fixes issues the formatter introduces(/false negative formatting checks) in modules that are located in a `$VMODULES` directory.
E.g. the following, when located in `~/.vmodules`,...
```v
// ~/.vmodules/foo/main.v
import x.json2 as json
import datatypes { Stack }
const my_datatype = Stack[string]{}
```
will currently be formatted into:
```v
// ~/.vmodules/foo/main.v
import x.json2
const my_datatype = Stack[string]{}
```
> fmt: fix removal of used selective and alias imports in modules in `$VMODULES` dirs

- vlib/v/gen/c/cgen.v
- vlib/v/tests/modules/consts_with_complex_init/config.v
- vlib/v/tests/modules/consts_with_complex_init/consts_should_not_conflict_test.v
> cgen: fix missing scope enclosing for const init which needs temp variables

- vlib/v/ast/types.v
The PR updates the mentioned method. The change should also bring be a slight performance improvement (not tested). It will help to add a simple fix in a follow up for further issues when running `v fmt` on modules inside a `$VMODULES` directory.
> ast: cleanup and simplify `shorten_user_defined_typenames` method

- vlib/v/parser/comptime.v
- vlib/v/parser/parse_type.v
- vlib/v/tests/comptime_for_mod_name_test.v
> parser: fix for comptime with fully type name

- vlib/v/ast/types.v
- vlib/v/fmt/fmt_vmodules_test.v
Fixes an issue where
```v
// ~/.vmodules/foo/foo.v || ~/.vmodules/foo/src/foo.v
module foo
import bar.baz
type MyAlias = baz.Baz
// Will be formatted into:
// type MyAlias = bar.baz.Baz
``` 
```v
// ~/.vmodules/foo/bar/baz/baz.v
module baz
enum Baz {
bar
baz
}
```
> ast, fmt: improve submodule type alias lookup; fix formatting of modules in `$VMODULES`

- vlib/io/reader.v
The `io.string_reader.StringReader` class uses private constants from `io.string_reader`. This PR makes those constants public so that the newly added StringReader class (and any future reader-like classes) can use them. Addresses #20975.
> io.reader: Make read_all constants public

- vlib/x/json2/decoder.v
- vlib/x/json2/tests/decoder_test.v
> x.json2: improve error message upon missing comma

- vlib/v/checker/checker.v
> checker: remove unnecessary string interpolation in deprecation method calls

- vlib/db/sqlite/sqlite.c.v
- vlib/db/sqlite/sqlite_test.v
Fixes a bug where sqlite errors would not be caught through `exec_param_many` and it's associated methods.
Previously runtime failures like unique constraints and others would not be caught when using `exec_param_many`.
> db.sqlite: Fix exec_param_many bug

- vlib/io/string_reader/string_reader.v
- vlib/io/string_reader/string_reader_test.v
This PR is meant to address https://github.com/vlang/v/issues/20998. 
It changes the condition so that if you request the last byte individually, then StringReader won't fail when the current offset is equal to the length of the builder before it increases the offset to EOF.
> fix needs_fill_until check

- vlib/v/checker/struct.v
Small cleanup of the checker method to reduce double checks, continue earlier/reduce load when possible and to improve future read-/maintainability. Tried building it up per commit in case this simplifies reviewing.
> checker: cleanup and simplify `check_ref_fields_initialized` methods

- cmd/tools/vdoc/tests/testdata/newlines/main.comments.out
- cmd/tools/vdoc/tests/testdata/output_formats/main.ansi
- cmd/tools/vdoc/tests/testdata/output_formats/main.text
- cmd/tools/vtest-self.v
- vlib/v/doc/utils.v
The PR enables vdoc tests.
vdoc is currently not test covered as it is skipped on all platforms. 
Enabling the tests on a working Linux platform - also what we use to deploy V docs - reveals that there currently is one failing test to fix.
> ci,tests: enable vdoc tests on linux; fix unintended line break

- vlib/os/process.v
The fields of the `Process` struct in the `os` modules incorrectly have their documentation behind the field, instead of before. Example of what it currently looks like:
```V
pub struct Process {
pub mut:
// ...
pid      int    // the PID of the process
code     int = -1
// the exit code of the process, != -1 *only* when status is .exited *and* the process was not aborted
// ...
}
```
This results in `code` incorrectly having the documentation associated with `pid`. This specific case is confusing in particular as both are integers and `code` could be mistaken for the `pid` after reading the associated comments.
> os: fix Process struct fields documentation applied to wrong field

- doc/docs.md
Updated the docs to be more visible. 
Using 
> [!NOTE]
> Note
or
> [!IMPORTANT]
> Important
than just 
> hello, this is a warning.
As it is more grayed out, and therefore less important/noticeable.
> Updated docs

- vlib/v/checker/struct.v
> checker: fix undefined reference to interface struct field regression

- vlib/v/scanner/scanner.v
- vlib/v/scanner/tests/shebang_outside_vsh_err.out
- vlib/v/scanner/tests/shebang_outside_vsh_err.vv
> scanner: disallow shebang outside of *.vsh files

- vlib/v/checker/tests/struct_init_with_iface_embed_iface_with_incorrect_method_impl_ref_field_err.out
- vlib/v/checker/tests/struct_init_with_iface_embed_iface_with_incorrect_method_impl_ref_field_err.vv
Due to a regression the following would result in a C error before #21030
```v
// iface_ref.v
interface Refresher {
Reader
}
interface Reader {
read(buf []u8) !int
}
struct Server {
refresher Refresher
}
struct Stream {}
// Implementation is missing the return type.
fn (a Stream) read(buf []u8) {}
fn test_struct_init_with_interface_field() {
s := &Stream{}
_ := &Server{
refresher: s
}
}
```
With PR:
```
v self && v -cc gcc run ./iface_ref.v
```
```
iface_ref.v:20:3: error: `&Stream` incorrectly implements method `read` of interface `Refresher`: expected return type `!int`
18 |     s := &Stream{}
19 |     _ := &Server{
20 |         refresher: s
21 |     }
22 | }
Details: main.Refresher has `fn read(x main.Refresher, buf []u8) !int`
main.Stream has `fn read(a …
```
> checker: add test for iface embedding iface with erroneous implementation struct ref field init

- vlib/v/ast/str.v
Fix `&u8(foo)` formatting when formatting `ast.AsmIO`.
```v
asm amd64 {
lock cmpxchgb '%1', '%2'
; =a (rv)
+m (*&u8(atom)) // this & is dropped without the PR
; q (xchg)
0 (cmp)
; memory
}
```
> fmt: fix type name on some cases

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/import_auto_with_shebang_expected.vv
- vlib/v/fmt/tests/import_auto_with_shebang_input.vv
input:
```v
#!/usr/bin/env -S v
os.join_path('a','b')
```
formatting it:
current:
```v
import os
#!/usr/bin/env -S v
os.join_path('a', 'b')
```
after:
```v
#!/usr/bin/env -S v
import os
os.join_path('a', 'b')
```
> fmt: insert auto imports after shebang

- vlib/strings/textscanner/textscanner.v
- vlib/strings/textscanner/textscanner_test.js.v
- vlib/strings/textscanner/textscanner_test.v
The skip function would not increment the current position if the current position was pointing to the last character in the input.  As a result, you could not skip to the end of input.  And, this means that you cannot detect end of input if you are using the skip function to move the current position forward.
Looking at the skip_n function, you can skip to the end of input.
This change makes skip and skip_n(1) work the same way and have the same semantics.
I have also updated the unit tests to detect proper behavior when reaching the end of input.
> strings/textscanner: fix off-by-one error in textscanner skip

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/import_submod_from_vmodule_src_dir_keep.vv
Resolves #19799
With the linked PR vfmt won't break the import anymore. I think, since it's a working import it's okay when fmt just keeps it for now. Eventually we can check if a module placed in the `src` dir of a parent module is recognize when importing it without the src dir like `import artemkakun.textproc.punctuation` and let vfmt do the job of removing the `src.` part - currently, the module would not be found.
> fmt: fix formatting for imports of submodule from module src dir

- cmd/tools/vtest-self.v
I'm working on a package for Exherbo Linux (a source based derivative of Gentoo). Packaging is done in a sandbox, without access to network and where compilers should be launched in a specific way. So, some essentials tests always fail and should be skipped. I added a variable for that.
> vtest-self: add sandboxed packaging case

- cmd/tools/vfmt.v
This extends v fmts exit codes in case of errors. This way it would allow to spot if there are unformatted files next to internal errors, at least it would be easily checkable by a script based on the error code.  
E.g. a current use case would be using v fmt with with v-analyzer and encountering internal vfmt erros.
> tools.fmt: extend exit codes to allow spotting unformatted files next to internal errors

- vlib/v/fmt/struct.v
The PR updates how struct field comments are determined. The goal is to increase robustness and to better resemble what is happening to improve maintainability. It uses a single instead of multiple loops.
> fmt: update determining of struct field comments

- vlib/builtin/wchar/wchar.c.v
- vlib/v/ast/types.v
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/dumpexpr.v
- vlib/v/gen/c/str.v
- vlib/v/gen/c/str_intp.v
- vlib/v/parser/fn.v
- vlib/v/tests/c_structs/cstruct.h
- vlib/v/tests/c_structs/cstruct_str_test.v
> cgen: force C struct types which does not implement str() to be passed as ptr

- vlib/v/parser/fn.v
Fixes #12966
Where formatting
```v
fn JS.state_is_ready_on_leave(retval int) {
println('Hooked callback')
}
```
results in
```v
fn JS.state_is_ready_on_leave(retval int)
```
With the changes it would throw an error instead
```
error: interop functions cannot have a body
1 | fn JS.state_is_ready_on_leave(retval int) {
|                                           ^
2 |     println('Hooked callback')
3 | }
```
> parser,fmt: inform about invalid interop function bodies instead of removing them

- .github/workflows/binary_artifact.yml
The person renamed their Github account.
Currently the old name is redirecting to the new name, but someone already took the old name and just has to create a new repository with the same name for us to have a problem.
See https://github.com/winterjung/split/issues/23
> ci: update gh action repository name

- vlib/v/util/diff/diff.v
For the temporary diff files we can use the temp instead of the cache directory
> v.util: use tmp instead of cache dir for temporary diff files

- cmd/tools/vdoc/tests/testdata/basic/basic.comments.out
- cmd/tools/vdoc/tests/testdata/basic/basic.out
- cmd/tools/vdoc/tests/testdata/basic/basic.v
- cmd/tools/vdoc/tests/vdoc_file_test.v
The PR extends vdoc tests while also simplifying the process of adding test files with modules/filenames other than main. This allows for a simpler inclusion of imho more "natural" use cases, as hared modules like libraries are the larger user base for public functions with generated documentation. It also updates one of the tests to make use of this new functionality. The changes should allow to tests vdoc functionality more easily when solidifying and extending it.
> vdoc,tests: detect expected files from input instead of hardcoding names

- vlib/v/ast/table.v
- vlib/v/checker/fn.v
- vlib/v/gen/c/fn.v
- vlib/v/parser/parser.v
- vlib/v/tests/generic_static_call_test.v
Fix #21056
```V
module main 
type Tag = int
type Octet = string
fn (o Octet) tag() Tag {
return Tag(1)
}
fn (o Octet) pack() ![]u8 {
return o.bytes()
}
fn (o Octet) bytes() []u8 {
s := string(o)
return s.bytes()
}
// static method on concrete type 
fn Octet.unpack(b []u8) Octet {
return Octet(b.bytestr())
}
// This is generic type 
struct Elm[T] {
mut:
val T
}
fn Elm.new[T](val T) Elm[T] {
return Elm[T]{
val: val
}
}
fn (el Elm[T]) the_t() T {
return el.val
}
//  static method on generic type, this not working
fn Elm.unpack[T](src []u8) !Elm[T] {
t := T.unpack(src)
return Elm[T]{t}
}
fn (el Elm[T]) tag() Tag {
return el.val.tag()
}
fn (el Elm[T]) pack() ![]u8 {
return el.val.pack()!
}
fn main() {
b := Octet('xx')
mut el := Elm.new[Octet](b)
dump(el)
bytes := el.pack()!
dump(bytes)
// …
```
> checker, parser, cgen: allow static call on generic type

- vlib/v/gen/c/auto_eq_methods.v
- vlib/v/gen/c/cgen.v
- vlib/v/parser/if_match.v
- vlib/v/tests/option_generic_sumtype_test.v
- vlib/v/tests/option_sum_type_test.v
Fix #21077
Fix #20823
Before this patch the option type as variant were created as option_xx_ptr, after this patch it will be a _option_xx* instead.
> cgen, parser: fix option as possible match case for sumtype

- vlib/x/crypto/chacha20/README.md
- vlib/x/crypto/chacha20/chacha.v
- vlib/x/crypto/chacha20poly1305/README.md
- vlib/x/crypto/chacha20poly1305/chacha20poly1305.v
- vlib/x/crypto/poly1305/README.md
- vlib/x/crypto/poly1305/poly1305.v
- vlib/x/crypto/poly1305/usage_test.v
- vlib/x/crypto/sm4/sm4.v
- vlib/x/crypto/sm4/sm4_test.v
- vlib/x/json2/README.md
- vlib/x/json2/count.v
- vlib/x/sessions/README.md
- vlib/x/sessions/sessions.v
- vlib/x/templating/dtm/README.md
- vlib/x/templating/dtm/dynamic_template_manager.v
- vlib/x/templating/dtm/dynamic_template_manager_cache_system_test.v
- vlib/x/vweb/README.md
- vlib/x/vweb/assets/README.md
- vlib/x/vweb/context.v
- vlib/x/vweb/static_handler.v
- vlib/x/vweb/tests/large_payload_test.v
- vlib/x/vweb/tests/static_handler_test.v
- vlib/x/vweb/tests/testdata/unknown_mime.what
- vlib/x/vweb/tests/testdata/unkown_mime.what
- vlib/x/vweb/vweb.v
The PR does some chore work fixing typos. It also makes partially differing formatting in the READMEs uniform - whereby aiming not to change the generally used formatting rules.
> vlib.x: fix typos, uniformize readme formatting

- doc/docs.md
Removes a obsolete listpoint from the comment newline section. The behavior was updated for to use a more adaptive approach.
> docs: remove deprecated newline info for doc comments

- .github/workflows/linux_ci.yml
- examples/submodule/mymodules/main_functions.v
- vlib/v/util/module.v
Fixes #21078 
Contains a little module import name correction.
Should we run the related example run in CI and add a info comment to not change the modules name?
> utils: fix module lookup if module import parts end with the word `modules`

- doc/packaging_v_for_distributions.md
In the documentation, there are scripts to replace `vup.v` and `vself.v` for packaging. They are composed of multiple `echo` to fill in a file line by line. 
But after the first line we should use `echo "content" >> dest_file.v` to append content and not `echo "content" > dest_file.v` to replace it. 
This PR fixes this.
> doc: fix vup/vself replacement scripts

- cmd/tools/vtest-self.v
For packaging purposes, I've added the `native_test` in skipped essential tests from `v test-self`, as Exherbo Linux packages we can't use external compilers/linkers during install. This test use `ld` and then leads to an unfixable error.
> vtest self: add native_test to skippable tests for sandboxed packaging

- cmd/tools/vbuild-tools.v
For packaging purposes, I need to launch `v build-tools` without any internet access, as Exherbo Linux prevents it at compile time. But the first thing this command does is to check modules and update them, even if they're already there. 
I've added the same env var use before (#21059) to avoid this check and internet access.
> vbuild-tools: prevent module update for sandboxed packaging

- vlib/v/checker/checker.v
- vlib/v/checker/tests/anon_fn_arg_type_err.out
- vlib/v/parser/tests/closure_not_declared.out
Fixes phrasing in some error messages adds error details about variable inheritance in closures.
> checker: update error messages

- vlib/v/checker/check_types.v
- vlib/v/checker/tests/option_receive_ptr_err.out
- vlib/v/checker/tests/option_receive_ptr_err.vv
> checker: fix option checker arg validation for ptr passing on non expected ptr

- vlib/v/markused/markused.v
Fixes compilation with the `skip-unused` flag when using a substr with a check.
```v
// try.v
// v -skip-unused try.v
fn main() {
try('foo')!
}
fn try(str string) !string {
return str[..3] or { panic('failed to get substr') }
}
```
With the changes the above code compiles cleanly. Currently, it's throwing:
```
/tmp/v_1000/temp.01HSVATM49ZWGNT7F2C6JJ4RGJ.tmp.c:6007: warning: implicit declaration of function 'string_substr_with_check'
/tmp/v_1000/temp.01HSVATM49ZWGNT7F2C6JJ4RGJ.tmp.c:6007: error: '{' expected (got ";")
...
builder error: 
```
> v: fix `-skip-unused` compilation when using substrings with check

- cmd/tools/vretry.v
- cmd/v/v.v
```
#0 16:47:14 ᛋ tools_add_v_retry /v/oo❱v retry -h
v retry 0.0.1
-----------------------------------------------
Usage: v retry [options] CMD
Description: Run the command CMD in a loop, untill it succeeds, or until a predetermined amount of seconds pass.
The arguments should be at least 1 in number.
Options:
-h, --help                Show this help screen.
-t, --timeout <float>     Timeout in seconds. Default: 300.0 seconds.
-d, --delay <float>       Delay between each retry in seconds. Default: 1.0 second.
-r, --retries <int>       Maximum number of retries. Default: 999_999_999.
#0 16:50:19 ᛋ tools_add_v_retry /v/oo❱
```
> tools: add `v retry apt update`, for more robust CI jobs

- vlib/v/gen/c/cheaders.v
This PR addresses #21003 by adding a check that will allow for Windows ARM64 users to compile the X64 version of V with `.\make.bat -msvc` . The only remaining issue is that there is a harmless but loud error that shows up from `detect_tcc` because TCC is downloaded even when another compiler is specified (which maybe shouldn't be the case?). But everything works:
```
Updating TCC
> Syncing TCC from https://github.com/vlang/tccbin
Updating vc...
> Sync with remote https://github.com/vlang/vc
Building V...
> Attempting to build "./v_win_bootstrap.exe" (from v_win.c) with MSVC
v_win.c
> Compiling "./v.exe" with "./v_win_bootstrap.exe"
> C compiler cmd: "C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.39.33519\bin\Hostx64\x64\cl.exe" …
```
> v.gen: add _M_ARM64 to endianness check

- vlib/v/checker/checker.v
- vlib/v/checker/tests/alias_type_cast_option_result_unhandled_err.out
- vlib/v/checker/tests/as_cast_option_result_unhandled_err.out
- vlib/v/checker/tests/option_type_call_err.out
- vlib/v/checker/tests/result_missing_propagate_err.out
- vlib/v/checker/tests/result_type_call_err.out
- vlib/v/checker/tests/struct_field_init_with_result_err.out
- vlib/v/checker/tests/struct_init_field_result_err.out
The main change of the PR is improving error messages to provide more details on return types. The changes serve as a base for a bugfix in a followup but take up their own scope so they are submitted separately.
The PR intentionally makes minimal changes to the error messages, keeping it similar to the current state. Imho the error messages can generally be optimized here by using error details to split things up into showing an expressive error message and providing a recommendation for action. But that's a scope for a separate PR as well.
There are also minor optimization to the codeblock of the check. It moves variables assignments deeper into the block scope where they are used and removes a duplicate conditional check. Modern compilers should be smart enough to optimize such variable …
> checker: optimize option and result typ check, add more typinfo to error details

- cmd/tools/vvet/vvet.v
Will result in the same behavior as `v fmt` for `v vet`.
> tools.vet: print help when passing no files or `--help`/`-help` flag after vet command

- cmd/tools/modules/testing/common.v
- In 'cmd/tools/vbuild-tools.v', vast, vcreate, vdoc, vpm, vvet and vwhere tools (sources in subfolders) are initially skipped, then added into a test session.
- During session run (function 'worker_trunner'), build was skipped for the tools list above.
- Fix vlang/v#21119
---
Build with `./v build-tools` OK on Linux Debian testing/amd64 and OpenBSD current/amd64
> tools: fix build for tools in subfolders

- cmd/tools/vpm/settings.v
- vlib/io/util/util_test.v
- vlib/os/file_buffering_test.v
- vlib/os/file_test.v
- vlib/os/find_abs_path_of_executable_test.v
- vlib/os/inode_test.v
- vlib/os/os_test.c.v
- vlib/os/process_test.v
- vlib/toml/tests/alexcrichton_toml_rs_test.v
- vlib/toml/tests/burntsushi_toml_test.v
- vlib/toml/tests/iarna_toml_spec_test.v
- vlib/v/gen/c/coutput_test.v
- vlib/v/gen/golang/tests/golang_test.v
- vlib/v/gen/native/tests/native_test.v
- vlib/v/gen/wasm/tests/wasm_test.v
- vlib/v/live/live_test.v
- vlib/v/slow_tests/valgrind/valgrind_test.v
- vlib/v/tests/closure_generator_test.v
- vlib/v/tests/run_v_code_from_stdin_test.v
- **ci: fix spurious test failures on the space-paths-windows job**
- **ci: make tests more robust to CI failures on windows**
> ci: improve test robustness on windows

- vlib/orm/orm.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/option_multi_return_err.out
- vlib/v/checker/tests/option_multi_return_err.vv
- vlib/v/tests/option_multi_return_test.v
- vlib/v/tests/return_option_call_test.v
Fixes #17874  
Fixes #21117
Due to the changes, a fix to the vlib orm module is included.
```v
fn split(str string) ?(string, string) {
return none
}
fn main() {
foo, bar := split('foo/bar')
println('${foo}.${bar}')
}
```
Will now throw:
```
error: split() returns `?(string, string)`, so it should have either an `or {}` block, or `?` at the end
4 | 
6 |     foo, bar := split('foo/bar')
|                 ~~~~~~~~~~~~~~~~
7 |     println('${foo}.${bar}')
8 | }
```
Based on #21105 (After resolving it first, the PR should rebased)
Superseeds #20515. The PR is stale for a while, but took good steps towards the solution.
> checker, orm: add error for unchecked option multi return types, fix undefined behavior

- thirdparty/cJSON/cJSON.c
- thirdparty/cJSON/cJSON.h
Commit no. 1 updates the libraries files for easy local diff comparison. 
Commit no. 2 fixes a compatibility issue with tcc and the `fabs` function.
> thirdparty: update CJSON to latest release 1.7.17

- thirdparty/cJSON/README.md
- thirdparty/cJSON/readme.txt
- thirdparty/picohttpparser/README.md
- thirdparty/sokol/README.md
- thirdparty/stb_image/README.md
- thirdparty/zip/README.md
- thirdparty/zstd/README.md
Adds a readme with license information to thirdparty modules as well as a tiny info section on top linking to the module. This makes it easier to access in case of updating / looking for the correct module.
MIT, BSD actually state to keep the license, so I think we should have it in order to follow license agreements.
> MIT [...] The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software. [...]
> BSD [...] Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.[...]
> thirdparty: add license information to modules

- .github/workflows/v_apps_and_modules_compile_ci.yml
- vlib/v/ast/ast.v
- vlib/v/ast/scope.v
- vlib/v/ast/str.v
- vlib/v/ast/table.v
- vlib/v/checker/checker.v
- vlib/v/checker/if.v
- vlib/v/comptime/comptimeinfo.v
- vlib/v/gen/c/auto_eq_methods.v
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/infix.v
- vlib/v/gen/c/struct.v
- vlib/v/tests/option_sumtype_variant_test.v
> v: fix sumtype option support

- cmd/tools/vvet/vvet.v
Same reason as sated in the block of the code for the `/tests/` directory. 
Currently even e.g. `_input.vv` a testdata dir are vetted.
It will allow to extend automatic code vetting on actual module code.
> ```
> // skip all /tests/ files, since usually their content is not
> // important enough to be documented/vetted, and they may even
> // contain intentionally invalid code.
> ```
> vet: skip testdata dirs

- cmd/tools/vvet/vvet.v
Uses a single instead of three consecutive loops for vetting files.
> vet: optimize performance for path detection when vetting files

- .github/workflows/v_apps_and_modules_compile_ci.yml
- vlib/v/fmt/fmt.v
- vlib/v/fmt/testdata/vmodules/src_import/src/a/aa/import_without_src_expected.vv
- vlib/v/fmt/testdata/vmodules/src_import/src/a/aa/import_without_src_input.vv
- vlib/v/fmt/testdata/vmodules/src_import/src/a/ab/ab.v
@spytheman your point made here https://github.com/vlang/v/pull/21134#discussion_r1544440533  confirms itself.
With our current module lookup there are more scenarios where it is required to keep the a `src.` part in the import. E.g. in v-analyzer for `build.vsh` (`src.metadata`) or in `tools/project-checker.v`. By removing the `src.` prefix vfmt would break the functionality, since the imported modules are not found anymore. 
Now vfmt would not try to "outsmart" anymore. And for scenarios where an import prefixed with `src.` and as well as the path without `src.` are valid, both will be also seen as valid by vfmt. 
General formatting will still happen ofc, unused import symbols will be cleared, just the path of the import won't be changed anymore. 
The tests that check for the import …
> fmt: don't change paths when formatting imports

- vlib/v/checker/checker.v
- vlib/v/checker/struct.v
- vlib/v/checker/tests/any_type_err.out
- vlib/v/checker/tests/any_type_err.vv
- vlib/v/checker/tests/struct_field_with_any_type_err.out
- vlib/v/parser/parse_type.v
- vlib/v/parser/tests/cast_to_any_type_err.out
- vlib/v/parser/tests/cast_to_any_type_err.vv
This can be a checker error. The type error during parsing causes parsing interruption and internal errors. E.g.:
```v
// any.v
type Any = any
```
```sh
v fmt any.v
```
```
error: cannot use `any` type here
1 | type Any = any
|            ~~~
Internal vfmt error while formatting file: any.v.
```
similar to how `type MyType = unknown_type` is treated
> parser, checker: move error handling for `any` type to the checker to resolve parsing issues

- cmd/tools/vvet/vet_test.v
- cmd/tools/vvet/vvet.v
- vlib/v/help/common/vet.txt
Allows to run vet over paths that include e.g. `tests` or `testdata` when explictly passing them. Currently, they will be excluded without any information.
```sh
v vet vlib/v/fmt/testdata # Silently skipped
v vet vlib/v/fmt/testdata # Vetted when explicitly specified
v vet vlib/v/fmt # Subdir /testdata will skipped
```
This feature also removes the need for keeping a flag that was used for vet development / test purposes.
E.g. checking out the first commit that just removes the flag before extending the functionality and running below will show the problems solved.
```
v cmd/tools/vvet/vet_test.v
```
> vet: allow to overwrite excluded dirs

- vlib/v/fmt/fmt.v
- vlib/v/fmt/struct.v
Makes minor code vetting / optimization in `fmt/fmt.v`. An array with a max len for a const named `max_len`.
> fmt: use fixed size array for max_len const

- vlib/v/checker/checker.v
- vlib/v/checker/tests/assign_ref_call_expr_with_ref_return_err.out
- vlib/v/checker/tests/assign_ref_call_expr_with_ref_return_err.vv
Fixes:
```v
@[heap]
struct Foo {}
fn foo() &Foo {
return &Foo{}
}
_ := &foo()
```
throwing:
```
error: lvalue expected
...
builder error: 
```
> checker: detect redundant ref when assigning call expr with ref return

- vlib/v/checker/checker.v
- vlib/v/tests/multi_return_nil_voidptr_test.v
> checker: fix multi return using nil and voidptr

- vlib/v/fmt/fmt.v
Splits up a refactoring from a fix since the fix would include a logic update.
The change simplifies code block for const name for matting. It might be a little safer as well, since it removes and unguarded array access.
```v
mod_prefix := vals[vals.len - 2]
```
> fmt: simplify const name formatting

- vlib/v/gen/c/auto_eq_methods.v
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/c_structs/cstruct.h
- vlib/v/tests/c_structs/cstruct_sumtype_test.v
Fix #21122
```v
#include "@VMODROOT/foo.h"
struct C.Foo {
a int
}
struct C.Bar {
a int
}
type Baz = C.Foo | C.Bar
fn main() {
mut a := Baz{}
a = C.Foo{a: 1000}
dump(a)	
}
```
> cgen: fix C struct sumtype support

- vlib/v/pkgconfig/pkgconfig.v
For 3rd party software that is part of the base FreeBSD install, their pkg-config files are in /usr/libdata/pkgconfig.
This path was not in the set of default pkgconfig paths.  As a result, if a module relied upon some library or include file from the base system, even as an indirect dependency, it would not be found.
I added the base path after the path for pkgconfig files that are from installing packages or ports so that packages or ports would be found preferentially over ones in the base system.  For example, if a newer version of openssl was installed via the pkg command or as a port, it would be found instead of the one from the base install.
> v/pkgconfig: add pkgconfig path for FreeBSD base packages

- vlib/builtin/builtin.v
- vlib/db/mysql/mysql_orm_test.v
- vlib/db/pg/pg_orm_test.v
- vlib/db/sqlite/sqlite_orm_test.v
- vlib/orm/orm.v
- vlib/orm/orm_fn_test.v
- vlib/v/ast/table.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/orm.v
- vlib/v/parser/comptime.v
- vlib/v/parser/parser.v
- vlib/v/tests/comptime_attr_test.v
- vlib/v/tests/comptime_dump_test.v
```v
@[foo;bar]
fn abc() {
}
@[foo]
struct Foo {
}
@[bar]
fn Foo.bar() {
}
@[baz]
enum EnumFoo {
a
b
}
@[iface]
interface IFoo {
}
@[custom]
type CustomType = Foo | EnumFoo
fn main() {
mut c := 0
$for f in abc.attributes {
dump(f)
assert f.name in ['foo', 'bar']
c++
}
assert c == 2
$for f in Foo.attributes {
dump(f)
assert f.name == 'foo'
c++
}
assert c == 3
a := Foo.bar
$for f in a.attributes {
dump(f)
assert f.name == 'bar'
c++
}
assert c == 4
b := abc
$for f in b.attributes {
dump(f)
assert f.name in ['foo', 'bar']
c++
}
assert c == 6
$for f in EnumFoo.attributes {
dump(f)
assert f.name == 'baz'
c++
}
assert c == 7
$for f in IFoo.attributes {
dump(f)
assert f.name == 'iface'		
c++
}
assert c == 8
$for f in CustomType.attributes {
dump(f)
assert f.name == 'custom'
c++
}
assert c == 9
} …
```
> v: added ability to read enum, fn, interface and sumtype attributes in compile-time

- vlib/v/tests/c_structs/cstruct_ref_test.v
The vlib/v/tests/c_structs/cstruct_ref_test.v test fails on FreeBSD and MacOS.  So I added a type conversion.
> v/tests: fix assignment to pointer

- examples/pendulum-simulation/modules/sim/anim/worker.v
- examples/sokol/fonts.v
- examples/sokol/freetype_raven.v
- vlib/gg/draw.c.v
- vlib/gg/gg.c.v
- vlib/math/big/division_array_ops.v
- vlib/v/builder/cbuilder/parallel_cc.v
- vlib/v/builder/compile.v
- vlib/v/builder/msvc_windows.v
- vlib/v/checker/assign.v
- vlib/v/checker/fn.v
- vlib/v/checker/if.v
- vlib/v/checker/infix.v
- vlib/v/checker/return.v
- vlib/v/checker/tests/mul_op_wrong_type_err.out
- vlib/v/checker/tests/mul_op_wrong_type_err.vv
- vlib/v/checker/tests/unused_import_err.out
- vlib/v/checker/tests/unused_import_err.vv
- vlib/v/gen/js/comptime.v
- vlib/v/parser/comptime.v
- vlib/v/parser/parser.v
- vlib/x/sessions/tests/session_app_test.v
Fixes e.g,
```v
import term as te
import te.ui // alias `te` as part of another import would register the import `term` as used, despite its never being used.
fn main() {}
```
The change reveals a lot of unused imports that are removed in this PR as a requirement to pass CI.
> parser: fix case of falsely registering imports as used, remove unused imports

- vlib/vweb/README.md
- vlib/x/vweb/README.md
I noticed that the bullet points under the Features heading on both vweb and x.vweb were not formatting right due to the line for "Easy to deploy" being continued on a second line.
It seems like that would be a bug in vdoc but I was unable to find it.  The expedient fix is to just have that bullet point all on one line.
I also re-worded some other descriptive text to make it easier (at least for me) to understand.
I am not sure of the status of x.vweb vs. vweb.  Using `v new --web` generates files referencing vweb so I assume that is still the preferred version.
> vweb, x.vweb: edit some descriptions

- vlib/x/json2/decoder.v
- vlib/x/json2/tests/decoder_test.v
Fixes #21150
Adds the ability to decode arrays, as currently it is an empty block:
- Current master
https://github.com/vlang/v/blob/5da1fccaed6ca699ecce79018b29b123c3e19969/vlib/x/json2/decoder.v#L251-L252
The feature is integrated in a simple enough manner that it should create little interference with #21039 . It might even help with a TODO there.
> x.json2: add ability to decode arrays

- vlib/net/http/server.v
- vlib/net/http/server_test.v
Fixes a panic when the server gets an empty address. Does a cleanup to the related scope.
```v
mut server := &http.Server{
addr: ''
on_running: fn (mut server http.Server) {
spawn fn [mut server] () {
println('server started')
server.stop()
println('server stopped')
}()
}
}
server.listen_and_serve()
```
Instead it will now behave like before passing 0 to the deprecated `port` field, or `:0` to `addr` - using a random port.
> net.http: fix panic on empty addr, cleanup `listen_and_serve` Server method

- vlib/v/checker/tests/modules/deprecated_module.out
- vlib/v/checker/tests/modules/deprecated_module/main.v
Resolved with the recent updates to vfmt
> checker: remove resolved workaround and TODO

- cmd/tools/vup.v
- vlib/v/checker/checker.v
- vlib/v/util/version/version.c.v
- vlib/v/util/version/version_test.v
Reworks `githash` to extend its use cases by allowing it to return the githash of any passed path. Currently, it is used for `@VCURRENTHASH` and only returns the path of the V hash. Chances that `githash` was called directly outside the V codebase itself are low, but it is a public function, so this change can be considered breaking.
The changes:
- Simplifies: the function no longer uses a bool param to return a static value if it is set to false; instead, we assign static values directly.
- Uses early returns instead of a less safe workaround with a for loop.
- Utilizes Result values to be able to trace down misbehavior instead of assigning a fallback value directly in the function.
The new functionality will enable an easy implementation of `@VMODHASH` in #21091.
> v.utils: update `githash` to be able to get the githash of every passed project

- examples/vtail.v
- vlib/os/file.c.v
The new example acts like `tail -f bigfile.log` .
> examples: add vtail.v, deprecate File.read_bytes_into_newline/1 in favor of File.read_bytes_with_newline/1

- vlib/builtin/string.v
- vlib/toml/toml.v
- vlib/v/checker/match.v
- vlib/v/parser/if_match.v
- vlib/v/parser/parse_type.v
- vlib/v/tests/comptime_match_type_test.v
- vlib/x/json2/decoder.v
- vlib/x/json2/json2.v
- vlib/x/json2/types.v
Fix #21170
Improve type checking from #21163
> x.json2,checker,toml: allow field.typ compile-time checking with MatchExpr and add array of option checking

- vlib/net/ftp/ftp.v
- vlib/net/ftp/ftp_test.v
ftp: allow to choose a different port than port 21 by simply removing the hardcoded port and using the same syntax for the address as for dial_tcp.
so instead of doing this
```v
ftp.connect("127.0.0.1")
```
would do this
```v
ftp.connect("127.0.0.1:2021")
```
this would allow to connect to ftp server using another port (for example due to security reason).
> breaking,net.ftp: allow to choose a different port than port 21 (change FTP.connect to accept `host:port`, not just a `host` address)

- doc/docs.md
- vlib/v/checker/checker.v
- vlib/v/parser/comptime.v
- vlib/v/token/token.v
- vlib/v/util/version/version_test.v
The PR should implement the possibility to store a commit hash of a vmodule as a compile time variable. Similar to Similar to `@VHASH` / `@VCURRENTHASH` for V itself. The reason for it is that I encountered multiple scenarios where it would be useful and function calls in constants are not yet evaluated at comptime.
> v: add `@VMODHASH` comptime variable to store the commit sha of a V module

- vlib/encoding/xml/test/local/12_doctype_entity/entity_expected.xml
- vlib/encoding/xml/test/local/12_doctype_entity/spec_entity_test.v
Upgrades an xml test that assigns values to the private field `parsed_reverse_entities` which in an external test. Otherwise, the fields data is only used internally.
https://github.com/vlang/v/blob/254250d375acff5a92c2a0b1a3079c98e7e16244/vlib/encoding/xml/types.v#L61-L63
The new test might be more robust and easier to follow as well, as it compares the parses files with entities with an an expected file that have the entities already resolved. 
The upgrade is also required for #21183
> xml: update entity parse test

- .github/workflows/linux_ci.yml
- .github/workflows/macos_ci.yml
- .github/workflows/v_apps_and_modules_compile_ci.yml
> ci: move build step for VPM site into apps and modules ci, add concurrency config

- vlib/x/json2/decoder.v
Fix #21168
Added generic way to decode a JSON array string into a array of generic type.
```v
import x.json2
pub struct Value {
value string
}
pub struct Value2 {
value string
}
fn main() {
println(json2.decode_array[Value]('[{"value": "abc"}, {"value": "def"}]')!)
println(json2.decode_array[Value2]('[{"value": "abc"}, {"value": "def"}]')!)
}
```
> x.json2: decode array

- .github/workflows/native_backend_tests_ci.yml
- .github/workflows/v_apps_and_modules_compile_ci.yml
- .github/workflows/wasm_backend_tests_ci.yml
Prevents false positives in regards to the current problems with the `-stats` flag
> ci: remove `-stats` flag from tests

- vlib/x/vweb/tests/vweb_test.v
- vlib/x/vweb/tests/vweb_test_server.v
- vlib/x/vweb/vweb.v
Add ability to accept method arguments for query parameters in a `get` request the same way form values are passed as arguments in a `post` request.
> x.vweb: accept query params as method arguments

- vlib/os/os.v
Mainly wording updates. One param name update to clarify the function signature.
> os: clarify some doc comments

- vlib/v/parser/comptime.v
- vlib/v/parser/expr.v
- vlib/v/parser/fn.v
- vlib/v/parser/parser.v
- vlib/v/parser/struct.v
Updates file field names on the parser. Main concern was `file_name` holding the path and same data field is e.g. used on the scanner named `file_path`. Imho simpler to understand during development when reading file_path and understanding assignments to path related fields then doing so with `file_name`.
> parser: update file path fields; use more expressive name for file path, remove obsolete `file_name_dir` field

- vlib/v/fmt/fmt.v
- vlib/v/fmt/fmt_test.v
- vlib/v/fmt/testdata/vmodules/submod_import_alias/vlas/module_alias_import_submod_in_submod_keep.vv
- vlib/v/fmt/testdata/vmodules/submod_import_alias/vlas/module_alias_submod_import_parent_mod_expected.vv
- vlib/v/fmt/testdata/vmodules/submod_import_alias/vlas/module_alias_submod_import_parent_mod_input.vv
Should fix and cover the current fmt fails on vls.
> fmt: extend import import alias reference map for submodules

- vlib/os/os.c.v
- vlib/v/ast/comptime_valid_idents.v
- vlib/v/checker/comptime.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/js/comptime.v
Add possibility to check if autofree is enabled.
```v
$if autofree ? {
}
```
> cgen: add `autofree` comptime check

- vlib/v/checker/tests/is_type_not_exist.out
- vlib/v/checker/tests/is_type_not_exist.vv
- vlib/v/parser/parse_type.v
Resolves #20891
change is in parser, it's a checker error tho.
> parser, checker: improve error message for unknown type

- cmd/tools/vpm/vcs.v
> vpm: optimize performance by adding filter when cloning

- .github/workflows/v_apps_and_modules_compile_ci.yml
Removes redundant CI runs that take about 12minutes.
The tests just re-run the same test as above since they just specify the default garbage collection option which is the same as specifying none.
E.g. at the vsl repo the same tests were improved / removed some months ago.
> ci: remove redundant tests runs

- vlib/v/checker/check_types.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/option_ptr_arg_none_test.v
> cgen, checker: allow `none` as arg to `?&type`

- cmd/tools/vdoc/vdoc.v
Running a command that specifies an output path for the documentation like `v doc -m -f html -o docs .` currently creates a `docs/_docs` directory. The change removes adding the additional directory and uses the output path as final directory for the document files. This is likely the more expected result and the behavior that is easier to work with.
> vdoc: don't add additional _docs directory when an out path is specified

- cmd/tools/vdoc/utils.v
The change extends a conditional check so that readme files in the project root are correctly recognized as readme allowing them to be included in the recent fix regarding indentation.
When having run a command like `v doc -m -f html -readme .` 
the current readme in `_docs/index.html` is rendered like:
As part of the module the readme is working `_docs/module_name.html`
> vdoc: fix indention of readme when generating docs with `-readme` in project root

- cmd/tools/vdoc/html.v
- cmd/tools/vdoc/tests/testdata/output_formats/README.md
- cmd/tools/vdoc/tests/testdata/output_formats/main.ansi
- cmd/tools/vdoc/tests/testdata/output_formats/main.html
- cmd/tools/vdoc/tests/testdata/output_formats/main.text
Fixes #21222
Issue in current test:
Updated:
> vdoc: fix character escape in code blocks in readme contents

- vlib/v/ast/comptime_const_values.v
- vlib/v/ast/types.v
> vlib: add missing docstrings for vlib/v/ast/comptime_const_values.v  functions

- vlib/v/util/diff/diff.v
> v.util: improve `color_compare_files`

- vlib/v/util/diff/diff.v
Makes the function do what it's name implies. I was really missing this when there is just diff installed and working in the codebase.
|Current|Updated|
|-|-|
| ![Screenshot_20240409_195735](https://github.com/vlang/v/assets/34311583/6dfb628d-c3c9-4c23-bb31-8405755a565e)|![Screenshot_20240409_195741](https://github.com/vlang/v/assets/34311583/d9a2c8f0-d2a4-41f1-8f45-a599187636ab)|
Due to the ansi codes in the output, it will conflict with #21242. Depending on which one is resolved first conflicts in the other will need to be taken care of.
> v.util: ensure output of `color_compare_files` is colorized

- vlib/v/doc/node.v
Pushing the fix for the vdoc sorting issue on non linux after this one to enable tests there as well.
> vdoc: cleanup `node.v`

- cmd/tools/vdoc/tests/vdoc_file_test.v
- cmd/tools/vdoc/vdoc.v
docs should still land in `<path>/_docs` in such cases. Sorry for the regression
> vdoc: fix out path if `-o` is not passed but input has a path, add test

- vlib/v/util/diff/diff.v
The PR works on the `util.diff` module's code related to the `VDIFF_TOOL` environment variable. 
It cleans up to help with maintainability and slightly extends by adding an error that should improve usability. 
Regarding the changes: 
At the beginning of the function we already checked if there is an `env_difftool` and return early. How  `env_difftool` was used after this in the function, was quasi dead code. 
https://github.com/vlang/v/blob/4dcc9265e16e74dc3691e6da427121e87bd05341/vlib/v/util/diff/diff.v#L11-L13
Then, instead of just returning the strings specified in the environment string it is also ensured here that specified command is executable. If not an error is returned to the user. E.g. when it isn't installed or if a typo or something.
> v.util: improve code related to diff tool specified via environment, add check if the diff tool exists

- cmd/tools/vdoc/html.v
- cmd/tools/vdoc/tests/vdoc_file_test.v
> vdoc: minor cleanup

- vlib/v/util/diff/diff.v
- Adds test for the diff util module.
- Fixes an issue where `find_working_diff_command()!` adds spaces to the result, potentially making it unavailable to other commands. E.g. `os.find_abs_path_of_executable` would not find the result of the function.
```v
cmd := util.find_working_diff_command()!
dump(os.find_abs_path_of_executable(cmd)!)
```
Might even be required to make the changes in #21243 robust.
> v.util: improve find_diff_cmd: don't add spaces to result without env opts

- vlib/v/util/diff/diff.v
When returning the diff command for FreeBSD or OpenBSD, the diff options from the environment were not included as they are for other OS's.
This fixes a broken unit test.
> util/diff: return diff options with the diff command for FreeBSD/OpenBSD

- vlib/v/util/diff/diff.v
- vlib/v/util/diff/diff_test.v
The PR should fix coloring when using a system default diff comparison and adds a test if the output actually includes color codes.
> v.util: fix diff coloring, add test

- vlib/v/util/diff.v
- vlib/v/util/diff/diff.v
The recent updates and fixes allow for a polishing of the diff utils. Doc comments are added as well. I think it's kind of a nice little milestone for the module from which further development can take place.
> v.util: polish off diff utils after recent updates and fixes, add doc comments to pub fns

- vlib/v/gen/c/assign.v
- vlib/v/tests/option_generic_cast_none_test.v
> cgen: fix code generated for `none` passed to generic option casting

- vlib/os/README.md
Auto-formats the os modules readme. Doing so it fixes an issue with markdown inside html tags.
The formatting changes match with what is used for the bigger part other markdown files in the codebase.
Following commonmarks recommended formatting for markdown inside html tags works here as a fix. Stackoverflow answer with link to commonmark example: https://stackoverflow.com/a/29378250
|Current|After formatting|
|-|-|
|![Screenshot_20240415_084810](https://github.com/vlang/v/assets/34311583/6eb5240e-093b-40e9-8c69-d1187be83ee9)|![Screenshot_20240415_084800](https://github.com/vlang/v/assets/34311583/d0453ed8-6854-4b2b-9c41-96f9e16fa0c4)|
<details>
Putting markdown immediately after a tag **never works**(at least as far as I know). It even breaks highlighting in the example below. It **can …
> os: format readme, fix markdown inside html

- cmd/tools/vdoc/html.v
- cmd/tools/vdoc/tests/testdata/output_formats/README.md
- cmd/tools/vdoc/tests/testdata/output_formats/main.ansi
- cmd/tools/vdoc/tests/testdata/output_formats/main.html
- cmd/tools/vdoc/tests/testdata/output_formats/main.text
> vdoc: fix markdown lists in html

- cmd/tools/vpm/vcs.v
- cmd/tools/vpm/vcs_test.v
When git is not from brew:
`git --version` reports `git version 2.39.3 (Apple Git-146)`
When git is compiled from source, or is from brew, the reported version is: `git version 2.44.0`.
~~I do not know, when it will have a `.windows` suffix.~~
Edit: On the windows CI jobs, the output is `git version 2.44.0.windows.1` .
> tools: fix vpm on macos, when using the bundled git executable

- .github/workflows/macos_ci.yml
- .github/workflows/v_apps_and_modules_compile_ci.yml
After:
https://github.com/vlang/ved/pull/181
https://github.com/vlang/v-analyzer/pull/99
Re-running Apps and Modules CI should suffice then.
> ci: reactivate app prod builds

- vlib/v/checker/checker.v
- vlib/v/checker/tests/unreachable_code.out
- vlib/v/checker/tests/unreachable_code.vv
> checker: detect unreachable code in loops after continue and break stmts

- .github/workflows/v_apps_and_modules_compile_ci.yml
It makes sense to continue testing other modules if one fails to build. This should give a better understanding of what is wrong and have more insight where fixes can happen.
Example run:
https://github.com/ttytm/v/actions/runs/8727507855/job/23945173601
> ci: continue testing other modules if one fails

- cmd/tools/vdoc/tests/vdoc_file_test.v
Clarifies things to simplify maintaining and extending the doc tests. 
Initially, part of #21281 but was ultimately omitted for a simpler diff. 
Now, I'm submitting it separately from an update/fix that includes adding new tests.
> vdoc: cleanup `vdoc_file_test.v`

- vlib/cli/command_test.v
> cli: update `command_test.v`

- .github/workflows/gen_vc_ci.yml
- .github/workflows/module_docs_ci.yml
- Limits the vc deployment workflow to run when relevant instead of
> ```yml
> # Note that failure below may happen, due to vlang/vc rejecting the push
> # from forked repos; that is not usually a problem.
> ```
- Extends the doc_ci workflow by adding the default condition that we currently use to make sure it runs when relevant.
> ci: prevent unintended deployment workflow steps

- vlib/flag/flag.v
- vlib/flag/flag_test.v
With the changes that are passed after `--` (end of options) will be considered as args when using `finalize` on a `FlaParser`.
To give an example that is currently using the flag module and suffering from the described issue on current master:
```
❯ v retry -- ls
Error: flag.ArgsCountError: Expected at least 1 arguments, but got 0
```
With the change:
```
❯ v retry -- ls
bench         changelogs0.x  CODE_OF_CONDUCT.md  doc         Dockerfile.alpine  examples     GNUmakefile  make.bat  README.md   samples   thirdparty  v3  vlib   v_old
CHANGELOG.md  cmd            CONTRIBUTING.md     Dockerfile  Dockerfile.cross   examples.sh  LICENSE      Makefile  ROADMAP.md  TESTS.md  tutorials   v            vc  v.mod
```
With the change, passing flags to a command after `--` will also be possible
``` …
```
> flag: include args after end-of-options(`--`) when checking min and max args

- cmd/tools/vretry.v
- cmd/tools/vretry_test.v
Next to minor updates to `vretry` it uses a default retry count of 10 as it can be a more sensible default in comparison to getting stuck in 999_999_999 loop(/ for 300sec) when passing an invalid command. This default count is similar to `.github/workflows/retry.sh`.
It might be a better fit the other defaults (1 sec delay and timeout of 300sec) as well.
The added test will pass after #21310
> tools: update vretry.v, add test

- cmd/tools/vdoc/files.v
- cmd/tools/vdoc/vdoc.v
- cmd/tools/vdoc/vdoc_test.v
After working on an improved status quo to also have a good fallback, this PR approaches to rewrite and to extend `.vdocignore`.
- It adds pattern support. 
Until now to ignore `a` and the same pattern in a sub-directory (`b/a`) it is required to set the exact path for every subdirectory. Now it is sufficient to set the pattern
<table width="400">
<tr width="100%">
<th>
Ignore Goal
</th>
<th>
Current
</th>
<th>
Updated
</th>
</tr>
<tr width="100%">
<td>
<pre>
a
a/b
b/c/a
</pre>
</td>
<td>
<pre>
a
a/b
b/c/a
</pre>
</td>
<td>
<pre>
a
</pre>
</td>
</tr>
</table>
- Similar to gitignore a pattern starting with `/` will be treated as relative pattern.
-> `/a` will ignore `/a` but not `/b/a`.  
-> `/c/d` will ignore `/c/d` but not `/b/c/d`
- Treats lines starting with `#` as comments
- Removes …
> vdoc: rewrite and extend vdocignore

- vlib/cli/command.v
- vlib/v/slow_tests/inout/cli_root_default_control.out
- vlib/v/slow_tests/inout/cli_root_default_control.vv
The PR extends functionality of the cli module to allow more control over defaults.
Creating an application with the cli module and default commands and will result in something like:
```
Usage: <cool_upcoming_app> [flags] [commands] <paths>
Flags:
-i  --include       Lorem ipsum dolor.
-h  --help          Prints help information.
-v  --version       Prints version information.
--man           Prints the auto-generated manpage.
Commands:
help                Prints help information.
version             Prints version information.
man                 Prints the auto-generated manpage.
```
An example result with more direct control over defaults could look like (keeps some default flags):
```
Usage: <cool_upcoming_app> [flags] <paths>
Flags:
-i  --include       Lorem ipsum dolor.
-h  --help …
```
> cli: extend control over defaults

- vlib/db/mysql/mysql.c.v
- vlib/db/mysql/mysql_test.v
When executing the exec_one() command, if a field with a NULL value came across, it caused the RUNTIME ERROR: invalid memory access error
> mysql: exec_one invalid memory access

- .github/workflows/v_apps_and_modules_compile_ci.yml
The latest state of discord.v includes the required updates for #21296
Then I think all that's left for the linked PR then is the PR at gitly.
> ci: use latest upstream `discord.v` in apps and modules test

- .gitattributes
- cmd/tools/vcreate/vcreate.v
- cmd/tools/vcreate/vcreate_init_test.v
For highlighting / in some editors comment toggle.
Example in viewing a .vdocignore file on github 
|Current|Updated|
|-|-|
|![Screenshot_20240420_131307](https://github.com/vlang/v/assets/34311583/730ad434-52d8-4623-96b5-9723aa75376e)|![Screenshot_20240420_131305](https://github.com/vlang/v/assets/34311583/d1f69b3f-d772-4d28-a2bd-ad0afdb28dbb)|
> v: update linguist languages, add .vdocignore

- vlib/v/gen/c/array.v
This makes `./v -cc clang -cflags -fsanitize=undefined -o v2 cmd/v && ./v2 -cc clang -cflags -fsanitize=undefined vlib/v/compiler_errors_test.v` pass.
> cgen: fix `-fsanitize=undefined` used with `[]int{}.sort()`

- cmd/tools/vtest-self.v
With the changes, it will be possible to choose to run `v test-self` for project parts in `cmd` and `vlib`. By default - as it already is - both will be included, the same when passing both flags `v test-self --vlib --cmd`.
This can also help with local development but is mainly motivated to further improve our current CI - running parts when and where required.
As far as I can see, when changes are made just to a cmd tool, it **should usually not** require to run tests for the whole vlib. While changes to the vlib **should** include running tests for cmd tools. On the CI part, this can skyrocket tool development and reduce stress on vlib development. As PRs including updates just made to a tool without changes on the vlib can skip the most heavy part of CI.
Workflow update suggestions …
> tools: update `test-self` to allow to choose running tests for cmd and vlib

- cmd/tools/vtest-self.v
Approaches to handle args more safe and maintainable.
After: #21326. Alternatively, it can supersede the PR
> tools: rewrite test-self arg handling

- vlib/v/gen/c/cgen.v
- vlib/v/tests/array_fixed_c_test.v
"C__" was removed for fixed size C. arrays and resulted in unknown type.
Fixed by removing the removal.
Not sure which tests are expected to fail, so please double check.
Cheers,
Anton
> cgen: fix `myarr [1]C.mytype` fixed array fields, for `pub type C.mytype = voidptr`

- .github/workflows/bootstrapping_works_ci.yml
- .github/workflows/c2v_ci.yml
- .github/workflows/cross_ci.yml
- .github/workflows/docker_alpine.yml
- .github/workflows/docker_ubuntu.yml
- .github/workflows/docs_ci.yml
- .github/workflows/gen_vc_ci.yml
- .github/workflows/gg_regressions_ci.yml
- .github/workflows/linux_ci.yml
- .github/workflows/macos_ci.yml
- .github/workflows/module_docs_ci.yml
- .github/workflows/native_backend_tests_ci.yml
- .github/workflows/other_ci.yml
- .github/workflows/paths_ci.yml
- .github/workflows/periodic_ci.yml
- .github/workflows/sanitized_ci.yml
- .github/workflows/sdl_ci.yml
- .github/workflows/time_ci.yml
- .github/workflows/toml_ci.yml
- .github/workflows/v_apps_and_modules_compile_ci.yml
- .github/workflows/vab_ci.yml
- .github/workflows/vinix_ci.yml
- .github/workflows/wasm_backend_tests_ci.yml
- .github/workflows/websockets_ci.yml
- .github/workflows/windows_ci.yml
The PR updates the workflow condition that ensures that workflows run on all branches on forks, initially added here https://github.com/vlang/v/pull/14498
The PR simplifies the conditions by accessing the required values directly instead of retrieving them from a further nested event object.
I double-checked the correctness of the values with the docs and by reviewing their values on a fork. Still, please don't hesitate to share any potential concerns so they can be addressed. The change is part of a more exciting evolution that I'm preparing for a follow-up that will help improve developer convenience, but this one could be a nice to have in the history separately.
> ci: simplify workflow conditions

- vlib/v/checker/fn.v
- vlib/v/tests/spawn_array_mut_test.v
> checker: allow pass array as mut param to spawn fn

- .github/workflows/check_symlink_works.yml
- cmd/tools/vsymlink.v
- **ci: add check_symlink_works.yml**
- **ci, experiment: try using `sudo ./v symlink -githubci`, for linux and macos**
- **ci: remove sudo usage, improve the diagnostic message for `sudo ./v symlink -githubci`.**
- **ci: checkout appending to GITHUB_STEP_SUMMARY**
- **ci: use :rocket: for GITHUB_STEP_SUMMARY**
- **ci: use shell: bash for the windows job**
- **ci: use shell: bash for the windows task (shell: is not valid for the entire job)**
- **ci: use cd ~ with bash on windows too**
> tools: improve `v symlink -githubci` diagnostic message, when used outside CIs or with sudo

- vlib/v/gen/c/fn.v
- vlib/v/tests/comptime_ref_arg_test.v
> cgen: fix comptime ref argument passing

- .github/workflows/periodic_ci.yml
- cmd/tools/vtest-self.v
- vlib/net/http/http_httpbin_test.v
- vlib/net/mbedtls/mbedtls_sslconn_shutdown_does_not_panic_test.v
- vlib/net/unix/use_net_and_net_unix_together_test.v
The PR fixes network tests and reactivates them in CI
- updates the sslcon shutdown test so that the scenario spawns a test function thread without reading input, since it will currently block finishing the test.
```
v -d network vlib/net/mbedtls/mbedtls_sslconn_shutdown_does_not_panic_test.v
```
- adds a currently broken ftp test to the skip files of test-self
```
v -d network vlib/net/ftp/ftp_test.v
```
- skips a net.unix test on windows
- updates periodic CI and reactivates tests. On current master it only builds, tests were commented out in https://github.com/vlang/v/commit/e2822356c2875e468ad541961ee87ae78cc8c607
(regarding macos runners: I'm making the experience that macos-13 runner availability is usually better in comparison to the new m1 runners. Tests often complete before a m1 …
> test, ci: fix network tests; update and activate tests in periodic ci

- .github/workflows/bootstrapping_works_ci.yml
- .github/workflows/c2v_ci.yml
- .github/workflows/cross_ci.yml
- .github/workflows/docker_alpine.yml
- .github/workflows/docker_ubuntu.yml
- .github/workflows/docs_ci.yml
- .github/workflows/gen_vc_ci.yml
- .github/workflows/gg_regressions_ci.yml
- .github/workflows/linux_ci.yml
- .github/workflows/macos_ci.yml
- .github/workflows/module_docs_ci.yml
- .github/workflows/native_backend_tests_ci.yml
- .github/workflows/other_ci.yml
- .github/workflows/paths_ci.yml
- .github/workflows/sanitized_ci.yml
- .github/workflows/sdl_ci.yml
- .github/workflows/time_ci.yml
- .github/workflows/toml_ci.yml
- .github/workflows/v_apps_and_modules_compile_ci.yml
- .github/workflows/vab_ci.yml
- .github/workflows/vinix_ci.yml
- .github/workflows/vpm_ci.yml
- .github/workflows/wasm_backend_tests_ci.yml
- .github/workflows/websockets_ci.yml
- .github/workflows/windows_ci.yml
The change should improve and extend our current concurrency and cancellation management. In doing this, it should also allow for simplifications.
The main change is about using concurrency groups that are more tailored to relevant scenarios:
- It will make adding conditions to every job obsolete, which are currently required to control workflow runs for forks and to prevent CI pollution on the original repository.
- It will make it more pleasant to work on branches on forks before opening PRs. Currently, pushing changes to the same branch on a fork will not cancel running and waiting workflows, unlike in a PR. Therefore, it's easy to run into blocked CI that would require long waiting times or manual cancellation to free the CI pipeline. Now, making the cancellation policy on a fork …
> ci: update detection of workflow cancellation scenarios

- cmd/tools/vwhere/finder_utils.v
fixes:
```
v -cc gcc -cstrict cmd/tools/vwhere
```
> tools: fix compiling vwhere with `-cc gcc -cstrict`

- .github/workflows/linux_ci.yml
> ci: remove obsolete `-gc boehm` job

- .github/workflows/linux_ci.yml
- .github/workflows/macos_ci.yml
- .github/workflows/sanitized_ci.yml
- .github/workflows/tools_ci.yml
- .github/workflows/windows_ci.yml
With the PR, CI is intended to run as follows:
- Updates only made to cmd/tools -> run tool workflows (takes about 3 minutes), don't run regular vlib workflows
(exception: changes to builder tools will also trigger regular workflows)
- Changes including vlib -> run regular platform workflows (now focusing on vlib) + tool workflows
Other notable changes:
- For most situations, there should also be faster workflow runs for the current platform/sanitized CI, since the tools workflow is run in parallel and tool tests are extracted from regular platform workflows.
(there will be situations where the benefit of the parallel run will be relativized due to limited runner availability, e.g., when there are many open PRs / active workflow runs. However, there is more potential to optimize our …
> ci: add tools ci

- vlib/gg/gg.v
Initializing `PenConfig` struct produces an warning (error after 2024-05-31) saying that initializing private fields is not allowed.
> gg: make `PenConfig` fields public

- .github/workflows/cross_ci.yml
- .github/workflows/gg_regressions_ci.yml
- .github/workflows/linux_ci.yml
- .github/workflows/native_backend_tests_ci.yml
- .github/workflows/other_ci.yml
- .github/workflows/sanitized_ci.yml
- .github/workflows/toml_ci.yml
- .github/workflows/v_apps_and_modules_compile_ci.yml
- .github/workflows/vinix_ci.yml
- .github/workflows/websockets_ci.yml
- Dockerfile
- doc/docs.md
- vlib/clipboard/x11/clipboard.c.v
- vlib/db/pg/README.md
- vlib/net/websocket/tests/autobahn/local_run/Dockerfile
- vlib/v/checker/tests/array_plus_assign_err.out
- vlib/v/checker/tests/array_plus_assign_err.vv
- vlib/v/help/build/build-c.txt
Shouldn't be a crime to use the more modern `apt` command here if not needing features that are specific to `apt-get`. The latter for installing packages is reserved for my grandpa.
> v: consitently use `apt` instead of `apt-get` for common APT subcommands

- .github/workflows/check_symlink_works.yml
- cmd/tools/vbuild-tools.v
- cmd/tools/vsymlink.v
- cmd/tools/vsymlink/vsymlink.v
- cmd/tools/vsymlink/vsymlink_nix.c.v
- cmd/tools/vsymlink/vsymlink_windows.c.v
~~To keep the review simpler this PR does an update of the current state prior to an extraction. Also, this can be good to have in the history.~~
~~The followup would be a~~ structural update that allows for better organization and maintainability:
```
├── tools
│   ├── vsymlink
│   │   ├── vsymlink.v
│   │   ├── vsymlink_nix.c.v
│   │   └── vsymlink_windows.c.v
│   ├── ...
```
edit: Splitting the changes runs into some issues. To save some time, I'd directly include the extraction. The conceptual idea of the beforehand simplification would remain part of this PRs history.
> tools: utilize environment specific files for vsymlink 

- .github/workflows/binary_artifact.yml
- Adds tiggers to include PRs updating this workflow, while the publishing and releasing part is limited to tag pushes. 
- Simplifes the current state without compromising on functionality where it can be appropriate, makes more consistent.
- For macos-x86 `macos-13` was set instead of `macos-latest` because `macos-latest` is migrating towards arm runners.
The workflow run under this PR should allow to manually inspect the crated binary artifacts.
edit: https://github.com/vlang/v/actions/runs/8860588557?pr=21364
> ci: update `binary_artifact.yml`

- .github/workflows/wasm_backend_ci.yml
- vlib/v/gen/wasm/tests/wasm_test.v
- Currently, when running wasm test without a runtime available, they pass without additional  info about the missing wasm runtime. This makes it easy to miss malfunctions or regressions.
```sh
./v test vlib/v/gen/wasm/tests/
./v vlib/v/gen/wasm/tests/wasm_test.v
```
With the updates `exit(1)` instead of `exit(0)` would be used when tests are called with `VTEST_ONLY=wasm` (env variable that is also used in CI). This will give a more appropriate test result when explicitly testing wasm code and prevent false negatives.
```sh
VTEST_ONLY=wasm ./v test vlib/v/gen/wasm/tests/
```
- Windows tests are activated as far as they work to prevent regressing further (3 tests where disabled for windows ci runs).
All updates should be easy to follow per commit.
> wasm,test,ci: prevent false negatives, activate windows in workflow tests

- cmd/tools/check_os_api_parity.v
The PR does required maintenance work on the check_os_api_parity tool.
> tools: update check_os_api_parity.v

- .github/workflows/c2v_ci.yml
- .github/workflows/cross_ci.yml
- .github/workflows/docker_alpine.yml
- .github/workflows/docker_ubuntu.yml
- .github/workflows/gen_vc_ci.yml
- .github/workflows/gg_regressions_ci.yml
- .github/workflows/linux_ci.yml
- .github/workflows/macos_ci.yml
- .github/workflows/module_docs_ci.yml
- .github/workflows/other_ci.yml
- .github/workflows/sdl_ci.yml
- .github/workflows/time_ci.yml
- .github/workflows/toml_ci.yml
- .github/workflows/tools_ci.yml
- .github/workflows/vab_ci.yml
- .github/workflows/websockets_ci.yml
- .github/workflows/windows_ci.yml
improves running tests when they are relevant and skipping them when they are not.
> ci: add docker to tools workflow, update ignore paths

- .github/workflows/v_apps_and_modules_compile_ci.yml
The splits tests of the modules into separate jobs. The result is faster runs of the overall workflow and quicker failures on potential regressions. Also a better overview in which step an issue occurred would be provided.
E.g., in #21371, it is visible that the `v_apps_and_modules_compile_ci.yml` workflow requires the most time with ~19m, the second longest takes ~7m. The updated reduces it to about 10m, which translates into the time for the full CI run for PRs that only affect tool changes.
> ci: split up vsl / vtl run

- cmd/tools/check_os_api_parity.v
Refines the tool:
- addresses a flaw after the recent fixes https://github.com/vlang/v/pull/21367#issuecomment-2081482198
- uses the host os as base os instead of hardcoded linux
- uses the `pref.OS` enum for the checked os list this as a minor improvement to secure that actually relevant oses are checked.
> tools: refine `check_os_api_parity.v`

- .github/workflows/native_backend_ci.yml
- cleans up the workflow matrix
- removes macos-11 which reached eol and is not tested anymore in other workflows as well.
The changes are part of finalizing on planed rougher-/maintenance-changes to the CI, before moving towards suggestions that are more enhancement-based.
> ci: update native backend ci matrix

- .github/workflows/check_symlink_works.yml
Makes use of a matrix for jobs that share the same steps cross-platform or have marginal differences. This allows for easier and more consistent changes, and should simplify maintainability by reducing redundancy and eliminating the need to update and review the same things in multiple places.
Notable changes:
- While the changes manage to mainly simplify things, they also include an extension in functionality: testing sudo symlinking on macOS.
- Summary messages were removed. Although they are a nice gimmick, they have no real technical benefit. But please don't hesitate to let me know if summary messages should be preserved.
<br>
The changes are part of finalizing on planed rougher-/maintenance-changes to the CI, before moving towards suggestions that are more enhancement-based.
> ci: update symlink ci, add matrix

- .github/workflows/sanitized_ci.yml
- vlib/v/builder/cc.v
- The PR utilizes an enum for the CC instead of multiple boolean fields on the CcompilerOptions struct. Since only one CC can be used at a time,  structuring things this way can make sense.
A nice side effect of the change was discovering a bug where the CC is not set when compiling V on macOS. This was fixed by enabling compiler guessing on macOS even when V is not compiled in prod mode
Example CI after swapping to use an enum and panicking on an unknown compiler:
- macos-12: https://github.com/ttytm/v/actions/runs/8870500885/job/24352354898
- macos-14: https://github.com/ttytm/v/actions/runs/8870500874/job/24352354543
- To pass the sanitized workflow, a vpath in a step (which was enabled in a recently made change) was fixed. Additionally, a trigger was added for changes to this …
> builder: use cc enum in CcompilerOptions, fix cc detection, enable cc guessing without prod flag

- vlib/v/pref/pref.c.v
- vlib/v/pref/pref_test.v
Current:
```sh
❯ v --version
V 0.4.5 3226365
❯ v retry --version
V 0.4.5 3226365
❯ v retry -- git --version
V 0.4.5 3226365
```
Updated:
```sh
❯ v --version
V 0.4.5 21b76c1
❯ v retry --version
v retry 0.0.1
❯ v retry -- git --version
git version 2.44.0
```
> pref: fix version flag handling

- .github/workflows/other_ci.yml
Updates poor detection in the job that tries to prevent GPL licensed code.
Currently it is checked for the pattern `"a GPL license"`. Which will miss to detect a lot of potentially unwanted additions.
A GPL license can be GPL-2.0 GPLv2, AGPL, LGPL, LGPLv3, (LGPLv3) etc.. Grepping the projects code-base will give an idea. 
A screenshot of a sample run that includes a potential gpl license text:
https://github.com/ttytm/v/actions/runs/8886970660/job/24401414482
If the CI should be triggered and there are no concerns, merging with the failed job should make it green for the run after the merge.
> ci: update detection of accidentally added gpl licenses

- vlib/v/pref/pref_test.v
On FreeBSD 14, there is a problem using tcc because it does not deal with the symver assembly directive.
There is a discussion and preliminary, partial fix discussed in https://lists.gnu.org/archive/html/tinycc-devel/2023-11/msg00006.html
The clang compiler comes standard on FreeBSD so it is always available unless it has been removed.
Until tcc addresses the problem, this change allows the test to pass.
> v/pref: Fix pref test on Freebsd

- vlib/v/builder/cc.v
Reduces nesting / loc by handling a potential fatal error directly.
> builder: simplify generic cc detection

- vlib/v/pref/arch.c.v
- vlib/v/pref/pref.v
We similarly structure with pref/os. Since the arch code contains the only C code in pref.c.v it can be renamed to pref.v.
> v.pref: extract architecture related code into `arch.c.v`; rename `pref.c.v` to `pref.v`

- vlib/v/builder/cbuilder/cbuilder.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/cmain.v
This PR improves the debugging experience with gdb and lldb, for the generated vinit/vcleanup and main functions.
> cgen: use the real C line number instead of `#line 1000000 ...` in the C footer with `-g`

- vlib/v/pref/os.v
Would extract a functional change from other updates I'd like to suggest.
As a change that is quasi related to the scope of the update - can the deprecated options be removed here? I've seen removing deprecated code is on the list, and these have been deprecated for quite some time.
> pref: update `os_from_string`, add missing `qnx`, remove deprecated wasm options that used `-` instead of `_`

- vlib/v/pref/pref.v
The PR does a cleanup and makes minor adjustments. E.g., sorting match arms for more relevant matches first, adding a `gcc` arm instead of using it only in the fallback.
> pref: cleanup `Backend` and `CompilerType` functions, make minor performance adjustments

- .github/workflows/bootstrapping_ci.yml
The changes should be able to address: https://github.com/vlang/v/commit/fd66067bc02dba9fc8198d1fea04c9e3c071de74#commitcomment-141513977
A small change included here is a resolved linter complaint for the empty
```
B_CFLAGS:
```
`B_CFLAGS: ''` Would address it, but as the var is apparently not used it was removed.
> ci: pass a good commit to oldv.v in `bootstrapping_ci.yml`

- vlib/v/pref/os.v
Split up of #21395 to allow isolating bug.
@spytheman in regards to what I commented in the linked PR about using:
```v
fn res_fn()  ! {
return match {
// ...
else { error() }
// vs
else { return error() }
}
}
```
I run the changes with just `error` instead of the `return error` in `os_from_string`  with the results: https://github.com/ttytm/v/actions?query=branch%3Apriv%2Fpref%2Fos-cleanup+
> v.pref: cleanup os from and to string functions

- vlib/datatypes/set.v
- vlib/datatypes/set_test.v
> datatypes: set - operator implementation changes original set

- vlib/v/checker/tests/result_chan_test_err.out
- vlib/v/checker/tests/result_chan_test_err.vv
- vlib/v/parser/parser.v
> parser: add check for result type on chan init

- .github/workflows/sanitized_ci.yml
The change is missing for this job. Other sanitized tests were already updated.
Tools get extended sanitized tests in the tools ci now.
> ci: remove now redundant tool tests also from gcc sanitized undefined job

- vlib/os/os_nix.c.v
- vlib/os/os_test.c.v
> Fix os.execute stderr redirection

- vlib/v/pref/pref.v
- vlib/v/pref/pref_test.v
Splits up changes to improve the module's quality step by step with as few complications as possible. Should eventually allow for further performance improvements
> v.pref: simplify command arg handling, add tests

- .github/workflows/macos_ci.yml
- cmd/tools/vtest-self.v
- vlib/v/builder/cc.v
- Fixes compilation with `-cstrict` on macos-13 and macos-arm. This is done by only adding `-x none` when there would be actual paths that follow it.
```sh
./v -cg -cstrict -o v cmd/v
```
- Adds arm runner to macos wokflow.
> builder, ci: fix compilation on macos-arm with cstrict; run macos ci also on arm runner

- vlib/time/duration.v
- vlib/time/duration_test.v
> time: fix string representation of negative Duration

- .github/workflows/bootstrapping_ci.yml
Fixes workflow fails of the `Bootstrapping CI` on forks and occasionally in PRs. 
Failures happen, because oldv receives a commit that is available on master, but the master branch itself is not available in the workflow due to a shallow checkout of the checkout action.
The fix is simple by ensuring the master branch is available.
> ci: ensure `master` is available when trying to check out it's commits to build oldv

- cmd/tools/install_binaryen.vsh
- cmd/tools/vvet/filter.v
- cmd/tools/vvet/vvet.v
- vlib/v/parser/parser.v
Currently, vet errors are validated and filtered in the parser.
The changes will help with to take vet to the next level while also simplifying the parser and improving it's performance. Similar to recent changes, this also fits under the mantra "Parse, don't validate".
This will also resolve TODOS, which should not be TODOs in those modules.
> ```v
> // TODO: `$if vet {` for performance`
> ```
To simplify reviewing things I'll try to submit the changes in a few parts that can hopefully stand on their own without falling appart. The parts should become simpler when things progress. 
The first part creates a base for vets evolution and extends it's ability to handle  trailing space and indentation errors on it's own. This already takes load of the parser.
> vet, parser: rewrite vet error handling (improve parser performance extend vvet) p1

- cmd/tools/vvet/tests/const_dynamic_array_notice.out
- cmd/tools/vvet/tests/prog_without_main_fn.out
- cmd/tools/vvet/vvet.v
- vlib/v/parser/parser.v
> vet, parser: move dynamic const array check from parser into vet

- cmd/tools/vfmt.v
- vlib/v/util/diff.v
- vlib/v/util/diff/diff.v
- vlib/v/util/diff/diff_test.v
The rewritten module should extend functionality, make usage easier/less verbose, fix issues and resolve friction points that may stand in the way of using it in whatever context.
An overview of the changes is given below. However, it should not be necessary for the review, it was attempted to keep the code changes compact and easy to understand. Feel free to skip the overview.
- Use of known diff tools that can actually return a string value.
To make the function call itself as safe and reliable as possible, tools like `code` and `opendiff` that open non-conforming files in a gui and do return a result string is limited to the overwrite via the environment variable. Additionally, it is possible to disable and to customize overwrites via the env variable.
- Use of Result return types
- …
> v.util: rewrite diff module, deprecate old functions

- vlib/v/help/common/fmt.txt
> v.help: update help for `fmt`

- cmd/tools/vvet/tests/array_init_one_val.out
- cmd/tools/vvet/tests/array_init_one_val.vv
- cmd/tools/vvet/vvet.v
- vlib/v/parser/expr.v
Due to similar locations changed in vvet this might conflict with #21421.
It's recommended to await the re-scan after one is resolved.
> vet, parser: move array_init_one_val checks from parser into vet

- vlib/net/address.c.v
- vlib/net/address_test.c.v
When I start write a reverse proxy for my android / ios app, I need a port that is always available, so I set address `':0'`, then I try to obtain port that automatically assigned, but i can't find a function like `a.port()`.  Although I can parse the address to get the port, but this is inelegant, so i add function `.port()`.
```v
fn main() {
mut server := net.listen_tcp(.ip, ':0') or { panic(err) }
println(server.addr()!)
println(server.addr()!.port()!) // add port func
mut socket := server.accept()!
// ...
}
```
```v
// port returns the ip or ip6 port of the given address `a`
pub fn (a Addr) port() !u16 {
match unsafe { AddrFamily(a.f) } {
.ip {
unsafe {
return conv.ntoh16(a.addr.Ip.port)
}
}
.ip6 {
unsafe {
return conv.ntoh16(a.addr.Ip6.port)
}
}
.unix {
return error('unix addr has no …
```
> vlib: add port() for net.Addr

- cmd/tools/vvet/vvet.v
- vlib/v/parser/parser.v
After #21422, #21423 this PR can already remove vet_errors and vet_notices from the parser. Extending vvet to be able to handle the scanner errors as well would be the next step.
> vet, parser: remove vet_errors and vet_notices from parser

- vlib/v/util/diff/diff.v
Fixes a mistake where a condition should use `tool` (the already resolved `opts.tool`). This will result in a correctly true condition when the `opts.tool` is `== .auto` and the auto tool is `diff`.
> v.util: fix condition for color attempt when auto tool is `diff`

- vlib/regex/README.md
The character class example for all latin lowercase, uppercase, and numeric characters used a lower case `z` for the end of the range starting with `A`.  While the resulting character class would contain all the above mentioned characters, there would be a few more, unexpected, characters included in the range.  In particular, `[`, `\`, `]`,  `^`, `_`, and the backtick character.
> regex: fix typo in regex character class example

- vlib/regex/README.md
I noticed several other minor typos while reading the README.md.
> regex: Fix a handful of typos in the regex README

- vlib/v/util/diff/diff.v
Using a constant meant that the diff tools were always found, even if they were not used.
That added some milliseconds, to the start time of programs that used `v.util.diff`, like `v fmt` or `v test-cleancode`.
Changing `available_tool` to be a function, allows it to delay, and cache the invocation of the slower find_working_diff_tool, until it is actually needed (which may be never).
> v.util: fix the performance of `v test-cleancode`, when a slower diff tool is installed

- cmd/tools/vvet/errors.v
- cmd/tools/vvet/filter.v
- cmd/tools/vvet/vvet.v
With the latest updates, we can move the `vlib/vet/vet.v` module, which was used for errors in the parser and scanner, to the vvet tool, as it is now able to handle the errors itself and not used anymore in the parser and scanner. This will cleanup the vlib and keep code closer to it's related source.
> v, vet: move now obsolete vlib vet module to cmd vet

- cmd/tools/vvet/vvet.v
- vlib/v/parser/parser.v
> vet, parser: use `parse_file`, remove `parse_vet_file`

- vlib/v/util/diff/diff.v
- vlib/v/util/diff/diff_test.v
Providing information in the public constant should further extend developer possibilities. 
A test for this is added in a way that makes the tests for the full module more regression safe:
Ref., regarding the availability of `diff` as tool on all CI runners:
> v.util: make all available diff tools accessible, extend tests

- .github/workflows/binary_artifact.yml
- .github/workflows/release_ci.yml
Same as with a recent matrix related CI update:
> Makes use of a matrix for jobs that share the same steps cross-platform or have marginal differences. This allows for easier and more consistent changes, and should simplify maintainability by reducing redundancy and eliminating the need to update and review the same things in multiple places.
While the changes manage to mainly simplify things, they also include improvements.
Notable changes concern only Windows release archives:
- data structure that allows for more platform consistency / independency when downloading and viewing the contents of a Windows archive.
Example screenshots showing directories and archives in comparison on a Linux system:
- Current - Windows and Linux directories after extraction on the left and archives on the …
> ci: update binary artifact workflow, add matrix

- cmd/tools/vfmt.v
- cmd/tools/vtest-cleancode.v
- vlib/v/help/common/fmt.txt
> tools: improve performance of `v test-cleancode` and `v fmt -inprocess -verify .`

- .github/workflows/check_symlink_works.yml
- cmd/tools/vsymlink/vsymlink.v
- cmd/tools/vsymlink/vsymlink_windows.c.v
Splits up changes to make `./v symlink` work platform independent in CI.
The PR:
- Moves handling of github symlink to the `vsymlink_windows.c.v` code. On unix-like systems regular symlinking will be used, whether or not `-githubci` was passed.
- An improvement made alongside is that instead of adding `os.getwd()` to the GITHUB_PATH, `new_sys_env_path` is used. It is the path used on a regular windows systems -> Brings tests in Windows CI closer to a regular scenario, makes them more reliable.
- Now `./v symlink` should already work platform independent. The `-githubci` flag is not required anymore. Cases with `sudo` and the `-githubci` flag are still covered by the current, unchanged CI jobs. They should continue to work and there are no plans in changing this inside the PRs that are …
> tools: make `./v symlink` work platform independent in CI

- cmd/tools/vup.v
When using v up the following is displayed
```zsh
v up
Updating V...
> git_command: git pull https://github.com/vlang/v master
V self compiling (-cc tcc -o v2)...
V built successfully as executable "v".
> done recompiling.
> recompiling vup.v ...
Current V version: V 0.4.5 6cc096a, timestamp: 2024-05-07 20:38:32 +0300
```
With this, I've capitalised `>Done recompiling`and `recompiling vup.v`.
> v up Info output.

- .github/workflows/c2v_ci.yml
- .github/workflows/cross_ci.yml
- .github/workflows/gg_regressions_ci.yml
- .github/workflows/linux_ci.yml
- .github/workflows/macos_ci.yml
- .github/workflows/native_backend_ci.yml
- .github/workflows/other_ci.yml
- .github/workflows/sanitized_ci.yml
- .github/workflows/toml_ci.yml
- .github/workflows/vab_ci.yml
- .github/workflows/vinix_ci.yml
- .github/workflows/vup_works.yml
- .github/workflows/websockets_ci.yml
- .github/workflows/windows_ci.yml
Removes the flag for where `v symlink` is used in a "regular" way. Keeps it in tests that should test the flag.
> ci: use `v symlink` without `-githubci` for regular symlinking

- vlib/v/util/diff/diff.v
The equality check of the strings that should be compared is done in most cases before the function is called in the V code base. It can be expected that it will be the same for external projects if they use the module.
Due to this, what was thought as fast-path can become a slow-down in cases where the compiler is not able to optimize the double check. Therefore it is removed and the function merely cares about returning the result of the comparison result.
> v.util: remove fast path in `diff.compare_text`

- cmd/tools/vpm/settings.v
`os.open_append` called by `logger.set_output_path` calls `C._wfopen(wpath, mode.to_wide())` with `mode := 'ab'`. When the folder `$VMODULES\cache` does not exist, `C._wfopen(wpath, mode.to_wide())` returns NULL and causes an error.
This PR aims to avoid 'V panic: error while opening log file `$VMODULES\cache\vpm.log` for appending' error.
Before modification:
```
/d/gym/test/mingw-w64-packages/mingw-w64-v/vmodules/mingw-w64-i686-v-weekly.2024.19-1
ls: cannot access '/d/gym/test/mingw-w64-packages/mingw-w64-v/vmodules/mingw-w64-i686-v-weekly.2024.19-1': No such file or directory
V panic: error while opening log file D:\gym\test\mingw-w64-packages\mingw-w64-v\vmodules\mingw-w64-i686-v-weekly.2024.19-1\cache\vpm.log for appending
v hash: d6d0f9b
print_backtrace_skipping_top_frames is not …
```
> vpm: init_settings: mkdir_all before set_output_path

- vlib/cli/cli_test.v
- vlib/cli/command.v
- vlib/cli/testdata/default_command_no_flag_err.out
- vlib/cli/testdata/default_command_no_flag_err.vv
- vlib/cli/testdata/default_help_flag_no_command.out
- vlib/cli/testdata/default_help_flag_no_command.vv
- vlib/cli/testdata/default_version_flag_no_command.out
- vlib/cli/testdata/default_version_flag_no_command.vv
- vlib/cli/version.v
Fixes default flags not working as expected when their commands are disabled.
Example:
```v
// foo.v
import cli { Command, CommandFlag }
import os
fn main() {
mut cmd := Command{
name: 'foo'
version: '0.1.0'
posix_mode: true
defaults: struct {
version: CommandFlag{false, true}
help: CommandFlag{false, true}
}
}
cmd.parse(os.args)
}
```
Current:
```sh
❯ v run foo.v --version
```
Updated:
```sh
❯ v run foo.v --version
foo version 0.1.0
```
> cli: fix default flags when their command equivalents are disabled

- cmd/tools/vvet/vvet.v
Minor cleanup and performance improvement.
Commits building up on each other.
> tools.vet: reduce nesting in `vet_fn_documentation`, skip vetting empty lines

- .github/workflows/symlink_ci.yml
- cmd/tools/vsymlink/vsymlink.v
This one contains an interesting coincidence and revelation. 
The last update used `./v symlink --githubci` (double-dashed) instead of `./v symlink -githubci` to cover extended cases for the flag. However, the double-dashed flag results in the default symlink being used instead of the GITHUB_PATH-symlink that is based on the current directory. Now, using the symlink with the single dash flag `-githubci` fails to pass the extended test cases.
This shows that using the flag actually results in worse functionality. The solution would be to already use `setup_symlink` instead of `setup_symlink_github` (even when the flag is passed), as it fixes an issue.
Based on the recent heated(while still constructive) discussion, the coincidence might look like an evil plan, setting this revelation up, …
> tools, ci: print info to use v symlink instead of `v symlink -githubci`

- cmd/tools/vdoc/vdoc_file_test.v
It's not clear why the error doesn't appear in ci, but the local test keeps appearing
```
D:/gym/test/mingw-w64-packages/mingw-w64-v/src/v-weekly.2024.19/cmd/tools/vdoc/tests/testdata/basic/basic.v OK
D:/gym/test/mingw-w64-packages/mingw-w64-v/src/v-weekly.2024.19/cmd/tools/vdoc/tests/testdata/comments/main.v OK
D:/gym/test/mingw-w64-packages/mingw-w64-v/src/v-weekly.2024.19/cmd/tools/vdoc/tests/testdata/multiline/main.v OK
D:/gym/test/mingw-w64-packages/mingw-w64-v/src/v-weekly.2024.19/cmd/tools/vdoc/tests/testdata/newlines/main.v OK
D:/gym/test/mingw-w64-packages/mingw-w64-v/src/v-weekly.2024.19/cmd/tools/vdoc/tests/testdata/output_formats/main.v OK
D:/gym/test/mingw-w64-packages/mingw-w64-v/src/v-weekly.2024.19/cmd/tools/vdoc/tests/testdata/readme_in_project_root/src/main.v OK …
```
> vdoc/vdoc_file_test.v: fix test_out_path

- vlib/picoev/picoev.v
C [`recv`](https://linux.die.net/man/2/recv) and [`accept`](https://linux.die.net/man/2/accept) calls can reply with `EAGAIN` or `EWOULDBLOCK` on a `-1` return value, which is to be expected for the asynchronous picoev event loop server.
Fix #21316 by continuing silently in these cases.
As a runtime asynchronous bug, the test is a stressful benchmark. In one terminal:
```
$ v run pico.v
Starting webserver on http://localhost:8089/ ...
```
In another (on a 24-core machine):
```
$ siege --concurrent=22 --reps=5000 http://localhost:8089
...
Transactions:                 110000 hits
Availability:                 100.00 %
Elapsed time:                   7.50 secs
Data transferred:               1.47 MB
Response time:                  0.00 secs
Transaction rate:           14666.67 trans/sec …
```
> picoev: handle `EAGAIN` or `EWOULDBLOCK` quietly

- .github/workflows/bootstrapping_ci.yml
- thirdparty/stdatomic/nix/atomic.h
- thirdparty/stdatomic/win/atomic.h
- vlib/os/filelock/lib_windows.c.v
- vlib/sync/channels.c.v
- vlib/sync/pool/pool.c.v
- vlib/sync/stdatomic/1.declarations.c.v
- vlib/sync/sync_windows.c.v
- vlib/sync/waitgroup.c.v
- vlib/v/builder/msvc_windows.v
- **ci: fix bootstrapping job, filter only event=push for finding commits with good CI runs, to prevent firing for commits on PRs with branch = master**
- **ci: workaround for cross compilation from macos to windows (mingw-w64--11.0.1_1.ventura.bottle.3.tar.gz is stricter)**
- **ci: fix os.filelock for windows (for crosscompiling from macos with mingw-w64--11.0.1_1.ventura.bottle.3.tar.gz)**
- **ci: fixes for cross compilation from macos->windows, due to stricter mingw-w64--11.0.1_1.ventura.bottle.3.tar.gz**
- **ci: fix cross compilation from macos to windows with mingw-w64**
> sync,os,thirdparty: fix cross compilation from macos to windows

- cmd/tools/modules/testing/common.v
- cmd/tools/test_if_v_test_system_works.v
- cmd/tools/vtest_test.v
- vlib/encoding/txtar/pack_unpack.v
- vlib/encoding/txtar/txtar_test.v
Fix #20778 .
Regression happened after https://github.com/vlang/v/pull/20520 .
> testing: fix `v -stats test folder/` not failing for a _test.v that fails

- vlib/os/dir_expansions_test.v
- vlib/os/os.v
- vlib/os/os_test.c.v
> vlib.os: fix join-path

- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/c_structs/cstruct.h
- vlib/v/tests/c_structs/cstruct_alias_test.v
> cgen: fix c struct option alias printing

- cmd/tools/vdoc/theme/doc.js
Fixes the last bug mentioned in the recent issue https://github.com/vlang/v/issues/21222#issuecomment-2049838713.
For a low-effort-repro I would reference a module that is currently suffering from the issue:
E.g. try to use the search in the README index page of https://ttytm.github.io/dialog/index.html.
Trying again with the changes in the modules directory:
```sh
v doc -f html -m -readme .
```
|Current|Update|
| - | - |
| ![](https://github.com/vlang/v/assets/34311583/c1aa2dc9-1f1c-4e26-8342-77e7389d75b9) | ![](https://github.com/vlang/v/assets/34311583/21801696-6648-4c34-aa56-138dea78e22d) |
> vdoc: fix search in README `index.html` when documentation was generated with `v doc -f html -m -readme` flags

- cmd/tools/vdoc/vdoc.v
If a module stores its code files in an `src` directory, it is currently necessary to explicitly pass the `src` directory as a submodule when generating the documentation for the module with `v doc`:
```sh
v doc -comments <modname>
v doc -comments <modname>.src # would be required
```
Without `.src` it will result in e.g.,:
```sh
❯ v doc -comments <modname>
Available modules:
<modname>.examples
<modname>.src
```
With the changes, `<modname>` and `<modname>/src` would be tried as sources when using `v doc -comments <modname>`. This would lead to a more consistent behavior with regard to the `src` directory, similar to module imports.
> vdoc: include `src` dir when trying to generate doc comments for module with `v doc -comments <modname>`

- cmd/tools/vdoc/files.v
Fixes *legitimately* failing tests in e.g.: #21511, https://github.com/vlang/v/actions/runs/9111620514/job/25049117265?pr=21511
I can't tell why the tests related to this functionality only fail now. I can't reproduce a non-failing state. Moving back several commits and rebuilding with the associated older vc, the tests should have failed earlier.
> vdoc: fix handling of .vdocignore files in subdirectories

- vlib/net/unix/stream.c.v
Prior to this patch, connecting over a Unix socket would print the path of the `.sock` file. Remove the debug print in order to give user code control over messages to the terminal.
> net.unix: Remove debug print.

- cmd/tools/vdoc/files.v
- cmd/tools/vdoc/vdoc_test.v
With the changes, all ignore rules for a specified directory and its subdirectories are gathered first. This removes coupling with the process of getting modules and should simplify  and improve testability. A test is also added.
> vdoc: improve vdocignore file handling by walking all .vdocignore sub-paths in IgnoreRules.get, add test

- vlib/v/gen/c/cgen.v
- vlib/v/tests/c_structs/cstruct.h
- vlib/v/tests/c_structs/cstruct_default_value_test.v
> cgen: fix C struct init when it has default expr

- cmd/tools/vdoc/vdoc_file_test.v
- vlib/v/pref/pref.v
- vlib/v/pref/unknown_options_test.v
- vlib/v/pref/vsh_envbang_test.v
Compiling a single code file with flags does not give a warning, and continues the compile.
This will work on real or fake flags
This does not look nice and could cause unknown usage.
```sh
$ ./v examples/hello_world.v -autofree
$ ./v examples/hello_world.v -garbage
$ echo $?
0
```
This change reports an error and exits as such. It will report the same error if the argument is valid or not, but it is clear what the problem is.
```sh
$ ./v examples/hello_world.v -autofree
Build flags must be before the source file.
$ ./v examples/hello_world.v -garbage
Build flags must be before the source file.
$ echo $?
1
```
> v.pref: error for `v file.v --unknown-option`

- vlib/builtin/js/builtin.v
- vlib/builtin/result.v
- vlib/os/signal_test.v
- vlib/v/gen/c/comptime.v
- vlib/v/slow_tests/inout/orm_panic_for_insert_into_not_created_table.out
- vlib/v/slow_tests/inout/orm_panic_for_select_from_not_created_table.out
- vlib/v/tests/option_test.c.v
- vlib/v/tests/results_test.v
- vlib/vweb/tests/controller_duplicate_server.v
- **builtin: let MessageError.msg() return only the message, make MessageError.str() return both the message and the code of an error**
- **fix warning in vlib/vweb/tests/controller_duplicate_server.v**
- **fix other test failures**
The PR was motivated by https://discord.com/channels/592103645835821068/592320321995014154/1241174911486136372 .
> builtin: simplify MessageError.msg()

- vlib/v/parser/assign.v
- vlib/v/parser/parser.v
Will extend capabilities and e.g. allow to finish #21421.
Current types in `scope` and `info`
```sh
scope: &# 3 - 311
* var: foo - ast.Type(0x0 = 0) # e.g. string type
* var: baz - ast.Type(0x0 = 0) # e.g. array type
info: ast.IdentInfo(ast.IdentVar{
typ: ast.Type(0x0 = 0)
share: mut
is_mut: false
is_static: false
is_volatile: false
is_option: false
})
```
Updated:
```sh
scope: &# 3 - 311
* var: foo - ast.Type(0x15 = 21)
* var: baz - ast.Type(0x17 = 23)
info: ast.IdentInfo(ast.IdentVar{
typ: ast.Type(0x17 = 23)
share: mut
is_mut: false
is_static: false
is_volatile: false
is_option: false
})
```
The parsing can be limited to `p.pref.is_vet` and `p.pref.is_fmt` if it is preferred.
> parser: parse string and array typ idx of `ScopeVar` and `Ident`

- vlib/v/ast/table.v
- vlib/v/checker/checker.v
- vlib/v/tests/option_interface_test.v
> checker: fix option interface member checking when `none` is passed

- cmd/tools/vtest_test.v
tcc on FreeBSD does not support `.symver` which causes compile errors for cmd/tools/vtest_test.v.
When this omission gets corrected, we can remove this update but in the mean time, this allows the test to pass.  The choice to use clang as the C compiler is because that is the default compiler distributed with the base FreeBSD system.
> tools: default to -cc clang on FreeBSD tests

- vlib/veb/sendfile_freebsd.c.v
- vlib/veb/veb.v
- vlib/x/vweb/sendfile_freebsd.c.v
- vlib/x/vweb/vweb.v
Use sendfile() on FreeBSD in vlib/veb as well as vlib/x/vweb. This call API is somewhat different from the Linux one so fix up args and return the expected value on linux.  Note that at least `vlib/veb/tests/large_payload_test.v` uses sendfile and succeeds. Use of sendfile can be manually verified by running the test under ktrace.
> veb: support sendfile() syscall on FreeBSD

- vlib/builtin/builtin.c.v
Mainly to have it available in the stdlib docs.
> builtin: make FnExitCb type public

- examples/process/execve.v
Cleans up an example that imho can become unclear to the viewer due to unnecessary complexity and confusing comments.
Alternatively, removing the file and adding the examples to the function comment could also work here:
```v
// Example:
// ```v
// execve('/usr/bin/ls', ['-la', '-h'], [])! // Passes only an array of args.
// execve('/usr/bin/bash', ['-c', 'ls -lah -s'], [])! // Considers args that would need to be passed within quotes.
// execve('/usr/bin/man', ['true'], ['MANWIDTH=60'])! // Passes an environment variable that affects the command.
// ```
```
> examples: cleanup `process/execve.v`

- vlib/builtin/string.v
- **builtin: reduce allocations for s.index_kmp/1 and s.replace_once/2**
- **builtin: reduce allocations for s.replace/2**
- **builtin: restore s.replace_once/2 from master**
> builtin: reduce allocations in s.index_kmp/1 and s.replace/2

- vlib/os/os_nix.c.v
> os: remove `mut` declarations for unchanged vars in `os_nix.c.v`

- vlib/net/http/server.v
Avoids conflicts with tools, that start their own http servers on 8080 by default, like https://github.com/koute/bytehound .
> net.http: change default http.Server listening address to :9009

- vlib/builtin/string.v
Simplifies the functions for better read and maintainability.
> builtin: simplify splint_nth methods

- vlib/os/debugger_darwin.c.v
- vlib/os/debugger_freebsd.c.v
- vlib/os/debugger_linux.c.v
So far the `debugger_present()` function only works partially. All Unix-based systems use the same procedure. `C.ptrace()` is used to check whether the process can “debug” itself. If this is the case, no debugger is present, but `ptrace` is now used as such. If it is called again, the function immediately returns that a debugger is present. However, the appropriate “detach” function cannot be used if the process “follows” itself. 
Current behaviour on non Windows systems:
```v
fn main(){
if os.debugger_present(){
println("debugger here")
}else{
println("no debugger")
}
println("###between os.debugger_present()###")
if os.debugger_present(){
println("debugger here")
}else{
println("no debugger")
}
}
```
Output:
```
no debugger
###between os.debugger_present()###
debugger here   <<< this …
```
> os: fix debugger_present() for non Windows OSes

- .github/workflows/macos_ci.yml
- .github/workflows/v_apps_and_modules_compile_ci.yml
- .github/workflows/vpm_ci.yml
Extends coverage on macOS and Linux
- V Apps and Modules get tested on macOS in `v_apps_and_modules_compile_ci.yml`
- macOS app-tests (ved and vlang/ui) that were tested in `macos_ci.yml` are now part of the above workflow
- vlang/ui examples that were tested on mac are now also tested on Linux
- vpm test runs include macos arm
> ci: extend coverage, move app test from macos_ci to v_apps_and_modules_ci

- vlib/v/ast/ast.v
- vlib/v/checker/struct.v
- vlib/v/tests/modules/structs_with_noinit/shapes.v
- vlib/v/tests/struct_field_default_union_of_structs_marked_with_noinit_test.v
> checker: fix checking of default field initialisations, that are part of unions of structs tagged with `@[noinit]`

- cmd/tools/vdownload.v
- cmd/v/v.v
Makes possible this:
```sh
v download https://raw.githubusercontent.com/vlang/v-analyzer/main/install.vsh
v install.vsh
```
instead of:
```sh
v -e "$(curl -fsSL https://raw.githubusercontent.com/vlang/v-analyzer/main/install.vsh)"
```
> tools: add `v download URL` as a simple way, to download single files, to avoid curl/wget etc, which are not available uniformly.

- vlib/net/urllib/urllib.v
- vlib/net/urllib/urllib_test.v
Updates the internal urllib function `parse_authority` that is used by the public `parse` function. Adds tests.
As far as I could tell the current implementation was based of Go's implementation, which has a different error handling. With V it was possible to make the code more readable while managing to slightly improve the performance at the same time.
<details>
<summary>Performance test:</summary>
```
❯ v repeat -r 20 benchmarks/pa_gcc_new benchmarks/pa_gcc_old
Summary after 1 series x 20 runs (`>` is the first cmd)                                                                                                                            
>  1       === `benchmarks/pa_gcc_new`
232.0ms ± σ:   6.6ms, 224.8ms … 254.0ms
2     +2.5% `benchmarks/pa_gcc_old`
237.7ms ± σ:   4.3ms, 231.8ms … …
```
> net.urllib: cleanup parse_authority, add test

- vlib/v/fmt/fmt.v
Fixes
```v
import arrays
struct Release {
version    string
prerelease bool
}
releases := [Release{'1.0.0-dev', true}, Release{'0.2.0', false}, Release{'0.1.0', false}]
version := 'nightly'
v := match version {
'nightly' {
arrays.find_first(releases, fn (it Release) bool {
return it.prerelease
})?
}
else {
Release{}
}
}
dump(v)
```
Where v fmt does
```diff
v := match version {
'nightly' {
first_l_match := arrays.find_first(arr, fn (it Foo) bool {
-			return !it.prerelease
+			return !version.prerelease
})?
}
}
```
The fix is achieved by removing code whose use was likely superseded and it remained as a hotbed for errors. This assumption is based no breaking tested cases and not being able to trigger what the condition apparently should cover.
> fmt: don't break `it` variable name in match expression function calls

- vlib/net/urllib/urllib.v
Currently, errors in this function are "covered" as the string type that would be returned when the function runs successful.
Using actual error returns is also closer to the Go implementation the function is based on:
Ref.: https://github.com/golang/go/blob/fa08befb25e6f4993021429aa222dad71a27ed07/src/net/url/url.go#L644-L656
> net.urllib: update parse host to allow for better error handling

- cmd/tools/vfmt.v
- examples/hello_world.v
Currently, it's hard to combine a diff-output while also verifying that paths are formatted.
Up to now I'm doing contortions like:
```sh
v fmt -verify <path> && exit 0 || v fmt -diff <path> && exit 1
```
`v fmt -verify -diff` is not possible either, since the single flags do return early.
With the changes, the `-diff` flag will cause an exit code 1 if diffs are encountered. This is equivalent to diff tools like `diff`.
> vfmt: exit with error code if encountering diffs with `-diff` flag

- vlib/regex/README.md
- vlib/regex/regex.v
- vlib/regex/regex_test.v
Implementation on the `\x` and `\X` BSLS
- regex added `\xAF` and `\X1234` BLSL match
- `\x12` match a byte with the hex value 0x12
- `\X1234` match two consecutive bytes with the hex values 0x12 0x34
- more tests
- some code cleaning
- solve the issue #21607
> Regex: implementation of the \x \X BSLS, issue #21607

- vlib/v/checker/tests/map_def_err.out
- vlib/v/checker/tests/map_def_err.vv
- vlib/v/parser/parse_type.v
> checker: fix missing map type definition syntax

- cmd/tools/vdownload.v
- vlib/net/http/backend.c.v
- vlib/net/http/download.v
- vlib/net/http/download_progress.v
- vlib/net/http/download_silent_downloader.v
- vlib/net/http/download_terminal_downloader.v
- vlib/net/http/http.v
- vlib/net/http/request.v
- vlib/net/http/server_test.v
- **net.http: implement http.download_file_with_progress/2, to download big content to a file, by saving each chunk as it is received, without growing the memory usage**
- **bump net.http bufsize to 64KB**
- **tools: implement --sha1 and --sha256 options to `v download` (off by default).**
- **net.http: enhance http.TerminalStreamingDownloader with speed, elapsed, eta, and bytes already downloaded**
> net.http:  implement http.download_file_with_progress/2, saving each chunk, as it is received, without growing the memory usage

- vlib/v/checker/tests/option_and_result_err.out
- vlib/v/checker/tests/option_and_result_err.vv
- vlib/v/parser/parse_type.v
- vlib/v/parser/tests/option_result_err.out
- vlib/v/parser/tests/result_option_err.out
> checker: fix missing option and result wrong type return type definition

- vlib/v/gen/c/cheaders.v
"bool" is a builtin type in latest c language standard, added "CUSTOM_DEFINE_no_bool" macro for compatibility.
> Add "no_bool" macro for clatest language standard

- vlib/builtin/js/string.js.v
- vlib/builtin/string.v
- vlib/builtin/string_test.v
- vlib/net/urllib/urllib.v
- vlib/os/os.v
- vlib/semver/parse.v
- vlib/v/checker/struct.v
- vlib/v/gen/js/js.v
Updates the `index_u8_last` => `last_index_u8` method and deprecates the former to be consistent with the recent switch made by Alex from `index_last` to `last_index`. It is also consistent with the Go func equivalents.
> builtin:  update `last_index_u8`, deprecate `index_u8_last` string methods, make consistent with `last_index`

- vlib/v/util/diff/diff.v
- vlib/v/util/diff/diff_test.v
Allows further customization when comparing strings.
It adds the ability to set the names that are used for the temporary files when comparing strings directly.
Two main reason:
- Some names in the output can fit better
- Several diff viewers colorize based on on the file extension. E.g. when using delta or piping output like `v fmt -diff file.v | diff-so-fancy` or using other viewers set via `VDIFF_CMD`.
<details>
Filename samples:
|Current default (not customizable)|Updated default|Updated names passed|
|-|-|-|
|![Screenshot_20240606_045034](https://github.com/vlang/v/assets/34311583/d844ec43-8d0e-4d52-8438-cd0d0fb8a4e9)|![Screenshot_20240606_035334](https://github.com/vlang/v/assets/34311583/255883ca-69c1-4625-a30a-5fc6d201f6bd)|![Screenshot_20240606_035502](https://github.com/vlang/v/a …
> v.utils: allow to set names of compared items when diffing strings

- vlib/os/font/font.v
The PR will change default font to "segoeui.ttf" on Windows. To support legacy Windows versions, it will use Arial font when "segoeui.ttf" is not exist.
It's important to make UI consistent between system and V applications.
> Use "segoeui.ttf" font if exist on Windows

- vlib/builtin/js/jsfns.js.v
- vlib/builtin/js/string.js.v
- vlib/builtin/js/string_test.js.v
Implement `string.split_any` for the JS backend.
This PR fixes #21440.
> builtin,js: implement JS `string.split_any`

- vlib/time/README.md
- vlib/time/time_test.v
- vlib/v/checker/checker.v
- vlib/v/checker/struct.v
- vlib/v/checker/tests/struct_field_private_err.out
- vlib/vweb/assets/assets.v
- vlib/x/json2/count_test.v
- vlib/x/json2/decoder2/tests/decode_struct_test.v
- vlib/x/json2/tests/decode_struct_test.v
- vlib/x/json2/tests/encode_struct_test.v
- vlib/x/json2/tests/encode_struct_todo_test.vv
> [!IMPORTANT]
> Merge **AFTER 2024-05-31**
> checker: turn warnings for private fields into errors (AFTER 2024-05-31)

- vlib/v/checker/checker.v
- vlib/v/checker/for.v
- vlib/v/checker/tests/labelled_break_continue.out
- vlib/v/tests/nested_fors_with_labels_test.v
Adds support for:
```v
abc: for x in 0..5 {
def: for y in 0..5 {
if y > 3 {
continue abc
}
println('> x: $x | y: ${y}')
}
}
```
> checker: support nested labeled for statements

- vlib/v/pref/pref.v
Fixes a regression where it's not possible to run some V commands with flags anymore after #21391. For example, if there is directory with the same name as the command, like having a `fmt` directory in the in the cwd and trying to run v fmt -diff file.v.
```sh
❯ v fmt -diff file.v
Unknown argument `-diff` for command `fmt`
```
> pref: fix regression of command flags not working

- vlib/builtin/string.v
- vlib/builtin/string_test.v
`find_between` returns the string found between start string and end string.
When `end` string not found, should return '', not the rest of string.
> builtin: fix string.find_between(), when not found end string return ''

- vlib/v/gen/c/spawn_and_go.v
- vlib/v/tests/spawn_with_cond_fncall_test.v
> cgen: fix spawn code generated when calling conditional function

- vlib/v/checker/fn.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/generic_comptime_arg_test.v
> cgen: fix comptime generic arg resolution

- vlib/builtin/string.v
- vlib/builtin/string_test.v
`camel_to_snake` convert string from camelCase to snake_case
`snake_to_camel` convert string from snake_case to camelCase
> builtin.string: add CamelCase to/from snake_case

- vlib/veb/veb.v
- vlib/vweb/vweb.v
- vlib/x/vweb/vweb.v
Adds the `M3U8 application/vnd.apple.mpegurl` for HLS video to vweb.
[See this wikipedia page for more info](https://en.wikipedia.org/wiki/M3U#Internet_media_types)
> vweb, veb, x.vweb: Add m3u8 MIME type

- vlib/builtin/string.v
- vlib/builtin/string_test.v
The PR improves the performance of the method by removing the `i > 0 and i > 1` checks from the loop.
> builtin: improve camel_to_snake

- vlib/v/gen/c/dumpexpr.v
- vlib/v/slow_tests/inout/dump_array_of_ref.out
- vlib/v/slow_tests/inout/dump_array_of_ref.vv
This PR fix dumping array of reference (fix #21690).
- Fix dumping array of reference.
- Add test.
```v
struct Balise {
a int
}
fn escape_tag(mut parents []Balise) {
dump(parents)
mut stack := []&Balise{}
stack << &Balise{10}
stack << &Balise{20}
dump(stack)
}
fn main() {
mut bal := [Balise{11}, Balise{22}]
escape_tag(mut bal)
}
[.\\tt1.v:6] parents: &[Balise{
a: 11
}, Balise{
a: 22
}]
[.\\tt1.v:10] stack: [&Balise{
a: 10
}, &Balise{
a: 20
}]
```
> cgen: fix dumping array of reference (fix #21690)

- vlib/v/checker/match.v
- vlib/v/tests/match_expr_with_auto_promote_number_test.v
This PR fix match expr with auto promote number (fix #21624).
- Fix match expr with auto promote number.
- Add test.
```v
// convert strings like 10K to i164
const block = 512
// const block = i64(512)
// **1
const kilo = i64(1024)
const kilobyte = i64(1000)
// **2
const mega = kilo * kilo
const megabyte = kilobyte * kilobyte
// **3
const giga = mega * kilo
const gigabyte = megabyte * kilobyte
// **4
const terra = giga * kilo
const terrabyte = gigabyte * kilobyte
// **5
const peta = mega * kilo
const petabyte = megabyte * kilobyte
// **6
const exa = peta * kilo
const exabyte = peta * kilo
// **7
const zetta = exa * kilo
const zettabyte = exabyte * kilobyte
// **8
const yotta = zetta * kilo
const yottabyte = zettabyte * kilobyte
// **9
const ronna = yotta * kilo
const ronnabyte = yottabyte …
```
> checker: fix match expr with auto promote number (fix #21624)

- vlib/orm/README.md
While working on my project I found that time.Time has non-obvious behavior when creating tables in the ORM. Some additional specificity regarding passing the structs as the table was appreciated, and so the expression examples have been updated to be more explicit about this.
Some wording was updated as well to make concepts more obvious.
This PR only updates the README file in `vlib/orm`, so no tests are necessary.
> orm: update readme with more specifics

- vlib/v/ast/str.v
- vlib/v/checker/infix.v
- vlib/v/parser/fn.v
- vlib/v/tests/sorting_compare_fn_with_mut_reference_test.v
This PR fix sorting compare fn with mut reference parameter (fix #21662).
- Fix sorting compare fn with mut reference parameter.
- Add test.
```v
struct Thing {
mut:
a  int = 2
b  int = 4
av int
}
fn (mut t Thing) average() int {
t.av = (t.a + t.b) / 2
return t.av
}
struct Things {
mut:
items []&Thing
}
fn (mut t Things) sort() {
t.items.sort_with_compare(fn (mut a &Thing, mut b &Thing) int {
if a.average() > b.average() {
return 1
} else if a.average() < b.average() {
return -1
}
return 0
})
}
fn main() {
mut t := Things{}
t.items << &Thing{2, 4, 0}
t.items << &Thing{5, 7, 0}
t.items << &Thing{1, 2, 0}
t.sort()
println(t)
assert t.items.len == 3
assert t.items[0] == &Thing{1, 2, 1}
assert t.items[1] == &Thing{2, 4, 3}
assert t.items[2] == &Thing{5, 7, 6}
} …
```
> parser, checker: fix sorting compare fn with mut reference parameter (fix #21662)

- vlib/v/fmt/tests/fn_with_mut_ref_params_keep.vv
- vlib/v/tests/in_expression_test.v
This PR add fn_with_mut_ref_params_keep.vv (related #21706).
- fn_with_mut_ref_params_keep.vv
```v
struct Bar {}
fn in_both_mut_ref(mut arr []&Bar, mut bar &Bar) {
assert bar !in arr
}
fn main() {
mut arr := []&Bar{}
mut bar := Bar{}
in_both_mut_ref(mut &arr, mut &bar)
}
```
> fmt: add fn_with_mut_ref_params_keep.vv (related #21706)

- vlib/v/ast/ast.v
- vlib/v/checker/assign.v
- vlib/v/checker/fn.v
- vlib/v/comptime/comptimeinfo.v
- vlib/v/gen/c/assign.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/for.v
- vlib/v/gen/c/str_intp.v
- vlib/v/tests/generic_return_test.v
> cgen, checker: fix generic variable resolution on generic func return assignment

- vlib/v/checker/checker.v
- vlib/v/checker/comptime.v
- vlib/v/checker/fn.v
- vlib/v/checker/if.v
- vlib/v/checker/infix.v
- vlib/v/checker/match.v
- vlib/v/checker/orm.v
- vlib/v/tests/result_call_or_block_with_stmts_test.v
This PR fix result call or_block with multi-statements (fix #21504).
- Fix result call or_block with multi-statements.
- Add test.
```v
fn str_ret_fn(str string) string {
return str
}
fn foo(str string) !string {
if str.contains('foo') {
return str
}
return error('error')
}
fn main() {
var := foo('bar') or {
foo_var := str_ret_fn('foo')
if foo_var == 'foo' {
foo(foo_var) or {
eprintln(err)
exit(1)
}
} else {
eprintln(err)
exit(1)
}
}
println(var)
assert var == 'foo'
}
foo
```
> checker: fix result call or_block with multi-statements (fix #21504)

- vlib/v/gen/c/fn.v
- vlib/v/tests/fn_call_mut_ref_args_test.v
- vlib/v/tests/in_expression_test.v
This PR fix fn call with mut reference args (fix #21265).
- Fix fn call with mut reference args.
- Add test.
```v
@[heap]
struct Client {
mut:
next &Client = unsafe { nil }
prev &Client = unsafe { nil }
}
fn init_vm1(mut head &Client) {
for c := head; c; c = c.next {
}
}
fn init_vm2(mut head &Client) {
for c := head; c == unsafe { nil }; c = c.next {
}
}
fn main() {
mut head := &Client{}
init_vm1(mut head)
init_vm2(mut head)
assert true
}
```
> cgen: fix fn call with mut reference args (fix #21265)

- vlib/v/checker/if.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/deref_mut_variable_in_if_expr_test.v
This PR fix auto dereference mut variable in if expr (fix #21309).
- Fix auto dereference mut variable in if expr.
- Add test.
```v
struct Foo {
str string
}
fn (mut f Foo) foo(f2 Foo) string {
return (if f.str != '' {
f
} else {
f2
}).str
}
fn main() {
mut foo := Foo{}
dump(foo.foo(Foo{ str: 'a' }))
assert foo.foo(Foo{ str: 'a' }) == 'a'
}
[.\\tt1.v:15] foo.foo(main.Foo{....}): a
```
> checker, cgen: fix auto dereference mut variable in if expr (fix #21309)

- vlib/builtin/string.v
- vlib/builtin/string_test.v
Ref.: https://github.com/vlang/v/pull/21691#issuecomment-2184905360
> builtin: fix `snake_to_camel` when passing a `SCREAMING_SNAKE_CASE` string

- vlib/encoding/base32/base32.v
Received the following warning when importing `encoding.base32`
```
v run base32_test.v
/Users/mike/Documents/github/v/vlib/encoding/base32/base32.v:289:13: notice: an implicit clone of the slice was done here
287 |             }
288 |             in0 := src[0]
289 |             src = src[1..]
|                      ~~~~~
290 |             if in0 == enc.padding_char && j >= 2 && src.len < 8 {
291 |                 // We`ve reached the end and there`s padding
Details: /Users/mike/Documents/github/v/vlib/encoding/base32/base32.v:289:13: details: To silence this notice, use either an explicit `a[..].clone()`,
or use an explicit `unsafe{ a[..] }`, if you do not want a copy of the slice.
287 |             }
288 |             in0 := src[0]
289 |             src = src[1..]
| …
```
> encoding.base32: fix warning of implicit clone of array by declaring unsafe

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/infix.v
- vlib/v/tests/sumtype_with_reference_test.v
This PR fix sumtype with reference (fix #21721).
- Fix sumtype with reference.
- Add test.
```v
struct Parse {
mut:
stack []&Element
}
struct Balise {}
struct RawText {
s string
}
type Element = Balise | RawText
fn (mut p Parse) process_open_tag() string {
mut last := &p.stack[0]
if mut last is RawText {
println(last)
return last.s
} else {
return ''
}
}
fn main() {
mut parse := Parse{
stack: [&RawText{'raw'}]
}
assert parse.process_open_tag() == 'raw'
}
RawText{
s: 'raw'
}
```
> cgen: fix sumtype with reference (fix #21721)

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/ctempvars.v
- vlib/v/tests/assert_fn_ret_option_test.v
> cgen: fix assert checking fn option ret with `none`

- vlib/v/checker/checker.v
Make the recursive method ensure_type_exists/2 a bit more robust, by terminating early, when the recursion depth exceeds a hard limit of 40 levels.
Without it, an unlimited recursion (which may be caused by various factors) will lead to a stack overflow, which can be harder to diagnose, than an explicit checker error message.
> checker: limit recursion in Checker.ensure_type_exists/2 to 40 levels (it is usually 4 or less)

- vlib/net/http/response.v
The `status()` method comment states it returns a Status struct. This is incorrect. It in fact returns a field of the `Status` enum. I have updated the comment to reflect this and used wording to be consistent with https://github.com/vlang/v/blob/8466c6c03d77ae623ffc023272aacaa569c942ae/vlib/net/http/status.v#L79 .
> net: Corrected `status()` method comment to indicate return of `Status` enum field instead of struct.

- examples/compiletime/d_compile_value.v
This PR adds an example that use `-d ident=value` and `$d('ident', value)` in various ways.
> examples: add `compiletime/d_compile_value.v`

- vlib/v/ast/table.v
- vlib/v/gen/c/struct.v
- vlib/v/tests/generics_map_with_reference_arg_test.v
This PR fix generics map with the reference argument (fix #21651).
- Fix generics map with the reference argument.
- Add test.
```v
import time
struct Entry[V] {
mut:
value     V
load_time u32
}
struct Lru[T, V] {
mut:
m      map[T]Entry[V]
list   datatypes.DoublyLinkedList[T]
cap    u32 = 1000
ttl    u32 = 3
on_del ?fn (T, V)
pub mut:
hits u32
miss u32
}
pub fn new[T, V](cap u32, ttl u32) &Lru[T, V] {
return &Lru[T, V]{
cap: cap
ttl: ttl
}
}
pub fn (mut l Lru[T, V]) set_on_del(on_del fn (T, V)) {
l.on_del = on_del
}
pub fn (mut l Lru[T, V]) add(k T, v V) {
if l.m.len >= (l.cap * 97 / 100) {
l.remove_expired(0)
for l.m.len > (l.cap * 90 / 100) {
l.del(l.list.pop_back() or { return })
}
}
l.m[k] = Entry[V]{v, u32(time.now().unix())}
l.list.push_front(k)
}
pub fn (mut l …
```
> ast, cgen: fix generics map with the reference argument (fix #21651)

- vlib/builtin/string.v
- vlib/builtin/string_test.v
Ref.: https://github.com/vlang/v/pull/21722#issuecomment-2190443321
> builtin: fix `assert '_ISspace'.camel_to_snake() == '_i_sspace'`

- vlib/v/checker/struct.v
- vlib/v/checker/tests/struct_field_fixed_size_init_with_d_as_size_err.out
- vlib/v/checker/tests/struct_field_fixed_size_init_with_d_as_size_err.vv
Add this:
```
vlib/v/checker/tests/struct_field_fixed_size_init_with_d_as_size_err.vv:3:31: error: cannot initialize a fixed size array field that uses `$d()` as size quantifier since the size may change via -d
1 | struct Gin {
2 | mut:
3 |     juice [$d('amount', 4)]int = [1, 2, 3, 4]!
|                                  ~~~~~~~~~~~~~
4 | }
5 |
```
for this code:
```v
struct Gin {
mut:
juice [$d('amount', 4)]int = [1, 2, 3, 4]!
}
fn main() {}
```
> checker: add error for `field [$d('x', 2)]int = [1, 2]!`

- vlib/v/gen/c/infix.v
- vlib/v/tests/infix_expr_and_or_operate_unnecessary_eval_test.v
This PR fix infix expr and/or operate unnecessary evaluate (fix #21590).
- Fix infix expr and/or operate unnecessary evaluate.
- Add test.
```v
fn f(s string) !int {
if s == '' {
return error('invalid s')
}
return s.len
}
fn main() {
v := ''
x := v != 'xyz' || f(v)! < f('abc')!
dump(x)
assert x
y := v == 'xyz' && f(v)! < f('abc')!
dump(y)
assert !y
}
[.\\tt1.v:11] x: true
[.\\tt1.v:15] y: false
```
> cgen: fix infix expr and/or operate unnecessary evaluate (fix #21590)

- vlib/v/gen/c/if.v
- vlib/v/gen/c/infix.v
This PR simplify in infix_expr_and_or_op() and cleanup in need_tmp_var_in_expr() (related #21740).
- It can now handle all situations that require the use of temporary variable.
> cgen: simplify in infix_expr_and_or_op() (related #21740)

- vlib/v/gen/c/fn.v
- vlib/v/tests/reference_variable_str_test.v
This PR fix reference variable str() method call (fix #19430).
- Fix reference variable str() method call.
- Add test.
```v
@[heap]
struct Foo {
bar string = 'bar'
baz string = 'baz'
}
fn (foo Foo) str() string {
return 'bar: ${foo.bar}, baz: ${foo.baz}'
}
fn main() {
mut many_foos := []&Foo{len: 3, init: &Foo{}}
println(many_foos.map(it.str()).join('\n'))
println(many_foos)
assert many_foos.map(it.str()) == ['&bar: bar, baz: baz', '&bar: bar, baz: baz',
'&bar: bar, baz: baz']
}
&bar: bar, baz: baz
&bar: bar, baz: baz
&bar: bar, baz: baz
[&bar: bar, baz: baz, &bar: bar, baz: baz, &bar: bar, baz: baz]
```
> cgen: fix reference variable str() method call (fix #19430)

- vlib/crypto/blowfish/block.v
> crypto.blowfish: apply `@[direct_array_access]` to very commonly used functions

- vlib/v/checker/fn.v
- vlib/v/tests/nested_if_expr_method_call_test.v
This PR fix nested if expr method call (fix #20976).
- Fix nested if expr method call.
- Add test.
```v
fn main() {
str_from_nested_exp1 := if true {
if true { 'foo.bar' } else { 'foo.bar.baz' }.all_after('foo.')
} else {
'foo'
}
println(str_from_nested_exp1)
assert str_from_nested_exp1 == 'bar'
str_from_nested_exp2 := if true {
(if true { 'foo.bar' } else { 'foo.bar.baz' }).all_after('foo.')
} else {
'foo'
}
println(str_from_nested_exp2)
assert str_from_nested_exp2 == 'bar'
str_from_nested_exp3 := if true {
'foo'
} else {
if true { 'foo.bar' } else { 'foo.bar.baz' }.all_after('foo.')
}
println(str_from_nested_exp3)
assert str_from_nested_exp3 == 'foo'
str_from_nested_exp4 := if true {
'foo'
} else {
(if true { 'foo.bar' } else { 'foo.bar.baz' }).all_after('foo.')
} …
```
> checker: fix nested if expr method call (fix #20976)

- vlib/v/debug/tests/or_expr_scope.expect
- vlib/v/debug/tests/or_expr_scope.vv
- vlib/v/gen/c/assign.v
- vlib/v/gen/c/cgen.v
Fix #21772
```v
fn r() !bool {
return error('fail')
}
fn main() {
a := r() or {
$dbg
false
}
}
```
> dbg: fix scope command when breakpoint is on or-expr

- vlib/v/checker/checker.v
- vlib/v/checker/struct.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/for.v
- vlib/v/tests/alias_fixed_arr_test.v
> cgen: allow alias to array fixed to be initialized like `[n]int{}`

- cmd/tools/vast/vast.v
- vlib/v/ast/ast.v
- vlib/v/ast/str.v
- vlib/v/fmt/tests/donut_card_expected.vv
- vlib/v/fmt/tests/expressions_expected.vv
- vlib/v/parser/fn.v
- **fmt: preserve manual line breaks in fn parameters, with no auto wrapping**
- **small cleanup (remove unused wrapping parameter in stringify_fn_after_name)**
> fmt: keep manual newlines after fn parameters in fn declarations, do not auto wrap

- cmd/tools/vrepl.v
- vlib/v/slow_tests/repl/comptime_tmpl.repl
- vlib/v/slow_tests/repl/fn_calls.repl
- vlib/v/slow_tests/repl/import_alias.repl
- vlib/v/slow_tests/repl/method_call.repl
This PR fix method call (fix #21788).
- Fix method call.
- Add test.
```v
____    ____
\    /     |  V 0.4.6 209063f . Use  list  to see the accumulated program so far.
>>> mut values := [1, 2, 3]
>>> values.pop()
>>> values
[1, 2]
```
> vrepl: fix method call (fix #21788)

- vlib/v/gen/c/comptime.v
- vlib/v/tests/comptimecall_slice_arg_test.v
> cgen: fix comptime call argument auto conversion for indexexpr

- examples/snek/snek.v
this PR updates the `snek` example to use interpolated movement (a smoothly animated snake) and an input queue (more responsive input, no dropped keypresses). it also simplifies some of the logic by changing the `Direction` enum to simply use the `Pos` struct (now named `Vec`).
> examples: add interpolated movement and input queue to `snek/snek.v`

- vlib/v/ast/ast.v
- vlib/v/ast/str.v
- vlib/v/parser/fn.v
This PR cleanup in stringify_fn_after_name().
- Remove inline comments.
> ast, parser: cleanup in stringify_fn_after_name()

- cmd/tools/vrepl.v
- vlib/v/slow_tests/repl/comptime_tmpl.repl
- vlib/v/slow_tests/repl/fn_calls.repl
- vlib/v/slow_tests/repl/import_alias.repl
- vlib/v/slow_tests/repl/method_call1.repl
- vlib/v/slow_tests/repl/method_call2.repl
This PR fix output of the fn call (related #21792).
- Fix output of the fn call.
- Add test.
```v
____    ____
\    /     |  V 0.4.6 0c2d72f . Use  list  to see the accumulated program so far.
>>> mut values := [1, 2, 3]
>>> values.pop()
3
>>> values
[1, 2]
>>>
```
```v
____    ____
\   \/   /   |  Note: the …
```
> vrepl: fix output of the fn call (related #21792)

- cmd/tools/vrepl.v
- vlib/v/slow_tests/repl/var_starts_with_print.repl
This PR fix variable name starts with `print` (fix #13981).
- Fix variable name starts with `print`.
- Add test.
```v
____    ____
\    /     |  V 0.4.6 a67bfeb . Use  list  to see the accumulated program so far.
>>> a_variable := 'yessir'
>>> a_variable
yessir
>>> printme := 'ohno'
>>> printme
ohno
>>> 
```
> vrepl: fix variable name starts with `print` (fix #13981)

- cmd/tools/vdoc/highlight.v
- cmd/tools/vdoc/html.v
- vlib/v/parser/for.v
- vlib/v/parser/parser.v
- vlib/v/token/token.v
This PR make token.is_assign() contain .decl_assign.
- Make `token.is_assign()` contain `.decl_assign`.
- Modify related calls.
> token: make is_assign() contain .decl_assign

- cmd/tools/vrepl.v
- vlib/v/slow_tests/repl/input.repl
This PR fix os.input() in vrepl tools (fix #5678).
- Fix os.input() in vrepl tool.
- Add test.
```v
____    ____
\    /     |  V 0.4.6 4475759 . Use  list  to see the accumulated program so far.
>>> mut s := os.input('aaa> ')
aaa> hello
>>> s
hello
>>> s = os.input('bbb> ')
bbb> world
>>> s
world
>>>
```
> vrepl: fix os.input() (fix #5678)

- vlib/v/pref/pref_test.v
When testing with VFLAGS='-cc gcc' I ran in to a similar problem that happened when I was testing with VFLAGS='-cc clang'.
The particular problem I am seeing is:
```
$ echo $VFLAGS
-cc gcc
$ v test vlib/v/pref/pref_test.v
---- Testing... ---------------------------------------------------------------------------------------
FAIL     0.000 ms vlib/v/pref/pref_test.v
tcc: error: Unknown relocation type for got: 541
```
I had previously put in a test for freebsd and clang.  Now, I am adding a test for freebsd and gcc.
Is it possible to instead test for !tinyc and then use the currently specified compiler from the -cc parameter?  Otherwise, I am reduced to testing for every possible c compiler by name.
> v/pref: handle using gcc on FreeBSD

- examples/vmatrix.v
A fun example of the, "Matrix" screen effect in V.
> examples: add vmatrix.v showing a Matrix like terminal screen effect

- vlib/v/checker/checker.v
- vlib/v/checker/tests/expr_evaluated_but_not_used.out
- vlib/v/checker/tests/expr_evaluated_but_not_used.vv
This PR check expr evaluated but not used (fix #21436).
- Check expr evaluated but not used.
- Add test.
```v
fn main() {
{1, 2, 3, 4}
println('works')
}
tt1.v:2:3: error: expression evaluated but not used
2 |     {1, 2, 3, 4}
|      ^
3 |     println('works')
4 | }
```
> checker: check expr evaluated but not used (fix #21436)

- cmd/tools/vrepl.v
- vlib/v/slow_tests/repl/error_eval_script.repl
This PR fix arbitrary script execute (fix #13981).
- Fix arbitrary script execute.
- Add test.
```v
____    ____
\    /     |  V 0.4.6 df18047 . Use  list  to see the accumulated program so far.
>>> "text") exit(-1)
error: expression evaluated but not used
6 |
7 | "text") exit(-1)
| ~~~~~~
>>>
```
> vrepl: fix arbitrary script execute (fix #13981)

- vlib/v/ast/str.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/option_reference_params_test.v
This PR fix closure variable with optional reference params (fix #21827).
- Fix closure variable with optional reference params.
- Fix fmt of mut optional reference params.
- Add test.
```v
struct Logger {}
fn (l Logger) log(this string) {
println(this)
}
fn new_logger() &Logger {
return &Logger{}
}
fn do_log(mut maybe_logr ?&Logger, this string) {
if logr := maybe_logr {
logr.log(this)
}
}
fn bang(mut logr ?&Logger, this string) {
nested_log := fn [mut logr] (this string) {
do_log(mut logr, this)
}
nested_log(this)
}
fn main() {
mut logr := new_logger()
bang(mut logr, 'bang!')
assert true
}
bang!
```
> ast, cgen: fix closure variable with optional reference params (fix #21827)

- vlib/v/checker/fn.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/generic_receiver_embed_test.v
> cgen, checker: fix wrong receiver generic resolution with embed types

- vlib/builtin/rune.v
- vlib/builtin/utf8.v
- vlib/strings/builder.c.v
- vlib/v/slow_tests/valgrind/buffer_passed_in_fn_that_uses_tos_on_it.v
Will require to pass a buffer arg that is muted as mutable.
The variables that were passed to the updated utf32_ fns were were already declared as mutable, the change makes sure the arg needs to be passed as mutable as well.
> builtin, strings: improve consistency and behavior regarding explicit mutability

- cmd/tools/vrepl.v
- vlib/v/slow_tests/repl/if_expr_oneline.repl
This PR fix one-line if exprssion.
- Fix one-line if exprssion.
- Add test.
before
```v
yuyi@yuyi-PC:~/v$ v
____    ____ 
\   \/   /   |  Note: the REPL is highly experimental. For best V experience, use a text editor, 
\      /    |  save your code in a  main.v  file and execute:  v run main.v 
\    /     |  V 0.4.6 547c056 . Use  list  to see the accumulated program so far.
>>> a := 10
>>> if a > 5 { println('good') } else { println('bad') }
error: the final expression in `if` or `match`, must have a value of a non-void type
7 | a := 10
8 | println(if a > 5 {
9 |  println('good') 
|  ~~~~~~~~~~~~~~~
10 | } …
```
> vrepl: fix one-line if exprssion

- examples/gg/digital_rain.v
This pull request implements the digital rain effect from the movie, "The Matrix", using `gg`. It is not feature complete, but decided getting some feedback was worth starting a pull request. Features needed:
- Window resizing logic
- Start the program in full screen. `gg.toggle_fullscreen()` didn't work for me. Maybe I'm using it wrong
- Keyboard shortcuts to change the rain speed
- Keyboard shortcut to toggle fullscreen
- Other ideas?
I'm OK with merging as is, but I'll likely add these other features in a few days.
> Add digital_rain.v to examples/gg

- examples/gg/digital_rain.v
The movie effect uses its own custom font (according to Wikipedia). By accident, I discovered overprinting with a different char produces chars similar to the movie effect (if you squint sideways 😆).
> digital_rain.v: over print to simulate custom font used in movie effect

- examples/sokol/02_cubes_glsl/cube_glsl.v
- fix bug #21547 for `sokol\02_cubes_glsl` where glsl shader is not running
The new version of sokol seem need an explicit declaration of the sampler to pass ot shader.
Adding the line: `app.cube bind.fs.samplers[C.SLOT_smp] = app.sampler` solve the problem
> sokol: added sampler to the 02_cube code, bugfix: #21547

- cmd/tools/vrepl.v
- vlib/v/slow_tests/repl/error_and_continue_print.repl
- vlib/v/slow_tests/repl/error_exitasdfasdf.repl
- vlib/v/slow_tests/repl/infix_shift_op.repl
This PR fix infix shift operation (fix #13968).
- Fix infix shift operation in vrepl.
- Add test.
```v
____    ____
\    /     |  V 0.4.6 65966ae . Use  list  to see the accumulated program so far.
>>> 4 >> 1
2
>>> 4 << 1
8
>>> println(4 << 1)
8
>>> typeof(4 >> 1).name
int literal
>>> typeof(4 << 1).name
int literal
>>> 
```
> vrepl: fix infix shift operation (fix #13968)

- vlib/v/gen/c/struct.v
- vlib/v/gen/c/testdata/assigning_and_printing_struct_with_optional_field.out
- vlib/v/gen/c/testdata/assigning_and_printing_struct_with_optional_field.vv
> cgen: fix option string struct member init with autofree

- doc/docs.md
- vlib/v/ast/ast.v
- vlib/v/help/build/build-c.txt
Noticed a few places where `@` was missing from `@[export]` attributes in docs/help and one comment.
> docs: add missing @ on export attributes

- examples/flag/animated_help_text.v
- examples/flag/flag_layout_editor.v
- vlib/flag/README.md
- vlib/flag/cmd_exe_style_flags_test.v
- vlib/flag/flag_to.v
- vlib/flag/flag_to_doc_test.v
- vlib/flag/flag_to_misc_test.v
- vlib/flag/gnu_style_flags_test.v
- vlib/flag/go_flag_style_flags_test.v
- vlib/flag/posix_style_flags_test.v
- vlib/flag/v_style_flags_test.v
This PR adds the functionality of https://github.com/larpon/flags to vlib's `flag` module.
Making it possible to map different styles of command line flags/options directly to a V `struct` via reflection.
It can also generate (customizable) "usage" documentation from the `struct`.
I've included two examples - one showing how you can make animated usage/help and one which is a small `WYSIWYG` editor, demoing most of the documentation layout features.
The flag styles supported are:
* POSIX (short and repeatable short) `-v`, `-vvv vv`
* GNU (long) `--long` and `--long=value`
* POSIX/GNU (long+short) in combination
* Go `flag` module style `-l`, `-long`, `-long value` + `--long` and `--long=value`
* V style `-l`, `-long`, `-long value`
* CMD.EXE style `/m`, `/M` or `/Moo` (activated by …
> flag: add `flag.to_struct[T]()!` and `flag.to_doc[T]()!` + tests

- cmd/tools/vrepl.v
- vlib/v/slow_tests/repl/error_and_continue_print.repl
- vlib/v/slow_tests/repl/error_exitasdfasdf.repl
This PR fix error of undefined ident (related #21855).
- Fix error of undefined ident.
- Modify the related tests.
```v
____    ____
\    /     |  V 0.4.6 c2f7afd . Use  list  to see the accumulated program so far.
>>> exitasdfasdf
error: undefined ident: `exitasdfasdf`
6 |
7 | println(exitasdfasdf)
>>> 
```
> vrepl: fix error of undefined ident (related #21855)

- vlib/flag/README.md
- vlib/flag/flag_from_test.v
- vlib/flag/flag_to.v
- vlib/flag/flag_to_misc_test.v
- vlib/flag/gnu_style_flags_test.v
This PR adds the ability to map flags to an *existing* instantiated ("defaults") struct. This makes it possible to map flags in cases where the user [might do exotic things](https://github.com/vlang/vab/blob/48c4093a86f3ee3763296772e697fc076b1307ff/cli/cli.v#L103) or simply needs a bit more flexibility while handling flags
**EDIT** other alternative names, I've thought about, for the function could also be `user_struct`, `use_struct`, `on_struct`, `onto_struct`, `merge_struct`, `via_struct`, `to_default_struct`
`from_struct` might imply that we are generating flags from a struct 🤔 (which may even be desirable to have?! 😬 )
> flag: add `flag.using[T]()!` that uses an existing instance of `T`

- vlib/v/checker/check_types.v
- vlib/v/checker/tests/fn_call_mut_arg_mismatch_err.out
- vlib/v/checker/tests/fn_call_mut_arg_mismatch_err.vv
This PR check mismatch of fn call mut argument (fix #21857).
- Check mismatch of fn call mut argument.
- Add test.
```v
module main
pub struct Expr1 {
name string
}
fn foo(mut expr &Expr1) { // <---- &
println(expr.name)
}
fn main() {
mut expr := Expr1{
name: '123'
}
foo(mut expr)
}
tt1.v:15:10: error: cannot use `Expr1` as `&&Expr1` in argument 1 to `foo`
13 |         name: '123'
14 |     }
15 |     foo(mut expr)
16 | }
```
> checker: check mismatch of fn call mut argument (fix #21857)

- vlib/v/gen/c/fn.v
- vlib/v/tests/fn_mut_arg_of_sumtype_ref_test.v
This PR fix fn mut argument of sumtype reference (fix #21856).
- Fix fn mut argument of sumtype reference.
- Add test.
```v
module main
pub struct Expr1 {}
pub struct Expr2 {}
pub type Expr = Expr1 | Expr2
pub struct Gen {
}
fn (mut g Gen) foo(mut expr &Expr1) string {
return '${expr}'
}
pub fn (mut g Gen) bar(mut expr Expr) string {
return match mut expr {
Expr1 { g.foo(mut &expr) }
Expr2 { '' }
}
}
fn main() {
mut expr := &Expr1{}
mut g := Gen{}
ret := g.bar(mut expr)
println(ret)
assert ret == 'Expr1{}'
}
Expr1{}
```
> cgen: fix fn mut argument of sumtype reference (fix #21856)

- cmd/tools/vrepl.v
- vlib/v/slow_tests/repl/struct_def_later.repl
This PR fix structure definition in vrepl.
- Fix structure definition.
- Add test.
before:
```v
yuyi@yuyi-PC:~/v$ v
____    ____ 
\   \/   /   |  Note: the REPL is highly experimental. For best V experience, use a text editor, 
\      /    |  save your code in a  main.v  file and execute:  v run main.v 
\    /     |  V 0.4.6 615a9a0 . Use  list  to see the accumulated program so far.
>>> mut name := 'foo1'
>>> pub struct Info1 {
... name string
... }
notice: script mode started here
6 | 
7 | mut name := 'foo1'
| ~~~
8 | pub struct Info1 {
9 |
error: all definitions must occur before code in …
```
> vrepl: fix structure definition

- vlib/v/builder/cc.v
- vlib/v/builder/msvc_windows.v
> v.builder: improve the C compilation output on cgen errors

- cmd/tools/vrepl.v
- vlib/v/slow_tests/repl/enum.repl
- vlib/v/slow_tests/repl/interface.repl
This PR fix enum and interface declarations in vrepl.
- Fix enum and interface declarations.
- Add tests.
```v
____    ____
\    /     |  V 0.4.6 adb85e0 . Use  list  to see the accumulated program so far.
>>> mut age := 22
>>> enum Info {
... young
... old
... }
>>> fn get_info(age int) Info {
... if age < 25 {
... return .young
... } else {
... return .old
... }
... }
>>> get_info(age)
young
>>> age = 45
>>> …
```
> vrepl: fix enum and interface declarations

- cmd/tools/vrepl.v
- vlib/v/slow_tests/repl/const.repl
This PR fix const declaration and single line struct/enum/interface.
- Fix const declaration and single line struct/enum/interface.
- Add test.
```v
____    ____
\    /     |  V 0.4.6 e9652f8 . Use  list  to see the accumulated program so far.
>>> mut a := [1, 2]
>>> pub const b = 3
>>> a << b
>>> a
[1, 2, 3]
>>> 
```
> vrepl: fix const declaration and single line struct/enum/interface

- examples/flag/flag_layout_editor.v
- vlib/flag/flag_to.v
This adds an option to let the flag output be compact, which resembles how the `FlagParser` renders it's flags.
Compact mode `false` (default):
Compact mode `true`:
> flag, examples: add `compact` to `flag.DocOptions`

- cmd/tools/vrepl.v
- vlib/v/slow_tests/repl/type_decl.repl
This PR fix type declaration in vrepl.
- Fix type declaration in vrepl.
- Add test.
- Optimize with starts_with_type_decl().
```v
____    ____
\    /     |  V 0.4.6 6d3a2ac . Use  list  to see the accumulated program so far.
>>> mut a := 22
>>> pub         type Int = int
>>> b := Int(a)
>>> b
22
>>> 
```
> vrepl: fix type declaration

- vlib/v/gen/c/fn.v
- vlib/v/tests/closure_option_direct_call_test.v
This PR fix optional closure direct call (fix #21165).
- Fix optional closure direct call.
- Add test.
```v
fn main() {
tmp_wd := 'aaa'
b := fn [tmp_wd] () !string {
return tmp_wd
}() or { panic(err) }
println(b)
assert b == 'aaa'
}
aaa
```
> cgen: fix optional closure direct call (fix #21165)

- cmd/tools/vrepl.v
- vlib/v/slow_tests/repl/error_single_line_fn_decl.repl
This PR fix handling of single-line type declaration syntax errors.
- Fix handling of single-line type declaration syntax errors.
- Add a test.
```v
____    ____
\    /     |  V 0.4.6 a7db095 . Use  list  to see the accumulated program so far.
>>> mut a := [1, 2]
>>> fn foo[int](a int) { print('hello') }
error: generic parameter needs to be uppercase
6 |
7 | fn foo[int](a int) {
|        ~~~
8 | …
```
> vrepl: fix handling of single-line type declaration syntax errors

- vlib/flag/flag_to.v
- vlib/flag/flag_to_doc_test.v
This PR fixes a subtle rendering bug in `flag.to_doc[T](...)`, as well as making the logic for how/when new lines are added more clean and readable.
Examples of the bug:
> flag: fix rendering bug, make newline logic/code more readable and clean

- vlib/v/checker/fn.v
- vlib/v/checker/tests/unsafe_generic_call_test.out
- vlib/v/checker/tests/unsafe_generic_call_test.vv
> cgen: fix wrong missing unsafe block checking when calling generic functions with @[unsafe] attr

- vlib/v/checker/tests/typeof_comptime_test.out
- vlib/v/checker/tests/typeof_comptime_test.vv
- vlib/v/comptime/comptimeinfo.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/comptime.v
This PR makes possible to read the type name from comptime for loop vars.
```v
type SumType = int | string
struct Test {
a int
b string
}
fn get_as_sumtype[T,R](struct_ T, name string, typname string) R {
$for f2 in T.fields {
println('field> ${f2.typ} ${typeof(f2.typ).name}')
if f2.name == name {
val := struct_.$(f2.name)
$for f in R.variants {
println('variant> ${f.typ} ${typeof(f.typ).name}')
if typeof(f.typ).name == typname {
return R(val)
}
}
}
}
return R{}
}
fn main() {
println(get_as_sumtype[Test,SumType](Test{a: 123}, 'a', 'int'))
println(get_as_sumtype[Test,SumType](Test{b: 'foo'}, 'b', 'string'))
}
```
> checker,cgen: fix typeof(var.typ) with comptime $for variables

- vlib/v/checker/checker.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/buitlin_fn_var_test.v
> cgen,checker: fix builtin fn var resolve

- cmd/tools/vrepl.v
- vlib/v/slow_tests/repl/error_multi_line_fn_decl.repl
This PR fix handling of multi-line type declaration syntax errors.
- Fix handling of multi-line type declaration syntax errors.
- Add test.
```v
____    ____
\    /     |  V 0.4.6 5486f0b . Use  list  to see the accumulated program so far.
>>> mut a := 22
>>> fn test() {
... aaa
... }
error: `aaa` evaluated but not used
7 | fn test() {
8 |
9 | aaa
| ~~~
10 |
11 | }
>>> fn print_info(a int) {
... println('${a}')
... }
>>> …
```
> vrepl: fix handling of multi-line type declaration syntax errors

- vlib/v/checker/fn.v
- vlib/v/checker/tests/spawn_wrong_fn_err.out
- vlib/v/checker/tests/spawn_wrong_fn_err.vv
Fix #21905
This PR makes `undefined function` error as fatal.
> checker: fix spawn when calling undefined function

- vlib/v/parser/parser.v
- vlib/v/tests/fullname_enumval_as_arg_test.v
> parser: fix enumval not recognized on fn args

- vlib/net/conv/conv.v
- vlib/net/conv/conv_test.v
[Feature Request](https://github.com/vlang/v/labels/Feature%20Request) #21915 
reverse_bytes_u64/reverse_bytes_u32/reverse_bytes_u16 reverse a u64/u32/u16's byte order
```v
assert 0x12345678ABCDEF00 == conv.reverse_bytes_u64(0x00EFCDAB78563412)
assert 0x12345678 == conv.reverse_bytes_u32(0x78563412)
assert 0x1234 == conv.reverse_bytes_u16(0x3412)
```
> net.conv: add conv.reverse_bytes_u64/u32/u16

- vlib/v/gen/c/cgen.v
- vlib/v/tests/enum_with_const_test.v
This PR fix enum field with const value (fix #21916).
- Fix enum field with const value.
- Add test.
```v
enum Foo {
a = c
b = 1
c = 2
}
const c = 0
fn main() {
mut foo := Foo.c
foo = .a
ret := match foo {
.a { 'a' }
.b { 'b' }
.c { 'c' }
}
println(ret)
assert ret == 'a'
}
a
```
> cgen: fix enum field with const value (fix #21916) 

- vlib/v/checker/checker.v
- vlib/v/checker/tests/enum_field_value_duplicate_d.out
- vlib/v/checker/tests/enum_field_value_duplicate_d.vv
This PR check enum field value duplicate (fix #21911).
- Check enum field value duplicate.
- Add test.
```v
const one = 1
enum MyEnum {
a = one
b
c = one
}
fn main() {
$for val in MyEnum.values {
println('> name: ${val.name} | value: ${val.value}')
}
}
tt1.v:6:6: error: enum value `1` already exists
4 |     a = one
5 |     b
6 |     c = one
|         ~~~
7 | }
8 |
```
> checker: check enum field value duplicate (fix #21911)

- vlib/v/checker/checker.v
- vlib/v/checker/tests/enum_field_value_duplicate_e.out
- vlib/v/checker/tests/enum_field_value_duplicate_e.vv
This PR check enum field value duplicate 2.
- Check enum field value duplicate 2.
- Add test.
```v
enum MyEnum {
a = one
b
c = one
}
const one = 1 + 1
fn main() {
$for val in MyEnum.values {
println('> name: ${val.name} | value: ${val.value}')
}
}
tt1.v:4:6: error: enum value `2` already exists
2 |     a = one
3 |     b
4 |     c = one
|         ~~~
5 | }
6 |
```
> checker: check enum field value duplicate 2

- vlib/readline/readline_nix.c.v
This PR fix s := read_line('Message\nName:') on unix/linux (fix #20563).
```v
import readline { read_line }
fn main() {
s := read_line('Prompt Message\n')!
print('${s} \n')
}
yuyi@yuyi-PC:~/test/t1$ v run .
Prompt Message
aaaaaaaaaaaaa
aaaaaaaaaaaaa 
```
```v
import readline { read_line }
fn main() {
s := read_line('Prompt Message\nName:')!
print('${s} \n')
}
yuyi@yuyi-PC:~/test/t1$ v run .
Prompt Message
Name:bbbbbbbbbbb
bbbbbbbbbbb 
```
> readline: fix s := read_line('Message\nName:') on unix/linux (fix #20563)

- vlib/v/scanner/scanner.v
- vlib/v/util/scanning.v
This has only the lookup changes from https://github.com/vlang/v/pull/21545 .
The substr_unsafe commit, turned out to be a problem.
- **v.scanner: use precomputed character tables instead of checks**
- **v.scanner: use util.func_char_table in Scanner.ident_name/0**
- **v.scanner: restore the checks in ident_name, instead of using util.func_char_table**
- **v.scanner: split long condition in ident_name into several smaller ones**
- **v.scanner: use substr_unsafe in Scanner.ident_name/0 and Scanner.num_lit/2**
- **Revert "v.scanner: use substr_unsafe in Scanner.ident_name/0 and Scanner.num_lit/2"**
- **v.scanner: move non_whitespace_table to v.util**
- **v.scanner: use util.func_char_table[c] and util.name_char_table[c] directly**
- **v.util: cleanup the table generating functions, by using …
> v.scanner: use table lookups for very frequently done character checks

- vlib/encoding/base58/base58.v
```
/opt/v/vlib/encoding/base58/base58.v:90:12: notice: an implicit clone of the slice was done here
88 | 
89 |     // now encode the values with actual alphabet in-place
90 |     val := out[i - zcount..]
|               ~~~~~~~~~~~~~~
91 |     sz = val.len
92 |     for i = 0; i < sz; i++ {
Details: /opt/v/vlib/encoding/base58/base58.v:90:12: details: To silence this notice, use either an explicit `a[..].clone()`,
or use an explicit `unsafe{ a[..] }`, if you do not want a copy of the slice.
88 | 
89 |     // now encode the values with actual alphabet in-place
90 |     val := out[i - zcount..]
|               ~~~~~~~~~~~~~~
91 |     sz = val.len
92 |     for i = 0; i < sz; i++ {
```
> encoding.base58: fix notice for slice creation

- vlib/v/checker/tests/wrong_arr_field_err.out
- vlib/v/checker/tests/wrong_arr_field_err.vv
- vlib/v/parser/containers.v
```v
bug.v:1:34: error: wrong field `init1`, expecting `len`, `cap`, or `init`
1 | arr := []int{len: 100, cap: 200, init1: index * 3}
|                                  ~~~~~
2 | println(arr)
```
> checker: fix wrong error message for invalid array attr key

- vlib/v/checker/check_types.v
- vlib/v/checker/tests/voidptr_arg_err.out
- vlib/v/checker/tests/voidptr_arg_err.vv
Fix #17787
This PR blocks voidptr to be passed to non-allowable ptr type.
> checker: fix voidptr type checking 

- vlib/builtin/string.v
- vlib/builtin/string_test.v
This PR fix 'aaaa'.split('aa') (fix #21936).
- Fix 'aaaa'.split('aa').
- Add test.
```v
fn main() {
println('aaaa'.split('aa'))
}
['', '', '']
```
> builtin: fix 'aaaa'.split('aa') (fix #21936)

- vlib/builtin/array.v
- vlib/builtin/array_d_gcboehm_opt.v
- vlib/builtin/int.v
This PR limits dynamic array capacity growth to max_int , and makes sure that a panic happens if that needs to be exceeded, instead of silently overflowing the .cap field (thus breaking the invariant about .len <= .cap).
It is a temporary workaround for #21918 , providing a better experience (allows for growing/processing till the actual limit, and a panic with a stacktrace, when the limit is reached, for improved debugging), until V transitions to using 64 bit numbers for the .len and .cap array fields.
> builtin: panic on trying to grow arrays with capacity bigger than 2^31, instead of overflowing a.cap (partial fix for #21918)

- vlib/v/checker/struct.v
- vlib/v/checker/tests/struct_field_mismatch_ref_err.out
- vlib/v/checker/tests/struct_field_mismatch_ref_err.vv
Fix #18088
```v
bug.v:6:26: error: field is not reference but default value is reference
4 | struct SafeCounter {
5 | mut:
6 |     mt sync.Mutex = sync.new_mutex()
|                          ~~~~~~~~~~~
7 | pub mut:
8 |     value map[string]int
```
> checker: fix missing struct field type checking for type mismatch (ref vs non-ref)

- vlib/v/checker/check_types.v
- vlib/v/tests/voidptr_sumtype_test.v
Allow passing voidptr to sumtype.
```v
type MySum = string | voidptr
type Alias = voidptr
fn t(a MySum) MySum {
return dump(a)
}
a := 'foo'
assert t(a) == MySum('foo')
b := voidptr(0x100)
assert t(b) == MySum(voidptr(0x100))
}
```
> checker: fix sumtype checking for voidptr variant

- vlib/regex/regex_test.v
- vlib/regex/regex_util.v
This PR fix regex.split() (fix #16876).
- Fix regex.split().
- Add test.
```v
import regex
fn main() {
mut r := regex.regex_opt('-') or { panic(err) }
println(r.split('a-'))
println('a-'.split('-'))
println(r.split('-a'))
println('-a'.split('-'))
}
['a', '']
['a', '']
['', 'a']
['', 'a']
```
> regex: fix regex.split() (fix #16876)

- examples/vweb/veb_example.v
- vlib/v/ast/ast.v
- vlib/v/fmt/fmt.v
- vlib/v/parser/comptime.v
- vlib/v/parser/tests/comptime_veb_without_import_veb_err.out
- vlib/v/parser/tests/comptime_veb_without_import_veb_err.vv
- vlib/v/parser/tests/comptime_vweb_without_import_vweb_err.out
- vlib/v/parser/tests/comptime_vweb_without_import_vweb_err.vv
This PR check using comptime veb/vweb without import veb/vweb.
- Check using comptime veb/vweb without import veb/vweb.
- Add test.
```v
fn main() {
$veb.html('index.html')
}
tt1.v:2:2: error: `$veb` cannot be used without import veb
2 |     $veb.html('index.html')
|     ~~~~
3 | }
```
```v
fn main() {
$vweb.html('index.html')
}
tt1.v:2:2: error: `$vweb` cannot be used without import vweb
2 |     $vweb.html('index.html')
|     ~~~~~
3 | }
```
> parser: check using comptime veb/vweb without import veb/vweb

- vlib/x/crypto/chacha20/chacha.v
Addresses #21967 
The cipher struct should be public so it can be included in user-defined data structures.
> x.crypto.chacha20: make Cipher struct public

- doc/docs.md
This PR aims to improve the C interop documentation by providing explanations about some not entirely obvious details for the V implementation and how it currently interacts with the used C backend compiler.
> docs: add more C interop notes and examples

- vlib/crypto/cipher/aes_ctr_test.v
- vlib/crypto/cipher/cfb.v
- vlib/crypto/cipher/cfb_test.v
- vlib/crypto/cipher/cipher.v
- vlib/crypto/cipher/ctr.v
- vlib/crypto/cipher/ctr_test.v
- vlib/crypto/cipher/des_ctr_test.v
- vlib/crypto/cipher/ofb.v
- vlib/crypto/cipher/ofb_test.v
- vlib/crypto/rc4/rc4.v
- vlib/crypto/rc4/rc4_test.v
- vlib/x/crypto/chacha20/chacha_test.v
Addresses #21973 
This may impact stream ciphers that implement xor_key_stream with immutable implementers, and may therefore be breaking.
Further checks should be made so that all stream ciphers implement xor_key_stream correctly, tests are missing for this scenario in all stream cipher implementations.
I am not sure how to perform such tests, help is needed to add such tests.
> crypto.cipher: make Stream.xor_key_stream implementers require a mutable receiver

- cmd/tools/vtest-all.v
Commit faea2d9 contained a short and quick typo fix, but without tests.
This adds tests too, so that `v test-all` can check that `-d trace_http_request` and `-d trace_http_response` will continue to work in the future.
> tools: add short tests in `v test-all` to ensure that `-d trace_http_request` and `-d trace_http_response` compile and work

- examples/gg/rotating_textured_quad.v
This PR makes the `examples/gg//rotating_textured_quad.v` able to compile and run on Android via `vab`.
The example is currently not rendering the image for reasons I have been unable to pin-point.
I decided to not spend anymore time on it now - but still thought the changes was an improvement.
On my physical device the example looks like the attached image.
(I've tried rendering the image it with `window.ctx.draw_image_with_config(...)` which produced correct output but I can not pin-point exactly why the current code does not render on my device :shrug: )
> examples: make `rotating_textured_quad.v` compile and run on Android

- vlib/crypto/md5/md5_test.v
- vlib/crypto/sha1/sha1_test.v
- vlib/crypto/sha256/sha256_test.v
- vlib/crypto/sha512/sha512_test.v
- vlib/hash/hash.v
Inferface `hash.Hash` is made public, this allows users to use it.
Tests are added to md5, sha1, sha256 and sha512 to ensure each Digest struct implements the hash.Hash interface
> Make hash.Hash public and add tests to implementers

- thirdparty/libgc/gc.c
- thirdparty/libgc/include/gc.h
- thirdparty/libgc/include/gc/gc.h
- thirdparty/libgc/include/gc/gc_config_macros.h
- thirdparty/libgc/include/gc/gc_gcj.h
- thirdparty/libgc/include/gc/gc_inline.h
- thirdparty/libgc/include/gc/gc_mark.h
- thirdparty/libgc/include/gc/gc_tiny_fl.h
- thirdparty/libgc/include/gc/gc_typed.h
- thirdparty/libgc/include/gc/leak_detector.h
I am looking in to why the vlib/v/slow_tests/keep_args_alive_test.c.v is flaky.
On FreeBSD, on amd64 CPUs, this test fails approximately 80% of the time.  FreeBSD on arm64 does not have this problem and this test always succeeds.
I have also tested with macos on a m1 processor and this test always succeeds.
The keep_args_alive_test on amd64 does not actually fail, it just never finishes and I have to kill it.  To get a feel for what is going on, I collected some user-level stack traces at 997 Hz, using dtrace, in order to generate a flamegraph so I could see where it was spending time.  The resulting image is:
Comparing the version in thirdparty/libgc with the version in the master branch at https://github.com/ivmai/bdwgc, I saw that there were some changes in the marking logic.  This …
> libgc: update libgc to commit 6d372272

- vlib/net/connection.v
- vlib/net/dialer.v
- vlib/net/mbedtls/ssl_connection.c.v
- vlib/net/openssl/ssl_connection.c.v
- vlib/net/socks/socks5.v
- vlib/net/socks/socks5_test.v
- vlib/net/ssl/dialer.v
- vlib/net/tcp.c.v
- vlib/net/unix/stream.c.v
From my thread on Discord:
> Hey there,
>
> I've recently taken an interest in vlang and I've been looking through the vlib net implementations.  I'm curious if you all would be open to some patches that move away from directly referencing `net.TCPConn` or `ssl.SSLConn` structures and instead work with interfaces (similar to golang).  For instance, I think the introduction of a `net.IDialer` interface as well as a `net.IConn` interface could go a long way to making vlangs net stack extendable, and reduce the amount of code required.
> 
> Taking the socks5.v (https://github.com/vlang/v/blob/master/vlib/net/socks/socks5.v) implementation as an example, today there are multiple entry points - one for TCP, one for SSL, which are required because its tightly bound to the concrete structures …
> net: add net.Dialer and net.Connection interfaces, abstracting the different types of connections, already supported by the V network stack

- vlib/encoding/csv/csv_reader_random_access.v
- vlib/net/http/header.v
- vlib/sokol/gfx/gfx_structs.c.v
- vlib/sokol/sapp/sapp_structs.c.v
- vlib/term/termios/termios_android.c.v
- vlib/term/termios/termios_darwin.c.v
- vlib/term/termios/termios_dragonfly.c.v
- vlib/term/termios/termios_freebsd.c.v
- vlib/term/termios/termios_linux.c.v
- vlib/term/termios/termios_openbsd.c.v
- vlib/term/termios/termios_qnx.c.v
- vlib/term/termios/termios_solaris.c.v
- vlib/term/ui/input_windows.c.v
- vlib/v/ast/str.v
- vlib/v/fmt/tests/struct_decl_with_const_default_value_and_comments_keep.vv
- vlib/v/gen/native/pe.v
This PR fix const field str().
fmt before:
```v
module foo
pub const endline_cr_len = 1
pub struct RandomAccessReader {
pub mut:
index i64
start_index i64
end_index   i64 = -1
end_line      u8  = `\n`
end_line_len  int = foo.endline_cr_len // size of the endline rune \n = 1, \r\n = 2
separator     u8  = `,`            // comma is the default separator
separator_len int = 1              // size of the separator rune
quote         u8  = `"`            // double quote is the standard quote char
quote_remove  bool // if true clear the cell from the quotes
comment       u8 = `#` // every line that start with the quote char is ignored
default_cell string = '*' // return this string if out of the csv boundaries
empty_cell   string = '#' // retunrn this if empty cell
// ram buffer
mem_buf_type …
```
> ast: fix const field str()

- vlib/hash/hash.v
The hash.Hash interface was likely partially ported from Go. 
Over time Vlang evolved and structs that implement the hash.Hash interface also gained new methods to bridge the differences between the Go version and the V version.
These new methods were not added to the hash.Hash interface.
This pull request adds these new methods to the hash.Hash interface.
> hash: Update hash.Hash methods

- vlib/v/gen/c/cgen.v
- vlib/v/tests/closure_of_method_defined_on_alias_test.v
Allows the following code to compile and execute correctly:
```v
type UInt = u32;
fn (me UInt) member() {
println("member called")
}
fn test_1() {
x := UInt(4).member
x()
}
```
The changes made change the generated C output from
```c
VV_LOCAL_SYMBOL void main__test_1(void) {
println(_SLIT("start"));
void (*x) (void) = __closure_create(_V_closure_main__UInt_take_136, memdup_uncollectable(&((main__UInt)(4)), sizeof(main__UInt)));
println(_SLIT("med"));
x();
println(_SLIT("done"));
}
```
to
```c
VV_LOCAL_SYMBOL void main__test_1(void) {
println(_SLIT("start"));
main__UInt _t1 = ((main__UInt)(4));
void (*x) (void) = __closure_create(_V_closure_main__UInt_take_136, memdup_uncollectable(&_t1, sizeof(main__UInt)));
println(_SLIT("med"));
x();
println(_SLIT("done"));
}
```
This does use one of …
> cgen: fix bug preventing generation of closures from methods

- vlib/v/ast/ast.v
- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/enum_fields_with_empty_line_keep.vv
- vlib/v/parser/parser.v
This PR fix enum fields with one empty line.
- Fix enum fields with one empty line.
- Add a test.
enum_fields_with_empty_line_keep.vv
```v
enum Info {
aa = 1 // aa
bbb // bbb
cccc = 5 // cccc
//
ddddd = 10 // ddddd
}
fn main() {}
```
> fmt: fix enum fields with one empty line

- vlib/v/fmt/tests/enum_fields_with_empty_line_keep.vv
- vlib/v/parser/parser.v
This PR fix fmt of enum fields with empty line.
- Fix fmt of enum fields with empty line.
- Change test.
vlib\v\fmt\tests\enum_fields_with_empty_line_keep.vv
```v
enum Info {
aa = 1 // aa
bbb // bbb
cccc = 5 /* cccc
--- cccc
*/
ddddd = 10 // ddddd
}
fn main() {}
```
> ast, parser, fmt: fix fmt of enum fields with empty line

- vlib/v/ast/ast.v
- vlib/v/fmt/struct.v
- vlib/v/parser/struct.v
This PR cleanup fmt of struct fields with empty line.
> ast, parser, fmt: cleanup fmt of struct fields with empty line

- vlib/time/date_time_parser.v
- vlib/time/format.v
- vlib/time/parse.c.v
- vlib/time/time_test.v
Allow weekday name to be parseable (doesn't affect Time struct)
> time: `d`,`c`,`dd`,`ddd`,`dddd` pattern support for parse_format()

- vlib/v/ast/ast.v
- vlib/v/checker/fn.v
- vlib/v/checker/tests/multi_return_err.out
- vlib/v/checker/tests/multi_return_err.vv
- vlib/v/gen/c/fn.v
- vlib/v/tests/multi_return_test.v
Fix #21956
```v 
fn my_func(a1 int, a2 int)  {}
fn my_func2() (int, int)  { return 0,0 }
fn main() {
my_func(my_func2())
}
```
> v: allow multi return as fn argument

- vlib/v/fmt/align.v
- vlib/v/fmt/fmt.v
- vlib/v/fmt/struct.v
This PR cleanup fields alignment.
> fmt: cleanup fields alignment

- vlib/flag/flag.v
- vlib/flag/flag_test.v
When using command line flags with string parameters, I found that the default val_desc values used were not as descriptive as I would like.  And there was no way to override val_desc to a more descriptive value.
Using trailing struct literal arguments, I was able to add this capability without breaking any existing code.
I only did this for string parameters since that seemed to me to be the place where it would be most useful.  It could easily be added to the other types if desired.
> flag: add optional value description to string parameters

- vlib/v/help/common/where.txt
Just fixing a minor wording problem.
> vlib/v/help/common: remove extraneous word "of"

- cmd/tools/vwhere/vwhere_test.v
I noticed that on FreeBSD, the test_find_in_dir_recursive code did locate all the matches but they were in a different order from the expected value in the assertion.  I don't know if all OS/toolchain combinations will return the matches in the same order.  It does appear that FreeBSD using -cc clang returns the results in the opposite order.
Since the point of the test is to see if the 2 matches are found, sorting the matches by line number makes this test pass on FreeBSD without breaking other OS/toolchain combinations.
> cmd/tools/vwhere: sort the match results to make test less flaky

- vlib/flag/flag.v
- vlib/flag/flag_test.v
Added the same sort of value description to bool, int, and float flags as was added for string flags.  I also tweaked the code for string value descriptions.
> flag: add custom value descriptions for bool, int, and float flags too

- cmd/tools/amalgamate.v
- thirdparty/libgc/amalgamation.txt
I wrote a V tool program to do the source amalgamtion for libgc, replacing the need to use the amalgamator.js script.
The existing amalgamator.js script was specific to doing the amalgamation for libgc.  I made this tool more generic so that it could handle libgc and anything else that one might want to amalgamate.  I also updated the description of how to generate gc.c and put it, along with updated header files, into the right place in the thirdparty/libgc directory.
This amalgamate tool is the same one I used for my previous update to thirdparty/libgc/gc.c.  I have a newer version of gc.c based on a newer commit of bdwgc, but I didn't want to include it in this pull request.  Hopefully, with this tool, it will be easier to keep libgc more current.
> cmd/tools: add amalgamate tool and description of usage

- vlib/flag/flag_to.v
- vlib/flag/flag_to_tail_test.v
Fixes an edge case I found using `flag.parse[T]()`. Some of the added tests would fail before the changes in this PR.
> flag: fix assigning to `@[tail]` field when no fields has been matched yet in `flag.parse[T]()`

- vlib/x/json2/decoder2/decode_test.v
Some json2 test
Next PR: include test bellow
```v
nodes = []
decoder = Decoder{
json: '{"_type": "Cat", "val": 2}'
}
decoder.fulfill_nodes(mut nodes)
dump(nodes)
assert nodes.len == 1
assert nodes[0].key_pos == 18
assert nodes[0].key_len == 3
assert nodes[0].children == none
```
> x.json2.decode2: add another internal test

- cmd/tools/modules/testing/output.v
- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/interface_declaration_comments_keep.vv
- vlib/v/preludes/test_runner.c.v
This PR fix interface fields/methods alignment.
- Fix interface fields/methods alignment.
- Modify the related test.
```v
interface TestRunner {
mut:
file_test_info      VTestFileMetaInfo // filled in by generated code, before .start() is called.
fn_test_info        VTestFnMetaInfo   // filled in by generated code, before .fn_start() is called.
fn_assert_passes    u64               // reset this to 0 in .fn_start(), increase it in .assert_pass()
fn_passes           u64               // increase this in .fn_pass()
fn_fails            u64               // increase this in .fn_fails()
total_assert_passes u64               // increase this in .assert_pass()
total_assert_fails  u64               // increase this in .assert_fail()
start(ntests int) // called before all tests, you can initialise …
```
> fmt: fix interface fields/methods alignment

- vlib/v/gen/c/cgen.v
- vlib/v/tests/array_init_fixed_test.v
Fix #22056
Fix #22057
Fix #22058
> cgen: fix array fixed with default init

- vlib/v/ast/ast.v
- vlib/v/ast/types.v
- vlib/v/checker/struct.v
- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/types_expected.vv
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/struct.v
- vlib/v/gen/c/testdata/sumtype_pass_by_reference.out
- vlib/v/tests/sumtype_init_test.v
- vlib/v/tests/sumtype_str_test.v
- vlib/x/json2/tests/encode_struct_test.v
> cgen: make possible to initialize sumtype with default type (first variant)

- vlib/builtin/js/builtin.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/cast_to_interface_err.out
- vlib/v/checker/tests/infix_is_notis_interface_unimplemented_err.out
- vlib/v/checker/tests/mut_receiver_wrong_return_type.out
- vlib/v/gen/c/cgen.v
This PR remove the obsolete .code and .msg fields of IError.
> all: remove the obsolete .code and .msg fields of IError

- vlib/v/checker/struct.v
- vlib/v/checker/tests/sumtype_init_with_ref_fields_err.out
- vlib/v/checker/tests/sumtype_init_with_ref_fields_err.vv
This PR add a checker error when initializing struct via sumtype as first variant type.
```v
struct Node {
parent &Node
left &Node
right &Node
}
type Sumtype = Node | int
fn main() {
s := Sumtype{}
dump(s)
}
```
```
bug.v:9:10: error: reference field `Node.parent` must be initialized
7 | 
9 |     s := Sumtype{}
|          ~~~~~~~~~
10 |     dump(s)
11 | }
bug.v:9:10: error: reference field `Node.left` must be initialized
7 | 
9 |     s := Sumtype{}
|          ~~~~~~~~~
10 |     dump(s)
11 | }
bug.v:9:10: error: reference field `Node.right` must be initialized
7 | 
9 |     s := Sumtype{}
|          ~~~~~~~~~
10 |     dump(s)
11 | }
```
> checker: add error when initializing sumtype with struct as first type

- vlib/arrays/arrays.v
I don't know if this improves performance, if cutting the array makes a new copy of it.
If it's not, close it.
> arrays: simplify arrays.sum and arrays.reduce

- vlib/x/json2/decoder.v
- vlib/x/json2/encoder.v
- vlib/x/json2/tests/decode_struct_test.v
- vlib/x/json2/tests/encode_struct_skippable_fields_test.v
In order to make the v version of json (x.json2) compatible with json, make the same functionality of skip working in json2
> json2: add compatibility of @[skip] in json2

- cmd/tools/vdoc/testdata/basic/basic.out
- vlib/v/checker/tests/like_operator_outside_orm_error.out
- vlib/v/parser/fn.v
- vlib/v/parser/tests/fn_call_args_without_comma_1_err.out
- vlib/v/parser/tests/fn_call_args_without_comma_1_err.vv
- vlib/v/parser/tests/fn_call_args_without_comma_2_err.out
- vlib/v/parser/tests/fn_call_args_without_comma_2_err.vv
- vlib/v/parser/tests/fn_call_unexpected_eof_rpar_multi_line_err.out
This PR check fn call args without comma between them (related #22021).
- Check fn call args without comma between them.
- Add test.
```v 
fn greet(i1 int, i2 int) {
println('${i1} ${i2}')
}
fn main() {
greet(17 23)
}
tt1.v:6:11: error: unexpected number `23`, expecting `,`
4 | 
6 |     greet(17 23)
|              ~~
7 | }
```
```v
fn greet(i1 int, i2 int) {
println('${i1} ${i2}')
}
fn main() {
greet(
17
23
)
}
tt1.v:8:3: error: unexpected number `23`, expecting `,`
6 |     greet(
7 |         17
8 |         23
|         ~~
9 |     )
10 | }
```
> parser: check fn call args without comma between them (related #22021)

- vlib/benchmark/benchmark.v
- vlib/benchmark/benchmark_test.v
Add more bechmark information to recorded measurements.
old:
new:
> bechmark: Add min, max & avg to recorded measurements

- vlib/builtin/string.v
- vlib/v/fmt/fmt.v
- vlib/v/fmt/struct.v
This PR cleanup alignment using `' '.repeat(n)` instead of `strings.repeat(' ', n)`.
> fmt: cleanup alignment using string.repeat() instead of strings.repeat()

- vlib/builtin/int.v
- vlib/builtin/js/rune.js.v
- vlib/builtin/rune.v
This PR cleanup `u8.repeat()` and `rune.repeat()`.
> builtin: cleanup `u8.repeat()` and `rune.repeat()`

- vlib/v/ast/ast.v
- vlib/v/ast/str.v
- vlib/v/gen/c/cgen.v
- **ast: cache Ident scope lookups for consts in Expr.str**
- **ast,cgen: remove instrumentation for the cached ident lookup, cleanup**
> ast: cache ident lookups for consts in ast Expr str

- vlib/v/ast/ast.v
- vlib/v/checker/fn.v
- vlib/v/checker/lambda_expr.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/lambda_generic_test.v
> v: fix generic lambda type binding and resolution

- vlib/v/ast/table.v
- vlib/v/ast/types.v
- vlib/v/checker/check_types.v
- vlib/v/checker/checker.v
- vlib/v/checker/comptime.v
- vlib/v/checker/fn.v
- vlib/v/checker/if.v
- vlib/v/checker/infix.v
- vlib/v/checker/match.v
- vlib/v/checker/orm.v
- vlib/v/checker/struct.v
- vlib/v/fmt/fmt.v
- vlib/v/gen/c/assign.v
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/dumpexpr.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/infix.v
- vlib/v/gen/c/json.v
- vlib/v/gen/js/comptime.v
- vlib/v/gen/js/js.v
- vlib/v/markused/markused.v
- vlib/v/parser/orm.v
- vlib/v/parser/parse_type.v
- vlib/v/parser/struct.v
- **ast: change ast.Type to be an alias of u32, add ast.idx_to_type/1 and ast.no_type, use them consistently**
- **ast: improve operations involving Type and TypeFlag**
- **ci: fix `v test vlib/builtin`**
> ast: improve Type and TypeFlag related operations

- cmd/tools/vtest-self.v
This PR fix vtest-self.v on Windows and tcc compiler.
before (local v test-self on Windows and tcc compiler) :
```v
OK    [1640/1961] C:   674.9 ms, R:    39.054 ms vlib/v/tests/ref_struct_test.v
FAIL  [1641/1961] C:  7211.4 ms, R:     0.000 ms vlib/v/tests/project_with_cpp_code/compiling_cpp_files_with_a_cplusplus_compiler_test.c.v
================== C compilation error (from tcc): ==============
cc: tcc: error: unrecognized file type
=================================================================
(You can pass `-cg`, or `-show-c-output` as well, to print all the C error messages).
builder error:
C error found. It should never happen, when compiling pure V code.
This is a V compiler bug, please report it using `v bug file.v`,
or goto …
```
> tools: fix vtest-self.v on Windows and tcc compiler

- vlib/v/gen/c/coutput_test.v
This PR fix coutput_test.v on Windows and tcc compiler.
before (on Windows and tcc compiler):
```v
FAIL  [ 470/1961] C:   605.2 ms, R: 54168.989 ms vlib/v/gen/c/coutput_test.v
retry: 1
comp_cmd: "D:\Vlang\v\v.exe" -skip-running   -o "C:\Users\yuyi9\AppData\Local\Temp\v_0\tsession_46d0_01J61XG3YHRFYQ9YXRE0JYXYGR\470_0\coutput_test.exe" "D:\Vlang\v\vlib\v\gen\c\coutput_test.v"
run_cmd: "C:\Users\yuyi9\AppData\Local\Temp\v_0\tsession_46d0_01J61XG3YHRFYQ9YXRE0JYXYGR\470_0\coutput_test.exe"
failure code: 1; foutput.len: 16060; failure output:
---------------------------------------------------------------------------------------------------- retry: 0 ; max_retry: 0 ; r.exit_code: 1 ; trimmed_output.len: 15890
> testing whether .out files match:
OK   C:   378ms, R:29ms v run …
```
> cgen: fix coutput_test.v on Windows and tcc compiler

- cmd/tools/vdoc/theme/doc.css
- vlib/time/format.v
- vlib/time/parse.c.v
parse_format: formating now using markdown table.
custom_format: specifiers sorted in logical order.
> docs: parse_format description formating

- vlib/os/os_stat_test.v
> tests: skip an assertion in os_stat_test.v on OpenBSD

- vlib/v/gen/c/cgen.v
- vlib/v/scanner/scanner.v
- **scanner: avoid new allocations, while scanning strings with no escapes**
- **cgen: avoid string interpolation in Gen.new_tmp_var/0**
> cgen, scanner: reduce allocations for the most common cases

- cmd/tools/bench/map_clear.v
- cmd/tools/bench/map_clear_runner.vsh
- vlib/builtin/map.v
- vlib/builtin/map_issue_22139_clear_test.v
> builtin: fix map.clear() not resetting map's metas and keys blocks (fix #22139)

- vlib/builtin/map.v
- vlib/builtin/map_issue_22143_clear_test.v
> builtin: fix incomplete m.clear(), allowing the map to have a duplicated entry for its first key (fix #22143)

- vlib/builtin/map.v
- vlib/builtin/map_issue_22145_clear_test.v
> builtin: fix m.clear() having different observable behavior to `m = {}`, after multiple iterations of setting keys and clearing (fix #22145)

- vlib/v/checker/assign.v
- vlib/v/gen/c/index.v
- vlib/v/tests/fixed_array_with_map_test.v
> cgen: fix array fixed initialization from map indexing

- vlib/v/builder/cc.v
When building in cstrict mode on OpenBSD with clang, some "braces around scalar initializer" errors occur. Add '-Wno-braced-scalar-init' flag for this case.
Fix vlang/v#22129
---
Tests OK when building in cstrict mode with Clang v16 on OpenBSD/amd64 and Linux (Debian testing/amd64).
> v.builder: fix errors in cstrict mode on OpenBSD with clang

- vlib/flag/README.md
- vlib/flag/flag_to.v
- vlib/flag/v_long_style_flags_test.v
This PR adds support for parsing flags that `flag.FlagParser` also supports (`--flag value`) - it is something I overlooked when initially implementing the functionality. I am working on simplifying `vab`'s flag handling and bumped into this :slightly_smiling_face:
> flag: add support for parsing `flag.FlagParser` style flags in `to_struct[T]`

- vlib/builtin/string.v
This PR cleanup comments of struct string.
> builtin: cleanup comments of struct string

- vlib/flag/flag.v
- vlib/flag/flag_parse_test.v
This PR fix parse_bool_value() (fix #22155).
- Fix parse_bool_value().
- Add test.
```v
import flag
pub struct Options {
pub:
verbosity  int
dump_usage bool
pub mut:
additional_args []string
archs           []string
v_flags         []string
api_level       string
}
fn main() {
args := ['/my/app', '-v', '3', '-f', '-d sdl_memory_no_gc', '-f', '-d shy_use_wren', '--api',
'21', '--archs', 'arm64-v8a', '/path/to/input.v']
mut fp := flag.new_flag_parser(args)
fp.application('bug')
fp.version('0.2.0')
fp.description('bugged')
fp.arguments_description('not important')
fp.skip_executable()
mut opt := Options{
v_flags:    fp.string_multi('flag', `f`, 'Additional flags for the V compiler')
archs:      fp.string('archs', 0, 'arm64-v8a,armeabi-v7a,x86,x86_64', 'Comma separated string with any of …
```
> flag: fix parse_bool_value() (fix #22155)

- vlib/v/gen/c/assign.v
- vlib/v/tests/generics/generic_options_with_reserved_ident_test.v
This PR fix generic options with reserved ident (fix #22163).
- Fix generic options with reserved ident.
- Add test.
```v
pub fn f[T](defaults ?T) T {
default := defaults or { T{} }
dump(default)
return default
}
fn main() {
ret1 := f(123)
println(ret1)
assert ret1 == 123
ret2 := f('hello')
println(ret2)
assert ret2 == 'hello'
}
[.\\tt1.v:3] default: 123
123
[.\\tt1.v:3] default: hello
hello
```
> cgen: fix generic options with reserved ident (fix #22163)

- vlib/v/gen/c/struct.v
- vlib/v/tests/structs/struct_field_default_value_optional_test.v
This PR fix struct field with default optional value (fix #11119).
- Fix struct field with default optional value.
- Add test.
```v
import regex
struct RegexCache {
mut:
tag_script_start regex.RE = regex.regex_opt(r'^script.*>') or { panic(err) }
}
pub struct Tokenizer {
mut:
regex_cache RegexCache = RegexCache{}
}
fn new_parser() &Parser {
mut parser := &Parser{}
return parser
}
pub struct Parser {
mut:
tnzr Tokenizer
}
fn main() {
p := new_parser()
println(p)
}
&Parser{
tnzr: Tokenizer{
regex_cache: RegexCache{
tag_script_start: regex.RE{
prog: [regex.Token{
ist: 2147483647
ch: 115
ch_len: 1
flag: 0
rep_min: 1
rep_max: 1
greedy: false
cc_index: -1
rep: 0
validator: fn (u8) bool
group_neg: false
group_rep: 0
group_id: -1
goto_pc: -1
next_is_or: false …
```
> cgen: fix struct field with default optional value (fix #11119)

- vlib/flag/flag_to.v
- vlib/flag/v_flag_parser_style_flags_test.v
This PR corrects some misunderstandings about what flags the `flag.FlagParser` supports.
Before: `--s <value>`
After: `-s <value>` (or `-s` for `bool` fields)
I decided to rename the `style` `enum` from `.v_long` to the more clear `.v_flag_parser` - I do not think the `.v_long` parsing style is much used in the  wid used - so breakage in userland should be minimal.
> flag: fix parsing `flag.FlagParser` style short flags in `to_struct[T]`

- vlib/builtin/builtin.c.v
- vlib/builtin/wasm/builtin.v
There were references to the v_calloc function but this function appears to have been removed.
> builtin: remove references to v_calloc in function comments

- vlib/v/parser/parser.v
- vlib/v/slow_tests/inout/printing_option_or_expr_with_map_val.out
- vlib/v/slow_tests/inout/printing_option_or_expr_with_map_val.vv
This PR fix parsing map value inside or expr (fix #12164).
- Fix parsing map value inside or expr.
- Add test.
```v
struct MyError {
msg string
code int
}
fn (my MyError) msg() string {
return my.msg
}
fn (my MyError) code() int {
return my.code
}
type MapString = map[string]string | int
fn f() ?MapString {
return MyError{msg: 'String Error'}
}
fn main() {
println(f() or { { 'abc': err.msg() } })
}
MapString({'abc': 'String Error'})
```
> parser: fix parsing map value inside or expr (fix #12164)

- vlib/v/checker/check_types.v
- vlib/v/checker/containers.v
- vlib/v/parser/containers.v
- vlib/v/tests/aliases/array_alias_test.v
> parser, checker: fix array alias

- vlib/crypto/pbkdf2/pbkdf2.v
- vlib/crypto/pbkdf2/pbkdf2_test.v
When running some test vectors I picked up from https://github.com/brycx/Test-Vector-Generation/blob/master/PBKDF2/pbkdf2-hmac-sha2-test-vectors.md, I found a small bug in the `key` function which I have fixed.
While I was in there, I added the capability to use sha224 and sha384 for the hash function.
The tests I have added cover the cases of the original tests and also exercise the code in a way that exposed the bug I ran in to.  I have commented out test case 4 because it takes several minutes to run just once.  Running it for all 4 hash functions would be excessive.  For the record, test case 4 does pass and if someone wanted to run it, it is there.
> crypto/pbkdf2: fix pbkdf2 key generation and add more tests

- vlib/builtin/string.v
- vlib/builtin/string_test.v
This PR fix string.trim() (fix #13021).
- Fix string.trim().
- Add test.
```v
fn main(){
s := 'あいうえお'
println(s)
ts := s.trim('あい')
println(ts)
}
あいうえお
うえお
```
> builtin: fix string.trim() (fix #13021)

- vlib/v/gen/c/match.v
- vlib/v/tests/conditions/matches/match_with_mut_cond_var_test.v
This PR fix match with mut cond variable (fix #22201).
- Fix match with mut cond variable.
- Add test.
```v
fn main() {
mut aaa := ['/', 'a', 'b']
for mut ccc in aaa {
match ccc {
'/' { println(ccc) }
else { println(ccc) }
}
}
}
/
a
b
```
> cgen: fix match with mut cond variable (fix #22201)

- vlib/v/fmt/struct.v
- vlib/v/fmt/tests/import_selective_with_implements_keep.vv
This PR fix import selective with interface implements (fix #22200).
- Fix import selective with interface implements.
- Add test.
vlib\v\fmt\tests\import_selective_with_implements_keep.vv
```v
import v.ast.walker { Visitor }
import v.ast { Node }
struct Walker implements Visitor {
aaa string
}
fn (mut n Walker) visit(node &Node) ! {
panic('not implemented')
}
```
> fmt: fix import selective with interface implements (fix #22200)

- doc/docs.md
With commits https://github.com/vlang/v/commit/0090170b26f291405b377d8adad47a227d1ed1bb and https://github.com/vlang/v/commit/ac6ca5f858e7a93a8764eb43fb116d8a216a2edb, there is now an optional `implements` keyword for explicit interface implementations.
---
Markdown format and V code checked with `v check-md`:
```bash
$ ./v check-md doc/docs.md
Checked .md files: 1 | OKs: 269 | Warnings: 0 | Errors: 0 | Formatting errors: 0
```
> docs: add implements keyword for explicit interface implementations

- vlib/v/fmt/tests/fn_with_c_binding_type_args_keep.vv
This PR add a test for fn with c binding type args (related #13233).
```v
fn C.archive_entry_copy_stat(&C.archive_entry, const_stat &C.stat)
```
> fmt: add a test for fn with c binding type args (related #13233)

- examples/http_server.v
- vlib/v/tests/enums/short_enum_syntax_across_module_test.v
- vlib/vweb/vweb.v
This PR add a test for short enum syntax across modules (related #12183).
- Add a test for short enum syntax across modules.
- Modify all the related files.
```v
fn main() {
header := http.new_header_from_map({
.content_type: 'application/json'
})
println(header)
}
Content-Type: application/json
```
> test: add a test for short enum syntax across modules (related #12183)

- doc/docs.md
- vlib/v/checker/checker.v
- vlib/v/parser/comptime.v
- vlib/v/tests/comptime/comptime_at_test.v
- vlib/v/token/token.v
- vlib/v/util/util.v
With this PR, this code:
```v
dump(@BUILD_DATE)
dump(@BUILD_TIME)
dump(@BUILD_TIMESTAMP)
```
will produce something like this (fixed at compile time), each time it is run:
```
[/v/misc/2024_09_13__12/a.v:2] @BUILD_DATE: 2024-09-13
[/v/misc/2024_09_13__12/a.v:3] @BUILD_TIME: 09:31:25
[/v/misc/2024_09_13__12/a.v:4] @BUILD_TIMESTAMP: 1726219885
```
... which eliminates one more common use of a separate build system.
> all: add support for `@BUILD_DATE`, `@BUILD_TIME` and `@BUILD_TIMESTAMP`, all using v.util.get_build_time(), and overridable through SOURCE_DATE_EPOCH

- GNUmakefile
On system where `thirdparty/tcc/tcc.exe` binary is not available (e.g. OpenBSD, NetBSD), during build with GNU `make`, don't check is `tcc` is working (don't run target `check_for_working_tcc`).
---
**Tests with GNU make**
- **OK** on OpenBSD current/amd64: **`tcc` not available**
```bash
$ gmake -v
GNU Make 4.4.1
Built for x86_64-unknown-openbsd7.6
(...)
$ gmake rebuild
rm -rf ./thirdparty/tcc
rm -rf ./thirdparty/legacy
rm -rf ./vc
gmake fresh_vc
gmake[1]: Entering directory '/home/fox/dev/vlang.git'
rm -rf ./vc
git clone --filter=blob:none --quiet https://github.com/vlang/vc ./vc
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving …
```
> GNUmakefile: don't check tcc if not available

- vlib/builtin/string.v
- vlib/builtin/string_test.v
This PR cleanup string trim()/trim_left()/trim_right().
- Cleanup string trim()/trim_left()/trim_right().
- Fix trim_left() and trim_right().
- Add tests.
```v
assert 'あいうえお'.trim('あい') == 'うえお'
assert 'あいうえお'.trim_left('あい') == 'うえお'
assert 'あいうえお'.trim_right('うえお') == 'あい'
```
> builtin: cleanup string trim()/trim_left()/trim_right()

- vlib/builtin/builtin_d_gcboehm.c.v
Fix vlang/v#22156
**Tests OK on OpenBSD/amd64** with:
- `tcc` installed from OpenBSD packages (`pkg_add tcc`)
- `tcc` built for OpenBSD/amd64 => see https://github.com/vlang/tccbin/pull/54
- clang 16.0.6
- gcc version 11.2.0
```
$ ./thirdparty/tcc/tcc.exe -v
tcc version 0.9.28rc 2024-09-14 HEAD@b8b6a5fd (x86_64 OpenBSD)
$ ./v -cc tcc run ~/tmp/hello_world.v
Hello world from V
$ /usr/local/bin/tcc  -v
tcc version 0.9.27 2023-07-05 mob@5b28165 (x86_64 OpenBSD)
$ ./v -cc /usr/local/bin/tcc run ~/tmp/hello_world.v
Hello world from V
$ ./v -cc clang run ~/tmp/hello_world.v
Hello world from V
$ ./v -cc egcc run ~/tmp/hello_world.v
Hello world from V
```
> builtin: fix compilation with tcc on OpenBSD using libgc

- vlib/json/json_decode_anon_struct_test.v
- vlib/v/ast/ast.v
- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/fmt/fmt.v
- vlib/v/parser/expr.v
Fix #21703
```v
import json
fn main() {
json_text := '{ "a": "b" }'
b := json.decode(struct {
a string
}, json_text)!.a
assert dump(b) == 'b'
}
```
> json: allow anon struct as decode type

- vlib/flag/flag.v
- vlib/flag/flag_test.v
This PR fix parse_bool_value() with different order short args (fix #22176).
- Fix parse_bool_value() with different order short args.
- Add test.
```v
import flag
fn main() {
mut fp := flag.new_flag_parser(['-ba', '-c'])
a_bool := fp.bool('a_bool', `a`, false, '')
assert a_bool
b_bool := fp.bool('b_bool', `b`, false, '')
assert b_bool
c_bool := fp.bool('c_bool', `c`, false, '')
assert c_bool
additional_args := fp.finalize()!
println(additional_args.join_lines())
assert additional_args == []
}
```
> flag: fix parse_bool_value() with different order short args (fix #22176)

- vlib/builtin/builtin.v
- vlib/v/ast/ast.v
- vlib/v/ast/str.v
- vlib/v/checker/comptime.v
- vlib/v/checker/if.v
- vlib/v/comptime/comptimeinfo.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/str_intp.v
- vlib/v/parser/comptime.v
- vlib/v/parser/tests/comptime_unknown_meta_kind_err.out
- vlib/v/tests/comptime/comptime_for_method_arg_test.v
- vlib/v/tests/comptime/comptime_for_method_param_test.v
Fix #20926
```v
fn register[T]() []string {
mut args := []string{}
$for method in T.methods {
$for arg in method.args {
$if arg.typ is f32 {
args << 'f32: ${arg.name} ${typeof(arg.typ).name}'
} $else $if arg.typ is voidptr {
args << '&void: ${arg.name} ${typeof(arg.typ).name}'
} $else {
}
}
}
return args
}
```
> feat: traverse method args in comptime

- doc/docs.md
Cross compilation to FreeBSD is supported since version 0.4.7 (added in commit https://github.com/vlang/v/commit/b7efbca8b65f46631cd077621e983e99929d489a)
> docs: add FreeBSD in cross compilation section

- vlib/builtin/int.v
` -Wimpure-v ` now default to coreutils, this PR fix test failure in coreutils
https://github.com/vlang/coreutils/actions/runs/10865356775/job/30151722872
Related: #20696
> builtin: drop C in int.v

- doc/docs.md
Docs
```v
struct Test {
}
fn (t Test) foo(arg1 int, arg2 string) {	
}
fn main() {
$for m in Test.methods {
$for param in m.params {
println('${typeof(param.typ).name}: ${param.name}')
}
}
}
```
> docs: comptime method params

- vlib/v/builder/cc.v
LTO is supported by Clang compiler on OpenBSD => enable `-flto` during compilation (used with `-prod` for optimizations)
- OpenBSD clang manpage: https://man.openbsd.org/OpenBSD-current/man1/clang.1 => flag `-flto`
- Clang code `OpenBSD.cpp`, line 397 => `OpenBSD::HasNativeLLVMSupport = true` https://clang.llvm.org/doxygen//OpenBSD_8cpp_source.html#l00397
---
- Tests on OpenBSD/amd64 with `clang` v16 + `prod` => flag `-flto` used for compilation **OK** 
```bash
$ ./v -prod -cc clang -showcc -o /tmp/hello_world examples/hello_world.v
> C compiler cmd: 'clang' '@/tmp/v_1000/hello_world.01J825QPG073H9G4EXT8EEGF72.tmp.c.rsp'
> C compiler response file "/tmp/v_1000/hello_world.01J825QPG073H9G4EXT8EEGF72.tmp.c.rsp":
-O3 -flto -DNDEBUG "/home/fox/.vmodules/cache/12/129a7ad1d9dc9094487dea50dd5193d …
```
> v.builder: enable LTO for clang on OpenBSD

- doc/docs.md
In section "Conditional compilation / Environment specific files" (https://docs.vlang.io/conditional-compilation.html#environment-specific-files), improve Markdown format for filenames and output strings.
> docs: improve format in the conditional compilation section

- vlib/v/gen/c/cheaders.v
- vlib/v/gen/c/comptime.v
The size of vint_t for riscv64 should be 64.
> cgen: fix wrong type of vint_t and const riscv64

- vlib/strconv/format_mem.c.v
This PR cleanup format_fl()/format_es() (related #22244).
> strconv: cleanup format_fl()/format_es() (related #22244)

- vlib/v/gen/c/fn.v
- vlib/v/tests/fns/anon_c_keywords_closure_test.v
> cgen: fix C name mangling with inherited closure vars

- vlib/crypto/rand/utils.v
- vlib/crypto/rand/utils_test.v
> crypto: add random big integer generation

- examples/2048/2048.v
This PR fixes a case where compiling with `-cg` causes an assert in the garbage collector to trigger. It only happens on the `aosp_atd` type of emulator for reasons I have not been able to pin point. I'm trying to speed up `vab` emulator runs by using official "slimmer" emulator images (some reports 40% speed ups) and ran into this edge-case.
It can be reproduced with a working `vab` and Andoid SDK+NDK setup like this
```bash
echo yes | sdkmanager 'system-images;android-30;aosp_atd;x86_64'
echo no | avdmanager create avd --force --name test --abi aosp_atd/x86_64 --package 'system-images;android-30;aosp_atd;x86_64'
emulator -avd test -wipe-data -no-metrics -no-snapshot -no-boot-anim -camera-back emulated -camera-front emulated &
adb wait-for-device shell 'while [[ -z $(getprop …
```
> examples: add `gc_is_enabled()` check to `2048` to prevent crash in Android emulator

- vlib/net/websocket/websocket_client.v
I am working on a TUI that connections to websocket servers. I am getting premature ws closures specifically when using net.websocket client in conjunction with term.ui. By checking for EINTR error code and continuing rather than returning ws.read_next_message() fails we avoid closing prematurely. EINTR calls should not cause ws closures in this case.
This change makes the websocket behave as expected.
I hope this helps others as for me it has fixed the problem.
> net:websocket EINTR handling

- vlib/io/buffered_writer.v
- vlib/io/buffered_writer_test.v
> io: add a BufferedWriter and supporting methods

- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/checker/tests/option_fn_var_err.out
- vlib/v/checker/tests/option_fn_var_err.vv
- vlib/v/gen/c/match.v
- vlib/v/tests/options/option_fn_var_test.v
> checker, cgen: fix codegen for option fntype

- vlib/v/gen/c/assign.v
- vlib/v/tests/options/option_fntype_assign_test.v
> cgen: fix option cast from fntype 

- vlib/x/benchmark/benchmark.v
- vlib/x/benchmark/benchmark_test.v
For my task, I need a benchmark that measures memory consumption. I checked the default benchmark library and didn't find that feature. So I decided to write it myself.
As advised in the Telegram chat, "just rewrite the golang library to vlang".
I checked the golang benchmark code and decided it was strange and overly complicated due to its use as a command-line tool.
So I decided to create my own library.
Basically, I copied the memory measurement logic and the prediction of the number of iterations from golang to estimate the expected benchmark evaluation time. And from vlang, I got the logic of using the benchmark as a library, not as a command-line tool.
How to use it:
- Create a Benchmark using the constructor, provide a closure to benchmark, optionally provide the expected number of …
> vlib.x: add a go like benchmark, that estimates automatically how many iterations are needed, to get a statistically significant result

- vlib/v/ast/ast.v
- vlib/v/parser/fn.v
- vlib/v/parser/tests/enum_method_duplicated_err.out
- vlib/v/parser/tests/enum_method_duplicated_err.vv
This PR check enum method duplicated (fix #20924).
- Check enum method duplicated.
- Add test.
```v
@[flag]
enum Flags {
bit0
bit1
bit2
bit3
bit4
bit5
bit6
bit7
}
fn (f Flags) has(f2 Flags) bool {
return f & f2 > 0
}
fn main() {}
tt1.v:13:14: error: duplicate method `has`, `has` is an enum type built-in method
11 | }
12 | 
13 | fn (f Flags) has(f2 Flags) bool {
|              ~~~
14 |     return f & f2 > 0
15 | }
```
> parser: check enum method duplicated (fix #20924)

- vlib/v/fmt/align.v
This PR cleanup align.v.
- Remove never used `ignore_newline` config para.
> fmt: cleanup align.v

- vlib/v/gen/c/fn.v
- vlib/v/tests/fns/method_call_on_rangeexpr_test.v
Fix #12610
```v
type Buffer = []byte
pub fn (mut sb Buffer) vbytes() string {
return sb[0..sb.len].a().str()
}
pub fn (mut sb Buffer) a() Buffer {
return sb
}
mut b := Buffer([]byte{cap: 10})
b << 1
b << 2
assert b.vbytes() == 'Buffer([1, 2])'
}
```
> cgen: fix codegen for method call on rangeexpr

- vlib/v/parser/tmpl.v
- vlib/v/tests/tmpl/escape.txt
- vlib/v/tests/tmpl_escape_test.v
> tmpl: add escape for `@` using `@@`

- vlib/v/gen/c/assign.v
- vlib/v/tests/builtin_arrays/array_fixed_op_overload_test.v
This PR fix fixed array operation overload (fix #22297).
- Fix fixed array operation overload.
- Add test.
```v
import math
import math.vec
type Vector3 = vec.Vec3[f32]
fn vector3(x f32, y f32, z f32) Vector3 {
return Vector3{x, y, z}
}
pub type Matrix4 = [16]f32
pub fn matrix4(x0 f32, x1 f32, x2 f32, x3 f32, x4 f32, x5 f32, x6 f32, x7 f32, x8 f32, x9 f32, x10 f32, x11 f32, x12 f32, x13 f32, x14 f32, x15 f32) Matrix4 {
return [
x0,
x1,
x2,
x3,
x4,
x5,
x6,
x7,
x8,
x9,
x10,
x11,
x12,
x13,
x14,
x15,
]!
}
pub fn (x Matrix4) str() string {
return '|${x[0]:-6.3},${x[1]:-6.3},${x[2]:-6.3},${x[3]:-6.3}|\n' +
'|${x[4]:-6.3},${x[5]:-6.3},${x[6]:-6.3},${x[7]:-6.3}|\n' +
'|${x[8]:-6.3},${x[9]:-6.3},${x[10]:-6.3},${x[11]:-6.3}|\n' +
'|${x[12]:-6.3},${x[13]:-6.3},${x[14]:-6.3},${x[15]:-6.3}|'
}
pub fn …
```
> cgen: fix fixed array operation overload (fix #22297)

- vlib/v/checker/fn.v
- vlib/v/checker/tests/array_delete_arg_mismatch_err.out
- vlib/v/checker/tests/array_delete_arg_mismatch_err.vv
This PR check array.delete() argument mismatch (fix #22298).
- Check array.delete() argument mismatch.
- Add test.
```v
interface IGameObject {
mut:
name string
}
struct GameObject implements IGameObject {
mut:
name string
}
struct Game {
mut:
objects []IGameObject
}
fn (mut game Game) gc() {
for obj in game.objects {
game.objects.delete(obj)
}
game.objects.clear()
}
fn main() {}
tt1.v:18:23: error: cannot use `IGameObject` as `int` in argument 1 to `.delete()`
16 | fn (mut game Game) gc() {
17 |     for obj in game.objects {
18 |         game.objects.delete(obj)
|                             ~~~
19 |     }
20 |     game.objects.clear()
```
> checker: check array.delete() argument mismatch (fix #22298)

- cmd/tools/vdoc/highlight.v
- vlib/v/checker/infix.v
- vlib/v/checker/str.v
- vlib/v/checker/tests/infix_dup_in_err.out
- vlib/v/checker/tests/infix_dup_in_err.vv
> checker: add missing check for duplicated items on in expr

- .github/workflows/hub_docker_ci.yml
Use cache images from docker repository during build process to store intermediate layers. This change should speed up build process.
Trigger on new release and weekly tags. Others will be ignored.
> Hub docker action - add cache and trigger

- vlib/net/util.v
- vlib/net/utils_test.v
> net: allow ipv6 address with brackets 

- vlib/builtin/builtin_d_gcboehm.c.v
After https://github.com/vlang/tccbin/pull/53 has merged.
We can use gcc/clang with libgc for V now.
```
>>> should_compile_filtered_files: res: ['/home/mzh/v/vlib/math/bits/bits.v', '/home/mzh/v/vlib/math/bits/bits_tables.v
', '/home/mzh/v/vlib/math/bits/unsafe_bits.v']
0.875    ms Builder.resolve_deps
172.462  ms Builder.parse_imports
79.080   ms SCAN
329.514  ms PARSE
430.260  ms ALL_FRONT_STAGES
0.050    ms Checker.generic_insts_to_concrete
254.352  ms CHECK
43.884   ms TRANSFORM
0.292    ms Table.complete_interface_check
0.112    ms Gen.write_sorted_fn_typesymbol_declaration
3.866    ms Gen.sort_structs
6.252    ms cgen init
77.833   ms cgen parallel processing
2.225    ms Gen.sort_globals_consts
6.491    ms cgen unification
0.451    ms Gen.write_init_function
0.645    ms …
```
> vlib: enable GC lib on rv64 build

- vlib/v/checker/interface.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/fns/interface_methods_fixed_arr_test.v
> cgen, checker: fix array fixed return type for interface methods

- vlib/builtin/array_test.v
- vlib/v/gen/c/array.v
- vlib/v/gen/c/fn.v
This PR fix aliases of array insert(...)/prepend(...) (fix #22323).
- Fix aliases of array insert(...)/prepend(...).
- Add test.
```v
type Strings = []string
fn main() {
mut strs := Strings(['hi', '1', '5', '3'])
strs.insert(0, ['33', '22'])
println(strs)
strs.prepend('44')
println(strs)
}
['33', '22', 'hi', '1', '5', '3']
['44', '33', '22', 'hi', '1', '5', '3']
```
> cgen: fix aliases of array insert(...)/prepend(...) (fix #22323)

- vlib/math/big/big_test.v
- vlib/math/big/integer.v
> math.big: fix `a + b` and `a - b`, when the signs are different, add more test cases

- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/checker/tests/array_sort_with_compare_err.out
- vlib/v/checker/tests/array_sort_with_compare_err.vv
- vlib/v/checker/tests/array_sorted_with_compare_err.out
- vlib/v/checker/tests/array_sorted_with_compare_err.vv
This PR check arguments mismatch of array.sorted_with_compare() (fix #22327).
- Check arguments mismatch of array.sorted_with_compare().
- Add test.
```v
fn main() {
names := ['aaa', 'bbb', 'ccc']
name1 := names.sorted_with_compare(sort_by_file_base)
println(name1)
name2 := names.sorted_with_compare(22)
println(name2)
}
fn sort_by_file_base(a string, b string) int {
return int(a > b)
}
tt1.v:11:24: error: sorted_with_compare callback function parameter `a` with type `string` should be `&string`
9 | }
10 | 
11 | fn sort_by_file_base(a string, b string) int {
|                        ~~~~~~
12 |     return int(a > b)
13 | }
tt1.v:11:34: error: sorted_with_compare callback function parameter `b` with type `string` should be `&string`
9 | }
10 | 
11 | fn …
```
> checker: check arguments mismatch of array.sorted_with_compare() (fix #22327)

- vlib/v/checker/fn.v
- vlib/v/checker/tests/any_return_type_err.out
- vlib/v/checker/tests/any_return_type_err.vv
> checker: add missing checker for `any` type

- vlib/v/ast/table.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/interfaces/interface_smartcast_call_test.v
> cgen: fix interface method call after smartcast

- vlib/v/gen/c/struct.v
- vlib/v/tests/structs/struct_init_alias_array_fixed_test.v
> cgen: fix struct init field with alias to array fixed

- vlib/v/checker/fn.v
- vlib/v/checker/tests/unknown_fn_call_err.out
- vlib/v/checker/tests/unknown_fn_call_err.vv
> checker: fix break when calling unknown fn call

- cmd/tools/vdoc/theme/doc.css
The PR adds the overflow property to the search result division to improve keyboard accessibility. Currently, when cycling from the last search result to the first via keyboard, the selection is not visible because the overflow boundaries of the division are not set. The behaviour is visible in the short screencasts below.
- Current
https://github.com/user-attachments/assets/05908a27-c402-470d-a8dd-8914291fb879
- Updated
https://github.com/user-attachments/assets/bbdc0efa-5ea8-483a-9ea2-7a64bab6a443
> v.doc: fix scrolling on keyboard select in search results with overflow

- vlib/net/util.v
Fix #14909
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmY5MmMyMjQzYjBiYWU0OTU4YzIyNzIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.JMBudOkDbGZv7LKErNxKha7X5uncQyEFREKILl4TZoQ">Huly&reg;: <b>V_0.6-20812</b></a></sub>
> net: fix split_address

- vlib/v/gen/c/cgen.v
- vlib/v/tests/consts/const_c_string_test.v
Fix #22358
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZhODE0ZjQzYjBiYWU0OTU4Y2ZiMmQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.zh-bPMmuyLcEbB8-btC268zZFo8pV3LBrjdXNJYGyw4">Huly&reg;: <b>V_0.6-20824</b></a></sub>
> cgen: fix const with c string literal

- vlib/v/checker/fn.v
- vlib/v/checker/tests/ambiguous_function_call.out
- vlib/v/checker/tests/c_fn_surplus_args.out
- vlib/v/checker/tests/error_fn_with_0_args.out
- vlib/v/checker/tests/fn_array_decompose_arg_mismatch_err_c.out
- vlib/v/checker/tests/fn_call_with_extra_parenthesis.out
- vlib/v/checker/tests/function_count_of_args_mismatch_err.out
- vlib/v/checker/tests/generics_fn_arguments_count_err.out
- vlib/v/checker/tests/generics_struct_field_fn_args_err.out
- vlib/v/checker/tests/multi_return_err.out
- vlib/v/checker/tests/no_interface_instantiation_b.out
- vlib/v/checker/tests/no_main_println_err.out
This PR makes improvements to the changes introduced in the commit 7514783d8310925c7f60bad73e94bb37f7e9d4ac.
Before:
```v
main.v:4:12: error: expected 2 arguments, but got 3
have (int literal, string, bool)
want (int, string)
2 | 
4 |     x(1, "2", true)
|               ~~~~
5 | }
```
After:
```v
main.v:4:12: error: expected 2 arguments, but got 3
2 | 
4 |     x(1, "2", true)
|               ~~~~
5 | }
Details: have (int literal, string, bool)
want (int, string)
```
> checker: improve `fn` argument mismatch error

- vlib/v/gen/c/str_intp.v
- vlib/v/tests/comptime/comptime_variant_interp_test.v
Fix #22366
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZhZDJmYjQzYjBiYWU0OTU5MDlmMmEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.J1RCiBKO4rRoU6kt37P_KuzrcXUYTDHRgosxKsmEsoE">Huly&reg;: <b>V_0.6-20830</b></a></sub>
> cgen: fix comptime variant string interpolation

- vlib/net/socket_options.c.v
- vlib/net/tcp.c.v
Prepare to fix other veb related issues
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZiOTcxMzQzYjBiYWU0OTU5YTI5ZWYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.Ffsj8tIeyyVTkHDlFPrjqhEUfICEvpynoK3Hl20YtnM">Huly&reg;: <b>V_0.6-20840</b></a></sub>
> net: add more SocketOptions enum values, make public fn new_tcp_socket

- vlib/v/gen/c/fn.v
This PR refactor to streamline gen_map_method_call().
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZhNzUyNDQzYjBiYWU0OTU4Y2M1YjkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.t46LcWGJskubYRaErTpkI3bvv-GWUaVfJOdCK2Vbve8">Huly&reg;: <b>V_0.6-20819</b></a></sub>
> cgen: refactor to streamline gen_map_method_call()

- vlib/v/checker/checker.v
- vlib/v/checker/tests/alias_to_generic_err.out
- vlib/v/checker/tests/alias_to_generic_err.vv
- vlib/v/checker/tests/any_type_err.out
Fix #22359
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZhN2NjNDQzYjBiYWU0OTU4Y2UyYTQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.GZuO0UZL4XXQnn-8sLZIULhcspvYbmInKidZhKYjZ0k">Huly&reg;: <b>V_0.6-20823</b></a></sub>
> checker: fix missing check for alias to generic type

- vlib/v/gen/c/cgen.v
- vlib/v/tests/consts/const_array_fixed_test.v
Fix #22357
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZhODRlODQzYjBiYWU0OTU4ZDI1ZDkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.kOqSreeHIbfcT6pQlRXbuaooMh5eIstvEcby4raGi-w">Huly&reg;: <b>V_0.6-20827</b></a></sub>
> cgen: fix codegen for const of fixed array

- vlib/net/tcp_simple_client_server_test.v
In some systems the IP address ::ffff:127.0.0.1 (which is equivalent to the local loopback address 127.0.0.1) it's used, allow to prevent the test fail
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZjNDA4MjQzYjBiYWU0OTVhMWE2YmMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.fINV4L4cid8vY97OUs331xBHNgop1k0I6mdkFgh12a8">Huly&reg;: <b>V_0.6-20847</b></a></sub>
> net: Allow special cases of ipv6 with ipv4 format

- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/c/str.v
- vlib/v/tests/c_structs/cstruct_arr_map_test.c.v
Fix #22379
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZiZWY2MjQzYjBiYWU0OTU5ZTI5MDAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.6ipcZG_zoeMbNmZ5DoXX7L_Y_QBJ1PhNzskvVw_Shog">Huly&reg;: <b>V_0.6-20843</b></a></sub>
> cgen: fix auto str for array and map for C struct

- vlib/v/gen/c/cgen.v
- vlib/v/tests/enums/enum_with_comptime_const_test.v
This PR fix enum with comptime const value (fix #22386).
- Fix enum with comptime const value.
- Add test.
```v
const enum_value = $if linux { 1 } $else { 2 }
pub enum Test {
a = enum_value
}
fn main() {
println(Test.a)
}
a
```
> cgen: fix enum with comptime const value (fix #22386)

- vlib/v/scanner/scanner.v
- vlib/v/scanner/tests/empty_character_literal_err.out
- vlib/v/scanner/tests/invalid_character_literal_err_1.out
- vlib/v/scanner/tests/invalid_character_literal_err_2.out
- vlib/v/scanner/tests/newline_character_literal_err.out
- vlib/v/scanner/tests/unknown_escape_sequence_in_ident_char_1_err.out
When using "`" for literals that are not characters, the compiler recommends using quotes for string, so far everything is fine, the problem is that when the compiler recommends that, it returns to showing the position where the error occurs, which is unnecessary, since the position is already shown previously. 
This PR removes that part of the suggestion.
Before:
```v
main.v:2:9: error: invalid character literal `ABC` => `ABC` ([`A`, `B`, `C`]) (more than one character)
2 |     _ = `ABC`
|         ^
3 | }
Details: 
main.v:2:9: details: use quotes for strings, backticks for characters
2 |     _ = `ABC`
|         ^
3 | }
```
After:
```v
main.v:2:9: error: invalid character literal `ABC` => `ABC` ([`A`, `B`, `C`]) (more than one character)
2 | …
```
> scanner: remove redundancy from the message suggesting to use quotes instead of backticks for characters

- vlib/v/preludes/test_runner_normal.v
- vlib/v/tests/skip_unused/assert_with_extra_message_works_test.run.out
- vlib/v/tests/skip_unused/assert_with_extra_message_works_test.skip_unused.run.out
- vlib/v/tests/skip_unused/assert_works_test.run.out
- vlib/v/tests/skip_unused/assert_works_test.skip_unused.run.out
Following a discussion in Discord: https://discord.com/channels/592103645835821068/592106336838352923/1291054248938836019 .
Before:
After:
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZkYmNjZjQzYjBiYWU0OTViMWZlZWEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.Pwdf25iYF54kVY-6RwIL-Onj4RFD2EMD45DBPeh1IXY">Huly&reg;: <b>V_0.6-20855</b></a></sub>
> tests: use `value` and show the .len field for the left/right values shown in failing assertions

- vlib/v/gen/c/struct.v
- vlib/v/tests/structs/struct_field_fixed_array_init_with_default_value_test.v
This PR fix struct fixed array field init with default value (fix #22392).
- Fix struct fixed array field init with default value.
- Add test.
```v
type Mat4 = [16]f32
pub fn mat4(x0 f32, x1 f32, x2 f32, x3 f32, x4 f32, x5 f32, x6 f32, x7 f32, x8 f32, x9 f32, x10 f32, x11 f32, x12 f32, x13 f32, x14 f32, x15 f32) Mat4 {
return [
x0,
x1,
x2,
x3,
x4,
x5,
x6,
x7,
x8,
x9,
x10,
x11,
x12,
x13,
x14,
x15,
]!
}
pub fn unit_m4() Mat4 {
return mat4(f32(1), 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1)
}
struct GameObject {
mut:
transform Mat4 = unit_m4()
}
fn main() {
p := GameObject{}
println(p)
assert p.transform[0] == 1.0
assert p.transform[1] == 0.0
assert p.transform[5] == 1.0
}
GameObject{
transform:     Mat4([1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, …
```
> cgen: fix struct fixed array field init with default value (fix #22392)

- vlib/v/gen/c/cgen.v
This PR perfect enum with comptime const value (related #22388).
- Avoid non-precomputed const variable names that contain const.
> cgen: perfect enum with comptime const value (related #22388)

- vlib/v/ast/table.v
- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/checker/return.v
- vlib/v/checker/str.v
- vlib/v/tests/generics/lamda_param_and_ret_test.v
Fix #22384
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZkMzk1OTQzYjBiYWU0OTVhYzM4OGQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.0khtODdqGOTCkAvSa5xaKM_RnNTfC95hakPteFuCvOg">Huly&reg;: <b>V_0.6-20849</b></a></sub>
> checker: fix lambda generic param and return validation 

- vlib/v/gen/c/cgen.v
- vlib/v/tests/global_fixed_arr_init_test.v
Fix #22402
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZlOWFhNTQzYjBiYWU0OTViZGQxZmMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.pKRqGjzsm-dys_2E_KjGV5vC6To3ohnWfaHRCsaOKgc">Huly&reg;: <b>V_0.6-20865</b></a></sub>
> cgen: fix global decl type default generation for fixed array

- vlib/v/checker/checker.v
- vlib/v/checker/match.v
- vlib/v/checker/tests/fn_return_void_fn_call_err.out
- vlib/v/checker/tests/fn_return_void_fn_call_err.vv
- vlib/v/tests/fns/fn_return_match_expr_with_result_test.v
This PR check fn return void fn call (no value) (fix #22389).
- Check fn return void fn call (no value).
- Fix return match expr with result.
- Add tests.
```v
fn main() {
install_command(['github:some/thing'], 1) or { panic(err) }
}
pub fn install_command(args []string, verbosity int) ! {
if args.len == 0 {
return error('${@FN} requires an argument')
}
component := args[0]
if component.count(':') == 0 {
return install_command(['github:${component}'], verbosity)
}
source := component.all_before(':')
if source != 'github' {
return error('${@FN} unknown source `${source}`')
}
unit := component.all_after(':')
return match source {
'github' {
install_from_github(unit, verbosity)!
}
else {
error('${@FN} unknown source `${source}`')
}
}
}
fn install_from_github(unit string, verbosity int) ! { …
```
> checker: check fn return void fn call (no value) (fix #22389)

- vlib/v/builder/msvc_windows.v
Related to https://github.com/vlang/v/pull/22405 .
Building with `-cc msvc` is hampered, when the paths stored in the .rsp file, have non ASCII characters. This PR solves it, by adding an explicit BOM header, so that cl.exe can then interpret the content without guessing and failing, no matter what the current code page is.
TODO: make the msvc option handling code respect -no-rsp.
> v.builder: write an UTF8 BOM header for the .rsp file, when using '-cc msvc'

- vlib/builtin/utf8.c.v
- vlib/builtin/utf8.v
- vlib/builtin/utf8_test.v
- vlib/v/builder/cc.v
- vlib/v/builder/msvc_windows.v
…nsi_not_null_terminated
As PR #22405 said, tcc will fail with non-ASCII filename under Windows 10.
So this PR try to make the .rsp file encoded in ANSI.
Also, builtin provide some new funcs help do the job UTF-8=>ANSI.
> builder: use ANSI .rsp file under Windows

- vlib/builtin/utf8.v
- vlib/v/builder/msvc_windows.v
- **v.builder: restore encoding used for .rsp files, when `-cc msvc` is used (fix msvc builds with non ASCII paths on windows 11)**
- **builtin: fix 'expression result unused' warning when building with clang**
> v.builder: fix building with `-cc msvc` and non ASCII characters in paths on windows 11

- vlib/strconv/format_mem.c.v
- vlib/strconv/format_test.v
- vlib/v/tests/builtin_strings_and_interpolation/string_interpolation_float_fmt_test.v
- vlib/v/tests/casts/cast_to_empty_interface_test.v
fix issue #22421 , it is a bug in `strconv.remove_tail_zeros()`
```v
assert strconv.remove_tail_zeros('1.234000000000') == '1.234'
assert strconv.remove_tail_zeros('1.0000000') == '1'
assert strconv.remove_tail_zeros('1234') == '1234'
assert strconv.remove_tail_zeros('1.00000000007') == '1.00000000007'
```
> strconv: fix remove_tail_zeros bug

- vlib/builtin/string_interpolation.v
- vlib/strconv/f64_str.c.v
- vlib/strconv/format_test.v
> strconv: fix e/g format

- vlib/v/ast/table.v
- vlib/v/parser/parse_type.v
- vlib/v/tests/generics/generic_fn_type_with_different_generic_type_test.v
This PR fix generic fn type with different generic type call (fix #22306).
- Fix generic fn type with different generic type call.
- Add test.
```v
type Fn[T] = fn () T
fn problem[X](f Fn[X]) X {
return f[X]()
}
fn foo() int {
return 1
}
fn main() {
t := problem[int](foo)
println(t)
}
1
```
> ast, parser: fix generic fn type with different generic type call (fix #22306)

- vlib/v/checker/fn.v
> checker: reduce allocations in Checker.method_call

- vlib/v/ast/ast.v
Add comment for farray
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA0MDNlMmI5ODBmNDFkYjY2Y2ZlZjIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.pUj6-aNOl4WDPk0c2eFsXkJzyBLbmexyFqwrBERKWjg">Huly&reg;: <b>V_0.6-20899</b></a></sub>
> v.ast: comment on the `IndexExpr.is_farray` field

- vlib/builtin/string.v
- vlib/builtin/string_test.v
- vlib/v/scanner/scanner.v
This PR adds a new method called `wrap` to `string`, this method was previously introduced in commit 8d1ba46875c8183bfffde4642d824f7b6d1dfcfd.
The `wrap` function added to the `v.scanner` module is also removed and the new method is used instead.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA0MDc2OGI5ODBmNDFkYjY2ZDA2NDYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.1SrquIOgR6e10iy5SixxbVBOD6OiB6n__F5N9-ygRYA">Huly&reg;: <b>V_0.6-20902</b></a></sub>
> builtin: add `string.wrap` method + tests

- vlib/v/checker/match.v
- vlib/v/tests/return_match_expr_of_sumtype_do_not_cast_to_ierror_test.v
- vlib/v/tests/return_match_expr_of_sumtype_result_test.v
Fixes #22435.
When checking match branch expression branch expression type, there was a check to cast yielded value to an `IError` when match return type is a Result and branch expression type is struct.
I added an additional test so that the cast (and check to ensure the struct conforms to the `IError` interface) does not occur when the return type is a sumtype and the struct is one of the sumtype types.
Tests updated to cover this
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA0NDYyMmI5ODBmNDFkYjY2ZDYwOTEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.lbvkaNkxRJ-eV-Ua7mKCPlfOytDK-cu3fHrRSOhGecU">Huly&reg;: …
> checker: don't cast match branch structs to IError when in sumtype

- vlib/v/parser/parse_type.v
- vlib/v/tests/generics/generics_method_chaining_call_test.v
This PR fix generics method chaining call (fix #22418).
- Fix generics method chaining call.
- Add test.
```v
struct Seq[T] {
ar []T
}
type MapFn[T, K] = fn (T) K
fn (s Seq[T]) map[K](map_fn MapFn[T, K]) Seq[K] {
mut map_ar := []K{cap: s.ar.len}
for _, i in s.ar {
map_ar << map_fn[T, K](i)
}
return Seq[K]{map_ar}
}
fn main() {
s := Seq[string]{['one', 'two']}
.map[int](fn (element string) int {
match element {
'one' { return 1 }
'two' { return 2 }
else { return -1 }
}
})
.map[int](fn (element int) int {
return element + 2
})
println(s)
}
Seq[int]{
ar: [3, 4]
}
```
> parser: fix generics method chaining call (fix #22418)

- vlib/v/ast/table.v
- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/checker/struct.v
- vlib/v/tests/structs/struct_array_generic_field_test.v
Fix https://github.com/vlang/v/issues/22406
(last one was reverted)
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA0NDJjMWI5ODBmNDFkYjY2ZDYwMmMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.oCt7weJHHK2gvTc85FluGzPzAK448nw2BeRUrVhPbpQ">Huly&reg;: <b>V_0.6-20904</b></a></sub>
> checker: fix struct array generic field

- vlib/json/json_fixed_array_test.v
- vlib/v/gen/c/json.v
Fix #22369
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA1MTUzZGI5ODBmNDFkYjY3MDRkN2IiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.J2vZHbU2o4bxGzNlsx9SyWv_SoH694UsBha_dQROqWE">Huly&reg;: <b>V_0.6-20909</b></a></sub>
> json: fix array fixed encode/decode

- vlib/math/big/special_array_ops.v
This PR will improve `left_shift_digits_in_place` and `right_shift_digits_in_place` performance.
Before:
```sh
134752       4252.705ms          31559ns math__big__left_shift_digits_in_place
```
After:
```sh
134752         31.996ms            237ns math__big__left_shift_digits_in_place
```
> math.big: improve the performance of left_shift_digits_in_place and right_shift_digits_in_place

- vlib/picoev/picoev.v
Fix #22292
Just noticed running `examples/veb/veb_assets/vweb_assets.v`
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA2NjdkZGI5ODBmNDFkYjY4ODcyNDIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.BxEjstnqB3OkW18WEmgzptDoBFvO16FB2-PmK2Rmk2w">Huly&reg;: <b>V_0.6-20922</b></a></sub>
> picoev: fix wrong return on failure

- vlib/v/checker/str.v
- vlib/v/tests/unicode_escape_test.v
Fix #22427
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA2NjNkYWI5ODBmNDFkYjY4ODBmNGYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.ZLr_PAE7r-h3NfmA3JontiDTl2x4pstouPjSwhmccvE">Huly&reg;: <b>V_0.6-20921</b></a></sub>
> checker: fix missing check for escape char on unicode checker

- vlib/v/gen/c/assign.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/fns/multi_return_array_fixed_test.v
Fix #22451
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA1YWEwOGI5ODBmNDFkYjY3M2FmMjMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.duaN6zx7wq1f1cMs_XRG4M2LacaQImhrUHxV9FDVSdU">Huly&reg;: <b>V_0.6-20914</b></a></sub>
> cgen: fix codegen for multi return with array fixed

- vlib/strings/builder.c.v
- vlib/v/ast/ast.v
- vlib/v/checker/fn.v
- vlib/v/gen/c/text_manipulation.v
- vlib/v/parser/fn.v
- vlib/v/transformer/transformer.v
- **transformer: add support for instrumenting the V compiler with `-d trace_transformer`**
- **transformer: optimise out simple string interpolations inside sb.write_string/1 calls**
> transformer: optimise calls to write string with simple interpolations

- vlib/v/parser/parser.v
- vlib/v/tests/enums/enum_field_name_same_as_keyword_test.v
This PR fix enum field name same as keyword (fix #22455).
- Fix enum field name same as keyword.
- Add test.
```v
enum TypeKind {
none
const
enum
struct
interface
sum_type
i32
f64
}
fn type_kind(kind TypeKind) string {
return '${kind}'
}
fn main() {
mut ret := type_kind(TypeKind.none)
println(ret)
assert ret == 'none'
ret = type_kind(TypeKind.struct)
println(ret)
assert ret == 'struct'
}
none
struct
```
> parser: fix enum field name same as keyword (fix #22455)

- vlib/v/gen/c/cgen.v
- vlib/v/tests/options/option_if_expr_with_panic_call_test.v
This PR fix option if expr with panic() call (fix #22467).
- Fix option if expr with panic() call.
- Add test.
```v
fn main() {
mut x := ?string(none)
x = if true {
''
} else {
panic('')
}
println(x)
}
Option('')
```
> cgen: fix option if expr with noreturn fn call (fix #22467)

- vlib/v/ast/str.v
This PR cleanup in stringify_fn_after_name().
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA3OWM5OTBiYjJlYTE0Yjc5YTI0MzgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.8ZDIz-kCYsLZEUcwtwvCq2rK8a0mFx6EH0Efcgk0CGI">Huly&reg;: <b>V_0.6-20931</b></a></sub>
> ast: cleanup in stringify_fn_after_name()

- vlib/v/checker/infix.v
Cleanup infix expr.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA3ZDM5MzBiYjJlYTE0Yjc5YTUzYzYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.HLbGtC0mlTbA7Pbo5QWs8slUPL90GbZjeSY3s-lNdz8">Huly&reg;: <b>V_0.6-20934</b></a></sub>
> checker: reduce sym resolution calls on infix checking

- vlib/v/checker/return.v
- vlib/v/checker/tests/empty_fn_noreturn_err.out
- vlib/v/checker/tests/empty_fn_noreturn_err.vv
- vlib/v/tests/reflection_test.v
Fix #22468
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA3YmEzMzBiYjJlYTE0Yjc5YTNkOGEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.juYaDZlUNeFZPrvOl06dG4A1C2URs8iQqPaW4kX5Csk">Huly&reg;: <b>V_0.6-20932</b></a></sub>
> checker: fix missing check for empty noreturn fn 

- cmd/tools/vrepl.v
This PR replace enum field name `@none` with `none` in vrepl.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA3ZGI4N2U1OWQ0N2Y3YjVkMDcwNDkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.pWFYEon_yHDxUqq-Tc5wT-npxuK3Vk4Q_a6P2HQfs7U">Huly&reg;: <b>V_0.6-20935</b></a></sub>
> vrepl: replace enum field name `@none` with `none`

- vlib/v/checker/infix.v
- vlib/v/tests/aliases/alias_with_op_overloading_test.v
Fix #22471
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA3YzZiODBiYjJlYTE0Yjc5YTQ4YzQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.y0WgMGte42Aakh1bie2jeW99Mc8PNhSGZx7xa9LW0sQ">Huly&reg;: <b>V_0.6-20933</b></a></sub>
> checker: fix wrong overload operator checking for generic aliased type

- cmd/tools/vwhere/finder.v
- cmd/tools/vwhere/finder_utils.v
- cmd/tools/vwhere/vwhere_test.v
- vlib/sokol/gfx/enums.v
- vlib/sokol/sapp/sapp.c.v
- vlib/v/tests/interfaces/interface_with_multi_nested_embed_3_test.v
This PR replace enum field name '@xxx' with 'xxx'.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA3ZjIzMmM3ZDZhNTZhOGY4ZDViNTciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.PzpdRRdPPJWU0ek-SDmruPLP7bNYCM7HbAkjBXJpZwY">Huly&reg;: <b>V_0.6-20937</b></a></sub>
> all: replace enum field name '@xxx' with 'xxx'

- examples/2048/2048.v
- examples/sokol/02_cubes_glsl/cube_glsl.v
- examples/sokol/03_march_tracing_glsl/rt_glsl.v
- examples/sokol/04_multi_shader_glsl/rt_glsl.v
- examples/sokol/05_instancing_glsl/rt_glsl.v
- examples/sokol/06_obj_viewer/modules/obj/rend.v
- examples/sokol/particles/particles.v
- vlib/clipboard/x11/clipboard.c.v
- vlib/db/mysql/_cdefs.c.v
- vlib/db/mysql/orm.c.v
- vlib/db/mysql/result.c.v
- vlib/db/mysql/stmt.c.v
- vlib/json/cjson/cjson_wrapper.c.v
- vlib/net/address.c.v
- vlib/sokol/gfx/gfx_structs.c.v
- vlib/sokol/sapp/sapp_structs.c.v
- vlib/v/checker/comptime.v
This PR replace struct field name '@type' with 'type'.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA4ODk4NWM3ZDZhNTZhOGY4ZTFmZmQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.3Ty6xl5jT-p8d98uXxcGPu9s0kQIBsqI6e_D2-AIfiE">Huly&reg;: <b>V_0.6-20943</b></a></sub>
> all: replace struct field name '@type' with 'type'

- vlib/picoev/socket_util.c.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/option_map_err.out
- vlib/v/checker/tests/option_map_err.vv
> checker: fix missing checker for option map indexing

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/testdata/c_extern_on_C_fn_declarations.c.must_have
- vlib/v/gen/c/testdata/c_extern_on_C_fn_declarations.vv
- **cgen: allow for `@[c_extern] fn C.somename(param1 int, param2 &char) &char`**
- **add a test .vv/.c.must_have pair**
> cgen: allow for `@[c_extern] fn C.somename(param1 int, param2 &char) &char`

- vlib/v/checker/if.v
- vlib/v/tests/options/option_unwrap_ifexpr_test.v
Fix #22500
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBhNWZmMGM3ZDZhNTZhOGY5NGVkNTEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.ZzqqLo8xaQZh7Sul5Yhc4Tskwr3fiqWCyVdMjaWyyh0">Huly&reg;: <b>V_0.6-20961</b></a></sub>
> v: implement option unwrapping on else branch

- vlib/v/parser/if_match.v
- vlib/v/tests/fns/static_call_on_match_test.v
Fix #22505
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBhZGM4MDQxNjJiMDJlNWRkMzM1MWUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.YQF_sffgjGwsIqrXzd7ltUhKUXT3HggpsfBy5Y5VUQ0">Huly&reg;: <b>V_0.6-20964</b></a></sub>
> parser: allow static method call on match branch

- examples/veb/file_transform/file_transform.v
Close #22508
Fix veb example file_transform port typo
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBiOTRkNTQxNjJiMDJlNWRkM2YyNzEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.NpPz5c34VWBH-I2tI-6p9jocQoHvQN0NtkCDOpWSsXo">Huly&reg;: <b>V_0.6-20968</b></a></sub>
> veb: fix veb example file_transform port typo

- vlib/v/checker/str.v
- vlib/v/comptime/comptimeinfo.v
- vlib/v/tests/generics/generic_lambda_inference_test.v
Fix #22497
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBiMTEyMTQxNjJiMDJlNWRkM2MyZTQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.0HALGzwpEnt_062l0HnS3ly42ZownWQXytSzrDYZQEI">Huly&reg;: <b>V_0.6-20966</b></a></sub>
> checker: fix generic lambda with late concrete type inference

- cmd/tools/oldv.v
Fixes a few grammatical errors and removes an extraneous `"` from the usage output.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBiZDA0ZjQxNjJiMDJlNWRkNDE2YzQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.uu0onQYXJ0vyoC54GlPV6tFI9hYDKYOWxmIlvVI7NAM">Huly&reg;: <b>V_0.6-20971</b></a></sub>
> oldv: grammar changes in usage

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/fn_call_concrete_type_keep.vv
Fix #22516
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBiZmIwYzQxNjJiMDJlNWRkNDI1NGQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.3Yf1Awjm9C0o32-qVuYbWV0h7CCHINQ3wtbywQxvs4w">Huly&reg;: <b>V_0.6-20973</b></a></sub>
> fmt: keep `C.` prefix for concrete type on generic fn call

- vlib/v/util/util.v
- **v.util: relax the `vup` recompilation; try an older `vup` tool, if it is still present; add more diagnostic messages**
> v.util: relax the `vup` tool recompilation; try an older `vup` tool, if it is still present; add more failure diagnostic messages 

- examples/net_resolve.v
This PR change var name '@type' to 'type' in examples/net_resolve.v.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBkY2JlYzhkY2MwMDM2MTU1YWVmYjQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.h9OR_7YLSWlLsiXUF1VDw0XomcozWdGe_XaESs4BXo0">Huly&reg;: <b>V_0.6-20981</b></a></sub>
> examples: change var name '@type' to 'type' in net_resolve.v

- vlib/stbi/stbi.c.v
- vlib/stbi/stbi_test.v
- **stbi: fix loading of images, that have .nr_channels != 4 (RGBA)**
- **cleanup stbi_test.v, eliminate warnings with latest V**
- **add test_load_image_with_channels_different_than_4**
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBlMTk0YThkY2MwMDM2MTU1YWY3OGUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.dyMzP4YQxUYpvmuv5keqXeTXe9AmoquHuEFISVlfw5c">Huly&reg;: <b>V_0.6-20982</b></a></sub>
> stbi: fix `nr_channels` property, after a forced conversion on load

- vlib/v/checker/containers.v
- vlib/v/checker/tests/use_empty_map_literal_to_initialize_anon_struct_error.out
- vlib/v/checker/tests/use_empty_map_literal_to_initialize_anon_struct_error.vv
This PR clarifies the error message about using empty map literal to initialize structs, in addition to that it prevents another error message from appearing when using empty map literal with anonymous structs.
Fix #22498.
```v
$ cat main.v
struct AStructName {
foo  int
anon struct {
bar int
}
}
fn main() {
s := AStructName{5, {}}
println(s)
}
```
```sh
$ v main.v
main.v:9:22: error: `{}` cannot be used to initialize anonymous structs. Use `struct{}` instead.
7 | 
9 |     s := AStructName{5, {}}
|                         ~~
10 |     println(s)
11 | }
```
> checker: clarify error message about using empty map literal to initialize structs

- vlib/v/checker/infix.v
- vlib/v/tests/conditions/ifs/if_expr_with_compound_conds_test.v
This PR fix if expr with compound conditions (fix #22496).
- Fix if expr with compound conditions.
- Add test.
```v
type Foo = int | []int
fn main() {
a := Foo([3])
if a is []int && a[0] == 3 {
println('works')
}
}
works
```
> checker: fix if expr with compound conditions (fix #22496)

- vlib/v/checker/infix.v
- vlib/v/tests/conditions/ifs/if_expr_with_compound_conds_1_test.v
- vlib/v/tests/conditions/ifs/if_expr_with_compound_conds_2_test.v
- vlib/v/tests/conditions/ifs/if_expr_with_compound_conds_3_test.v
- vlib/v/tests/conditions/ifs/if_expr_with_compound_conds_4_test.v
- vlib/v/tests/conditions/ifs/if_expr_with_compound_conds_test.v
This PR perfect if expr with compound conditions.
- Perfect if expr with compound conditions.
- Add tests.
```v
type Foo = int | []int
fn works() bool {
arr := [1, 2, 3]
a := Foo(2)
if a is int && arr[a] == 3 {
println('works')
return true
}
return false
}
fn test_if_expr_with_compound_conds() {
assert works()
}
```
```v
type Foo = int | []int
fn works() bool {
a := Foo(2)
if a is int && '${a}' == '2' {
println('works')
return true
}
return false
}
fn test_if_expr_with_compound_conds() {
assert works()
}
```
```v
type Foo = int | []int
fn works() bool {
arr := [1, 2, 3]
a := Foo(2)
if a is int && unsafe { arr[..a] == [1, 2] } {
println('works')
return true
}
return false
}
fn test_if_expr_with_compound_conds() {
assert works()
}
```
> checker: perfect if expr with compound conditions

- vlib/builtin/array.v
- vlib/builtin/string.v
- vlib/builtin/string_test.v
- vlib/encoding/base58/base58_usage_test.v
- vlib/os/file_test.v
- vlib/os/os_test.c.v
- vlib/v/compiler_errors_test.v
- vlib/v/gen/js/tests/interp.v
- vlib/v/tests/builtin_strings_and_interpolation/cstrings_test.c.v
- vlib/v/tests/builtin_strings_and_interpolation/string_interpolation_test.v
- vlib/v/tests/fns/go_call_fn_return_test.v
- **builtin: implement a `s.hex()` method, allowing shortening `s.bytes().hex()` chains, and reducing the intermediate allocations; add tests for it**
- **replace usages of s.bytes().hex() with just s.hex()**
> builtin: implement a `s.hex()` method, allowing shortening `s.bytes().hex()` chains, and reducing the intermediate allocations; add tests for it

- vlib/x/json2/decoder2/decode.v
- vlib/x/json2/decoder2/decode_test.v
This is a part of json2 decoder2 rewriting in https://github.com/enghitalo/v/tree/json2/decode2-precalc-and-validation
It was splitted to help in review
This fraction is related to:
- new json cheking
- v type checking
- new decoding strategy using `ValueInfo`
OBS: I am thinking about split the already done work in around 5 parts. What not means this work is done
benchmark still great
```sh
./v -prod crun vlib/x/json2/decoder2/tests/bench.v                          ─╯
SPENT    35.895 ms in old_json.decode(Stru, json_data)!
SPENT    12.861 ms in decoder2.decode[StructType[string]](json_data1)!
SPENT     9.902 ms in old_json.decode(StructType[string], json_data1)!
SPENT    13.673 ms in decoder2.decode[StructTypeOption[string]](json_data1)!
SPENT    11.536 ms in …
```
> json2: new decoder2 part 1

- vlib/x/json2/decoder2/decode.v
- vlib/x/json2/decoder2/decode_test.v
- vlib/x/json2/decoder2/tests/bench.v
- vlib/x/json2/decoder2/tests/decode_number_and_boolean_test.v
```v
json.decode[int]('1234567890')!
```
```sh
SPENT   331.243 ms in old_json.decode(Stru, json_data)!
SPENT   121.179 ms in decoder2.decode[StructType[string]](json_data1)!
SPENT    85.539 ms in old_json.decode(StructType[string], json_data1)!
SPENT   133.756 ms in decoder2.decode[StructTypeOption[string]](json_data1)!
SPENT    83.031 ms in old_json.decode(StructTypeOption[string], json_data1)!
SPENT   119.793 ms in decoder2.decode[StructType[int]](json_data2)!
SPENT    84.340 ms in old_json.decode(StructType[int], json_data2)!
SPENT   115.752 ms in decoder2.decode[map[string]string](json_data1)!
SPENT   195.674 ms in old_json.decode(map[string]string, json_data1)!
***simple types***
SPENT    24.796 ms in …
```
> decoder2: decode bool and numbers

- vlib/regex/regex.v
- vlib/regex/regex_util.v
- vlib/v/fmt/fmt.v
This PR optimize receiver with reference because struct `RE` and struct `Fmt` are relatively large structures.
> regex, vfmt: optimize receiver with reference

- vlib/v/gen/c/cgen.v
- vlib/v/tests/sumtypes/sumtype_map_set_test.v
> cgen: fix map_set codegen for sumtype array variant with autofree
