vlang/v

- README.md
Link to the new one version instead of deprecated one
> docs: change link in docs for the builtin framework, from vlib/vweb to vlib/veb

- vlib/encoding/utf8/east_asian/east_asian_width.v
- vlib/encoding/utf8/utf8_util.v
- vlib/encoding/utf8/utf8_util_test.v
- vlib/x/ttf/render_bmp.v
`ustring`  has been replaced with `[]rune` in V 0.3 https://github.com/vlang/v/discussions/14895
`uchar`  should therefore be replaced with `rune` in the `encoding.utf8` module:
- added  `rune`-method --><br />deprecated `uchar` -method
public: 
-  `get_rune(s string, index int) rune` --><br />`get_uchar(s string, index int) int`
- `is_rune_punct(r rune) bool` --><br />`is_uchar_punct(uchar int) bool`
- `is_rune_global_punct(r rune) bool` --><br />`is_uchar_global_punct(uchar int) bool`
private:
- `find_punct_in_table(in_code rune, in_table []rune) rune`  --><br />`find_punct_in_table(in_code int, in_table []int) int`
- `unicode_punct_western rune[]` --><br />`unicode_punct_western int[]`
- `unicode_punct rune[]` --><br />`unicode_punct int[]`
> encoding.utf8: replace uchar with rune

- doc/docs.md
- vlib/builtin/utf8.v
- vlib/encoding/utf8/utf8_util.v
- vlib/readline/readline_default.c.v
- vlib/readline/readline_js.js.v
- vlib/readline/readline_nix.c.v
- vlib/readline/readline_windows.c.v
This PR only changes the docs and comments. 
It follows up on https://github.com/vlang/v/discussions/22461
The goal of this PR is to make it easier to understand where V uses UTF-8 and where UTF-32
> utf8, readline: clarify UTF-8 vs UTF-32 usage

- vlib/orm/orm_insert_test.v
- vlib/v/gen/c/orm.v
Fix #22583 .
- **cgen: fix hardcoded db__pg__DB_last_id for `x := sql db { insert address into Address }`**
The problem this solves, was reported on Discord: https://discord.com/channels/592103645835821068/1146520093824651385/1297062271914344459 .
A local reproduction is:
```v
struct Address {
street string
number int
}
dblite := sqlite.connect('my_database.db')!
address := Address{'abc', 123}
dump(address)
sql dblite {
create table Address
} or {}
aid := sql dblite {
insert address into Address
} or {
println('error inserting address')
panic(err)
}
dump(aid)
```
... producing a C error on `master`.
> cgen: fix hardcoded `db__pg__DB_last_id` for `x := sql db { insert address into Address }`

- vlib/maps/maps.v
- vlib/maps/maps_clone_test.v
> maps: fix map cloning

- vlib/x/json2/decoder2/decode.v
- vlib/x/json2/decoder2/decode_test.v
- vlib/x/json2/decoder2/tests/bench.v
- vlib/x/json2/decoder2/tests/decode_object_test.v
- vlib/x/json2/decoder2/tests/decode_string_test.v
- vlib/x/json2/decoder2/tests/decode_struct_test.v
- Improve performance between 50% and 200%
- Replace array and node to only LinkedList
- decode string
- decode map
- decode array
- decode time
```sh
./v wipe-cache && ./v -prod -cc gcc crun vlib/x/json2/decoder2/tests/bench.v 
V cache folder /home/hitalo/.vmodules/.cache was wiped.
V tmp.c and tests folder folder /tmp/v_1000 was wiped.
SPENT   349.628 ms in decoder2.decode[Stru](json_data)!
SPENT   369.915 ms in old_json.decode(Stru, json_data)!
SPENT    99.198 ms in decoder2.decode[StructType[string]](json_data1)!
SPENT    92.955 ms in old_json.decode(StructType[string], json_data1)!
SPENT   121.837 ms in decoder2.decode[StructTypeOption[string]](json_data1)!
SPENT   143.498 ms in …
```
> x.json2.decoder2: use Linked List data structure strategy

- vlib/v/gen/c/array.v
- vlib/v/tests/builtin_arrays/fixed_array_literal_infix_test.v
> cgen: fix array contains codegen for fixed array

- vlib/v/gen/c/array.v
- vlib/v/tests/builtin_arrays/fixed_array_literal_infix_test.v
This PR improve fixed array literal in operation and index calls (related #22579).
- Improve fixed array literal in operation and index calls.
- Add tests.
```v
fn test_array_of_fixed_array_in_op() {
mut a := [][2]int{}
a << [1, 2]!
println([1, 2]! in a)
ret := [1, 2]! in a
println(ret)
assert ret
}
fn test_fixed_array_of_fixed_array_in_op() {
mut a := [2][2]int{}
a[0] = [1, 2]!
println([1, 2]! in a)
ret := [1, 2]! in a
println(ret)
assert ret
}
fn test_array_of_fixed_array_index() {
mut a := [][2]int{}
a << [1, 2]!
println(a.index([1, 2]!))
ret := a.index([1, 2]!)
println(ret)
assert ret == 0
}
```
> cgen: improve fixed array literal in operation and index calls (related #22579)

- vlib/v/checker/check_types.v
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE0ZmI4YTJlYjk5ZmZhYzRiMWY5ZTEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.8zl5lC2b0GKElIqEgL6dTfxJqEayRSxXxQobuZWOK-g">Huly&reg;: <b>V_0.6-21045</b></a></sub>
> checker: optimise identical type checking

- vlib/x/json2/decoder2/decode.v
- vlib/x/json2/decoder2/tests/bench.v
- vlib/x/json2/decoder2/tests/decode_struct_test.v
full support to alias, thanks to @felipensp :partying_face:
```sh
./v wipe-cache && ./v -prod -cc gcc crun vlib/x/json2/decoder2/tests/bench.v 
V cache folder /home/hitalo/.vmodules/.cache was wiped.
V tmp.c and tests folder folder /tmp/v_1000 was wiped.
SPENT   342.294 ms in decoder2.decode[Stru](json_data)!
SPENT   388.660 ms in old_json.decode(Stru, json_data)!
SPENT   107.604 ms in decoder2.decode[StructType[string]](json_data1)!
SPENT   107.973 ms in old_json.decode(StructType[string], json_data1)!
SPENT   129.924 ms in decoder2.decode[StructTypeOption[string]](json_data1)!
SPENT   145.859 ms in old_json.decode(StructTypeOption[string], json_data1)!
SPENT    66.341 ms in …
```
> x.json2.decoder2: full support to alias

- vlib/v/gen/c/cgen.v
Cgen `base_type()` caching
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE2Yjk0ZjRjMjRlYTI4ODIwMTcyYzUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.8Vf7I1Q4SrtrFzf6iXS_xjnsffrRD6oa4kGhva3RR0E">Huly&reg;: <b>V_0.6-21062</b></a></sub>
> cgen: cache the results of g.base_type/1

- vlib/v/gen/c/cgen.v
This PR add optimization to contains_ptr by caching its return.
new
old
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE1NjMxNDJlYjk5ZmZhYzRiNDgzZWMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.K9HObQQ0TQxxfTK2dA5bdF23QufqsykDLQTmpn9VHW0">Huly&reg;: <b>V_0.6-21054</b></a></sub>
> cgen: optimize caching contains_ptr return

- vlib/builtin/fixed_array_any_all_test.v
- vlib/v/checker/fn.v
- vlib/v/gen/c/array.v
- vlib/v/gen/c/fn.v
This PR implement fixed array methods any() and all().
- Implement fixed array methods any() and all().
- Add test.
```v
fn test_any_all_of_ints() {
mut ii := ia.any(it > 2)
println(ii)
assert ii
ii = ia.all(it > 1)
println(ii)
assert !ii
ii = ia.any(it == 2)
println(ii)
assert ii
ii = ia.all(it == 3)
println(ii)
assert !ii
}
fn test_any_all_of_strings() {
mut si := sa.any(it == 'b')
println(si)
assert si
si = sa.all(it == 'c')
println(si)
assert !si
}
fn test_any_all_of_voidptrs() {
mut pi := pa.any(it == voidptr(45))
println(pi)
assert pi
pi = pa.all(it == voidptr(123))
println(pi)
assert !pi
}
fn a() {}
fn b() {}
fn c() {}
fn v() {}
fn test_any_all_of_fns() {
fa := [a, b, c]!
mut fi := fa.any(it == …
```
> checker, cgen: implement fixed array methods any() and all()

- vlib/strings/builder.c.v
- vlib/v/gen/c/array.v
- vlib/v/gen/c/assert.v
- vlib/v/gen/c/assign.v
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/cmain.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/for.v
- vlib/v/gen/c/if.v
- vlib/v/gen/c/index.v
- vlib/v/gen/c/infix.v
- vlib/v/gen/c/live.v
- vlib/v/gen/c/match.v
- vlib/v/gen/c/orm.v
- vlib/v/gen/c/profile.v
- vlib/v/gen/c/spawn_and_go.v
- vlib/v/gen/c/str.v
- vlib/v/gen/c/str_intp.v
- vlib/v/gen/c/struct.v
- vlib/v/gen/c/text_manipulation.v
This PR aims to reduce calls to `g.writeln()`, `g.write()`, `sb.write_string()`, `sb.writeln()`.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE2NWJhMDRjMjRlYTI4ODJmZDZkMzYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.ut7oZb_avaVUH3-pac4BcVdnPgdQ9fD8GkcFZP41wHw">Huly&reg;: <b>V_0.6-21059</b></a></sub>
> cgen: reduce write calls (string_builder + gen.c)

- vlib/net/http/cookie.v
- vlib/picoev/picoev.v
use faster http_header_string method
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE3OTZiZGYwMmQ4YTAzZmIyZGYzYjgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.BkDaJpvGe1lxPYYMFLulQZm2_2wR1iXURZpfW1dMMkE">Huly&reg;: <b>V_0.6-21068</b></a></sub>
> picoev,net.http: use Time.http_header_string method, to improve performance

- vlib/builtin/string.v
10x faster in TCC
```v
import benchmark
const max_iterations = 1_000_000
fn main() {
value := 'abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz'
mut b := benchmark.start()
for i := 0; i < max_iterations; i++ {
value.starts_with('abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz')
// value.ends_with('pqrstuvwxyzabcdefghijklmnopqrstuvwxyz')
}
b.measure("value.starts_with('abcd')")
}
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE3OWZlZGYwMmQ4YTAzZmIyZGY3Y2MiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.o7v4jcrvPxhSOlIDmfjzuu …
> perf: `string.starts_with` and `string.ends_with` by 10x in TCC

- vlib/v/gen/c/reflection.v
- vlib/v/reflection/reflection.v
- vlib/v/tests/reflection_sym_test.v
Fix #22488
This PR extracts the mod name from the `name` to a new `mod` field.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE3ODk0M2YwMmQ4YTAzZmIyZGVhYWIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.L33MBqHmYSwHvkwGr-Hon3JgRP8fetH7TyipaR21txo">Huly&reg;: <b>V_0.6-21067</b></a></sub>
> reflection: split mod from typesymbol name

- vlib/builtin/fixed_array_contains_test.v
- vlib/v/checker/fn.v
- vlib/v/gen/c/array.v
- vlib/v/gen/c/fn.v
This PR implement fixed array method contains().
- Implement fixed array method contains().
- Add test.
```v
fn test_contains_of_ints() {
mut ii := ia.contains(2)
dump(ii)
assert ii
ii = ia.contains(5)
dump(ii)
assert !ii
}
fn test_contains_of_strings() {
mut si := sa.contains('b')
dump(si)
assert si
si = sa.contains('v')
dump(si)
assert !si
}
fn test_contains_of_voidptrs() {
mut pi := pa.contains(voidptr(45))
dump(pi)
assert pi
pi = pa.contains(unsafe { nil })
dump(pi)
assert !pi
}
fn a() {}
fn b() {}
fn c() {}
fn v() {}
fn test_contains_of_fns() {
fa := [a, b, c]!
mut fi := fa.contains(b)
dump(fi)
assert fi
fi = fa.contains(v)
dump(fi)
assert !fi
}
```
<sub><a …
> checker, gen: implement fixed array method contains()

- vlib/builtin/fixed_array_any_all_test.v
This PR improve fixed_array_any_all_test.v (related #22609).
- Add lambda expr tests.
```v
fn test_any_all_of_ints() {
assert ia.any(it > 2)
assert ia.any(|x| x > 2)
assert !ia.all(it > 1)
assert !ia.all(|x| x > 1)
assert ia.any(it == 2)
assert ia.any(|x| x == 2)
assert !ia.all(it == 3)
assert !ia.all(|x| x == 3)
}
fn test_any_all_of_strings() {
assert sa.any(it == 'b')
assert sa.any(|x| x == 'b')
assert !sa.all(it == 'c')
assert !sa.all(|x| x == 'c')
}
fn test_any_all_of_voidptrs() {
assert pa.any(it == voidptr(45))
assert pa.any(|x| x == voidptr(45))
assert !pa.all(it == voidptr(123))
assert !pa.all(|x| x == voidptr(123))
}
fn a() {}
fn b() {}
fn c() {}
fn v() {}
fn test_any_all_of_fns() {
fa := [a, …
```
> builtin: improve `fixed_array_any_all_test.v` (related #22609)

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/testdata/embed_with_prod_and_several_decoders.c.must_have
This PR improves the code generated by not using stack to alloc option struct to its immediate return and by returning literal values directly.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE3YWE3NWYwMmQ4YTAzZmIyZTk2ZDMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.1N6Z-NfS51PsjjADcC37LUJ4ynd04YpiBFC0rFnD6GQ">Huly&reg;: <b>V_0.6-21071</b></a></sub>
> cgen: optimise the generated code for returning literal values and option/result values

- vlib/builtin/fixed_array_any_all_test.v
This PR temporary fix fixed_array_any_all_test.v (related #22621).
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE4Njc0YWYwMmQ4YTAzZmIyZmExMTQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.EzfbhSU9l8S44mtfaCqIp-9VZbl8UDpA1MEiEmu49RY">Huly&reg;: <b>V_0.6-21073</b></a></sub>
> builtin: temporary fix fixed_array_any_all_test.v (related #22621)

- vlib/v/gen/c/cheaders.v
- vlib/v/gen/c/infix.v
This PR makes literal string comparison `==` and `!=` to generate `_SLIT_EQ` and `_SLIT_NE` macro usage instead of `string__eq`.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE2ZDczYjRjMjRlYTI4ODIwMjg3MGIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.HRdQ-mAsMEwqlHkFEXi7laxd422ZZoUjtahd9Nfq0kE">Huly&reg;: <b>V_0.6-21063</b></a></sub>
> cgen: optimize literal string comparison (string__eq -> vmemcmp)

- vlib/v/checker/fn.v
- vlib/v/checker/tests/fixed_array_builtin_method_args_err.out
- vlib/v/checker/tests/fixed_array_builtin_method_args_err.vv
This PR check fixed array builtin method args mismatch.
- Check fixed array builtin method args mismatch.
- Add test.
```v
fn main() {
arr := [1, 2, 3]!
_ := arr.index()
_ := arr.index('hello')
_ := arr.contains()
_ := arr.contains('hello')
_ := arr.any()
_ := arr.any(22)
_ := arr.all()
_ := arr.all('hello')
}
PS D:\Test\v\tt1> v run .      
tt1.v:4:11: error: `.index()` expected 1 argument, but got 0
2 |     arr := [1, 2, 3]!
3 | 
4 |     _ := arr.index()
|              ~~~~~~~
5 |     _ := arr.index('hello')
6 |     _ := arr.contains()
tt1.v:4:4: error: assignment mismatch: 1 variable but `index()` returns 0 values
2 |     arr := [1, 2, 3]!
3 | 
4 |     _ := arr.index()
|       ~~
5 |     _ := arr.index('hello')
6 |     _ := arr.contains()
tt1.v:5:17: error: cannot use `string` as `int` …
```
> checker: check fixed array builtin method args mismatch

- vlib/v/gen/c/cgen.v
- vlib/v/tests/selector_indexexpr_fn_type_assign_test.v
Fix #22635
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE5NzMwMWYwMmQ4YTAzZmIyZmVmMDQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.WhIx48DAiLAE2dBm6u8WYBE3NtXqXbqg4InEQzMo9JA">Huly&reg;: <b>V_0.6-21086</b></a></sub>
> cgen: fix selector indexexpr with fntype on assignment

- vlib/v/gen/c/fn.v
- vlib/v/tests/fns/anon_with_prefix_test.v
Fix #22628
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE5NzZkNWYwMmQ4YTAzZmIyZmVmNzciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.plTRFJHxL5qwljP0YxJwBmptd7NM30ITjt1dpRu1I-Y">Huly&reg;: <b>V_0.6-21087</b></a></sub>
> cgen: fix anon fn with prefix `&`

- vlib/v/checker/fn.v
- vlib/v/checker/tests/fixed_array_builtin_method_args_err.out
This PR improve checking parameter mismatches for fixed array builtin methods.
```v
fn main() {
arr := [1, 2, 3]!
_ := arr.index()
_ := arr.index('hello')
_ := arr.contains()
_ := arr.contains('hello')
_ := arr.any()
_ := arr.any(22)
_ := arr.all()
_ := arr.all('hello')
}
tt1.v:4:11: error: `.index()` expected 1 argument, but got 0
2 |     arr := [1, 2, 3]!
3 | 
4 |     _ := arr.index()
|              ~~~~~~~
5 |     _ := arr.index('hello')
6 |     _ := arr.contains()
tt1.v:5:17: error: cannot use `string` as `int` in argument 1 to `.index()`
3 | 
4 |     _ := arr.index()
5 |     _ := arr.index('hello')
|                    ~~~~~~~
6 |     _ := arr.contains()
7 |     _ := arr.contains('hello')
tt1.v:6:11: error: `.contains()` expected 1 argument, but got 0
4 | …
```
> checker: improve checking parameter mismatches for fixed array builtin methods

- vlib/v/gen/c/struct.v
- vlib/v/tests/structs/struct_field_init_with_fixed_array_init_test.v
This PR fix struct field init with fixed array using index (fix #22616).
- Fix struct field init with fixed array using index.
- Add test.
```v
fn main() {
mut a := [5]int{init: [1, 2][index] or { 0 }}
struct ArrayTest {
aa [5]int
}
array_a := ArrayTest{
aa: a
}
println('array_a: ${array_a}')
assert array_a.aa == [1, 2, 0, 0, 0]!
array_b := ArrayTest{
aa: [5]int{init: [1, 2][index] or { 0 }}
}
println('array_b: ${array_b}')
assert array_b.aa == [1, 2, 0, 0, 0]!
}
array_a: ArrayTest{
aa: [1, 2, 0, 0, 0]
}
array_b: ArrayTest{
aa: [1, 2, 0, 0, 0]
}
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFhNDNhOWYwMmQ4YTAzZmIzMzYwODMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlc …
> cgen: fix struct field init with fixed array using index (fix #22616)

- vlib/v/gen/c/auto_eq_methods.v
- vlib/v/gen/c/infix.v
- vlib/v/gen/c/match.v
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFhNGViZGYwMmQ4YTAzZmIzMzYxYWMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.xKtrUwQm3CiTBRfc1T0OjsjvxB_Mjb3F_6PSPuDxy5E">Huly&reg;: <b>V_0.6-21092</b></a></sub>
> v: optimize literal string comparison (`match`, `in` and `==`)

- vlib/v/ast/types.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/infix.v
This PR fixes the race issue about reading/writing on interface `info.conversions` map reffered by @medvednikov on PR #22640
Probably related to #17943
My test was:
`for i in $(seq 1 50); do v ui/examples/users.v && echo "Success compilation" ; done`
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFjNWNkMWYwMmQ4YTAzZmIzM2ZiYWMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.j6sduk9HDtHXrFjYRzbp-9v-e1d4uPX_vVybXfAKcBI">Huly&reg;: <b>V_0.6-21104</b></a></sub>
> v: fix interface conversion codegen race issue

- vlib/coroutines/README.md
- vlib/db/README.md
- vlib/v2/README.md
As mentioned at #17003 missing README broke the links so add some short READMEs for such cases
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE5NjAxM2YwMmQ4YTAzZmIyZmViNmMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.ZiJl2cEHpP-UKUMKoLzSUjGxYpC3uRTB4jxdeAMIuow">Huly&reg;: <b>V_0.6-21085</b></a></sub>
> docs: fix broken links by adding missing READMEs

- vlib/v/checker/tests/fixed_array_sort_err.out
- vlib/v/checker/tests/fixed_array_sort_err.vv
- vlib/v/checker/tests/fn_return_fixed_array_sort_err.out
- vlib/v/checker/tests/fn_return_fixed_array_sort_err.vv
This PR add tests for checking fixed array .sort() errors.
```v
fn main() {
mut arr := [3, 2, 1]!
arr.sort(a < b, a)
arr.sort(a == b)
arr.sort(a > a)
arr.sort(c > d)
}
tt1.v:3:6: error: expected 0 or 1 argument, but got 2
2 |     mut arr := [3, 2, 1]!
3 |     arr.sort(a < b, a)
|         ~~~~~~~~~~~~~~
4 |     arr.sort(a == b)
5 |     arr.sort(a > a)
tt1.v:4:6: error: `.sort()` can only use `<` or `>` comparison
2 |     mut arr := [3, 2, 1]!
3 |     arr.sort(a < b, a)
4 |     arr.sort(a == b)
5 |     arr.sort(a > a)
6 |     arr.sort(c > d)
tt1.v:5:6: error: `.sort()` cannot use same argument
3 |     arr.sort(a < b, a)
4 |     arr.sort(a == b)
5 |     arr.sort(a > a)
|         ~~~~~~~~~~~
6 |     arr.sort(c > d)
7 | } …
```
> tests: add tests for checking fixed array .sort() errors

- vlib/v/checker/checker.v
- vlib/v/comptime/comptimeinfo.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/sumtype_init_by_name_test.v
This PR allows to initialize Sumtype through its `variant` comptime types.
e.g.
```v
type Sum = int | string
fn get[T](val T, type_name string) T {
$if T is $sumtype {
$for v in val.variants {
if type_name == typeof(v.typ).name {
return T(v)
}
}
}
return T{}
}
fn main() {
dump(get(Sum{}, 'int')) // Sum(0)
dump(get(Sum{}, 'string')) // Sum('')
}
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFjZjc2OWYwMmQ4YTAzZmIzNDA3ZDYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.ULlU4oSZIOGYmiUhRsXhHRu9fon0EsFShoWs56Gi2IQ">Huly&reg;: <b>V_0.6-21113</b></a></sub>
> v: allow sumtype init by variant comptime var `T(v)` / `SumType(v)`

- .github/workflows/macos_ci.yml
- vlib/picoev/loop_linux.c.v
Fixes the failures in the `alpine-docker-musl-gcc` and `ubuntu-docker-musl` jobs, that are compiled using musl, which does not have a `sys/cdefs.h` header.
> ci: fix failing jobs after 2684ef9

- vlib/log/log.v
- vlib/time/format.v
- vlib/time/time_test.v
- vlib/v/slow_tests/inout/dump_expression.out
`v wipe-cache && v -prod crun log_.v > lala.log`
```sh
SPENT  354.390 ms in log.info
SPENT  354.037 ms in log.error
SPENT   40.974 ms in println
```
```sh
SPENT  171.269 ms in log.info
SPENT  171.246 ms in log.error
SPENT   38.279 ms in println
```
```v
import log
import benchmark
const max_iterations := 1000000
fn main() {
println('max_iterations: $max_iterations')
mut l := log.Log{}
l.set_level(.info)
l.set_full_logpath('./info.log')
mut b := benchmark.start()
for i := 0; i < max_iterations; i++ {
l.info('Hello, World!')
}
b.measure('log.info')
for i := 0; i < max_iterations; i++ {
l.error('Hello, World!')
}
b.measure('log.error')
for i := 0; i < max_iterations; i++ {
println('Hello, World!')
}
b.measure('println')
}
```
*Note: if I remove …
> log,time: improve performance for writing a line to a log, add Time.format_rfc3339_micro/0

- vlib/v/checker/checker.v
- vlib/v/checker/tests/immutable_array_in_if_expr_index.out
- vlib/v/checker/tests/immutable_array_in_if_expr_index.vv
- vlib/v/gen/c/if.v
- vlib/v/tests/indexexpr_with_if_expr_test.v
This PR fix index expr that left is if expr (fix #22654).
- Fix index expr that left is if expr.
- Add test.
```v
fn main() {
mut array_a := [1, 2, 3]
mut array_b := [4, 5, 6]
(if true { array_a } else { array_b })[0] = 999
println(array_a)
assert array_a == [999, 2, 3]
}
[999, 2, 3]
```
```v
fn main() {
array_a := [1, 2, 3]
array_b := [4, 5, 6]
(if true { array_a } else { array_b })[0] = 999
println(array_a)
assert array_a == [999, 2, 3]
}
tt1.v:4:13: error: `array_a` is immutable, declare it with `mut` to make it mutable
2 |     array_a := [1, 2, 3]
3 |     array_b := [4, 5, 6]
4 |     (if true { array_a } else { array_b })[0] = 999
|                ~~~~~~~
5 |     println(array_a)
6 |     assert array_a == [999, 2, 3]
tt1.v:4:30: …
```
> checker: fix index expr that left is if expr (fix #22654)

- vlib/builtin/builtin.v
- vlib/v/gen/c/assert.v
- vlib/v/tests/skip_unused/assert_of_sumtype_values_works_test.run.out
- vlib/v/tests/skip_unused/assert_of_sumtype_values_works_test.skip_unused.run.out
- vlib/v/tests/skip_unused/assert_of_sumtype_values_works_test.vv
This PR improve the assert informations  (related #22666).
```v
type Sum = int | string
fn main() {
assert Sum(1) == Sum(2)
}
.\\tt1.v:4: FAIL: fn main.main: assert main.Sum(1) == main.Sum(2)
left value: main.Sum(1)
right value: main.Sum(2)
V panic: Assertion failed...
v hash: 14b1a14
C:/Users/yuyi9/AppData/Local/Temp/v_0/tt1.01JB6ZGGR5EPG0CM0FD2MRVCFX.tmp.c:7314: at _v_panic: Backtrace
C:/Users/yuyi9/AppData/Local/Temp/v_0/tt1.01JB6ZGGR5EPG0CM0FD2MRVCFX.tmp.c:13684: by main__main
C:/Users/yuyi9/AppData/Local/Temp/v_0/tt1.01JB6ZGGR5EPG0CM0FD2MRVCFX.tmp.c:13721: by wmain
00466ea8 : by ???
0046700b : by ???
7ffe207e259d : by ???
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nz …
> builtin, cgen: improve the assert informations (related #22666)

- vlib/v/checker/return.v
- vlib/v/checker/tests/mut_receiver_wrong_return_type.out
- vlib/v/checker/tests/wrong_return_type_err.out
- vlib/v/checker/tests/wrong_return_type_err.vv
- vlib/v/slow_tests/inout/printing_option_or_expr_with_map_val.out
- vlib/v/slow_tests/inout/printing_result_or_expr_with_map_val.out
- vlib/v/slow_tests/inout/printing_result_or_expr_with_map_val.vv
Fix #22659
Fix #22658
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFjY2Y3OGYwMmQ4YTAzZmIzNDA0YzQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.ayD8fzOP3MbaaRpZTGvqup_m_tYARyDeoFABnw2oEjQ">Huly&reg;: <b>V_0.6-21109</b></a></sub>
> checker: fix return type checker when returning struct which implements IError on non-result fn

- vlib/x/json2/decoder2/decode.v
- vlib/x/json2/decoder2/tests/json_sumtype_test.v
- vlib/x/json2/decoder2/tests/json_sumtype_test_todo.vv
```v
type Sum = int | string | bool
fn test_simple_sum_type() {
assert json.decode[Sum]('1')! == Sum(1)
assert json.decode[Sum]('"hello"')! == Sum('hello')
assert json.decode[Sum]('true')! == Sum(true)
assert json.decode[Sum]('false')! == Sum(false)
}
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFlM2YzZDI3Y2M3NjgxYzYyMTA2Y2QiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.Tw5qqbMVJ6jfIG04yyGFnja9ehsKe3nUChu1l7GEslA">Huly&reg;: <b>V_0.6-21118</b></a></sub>
> x.json2.decoder2: init support to sumtype

- vlib/v/gen/c/dumpexpr.v
- vlib/v/tests/options/option_fn_alias_test.v
Fix #22670
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFlYWNlMTI3Y2M3NjgxYzYyMmRiOTIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.XcnL0T7fg0VIjY1FMyFVGutFpSYRPH4_FPjNpNZtjwY">Huly&reg;: <b>V_0.6-21125</b></a></sub>
> cgen: fix dump of alias to option fn type

- vlib/v/parser/expr.v
- vlib/v/tests/structs/struct_generic_init_test.v
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFmNzk1NDI3Y2M3NjgxYzYyMzAxZGEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.EUc6ZpvN8Hk6qpIPE4g7lsxiz-7oAJGrjSDqvWAdD8s">Huly&reg;: <b>V_0.6-21131</b></a></sub>
> parser: fix generic struct init detection `T{}`

- vlib/v/gen/c/index.v
- vlib/v/tests/builtin_arrays/array_append_map_with_or_expr_test.v
This PR fix array append map value with or expr (fix #22674).
- Fix array append map value with or expr.
- Add test.
```v
fn main() {
foobar := {
'foo': 'Foo'
'bar': 'Bar'
}
mut arr := []string{}
arr << foobar['foo']
arr << foobar['baz'] or { 'Unknown' }
assert arr == ['Foo', 'Unknown']
}
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFlZjljNzI3Y2M3NjgxYzYyMmViMjYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0._4l6IA64IyStrPA6EMhiZ6GFtK6nGf9Koul8XqHPlJI">Huly&reg;: <b>V_0.6-21127</b></a></sub>
> cgen: fix array append map value with or expr (fix #22674)

- vlib/orm/orm.v
- vlib/orm/orm_mut_connection_test.v
This PR allows implementing the orm.Connection interface with methods that take in mutable or immutable Connections
Before the change, the following would result in an error similar to:
error: `Database` incorrectly implements method `select` of interface `orm.Connection`: expected `orm.Connection` which is immutable, not `mut &Database`
```v
fn (mut db Database) drop(table string) ! {
query := 'DROP TABLE ${table};'
db.query(query)!
}
```
This can be tested with
```bash
v -stats test ./vlib/orm/orm_mut_connection_test.v
```
> orm: fix orm.Connection only allowing immutable Connections

- vlib/v/checker/checker.v
- vlib/v/tests/generics/generic_default_expression_in_or_block_test.v
This is continuation of #22672 .
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFmZTg0ZDI3Y2M3NjgxYzYyMzFkMmIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.lH1B4aIHYvnK4HyYMC_YOvGi_byJvv7Tarj-Is1hnIM">Huly&reg;: <b>V_0.6-21136</b></a></sub>
> checker: allow for `f() or { T{} }` part 2 (handle the case of an ignored result as well) (see also #22672)

- vlib/v/ast/str.v
- vlib/v/checker/tests/globals_run/function_stored_in_global.run.out
- vlib/v/slow_tests/inout/dump_sumtype_of_fntype.out
- vlib/v/tests/skip_unused/assert_of_sumtype_values_works_test.run.out
- vlib/v/tests/skip_unused/assert_of_sumtype_values_works_test.skip_unused.run.out
This PR improve the assert informations (related #22668).
```v
type Sum = int | string
fn main() {
assert Sum(1) == Sum(2)
}
.\\tt1.v:4: FAIL: fn main.main: assert Sum(1) == Sum(2)
left value: Sum(1)
right value: Sum(2)
V panic: Assertion failed...
v hash: 9c72d94
C:/Users/yuyi9/AppData/Local/Temp/v_0/tt1.01JB994DG71BPHW0GK9AEFXYZS.tmp.c:7314: at _v_panic: Backtrace
C:/Users/yuyi9/AppData/Local/Temp/v_0/tt1.01JB994DG71BPHW0GK9AEFXYZS.tmp.c:13684: by main__main
C:/Users/yuyi9/AppData/Local/Temp/v_0/tt1.01JB994DG71BPHW0GK9AEFXYZS.tmp.c:13721: by wmain
00466ea8 : by ???
0046700b : by ???
7ffe207e259d : by ???
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFmNjBmMDI3Y2M3NjgxYzYyMmZ …
> ast: improve the assert informations (related #22668)

- vlib/x/json2/decoder2/decode.v
- vlib/x/json2/decoder2/decode_sumtype.v
- vlib/x/json2/decoder2/tests/bench.v
- vlib/x/json2/decoder2/tests/decode_number_and_boolean_test.v
- vlib/x/json2/decoder2/tests/json_sumtype_test.v
- vlib/x/json2/types.v
```v
fn test_any_sum_type() {
assert json.decode[json2.Any]('1')! == json2.Any(f64(1))
assert json.decode[json2.Any]('123321')! == json2.Any(f64(123321))
assert json.decode[json2.Any]('"hello"')! == json2.Any('hello')
assert json.decode[json2.Any]('true')! == json2.Any(true)
assert json.decode[json2.Any]('false')! == json2.Any(false)
assert json.decode[json2.Any]('1.1')! == json2.Any(f64(1.1))
}
fn test_sum_type_struct() {
assert json.decode[Animal]('{"cat_name": "Tom"}')! == Animal(Cat{'Tom'})
assert json.decode[Animal]('{"dog_name": "Rex"}')! == Animal(Cat{''})
assert json.decode[Animal]('{"dog_name": "Rex", "_type": "Dog"}')! == Animal(Dog{'Rex'})
}
```
```sh
SPENT   372.589 ms in decoder2.decode[Stru](json_data)! …
```
> x.json2.decoder: full support sumtypes

- vlib/bitfield/bitfield.v
- vlib/bitfield/bitfield_test.v
```v
bitfield.shift_left(count int)
bitfield.shift_right(count int)
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzIyMmRjNzI3Y2M3NjgxYzYyM2E4MjEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.PtCp09V_Y9-Csrs4Z4AA7TlIs7nbbHr3GEzkzRbNRVw">Huly&reg;: <b>V_0.6-21148</b></a></sub>
> bitfield: add shift left/right functions

- vlib/v/checker/fn.v
- vlib/v/checker/tests/anon_missing_generic_err.out
- vlib/v/checker/tests/anon_missing_generic_err.vv
Fix #19045
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFmOGI4YjI3Y2M3NjgxYzYyMzA1MmIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.y_yJhgBb7bGyafNUS3ZbiXYuO3GcrLTWVTX_2SvpD7Y">Huly&reg;: <b>V_0.6-21132</b></a></sub>
> checker: fix missing check for fn var with generic return inherited to anon fn

- vlib/v/gen/c/assign.v
- vlib/v/tests/init_global_test.v
Fix #22705 .
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzIyOWI0OTI3Y2M3NjgxYzYyM2JlZDgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.jDbJ4c-l2LkifI4SgxVRXHk1ScpdENhYWgL3OJ_wHS8">Huly&reg;: <b>V_0.6-21155</b></a></sub>
> cgen: ensure proper saving/restoring of cgen `map[k] := fn ()` state, when assigning anonymous fns (fix #22705)

- vlib/v/checker/fn.v
- vlib/v/checker/tests/globals/global_receiver_var_name_err.out
- vlib/v/checker/tests/globals/global_receiver_var_name_err.vv
Fix #22698
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzIyYjczNDI3Y2M3NjgxYzYyM2MwOTMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.rlSaOKy0XyRnHYRA97ySIcLNg6gXWZj5Rj_r7ITT45U">Huly&reg;: <b>V_0.6-21156</b></a></sub>
> checker: check for receiver name clashing with global var

- vlib/builtin/fixed_array_sort_test.v
- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/gen/c/array.v
- vlib/v/gen/c/fn.v
This PR implement methods sort_with_compare()/sorted_with_compare() for fixed array.
- Implement methods sort_with_compare()/sorted_with_compare() for fixed array.
- Add tests.
```v
fn test_sort_with_compare_1() {
mut a := ['hi', '1', '5', '3']!
a.sort_with_compare(fn (a &string, b &string) int {
if a < b {
return -1
}
if a > b {
return 1
}
return 0
})
assert a == ['1', '3', '5', 'hi']!
}
fn test_sorted_with_compare_1() {
a := ['hi', '1', '5', '3']!
b := a.sorted_with_compare(fn (a &string, b &string) int {
if a < b {
return -1
}
if a > b {
return 1
}
return 0
})
assert b == ['1', '3', '5', 'hi']!
}
struct Ka {
s string
i int
}
fn test_sort_with_compare_2() {
mut arr := [
Ka{
s: 'bbb'
i: 100
},
Ka{
s: 'aaa'
i: 101
},
Ka{
s: 'ccc'
i: 102
},
]!
cmp := fn (a &Ka, b &Ka) int {
return …
```
> checker, cgen: implement methods sort_with_compare()/sorted_with_compare() for fixed array

- vlib/builtin/fixed_array_reverse_test.v
- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/gen/c/array.v
- vlib/v/gen/c/fn.v
This PR implement methods reverse()/reverse_in_place() for fixed array.
- Implement methods reverse()/reverse_in_place() for fixed array.
- Add tests.
```v
struct User {
age  int
name string
}
fn test_fixed_array_reverse_in_place() {
mut a := ['hi', '1', '5', '3']!
a.reverse_in_place()
assert a == ['3', '5', '1', 'hi']!
mut nums := [67, -3, 108, 42, 7]!
nums.reverse_in_place()
assert nums == [7, 42, 108, -3, 67]!
mut users := [User{22, 'Peter'}, User{20, 'Bob'}, User{25, 'Alice'}]!
users.reverse_in_place()
assert users[0].age == 25
assert users[1].age == 20
assert users[2].age == 22
assert users[0].name == 'Alice'
assert users[1].name == 'Bob'
assert users[2].name == 'Peter'
}
fn test_fixed_array_reverse() {
a := ['hi', '1', '5', '3']!
b := a.reverse()
assert a == ['hi', '1', '5', '3']! …
```
> checker, cgen: implement methods reverse()/reverse_in_place() for fixed array

- cmd/tools/modules/testing/common.v
Make diagnosing flaky tests easier, on the CI and locally, without having to run them manually first.
It now shows all the lines below starting with `>>>`:
```
retrying 1/3 of vlib/x/vweb/tests/vweb_should_listen_on_both_ipv4_and_ipv6_by_default_test.v ; known flaky: true ...
retrying 2/3 of vlib/x/vweb/tests/vweb_should_listen_on_both_ipv4_and_ipv6_by_default_test.v ; known flaky: true ...
retrying 3/3 of vlib/x/vweb/tests/vweb_should_listen_on_both_ipv4_and_ipv6_by_default_test.v ; known flaky: true ...
>>> flaky failures so far:
>>>>>> ---------------------------------------------------------------------------------------------------- retry: 0 ; max_retry: 3 ; r.exit_code: 1 ; trimmed_output.len: 1149
>>>>>> 2024-10-31T16:19:23.728582Z [DEBUG] testsuite_begin
>>>>>> …
```
> tools: show the full test output, on known flaky test failure with `v test folder/`

- vlib/builtin/string.v
- vlib/v/ast/ast.v
- vlib/v/ast/scope.v
- vlib/v/ast/table.v
- vlib/v/ast/types.v
- vlib/v/checker/checker.v
- vlib/v/checker/struct.v
- vlib/v/depgraph/depgraph.v
- vlib/v/gen/c/array.v
- vlib/v/gen/c/auto_eq_methods.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/infix.v
- vlib/v/gen/c/json.v
- vlib/v/gen/c/utils.v
- vlib/v/parser/parser.v
- vlib/v/parser/struct.v
This PR tries to identify points to optimize by checking `gprof` output by:
- Reducing uneeded `string__eq` calls
- Removing repeated `typ.has_flag(.flag)` calls
- Reducing `array_get` calls where `@[direct_array_access]` can helps
- Reducing `alias_eq` calls to numeric types (like `ast.Type`)
- Reducing check for embed by adding `is_embed` flag to `ast.StructDecl` and `ast.StructInitField`
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzIyZDM4MTI3Y2M3NjgxYzYyM2MyNWQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.2VVEb-VNocN_dH4fnQ8m74k6wn9a6_YmpwUPzAxjTWo">Huly&reg;: <b>V_0.6-21157</b></a></sub>
> v: optimization improvements

- vlib/builtin/fixed_array_map_test.v
- vlib/v/gen/c/array.v
- vlib/v/gen/c/ctempvars.v
This PR fix `assert [1, 2, 3]!.map(it * 2) == [2, 4, 6]!`.
- Fix `assert [1, 2, 3]!.map(it * 2) == [2, 4, 6]!`.
- Add tests.
```v
fn test_fixed_array_map() {
a := [1, 2, 3]!
b1 := a.map(it * 2)
println(b1)
assert b1 == [2, 4, 6]!
b10 := [1, 2, 3]!.map(it * 2)
assert b10 == [2, 4, 6]!
assert [1, 2, 3]!.map(it * 2) == [2, 4, 6]!
b11 := a.map(|x| x * 2)
println(b11)
assert b11 == [2, 4, 6]!
b110 := [1, 2, 3]!.map(|x| x * 2)
assert b110 == [2, 4, 6]!
assert [1, 2, 3]!.map(|x| x * 2) == [2, 4, 6]!
b2 := a.map('${it}')
println(b2)
assert b2 == ['1', '2', '3']!
b20 := [1, 2, 3]!.map('${it}')
assert b20 == ['1', '2', '3']!
assert [1, 2, 3]!.map('${it}') == ['1', '2', '3']!
b22 := a.map(|x| '${x}')
println(b22)
assert b22 == ['1', '2', '3']!
b220 := [1, 2, 3]!.map(|x| '${x}')
assert b220 == ['1', …
```
> cgen: fix `assert [1, 2, 3]!.map(it * 2) == [2, 4, 6]!`

- vlib/builtin/fixed_array_contains_test.v
- vlib/v/gen/c/array.v
This PR fix `assert [1, 2, 3]!.contains(2)`.
- Fix `assert [1, 2, 3]!.contains(2)`.
- Add tests.
```v
fn test_contains_of_ints() {
mut ii := ia.contains(2)
dump(ii)
assert ii
assert [1, 2, 3]!.contains(2)
ii = ia.contains(5)
dump(ii)
assert !ii
assert ![1, 2, 3]!.contains(5)
}
fn test_contains_of_strings() {
mut si := sa.contains('b')
dump(si)
assert si
assert ['a', 'b', 'c']!.contains('b')
si = sa.contains('v')
dump(si)
assert !si
assert !['a', 'b', 'c']!.contains('v')
}
fn test_contains_of_voidptrs() {
mut pi := pa.contains(voidptr(45))
dump(pi)
assert pi
assert [voidptr(123), voidptr(45), voidptr(99)]!.contains(voidptr(45))
pi = pa.contains(unsafe { nil })
dump(pi)
assert !pi
assert ![voidptr(123), …
```
> cgen: fix `assert [1, 2, 3]!.contains(2)`

- vlib/builtin/fixed_array_index_test.v
- vlib/v/gen/c/array.v
This PR fix `assert [1, 2, 3]!.index(2) == 1`.
- Fix `assert [1, 2, 3]!.index(2) == 1`.
- Add tests.
```v
fn test_index_of_ints() {
mut ii := ia.index(2)
dump(ii)
assert ii == 1
assert [1, 2, 3]!.index(2) == 1
ii = ia.index(5)
dump(ii)
assert ii == -1
assert [1, 2, 3]!.index(5) == -1
}
fn test_index_of_strings() {
mut si := sa.index('b')
dump(si)
assert si == 1
assert ['a', 'b', 'c']!.index('b') == 1
si = sa.index('v')
dump(si)
assert si == -1
assert ['a', 'b', 'c']!.index('v') == -1
}
fn test_index_of_voidptrs() {
mut pi := pa.index(voidptr(45))
dump(pi)
assert pi == 1
assert [voidptr(123), voidptr(45), voidptr(99)]!.index(voidptr(45)) == 1
pi = pa.index(unsafe { nil })
dump(pi)
assert pi == -1
assert …
```
> cgen: fix `assert [1, 2, 3]!.index(2) == 1`

- vlib/v/gen/c/spawn_and_go.v
- vlib/v/tests/concurrency/spawn_with_different_method_receivers_test.v
Fix #22718
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzIzZWQ0YjI3Y2M3NjgxYzYyNTdjZjQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.NlvBilCcDbwXueAz2bDPwKEum7Zajn9rDcFTKmhgm2o">Huly&reg;: <b>V_0.6-21166</b></a></sub>
> cgen: fix spawn with non-pointer receiver

- vlib/v/checker/match.v
- vlib/v/checker/tests/match_option_without_none_err.out
- vlib/v/checker/tests/match_option_without_none_err.vv
Fix #22728
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzI1NzFmODI3Y2M3NjgxYzYyNWQ2MTYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.uOC6lQsBRPmaCQpX6liilSIojG9ffKauPOEp8vcvrUQ">Huly&reg;: <b>V_0.6-21179</b></a></sub>
> checker: fix none check for match expr with option

- vlib/builtin/fixed_array_reverse_test.v
- vlib/v/gen/c/array.v
This PR fix `assert [1, 2, 3]!.reverse() == [3, 2, 1]!`.
- Fix `assert [1, 2, 3]!.reverse() == [3, 2, 1]!`.
- Add tests.
```v
fn test_fixed_array_reverse() {
a := ['hi', '1', '5', '3']!
b := a.reverse()
assert a == ['hi', '1', '5', '3']!
assert b == ['3', '5', '1', 'hi']!
assert ['hi', '1', '5', '3']!.reverse() == ['3', '5', '1', 'hi']!
mut nums := [67, -3, 108, 42, 7]!
n := nums.reverse()
assert nums == [67, -3, 108, 42, 7]!
assert n == [7, 42, 108, -3, 67]!
assert [67, -3, 108, 42, 7]!.reverse() == [7, 42, 108, -3, 67]!
mut users := [User{22, 'Peter'}, User{20, 'Bob'}, User{25, 'Alice'}]!
u := users.reverse()
assert users[0].age == 22
assert users[1].age == 20
assert users[2].age == 25
assert users[0].name == 'Peter'
assert users[1].name == 'Bob'
assert users[2].name == 'Alice'
assert …
```
> cgen: fix `assert [1, 2, 3]!.reverse() == [3, 2, 1]!`

- vlib/builtin/fixed_array_sort_test.v
- vlib/v/gen/c/array.v
This PR fix `assert [2, 3, 1]!.sorted() == [1, 2, 3]!`.
- Fix `assert [2, 3, 1]!.sorted() == [1, 2, 3]!`.
- Add tests.
```v
fn test_sorted_immutable_original_should_not_change() {
a := ['hi', '1', '5', '3']!
b := a.sorted()
assert a == ['hi', '1', '5', '3']!
assert b == ['1', '3', '5', 'hi']!
assert ['hi', '1', '5', '3']!.sorted() == ['1', '3', '5', 'hi']!
}
fn test_sorted_mutable_original_should_not_change() {
mut a := ['hi', '1', '5', '3']!
b := a.sorted()
assert a == ['hi', '1', '5', '3']!
assert b == ['1', '3', '5', 'hi']!
assert ['hi', '1', '5', '3']!.sorted() == ['1', '3', '5', 'hi']!
}
fn test_sorted_reversed() {
aa := ['hi', '1', '5', '3']!
bb := aa.sorted(a > b)
assert aa == ['hi', '1', '5', '3']!
assert bb == ['hi', '5', '3', '1']!
assert ['hi', '1', '5', '3']!.sorted(a > b) == …
```
> cgen: fix `assert [2, 3, 1]!.sorted() == [1, 2, 3]!`

- vlib/builtin/fixed_array_any_all_test.v
This PR improve fixed_array_any_all_test.v.
- Add `assert [1, 2, 3]!.any(it > 2)`.
```v
fn test_any_all_of_ints() {
assert ia.any(it > 2)
assert ia.any(|x| x > 2)
assert [1, 2, 3]!.any(it > 2)
assert [1, 2, 3]!.any(|x| x > 2)
assert !ia.all(it > 1)
assert !ia.all(|x| x > 1)
assert ![1, 2, 3]!.all(it > 1)
assert ![1, 2, 3]!.all(|x| x > 1)
assert ia.any(it == 2)
assert ia.any(|x| x == 2)
assert [1, 2, 3]!.any(it == 2)
assert [1, 2, 3]!.any(|x| x == 2)
assert !ia.all(it == 3)
assert !ia.all(|x| x == 3)
assert ![1, 2, 3]!.all(it == 3)
assert ![1, 2, 3]!.all(|x| x == 3)
}
fn test_any_all_of_strings() {
assert sa.any(it == 'b')
assert sa.any(|x| x == 'b')
assert ['a', 'b', 'c']!.any(it == 'b')
assert ['a', 'b', 'c']!.any(|x| x == 'b')
assert !sa.all(it == …
```
> builtin: improve fixed_array_any_all_test.v

- vlib/builtin/string.v
- vlib/builtin/string_test.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/js/js.v
This PR add `string.is_pure_ascii()` and modify all the related calls.
```v
fn test_len_utf8() {
assert 'Vlang'.len_utf8() == 5
assert 'María'.len_utf8() == 5
assert '姓名'.len_utf8() == 2
assert 'Слово'.len_utf8() == 5
assert 'Λέξη'.len_utf8() == 4
}
fn test_is_pure_ascii() {
assert 'Vlang'.is_pure_ascii()
assert !'María'.is_pure_ascii()
assert !'姓名'.is_pure_ascii()
assert !'Слово'.is_pure_ascii()
assert !'Λέξη'.is_pure_ascii()
}
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzI3NTNkNzI3Y2M3NjgxYzYyNjEzNzQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.WlxeVX1Dv_lY1Pbo0OIKdGJkI_lYOQUJ64KUMdzaljs">Huly&reg;: …
> builtin: add `string.is_pure_ascii()`

- vlib/v/checker/containers.v
- vlib/v/checker/fn.v
- vlib/v/checker/tests/result_param_type_err.out
- vlib/v/checker/tests/result_param_type_err.vv
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/js/auto_str_methods.v
- vlib/v/gen/js/js.v
- vlib/v/gen/native/expr.v
- vlib/v/parser/fn.v
- vlib/v/tests/options/option_map_fn_value_test.v
Fix #22736
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzI2MDFlMTI3Y2M3NjgxYzYyNWYyYzQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.iZXgsd0VjB8ZaxM8vM-qQN2nppfJx-NUB6BY-3X6GyU">Huly&reg;: <b>V_0.6-21185</b></a></sub>
> parser,checker: fix option map fn type and missing check for result param type

- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/checker/tests/generic_fn_infinite_loop_limit_err.out
- vlib/v/checker/tests/generic_fn_var_unresolved_err.out
- vlib/v/checker/tests/generic_fn_var_unresolved_err.vv
Fix #22734
Fix #22733
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzI2NGU0ODI3Y2M3NjgxYzYyNWZiYzYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.2DCEqewNEJErvS_4wwF-VaGKiWLDZxxWXjSCLcVxaIA">Huly&reg;: <b>V_0.6-21190</b></a></sub>
> checker: fix missing info about generic fn var usage without concrete types

- vlib/v/gen/c/infix.v
- vlib/v/gen/c/testdata/for_in_side_effect.out
- vlib/v/gen/c/testdata/for_in_side_effect.vv
This PR fixes the issue addressed in #22758. It prevents the left expression of an `in` infix expression from being emitted multiple times. This occurs in the following code example:
```v
x() in [12, 13]
```
This gets optimized into:
```c
x() == 12 || x() == 13
```
In this case this optimization is incorrect.
The fix I implemented checks if the left expression is an `ast.Ident`. However, I'm unsure if there is side effect information present in the compiler. Having this information available would allow this optimization to be applied in more situations.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzI5NDljNWU3Y2M1YTc4NTQyNzg2ZDQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZS …
> v: fix redundant emission of left expression in in infix expressions

- vlib/v/gen/c/cmain.v
Testing compiling .c file from #22762 I noticed that `_vinit`, `_vcleanup` are called but removed its declaration due -no-builtin flag, as `g_main_argc` and `g_main_argv` too.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzI5ZjRjOGU3Y2M1YTc4NTQyN2FhM2MiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.GluxRAL5jBeT7y5H4FbJP-P2U1bL2aMqFtMjMlj0WaU">Huly&reg;: <b>V_0.6-21212</b></a></sub>
> cgen: fix codegen for -no-builtin flag

- vlib/v/gen/c/infix.v
The cost of only doing the optimization for `ast.Ident`, was ~12% slowdown for `v self` and larger produced .c and executable sizes (because of the additional generated .contains() methods).
This adds back the same optimization for the cases of ast.SelectorExpr - `x.y` and ast.IndexExpr - a[i] to reduce the amount of generated code and restore some of the compilation speed.
> cgen: apply the `a in [x,y,z]` optimisation for ast.IndexExpr and ast.SelectorExpr again

- vlib/v/gen/c/infix.v
- vlib/v/slow_tests/inout/in_expr_callexpr.out
- vlib/v/slow_tests/inout/in_expr_callexpr.vv
Fix #22758
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzI5NTJlNWU3Y2M1YTc4NTQyNzg4YTIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.kpe1y_WnxwqN70OaP7sMk82Mn6CM9WcH08_KnxSkGoU">Huly&reg;: <b>V_0.6-21211</b></a></sub>
> cgen: fix codegen to emit callexpr one time for `in` expr optimization

- vlib/v/gen/c/fn.v
- vlib/v/parser/expr.v
- vlib/v/parser/parser.v
- vlib/v/tests/fns/map_index_call_test.v
This PR allows to do:
`map['f']()?`
`map['f'](arg)(arg2)`
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzI2NDEyMzI3Y2M3NjgxYzYyNWY4ZmEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.nTQFvmkXUbnl2WYFYAiLrms4zDEXNpG758JWjc7jPHQ">Huly&reg;: <b>V_0.6-21187</b></a></sub>
> v: allow `map[k]()?` and `map[k]()()`

- vlib/v/checker/tests/enum_redeclare_err.out
- vlib/v/checker/tests/enum_redeclare_err.vv
- vlib/v/parser/parser.v
Fix #22759
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJhMDQyOWU3Y2M1YTc4NTQyN2UxMmIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.bsG19_9zoDr2WoXBSxmsZJoqIYa6HMx6ugLqP649qBQ">Huly&reg;: <b>V_0.6-21213</b></a></sub>
> parser: fix enum redeclaration error

- vlib/v/gen/c/match.v
This PR removes an extra tab before return statement.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJhMjE4OGU3Y2M1YTc4NTQyODc2ZDIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.iwPe0vvWiTWeaHzkjhLtGIHAT4JGunbGVDS7RP_7498">Huly&reg;: <b>V_0.6-21215</b></a></sub>
> cgen: fix c codegen formatting for `return match`

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/testdata/unused_result_err.c.must_have
- vlib/v/gen/c/testdata/unused_result_err.vv
With this PR, code like the following:
```v
module main
fn res() ! {}
fn main() {
res() or {}
}
```
It will be generated in C like this:
```c
_result_void _t1 = main__res();
(void)_t1;
;
}
```
Previously it was generated like this:
```c
_result_void _t1 = main__res();
if (_t1.is_error) {
IError err = _t1.err;
}
;
}
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJiN2I5YWU3Y2M1YTc4NTQyOGMwMDgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.JIk2mdp4ZycKegOK1gb-kUK66CmsZRvuh43bsXZq6BU">Huly&reg;: <b>V_0.6-21221</b></a></sub>
> cgen: avoid generation of empty `or` block

- vlib/v/checker/fn.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/testdata/autofree_json_encode.c.must_have
- vlib/v/gen/c/testdata/autofree_json_encode.vv
Fix ved CI failure.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJiZjYxYmU3Y2M1YTc4NTQyOGY4YmEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.pKI_qNZxBTyTWabTVf2K1vLZYhBMCipmbLD_92g36zA">Huly&reg;: <b>V_0.6-21227</b></a></sub>
> autofree: fix argument freeing for json.encode and json.encode_pretty calls

- vlib/v/gen/c/cgen.v
- vlib/v/tests/structs/struct_field_name_using_c_keyword_test.v
This PR fix struct field name using c keyword `typeof` (fix #22779).
- Fix struct field name using c keyword `typeof`.
- Add test.
```v
struct Keywords {
typeof u8
}
fn main() {
key := Keywords{}
println(key)
}
Keywords{
typeof: 0
}
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJjMTVkYmU3Y2M1YTc4NTQyOGZjODUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.i4j_Jdt0rlML5ZOQrCgw1krVgDBLA4HPlFBUkk33gFo">Huly&reg;: <b>V_0.6-21228</b></a></sub>
> cgen: fix struct field name using c keyword `typeof` (fix #22779)

- vlib/picoev/loop_linux.c.v
`v -prod -gc none main.v -o main.c && gcc main.c `
```sh
main.c: In function ‘picoev__Picoev_poll_once’:
main.c:27012:54: warning: passing argument 2 of ‘epoll_wait’ from incompatible pointer type [-Wincompatible-pointer-types]
27012 |         int nevents = epoll_wait(pv->loop->epoll_fd, &pv->loop->events, _const_picoev__max_fds, (int)(max_wait_in_sec * 1000));
|                                                      ^~~~~~~~~~~~~~~~~
|                                                      |
|                                                      struct epoll_event (*)[1024]
In file included from main.c:1214:
/usr/include/x86_64-linux-gnu/sys/epoll.h:124:56: note: expected ‘struct epoll_event *’ but argument is of type ‘struct epoll_event (*)[1024]’
124 | extern int epoll_wait (int __epfd, …
```
> picoev: fix incompatible pointer type

- vlib/v/checker/assign.v
- vlib/v/checker/checker.v
- vlib/v/checker/str.v
- vlib/v/comptime/comptimeinfo.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/infix.v
This PR introduces `comptime.get_type_or_default` to simplify checking for comptime expr or getting its default value.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJiZTQwMWU3Y2M1YTc4NTQyOGY3M2EiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.PSXuFPdo_HMbJvGuWYCDE5w2kCk_tuBq_KhrvoPuB8U">Huly&reg;: <b>V_0.6-21226</b></a></sub>
> comptime: cleanup

- vlib/v/gen/c/if.v
- vlib/v/tests/if_guard_elseif_test.v
Fix #22784
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJjYjExZGU3Y2M1YTc4NTQyOTI3ZmQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.w09SV8ggqIFcrzogij1xyUlhp9E-H2r3zi2beBuDi6Q">Huly&reg;: <b>V_0.6-21232</b></a></sub>
> cgen: enable if guard to add `err` var on else branch after last `else if`

- vlib/v/checker/checker.v
- vlib/v/checker/str.v
- vlib/v/checker/tests/cast_integer_with_overflow_err.out
This PR fix a redundant message that appears when checking for integer literal casting.
Fix https://github.com/vlang/v/issues/22761.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJjYzBjNmU3Y2M1YTc4NTQyOTUwNDAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.6jilNTVuFKhUr8fz8_fUxXJntMFmKb0p-kk2FLQidVY">Huly&reg;: <b>V_0.6-21234</b></a></sub>
> checker: fix integer literal casting check (fix #22761)

- cmd/tools/modules/testing/common.v
- vlib/v/builder/msvc_windows.v
Fix #22772
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJjYzk2ZmU3Y2M1YTc4NTQyOTUyMGYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.gtek6uvdqdi2RsMlqlMUHBqY2rcUCAE5zuZB1gIefLk">Huly&reg;: <b>V_0.6-21235</b></a></sub>
> builder: fix msvc build thirdparty obj file from .cpp

- vlib/builtin/rune.v
- vlib/builtin/rune_map.v
- vlib/builtin/rune_test.v
This PR fix rune.to_title().
- Fix rune.to_title().
- Add tests.
```v
fn test_to_upper() {
assert `c`.to_upper() == `C`
assert `C`.to_upper() == `C`
assert `δ`.to_upper() == `Δ`
assert `Δ`.to_upper() == `Δ`
assert `ā`.to_upper() == `Ā`
assert `Ā`.to_upper() == `Ā`
assert `Я`.to_upper() == `Я`
assert `я`.to_upper() == `Я`
assert `ǅ`.to_upper() == `Ǆ`
assert `ǆ`.to_upper() == `Ǆ`
assert `Ǆ`.to_upper() == `Ǆ`
}
fn test_to_lower() {
assert `C`.to_lower() == `c`
assert `c`.to_lower() == `c`
assert `Δ`.to_lower() == `δ`
assert `δ`.to_lower() == `δ`
assert `Ā`.to_lower() == `ā`
assert `ā`.to_lower() == `ā`
assert `я`.to_lower() == `я`
assert `Я`.to_lower() == `я`
assert `ǅ`.to_lower() == `ǆ`
assert `Ǆ`.to_lower() == `ǆ`
assert `ǆ`.to_lower() == `ǆ`
}
fn test_to_title() {
assert `c`.to_title() == …
```
> builtin: fix rune.to_title()

- vlib/builtin/rune.v
This PR make a minor optimization in rune.map_to().
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJlMzQ1M2U3Y2M1YTc4NTQyOThhZDEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.QOQ7P1jdSmZv9yQO9jCc0kaFg943jrJapTiy2dOMAmg">Huly&reg;: <b>V_0.6-21256</b></a></sub>
> builtin: minor optimization in rune.map_to()

- vlib/v/checker/fn.v
Fix #22800
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJlMjkxNGU3Y2M1YTc4NTQyOTg5YzYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.XcG8I8aOlyApJ9TOUuA1uhEHkNTi9feaEodEi4AHkWg">Huly&reg;: <b>V_0.6-21255</b></a></sub>
> checker: fix callexpr after auto C func identification

- vlib/v/checker/fn.v
- vlib/v/tests/fns/param_fixed_array_const_test.v
Fix #22811
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJlN2NkOGU3Y2M1YTc4NTQyOTk3NzgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.K1k5rrMGWXmf0gUitraadXSiKYjYFVn8WE3E6gxePR0">Huly&reg;: <b>V_0.6-21258</b></a></sub>
> cgen: fix codegen for fn fixed array param w/ size defined by const

- vlib/v/ast/ast.v
- vlib/v/checker/checker.v
- vlib/v/checker/if.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/js/js.v
- vlib/v/parser/parser.v
- vlib/v/tests/typeof_indirections_test.v
This PR adds a way to retrieve the number of indirections related to `typeof(expr)` and `T` generic type.
```v
fn indirections[T](val T) int {
return T.indirections
}
a := 0
assert typeof(a).indirections == 0
assert indirections(a) == 0
b := &a
assert typeof(b).indirections == 1
assert indirections(b) == 1
c := [1]
assert typeof(c).indirections == 0
assert indirections(c) == 0
d := &c
assert typeof(d).indirections == 1
assert indirections(d) == 1
}
```
Related to #22792
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJlMDRhOGU3Y2M1YTc4NTQyOTdmOWEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.JzK …
> v: add `typeof(var).indirections` and `T.indirections`

- vlib/v/comptime/comptimeinfo.v
- vlib/v/gen/c/infix.v
- vlib/v/tests/comptime/comptime_infix_test.v
Fix bug spoted by @shove70  👍🏻
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJkZWVlMGU3Y2M1YTc4NTQyOTdiY2QiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.wO0P0qioOx0LslsAjNuK9x8RIJJjnr9MPDxIfdh_kIU">Huly&reg;: <b>V_0.6-21250</b></a></sub>
> comptime: fix wrong type resolution on infix

- vlib/v/checker/fn.v
- vlib/v/checker/tests/from_string_on_non_enum_err.out
- vlib/v/checker/tests/from_string_on_non_enum_err.vv
Fix bug spoted on @blackshirt asn1 pr #22783.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJkZTVlOWU3Y2M1YTc4NTQyOTc5ZGUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.NYDituPwxJq7Jsa2D_nnlwfNhU3CeFHRuEuKFPZ9CW4">Huly&reg;: <b>V_0.6-21249</b></a></sub>
> checker: fix missing auto `from_string` type restriction

- vlib/v/ast/types.v
- vlib/v/fmt/tests/struct_fixed_array_ident_keep.vv
This PR fixes `vfmt` changing `ed25519.public_key_size` (Ident) to `crypto.ed25519.public_key_size` (SelectorExpr) on:
```v
struct SSHClientHello {
version    u8
public_key [ed25519.public_key_size]u8
}
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJmNDU1Y2U3Y2M1YTc4NTQyOWRmYjYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.edgBZRfBYpfn0ZMvnYEcAck1h-xmdDn4BsxMH2oKUJo">Huly&reg;: <b>V_0.6-21261</b></a></sub>
> fmt: fix formatting fixed array size of struct member

- vlib/v/checker/containers.v
- vlib/v/checker/match.v
- vlib/v/tests/conditions/matches/match_expr_with_empty_array_init_test.v
This PR fix match expr with empty array init expression (fix #22828).
- Fix match expr with empty array init expression.
- Add test.
```v
fn main() {
arr1 := ['Peter', 'Bob']
arr2 := ['Sam', 'Mike']
typ := 1
names := match typ {
1 {
arr1
}
2 {
arr2
}
else {
[]
}
}
println(names)
assert names == ['Peter', 'Bob']
}
['Peter', 'Bob']
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzMyMjM5MmU3Y2M1YTc4NTQyYWRlMzMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.XVteL55gOSBkxwXUFuApwog97tfKHG0r27jfF3IYric">Huly&reg;: <b>V_0.6-21277</b></a></sub>
> checker: fix match expr with empty array init expression (fix #22828)

- vlib/v/ast/scope.v
- vlib/v/checker/assign.v
- vlib/v/checker/checker.v
- vlib/v/checker/lambda_expr.v
- vlib/v/fmt/fmt.v
- vlib/v/gen/c/assign.v
- vlib/v/gen/c/fn.v
This PR aims optimize scope usage.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzMyMzMzZWU3Y2M1YTc4NTQyYWUxNDUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.y96tJAyBIV1FTedfa74LMUuzhSQVjuE-yZHW7T2DrT4">Huly&reg;: <b>V_0.6-21278</b></a></sub>
> v: cleanup calls to Scope.find() methods

- cmd/tools/translate.v
- cmd/tools/vls.v
- cmd/tools/vsetup-freetype.v
- vlib/v/util/util.v
Prevent transient network problems from causing CI false positives like this one: https://github.com/vlang/v/actions/runs/11781538022/job/32814585067?pr=22832
> tools: use `v retry` in more places, that do network operations that can fail temporarily

- vlib/v/checker/if.v
- vlib/v/tests/conditions/ifs/if_expr_with_empty_array_init_test.v
This PR fix if expr with empty array init expression (related #22832).
- Fix if expr with empty array init expression.
- Add test.
```v
fn main() {
arr1 := ['Peter', 'Bob']
arr2 := ['Sam', 'Mike']
typ := 1
names := if typ == 1 {
arr1
} else if typ == 2 {
arr2
} else {
[]
}
println(names)
assert names == ['Peter', 'Bob']
}
['Peter', 'Bob']
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzMzMWMxZWU3Y2M1YTc4NTQyYjUxOTkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.o20ENs2aF_pRcDvJhGI4edxdclj2JE3FvVB-6HaKPfw">Huly&reg;: <b>V_0.6-21286</b></a></sub>
> checker: fix if expr with empty array init expression (related #22832)

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/testdata/if_else_return.c.must_have
- vlib/v/gen/c/testdata/if_else_return.out
- vlib/v/gen/c/testdata/if_else_return.vv
Fix #22838
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzMyYzA5NmU3Y2M1YTc4NTQyYjQwOTYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.1J9fbK_6LL9-824Ly15f1e7YSOYNttNpT_rjWldJUt8">Huly&reg;: <b>V_0.6-21284</b></a></sub>
> cgen: fix missing return code generated

- vlib/v/ast/scope.v
- vlib/v/parser/comptime.v
- vlib/v/parser/expr.v
- vlib/v/parser/parser.v
This PR aims cleanup mark var as used operation on Scope.
The logic was moved from parser to Scope.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzMzNGQ3M2U3Y2M1YTc4NTQyYjYyNzMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.nnx8Xugyn8sdy3c6X_dWjO2vfiGT12K1YVP7nPwKd7w">Huly&reg;: <b>V_0.6-21287</b></a></sub>
> v: cleanup mark var as used operation

- vlib/v/checker/lambda_expr.v
This PR makes a minor cleanup in lambda_expr.v.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzMzNmJkYWU3Y2M1YTc4NTQyYjY4ZWIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.LVNHodzWnmyMVqRg1sujwU3uVEEOn-hi5Yq9S3BzFMY">Huly&reg;: <b>V_0.6-21289</b></a></sub>
> checker: minor cleanup in lambda_expr.v

- vlib/v/checker/fn.v
- vlib/v/tests/generics/generics_with_empty_array_arg_test.v
This PR fix generic fn call with empty array argument (fix #22843).
- Fix generic fn call with empty array argument.
- Add test.
```v
fn count_str(array []string) int {
return array.len
}
fn count_int(array []int) int {
return array.len
}
fn count[T](array []T) int {
return array.len
}
fn main() {
assert count_str(['one', 'two']) == 2
assert count_str([]string{}) == 0
assert count_str([]) == 0
assert count_int([1, 2]) == 2
assert count_int([]int{}) == 0
assert count_int([]) == 0
assert count[f64]([1.0, 2.0]) == 2
assert count[f64]([]f64{}) == 0
assert count[f64]([]) == 0
assert count[int]([1, 2]) == 2
assert count[int]([]int{}) == 0
assert count[int]([]) == 0
}
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGci …
> checker: fix generic fn call with empty array argument (fix #22843)

- vlib/v/checker/fn.v
- vlib/v/checker/tests/array_method_call_immutable_err.out
- vlib/v/checker/tests/array_method_call_immutable_err.vv
- vlib/v/checker/tests/array_pop_immutable_err.out
- vlib/v/checker/tests/array_pop_immutable_err.vv
This PR check array builtin method call immutable errors (fix #22850).
- Check array builtin method call immutable errors.
- Add tests.
```v
fn main() {
a0 := [1, 2]
a1 := [3, 4]
a2 := [5, 6]
a3 := ['aa', 'bb']
a2.prepend(a1)
a1.insert(0, a0)
a3.sort_with_compare(fn (a &string, b &string) int {
if a < b {
return -1
}
if a > b {
return 1
}
return 0
})
a3.delete(0)
a2.pop()
a3.sort()
b0 := ['aa', 'bb']!
b0.sort_with_compare(fn (a &string, b &string) int {
if a < b {
return -1
}
if a > b {
return 1
}
return 0
})
b0.sort()
}
tt1.v:7:2: error: `a2` is immutable, declare it with `mut` to make it mutable
5 |     a3 := ['aa', 'bb']
6 | 
7 |     a2.prepend(a1)
|     ~~
8 |     a1.insert(0, a0)
9 |     a3.sort_with_compare(fn (a &string, b &string) int {
tt1.v:8:2: …
```
> checker: check array builtin method call immutable errors (fix #22850)

- vlib/v/checker/infix.v
- vlib/v/checker/tests/alias_array_unknown_op_overloading_err.out
- vlib/v/checker/tests/alias_array_unknown_op_overloading_err.vv
- vlib/v/tests/builtin_arrays/array_of_alias_op_overload_test.v
This PR check alias of array op overloading and fix op overloading (fix #22851).
- Check alias of array op overloading and fix op overloading.
- Add tests.
```v
type Array1 = []u8
type Array2 = []u8
fn (a Array2) == (other Array2) bool {
return a[0] == other[0]
}
fn (a Array2) < (other Array2) bool {
return a[0] < other[0]
}
fn main() {
a := Array1([u8(127), 0, 0, 1])
b := Array1([u8(127), 0, 0, 1])
c := Array2([u8(127), 0, 0, 1])
d := Array2([u8(127), 0, 0, 1])
println(a == b)
println(a < b)
println(c == d)
println(c < d)
}
tt1.v:20:12: error: only `==` and `!=` are defined on arrays
18 |
19 |     println(a == b)
20 |     println(a < b)
|               ^
21 |
22 |     println(c == d)
```
```v
type Array1 = []u8
type Array2 = []u8
fn (a Array2) == (other …
```
> checker: check alias of array op overloading and fix op overloading (fix #22851)

- vlib/v/ast/table.v
- vlib/v/checker/assign.v
- vlib/v/checker/fn.v
- vlib/v/checker/return.v
- vlib/v/gen/c/assign.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/fns/generic_static_method_call_test.v
Fix #22855
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzM3MjBkNmU3Y2M1YTc4NTQyZDBiMmEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.kI9zQMCN8HVa6tNeeTjhPmlMPm72A6rLWZvj7ieNZAY">Huly&reg;: <b>V_0.6-21308</b></a></sub>
> checker, cgen: fix generic static method call return type resolution

- vlib/v/checker/struct.v
- vlib/v/checker/tests/struct_aliased_field_unsign_type_check_err.out
- vlib/v/checker/tests/struct_aliased_field_unsign_type_check_err.vv
This PR check struct aliased field unsign type assigning negative value (fix #22868).
- Check struct aliased field unsign type assigning negative value.
- Add test.
```v
type Port = u16
struct App {
port Port
}
fn main() {
app := App{
port: -1
}
println(app)
}
tt1.v:9:9: error: cannot assign negative value to unsigned integer type
8 |     app := App{
9 |         port: -1
|               ~~
10 |     }
11 |     println(app)
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzM4M2FjN2U3Y2M1YTc4NTQyZDNkYjIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.NHWfJRENz5yKds8xw6ydP9x …
> checker: check struct aliased field unsign type assigning negative value (fix #22868)

- vlib/x/encoding/asn1/time.v
- vlib/x/encoding/asn1/time_test.v
When splitting the string representation of the time, the code did not previously allow for negative timezone offsets.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzM2MmRmMWU3Y2M1YTc4NTQyY2ViYmEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.dtHSbpN4XE_CBKgTuN3iaOQsWbLx36X-6_mwGi1u7rM">Huly&reg;: <b>V_0.6-21304</b></a></sub>
> encoding/asn1: fix time creation to also accommodate negative timezone offsets

- vlib/builtin/builtin.v
- vlib/v/ast/ast.v
- vlib/v/ast/scope.v
- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/checker/struct.v
- vlib/v/comptime/comptimeinfo.v
- vlib/v/gen/c/struct.v
This PR aims provide some optimization on cmd/v code.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzM4YjI3ZmU3Y2M1YTc4NTQyZDRiNjIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.lqJnc70Jhk0COSJJAUF-Odtx7LCTnzgnU03TkzJPVhg">Huly&reg;: <b>V_0.6-21321</b></a></sub>
> v: minor optimizations on `cmd/v`

- vlib/v/markused/markused.v
This PR cleanup some `-skip-unused` code.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzM4YTIxNGU3Y2M1YTc4NTQyZDQ5ZWUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.cnnE3VUIEx0k57SC74Gc3AgScluabOW9OKAFMvDm-E0">Huly&reg;: <b>V_0.6-21320</b></a></sub>
> v: `-skip-unused` cleanup

- vlib/v/checker/checker.v
- vlib/v/checker/tests/unused_param.out
- vlib/v/checker/tests/unused_param.vv
- vlib/v/compiler_errors_test.v
- vlib/v/parser/fn.v
- vlib/v/pref/pref.v
The PR should implement #22875 as desired.
Example:
NOTE: the v-analyzer hints won't work until this is on by default. For now, when compiling with `-check-unused-fn-args` you'll get:
```v
fn (unused_receiver Foo) method(unused_param int) {}
fn func(unused_param int) {}
```
```
❯ v -check-unused-fn-args run vlib/v/checker/tests/unused_param.vv
vlib/v/checker/tests/unused_param.vv:5:33: notice: unused parameter: `unused_param`
3 | struct Foo {}
4 | 
5 | fn (unused_receiver Foo) method(unused_param int) {}
|                                 ~~~~~~~~~~~~
6 | 
7 | fn func(unused_param int) {}
vlib/v/checker/tests/unused_param.vv:7:9: notice: unused parameter: `unused_param`
5 | fn (unused_receiver Foo) method(unused_param int) {}
6 | 
7 | fn func(unused_param int) {}
8 | …
```
> parser, checker, pref: allow getting notified about unused function params

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/struct.v
- vlib/v/tests/fixed_array_2_dims_init_test.v
Fix #22866
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzM4OWFhY2U3Y2M1YTc4NTQyZDQ5OTciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.OBnOZCbvk_blQHZ2VbHeJxt2OOxwIP_kY1GN26KPJJU">Huly&reg;: <b>V_0.6-21319</b></a></sub>
> cgen: fix array fixed code generation for more than 1 dimension

- vlib/v/ast/table.v
- vlib/v/checker/checker.v
- vlib/v/tests/aliases/alias_generic_struct_test.v
Fix #22866
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzM4ODcwYWU3Y2M1YTc4NTQyZDQ3M2YiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.dMkoaBwRGVWSeOWjuzQa8j276iG5BuIdCrWFSjKeIm8">Huly&reg;: <b>V_0.6-21315</b></a></sub>
> checker: fix alias to struct generic type

- vlib/v/markused/walker.v
- vlib/v/tests/skip_unused/aggregate_call.vv
Fix #22852
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzM5M2NjMGU3Y2M1YTc4NTQyZDVkYmQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.tZJ5RKJDi8vwVkuQAonfTlQptynrKdZrSxKRdN5kZq4">Huly&reg;: <b>V_0.6-21326</b></a></sub>
> v: fix `-skip-unused` error with aggregate method call

- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/match.v
- vlib/v/gen/c/testdata/comptime_if_cond.vv
- vlib/v/tests/comptime/comptime_if_cond_test.v
Fix #22873
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNhMjJhMGU3Y2M1YTc4NTQyZDhkNTMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.M7ERA4Rm2PK9vtufrKFX_pIEEAAbBMSFzmsPWqKfEsk">Huly&reg;: <b>V_0.6-21331</b></a></sub>
> cgen: fix codegen for if comptime with `-g`

- vlib/json/tests/json_test.v
- vlib/v/checker/fn.v
Fixes:
```v
error: expression cannot be passed as `voidptr`
20 | 
21 | if !os.is_file(path) {
22 |     os.write_file(path, json.encode_pretty(Config{}))!
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNhNzhiNWU3Y2M1YTc4NTQyZDk3YjUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.YWcl0rBFIQEjlsLQaOKxXqxuvL-WGm4IzZgsgyUiaLI">Huly&reg;: <b>V_0.6-21340</b></a></sub>
> checker: fix `json.encode_pretty` for struct expressions

- vlib/v/ast/ast.v
- vlib/v/checker/containers.v
- vlib/v/gen/c/array.v
- vlib/v/gen/c/struct.v
- vlib/v/tests/assign/array_fixed_init_with_call_test.v
Fix #22887
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNhMzE0NWU3Y2M1YTc4NTQyZDhmZTYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0._D7w6sKoyzp_0k4ZMmC-HANLaTLItOm8FTurn0S6CJk">Huly&reg;: <b>V_0.6-21334</b></a></sub>
> cgen, checker: fix codegen for fixed array initialization with fn call

- vlib/json/tests/json_decode_test.v
- vlib/v/gen/c/json.v
The changes make error messages for `json.decode` more informative. The reason is that error messages we'll get when walking back on the cJSON error_ptr can currently be empty and become hard to localize. The example below would currently just print an empty line.
```v
json_txt := 'abc'
_ := json.decode(Foo2, json_txt) or {
eprintln(err)
}
```
With the changes the errors message `failed to decode JSON string` is added. Similar to `failed to open file` during a `os.read_file` error.
---
This should help with the first of the two problems initially attempted to solve in #21184.
The second example in the linked PR could be addressed in a separate PR, where cgen is extended to add a check to verify the variable that should be decoded for validity.
<sub><a …
> cgen, json: make errors more informative (resolve empty panics)

- vlib/term/term.v
When using the term module for CLI projects, functions like `colorize` and other functions that check first for the ability to display colors can be called quite a lot. Currently the value of `can_show_color_on_stdout()->supports_escape_sequences()` is re-processed on every call of these functions.
https://github.com/vlang/v/blob/5bba92a65adfbd160c3f09c4315f609c76936532/vlib/term/term.v#L184-L202
The changes add a cache for the can_show_color status which results in a speedup of 100%+.
```v
import term
import time
sw := time.new_stopwatch()
for _ in 0 .. 10_000 {
term.ok_message('my message')
term.colorize(term.red, 'red')
}
println(sw.elapsed())
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNhMzhkZmU3 …
> term: improve performance by caching redundant can_show_color calls

- vlib/v/gen/c/json.v
A tiny chore, not worth the CI run on a busier time of the day.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNhZDBmOWU3Y2M1YTc4NTQyZGE1NmMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.ORuM8aU3LQkU6SLjRE42Bn_ClAQotZvKWblwhjsX9yQ">Huly&reg;: <b>V_0.6-21342</b></a></sub>
> cgen: generate cjson array lines on uniform indent lvl

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/blocks_keep.vv
- vlib/v/gen/golang/golang.v
- vlib/v/tests/structs/struct_local_test.v
- vlib/x/json2/decoder2/decode_test.v
This PR fix formating non-unsafe blocks with break line (fix #22900).
- Fix formating non-unsafe blocks with break line.
- Add test.
blocks_keep.vv
```v
fn main() {
{
println('(1/3) My first small scope')
//
}
{
println('(2/3) My second small scope')
//
}
// A line below prevents the line removal
{
println('(3/3) My Third small scope')
}
}
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNiNDIyOGU3Y2M1YTc4NTQyZGM2YjYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.wuM0irfqiwgS5_ZDZb1ke71QTvvcEwAka0FNGTcBD7k">Huly&reg;: <b>V_0.6-21346</b></a></sub>
> fmt: fix formating non-unsafe blocks with break line (fix #22900)

- .github/workflows/build_vinix_locally.sh
- .github/workflows/vinix_ci.yml
- CONTRIBUTING.md
- Dockerfile
- README.md
- doc/docs.md
The big advantage of using `--depth=1` as the default instruction, is that it only downloads ~10MB currently, and that will stay more or less the same (it is proportional to the compressed size of the files in the latest checkout, and is not proportional to the size of the complete history).
It has big drawbacks for people that want to contribute actively to V, because cloning with `--depth=1` will mean that they will not get the complete history of the project, and some tooling uses that (bisecting for problems, `git blame` etc, are much more effective in a repository that has the complete history).
A complete clone, currently downloads ~79MB in contrast, and can fail more easily for people that have less reliable or slower networks.
> docs: change installation instructions for cloning the V repository to use `--depth=1`

- vlib/v/gen/c/cgen.v
- vlib/v/tests/fns/aliased_interface_methods_test.v
Fix #22901
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNiMmUyMGU3Y2M1YTc4NTQyZGMyNzMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.M9Dw7WnSxXHQa5PSCPi-ZHNiUNLsznebb9RSDdJfPWM">Huly&reg;: <b>V_0.6-21345</b></a></sub>
> cgen: fix codegen for alias type interface methods

- vlib/v/parser/fn.v
Instead of comparing the whole type_pos struct this can be the key index.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNjMjRlNGU3Y2M1YTc4NTQyZGY5YWIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.3cr_Vo3JZzTM_z3JaGqD9Ftm8NpJC5TF9ATsVsW8gwI">Huly&reg;: <b>V_0.6-21358</b></a></sub>
> parser: optimize method parameter detection in used check

- vlib/v/scanner/scanner.v
This PR simplifies the scanner, removing the `is_started` field from `Scanner`. Now, `Scanner.pos` will have a default value of `-1`.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNkMGQzMGU3Y2M1YTc4NTQyZTJmZTYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.jBmHOld03sjIHI1Ws_8XnsQtoTpMDlwZDTrxSNdq2NY">Huly&reg;: <b>V_0.6-21361</b></a></sub>
> scanner: remove `Scanner.is_started` field

- doc/docs.md
An attempt to describe V's module hierarchy. Warning: Written by a v beginner, and non native speaker. Read carefully to avoid wrong informations.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNkMWNmNWU3Y2M1YTc4NTQyZTMxM2MiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.HDVbj98ED-jJsc-q5tYAJ1ChgYQ8kXwZgMHxruvqScM">Huly&reg;: <b>V_0.6-21362</b></a></sub>
> Update docs.md. Added module hierarchy paragraph.

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/for.v
- vlib/v/gen/c/struct.v
- vlib/v/tests/options/option_array_fixed_test.v
- vlib/v/tests/options/option_fixed_array_2_test.v
Fix #22910
Fix #22911
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNiYjJiNWU3Y2M1YTc4NTQyZGVhZjAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.wKm0kKjIIHodWf1qYndZnXzldOV-D51T1BuueReAtJw">Huly&reg;: <b>V_0.6-21355</b></a></sub>
> cgen: fix codegen for returning option aliased fixed array 

- vlib/v/gen/c/infix.v
- vlib/v/tests/aliases/alias_fixed_array_infix_expr_test.v
This PR fix aliases of fixed array infix expression (fix #22925).
- Fix aliases of fixed array infix expression.
- Add test.
```v
import encoding.binary
pub type Addr = [4]u8
pub fn (a Addr) u32() u32 {
return binary.big_endian_u32_fixed(a)
}
pub fn (a Addr) == (oth Addr) bool {
return a.u32() == oth.u32()
}
pub fn (a Addr) < (oth Addr) bool {
return a.u32() < oth.u32()
}
fn main() {
addr := Addr([u8(127), 0, 0, 1]!)
assert addr == Addr([u8(127), 0, 0, 1]!)
assert Addr([u8(127), 0, 0, 1]!) == addr
assert addr == [u8(127), 0, 0, 1]!
assert [u8(127), 0, 0, 1]! == addr
assert addr < Addr([u8(127), 0, 0, 2]!)
assert addr < [u8(127), 0, 0, 2]!
}
D:\Test\v\tt1> v run .
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQ …
> cgen: fix aliases of fixed array infix expression (fix #22925)

- vlib/v/gen/c/infix.v
- vlib/v/tests/aliases/alias_fixed_array_append_to_array_test.v
This PR fix aliases of fixed array append to array (fix #22926).
- Fix aliases of fixed array append to array.
- Add test.
```v
pub type Addr = [4]u8
fn main() {
mut my_array := []Addr{}
for i := 0; i <= 3; i++ {
my_array << Addr([u8(10), 0, 0, u8(i)]!)
}
println(my_array)
assert my_array[0] == Addr([u8(10), 0, 0, 0]!)
assert my_array[1] == Addr([u8(10), 0, 0, 1]!)
assert my_array[2] == Addr([u8(10), 0, 0, 2]!)
assert my_array[3] == Addr([u8(10), 0, 0, 3]!)
}
[[10, 0, 0, 0], [10, 0, 0, 1], [10, 0, 0, 2], [10, 0, 0, 3]]
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNlYzkwNmU3Y2M1YTc4NTQyZWEyZTgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6 …
> cgen: fix aliases of fixed array append to array (fix #22926)

- vlib/veb/veb.v
veb: fix error with large file transfer. issue #22489
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNlNTEzOGU3Y2M1YTc4NTQyZTY5ZDEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.QuLos9j-LKtUnGRSLsF54esfSdAe9mNA7xZ6_KXrOUo">Huly&reg;: <b>V_0.6-21366</b></a></sub>
> veb: fix large file transfer

- vlib/v/gen/c/cgen.v
- vlib/v/tests/aliases/aliased_fixed_array_option_fn_call_test.v
This PR fix aliased fixed array option fn call (fix #22927).
- Fix aliased fixed array option fn call.
- Add test.
```v
import encoding.binary
pub type Addr = [4]u8
pub fn Addr.from_u32(a u32) Addr {
mut bytes := [4]u8{}
binary.big_endian_put_u32_fixed(mut bytes, a)
return Addr(bytes)
}
pub fn (a Addr) u32() u32 {
return binary.big_endian_u32_fixed(a)
}
struct Net {
netaddr   Addr
broadcast Addr
}
// returns Nth IP-address from the network if exists, else none
fn (n Net) nth(num i64) ?Addr {
mut addr := Addr{}
if num >= 0 {
addr = Addr.from_u32(n.netaddr.u32() + u32(num))
} else {
addr = Addr.from_u32(n.broadcast.u32() + u32(num))
}
if !(n.netaddr.u32() < addr.u32() && addr.u32() < n.broadcast.u32()) {
return none
}
return addr
}
fn main() {
net := Net{
netaddr:   Addr([u8(172), 16, 16, …
```
> cgen: fix aliased fixed array option fn call (fix #22927)

- vlib/v/gen/c/infix.v
- vlib/v/tests/builtin_arrays/dump_fixed_array_on_array_append_test.v
This PR fix dump fixed array on array append (fix #22935).
- Fix dump fixed array on array append.
- Add test.
```v
fn main() {
mut myarr := [][3]u8{}
myarr << [u8(1), 2, 3]!
myarr << [u8(4), 5, 6]!
myarr << [u8(7), 8, 9]!
println(myarr)
assert myarr[0] == [u8(1), 2, 3]!
assert myarr[1] == [u8(4), 5, 6]!
assert myarr[2] == [u8(7), 8, 9]!
mut myarr2 := [][3]u8{}
myarr2 << dump([u8(1), 2, 3]!)
myarr2 << dump([u8(4), 5, 6]!)
myarr2 << dump([u8(7), 8, 9]!)
println(myarr2)
assert myarr2[0] == [u8(1), 2, 3]!
assert myarr2[1] == [u8(4), 5, 6]!
assert myarr2[2] == [u8(7), 8, 9]!
}
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[.\\tt1.v:12] [u8(1), 2, 3]u8{}: [1, 2, 3]
[.\\tt1.v:13] [u8(4), 5, 6]u8{}: [4, 5, 6]
[.\\tt1.v:14] [u8(7), 8, 9]u8{}: [7, 8, 9]
[[1, 2, 3], [4, 5, 6], [7, 8, …
```
> cgen: fix dump fixed array on array append (fix #22935)

- vlib/net/http/backend.c.v
- vlib/net/http/backend_vschannel_windows.c.v
- vlib/net/http/http_proxy.v
- vlib/net/http/request.v
- vlib/net/http/server_test.v
This PR tries to fix the `Host` header, making sure that the port is included when we are not using ports 80 and 443. 
Ignoring the port breaks allow rules for servers that check the Host header, Caddy for instance uses it for the Admin API `localhost:2019/config`.
- https://github.com/vlang/v/issues/22941
```v
fn main() {
mut response := http.get('https://anything.vithorio.codes:2033/path') or { panic(err) }
if response.status() != .ok {
eprintln('Error executing start action. Status: ${response.status()}\n${response.body}')
}
eprintln('result: ${response.body}')
}
```
Should print:
```
result: yay \o/ host anything.vithorio.codes 2033 anything.vithorio.codes:2033
```
While a bad result will print:
```
result: NO PORT anything.vithorio.codes  anything.vithorio.codes
``` …
> net.http: build Host headers with port (fix #22941)

- vlib/v/checker/fn.v
- vlib/v/checker/tests/method_call_on_undefined_err.out
- vlib/v/checker/tests/method_call_on_undefined_err.vv
Fix #22949
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQxZWM4OWQyZWY0Y2JjYzQ2ODQ1MzQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.jxdSbAfF_pKo0PnkhTolIFcIVBNfMLcBut25vDy4gYc">Huly&reg;: <b>V_0.6-21392</b></a></sub>
> checker: fix or-expr check on invalid method call 

- vlib/v/ast/table.v
- vlib/v/gen/c/str_intp.v
- vlib/v/tests/enums/enum_print_test.v
Fix #22938
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQxYmNhZmQyZWY0Y2JjYzQ2ODFkOTgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.d0-yvSZoOuyQgbyJWZxFyMJGBvze_KVTMmHMUjvkaWs">Huly&reg;: <b>V_0.6-21387</b></a></sub>
> cgen: fix enum value to print like its declared enum underlying type

- cmd/tools/vvet/tests/array_init_one_val.out
- cmd/tools/vvet/tests/indent_with_space.out
- cmd/tools/vvet/vvet.v
This PR makes the output for `v vet` a little nicer by making the notice print include the actual offending files instead of the example file `file.v` (which may or may not exist, or be offending):
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQyOWE4M2QyZWY0Y2JjYzQ2ODUzNjQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.5Ot7lMtWc7zhSmpkIn0MQrv5jQ_8tGlpeQFuiQ1hSTk">Huly&reg;: <b>V_0.6-21398</b></a></sub>
> vet: make `v vet` produce a nicer note, including the offending files, instead of the example `file.v`

- vlib/v/checker/comptime.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/testdata/if_define_check_not_set.out
- vlib/v/gen/c/testdata/if_define_check_not_set.vv
- vlib/v/gen/c/testdata/if_define_check_set.out
- vlib/v/gen/c/testdata/if_define_check_set.vv
- vlib/v/pref/pref.v
Fix #22906
This PR treats `-d custom_define` and `-d custom_define=<something>` as set. And `-d custom_define=` as unset.
Currently `-d custom_define=foo` was not treated as defined.
PS: With this PR `-d foo=0` is a set one.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQxZDIzYWQyZWY0Y2JjYzQ2ODMyZjIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.rr9k-IYqRXXG_riEPzR2l_yjB1ChmF798_wCYA2jJ3o">Huly&reg;: <b>V_0.6-21388</b></a></sub>
> checker, cgen: fix if define comptime checking 

- vlib/v/ast/ast.v
- vlib/v/checker/checker.v
- vlib/v/checker/for.v
- vlib/v/checker/if.v
- vlib/v/checker/infix.v
- vlib/v/checker/match.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/generics/generic_selector_test.v
- vlib/v/tests/options/option_var_mut_test.v
- vlib/v/tests/options/option_var_test.v
Fix #22936
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQxMWQ5ZWQyZWY0Y2JjYzQ2ODE0ZTMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.lZlq6S-antknaTur7zc7jHVoVGeTmiGFukJlMVhrFu0">Huly&reg;: <b>V_0.6-21385</b></a></sub>
> checker: fix mut var option unwrap with `!= none`

- vlib/v/gen/c/cgen.v
- vlib/v/tests/options/modules/mymod/mod.v
- vlib/v/tests/options/modules/mymod/mod_test.v
Fix #22961
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQzNjIxOWQyZWY0Y2JjYzQ2ODcxNTciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.9gkfst2bAu9rNr9EE4qx8vAZWGkduyBEsi5RJ_PdyGE">Huly&reg;: <b>V_0.6-21404</b></a></sub>
> cgen: fix codegen for result/option propagation out of fn context

- vlib/v/gen/c/cgen.v
- vlib/v/tests/options/option_concatexpr_test.v
Fix #22951
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQzNzI2M2QyZWY0Y2JjYzQ2ODcyOWYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.mqeeNdg3gDMJ0s69W3-jOwuvtI_B4dmYoKJyfuM0tnI">Huly&reg;: <b>V_0.6-21405</b></a></sub>
> cgen: fix codegen for option on concatexpr

- vlib/x/encoding/asn1/element.v
- vlib/x/encoding/asn1/element_decode.v
- vlib/x/encoding/asn1/element_encode.v
- vlib/x/encoding/asn1/field_options.v
- vlib/x/encoding/asn1/other_element.v
- vlib/x/encoding/asn1/sequence.v
- vlib/x/encoding/asn1/set.v
- vlib/x/encoding/asn1/tagged_test.v
- vlib/x/encoding/asn1/time.v
- vlib/x/encoding/asn1/time_test.v
This PR is rather of
follow-up from previous PR in attempt to improves `x.encoding.asn1` module, as availables  in [22948](https://github.com/vlang/v/pull/22948), [22932](https://github.com/vlang/v/pull/22932), [22861](https://github.com/vlang/v/pull/22861), and [22847](https://github.com/vlang/v/pull/22847) PRs.
This PR contains some small changes to the module:
- Refinement to align with the latest fix of Option unwrapping. (mostly from @felipensp, thank guys)
- Just removes `.str()` from sequence and set for now, its needed to allow just dump current sequence fields.
- Unifies some of `RawElement` methods
- Some small refinements.
The latest bench run with `-prod` flag results in
```v
Benchmarking ASN.1 encode...
Average example encode time: 1 µs
Benchmarking ASN.1 decode (with …
```
> `x.encoding.asn1`: another minor  cleanup

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/if.v
- vlib/v/gen/c/past_tmp_var.v
- vlib/v/gen/c/str.v
- vlib/v/gen/c/str_intp.v
- vlib/v/gen/c/testdata/alias_char_ptr_to_ptr.c.must_have
- vlib/v/gen/c/testdata/if_else_return.c.must_have
This PR aims to reduce code generated for returning values when possible.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQzOWJkY2QyZWY0Y2JjYzQ2ODdiYjUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.03brLuMMcP1Ehc4BYtRkcxEekeB7C9H5vrWt7SqyKus">Huly&reg;: <b>V_0.6-21408</b></a></sub>
> cgen: reduce code for returning and extra whitespaces on `return`

- vlib/v/ast/table.v
- vlib/v/checker/checker.v
- vlib/v/checker/comptime.v
- vlib/v/debug/debug.v
- vlib/v/markused/markused.v
- vlib/v/pref/pref.v
This PR fixes:
v -skip-unused test vlib/toml/tests/encode_and_decode_test.v 
v -skip-unused test vlib/v/debug/interactive_test.v
> v: fix `-skip-unused` feature for some broken tests

- vlib/v/checker/fn.v
- vlib/v/checker/tests/array_fancy_sort_err.out
- vlib/v/checker/tests/array_fancy_sort_err.vv
- vlib/v/gen/c/array.v
- vlib/v/tests/builtin_arrays/array_sort_with_call_test.v
Fix #22988
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQ3MGEzN2QyZWY0Y2JjYzQ2YmM2NzkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.TgtBjxDiMvVQKOSQwnA1OwmhwcbWlDXFxcnH0ASRJL4">Huly&reg;: <b>V_0.6-21430</b></a></sub>
> checker: allow array sort with callexpr

- vlib/builtin/map.v
- vlib/v/ast/table.v
- vlib/v/checker/checker.v
- vlib/v/checker/containers.v
- vlib/v/checker/fn.v
- vlib/v/checker/for.v
- vlib/v/checker/str.v
- vlib/v/gen/c/cgen.v
- vlib/v/markused/markused.v
- vlib/v/markused/walker.v
- vlib/v/pref/pref.v
This PR fixes some missing break when enabling `-skip-unused` as default.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQ1YTc3MWQyZWY0Y2JjYzQ2YjY0MTEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.3U2IzRbslNDk7dbxq3z9z_oWiXLw1M0ezBxbXdlBU4c">Huly&reg;: <b>V_0.6-21419</b></a></sub>
> v: missing `-skip-unused` fixes

- vlib/v/gen/c/cgen.v
- vlib/v/tests/sumtypes/sumtype_with_embedded_struct_of_option_field_test.v
This PR fix sumtype with embedded struct of option field (fix #22984).
- Fix sumtype with embedded struct of option field.
- Add test.
```v
struct Value {
x int
}
struct BValue {
v ?Value
}
struct Word {
BValue
}
struct Long {
BValue
}
struct Variadic {
BValue
}
type Param = Word | Long | Variadic
fn main() {
a := [Param(Word{}), Long{}, Variadic{}]
dump(a)
f := a[0]
v := f.v
dump(v)
assert v == none
}
[.\\tt1.v:25] a: [Param(Word{
BValue: BValue{
v: Option(none)
}
}), Param(Long{
BValue: BValue{
v: Option(none)
}
}), Param(Variadic{
BValue: BValue{
v: Option(none)
}
})]
[.\\tt1.v:28] v: Option(none)
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQ4MDc4MWQyZWY0Y2JjYzQ2YmU1MGUiL …
> cgen: fix sumtype with embedded struct of option field (fix #22984)

- vlib/v/markused/walker.v
Some fixes I've done detected by running `--skip-unused` on v.ui, vtl, vsl, ved etc.
- Make walker visit more nodes (e.g. `{...foo}`)
- Handle function as global var
- Load embeded struct definition
- Load struct when used on []Struct
- Load struct when used on map[k]Struct
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRhMTRkZWQyZWY0Y2JjYzQ2Y2E4ZGYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.CQtXAC9i_bbB2q0o0BBOPeYQJcPlfwH5Lem8JFMk_AI">Huly&reg;: <b>V_0.6-21449</b></a></sub>
> markused: fixing missing info tracking on walker

- vlib/v/gen/c/auto_str_methods.v
- vlib/v/tests/printing/dump_interface_circular_test.v
Fix #23022
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRiOTg0YmQyZWY0Y2JjYzQ2Y2YxOTIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.1ob6u5fq9YfonAJfeJ2UYB08XCTs4XogPo1uUjGQPJM">Huly&reg;: <b>V_0.6-21467</b></a></sub>
> cgen: fix autostr for interface with circular type

- vlib/x/json2/decoder2/decode.v
- vlib/x/json2/decoder2/tests/decode_object_test.v
Note: pretty useful code to find and fix json related bugs. maybe I should bind it in debug a day
```v
@[direct_array_access; manualfree]
pub fn push_bytes_repeatedly_into_the_buffer(byte_ u8, repetitions int, mut buffer []u8) {
if repetitions <= 0 {
return
}
mut bytes_ptr := unsafe { malloc_noscan(repetitions + 1) }
unsafe {
C.memset(bytes_ptr, byte_, repetitions)
buffer.push_many(bytes_ptr, repetitions)
free(bytes_ptr)
}
}
// str_info returns a string representation of the linked list.
pub fn (list LinkedList) str_info(json string) string {
mut result_buffer := []u8{}
result_buffer << u8(\n)
mut current := list.head
for current != unsafe { nil } {
value_kind_as_string := current.value.value_kind.str()
unsafe {
result_buffer.push_many(json.str + current.value.position, …
```
> x.json2.decoder2: nested map

- vlib/orm/README.md
The loose backtick will look ahead to the next backtick, which is on the next line, which messes up the whole list. Also I had to insert a newline for some reason to get it to generate properly.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRjYWIzMWQyZWY0Y2JjYzQ2ZDBjYjYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.Bzh8pfKPXQmjcmmrTg1VKxpeYhnMUYWoyNv9XERAxZM">Huly&reg;: <b>V_0.6-21479</b></a></sub>
> orm: fix list generation and escape loose backtick

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/fns/const_call_or_expr_test.v
Fix #23029
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRjZDNmMGQyZWY0Y2JjYzQ2ZDEyNzciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.yHSnjgbAPOPAPB9h--dlvCTCBshNboyWavPuUpQiHUg">Huly&reg;: <b>V_0.6-21483</b></a></sub>
> cgen: fix callexpr or-expr codegen on const decl

- vlib/v/gen/c/json.v
This PR makes a minor cleanup in gen_jsons().
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRkMjY5MGQyZWY0Y2JjYzQ2ZDQxMTMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.KSm4u9l3dPk9M8SN-qfMXwUjPXe1eXm6CCdX_Kyoxp8">Huly&reg;: <b>V_0.6-21484</b></a></sub>
> cgen: minor cleanup in gen_jsons()

- vlib/v/checker/return.v
- vlib/v/tests/generics/generics_return_closure_test.v
This PR fix generic fn returning generic closure (fix #23035).
- Fix generic fn returning generic closure.
- Add test.
```v
fn vectorize[T](op fn (T) T) fn ([]T) []T {
return fn [op] [T](values []T) []T {
mut result := []T{len: values.len}
for i in 0 .. values.len {
result[i] = op(values[i])
}
return result
}
}
fn add_one(x f64) f64 {
return x + 1
}
fn main() {
vadd := vectorize[f64](add_one)
v := [1.0, 2, 3, 4]
println(vadd(v))
assert vadd(v) == [2.0, 3, 4, 5]
}
[2.0, 3.0, 4.0, 5.0]
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRkNzIxZGQyZWY0Y2JjYzQ2ZDU3NjEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0 …
> checker: fix generic fn returning generic closure (fix #23035)

- vlib/v/checker/return.v
- vlib/v/checker/tests/generics_fn_return_generic_closure_err.out
- vlib/v/checker/tests/generics_fn_return_generic_closure_err.vv
- vlib/v/parser/fn.v
- vlib/v/tests/generics/generics_return_closure_test.v
This PR fix generic fn returning generic closure (related #23047).
- Fix generic fn returning generic closure.
- Add tests.
```v
fn vectorize[T](op fn (T) T) fn ([]T) []T {
return fn [op] [T](values T) []T {
mut result := []T{}
return result
}
}
fn add_one(x f64) f64 {
return x + 1
}
fn main() {
vadd := vectorize[f64](add_one)
v := [1.0, 2, 3, 4]
println(vadd(v))
}
tt1.v:2:9: error: cannot use `fn (f64) []f64` as type `fn ([]f64) []f64` in return argument
1 | fn vectorize[T](op fn (T) T) fn ([]T) []T {
2 |     return fn [op] [T](values T) []T {
|            ~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 |         mut result := []T{}
4 |         return result
```
```v
fn vectorize[T](op fn (T) T) fn ([]T) []T {
return fn [op] [T](values []T) []T {
mut result := []T{len: …
```
> parser, checker: fix generic fn returning generic closure (related #23047)

- vlib/v/gen/c/reflection.v
- vlib/v/tests/reflection_attr_quotes_test.v
Fix #23046
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRkYmMyMGQyZWY0Y2JjYzQ2ZDY3MzYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.lZenE7HlN8O_EHluxQssFehJHuU_kt6TkLGJyx_brIo">Huly&reg;: <b>V_0.6-21490</b></a></sub>
> v.reflection: fix codegen to work with quoted strings on attr value

- vlib/v/markused/markused.v
- vlib/v/markused/walker.v
This PR fixes V DOOM build with `-skip-unused` without code changes on the project.
On `-translated` ... with this PR:
Functions tagged by `@[c:'foo']` are implicitly marked as useds.
Constantes tagged by `@[export: '']` are implicitly marked as useds.
This PR also fixes markused on source that has fn prototype + fn declaration. Before this PR the declaration that was traversed was the no_body one, so no code was visited.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRkZGMzNWQyZWY0Y2JjYzQ2ZDZkMzYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.5pOmGOzW3u1WwAbqkMmUpencV41jCo-QWLl-H9BnA9I">Huly&reg;: …
> markused: make some attrs on `@[translated]` be implicit `@[markused]` + fix FnDecl visitor (when no_body is present)

- vlib/builtin/array.v
- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/checker/tests/array_count_err.out
- vlib/v/checker/tests/array_count_err.vv
- vlib/v/fmt/fmt.v
- vlib/v/gen/c/array.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/infix.v
- vlib/v/gen/golang/golang.v
- vlib/v/parser/parser.v
- vlib/v/tests/builtin_arrays/array_count_test.v
This PR implements builtin array.count() (including fixed array version).
Fix #23028
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRlNTA4NmQyZWY0Y2JjYzQ2ZDdjNTAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.t-J4yxLmEm3DkmwEnI8P_TfWGEWOze_CSWbQaluSZIg">Huly&reg;: <b>V_0.6-21494</b></a></sub>
> v: add array.count

- vlib/v/checker/tests/orm_unused_var.out
- vlib/v/checker/tests/orm_unused_var.vv
- vlib/v/compiler_errors_test.v
- vlib/v/parser/orm.v
Fix #23032
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRjYTBkOWQyZWY0Y2JjYzQ2ZDA5ZTciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.HvWcDQWAigqr5yLpIVAT9nxUBZgO22j3naRbnQHmzbQ">Huly&reg;: <b>V_0.6-21478</b></a></sub>
> orm: fix mark as used var on insert statement

- vlib/v/checker/checker.v
- vlib/v/checker/tests/cast_to_concrete_mut_err.out
- vlib/v/checker/tests/cast_to_concrete_mut_err.vv
Fix #23017
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRlZTRmOWQyZWY0Y2JjYzQ2ZGM0NjMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.Xvf9dfnmx4nG4Q5Qwc4efAuEUF4imrk7fNFWv1rsPJ0">Huly&reg;: <b>V_0.6-21496</b></a></sub>
> checker: fix missing checker for cast from mut var to non-ptr type

- .github/workflows/v_apps_and_modules_compile_ci.yml
- vlib/builtin/string.v
- vlib/compress/zstd/zstd.c.v
- vlib/crypto/scrypt/scrypt.v
- vlib/os/os.c.v
- vlib/rand/rand.c.v
- vlib/v/ast/table.v
- vlib/v/ast/types.v
- vlib/v/checker/check_types.v
- vlib/v/checker/struct.v
- vlib/v/checker/tests/fn_call_arg_mismatch_err_e.out
- vlib/v/checker/tests/fn_call_arg_mismatch_err_e.vv
- vlib/v/checker/tests/globals/global_receiver_var_name_err.vv
- vlib/v/gen/c/cgen.v
- vlib/v/tests/if_guard_elseif_test.v
- vlib/v/tests/reflection_sym_test.v
- vlib/v/tests/reflection_test.v
- vlib/x/json2/encoder.v
This PR check fn call argument mismatch (fix #23016).
- Check fn call argument mismatch.
- Add test.
```v
fn f(x int) {
println(x)
}
fn main() {
x := u32(2251797157)
println(x)
f(x)
}
tt1.v:8:4: error: cannot use `u32` as `int` in argument 1 to `f`
6 |     x := u32(2251797157)
7 |     println(x)
8 |     f(x)
|       ^
9 | }
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRmYzZlYmQyZWY0Y2JjYzQ2ZTE2NGIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.zJ7pi-9H-EX2DushtECBXUhwIZPqAbtXmDXQSpAFxGQ">Huly&reg;: <b>V_0.6-21501</b></a></sub>
> checker: check fn call argument mismatch (fix #23016)

- vlib/v/preludes/test_runner_teamcity.v
Running tests in intellij idea 2024.3 makes IDE panic and report following error:
```Failed to parse service message
Details: ##teamcity[ testFailed name='test_failing' duration='0' details='See failed assertion: /home/jakub/repos/villmo/src/villmo/gen/llvm/simple_test.v:12' type='comparisonFailure' actual='4' expected='100' message='Assertion "four == 100" failed' ]
testFramework:V Test
java.text.ParseException: Error while parsing TeamCity service message: Incorrect property name "testFailed name": should not contain spaces. Valid service message has a form of "##teamcity[messageName name1='escaped_value' name2='escaped_value']" where escaped_value uses substitutions: '->|', [->|[, ]->|], |->||, newline->|n
at jetbrains.buildServer.messages.serviceMessages.MapSerializerUtil.parseName(Map …
```
> Fix teamcity reporter message formatting

- vlib/v/markused/markused.v
- vlib/v/markused/walker.v
markused simplification.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzUxODFlMWQyZWY0Y2JjYzQ2ZWNjNTMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.iwb65deH3JOcQPQRmyr01YQB_asGq02uimImnejtvig">Huly&reg;: <b>V_0.6-21510</b></a></sub>
> markused: remove 2 loops across `all_fns`

- vlib/v/gen/c/cgen.v
- vlib/v/tests/casts/cast_interface_value_in_match_test.v
This PR fix cast interface value in match expr (fix #23060).
- Fix cast interface value in match expr.
- Add test.
```v
interface Number2 {}
fn t(v Number2) {
match v {
int, i32, isize, i64 {
x := isize(v)
println(x)
assert x == 42
}
else {}
}
match v {
int {
x := isize(v)
println(x)
assert x == 42
}
else {}
}
}
fn main() {
t(int(42))
}
42
42
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzUxNjc4ZGQyZWY0Y2JjYzQ2ZWM2YjYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.aHvyD-V7Y-Og3FNwlRihPRUiamOnfC8gRUMx6_Pyhlg">Huly&reg;: <b>V_0.6-21508</b></a></sub>
> cgen: fix cast interface value in match expr (fix #23060)

- vlib/v/ast/ast.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/parser/struct.v
This PR aims to fix msvc build removing usage of `ADDR` macro on `__as_cast()` calls which makes msvc messed up with precedence order (even on non-prod builds)
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzUzOTNmN2QyZWY0Y2JjYzQ2ZjcxYmYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.sCHpATrHoctpB5Alh9H8mKV6ZBRDWmJiB9H6DISV6bk">Huly&reg;: <b>V_0.6-21522</b></a></sub>
> cgen: fix smartcast codegen for msvc

- vlib/v/parser/fn.v
- vlib/v/tests/keyword_as_params_field_test.v
Fix #23091
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU0YWRlNGQyZWY0Y2JjYzQ2ZjgwNTMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.Cg02VkEKULKBQgf4xQBwcaqbRV0x9qvElJxpWosPHTY">Huly&reg;: <b>V_0.6-21536</b></a></sub>
> parser: allow `type` as field type on params struct construction

- vlib/v/checker/fn.v
- vlib/veb/tests/cors_2_test.v
This PR fix veb route method param with non ctx name (fix #23105).
- Fix veb route method param with non ctx name.
- Add test.
```v
import veb
pub struct User {
pub mut:
name string
id   int
}
// Our context struct must embed `veb.Context`!
pub struct Context {
veb.Context
pub mut:
// In the context struct we store data that could be different
// for each request. Like a User struct or a session id
user       User
session_id string
}
pub struct App {
pub:
// In the app struct we store data that should be accessible by all endpoints.
// For example, a database or configuration values.
secret_key string
}
// This is how endpoints are defined in veb. This is the index route
pub fn (app &App) index(mut context Context) veb.Result {
return context.text('Hello V! The secret key is …
```
> checker: fix veb route method param with non ctx name (fix #23105)

- vlib/v/gen/c/str.v
- vlib/v/slow_tests/inout/printing_reference_alias.out
- vlib/v/tests/c_structs/csize.h
- vlib/v/tests/c_structs/return_csize_test.v
This PR fix printing fn call of returning c struct value (fix #23104).
- Fix printing fn call of returning c struct value.
- Add test.
csize.h
```v
struct Size {
int width;
int height;
};
```
```v
#include "@VMODROOT/csize.h"
struct C.Size {
width  int
height int
}
type Size = C.Size
fn get_size() C.Size {
return C.Size{11, 22}
}
fn get_csize() Size {
return Size(C.Size{11, 22})
}
fn main() {
println(get_size())
assert true
println(get_csize())
assert true
}
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU2NzdiYTFlMDYzMmRkMDhlMjZkNTQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.c-Ghf8Iom_rocSryn0Wk9_zP2eDX …
> cgen: fix printing fn call of returning c struct value (fix #23104)

- vlib/v/ast/ast.v
- vlib/v/gen/c/auto_eq_methods.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/ctempvars.v
- vlib/v/gen/c/infix.v
- vlib/v/tests/aliases/alias_fixed_array_compare_test.v
Fix #23071
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU2ZTkyZjFlMDYzMmRkMDhlMjdkN2QiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.3Av6BWghh2qAL1QIooSIDYNHWKAm7KFUYUds2HMGRMY">Huly&reg;: <b>V_0.6-21551</b></a></sub>
> cgen: fix array fixed comparison from fn return

- vlib/v/checker/infix.v
- vlib/v/gen/c/infix.v
- vlib/v/tests/options/option_indexexpr_eq_test.v
Fix #23108
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU2ZDNkZjFlMDYzMmRkMDhlMjdiOTAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.FMtTxVtLg9MMHG-mwIQz615q3GHUBQStJu7L2gcTbhA">Huly&reg;: <b>V_0.6-21550</b></a></sub>
> v: allow option array element comparison `==` and `!=`

- .github/workflows/compile_discordv.sh
I've renamed organization as I don't like the name anymore.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU3N2EyMjFlMDYzMmRkMDhlMjk1Y2UiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.VXEks84WDh-GnV2iI3kJZQ29tFHs8QSDB5lTRovvRYY">Huly&reg;: <b>V_0.6-21554</b></a></sub>
> ci: rename `discord.v`'s org name to `vcv88`

- vlib/v/gen/c/array.v
- vlib/v/tests/builtin_arrays/array_map_to_fixed_array_test.v
This PR fix array map to fixed array (fix #23116).
- Fix array map to fixed array.
- Add test.
```v
module main
type Mat4 = [16]f32
struct GameObject  {
mut:
transform Mat4
children []&GameObject
}
fn main() {
mut v1 := &GameObject{}
eprintln("children: ${v1.children.map(it.transform)}")
assert '${v1.children.map(it.transform)}' == '[]'
}
children: []
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU3YTU1OTFlMDYzMmRkMDhlMjk3ZjAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.l6DWVvqGCRfGM3e18pS2ln5kma1IZW0R9UFxU9jdCoc">Huly&reg;: <b>V_0.6-21555</b></a></sub>
> cgen: fix array map to fixed array (fix #23116)

- vlib/v/gen/c/array.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/sort_fn_def_test.v
Fix #23120
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU4MzEwMDFlMDYzMmRkMDhlMmFmYjEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.6g05kxiz4wDCKtBHMpcfIpXDSEwtWwlRKLk1cbgXm8s">Huly&reg;: <b>V_0.6-21558</b></a></sub>
> cgen: fix sort fn definitions

- vlib/math/big/big_test.v
- vlib/math/big/integer.v
Fix: #23115 .
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU4NGVmMDFlMDYzMmRkMDhlMmI4MTUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.tgAtu8Fzgt-T9QuOtS5SFfbhJJ3VWxHtyEUwWo7vSks">Huly&reg;: <b>V_0.6-21561</b></a></sub>
> math.big: fix `assert big.integer_from_int(1) == big.integer_from_bytes([u8(0), 0, 0, 0, 1])` (fix #23115)

- vlib/math/log.c.v
- vlib/math/log_test.v
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU5NThmODFlMDYzMmRkMDhlMzE0MWMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.aeTsYNUBHaqHS9fpfRwCHgIgNZtXkb9XlXJFZoYmMEo">Huly&reg;: <b>V_0.6-21566</b></a></sub>
> math: use libc wrappers for math.log2/1, math.log10/1, math.log1p/1 and math.log_b/1. Make `assert math.log10(10) == 1.0` pass.

- vlib/v/checker/for.v
- vlib/v/checker/for_in_same_var_err.out
- vlib/v/checker/for_in_same_var_err.vv
- vlib/v/parser/for.v
Fix bug spotted by @Bruno-Vdr
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU5NjNjNDFlMDYzMmRkMDhlMzE3NzMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.NJByJcoKfXeioCYv2d1cMhB3sfkg8ZTTjwsYYRedNFA">Huly&reg;: <b>V_0.6-21567</b></a></sub>
> checker: fix missing check on range expr when high var is same iteration value var

- vlib/v/gen/c/cgen.v
- vlib/v/tests/generic_selector_ptr_test.v
Fix #22974
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU5N2Y5MTFlMDYzMmRkMDhlMzFlZDEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.GxP20X9wYRcXPxdxWunQ_tmkWUkTQaPEs8BO8mESqSc">Huly&reg;: <b>V_0.6-21569</b></a></sub>
> cgen: fix codegen for generic selector expr

- vlib/v/gen/c/assign.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/options/option_diff_alias_arg_test.v
Fix #23086
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU5NmU5ZTFlMDYzMmRkMDhlMzFhNTAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.RPkE-HkV9ExQZ_pM-SJEDx3gTly4bDBFgS0k3UAyoj0">Huly&reg;: <b>V_0.6-21568</b></a></sub>
> cgen: fix different option alias type as fn arg

- vlib/v/ast/ast.v
- vlib/v/checker/checker.v
- vlib/v/checker/for.v
- vlib/v/checker/if.v
- vlib/v/checker/infix.v
- vlib/v/checker/postfix.v
- vlib/v/checker/str.v
- vlib/v/comptime/comptimeinfo.v
- vlib/v/gen/c/array.v
- vlib/v/gen/c/assign.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/dumpexpr.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/for.v
- vlib/v/gen/c/str_intp.v
- Move ct expr marking to checker instead of checking all the time on cgen
- Simplify ct expr checking on cgen.
Hence the code runs faster. :-)
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU5YTYyZDFlMDYzMmRkMDhlMzI1M2EiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.zVoS43mvrfhzDwPh6Kulo-128NUC3eEv0NSrpyt2aLM">Huly&reg;: <b>V_0.6-21571</b></a></sub>
> checker, cgen: cleanup comptime var marking on checker optimizing the way as it is checked on cgen

- vlib/gg/gg.c.v
This PR adds `window_icon` to the gg.Config struct for easier access and use with the `gg.new_context` method.
This allows us to have the option to just pass `window_icon: sapp.IconDesc{}` directly into the `new_context` method without needing to directly make the window with sokol.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU5ZTA2ZTFlMDYzMmRkMDhlMzJhN2MiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.9DytsjoWi6xFaqShZ_oT_au92RanTQoBdbaKmdxft3I">Huly&reg;: <b>V_0.6-21575</b></a></sub>
> gg: add icon to gg.Config for easier access

- vlib/v/gen/c/index.v
- vlib/v/tests/options/option_index_amp_test.v
Fix #23133 (stack-use-after-return bug)
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU5ZTk0ZDFlMDYzMmRkMDhlMzJiNDgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.9E9sPjMgUZJvlCrePdv8k1qPylSZ3c4D773YoDwFGm8">Huly&reg;: <b>V_0.6-21576</b></a></sub>
> cgen: fix codegen for returning option reference from indexexpr

- vlib/v/builder/cbuilder/cbuilder.v
- vlib/v/builder/cbuilder/parallel_cc.v
- vlib/v/gen/c/array.v
- vlib/v/gen/c/auto_eq_methods.v
- vlib/v/gen/c/auto_free_methods.v
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/cheaders.v
- vlib/v/gen/c/consts_and_globals.v
- vlib/v/gen/c/fn.v
- vlib/v/parser/v_parser_test.v
This PR fixes the global codegen on `-parallel-cc`.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVjMTk5OTFlMDYzMmRkMDhlMzc4YjEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.wKMQAiLCSBl4E_anzdTuv0n-gUuTmxaQknBp9S40SO0">Huly&reg;: <b>V_0.6-21585</b></a></sub>
> parallel-cc: make it working on gcc, clang and tcc + restore static on non-parallel builds + cleanups

- vlib/v/scanner/scanner.v
- vlib/v/tests/builtin_strings_and_interpolation/string_interpolation_test.v
Fix #22429
This is really a PR #22453 with improve tests.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVjMDI3YzFlMDYzMmRkMDhlMzczZDciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.H-uIw596IwSYUZNssJPwKAHVlzIyrFmXQ9kJYezN_68">Huly&reg;: <b>V_0.6-21584</b></a></sub>
> scanner: fix string interpolation for float e format

- vlib/v/markused/markused.v
- vlib/v/tests/skip_unused/import_json_only.run.out
- vlib/v/tests/skip_unused/import_json_only.skip_unused.run.out
- vlib/v/tests/skip_unused/import_json_only.vv
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVjYmU1MDFlMDYzMmRkMDhlMzhiYTYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.E7NVF2lCWKjU02PJ7oyreC_NVcM3Q5Us8liEuOk6Cgs">Huly&reg;: <b>V_0.6-21592</b></a></sub>
> markused: fix codegen for empty `import json` file

- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/receiver_state_keep.vv
Fix #23151
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVjYjQ1NjFlMDYzMmRkMDhlMzhiMzAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.4FBN4uvFq0XtsyN0LKxSbIwcKdpervNJHOE_mqCJQtA">Huly&reg;: <b>V_0.6-21590</b></a></sub>
> fmt: fix shared receiver formatting

- vlib/v/fmt/tests/keyword_attr_keep.vv
- vlib/v/fmt/tests/type_attr_keep.vv
- vlib/v/parser/parser.v
Fix #23150
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVjYjkwYjFlMDYzMmRkMDhlMzhiNmQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.DG1fSKB_kX2K5SQqKXO6k5qggTkH1zu6jTPOzVrFHCQ">Huly&reg;: <b>V_0.6-21591</b></a></sub>
> parser: allow `type` as plain attr value

- vlib/builtin/builtin.v
- vlib/v/parser/parser.v
- vlib/v/tests/comptime/comptime_attribute_selector_test.v
This PR fixes a recent bug introduced by my PR override bool attributes identification. And fixes missing .bool kind for comptime .attributes kind.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVkNmFhMTFlMDYzMmRkMDhlMzk4OGYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.dOZjFumQCbmtaxXZXfOmCDhRaCW99tus0Ls28Z-TEAo">Huly&reg;: <b>V_0.6-21596</b></a></sub>
> comptime: fix missing bool AttributeKind.kind

- vlib/v/gen/c/index.v
- vlib/v/tests/left_shift_array_fixed_test.v
Fix #23156
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVkODAwYzFlMDYzMmRkMDhlMzk5NzYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.jzfwwx9C3lYczTuHFP3jo9sXzXoOyz3fM4WiEjfrdXw">Huly&reg;: <b>V_0.6-21597</b></a></sub>
> cgen: fix codegen for array append on indexexpr

- vlib/v/checker/fn.v
- vlib/v/tests/skip_unused/option_int_println.run.out
- vlib/v/tests/skip_unused/option_int_println.skip_unused.run.out
- vlib/v/tests/skip_unused/option_int_println.vv
Fix #23163
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVlMjQwNjFlMDYzMmRkMDhlM2FhODQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0._T4auWI6SzRlZB86mbrW2MphFqilLcj6kinNiLYEBFk">Huly&reg;: <b>V_0.6-21604</b></a></sub>
> markused: fix short program printing option

- vlib/v/gen/c/cgen.v
- vlib/v/tests/alias_cast_to_fixed_array_test.v
Fix #23164
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVlMjg3MjFlMDYzMmRkMDhlM2FhZTEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.JFMwLBqzPkJ2x_D-RGdIZtabK7Grj3NUXV97eiVOmlg">Huly&reg;: <b>V_0.6-21605</b></a></sub>
> cgen: fix fixed array option cast with `none`

- vlib/v/gen/c/fn.v
- vlib/v/tests/selector_call_with_reserved_c_name_test.v
Fix #23170
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVmM2QxNWYxNDRmNTg1YWU0ZDY5OGEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.F_WmKus1wn219oxgUlGYgogrMN8vsM56sIw_rb3BpkE">Huly&reg;: <b>V_0.6-21612</b></a></sub>
> cgen: fix selector call with reserved c name

- cmd/tools/vast/vast.v
- vlib/v/ast/ast.v
- vlib/v/checker/containers.v
- vlib/v/fmt/fmt.v
- vlib/v/gen/c/array.v
- vlib/v/parser/containers.v
- vlib/v/tests/array_fixed_none_init_test.v
Complement fix for #23164
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVmNDZhNGYxNDRmNTg1YWU0ZDY5YjkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.ALUSJcKuZxmjXkqSfUEAmqPiaqYl9_rwkNJibg3k19E">Huly&reg;: <b>V_0.6-21613</b></a></sub>
> parser,checker,cgen,fmt: fix array fixed option initialization (`none`)

- vlib/v/checker/checker.v
- vlib/v/checker/tests/cast_to_concrete_mut_err.vv
- vlib/v/checker/tests/option_selector_fn_unwrap_err.out
- vlib/v/checker/tests/option_selector_fn_unwrap_err.vv
- vlib/v/gen/c/cgen.v
- vlib/v/tests/options/option_ptr_unwrap_test.v
- vlib/v/tests/options/option_selector_fn_none_test.v
Fix missing selector checker for:
```v
fn callback(foo &Foo) bool {
return foo.func? == callback
}
```
Return type was not required to be `?bool` in this case.
Beside this it was generating wrong none return code:
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzYwMjNlYmYxNDRmNTg1YWU0ZDg4NzMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.zw-lMyxHXM46hcys-XuhO1VnN2D0sLvUcxtjWqoTUpc">Huly&reg;: <b>V_0.6-21620</b></a></sub>
> checker,cgen: fix missing validation for selector unwrapping + fix default `return none` for unwrapping

- .github/workflows/linux_ci.yml
Extra blank line was failing `prettier` check.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzYwYzRlM2YxNDRmNTg1YWU0ZGE4OTMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.KhpAQbBfj7aWa2jFd6Jf1ffakl0wfewiOfwueSoEdz8">Huly&reg;: <b>V_0.6-21624</b></a></sub>
> ci: remove extra EOL from linux_ci.yml

- vlib/v/ast/ast.v
- vlib/v/checker/fn.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/options/option_method_selector_test.v
Make works:
```v
struct Foo {
mut:
func ?fn (voidptr) ?bool = unsafe { nil }
}
fn callback(foo &Foo) ?bool {
return foo.func? == callback
}
t := Foo{
func: callback
}
assert t.func? == callback
if t.func != none {
assert t.func(&t)
} else {
assert false
}
}
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzYwMWEwZGYxNDRmNTg1YWU0ZDg1NWMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.RdjTIOlzQoGbLltZtzsF3jZC49AGek8GkTHNEkpkExI">Huly&reg;: <b>V_0.6-21619</b></a></sub>
> cgen, checker: fix option unwrapping and call from option struct field

- vlib/v/gen/c/assign.v
- vlib/v/tests/assign/assign_option_of_fixed_array_test.v
This PR fix assign optional aliases of fixed array (fix #23185).
- Fix assign optional aliases of fixed array.
- Add test.
```v
type Addr = [4]u8
fn main() {
mut addr := ?Addr(none)
addr = Addr([u8(1), 2, 3, 4]!)
println(addr)
assert '${addr}' == 'Option(Addr([1, 2, 3, 4]))'
}
Option(Addr([1, 2, 3, 4]))
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzYwZWJhYmYxNDRmNTg1YWU0ZGFmMmYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.vOUcabZaFlGthgllihnOowINlpNAmBiQzyOfrozCDwU">Huly&reg;: <b>V_0.6-21625</b></a></sub>
> cgen: fix assign optional aliases of fixed array (fix #23185)

- vlib/v/checker/assign.v
- vlib/v/checker/tests/globals/global_var_redeclare.out
- vlib/v/checker/tests/globals/global_var_redeclare.vv
Fix #22970
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVkYjU5MjFlMDYzMmRkMDhlMzlkNzciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.sVVxeRI_UKSUrC0NhtqT0fuRPCPIimIzsJiv5VGMbzM">Huly&reg;: <b>V_0.6-21599</b></a></sub>
> checker: make an notice global variable redeclaration

- .github/workflows/c2v_ci.yml
- .github/workflows/download_full_toml_test_suites.sh
- .github/workflows/gg_regressions_ci.yml
- .github/workflows/prebuilt.yml
- .github/workflows/vup_works.yml
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzYxYWIxYmYxNDRmNTg1YWU0ZGNkNDkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.ij74DNCWFELV5t9IFY4PnkjzLOZuusz5mCtR11maHb4">Huly&reg;: <b>V_0.6-21633</b></a></sub>
> ci: make the CI more robust, by retrying commands and `v download` instead of wget

- vlib/v/checker/struct.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/for.v
- vlib/v/gen/c/index.v
- vlib/v/markused/walker.v
- Removed repetitive .has_flag() calls on fns
- Inline markused.walker or_block()
- Spread .has_option_or_result() instead of double check .has_flag(.option) + .has_flag(.result) calls.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzYxNzU2MGYxNDRmNTg1YWU0ZGM2MjkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.JKl35d2-H77ELwqaGU2ReqATb2xSX_cDlk3rFTuAsRE">Huly&reg;: <b>V_0.6-21628</b></a></sub>
> cgen,checker: minor optimizations

- .github/workflows/sanitized_ci.yml
- vlib/v/gen/c/json.v
Fix leftover memleak on json lib.
To test use: 
`v -cc clang-17 -cflags -fsanitize=address,pointer-compare,pointer-subtract test vlib/json/tests/json_sumtype_test.v`
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzYxZDcwM2YxNDRmNTg1YWU0ZGQyYmUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.aWIKp7n_ob6loUUajFtncqj3thtgKLgqKqYvmeQSUxA">Huly&reg;: <b>V_0.6-21634</b></a></sub>
> json: fix memleak on sumtype decoding

- vlib/v/gen/c/assign.v
- vlib/v/gen/c/struct.v
- vlib/v/tests/structs/struct_field_init_with_fixed_array_opt_test.v
This PR fix struct field init with optional fixed array (fix #23195, fix #23193).
- Fix struct field init with optional fixed array.
- Add test.
```v
type Arr = [4]u8
struct Foo {
bar int
baz ?Arr
}
fn main() {
f1 := Foo{
bar: 1
baz: Arr([u8(5), 4, 3, 2]!)
}
println(f1)
assert f1.baz as Arr == [u8(5), 4, 3, 2]!
f2 := Foo{
bar: 1
baz: ?Arr(none)
}
println(f2)
assert f2.bar == 1
assert f2.baz == none
arr := Arr([u8(5), 4, 3, 2]!)
f3 := Foo{
bar: 1
baz: arr
}
println(f3)
assert f3.bar == 1
assert f3.baz as Arr == [u8(5), 4, 3, 2]!
}
Foo{
bar: 1
baz: Option(    Arr([5, 4, 3, 2]))
}
Foo{
bar: 1
baz: Option(none)
}
Foo{
bar: 1
baz: Option(    Arr([5, 4, 3, 2]))
}
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJI …
> cgen: fix struct field init with optional fixed array (fix #23195)

- vlib/v/gen/c/array.v
- vlib/v/gen/c/assign.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/struct.v
- vlib/v/tests/structs/struct_field_init_with_fixed_array_opt_test.v
This PR fix all the cases of struct field init with optional fixed array (related #23199).
- Fix all the cases of struct field init with optional fixed array.
- Add test.
```v
type Arr = [4]u8
struct Foo {
bar int
baz ?Arr
}
fn main() {
foo1 := Foo{
bar: 1
baz: Arr([u8(5), 4, 3, 2]!)
}
println(foo1)
assert foo1.baz as Arr == [u8(5), 4, 3, 2]!
foo11 := Foo{
bar: 1
baz: ?Arr([u8(5), 4, 3, 2]!)
}
println(foo11)
assert foo11.baz as Arr == [u8(5), 4, 3, 2]!
foo12 := Foo{
bar: 1
baz: [u8(5), 4, 3, 2]!
}
println(foo12)
assert foo12.baz as Arr == [u8(5), 4, 3, 2]!
foo2 := Foo{
bar: 1
baz: ?Arr(none)
}
println(foo2)
assert foo2.bar == 1
assert foo2.baz == none
foo21 := Foo{
bar: 1
baz: none
}
println(foo21)
assert foo21.bar == 1
assert foo21.baz == none
arr1 := Arr([u8(5), 4, 3, 2]!)
foo3 := Foo{ …
```
> cgen: fix all the cases of struct field init with optional fixed array (related #23199)

- vlib/x/ttf/common.v
- vlib/x/ttf/render_bmp.v
- vlib/x/ttf/render_sokol_cpu.v
- vlib/x/ttf/text_block.v
- vlib/x/ttf/ttf.v
Part of #7047
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzYzZWNkNmYxNDRmNTg1YWU0ZTM3MmIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.UCFF3C3nC_yLMlyi8fobi120GmU5KJFn4TgnDWzeYec">Huly&reg;: <b>V_0.6-21642</b></a></sub>
> vlib: add missing doc strings to `x.ttf` module

- vlib/v/help/build/build-c.txt
- vlib/v/help/default.txt
- vlib/v/pref/pref.v
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY0NjlmOWYxNDRmNTg1YWU0ZTRkYTAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.ZTc06I_H11BsPSVtI8-zRaQRgFr5Foul_-CrxqZYTQ4">Huly&reg;: <b>V_0.6-21644</b></a></sub>
> v.pref: support `-debug` and `-cdebug`, as more explicit alternative names for `-g` and `-cg`

- cmd/tools/vast/vast.v
- vlib/fontstash/fontstash.c.v
- vlib/sokol/audio/audio.c.v
- vlib/sokol/c/declaration.c.v
- vlib/sokol/f/f.v
- vlib/v/ast/ast.v
- vlib/v/fmt/fmt.v
- vlib/v/fmt/tests/hashstmt_keep.vv
- vlib/v/parser/comptime.v
- vlib/v/parser/fn.v
Related: https://github.com/vlang/v/issues/23209
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY0ODJmYWYxNDRmNTg1YWU0ZTViY2MiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.XLORvVaSI1YLTj_CIaZz9kveNmX8VTvixuV6jY9WzVQ">Huly&reg;: <b>V_0.6-21646</b></a></sub>
> v,ast,fmt,parser: support `@[tag]` for hash statements, like `#define` and `#flag`

- vlib/v/builder/cbuilder/cbuilder.v
- vlib/v/builder/cbuilder/parallel_cc.v
Related: https://github.com/vlang/v/issues/23209
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY0ODk0OWYxNDRmNTg1YWU0ZTYwOWQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.inJE0K2SgtiFsxbgWga_2AB91uKOdG01H46qBjXCyOw">Huly&reg;: <b>V_0.6-21647</b></a></sub>
> v.builder: fail v compilation, if linking or compiling during `-parallel-cc` fails

- vlib/v/checker/assign.v
- vlib/v/checker/checker.v
- vlib/v/comptime/comptimeinfo.v
- vlib/v/tests/generics/generic_selector_indexexpr_test.v
- vlib/x/json2/decoder2/decode_sumtype.v
Fix #23202
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY0OGEyN2YxNDRmNTg1YWU0ZTYwYmYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.mCsWYk4WtmEma6uG7-ArknVYh_XARFH8JRmTrf0lIfM">Huly&reg;: <b>V_0.6-21648</b></a></sub>
> checker: fix assign checker when rechecking for another concrete type

- vlib/v/builder/cbuilder/cbuilder.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/cmain.v
- vlib/v/parser/v_parser_test.v
```
#0 22:33:59 ^ cgen_avoid_making_a_string_from_the_final_builder /v/oo>xtime ./vold -o x.c cmd/v
CPU: 2.56s      Real: 2.52s     Elapsed: 0:02.52        RAM: 428828KB   ./vold -o x.c cmd/v
#0 22:38:55 ^ cgen_avoid_making_a_string_from_the_final_builder /v/oo>xtime ./vnew -o x.c cmd/v
CPU: 2.54s      Real: 2.24s     Elapsed: 0:02.24        RAM: 422624KB   ./vnew -o x.c cmd/v
#0 22:39:01 ^ cgen_avoid_making_a_string_from_the_final_builder /v/oo>
```
The difference for V itself is ~6MB less, due to the avoidance of the final .str() creation.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY1ZDRiZGYxNDRmNTg1YWU0ZWEzMDQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGF …
> cgen: reduce RAM usage, by avoiding a .str() call, for the final string builder, containing the final C program, used to write it to a file

- vlib/v/gen/c/profile.v
Fix issue #19130
`QueryPerformanceCounter()` only a counter value, it need to divide `QueryPerformanceFrequency()` to get real time.
As `time.vpc_now()` return only a counter value:
```v
@[inline]
fn vpc_now() u64 {
tm := u64(0)
C.QueryPerformanceCounter(voidptr(&tm))
return tm
}
```
https://learn.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY2MDBlMGYxNDRmNTg1YWU0ZWE3YTYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.TAnCyBuaaKqlaEIArhch8pBwz4dtIBEZNOAL22wFtnA">Huly&reg;: <b>V_0.6-21661</b></a></sub>
> cgen: fix profile time on windows 

- vlib/crypto/bcrypt/bcrypt.v
- vlib/crypto/bcrypt/bcrypt_test.v
Fix issue #18923
Some discussion here: https://security.stackexchange.com/questions/39849/does-bcrypt-have-a-maximum-password-length
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY2OGNhOWYxNDRmNTg1YWU0ZWFjOGEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.jLXAtyW4Oxy14ccr3YJKyHqsUbipcbw8bn9KrGulvWM">Huly&reg;: <b>V_0.6-21663</b></a></sub>
> crypt.bcrypt: limit max password length to 72 bytes

- vlib/v/checker/containers.v
- vlib/v/tests/builtin_arrays/array_init_i32_test.v
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY3MTdhZWYxNDRmNTg1YWU0ZWI4NjUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.BtN45L-C0rwBnXcgRMI8dn5Y3E0RExmAlh1sMXYBbdM">Huly&reg;: <b>V_0.6-21666</b></a></sub>
> checker: fix `index` validating for []i32

- doc/docs.md
- vlib/json/tests/json_test.v
- vlib/v/gen/c/json.v
By default, allow parsing a json with nulls, validate only the null if in the field has the attribute `@[required]`.
Resolves: #23207
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY1MzMwNGYxNDRmNTg1YWU0ZTczNTIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.C9k24rXfCqVsREHelGxbV32S1jcciM4G3q259qeHN_s">Huly&reg;: <b>V_0.6-21653</b></a></sub>
> json: use `@[required]` to disallow parsing nulls

- vlib/v/checker/check_types.v
- vlib/v/checker/fn.v
- vlib/v/tests/generics/generic_method_lambda_arg_test.v
Fix #23221
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY3NDc5N2YxNDRmNTg1YWU0ZWJhMzciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.cSbZePVqoJRU5hFTLi1bO2OeXmflGh7iqcA_R_HxzFk">Huly&reg;: <b>V_0.6-21668</b></a></sub>
> cgen: fix lambda inferring generic type on method call

- vlib/v/ast/types.v
- vlib/v/checker/fn.v
- vlib/v/parser/struct.v
- vlib/v/tests/interfaces/interface_arr_auto_str_test.v
Fix #23006
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY3NzNiZmYxNDRmNTg1YWU0ZWJiZGIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.X0jFjdb01RWnijiF1Y5vc0AiK323HtoU53K5k_mtAU8">Huly&reg;: <b>V_0.6-21672</b></a></sub>
> v: fix identification of abstract vs real interface methods

- vlib/v/checker/infix.v
- vlib/v/tests/concurrency/chan_push_enum_test.v
This PR fix pushing enum value to channel (fix #23244).
- Fix pushing enum value to channel.
- Add test.
```v
enum FooBar {
foo
bar
}
fn test_chan_push_enum() {
ch := chan FooBar{cap: 10}
ch <- .foo
println(<-ch)
assert true
}
foo
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY5MWEyY2YxNDRmNTg1YWU0ZWQ5NDMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.dqk-r-LQGjdesgJxpt9H1pfZkznjhZSVDMJ4bomfafc">Huly&reg;: <b>V_0.6-21681</b></a></sub>
> checker: fix pushing enum value to channel (fix #23244)

- vlib/db/sqlite/sqlite.c.v
New function exec_map returns an array of maps from query
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY4ZTdmNmYxNDRmNTg1YWU0ZWQzODAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.at5IgUm3JHPMaGqTvoYHBZIAsV0rmdV0E4l4nr60wIw">Huly&reg;: <b>V_0.6-21680</b></a></sub>
> db.sqlite: added exec_map function 

- vlib/math/stats/stats.v
- vlib/math/stats/stats_test.v
Fix issue #23245
1. add support for int/i64/.. arrays;
2. add tests for `minmax`, `min_index`,`max_index`,`minmax_index`,`covariance`,`lag1_autocorrelation`,`kurtosis`,`skew`,`quantile`
3. use math.alike to compare f32/f64.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY5Njc2NGYxNDRmNTg1YWU0ZjYzOGEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.tD08tfV76gP9J0i0LTXlmrcT4OalblFgyIfUtfv8f4M">Huly&reg;: <b>V_0.6-21683</b></a></sub>
> math.stats: support int/i64 arrays, fix tests

- vlib/v/gen/c/fn.v
- vlib/v/tests/concurrency/chan_try_push_literal_test.v
This PR fix try_push string literal to channel  (fix #23242).
- Fix try_push string literal to channel.
- Add test.
```v
fn main() {
foo := chan string{}
foo.try_push('some string')
assert true
}
PS D:\Test\v\tt1> v run .  
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZhN2I3N2YxNDRmNTg1YWU0ZmZmOWQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.sW_kbs8wcryM0crDD4d51Tgd4P0Kse7fgoXD1Arkzd8">Huly&reg;: <b>V_0.6-21693</b></a></sub>
> cgen: fix try_push string literal to channel  (fix #23242)

- vlib/v/gen/c/cgen.v
- vlib/v/tests/aliases/alias_array_fixed_sumtype_test.v
Fix #23009
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY5NGM5NWYxNDRmNTg1YWU0ZjM4OTMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.lYl_mAX_xGzJXOt6y5uKNOIO5ipxgwr11WtCZd808Bo">Huly&reg;: <b>V_0.6-21682</b></a></sub>
> cgen: fix codegen for casting aliased fixed array to sumtype array

- vlib/v/gen/c/spawn_and_go.v
- vlib/v/tests/chan_same_fn_name_test.v
Fix #21746
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZiNGQ2M2YxNDRmNTg1YWU1MDFhM2MiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.oyEkm765TzTOyUACuQzqaBCwUw7D_a0OevnAJBcseZ0">Huly&reg;: <b>V_0.6-21695</b></a></sub>
> cgen: fix thread struct name for same fn var name on different scope

- vlib/json/tests/json_decode_option_alias_test.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/json.v
Fix #23262
Makes `g.type_default()` more compatible with `g.expr(StructInit{})`.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZiZWRhNWYxNDRmNTg1YWU1MDQ2NTkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.L-MZUny8nit4q_e-4cm_hgvFLELMu1430p9Iu2iLPEs">Huly&reg;: <b>V_0.6-21697</b></a></sub>
> cgen,json: fix default initialization

- vlib/crypto/README.md
Added JWT Payload Decoding Examples.
```
$ v run .
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
auth_verify(secret, token): true
decode_payload(token): JwtPayload{
sub: '1234567890'
name: 'John Doe'
iat: 1516239022
}
Elapsed time: 102 uS
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZkMmQ2YWYxNDRmNTg1YWU1MGU1MzciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.mr9yIVCNEY2nIElx7gP1_OrG6sZBePYEKfHFcv7ml5A">Huly&reg;: <b>V_0.6-21709</b></a></sub>
> crypto: add JWT Payload Decoding sample

- vlib/net/smtp/smtp.v
Fix #23289
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZlZWFkOWYxNDRmNTg1YWU1MTJhNGEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.nZRxszcSWD2qC5x-N3aMt3uqfvJdmp8UAmQWDDJIx4k">Huly&reg;: <b>V_0.6-21722</b></a></sub>
> smtp: fix crash when reconnecting with encrypted=true

- vlib/builtin/array.v
- vlib/builtin/array_d_gcboehm_opt.v
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZmZWQwMmYxNDRmNTg1YWU1MTM2YjIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.WcCEKQv7Pjow_4b5Hnlk4ZOdWzkdJjFuQBjFvZy5DBw">Huly&reg;: <b>V_0.6-21726</b></a></sub>
> builtin: add runtime checks for `[]u8{len: negative}`

- vlib/log/common.v
- vlib/log/log.v
- vlib/v/slow_tests/inout/dump_expression.out
- vlib/v/slow_tests/inout/dump_expression.vv
This PR:
- Adds `set_output_stream()` fn to `log.Log` struct which allows setting `io.Writer` as log output. It makes possible send logs to arbitrary targets such as sockets. Use cases: write logs to system journal e.g. syslog, send logs to remote server over UDP.
- Makes STDERR the default output stream (be STDOUT before). Sending logs to STOUT is not generally used in logging libraries e.g. Go, Python stdlibs etc.
- Edit test, since `log.Log` now have `output_stream` field with file address which can change at runtime and therefore cannot be tested in "inout" tests.
Example:
```v
import log
import os
import net
fn main() {
mut logger := log.Log{}
logger.set_level(.info)
log.set_logger(logger)
logger.info('hello stderr')
logger.set_output_stream(os.stdout())
logger.info('hello stdout') …
```
> log: set stderr as default log output, add .set_output_stream()

- vlib/net/http/cookie.v
Fixes #23297
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcwM2U5ZmYxNDRmNTg1YWU1MTNhMTciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.fvhHU20pBrvo7okaZQsENP3IY-_rP4yQuzvzd6GumcQ">Huly&reg;: <b>V_0.6-21732</b></a></sub>
> net.http.cookie: handle value with `=` better

- vlib/v/checker/assign.v
- vlib/v/checker/checker.v
- vlib/v/checker/comptime.v
- vlib/v/checker/fn.v
- vlib/v/checker/for.v
- vlib/v/checker/if.v
- vlib/v/checker/infix.v
- vlib/v/gen/c/assign.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/fn.v
- vlib/v/gen/c/for.v
- vlib/v/gen/c/infix.v
- vlib/v/type_resolver/comptime_resolver.v
- vlib/v/type_resolver/type_resolver.v
Cleanup
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcxNTM1ZWYxNDRmNTg1YWU1MTQ1N2IiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.YaBqlvVUfzpQImtb0H4EhKXog0TZIr3IjGLtLGbYRzQ">Huly&reg;: <b>V_0.6-21737</b></a></sub>
> v: cleanup type resolver

- doc/docs.md
Fixing verbiage removing potential confusion of statement context in the Hello World section of documentation.
Documentation uses `one file programs`, which can cause confusion and cause the user to think it can only be utilized in one file/program.
Changing to `single file programs` to prevent any confusion when it is being read.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcxYmQ5Y2YxNDRmNTg1YWU1MTUxZjciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.kauIFzq3xVHuAGsbCjYi8G61hzxGbs_hftBzGkLXDT8">Huly&reg;: <b>V_0.6-21742</b></a></sub>
> Verbiage: Fix Verbiage Context in Hello World

- vlib/v/checker/infix.v
- vlib/v/tests/sumtypes/sumtype_generic_checking_test.v
Fix #23282
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcxYjdjNWYxNDRmNTg1YWU1MTUwZDIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.xiEH_XqN96QlV6JV4ZnnJFEPlaDw5Rw1fcNbkbW0Gqo">Huly&reg;: <b>V_0.6-21741</b></a></sub>
> checker: fix sumtype generic checking

- vlib/v/checker/assign.v
- vlib/v/checker/checker.v
- vlib/v/checker/containers.v
- vlib/v/checker/fn.v
- vlib/v/checker/struct.v
- vlib/v/checker/tests/dump_char.out
- vlib/v/checker/tests/dump_char.vv
- vlib/v/checker/tests/struct_type_cast_err.out
- vlib/v/checker/tests/struct_type_cast_err.vv
- vlib/v/checker/tests/top_level_fn_builtin_decl_err.out
- vlib/v/checker/tests/top_level_fn_builtin_decl_err.vv
- vlib/v/checker/tests/use_byte_instead_of_u8_err.out
- vlib/v/checker/tests/use_byte_instead_of_u8_err.vv
- vlib/v/fmt/tests/import_selective_keep.vv
- vlib/v/fmt/tests/pointer_casts_keep.vv
This PR fix cannot use "byte" as const name (#23236)
- Remove `byte` from reserved keywords.
- Make use of `byte` error. Use `u8` instead.
- Add checker test.
use_byte_insead_of_u8_err.vv:
```v
type Byte = byte
fn foo(_ byte) {}
fn main() {
_ := byte(0)
_ := fn(_ byte) {}
}
```
use_byte_insead_of_u8_err.out:
```
vlib/v/checker/tests/use_byte_instead_of_u8_err.vv:1:13: error: type `byte` is an alias, use the original alias type `u8` instead
1 | type Byte = byte
2 |
3 | fn foo(_ byte) {}
vlib/v/checker/tests/use_byte_instead_of_u8_err.vv:3:10: error: byte is deprecated, use u8 instead
1 | type Byte = byte
2 |
3 | fn foo(_ byte) {}
|          ~~~~
4 |
vlib/v/checker/tests/use_byte_instead_of_u8_err.vv:6:7: error: byte is deprecated, use u8 instead
4 |
5 | …
```
> checker: make `byte(0)` an error; use `u8(0)` (fix #23236)

- vlib/v/checker/fn.v
- vlib/v/checker/tests/array_generic_methods_err.out
- vlib/v/checker/tests/array_generic_methods_err.vv
Fix #23283
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcxNDZkNGYxNDRmNTg1YWU1MTQ0ZTUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.EZYh_gf-EdlsoY1zLt32X51ptngpmtKvE9QxA10XGko">Huly&reg;: <b>V_0.6-21736</b></a></sub>
> checker: fix array method error message with generic type

- vlib/json/tests/json_is_null_attr_test.v
- vlib/v/gen/c/json.v
Implementing feature request.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcyYmM3NmYxNDRmNTg1YWU1MTZmMmMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.IuqTMFe-F_ZEWbZgfl9dlS5Z2iuZ5myuO48HUP_kkqA">Huly&reg;: <b>V_0.6-21751</b></a></sub>
> json: support `@[json_null]` tag to enforce `null`, when encoding `none` option values

- vlib/json/tests/json_encode_default_option_none_test.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/json.v
Fix #23318
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcyZDcyMWYxNDRmNTg1YWU1MTcxY2YiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.Sjgbkgei8ZEgXo03zz2Onn1IojO5CJVK_5CJjmtiMY8">Huly&reg;: <b>V_0.6-21752</b></a></sub>
> cgen: fix type_default for option type when the default expr is `none`

- vlib/v/ast/ast.v
- vlib/v/ast/comptime_const_values.v
Improve compiler performance a bit, by reducing the amount of small allocations, for creating `ComptTimeConstValue(EmptyExpr(0))` for the default field values of the AST nodes.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzczMGUxYWYxNDRmNTg1YWU1MTk5NTMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.XXeFx25-_bL8OcieiJ5Hdx-d_-zUfQcgGHhCiLoTLgE">Huly&reg;: <b>V_0.6-21756</b></a></sub>
> ast: reduce allocations in empty_comptime_const_expr

- vlib/v/checker/fn.v
- vlib/v/tests/generics/generic_fn_array_infer_var_test.v
Fix #23315
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcyZWMzM2YxNDRmNTg1YWU1MThhMDMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.8bawvd-akhDZT87qOeY05vifQTENOkJXfAb0pR4zdCw">Huly&reg;: <b>V_0.6-21754</b></a></sub>
> checker: fix generic var inferring to be passed to `[]T`

- vlib/v/checker/infix.v
Minor optimize
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc0NzYwMGYxNDRmNTg1YWU1MWNmYjMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.8qCdec9Tx6kDxwYOmXZgzUZ-vPPZjq4wgG-lNGYnPvQ">Huly&reg;: <b>V_0.6-21758</b></a></sub>
> checker: cleanup infix - reduce `as` casting

- vlib/v/checker/fn.v
- vlib/x/json2/tests/decode_map_of_map_test.v
Fix #23329
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc1MzVlZmYxNDRmNTg1YWU1MjAxMmUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.nRewa03mH6iz6opilCyJs-7i5ZYQ6-VsxSrzHGrHVK0">Huly&reg;: <b>V_0.6-21763</b></a></sub>
> checker: fix structinit validation on nested generic Map[K]V

- vlib/v/gen/c/cgen.v
- vlib/v/tests/structs/default_expr_array_init_test.v
Spoted when building vhamll project.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc1NTYwN2YxNDRmNTg1YWU1MjAzOTkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.6YuDFqgB89hMFKCeg_J1Ns27KEFhwBI9rf5T0bPOPjQ">Huly&reg;: <b>V_0.6-21765</b></a></sub>
> cgen: fix type_default for array init >= 8 items

- cmd/tools/vbug.v
- **Modified code in order to take any additional compiler flags.**
- **Replace compiler_flag_to_single_str function by a call to join(' ') on compiler_args string array.**
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc1NTY0MmYxNDRmNTg1YWU1MjAzYjAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.bwwNPtstXO9XTdDXPSFiNZi3ziJpEvEzIg57gb5iUas">Huly&reg;: <b>V_0.6-21766</b></a></sub>
> tools: allow passing more V compiler arguments to `v bug file.v`

- vlib/v/parser/parser.v
Hi!
Updated the broken link in [parser.v](https://github.com/vlang/v/blob/8a681bae6d1d8f31c0657e016fb54efdecbded22/vlib/v/parser/parser.v#L1306):
https://github.com/jameslzhu/riscv-card/releases/download/latest/riscv-card.pdf
This change aligns with the update made in [commit 6628be3](https://github.com/jameslzhu/riscv-card/commit/6628be3cca53b590896ae7a72a9d9446eee7bfd1).
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc2N2VlZGYxNDRmNTg1YWU1MjI1NmQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.c8CO92lI375ga8kdsIXMA7rwNlQx9-UWqvHYWkgjXt4">Huly&reg;: <b>V_0.6-21774</b></a></sub>
> v.parser: fix broken link to riscv-card.pdf

- vlib/v/type_resolver/generic_resolver.v
Cleanup
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc2NzMyMWYxNDRmNTg1YWU1MjIxZTgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.ht78BJDepDER_HyC0RWHCZWXQsbdw_fx1Je2JH0_JYs">Huly&reg;: <b>V_0.6-21773</b></a></sub>
> type_resolver: cleanup get_generic_array_element_type

- .github/workflows/gg_regressions_ci.yml
- .github/workflows/other_ci.yml
- .github/workflows/sanitized_ci.yml
- .github/workflows/v_apps_and_modules_compile_ci.yml
- .github/workflows/vsl_and_vtl_compile_ci.yml
- README.md
- ci/linux_ci.vsh
- examples/tetris/README.md
- vlib/gg/gg.c.v
Fixes #23146 by adding support for Linux users using X11.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc0NGM4ZGYxNDRmNTg1YWU1MWNlOWEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.nsEUjcC-vRZwG3V-Njl7nawqDrPsAP6Uzr71s55SKo8">Huly&reg;: <b>V_0.6-21757</b></a></sub>
> gg: add linux support for `fn screen_size() Size` fix (#23146)

- vlib/v/gen/c/struct.v
- vlib/v/tests/struct_with_alias_embed_test.v
Fix #23347
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc3Y2RjZWYxNDRmNTg1YWU1MjU2NjkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.lEVKoNoZO1vQm2DWzMA45Y64ucEXefFc74efKyhUAWg">Huly&reg;: <b>V_0.6-21784</b></a></sub>
> cgen: fix codegen for alias struct embed

- examples/hot_reload/message.v
- vlib/builtin/builtin.c.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/consts_and_globals.v
- vlib/v/gen/c/live.v
- vlib/v/live/common.c.v
- vlib/v/live/executable/reloader.c.v
- vlib/v/live/live_test.v
- vlib/v/live/sharedlib/live_sharedlib.v
Fix issue #23214
Force generate `_vinit_caller`, `_vcleanup_caller` , these are needed under Windows, because dl.open() / dl.close() will call them when loading/unloading shared dll.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc3NDY4NWYxNDRmNTg1YWU1MjQxNDciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.FiYiE_5Q5UQQVdy-ADsvLoIk8lh1_DD0d8SmsYJTsT4">Huly&reg;: <b>V_0.6-21781</b></a></sub>
> cgen: fix windows hot reload

- vlib/json/tests/json_decode_struct_default_test.v
- vlib/v/gen/c/json.v
- vlib/x/json2/decoder.v
Fix
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc3Zjc2ZGYxNDRmNTg1YWU1MjVlMTAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.8Dx4ssMCkhWzMVIkmc5wSA89T9kzYnqhlVHDM-mM9b0">Huly&reg;: <b>V_0.6-21786</b></a></sub>
> json: fix default struct field initialization with long array

- vlib/v/ast/ast.v
- vlib/v/checker/infix.v
- vlib/v/gen/c/infix.v
- vlib/v/type_resolver/comptime_resolver.v
- vlib/v/type_resolver/type_resolver.v
Cleanup
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc4OTYxZmYxNDRmNTg1YWU1MjZiNzYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.W-vFaEYJps8Cphwr8yGoHynG0z_8RQUxd7vZBuQRL2w">Huly&reg;: <b>V_0.6-21793</b></a></sub>
> v.type_resolver: optimize infix ct checking

- vlib/v/ast/ast.v
- vlib/v/ast/types.v
- vlib/v/builder/builder.v
- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/tests/aliases/alias_const_array_fixed_test.v
Fix #23356
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc4MzI0N2YxNDRmNTg1YWU1MjY0ODkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.SdNcI_X3ARrqx5lCI46WabCTU0dSisMlfNmO5JIh33Q">Huly&reg;: <b>V_0.6-21788</b></a></sub>
> checker: fix alias to fixed array w/ size defined by constant

- vlib/v/checker/checker.v
- vlib/v/checker/tests/option_as_cast_err.out
- vlib/v/checker/tests/option_as_cast_err.vv
- vlib/v/tests/options/option_concatexpr_test.v
- vlib/v/tests/options/option_unwrap_as_cast_test.v
Fix #23349
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc4NGY3ZWYxNDRmNTg1YWU1MjY3MGEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.QKmzY0zea19BgkOCSPTtiGI_VY1aElQNtHdmBkbJDZo">Huly&reg;: <b>V_0.6-21789</b></a></sub>
> checker: fix missing option variable checking when casting using `as` operator

- vlib/v/gen/c/cgen.v
For `gettid()` declaration (and other GNU-specific bits).
Fixes #23351.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc4YTMxOWYxNDRmNTg1YWU1MjZjYjkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.YSwkyXv9mScCDLP38t0WfbitH3AUm5g307R4MTyN_vk">Huly&reg;: <b>V_0.6-21795</b></a></sub>
> cgen: define _GNU_SOURCE on Linux

- vlib/v/help/build/build.txt
- vlib/v/help/default.txt
Some formatting to the `v help` message
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc4OWJiMGYxNDRmNTg1YWU1MjZiZWMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.eQebAsmsqG58m55X6wm02wdEYsuPZHuCoJVeuBk0Wzg">Huly&reg;: <b>V_0.6-21794</b></a></sub>
> v help message formatting

- cmd/tools/vdoctor.v
This PR will 
1. create a nice looking vdoctor output;
2. fix windows ANSI->UTF-8 text encoding;
3. fix windows get CPU name;
4. add `tcc -v` to output;
5. add `gcc`,`clang`,`glibc` version detect;
6. add `msvc` version detect under Windows;
7. remove path contains non-ANSI character/spaces warning;
8. add free memory / total memory;
9. remove `emcc` detection;
New `v doctor` will output:
```sh
~/v/测试/dir contains spaces$ v doctor
|V full version      |V 0.4.9 3ed799e
|:-------------------|:-------------------
|OS                  |linux, Ubuntu 24.04.1 LTS
|Processor           |8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
|Memory              |2.97GB/15.51GB
|                    |
|V executable        |/media/HD/github/kbkpbot/v/v
|V last modified time|2025-01-03 …
```
> vdoctor: fix format, windows, tcc

- cmd/tools/vdoctor.v
Fix
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc5MmJkYWYxNDRmNTg1YWU1MjdhZjIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.9dDgpJGyiXXDM-85MRMNFgNNvDHp1xkxOqp_VAjL7D0">Huly&reg;: <b>V_0.6-21799</b></a></sub>
> fix windows CI for `v -W build-tools`

- .github/workflows/tools_ci.yml
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc5MzczMWYxNDRmNTg1YWU1MjdjMDAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.eoStn-ocUl_1ZDLzv5MRxSpTZbSm5L1DAAn0nwkpnqo">Huly&reg;: <b>V_0.6-21802</b></a></sub>
> ci: force all tools to build without warnings/notices in tools_ci.yml

- vlib/v/checker/assign.v
- vlib/v/tests/enums/enum_assign_on_anon_fn_test.v
Fix #23366
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc5MjQ1YWYxNDRmNTg1YWU1MjdhOTEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.NwmbTphj9Pm1LsUo3pV7heu4_vyOPRaxZW2yjQSG9ZE">Huly&reg;: <b>V_0.6-21798</b></a></sub>
> checker: fix assign expected type on rechecking enum assigns 

- vlib/compress/gzip/gzip.v
- vlib/compress/gzip/read_gz_files_test.v
Fix issue #14994
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc5MzA2OWYxNDRmNTg1YWU1MjdiNjAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.KgVodTiJAjCnSuFn-2SFFvkgSft2wGHECOkSYh2caj4">Huly&reg;: <b>V_0.6-21801</b></a></sub>
> compress.gzip: add compression flags

- vlib/v/builder/builder.v
- vlib/v/builder/cc_windows.v
This PR ensure that when compile with other compilers ( such as `tcc` ), will not search for `msvc` first, which will create another process may slow down the whole compilation.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzdiMWNkM2YxNDRmNTg1YWU1MjliZGUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.n3BOrIWESPEwwWzqNJXY1hsmxNq_Pl9gVpJDzkgWIM8">Huly&reg;: <b>V_0.6-21817</b></a></sub>
> builder: do not search for msvc when no need

- vlib/v/gen/c/assign.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/options/option_generic_alias_test.v
Fix #23382
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzdjMmNmOGYxNDRmNTg1YWU1MmU3NDQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.lkUwounqQaCE_jaXFViDCAZAdYlfTgDJCTMtf7NufSM">Huly&reg;: <b>V_0.6-21824</b></a></sub>
> cgen: fix generic alias option assigning

- vlib/v/gen/c/cgen.v
- vlib/v/tests/concurrency/selector_shared_var_test.v
Fix #23378
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzdjNDcyZGYxNDRmNTg1YWU1MmU4OGIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.2f-rMxEBGbcMvBLC0gUyo0jheE9dajlQAECUtM123Co">Huly&reg;: <b>V_0.6-21825</b></a></sub>
> cgen: fix codegen for selector on shared var with embed

- vlib/v/parser/parser.v
- vlib/v/tests/map_cast_test.v
Allow
```v
fn foo() map[int]int {
return {
1: 2
}
}
a := ?map[int]int(none)
assert a == none
b := ?map[int]int({
1: 2
})
assert b?[1] == 2
c := ?map[int]map[string]string({
1: {
'foo': 'bar'
}
})
assert c?[1]['foo'] == 'bar'
d := ?map[int]int(foo())
assert d?[1] == 2
}
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzdkNWRkOGYxNDRmNTg1YWU1MzE0MTYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.sszAYnovv-8EKL6B89JWetKkXtyKLmBO7HUxjFs4gMs">Huly&reg;: <b>V_0.6-21832</b></a></sub>
> parser: allow map cast syntax `map[k]v(expr)`

- vlib/v/gen/c/assign.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/comptime/comptime_generic_map_test.v
Fix #23376
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzdkOGIyMWYxNDRmNTg1YWU1MzFhMzkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.5UvD-0YoD6ZreefYE-6bzeuLL_2GGgWbh8OI9xQh2go">Huly&reg;: <b>V_0.6-21833</b></a></sub>
> cgen: fix codegen for indexing generic map

- vlib/v/gen/c/index.v
- vlib/v/tests/concurrency/shared_array_indexing_test.v
Fix #23410
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzdlZjFlN2YxNDRmNTg1YWU1MzRmZjIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.QsO_7z6jrGq391oBYhtRBkklgVa82pdckKruLuG19Ko">Huly&reg;: <b>V_0.6-21844</b></a></sub>
> cgen: fix shared array indexing

- vlib/v/gen/c/struct.v
- vlib/v/tests/concurrency/shared_fixed_array_init_test.v
Fix build of chip8-v project.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzdlZjdlNmYxNDRmNTg1YWU1MzUwNWEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.bKpKtrXElF6jPqHzmXx-kHvqWzddBIGUZosEK2KpOFE">Huly&reg;: <b>V_0.6-21845</b></a></sub>
> cgen: fix shared array fixed initializing with `-cstrict`

- vlib/v/checker/fn.v
Cleanup and optimize.
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzdlY2ViZGYxNDRmNTg1YWU1MzRjZWQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.JGEK7zezMA6WAyya0F9hTzYkcvERjQdye1hMldr2WRw">Huly&reg;: <b>V_0.6-21842</b></a></sub>
> checker: cache `node.args[0]` on `fixed_array_builtin_method_call` and `array_builtin_method_call`

- vlib/veb/README.md
- vlib/veb/context.v
`veb` currently lacks a convenient way to return a **204 No Content** response without a body and no content-type header.
This PR adds such a method and prevents `ctx.send_response_to_client` to always set a content-type header, even if it is set to an empty string.
```
// send a 204 No Content response without body and content-type
pub fn (mut ctx Context) no_content() Result {
ctx.res.set_status(.no_content)
return ctx.send_response_to_client('', '')
}
```
Using `curl`, the response looks like this:
```
> GET / HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 204 No Content
< Server: veb
```
<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzgx …
> veb: add ctx.no_content() + prevent content-type being set if empty

- vlib/v/checker/return.v
- vlib/v/checker/tests/lockexpr_missing_return_err.out
- vlib/v/checker/tests/lockexpr_missing_return_err.vv
> checker: fix missing detection for `return` on lockexpr stmts

- cmd/tools/modules/testing/common.v
- vlib/crypto/ecdsa/README.md
- vlib/crypto/ecdsa/ecdsa.v
- vlib/crypto/ecdsa/ecdsa_test.v
- vlib/crypto/ecdsa/util.v
- vlib/crypto/ecdsa/util_test.v
There are lack of functionality commonly
needed in the `crypto.ecdsa` module.
Some of them are
- Currently, only support for NIST  P-256 curve, we need more curve on the stock.
- Current `ecdaa.PrivateKey.sign(message)`  does not work on hash (digest) of the message, but its work on message directly.. Its not recommended working on signing messages directly.
This PR  address some of them issue,  by adding and expand support for another popular ecc curve, ie,
- Add support for NIST P-384, ie, `secp384r1` curve
- Add support for NIST P-521, ie, `secp521r1` curve
- Add support for famous `|secp256k1` curve used in bitcoin ecosystem.
This PR also add a routine to sign message with options to use irecommended hash function or custom hash (maybe its can be unified with the current sign routine) …
> crypto.ecdsa: expand ecdsa module to support another curve.

- vlib/v/gen/c/if.v
- vlib/v/tests/options/option_ifguard_array_of_option_test.v
> cgen: fix codegen for ifguard indexing array of option 

- vlib/db/pg/pg.c.v
- vlib/db/pg/pg_test.v
PostgreSQL has two separate calls to support prepared statements. This PR adds the following two public functions to `db.pg`:
```vlang
pub fn (db DB) prepare(name string, query string, num_params int) !
pub fn (db DB) exec_prepared(name string, params []string) ![]Row
```
plus one to handle an empty result to check for an error when `prepare` is called.
Also an appropriate test has been added.
> db.pg: add support for prepared statements

- vlib/crypto/ecdsa/ecdsa_test.v
- vlib/crypto/ecdsa/util.v
- vlib/crypto/ecdsa/util_test.v
Fix memleak spotted by sanitizers CI.
> ecdsa: fix memleaks

- vlib/builtin/builtin.v
Fix issue #23461 
As `cgen.v` will call `isnil()` in `builtin.v`.
> builtin: isnil() markused

- vlib/v/ast/types.v
- vlib/v/fmt/struct.v
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/c/struct.v
- vlib/v/parser/struct.v
- vlib/v/tests/structs/struct_field_shared_test.v
> v: allow shared anon struct + fix shared struct field initialization with no default value

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/index.v
- vlib/v/tests/assign/assign_option_of_array_index_test.v
This PR fix assigning option of array index  (fix #23451).
- Fix assigning option of array index.
- Add test.
```v
fn make_option() ?string {
return none
}
fn main() {
arr := [make_option()]
unwrapped := arr[99] or { 'unknown' } // <- out of bounds access!
println('... ${unwrapped}')
}
... Option('unknown')
```
> cgen: fix assigning option of array index  (fix #23451)

- vlib/v/ast/ast.v
- vlib/v/checker/assign.v
- vlib/v/checker/fn.v
- vlib/v/gen/c/array.v
- vlib/v/gen/c/assign.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/comptime_generic_comptime_variant_test.v
- vlib/v/tests/generics/generic_var_loop_test.v
- vlib/v/type_resolver/comptime_resolver.v
- vlib/v/type_resolver/generic_resolver.v
- vlib/v/type_resolver/type_resolver.v
> type_resolver: fix fn detection for comptime arg type

- vlib/math/stats/stats.v
- vlib/v/gen/c/infix.v
- vlib/v/tests/generics/generic_selector_len_test.v
- vlib/v/type_resolver/comptime_resolver.v
```v
struct Foo[T] {
len T
}
fn t[T](val T) string {
a := val.len + val.len
println(a)
return a.str()
}
assert t(Foo[string]{ len: 'hello' }) == 'hellohello'
assert t(Foo[int]{ len: 123 }) == '246'
assert t([1, 2, 3]) == '6'
assert t([1.2, 2.2, 3.3]) == '6'
assert t(['', '', '']) == '6'
}
```
> type_resolver: fix generic selector field type resolving

- vlib/builtin/builtin.v
- vlib/v/checker/str.v
- vlib/v/tests/skip_unused/auto_string.run.out
- vlib/v/tests/skip_unused/auto_string.skip_unused.run.out
- vlib/v/tests/skip_unused/auto_string.vv
This PR is an improved version of PR #23462
Fix issue #23461
> checker: fix isnil() markused, use c.table.used_features.auto_str_ptr = true

- vlib/v/gen/c/fn.v
- vlib/v/gen/c/spawn_and_go.v
- vlib/v/slow_tests/inout/thread_uninitialized_err.out
- vlib/v/slow_tests/inout/thread_uninitialized_err.vv
> cgen: fix cgen error for `instance.t.wait()` on default 0 initialized thread field `t` (fix #23390)

- vlib/v/ast/table.v
- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/checker/struct.v
- vlib/v/gen/c/cgen.v
- vlib/v/markused/markused.v
- vlib/v/tests/skip_unused/ierror_str.run.out
- vlib/v/tests/skip_unused/ierror_str.skip_unused.run.out
- vlib/v/tests/skip_unused/ierror_str.vv
Fix build of  v-r2pipe project.
> markused: fix `eprintln(err)` on imported module on short program

- vlib/v/gen/c/cgen.v
- vlib/v/tests/options/option_nested_selector_unwrap_test.v
Fix #23500 
```v
type Foo = string | int | f32
struct Bar {
log ?Foo
}
fn Bar.init(log ?Foo) {
mut bar := Bar{
log: log
}
if bar.log != none {
if bar.log is string {
assert bar.log == 'foobar'
return
}
}
assert false
}
Bar.init('foobar')
}
```
> cgen: fix nested option selector unwrapping

- vlib/v/ast/table.v
- vlib/v/checker/checker.v
- vlib/v/checker/comptime.v
- vlib/v/checker/containers.v
- vlib/v/checker/fn.v
- vlib/v/checker/infix.v
- vlib/v/checker/interface.v
- vlib/v/checker/str.v
- vlib/v/checker/used_features.v
- vlib/v/pref/pref.v
> v: cleanup used_features logic from checker

- vlib/v/checker/match.v
- vlib/v/checker/tests/match_generic_case_err.out
- vlib/v/checker/tests/match_generic_case_err.vv
- vlib/v/checker/tests/match_return_mismatch_type_err.out
- vlib/v/checker/tests/match_return_sumtype_mismatch_err.out
- vlib/v/checker/tests/return_match_expr_type_mismatch.out
- vlib/v/tests/generics/generic_match_expr_test.v
> checker: fix missing check for concrete type on match branch expr

- vlib/v/checker/fn.v
- vlib/v/checker/str.v
- vlib/v/checker/tests/invalid_generic_field_err.out
- vlib/v/checker/tests/invalid_generic_field_err.vv
> checker: fix missing check for invalid argument for builtin

- vlib/v/ast/ast.v
- vlib/v/ast/scope.v
- vlib/v/checker/checker.v
> checker: fix selector nested unwrapping

- vlib/v/pref/pref.v
Running the coroutine example was failing on darwin/arm64:
```
$ git clone --depth=1 https://github.com/vlang/v
$ cd v
$ make                                                     
cd ./vc && git clean -xf && git pull --quiet
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
cc  -std=gnu99 -w -o v1.exe ./vc/v.c -lm -lpthread 
./v1.exe -no-parallel -o v2.exe  cmd/v
./v2.exe -nocache -o ./v  cmd/v
rm -rf v1.exe v2.exe
V has been successfully built
V 0.4.9 1b9f15d
$ v -use-coroutines run ./examples/coroutines/simple_coroutines.v
coroutines .so not found, downloading...
done!
dyld[41752]: Library not loaded: photonwrapper.so
Referenced from: <7E4605BF-8E27-3070-8498-3EE37E5AC4BB> /Users/u/Projects/v/v/examples/coroutines/simple_coroutines
Reason: tried: 'photonwrapper.so' (no such file), …
```
> pref: -use-coroutines download photonwrapper to root

- vlib/v/gen/c/auto_eq_methods.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/interfaces/interface_as_cast_in_anon_fn_test.v
This PR fix interface casting in anon fn (fix #23530).
- Fix interface casting in anon fn.
- Add test.
```v
@[heap]
struct Foo {
mut:
val int
}
@[heap]
struct Bar {
mut:
val int
}
interface FooBar {
mut:
val int
}
fn main() {
mut fbs := []&FooBar{}
fbs << &Foo{1}
do_something := fn [mut fbs] () {
_ := fbs.last() as Foo // this line works outside of anon fn
}
do_something()
assert true
}
```
> cgen: fix interface casting in anon fn (fix #23530)

- vlib/v/checker/comptime.v
- vlib/v/checker/fn.v
- vlib/v/checker/return.v
- vlib/v/checker/tests/ctdefine.out
> checker: fix message with old attr syntax

- vlib/v/parser/parser.v
- vlib/v/util/util.v
> util, parser: inline some fns

- vlib/v/ast/ast.v
- vlib/v/ast/scope.v
- vlib/v/checker/checker.v
- vlib/v/tests/options/option_generic_selector_unwrap_test.v
- vlib/v/tests/options/option_selector_nested_unwrap_test.v
> checker: simplify unwrap nested selector fix

- vlib/v/markused/markused.v
> markused: minor optmization checking names with dot

- vlib/v/checker/fn.v
- vlib/v/checker/infix.v
> v: cache repeated `node.args.len`, `method.generic_names.len`, `node.concrete_types.len` and `node.op.str()`

- vlib/v/ast/table.v
- vlib/v/fmt/tests/union_with_nested_union_keep.vv
- vlib/v/gen/c/cgen.v
- vlib/v/parser/struct.v
- vlib/v/tests/unions/nested_union_test.v
- **v.parser,vfmt: support nested unions, with `field union {`, similar to `field struct {`**
- **fix cgen, add test**
> parser,ast,cgen: support nested unions with `field union {`, to improve c interoperability (similar to `field struct {`)

- vlib/v/markused/markused.v
- vlib/v/markused/walker.v
> markused: cleanup as_cast handling

- vlib/os/os.v
- vlib/os/os_test.c.v
This will help user get the filename without ext.
`split_path` will split `opath` into (`dir`,`filename`,`ext`).
Examples:
```v
dir,filename,ext := os.split_path('/usr/lib/test.so')
assert [dir,filename,ext] == ['/usr/lib','test','.so']
```
Bug fix:
`os.base()`, `os.file_name()`, `os.dir()` all support both windows/non-windows path at the same time.
> os: add split_path()

- vlib/log/README.md
- vlib/log/common.v
- vlib/log/log.v
- vlib/v/slow_tests/inout/dump_expression.out
- vlib/v/slow_tests/inout/dump_expression.vv
This PR is second try of https://github.com/vlang/v/pull/23296
In short:
- Makes possible set log output to `io.Writer` via new `.set_output_stream()` fn
- Sets `os.stderr()` as default log output.
> breaking,log: set stderr as default log output, add .set_output_stream()

- cmd/tools/vast/vast.v
- cmd/tools/vvet/analyze.v
- cmd/tools/vvet/errors.v
- cmd/tools/vvet/vvet.v
- vlib/v/ast/ast.v
- vlib/v/help/common/vet.txt
- vlib/v/parser/fn.v
> vet: notice potentially fn to be inlined

- vlib/v/gen/c/assign.v
- vlib/v/tests/builtin_arrays/array_fixed_from_unsafe_test.v
> cgen: fix codegen for assign from unsafe fn returning fixed array

- vlib/v/gen/c/cgen.v
- vlib/v/tests/builtin_arrays/array_fixed_init_node_test.v
> cgen: fix codegen for array fixed init with different node types

- vlib/v/gen/c/cgen.v
- vlib/v/tests/options/option_multi_return_if_test.v
> cgen: fix codegen for return on last statement of `return IfExpr`

- vlib/v/gen/c/assign.v
- vlib/v/tests/generics/generic_selector_infix_test.v
- vlib/v/type_resolver/type_resolver.v
> cgen: fix codegen for assigning from infixexpr with generic operand

- vlib/v/gen/c/fn.v
- vlib/v/tests/builtin_arrays/array_grow_cap_test.v
> cgen: fix codegen for array's grow_cap, grow_len method from generic array

- vlib/v/ast/ast.v
- vlib/v/checker/assign.v
- vlib/v/checker/comptime.v
- vlib/v/checker/fn.v
- vlib/v/checker/postfix.v
- vlib/v/checker/tests/option_str_call.out
- vlib/v/checker/tests/option_str_call.vv
- vlib/v/gen/c/assign.v
- vlib/v/gen/c/cgen.v
- vlib/v/parser/comptime.v
- vlib/v/tests/c_struct_with_reserved_field_name_test.v
- vlib/v/tests/comptime/comptime_unwrap_test.v
- vlib/v/tests/comptime/comptime_var_assignment_test.v
- vlib/v/tests/options/option_var_cast_test.v
- vlib/v/tests/sumtypes/sumtype_generic_checking_test.v
- vlib/v/type_resolver/comptime_resolver.v
- vlib/v/type_resolver/type_resolver.v
- vlib/x/json2/encoder.v
- vlib/x/sessions/tests/session_app_test.v
> checker: turn `option_var.str()` an error without unwrapping first

- vlib/encoding/iconv/iconv_nix.c.v
Fix vlang/v#23573
----
**Tests for iconv OK on OpenBSD current/amd64 with tcc, egcc and clang**
- Tests with tcc
```shell
$ ./v -stats test vlib/encoding/iconv/                                                                                                                                                                    
---- Testing... -----
running tests in: /home/fox/dev/vlang.git/vlib/encoding/iconv/iconv_test.v                                                                                                                                                                                                        
OK    [1/5]     0.124 ms     8 asserts | main.test_vstring_to_encoding() …
```
> encoding.iconv: add flag for OpenBSD to find iconv include and library

- vlib/runtime/free_memory_impl_openbsd.c.v
Implementation of `free_memory` function for OpenBSD => add specific implementation in `vlib/runtime/free_memory_impl_openbsd.c.v`
Closes vlang/v#23579
---
**Tests OK for `runtime` on OpenBSD/amd64**
```shell
$ uname -mrs
OpenBSD 7.6 amd64
$ ./v -stats test vlib/runtime/runtime_test.v
---- Testing... ----
running tests in: /home/fox/dev/vlang.git/vlib/runtime/runtime_test.v
total memory: 4278042624
free  memory: 1288601600
OK    [1/9]     0.018 ms     1 assert  | main.test_physical_memory()
nr cpus: 4
OK    [2/9]     0.008 ms     1 assert  | main.test_nr_cpus()
nr jobs: 3
OK    [3/9]     0.009 ms     1 assert  | main.test_nr_jobs()
is_32bit: false
OK    [4/9]     0.006 ms     1 assert  | main.test_is_32bit()
is_64bit: true
OK    [5/9]     0.008 ms     1 assert  | main.test_is_64bit() …
```
> runtime: add free_memory implementation for OpenBSD

- cmd/tools/vdoctor.v
- get gcc version via `egcc --version`
- don't run `ldd` to get glibc version
Fix vlang/v#23576
---
**vdoctor output OK on OpenBSD and Linux**
- OpenBSD/amd64
```shell
$ ./v doctor
|V full version      |V 0.4.9 d710d9e.62d618e
|:-------------------|:-------------------
|OS                  |openbsd, 7.6, GENERIC.MP#518
|Processor           |4 cpus, 64bit, little endian
|Memory              |9.3e-10GB/3.98GB
|                    |
|V executable        |/home/fox/dev/vlang.git/v
|V last modified time|2025-01-25 17:44:17
|                    |
|V home dir          |OK, value: /home/fox/dev/vlang.git
|VMODULES            |OK, value: /home/fox/.vmodules
|VTMP                |OK, value: /tmp/v_1000
|Current working dir |OK, value: /home/fox/dev/vlang.git
|                    |
|Git version …
```
> tools: fix doctor output on OpenBSD

- vlib/builtin/cfns.c.v
- vlib/builtin/int.v
- vlib/builtin/js/int.js.v
- vlib/builtin/wasm/wasi/int.v
- vlib/compress/szip/szip.c.v
- vlib/encoding/csv/csv_reader_random_access.v
- vlib/v/ast/table.v
- vlib/v/ast/types.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/modules/private_symbol.out
- vlib/v/checker/tests/modules/private_symbol/main.v
- vlib/v/checker/tests/modules/private_symbol/priv_sym.v
- vlib/x/templating/dtm/dynamic_template_manager.v
Fix #23518
Additional fixes:
https://github.com/larpon/shy/pull/20
https://github.com/vlang/ui/pull/593
https://github.com/vlang/ui/pull/594
> checker: fix private symbol visibility checking

- vlib/v/checker/checker.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/comptime/comptime_var_unwrap_test.v
> cgen: fix codegen for unwrapping option comptime var

- vlib/encoding/utf8/utf8_util_test.v
> encoding: remove/modify deprecated tests for utf8/utf8_util

- vlib/v/checker/checker.v
> checker: disallow constant modification on `unsafe {}` 

- vlib/builtin/array.v
- vlib/v/gen/c/auto_free_methods.v
- vlib/v/gen/c/autofree.v
- vlib/v/tests/u8_free_test.v
> builtin: add &u8.free()

- vlib/builtin/map_test.v
Fix vlang/v#23601
---
**Tests OK** for `vlib/builtin/map_test.v`: no warning/error
```sh
$ ./v -stats test vlib/builtin/map_test.v                                                                                                                                                                                                     
---- Testing... ----------------------------------------------------------------------------------------------------------------------------                                                                                                                                      
running tests in: /home/fox/dev/vlang.git/vlib/builtin/map_test.v …
```
> builtin: fix tests for map

- doc/docs.md
Rearranged `Strings` section a small amount, clarified some descriptions, added a small amount of detail to some examples.
> doc: rework strings section to clarify

- vlib/builtin/cfns.c.v
- vlib/runtime/free_memory_impl_freebsd.c.v
> runtime: add freebsd free_memory() support

- vlib/log/safe_log.v
- vlib/sync/sync.c.v
- vlib/sync/sync_darwin.c.v
- vlib/sync/sync_default.c.v
- vlib/sync/sync_freebsd.c.v
- **log,sync: fix macos failure with log.ThreadSafeLog**
- **log: add missing free(x.mu), since now `mu` is heap allocated**
> log,sync: fix macos CI failure when log.ThreadSafeLog is used explicitly in `v download`

- vlib/crypto/ecdsa/ecdsa.v
- vlib/crypto/ecdsa/ecdsa_test.v
- vlib/crypto/ecdsa/util_test.v
This PR contains small fix bug when signing message with .`with_no_hash` options. The bug more clearly self-explained in this snippet
```v
import crypto.ecdsa
fn main() {
// default prime256v1 key was 32 bytes length
pv := ecdsa.PrivateKey.new()!
// creates message with length over key size
msg_a := 'a'.repeat(34).bytes()
opt := ecdsa.SignerOpts{
hash_config: .with_no_hash
}
signed := pv.sign(msg_a, opt)!
pb := pv.public_key()!
st := pb.verify(msg_a, signed, opt)!
// this should be true
dump(st) 
// different msg should not be verified under the same signature.
msg_b := 'a'.repeat(392).bytes()
ds := pb.verify(msg_b, signed, opt)!
// should false
dump(ds)
}
```
but the output was
```
[code.v:14] st: true
[code.v:19] ds: true
```
Its changed `.with_no_hash` to have the same behaviour with …
> crypto.ecdsa: fix bug when signing with `.with_no_hash` options.

- vlib/crypto/ecdsa/ecdsa.v
- vlib/crypto/ecdsa/util_test.v
This small PR following previously already merged PR in [fix-no-hash](https://github.com/vlang/v/pull/23612) commit.
The current handling with custom hash was still contains some bogus thing without additional test (sorry, its my bad).
Its resolved in the current PR, by the way with:
- call `.reset()` on the custom hash before writing messages
- previously, its not call `.write()` before `.sum()` ..its does not matching to expected result, when compared, for examples digest produced with `sha256.sum256(message)` directly.  The equivalent of `sum(message)` was
```v
_ := custom_hash.write(message)!
digest := custom_hash.sum([]u8{})
```
- Add some test to verify expected behaviour
Thanks ...
> crypto.ecdsa: fix handling sign with custom_hash

- vlib/runtime/runtime_nix.c.v
Implementation available only on Darwin, FreeBSD, Linux, OpenBSD and Windows.
> runtime: add note for the availability of the free_memory/0 implementation

- vlib/v/checker/checker.v
- vlib/v/gen/c/infix.v
- vlib/v/type_resolver/comptime_resolver.v
- vlib/v/type_resolver/type_resolver.v
> type_resolver: remove type_resolver.get_expr_type_or_default and type_resolver.is_comptime_expr

- vlib/v/gen/c/cgen.v
- vlib/v/tests/enums/maps_with_enum_flag_keys_test.v
> cgen: fix hash functions for `map[Enum]Value`, and `enum Enum as u64 {` (fix #23630)

- vlib/builtin/cfns.c.v
- vlib/os/os.c.v
- vlib/os/os_nix.c.v
- vlib/os/os_test.c.v
- vlib/os/os_windows.c.v
disk_usage(path) returns disk usage of `path`
Examples:
```v
pub struct DiskUsage {
pub:
total     u64
available u64
used      u64
}
usage := os.disk_usage('.')!
assert usage.total > 0
assert usage.available > 0
assert usage.used > 0
```
> os: add disk_usage()

- vlib/v/gen/c/cgen.v
- vlib/v/tests/options/option_ptr_unwrap_selector_test.v
> cgen: fix unwrap option ptr selector

- vlib/builtin/string.v
- vlib/builtin/string_test.v
This PR:
- Add new fn `split_by_space()` for `string` builtin.
- Add test
Usecase:
```shell
>>> cmd := os.execute('ip -br link show wlan0')
>>> cmd.output
wlan0            UP             14:75:7b:ca:a2:c4 <BROADCAST,MULTICAST,UP,LOWER_UP> 
>>> cmd.output.split_by_space()
['wlan0', 'UP', '14:75:7b:ca:a2:c4', '<BROADCAST,MULTICAST,UP,LOWER_UP>']
>>> mac := cmd.output.split_by_space()[2]
>>> mac
14:75:7b:ca:a2:c4
```
> builtin: add string.split_by_space()

- vlib/crypto/ecdsa/ecdsa.c.v
- vlib/crypto/ecdsa/ecdsa.v
This PR was a continuation of migration step of this [phase](https://discord.com/channels/592103645835821068/592320321995014154/1332203056707801138). In this PR, its only migrates one generator function `ecdsa.PrivateKey.new()` to use high level api. Its also still use old deprecated api to support old function that relies on `EC_KEY` function.
So, its does not changes the current behaviour, and the old opaque still avaialbles on there.
The other changes are:
- Add required C declarations
- Some bits of code reorganization to make its easy to read.
- Add some constants to easy the access
- Improves the function docs.
Its is..
Happy days..
> crypto.ecdsa: migrate `ecdsa.PrivateKey.new()` to use high level api

- vlib/v/gen/c/assign.v
- vlib/v/tests/options/option_map_set_test.v
> cgen: fix codegen for option value on `map_set`

- vlib/v/gen/c/assign.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/options/option_sumtype_option_variant_test.v
> cgen: fix codegen for option sumtype with option variant

- vlib/gg/gg.c.v
Fixes #23667. I don't if this type of thing can have _test.v files written for it. But I have verified that this does work on Mac. The issue was caused by `Event.mouse_x/y` not being divided by the `Context.scale` before triggering the `Context.event_fn`. It needs to be tested on a high DPI display on Windows and Linux.
> gg: fix incorrect `Event.mouse_x` and `Event.mouse_y` on  `gg.Context.event_fn` and `gg.Context.on_event`.

- doc/docs.md
Removed the paragraph and about `vfmt` renaming `go` to `spawn`. Add a sentence about using `go` keyword. More about `go` coroutines should be added but for now this pull request removes the outdated stuff.
> Doc: remove paragraph about vfmt renaming go to spawn.

- vlib/v/checker/check_types.v
Cache
```v
got_is_any_kind_of_pointer := got.is_any_kind_of_pointer()
exp_is_any_kind_of_pointer := expected.is_any_kind_of_pointer()
```
> checker: cleanup check_types

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/testdata/fixed_arr_const_unsafe.c.must_have
- vlib/v/gen/c/testdata/fixed_arr_const_unsafe.vv
> cgen: fix codegen for array fixed const initialized with unsafe exprs

- vlib/orm/orm_serial_attribute_test.v
- vlib/v/gen/c/orm.v
Fix https://github.com/vlang/v/issues/23346
> orm,cgen: fix `@[sql: serial]` and `@[serial]` are not the same

- vlib/crypto/ecdsa/ecdsa.c.v
- vlib/crypto/ecdsa/ecdsa.v
- vlib/crypto/ecdsa/ecdsa_test.v
- vlib/crypto/ecdsa/util_test.v
This is a 3rd PR sent in efforts to migrate `crypto.ecdsa` module to use high level api. In this current PR, its basically migrates two thing, ie, in the form:
- Migrates `PrivateKey.public_key()` to use the new one. Its approach was done by serializing this high level opaque (if availables) to der serialized bytes and get its back into other opaque and use this as public key part. If this high level opaque (`evpkey` field) was not availables, it will use the old one.
- Simplify `generate_key` function to use this new approach , by just more simpler calling to the `.new()` and `.public_key()` .
- Removes `.key_free()` .. Its has been replaced by its explicit counterparts of `.free()` of the desired key.
- Just some cleansup of bits
Happy days
> crypto.ecdsa: migrate generate_key and makes it more simpler.

- vlib/encoding/csv/csv_reader_random_access.v
- vlib/encoding/csv/csv_reader_test.v
- Added support for multithreading to `encoding.csv.RandomAccessReader`
- Added multithreading tests
The multithreading was performed with file up to 6GB with 60M of rows.
*Note:* if the file is huge the use of `-thread-stack-size` flag is needed to adjust the stack size
> encoding.csv: add support for multithreading to `encoding.csv.RandomAccessReader`

- vlib/v/builder/cc.v
builder: Fix #23685
Added os.quoted_path for all os.system calls for the compress option.
> Added os.quoted_path to os.system calls for the compress flag

- cmd/tools/vreduce.v
Improve the parser by enabling full function removal by considering it as a scope (before it left the signature and the brackets out of the scope)
Add an outer loop to the reducing process to clean as much code it can.
Before: lots leftover unnecessary functions that needed to be removed by hand
for my last MRE made by reduce for a 3k lines file: 66 lines
now: made by reduce for the same file: 9 lines (a const leftover, a struct used by the error producing function, and the function in itself)
> tools: reduce: improve parser for functions and add more loops to reduce more

- cmd/tools/vreduce.v
fix: warn_on_false did not check if it was false
Now it does not warn for nothing.
> tools: reduce: fix warnings

- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/checker/tests/unkown_enum_call_err.out
- vlib/v/checker/tests/unkown_enum_call_err.vv
> checker: fix call from unknown enum

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/if.v
- vlib/v/tests/nested_if_return_test.v
> cgen: fix codegen for nested if on return 

- vlib/v/gen/c/cgen.v
- vlib/v/tests/enum_packed_test.v
> cgen: fix map with Enum minor than 4 bytes on tcc

- vlib/v/checker/fn.v
- vlib/v/checker/tests/call_arg_multi_return_err.out
- vlib/v/checker/tests/call_arg_multi_return_err.vv
> checker: add checker for passing multi return as arg to func that expects less param

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/native/tests/print.vv
- vlib/v/gen/native/tests/print.vv.out
Adds comments to help understanding the code.
Adds more `c.g.println` calls to have an easier time in verbose native mode.
Fixes the new test by terminating the buffer used in `convert_int_to_string` with `\0` because it is assumed after when reversing it and when priting it (it tries to find it's lenght by searching `\0`). (I did not know how to name my test function.)
Adds CLD when reversing the string to prevent the case where DF would be set and REPNE SCAS would do the opposite of what is expected.
> native: fix convert_int_to_string, add comments, more verbose

- vlib/strconv/atoi.v
- vlib/strconv/atoi_test.v
Added atoi8, atoi16, atoi32 and atoi64 method. Added respective tests.Refactor some atoi() code to avoid code duplication. atoi64() uses a slightly different code, to keep using i64 types. Spytheman suggested to use math.i128 aritmetic. I didn't do it, but this can be done by anyone else.
I didn' t replicate Spytheman' s work around for MSVC compiler (msvc has a bug that treats just i64(min_int) as 2147483648).
> strconv : Addition of Atoi8/16/32/64 helper, with their test.

- vlib/strconv/atoi_test.v
- vlib/strconv/atou.v
- vlib/strconv/atou_test.v
New file in strconv module: atou.v and atou_test.v.
atou / atou32 are provided to keep implementation symmetric with atoi / atoi32.
I choose to partially duplicate code, to avoid parametrizing atoi_common_check
and atoi_common for unsigned case.  This choice let the code simpler.
> strconv : atou, atou8/16/32/64 function added, with tests.

- vlib/v/builder/msvc_windows.v
- vlib/v/cflag/cflags.v
- vlib/v/parser/comptime.v
This PR provides a way to cleanup `vlib/sync/stdatomic/1.declarations.c.v` later.
It will look like this:
```v
$if linux {
$if tinyc {
$if amd64 {
// most Linux distributions have /usr/lib/libatomic.so,
// but Ubuntu uses gcc version specific dir
#flag $when_first_existing('/usr/lib/gcc/x86_64-linux-gnu/6/libatomic.a','/usr/lib/gcc/x86_64-linux-gnu/7/libatomic.a','/usr/lib/gcc/x86_64-linux-gnu/8/libatomic.a','/usr/lib/gcc/x86_64-linux-gnu/9/libatomic.a','/usr/lib/gcc/x86_64-linux-gnu/10/libatomic.a','/usr/lib/gcc/x86_64-linux-gnu/11/libatomic.a','/usr/lib/gcc/x86_64-linux-gnu/12/libatomic.a','/usr/lib/gcc/x86_64-linux-gnu/13/libatomic.a','/usr/lib/gcc/x86_64-linux-gnu/14/libatomic.a')
// Redhat/CentOS paths:
#flag $when_first_existing('/usr/lib/gcc/x86_64-redhat-linux/6/libatomic.a','/usr/ …
```
> v.cflag: support `#flag $when_first_existing(libABC.a, /some/path/libABC.a, ...)`, without panicing (unlike `#flag $first_existing(...)`)

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/match.v
- vlib/v/tests/sumtypes/sumtype_ptr_ptr_test.v
> cgen: fix codegen for match with sumtype ptrptr

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/arm64.v
- vlib/v/gen/native/elf.v
- vlib/v/gen/native/expr.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/native/macho.v
- vlib/v/gen/native/pe.v
- vlib/v/gen/native/stmt.c.v
- vlib/v/gen/native/tests/enum.vv
Add support for enums with a user-chosen type like `enum MyEnum as u8`
Instead of duplicating functions for u64 and i64, use a sumtype
Add tests for enums of different types
> native: add support for enums of different types

- vlib/v/pref/pref.v
Simply add #  before range in  args#[command_idx + 1..] on Spytheman's suggestion.
This  will prevent panic, but just produce an [], when there are not enough arguments.
It solves the issue : https://github.com/vlang/v/issues/23713
> pref: Fix panic in parse_args_and_show_errors was called with no args.

- vlib/v/checker/checker.v
- vlib/v/checker/tests/c_struct_cast.out
- vlib/v/checker/tests/c_struct_cast.vv
> checker: fix missing struct cast validation

- vlib/v/gen/c/spawn_and_go.v
- vlib/v/tests/concurrency/mut_receiver_gowrapper_test.v
> cgen: fix gowrapper codegen for receiver ptrptr

- vlib/veb/request_id/README.md
- vlib/veb/request_id/request_id.v
- vlib/veb/request_id/request_id_test.v
This module implements request ID tracking functionality for V web applications. Request IDs are unique identifiers assigned to each HTTP request, which is essential for request tracing, debugging, and maintaining distributed systems.
Request IDs help in:
- Tracking requests across distributed systems
- Correlating logs from different services
- Debugging and troubleshooting
- Performance monitoring
- Request chain tracing
To enable request ID tracking in your veb app, you must embed the `RequestIdContext` struct in your `Context` struct.
**Example:**
```v
import veb
import veb.request_id
pub struct Context {
veb.Context
request_id.RequestIdContext
}
```
Here's a simple configuration example:
```v
const request_id_config := request_id.Config{
header: 'X-Request-ID'
generator: rand.uuid_v4 …
```
> veb.request_id: New middleware that implements request ID tracking

- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/stmt.c.v
- vlib/v/gen/native/tests/vtest_int_cmp.vv
Fix unsigned / signed integer comparison
Add test coming from vlib/v/tests with prefix `vtest_`
I took the test from the cgen backend because it's quite complete for edge cases
> native: fix unsigned and signed int comparison

- vlib/sokol/c/declaration.c.v
See <https://github.com/emscripten-core/emscripten/issues/7950> for the details.
> sokol: allow for `v -os wasm32_emscripten -o examples/tetris/tetris.html examples/tetris/` (avoid using `-sMODULARIZE`)

- vlib/v/tests/reserved_keywords_as_struct_field_test.v
Dear Vlang Community,
I recently discovered that a piece of code I wrote has been used in the V language tests without proper attribution. While I am happy to contribute to the project, I would like to request that my ownership be acknowledged, as required by the MIT License under which my code is distributed.
Details:
I initially encountered a bug in V and reported it in this issue: [#11368](https://github.com/vlang/v/issues/11368).
As part of the issue, I provided an example of my code, which can be found here: [linked_list.v](https://github.com/ep4sh/algoV/blob/master/linked_list.v).
My code was subsequently added to the V language tests in this file: [reserved_keywords_as_struct_field_test.v](https://github.com/vlang/v/blob/master/vlib/v/tests/reserved_keywords_as_struct_field_test.v). …
> Add missing license info for reserved_keywords_as_struct_field_test file

- vlib/builtin/string.v
- vlib/strconv/atof.c.v
- vlib/strconv/atof_test.c.v
This PR help detect extra char after number during the `atof64()` conversion.
`strconv.atof64('123xyz')` will get error `extra char after number` now.
> fix strconv.atof64(), return error when detect extra char after number

- vlib/v/gen/c/fn.v
- vlib/v/tests/c_function/code.c
- vlib/v/tests/c_function/code_test.c.v
- vlib/v/tests/c_function/v.mod
Fix #23804 (partial fix)
With this patch the code builds on gcc and tcc without `-cstrict`. Because it does not cover the code generating ordering issue.
> cgen: fix array fixed assignment for `@[keep_args_alive]`

- vlib/v/checker/if.v
- vlib/v/checker/match.v
- vlib/v/checker/tests/if_expr_with_none_only.out
- vlib/v/checker/tests/if_expr_with_none_only.vv
- vlib/v/checker/tests/match_expr_with_none_only.out
- vlib/v/checker/tests/match_expr_with_none_only.vv
Fix current crash when using:
```v
fn main() {
a := if true { none } else { none }
}
```
> checker: add missing check for IfExpr and MatchExpr with no valid type

- vlib/v/checker/match.v
- vlib/v/tests/options/option_match_none_test.v
> checker: fix MatchExpr type inferring when `none` is used  

- vlib/veb/tests/veb_test.v
- vlib/veb/tests/veb_test_server.v
- vlib/veb/veb.v
Possible fix for #22464
Currently, if a client sends request with the Content-Length > 0, veb expects some data of the body to be ready after the headers are parsed in the same picoev callback, else it shows an `Eof` error.
It is possible that a client sends the headers first and the body has not been received yet. In this case veb should wait for the connection to provide more data, but it errors. I believe this is what's causing the randomness in the error message.
This pr changes the behaviour to wait for the body data, if the headers are parsed in the same piceov callback (callback that the connection has data available).
> veb: fix "error parsing request: io.Eof" error when a request body is expected, but the data is not ready yet

- vlib/time/format.v
- vlib/time/time.v
- vlib/time/time_test.v
Follow ISO 8601 standard.
Fix issue #23835
> time: add week_of_year()

- vlib/v/gen/c/cgen.v
- vlib/v/tests/options/option_nested_fixed_array_test.v
> cgen: fix codegen for nested option fixed array

- examples/get_raw_line.v
- vlib/builtin/cfns.c.v
- vlib/os/os.c.v
Fix issue #23843
1. read 1 byte/char from file pipe/console every time, and check for `\n` and `Ctrl+Z`.
2. add a `example/get_raw_line.v` as I don't know how to test it.
A discussion can be found at https://github.com/golang/go/commit/610d522189ed3fcf0d298609a248a3283bde62cd
> os: fix get_raw_line() under windows

- vlib/v/gen/c/match.v
- vlib/v/tests/match_on_return_test.v
> cgen: fix codegen for match on return

- vlib/v/checker/fn.v
- vlib/v/checker/tests/generic_fntype_err.out
- vlib/v/checker/tests/generic_fntype_err.vv
> checker: add missing check for generic fntype type names

- cmd/tools/vrepl.v
Fix issue #23856
Because `readline.read_line(prompt)` return a line without the ending `\n`, so remove the checking for `ends_with('\n')`.
This make vrepl response quickly to empty line input (just press `enter` key).
> vrepl: fix empty line input slowly

- vlib/sokol/audio/audio.c.v
This fixes running the Breakout game in #23861 on Android
> sokol, audio: link against `aaudio` on Android

- vlib/time/parse.js.v
- vlib/time/time.js.v
- vlib/time/time.v
This pull request includes several documentation improvements to the `vlib/time` module.
Documentation improvements:
* [`vlib/time/parse.js.v`](diffhunk://#diff-595d96f92385bda52b73dbaa323bb0cfd96e3265ad7b70ada08db75870da7846R22-R26): Added comments to describe the `parse_iso8601` function, explaining its purpose and limitations.
* [`vlib/time/time.js.v`](diffhunk://#diff-a822823433dd7b48150789001d5694674619ac665e7e37348079c16c91cf4b5aR3): Added comments to describe the `now`, `utc`, and `ticks` functions, explaining their return values and behavior. [[1]](diffhunk://#diff-a822823433dd7b48150789001d5694674619ac665e7e37348079c16c91cf4b5aR3) [[2]](diffhunk://#diff-a822823433dd7b48150789001d5694674619ac665e7e37348079c16c91cf4b5aR19) …
> time: add documentation for time-related functions and ISO 8601 parsing

- vlib/v/gen/c/assign.v
- vlib/v/tests/options/option_cast_primitive_test.v
> cgen: fix codegen for casting primitive type to alias where option alias is expected

- vlib/v/checker/assign.v
- vlib/v/checker/checker.v
- vlib/v/checker/fn.v
- vlib/v/checker/struct.v
- vlib/v/gen/c/fn.v
- vlib/v/tests/structs/anon_struct_assign_expr_test.v
Fix #23855
`mut var := struct { ... }`
Makes the anon struct mutable
```v
fn t() int {
return 123
}
fn r(a struct { name string age int }) {
assert '${a}' == "struct {
name: 'Foo'
age: 123
}"
}
mut a := struct {
name: 'Foo'
age:  t()
}
dump(a)
r(a)
r(struct { name: 'Foo', age: t() })
a.age = 2
assert '${a}' == "struct {
name: 'Foo'
age: 2
}"
}
```
> v: implement assignable anon struct

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/testdata/iface_method_order.c.must_have
- vlib/v/gen/c/testdata/iface_method_order.vv
> cgen: fix interface method list ordering to make test buildable with `g++`

- vlib/v/checker/assign.v
- vlib/v/checker/comptime.v
- vlib/v/checker/if.v
- vlib/v/checker/tests/comptime_selector_assign.out
- vlib/v/checker/tests/comptime_selector_assign.vv
- vlib/v/type_resolver/type_resolver.v
> checker: add checking for comptime assign without comptime if checking

- vlib/v/live/executable/reloader.c.v
Fix issue #6936
Now, `-live` work both under Windows and Linux:
```
D:\v\v\v>v -live run examples\hot_reload\message.v
OK reloads:    1 | Total reloads:    1 | Hello! Modify this message while the program is running. app: 48e0fd0 | app.x:      0 | app.counter:      0
OK reloads:    1 | Total reloads:    1 | Hello! Modify this message while the program is running. app: 48e0fd0 | app.x:      0 | app.counter:      1
OK reloads:    1 | Total reloads:    1 | Hello! Modify this message while the program is running. app: 48e0fd0 | app.x:      0 | app.counter:      2
```
```
D:\v\v\v>v -live run examples\hot_reload\message.v -cc msvc
OK reloads:    1 | Total reloads:    1 | Hello! Modify this message while the program is running. app: 1550fd0 | app.x:      0 | app.counter:      0
OK reloads:    1 …
```
> live: add ext(.dll/.so) to output name of -live

- vlib/crypto/ecdsa/ecdsa.c.v
- vlib/crypto/ecdsa/ecdsa.v
- vlib/crypto/ecdsa/util.v
This follow-up PR from the last commited [pr](https://github.com/vlang/v/pull/23876). In this PR, its done by migrating the last bits required to be changed, ie `.bytes()` method on the `PrivateKey` and `PublicKey`.
Its was done by using high level function. All info's of `EVP_PKEY` opaque was already availables on both of them by previous migrations. This series contains the bits forms:
- The changes on `.bytes()` on the both of `PrivateKey` and `PublicKey`
- Adds required definitions
- Some fixs of private and public key loader
After this PR, we can start out to cleanup some deprecated code. Should be this cleanup phase done in gradually step ?
> crypto.ecdsa: the last bits of migration steps

- vlib/v/gen/c/fn.v
- vlib/v/tests/global_init_array_test.v
> cgen: fix codegen for global array passed as mut

- examples/breakout/breakout.v
Small visual tweaks to give the elements a little more depth:
> examples, breakout: add subtle light and shadow effects for feeling of depth

- vlib/crypto/ecdsa/ecdsa.c.v
- vlib/crypto/ecdsa/ecdsa.v
- vlib/crypto/ecdsa/ecdsa_test.v
- vlib/crypto/ecdsa/util.v
After this [PR](https://github.com/vlang/v/pull/23877) has been merged, all info's of high level opaque was already availables on the public and private key object, so, we can start out the removal of the deprecated ec_key opaque.
This PR contains this cleansup step in one-shoot commit.  This cleansup significantly reduces the overall size line of the code, ie,
- `ecdsa.v` file, reduced from 905 lines down to 621 lines
- `ecdsa.c.v` file reduced from 200 down to 172 lines
- `util.v` gets increased from 233 into 247, not too much addition, mostly for checking functionality
- the rest test files remain the same, not changed in the count
This PR contains some bits in the forms of :
- Removes out of `EC_KEY` opaque from definitions and private and public key structure
- Removes out of the …
> crypto.ecdsa: cleans out old deprecated keypair opaque from the module.

- cmd/tools/vdoc/vdoc.v
Locally running `v doc -m -f html -o ./tmpdocs vlib/ && firefox tmpdocs/builtin.html` now results in source links showed:
I'm unsure about how to add a regression test :thinking: 
Maybe we could do an `assert` somewhere if `cfg.is_vlib == true`  :shrug:
> docs, cmd: fix broken docs source links regression in `vdoc`

- vlib/veb/veb.v
fix [the issue in the discord server help channel](https://discord.com/channels/592103645835821068/592294828432424960/1348248565646102569) where cancelling a download prompted by `return ctx.file("filename")` occasionally crashed the program due to a SIGPIPE signal being caught (no github issue for this exists as far as i'm aware)
no test comes with this PR due to the issue being seemingly random(?) and most likely impossible to automate. if needed, create a simple server in veb that serves a file, then repeat the download request, cancelling it each time until the program crashes (which shouldn't happen with this fix)
> veb: handle sendfile errors

- vlib/v/builder/msvc_windows.v
- vlib/v/gen/c/cgen.v
1. Partially fix issue #23888 . If user specify a output name other than `.exe` or `.dll`, the output name will be appended with `.exe` or `.dll`;
2. Remove `msvc` generate temp files.
> builder,cgen: fix msvc build filename, remove temp files

- vlib/crypto/ecdsa/ecdsa.v
After [this PR](https://github.com/vlang/v/pull/23876), The values of `Nid` enum was changed directly into underlying C counterparts, so, technically, the info's about nid of the group passed in options was already availables to the key generator routine.
This PR changes the `PrivateKey.new` method to utilize this information directly in the C call and removes out the `match` branch block to get the nid of the group in the preliminary call.
On my simple benchmark on my test machine, before the patch `PrivateKey.new` gets averages time in 37-40  µs (variesly) in 10.000 iterations, and after the patch, its gets down into 31-34  µs (variesly) with the same number of iterations. Not too bad improvement in small changes
NB:
the benchmark code
```v
import time
import crypto.ecdsa
fn main() { …
```
> crypto.ecda: small bits improvement of the`PrivateKey.new` method

- vlib/crypto/ecdsa/ecdsa.v
The current internal rotine `calc_digest_with_evpkey` call key size calculations step before `match` block.  This key size check only happens when you pass `.with_custom_hash` as an options., so, with default options, this calculation step was not needed in another options.
This PR improves it a bit by moving out this key size calculation step goes down inside `.with_custom_hash` branch of match block. In my benchmark, nothing significantly changes in the number, its only about $\pm$ 5% improvement.
> crypto.ecdsa: improves internal function of `calc_digest_with_evpkey`

- vlib/v/checker/assign.v
- vlib/v/checker/tests/assign_any_err.out
- vlib/v/checker/tests/assign_any_err.vv
> checker: add missing `any` type validation on assignment

- README.md
I didn't see an IDE plugin I needed because the links were split between the list and the paragraph. So I put them all in the list.
> As always, you are welcome to close this or make any edits on top -- no need to ask me.
> docs: combine IDE plugins into one list in README.md

- vlib/crypto/ecdsa/ecdsa.c.v
- vlib/crypto/ecdsa/ecdsa.v
Even after this [PR](https://github.com/vlang/v/pull/23899), `PrivateKey.new` has been improved, overall of `generate_key` routine still has an overhead. In my test, its overhead happens on `.public_key` call. The overhead is about $\pm$ 310  µs (variesly).
After some digs to search the alternative approachs, i test 3 of them, for optimizing `public_key` part
- With the current approach, serializing using `d2i` based function
- Serializing and unserializing with `pem` based approach
- With duplicating key and clears out private info from the key.
With these approach, this is my test number
```bash
Average time using public_key_using_d2i (current)       : 288 µs
Average time using public_key_using_pem                 : 435 µs
Average time using public_key_using_dup_n_set_null      : 5 µs …
```
> crypto.ecdsa: improves performances of `.public_key` call 

- vlib/os/process_windows.c.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/cast_fn_err.out
- vlib/v/checker/tests/cast_fn_err.vv
- vlib/v/checker/tests/mut_arg_different_muls_err.vv
> checker: add fntype casting validations

- vlib/v/checker/checker.v
- vlib/v/checker/tests/cast_generic_err.out
- vlib/v/checker/tests/cast_generic_err.vv
> checker: add missing check for casting generic type to literal values

- vlib/datatypes/linked_list.v
- vlib/datatypes/linked_list_test.v
Fix issue #23928
1. add a field `tail` in `LinkedList[T]`;
2. use `nil` instead of `0`, use `isnil` replace some `unsafe` blocks.
3. add `@[heap]`, `@[inline]`
list.v
```v
module main
import benchmark
fn main() {
mut b := benchmark.start()
mut list := datatypes.LinkedList[int]{}
for i in 0 .. 10_000_000 {
list.push(i)
}
b.measure('list.push')
}
```
```
v -prod list.v
./list
SPENT   777.296 ms in list.push
```
> vlib.datatypes: optimize linkedlist

- vlib/v/ast/str.v
- vlib/v/markused/markused.v
- vlib/v/markused/walker.v
- vlib/v/tests/skip_unused/struct_field_default_expr.vv
> markused: Fix markused behavior on struct field's default expression

- cmd/tools/vast/vast.v
As `v.checker` may modify the AST tree, so introduce a new flag `--check` flag, which default is `false`. If set to `true`, then `vast` will product a checker-modified AST tree.
> vast: add --check flag

- vlib/v/gen/c/fn.v
- vlib/v/tests/generics/generic_array_ret_test.v
- vlib/v/type_resolver/generic_resolver.v
Fix #23916
Fix the array part of the issue. The `typeof()` stuff or map related bug is not handled in this PR.
> cgen: fix codegen for generic structinit and generic array return

- vlib/v/ast/table.v
- vlib/v/tests/consts/const_fixed_array_test.v
> table: fix array fixed symbol registering when size_expr is a const

- vlib/x/json2/scanner.v
- vlib/x/json2/scanner_test.v
- vlib/x/json2/tests/decoder_test.v
- Fix bug where `"\\"` is parsed incorrectly due to closing `` `"` `` requiring no preceding backslash
- Improve error messages for text_scan()
- Make unescaped control characters (ch < 0x20) an error, as per JSON spec.
- Fix decoder_test, '"\u001b"' should be an error, '"\\u001b"' is fine
standalone test:
```v
import x.json2
json2.decode[json2.Any](r'"\\"')!
```
`message: [x.json2] missing double quotes in string closing (0:44)`
from current https://play.vlang.io/
> json2/scanner: fix "\\" parsing bug, disallow (ch < 0x20) unescaped control characters

- vlib/crypto/ecdsa/ecdsa.v
This PR improves `sign_digest`  internal routine used by `PrivateKey.sign` method. Its done by eleminating one step of `C.EVP_PKEY_sign` calls with null signature buffer to know the length (size) of required buffer. This maximal sizes of the buffer was already known by calling `C.EVP_PKEY_size`, so its not needed to call `C.EVP_PKEY_sign` just to know the size of required buffer and we can allocate the buffer instead and call `C.EVP_PKEY_sign` directly  with this allocated buffer.
In my benchmark test, there are small improvements on this part
```v
Benchmarking PrivateKey.sign() (before patch)...
Average PrivateKey.sign() (before patch) time: 37 µs
```
and after patch
```v
Benchmarking PrivateKey.sign() (after patch)...
Average PrivateKey.sign() (after patch) time: 27 µs
```
Thanks
> crypto.ecdsa: improves internal `sign_digest` routine

- vlib/dl/dl_windows.c.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/cmain.v
- vlib/v/gen/c/testdata/closure_shared_lib.c.must_have
- vlib/v/tests/create_dll/create_win_dll.c.v
Fix issue #8313
When create `.dll` under windows, create a default `DllMain()` for it, which will call `_vinit(0, (voidptr)0);` and `_vcleanup();`.
Then we can remove the workaround in `dl.open()` and `dl.close()`
This is helpful when try to create dll can be called by non-v APPs.
> dl: remove workaround; cgen: add DllMain()

- thirdparty/build_scripts/README.md
- thirdparty/build_scripts/thirdparty-linux-amd64_bdwgc.sh
- thirdparty/build_scripts/thirdparty-linux-amd64_tcc.sh
- **thirdparty: add thirdparty/build_scripts/ folder, to streamline CI testing of different versions of tcc and bdwgc**
- **add thirdparty/build_scripts/thirdparty-linux-amd64_bdwgc.sh ; make thirdparty-linux-amd64_tcc.sh stricter**
> thirdparty: add `thirdparty/build_scripts/` to prepare for prebuilt tcc upgrades

- vlib/os/process.c.v
- vlib/os/process_nix.c.v
- vlib/os/process_windows.c.v
Fix issue #23990
1. add `win_is_pending()`;
2.  modify windows stdout pipe / stderr pipe buffer length from 4KB to 64KB, this is the same of Linux version.
> os: windows add is_pending()

- vlib/v/ast/table.v
- vlib/v/ast/types.v
> cgen: fix parallel `cached_type_to_str` access

- vlib/net/udp.c.v
The return signature of `remote/0` is also changed to use an `Option` (`none`) instead of a `Result` (`error('none')`). This oddity is likely a workaround for older versions of V.
> net: make `close/0`, `select/2` and `remote/0` methods of `UdpSocket` `pub`

- vlib/builtin/js/array.js.v
- vlib/strings/builder.c.v
- vlib/strings/builder.js.v
Currently, `strings.Builder` has a function named `clear()` which clears the content by reallocating the backing array.
However, there is no need to reallocate the array. For example, in `str()` function, the backing array is simply trimmed to zero length.
Also, the array type itself has a `clear()` function which does the same as `trim(0)`. This PR reuses the `clear()` function in the `array` by simply removing the `clear()` function in `strings.Builder` and replacing `trim(0)` with `clear()` which does the same thing.
This PR shouldn't break existing code
> strings, builtin: remove `strings.Builder.clear()`, fix `array.clear()` not working in the JS backend

- vlib/v/ast/table.v
- vlib/v/checker/checker.v
- vlib/v/checker/tests/chan_unknown_err.out
- vlib/v/checker/tests/chan_unknown_err.vv
> checker: fix chan elemen type validation with inexistent type

- vlib/x/crypto/chacha20/chacha.v
- vlib/x/crypto/chacha20/chacha_test.v
- vlib/x/crypto/chacha20poly1305/chacha20poly1305.v
This PR fixs the issue related consecutive calls of `xor_key_stream` thats not handled correctly after the first calls. Its issue was reported by @einar-hjortdal . See the issue at [23977](https://github.com/vlang/v/issues/23977). Thank for report the issue.
In this PR, we follow and adapt the go version and also unifies between `chach20_block` and `generic_key_stream` method to single one in the form of `chacha20_block_generic`. Its also adds a test for this consecutive calls issue.
Thanks
> x.crypto.chacha20: fix issue on consecutive calls of `xor_key_stream`

- vlib/gg/draw.c.v
- vlib/gg/testdata/draw_rectangles.vv
The result of:
```v
module main
import gg
import gx
gg.start(
bg_color:     gx.white
window_title: 'Rectangles'
width:        250
height:       100
frame_fn:     fn (ctx &gg.Context) {
ctx.begin()
ctx.draw_rect_filled(10, 10, 10, 10, gx.blue)
ctx.draw_rect_empty(30, 10, 10, 10, gx.red)
ctx.draw_rect_filled(50, 10, 30, 10, gx.green)
ctx.draw_rect_empty(100, 10, 30, 10, gx.black)
ctx.draw_rect_empty(10, 50, 10, 10, gx.blue)
ctx.draw_rect_filled(30, 50, 10, 10, gx.red)
ctx.draw_rect_empty(50, 50, 30, 10, gx.green)
ctx.draw_rect_filled(100, 50, 30, 10, gx.black)
ctx.end()
}
)
```
with this PR on linux (with added guidelines) is:
(the top image is from my GPU, the bottom one is from MESA, rendered with `LIBGL_ALWAYS_SOFTWARE=1`)
on macos, it is (with added guidelines):
In both cases …
> gg: make draw_rect_empty/5 draw more exact borders, independent of the device, and fitting the draw_rect_filled/5 shapes

- vlib/v/gen/c/cgen.v
- vlib/v/parser/parser.v
- vlib/v/slow_tests/assembly/asm_test.arm64.v
1. fix issue #24014
2. fix imm in `arm64` as it starts with `#` not `$`
3. fix parser support `arm64` dot instructions, such as `b.le`
4. fix issue #24015
> cgen,parser: fix arm64 asm operand position; fix arm64 asm imm; support arm64 dot instruction

- vlib/v/gen/c/cmain.v
- vlib/v/tests/test_global_init_test.v
> cgen: allow asserts inside fn calls on const/global initialization in test files

- vlib/v/parser/parser.v
- vlib/v/tests/options/option_last_call_test.v
> cgen: fix codegen for option return unwrapping on last statement

- vlib/sync/pool/pool.c.v
- vlib/v/gen/c/assign.v
This PR fixes a race spotted by *Helgrind* running on same repo used on issue #23980
```
==12656== Possible data race during read of size 8 at 0xAAC5A20 by thread #1
==12656== Locks held: none
==12656==    at 0x4D0DFB: sync__pool__PoolProcessor_get_results_ref_T_v__gen__c__Gen (pool.c.v:152)
==12656==    by 0x740243: v__gen__c__gen (cgen.v:388)
==12656==    by 0x8AC1BC: v__builder__cbuilder__gen_c (cbuilder.v:80)
==12656==    by 0x8ABD84: v__builder__cbuilder__build_c (cbuilder.v:60)
==12656==    by 0x8ABBDC: v__builder__cbuilder__compile_c (cbuilder.v:50)
==12656==    by 0x8AA3AD: v__builder__Builder_rebuild (rebuilding.v:325)
==12656==    by 0x8A1281: v__builder__compile (compile.v:17)
==12656==    by 0x8B14B2: main__rebuild (v.v:193)
==12656==    by 0x8B09FE: main__main (v.v:151) …
```
> sync: fix race on poolprocessor

- vlib/x/crypto/chacha20/chacha.v
- vlib/x/crypto/chacha20/chacha_test.v
- vlib/x/crypto/chacha20/xchacha.v
- vlib/x/crypto/chacha20/xchacha_test.v
This small PR acts as a preliminary step  in trying to add support for 64-bit counters to the `x.crypto.chacha20` module.
Currently, the `x.crypto.chacha20` module only supports for standard IETF variant which only support for 32-bit counters, and does not yet support for 64-bit counters.
This PR only contains some small cleans up by cleaning out some wrappers to simplify future works.
Thanks
> `x.crypto.chacha20`: Small cleans up as preliminary works to support 64bit counter

- vlib/x/crypto/chacha20/chacha.v
Related to this [issues](https://github.com/vlang/v/issues/23904), here is the plan to add support for original ChaCha20 stream cipher with 64 bit counter. 
- The changes was needed to the internal `chacha20.Cipher` representation (was done in this PR). Its changed to the raw 128 bytes of```[4]u32``` opaque where the counter was contained internally and handles transparently.  Previously, its separated in the `nonce` and `counter` of the `Cipher` field's.
- Adding 64 bit counter handling and related keystream generation that aware of new size of counter (not ready)
- Make stream cipher creation support for 64-bit counter variant. Its partially was done in this PR, but still not fully supported.
- Make `xor_key_stream` and other routines awares for 64-bit counter variant
- Adds 64-bit …
> x.crypto.chacha20: changes internal cipher representation to support 64 bit ctr

- vlib/crypto/sha3/sha3_state_generic.v
And as a result of these change, the results of sha3 will be the same across all systems, including s390x.
> crypto.sha3: be big-endian friendly

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/if.v
- vlib/v/tests/options/option_match_case_test.v
> cgen: fix match option with case non option

- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/profile.v
Adds a new column to the profiler output: time spent in the current function without the time spent in its children
Known problem: for multithreaded programs the time calculations are wrong and might show negative times.
Sample profiling output:
```
1          0.034ms          0.007ms          34003ns rand__init
1560          2.501ms          0.959ms           1603ns rand__PRNG_u32n
1560          3.264ms          0.443ms           2092ns rand__PRNG_intn
1560          4.015ms          0.432ms           2574ns rand__PRNG_int_in_range
3120          1.064ms          0.419ms            341ns rand__PRNG_f64
3120          2.355ms          0.678ms            755ns rand__PRNG_f64n
3120          3.686ms          0.697ms           1181ns rand__PRNG_f64_in_range
1          0.014ms          0.001ms …
```
> profile: new column for time of the function without the time of its children functions

- vlib/v/parser/comptime.v
> parser: fix `$dbg` on function that uses veb comptimecall

- vlib/v/checker/orm.v
- vlib/v/gen/c/orm.v
- vlib/v/tests/orm_type_alias_test.v
Corollary to #15478, which fixes the type alias support for db type, this commit allows the use of an alias to a supported type in a column.
The fix is mainly replacing `field.typ` occurrences with `table.final_type(field.typ)` or equivalent.
Example use:
```
type CountryCode = string
@[table: 'addresses']
pub struct Address {
id      int @[primary; sql: serial]
name    string
address string
country CountryCode
}
// …
sql db {
create table Address
} or { panic("don't panic!") }
```
Created as a draft because all comments welcome and and tests / doc not yet written because of this.
> orm: fix type alias not supported in table columns

- vlib/v/gen/c/assert.v
- vlib/v/tests/skip_unused/assert_works_test.run.out
- vlib/v/tests/skip_unused/assert_works_test.skip_unused.run.out
- vlib/v/tests/skip_unused/assert_works_test.vv
> cgen: fix showing the expression as literal value in case of `assert s[x..y] == "literal"` (fix #24103)

- vlib/v/ast/types.v
- vlib/v/gen/c/cheaders.v
- vlib/v/gen/c/comptime.v
- vlib/v/pref/arch.c.v
New architecture: s390x.
97% tests passed in `vlib/v/tests`.
Additional efforts will be required to bring everything to proper functioning inside `vlib` dir too.
`Whats next:`
Inline assembly basically works and will require some more tests. It will be a different PR.
> new architecture: s390x

- vlib/v/gen/c/fn.v
- vlib/v/gen/c/infix.v
- vlib/v/tests/options/option_unwrapped_arg_generic_opt_test.v
> cgen: fix codegen for option unwrapped var passed to generic option type

- vlib/v/checker/if.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/loops/for_smartcast_test.v
- vlib/v/tests/options/option_if_unwrap_test.v
- vlib/v/tests/options/option_ptr_unwrap_test.v
- vlib/v/tests/options/option_struct_init_with_ref_opt_test.v
- vlib/v/type_resolver/comptime_resolver.v
> checker, cgen: fix selector option unwrapping on infix

- vlib/crypto/rc4/rc4.v
if x.crypto.chacha20 new_cipher returns `!&Cipher`, then all new_cipher functions that return a cipher.Stream implementation should return a reference for consistency.
From [here](https://github.com/einar-hjortdal/firebird/blob/8420b91899fc21608c2a691a50c75ac185d03ecc/src/protocol_channel.v#L13)
```v
struct WireChannel {
mut:
conn          &net.TcpConn
reader        &io.BufferedReader
writer        &io.BufferedWriter
plugin        string
crypto_reader &cipher.Stream
crypto_writer &cipher.Stream
}
fn (mut c WireChannel) set_crypt_key(plugin string, session_key []u8, nonce []u8) ! {
c.plugin = plugin
match plugin {
chacha20_64_plugin_name, chacha20_32_plugin_name {
mut digest := sha256.new()
digest.write(session_key)!
key := digest.sum([]u8{})
c.crypto_reader = chacha20.new_cipher(key, …
```
> crypto.rc4: new_cipher should return a reference to the Cipher for consistency with other ciphers

- vlib/db/mysql/mysql_orm_test.v
- vlib/db/mysql/orm.c.v
Fix the issue in `mysql_orm_test.v`.
for example:
```v
struct TestTimeType {
mut:
id         int @[primary; sql: serial]
username   string
created_at time.Time @[sql_type: 'DATETIME']
updated_at string    @[sql_type: 'DATETIME']
deleted_at time.Time
}
```
The field `updated_at` has a orm type of `string`, but in mysql db, it is a `DATETIME`, and it should not use dynamically allocation.
> db.mysql: use mysql datatype for alloc string_binds_map, not orm's

- vlib/db/mysql/mysql.c.v
- vlib/db/mysql/mysql_orm_test.v
- vlib/db/mysql/orm.c.v
- vlib/db/mysql/stmt.c.v
Fix issue #24130
This PR will check fetched field is `NULL` or not.
If the field is `NULL`, it will return `orm.Null{}` to `orm`, avoid use the old value stored in field.
> db.mysql: add null result support

- vlib/v/ast/ast.v
- vlib/v/gen/c/cgen.v
- vlib/v/slow_tests/assembly/asm_test.s390x.v
My attempt to add s390x assembly.
Highlights:
- Intel syntax
- I tried creating asm in C code and gcc only accepted integer literals as naked 5
- The test file is copied from a neighboring file. Not bad for a start
> add s390x assembly support + test

- vlib/v/ast/ast.v
- vlib/v/ast/comptime_const_values.v
- vlib/v/checker/checker.v
- vlib/v/gen/c/cgen.v
- vlib/v/parser/containers.v
- vlib/v/tests/interfaces/interface_arr_init_test.v
> parser,checker,cgen: fix wrong auto heap deref of auto `index` loop var

- vlib/os/file.c.v
- vlib/v/checker/fn.v
- vlib/v/checker/struct.v
- vlib/v/checker/tests/struct_void_field_err.out
- vlib/v/checker/tests/struct_void_field_err.vv
- vlib/v/checker/tests/struct_voidptr_field_init_err.out
- vlib/v/gen/c/cgen.v
> checker, cgen: fix non-voidptr to voidptr on `-cstrict` + notice about such usage

- vlib/encoding/iconv/iconv_nix.c.v
This PR fixes `encoding.iconv` on termux.
Before:
```
$ v doctor
cannot compile `/data/data/com.termux/files/home/.vlang/cmd/tools/vdoctor.v`: 1
ld.lld: error: undefined symbol: libiconv_open
>>> referenced by iconv_nix.c.v:42 (vlib/encoding/iconv/iconv_nix.c.v:42)
>>>               /data/data/com.termux/files/usr/tmp/vdoctor-72962e.o:(encoding__iconv__conv)
ld.lld: error: undefined symbol: libiconv
>>> referenced by iconv_nix.c.v:54 (vlib/encoding/iconv/iconv_nix.c.v:54)
>>>               /data/data/com.termux/files/usr/tmp/vdoctor-72962e.o:(encoding__iconv__conv)
ld.lld: error: undefined symbol: libiconv_close
>>> referenced by iconv_nix.c.v:46 (vlib/encoding/iconv/iconv_nix.c.v:46)
>>>               /data/data/com.termux/files/usr/tmp/vdoctor-72962e.o:(encoding__iconv__conv)
>>> …
```
> encoding.iconv: add path to libiconv on termux

- vlib/v/ast/cflags.v
- vlib/v/ast/cflags_test.v
Fix issue #24121
Parse cflags like '-I/usr/include/mysql -m64 -I/usr/include', if the first flag is in `allowed_flags`, it will treat all before next `allowed_flags` as a value, which is not correct. The old code will create `name=-I`, `value=/usr/include/mysql -m64`.
> ast: fix parse_cflag() support other flags between allowed_flags

- .github/workflows/s390x_linux_ci.yml
- vlib/os/os_test.c.v
- **ci: add a small s390x testing job (a big endian system)**
- **add a base_image: tag**
- **install make and gcc first**
- **add githubToken: and shell: tags**
- **remove `file ./v` command, since `file` is not installed**
- **install file, coreutils and binutils as well**
- **use --no-install-recommends for the apt-get command**
- **remove --no-install-recommends**
- **test also vlib/os and vlib/encoding/binary**
- **os: fix os_test.c.v for QEMU s390x**
- **cleanup**
> ci: add s390x runner (using QEMU), for the tests in `builtin`, `os`, and `encoding.binary`

- vlib/sync/sync_darwin.c.v
- vlib/sync/sync_default.c.v
- vlib/sync/sync_freebsd.c.v
During the porting of `vlang` to `NetBSD`, it was discovered that `pthread_rwlockattr_setpshared()` is hidden, and `PTHREAD_PROCESS_PRIVATE` is actually the default value in all systems.
Let's remove it completely and save `NetBSD`.
[FreeBSD 14](https://man.freebsd.org/cgi/man.cgi?query=pthread_rwlockattr_setpshared&apropos=0&sektion=3&manpath=FreeBSD+14.2-RELEASE&arch=default&format=ascii)
[MacOS 15](https://man.freebsd.org/cgi/man.cgi?query=pthread_rwlockattr_setpshared&apropos=0&sektion=3&manpath=macOS+15.0&arch=default&format=ascii)
[POSIX](https://linux.die.net/man/3/pthread_rwlockattr_setpshared)
[GNU Lib](https://www.gnu.org/software/gnulib/manual/html_node/pthread_005frwlockattr_005fsetpshared.html)
> sync: remove pthread_rwlockattr_setpshared

- GNUmakefile
This is next step for porting `vlang` to `NetBSD`.
Tested on `NetBSD 10` so far, my goal is working `vlang` on `NetBSD 8-10` out of box.
> GNUmakefile: add initial NetBSD support

- vlib/term/termios/termios_netbsd.c.v
- vlib/v/pkgconfig/pkgconfig.v
Main step for NetBSD build:
- `-d dynamic_boehm` and static builds;
- tested on `NetBSD 8-10`;
- gate for `sparc64` support is open.
> pkgconfig, termios: NetBSD support

- vlib/v/checker/checker.v
> markused: fix for gated index range on string

- vlib/orm/orm_func.v
- vlib/orm/orm_func_test.v
This PR fix PR #24222
For struct option fields with default values, a `null` in database field should update the struct's field to `none`, not it's default value.
```v
@[table: 'sys_users']
struct UserPart {
id         int @[primary; serial]
created_at time.Time @[sql_type: 'TIMESTAMP']
updated_at time.Time @[sql_type: 'TIMESTAMP']
option_i8	?i8 = 13		// option with default test
option_string ?string = 'this is not none'
}
```
for example, if database field `option_i8`, `option_string` are `null`, then these fields should set to `none`, not their default values.
> orm: fix option field with default null value

- examples/build_system/.gitignore
- examples/build_system/build.vsh
- examples/build_system/main.v
- vlib/build/README.md
- vlib/build/build.v
This PR introduces a small `build` module into the Vlib, based on the API in [Clockwork](https://github.com/emmathemartian/clockwork). It's not quite 1:1 but is still similar.
I am seeking feedback, just leave a comment here if you have any!
This PR will remain a draft while I am receiving feedback, once I feel like it's in a more comfortable state then I will un-draft it.
> build,examples: add build system

- vlib/v/fmt/tests/import_multiple_imports_at_one_line_expected.vv
- vlib/v/fmt/tests/import_multiple_imports_at_one_line_input.vv
- vlib/v/parser/parser.v
> parser: fix mutiple imports at one line

- doc/docs.md
Step 1 for removing `any` from V.
> doc: remove reference to `any` type

- vlib/v/tests/assign/assert_with_array_ref_test.v
Make this work on big_endian systems too.
Tested on `both` versions of Alpine.
> make this test work on s390x too

- vlib/v/tests/trace_calls_test.v
- vlib/v/trace_calls/tracing_calls_d_musl.v
Latest supported `Alpine Linux` version is 3.18.12, it have `gettid()` in manual pages.
Now test is broken, lets make it work. Tested on latest 3.21.3
```
94cc75377785:~/v/vlib# ../v test v/tests/trace_calls_test.v
FAIL  5033.210 ms /root/v/vlib/v/tests/trace_calls_test.v
> trace_fns_only_println compilation output:
================== C compilation error (from cc): ==============
cc: /tmp/v_0/tsession_4002904cc0_01JRYX8ABNH5HRE009SG5GQZVM/single_println.01JRYX8FW0CN09699MYB2GPFW8.tmp.c:2120:31: error: conflicting types for 'gettid'; have 'u32 *(void)' {aka 'unsigned int *(void)'}
cc:  2120 | VV_EXPORTED_SYMBOL VWEAK u32* gettid(void); // exported fn …
```
> now musl have gettid()

- vlib/flag/flag_to.v
- vlib/net/websocket/message.v
This PR fixes a typo in the flag module where the word "occurrences" was misspelled as "occurences" (missing an "r") in several trace_print messages. Also highlights the "payload" keyword in a websocket module comment.
> flag,net.websocket: fix typos in errors, traces and comments

- vlib/orm/orm_func.v
- vlib/orm/orm_func_test.v
1. Fix issue #24244
2. Add `or_where()` help create an or where clause.
> orm: add or_where() method to the builder

- vlib/v/gen/js/js.v
- vlib/v/gen/js/tests/testdata/match.out
- vlib/v/gen/js/tests/testdata/match.v
This commit fixes a bug in the JavaScript code generator where array types in sum type match expressions were not being properly checked. The issue was that the generated code was checking if array elements were instances of the array type itself, rather than the element type of the array.
Fixes #24237
> js: fix array type checking in sum type match expressions (fix #24237 )

- vlib/v/gen/c/array.v
- vlib/v/tests/fixed_array_init_with_init_test.v
> cgen: fix codegen for fixed array init with init using structinit

- vlib/v/checker/checker.v
- vlib/v/checker/tests/no_heap_struct.out
- vlib/v/checker/tests/stack_var_check_err.vv
> checker: fix stack var outside usage when var is a mutable param

- vlib/log/log.v
- vlib/log/log_test.v
This PR enable `log` to set log time in local time or utc time(default).
ll.v
```v
module main
import log
fn main() {
mut l := log.Log{}
l.set_time_format(.tf_default)
l.info('utc time')
l.set_local_time(true)
l.info('local time')
}
```
run :
```
$ ./ll
2025-04-19 06:47 [INFO ] utc time
2025-04-19 14:47 [INFO ] local time
```
> log: add local time / utc time selection support

- vlib/v/util/version/version.v
Fix vlang/v#24263
**Tests OK on Linux Debian/testing**
- build from Git repository commit 11e25bc9ea30ffde14bcd51d79ced465e3dcb4e2 (`VCURRENTHASH` defined)
```sh
$ git clone https://github.com/vlang/v
$ cd v
$ make
(...)
$ ./v version
V 0.4.10 11e25bc
$ ./v -v version
V 0.4.10 11e25bc9ea30ffde14bcd51d79ced465e3dcb4e2.11e25bc
```
- build from 0.4.10 sources (`VCURRENTHASH` not defined)
```sh
$ wget https://github.com/vlang/v/archive/refs/tags/0.4.10.tar.gz -O v-0.4.10.tar.gz
$ wget https://github.com/vlang/vc/archive/66ea39be2275ac723225b9ca99d51ec1212c640d.tar.gz -O vc-66ea39be2275ac723225b9ca99d51ec1212c640d.tar.gz
$ tar xzvf v-0.4.10.tar.gz
$ tar xzvf vc-66ea39be2275ac723225b9ca99d51ec1212c640d.tar.gz
$ cd v-0.4.10
$ mv ../vc-66ea39be2275ac723225b9ca99d51ec1212c640d ./vc
$ make local=1 …
```
> v.util.version: fix output when VCURRENTHASH not defined

- vlib/v/gen/c/consts_and_globals.v
- vlib/v/gen/c/testdata/const_init_or_block.c.must_have
- vlib/v/gen/c/testdata/const_init_or_block.vv
> cgen: fix missing braces for const init with castexpr from option unwrapping expr

- vlib/v/parser/expr.v
- vlib/v/tests/range_expr_logical_and_test.v
> parser: fix range expr precedence on compound logical and operator

- vlib/v/checker/containers.v
- vlib/v/checker/fn.v
- vlib/v/checker/tests/deprecate_any.out
- vlib/v/checker/tests/deprecate_any.vv
> checker: add deprecate notice for `any` arg, prevent `any` from being used as map key,value or array type (currently crashing)

- vlib/v/ast/types.v
- vlib/v/gen/c/cheaders.v
- vlib/v/gen/c/comptime.v
- vlib/v/pref/arch.c.v
Initial `ppc64le` support. Works in `qemu`, needs hardware testing.
Highlights:
- no stack frame(s)
- thunk uses 1 floating point register
- all `vlib/v/tests` and all `*closure*_test.v` passed
- full bootstrap tested on `Debian` (POWER10) and `Alma` (POWER9)
- `wiki` page will be later
- assembler support will be later
> v: add initial support for ppc64le

- vlib/v/gen/c/cgen.v
- vlib/v/tests/index_on_loop_test.v
> cgen: fix codegen for indexexpr on for loop with branchstmt

- vlib/v/parser/parser.v
- vlib/v/tests/if_elseif_else_test.v
> parser: fix wrong string parsing 

- vlib/v/gen/c/cgen.v
- vlib/v/tests/fns/return_multi_aliased_fixed_array_test.v
Fix second bug case posted at #24280
> cgen: fix codegen for multi return with aliased fixed array

- vlib/v/ast/ast.v
- vlib/v/gen/c/cgen.v
- vlib/v/slow_tests/assembly/asm_test.ppc64le.v
> cgen,ast: add ppc64le assembly support + test

- vlib/rand/rand.c.v
- vlib/rand/rand.v
- vlib/rand/random_identifiers_test.v
- vlib/rand/random_numbers_test.v
> rand: add uuid_v7(), session function, simplify uuid_v4()

- vlib/v/gen/js/fn.v
- vlib/v/gen/js/tests/callback.v
- Modified `fn.v` and check if the callback expression is a field
- Added `callback.v` test
> js: fix callback passed as params (fix #24260)

- vlib/v/gen/c/array.v
- vlib/v/tests/concurrency/thread_wait_ptr_test.v
> cgen: fix codegen for thread.call() on var auto heap

- vlib/toml/checker/checker.v
- vlib/toml/tests/quoted_string_crlf_test.v
> toml: fix crlf escape check

- vlib/v/gen/c/cheaders.v
- vlib/v/gen/c/comptime.v
Highlights:
o) dev&test on Alpine
o) all closure works
o) `vlib/v/tests/` all passed too
> v: add initial support for loongarch64

- vlib/builtin/string.v
- vlib/builtin/string_test.v
function to check if a string is a valid identifier (starts with letter/underscore, followed by letters, digits, or underscores)
> builtin: add string is_identifier()

- vlib/compress/szip/szip.c.v
- vlib/compress/szip/szip_test.v
> szip: don't panic on empty files

- doc/docs.md
- vlib/stbi/stbi.c.v
- updates profiler documentiation for the new fourth column
- adds a description to the unclear comp argument. It was described somewhere in the C library but not close to the C functions
> doc: multithread compatible profiler, stib comp arg

- vlib/os/os.c.v
Fix #24356
If not set `code`,  `error_win32()` will call `C.GetLastError()` again and get a zero value.
> os: fix windows rmdir GetLastError()

- vlib/x/crypto/chacha20/chacha.v
- vlib/x/crypto/chacha20/chacha_64bitctr_test.v
This small PR contains two small fix,
1. The first part was adding check into `.set_counter` routine, especially in standard variant where its only allowing 32bit counter values.
2. The second fixs the warning when run the test of `chacha_64bitctr_test` with `-cstrict` options, would lead into  `error: integer constant is so large that it is unsigned [-Werror]` because counter was defined as `int` before changes.
Thanks
> x.crypto.chacha20: add a check counter overflow to set_counter

- cmd/tools/vtimeout.v
> vtimeout: rewrite

- cmd/tools/vreduce.v
- uses breadth first search instead of depth first search
> tools: vreduce: breadth first search

- vlib/v/gen/c/cheaders.v
This PR will enable `tcc_backtrace()` compile support for custom `tcc` under Windows.
```
D://v//v//v//vlib//builtin//backtraces.c.v:16: error: implicit declaration of function 'tcc_backtrace'
builder error:
C error found. It should never happen, when compiling pure V code.
This is a V compiler bug, please report it using `v bug file.v`,
or goto https://github.com/vlang/v/issues/new/choose .
You can also use #help on Discord: https://discord.gg/vlang .
```
> cgen:enable windows tcc_backtrace() support

- vlib/v/tests/fns/closure_test.v
Every CPU arch have `closure` implemented.
Enable good tests.
> tests: enable closure_test.v for every CPU arch

- cmd/tools/vreduce.v
- make a save at each big step, in case the user does not want to wait more
- timeout option now kills all the children processes, to avoid children leaks when using `v run file.v` with timeout option
> tools: vreduce: more frequent saves, fix timeout leaks

- vlib/v/parser/struct.v
- vlib/v/parser/tests/struct_with_empty_pub_mut_section.vv
Fix #24404 .
- **ci: reduce false positives for init_global_test.v on windows (retry it 2 times)**
- **ci: reduce false positives for orm_func_test.v on windows (retry it 2 times)**
- **parser: fix panic for `struct Abc { pub mut: }`**
> parser: fix panic for `struct Abc { pub mut: }`

- cmd/tools/vdoctor.v
Fix #24419
---
**Tests OK** on Linux Debian with build from 0.4.10 sources + patch for `cmd/tools/vdoctor.v`
```sh
$ wget https://github.com/vlang/v/archive/refs/tags/0.4.10.tar.gz -O v-0.4.10.tar.gz
$ wget https://github.com/vlang/vc/archive/66ea39be2275ac723225b9ca99d51ec1212c640d.tar.gz -O vc-66ea39be2275ac723225b9ca99d51ec1212c640d.tar.gz
$ tar xzvf v-0.4.10.tar.gz
$ tar xzvf vc-66ea39be2275ac723225b9ca99d51ec1212c640d.tar.gz
$ cd v-0.4.10
$ mv ../vc-66ea39be2275ac723225b9ca99d51ec1212c640d ./vc
Apply patch for cmd/tools/vdoctor.v (function git_info)
$ make local=1 prod=1
Using local vc
Using local tcc
The executable './thirdparty/tcc/tcc.exe' does not work.
cc  -std=gnu99 -w -o v1 ./vc/v.c -lm -lpthread  || cmd/tools/cc_compilation_failed_non_windows.sh
./v1 -no-parallel -o v2 -prod …
```
> tools: add check for Git repository in v doctor

- vlib/x/json2/decoder2/decode.v
- vlib/x/json2/decoder2/tests/old_json_compatibility/json_decode_struct_default_test.v
```v
import x.json2 as json
import x.json2.decoder2
struct Bar {
b []int = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
}
struct Foo {
Bar
a []int = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
}
str := json.encode(Foo{})
assert decoder2.decode[Foo](str)!.str() == 'Foo{
Bar: Bar{
b: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
}
a: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
}'
}
```
> x.json2.decoder2: fix array decoding in struct is field, when array is initialized

- vlib/v/gen/c/auto_eq_methods.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/infix.v
- vlib/v/tests/interfaces/interface_edge_cases/fn_returning_voidptr_casted_as_interface_test.v
- vlib/v/tests/interfaces/interface_nil_cmp_test.v
- vlib/v/tests/structs/struct_init_with_interface_pointer_and_embed_test.v
> cgen: fix interface `unsafe {nil}` comparison and initialization

- cmd/tools/vdoctor.v
glibc not available on FreeBSD
**Tests OK on FreeBSD 14.2**
```sh
$ ./v doctor
|V full version      |V 0.4.10 dd859eae55cf4e69346851fe285b9af104c8ffb7.bab0441
|:-------------------|:-------------------
|OS                  |freebsd, 14.2-RELEASE-p1, FreeBSD 14.2-RELEASE-p1 GENERIC
|Processor           |4 cpus, 64bit, little endian
|Memory              |0.62GB/0.97GB
|                    |
|V executable        |/home/fox/dev/vlang.git/v
|V last modified time|2025-05-06 13:32:11
|                    |
|V home dir          |OK, value: /home/fox/dev/vlang.git
|VMODULES            |OK, value: /home/fox/.vmodules
|VTMP                |OK, value: /tmp/v_1000
|Current working dir |OK, value: /home/fox/dev/vlang.git
|                    |
|Git version         |git version 2.48.1
|V git status …
```
> Fix v doctor output on FreeBSD, do not run ldd to get glibc version

- vlib/v/gen/js/js.v
- vlib/v/gen/js/tests/array.v
> jsgen: fix array initialization with "index" and "it" (fix #24397)

- doc/docs.md
- vlib/v/ast/comptime_valid_idents.v
A similar commit was already made for `s390x`. It's time for `ppc64le`.
> comptime: enable ppc64le + docs

- vlib/runtime/free_memory_impl_openbsd.c.v
It's more accurate to use `sysctl` with `uvmexp` struct (statistics about the UVM memory management system) to get pagesize and free pages, than using calls to `C.sysconf`.
See [OpenBSD uvm/uvmexp.h](https://github.com/openbsd/src/blob/master/sys/uvm/uvmexp.h) include file for definition of `uvmexp` struct.
**Tests OK on OpenBSD current/amd64**
`get_free_memory.v`:
```v
// Get free memory (vlib/runtime/free_memory_impl*.c.v)
import os
import runtime
fn main() {
println('OS: ${os.user_os()}')
total := runtime.total_memory()
free := runtime.free_memory()
println('total memory: ${total}')
println('free  memory: ${free}')
}
```
```sh
$ ./v run ~/tmp/get_free_memory.v 
OS: openbsd
total memory: 4278042624
free  memory: 1475702784
```
> runtime: improve free_memory implementation for OpenBSD

- vlib/v/ast/ast.v
- vlib/v/ast/types.v
- vlib/v/gen/c/cgen.v
- vlib/v/parser/parser.v
- vlib/v/pref/arch.c.v
- vlib/v/slow_tests/assembly/asm_test.loongarch64.v
I just wanted to add support for `loongarch64` assembly and accumulated so many changes.
If needed, I can split this into different PRs.
Highlights:
o) `ast.AsmRegister` part - 90% of the time was spent proving that everything works exactly as intended.
Did reverse engineering of the parser to find asm inline code lines that check and work for this architecture.
o) in this architecture, assembly instructions also have `dots`.
o) test file is simple.
o) the rest is trivial and was based on my similar previous patches.
o) developed and tested on x64 and loongarch64 under Alpine on qemu.
> ast,cgen,parser,pref: enable loongarch64 assembler + test

- vlib/toml/toml.v
fixes #24435 ... kind of. The C error should still be fixed somehow IMO and maybe the MRE in #24435 is actually valuable. I can reproduce something similar with e.g. (without importing `toml`):
```v
module main
type Any = string | int
fn (a Any) to_toml() string {
return match a {
string {
'TOML string'
}
int {
'TOML int'
}
}
}
fn (m map[string]Any) to_toml() string {
mut t := ''
for _, v in m {
t += v.to_toml() + ','
}
return t
}
fn main() {
mut doc := map[string]Any{}
doc['key'] = Any('value')
// Try to encode it - this is where the bug occurs
toml_content := encode(doc)
println(toml_content)
}
fn encode[T](typ T) string {
$for method in T.methods {
$if method.name == 'to_toml' {
return typ.$method()
}
}
mp := encode_struct[T](typ)
return mp.to_toml()
}
fn encode_struct[T](typ T) …
```
> toml: add compile error when passing `encode/1` types of T != struct

- vlib/runtime/free_memory_impl_openbsd.c.v
In my previous commit https://github.com/vlang/v/commit/656afa9d1380abd037e00d6b9ce43726f7981de6, error in cast (usize) to get free memory on OpenBSD.
**Tests OK on OpenBSD current/amd64**
Code to illustrate this error with cast: `get_free_mem.c.v`
```go
#include <sys/sysctl.h>
#include <uvm/uvmexp.h>
struct C.uvmexp {
pagesize int
free int
}
fn main() {
mib := [C.CTL_VM, C.VM_UVMEXP]!
mut uvm := C.uvmexp{0, 0}
mut len := sizeof(C.uvmexp)
unsafe { C.sysctl(&mib[0], mib.len, &uvm, &len, C.NULL, 0) }
println('uvm.pagesize = ${usize(uvm.pagesize)}')
println('uvm.free = ${usize(uvm.free)}')
free_mem := usize(uvm.pagesize) * usize(uvm.free)
println('free mem = ${free_mem}')
// Error with cast to usize (int * int)
free_mem_1 := usize(uvm.pagesize * uvm.free)
println('free mem_1 = …
```
> runtime: fix cast error in free_memory implementation for OpenBSD

- vlib/v/ast/table.v
- vlib/v/tests/consts/const_depend_update_expr_test.v
> cgen: fix const declaration dependant mapping when using update_expr

- vlib/v/slow_tests/assembly/asm_test.amd64.v
A good and important test that didn't work at all and returned garbage.
I decided to fix it in this batch while minimally touching everything else.
Now everything is ok and the result will always start with a capital letter.
> slow_tests: fix good broken test

- vlib/v/gen/c/assign.v
- vlib/v/tests/assign/assign_mut_for_var_test.v
> cgen: fix assign from mut `for` variable to pointer

- vlib/v/gen/js/builtin_types.v
- vlib/v/gen/js/js.v
- vlib/v/gen/js/tests/unsafe.v
Fixes #24407, #24436
- Use `assert` instead of `JS.console.log`
- Use declared `nil__` constant instead of `null`
> jsgen: cannot assign unsafe nil values (fix #24407, #24436)

- vlib/v/slow_tests/assembly/asm_test.amd64.v
Lets fix this warning too.
```
cpuid.c: In function 'main__Manu_str':
cpuid.c:5941:33: warning: initialization of 'u8 *' {aka 'unsigned char *'} from incompatible pointer type 'main__Manu *' [-Wincompatible-pointer-types]
5941 |         return ((string){.str = m, .len = 12, .is_lit = 1});
|                                 ^
cpuid.c:5941:33: note: (near initialization for '(anonymous).str')
```
> slow_tests: use strict pointer casting in asm_test.amd64.v

- vlib/v/checker/fn.v
- vlib/v/tests/generics/generic_array_pass_test.v
> checker: fix generic option array arg passing to `[]T`

- cmd/tools/modules/testing/common.v
To transform an absolute path into a relative one, you need to remove the `root` only at the beginning of the path, not everywhere.
I'm curious how this will work in `CI`.
> vtest: remove ts.vroot only from beginning of the path (fix #24363)

- vlib/term/ui/termios_nix.c.v
- vlib/term/ui/termios_nix_test.v
There are some cases I've encountered when running a V terminal/TUI application where the host does not respond with actual cursor position data when requested. If this occurs we get an OOB panic, even if the TUI application doesn't need or care what the current cursor position is.
This very simple PR just adds an additional check to prevent an OOB based panic/fatal crash and also includes a test to demonstrate that this is working as expected.
> term/ui: fix fatal from missing cursor pos resp

- vlib/math/big/big_test.v
- vlib/math/big/integer.v
"Bitwise complement" is like `~` but for math.big.
Complete test coverage of edge cases + tested against `mpz_com()` from `libgmp` on 1B loop.
> math.big: new function com() + tests

- vlib/v/util/version/version.v
- `vhash()` function returns full hash (`C.V_COMMIT_HASH`) ; length = 50, see `v/util/version/version.c.v`
- `vcurrent_hash() `returns short form (length = 7)
**Tests OK** on Linux Debian/testing
With a clean Git worktree (`C.V_COMMIT_HASH == vcurrent_hash()`)
```sh
$ ./v version
V 0.4.10 b9fe26c
$ ./v -v version
V 0.4.10 b9fe26cbf18c746256414ae7a6d09cd80b4fa61d
```
With a dirty Git worktree (`C.V_COMMIT_HASH != vcurrent_hash()`)
```sh
$ ./v version
V 0.4.10 8877fe2
$ ./v -v version
V 0.4.10 b9fe26cbf18c746256414ae7a6d09cd80b4fa61d.8877fe2
```
> v.util.version: fix output for V full version

- vlib/math/big/big_test.v
- vlib/math/big/integer.v
The `+` function has incorrect `sign` management and cannot pass the new test.
The new version also passes the 1M loop test against `libgmp`.
> math.big: fix sign machinarium in .+/2 function, add test

- vlib/os/debugger_openbsd.c.v
Check if a child process could trace its parent process, if not a debugger must be present.
On OpenBSD, impossible to trace a parent process from its child. But with errors (errno), it's possible to determine if a debugger is present or not.
Possible errors for ptrace / PT_ATTACH in child process:
- EBUSY: process already traced
- EPERM: process is not a child of tracer (sysctl kern.global_ptrace=0)
- EINVAL: process is an ancestor of the current process and not init (sysctl kern.global_ptrace=1)
Closes #23603 
---
**Tests OK** on OpenBSD current/adm64
Code `debugger_present.v` to test if debugger is present or not
```go
import os
fn main() {
println('Call 1:')
if os.debugger_present() {
println('debugger here')
} else {
println('no debugger')
}
println('Call 2:')
if os.debugger_present() …
```
> os: add debugger_present implementation for OpenBSD

- vlib/v/gen/c/spawn_and_go.v
Fix issue #24482
This PR introduce a tmp var, a workaround for the `tcc/aarch64` bug.
before :
```c
void* string_hex_thread_wrapper(thread_arg_string_hex *arg) {
string* ret_ptr = (string*) _v_malloc(sizeof(string));
*ret_ptr = arg->fn(arg->arg0); 
_v_free(arg);
return ret_ptr;
}
```
after:
```c
void* string_hex_thread_wrapper(thread_arg_string_hex *arg) {
string* ret_ptr = (string*) _v_malloc(sizeof(string));
string _t3 = arg->fn(arg->arg0);
*ret_ptr = _t3;
_v_free(arg);
return ret_ptr;
}
```
> cgen: workaround tcc aarch64 spawn call bug

- vlib/os/debugger_default.c.v
`debugger_present` implementation only available on Darwin, FreeBSD, Linux, OpenBSD and Windows.
> os: add note for the availability of the debugger_present implementation

- vlib/v/gen/c/if.v
- vlib/v/gen/c/index.v
- vlib/v/tests/builtin_maps/map_fixed_array_if_guard_test.v
This PR fix map of fixed array value in if guard. (fix #24488)
- Fix map of fixed array value in if guard.
- Add test.
```v
struct Serials {
a u8
b u8
c u8
pub mut:
ids map[u8][3]u8
}
pub fn (mut s Serials) id(id u8) {
if _ := s.ids[id] {
} else {
s3 := u8(s.c + s.ids.len)
s.ids[id] = [s.a, s.a, s3]!
}
}
fn main() {
mut s := Serials{
a: 1
b: 2
}
s.id(u8(3))
println(s)
assert s.ids[3] == [u8(1), 1, 0]!
s.id(u8(4))
println(s)
assert s.ids[4] == [u8(1), 1, 1]!
}
Serials{
a: 1
b: 2
c: 0
ids: {3: [1, 1, 0]}
}
Serials{
a: 1
b: 2
c: 0
ids: {3: [1, 1, 0], 4: [1, 1, 1]}
}
```
> cgen: fix map of fixed array value in if guard

- vlib/v/gen/c/cgen.v
- vlib/v/tests/options/option_ptr_nil_test.v
- vlib/v/tests/options/option_ptr_zero_test.v
> cgen: fix codegen for assigning `nil` or `0` to option ptr field

- vlib/v/gen/c/cgen.v
- vlib/v/tests/fns/call_with_nil_test.v
> cgen: fix codegen inconsistency handling `nil` param to arg expecting ptr

- cmd/tools/vrepl.v
- vlib/v/slow_tests/repl/print_output_warning.repl
This PR fix `typeof(a)` with warning in repl (fix #24499).
- Fix `typeof(a)` with warning.
- Add test.
```v
PS D:\Dev\vlang\v> v
____    ____
\    /     |  V 0.4.10 2c42574 . Use  list  to see the accumulated program so far.
>>> a := error('hi')
>>> typeof(a)
warning: use e.g. `typeof(expr).name` or `sum_type_instance.type_name()` instead
6 |
7 | a := error('hi')
8 | println(typeof(a))
|         ~~~~~~
IError
>>> typeof(a)
warning: use …
```
> repl: fix `typeof(a)` with warning (fix #24499)

- vlib/x/json2/decoder2/tests/json2_tests/decode_struct_test.v
- vlib/x/json2/decoder2/tests/json2_tests/json2_test.v
- vlib/x/json2/tests/json2_test.v
`x.json2`: `fast_raw_decode` deprecated after 2025-03-18 => needs to be replaced by `decode[json.Any]` instead
Fix tests in `vlib/x/json2/tests/json2_test.v` and `vlib/x/json2/decoder2/tests/json2_tests/json2_test.v`
**Tests OK** on Linux Debian/testing (amd64) with `prod` mode
- Before this fix
```bash
$ ./v -prod test vlib/x/json2/tests/json2_test.v
FAIL     0.000 ms vlib/x/json2/tests/json2_test.v
vlib/x/json2/tests/json2_test.v:19:12: error: function `x.json2.fast_raw_decode` has been deprecated since 2025-03-18, it will be an error after 2025-09-14; use `decode[json.Any]` instead
17 | fn test_fast_raw_decode() {
18 |     s …
```
> x.json2: fix tests for deprecated function fast_raw_decode

- vlib/builtin/builtin_d_gcboehm.c.v
This PR fix a Windows/msvc issue
```
v -prod vlib\v\gen\c\testdata\self_printer_with_prod.vv
```
When execute the generated `.exe`, it output nothing.
This is due to a mix using of debug/non-debug of `ucrt.lib/ucrtd.lib`. It will cause `os.c.v` `fdopen` crash.
It may also related to issue #20923
> builtin: fix mix prod and debug ucrt lib

- vlib/builtin/isnil_test.v
**Tests OK** on Linux (Debian/testing amd64)
- Before fix
```bash
$ ./v -W test /home/fox/dev/vlang.git/vlib/builtin/isnil_test.v
FAIL     0.000 ms vlib/builtin/isnil_test.v
vlib/builtin/isnil_test.v:17:8: error: cannot cast a number to a type reference, use `nil` or a voidptr cast first: `&Type(voidptr(123))`
15 | 
16 | fn test_isnil_intptr() {
17 |     pi := &int(0)
|           ~~~~~~~
18 |     assert isnil(pi)
19 | }
--------------------------------------------------------------------------------------------------------------------------------------------
To reproduce just failure 1 run:    '/home/fox/dev/vlang.git/v' -W …
```
> builtin: fix tests for isnil

- vlib/v/checker/str.v
- vlib/v/checker/tests/invalid_utf8_string.out
Fix #24538
---
**Tests OK** on Linux (Debian/amd64)
```bash
$ ./v -stats -W test vlib/encoding/utf8/validate/encoding_utf8_test.v
vlib/encoding/utf8/validate/encoding_utf8_test.v:6:36: notice: invalid utf8 string, please check your file's encoding is utf8
4 |     assert validate.utf8_string('añçá') == true
5 |     assert validate.utf8_string('\x61\xC3\xB1\xC3\xA7\xC3\xA1') == true
6 |     assert validate.utf8_string('\xC0\xC1') == false
|                                       ~~~~
7 |     assert validate.utf8_string('\xF5\xFF') == false
8 |     assert validate.utf8_string('\xE0\xEF') == false
vlib/encoding/utf8/validate/encoding_utf8_test.v:7:36: …
```
> checker: replace warning by notice for UTF8 strings validation

- vlib/encoding/utf8/validate/encoding_utf8_test.v
- vlib/encoding/utf8/validate/validate_utf8.v
During fix/debug of issue #24538, I need to add new tests with valid/invalid UTF-8 strings for each step of checks according to the Unicode standard.
- add new tests for valid/invalid UTF-8 strings. Extract from Go UTF8 tests https://cs.opensource.google/go/go/+/refs/tags/go1.24.3:src/unicode/utf8/utf8_test.go
- add note about checks for UTF-8 Byte sequences according to Unicode Standard
---
**Tests OK** on Linux with fix from PR #24543
```bash
$ ./v test vlib/encoding/utf8/validate/encoding_utf8_test.v
OK       1.932 ms vlib/encoding/utf8/validate/encoding_utf8_test.v
----------------------------------------------------------------------------------- …
```
> encoding.utf8: add more tests for UTF-8 strings

- vlib/v/checker/checker.v
- vlib/v/checker/tests/import_mod_as_import_alias_duplicate_err.out
- vlib/v/checker/tests/import_mod_as_import_duplicate_err.out
- vlib/v/tests/import_order_1_test.v
- vlib/v/tests/import_order_2_test.v
**Assumption** The V syntax `import <name> as <alias>` allows for:
- shortening a modules name
- resolve name conflicts
Scenario we have two distinct modules that happen to have the same name. The user correctly uses the `import <name> as <alias>` in one of the imports to correct the name collision.
> Project replicating error [prj_module_alias_error.zip](https://github.com/user-attachments/files/20361788/prj_module_alias_error.zip).
Depending on the order of the import there is an edge case where the checker will report a module as already imported although it has an alias.  The following import triggers an error:
```v
import utilities.validations
import validations as vals //<-- triggers error
```
While this one is accepted:
```v
import validations as vals
import utilities.validations …
```
> checker: revise logic for reporting import conflicts with module names

- vlib/net/openssl/openssl_openbsd.c.v
- vlib/net/openssl/ssl_connection.c.v
OpenBSD uses LibreSSL (OpenSSL fork) by default for libssl/libcrypto. `SSL_get1_peer_certificate` is not supported by LibreSSL, replace it by `SSL_get_peer_certificate`.
Fix #24547
---
**Tests OK** on OpenBSD current/amd64
```bash
$ ./v -stats -W -d use_openssl test vlib/net/http/http_test.v
---- Testing... ----
V  source  code size:      42212 lines,     193393 tokens,    1164711 bytes,   474 types,    33 modules,   221 files
generated  target  code size:      21296 lines,     793237 bytes
compilation took: 1099.270 ms, compilation speed: 38400 vlines/s, cgen threads: 3
running tests in: /home/fox/dev/vlang.git/vlib/net/http/http_test.v
OK    [1/4]     0.005 ms    NO asserts | main.test_http_get()
OK    [2/4]     0.005 ms    NO asserts | main.test_http_get_from_vlang_utc_now()
OK …
```
> net.openssl: replace SSL_get1_peer_certificate by SSL_get_peer_certificate for OpenBSD

- vlib/sync/chan_mod_sync_test.v
- vlib/v/checker/checker.v
- vlib/v/parser/module.v
Fix issue #24552
This bug is because when code has `chan` in it, `parser` will `register_auto_import('sync')`, and then `checker` will fail with error.
> parser: fix duplicate mod imports

- thirdparty/mbedtls/include/mbedtls/mbedtls_config.h
Fix #22239
---
**Tests OK** on OpenBSD current/amd64 with tcc
- Before fix
```bash
$ ./v -W test vlib/net/mbedtls/
FAIL  [1/2] C:  3117.7 ms, R:     0.000 ms vlib/net/mbedtls/mbedtls_compiles_test.v
failed thirdparty object build cmd:
'/home/fox/dev/vlang.git/thirdparty/tcc/tcc.exe' -std=c99 -D_DEFAULT_SOURCE    -fPIC -I "/home/fox/dev/vlang.git/thirdparty/mbedtls/library" -I "/home/fox/dev/vlang.git/thirdparty/mbedtls/include" -I "/home/fox/dev/vlang.git/thirdparty/mbedtls/3rdparty/everest/include" -I "/home/fox/dev/vlang.git/thirdparty/mbedtls/3rdparty/everest/include/everest" -I …
```
> net.mbedtls: disable AES-NI on OpenBSD with tcc

- thirdparty/mbedtls/include/mbedtls/mbedtls_config.h
`pthread` is supported on OpenBSD => enable it for `thirdparty/mbedtls`
**Tests OK** on OpenBSD current/amd64 with tcc, clang and gcc
```bash
$  ./v -W test vlib/net/mbedtls/
---- Testing... ----
OK    [1/2] C:  6266.7 ms, R:    96.169 ms vlib/net/mbedtls/mbedtls_compiles_test.v
OK    [2/2] C:  6359.2 ms, R:    16.750 ms vlib/net/mbedtls/mbedtls_sslconn_shutdown_does_not_panic_test.v
----
Summary for all V _test.v files: 2 passed, 2 total. Elapsed time: 6387 ms, on 2 parallel jobs. Comptime: 12625 ms. Runtime: 112 ms.
$ ./v -cc clang -W test vlib/net/mbedtls/
---- Testing... ----
OK    [1/2] C: 30411.9 ms, R:     9.918 ms vlib/net/mbedtls/mbedtls_compiles_test.v
OK    [2/2] C: 30670.9 ms, R:     7.100 ms vlib/net/mbedtls/mbedtls_sslconn_shutdown_does_not_panic_test.v
----
Summary for all …
```
> net.mbedtls: enable MBEDTLS_THREADING_C and MBEDTLS_THREADING_PTHREAD on OpenBSD

- thirdparty/build_scripts/thirdparty-openbsd-amd64_tcc.sh
**tcc build OK on OpenBSD/amd64** with commit cb39bc4c (2025-05-27) => see PR https://github.com/vlang/tccbin/pull/60
> thirdparty: add thirdparty/build_scripts/thirdparty-openbsd-amd64_tcc.sh for compiling tcc on OpenBSD

- vlib/v/builder/cc.v
`-fwrap` option for C compilation ("Treat signed integer overflow as two's complement") is supported by tcc, clang and gcc on OpenBSD => enable it in `vlib/v/builder/cc.v`
**Tests OK** on OpenBSD current/amd64 with tcc, clang and gcc
```bash
$ VTEST_JUST_ESSENTIAL=1 VTEST_SANDBOXED_PACKAGING=1 ./v -W test-self
```
> v.builder: enable fwrap for C compilation on OpenBSD

- vlib/v/ast/table.v
- vlib/v/checker/fn.v
- vlib/v/markused/markused.v
- vlib/v/tests/skip_unused/thread_waiter.run.out
- vlib/v/tests/skip_unused/thread_waiter.skip_unused.run.out
- vlib/v/tests/skip_unused/thread_waiter.vv
> markused: fix for thread waiter usage

- vlib/v/gen/c/fn.v
- vlib/v/tests/generics/generic_fn_struct_test.v
> cgen: fix generic name handling for struct generic

- vlib/sync/cond.v
- vlib/sync/cond_test.v
> sync: add condition support

- vlib/builtin/builtin.c.v
Flush stdout when panic or panic_debug is called
> builtin: flush stdout on panic

- vlib/builtin/js/map.js.v
- vlib/v/gen/js/builtin_types.v
- vlib/v/gen/js/tests/map.v
- Replace `in key` with `key.hasOwnProperty`, since the `in` operator fails on scalars (string, numbers, etc).
- Fix `len` init in map constructor.
- Add a few tests
Fixes #24616 and #24605
> jsgen: fix direct map key access and map.len (fix #24616, fix #24605)

- vlib/vanilla_http_server/CONTRIBUTING.md
- vlib/vanilla_http_server/README.md
- vlib/vanilla_http_server/http_server/http_server.c.v
- vlib/vanilla_http_server/request_parser/request_parser.v
- vlib/vanilla_http_server/request_parser/request_parser_test.v
- vlib/vanilla_http_server/x.v
```v
module main
import enghitalo.vanilla.http_server
import enghitalo.vanilla.request_parser
fn handle_request(req_buffer []u8, client_conn_fd int) ![]u8 {
req := request_parser.decode_http_request(req_buffer)!
method := request_parser.slice_to_string(req.buffer, req.method)
path := request_parser.slice_to_string(req.buffer, req.path)
match method {
'GET' {
match path {
'/' {
return home_controller([])
}
'/users' {
return get_users_controller([])
}
else {
if path.starts_with('/user/') {
id := path[6..]
return get_user_controller([id])
}
return http_server.tiny_bad_request_response
}
}
}
'POST' {
if path == '/user' {
return create_user_controller([])
}
return http_server.tiny_bad_request_response
}
else {
return http_server.tiny_bad_request_response
}
}
return …
```
> vlib: vanilla_http_server

- cmd/tools/vtest-self.v
- vlib/db/mysql/orm.c.v
- vlib/db/pg/orm.v
- vlib/db/sqlite/orm.v
- vlib/orm/orm.v
- vlib/orm/orm_where_in_test.v
- vlib/v/gen/c/orm.v
This PR add support for IN and NOT IN comparisions in the orm.
Usage is simply:
```v
return sql db {
select from User where name in names
}!
```
or
```v
return sql db {
select from User where name !in names
}!
```
Closes #24347
> orm: add IN and NOT IN

- vlib/v/pref/pref.v
> pref: avoid changing the backend with `.js.v` when `-backend` has already been used (fix #7840)

- vlib/v/checker/checker.v
- vlib/v/tests/match_or_expr_test.v
> checker: fix missing type bounding to match expr on or-expr

- vlib/math/big/integer.v
Faster conversion of limbs to radix.
Had to split the function into two. They are very similar, as it should be.
Each solves its specific tasks.
Now a larger number of digits is calculated at once.
Performance for radix 10:
o) -current -> 9 times faster;
o) 0.4.10 -> 57 times faster;
Tested against GMP for all radixes in range 2-36.
> math.big: faster radix_str()

- vlib/math/big/integer.v
Lets make `integer_from_radix()` faster too.
Use the same mechanism to calculate more digits at once as in `radix_str()`.
o) ~10 times faster
o) these two functions tested together in 1M loop against `gmp`.
> math.big: faster integer_from_radix()

- vlib/builtin/js/map.js.v
- vlib/v/gen/js/auto_str_methods.v
- vlib/v/gen/js/js.v
- vlib/v/gen/js/tests/map.v
Fixes #24607 and #24671
The original problem is that map keys do not preserve the prototype methods of the original key values. The trick is to store the original key values, along with their prototype, so the following V code:
```v
m := {
1: 'one'
2: 'two'
3: 'three'
}
```
Is translated to this JS code:
```js
const map = {
"map": {
// the `key` property preserves the original key value, along with its prototype
"1": { "val": { "str": "one" }, "key": { "val": 1 } },
"2": { "val": { "str": "two" }, "key": { "val": 2 } },
"3": { "val": { "str": "three" }, "key": { "val": 3 } }
},
"length": 3
};
```
Later, we can then use the "key values" for other purposes, such as returning the keys from the map.
> jsgen: fix maps are always constructed using string keys (fix #24607 #24671)

- vlib/builtin/js/jsfns.js.v
Fixes #23711
How to test in Linux (macos):
```bash
npm -g install esbuild
cd examples
v -skip-unused -backend js_browser -prod ./js_hello_world.v -o hello.js
esbuild --minify --platform=browser --bundle hello.js --outfile=hello.min.js
node hello.min.js
```
Output:
```
Hello from V.js (0)
Hello from V.js (1)
Hello from V.js (2)
```
> jsgen: fix slightly incorrect JS (breaks esbuild) (fix #23711)

- vlib/runtime/free_memory_impl_openbsd.c.v
Cast `len` to `usize` type (aka unsigned long) for `sysctl` function on OpenBSD: get `pagesize` and `free` from C `uvmexp` struct.
Without this cast, errors with tcc, clang and GCC when checking C code with `-cstrict`:
```bash
================== C compilation error (from clang): ==============
cc: /tmp/v_1000/get_free_mem_openbsd.01JXF6BTF9DM869CQGFEHKTKZG.tmp.c:5718:41: error: incompatible pointer types passing 'u32 *' (aka 'unsigned int *') to parameter of type 'size_t *' (aka 'unsigned long *') [-Werror,-Wincompatible-pointer-types]
cc:                 int retval = sysctl(&mib[0], 2, &uvm, &len, NULL, 0);
cc:                                                       ^~~~
cc: /usr/include/sys/sysctl.h:1100:48: note: passing argument to parameter here
cc: int     sysctl(const int *, u_int, …
```
> runtime: fix cast for free_memory on OpenBSD

- vlib/net/http/server_test.v
On OpenBSD, TCP connect fails (return EINVAL) if attempted with 0.0.0.0 address.
In `vlib/net/http/server_test.v`, for tests `test_server_custom_handler` and `test_host_header_sent_to_server`, use 127.0.0.1 as IP addr for the HTTP server.
Fix https://github.com/vlang/v/issues/22126
**Tests OK** on OpenBSD/amd64 and Linux/amd64 with tcc, clang and gcc
```bash
$ ./v test vlib/net/http/server_test.v 
OK    1996.242 ms vlib/net/http/server_test.v
--------------------------------------------------------------------------------------------------------------------------------------------
Summary for all V _test.v files: 1 passed, 1 total. Elapsed time: 3590 …
```
> net.http: set IP address for HTTP server during tests

- vlib/v/gen/c/str.v
- vlib/v/tests/enums/enum_val_test.v
> cgen: fix enumval str() call on stringinterliteral

- thirdparty/build_scripts/thirdparty-freebsd-amd64_bdwgc.sh
Script `thirdparty/build_scripts/thirdparty-freebsd-amd64_bdwgc.sh` added to build static library `libgc.a` on FreeBSD/amd64.
Used to build and add `libgc` static library in [vlang/tccbin](https://github.com/vlang/tccbin) repository, branch `thirdparty-freebsd-amd64`.
See my detailed explanations in issue https://github.com/vlang/v/issues/24710#issuecomment-2972473239
> thirdparty: add script to build libgc on FreeBSD/amd64

- vlib/x/templating/dtm/README.md
The outdated link to the dynamic_template_manager_test_server demo in the README has been replaced with the correct, up-to-date path:
https://github.com/vlang/v/tree/master/vlib/vweb/tests/dynamic_template_manager_test_server
This ensures users can easily find and view the demonstration project.
> Update demo link in README to current dynamic_template_manager_test_server location

- cmd/tools/vdoc/markdown.v
- cmd/tools/vdoc/testdata/output_formats/main.md
- cmd/tools/vdoc/vdoc_file_test.v
This PR makes autogenerated markdown docs useful.
Before this PR `v doc -f md module` without `-comments` produces useless docs without function signatures, struct bodies, etc and actual docstrings. There is no `-comments` flag needed anymore for getting normal docs.
There is example [before](https://gist.github.com/gechandesu/5daeb38eb0fc6b0caefc2ae801869bb3#file-vdoc_net-smtp-md) and [after](https://gist.github.com/gechandesu/5daeb38eb0fc6b0caefc2ae801869bb3#file-vdoc_fixed_net-smtp-md) output.
> tools: make  `v doc -f md module` output useful by default

- vlib/builtin/string.v
- vlib/os/asset/asset.v
- vlib/os/font/font.v
- **builtin: allow for freeing the intermediate allocations in string methods like split_by_space, split_into_lines, split_nth, split_n, split_any, rsplit_any**
- **os: enable no warnings for `v -gc boehm_leak -cg -keepc run examples/gg/minimal.v` (part 1 - before gg loop)**
> builtin,os: enable no warnings for gg programs like `v -gc boehm_leak -cg -keepc run examples/gg/minimal.v` (part 1 - before the `gg` loop)

- thirdparty/sokol/sokol_gfx.h
Fixes a performance drop caused by https://github.com/vlang/v/commit/37e5ead75d18e0c4d1261b7858f3a6a63c642c9d
When built for release, assert(x) is no-op. Commit 37e5ead, had introduced an if-block & fprintf statement to print the glGetError() code to make diagnostic easier. However, this change will execute even when assert(x) is void.
This commit provides a fix by having an ifdef check for NDEBUG, and if NDEBUG is defined then _SG_GL_CHECK_ERROR will be defined as nothing, as the result of SOKOL_ASSERT/ASSERT, would also be nothing (glibc/assert.h).
Edit:
Video of performance drop (left is after this pull, right is before):
https://github.com/user-attachments/assets/1b71a5d0-dd93-4df5-82ea-49480af40bb5
> thirdparty: add NDEBUG check before glGetErrorCode if-statement in sokol_gfx.h

- vlib/x/crypto/curve25519/curve25519.v
- vlib/x/crypto/curve25519/curve25519_test.v
This small patch improves `x.crypto.curve25519` a bit in the sense
- fixs possible double free on `.free()` call.
- we reject zeros bytes as an input, as a scalar or point, so, we add consistency check on required routines
- fixs some typos comment, its comes from automagically github `apply suggestion` features.
- remove out the slow test part. Its has been proposed into specialized repo for that, see [PR#3](https://github.com/vlang/slower_tests/pull/3)
Thanks
> `x.crypto.curve25519`: small fix and add consistencies check

- vlib/math/big/big_test.v
- vlib/math/big/integer.v
It's time to add mathematical modulo.
The old commit 6e271b2 fixed the behavior of div_mod() family with negative input data as `truncate` (equivalent to `gmplib's` `mpz_tdiv` function family).
Now the new functions `mod_euclid()` and `mod_euclid_checked()` will behave like libgmp's `mpz_mod()`.
Tested against `mpz_mod()` on 1M cycle.
> math.big: new math modulo function mod_euclid(), add tests (fix #24756)

- vlib/crypto/sha512/sha384_shavs_test.v
- vlib/crypto/sha512/sha512_224_shavs_test.v
- vlib/crypto/sha512/sha512_256_shavs_test.v
- vlib/crypto/sha512/sha512_shavs_test.v
**All tests OK** for `vlib.crypto` with `-W` flag:
```bash
$ ./v -W test vlib/crypto/
(...)
Summary for all V _test.v files: 60 passed, 4 skipped, 64 total. Elapsed time: 29025 ms, on 3 parallel jobs. Comptime: 58158 ms. Runtime: 27687 ms.
```
> crypto: remove unused os import for SHA512 tests

- vlib/math/big/integer.v
This code is completely unnecessary.
The definition of how to handle negative input values is already located in `div_mod()`.
Tests are already in the code base and they pass successfully.
For double reliability, all of this is verified against `libgmp`.
> math.big: remove unnecessary code from / and %

- vlib/builtin/builtin.v
- vlib/builtin/string.v
- vlib/builtin/string_iterator_test.v
- vlib/builtin/utf8.v
- vlib/v/gen/c/testdata/if_else_return.c.must_have
- **builtin: add a s.runes_iterator() method, allowing for `for i, r in s.runes_iterator() {` with no allocations**
- **fix if_else_return.c.must_have**
> builtin: add a rune iterator method to strings, allowing `for for i, r in s.runes_iterator() {` without first allocating an array for all the runes

- README.md
Improve documentation with a dedicated section to build V on OpenBSD: 3 packages needed to build it.
> docs: add section in README for compilation on OpenBSD

- cmd/tools/modules/testing/common.v
- vlib/crypto/ecdsa/ecdsa.c.v
- vlib/crypto/ecdsa/ecdsa_test.v
- vlib/crypto/ecdsa/example/ecdsa_seed_test.v
- vlib/crypto/ecdsa/example/ensure_compatibility_with_net_openssl_test.v
- vlib/crypto/ecdsa/util_test.v
On OpenBSD, LibreSSL (https://www.libressl.org/) is used by default as TLS/crypto stack. This library is not fully compatible with OpenSSL v3.
OpenSSL v3.4 could be installed on OpenBSD via `eopenssl34` package available in official ports tree.
This PR adds support for OpenSSL version 3.4 (more recent version available for 7.7 release) on OpenBSD :
- `cmd/tools/modules/testing/common.v`: add special case for OpenBSD to check if OpenSSL is present
- `vlib/crypto/ecdsa/ecdsa.c.v`: add flags for OpenSSL to find OpenSSL v3.4 includes/libs
- disable tests for OpenBSD with gcc in `crypto/ecdsa`: issues to find OpenSSL symbols during link (unable to fix theses errors for now).
---
**Tests OK** on OpenBSD/amd64 with tcc, clang and gcc for `vlib/crypto`, `vlib/net/ssl/` and `vlib/net/openssl/` …
> crypto.ecdsa: add support for OpenSSL on OpenBSD

- vlib/builtin/string.v
- vlib/builtin/string_test.v
Add string.expand_tabs() replaces tab characters (\t) in the input string with spaces to achieve proper column alignment.
Example: assert 'AB\tHello!'.expand_tabs(4) == 'AB  Hello!'
> builtin: add string.expand_tabs()

- vlib/os/environment.c.v
Move comments/TODO after function declaration, otherwise HTML documentation are not properly generated by `vdoc` tool.
> os: fix documentation for environ function

- vlib/sync/waitgroup.c.v
- vlib/sync/waitgroup_test.v
A followup to a Discord discussion: https://discord.com/channels/592103645835821068/592115457029308427/1387825635895939113 .
> sync: add implementation for WaitGroup.go/1, add test

- vlib/sync/spinlock_test.v
- vlib/sync/stdatomic/1.declarations.c.v
- vlib/sync/sync.c.v
1. Bug fix for spin lock expected value reset to unlock before retry.
2. Update test.
3. Add `destroy()`.
4. Add `try_lock()`.
5. Add `valgrind` `ANNOTATE` support  to avoid false error report with spin lock detection. When using with `valgrind`, please add `-d valgrind` to enable this.
Original code(`expected = C.atomic_load_byte(&s.locked)`) will cause the updated test fail sometimes.
> sync: fix spin lock, add destroy() and try_lock()

- vlib/picoev/loop_openbsd.c.v
- vlib/picoev/picoev.v
- `vlib/picoev/picoev.v`: add case for openbsd to use kqueue loop
- `vlib/picoev/loop_openbsd.c.v`: implementation for OpenBSD using kqueue (same as FreeBSD implementation).
---
**Tests OK** on OpenBSD/amd64 with tcc, clang and gcc for `vlib/picoev` tests and tests with `veb` (implementation uses picoev).
```bash
$ ./v  -W test vlib/picoev/
OK       9.768 ms vlib/picoev/picoev_test.v
--------------------------------------------------------------------------------------------------------------------------------------------
Summary for all V _test.v files: 1 passed, 1 total. Elapsed time: 947 ms, on 1 job. Comptime: 933 ms. Runtime: 9 ms.
$ ./v -stats …
```
> picoev: add implementation for OpenBSD using kqueue

- vlib/sync/bench/run_bench.v
- vlib/sync/channels.c.v
1. Use `SpinLock` for channel, replace some atomic operations.
2. Fix issue #24680,  avoid false error report from `valgrind`, this will may debugging multi-thread app easier.
BTW, I found that it can read from a closed channel, is this a correct behavior?
> sync: use SpinLock for channel

- vlib/v/checker/str.v
- vlib/v/scanner/scanner.v
- vlib/v/tests/builtin_strings_and_interpolation/string_interpolation_multi_level_test.v
fix multi-level string interpolation in if/match branch, and "fix" match expr type in string interpolation, there still has some codegen error for `assert '${match true { true { '${x}' } else { '${x + 1}' } }}' == '0'`
> scanner: fix multi-level string interpolation in if/match branch

- vlib/v/checker/comptime.v
- vlib/v/checker/struct.v
- vlib/v/tests/structs/struct_generic_sizeof_test.v
> checker: fix `sizeof(T)` usage on generic struct

- cmd/tools/vast/vast.v
- vlib/v/ast/ast.v
- vlib/v/gen/c/assign.v
- vlib/v/gen/c/fn.v
- vlib/v/parser/assign.v
- vlib/v/tests/defer/defer_static_test.v
> parser, cgen: fix static and volatile var deref

- vlib/math/unsigned/uint128.v
- vlib/math/unsigned/uint128_test.v
The `math.unsigned` module is also raw, untested and therefore buggy.
This patch allowed me to pass a multi-billion test against `gmplib`.
This is the first fix from a future series of corrections.
> math.unsigned: fix lsh() for Uint128, add tests

- vlib/math/unsigned/uint128.v
- vlib/math/unsigned/uint128_test.v
Lets fix rsh() for Uint128.
Multi-billion loop against `libgmp` passed.
> math.unsigned: fix rsh() for Uint128, add tests

- vlib/datatypes/lockfree/README.md
- vlib/datatypes/lockfree/bench/bench_channel.v
- vlib/datatypes/lockfree/bench/bench_ringbuffer.v
- vlib/datatypes/lockfree/counter.v
- vlib/datatypes/lockfree/counter_test.v
- vlib/datatypes/lockfree/lockfree.v
- vlib/datatypes/lockfree/ringbuffer.v
- vlib/datatypes/lockfree/ringbuffer_test.v
Thread-safe high-performance datatypes implemented using atomic operations, currently supporting `counter` and `ringbuffer`.
TBD:
1. Stack
2. Double-Ended Queue (Deque)
3. Concurrent Map
4. ...
> datatypes: add lockfree version of counter and ringbuffer

- vlib/v/tests/unions/union_implementing_interface_test.v
Prevent silent regression of currently not tested functionality discovered in https://discord.com/channels/592103645835821068/784039809459027979/1391493199402504293 , i.e.
Unions can have methods, and they can also use `implements` similar to structs.
> tests: add union_implementing_interface_test.v

- vlib/math/unsigned/uint128.v
Fix 3 typos in descriptions of uint128's functions.
> math.unsigned: fix typos for uint128

- vlib/math/unsigned/uint256.v
- vlib/math/unsigned/uint256_test.v
`lsh()` for uint256 is broken.
The same mechanism as used for uint128 is used for the fix.
Now passed big loop against gmplib.
> math.unsigned: fix lsh() for uint256, add tests

- vlib/math/big/array_ops.v
- vlib/math/big/big_test.v
- vlib/math/big/special_array_ops.v
**Description:**
Karatsuba is already fixed, now it's time for `Toom-Cook-3`.
The current Toom-Cook-3 is broken and although Toom-Cook-3 was correctly implemented and worked correctly if not raising two to large powers for example.
**New thresholds:**
Karatsuba+Toom-Cook-3 are twin brothers with similar characteristics and the threshold values at which they come into operation should be close. If the threshold for Toom-Cook-3 is now lowered below 250, even the current tests will break. The values for the two thresholds were chosen programmatically by a script and now 9 to the power of 33420489 works ~7 times faster and approaches and/or exceeds cpython.
**Toom-Cook-3 fix:**
If the some operand contains all zeros except for the last limb, then when dividing the limb array into three parts, …
> math.big: fix toom-cook 3-way multiplication

- vlib/builtin/builtin.c.v
- vlib/builtin/builtin_d_gcboehm.c.v
- vlib/builtin/builtin_notd_gcboehm.c.v
- vlib/builtin/cfns.c.v
- vlib/builtin/prealloc.c.v
- vlib/builtin/wasm_bare/libc_impl.c.v
- vlib/v/ast/table.v
- vlib/v/checker/struct.v
- vlib/v/eval/expr.c.v
- vlib/v/gen/c/assign.v
- vlib/v/gen/c/cheaders.v
- vlib/v/gen/c/struct.v
- vlib/v/markused/markused.v
- vlib/v/tests/structs/struct_aligned_test.v
Fix issue #24882
This make following example always aligned at 64,
```v
@[aligned: 64]
a int
}
fn test_struct_aligned() {
x := u64(voidptr(&MyStruct{}))
assert x % 64 == 0
y := MyStruct{}
ptr := u64(voidptr(&y))
assert ptr % 64 == 0
}
```
This PR modifies the built-in `malloc()` family of functions. On Windows, all `malloc()` calls now utilize `_aligned_malloc()`, meaning the returned pointers must be freed using `_aligned_free()`.
Therefore, in your codebase:
- **Avoid** directly calling `C.malloc()`, `C.realloc()`, `C.calloc()` or `C.free()`
- **Instead use** the built-in memory management functions: `malloc()`, `v_realloc()`, `vcalloc()`, and `free()`
> builtin,cgen,markused: add struct [aligned] support

- vlib/builtin/cfns.c.v
- vlib/os/os_windows.c.v
```v
C.FormatMessageW(format_message_allocate_buffer,...)
```
The function allocates a buffer large enough to hold the formatted message, and it must be freed by `C.LocalFree()`.
> os: fix windows get_error_msg() leak

- vlib/v/ast/comptime_valid_idents.v
- vlib/v/tests/comptime/comptime_arch_test.v
> ast: fix arch loongarch64 comptime support

- vlib/x/json2/decoder2/decode.v
- vlib/x/json2/decoder2/tests/decode_escaped_string_test.v
fix #24834. Modified checker to correctly handle escaped ", also rewrote the string decoder in a correct and faster way.
> decoder2: fix checking and decoding of escape characters

- vlib/runtime/used_memory_default.c.v
- vlib/runtime/used_memory_openbsd.c.v
**Tests OK** on OpenBSD current/amd64 with tcc, clang and gcc
```sh
$ ./v -stats -W test vlib/runtime/used_memory_test.v
V  source  code size:      30279 lines,     139117 tokens,     818664 bytes,   292 types,    13 modules,   137 files
generated  target  code size:       9919 lines,     342127 bytes
compilation took: 623.194 ms, compilation speed: 48586 vlines/s, cgen threads: 3
running tests in: /home/fox/dev/vlang.git/vlib/runtime/used_memory_test.v
used memory 1 : 2293760
used memory 2 : 10731520
used memory 3 : 78139392
1
1
OK      66.081 ms     3 asserts | main.test_used_memory()
Summary for running V tests in "used_memory_test.v": 3 passed, 3 …
```
> runtime: add used_memory implementation for OpenBSD

- vlib/x/json2/decoder2/decode.v
- vlib/x/json2/decoder2/tests/decode_option_field_test.v
> decoder2: fix decoding of structs with option fields

- vlib/builtin/cfns.c.v
- vlib/os/os_windows.c.v
- vlib/runtime/runtime_windows.c.v
- vlib/sync/sync_windows.c.v
os,runtime: move some struct and fn def to `builtin` as they may needed by other modules ( e.g. `builtin.closure`).
> os,runtime: move some struct and fn def to builtin

- vlib/v/slow_tests/assembly/asm_test.amd64.v
Currently, this test crashes on `clang`.
This needs to be fixed by proactively specifying that the `eax` register is modified.
It worked on `gcc` as is, but clang requires an explicit specification.
> slow_tests: fix crash on clang for asm_test.amd64.v

- vlib/v/parser/fn.v
- vlib/v/tests/fns/call_struct_params_with_keyword_test.v
> parser: allow keyword as struct param key on fn call

- vlib/regex/regex.v
- **regex: fix OOB bug discovered through `./v -g -force-bounds-checking vlib/regex/`**
> regex: fix OOB bug discovered through `./v -g -force-bounds-checking test vlib/regex/`

- vlib/v/eval/eval.v
- vlib/v/eval/expr.c.v
- vlib/v/eval/infix.v
- vlib/v/eval/stmt.v
- vlib/v/eval/tests/comptime_if_test.v
- vlib/v/eval/tests/if_test.v
This PR:
1. add support for `&&`, `||`, `>=`, `<=`,`!`;
2. comptime infix expr support;
3. early function return.
> eval:add more infix op support; fix early func return

- vlib/x/json2/decoder2/decode.v
- vlib/x/json2/decoder2/decode_sumtype.v
- vlib/x/json2/decoder2/tests/json_sumtype_test.v
Reworks the sumtype decoder to allow for more complex sumtypes and better error handling.
- Adds Decoding for json2.Null, so that json2.Any is fully supported
- Sumtype that cant be resolved now gives a clearer error e.g. `could not resolve sumtype Sum, got string_` instead of `Expected number, but got string_`
- map & array now only get resolved if the entire type matches (instead of just using the first array / map). This allows for sumtypes with multiple different array types like `type MultiArray = []int | []bool`. This also enhances error messages.
- Options & Type aliases are still not support, but now give runtime errors instead of cryptic compiler errors
- Fix random compiler error when having multiple sumtypes with maps in the code
Because the decoder now gives errors, instead of …
> decoder2: rework decoding of sumtypes

- examples/archive/tar_gz_reader.v
- vlib/archive/tar/reader.v
- vlib/archive/tar/reader_test.v
This PR fixes typo in `archive.tar` `new_decompressor` fn name. It's unlikely that anyone has had time to use this module, so this shouldn't be a breaking change.
> archive.tar: fix typo in new_decompressor fn name

- vlib/v/gen/c/infix.v
- vlib/v/tests/builtin_maps/map_generic_keys_with_in_op_test.v
> cgen: fix generic key's type with `in` operation(fix #24983)

- cmd/tools/vast/vast.v
- vlib/v/ast/ast.v
- vlib/v/ast/table.v
- vlib/v/markused/markused.v
- vlib/v/markused/walker.v
- vlib/v/parser/fn.v
- vlib/v/parser/module.v
- **ci,tools: implement support for VREPEAT_SILENT=1 and `v repeat -S`, to only show the summary of the runs, without the progress lines**
- **markused,ast: improve the tracking of closure usages (including instance.method that uses an implicit closure)**
> markused: improve the tracking of used closures

- vlib/net/http/http.v
The post_multipart_form function prints the configured headers when called. I suppose this is not intended. This PR just removes this debug print statement.
> net.http: remove debug print statement from post_multipart_form

- .github/workflows/s390x_linux_ci.yml
- vlib/v/gen/c/comptime.v
Currently, C code is generated in such a way that all platforms after `riscv32` don't receive control, and as a result, closures crash.
```
#if defined(__V_amd64)
#elif defined(__V_x86)
#elif defined(__V_arm64)
#elif defined(__V_arm32)
#elif defined(__V_rv64)
#elif defined(true)
#elif defined(__V_s390x)
#elif defined(__V_ppc64le)
#elif defined(__V_loongarch64)
#else
#endif
```
The patch fixes this, and adding a existing test to s390x CI minimizes the consequences of similar situations in the future.
> cgen, ci: fix closures on s390x, ppc64le and loongarch64 platforms, add test to s390x CI

- vlib/v/parser/fn.v
Fix issue #25024
In `-translated` mode, a definition made in a .c.v file, should have a priority over a .v file definition of the same function.
Test will be added in another PR #25020
Closes #25024
> parser: translated same fn name overridden

- vlib/gg/draw.c.v
fix local pixel misalignment and simplify the drawing logic of the `gg`/`draw_rounded_rect_empty()`
> gg:improve drawing effect and logic of the `draw_rounded_rect_empty`

- vlib/v/gen/c/cgen.v
- vlib/v/slow_tests/assembly/stmt_separator_test.amd64.v
```
"mul %[lo], %[x], %[y];"
"umulh %[hi], %[x], %[y];"
```
This violates GCC/Clang's inline assembly syntax requirements. And this PR replaced semicolons with proper `\n\t` separators.
```
"mul %[lo], %[x], %[y]\n\t"
"umulh %[hi], %[x], %[y]\n\t"
```
> cgen: fix asm stmt separators

- vlib/v/parser/asm.v
- vlib/v/slow_tests/assembly/asm_test.amd64.v
Fix issue #25070
Output constrains: `=r`, `=&r`, `+r`, `+&r`,`=m`,`=rm`,`=@ccl`, `=*r`
Input constrains: `r`, `0`, `rm`, `i`, `%r`, `*m`
> parser: fix asm modifier parse

- vlib/v/gen/c/cgen.v
- vlib/v/tests/options/option_or_expr_dump_test.v
> cgen: fix codegen for option void fn return block unwrap

- .github/workflows/module_docs_ci.yml
- **vdoc: enable example lines that have explicit imports too, fixup the remaining vlib examples, so `v doc -v -unsafe-run-examples -f none vlib/` could be added to the CI**
- **ci: use `./v doc -m -f html -unsafe-run-examples -time vlib/` for module doc generation**
- **ci: fix dependencies for modules with examples (libasound2-dev is needed for sokol.audio on Ubuntu)**
> ci: fix dependencies for modules with examples (libasound2-dev is needed for sokol.audio on Ubuntu)

- vlib/math/big/big_test.v
- vlib/math/big/integer.v
The current implementation of `integer_from_i64()` already has support for the minimum int value `min_i64`.
Currently this code returns wrong output:
```
pulsar:~# cat r.v 
import math.big
fn main() {
println(big.integer_from_int(min_int))
}
pulsar:~# v run r.v 
-18446744071562067968
pulsar:~# 
```
Lets fix `integer_from_int()` too.
> math.big: fix integer_from_int(min_int) edge case, add tests

- vlib/v/checker/struct.v
- vlib/v/checker/tests/generic_field_init_with_call_err.out
- vlib/v/checker/tests/generic_field_init_with_call_err.vv
- vlib/v/checker/tests/generics_struct_init_with_inconsistent_generic_types_3_err.out
- vlib/v/checker/tests/generics_struct_init_with_inconsistent_generic_types_3_err.vv
> checker: fix missing check for struct generic init from call

- vlib/v/checker/checker.v
- vlib/v/checker/comptime.v
- vlib/v/checker/if.v
- vlib/v/checker/tests/comptime_field_name_not_exist.out
- vlib/v/checker/tests/comptime_field_name_not_exist.vv
- vlib/v/checker/tests/custom_comptime_define_error.out
- vlib/v/checker/tests/unknown_comptime_expr.out
- vlib/v/gen/c/testdata/comp_if_unknown.c.must_have
- vlib/v/gen/c/testdata/comp_if_unknown.vv
- vlib/v/tests/comptime/comptime_for_if_cond_check_test.v
- vlib/v/tests/comptime/comptime_if_glibc_test.v
- vlib/v/type_resolver/type_resolver.v
This PR:
1. Rewrite `comptime_if_cond()` in `checker`, fully support comptime if conditon evaluate to `true`/`false`.
2. Add comptime iter $for support for enum/method/method params/sumtype variants/attribute.
3. Fix issue #25099, #24938.
for test `vlib/v/gen/c/testdata/comp_if_unknown.vv`
```v
fn main() {
mut x := 1
$if glibc {
x = 2
} $else {
x = 3
}
println('done')
}
```
I think the output should contain :
```c
#if defined(__GLIBC__)
x = 2;
#else
#endif
```
instead of :
```c
#if defined(__GLIBC__)
x = 2;
#else
x = 3;
#endif
```
> checker: rewrite comptime_if_cond() to support comptime if cond evaluate

- vlib/math/big/array_ops.v
The first of two patches for addition.
It all started when I found that there was no fast exit from the function when the input array was empty. Currently there are three places in the library that use this function - `subtract`, `addition` and `Karatsuba`.
Simple arithmetic has protection and doesn't let empty arrays pass through, but `Karatsuba` does.
The patch contains three blocks of changes:
1. just protection for the future if someone uses the function incorrectly
2. `Karatsuba` can pass an empty array, it is necessary to do `shrink`, without `shrink` tests will fail
3. Here the point is to remove the unnecessary `if` and `delete_last()`
Multi-million loop passed against 'gmplib`.
> math.big: add_digit_array() refactoring

- vlib/v/gen/c/auto_eq_methods.v
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/tests/c_structs/cstruct_anon_eq_test.c.v
Given the below C struct (typedef is not required to repro):
```c
// anon.h
typedef struct {
struct {
int x;
} inner;
} outer;
```
```v
// cstruct_anon_eq_test.c.v
#insert "@VMODROOT/anon.h"
@[typedef]
struct C.outer {
inner struct {
x int
}
}
a := C.outer{}
b := C.outer{}
assert a == b
}
```
Currently generates invalid eq functions:
```
======== Output of the C Compiler (/home/dylan/Downloads/v_linux/v/thirdparty/tcc/tcc.exe) ========
/tmp/v_1000/cstruct_anon_eq_test.01K37GBP8GYEP9GV6HW3RTH1D4.tmp.c:2416: error: cannot convert 'struct <anonymous>' to 'struct main___VAnonStruct1'
===================================================================================================
======== Output of the C Compiler (cc) ======== …
```
> cgen: fix eq for anon C structs

- vlib/math/big/integer.v
To transition to a 60-bit base for `math.big`, it is necessary to return and rewrite the code for `str()` and `integer_from_string()`. This is also a good opportunity to additionally perform refactoring. 
Tests show that for multi-thousand digit numbers, `str()` will now be `~14x` faster, and `integer_from_string()` `~11x` faster.
The repo already contains the necessary tests for all `radix`.
Patch passed tests against `gmplib`.
> math.big: restore and refactor str() and integer_from_string()

- vlib/v/ast/ast.v
- vlib/v/checker/comptime.v
- vlib/v/checker/match.v
- vlib/v/checker/tests/comptime_match_cond_cannot_mut.out
- vlib/v/checker/tests/comptime_match_cond_cannot_mut.vv
- vlib/v/checker/tests/comptime_match_value_different_type.out
- vlib/v/checker/tests/comptime_match_value_different_type.vv
- vlib/v/checker/tests/comptime_match_value_type_mix_check.out
- vlib/v/checker/tests/comptime_match_value_type_mix_check.vv
- vlib/v/fmt/fmt.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/comptime.v
- vlib/v/parser/expr.v
- vlib/v/parser/if_match.v
- vlib/v/parser/parser.v
- vlib/v/tests/comptime/comptime_match_assign_test.v
- vlib/v/tests/comptime/comptime_match_for_field_type_test.v
- vlib/v/tests/comptime/comptime_match_for_field_value_test.v
- vlib/v/tests/comptime/comptime_match_generic_type_test.v
- vlib/v/tests/comptime/comptime_match_type_2_test.v
- vlib/v/tests/comptime/comptime_match_type_check_test.v
- vlib/v/tests/comptime/comptime_match_value_check_test.v
Feature require by #25100
This PR support two kinds of `$match`, a type `$match` and a value `$match`.
ex:
```v
$match T {
int { }
string {}
$else{}    // `$else` is optional
}
```
```v
$match x {
1 {}
2 {}
3 {}
}
```
also, support assignment :
```v
x := $match val {
1 { '1' }
2 { '2' }
$else { 'unknown' }
}
```
> checker,cgen: add comptime match support

- vlib/v/markused/walker.v
- vlib/v/tests/skip_unused/option_array_init.vv
> markused: fix option array element

- vlib/veb/tests/handle_split_requests_in_chrome_test.v
- vlib/veb/veb.v
- **net: improve tracing output for `-d trace_tcp`; move `error_code()` calls right after the corresponding C APIs (errno is a global that should be read immediately to be valid)**
- **veb: fix a spurious error with Chromium based browsers, when an http POST request is split into several parts, where the first one has only http headers, without a body (fix #25191)**
> veb: fix a spurious error with Chromium, for POST requests, split into 2 parts, 1st with only http headers, without body (fix #25191)

- vlib/x/json2/decoder2/decode.v
- vlib/x/json2/decoder2/tests/decode_escaped_string_test.v
Will now decode utf-16 surrogates, used by some encoders for characters outside the bilingual plane.
`println(decoder2.decode[string](r'"\ud83d\ude00"')!) // '😀'`
> decoder2: Add support for surrogates

- vlib/v/ast/ast.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/comptime.v
- vlib/v/gen/c/testdata/comptime_if_top_hash_stmts.c.must_have
- vlib/v/gen/c/testdata/comptime_if_top_hash_stmts.vv
Fix issue #25184
When processing hash statements, only their nodes are recorded and placed into the corresponding `_nodes` array. After processing all other statements, the various `_nodes` arrays are scanned to generate the corresponding hash statements.
TODO:  Fix `native` backend.
| C code sections | Description |
|:----------------|:------------|
| **preincludes** | `preinclude_nodes` go here |
| **includes**    | `include_nodes` go here |
| **definitions** | `definition_nodes` go here |
| **code**        |             |
| **postinclude** | `postinclude_nodes` go here |e
> cgen: fix hash stmt code generation

- vlib/v/checker/comptime.v
- vlib/v/checker/match.v
- vlib/v/parser/if_match.v
- vlib/v/parser/parser.v
- vlib/v/tests/comptime/comptime_if_at_expr_test.v
- vlib/v/tests/comptime/comptime_match_at_expr_test.v
This PR enable top level `$match`.
Add @token support in `$if` and `$match`.
So we can write code such as :
```v
$match $OS {
'linux' {
import mymodule_linux
}
'windows' {
import mymodule_windows
}
'macos' {
import mymodule_macos
}
$else {
import mymodule_default
}
}
```
Top level comptime `$if` or `$match` only support @token `@MOD` `@OS` `@CCOMPILER` `@BACKEND` or `@PLATFORM` right now.
I am not sure other @token is useful or not at top level: `@VROOT`, `@VMODROOT`, `@VEXEROOT`, `@FN`, `@METHOD`, `@STRUCT`,
`@VEXE`, `@FILE`, `@DIR`, `@LINE`, `@COLUMN`, `@VHASH`, `@VCURRENTHASH`, `@VMOD_FILE`,
`@VMODHASH`, `@FILE_LINE`, `@LOCATION`, `@BUILD_DATE`, `@BUILD_TIME`, `@BUILD_TIMESTAMP`
> parser,checker: add top level comptime match support

- vlib/builtin/builtin.v
- vlib/v/checker/comptime.v
- vlib/v/gen/c/comptime.v
- vlib/v/tests/comptime/comptime_for_test.v
- vlib/v/type_resolver/comptime_resolver.v
Add is_embed to the FieldData struct accessed when iterating over the fields of a struct using comptime for. This is required to effectively en/decode embedded structs.
Example:
```v
struct Inner {
a int
}
struct Outer {
Inner 
b int
}
fn main() {
$for field in Outer.fields {
if field.is_embed {
}
}
}
// output: Inner
```
> builtin, checker, cgen: expose is_embed in FieldData

- vlib/v/checker/fn.v
- vlib/v/checker/tests/fn_call_arg_multi_err.out
- vlib/v/checker/tests/fn_call_arg_multi_err.vv
> checker: fix multi return var passing to fn arg

- vlib/builtin/builtin_windows.c.v
On Windows, SetThreadName traditionally raises exception 0x406D1388 to set a thread name in the debugger. This exception is harmless and serves only as a debugging aid.Certain libraries might raise this exception and crash the program; it should be ignored or filtered.
> builtin: fixed the thread naming issue by using RaiseException (0x406D1388) on windows.

- vlib/builtin/int_test.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/testdata/globals_with_weak_tag.c.must_have
Fix issue #25269
As `msvc` need a `LL` postfix for big IntegerLiteral, without this `LL` postfix, it will save the IntegerLiteral in a 32bit register.
`-2147483649` => `-2147483649LL`.
> cgen: fix big IntegerLiteral LL postfix

- vlib/v/gen/c/cgen.v
- vlib/v/tests/modules/sub/global_fixed_array_test.v
Fix issue #25291
In `msvc`,  initializer for the global array uses compound literals (which are not constant expressions in C) and also uses a cast-like syntax that is not allowed in constant expressions.
And this PR also enable `i32` in the check.
```c
Array_fixed_main__DummyStruct_2 _const_main__f = {(main__DummyStruct){.dummy_item = 0,}, (main__DummyStruct){.dummy_item = 0,}}; // fixed array const
```
=>
```c
Array_fixed_main__DummyStruct_2 _const_main__f = {{.dummy_item = 0,}, {.dummy_item = 0,}}; // fixed array const
```
> cgen: fix fixed-array const initializer

- vlib/v/gen/c/cgen.v
- vlib/v/tests/sumtypes/sumtype_empty_struct_test.v
- vlib/x/json2/types.v
> cgen: fix generic cast to sumtype of empty struct (fix #25263)

- examples/rune.v
This PR fixes examples/rune.v by using the correct cast, instead of bytes.
> examples: rune.v fix rune casting u32

- vlib/builtin/map.c.v
- vlib/v/gen/c/cgen.v
- vlib/v/tests/enums/map_with_enum_keys_test.v
> builtin,cgen: fix i64 enum as a map key, when the enum values are too small (fix #25294)

- vlib/x/crypto/chacha20/bench/bench.v
- vlib/x/crypto/chacha20/chacha.v
- vlib/x/crypto/chacha20/chacha_test.v
- vlib/x/crypto/chacha20/stream.v
- vlib/x/crypto/chacha20/stream_test.v
- vlib/x/crypto/chacha20/xchacha.v
Motivated by [this](https://discord.com/channels/592103645835821068/592320321995014154/1416424355046621244) benchmark thread, this PR contains several changes made into internal of `x.crypto.chacha20` module.
The changes included:
- rewrites the core of chacha20 quarter round to reduce allocation. Its defines several internal structure and helpers to accomply this.
- split out and delegates some part of internal `chacha20.Cipher` into dedicated own structures, in the mean of `Stream` opaque. This opaque handles of  heavyweight part of chacha20 stream implementation. The old `Cipher` focus on public part of the api and `xor_key_stream` functionality.
- rewrites precomputed counter-independent of quarter-round values using the new approach.
- rewrites and reorganizes accross the module to …
> x.crypto.chacha20: improves internal of chacha20

- vlib/v/gen/c/auto_free_methods.v
- vlib/v/gen/c/testdata/free_for_struct_with_c_fields.c.must_have
- vlib/v/gen/c/testdata/free_for_struct_with_c_fields.out
- vlib/v/gen/c/testdata/free_for_struct_with_c_fields.vv
- **cgen: restore old behaviour for `struct Name{field &C.FILE};i:=Name{};unsafe{i.free()}` (fix #25325)**
- **add test**
> cgen: restore old behaviour for `struct Name{field &C.FILE};i:=Name{};unsafe{i.free()}` (fix #25325)

- vlib/time/parse.c.v
- vlib/time/parse_test.v
- vlib/toml/checker/checker.v
Fixes issue https://github.com/vlang/v/issues/25272 for parsing dates in format rfc3339.
- Accepts `t` and ` ` (space) as alternatives to default date time separator `T`.
- Continue accepting `z` as alternative of default `Z` for timezone zero.
- Reject (as golang does) not complete date-time strings or without timezone.
- Fix panic in fractions of second without `Z`.
Revised function `time.parse_rfc3339(string) !time.Time` can be used as simple and unique format for `json2.Any.to_time()` of type `string`.
> time: make parse_rfc3339 accept `t`, and space, in addition to `T`, reject incomplete date-times and such with no timezone

- vlib/flag/flag.v
- vlib/flag/flag_autofree_test.v
Fixes #9815.
It seems to me like calling these frees on `f.args` frees `os.args` only on `-autofree`? Not sure why that would happen since `os.args` is always cloned.
I set it to `@[manualfree]` here but it might actually end up leaking some memory since the `new_flag_parser` function creates some clones, but it was preferable to freeing the variables before (and after) returning them?
A few flag tests still fail with autofree but not in a way related to this issue.
> autofree,flag: fix double free in FlagParser free

- vlib/v/checker/tests/wrong_muti_dim_arr_declare_err.out
- vlib/v/checker/tests/wrong_muti_dim_arr_declare_err.vv
- vlib/v/parser/parse_type.v
Fix issue #25333
Terminate the array type scan after parser got an element type, do not scan further `[]` pairs.
I think this is a code snippet left behind from the early stages for detecting multidimensional arrays with legacy syntax.
> parser: detect wrong multi-dim arr declare

- vlib/builtin/int.v
- vlib/builtin/js/int.js.v
- vlib/v/ast/ast.v
- vlib/v/ast/types.v
- vlib/v/checker/check_types.v
- vlib/v/checker/checker.v
- vlib/v/checker/containers.v
- vlib/v/checker/match.v
- vlib/v/gen/c/auto_str_methods.v
- vlib/v/gen/c/cgen.v
- vlib/v/gen/c/str_intp.v
- vlib/v/gen/js/builtin_types.v
- vlib/v/gen/js/js.v
- vlib/v/gen/native/amd64.v
- vlib/v/gen/native/gen.v
- vlib/v/gen/wasm/ops.v
Replace `(arm64 || amd64 || rv64 || s390x || ppc64le || loongarch64)` with `x64`.
In `cgen`, `x64` comptime ident will generate following code:
```c
#if INTPTR_MAX == INT32_MAX
#define TARGET_IS_32BIT 1
#elif INTPTR_MAX == INT64_MAX
#define TARGET_IS_64BIT 1
#else
#error "The environment is not 32 or 64-bit."
#endif
...
#if defined(TARGET_IS_64BIT)
{
println(_S("x64"));
}
#endif
```
This should be a better way detect the compile environment  is 64-bit or not.
And this will help compile 32bit `int` on an 64bit environment.
And also, it is much shorter. :)
> v: cleanup, replace complex 64bit CPU comptime ident with `&& x64`

- vlib/x/crypto/chacha20/chacha.v
- vlib/x/crypto/chacha20/chacha_64bitctr_test.v
- vlib/x/crypto/chacha20/chacha_test.v
- vlib/x/crypto/chacha20/stream.v
- vlib/x/crypto/chacha20/stream_test.v
- vlib/x/crypto/chacha20/xchacha_test.v
- vlib/x/crypto/chacha20poly1305/chacha20poly1305.v
This small patch fix internal counter handling after rewrites the internal of `x.crypto.chacha20`. The counter increments phase not be adjusted to align with the changes and leads to the bug in [25318](https://github.com/vlang/v/issues/25318).
In my test for `firebird` by @einar-hjortdal, it pass successfully,
```bash
---- Testing... ------------------------------------------------------------------------------------------------------
OK    [1/5] C:   645.2 ms, R:     2.047 ms /workspaces/firebird/protocol_test.v
OK    [2/5] C:   613.6 ms, R:     2.126 ms /workspaces/firebird/protocol_utils_test.v
OK    [3/5] C:   606.7 ms, R:    69.396 ms /workspaces/firebird/secure_remote_password_test.v
OK    [4/5] C:   746.3 ms, R:   603.540 ms /workspaces/firebird/statement_test.v
OK    [5/5] C: …
```
> x.crypto.chacha20: fix internal counter handling

- vlib/v/gen/c/cgen.v
- vlib/v/tests/interfaces/interface_mut_value_update_test.v
Fixes #25354.
Maybe in the future we would like to not heap allocate `i` and `f`? Seems kind of unnecessary.
> cgen: fix interface heap allocate pointing to same value

- examples/get_weather/README.md
- examples/get_weather/get_weather.v
- Use json2 to parse weather data. Leave in struct only relevant fields.
- I took the liberty adding translation for the original texts. Parse translation response with `json2.Any` arrays.
> examples: get_weather use json2 and add translation

- vlib/x/crypto/chacha20/README.md
- vlib/x/crypto/chacha20/chacha.v
- vlib/x/crypto/chacha20/chacha_test.v
- vlib/x/crypto/chacha20/stream.v
- vlib/x/crypto/chacha20/stream_test.v
- vlib/x/crypto/chacha20/xchacha.v
- vlib/x/crypto/chacha20/xchacha_test.v
This patch expands eXtended ChaCha20 construction to support for 64-bit counter, completes support for the existing 32-bit counter construct.
@spytheman, @tankf33der: can you look into it ?
Cheers,
thanks
> x.crypto.chacha20: expands xchacha20 construction to support for 64-bit counter

- vlib/v/ast/table.v
- vlib/v/ast/table_test.v
- vlib/v/ast/types.v
Allow update existing symbol via call `update_sym()`.
a use case:
To support the new array syntax, we need to update the fixed-arrays size after scan the array lit. For example, 
```v
[..][..]int[[1 2][3 4]]
```
When parse this, we don't known the size of the fixed-array first, but register a `[-1][-1]int` symbol in the system.
And then after scan the array lit, `[[1 2][3 4]]`, we can update the existing `[-1][-1]int` symbol to `[2][2]int`.
> v.ast: add Table.update_sym_by_idx/2

- vlib/x/crypto/ascon/aead128.v
Currently, decryption is broken due to a trivial typo.
Here is the line in reference [implementation](https://github.com/ascon/ascon-c/blob/main/crypto_aead/asconaead128/ref/aead.c#L208) that can be easily compared to spot the typo.
Test will be added in the next PR when encryption will be fixed too.
> x.crypto.ascon: fix decryption

- vlib/os/os.v
- vlib/os/os_nix.c.v
Return the error code from `os.ls/1` and `os.mkdir_all/1` to enable detailed error handling e.g. you can now differ ENOENT (no such file or directory) and other possible I/O errors:
```
>>> os.ls('/nonexistent') or { println(err.code()) }
2
>>> os.rmdir_all('/nonexistent') or { println(err.code()) }
2
```
> os: propagate POSIX error code from os.ls/1 and os.rmdir_all/1 on UNIX-like systems

- vlib/net/websocket/handshake.v
fix that makes custom headers during ws client handshake actually valid
if for example a server requires the `Origin` header to be set, before this fix, said server would've denied the connection even if the value was correct and the header was there, just because the header isn't valid, but now since it's valid it no longer fails
i didn't make a specific test for this fix in particular because it just adds a space to a string and the only valid testing option i know of is a very specific domain (not local) and i wouldn't want to have an external connection in a test like that
> net.websocket: fix incorrect formatting for custom headers during handshake

- vlib/v/checker/containers.v
- vlib/v/parser/parse_type.v
- vlib/v/tests/complex_dim_fixed_array_test.v
Fix issue #25404
BTW, I think we should remove `eval_array_fixed_sizes()` from `parser`. Because in `parser`, it has no full information, for example, `[2][const_a - sizeof(T)]int{}`, `sizeof(T)` is ready in `checker`. And `checker` also has it's own `eval_array_fixed_sizes()`.
> parser: fix eval fixed array size

- vlib/x/crypto/chacha20poly1305/chacha20poly1305.v
- vlib/x/crypto/chacha20poly1305/xchacha20poly1305_test.v
This patch enables supports for underlying variant already supported by `x.crypto.chacha20` module, like a supports for 64-bit counter with 8-bytes nonce, and experimental features of extended construct with 64-bit counter.
This patch contains:
- Enables support for original 64-bit counter with 8-bytes nonce.
- Enables a `chacha20.Options` in the constructor and encryption routines to pass an option into underlying chacha20 constructor.
- Unifies generic `encryption` and `decryption` routines into single one, its already shares a common thing.
- Add a test material for `XChaCha20Poly1305` construct, adapted from `pycryptodome` vector tests
- Some bits of cleanup
@tankf33der: can you take a look into it?
NB: This is my latest bench run of `vlib/x/crypto/ascon/bench/aead.v`
```bash …
```
> x.crypto.chacha20poly1305: enables support for (x)chacha20 with 64-bit counter construct

- vlib/v/checker/fn.v
- vlib/v/checker/tests/sumtype_array_to_variadic.out
- vlib/v/checker/tests/sumtype_array_to_variadic.vv
- vlib/v/tests/fns/call_args_variadic_sumtype_test.v
- vlib/v/tests/fns/variadic_sumtype_test.v
Fixes #25424.
When passing an array of sumtype to a function taking a vararg, the `...` prefix was not required which caused a cgen error. 
This makes sure the `...` prefix is required for arrays.
The check is a bit long so let me know if there's a simpler way.
> checker: always use ... prefix when passing array to vararg

- vlib/x/crypto/chacha20/chacha_test.v
- vlib/x/crypto/chacha20/stream.v
- vlib/x/crypto/chacha20/xchacha.v
- vlib/x/crypto/poly1305/poly1305.v
While have a working prototype implementation of `ChaCha20-Poly1305-PSIV` construct, its used an internal of `chacha20` by rewriting it as a new routine, makes it a duplicated in a lot places. I think its should be a public to make it reusable thing. See the working implementation of this construct at [here](https://github.com/blackshirt/v/blob/psiv/vlib/x/crypto/chacha20poly1305/psiv.v).
By making it accessible outside the module, its make possible to expand by new construction based on this state, like above psiv construct or possibility of [this](https://arxiv.org/pdf/2507.18157v11). This also mean reduces code duplication.
This patch was related to previously merged PR [#25438](https://github.com/vlang/v/pull/25438), but comes with the changes on the `chacha20` sides..
Its exposes …
> x.crypto.chacha20: mark `State` as public to make it a reusable thing

- vlib/builtin/int.v
Fix issue #25457 
test will be integrated in PR #25442
> builtin: fix int.str_l() integer overflow
