README.md

readme: simpler bootstrap test

---

vlib/vweb/vweb.v

This pr adds handling for the expire date in the new set_cookie function

vweb: implement usage for expire date in new cookie function

---

vlib/v/gen/cgen.v
vlib/v/tests/array_init_test.v

cgen: fix array of fns init

---

cmd/tools/vpm.v
cmd/v/help/default.txt
cmd/v/v.v

Use `v list` to see all installed modules

vpm: add list command

---

examples/quick_sort.v

Generics is finally fixed so I could update this example.

example: make quick_sort generic

---

vlib/v/checker/checker.v
vlib/v/checker/tests/unknown_var_assign.out
vlib/v/checker/tests/unknown_var_assign.vv
vlib/v/parser/parser.v

checker: suggest using `:=` when assigning to undefined variable

---

vlib/v/gen/cgen.v
vlib/v/tests/map_and_array_with_fns_test.v

This PR
a. simplifies previous code by adding write_fn_ptr_decl function.
b. fixes `for in array/map with fns` bug and adds tests.

cgen: further fix and refactor array and map with fn

---

doc/docs.md

doc: document range match branch syntax

---

doc/docs.md

Fix #5925 
Fixed compile error
I confirmed to pass the compile.

doc: Fix example program for array in doc/docs.md

---

vlib/builtin/builtin_nix.c.v
vlib/builtin/sorted_map.v
vlib/builtin/string.v
vlib/builtin/utf8.v
vlib/encoding/base64/base64.v
vlib/encoding/utf8/utf8.v
vlib/net/websocket/handshake.v
vlib/net/websocket/utils.v
vlib/net/websocket/ws.v
vlib/os/environment.v
vlib/os/os.v
vlib/os/os_nix.c.v
vlib/os/os_windows.c.v
vlib/rand/rand.v
vlib/regex/regex.v
vlib/v/checker/checker.v
vlib/v/checker/tests/unsafe_required.out
vlib/v/checker/tests/unsafe_required.vv
vlib/v/util/util.v

Finishes work started in merged #5836.

v/checker: Warn about pointer indexing outside unsafe {}

---

vlib/v/checker/checker.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/expressions_expected.vv

This PR is a minor improvement for `vfmt`.

fmt: give braced sub expressions higher priority

---

vlib/v/gen/cgen.v

Ran into this one in vapor a while back and had my fix locally for a long time, forgetting to push it. This properly handles returning optional multi returns inside of optional multi returns an example of this can be found in emily33901.vproto
```v
pub fn unpack_bytes_field(buf []byte, wire_type WireType) ?(int,[]byte) {
ensure_wiretype(wire_type, .length_prefixed)?
return bytes_unpack(buf)
}
pub fn unpack_message_field(buf []byte, wire_type WireType) ?(int,[]byte) {
return unpack_bytes_field(buf, wire_type)?
}
```
This wouldnt compile before because `g.expr()` on the optional would generate the whole opt checking code aswell which broke my expectation that it would just be the function call. This is now handled.

cgen: Properly handle more multi-return edge cases

---

cmd/v/help/build-c.txt
vlib/builtin/cfns.c.v
vlib/os/os.v
vlib/v/builder/cc.v
vlib/v/gen/cgen.v
vlib/v/parser/comptime.v
vlib/v/pref/os.v
vlib/v/pref/pref.v

* Needs XCode to be installed in the system
* Requires v.c to be regenerated to support 'if $ios'
* make selfcompile; ./v -os ios hello.v

Initial support for iOS crosscompilation

---

vlib/v/gen/comptime.v
vlib/v/parser/comptime.v
vlib/vweb/vweb.v

This PR adds, that comp for use attrs as string array instead of a string. I also changed the vweb router that the compilation works

parser: comp for use attrs as string array

---

doc/docs.md

Add subheadings.
Change 2 examples to use `+= 2` to show flexibility over range for.

docs: Document `for v in low..high {` and tweak `for` docs

---

vlib/v/checker/checker.v

run fmt on checker.v

---

vlib/net/websocket/ws.v
vlib/net/websocket/ws_test.v

Maybe it's not correct test and wait an remote backend instead of a dummy, but it's better than nothing.

ws: add tests

---

vlib/builtin/int_test.v
vlib/v/scanner/scanner.v

Now these are invalid as they have no sense 
```
1__2
11_
0b0__1
0b011_
0o2_
etc..
```

scanner: more checks for `_` as num_sep

---

vlib/net/http/http.v
vlib/net/http/method.v

http: str() all of the methods

---

vlib/net/websocket/README.md

Update readme with the doed things
@thecodrr I don't know if the actual test supplies the AutoBahn test client, please I need your opinion and the TODOs to complete it, thanks by advance!

ws: update README.md

---

tutorials/building-a-simple-web-blog-with-vweb.md

some code snippets cannot be complied or run error

docs: fix bugs

---

vlib/net/websocket/ws.v

Add an getter to know the state of the ws

ws: make pub mut: state

---

examples/eventbus/modules/some_module/some_module.v
vlib/math/unsafe.v
vlib/rand/mt19937/mt19937.v
vlib/sokol/gfx/gfx_structs.v
vlib/sync/pool.v
vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/checker/tests/return_ref_as_no_ref_bug.out
vlib/v/checker/tests/return_ref_as_no_ref_bug.vv
vlib/v/doc/doc.v
vlib/v/table/atypes.v
vlib/v/tests/generics_test.v

checker: add error for `fn f() Struct { return &Struct{} }`

---

vlib/vweb/vweb.v

vweb: fix request checking

---

doc/docs.md

After reading the manual I didn't grasp how to use generic functions as the current example mixes in generic structs.
I think it's a good idea to include more "pure" example of the generic function:
```v
fn compare<T>(a, b T) int {
if a < b {
return -1
}
if a > b {
return 1
}
return 0
}
println(compare<int>(1,0)) // Outputs: 1
println(compare<int>(1,1)) //          0
println(compare<int>(1,2)) //         -1
println(compare<string>('1','0')) // Outputs: 1
println(compare<string>('1','1')) //          0
println(compare<string>('1','2')) //         -1
println(compare<float>(1.1, 1.0)) // Outputs: 1 
println(compare<float>(1.1, 1.1)) //          0
println(compare<float>(1.1, 1.2)) //         -1
```

doc: another generics example

---

vlib/v/gen/js/js.v

jsgen: don't generate `JS.` struct decls

---

vlib/log/log.v
vlib/os/file.v
vlib/os/os.v
vlib/os/os_linux.c.v
vlib/os/os_nix.c.v
vlib/os/os_windows.c.v

The main objective of this PR is to split the size of os/os.v (to make it an little bit more clean), by the moment moving the struct File and her things to file os/file.v
Make C calls inside unsafe

os: split component

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/fntype_return_optional_expected.vv
vlib/v/fmt/tests/fntype_return_optional_input.vv

Fixes https://github.com/vlang/v/issues/6040

fmt: fix #6040

---

vlib/hash/wyhash.v

Use a match expression instead of a long if/else if chain.

hash/wyhash.v: Use match expression with ranges

---

doc/docs.md

I've added an example of a 2d array:
```v
mut a := [][]int{len:2}
a = a.map([]int{len:3})
a[0][1] = 2
println(a) // [[0, 2, 0], [0, 0, 0]]
```

doc: 2d array example

---

vlib/v/builder/msvc.v

builder: don't panic if msvc rootdir isn't found

---

.github/ISSUE_TEMPLATE/bug_report.md

This'll help lower the number of invalid issues filed

Added a hint to the issue template

---

doc/docs.md

There was no information in the docs about variadic functions.
I've added the following example:
```v
fn sum(a ...int) int {
mut total := 0
for x in a {
total += x
}
return total
}
println(sum())    // Output: 0
println(sum(1))   //         1
println(sum(2,3)) //         5
```

doc: variadic function example

---

vlib/builtin/array.v
vlib/builtin/bare/mm_bare.v
vlib/builtin/builtin.v
vlib/builtin/cfns.c.v
vlib/builtin/map.v
vlib/builtin/string.v
vlib/os/os.v
vlib/picohttpparser/misc.v
vlib/v/builder/compile.v
vlib/v/parser/fn.v
vlib/v/parser/parser.v
vlib/v/tests/unsafe_test.v

~~Draft, depends on #6066 - `[unsafe]` should be used instead.~~

v/parser: Error on `[unsafe_fn]`

---

vlib/vweb/vweb.v

vweb: fix body size calculation

---

vlib/v/gen/cgen.v
vlib/v/tests/anon_fn_test.v

cgen: fixes calling anon fn asynchronously

---

vlib/json/json_test.v
vlib/v/gen/fn.v
vlib/v/gen/json.v

Fixes #3367 
Also fixes a leaking  json object when decoding array
Testing code:
```V
import json
struct Nested1 {
item1	string
item2	string
}
struct Nested2 {
item1	int
item2	bool
}
struct Top {
mut:
mp1	map[string]int
nes1	map[string]Nested1
nes2	Nested2
}
fn main() {
mut tp := Top{}
tp.mp1['int example'] = 2
tp.nes1['struct example'] = Nested1{
item1: 'string1',
item2: 'string2',
}
tp.nes2 = Nested2{
item1: 39,
item2: true,
}
str := json.encode(tp)
tp2 := json.decode(Top, str) or { panic(err) }
assert tp.str() == tp2.str()
}
```

json: maps, memory leak, and error forwarding

---

vlib/term/README.md

I noticed that there was no proper documentation for the term module, so i opened an issue and was tasked to do the task myself, so here it is. 
I documented the term library and explained most of it's functions for a lambda user

term: add documentation

---

vlib/v/checker/checker.v
vlib/v/gen/cgen.v
vlib/v/parser/if_match.v
vlib/v/tests/if_smartcast_test.v

all: fix mutability after if-smartcast

---

cmd/tools/vpm.v
cmd/v/help/default.txt
cmd/v/v.v

Add 'vpm upgrade' to update all the outdated vpm modules

---

examples/2048/main.v
examples/tetris/tetris.v
vlib/gg/gg.v
vlib/gg/text_rendering.v
vlib/gx/text.v
vlib/os/os_android.c.v
vlib/sokol/sapp/sapp.v
vlib/v/parser/parser.v

This PR adds some functions to `gg` to allow [my fork of the 2048 example](https://github.com/spaceface777/v2048) to build. It also adds some necessary steps for Android support. 
Note that to build an APK successfully, @Larpon 's great work [here](https://github.com/Larpon/v/commit/4a66d94e9aa2e8c54a1c372920fc5f1ac85f8c90) and [here](https://github.com/Larpon/v-android-bootstrap) is still required. Maybe we can turn the build script into a `.vsh` and merge it into V at some point.

gg: fixes and Android support

---

examples/cli.v

examples/cli: more readable and informative program output

---

doc/docs.md

docs #conditional compilation: add $else

---

vlib/clipboard/clipboard_windows.c.v

clipboard_windows: wrap pointer indexing in unsafe block

---

vlib/v/checker/checker.v
vlib/v/gen/cgen.v

checker: fix sort return type

---

examples/net_raw_http.v
vlib/x/net/aasocket.c.v
vlib/x/net/address.v
vlib/x/net/common.v
vlib/x/net/errors.v
vlib/x/net/net_nix.c.v
vlib/x/net/net_windows.c.v
vlib/x/net/socket_options.c.v
vlib/x/net/tcp.v
vlib/x/net/tcp_test.v
vlib/x/net/udp.v
vlib/x/net/udp_test.v
vlib/x/net/util.v

This PR is the inital work for merging emily33901/vlang-net into vlib.
The old websocket lib has been removed because I don't see a massive reason to fix it if @helto4real's lib is going to be taking its place anyway. I have fixed up http but I have not made an attempt to fix the SMTP or FTP libs (since I dont really know enough from the top of my head to reason about what is going on there).

vlib/net: merge emily33901/vlang-net into vlib/net

---

vlib/x/openssl/openssl.v

Removed println debugging leftovers

x.openssl: remove printlns

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/gen/cgen.v
vlib/v/tests/fixed_array_test.v

cgen: implement fixed array `.len` property

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/parser/comptime.v
vlib/v/util/util.v

compiler: move flag logic to checker

---

cmd/tools/vbin2v.v

Silences warning about having uppercase letters in constants should the filename or prefix contain any.

bin2vr: to_lower() the const names

---

doc/docs.md

doc: fix a typo

---

vlib/x/websocket/websocket_client.v

Removed println debugging leftovers

x.websocket: remove debuging leftover

---

vlib/v/gen/fn.v

This was requested a few times on Discord recently; it's useful if you want to use V to create shared libraries and you don't control the function names they import.

cgen: implement the `[export: 'FooBar']` attribute

---

doc/docs.md

**Earlier:** Note the (important) difference between `:=` and <ins>**`=` `:=`**</ins> is used ...
**Now:** Note the (important) difference between`:=` and <ins>**`=`. `:=`**</ins>is used ...

Docs: Add period(.) in Initialization vs assignment 

---

examples/terminal_control.v
vlib/readline/readline_linux.c.v
vlib/term/README.md
vlib/term/control.v
vlib/term/term.v
vlib/term/term_nix.c.v
vlib/term/term_test.v
vlib/term/term_windows.c.v

// get_cursor_position returns a Coord containing the current cursor position
```
cursor_position := term.get_cursor_position()
println('x: $cursor_position.x')
println('y: $cursor_position.y')
```
```
title_change := term.set_terminal_title('v is awesome')
println('Title changed: $title_change')
```
tests have been added to ./vlib/term/term_test.v

term: feature terminal functions

---

vlib/x/json2/README.md
vlib/x/json2/builder.v
vlib/x/json2/decoder.v
vlib/x/json2/encoder.v
vlib/x/json2/json2.v
vlib/x/json2/json2_test.v

This is the revised PR from the closed #5582 but instead as an experimental module alongside the original `json` module. The module was named `json2` in order to avoid any unwanted conflicts with the Cgen's special `json` codegen.
Most of the tests for the said module are disabled for now.

vlib: Add x/json2

---

examples/2048/2048.v

Allowing a move where no tiles change is not a legal move. This commit
checks to see if a move is illegal before generating a new tile.
Also, the game-over and victory screens now display the score.

2048: fixed movement bug and show score at end

---

.github/workflows/ci.yml

Temporary remove autobahn tests to fix the websocket code to work with latest autofree changes.

CI: Temporary remove ws autobahn tests 

---

.github/workflows/ci.yml
vlib/x/websocket/tests/autobahn/ws_test/Dockerfile

This PR re-enable autobahn tests but it has autofree removed.

ci: re-enable autobahn tests (without autofree)

---

cmd/v/help/build-c.txt
cmd/v/help/build.txt
cmd/v/help/doc.txt
cmd/v/help/fmt.txt
cmd/v/help/test.txt

help text: remove note about v2 backend

---

doc/docs.md

docs: clarify about strings immutabilitiy

---

doc/docs.md

Fix typo in the primitive types descrtiption.

doc: fix typo

---

cmd/tools/vpm.v

vpm outdated: support for mercurial

---

doc/docs.md

doc: simplify string mutability section

---

cmd/tools/vup.v

PR made for me, so I can see the version of V with `v up` :D

/cmd/tools/vup.v: Add quotes for the people with weird V paths.

---

vlib/vweb/vweb.v

vweb: make ip() to return peer_ip work

---

vlib/v/ast/ast.v
vlib/v/checker/check_types.v
vlib/v/checker/checker.v
vlib/v/checker/tests/is_type_invalid.out
vlib/v/checker/tests/is_type_invalid.vv
vlib/v/checker/tests/match_sumtype_type_invalid.out
vlib/v/checker/tests/match_sumtype_type_invalid.vv
vlib/v/fmt/fmt.v

Check that the type on the right of an `is` infix expression is a sub-type of the expression on the left.

checker: check type in `is` InfixExpr

---

vlib/v/checker/check_types.v
vlib/v/checker/checker.v
vlib/v/checker/tests/infix_err.out
vlib/v/checker/tests/infix_err.vv

Draft until test added.
Fixes #6392.

checker: disallow infix op on an optional type

---

doc/docs.md

Fixed some typos and some phrasing.

doc: fix typos

---

vlib/v/gen/cgen.v

https://stackoverflow.com/questions/6990569/comparison-of-unsigned-expression-0-is-always-true/6990576#:~:text=Yes%20%2D%20since%20length%20returns%20an,You%20can%20delete%20the%20status.&text=If%20you%20want%20to%20make,length%20%3E%200%20.

gen: c don't generate >= 0 check on unsigned integers

---

vlib/readline/readline_linux.c.v
vlib/v/util/util.v

**Additions**:
Fix the "put to background" CTRL+Z keypress
**Notes**:
Fixes #2638 
Fixes #5859 
**Examples**:

repl: fix ctrl+z job to background

---

vlib/os/const_nix.c.v
vlib/os/const_windows.c.v
vlib/os/os.v
vlib/os/os_test.v

Added binary file mode on windows
Fixes #6430

Fixed binary mode read/write

---

doc/docs.md

Update the Module import example in vdocs (docs.md)
The existing sample code gives the impression that there should be at least one file in each module whose name matches the module's name. Which is not the case. Hence suggesting the modification.

vdoc: update the module import example in docs.md

---

.github/workflows/ci.yml
cmd/tools/vdoctor.v

doctor: detect if running in a VM / WSL / chroot

---

cmd/tools/vdoc.v

**Additions**:
V Docs is slow and has a big memory usage, some optimizations are needed.

vdocs: rendering optimizations

---

vlib/v/checker/check_types.v
vlib/v/gen/auto_str_methods.v
vlib/v/gen/cgen.v
vlib/v/tests/sumtype_str_test.v

This implements str() generation for sumtypes.
TODO:

cgen: implement sum type str gen

---

vlib/flag/flag.v
vlib/flag/flag_test.v

Fixed flag module

---

vlib/builtin/string_test.v
vlib/v/gen/str.v

Escape string function in gen/str.v

---

vlib/v/checker/checker.v

checker: fix comp. if branch logic

---

vlib/gg/gg.v

gg: don't call `os.is_file()` on Android

---

vlib/flag/flag.v
vlib/flag/flag_test.v

flag: fix panic if flag value was not provided

---

vlib/time/time.v
vlib/time/time_linux.c.v
vlib/time/time_nix.c.v

time: use linux high-precision timers on Android as well

---

cmd/tools/vdoctor.v

- display the number of commits behind V master if > 0
- show a better OS details line on Windows
- simplify and make parse() an independent function

doctor: small features and tweaks

---

doc/docs.md

Explain asserts.
Reformat sentences, tweak wording.
Explain other symbols can be defined in test files.

doc: improve Testing section

---

doc/docs.md

Tweak wording & formatting.
Add subheading for `init` functions.

doc: tweak Modules section

---

vlib/v/gen/auto_str_methods.v
vlib/v/tests/str_gen_test.v

gen: print empty struct with less space

---

examples/2048/2048.v

There's now a freeplay mode as well, and I've possibly forgotten other small things.
The wasm build (https://v2048.vercel.app) has been updated to this PR for testing.

examples/2048: new end screens with alpha, better touch support

---

examples/sokol/particles/modules/particle/particle.v
examples/sokol/particles/modules/particle/system.v
examples/sokol/particles/particles.v

This PR will let particles in the example gradually fade towards the color behind them based on their life span.
(Dead particles will still give a short red spark)

examples: add support for opacity / alpha in particle example

---

cmd/v/help/help.v

Hi! I believe it's better to write an error here in stderr.

help: print errors to stderr

---

doc/docs.md

Seems `Interfaces` section example is missing `breed` field for `Dog` struct. Also, there's a small indentation problem within the example.

Docs: fix Interfaces example

---

vlib/cli/help.v

cli: fix minor newline error

---

cmd/tools/vpm.v
vlib/os/os.v
vlib/v/pref/default.v

os: home_dir() remove trailing slash

---

vlib/v/checker/checker.v
vlib/v/checker/tests/match_sumtype_multiple_types.out
vlib/v/checker/tests/match_sumtype_multiple_types.vv
vlib/v/gen/js/js.v
vlib/v/parser/if_match.v
vlib/v/table/atypes.v
vlib/v/table/table.v
vlib/v/tests/match_test.v

parser: allow multiple types in match branch

---

doc/docs.md

some phrasing and whitespace clean up for the "Hello world" section

doc: fix phrasing and whitespace

---

examples/v_script.vsh

examples: make v_script.vsh compile and slightly improve it

---

examples/tetris/tetris.v

Trivial enhancement to Tetris example, displaying a "ghost" of the current tetro,
at the place it would land if we would be hitting the "drop" key.

tetris: add ghost

---

vlib/v/gen/auto_str_methods.v
vlib/v/tests/sumtype_str_test.v

custom str method were ignored before

Fix sumtype custom str

---

examples/tetris/tetris.v

Trivial tetris enhancement to display next tetro

tetris: display next tetro

---

examples/tetris/tetris.v

Trivial enhancement to tetris to display total number of eliminated lines

tetris: display lines

---

vlib/v/checker/checker.v
vlib/v/checker/tests/chan_mut.out
vlib/v/checker/tests/chan_ref.out

checker: fix msg for chan

---

vlib/v/table/table.v

**Additions**:
Fix indentations from spaces to tabs introduced in de77f0b that is causing all CIs to fail

parser: fix indentation to tabs

---

vlib/builtin/builtin.v
vlib/builtin/builtin_windows.c.v
vlib/builtin/string.v
vlib/rand/rand.v
vlib/sokol/sapp/sapp.v
vlib/v/parser/parser.v

**Additions**:
Remove the handling of the old global syntax (Was handled as an intermediate PR)
Updates all global definitions inside the V Compiler codebase

syntax: remove intermediate handling for both global definition syntaxes

---

vlib/pg/pg.v

Commands executed on the database server can end with an error state, and this PR make the error state immediately detectable by using an optional type instead of just printing the error message to stdout and returning a default value.

pg: `exec`, `q_int` and `q_strings` return an optional

---

vlib/v/gen/str.v

Use string builder to increase speed of c gen.
Old pull request #6452

Updated to use string builder

---

vlib/cli/command.v
vlib/crypto/internal/subtle/aliasing.v
vlib/regex/regex.v
vlib/strconv/f32_str.v
vlib/strconv/f64_str.v
vlib/sync/channels.v
vlib/v/builder/generics.v
vlib/v/checker/checker.v
vlib/v/compiler_errors_test.v
vlib/v/gen/cgen.v
vlib/v/table/table.v
vlib/v/tests/unsafe_test.v

checker: disallow address of array and map index outside unsafe

---

vlib/v/checker/checker.v
vlib/v/checker/tests/assign_multi_immutable_err.out
vlib/v/checker/tests/assign_multi_immutable_err.vv

checker: error if assigning to a function

---

cmd/tools/vcreate.v

For developers who develop for Windows it will be useful

vcreate: gitignore executable files

---

vlib/vweb/assets/assets_test.v

vweb: fix/remove todos from assets tests

---

vlib/gg/gg.v

Adding draw_circle(), draw_circle_line(), draw_arc() and finally draw_arc_line()

gg: add draw_circle and draw_arc functions

---

vlib/crypto/hmac/hmac.v
vlib/crypto/hmac/hmac_test.v

Add HMAC: Keyed-Hashing for Message Authentication functionality to crypto module

crypto: add hmac module

---

vlib/readline/readline_linux.c.v
vlib/v/ast/str.v
vlib/v/doc/doc.v
vlib/v/gen/cgen.v

More changes based on recent match statement changes.
Passes `v test-compiler` cleanly.

cleanup: more match statements

---

vlib/v/checker/checker.v
vlib/v/checker/tests/none_type_cast_err.out
vlib/v/checker/tests/none_type_cast_err.vv

Solves https://github.com/vlang/v/issues/6627

checker: disallow type casting to `none`

---

examples/word_counter/word_counter.v

Apply `TODO` suggestion in word counter example
I am just exploring `vlang` for now, let me know if you need further informations or if you see missing things.

examples: Apply todo suggestion in word counter

---

vlib/v/doc/doc.v

This PR fixes an issue where a user could not generate documentation for a 3rd-party module by running `v doc -f html .`
When `vdoc` generates a module name, it uses `vdoc.get_parent_mod` function to get a full module name, including directories (e.g. `module.submodule` for `module/submodule`). This function gets an input string (a path to the module), and search for a root directory.
The problem is the function starts searching using a base directory of the given directory, but the given directory could be a root directory in some cases.
The solution is quite simple - make the `get_parent_mod` to check if the input dir is a root directory as well.
(I intentionally omitted non-related `v doc` output)
```sh
> v doc -f html vlib/os
Generating vlib\os\os.html...
> v doc -f html vlib/v/ast …
```

vdoc: fix generating documentation for 3rd-party modules

---

README.md

Hi there, 
This PR updates the Patreon badge that was broken since I've taken the previous endpoint down last week (more info https://github.com/endel/shieldsio-patreon/issues/8)
Cheers!

update patreon badge on README

---

vlib/mysql/mysql.v
vlib/mysql/result.v

Bug: https://github.com/vlang/v/issues/6680

mysql: fix unwrapped unsafe code of mysql lib (#6680).

---

vlib/pkgconfig/README.md
vlib/pkgconfig/bin/pkgconfig.v
vlib/pkgconfig/main.v
vlib/pkgconfig/pkgconfig.v
vlib/pkgconfig/v.mod
vlib/semver/LICENSE.md
vlib/semver/README.md
vlib/semver/compare.v
vlib/semver/parse.v
vlib/semver/range.v
vlib/semver/semver.v
vlib/semver/semver_test.v
vlib/semver/util.v
vlib/semver/v.mod
vlib/v/checker/checker.v

Add #pkgconfig directive using the new vlib modules

---

doc/docs.md

pkgconfig: add some lines in docs.md

---

vlib/v/checker/check_types.v
vlib/v/gen/auto_str_methods.v
vlib/v/gen/str.v
vlib/v/tests/str_gen_test.v

```v
fn test<T>(foo T) string {
return '$foo'
}
fn main() {
t := MyStruct{}
println(test(t))
}
```
this works now.
#generics

all: make generics printable

---

vlib/mysql/_cdefs.c.v
vlib/mysql/_cdefs_nix.c.v
vlib/mysql/_cdefs_windows.c.v
vlib/mysql/mysql.v

To make "import mysql" work for Windows and FreeBSD

mysql: patch for Windows and FreeBSD

---

vlib/sqlite/readme.md

If someone happened to copy-pasted these, they would error out, since the extra backticks are for command substitution.

docs: fix syntax in sqlite install instructions

---

vlib/clipboard/clipboard_darwin.c.v
vlib/clipboard/clipboard_linux.c.v
vlib/clipboard/clipboard_solaris.c.v
vlib/clipboard/clipboard_test.v
vlib/clipboard/clipboard_windows.c.v

clipboard: fix windows warnings and run vfmt

---

vlib/json/json_test.v
vlib/v/gen/json.v

cgen: fix generic json bug

---

vlib/v/checker/checker.v
vlib/v/scanner/scanner.v
vlib/v/token/token.v

Minor fixes to the recent at(`@`) token remove from scanner

at(@): remove unused enum, improve error message for at(@) tokens in scanner

---

.github/workflows/ci.yml
vlib/x/websocket/websocket_client.v
vlib/x/websocket/websocket_test.v

This PR fixes a problem that the port was faulty parsed when using 'ws://xys.com:1000'
The tests are also fixed to fail on connect errors. This is why this bug could be introduced without test failing.
Next PR will fix and reenable the autobahn tests to make sure latest V are used in all tests.

x.websocket: Fixes the uri port parsing problem and test

---

vlib/v/checker/checker.v
vlib/v/tests/generics_test.v

checker: support ?T, &T generic return types

---

vlib/net/http/backend_windows.c.v
vlib/net/http/download_windows.c.v
vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/checker/tests/vweb_routing_checks.out
vlib/v/checker/tests/vweb_routing_checks.vv
vlib/v/parser/fn.v
vlib/v/table/table.v
vlib/vweb/vweb.v

Fixes https://github.com/vlang/v/issues/6747

vweb: check function and route parameter count

---

vlib/x/json2/decoder.v

Fixes #6366.
Also includes some typo fixes.

x.json2: change default number type to i64

---

vlib/v/checker/checker.v
vlib/v/checker/tests/optional_method_err.out
vlib/v/checker/tests/unexpected_or_propagate.out
vlib/v/checker/tests/wrong_propagate_ret_type.out

Hey,
Nothing urgent – ran into some `checker` error messages in my first project & thought their wording could be improved a little bit.
Thanks!

checker: improve wording on error messages

---

doc/docs.md

Make embedding example compile.
Use embedded field instead of method. Methods don't seem to work yet, plus fields are simpler for the example.

doc: fix embedding example

---

doc/docs.md

~~Also fix doc CI embedding example.~~

doc: document sum type smart cast

---

examples/term.ui/term_drawing.v

term: handle keyboard keys in the term_drawing example

---

examples/term.ui/event_viewer.v
examples/term.ui/term_drawing.v
vlib/term/ui/README.md
vlib/term/ui/input.v
vlib/term/ui/input_nix.c.v
vlib/term/ui/input_windows.c.v
vlib/term/ui/termios_nix.c.v
vlib/term/ui/ui.v

plus some overall cleanup, and other minor fixes/improvements to the module and its examples

term.ui: allow setting terminal title

---

examples/term.ui/text_editor.v

Add a small terminal text editor example to recent `term.ui` module

example: add simple text editor example to term.ui

---

examples/term.ui/text_editor.v

also implements scrolling via the mouse

examples/text_editor: minor cleanup and simplifications

---

vlib/net/socket_test.v

It's my first contribution to v. So I tried small challenge.
-  use defer (refactoring)
- Add test_socket_read_line
- v fmt

net: Improve socket_test

---

examples/term.ui/event_viewer.v
examples/term.ui/term_drawing.v
vlib/term/ui/input.v
vlib/term/ui/input_nix.c.v
vlib/term/ui/termios_nix.c.v
vlib/term/ui/ui.v

term.ui: handle middle mouse button events and modifier keys

---

examples/term.ui/text_editor.v

makes scrolling smoother by moving the cursor to the top of the file, before starting to scroll back up.
plus some minor UI changes/improvements: <https://asciinema.org/a/xfujToPbZcehJCMBLKK2K4CFh>

examples/text_editor: make scrolling smoother

---

examples/term.ui/text_editor.v
vlib/term/ui/termios_nix.c.v

Improve example to permit edit multiple files.

examples/text_editor: edit multiple files

---

vlib/builtin/string.v
vlib/builtin/string_test.v

Implement https://github.com/vlang/v/issues/6829

string: add charptr.vstring() and charptr.vstring_with_len()

---

vlib/encoding/csv/reader.v
vlib/encoding/csv/readme.md

Fixes #6774.
Add Reader example.

encoding/csv: improve Reader docs

---

examples/term.ui/text_editor.v

examples/text_editor: implement ctrl+arrows to move by word

---

vlib/builtin/string.v
vlib/builtin/string_test.v
vlib/strings/strings.c.v
vlib/strings/strings_test.v

New PR for https://github.com/vlang/v/pull/6807 as there were merge conflicts.

deprecate `strings.repeat_string`

---

vlib/x/json2/decoder.v
vlib/x/json2/encoder.v
vlib/x/json2/json2_test.v

Doing discord lib, and getting string with 
`HellonI'm Anton. `
instead of 
```
Hello
I'm Anton.
```
is annoying

json2: unescape characters

---

vlib/v/ast/scope.v
vlib/v/checker/checker.v
vlib/v/checker/tests/sum_type_mutable_cast_err.out
vlib/v/checker/tests/sum_type_mutable_cast_err.vv
vlib/v/tests/union_sum_type_test.v

https://github.com/vlang/v/pull/6817/files

checker: smartcast only if type is not mut

---

.github/workflows/ci.yml
.github/workflows/docs_ci.yml
CONTRIBUTING.md

check-md: check CONTRIBUTING.md too

---

vlib/term/ui/ui.v

As title states - this will allow for drawing dashed lines and rectangles

term.ui: add dashed lines and rectangles

---

examples/term.ui/pong.v

This will add "VONG" (a V pong clone) to the `term.ui` examples.
It features a notoriously evil and invincible AI named Victoria.

examples: term.ui - add pong clone

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/struct_no_extra_attr_keep.vv
vlib/v/parser/struct.v

Fix #6851 
All tests pass, so I think nothing broke :)

parser: fix duplicated struct attrs on first field

---

vlib/x/openssl/openssl.v

This PR fixes the WSS client.
Tests will be added into another PR.
PD: thanks to @helto4real 
This fixes: #6862

Fix WSS client (#6862)

---

vlib/x/websocket/websocket_client.v

x.websocket: expose logger field

---

vlib/v/checker/checker.v
vlib/v/gen/cgen.v
vlib/v/parser/if_match.v
vlib/v/tests/union_sum_type_test.v

bring back multi branch for match expr

all: match multi aggregate for union sum types

---

.github/workflows/ci.yml

macos ci: change "vid" to "ved"

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/fmt/fmt.v
vlib/v/parser/if_match.v
vlib/v/tests/union_sum_type_test.v

```v
if mut expr is ast.TypeOf {
// expr is smartcastet even it's mutable
}
match union mut expr {
ast.TypeOf {
// expr is smartcastet even it's mutable
}
}
```

Smartcast mut

---

vlib/v/parser/if_match.v
vlib/v/parser/tests/unnecessary_mut.out
vlib/v/parser/tests/unnecessary_mut.vv
vlib/v/parser/tests/unnecessary_mut_2.out
vlib/v/parser/tests/unnecessary_mut_2.vv
vlib/v/tests/union_sum_type_test.v

Smartcast mutable selector

---

.gitignore

gitignore: ignore .env

---

vlib/v/gen/js/jsgen_test.v

jsgen_test: ensure output deletation also on failure

---

.gitignore
vlib/v/ast/ast.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/types_expected.vv
vlib/v/fmt/tests/types_input.vv
vlib/v/parser/parser.v

vfmt handle comments after type declarations

---

doc/docs.md

doc: explain labelled break and continue

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/checker/tests/array_init_sum_type_without_init_value_and_len_err.out
vlib/v/checker/tests/array_init_sum_type_without_init_value_and_len_err.vv

checker: disallow array sum types without default field with len field

---

vlib/gg/gg.v

Added draw_empty_rounded_rect() to the `gg` module.

gg: new draw_empty_rounded_rect()

---

vlib/gg/gg.v

Added draw_rouded_rect() to the `gg` module.

gg: new draw_rounded_rect()

---

vlib/v/fmt/tests/comments_expected.vv
vlib/v/fmt/tests/comments_input.vv
vlib/v/parser/parser.v

WIP vfmt: Fix error with commment after return

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/checker/tests/sum_type_assign_non_variant_err.out
vlib/v/checker/tests/sum_type_assign_non_variant_err.vv
vlib/v/gen/cgen.v
vlib/v/table/atypes.v
vlib/v/table/table.v
vlib/v/tests/union_sum_type_test.v

like we discussed, check the tests for the behaviour

all: nested sum types

---

vlib/v/parser/parse_type.v
vlib/v/parser/parser.v
vlib/v/tests/generics_test.v
vlib/v/tests/modules/simplemodule/simplemodule.v

Fixes https://github.com/vlang/v/issues/6801

Fix generic structs from other modules

---

vlib/v/ast/ast.v
vlib/v/checker/check_types.v
vlib/v/checker/checker.v
vlib/v/checker/tests/is_type_invalid.out
vlib/v/checker/tests/match_invalid_type.out
vlib/v/checker/tests/match_sumtype_multiple_types.out
vlib/v/checker/tests/match_sumtype_multiple_types.vv
vlib/v/doc/utils.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/integer_literal_keep.vv
vlib/v/fmt/tests/struct_keep.vv
vlib/v/fmt/tests/sum_smartcast_keep.vv
vlib/v/fmt/tests/types_expected.vv
vlib/v/fmt/tests/types_input.vv
vlib/v/gen/auto_str_methods.v
vlib/v/gen/cgen.v
vlib/v/gen/fn.v
vlib/v/gen/js/js.v
vlib/v/parser/fn.v
vlib/v/parser/if_match.v
vlib/v/parser/parser.v
vlib/v/table/table.v
vlib/v/table/types.v
vlib/v/tests/if_smartcast_test.v
vlib/v/tests/match_sumtype_var_shadow_and_as_test.v
vlib/v/tests/match_test.v
vlib/v/tests/sum_type_test.v
vlib/v/tests/typeof_test.v

removes old sum type code.
next steps are: remove `match union` and `__type`
remove all `union` names
then, refactor UnionSumType to SumType

Remove old sumtype

---

examples/term.ui/term_drawing.v
vlib/term/ui/color.v
vlib/term/ui/input.v
vlib/term/ui/input_nix.c.v
vlib/term/ui/input_windows.c.v
vlib/term/ui/termios_nix.c.v
vlib/term/ui/ui.v

term.ui: approximate colors into ansi if rgb isn't supported

---

vlib/term/ui/termios_nix.c.v

term.ui: simplify/fix the truecolor feature test

---

vlib/v/gen/auto_str_methods.v
vlib/v/gen/cgen.v
vlib/v/tests/str_gen_test.v

fixes https://github.com/vlang/v/issues/6831

gen: print generic structs

---

vlib/v/ast/ast.v
vlib/v/ast/scope.v
vlib/v/checker/checker.v
vlib/v/fmt/fmt.v
vlib/v/parser/if_match.v
vlib/v/parser/parser.v
vlib/v/parser/tests/unnecessary_mut_2.out

This allows further smartcast improvements :)

parser: move mut in if/match to expr

---

vlib/v/gen/cgen.v
vlib/v/tests/anon_fn_test.v

```v
struct AnonFnWrapper {
mut:
fn_ fn () bool
}
fn test_anon_assign_struct() {
mut w := AnonFnWrapper{}
w.fn_ = fn () bool {
return true
}
assert w.fn_()
}
```
this works now.

gen: anon fn assign to struct

---

doc/docs.md
vlib/v/checker/checker.v
vlib/v/checker/tests/struct_required_field.out

docs: document the `[required]` struct attribute

---

vlib/v/gen/auto_str_methods.v
vlib/v/gen/cgen.v

cgen: minor cleanup

---

examples/term.ui/vyper.v

Adds a simple snake clone using term.ui.

Examples: term.ui --- Create vyper.v

---

vlib/term/ui/ui.v

As title states this will add a some documentation to `term.ui` functions.

term.ui: document functions

---

vlib/time/parse.v
vlib/time/parse_test.v

Support
- UTC: 2020-06-05T15:38:06.015959Z
- Local(without offset): 2020-06-05T15:38:06.015959

Improve parse iso8601

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/string_raw_and_cstr_keep.vv

fmt: add formatting for cstrs

---

cmd/v/help/build-c.txt
cmd/v/help/build.txt

help: list -showcc, -w options

---

vlib/v/builder/cc.v
vlib/v/gen/auto_str_methods.v
vlib/v/gen/cgen.v
vlib/v/gen/cheaders.v

compiler: fix self compilation with cached modules on macOS

---

make.bat

Rationale: since TCC is bootstrapped by default and immutable, the `-fresh-tcc` flag is no longer necessary and can be substituted by `make cleanall  && make -tcc` . this commit also improves logic around verifying directories and file by using attributes, as well as add output of the MSVC version when the initial C compilation fails.  In CI, `.\make.bat -gcc` or `.\make.bat -msvc` should be sufficient.

make.bat: download TCC by default and improve file search and detection

---

vlib/v/gen/cgen.v

This PR does minor optimization in `type_to_fmt()`.

gen: minor optimization in `type_to_fmt()`

---

vlib/v/pref/default.v

pref: don't use tcc by default in -prod mode

---

vlib/v/README.md
vlib/v/parser/comptime.v
vlib/v/parser/parser.v

This is an investigation for VLS.

docs: detailed (high level) documention of the compiler pipeline

---

vlib/builtin/option.v
vlib/v/checker/check_types.v
vlib/v/checker/checker.v
vlib/v/checker/tests/print_optional_type_err.out
vlib/v/checker/tests/print_optional_type_err.vv
vlib/v/gen/auto_str_methods.v
vlib/v/gen/cgen.v
vlib/v/gen/str.v
vlib/v/tests/str_gen_test.v

initial Option printin /auto str.
Doesn't work compeltely, But since Option types are not supported in all scenarions this might not be possible currently.
This fixes https://github.com/vlang/v/issues/6724

gen: initial option auto str support

---

tutorials/building-a-simple-web-blog-with-vweb.md
vlib/sqlite/README.md

I also linked the sqlite readme inside the blog tutorial.
My goal is to prevent issue like https://github.com/vlang/v/issues/7034 in the future.

sqlite: add Windows instructions to readme

---

vlib/v/gen/js/js.v

jsgen: fix JS.@typeof

---

vlib/x/websocket/events.v
vlib/x/websocket/handshake.v
vlib/x/websocket/io.v
vlib/x/websocket/message.v
vlib/x/websocket/uri.v
vlib/x/websocket/utils.v
vlib/x/websocket/websocket_client.v
vlib/x/websocket/websocket_nix.c.v
vlib/x/websocket/websocket_server.v
vlib/x/websocket/websocket_windows.c.v

- Better docs of x.websocket according to: #7047 
- Cleanup and fmt of code

x.websocket: Docs and cleanup

---

doc/docs.md

doc : Add string and array slicing examples

---

vlib/builtin/array_test.v
vlib/v/gen/fn.v

Fix #7046 and add tests for array.first() and array.last()

gen: fix arr.last().field

---

doc/docs.md

doc: add anonymous function exemples on filter/map

---

cmd/tools/vdoctor.v
vlib/v/parser/parser.v
vlib/v/tests/option_default_values_test.v

Fixes https://discord.com/channels/592103645835821068/592294828432424960/783683595444813825

parser: add check for known vars in or block

---

vlib/v/builder/builder.v
vlib/v/builder/c.v
vlib/v/builder/cc.v
vlib/v/builder/js.v
vlib/v/builder/msvc.v
vlib/v/checker/checker.v
vlib/v/doc/doc.v
vlib/v/doc/module.v
vlib/v/doc/utils.v
vlib/v/fmt/fmt.v
vlib/v/fmt/fmt_keep_test.v
vlib/v/fmt/fmt_test.v
vlib/v/fmt/fmt_vlib_test.v
vlib/v/fmt/tests/or_input.vv
vlib/v/fmt/tests/or_keep.vv
vlib/v/fmt/tests/void_optional_keep.vv
vlib/v/gen/cgen_test.v
vlib/v/gen/comptime.v
vlib/v/gen/x64/elf.v
vlib/v/parser/parser.v
vlib/v/pref/pref.v
vlib/v/table/cflags.v
vlib/v/table/cflags_test.v
vlib/v/table/table.v
vlib/v/table/types.v
vlib/v/util/diff.v
vlib/v/util/errors.v
vlib/v/util/util.v
vlib/v/vet/vet_test.v
vlib/v/vmod/parser.v

fmt: make single-stmt `or` blocks single-line

---

vlib/v/checker/checker.v
vlib/v/tests/method_call_chain_test.v

checker: don't disallow method call chains

---

vlib/builtin/map_test.v

This PR adds more tests to `map_test.v`. They test the map with (20k) unique keys. The file has also been formatted.

map: more tests

---

vlib/regex/README.md

regex: format readme examples

---

vlib/v/gen/cgen.v

This is an optimization for map element op-assign statements. An expressions like:
```v
m1['foo'] += 5
```
used to be compiled to:
```C
map_set(&m1, _SLIT("foo"), &(int[]) { (*(int*)map_get(m1, _SLIT("foo"), &(int[]){ 0 })) + 5 });
```
so the (expensive) computation of the map element's address has to be done twice. This PR changes this to:
```C
*((int*)map_get_and_set(&m1, _SLIT("foo"), &(int[]) { 0 })) += 5;
```
Test cases already exist in `map_test.v` and `shared_map_test.v`.

cgen: optimize map op_assign

---

vlib/time/parse_test.v

time: fix typo

---

vlib/v/gen/js/js.v

Simplifies the namespacing logic in jsgen. 
It should currently improve performance quite a bit, since there'll now be many less map lookups, but the main goal behind this is to remove the first pass through the ast (currently used to find all class methods), and do everything in a single pass, to make jsgen even faster.

jsgen: restructure namespaces

---

vlib/regex/regex.v
vlib/regex/regex_test.v

- Fix for bug with dot as last token in a group
- Added support for simple `capturing group` test
- Added some regression test

Regex: some bug fix, test suite with new features

---

vlib/v/scanner/scanner.v

This PR minor cleanup and optimize in scanner.v.

scanner: minor cleanup and optimize in scanner.v

---

Makefile

Makefile: trim trailing whitespace

---

vlib/builtin/string.v
vlib/json/json_test.v
vlib/v/gen/json.v

this fixes https://github.com/vlang/v/issues/7205

json: fix raw json string decoding crash when expected key is missing

---

vlib/v/parser/parser.v

This PR makes minor cleanup and optimization in `parser.v`.

parser: minor cleanup and optimization in `parser.v`

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/parser/fn.v

Fixes https://github.com/vlang/v/issues/7097

checker: correct underline for unknown type in method type

---

.github/workflows/ci.yml
examples/json.v
vlib/v/checker/checker.v
vlib/v/parser/fn.v
vlib/v/parser/parse_type.v
vlib/v/parser/struct.v

Fix parser silent example/json

---

vlib/v/parser/parser.v
vlib/v/parser/tests/expected_type_enum_err.out
vlib/v/parser/tests/expected_type_enum_err.vv

fixes https://github.com/vlang/v/issues/7263

parser: fix expected type enum error pos

---

vlib/time/time.v
vlib/time/time_test.v

time: add Time.add

---

vlib/time/parse_test.v

time: add test_parse_is8601_invalid

---

vlib/v/checker/checker.v
vlib/v/parser/if_match.v
vlib/v/parser/parse_type.v
vlib/v/parser/parser.v

parser: fix cgen in silent mode

---

.github/workflows/ci.yml
vlib/v/parser/parse_type.v
vlib/v/scanner/scanner.v

https://archive.fosdem.org/2007/slides/lightningtalks/Zzuf.pdf

ci: add parser fuzzer

---

.github/workflows/ci.yml

ci: add valgrind

---

.github/workflows/ci.yml
vlib/os/environment.v
vlib/os/os.v
vlib/v/builder/cc.v
vlib/v/gen/cgen.v

This PR fixes all C warnings of `-Wshadow`. I have added `-Wshadow` to `args` in cc.v. Since CI has `-Werror`, future commits with shadowing will fail.

cgen: fix shadowing

---

.github/workflows/ci.yml
vlib/builtin/array.v
vlib/strconv/atof.v
vlib/v/ast/scope.v

This PR makes the sanitizers exit with exitcode = 1 on erros and I've added `-fsanitize=undefined` to ubuntu and macos.

ci: fix sanitizers and add -fsanitize=undefined

---

cmd/tools/vtest-cleancode.v
vlib/builtin/map.v

Depends on #7284 being merged first.

vtest-cleancode: add builtin/map.v to fmt list

---

vlib/regex/README.md
vlib/regex/regex.v
vlib/regex/regex_test.v

- Refactoring of continuous capturing groups
- Update of the `README.md`
- Code preparation for capture groups call-backs

Regex: Refactoring of continuous capturing groups

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/comments_keep.vv
vlib/v/scanner/scanner.v

**Any spaces that are currently present will be kept!**
Part of #6684 but multiline comments are a lot more complex to implement, so they might follow later.

fmt: only insert a space after // if the 3rd char is alphanumeric

---

vlib/os/os.v

This PR just format os.v.
- Makes cleanup through format command.

os: format os.v

---

vlib/builtin/array.v

Add docs for `buitlin/array.v` as https://github.com/vlang/v/issues/7047

array: add more docs

---

vlib/math/big/big.v
vlib/math/big/big_test.v

math.big: fix big.from_string #7313

---

vlib/time/operator.v
vlib/time/parse.v
vlib/time/parse_test.v
vlib/time/time_darwin.c.v
vlib/time/time_nix.c.v
vlib/time/time_solaris.c.v
vlib/time/time_test.v
vlib/time/time_windows.c.v
vlib/time/unix.v

time: parse_iso8601 supports date only format

---

vlib/v/checker/checker.v
vlib/v/checker/tests/type_cast_optional_err.out
vlib/v/checker/tests/type_cast_optional_err.vv

Fixes https://github.com/vlang/v/issues/7350

checker: add more casts checks

---

doc/docs.md

doc: Add missing word "type" on array.clone() docs

---

vlib/v/gen/cgen.v
vlib/v/tests/string_alias_test.v

Fixes https://github.com/vlang/v/issues/7354

Alias string compare

---

cmd/tools/vdoc-resources/doc.css

When scroll the sidebar (right) to bottom move the cursor and scoll again, it resets to top. this fixes it.

vdoc: fix sidebar scroll when reaching bottom

---

examples/regex_example.v
vlib/regex/README.md
vlib/regex/regex.v
vlib/regex/regex_opt.v
vlib/regex/regex_test.v

Version 1.0 alpha
- Refactoring of most of the `dot_char` code and of the `groups` 
- Enhanced the debugger
- Added a long awaited helper functions for the groups
- Added custom "find and replace" ;)
- Made more smart `continuous capture` mode
- Simplified the `end of text` code
- Reduced the number of states used by the FSM
- Various small fixes
- Update the documentation to the latest version

Regex: V 1.0 alpha

---

vlib/log/log.v

As title states.
This will tick off a box in #7047 when merged.

log: document all functions, add missing copyright header

---

vlib/builtin/builtin.c.v

As title states this will document all functions in `builtin.c.v`
For some reason the file is currently missing in the #7047 list - though `missdoc` is reporting it correctly.
I'll add it to the list for good measure - so it can be ticked off :)

builtin: document all functions in builtin.c.v

---

vlib/regex/README.md
vlib/regex/regex.v
vlib/regex/regex_test.v

- Few small fix on the init code
- Code cleaning, removed all the `repeat`
- Fixed few typos in the `README.md`
- Added *crazywulf* tests

Regex: small fixes

---

vlib/regex/README.md
vlib/regex/regex.v
vlib/regex/regex_opt.v
vlib/regex/regex_util.v

- Refactoring of utils function
- More customizable params in the regex init
- Added more examples and further documentation in `README.md`

Regex: utils refactoring, more docs

---

vlib/regex/README.md
vlib/regex/regex.v
vlib/regex/regex_test.v

- Optimization on dot_char stack size
- Fix of end_group in a particular end_of_text situation
- Added tests

Regex: fixes and optimizations

---

vlib/arrays/arrays_test.v
vlib/v/gen/cgen.v

This fixes #7417 and add tests for #7417 and #7411
btw assign_stmt in cgen is a mess :D needs cleanup bad

cgen: fix assignment of fixed array var to another var & add array tests

---

cmd/tools/vcomplete.v

This will help completions for at least bash's completion system by appending path separators (`/`) to results that can be identified as directories.
Before:
`v run exam<tab>` -> `v run examples`
After:
`v run exam<tab>` -> `v run examples/` <- next `<tab>` will then correctly list the contents of the examples dir.

vcomplete: append path separator to results if they're directories

---

vlib/time/operator.v
vlib/time/operator_test.v
vlib/time/time.v
vlib/time/time_test.v

time: Move (Time - Time) into operator.v from time.v

---

vlib/builtin/map_test.v
vlib/v/gen/cgen.v
vlib/v/gen/json.v

gen: use new_map, new_map_init_1 functions

---

.github/workflows/ci.yml
vlib/v/builder/cc.v
vlib/v/parser/comptime.v
vlib/v/pref/default.v

Closes #6350.
Also adds tests for cross-compiling from macOS to Windows.

pref: fix cross-compiling graphical apps to Windows

---

vlib/cli/cli_flag_test.v
vlib/cli/command.v
vlib/cli/command_test.v
vlib/cli/flag.v

cli: v fmt

---

vlib/semver/compare.v
vlib/semver/parse.v
vlib/semver/range.v
vlib/semver/semver.v
vlib/semver/util.v

semver: v fmt

---

cmd/tools/vtest-cleancode.v
vlib/strings/builder.js.v
vlib/strings/builder.v
vlib/strings/builder_test.v
vlib/strings/similarity.v
vlib/strings/strings.c.v
vlib/strings/strings.js.v
vlib/strings/strings.v

strings: v fmt

---

vlib/sqlite/sqlite.v
vlib/sqlite/sqlite_test.v

Also I added a test for the close function. It's fairly trivial.

sqlite: Added `close` method along with `is_open` field

---

vlib/v/checker/checker.v
vlib/v/checker/tests/sum_type_multiple_type_define.out
vlib/v/checker/tests/sum_type_multiple_type_define.vv

checker: error if same type is used multiple times in a sum type

---

vlib/builtin/int.v
vlib/builtin/string.v
vlib/net/http/http.v
vlib/v/table/types.v
vlib/v/token/token.v

This PR remove redundant array.contains() definition.

contains: remove redundant array.contains definition

---

cmd/tools/vtest-cleancode.v

test-cleancode: Remove duplication

---

vlib/v/scanner/scanner.v

This PR makes minor cleanup of scanner.v.

scanner: minor cleanup of scanner.v

---

vlib/v/ast/str.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/fn_js_object_keep.vv

fmt: keep JS object name

---

.github/workflows/module_docs.yml

Closes #7183.
NOTE: this change requires a new `VERCEL_TOKEN` secret to be added.
I have my fork set up to deploy this already; an example workflow can be seen [here](https://github.com/spaceface777/v/runs/1565527949), and this is being deployed to https://vmodules.vercel.app. Feel free to push changes to the `master` branch on my fork to try out the new action :)

ci: update `vmodules` docs on every commit

---

vlib/regex/README.md
vlib/regex/regex.v
vlib/regex/regex_test.v

- Regex general optimization on reset functions
- Some optimization on the code of the loop
time test from `43200.807ms` to `17759.776ms`

Regex speed optimization

---

thirdparty/sokol/sokol_app.h

sokol: fix compilation with tcc on windows

---

README.md

Version 0.2 in the REPL :)

---

cmd/tools/vdoc-resources/doc.css
cmd/tools/vdoc-resources/doc.js

- Fixes dark mode switch
- Fix image width

vdoc: minor css and js fixes

---

vlib/v/gen/cgen.v

This PR uniforms format for automatic code generation.

cgen: uniform format for automatic code generation

---

Makefile

makefile: detect CPU architecture for tcc branch

---

Makefile

makefile: fix `aarch64` architecture detection, add some comments

---

doc/docs.md

I only fixed two small typo errors

fix: small errors

---

Dockerfile.alpine

Alpine Linux: upgrade version to 3.12
Upgrade Alpine Linux version to 3.12 in Dockerfile.alpine since actual Alpine Linux version is 3.12.

Alpine Linux: upgrade version to 3.12

---

vlib/regex/README.md
vlib/regex/regex.v
vlib/regex/regex_opt.v
vlib/regex/regex_test.v
vlib/regex/regex_util.v

- New `find_all_str` function
- Updated `README.md`
- Some refactoring of utility functions
- Refactoring of the finders test

Regex: added new find_all_str function

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/comments_expected.vv
vlib/v/fmt/tests/comments_input.vv

```v
arr := [
// comment
0,
]
```
before 
```v
arr := [
/*  comment */
0,
]
```
after
```v
arr := [
/* comment */
0,
]
```

fmt: Trim space in embedded comments

---

vlib/v/parser/parser.v
vlib/v/parser/tests/uncomplete_module_call_err.out
vlib/v/parser/tests/uncomplete_module_call_err.vv

Fixes https://github.com/vlang/v/issues/7528

parser: fix incomplete module selector

---

vlib/time/parse.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/unsafe_keep.vv
vlib/v/parser/parser.v
vlib/v/parser/pratt.v

fmt: keep UnsafeExpr linebreacks as set by developer

---

vlib/v/parser/parser.v

This PR makes minor simplification of `stmt` in parser.v.

parser: minor simplification of `stmt`

---

doc/docs.md

fix the example of century algorithm in document

docs: fix the example of century algorithm in document

---

doc/docs.md

More precise explanation of the value returned by match

---

vlib/v/ast/scope.v

ast: fix c error for scope.str() method

---

vlib/v/ast/ast.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/comments_keep.vv
vlib/v/parser/parser.v

https://github.com/vlang/v/issues/6755 5.

fmt: keep comment between enum fields

---

vlib/v/ast/ast.v
vlib/v/doc/utils.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/match_keep.vv

fmt: update expr_is_single_line for MatchExpr, StructInit and CallExpr with or block

---

doc/docs.md

files like `_nix.c.v` are used often but it is undocumented. So I added description.

docs: Add description for environment-specific files

---

vlib/v/gen/cgen.v
vlib/v/tests/struct_embed_test.v

Fixes https://github.com/vlang/v/issues/7565

cgen: fix zero init bug of embeds

---

cmd/tools/vdoc.v
vlib/v/doc/doc.v

Fixes https://github.com/vlang/v/issues/7539

vdoc: node type prefix

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/orm_keep.vv

fmt: keep order by in orm blocks

---

cmd/tools/vtest-cleancode.v
vlib/orm/orm_test.v

This will work after https://github.com/vlang/v/pull/7576 is merged.

test-cleancode: add vlib/orm

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/array_init_keep.vv
vlib/v/fmt/tests/fixed_size_array_type_keep.vv

fmt: use single quotes around fixed string arr default expr

---

vlib/v/parser/assign.v
vlib/v/parser/tests/multi_argumented_assign_err.out
vlib/v/parser/tests/multi_argumented_assign_err.vv

Fixes https://github.com/vlang/v/issues/5858

parser: fix pos for mutli argumented assign error

---

cmd/tools/vtest-cleancode.v
vlib/arrays/arrays_test.v

test-cleancode: add arrays module

---

cmd/v/help/default.txt

Add an entry about doctor tool in help

---

doc/docs.md

List more builtin functions with better description

---

vlib/regex/regex.v
vlib/regex/regex_opt.v
vlib/regex/regex_test.v
vlib/regex/regex_util.v

***what's inside**
- Bug fix for #7559
- New tests

Regex: bug fix #7559

---

doc/docs.md

doc: module names must be snake_case

---

doc/docs.md

doc: sync the table of contents

---

cmd/tools/vdoc/resources/doc.css
cmd/tools/vdoc/vdoc.v

scrollbar was invisible on some states of the page on mobile devices. this makes it look better.

vdoc: fix scrollbar on mobile

---

vlib/rand/README.md
vlib/rand/mt19937/mt19937.v
vlib/rand/musl/musl_rng.v
vlib/rand/pcg32/pcg32.v
vlib/rand/rand.v
vlib/rand/splitmix64/splitmix64.v
vlib/rand/util/util.v
vlib/rand/wyrand/wyrand.v

This will tick all `rand/...` boxes in #7047 when merged.
I've added a note about the range notation form used and cleaned up existing comments a bit also (added punctuation, made comments differ less between modules, used UTF-8 super script chars instead of HTML `<sup></sup>`).

rand: document all functions, document range notation form, fix copy-pasta

---

vlib/builtin/array_test.v
vlib/v/gen/auto_eq_methods.v

Fixes https://github.com/vlang/v/issues/7617

gen: fix generic contains method

---

vlib/runtime/runtime.c.v
vlib/runtime/runtime.v
vlib/runtime/runtime_nix.c.v
vlib/runtime/runtime_windows.c.v

Should tick a few boxes when merged in #7047 - it will also help ongoing work in #7192 by separating C. calls from pure V

runtime: document all functions

---

vlib/regex/README.md
vlib/regex/regex.v
vlib/regex/regex_opt.v
vlib/regex/regex_test.v
vlib/regex/regex_util.v

- bug fix on `.{x}` repeat management under minimum in speed optimization
- updated `README.md` on the differences PCRE <==> V-Regex

Regex: bug fix, docs update

---

vlib/v/ast/ast.v

I try to add more comments in the vlib/v/ast/ast.v.
If the comments in the pull request is ok, I will add more in the next pull request.

ast:document vlib/v/ast/ast.v

---

vlib/v/ast/ast.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/interface_declaration_comments_keep.vv
vlib/v/parser/struct.v

fmt: keep interface comments between methods

---

vlib/builtin/map_test.v
vlib/v/gen/cgen.v
vlib/v/gen/cheaders.v

This fixes https://github.com/vlang/v/issues/7647

cgen: fix map exists bug (#7647)

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/fn_trailing_arg_syntax_keep.vv

fmt: AnonFn with body is not single line

---

doc/docs.md

doc: fix titles

---

cmd/tools/vdoc/resources/doc.css
cmd/tools/vdoc/resources/doc.js
cmd/tools/vdoc/vdoc.v

Could some guys take a look?
Check it out and run it. Test a bit a give me some hints.
`search_index.js` has 307kb so far for vlib. Maybe there are tequniques to save space.
Sorting is very primitive and in frontend.

vdoc: implement advanced search (beta)

---

vlib/readline/README.md
vlib/readline/readline.v
vlib/readline/readline_default.c.v
vlib/readline/readline_linux.c.v
vlib/readline/readline_windows.c.v

This will tick off `vlib/readline/*` in #7047.
I've also added a preliminary `README.md`

readline: add missing documentation, fix documentation format, add README.md

---

vlib/v/gen/fn.v
vlib/v/tests/struct_embed_test.v

Fixes https://github.com/vlang/v/issues/7708

cgen: fix struct embedding method when receiver is ptr

---

vlib/v/parser/fn.v
vlib/v/parser/tests/invalid_fn_decl_script_err.out
vlib/v/parser/tests/invalid_fn_decl_script_err.vv

Fixes https://github.com/vlang/v/issues/7662

parser: proper error on fn decl in script mode

---

doc/docs.md

This PR adds an example of using array decomposition to varg

docs: add example of using array decomposition to varg

---

vlib/builtin/cfns.c.v
vlib/os/os_c.v

This PR change `os.mv()` to optional.

os.mv: change to optional

---

examples/2048/2048.v
vlib/gg/gg.v

WASM version preview: https://v2048-a7sxl6ova.vercel.app

examples/2048: make tiles have rounded corners

---

vlib/v/checker/checker.v
vlib/v/tests/complex_assign_test.v

This would previously not compile: 
```v
test := true
match test {
true {
// something....
}
false {
// something else....
}
}
```
It now will compile
Fixes #7747

match: Exhaustive bool match

---

doc/docs.md

Update docs.md: fix custom types link

---

examples/vweb/vweb_assets/vweb_assets.v
vlib/v/checker/checker.v

talked with joe. this was not a bug, it worked.
use this:
`app.Context.text()`
since `text()` got overwritten by `App`

Revert e9f9f27

---

vlib/v/parser/parse_type.v
vlib/v/parser/pratt.v
vlib/v/tests/sizeof_test.v
vlib/v/token/token.v

Fixes #7778.
Add ~~Parser.is_first_type_token~~ `Token.can_start_type` method.

parser: Parse non-identifier expressions for sizeof

---

vlib/v/gen/fn.v
vlib/vweb/vweb.v

vweb: default init methods

---

cmd/tools/vdoc/vdoc.v

Hi, I have fixed the indentation of the html file generated by vdoc.
This may improve its readability when you want to examine the html or modify it 😃

Fixed indentation of the html file generated by vdoc.

---

examples/database/mysql.v
vlib/mysql/consts.v
vlib/mysql/mysql.v

The last time i touch it, V doesn't support load enums from C.

mysql: Migrate connection flags to enum instead of const

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/struct_fn_fields_expected.vv
vlib/v/fmt/tests/struct_fn_fields_input.vv
vlib/v/table/types.v

Fix #7771
Required fixing #7773 (#7795) before this

fmt: Fix broken formatting in fn type of struct

---

vlib/builtin/map.v
vlib/builtin/map_test.v
vlib/v/checker/checker.v
vlib/v/gen/fn.v

Also make 2 map methods private.

checker: support non-string map.keys method

---

vlib/regex/regex_test.v
vlib/regex/regex_util.v

- Fix for bugwith find or find_all strarting with a `.*`
- New tests

Regex: fix for bug in find and find_all

---

vlib/cli/command.v
vlib/flag/flag.v
vlib/gg/gg.v
vlib/os/os_windows.c.v
vlib/os/process.v
vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/doc/doc.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/struct_default_field_expressions_keep.vv
vlib/v/fmt/tests/struct_init_with_custom_len_keep.vv
vlib/v/fmt/tests/structs_expected.vv
vlib/v/fmt/tests/structs_input.vv
vlib/v/gen/cgen.v
vlib/v/parser/parser.v
vlib/v/pref/pref.v
vlib/v/scanner/scanner.v
vlib/v/table/attr.v
vlib/vweb/tests/vweb_test.v
vlib/vweb/vweb.v
vlib/x/websocket/events.v
vlib/x/websocket/message.v
vlib/x/websocket/websocket_client.v
vlib/x/websocket/websocket_server.v

align comments and default expr in struct

fmt: More align struct

---

doc/docs.md

CI: Fix check-markdown CI

---

vlib/v/gen/array.v
vlib/v/tests/filter_in_map_test.v

Fixes https://github.com/vlang/v/issues/7793

cgen: fix filter in map

---

vlib/clipboard/clipboard_windows.c.v
vlib/v/gen/cgen.v

cgen: do not generate `!=` and `==` for C types

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/type_ptr_keep.vv
vlib/v/parser/pratt.v
vlib/v/tests/array_cast_test.v

parser: support casting to a pointer to array

---

vlib/v/checker/checker.v
vlib/v/gen/cgen.v
vlib/v/tests/for-in-iterator_test.v

for_in: implement compiler magic for iterators

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/generics_keep.vv

fmt: keep generic method call

---

vlib/v/parser/fn.v
vlib/v/parser/tests/anon_fn_return_type.out
vlib/v/parser/tests/anon_fn_return_type.vv
vlib/v/token/token.v

Fixes #7280.
Also tweak Token.can_start_type to detect `fn` keyword too.

 parser: add errors for invalid anonymous function 

---

cmd/tools/vdoc/vdoc.v

If the module has a README, it will be linked in the toc too.

vdoc: include readme link in toc

---

vlib/v/checker/checker.v
vlib/v/checker/tests/enum_empty.out
vlib/v/checker/tests/enum_empty.vv

checker: deny empty enum 

---

cmd/tools/vself.v

This PR makes minor optimization of vself module.
- Add file operation exception handling.
- Add successfully compiled information output.

vself: minor optimization of vself module

---

vlib/time/operator.v
vlib/time/operator_test.v

time: use operator overloading

---

vlib/cli/README.md
vlib/cli/command.v
vlib/cli/command_test.v

It is useful for declarative use

cli: Add Command.setup()

---

cmd/tools/missdoc.v

Let `missdoc` take both directories AND files as input arguments

missdoc: add support for single files as arguments

---

vlib/builtin/int.v

This should tick off `vlib/builtin/int.v` in #7047 when merged.

builtin: document all functions in int.v

---

vlib/builtin/float.v

When merged this should tick off the `vlib/builtin/float.v` box in #7047

builtin: document all functions in float.v

---

vlib/vweb/vweb.v

Fixes https://github.com/vlang/v/issues/7880

vweb: fix array.last bug

---

cmd/tools/modules/testing/common.v
examples/x/websocket/client-server/client.v
examples/x/websocket/client-server/server.v
vlib/x/websocket/websocket_client.v
vlib/x/websocket/websocket_server.v

Time to show x.websocket server some love.
- Adds an client-server broadcast example of x.websockets
- Expose connected clients (bugfix) 
- Removes double close callback (bugfix)

x.websocket: websocket server broadcast plus examples

---

cmd/tools/vbin2v.v

bin2v: correct newlines in console output

---

vlib/net/ftp/ftp.v

This PR fixes error of ftp.connect() (fix parts of #7914).
- `ftp.reader` assignment operation was misplaced, it should placed before read.
```v
pub fn (mut ftp FTP) connect(ip string) ?bool {
ftp.conn = net.dial_tcp('$ip:21') ?
ftp.reader = io.new_buffered_reader(reader: io.make_reader(ftp.conn))
code, _ := ftp.read() ?
if code == connected {
return true
}
return false
}
```
```v
module main
import net.ftp
fn main() {
mut ftp := ftp.new()
defer {
ftp.close()
}
connect_result := ftp.connect('ftp.redhat.com') ?
assert connect_result
login_result := ftp.login('ftp', 'ftp') ?
assert login_result
mut pwd := ftp.pwd() ?
println(pwd)
assert pwd.len > 0
ftp.cd('/suse/linux')
pwd = ftp.pwd() ?
println(pwd)
}
/
/suse/linux
```

ftp: fix error of ftp.connect() (fix parts of #7914)

---

vlib/builtin/int.v

builtin: add TODO example in int.v, fix doc example of (b byte).str()

---

vlib/v/gen/cgen.v
vlib/v/tests/match_test.v

Fixes https://github.com/vlang/v/issues/7585

cgen: fix match comparing with ident of type string

---

vlib/vweb/tmpl/README.md

Update Readme.md with @js directive

---

cmd/tools/check-md.v

Clean up some duplicate code for fmt verification.

check-md: minor cleanup

---

vlib/json/json_test.v
vlib/v/gen/json.v

This PR fixes decode map/array null object  (fix parts of #7914).
- Fixes decode map/array null object.
- Fixes `http_httpbin_test.v`.
- Add test in `json_test.v`.
```v
struct Info {
id    int
items []string
maps  map[string]string
}
fn test_decode_null_object() {
info := json.decode(Info, '{"id": 22, "items": null, "maps": null}') or { panic(err) }
assert info.id == 22
assert '$info.items' == '[]'
assert '$info.maps' == '{}'
}
```
- http_httpbin_test
```v
module main
import json
struct HttpbinResponseBody {
args    map[string]string
data    string
files   map[string]string
form    map[string]string
headers map[string]string
json    map[string]string
origin  string
url     string
}
fn http_fetch_mock(_methods []string, _config http.FetchConfig) ?[]http.Response {
url := …
```

json: fix decode map/array null object  (fix parts of #7914)

---

vlib/v/ast/str.v

ast: add params info to str of FnDecl

---

vlib/cli/command.v

I want to print help manually in FnCommandCallback func

cli: make execute_help pub

---

CHANGELOG.md
vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/parser/for.v
vlib/v/tests/for_smartcast_test.v

Closes https://github.com/vlang/v/issues/7040

checker: smartcast in for loops

---

cmd/tools/vbin2v.v
vlib/v/fmt/fmt_keep_test.v
vlib/v/fmt/tests/bin2v_keep.vv

fmt: test bin2v output formatting

---

cmd/tools/vbin2v.v

bin2v: replace hyphens for const names

---

vlib/v/checker/check_types.v
vlib/v/checker/tests/method_generic_infer_err.out
vlib/v/checker/tests/method_generic_infer_err.vv

Fixes https://github.com/vlang/v/issues/7875

checker: fix panic when could not infer method generic type

---

.github/workflows/periodic.yml

This PR increases test frequency of periodic ci, so we can find mistakes in time.

ci: increase test frequency of periodic

---

.github/workflows/prebuilt.yml

This PR fixes prebuilt.yml.
- Error v executing file directory.
Unzip v_xxx.zip, v is in v directory.

ci: fix prebuilt.yml

---

vlib/gx/color.v
vlib/gx/color_test.v

very useful converter to be used in low level programming,
very useful in sokol for example

converter gx.Colors to 'hex' and 'swapped hex'

---

doc/docs.md

docs: Add note on initializing structs with reference fields

---

vlib/v/gen/comptime.v
vlib/v/tests/comptime_if_expr_test.v

Fixes https://github.com/vlang/v/issues/7946

gen: fix generation of comptime if T is

---

doc/docs.md

Add entry for building graphical Android apps via V
Entry:
https://github.com/Larpon/v/blob/docs/add-android-vab-entry/doc/docs.md#android

docs: add vab/android info

---

vlib/v/parser/parser.v

See https://github.com/vlang/v/pull/7872#discussion_r554121958

parser: avoid value receiver

---

vlib/v/checker/checker.v
vlib/v/gen/cgen.v
vlib/v/parser/struct.v
vlib/v/parser/tests/invalid_recursive_struct1_err.out
vlib/v/parser/tests/invalid_recursive_struct1_err.vv
vlib/v/parser/tests/invalid_recursive_struct2_err.out
vlib/v/parser/tests/invalid_recursive_struct2_err.vv
vlib/v/table/table.v

same behaviour as Go: https://play.golang.com/p/mZAQVLCFjXR

parser: error on recursive struct

---

examples/database/mysql.v
vlib/mysql/_cdefs.c.v
vlib/mysql/_cdefs_nix.c.v
vlib/mysql/mysql.v
vlib/mysql/result.v
vlib/mysql/utils.v

mysql: Add more documentation

---

vlib/v/ast/str.v

ast: add str for EnumDecl

---

vlib/v/ast/ast.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/comments_keep.vv
vlib/v/fmt/tests/vscript_keep.vv
vlib/v/parser/fn.v

fmt: keep comments after call_expr in vsh files on the same line

---

vlib/v/pkgconfig/pkgconfig.v

Support Requires.private and handle double spaces in pkgconfig files

---

vlib/v/ast/str.v

ast: remove redundant InfixExpr.str()

---

doc/docs.md

docs: format more code blocks

---

vlib/time/operator.v
vlib/time/operator_test.v

time: use operator overloading for `ge` and `le`

---

vlib/v/ast/ast.v
vlib/v/fmt/fmt.v

fmt: fix rare extra tab after a SumType

---

Makefile

Makefile: support more CPU architectures.

---

vlib/x/ttf/common.v
vlib/x/ttf/render_bmp.v
vlib/x/ttf/render_sokol_cpu.v
vlib/x/ttf/ttf.v

***Whats's inside***
- More robust management for Glyphs not found
- notdef_glyph management and display on bitmap
Related to issue: #8014

TTF: improvement on not found glyphs

---

vlib/v/checker/checker.v
vlib/v/checker/tests/method_op_err.out
vlib/v/checker/tests/method_op_err.vv

Some additional checks which are needed for operator overloading.

checker: add more checks for operator overloading

---

CHANGELOG.md
vlib/v/gen/array.v
vlib/v/tests/sorting_by_different_criteria_test.v

This works due to @yuyi98's help

allow using of  sort with`<` and `>` op overloading

---

CHANGELOG.md
doc/docs.md
vlib/v/checker/checker.v
vlib/v/checker/tests/method_op_err.out
vlib/v/checker/tests/method_op_err.vv
vlib/v/gen/cgen.v
vlib/v/tests/operator_overloading_with_string_interpolation_test.v
vlib/v/token/token.v

Closes https://github.com/vlang/v/issues/4571

cgen: implement argument operator overloading

---

vlib/v/ast/str.v

ast: add str for Module

---

vlib/builtin/array.v
vlib/flag/flag_test.v
vlib/os/os.v
vlib/v/builder/cc.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/string_quotes_expected.vv
vlib/v/fmt/tests/string_quotes_input.vv
vlib/v/gen/auto_str_methods.v
vlib/v/gen/cgen.v
vlib/v/scanner/scanner.v
vlib/vweb/tmpl/tmpl.v

fmt: improve string quotes

---

cmd/tools/modules/testing/common.v
cmd/tools/preludes/tests_assertions.v
cmd/tools/vtest.v
vlib/benchmark/benchmark.v
vlib/term/term.v

test: more fancy output

---

vlib/v/fmt/fmt.v

fmt: cleanup string quotes handling

---

vlib/v/ast/str.v

ast: add str for ConstDecl

---

vlib/v/ast/str.v

ast: add str for Import

---

vlib/time/misc/misc.v
vlib/time/operator.v
vlib/time/stopwatch.v
vlib/time/time.v
vlib/time/time_linux.c.v
vlib/time/time_nix.c.v
vlib/time/time_windows.c.v

time: complete doc

---

vlib/v/gen/fn.v
vlib/v/tests/interface_test.v

gen: fix interface method call name that is C reserved word

---

vlib/v/gen/cgen.v
vlib/v/tests/go_call_generic_fn_test.v

gen: fix go call with generic function

---

vlib/v/ast/str.v

ast: add str for ArrayInit

---

vlib/v/ast/str.v

ast: add str for comment

---

vlib/v/ast/str.v

ast: add str for AssertStmt

---

vlib/v/checker/checker.v
vlib/v/checker/tests/struct_type_cast_err.out
vlib/v/checker/tests/struct_type_cast_err.vv
vlib/v/checker/tests/unimplemented_interface_e.out
vlib/v/checker/tests/unimplemented_interface_e.vv

Check the methods are compatible.

checker: check casting struct -> interface; disallow casting struct -> interface pointer

---

vlib/v/tests/sum_type_test.v

This PR adds a test of sumtype-based binary tree.

test: add test of sumtype-based binary tree

---

vlib/x/ttf/common.v
vlib/x/ttf/render_bmp.v
vlib/x/ttf/render_sokol_cpu.v
vlib/x/ttf/ttf.v

- Bug fix for problem with `voidptr` and MSVC in the `get_string` function
tnx to @spaceface777 for the hint to avoid auto double returns :)

TTF: fix on MSVC get_string pointer issue

---

doc/docs.md
vlib/v/fmt/fmt.v

This PR adds documentation for `handle := go f()` and `handle.wait()`
A minor fix for `vfmt` is added, too.

docs: document `go` with handle and `wait()`

---

vlib/x/ttf/README.md
vlib/x/ttf/common.v
vlib/x/ttf/render_sokol_cpu.v
vlib/x/ttf/text_block.v
vlib/x/ttf/ttf.v

- Added first release of documentation
- Added comments on code
- Fixed `get_date` results
- other small fixes

TTF: added README, some improvement.

---

vlib/v/checker/checker.v
vlib/v/checker/tests/method_op_alias_err.out
vlib/v/checker/tests/method_op_err.out
vlib/v/parser/fn.v
vlib/v/table/table.v

checker: improve message and positioning for operator overloading

---

examples/tetris/tetris.v

This will enable tetris to run on Android (via `vab`)

tetris: enable to run on android, run v fmt

---

vlib/v/parser/fn.v
vlib/v/parser/parse_type.v
vlib/v/parser/struct.v

parser: use Parser.builtin_mod instead of checking p.mod

---

CHANGELOG.md
cmd/tools/vdoc/html.v
cmd/tools/vdoc/resources/doc.css
cmd/tools/vdoc/resources/doc.js

vdoc: implement advanced search on mobile layout

---

LICENSE

 update copyright year

---

vlib/builtin/sorting_test.v
vlib/v/checker/checker.v
vlib/v/gen/array.v

builtin: fix sorting arrays of primitives

---

vlib/v/pkgconfig/pkgconfig.v

pkgconfig: add support for Fedora and CentOS Linux.

---

vlib/v/checker/tests/array_filter_anon_fn_err_a.out
vlib/v/checker/tests/array_filter_anon_fn_err_b.out
vlib/v/checker/tests/array_map_anon_fn_err_a.out
vlib/v/checker/tests/array_map_anon_fn_err_b.out
vlib/v/checker/tests/array_map_anon_fn_err_c.out
vlib/v/checker/tests/fn_var.out
vlib/v/parser/fn.v

parser: improve anon fn pos

---

vlib/v/checker/checker.v
vlib/v/tests/if_expression_test.v
vlib/v/tests/match_test.v

Closes https://github.com/vlang/v/issues/8088
Fixes https://github.com/vlang/v/issues/8222
Fixes https://github.com/vlang/v/issues/8223

checker: fix if expr infix

---

vlib/clipboard/clipboard.v
vlib/clipboard/clipboard_darwin.c.v
vlib/clipboard/clipboard_default.c.v
vlib/clipboard/clipboard_solaris.c.v
vlib/clipboard/clipboard_windows.c.v
vlib/clipboard/dummy/dummy_clipboard.v
vlib/clipboard/x11/clipboard.c.v

clipboard: document all pub functions, adhere to vdoc style

---

examples/snek/snek.v

this pr adds snek (the snake game) to the examples folder.

add snek (snake game) to examples

---

vlib/vweb/vweb.v

This PR makes the multipart detection case-insensitive. Thanks to https://discord.com/channels/592103645835821068/697813437237166131/801808299422384148

vweb: make multipart case-insensitive

---

vlib/v/gen/comptime.v
vlib/v/tests/comptime_if_expr_test.v

This PR fixes generic comp time if expr close #5621

gen: fix generic comp time if

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/gen/cgen.v
vlib/v/tests/if_smartcast_test.v

Fixes https://github.com/vlang/v/issues/8233
this was difficult to fix ^^

checker/gen: fix smartcast pointer sumtype

---

vlib/builtin/string.v

FYI, ustring's left and right are public

builtin: make string.(left|right) pub

---

vlib/v/checker/tests/mut_receiver.out
vlib/v/checker/tests/mut_receiver.vv
vlib/v/checker/tests/mut_receiver_warning.out
vlib/v/parser/fn.v

Before
```
vlib/v/checker/tests/mut_receiver.vv:5:7: warning: use `(mut f Foo)` instead of `(f mut Foo)`
3 |     name string
4 | }
5 | fn (f mut Foo) info() {
|       ~~~
6 |     f.name = 'foo'
7 | }
vlib/v/checker/tests/mut_receiver.vv:8:15: error: use `(mut f Foo)` or `(f &Foo)` instead of `(mut f &Foo)`
6 |     f.name = 'foo'
7 | }
8 | fn (mut f &Foo) info2() {
|               ^
9 |     f.name = 'foo'
10 | }
```
After
```
vlib/v/checker/tests/mut_receiver.vv:5:4: warning: use `(mut f Foo)` instead of `(f mut Foo)`
3 |     name string
4 | }
5 | fn (f mut Foo) info() {
|    ~~~~~~~~~~~
6 |     f.name = 'foo'
7 | }
vlib/v/checker/tests/mut_receiver.vv:8:4: error: use `(mut f Foo)` or `(f &Foo)` instead of `(mut f &Foo)`
6 |     f.name = 'foo'
7 | }
8 | fn (mut f &Foo) info2() {
| …
```

parser: Improve position of mut receiver waning / error

---

examples/cli.v
vlib/cli/command.v
vlib/cli/command_test.v
vlib/cli/flag.v
vlib/cli/flag_test.v

This PR is to allow in cli module to have a same flag multi time:
```
$ my_app -f filter1 -f filter2
```

cli: allow flag to be set multi time

---

vlib/encoding/base64/base64.v

Ticks off `vlib/encoding/base64/base64.v` in #7047 when merged.

encoding: document all of base64

---

.github/workflows/ci.yml

After https://github.com/vlang/vls/pull/63 is fixed

ci: reenable vls-compiles

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/checker/tests/orm_empty_struct.out
vlib/v/checker/tests/orm_empty_struct.vv
vlib/v/fmt/fmt.v
vlib/v/gen/sql.v
vlib/v/parser/sql.v

close #5553
This PR add handling for orm when struct that get parse into are empty

orm: fix empty struct

---

0.3_roadmap.txt
CHANGELOG.md
doc/docs.md
vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/fmt/fmt.v
vlib/v/gen/cgen.v
vlib/v/gen/fn.v
vlib/v/parser/struct.v
vlib/v/table/table.v
vlib/v/table/types.v
vlib/v/tests/interface_fields_test.v

~~WIP - cgen does not work yet. I'm still not sure what the best way of implementing this is :/~~
~~vfmt cannot handle the new feature yet, that's why CI is red.~~
edit: it's all good now :)
Closes #3868

all: implement interface fields

---

doc/docs.md

Add description for `$` symbol.

Add description for `$`

---

.github/workflows/ci.yml
vlib/x/websocket/tests/autobahn/fuzzing_server/check_results.py
vlib/x/websocket/websocket_server.v
vlib/x/websocket/websocket_test.v

Workaround for a V bug that returns bad pointer in `for _, x in some_map_of_ref`.
This was shown in the autobahn tests cause after a certain period of time the automatic ping handler would fail and sometimes it would not have time to run. This is why it fails some times and was ok some times.
I will also find root cause and repro of V bug so we can get that fixed.

x.websocket: Websocket server fix and bring back server autobahn

---

vlib/strconv/utilities.v

Spelling corrections for some comments.

Just spelling corrections

---

doc/docs.md

Wrote an example of how multiple variable assignment can be used to swap two variables.

docs: add an example of variable swapping

---

vlib/v/gen/cgen.v

Prevents memory leaks when using channels

cgen: Free temporary channel arrays

---

vlib/v/gen/cgen.v
vlib/v/tests/option_test.v

Fixes https://github.com/vlang/v/issues/7959

cgen: fix optional sum types

---

examples/sokol/cube.v

An example of 3d cube using sokol module

added 3d cube example for sokol

---

vlib/strconv/format.v

Just another little spelling correction while reading the code.

Little spelling correction

---

vlib/v/fmt/tests/if_single_line_keep.vv
vlib/v/fmt/tests/if_ternary_expected.vv
vlib/v/fmt/tests/if_ternary_input.vv
vlib/v/fmt/tests/if_ternary_keep.vv

fmt: cleanup and expand tests for ternary if

---

vlib/v/gen/comptime.v
vlib/v/tests/comptime_if_is_test.v

gen: Fix `$if T !is`

---

vlib/builtin/builtin_windows.c.v

builtin: fix truncating of EOL on windows terminal

---

vlib/v/fmt/fmt.v

fmt: minor cleanup of return_stmt

---

vlib/v/checker/check_types.v
vlib/v/tests/generics_test.v

Fixes https://github.com/vlang/v/issues/8344

checker: fix multi generic args

---

vlib/builtin/array_test.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/asserts_expected.vv
vlib/v/fmt/tests/asserts_input.vv

fmt: assert (a == b) -> assert a == b

---

vlib/v/ast/ast.v
vlib/v/fmt/fmt.v

fmt: minor cleanup of sql_expr

---

vlib/v/checker/checker.v
vlib/v/checker/tests/fn_call_no_body.out
vlib/v/checker/tests/fn_call_no_body.vv
vlib/v/parser/fn.v
vlib/v/table/table.v
vlib/v/table/types.v

https://discord.com/channels/592103645835821068/592294828432424960/801312897783431179

checker: make a calling no-body function a checker error

---

examples/term.ui/text_editor.v
vlib/term/term_windows.c.v
vlib/term/ui/consoleapi_windows.c.v
vlib/term/ui/input.v
vlib/term/ui/input_nix.c.v
vlib/term/ui/input_windows.c.v
vlib/term/ui/termios_nix.c.v
vlib/term/ui/ui.v

term.ui: native Windows console implementation

---

vlib/math/fractions/fraction.v

minor typo

---

vlib/v/checker/tests/ambiguous_function_call.out
vlib/v/checker/tests/ambiguous_function_call.vv
vlib/v/checker/tests/ambiguous_function_call_a.out
vlib/v/checker/tests/ambiguous_function_call_a.vv
vlib/v/checker/tests/ambiguous_function_call_b.out
vlib/v/checker/tests/ambiguous_function_call_b.vv

This PR merges ambiguous_function_call tests.

checker: merge ambiguous_function_call tests

---

vlib/v/checker/checker.v
vlib/v/checker/tests/interface_implementing_interface.out
vlib/v/checker/tests/interface_implementing_interface.vv
vlib/v/checker/tests/struct_type_cast_err.out

checker: make implementing an interface with another interface an error

---

vlib/gg/gg.v

gg: add window_size() function

---

examples/gg/raven_text_rendering.v

Depends on #8409 for getting window dimensions without importing `sapp`

examples: make raven text run on android, fix text scaling

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/import_selective_expected.vv
vlib/v/fmt/tests/import_selective_input.vv

fmt: keep multiline selective import

---

vlib/vweb/vweb.v

This PR fix the vweb file upload example

vweb: fix vweb upload

---

vlib/v/gen/str.v

change str from `none` to `<none>`

---

vlib/v/checker/check_types.v
vlib/v/checker/tests/function_count_of_args_mismatch_err.out
vlib/v/checker/tests/function_count_of_args_mismatch_err.vv
vlib/v/checker/tests/function_too_many_args_err.out
vlib/v/checker/tests/function_too_many_args_err.vv

Fix this
```v
fn fff<T>(i int, v T) {}
fn main() {
fff(0)
}
```
```
V panic: array.get: index out of range (i == 1, a.len == 1)
|       0x4060e2 | v()
|       0x47ea98 | v()
|       0x49111b | v()
|       0x48bac6 | v()
|       0x47d9ca | v()
|       0x480512 | v()
|       0x48ba02 | v()
|       0x49a329 | v()
|       0x48056c | v()
|       0x47ff59 | v()
|       0x48213e | v()
|       0x548567 | v()
|       0x548c8c | v()
|       0x5490f4 | v()
|       0x5545d6 | v()
|       0x5591ab | v()
|       0x56f067 | v()
| 0x7fa748c8dbf7 | /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)
|       0x401d9a | v()
```

checker: fix panic when calling generic function with too few args

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/import_multiple_input.vv

fmt: remove duplicated imports

---

doc/docs.md

Created a subheader under Arrays for detailing slices.

docs: elaborated on slices

---

cmd/tools/vup.v

This downloads the git-for-windows installer and has the user install it. vup then retries the git commands it needs to use. This PR assumes non-Windows users know how to at least install git from their package manager of choice.
Suggestions are welcome, right now the installer used is hard-coded, and I think there are other places for improvement.
I don't think it 100% closes #8406 but it comes close.

vup: Add auto-ish git installer for Windows (#8406)

---

vlib/v/gen/cgen.v

This PR makes minor cleanup of consts in cgen.v.

cgen: minor cleanup of consts

---

doc/docs.md
vlib/v/ast/ast.v
vlib/v/ast/str.v
vlib/v/checker/checker.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/offset_keep.vv
vlib/v/gen/cgen.v
vlib/v/gen/js/js.v
vlib/v/parser/pratt.v
vlib/v/tests/offsetof_test.v

Adds support and tests for `__offsetof(Struct, field)`.

all: add offsetof

---

examples/vweb/vweb_assets/index.html
examples/vweb/vweb_assets/vweb_assets.v

vweb example: Making css in vweb_assets.v work

---

vlib/builtin/builtin.v
vlib/v/gen/cgen.v
vlib/v/tests/inout/bad_st_as.out

gen: panic with correct type names

---

vlib/builtin/array_test.v
vlib/v/checker/checker.v

fix generic_mutable_arrays in functions

---

doc/docs.md

This pr demonstrates and explains implementing a basic method onto an interface.

docs: documented interface methods

---

vlib/v/gen/cgen.v
vlib/v/gen/cmain.v

add destructor along with constructor so `_vcleanup` can be called in shared lib.

cgen: add destructor to cleanup v

---

doc/docs.md

Also:
* Remove `${typeof(item).name}` because it is always `Speaker`. (Later if/when `item.type_name()` is implemented we can use that).
* Add headings
* Use separate interface `Something` to show that smart casting changes the type to access underlying struct fields. The `Speaker` interface already has a field called `breed` so using that doesn't showcase the smart casting.

doc: simplify interface method definition example

---

vlib/v/checker/checker.v
vlib/v/checker/tests/comptime_call_method.out
vlib/v/checker/tests/comptime_call_method.vv
vlib/v/parser/comptime.v
vlib/v/tests/comptime_call_test.v

Also mark `arg` as used and check it's in scope.
Add runtime test for `s.$method(arg)`.

checker: check s.$method(arg) argument is []string

---

vlib/v/ast/str.v
vlib/v/fmt/tests/string_interpolation_literal_keep.vv

fmt: keep braces around @ escaped fields in string interpolation

---

doc/docs.md
vlib/math/big/big.v
vlib/os/os_c.v
vlib/os/os_darwin.c.v
vlib/os/os_nix.c.v
vlib/os/os_windows.c.v
vlib/time/time.v
vlib/time/time_darwin.c.v
vlib/time/time_nix.c.v
vlib/time/time_windows.c.v
vlib/v/builder/msvc.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/hashstmt_expected.vv
vlib/v/fmt/tests/hashstmt_input.vv
vlib/v/fmt/tests/hashstmt_keep.vv
vlib/v/fmt/tests/include_vroot_keep.vv

fmt: insert newline after last HashStmt

---

examples/gg/polygons.v
vlib/gg/gg.v

Added two new functions to [gg.v](https://github.com/vlang/v/blob/master/vlib/gg/gg.v): draw_convex_poly() and draw_empty_poly()
The first is implemented by drawing a triangle fan, while the second is implemented with a line strip.
draw_convex_poly:
```v
//Draws a convex polygon, given an array of x coordinates and an array of y coordinates, and a color.
//Note that the points must be given in clockwise order.
pub fn (ctx &Context) draw_convex_poly(x []f32, y []f32, c gx.Color) {
assert x.len == y.len
len := x.len
assert len >= 3
if c.a != 255 {
sgl.load_pipeline(ctx.timage_pip)
}
sgl.c4b(c.r, c.g, c.b, c.a)
sgl.begin_triangle_strip()
for i in 0 .. (len / 2) {
sgl.v2f(x[0], y[0])
sgl.v2f(x[i * 2 + 1], y[i * 2 + 1])
sgl.v2f(x[i * 2 + 2], y[i * 2 + 2])
}
if len % 2 == 0 {
sgl.v2f(x[len - …
```

gg: Added polygon-related functions

---

doc/docs.md

I added a `goto` section under Advanced Topics.

docs: goto

---

doc/docs.md
doc/upcoming.md

docs: remove `&` from `shared` initializers

---

vlib/orm/orm_test.v
vlib/v/gen/sql.v

This PR fix issue #8308, which are null values in the database

orm: fix orm null strings, close #8308

---

cmd/tools/vtest-parser.v
vlib/v/doc/doc.v
vlib/v/fmt/fmt_keep_test.v
vlib/v/fmt/fmt_test.v
vlib/v/fmt/fmt_vlib_test.v

fmt: fix tests

---

examples/sokol/cube.v

... effectively making it work + look better on mobile devices:

examples: cube support touch events, correct placment and scaling on nonsquare viewports

---

cmd/tools/vfmt.v

vfmt: enable colored warnings/errors

---

vlib/gx/text.v
vlib/net/common.v
vlib/net/errors.v
vlib/time/time.v
vlib/v/checker/checker.v
vlib/v/checker/tests/import_symbol_const_private_err.out
vlib/v/checker/tests/import_symbol_const_private_err.vv
vlib/v/parser/parser.v
vlib/v/token/token.v

checker: check private constant

---

vlib/v/checker/tests/array_map_anon_fn_err_a.out
vlib/v/checker/tests/array_map_anon_fn_err_a.vv
vlib/v/checker/tests/array_map_anon_fn_err_b.out
vlib/v/checker/tests/array_map_anon_fn_err_b.vv
vlib/v/checker/tests/array_map_anon_fn_err_c.out
vlib/v/checker/tests/array_map_anon_fn_err_c.vv
vlib/v/checker/tests/array_map_fn_err.out
vlib/v/checker/tests/array_map_fn_err.vv
vlib/v/checker/tests/array_map_fn_err_a.out
vlib/v/checker/tests/array_map_fn_err_a.vv
vlib/v/checker/tests/array_map_fn_err_b.out
vlib/v/checker/tests/array_map_fn_err_b.vv
vlib/v/checker/tests/array_map_fn_err_c.out
vlib/v/checker/tests/array_map_fn_err_c.vv

This PR merge array_map_fn_err tests in checker.
```vlang
fn main() {
a1 := [1,2,3,4].map(fn(a int, b int) int {return a + b})
println(a1)
a2 := [1,2,3,4].map(fn(a string) string { return a })
println(a2)
a3 := [1,2,3,4].map(fn(a string) {})
println(a3)
a4 := [1,2,3,4].map(add1)
println(a4)
a5 := [1,2,3,4].map(add2)
println(a5)
a6 := [1,2,3,4].map(do_nothing)
println(a6)
}
fn add1(a int, b int) int {
return a + b
}
fn add2(a string) string {
return a
}
fn do_nothing(a string) {
}
vlib/v/checker/tests/array_map_fn_err.vv:2:22: error: function needs exactly 1 argument
2 |     a1 := [1,2,3,4].map(fn(a int, b int) int {return a + b})
|                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 |     println(a1)
4 |
vlib/v/checker/tests/array_map_fn_err.vv:5:22: error: type …
```

checker: merge array_map_fn_err tests

---

vlib/v/token/token.v

This PR correct some comments and add some necessary comments in token.v.

token: correct some comments and add some necessary comments

---

vlib/vweb/tmpl/tmpl.v

This PR will make the functionality @include i vweb working well.
I can add a small set of files to test if needed.

vweb: fix template include html file

---

vlib/v/ast/ast.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/struct_decl_keep.vv
vlib/v/parser/struct.v

fmt: keep __global in struct declarations

---

doc/docs.md
vlib/term/ui/README.md
vlib/x/json2/README.md

docs/readmes: format almost all remaining code blocks

---

vlib/semver/semver.v

This should tick off the following entries in #7047 when merged:
```
vlib/semver/compare.v
vlib/semver/parse.v
vlib/semver/range.v
vlib/semver/semver.v
vlib/semver/util.v
```

semver: document all pub functions

---

vlib/v/gen/c/cgen.v
vlib/v/tests/operator_overloading_cmp_test.v

Fixes https://github.com/vlang/v/issues/8597

cgen: fix gen of `>` operator overloading

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/if_ternary_expected.vv
vlib/v/fmt/tests/if_ternary_input.vv
vlib/vweb/vweb.v

fmt: better function call wrapping inside ternary if branches

---

vlib/v/parser/pratt.v
vlib/v/parser/tests/anon_fn_return_type.out
vlib/v/parser/tests/struct_field_expected.out
vlib/v/parser/tests/struct_field_expected.vv
vlib/v/token/token.v

Also improve error messages when expecting a struct field name.

token: fix Token.str() for punctuation and operators

---

doc/docs.md
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/import_selective_expected.vv
vlib/v/fmt/tests/import_selective_input.vv

fmt: remove unused selective imports

---

doc/docs.md

Update docs.md: use `make.bat` under Windows.

---

vlib/v/checker/checker.v
vlib/v/gen/c/cgen.v
vlib/v/tests/array_type_alias_test.v

checker/gen: allow `<<` operator for array alias

---

vlib/v/checker/tests/assign_expr_undefined_err_h.out
vlib/v/checker/tests/assign_expr_undefined_err_h.vv
vlib/v/parser/assign.v

parser: make `v := f(v)' an undefined variable error

---

vlib/v/ast/ast.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/import_keep.vv
vlib/v/parser/parser.v

> ~~I need to rebase this after #8636 has been merged.~~
fix #8484

fmt: keep comments between and after imports

---

vlib/net/aasocket.c.v
vlib/net/address.v
vlib/net/net_nix.c.v

This PR adds basic support for unix sockets.

net: add unix socket support

---

examples/database/pg/customer.v
vlib/vweb/vweb.v

pg example: dash prints are optimazed
vWeb: Changed Log From `Running a Vweb app on http://localhost:$port` to `[Vweb]Running  app on http://localhost:$port`

lib, example: Small improvements

---

vlib/rand/rand.v

With this proposed function, you will be able to generate pseudorandom hexadecimal numbers in a string form.

Generate pseudorandom hexadecimal numbers

---

vlib/v/checker/checker.v

Extract long branches into new func.

checker: minor cleanup in stmt()

---

vlib/rand/rand.v

This new function will be able to generate pseudorandom ASCII characters.

Generate pseudorandom ASCII Characters

---

CONTRIBUTING.md

CONTRIBUTING.md: update outdated name to correct one

---

README.md

Rendered example here:
https://github.com/Larpon/v/tree/readme/mention-graphical-android-support#android-graphical-apps

readme: mention graphical app android support

---

doc/docs.md

docs: fix "plugin-in" beef

---

doc/docs.md
vlib/v/ast/str.v
vlib/v/checker/tests/prefix_err.out
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/maps_of_fns_with_string_keys_keep.vv

docs: fix functions in array/map example

---

doc/docs.md

doc: group `for`/`in` forms

---

doc/docs.md

Enable example test.
Document single const declaration.
Add heading for `const` required module prefix.
Mention function call is not evaluated at compile-time yet
Tweak wording of unqualified constants in `main` module
Hide confusing `top_cities` example (should be part of commented-out text).

doc: improve `const` docs

---

doc/docs.md

doc: fix Modules position in Contents

---

vlib/v/parser/fn.v
vlib/v/tests/fn_test.v

parser: fix parsing attribute after fn prototype with no return type

---

vlib/v/checker/checker.v
vlib/v/checker/tests/if_non_bool_cond.out

checker: report correct position for non-bool cond error

---

vlib/v/builder/builder.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/if_ternary_keep.vv

fmt: keep single line if in struct init

---

vlib/v/checker/checker.v
vlib/v/gen/c/cgen.v
vlib/v/gen/c/fn.v
vlib/v/parser/struct.v

all: implement `type_name()` for interfaces too

---

vlib/v/gen/c/fn.v

gen: fix type_name for sumtype/interface pointers

---

vlib/glm/glm.v

Multiplicates is a typo

---

vlib/pg/pg.v

Update pg.v "Underlaying" is not the proper word.

---

vlib/builtin/array.v

Sort docstring grammar fix

---

vlib/v/scanner/scanner.v

scanner: do not warn on \' after string interpolation

---

vlib/v/parser/fn.v

parser: cleanup fn_decl

---

vlib/v/checker/checker.v
vlib/v/checker/tests/multi_value_method_err.out
vlib/v/checker/tests/multi_value_method_err.vv

checker: reject method that have multi-value type receiver

---

vlib/v/checker/checker.v
vlib/v/checker/tests/c_fn_surplus_args.out
vlib/v/checker/tests/c_fn_surplus_args.vv

checker: check argument count for C fn with attribute

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/or_keep.vv

fmt: fix possible code corruption by unwrapped single line if

---

vlib/v/fmt/tests/structs_expected.vv
vlib/v/fmt/tests/structs_input.vv
vlib/v/parser/struct.v

fmt: fix bug of disappearing `pub` in struct decl

---

cmd/tools/repeat.v
cmd/tools/vdoctor.v
vlib/net/http/http.v
vlib/v/checker/checker.v
vlib/v/gen/js/js.v
vlib/v/markused/markused.v

~~Depends on #8660.~~
Before, only assigning a map Ident to another Ident was checked. This checks any copy when the right hand side is an lvalue.

checker: do not allow copying any map lvalue

---

vlib/x/json2/decoder.v
vlib/x/json2/encoder.v

json2: mark strings.Builder.free() calls as unsafe

---

vlib/v/checker/checker.v
vlib/v/table/table.v

checker/table: minor cleanup by removing unnecessary `_` variable

---

.github/workflows/ci.yml
examples/regex/pcre.v
examples/regex/pcre.vv
examples/regex/readme.md
examples/regex/regex_example.v
examples/regex/regex_with_memoization.v
examples/templates/data.json
examples/templates/readme.md
examples/templates/result.md
examples/templates/template.md
examples/templates/templates.v
vlib/v/parser/comptime.v
vlib/v/tests/tmpl_test.v

there is a new example for how to use templates 
also created a pcre example

template & regex updated example (pcre)

---

examples/cli.v
vlib/cli/command.v
vlib/cli/command_test.v

This PR correctly checks for missing flags that are marked required. It also adds a test and updates the example cli program.

cli: fix check for required flags

---

vlib/v/fmt/fmt.v

fmt: cleanup obsolete comments

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/import_selective_expected.vv

Sort syms in selective imports alphabetically

fmt: sort syms in selective imports

---

cmd/tools/vdoc/html.v

vdoc: hide README toc entry without readme

---

vlib/v/fmt/comments.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/comments_expected.vv
vlib/v/fmt/tests/comments_input.vv
vlib/v/fmt/tests/comments_keep.vv
vlib/v/parser/if_match.v

fmt: keep empty line between if statement and comment 

---

vlib/v/builder/cc.v

This avoids issues, especially on windows, where the system C compiler may either not exist, or be too old a version, or have any issues that would make its output contain absolutely no useful debugging info.

builder: print tcc output instead, when the system C compiler fails

---

vlib/v/pref/pref.v

v.pref: add a `-debug-tcc` compiler option

---

vlib/v/checker/checker.v
vlib/v/checker/tests/use_deprecated_function_warning.out
vlib/v/checker/tests/use_deprecated_function_warning.vv

checker: warn for deprecated methods too

---

vlib/builtin/string.v
vlib/math/fractions/fraction.v
vlib/os/file.c.v
vlib/os/os.v

lib: remove old deprecated functions

---

vlib/regex/regex.v
vlib/regex/regex_test.v
vlib/regex/regex_util.v

- removed `[deprecated]` function and they usage
- small code clean
- added test for regex_base  function

Regex: removed [deprecated], code clean, added test for regex_base

---

doc/docs.md

Document integer assignment to enums and need for explicit casting to int. Currently undocumented.

docs: enum assignment

---

vlib/v/parser/parser.v
vlib/v/tests/imported_symbols_test.v
vlib/v/tests/modules/geometry/geometry.v

parser: set is_public correctry when registering enum type symbol

---

examples/term.ui/event_viewer.v
examples/term.ui/term_drawing.v
examples/term.ui/text_editor.v
vlib/term/ui/README.md
vlib/term/ui/input.v
vlib/term/ui/input_windows.c.v
vlib/term/ui/termios_nix.c.v
vlib/v/parser/parser.v

term.ui: use the new `[flag]` enums

---

examples/vweb/server_sent_events/server.v
examples/vweb/vweb_assets/vweb_assets.v
examples/vweb/vweb_example.v
vlib/vweb/vweb.v

Close #8643 
This PR adds handle static root options, which means there is no mount point and adds documentation

vweb: add handle static root & documentation

---

vlib/v/ast/ast.v
vlib/v/fmt/comments.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/comments_keep.vv
vlib/v/parser/containers.v

fmt: do not struggle with comments inside maps

---

vlib/v/gen/c/cgen.v
vlib/v/tests/match_interface_test.v

cgen: fix `match`ing interface types

---

vlib/net/http/cookie.v

net/http/cookie: use filter

---

vlib/v/ast/str.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/comments_embedded_keep.vv

fmt: fix missing space after single line array pre comments

---

examples/2048/2048.v
vlib/gg/gg.v
vlib/gg/gg_android.c.v

gg: handle Android's own native dpi scaling factor

---

vlib/encoding/csv/writer.v
vlib/strings/builder.v

builder: implements io.Writer

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/chan_init_keep.vv

fmt: do not remove chan type of struct fields

---

doc/docs.md

Variadics is mentioned too early, move to `Functions 2` section.
Add missing `Structs with reference fields` entry in TOC.
Methods should not be under Structs - they can have other receiver kinds.
Mention methods have to be in same module as receiver type.

doc: move variadics, tweak methods, add missing TOC item

---

vlib/v/fmt/fmt.v
vlib/v/parser/containers.v

parser,fmt: refactor array comment handling to fully rely on the ecmnts field

---

.github/workflows/ci.yml
cmd/tools/vtest-self.v
make.bat
vlib/gg/m4/m4_test.v
vlib/gg/m4/matrix.v
vlib/sync/channels.v
vlib/v/gen/c/profile.v

Early I did some work to enable V+tcc32+windows.
If smooth this would be the first official 32-bit backend option : )
CI failing is expected and please try merging this first: https://github.com/vlang/tccbin/pull/21 [**MERGED**].

add tcc32 CI on windows

---

vlib/crypto/md5/md5.v
vlib/crypto/sha1/sha1.v
vlib/crypto/sha256/sha256.v
vlib/crypto/sha512/sha512.v

crypto: Digest implements io.Writer

---

vlib/v/checker/checker.v
vlib/v/checker/tests/cast_err.out
vlib/v/checker/tests/cast_err.vv

Fixes https://github.com/vlang/v/issues/8964.

checker: detect unknown type for cast

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/checker/tests/comptime_for.out
vlib/v/checker/tests/comptime_for.vv
vlib/v/parser/comptime.v

Also fix error message positions.

checker: detect unknown type to iterate with $for

---

vlib/v/builder/cc.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/or_keep.vv
vlib/v/fmt/tests/stmt_keep.vv

fmt: do not write single line or blocks with multi line stmts

---

vlib/v/gen/c/cgen.v
vlib/v/tests/for_in_iterator_test.v

cgen: move the condition of an iterator to a temp var

---

Dockerfile
Dockerfile.alpine
README.md

I think docker image should run v repl by default

Dockerfile: set CMD ["v"]

---

examples/wkhtmltopdf.v
vlib/os/file.c.v
vlib/os/os.v
vlib/v/gen/x64/elf.v

os: tag File methods unsafe - write_bytes, write_bytes_at

---

vlib/net/ftp/ftp.v
vlib/net/tcp.v
vlib/net/udp.v
vlib/net/unix/stream_nix.v
vlib/x/openssl/openssl.v
vlib/x/websocket/io.v
vlib/x/websocket/websocket_client.v

net/openssl/websocket: implement io.Writer

---

vlib/v/checker/checker.v
vlib/v/checker/tests/fn_init_sig.out
vlib/v/checker/tests/fn_init_sig.vv

Fixes https://github.com/vlang/v/issues/8982.

checker: check `init` fn with no params has no return type

---

vlib/v/checker/checker.v
vlib/v/gen/c/cgen.v
vlib/v/gen/c/fn.v

builtin: allow passing any argument type to `panic`

---

vlib/v/gen/c/comptime.v
vlib/v/tests/comptime_for_test.v

cgen: scope `$for` fields/methods independently

---

.github/workflows/ci.yml
vlib/v/parser/comptime.v
vlib/v/tests/tmpl/base.txt
vlib/v/tests/tmpl/inner.txt
vlib/v/tests/tmpl_test.v
vlib/vweb/tmpl/tmpl.v

doubling template folder directory name
with that hierarchy

tmpl: fix doubling templates folder path and enhancements

---

vlib/v/checker/checker.v
vlib/v/gen/c/cgen.v
vlib/v/table/table.v
vlib/v/tests/interface_test.v

checker, cgen: allow implementing an interface with an embedded struct

---

vlib/dl/dl.v

This PR makes a minor improvement to the dl module.

dl: minor improvement

---

vlib/v/checker/checker.v
vlib/v/checker/tests/is_type_invalid.out

checker: correct pos for type error of `if v is interface`

---

vlib/v/checker/checker.v

This PR removes a FIXME that was in the `call_method` method.

checker: minor cleanup in `call_method`

---

vlib/time/operator.v

Cleanup of `==` and `<` operators.
Less branches for more performances 😄

time: minor cleanup of operators

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/empty_lines_expected.vv
vlib/v/fmt/tests/empty_lines_input.vv
vlib/vweb/route_test.v

fmt: force empty lines after struct declarations and most functions

---

vlib/clipboard/clipboard_darwin.c.v
vlib/clipboard/clipboard_windows.c.v
vlib/clipboard/dummy/dummy_clipboard.v
vlib/clipboard/x11/clipboard.c.v

This fixes building V UI on various platforms after the merge of #9062.
I'm not sure why CI didn't catch this - maybe we should add building of more examples?

clipboard: ensure public method access after #9062. Fixes #9089

---

vlib/v/checker/checker.v
vlib/v/checker/tests/unknown_as_type.out

checker: replace checking type exists with c.ensure_type_exists

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/cast_expected.vv
vlib/v/fmt/tests/cast_input.vv

fmt: don't prepend mod when cast with selective imported types

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/fn_trailing_arg_syntax_keep.vv

fmt: prevent code corruption with struct update syntax as trailing function arg

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/fn_trailing_arg_syntax_expected.vv
vlib/v/fmt/tests/fn_trailing_arg_syntax_input.vv
vlib/vweb/tests/vweb_test.v

fmt: remove tail space when using multiline short arg

---

vlib/v/checker/checker.v
vlib/v/checker/tests/array_sort_err.out
vlib/v/checker/tests/array_sort_err.vv

Report `too many arguments in call to sort()`

checker: check arguments count of sort

---

vlib/builtin/array.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/attrs_expected.vv
vlib/v/fmt/tests/attrs_input.vv
vlib/v/fmt/tests/attrs_keep.vv
vlib/vweb/tests/vweb_test_server.v

As discussed on Discord https://discord.com/channels/592103645835821068/700746775962714232/817007181294731274.

fmt: combine simple attributes into a single line

---

.github/ISSUE_TEMPLATE/bug_report.md

bug_report.md: Fix typo

---

vlib/v/gen/c/cgen.v

This PR makes minor optimization in for_in_array.
- Avoid generate tmp_var when cond is var.
before:
```vlang
Array_Array_fixed_int_2 arr = __new_array_with_default(10, 0, sizeof(Array_fixed_int_2), 0);
// FOR IN array
Array_Array_fixed_int_2 _t109 = arr;
for (int _t110 = 0; _t110 < _t109.len; ++_t110) {
Array_fixed_int_2 pair;
memcpy(*(Array_fixed_int_2*)pair, (byte*)((Array_fixed_int_2*)_t109.data)[_t110], sizeof(Array_fixed_int_2));
println(Array_fixed_int_2_str(pair));
}
}
```
now:
```vlang
Array_Array_fixed_int_2 arr = __new_array_with_default(10, 0, sizeof(Array_fixed_int_2), 0);
// FOR IN array
for (int _t101 = 0; _t101 < arr.len; ++_t101) {
Array_fixed_int_2 pair;
memcpy(*(Array_fixed_int_2*)pair, …
```

cgen: minor optimization in for_in_array

---

vlib/v/fmt/fmt.v

fmt: extract type decls code into functions to cleanup

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/expressions_expected.vv
vlib/v/fmt/tests/expressions_input.vv

fmt: proper single line check for ConcatExpr

---

vlib/os/os_android.c.v

There were some typo that makes vab failing.

os: fix typo in os_android.c.v

---

vlib/v/checker/checker.v

checker: minor cleanup: clear_flag(.optional) in check_expr_opt_call

---

vlib/v/ast/str.v
vlib/v/fmt/tests/string_interpolation_keep.vv

fmt: fix string interpolation with CastExpr

---

cmd/tools/vcreate.v
cmd/v/help/new.txt

v new: accept name and description from argument

---

vlib/os/file_test.v
vlib/os/inode_test.v
vlib/os/os_test.v
vlib/os/process_test.v
vlib/v/checker/checker.v
vlib/v/fmt/fmt.v
vlib/v/fmt/tests/or_keep.vv
vlib/v/live/executable/reloader.v
vlib/v/live/live_test.v
vlib/v/pref/pref.v
vlib/v/table/cflags_test.v
vlib/v/vcache/vcache_test.v
vlib/vweb/request.v
vlib/vweb/tests/vweb_test.v
vlib/vweb/vweb.v
vlib/x/websocket/websocket_client.v
vlib/x/websocket/websocket_test.v

```v
foo() or {}
foo() or {
}
```

fmt: write empty or blocks the same as empty fn bodies, empty structs, etc

---

vlib/v/fmt/tests/attrs_keep.vv
vlib/v/table/attr.v

fmt: fix backslash doubling in attribute string args

---

Makefile
vlib/v/util/util.v

build: add address sanitizer make target

---

vlib/v/gen/c/cgen.v

This PR add `expr_string()` and remove redundant codes in cgen.v.

cgen: add `expr_string()` and remove redundant codes

---

doc/docs.md

docs: mention deprecated attribute with argument

---

cmd/tools/vcheck-md.v

combined warings, errors, and oks into a struct

vcheck-md: minor cleanup

---

vlib/v/gen/c/cgen.v
vlib/v/tests/match_expr_with_one_branch_test.v

Fixes https://github.com/vlang/v/issues/9223

cgen: fix match for one branch

---

doc/docs.md
vlib/v/checker/checker.v
vlib/v/gen/c/cgen.v
vlib/v/gen/c/comptime.v
vlib/v/tests/prod/assoc.prod.v
vlib/v/tests/prod/assoc.prod.v.expected.txt

support `$if prod` like `$if debug`
```
fn main() {
$if prod {
println('prod')
} $else {
println('not prod')
}
}
```
```
$ v -prod run main.v
prod
$ v run main.v
not prod
```

v: support `$if prod`

---

vlib/v/checker/checker.v

checker: split fn_decl into functions to cleanup

---

vlib/gg/m4/m4_test.v
vlib/gg/m4/matrix.v
vlib/gg/m4/vector.v

- removed `abs` function, using stdlib `f32_abs`
- bug fix on matrix translate

gg.m4: bug fix on translate, removed abs fn

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/doc/doc.v
vlib/v/fmt/fmt.v
vlib/v/gen/c/cgen.v
vlib/v/parser/if_match.v

and use the new common sumtype field access syntax instead

ast: remove the `stmt.position()` method

---

doc/docs.md

Use the `for mut val in arr` syntax in the example.

Update mutable iteration example

---

vlib/v/checker/checker.v

This PR changes a `if ... else` to `match` in the method `Checker.hash_stmt()`

checker: minor changes to `Checker.hash_stmt()`

---

tutorials/building_a_simple_web_blog_with_vweb/README.md

Going through the blog tutorial I found that this particular portion of the README was not in sync with the code.  Anyone following along with the tutorial as is will be stuck at this point.

tutorials: align content with code

---

vlib/v/checker/checker.v
vlib/v/checker/tests/is_type_invalid.out

This PR makes minor cleanup in if_expr() of checker.v.

checker: minor cleanup in if_expr()

---

cmd/tools/vpm.v

v remove: use correct command name in error when no args are given

---

cmd/v/help/bin2v.txt
cmd/v/help/default.txt
cmd/v/help/doc.txt
cmd/v/help/help.v
cmd/v/help/install.txt
cmd/v/help/new.txt
cmd/v/help/other.txt
cmd/v/help/remove.txt
cmd/v/help/search.txt
cmd/v/help/test.txt
cmd/v/help/update.txt
cmd/v/help/vpm.txt

No functionality changes except if `v help init` is ran it will display the `new` help doc as well.

help files: Unified and clarified some 'help' documents

---

vlib/gg/image.v

And a Rect struct
Since I don't have a mac, I didn't try to find a way to implement it on macos

gg: add draw_image_part

---

vlib/builtin/option.v
vlib/v/checker/checker.v
vlib/v/gen/c/cgen.v
vlib/v/gen/c/fn.v
vlib/v/gen/c/index.v
vlib/v/gen/c/json.v
vlib/v/markused/markused.v

builtin: cleanup option names (part 1)

---

vlib/v/builder/cc.v

Fixes https://github.com/vlang/v/issues/9261.

builder: warn when using tcc with -prod

---

vlib/v/fmt/fmt.v

fmt: use type_to_str_using_aliases

---

cmd/tools/vvet/vvet.v
cmd/v/help/default.txt
cmd/v/help/vet.txt

vet: add -W flag and detailed help

---

vlib/v/fmt/comments.v
vlib/v/fmt/tests/comments_keep.vv

fmt: allow ascii art block comments

---

vlib/v/fmt/tests/empty_lines_keep.vv
vlib/v/parser/sql.v

parser: correctly set pos of sql blocks

---

vlib/v/ast/ast.v
vlib/v/checker/check_types.v
vlib/v/checker/checker.v
vlib/v/gen/c/fn.v
vlib/v/parser/fn.v
vlib/v/table/table.v
vlib/v/table/types.v
vlib/v/tests/generics_test.v

Fix https://github.com/vlang/v/issues/9297
Also fix inferring type for variadic

gen: fix generic variadic

---

vlib/v/fmt/tests/empty_lines_keep.vv
vlib/v/parser/struct.v

parser: set correct last line for struct inits

---

vlib/v/checker/checker.v
vlib/v/checker/tests/assign_multi_mismatch.out
vlib/v/tests/complex_assign_test.v

checker: fix #9330

---

vlib/v/parser/fn.v

This PR makes minor cleanup in call_args().

parser: minor cleanup in call_args()

---

vlib/builtin/map.v
vlib/net/tcp.v
vlib/net/udp.v
vlib/v/gen/c/cheaders.v

cgen: make `bool`s take up a single byte, not 4

---

vlib/v/fmt/attrs.v
vlib/v/fmt/fmt.v

fmt: reorder and sort methods into section

---

vlib/os/file.c.v

os: deprecate read_at and add read_from to implement RandomReader

---

cmd/tools/vtest-cleancode.v

This is useful to fmt before submit PR

test-cleancode: add -fix flag

---

cmd/tools/vbin2v.v
vlib/v/fmt/fmt_keep_test.v
vlib/v/fmt/fmt_test.v
vlib/v/fmt/fmt_vlib_test.v

fmt: fail keep test when bin2v_keep preparation step fails

---

vlib/v/checker/checker.v

checker: minor cleanup call_method

---

vlib/regex/regex_test.v
vlib/regex/regex_util.v

- Bug fix for the replace with function
- Added some tests

regex: bug fix in replace using function, added tests

---

vlib/builtin/option.v
vlib/v/gen/c/auto_str_methods.v
vlib/v/tests/str_gen_test.v

builtin: add a proper str() method to IError

---

examples/net_udp_server_and_client.v
examples/websocket/client-server/client.v
examples/websocket/ping.v
vlib/net/tcp_simple_client_server_test.v
vlib/net/tcp_test.v
vlib/net/udp.v
vlib/net/udp_test.v
vlib/net/unix/stream_nix.v
vlib/net/unix/unix_test.v
vlib/os/os_test.v
vlib/picohttpparser/response.v
vlib/x/websocket/websocket_client.v
vlib/x/websocket/websocket_test.v

all: deprecate write_str and replace it with write_string

---

vlib/v/checker/checker.v
vlib/v/checker/tests/optional_fn_err.out
vlib/v/checker/tests/optional_fn_err.vv

checker: make optional arguments in func call an error

---

doc/docs.md

Adds a short snippet for the `any()` and `all()` array methods.

docs: document array .any() and .all()

---

vlib/rand/README.md

Match the documentation to the current state of this module (and its submodules).

rand: update documentation

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/parser/if_match.v
vlib/v/parser/struct.v
vlib/v/scanner/scanner.v
vlib/v/token/position.v
vlib/v/token/token.v
vlib/v/util/errors.v

This PR implements a column field in the scanner tokens and computes them on demand. Extension of #9395

scanner, token: add column information to tokens

---

vlib/v/gen/c/cgen.v
vlib/v/tests/if_expr_of_optional_test.v

cgen: fix treating errors as values inside if expressions

---

vlib/v/gen/c/cheaders.v

This PR needs a follow-up PR for bootstrapping:
https://github.com/vlang/v/pull/9452

wyhash: update to final_version_3 (part 1)

---

vlib/hash/wyhash.c.v
vlib/v/gen/c/cheaders.v

This PR should be merged after https://github.com/vlang/v/pull/9451

wyhash: update to final_version_3 (part 2)

---

vlib/x/json2/decoder.v
vlib/x/json2/encoder.v
vlib/x/json2/json2.v

Add u64() to the x.json2 decoder

---

vlib/v/gen/c/cgen.v

This PR make minor cleanup in for_in_stmt().

cgen: minor cleanup in for_in_stmt()

---

doc/docs.md

Seems obvious and natural now that I know it.

doc: Add a note on how to define type aliases.

---

vlib/v/fmt/struct.v
vlib/v/fmt/tests/import_with_alias_keep.vv
vlib/v/table/types.v

fmt: fix import aliases in type declarations

---

examples/fireworks/fireworks.v

Fix for issue: #9485

---

vlib/v/fmt/fmt.v

fmt: remove cur_short_mod

---

vlib/v/gen/c/cgen.v
vlib/v/tests/defer_test.v

cgen: execute defer stmts in LIFO order

---

vlib/x/websocket/handshake.v
vlib/x/websocket/websocket_client.v

x.websocket: Add header to client

---

vlib/v/checker/checker.v
vlib/v/checker/tests/alias_array_unknown_op_overloading_err.out
vlib/v/checker/tests/alias_array_unknown_op_overloading_err.vv
vlib/v/checker/tests/alias_map_unknown_op_overloading_err.out
vlib/v/checker/tests/alias_map_unknown_op_overloading_err.vv
vlib/v/gen/c/cgen.v
vlib/v/tests/alias_array_operator_overloading_test.v
vlib/v/tests/alias_map_operator_overloading_test.v

I forgot to add support for this but https://github.com/vlang/v/issues/9499 reminded me to do it :laughing:

cgen: add support for operator overloading for those alias who have array, map, fixed array as aliased type

---

vlib/crypto/rand/rand.v
vlib/crypto/rand/rand_darwin.c.v
vlib/crypto/rand/rand_linux.c.v
vlib/crypto/rand/rand_solaris.c.v
vlib/crypto/rand/rand_windows.c.v

As discussed in #9367 this PR add custom error types to crypto package.
A working example for semver was already merged in #9493.

Crypto: add custom errors to crypto lib

---

vlib/time/format.v
vlib/time/time.v
vlib/time/time_format_test.v

time: extend date str formats

---

main.v
vlib/v/checker/checker.v
vlib/v/checker/tests/filter_func_return_nonbool_err.out
vlib/v/checker/tests/filter_func_return_nonbool_err.vv
vlib/v/checker/tests/map_func_void_return_err.out
vlib/v/checker/tests/map_func_void_return_err.vv

Fixes https://github.com/vlang/v/issues/9551

checker: add check for call expr in map/filter

---

vlib/regex/README.md
vlib/regex/regex_test.v
vlib/regex/regex_util.v

- Added support for using groups in the replace strings
- Added tests

Regex: added groups in replace strings

---

.github/workflows/gen_vc.yml

vc: move the regeneration logic to CI

---

.github/workflows/gen_vc.yml

ci: add git authentication to the vc job

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/checker/tests/interface_return_parameter_err.out
vlib/v/parser/fn.v
vlib/v/parser/struct.v

- Adds return type position info for FnDecl
- Add name pos info for InterfaceDecl
- Extend Param position in Node.position()

ast, parser: add additional pos info for FnDecl and InterfaceDecl nodes

---

vlib/encoding/utf8/utf8_util.v
vlib/encoding/utf8/utf8_util_test.v

- Fix on `to_lower` bug on few glyph
- Added test

Utf8: fix to_lower bug

---

doc/docs.md

dock: correcting a spelling mistake

---

vlib/v/ast/ast.v
vlib/v/fmt/tests/empty_lines_keep.vv
vlib/v/parser/comptime.v
vlib/v/parser/parser.v
vlib/v/parser/struct.v
vlib/v/scanner/scanner.v

I will fix the match expr linebreaks in `ast.v` in a followup PR.

scanner,parser,ast: many fixes related to Node.pos

---

vlib/orm/orm_test.v
vlib/v/ast/ast.v
vlib/v/fmt/fmt.v
vlib/v/gen/c/sql.v
vlib/v/parser/sql.v

This PR add table creation to orm
This is the syntax:
```v
sql db {
create <Struct>
}

orm: add table creation

---

vlib/v/gen/c/sql.v

This PR fixes the compilation problem in cpp

orm: fix compilation

---

examples/sokol/02_cubes_glsl/cube_glsl.v
examples/sokol/03_march_tracing_glsl/rt_glsl.v
examples/sokol/04_multi_shader_glsl/rt_glsl.v
examples/sokol/05_instancing_glsl/rt_glsl.v
examples/sokol/06_obj_viewer/show_obj.v

- New instruction on how to compile the shaders
P.S. @Larpon GREAT JOB MAN!!

sokol examples: modified the comments on how to compile the shaderes

---

vlib/vweb/request.v
vlib/vweb/request_test.v

Closes https://github.com/vlang/v/issues/9615

vweb: Read entire body from buffered reader

---

vlib/v/checker/checker.v
vlib/v/checker/tests/modules/module_alias_started_with_underscore.out
vlib/v/checker/tests/modules/module_alias_started_with_underscore/main.v
vlib/v/checker/tests/modules/module_alias_started_with_underscore/underscore.v

checker: do not allow module aliases started with '_' (underscore)

---

doc/docs.md
vlib/v/builder/compile.v
vlib/v/checker/checker.v
vlib/v/gen/c/comptime.v
vlib/v/pref/default.v
vlib/v/pref/pref.v
vlib/v/pref/should_compile.v

This adds the necessary features for #9624, so that the v.c is rebuilt and the CIs pass.

all: add necessary components for other`-freestanding` PR

---

.github/workflows/ci.yml

ci: build examples with V compiled with -fsanitize

---

vlib/builtin/map.v
vlib/v/gen/c/auto_eq_methods.v
vlib/v/gen/c/cgen.v
vlib/v/gen/c/cheaders.v
vlib/v/gen/c/fn.v
vlib/v/gen/c/index.v
vlib/v/gen/c/json.v
vlib/v/markused/markused.v

The map has accumulated a lot of unfortunate names over time because of bootstrapping. This PR aims to combat this and it will have a follow-up commit.

map: rename methods

---

vlib/v/checker/checker.v
vlib/v/tests/cast_to_byte_test.v

checker: fix casting bool to byte

---

vlib/log/log.v

log: unify cli and file output order

---

vlib/builtin/map.v
vlib/v/checker/tests/import_symbol_fn_private_err.out
vlib/v/checker/tests/import_symbol_fn_private_err.vv

This is just a follow-up commit of https://github.com/vlang/v/pull/9657

map: rename methods (part 2)

---

README.md

this was moved into a subdirectory so the example doesn't work anymore

README: update example

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/import_selective_expected.vv
vlib/v/fmt/tests/import_selective_input.vv

fmt: mark types import as used in interface

---

vlib/v/gen/c/sql.v

fix static var name, close #9725

---

vlib/v/ast/table.v

This PR make minor simplification and cleanup of resolve_generic_by_names/types.
- Minor simplification of resolve_generic_by_names/types.
- Minor cleanup of resolve_generic_by_names/types.

table: minor simplification and cleanup of resolve_generic

---

doc/docs.md

i noticed in the modules installation section
the grammar was a bit of
instead of `for remove module` it should be `for removing a module`.

Fixed tenses

---

vlib/builtin/cfns.c.v
vlib/os/os_c.v
vlib/os/os_nix.c.v
vlib/os/os_test.v
vlib/os/os_windows.c.v

This PR implements a new OS function loginname(). Furthermore it adds a better error handling in file_size() and truncate().
- add os.loginname() returns name of logged in user
- improvements for error handling in os.file_size() and os.truncate()

os: add function os.loginname(), make some error improvements 

---

vlib/net/urllib/urllib.v

urllib: fix #9748 out of bounds accesses in unescape()

---

vlib/v/fmt/fmt.v

fmt: fix panic in module docs generation

---

vlib/v/gen/c/cgen.v

This PR make a minor simplification in cc_type().

cgen: minor simplification in cc_type()

---

vlib/v/ast/types.v

This PR remove unused comments in ast/types.v.

ast: remove unused comments in types.v

---

vlib/v/ast/attr.v
vlib/v/parser/parser.v

This PR adds support for numeric attribute arguments

parser: add number attribute args

---

vlib/v/ast/ast.v
vlib/v/checker/checker.v
vlib/v/checker/tests/globals/unknown_typ.out
vlib/v/checker/tests/globals/unknown_typ.vv
vlib/v/parser/parser.v

Requires merging https://github.com/vlang/ved/pull/115 before.

checker: check __global type

---

vlib/builtin/utf8.v
vlib/strconv/f32_str.v
vlib/strconv/f64_str.v
vlib/strconv/format.v

-Speed optimization for some utf8 functions
-Speed optimization for some strconv functions
This PR is preparatory for the future **string interpolation PR**.

fix and optimization for utf8 functions, strconv optimizations

---

doc/docs.md

Makes the channels buffered so they do not block.

docs: Correct channel example

---

vlib/v/gen/js/js.v

jsgen: basic struct embedding support

---

vlib/io/io.v

This PR makes io.cp chunked with 1KB chunk size

io: make io cp chunked

---

vlib/v/parser/fn.v

parser: don't disallow closures in the JS backend

---

vlib/gg/gg.v

gg:fix draw_line for android

---

vlib/strconv/atof.v

- New parser for the `atof` function without string concatenation and less memory usage.
- Removed the FSM from the parser.

strconv: new atof function, more speed

---

cmd/tools/vtest-cleancode.v
vlib/v/ast/table.v
vlib/v/ast/types.v
vlib/v/checker/checker.v
vlib/v/fmt/tests/fixed_size_array_type_keep.vv
vlib/v/parser/parse_type.v

```v
struct Foo {
bar [size]int
}
```

fmt: keep constant sizes in struct field fixed array types

---

vlib/v/gen/c/sql.v

This PR add support for orm statements with pg

orm: add pg orm statements

---

examples/database/orm.v
vlib/mysql/mysql.v
vlib/v/gen/c/sql.v

This PR adds support for substructs selection in orm with mysql

orm: fix mysql substructs

---

examples/database/orm.v
vlib/v/checker/checker.v
vlib/v/gen/c/cgen.v
vlib/v/gen/c/sql.v

This PR adds array support to orm

orm: support arrays

---

doc/docs.md

Fixes https://github.com/vlang/v/issues/9392

docs: fix misleading 'maps' section

---

vlib/v/tests/generics_test.v

This PR enable 'test_generic_fn_with_variadics()' test in generics_test.v.

tests: enable 'test_generic_fn_with_variadics()' test

---

vlib/v/gen/c/cheaders.v

This should fix https://github.com/vlang/v/issues/9553 - I've closed it in advance. I also removed `make_secret` because we currently don't use it. We will use it in the future, however.

cheaders: update wyhash

---

vlib/builtin/map_test.v

`map_test.v` was missing tests for a lot of key types, so here they are :slightly_smiling_face:

map_test: test more key types

---

vlib/v/gen/c/fn.v
vlib/v/tests/interface_fields_test.v

cgen: fix calling function-pointer fields on interfaces

---

vlib/builtin/string.v

'del' is a poor name for something that is added rather than deleted, & 'sep' for separator is more conventional and understandable than 'del' for delimiter.

join: Changed docs + arg name for join()

---

vlib/v/fmt/fmt.v
vlib/v/fmt/tests/module_alias_keep.vv

fmt: keep module alias in interfaces

---

vlib/v/parser/parse_type.v
vlib/v/parser/tests/struct_field_unknown_module_a.out
vlib/v/parser/tests/struct_field_unknown_module_a.vv
vlib/v/parser/tests/struct_field_unknown_module_b.out
vlib/v/parser/tests/struct_field_unknown_module_b.vv
vlib/v/parser/tests/struct_field_unknown_module_c.out
vlib/v/parser/tests/struct_field_unknown_module_c.vv

parser: better error message for use of `mod.submod.Type`

---

vlib/v/ast/types.v
vlib/v/checker/tests/fn_args.out
vlib/v/checker/tests/fn_args.vv
vlib/v/checker/tests/struct_field_type_err.out
vlib/v/checker/tests/struct_field_type_err.vv

ast: fix bug where fn_signature return wrong str for variadic arg

---

vlib/vweb/route_test.v
vlib/vweb/vweb.v

Fixes array index out of bounds panic

vweb: Fix route matching on `/`

---

examples/bfs.v

Add **BFS** as example to **examples**.

examples: add bfs as example

---

doc/docs.md

I also suggest globally replacing "is casted" with "is cast" throughout since this is better English.

manual: Small English improvement + suggestion

---

.github/workflows/ci.yml
.github/workflows/ci_cross.yml
.github/workflows/ci_sanitized.yml

This PR add 'sudo apt upgrade' in ci.yml/ci_sanitized.yml/ci_cross.yml.

ci: add 'sudo apt update' in ci.yml

---

vlib/v/checker/checker.v
vlib/v/tests/interface_variadic_test.v

checker: fix calling functions with variadic interface parameters

---

vlib/v/ast/table.v

This PR makes minor cleanup of resolve_generic_to_concrete().

table: minor cleanup of resolve_generic_to_concrete()

---

examples/gg/worker_thread.v

This will add a simple example of how to get a value from a worker thread without blocking the rendering thread.
Credits to @spytheman for some crucial fixes.

examples: add gg drawing result from worker thread

---

vlib/v/checker/checker.v

This PR makes a minor cleanup in check_files().

checker: minor cleanup in check_files()

---

vlib/strconv/f32_str.v
vlib/strconv/f64_str.v

- Speed up on float to string conversion
- code cleaning
This code is propaedeutic for V string interpolation

strconv: float functions cleaning and speed optimization

---

vlib/v/ast/table.v
vlib/v/checker/checker.v

This PR cleanup generics struct.
- Add handling of inconsistencies between structural generic parameters and generics function generic parameters.

checker: cleanup generics struct

---

vlib/v/gen/c/cgen.v
vlib/v/tests/interface_test.v
vlib/v/tests/sumtype_calls_test.v

cgen: fix `cannot take rvalue` error of interface

---

vlib/vweb/README.md

Some reformatting, updated example for how to run, and some text updates.

docs: vweb README

---

vlib/encoding/utf8/utf8_util.v

ut8: format utf8_util.v

---

vlib/v/ast/types.v
vlib/v/fmt/tests/generics_keep.vv
vlib/v/parser/parse_type.v

fmt: keep generics for selective import as fn param

---

Makefile

Honor local=1 in the tccbin target

---

cmd/v/help/build.txt
cmd/v/help/default.txt
vlib/v/gen/native/amd64.v
vlib/v/gen/native/arm64.v
vlib/v/gen/native/elf.v
vlib/v/gen/native/gen.v

native: initial support linux-arm64 (hello world only for now)

---

.github/workflows/vab_ci.yml

This PR will add a minimal subset of the build matrix from `vab`'s CI.
I'm adding this to test if V's C output can be compiled successfully with the 4 Android SDK compilers.
I've chosen to test `vab`'s minimum and maximum supported Android API and Java version levels - since these can affect the Android SDK build/compile process.
I'm also leaving out AAB packaging since this requires downloads of external tools and would have to be cached - which is overkill for the scope of these tests.
(`vab`'s own CI has a more in-depth build matrix covering more scenarios)

ci: add vab job compiling v graphical examples

---

vlib/builtin/string.v
vlib/readline/readline_linux.c.v
vlib/v/gen/c/cgen.v

Remove some more compiler magic, for ustring here.

builtin,gen: use operator overloading on ustring

---

vlib/v/checker/checker.v
vlib/v/gen/c/cgen.v
vlib/v/tests/match_with_complex_sumtype_exprs_test.v

This PR fix match with complex sumtype exprs (fix #10180).
- Fix match with complex sumtype exprs.
- Add test.
```vlang
struct Node {
value f64
left  Tree
right Tree
}
type Tree = Empty | Node
// return size(number of nodes) of BST
fn size(tree Tree) int {
return match tree {
// TODO: remove int() once match gets smarter
Empty { int(0) }
Node { 1 + size(tree.left) + size(tree.right) }
}
}
// insert a value to BST
fn insert(tree Tree, x f64) Tree {
return match tree {
Empty {
Node{x, tree, tree}
}
Node {
if x == tree.value {
tree
} else if x < tree.value {
Node{
...tree
left: insert(tree.left, x)
}
} else {
Node{
...tree
right: insert(tree.right, x)
}
}
}
}
}
// whether able to find a value in BST
fn search(tree Tree, x f64) bool {
return match tree {
Empty {
false
}
Node { …
```

checker, cgen: fix match with complex sumtype exprs (fix #10180)

---

vlib/v/parser/parser.v
vlib/v/tests/imported_symbols_test.v
vlib/v/tests/modules/geometry/geometry.v

parser: set is_public of TypeSymbol for fn type decl

---

cmd/tools/vdoc/resources/doc.js

Because we have in vlib such modules as pg, os, ui, io, gg, dl and they are pretty important we need to decrease letter threshold for search to 2

doc: decrease letter count for search to 2

---

vlib/sqlite/sqlite.v

Added the ability to retrieve result code from functions that return an option

sqlite: add error struct for optional result

---

doc/docs.md

variable `c` should be of type `f64`, not `chan f64`.

docs: fix channel select example
